### ISSUE TITLE
ARMA trend is in fit

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1049]
Shoudn't the trend also be specified in `__init__`?

I didn't check the implementation, but if constant is used as part of estimation then using it in fit might still be justified. ?

issue #149 what disallows users to specify a constant in exog instead of a trend='c' ?

for information:
what happens if we have a set of dummy variable instead of a constant? (haven't tried)
use case mean is piecewise constant

**Comment by josef-pkt** [comment]
see also #2531 issue closed as duplicate of this

**Comment by bashtage** [comment]
Closing as unfixable.  The solution is to guild users to SARIMAX or possible a light-weight shim'd version for AR(I)MA, which I believe is @ChadFulton 's idea.
