### ISSUE TITLE
diagnostic linear_rainbow is missing sort order_by option

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1060]
see thread at https://groups.google.com/d/msg/pystatsmodels/ylx--SGnDNQ/29COOwXeH6EJ

http://www.inside-r.org/packages/cran/lmtest/docs/raintest   (edit: previous link was broken)

Also, I assume this kind of test can be extended to other models.
(maybe as Likelihood ratio test)

**Comment by bashtage** [comment]
Fixed.
