### ISSUE TITLE
Remove version compatibility code

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#1063]
We can remove some old functions that are no longer needed, etc.. A lot of the time there are source comments so they're easy to find with grep. For example, #127.

Will need to do similar for pandas workarounds 0.7.x -> 0.8.x, mainly in tsa.

**Comment by jbrockmendel** [comment]
#5036 is about all that’s left of this, unless you count code copy/pasted from scipy.

**Comment by bashtage** [comment]
Appears to be closed in master.
