### ISSUE TITLE
MingW setuptools bug (for gcc >= 4.6)

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1085]
For now just a piece of information

python distutils uses automatically `--mno-cygwin` which is an invalid option for MingW since 4.6 which means building with distutils will not work anymore
http://bugs.python.org/issue12641

numpy has already patched this a while ago
https://github.com/numpy/numpy/blob/master/numpy/distutils/mingw32ccompiler.py#L117

However, with the last changes in setup.py, we are not using numpy's patched version of distutils any more.
Maybe we should change back to it.

(python-xy currently uses MingW < 4.6)

**Comment by bashtage** [comment]
@josef-pkt This seems quite old and likely fixed.

**Comment by josef-pkt** [comment]
I don't have problems with mingw in the default setup of Winpython, at least for compiling for python 3.4, and 2.7.

closing as outdated

Thanks @bashtage
