### ISSUE TITLE
ENH: zero-inflated poisson

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#1086]
Parking this here in case someone else gets an itch. I need the estimation only right now. Shouldn't be too much more work to add analytic derivatives, Vuong test, results class, summary etc.

https://gist.github.com/jseabold/6617976

**Comment by jbrockmendel** [comment]
@josef-pkt this has been implemented right?  Closeable?

**Comment by jseabold** [comment]
Closed by #3908.
