### ISSUE TITLE
development docs

### ISSUE THREAD

**Issue by argriffing** [statsmodels/statsmodels#1144]
I'm spoiled by the `runtests.py` script in scipy, where my workflow is to update my master branch, then make a new branch for my changes, then make the changes, then add some unit tests, then check that all tests pass by running the runtests script, then push my branch, then submit a PR.  After reading http://statsmodels.sourceforge.net/stable/dev/git_notes.html I assume that the statsmodels development workflow is similar, except that I'm not sure what to do without the `runtests.py` script.

**Comment by bashtage** [comment]
This is documented now.
