### ISSUE TITLE
ENH: Poisson for continuous regression

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#1151]
[**Edit**: I changed the name of the issue to indicate that this is an open ended issue for exploring what results we need the PMLE applications of Poisson.]

For the Poisson model to be consistent requires only that the first moment be correctly specified. We need the second moment to be correctly specified (the equidispersion assumption) for inference. Neither of these assumptions relies on y being an integer. Standard pseudo-maximum likelihood theory applies here (Gourieroux, Monfort, and Trognon 1984). Using this result, Poisson models are sometimes used in place of log-linear models. (See Santos Silva and Tenreyro 2006 and Westerlund and Wilhelmsson 2006 for applications to gravity models.)

So we need to change pdf/cdf not to rely on `scipy.stats` to avoid the integer truncation. I think.

**Comment by josef-pkt** [comment]
I'm closing #2712 contains more related information and links to issues
This works without problems, we also have the sandwich robust cov_types for it.

Documentation, examples, FAQ are still spread out or missing.

I'm not sure we have the references collected somewhere, there are many articles on Poisson for continuous non-negative response and Logit for fractional response.
