### ISSUE TITLE
docstring in sandbox functions are incomplete or messy

### ISSUE THREAD

**Issue by wesm** [statsmodels/statsmodels#12]
Original Launchpad bug 522249: https://bugs.launchpad.net/statsmodels/+bug/522249
Reported by: josef-pktd (joep).

several of the functions in the sandbox that are added to the sphinx docs have incomplete docstrings or docstrings with developer notes.

At least the docstrings exposed in sphinx should be cleaned up and missing ones added.

**Comment by jseabold** [comment]
This needs more actionable info. 3.5 year old "the sandbox is a mess" issue is not useful.
