### ISSUE TITLE
Use numpy.dual?

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#1218]
I just discovered this. Perhaps we should be importing from here? It's not clear to me what's at stake. E.g., what's better about `scipy.linalg.inv` than `numpy.linalg.inv`?

https://github.com/numpy/numpy/blob/master/numpy/dual.py

**Comment by stefanv** [comment]
We will likely deprecate or remove `numpy.dual` soon; it seemed like a good idea at the time, but there are issues around incompatible APIs, discoverability, etc.
