### ISSUE TITLE
add pca class

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1238]
https://github.com/statsmodels/statsmodels/commits/add-pca

the least recently updated branch in the main repo.

one commit with draft for pca class 312ca86916740ac83cbac277941db71376348778

(candidate for branches to get rid off)

**Comment by jbrockmendel** [comment]
There now exists a PCA class.  Is this issue closeable?

**Comment by josef-pkt** [comment]
yes closing, PCA class by bashtage has been merged years ago

@jbrockmendel  Thanks for finding this
