### ISSUE TITLE
Feature request : Time series decomposition

### ISSUE THREAD

**Issue by dfrusdn** [statsmodels/statsmodels#1247]
Can we have a method for decomposing a time series ? Like the STL or decompose function in R?
http://www.r-bloggers.com/seasonal-trend-decomposition-in-r/

**Comment by MaxPowerWasTaken** [comment]
this should be closed right, given that sm.tsa.seasonal_decompose() now exists?

**Comment by josef-pkt** [comment]
@MaxPowerWasTaken  Thanks for pointing it out

a version of seasonal_decompose was added in #1484
Note: There is a full model using seasonal/trend decomposition in the new statespace models by Chad
