### ISSUE TITLE
Basic ARCH(q) model for autoregressive Time series

### ISSUE THREAD

**Issue by dfrusdn** [statsmodels/statsmodels#1270]
Before implementing GARCH we might as well implement this since it is in the same family of models and is the most basic

ARCH(q) ( AutoRegressive Conditional Heteroskedasticity) is a basic model used to measure variance.

http://www.jstor.org/discover/10.2307/1912773?uid=2&uid=4&sid=21103174467947

https://en.wikipedia.org/wiki/Autoregressive_conditional_heteroskedasticity

Input will be q, the ARCH term

To fit the model the Lagrange multiplier test can be used on the residuals

A White test is also needed for checking for heteroscedasticity

https://en.wikipedia.org/wiki/White_test

**Comment by bashtage** [comment]
Use the `arch` package.
