### ISSUE TITLE
Cleanup: Remove branches from main repo

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#1280]
We shouldn't have any scratch work branches in master like desc-stats, add-pca, add-tokyo, dcm_rebased, gee_rebased, misc_io, and nonlinearls. These should be moved to someone's fork if they're going to get worked on or deleted.

**Comment by bashtage** [comment]
@JOSEF-PKT should these be removed. They clutter up lists of branches in some gui environments.

**Comment by josef-pkt** [comment]
I will have to save/copy some of them in my clone of statsmodels.
For example my branch of nonlinearls is older than the one in the main repo.
nonlinearls and dcm were GSOC projects and there are several branches and PRs with code at different stages. but I have no overview right now.

I deleted 3 branches, I have to look at the other ones more closely
tokyo branch was a linalg rewrite that is obsolete with BLAS/LAPACK access via scipy
The other two were recent branches that got pushed to the main repo by mistake, I guess.

@ChadFulton there is a `ss-cykfs`.   Is it obsolete and can it be deleted?
AFAIR, this was merged in some form into master.

**Comment by ChadFulton** [comment]
Yes, sorry, that branch is obsolete (merged in some way) and can be removed!

**Comment by bashtage** [comment]
Is suppose this can be closes since all unnecessary branches have been removed

**Comment by bashtage** [comment]
Need to remove the kalman filter branch

**Comment by tqa236** [comment]
The kalman filter branch is removed now. Is it possible to close this issue?

**Comment by bashtage** [comment]
Thanks.
