### ISSUE TITLE
add matplotlib and other optional dependencies to a TravisCI version

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1298]
we missed some errors in a merge relying on TravisCI which however skips the plot tests

https://launchpadlibrarian.net/161734555/buildlog_ubuntu-raring-amd64.statsmodels_0.6.0~ppa18~revno-1520~ubuntu13.04.1_UPLOADING.txt.gz

**Comment by jbrockmendel** [comment]
@josef-pkt wasn’t there another issue just like this an hour ago?

**Comment by josef-pkt** [comment]
yes, outdated
