### ISSUE TITLE
target pandas objects in lagmat/lagmat2ds

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#1306]
Handle pandas objects in these functions for easier construction of lagged variables.

**Comment by bfcondon** [comment]
This looks like it is addressed by #2240 and should be closed when it is merged.

**Comment by bashtage** [comment]
@josef-pkt I think this is closeable.

**Comment by josef-pkt** [comment]
#2310 added pandas support for lagmat but not for lagmat2ds, but that is essentially a column rearranged version of lagmat.

(aside: 
lagmat has blocks by lags which is useful for lag search, 
lagmat2ds has blocks by variable which is useful for variable selection and granger causality tests
)
