### ISSUE TITLE
ARCH(q) model (with working code)

### ISSUE THREAD

**Issue by ccsv** [statsmodels/statsmodels#1321]
I will attempt to work on ARCH and GARCH if someone can help me with understanding of what is available in Statsmodels (ie: some estimators MLE for which models, methods automatic estimation of ARMA parameters...etc) and where to find them.

I also have no idea how to perform unit test.

But here is what I have so far on ARCH(q)

```
import numpy as np
import statsmodels.api as sm
np.set_printoptions(suppress=True)

def running_view(y, window, axis=-1):
    '''
    return a running view of length 'window' over 'axis'
    the returned array has an extra last dimension, which spans the window

    y: array
        Time series data
    window: int
        window of running view
    axis: int
    '''
    shape = list(y.shape)
    shape[axis] -= (window-1)
    assert(shape[axis] > 0)
    return np.lib.index_tricks.as_strided(
        y,
        shape + [window],
        y.strides + (y.strides[axis],))


def arch(y, q, alpha='OLS'):
    '''
    Autoregressive conditional heteroskedasticity (ARCH)

    Parameters
    ----------
    y: array
        Time series data, usually the residuals
    q: int
        Order of the ARCH model
    alpha: float, str (optional)
        parameters for the equation.
        'OLS' will solve parameters for alpha using ordinary least squares
    '''
    #Initialize data
    y = np.asarray(y)
    mod = np.delete(y, np.s_[:q])

    ymatrix = running_view(y, q+1)
    #square error terms and add omega
    ymatrix = ymatrix ** 2
    ymatrix = sm.add_constant(ymatrix)
    #Solve for parameters alpha
    if alpha == 'OLS':
        alpha = sm.OLS(mod, ymatrix)
        alpha = alpha.fit()
        alpha = alpha.params
        #print alpha
    #Execute ARCH(q) equation
    ymatrix = np.dot(ymatrix, alpha)
    return ymatrix
```

So basically what it does so far is you put y and it solves for the variance at time t.
What it needs now is:

* a method to solve for a recommended order (it said by fitting autoregressive model so I assume there is a function somewhere my guess is `AR.select_order` )
* a way to back-propagate the values
* a summary and a way to forecast n steps ahead.

I am not familiar enough with classes to create something like the  `class ARMA`. Someone should also check if it works correctly.

Should I do a pull request? and if so where?

**Comment by josef-pkt** [comment]
ARCH/GARCH is a huge area. Any implementation will have to be in several model classes integrated with current tsa.

Kevin has his own package now in python
