### ISSUE TITLE
string versus bytes, py 3 conversion/compatibility

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1324]
There has been a long discussion on the numpy mailing list on unicode and string support in numpy thread title: "using loadtxt to load a text file in to a numpy array"

We need some test cases with or without pandas and patsy.

For most of the code in statsmodels we don't care what we work with. 

pandas and patsy use text categorical variables to construct variable names, or similar.

np.recfromtext currently only works with returning bytes not strings in python 3, used in datasets, examples and unittest.

PR for facetplot has some unicode test cases that are currently broken on py3.
IIRC, patsy has problems with non-ASCII strings.

My guess is that we should switch to unicode (strings in py3) instead of bytes that we got as consequence of recfromtext. I don't think we need to change and core code in statsmodels, but we need working examples and make sure the interaction patsy, pandas, statsmodels works with non-ASCII. Maybe it does already. (for most parts ? I didn't hear any complaints.)

**Comment by bashtage** [comment]
Fixed by time. Python 3 only now.
