### ISSUE TITLE
predict accepts a DataFrame but returns a numpy array (rather than Series)

### ISSUE THREAD

**Issue by cancan101** [statsmodels/statsmodels#1352]
This loses any `Index` information on the input `DataFrame`.

This would not be an issue except for the fact that the shape of the input DataFrame does not match the returned numpy array which makes combining the two tricky.

This is because some of the data is dropped when performing the transform:
```
exog = dmatrix(self.model.data.orig_exog.design_info.builder, exog)
```

This actually seems to be a rather simple fix.

``dmatrix`` can be told to return a "dataframe" and then that DataFrame can be dot'ed with the params.

**Comment by josef-pkt** [comment]
I opened a SUMMary issue #2150 and started to look into prediction methods. 
I'd like a general solution instead of patching code in various places.

**Comment by josef-pkt** [comment]
see also #2145 as a more general duplicate

**Comment by jseabold** [comment]
Putting this on my radar for 0.7. That's annoying.

**Comment by josef-pkt** [comment]
I started part of pandas handling in my branch for prediction intervals.
I want to remove all data/exog handling from predict and outsource it, which is another issue

We need design decision and helper functions, Kerby has also PRs for prediction.

**Comment by jseabold** [comment]
Ok, we have general wrapping code that I wrote for MixedLM, so it should be simple to just fix this issue without getting too far afield.

**Comment by saroele** [comment]
+1

**Comment by malcolm415** [comment]
+
