### ISSUE TITLE
Feature: Associative Rule Learning

### ISSUE THREAD

**Issue by ccsv** [statsmodels/statsmodels#1357]
Have not seen Associative Rule Learnining Algorithms in any python libraries so far. Is this something for statsmodel? or is it more for scikit learn? 

Basically what they do is you input a list of transaction made up of a list of items lets say A,B, C, D. The output would be support and confidence for patterns such as A and B occurring together. This is used for market basket analysis and finding frequent patterns.

Some of the common algorithms include:
Apriori 
Eclat
FP-Growth
Prefix Span

**Comment by josef-pkt** [comment]
closing, doesn't sound like it's something we will get anytime soon, if ever
