### ISSUE TITLE
unicode in formulas

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#1390]
Need to add tests for unicode (non-ascii) formulas coming in and make sure we're passing these to patsy correctly. See #1388 for notes and for potential test cases. Might need to add an encoding keyword to models, though a default 'utf-8' should be fine in most cases. (Maybe not datasets written by stata, which will always be 'latin-1'.

**Comment by bashtage** [comment]
Fixed by time since Python 3 only.
