### ISSUE TITLE
Use expit

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#1442]
Maybe get micro-speedups from using expit (added in scipy 0.10) in places where we have

```
1/(1+np.exp(np.asarray(-x)))
```

In discrete. I see about a 1.15x speed-up in the operation. Might gain more after

https://github.com/scipy/scipy/pull/3426

**Comment by souravsingh** [comment]
@jseabold Is the issue still open? I would like to take a stab at it.

**Comment by josef-pkt** [comment]
closing,
expit breaks with complex step derivatives (complex numbers not supported)
see #8577
