### ISSUE TITLE
DOC example robust_models_1  missing link and R error

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1461]
link on landing page is wrong because of typo
typo: should be models with s at the end
https://github.com/statsmodels/statsmodels/blob/master/docs/source/examples/landing.json#L100

robust_models_1 was not edited in https://github.com/statsmodels/statsmodels/pull/1445/files
was this an oversight or nothing to do?

also 
http://statsmodels.sourceforge.net/devel/examples/notebooks/generated/robust_models_1.html
contains rmagic which is not calculated/rendered in the notebook

```


%load_ext rmagic

%R library(robustbase)
%Rpush yy xx
%R mod <- lmrob(yy ~ xx);
%R params <- mod$coefficients;
%Rpull params

Error in X11(paste("png::", filename, sep = ""), g$width, g$height, pointsize,  :
  unable to start device PNG
In addition: Warning message:
In png("/tmp/tmpiRnqij/Rplots%03d.png", ) :
  unable to open connection to X11 display ''
```

**Comment by bashtage** [comment]
@josef-pkt This has been fixed. Closeable.

**Comment by josef-pkt** [comment]
ancient issue, closing

@bashtage  Thanks for finding it
