### ISSUE TITLE
Doc Examples - exceptions in code

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1467]
(we had a discussion once for checking automatically whether notebooks raise an exception. difference to before: one exception doesn't stop the processing anymore)
- http://statsmodels.sourceforge.net/devel/examples/notebooks/generated/ols.html In [22]
  an uninitialized array, but I'm not sure what the division by norm is doing

**Comment by bashtage** [comment]
@josef-pkt This looks close-able.

**Comment by josef-pkt** [comment]
@bashtage  thanks for checking
