### ISSUE TITLE
summary() params table split conf_int

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1492]
If the params table is rendered as html, then it doesn't look nice that confidence interval is a single column.
 
for example
http://nbviewer.ipython.org/github/nipunreddevil/PythonAnalyticsEdge/blob/master/week_2/lecture/baseball.ipynb?create=1

single column conf_int was optimized for string/text printing.
I guess it will also be messed up in Latex.

**Comment by kiyoto** [comment]
How would you render it in HTML? Also, based on my cursory look into `iolib/*.py`, it's not that easy to switch a cell's representation based on the output format?

**Comment by josef-pkt** [comment]
(I'm trying to catch up with some issues)

This doesn't require changing the rendering itself because that is handled by `SimpleTable`.
The task here is to split the columns into two columns, keeping the numeric formatting, but the header for confidence interval needs to change. The header needs to be split into two corresponding to the two columns. AFAIR, the header was my reason to use a single column, but at the time html view of summary wasn't very popular yet (and I didn't see how bad it looks).

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/iolib/summary.py#L474
is making the combined string for lower and upper confidence limite which is further down added to the params_table.  There might be other places, that I didn't see right now.

**Comment by kiyoto** [comment]
@josef-pkt I see. If we are splitting the header for confint, what should each header say? Will it look decent in the print/text context?

**Comment by josef-pkt** [comment]
I'm not sure about the header, maybe we try the same as what `summary2` uses, i.e. `[0.025    0.975]`
alpha / 2 and (1 - alpha) / 2
