### ISSUE TITLE
rpy2 stop-gaps?

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#1557]
Should we include things like the `STL` wrapper posted by Andreas, `auto.arima`, etc. wrappers for functions that use rpy2 (if available) as stop-gaps until we have native solutions?

**Comment by jbrockmendel** [comment]
@josef-pkt closable?

**Comment by josef-pkt** [comment]
Yes, I think we can close this.
There was no interest in a long time.

(I'm not using R except for writing unit tests every once in a while.)
