### ISSUE TITLE
ARIMA Cython Optimization

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#1564]
Need to explore when memoryviews aren't needed. Right now, we're mostly using them but can maybe get away with pure numpy C-api in many cases. Acquiring the buffer is 'slow'.

**Comment by jbrockmendel** [comment]
IIRC ARIMA now uses cython code from tsa.kalmanf.  Were there other optimizations you had in mind?

**Comment by bashtage** [comment]
This can be closed. Not worth effort to try lower level access.
