### ISSUE TITLE
TravisCI  add verbose to nosetests

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1633]
TravisCI job run stalled twice in a row in checking PRs

in `PYTHON=2.7 NUMPY= SCIPY= MATPLOTLIB= PANDAS=` version

Should we add verbose to the nosetests to see in which unit test it hangs.

**Comment by bashtage** [comment]
@josef-pkt This is fixed.

**Comment by josef-pkt** [comment]
I added verbose to find which tests are slow or hanging on travis. But it is pretty useful so we keep it.
(The only disadvantage of verbose is that we don't get a quick overview of test noise and warnings.)
