### ISSUE TITLE
linalg check_finite  hang with inf

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1642]
In 0.5.0 we use a rank function that uses scipy.linalg.svdvals which includes check_finite.
For 0.6 we switched to using np.matrix_rank which uses np.linalg.svd without a isfinite check.

nans raise a SVD not converged error
infs in the exog causes svd to hang and not to return without killing the process (Ctrl-C doesn't work) 
based on numpy discussion it happens for some but not all linalg libraries.

Win 32 MingW official binaries:  hangs and never comes back
Win 64 MingW64 OpenBlas wheels (Matthews): `SVD did not converge` also with infs
Win 64 MKL ? 

```
import numpy as np

import statsmodels.api as sm

nobs, k_vars = 100, 5
x = np.random.randn(nobs, k_vars)

beta = np.ones(k_vars)
y = np.dot(x, beta) + np.random.randn(nobs)

x[:5,-1] = np.nan
x[5:10, -1] = np.inf

mod = sm.OLS(y, x)
res = mod.fit()
print(res.summary())
```

**Comment by jbrockmendel** [comment]
The `mod = sm.OLS(y, x)` call now raises `statsmodels.tools.sm_exceptions.MissingDataError: exog contains inf or nans`
