### ISSUE TITLE
ARMAX with constant X / collinear regressors

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#1644]
It's in the docs that this doesn't work, but we should fail more gracefully.

```
y = np.random.randn(24)
X = np.ones(24)/.25

res = sm.tsa.ARMA(y, (1, 0), exog=X).fit()
res = sm.tsa.ARMA(y, (1, 0), exog=X).fit(trend='nc')
```

This is part of a bigger issue of what to do in the case of collinear regressors. Stata will drop a regressor and print a warning. R (arima) fails non-gracefully.

**Comment by josef-pkt** [comment]
See #2542

**Comment by bashtage** [comment]
ARMA is deprecated and will be removed soon.
