### ISSUE TITLE
BUG: ARIMA exog_names expands in each fit.

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1691]
trying out the example from test_arima. small sample

If I call fit repeatedly, then summary() raises an exception.

It looks like `exog_names` is appended in each call of fit.

```
    y = [-1214.360173, -1848.209905, -2100.918158, -3647.483678, -4711.186773]
    mod = ARIMA(y, (1, 0, 2))

>>> mod.exog_names
['const', 'const', 'const', 'ar.L1.y', 'ma.L1.y', 'ma.L2.y', 'ar.L1.y', 'ma.L1.y', 'ma.L2.y', 'ar.L1.y', 'ma.L1.y', 'ma.L2.y']

>>> res = mod.fit(disp=0, start_params=[np.mean(y), .1, .1, .1])
>>> mod.exog_names
['const', 'const', 'const', 'const', 'ar.L1.y', 'ma.L1.y', 'ma.L2.y', 'ar.L1.y', 'ma.L1.y', 'ma.L2.y', 'ar.L1.y', 'ma.L1.y', 'ma.L2.y', 'ar.L1.y', 'ma.L1.y', 'ma.L2.y']

>>> res = mod.fit(disp=0, start_params=[np.mean(y), .1, .1, .1])
>>> mod.exog_names
['const', 'const', 'const', 'const', 'const', 'ar.L1.y', 'ma.L1.y', 'ma.L2.y', 'ar.L1.y', 'ma.L1.y', 'ma.L2.y', 'ar.L1.y', 'ma.L1.y', 'ma.L2.y', 'ar.L1.y', 'ma.L1.y', 'ma.L2.y', 'ar.L1.y', 'ma.L1.y', 'ma.L2.y']
```

working in a plain Windows shell in py3.3 virtualenv

**Comment by josef-pkt** [comment]
reopening because there is still the problem if users call fit with different trend arguments.

#2526  fixes the case when the model stays the same.

**Comment by josef-pkt** [comment]
postponed to 0.10
trend should go out of fit, it is a data/model keyword and not a fit keyword.
If we change that, then there is nothing to fix here.

**Comment by bashtage** [comment]
Fixed in master.  ARMA is deeply broken since the model doesn't follow the immutable pattern.  Hopefully, @ChadFulton will unify ARMA/ARIMA/SARIMAX with a single implementation.
