### ISSUE TITLE
GLM.fit maxiter=0  incorrect

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1728]
GLM fit still does a lot of initialization calculations that are not necessary if maxiter=0.

I'm using maxiter=0 with start_params=params to get a full results instance.

I think the error is in missing offset and exposure in the initialization
`mu = self.family.fitted(np.dot(wlsexog, start_params))`  see #1486

**Comment by josef-pkt** [comment]
maxiter=0 and method='irls' returns results with params is None

see #2393 for current case, working towards a generic solution

**Comment by josef-pkt** [comment]
might be fixed, but needs checking

**Comment by bashtage** [comment]
Fixed in master, fast path for maxiter==0.
