### ISSUE TITLE
DOC see also links broken

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1810]
http://statsmodels.sourceforge.net/devel/generated/statsmodels.regression.linear_model.RegressionResults.f_test.html

`see also` are not links

**Comment by bashtage** [comment]
@josef-pkt These are all fixed now.  Closeable.

**Comment by josef-pkt** [comment]
closing this but I added a FAQ-D issue as reminder for how to run doctests on a method or function
