### ISSUE TITLE
f_test, t_test, wald_test  unused scale argument

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1811]
t_test has scale=None
f_test and wald_test have scale=1
as arguments, and they are described in docstring.

However they are not used in the method.

and using `scale=1` in call to `cov_params()` would be a mistake if `normalized_cov_params` is used.

**Comment by josef-pkt** [comment]
Maybe we should remove `scale` in wald-tests. There are too many options now to specify and manipulate the covariance of the parameters.
Also, `cov_params` uses scale only when `normalized_cov_params` is used, it doesn't multiply as scale factor the `cov_params_default`.

Choosing the scale would be useful for overdispersed Poisson, but that should go into cov_type, or we need to add scale also as factor to multiply `cov_params_default` in `cov_params`.

Also still open, do we enforce `normalized_cov_params` to be used for the Hessian, or do we drop it. (Open question for kalman filter/SARIMAX PR)

**Comment by bashtage** [comment]
closed by #5614
