### ISSUE TITLE
DOC DiscreteResults: missing attributes in docstring

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1816]
tvalues, pvalues, mle_retvals,  ... of LikelihoodModelResults are missing in the DiscreteResults

copy paste or template ?

**Comment by bashtage** [comment]
Seem to be present in master:

https://www.statsmodels.org/stable/generated/statsmodels.discrete.discrete_model.DiscreteResults.html?highlight=discreteresults#statsmodels.discrete.discrete_model.DiscreteResults
