### ISSUE TITLE
Show warnings if glm.fit doesn't converge.

### ISSUE THREAD

**Issue by colinfang** [statsmodels/statsmodels#1844]
Currently in a glm fit I cannot find a way to check if a fit is convergent or not.

http://stackoverflow.com/questions/24939357/how-can-i-check-if-a-glm-lm-of-statsmodels-is-converged-or-not?

Having read the source code:

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/generalized_linear_model.py

It doesn't seem to pass `converged` to an outer scope. Can we have it in the result as well?

**Comment by josef-pkt** [comment]
check for 0.7 if this is still open.

**Comment by josef-pkt** [comment]
`GLM._fit_irls` attaches a `converged` attribute, but doesn't define `mle_retvals` (see #1722 )

`glm_results.converged = converged`

closing
