### ISSUE TITLE
ARMAResult.predict insconsistency in 'end' paramter sm-0.5.0-10

### ISSUE THREAD

**Issue by lJoublanc** [statsmodels/statsmodels#1857]
There is a really annoying inconsistency in the way ARMAResults.predict handles the `end` parameter in statsmodels 0.5.0-10 (from enthought distro).

If you pass pandas timestamps as the start and end paramters,

```
d  = pd.to_datetime("2014-07-15 08:32")
armaReg.predict(start=d,end=d + pd.to_timedelta(30,unit='m'),dynamic=True).plot(color="r")
```

 you get an error:

```
C:\Users\xxx\local\Enthought\Canopy\User\lib\site-packages\statsmodels\tsa\base\tsa_model.pyc in _get_predict_end(self, end)
    201 
    202         elif freq is None: # should have a date with freq = None
--> 203             raise ValueError("When freq is None, you must give an integer "
    204                              "index for end.")
    205 

ValueError: When freq is None, you must give an integer index for end.
```

If instead you convert the `end` parameter to a string by calling `__str__()`, which is then parsed by statsmodels, it works fine.

**Comment by josef-pkt** [comment]
@jseabold  This still has a 0.6 milestone.
Is it still relevant? Do we push it to the 0.8 milestone?

**Comment by bashtage** [comment]
Fixed in master.
