### ISSUE TITLE
TST: safeguard against multiprocessing problems, limit number of cores

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#1892]
Something is wrong in my virtualenv, and joblib/multiprocessing creates new processes.

During a test run my computer was essentially frozen, and didn't respond for some time.
My guess is that there is some multiprocessing problem that uses up all cores and doesn't leave much for the system. (I couldn't access task manager to check this.)

I think we should limit the number of cores that can be used in the multiprocessing unit tests to avoid any problems, if there is a bug or incorrect installation somewhere.

**Comment by bashtage** [comment]
I don't think this is a problem anymore, so closing.
