### ISSUE TITLE
More numerical issues in genmod families

### ISSUE THREAD

**Issue by kshedden** [statsmodels/statsmodels#2037]
#2028 doesn't fix one of the issues I am having with GLM: if any endog == 0 for negative binomial regression, the residual deviances are NaN.  The changes as recently merged via #2028 effectively have a term `notzero * log(endog/mu)`, which is still NaN even when endog is zero.

**Comment by josef-pkt** [comment]
family NegativeBinomial doesn't have 0log0 protection. But, AFAICS this only appears in resid_dev.

I guess this would mean that it is broken for all data with endog=0. Do we have unit tests?
