### ISSUE TITLE
ValueError on tsa with constant column

### ISSUE THREAD

**Issue by DavideCanton** [statsmodels/statsmodels#2043]
Hi, the following code:

``` python
__author__ = 'davide'

import datetime
import numpy as np

import pandas as pd
from statsmodels.tsa.vector_ar.var_model import VAR


def compute_coeffs(series, p, index=None):
    data = pd.DataFrame(series)

    if index is None:
        d = datetime.datetime.now()
        delta = datetime.timedelta(days=1)
        index = []
        for i in range(data.shape[0]):
            index.append(d)
            d += delta

    data.index = pd.DatetimeIndex(index)

    model = VAR(data)
    res = model.fit(p)
    return res.intercept, res.coefs


if __name__ == "__main__":
    series = np.array([[2., 2.], [1, 2.], [1, 2.], [1, 2.], [1., 2.]])
    coeffs = compute_coeffs(series, 1)

    print(coeffs)
```

gives me the following error:

ValueError: total size of new array must be unchanged

This is because the add_constant function in tools.py skips the addition on a column when there is already a constant column in the data (from the documentation of the function). The problem is that I can't estimate the coefficients of the model where there is a constant column such that. I commented out rows 290-292 in tools.py as a workaround, but I would know if this is a feature or it is a bug. (At least change the error message or catch it and raise a more appropriated exception).

Bye

**Comment by saravanansaminathan** [comment]
In your dataset,if any column value is constant in all entries(rows) or if the variance of the data is zero then it shows this error. Just remove the column with zero variance and try it again
