### ISSUE TITLE
Categorical GEE missing from api

### ISSUE THREAD

**Issue by kshedden** [statsmodels/statsmodels#2051]
NominalGEE, OrdinalGEE, and the Multinomial family class are missing from the api.

I can prepare a PR if we want to add them.

Perhaps Multinomial should be renamed "GEE_Multinomial", since it is not a general-purpose implementation.

**Comment by josef-pkt** [comment]
Has this  been all fixed in 0.6.1?

**Comment by kshedden** [comment]
Yes, I think so.  I just updated some of my notebooks to use the new
classes (everything runs fine):

http://nbviewer.ipython.org/urls/umich.box.com/shared/static/y1fw0iameuixrq9zt02d.ipynb?create=1
http://nbviewer.ipython.org/urls/umich.box.com/shared/static/wwwlg3z8as0layod22lx.ipynb

**Comment by josef-pkt** [comment]
Thanks, closing
