### ISSUE TITLE
ARIMA precision problem (LinAlgError: SVD did not converge)

### ISSUE THREAD

**Issue by mapsa** [statsmodels/statsmodels#2064]
Hi,

I've tried to run ARIMA(2,1,1) with the following data https://dl.dropboxusercontent.com/u/290208/matlab.csv but the model gives me a LinAlgError. I've tried the same in matlab I have no problem.
Thanks

**Comment by josef-pkt** [comment]
@jseabold   is this a bug or a corner case, or insufficient information.

**Comment by josef-pkt** [comment]
fix or close for 0.7

**Comment by jseabold** [comment]
I can't replicate this. Please re-open, if the problem still persists.

**Comment by josef-pkt** [comment]
then it doesn't need a bug label

**Comment by eromoe** [comment]
Below data come to this error.
```
datetime_create
2018-04-11   -0.149532
2018-04-12    0.000000
2018-04-13    0.126041
2018-04-14    0.056695
2018-04-15    0.389717
2018-04-16    0.441833
2018-04-17    0.450201
2018-04-18    0.216671
2018-04-19    0.456758
2018-04-20    0.473288
2018-04-21    0.249563
2018-04-22   -0.166573
2018-04-23   -0.031091
2018-04-24    0.060625
2018-04-25    0.098846
2018-04-26   -0.195745
2018-04-27   -0.447312
2018-04-28   -0.289729
2018-04-29   -0.313000
2018-04-30    0.182322
2018-05-01    0.470004
2018-05-02    0.068208
2018-05-03    0.330664
```

If I  change `2018-04-12    0.000000`  to other value ,  error gone.

**Comment by josef-pkt** [comment]
@eromoe  Can you make a full example that I can just run to check this?
One issue to check is whether this is in the start_params computation or in the main ARMA estimation.
My guess would be that there is still a problem with the Hannan-Risannen start_params computation.

i.e. you could try providing start_params explicitly, or set `start_ar_lags=4` or to a similar number > ar order.

**Comment by lemonsong** [comment]
I also met this problem. It works when I set p,d,q as (2,1,1), but not work when I set it as (2,1,2). I'm not sure whether it's a problem in the model itself or the source code. Posted the data and error here:
Data:
month
2016-01-01    17.143812
2016-02-01    17.204329
2016-03-01    17.310005
2016-04-01    17.370695
2016-05-01    17.412922
2016-06-01    17.416952
2016-07-01    17.460220
2016-08-01    17.548044
2016-09-01    17.575716
2016-10-01    17.594671
2016-11-01    17.572424
2016-12-01    17.527962
2017-01-01    17.577181
2017-02-01    17.630161
2017-03-01    17.762602
2017-04-01    17.837435
2017-05-01    17.915522
2017-06-01    17.942329
2017-07-01    17.976513
2017-08-01    18.055845
2017-09-01    18.096987
2017-10-01    18.134558
2017-11-01    18.135798
2017-12-01    18.080412
2018-01-01    18.120905
2018-02-01    18.194347
2018-03-01    18.278738
2018-04-01    18.323374
2018-05-01    18.370972
2018-06-01    18.387842
2018-07-01    18.395041
2018-08-01    18.445559
2018-09-01    18.479631
2018-10-01    18.496305
2018-11-01    18.437532
2018-12-01    18.379660
Log:
LinAlgError                               Traceback (most recent call last)
<ipython-input-638-071596e3db91> in <module>()
      4 
      5 model = ARIMA(data_log, order=(2, 1, 2))
----> 6 results_ARIMA = model.fit(disp=-1)
      7 print(results_ARIMA.summary())
      8 plt.plot(data_transformed)

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/statsmodels/tsa/arima_model.pyc in fit(self, start_params, trend, method, transparams, solver, maxiter, full_output, disp, callback, start_ar_lags, **kwargs)
   1155                                            method, transparams, solver,
   1156                                            maxiter, full_output, disp,
-> 1157                                            callback, start_ar_lags, **kwargs)
   1158         normalized_cov_params = None  # TODO: fix this?
   1159         arima_fit = ARIMAResults(self, mlefit._results.params,

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/statsmodels/tsa/arima_model.pyc in fit(self, start_params, trend, method, transparams, solver, maxiter, full_output, disp, callback, start_ar_lags, **kwargs)
    957                                        maxiter=maxiter,
    958                                        full_output=full_output, disp=disp,
--> 959                                        callback=callback, **kwargs)
    960         params = mlefit.params
    961 

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/statsmodels/base/model.pyc in fit(self, start_params, method, maxiter, full_output, disp, fargs, callback, retall, skip_hessian, **kwargs)
    464                                                        callback=callback,
    465                                                        retall=retall,
--> 466                                                        full_output=full_output)
    467 
    468         # NOTE: this is for fit_regularized and should be generalized

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/statsmodels/base/optimizer.pyc in _fit(self, objective, gradient, start_params, fargs, kwargs, hessian, method, maxiter, full_output, disp, callback, retall)
    189                             disp=disp, maxiter=maxiter, callback=callback,
    190                             retall=retall, full_output=full_output,
--> 191                             hess=hessian)
    192 
    193         optim_settings = {'optimizer': method, 'start_params': start_params,

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/statsmodels/base/optimizer.pyc in _fit_lbfgs(f, score, start_params, fargs, kwargs, disp, maxiter, callback, retall, full_output, hess)
    408                                      callback=callback, args=fargs,
    409                                      bounds=bounds, disp=disp,
--> 410                                      **extra_kwargs)
    411 
    412     if full_output:

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/scipy/optimize/lbfgsb.pyc in fmin_l_bfgs_b(func, x0, fprime, args, approx_grad, bounds, m, factr, pgtol, epsilon, iprint, maxfun, maxiter, disp, callback, maxls)
    197 
    198     res = _minimize_lbfgsb(fun, x0, args=args, jac=jac, bounds=bounds,
--> 199                            **opts)
    200     d = {'grad': res['jac'],
    201          'task': res['message'],

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/scipy/optimize/lbfgsb.pyc in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, **unknown_options)
    333             # until the completion of the current minimization iteration.
    334             # Overwrite f and g:
--> 335             f, g = func_and_grad(x)
    336         elif task_str.startswith(b'NEW_X'):
    337             # new iteration

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/scipy/optimize/lbfgsb.pyc in func_and_grad(x)
    278     if jac is None:
    279         def func_and_grad(x):
--> 280             f = fun(x, *args)
    281             g = _approx_fprime_helper(x, fun, epsilon, args=args, f0=f)
    282             return f, g

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/scipy/optimize/optimize.pyc in function_wrapper(*wrapper_args)
    290     def function_wrapper(*wrapper_args):
    291         ncalls[0] += 1
--> 292         return function(*(wrapper_args + args))
    293 
    294     return ncalls, function_wrapper

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/statsmodels/base/model.pyc in f(params, *args)
    438 
    439         def f(params, *args):
--> 440             return -self.loglike(params, *args) / nobs
    441 
    442         if method == 'newton':

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/statsmodels/tsa/arima_model.pyc in loglike(self, params, set_sigma2)
    778         method = self.method
    779         if method in ['mle', 'css-mle']:
--> 780             return self.loglike_kalman(params, set_sigma2)
    781         elif method == 'css':
    782             return self.loglike_css(params, set_sigma2)

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/statsmodels/tsa/arima_model.pyc in loglike_kalman(self, params, set_sigma2)
    788         Compute exact loglikelihood for ARMA(p,q) model by the Kalman Filter.
    789         """
--> 790         return KalmanFilter.loglike(params, self, set_sigma2)
    791 
    792     def loglike_css(self, params, set_sigma2=True):

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/statsmodels/tsa/kalmanf/kalmanfilter.pyc in loglike(cls, params, arma_model, set_sigma2)
    647             loglike, sigma2 =  kalman_loglike.kalman_loglike_double(y, k,
    648                                     k_ar, k_ma, k_lags, int(nobs), Z_mat,
--> 649                                     R_mat, T_mat)
    650         elif issubdtype(paramsdtype, np.complex128):
    651             loglike, sigma2 =  kalman_loglike.kalman_loglike_complex(y, k,

kalman_loglike.pyx in statsmodels.tsa.kalmanf.kalman_loglike.kalman_loglike_double()

kalman_loglike.pyx in statsmodels.tsa.kalmanf.kalman_loglike.kalman_filter_double()

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/numpy/linalg/linalg.pyc in pinv(a, rcond)
   1870         return wrap(res)
   1871     a = a.conjugate()
-> 1872     u, s, vt = svd(a, full_matrices=False)
   1873 
   1874     # discard small singular values

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/numpy/linalg/linalg.pyc in svd(a, full_matrices, compute_uv)
   1560 
   1561         signature = 'D->DdD' if isComplexType(t) else 'd->ddd'
-> 1562         u, s, vh = gufunc(a, signature=signature, extobj=extobj)
   1563         u = u.astype(result_t, copy=False)
   1564         s = s.astype(_realType(result_t), copy=False)

/Users/ywei/virtualenvs/ishtest/lib/python2.7/site-packages/numpy/linalg/linalg.pyc in _raise_linalgerror_svd_nonconvergence(err, flag)
     96 
     97 def _raise_linalgerror_svd_nonconvergence(err, flag):
---> 98     raise LinAlgError("SVD did not converge")
     99 
    100 def _raise_linalgerror_lstsq(err, flag):

LinAlgError: SVD did not converge

**Comment by ChadFulton** [comment]
@lemonsong I can't replicate your error. Can you confirm that when you run just the following code, you get the `LinAlgError`?

```python
import statsmodels.api as sm
import pandas as pd
dta = [17.143812, 17.204329, 17.310005, 17.370695, 17.412922, 17.416952, 17.460220,
       17.548044, 17.575716, 17.594671, 17.572424, 17.527962, 17.577181, 17.630161,
       17.762602, 17.837435, 17.915522, 17.942329, 17.976513, 18.055845, 18.096987,
       18.134558, 18.135798, 18.080412, 18.120905, 18.194347, 18.278738, 18.323374,
       18.370972, 18.387842, 18.395041, 18.445559, 18.479631, 18.496305, 18.437532,
       18.379660]
endog = pd.Series(dta, index=pd.PeriodIndex(start='2016-01-01', freq='M', periods=len(dta)))

mod = sm.tsa.ARIMA(endog, order=(2, 1, 2))
res = mod.fit()
```

**Comment by ajbarjatya** [comment]
i have same issue with 
data = [466.61000000000007, 724.2699999999999, 1765.3099999999997, 3914.8799999999997, 3714.2100000000005, 3246.7099999999996, 2749.41, 3212.3700000000003, 3747.84, 4762.4800000000005, 16023.11, 24675.989999999998, 25414.95, 18727.92, 18495.97, 13911.449999999999, 15069.61, 18418.79, 19194.44, 16660.550000000003, 13357.32, 11286.310000000001, 10985.72, 10627.24, 7807.9699999999975, 6568.51, 8361.460000000001, 7072.23, 7370.71, 7134.81, 8676.650000000001, 7853.499999999999, 7031.899999999998, 8232.62, 10476.109999999999, 13105.749999999998, 12769.610000000002, 11656.699999999999, 12864.800000000001, 13052.520000000002, 14331.559999999998, 19266.829999999998, 20556.560000000005, 18023.94, 18154.400000000005, 19887.380000000005, 21746.880000000005, 25468.050000000003, 28332.079999999998, 29768.270000000008, 35223.880000000005, 36478.420000000006, 59037.26, 78541.45999999999, 77396.65, 118932.74, 123327.96000000002, 164085.85999999996, 233526.93, 468208.34, 399174.89, 262798.98, 279764.27, 239426.16999999998, 261515.75000000003, 203474.3500000001, 219998.34999999992, 207423.51000000004, 197693.34, 198889.05, 161678.78999999998]
pqd = 3,0,1 respectively

**Comment by ChadFulton** [comment]
@ajbarjatya I can't replicate the LinAlgError with your dataset, but also the scale of your data is quite large, so you might consider a log transformation

**Comment by eromoe** [comment]
Have tested below code
```
import statsmodels.api as sm
import pandas as pd
dta = [17.143812, 17.204329, 17.310005, 17.370695, 17.412922, 17.416952, 17.460220,
       17.548044, 17.575716, 17.594671, 17.572424, 17.527962, 17.577181, 17.630161,
       17.762602, 17.837435, 17.915522, 17.942329, 17.976513, 18.055845, 18.096987,
       18.134558, 18.135798, 18.080412, 18.120905, 18.194347, 18.278738, 18.323374,
       18.370972, 18.387842, 18.395041, 18.445559, 18.479631, 18.496305, 18.437532,
       18.379660]
endog = pd.Series(dta, index=pd.PeriodIndex(start='2016-01-01', freq='M', periods=len(dta)))

mod = sm.tsa.ARIMA(endog, order=(2, 1, 2))
res = mod.fit()
```

can get error 
```
C:\Anaconda3\lib\site-packages\numpy\linalg\linalg.py in pinv(a, rcond)
   1936         return wrap(res)
   1937     a = a.conjugate()
-> 1938     u, s, vt = svd(a, full_matrices=False)
   1939
   1940     # discard small singular values

C:\Anaconda3\lib\site-packages\numpy\linalg\linalg.py in svd(a, full_matrices, compute_uv)
   1610
   1611         signature = 'D->DdD' if isComplexType(t) else 'd->ddd'
-> 1612         u, s, vh = gufunc(a, signature=signature, extobj=extobj)
   1613         u = u.astype(result_t, copy=False)
   1614         s = s.astype(_realType(result_t), copy=False)

C:\Anaconda3\lib\site-packages\numpy\linalg\linalg.py in _raise_linalgerror_svd_nonconvergence(err, flag)
    104
    105 def _raise_linalgerror_svd_nonconvergence(err, flag):
--> 106     raise LinAlgError("SVD did not converge")
    107
    108 def _raise_linalgerror_lstsq(err, flag):

LinAlgError: SVD did not converge
```

**Comment by ajbarjatya** [comment]
@ChadFulton  i did log transform and fore casted the data now how do I get the original value back from the transformed forecast ?

**Comment by ajbarjatya** [comment]
@eromoe I think when the series is non statonary in some of those cases `LinAlgError: SVD did not converge` error comes

**Comment by ChadFulton** [comment]
> @ChadFulton i did log transform and fore casted the data now how do I get the original value back from the transformed forecast ?

If you can't do your analysis in the log domain, you can back-transform. An approximate method is just to `exp` your results which will give you the median of the forecast density, see https://stats.stackexchange.com/a/87757/11974.

A more complete approach is described here: https://robjhyndman.com/hyndsight/backtransforming/

**Comment by TrinhDinhPhuc** [comment]
I have the same issue like this using ARIMA

**Comment by ajbarjatya** [comment]
@TrinhDinhPhuc try using log of data that solved my problem

**Comment by KavishGoyal** [comment]
Changing (p,d,q) values solved my problem.
