### ISSUE TITLE
run unit tests on Mac OSX

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2069]
We don't have continuous integration testing on Apple OSX, but we have a repo created by Matthews that can run the tests on demand and build wheels

https://github.com/MacPython/statsmodels-wheels
see description in readme and mailing list thread

test results
https://travis-ci.org/MacPython/statsmodels-wheels

 (currently all green)

**Comment by jbrockmendel** [comment]
Travis now supports OSX runs; any reason not to do it there?

**Comment by josef-pkt** [comment]
If OSX testing works on travis, then I don't see a reason not to include it.
To limit the number of additional environments, I guess we could add only one OSX version.

**Comment by jbrockmendel** [comment]
> To limit the number of additional environments, I guess we could add only one OSX version.

Sure.  Also could take some of the pressure off by using CircleCI.

FWIW, CI and related are an are that Kevin has a clear comparative advantage in.

**Comment by thequackdaddy** [comment]
Closable.
