### ISSUE TITLE
DOC  incorrect docstrings because of copy-paste

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2095]
http://statsmodels.sourceforge.net/devel/_modules/statsmodels/stats/weightstats.html#CompareMeans.ztest_ind

refers to t-test, but does z-test, and doesn't return `df` because it's not used in ztest

found because of (OT on stats.stackexchange)
http://stats.stackexchange.com/questions/124096/two-samples-z-test-in-python/124171#124171

**Comment by kiyoto** [comment]
This Issues can be closed, @josef-pkt

**Comment by josef-pkt** [comment]
@kiyoto Thanks for pointing it out

closing, fixed in #2518
