### ISSUE TITLE
Review Example Notebook Output

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#2101]
Some are reporting exceptions during doc building.

**Comment by cfblaeb** [comment]
I'm not sure if this is related but the example page has failed cells: http://statsmodels.sourceforge.net/devel/examples/notebooks/generated/tsa_arma_0.html

**Comment by bashtage** [comment]
@josef-pkt I think this can be closed.

**Comment by josef-pkt** [comment]
@bashtage  thanks for triage, Can you add a PR number that fixed the issue or made it obsolete if you know it.

latest problem where fixed by #3037  some other were fixed by Tom during doc build updating
