### ISSUE TITLE
freq_to_period doens't understand "D"

### ISSUE THREAD

**Issue by ThomasLecocq** [statsmodels/statsmodels#2109]
I'm trying to compute some nice seasonal_decompose of a 'D' freq'd series, but this freq isn't recognized by https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/tsatools.py#L625... Is there a good reason for it ?

**edit**  doesn't understand 'H' neither (see comment and link to stackoverflow below)

Best !

Thomas

**Comment by josef-pkt** [comment]
@jseabold @ThomasLecocq  Is this easy to fix for 0.7? Looks like just adding two lines to me.

related question: What happens if we have daily data but a weekly seasonality instead of annual?

**Comment by jseabold** [comment]
Yes, looks easy enough. I'll look at it before the release. (Let's set a date, so I know when I should stop procrastinating late night plowing through issues)

**Comment by josef-pkt** [comment]
@jseabold If you want to finish some PR's and get some more in, then you should do them ASAP so we avoid last minute refactoring problems.
I thought of a soft deadline at the end of next week, plus a few days buffer and release preparation, expecting and hoping that we don't run into time consuming problems with the kalman filter/SARIMAX merge.

**Comment by josef-pkt** [comment]
stackoverflow: seasonal_decompose() in statsmodels can't understand frequent H
http://stackoverflow.com/questions/29229889/seasonal-decompose-in-statsmodels-cant-understand-frequent-h

**Comment by josef-pkt** [comment]
I think the `seasonal_decompose` function should allow that the user overrides that default periodicity or missing periodicity

`seasonal_decompose(pd_series.values, freq=24)`  (copied with `24` adjustment from unit test)
`seasonal_decompose(pd_series, freq=24)`  should use 24 period seasonality for whatever freq is specified in the pandas series.

In the current code freq of pd_series is checked first and used, independent of whether `freq is None`

**Comment by nipunreddevil** [comment]
Hi,
Many thanks for the awesome package!
I was wondering if there's progress on this. Is there a workaround in the meanwhile?

**Comment by cheevahagadog** [comment]
The last comment on #2856 helped me (e.g. using `.values` on my pandas series)

**Comment by bashtage** [comment]
See the workaround in #2398. `'D'` is supported now but corresponds to a 7 day period.
