### ISSUE TITLE
[tsa] Why is the data sorted in the seasonal plot

### ISSUE THREAD

**Issue by ThomasLecocq** [statsmodels/statsmodels#2110]
At first, it seems counter intuitive to sort the Series when plotting a seasonal_plot (month- or quarter-, e.g.), what is the reason for this ? https://github.com/statsmodels/statsmodels/blob/master/statsmodels/graphics/tsaplots.py#L190

The result of a month plot makes more sense (to me) when it is not sorted. Maybe it should be optional ?

I've also added a trendline to each group, which adds some info on the behaviour of the changes through the years: this is an example of 30 years temperature data, monthly plotted: 

![temp](https://cloud.githubusercontent.com/assets/916937/5216481/3a248400-7634-11e4-8e71-af0a86700ef1.png)

What do you reckon ?

**Comment by josef-pkt** [comment]
any PR for 0.7, or move to 0.8 ?

**Comment by ThomasLecocq** [comment]
When is 0.7 planned? I could work on that before the end of this week, but not today...

**Comment by josef-pkt** [comment]
my guess is between one and two weeks from now, assuming no unexpected problems.
If the PR looks reasonably "safe", then it could be merged in the last minute.

**Comment by ThomasLecocq** [comment]
have not forgotten.. will do it tomorrow !

**Comment by josef-pkt** [comment]
Thanks, there is still work for a few days left before we can start with the release

**Comment by kiyoto** [comment]
@josef-pkt I am not really sure why df.sort_index() is even needed? When you run groupby in pandas, doesn't it sort by index?

**Comment by josef-pkt** [comment]
@kiyoto  I don't know or I'm not sure, I never went much beyond the use-a-recipe stage with pandas.  Asking on the mailing list might provide an answer.

**Comment by ThomasLecocq** [comment]
djeeeeeez... again completely forgotten this one... pff... will do it asap, really...
