### ISSUE TITLE
llf with robust cov_type

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2140]
related SUMMary issue for robust covariances #1158 
loglikelihood values `llf` is not valid or cannot be used if the model is misspecified and we use a robust sandwich covariance.

nan it by default if `cov_type != 'nonrobust'`, so it disappears from summary()  ???
set llf to nan in PR #2137 

Doing this broke a test for `compare_lr_test` in RegressionResults which raises a warning but still returns the results.
see comment below: it also caused test failures in discrete where Stata reports llf

I reverted the change in PR #2137

TODO: There are other cov_types besides 'nonrobust' where llf is valid and where we can use appropriate LR test. We need to remove the nan for those cases.
`cov_type='fixed scale'` (PR #2137)  and 
GLM with over/under dispersion (not yet implemented)

**Comment by bashtage** [comment]
You should leave the llf since it is always interpretable in terms of KLIC divergence even when the model is misspecified.

**Comment by josef-pkt** [comment]
@bashtage  good argument, I didn't think about KLIC distance. And it's good to have another opinion.

I'm tending now to leaving this things alone, because just seeing the choice of a robust covariance `cov_type` doesn't tell us enough about how the user wants to interpret the model.

The problem I have is that Quasi-likelihood models might not have a likelihood interpretation at all.

In the simple case, we have a model that is close to the specified model, e.g. roughly normal with some heteroscedasticity. In this case, KLIC divergence makes sense.

In the opposite extreme we just use QMLE as a tool to solve the moment conditions, when all we really have and impose is the conditional expectation of the endog. Examples: estimating binary y with OLS, estimating exponential model y = exp(x b) by Poisson, or estimating fractions by Logit and Probit.
This case is much closer to GMM (or even equivalent to it with the mean function as moment condition) than to maximum likelihood.

Another point, misspecified MLE in general estimates the pseudo true value and minimizes KLIC given the specified class of models.
In this case (linear exponential family) we get consistent estimation of mean parameters if the mean function is correctly specified, the rest including `llf` is "extra" and not needed for parameter inference.

essentially: If users are estimating with OLS, do they use a semi-parametric estimator that corresponds to GMM, or do they estimate a linear model that is close to normal?

We don't really know, and in many cases users might not know either or not care.

The follow-up question: If we don't nan or drop any results, do we still adjust the information that is reported in the `summary`?

**Comment by bashtage** [comment]
IMO the role of statistical software is not to be "professor-in-a-box", but to make correct calculations of relevant quantities.  

Plus I don't see much upside in making this change form a long-term maintenance POV (adding another if-then path), which is probably a more important concern.

**Comment by bashtage** [comment]
I think time has settled this one, so closing.
