### ISSUE TITLE
BUG: get_robustcov_results('cluster') fails if `groups` is 2D vector

### ISSUE THREAD

**Issue by dmsul** [statsmodels/statsmodels#2168]
```python
import pandas as pd
import numpy as np
from numpy.random import randn, randint

import statsmodels.api as sm

N = 1000000
Ng = 100000
df = pd.DataFrame({'y': randn(N), 'a': randn(N), 'b': randn(N),
                   'group': randint(Ng, size=N)})
reg = sm.OLS.from_formula('y ~ a + b', df).fit()
if 1 == 1:
    # Variation 1: An (N, 1) array
    clust = reg.get_robustcov_results('cluster', groups=df[['group']].values)
else:
    # Variation 2: An (N, 1) DataFrame
    clust = reg.get_robustcov_results('cluster', groups=df[['group']])
```
As far as I can tell from the documentation, passing these kind of arrays should be supported. It also seems like it should be very easy to fix both. I would have just gone straight to a pull request, but I haven't been using statsmodels very long and I'm still getting a feel for the code, philosophy, etc etc. Wanted to check first before spending the time.

Versions: win7, python 2.7.7 (Anaconda), pandas 0.15.2, numpy 1.9.1, statsmodels 0.7.0 (pulled about 10 minutes ago)

**Comment by josef-pkt** [comment]
related to #2169
most likely insufficient input checking and handling.

In this case a `squeeze` is missing.  groups can be a Series, or it can be 2d with 2columns (IIRC).
groups cannot be a one column array or DataFrame, i.e. shape (nobs, 1)

`clust = reg.get_robustcov_results('cluster', groups=df[['group']].values.squeeze())`
works

**Comment by josef-pkt** [comment]
A PR would be welcome, if you find where the array conversion and `squeeze` needs to go, + unit tests.
Otherwise, I will fix this before 0.7, i.e. soon.

Thanks for the report.

**Comment by dmsul** [comment]
Happy to, once I get familiar with the unit tests.

**Comment by dmsul** [comment]
I now see the problem with having it inside of the `elif`. Will fix. It also turns out that trying to 2way cluster with a DataFrame doesn't work because the way indexing works. I will add a fix for that as well.
