### ISSUE TITLE
compat/python.py does not always define HTTPError

### ISSUE THREAD

**Issue by Anaphory** [statsmodels/statsmodels#2182]
`dataset/utils.py` tries to `import HTTPError` from `compat/python.py`, but that variable is not defined when all imports go right and `PY3` is `True`.

    from statsmodels.compat.python import (range, StringIO, urlopen, HTTPError,
                                       lrange, cPickle, urljoin)

I am not sure what the precise changes mitigated by `compat.python` are. I removed the problem by adding the line

    HTTPError = urllib.error.HTTPError

in the first `try` block, but that may not be the correct way to do it.

**Comment by Anaphory** [comment]
The same is valid for `int`, imported into something else.

**Comment by josef-pkt** [comment]
@Anaphory Are we using `HTTPError` somewhere in statsmodels or did you find this in your own code?

**Comment by Anaphory** [comment]
It's being used in `dataset/utils.py`

**Comment by bashtage** [comment]
Are you using Python 2 or 3?  It looks like it should always get imported one way or the other.

**Comment by Anaphory** [comment]
Python 3.
`statsmodels/dataset/utils.py` *does* try to import it, but fails, because `statsmodels/compat/python.py` does not define it in my case (Python 3.3.5 on FreeBSD):

line 34:

    from urllib.request import HTTPError, urlretrieve

is only run when any of the imports fail. Line 137:

     HTTPError = urllib2.HTTPError

is only run if `not PY3`.
Therefore, HTTPError is never defined for Python 3.

**Comment by bashtage** [comment]
I _think_ the `try` should fail on Python 3 since there is no `urllib2`, and so the except block should execute which will import `HTTPError`.  Running that block on a Python 3.4 works as expected.  Do you have some name-compatability modules installed (e.g. something called urllib2) on your python 3.3?

**Comment by bashtage** [comment]
FWIW This is covered by tests

https://coveralls.io/files/427735574

and so it should fail if not defined in a standard setup.  

I think this issue here is that the `try` `except` is fragile since there can be other modules installed that will allow it to silently complete.

**Comment by josef-pkt** [comment]
I think what would be better is to have the same names defined in the try and in the except so there is no difference in available function names between which branch try/py2 or except/py3 is taken.
in this case, move the `HTTPError, urlretrieve` also into the `try` part

**Comment by josef-pkt** [comment]
@bashtage  general question: Why is there a separate try-except block? Wouldn't it be better to keep all py2 and py3 definitions and imports together in the explicit if else?

**Comment by bashtage** [comment]
This is a minified derivative of how `six` and `pandas` do it.  It was not written from scratch.

**Comment by Anaphory** [comment]
Hmmm. I don't know. Generally, an urllib2 import fails on my system:

    $ python
    Python 3.3.5 (default, Dec  4 2014, 15:54:16) 
    [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd11
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import urllib2
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named 'urllib2'

In that case, I need to do some deeper investigation as to why it failed on my system before I tampered with it, which I cannot do right now.

**Comment by bashtage** [comment]
No problem - still probably a good idea to simplify this module and just use a basic `if`-`then` method to avoid even strange problems.

**Comment by jseabold** [comment]
Try/except comments were addressed in #2187. Can you see if that fixes this odd issue so we can close?

**Comment by josef-pkt** [comment]
closing, reopen if necessary
