### ISSUE TITLE
x13 isn't producing a seasadj file

### ISSUE THREAD

**Issue by lminer** [statsmodels/statsmodels#2201]
Trying to get x13 to work with latest version of x13as on ubuntu 14.04. Ran the following:

    data = sm.datasets.macrodata.load_pandas()
    df = data.data.set_index(pd.period_range('1/1/1959', '9/1/2009', freq='Q'))
    df = df.dropna()
    res = x13_arima_select_order(df['realgdp'], x12path=XPATH, print_stdout=True)

Fails trying to get the seasadj output file as it isn't produced by x13as:

````python
Error
Traceback (most recent call last):
  File "...test.py", line 58, in test_order_selector
    res = x13_arima_select_order(df['realgdp'], x12path=XPATH, print_stdout=True)
  File "/home/.../anaconda/lib/python2.7/site-packages/statsmodels/tsa/x13.py", line 570, in x13_arima_select_order
    start=start, freq=freq, prefer_x13=prefer_x13)
  File "/home/.../anaconda/lib/python2.7/site-packages/statsmodels/tsa/x13.py", line 449, in x13_arima_analysis
    seasadj = _open_and_read(ftempout.name + '.d11')
  File "/home/.../anaconda/lib/python2.7/site-packages/statsmodels/tsa/x13.py", line 198, in _open_and_read
    with open(fname, 'r') as fin:
IOError: [Errno 2] No such file or directory: '/tmp/tmpDqmyet.d11'
````

No error messages written to the .err file.

**Comment by josef-pkt** [comment]
I'm not able to run x13 right now.
Does changing `print_stdout` to False have any effect?

**Comment by lminer** [comment]
No it doesn't have any effect unfortunately

**Comment by josef-pkt** [comment]
The example works for me on Windows (on the commandline not in IDLE which has a conflict with subprocess)

```
>>> res.keys()
['order', 'include_mean', 'results', 'sorder', 'stdout']
>>> res.sorder
(1, 0, 1)
>>> res.order
(1, 1, 0)
>>> len(res.stdout)
474
>>> len(res.results)
115078
>>> print(res.stdout)

X-13ARIMA-SEATS Seasonal Adjustment Program
Version Number 1.1 Build 9
Execution began  Jan 22, 2015  17.40.44

 Reading input spec file from c:\users\josef\appdata\local\temp\tmpksqasx.spc
 Storing any program output into c:\users\josef\appdata\local\temp\tmp_5gmpd.out
 Storing any program error messages into c:\users\josef\appdata\local\temp\tmp_5gmpd.err


Execution complete for c:\users\josef\appdata\local\temp\tmpksqasx.spc at  Jan 22, 2015  17.40.44
```

so it must be something with the Ubuntu setup, where I have no clue.

**Comment by josef-pkt** [comment]
one possibility, having no clue and just comparing the patterns:

`'/tmp/tmpDqmyet.d11'`

has a `d11` extension, while my files are `spc` and `out`

Can you check if the temp directory still exists and if there are any files in there that could match something written by x13?

**Comment by lminer** [comment]
yeah, i get an out file but no d11 file

**Comment by josef-pkt** [comment]
good, then it's just digging through the source to find where the file extension is set. 

can you give it a try?

**Comment by lminer** [comment]
Sure. So dig through the source for x13.py?

**Comment by josef-pkt** [comment]
yes, there is a `d11 d12 d13` on line 426 and more on lines 449 and following, but I never looked at those parts.

**Comment by lminer** [comment]
Looking at `x13.py` it looks like `d11 d12 d13` are options that are written to the spec file. These files should be written out by `x13as`. The program is then expecting a `d11` file but only a `out` file has been produced. Are you sure you aren't getting a `d11` file? You should be getting the same error...

**Comment by jseabold** [comment]
You may have to drop in to the debugger here to see what's going on. I'll
see if I can replicate shortly. How did you build and install x13?

**Comment by jseabold** [comment]
Maybe the x11 option in the spec has changed? Might check the x13 manual to
see.

**Comment by josef-pkt** [comment]
Ok, misleading clue then, checking my tmp directory, I have all files:

"C:\Users\josef\AppData\Local\Temp\tmp_5gmpd.d11"
"C:\Users\josef\AppData\Local\Temp\tmp_5gmpd.d12"
"C:\Users\josef\AppData\Local\Temp\tmp_5gmpd.d13"
"C:\Users\josef\AppData\Local\Temp\tmp_5gmpd.err"
"C:\Users\josef\AppData\Local\Temp\tmp_5gmpd.log"
"C:\Users\josef\AppData\Local\Temp\tmp_5gmpd.out"

.d11 has the time series

```
date	realgdp.d11
------	-----------------------
195901	+0.271321389580318E+04
195902	+0.277084396110652E+04
195903	+0.277087378633951E+04
195904	+0.279509592090276E+04
196001	+0.285014940041844E+04
196002	+0.282701260834353E+04
196003	+0.283407220737162E+04
...
```

**Comment by lminer** [comment]
I downloaded the linux binary from the X-13ARIMA-SEATS homepage. However it wouldn't run because ubuntu 14.04 is missing some libraries associated with the g77 compiler. 

As a result I installed g77 using a method described on this page: http://conquer-ur-computer.blogspot.com/2011/02/g77-offline-installation-for-all-ubuntu.html. So maybe this is the origin of my troubles.

**Comment by jseabold** [comment]
I always just change the ifort or g77 compiler to gfortran and build it.
It's pretty straightforward. Copy the Makefile.linux to Makefile and edit.
Let me know.

**Comment by jseabold** [comment]
I'm unable to replicate on ubuntu 14.04.

```
|5 $ ./x13as --version

 X-13ARIMA-SEATS Seasonal Adjustment Program
 Version Number 1.1 Build 9
```

You might try using `x13_arima_analysis` with the speconly option and
running the spec straight through x13as.

**Comment by lminer** [comment]
Built it with gfortran and now it works perfectly. problem solved!
