### ISSUE TITLE
survival2: incomplete refactoring, input/data format?

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#223]
In d307d1b8c75527139abbe315ce9cf4614c17fa08
https://github.com/josef-pkt/statsmodels/commit/d307d1b8c75527139abbe315ce9cf4614c17fa08

I did the necessary changes to get ex_kaplan_meier.py to work

some thoughts

the example uses a string array for exog, and cast partially internally. This is fragile, 
    for example np.array(['1.0']).astype(int) doesn't work, requires casting to float first
    -> I think we should just require numeric input, and use formula or pandas to let the user convert the data to a numeric format, and we provide the support/helper functions for this

the earlier format used indices into the data array as argument, now a Survival instance, and for exog an array is required. 
    This might not be fully converted yet, some parts that are now handled in Survival still seem to be in CoxPH

stratification assigns groups/strata by equality of floating numbers. This might be fragile, but we could just alert the user.

KMResults.normalized_cov_params in example is 1d ?

no tests, needs at least sanity checks to keep the different parts up-to-date through refactorings

long methods, and long if statements indicate that some outsourcing would improve the structure.

Overall survival2.py has a lot of features, and looks like it could be already used. Main problem are that there are not tests.

class structure overall looks fine, nice to have plots to show results

I mainly went through to check for refactoring bugs, especially to check the status after the rebase, and haven't looked at the content in detail yet.

We might want to have a WIP PR, pull request for Work in Progress, as scikit-learn does, for easier commenting on the code.

**Comment by jbrockmendel** [comment]
Isn’t survival2 gone now?  If so, closeable?

**Comment by jseabold** [comment]
Closing this. At a glance, I don't see that most of these notes are still relevant to the current code. Maybe more work to figure out than to file new ones as they come up.
