### ISSUE TITLE
TST: webuse test failure on python-xy Ubuntu

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2233]
We get two test failures across all Ubuntu machines in python-xy testing
e.g. https://launchpadlibrarian.net/196880479/buildlog_ubuntu-vivid-i386.statsmodels_0.7.0~ppa25~revno-1812~ubuntu15.04.1_FAILEDTOBUILD.txt.gz

is this a permission error, or disabled feature on a test server?
there is also a test for `get_rdataset` that uses `urlopen` and doesn't fail

what does pandas do?

```
======================================================================
ERROR: statsmodels.datasets.tests.test_utils.test_webuse
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/buildd/statsmodels-0.7.0~ppa25~revno/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/datasets/tests/test_utils.py", line 26, in test_webuse
    res1 = webuse('macrodata', baseurl=base_gh, as_df=False)
  File "/build/buildd/statsmodels-0.7.0~ppa25~revno/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/datasets/utils.py", line 47, in webuse
    dta = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>

======================================================================
ERROR: statsmodels.datasets.tests.test_utils.test_webuse_pandas
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/buildd/statsmodels-0.7.0~ppa25~revno/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/datasets/tests/test_utils.py", line 36, in test_webuse_pandas
    res1 = webuse('macrodata', baseurl=base_gh)
  File "/build/buildd/statsmodels-0.7.0~ppa25~revno/debian/python-statsmodels/usr/lib/python2.7/dist-packages/statsmodels/datasets/utils.py", line 47, in webuse
    dta = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>

----------------------------------------------------------------------
Ran 3428 tests in 645.599s

FAILED (SKIP=24, errors=2)
```

**Comment by josef-pkt** [comment]
it doesn't fail on Debian
http://nipy.bic.berkeley.edu/builders/statsmodels-py2.x-sid-sparc/builds/273/steps/shell_5/logs/stdio

BTW: Debian wheezy testing of nipy is using statsmodels 0.5 ! 
results currently irrelevant

**Comment by matthew-brett** [comment]
What is the value of ``url``?

**Comment by josef-pkt** [comment]
It should be the link to one of our data files, but maybe github uses https (it does for me)

`"http://github.com/statsmodels/statsmodels/raw/master/statsmodels/datasets/macrodata/macrodata.dta"`

**Comment by matthew-brett** [comment]
Can you make an extra test doing a simple system call?:

process.check_call(['curl', '-O',  'http://github.com/statsmodels/statsmodels/raw/master/statsmodels/datasets/macrodata/macrodata.dta'])

to see what happens?

**Comment by josef-pkt** [comment]
It's a bit of a detour to check this. The Ubuntu python-xy testing on launchpad runs the unit tests and build each night, so any debugging has a 24 hour cycle, and needs to go through making changes in the unit test.
That's why I was hoping that someone has a more educated guess than mine.

the test was added in #2226

**Comment by josef-pkt** [comment]
@timmie  Do you have a bit of time to help figure this out?

@matthew-brett  as explanation: Timmie set up the python-xy build recipe on Ubuntu some years ago, but he doesn't use python anymore. However, he is still maintaining it with limited time.

https://code.launchpad.net/~pythonxy/+recipe/statsmodels-daily-current

**Comment by matthew-brett** [comment]
Test passes on a machine built with:

```
vagrant init larryli/vivid64
vagrant up
vagrant ssh
```

Then (on the machine):

```
sudo apt-get install python-statsmodels cython virtualenv
git clone git://github.com/statsmodels/statsmodels.git
cd statmodels
virtualenv --system-site-packages tmp
. tmp/bin/activate
python setup.py install

cd ..
nosetests /home/vagrant/statsmodels/tmp/local/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-linux-x86_64.egg/statsmodels/datasets/tests/test_utils.py
```

**Comment by josef-pkt** [comment]
Is there a way to check what error message is created if https is disabled?

I just realized that I can also try on my Windows. Without internet connection, I get two errors in the test_utils with
```
  File "C:\Programs\Python27\lib\urllib2.py", line 1161, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11004] getaddrinfo failed>
```

which is similar but a different Errno

I think we need to skip the test if a valid internet access or permission is not available.

**Comment by matthew-brett** [comment]
I have a similar thought, that Python x, y may have a broken SSL library somewhere.

**Comment by josef-pkt** [comment]
broken or intentionally disabled?
Last time I tried to figure out something about the Ubuntu build process on launchpad, I didn't find anything at all, information is not searchable and I don't know much about Linux distributions.

Also the test doesn't fail on travis, nipy debian, nor appveyor or my local windows machine.

**Comment by josef-pkt** [comment]
If the problems is with https and ssl, then we could work around it by finding another location to download the file that uses plain http.

**Comment by matthew-brett** [comment]
I see the same version of Python (2.7.9-1) and openssl (1.0.1f-1ubuntu10) on the vagrant machine I built.  Python x, y seems to use i386 architecture on a 64-bit machine, I have no idea whether that makes a difference.

**Comment by josef-pkt** [comment]
Ok, I will try http, and we see the results tomorrow.
I put the file on sourceforge `"http://statsmodels.sourceforge.net/devel/_static/macrodata.dta"` for testing

Thanks @matthew-brett 
Python-xy is testing and building the ppa for 6 versions, 3 Ubuntu version and each for i386 and for 64 bit. In this case all of them became red. I only checked a few of the log files.

**Comment by saketkc** [comment]
Another option would be to put all data on `gh-pages` branch. It is served through http.

**Comment by josef-pkt** [comment]
gh-pages sounds good, because our sourceforge is currently only for the documentation and regenerated.
We don't use gh-pages, and we don't want a branch in the main repo for it, but it would be a good longer term solution for storing extra files.

**Comment by saketkc** [comment]
On a side note,  `get_rdataset` tests pass because it is cached, right?
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/datasets/tests/raw.github.com%2Cvincentarelbundock%2CRdatasets%2Cmaster%2Ccsv%2Ccar%2CDuncan.csv.zip

On another note, do you think it makes sense to enable 'verbose' setting for all `urllib2` requests while testing?

**Comment by josef-pkt** [comment]
@saketkc about `get_rdataset`: 
I didn't see those files, or I didn't pay attention to them.
I tried to read through the tests for `get_rdataset` and checked it's urlopen code briefly while comparing to `webuse`. I didn't manage to figure out whether it caches or not.
I also have the files locally cached (in my User location), so I didn't get suspicious enough.

`get_rdataset` has also other code to test not just the downloading, while `webuse` is just downloading and sending it to the Stata reader.
But `get_rdataset` is not tested on python 3.  ->  more unit tests are needed, and maybe a review of what the current tests are doing.

I didn't know about `verbose` for urllib2. We don't want to have noisy printing in the tests if everything works as it's supposed to work. It should just show `.........................................`.
But it sounds helpful for debugging when there is a problem and we could enable it temporarily.

**Comment by josef-pkt** [comment]
OK, now I understand the unit test for `get_rdataset`. 
It's essentially a smoke test to read from cache.

```
>>> from statsmodels.datasets import get_rdataset
>>> cur_dir = r"E:\Josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2_py27\statsmodels\statsmodels\datasets\tests"
>>> duncan = get_rdataset("Duncan", "car", cache=cur_dir)
>>> duncan.from_cache
True
```

**Comment by saketkc** [comment]
Any particular reason to not cache the other datasets?

**Comment by dacoex** [comment]
@josef-pkt 

I think the problem was a very slow response of the github servers this weekend.

So maybe good to add some exception handling:
http://stackoverflow.com/questions/25277833/retry-loading-page-on-timeout-with-urllib2
http://stackoverflow.com/questions/9446387/how-to-retry-urllib2-request-when-fails

I do not know why this does not work.
files a Launchpad bug:
https://bugs.launchpad.net/bugs/1419510

**Comment by josef-pkt** [comment]
Ok, this has been cleared up in the bug report. Thanks for filing it.
https://bugs.launchpad.net/launchpad/+bug/1419510

```
Launchpad's build farm does not have Internet access. Build dependencies must be 
packaged in the Ubuntu primary archive or your PPA, and declared in your source 
package's Build-Depends field.
```

**Comment by timmie** [comment]
@josef-pkt 
That meas we'd need a separate data package?

IMHO, this could be then even leverage some potential to use the data for test in other packages such as pandas or seaborn, blaze/into...

**Comment by josef-pkt** [comment]
@timmie  Thanks, but that's not necessary.
In our case these are just two supporting functions mainly used for examples. We either use a test file that is included in the source, as we already do for one of them, or we just skip the tests if there is no internet connection.

The point here was largely to figure out what to do so we have again a clean test run in the python-xy testing, and to make sure there were no hidden bugs.

related: I think some of our notebook examples in the doc build might require internet access, but I haven't checked and I might be wrong if those examples are not included yet. There is no failure on launchpad.

**Comment by josef-pkt** [comment]
Related to this test Travis-CI just timed out for the internet connection on one of the python versions.

**Comment by timmie** [comment]
@josef-pkt 
So will you implement a workaround here?

**Comment by josef-pkt** [comment]
@timmie  Yes, I will, just didn't have time today.

**Comment by jseabold** [comment]
Parking [this comment](https://github.com/statsmodels/statsmodels/pull/2247#issuecomment-73979324) here. We shouldn't have any unit tests depend on an internet connection (or any external state). It's a PITA but we're not testing internet connections of our build bots.

**Comment by josef-pkt** [comment]
`get_rdataset` is not tested on python 3, webuse PR was fixing bug for python 3, and I'm not running py 3 right now on a regular basis to test it.

I'd rather use an internet connection and test what the function is supposed to be doing, than no test at all or possibly some messy mocking for two non-core functions.

Now that webuse was tested, I don't really care very much, until there is a change in code. (We don't need to test that youtube parsing isn't broken)

**Comment by josef-pkt** [comment]
#2247 added skipping the tests if internet is not available

adding caching to webuse should be a separate issue

closing

**Comment by josef-pkt** [comment]
not enough, `error: [Errno 104] Connection reset by peer`  error
https://travis-ci.org/statsmodels/statsmodels/jobs/50981956

I'm going to disable this again for 0.7

**Comment by saketkc** [comment]
Probably due to https://twitter.com/sfnet_ops/status/567377437193797632

**Comment by josef-pkt** [comment]
We can try again, when I'm not in the rush of preparing for a release.

**Comment by bashtage** [comment]
> not enough, error: [Errno 104] Connection reset by peer error
> https://travis-ci.org/statsmodels/statsmodels/jobs/50981956
> 
> I'm going to disable this again for 0.7

The issue with the previous PR is that is isn't checking the actual URL, just checking if internet is available.  Of course it is possible that goggle is reachable but this file is not.

**Comment by saketkc** [comment]
Yes. The point of that PR was to just check internet availability. Anything except `URLError` still needs to be handled, separately.
