### ISSUE TITLE
Incorporation of MICE?

### ISSUE THREAD

**Issue by agartland** [statsmodels/statsmodels#2237]
Hi,
I was excited to find Frank Cheng's blog posts and code implementing MICE in Python with pandas and statsmodels. It doesn't seem that the code is  incorporated into a statsmodels branch or elsewhere on Github. Do you know what state its in or what the plan for that code is?

I don't think I know statsmodels well enough to know how to build it in, but if you think its ready I'll start using MICE for a project I'm working on now. I'd be happy to fork a version and contribute fixes, documentation, features etc. as I go.
Thanks, 
Andrew

**Comment by josef-pkt** [comment]
The PR with the updated version of Frank's GSOC is #2076
Frank's original PR is #1757  
@kshedden will know more

I haven't looked at the new version yet. Overall the project was in good shape at the end of GSOC which is the last time that I looked at it. There were a few smaller things still unclear, like how to handle the different degrees of freedom (when taking the number of missing values for each variable into account)

I was thinking of targeting it for merge in 0.8, but my todo list is already getting very large, having an additional user and reviewer would make this much easier.

About building statsmodels: What's your operating system? 
Mice is pure python and changes don't require recompiling, but the initial setup of a development version of statsmodels requires the compiled extensions.
With a compiler (and cython) available it would be just `setup.py build_ext --inplace` in the checkout folder. 
(Without a compiler it would be possible to "cheat" by copying the extensions a binary install, when we only work on pure python changes.)

I guess, that it will be necessary to rebase #2076 before you start to work with it. There have been changes in master in many places and some might have affected Mice which works on top of several of the existing models

**Comment by josef-pkt** [comment]
I will close this issue as duplicate, so it will be better to discuss MICE in the comments to the PR.

We can still discuss installation issues here, if you have questions or need help.

**Comment by agartland** [comment]
Thanks @josef-pkt. The ipython notebooks look great. I don't know how my searching didn't find these PRs.

I will clone and try to build and see how far I get. I have different systems I could work on. How would I checkout this PR though? Should I fork @kshedden's statsmodels repo?

**Comment by josef-pkt** [comment]
The simple way is to clone the remote branch from the author of the PR, i.e. Kerby's.

(I stopped doing this because github adds a PR branch also as a semi-hidden branch to the main statsmodels repo and it is possible to checkout a PR directly. After some initial setup, which I don't remember and need to google for, I can just do
`git checkout remotes/upstream/pr/2076`
which is nice because I have to check out many PR's and don't need to add and fetch from each contributors fork/remote.)

**Comment by kshedden** [comment]
It should work to just copy the mice.py file into your statsmodels distribution (put it into the sandbox directory).  This particular PR is self contained in a single file.

**Comment by josef-pkt** [comment]
Copying the file is easier to just give it a quick try.
However, with a full checkout/clone @agartland  can also make changes and submit a PR either to the PR branch or to statsmodels after merge.

One possibility is also to merge MICE right after statsmodels 0.7 has been released, and then make incremental improvements in statsmodels master for the 0.8 release. It looks to me that the main task will be to bring test coverage to acceptable levels, either against R or Stata (subject to random fluctuations).

**Comment by agartland** [comment]
FYI, I've copied the mice directory from @kshedden and made my own branch `mymice` on the statsmodels repo. Everything is built and I ran the code from the example notebook. I should have time to work with it over the next couple weeks. If I discover anything that needs work I suppose I'll submit a PR after this all gets merged? Thanks for your help today
