### ISSUE TITLE
import error:　from scipy.linalg import calc_lwork

### ISSUE THREAD

**Issue by allcyy** [statsmodels/statsmodels#2255]
when i import  statsmodels.api, it tips [cannot import name 'calc_lwork']
i've installed scipy, and in the package scipy.linalg i didn't find out any object named calc_lwork.

python version: 3.4.2, 32bit on win32.

**Comment by josef-pkt** [comment]
This happens only with scipy 0.15.0, It has been fixed in scipy 0.15.1.
It's also fixed in statsmodels master

see #2184
for a temporary work around by monkey patching the missing name, see end of issue description in #2191

will close as duplicate and already fixed

**Comment by allcyy** [comment]
Thanks, problem solved.
