### ISSUE TITLE
DOCs pca_fertility_factors notebook includes output

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2281]
https://github.com/statsmodels/statsmodels/blob/master/examples/notebooks/pca_fertility_factors.ipynb

we don't want to fill up the repo with automatically created output

**Comment by bashtage** [comment]
The output is nice since it makes the notebook useful in nbviewer.

Compare

http://nbviewer.ipython.org/github/statsmodels/statsmodels/blob/master/examples/notebooks/ols.ipynb

to 

http://nbviewer.ipython.org/github/statsmodels/statsmodels/blob/master/examples/notebooks/pca_fertility_factors.ipynb

**Comment by josef-pkt** [comment]
Yes, but over time we get megabytes of outdated pictures and print output in the git repo.
That's why we decided to keep them empty. We have automatic execution/rendering/conversion for the documentation build.

**Comment by josef-pkt** [comment]
http://statsmodels.sourceforge.net/devel/examples/notebooks/generated/ols.html

the nbconvert.py script is in top tools folder.
I'm just trying to work my way through part of the doc build.

**Comment by bashtage** [comment]
Why not run BFG once in a while to remove very large bits of history?

https://rtyley.github.io/bfg-repo-cleaner/

**Comment by bashtage** [comment]
One other issue is that this notebook won't work in Python3.  Ar the notebooks tested against both versions of Python?

**Comment by josef-pkt** [comment]
We don't rebase master, or apply filter-branch or similar on it because it would mess up everyone's checkout and branches, (except in an emergency).
We used filter-branch when we moved to github to clean away the nipy and other unrelated history from when stats.models was part of other packages.

There is no check for python 3 compatibility, checking it relies on authors or users.
