### ISSUE TITLE
AutoRegression fit method. how to fit model?

### ISSUE THREAD

**Issue by VlamV** [statsmodels/statsmodels#2290]
In the AR fit method, the OLS is performed in the following manner:
>        # redo estimation for best lag
        # make LHS
        Y = endog[k_ar:, :]
        # make lagged RHS
        X = self._stackX(k_ar, trend)  # sets self.k_trend
        k_trend = self.k_trend
        self.exog_names = util.make_lag_names(self.endog_names, k_ar, k_trend)
        self.Y = Y
        self.X = X
        if method == "cmle":     # do OLS
>            arfit = OLS(Y, X).fit()

if  the size of endog=100 and k_ar=12, then size of Y =88,
thus OLS is performed on 88 points.
shouldn't AR models be performed on the last k_ar points (which is the order)
am I getting this worng?
Thanks

**Comment by bashtage** [comment]
If you have 100 points 0,...,99, and you fit an AR(1), then you regress `y[1:100]` on `y[0:99]` which is just `y[k_ar:`] on the lags formed by `_stackX`

So this is correct.
