### ISSUE TITLE
add seasonal to docs

### ISSUE THREAD

**Issue by dacoex** [statsmodels/statsmodels#2299]
Does 

http://statsmodels.sourceforge.net/0.6.0/release/version0.6.html#seasonal-decomposition

needed to be added to:
http://statsmodels.sourceforge.net/stable/tsa.html

**Comment by harrymvr** [comment]
Just a reminder that the documentation the seasonal decomposition is still not part of the main documentation. It's a simple fix I assume, and of high priority. People should not have to look at the code to figure out how to call a function.
