### ISSUE TITLE
duplicate plots

### ISSUE THREAD

**Issue by dacoex** [statsmodels/statsmodels#2300]
running
http://statsmodels.sourceforge.net/0.6.0/release/version0.6.html#seasonal-decomposition
always leads to double insertion of the figure in IPython (inline mode)

also
sm.tsa.seasonal_decompose does not work
but rather
sm.tsa.seasonal.seasonal_decompose

**Comment by kiyoto** [comment]
>also
sm.tsa.seasonal_decompose does not work
but rather
sm.tsa.seasonal.seasonal_decompose

No, `sm.tsa.seasonal_decompose` works because of [this](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/api.py#l15) in `tsa/api.py`:

```python
from .seasonal import seasonal_decompose
```

**Comment by kiyoto** [comment]
>always leads to double insertion of the figure in IPython (inline mode)

I looked at the code, and this is because the `DecomposeResult.plot` [method](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/seasonal.py#L147) returns the figure.

I would vote for `DecomposeResult.plot` returning `None`, but I am a novice here. Should ask @jseabold.

**Comment by josef-pkt** [comment]
see #1265 for the duplicate plot issue.

There were long discussions for the plot interface, and it is settled the way it is.  
(Changes in response to future development, e.g. in matplotlib, are never ruled out, but currently I don't see any changes on the horizon.)

**Comment by josef-pkt** [comment]
I assume @kiyoto  has answered the import path issue. (I haven't checked)

**Comment by josef-pkt** [comment]
I remove the FAQ label her in favor of #1265
