### ISSUE TITLE
doc build on python 3

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2312]
it's broken all over the place
- tools are not python 3 compatible eg. example_rst.py (I fixed some of those locally)
- we still include our own numpydoc, which might be obsolete now, and is not py 3 compatible
  (I fixed those modules locally)
- There seems to be a problem with sphinx reading files with the system encoding cp1252 in my case, see error message below

I managed to get around the first two, but I'm giving up on sphinx autosummary encoding problems.

```
# Sphinx version: 1.2.3
# Python version: 3.4.3
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Loaded extensions:
Traceback (most recent call last):
  File "C:\programs\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\site-packages\sphinx\cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "C:\programs\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\site-packages\sphinx\application.py", line 147, in __init__
    self._init_builder(buildername)
  File "C:\programs\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\site-packages\sphinx\application.py", line 209, in _init_builder
    self.emit('builder-inited')
  File "C:\programs\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\site-packages\sphinx\application.py", line 408, in emit
    results.append(callback(self, *args))
  File "C:\programs\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\site-packages\sphinx\ext\autosummary\__init__.py", line 548, in process_generate_options
    base_path=app.srcdir)
  File "C:\programs\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\site-packages\sphinx\ext\autosummary\generate.py", line 110, in generate_autosummary_docs
    items = find_autosummary_in_files(sources)
  File "C:\programs\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\site-packages\sphinx\ext\autosummary\generate.py", line 227, in find_autosummary_in_files
    lines = f.read().splitlines()
  File "C:\programs\WinPython-64bit-3.4.3.1\python-3.4.3.amd64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1161: character maps to <undefined>
```

**Comment by josef-pkt** [comment]
`nbgenerate.py`  

- I don't manage to get the hashing hashfunc to work in py3 string versus bytes issue.
  current work around disable hashing
- somewhere `failed to run cell: AttributeError("'dict' object has no attribute 'iteritems'"`
  the notebooks I checked so far run under python 3.4 using directly `ipython notebook`, 
  however    running nbgenerate shows many errors on the command line

**Comment by josef-pkt** [comment]
about numpydoc: After updating to recent release numpydoc 0.6, the python 3.4 build works (I didn't build the examples/notebooks)
There are 742 warnings in this build. I get 122 warnings when building with python 2.7

see #981  To try out, I copied the released numpydoc into our sphinx ext folder. Instead we could switch to doc build requirement for it.

**Comment by rgommers** [comment]
great! 

there's also better error reporting in the new ``numpydoc`` version, so the errors are actually traceable to their source.

**Comment by josef-pkt** [comment]
I was running in a different python version than I thought.
Now I get 1588 warnings with sphinx 1.3.1 :(

It looks like our autodoc template might need a makeover.
I have a huge number of "references unknown document" and a huge number of "document isn't included in any toctree", which might be largely a problem with super or intermediate classes which are not supposed to be in the documentation, I think, e.g. MultinomialResults.

**Comment by josef-pkt** [comment]
I'm back down to 775 warnings after installing sphinx 1.3.5

The "document isn't included in any toctree" for classes like MultinomialResults are gone again.

"Nonexisting documents" methods/attributes/cached are similar to sphinx 1.2.3 on py 3.4
top candidates: `__call__ e.g. in links, `endog_names`, `exog_names` in every (?) model
`VARResults.aic and many others`

**Comment by rgommers** [comment]
I've always avoided Sphinx versions 1.3.0 - 1.3.3, they're quite buggy. 1.3.5 seems to have fixed a few things indeed.

**Comment by TomAugspurger** [comment]
I believe all the tools (nbgenerate and the dataset hashing) are Py3 compatible on [my branch](https://github.com/statsmodels/statsmodels/pull/2816), so we can close this once that's finished.

Unfortunately I don't have a Windows machine that's easily accessible. But hopefully the changes I've made will all be cross-platform, or at least make it easier to debug the problems :) The bit I worry about most is rpy2 for the notebooks that use it to compare to R. I've never had luck installing it on Windows.

**Comment by josef-pkt** [comment]
I haven't tried to install rpy2 yet (I tried it successfully once when Gohlke provided the rpy2 binaries for the first time). 
Winpython has pretty good documentation and, for example, I didn't have problems installing Julia following their instructions. But I just use R directly and wasn't eager enough to figure out R/rpy2.

**Comment by bashtage** [comment]
This can be closed -- docbuild have been on Python3 for a while now.
