### ISSUE TITLE
Cointegration tests - Johansen method not found

### ISSUE THREAD

**Issue by mattivi** [statsmodels/statsmodels#2315]
Dear all,
I've tried to find the `coint_johansen` method, that previously was in `statsmodels.tsa.johansen`. 

A recent Notebook with the previous method is here http://nbviewer.ipython.org/github/mapsa/seminario-doc-2014/blob/master/cointegration-example.ipynb

Where can I now find the unit root test methods?  (I see there is johansen.py in coint branch, but NOT in master)

**Comment by mapsa** [comment]
This method is implemented in a fork of this method:
https://github.com/josef-pkt/statsmodels

**Comment by josef-pkt** [comment]
cointegration test form that branch is no included in the VECM PR #3070

**Comment by mapsa** [comment]
I can't see the vecm package in the master branch, could you please tell me where I can find that function? 
According the notebook I should be able to import it as:

from statsmodels.tsa.vecm.vecm import VECM

Thanks,
Paola

**Comment by josef-pkt** [comment]
It's not yet merged, but will be soon, It's waiting for final review.
I had the wrong PR number, the current version of VECM is #3246   (I fixed it in my previous comment)

**Comment by yangnw** [comment]
@mattivi @mapsa It's been merged into master already. The method can be now found at `statsmodels.tsa.vector_ar.vecm`.

**Comment by nkarnev** [comment]
import statsmodels.tsa.vector_ar.vecm actually produces an error despite vecm.py being in the correct place upon inspecting the older i cloned.
