### ISSUE TITLE
handle seasonality in ARMA models

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#232]
Would be nice to have a seasonal ARMA model.

**Comment by paragrastogi** [comment]
Hi jseabold,

I've implemented a SARIMA model in R using the forecast package from Rob Hyndman: [Rob's website](http://robjhyndman.com/software/forecast/), [package download](https://cran.r-project.org/web/packages/forecast/), and [GitHub repo](https://github.com/robjhyndman/forecast).

I'm not good enough with Python to consider implementing this myself, but maybe this could be a good way to introduce this functionality in your code?

Thanks,

P

**Comment by jbrockmendel** [comment]
closed by sarimax?

**Comment by paragrastogi** [comment]
@jbrockmendel  - funnily enough, I had occasion to revisit the same script over the last couple of weeks. And yes, SARIMAX takes care of this!

**Comment by bashtage** [comment]
Closing since SARIMAX is available.
