### ISSUE TITLE
problems in example notebooks

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2320]
- interaction_anova  minority.table http://stats191.stanford.edu/data/minority.table is no longer available

**Comment by saketkc** [comment]
Still alive here: 
http://web.archive.org/web/20131019010037/http://www.stanford.edu/class/stats191/data/minority.table

**Comment by josef-pkt** [comment]
google found a copy here https://github.com/tcdoan/stats/blob/master/regression/minority.table
(old version of stats 191 R examples)

**Comment by kiyoto** [comment]
Why would this example need to fetch the data from the Web when the file is available locally in the examples directory?

**Comment by kiyoto** [comment]
@josef-pkt Let me know if this is what the issue was about =)

**Comment by josef-pkt** [comment]
@kiyoto  Updating the link is ok, but to avoid further problems with data files in examples I started our own smdatasets repository. 

AFAIR, It will be stored or cached locally after it has been fetched the first time the example is run.

**Comment by kiyoto** [comment]
ah I see. I guess the better way to address all of this is to update the link to files under https://github.com/statsmodels/smdatasets once they are available there.

What will you do to the local copies of *.table files once smdatasets is ready?

**Comment by josef-pkt** [comment]
@kiyoto  Skipper found that the data file was just renamed in the original website and I merged that.
This makes your `stats191-example-data`  branch obsolete.

Thanks anyway, and the plan is still to use smdatasets eventually.
