### ISSUE TITLE
BUG adfuller _str missing in ResultsStore

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2321]
reported by Alan on the mailing list

```
statsmodels\tsa\stattools.pyc in __str__(self)
     23 class ResultsStore(object):
     24     def __str__(self):
---> 25         return self._str  # pylint: disable=E1101

AttributeError: 'ResultsStore' object has no attribute '_str'
```

and 

the attribute names given for the ADF results
http://statsmodels.sourceforge.net/0.6.0/generated/statsmodels.tsa.stattools.adfuller.html
do not match the attribute names in the results store.

**Comment by kiyoto** [comment]
I can "fix" this one what the fix means. Why can't ResultsStore be just a Python hash?

**Comment by josef-pkt** [comment]
> Why can't ResultsStore be just a Python hash?

I like attribute access instead of dictionary access (for autocompletion and less typing), so we use either a simple class or a `Bunch`.

The idea was to get a nice string representation, but the individual hypothesis test need to provide the `_str` attribute, which is missing in 
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/stattools.py#L267

The quickfix is to add a informative `_str`, the longterm solution is to find a common structure for which we have several attempts but haven't settled on a conistent pattern yet.

Often I check Stata, R or SAS printouts to see what is useful information for string representation of results.

**Comment by kiyoto** [comment]
Got it. Do you think one of the hacks [here](http://stackoverflow.com/questions/4984647/accessing-dict-keys-like-an-attribute-in-python) will work?

**Comment by theaverageguy** [comment]
A little help to start @josef-pkt
