### ISSUE TITLE
DOC: notebook examples - require mathjax

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2322]
statespace_local_linear_trend.pynb doesn't render math

I assume that we need mathjax as sphinx-ext  (not tried yet) for notebooks, currently we use pngmath extensions for rst docs

adding
`<script type="text/javascript" src=http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML></script>`
to the generated html of `statsmodels_py34/docs/build/html/examples/notebooks/generated/statespace_local_linear_trend.html`

renders the math correctly

**Comment by bashtage** [comment]
Should probably just add the to the template - it has a logn cache age so there is little harm in having it on every page.

**Comment by josef-pkt** [comment]
I tried adding it to the layout page. However it messes up the pngmath on the regular rst documentation, e.g  in regression.html

Also, the mathjax javascript link is not missing on the notebook pages, it's just the wrong link.
Someone mentioned that the old link that ipython includes is obsolete:

```
<script src="https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"type="text/javascript"></script>
<script type="text/javascript">
```

On my old computer, I had it changed in the ipython source, but that's not transferable and won't work with a unpatched ipython.

**Comment by josef-pkt** [comment]
Actually, on this computer ipython is newer and has the correct mathjax url.
However,  we use our own `tools/notebook_output_template.py` with hardcoded old mathjax url.
Fixing that works for the notebooks to render math correctly.

(sphinx only partially rebuild the docs, so I still need a cleaned make to check if everything works.)

**Comment by josef-pkt** [comment]
in previous comment: math not displaying in `regression.html` is most likely because I don't have latex for pngmath yet on this computer, but sphinx doesn't show an error message now. (maybe it did at the first run)

**Comment by josef-pkt** [comment]
Ok, spotchecking: everything looks fine with the math after installing Latex. 

The only change to make here is changing the link url in `tools/notebook_output_template.py`

(There are still exceptions in statespace_local_linear_trend on python 3.4, but that's a different issue)

**Comment by bashtage** [comment]
mathjax works correctly in docbuilds, e.g., http://www.statsmodels.org/devel/regression.html?highlight=regression
