### ISSUE TITLE
Attribute Error on statsmodels.stats.outliers_influence.variance_inflation_factor

### ISSUE THREAD

**Issue by efranco63** [statsmodels/statsmodels#2325]
When trying to call statsmodels.stats.outliers_influence.variance_inflation_factor, I am receiving an error 'AttributeError: 'module' object has no attribute 'outliers_influence''
Was able to call it just fine a few days ago, did something change?

**Comment by josef-pkt** [comment]
There are no recent changes in our code.

check your imports 
try `import statsmodels.stats.outliers_influence`

I don't see it available through the api `statsmodels.api`

**Comment by efranco63** [comment]
That did the trick, thanks for the help sorry for the bother
