### ISSUE TITLE
tests versus pandas 0.16rc1

### ISSUE THREAD

**Issue by jreback** [statsmodels/statsmodels#2332]
we are about to release `pandas 0.16.0`, can you give a run against the pre-release [here](https://github.com/pydata/pandas/releases) and let us know [here](https://github.com/pydata/pandas/issues/9598)

**Comment by bashtage** [comment]
Just tested against HEAD and there were no pandas-related failures (only ones due to MKL as in #2308)

**Comment by jbrockmendel** [comment]
Closeable?
