### ISSUE TITLE
statsmodels.datasets.webuse should be more generic?

### ISSUE THREAD

**Issue by saketkc** [statsmodels/statsmodels#2336]
Use case:
I have a csv hosted [somewhere](https://raw.githubusercontent.com/saketkc/Rdatasets/lme4_datasets/csv/lme4/sleepstudy.csv)
Note that this doesn't end in `.dta` as the [utils/webuse.py](https://github.com/statsmodels/statsmodels/blob/8a671ed9db2bc981bab3b3251d1d0a13a25c5d2f/statsmodels/datasets/utils.py#L47) currently assumes.

Does it make sense to make it more generic so that `dta` parameter needs to be passed explicitly?
For example(this currently returns a 404):

```
data = sm.datasets.utils.webuse(data="sleepstudy.csv", 

baseurl="https://raw.githubusercontent.com/saketkc/Rdatasets/lme4_datasets/csv/lme4/")
```

**Comment by josef-pkt** [comment]
In the notebooks, IIRC, we are currently reading csv files directly from the web using pandas, which takes a url as location.

```
>>> url = "https://raw.githubusercontent.com/saketkc/Rdatasets/lme4_datasets/csv/lme4/sleepstudy.csv"
>>> import pandas
>>> data = pandas.read_csv(url)
>>> data
     Unnamed: 0  Reaction  Days  Subject
0             1  249.5600     0      308
1             2  258.7047     1      308
2             3  250.8006     2      308
```

with extra keywords

```
>>> data = pandas.read_csv(url, index_col=0)
>>> data.head()
   Reaction  Days  Subject
1  249.5600     0      308
2  258.7047     1      308
3  250.8006     2      308
4  321.4398     3      308
5  356.8519     4      308
```


webuse was initially a utility function to replicate Stata examples.
get_rdatasets is another function with a specific purpose

I guess eventually we can have a generic webuse, but I'm not sure what the advantage is. a unified local caching pattern, ...

**Comment by saketkc** [comment]
I have been using `pandas` as well, however I would have preferred to do it the `sm.datasets` way which keeps consistency, avoiding explicit `pandas` export.

**Comment by saketkc** [comment]
Quick update: I am working on this.

**Comment by bashtage** [comment]
IMO continuing this is not a worthwhile cause since pandas and pandas-datareader are much more maintained and heavily tested. 

Should be closed.
