### ISSUE TITLE
grangercausalitytests hangs

### ISSUE THREAD

**Issue by jerome-white** [statsmodels/statsmodels#2344]
I'm calculating Granger Causality for several time series; on a subset of those time series the function (statsmodels.tsa.stattools.grangercausalitytests) hangs. In many of these situations, SIGALRM is ignored, and even interrupting the script itself (CTRL^C) is ineffective as well.

I've attached an example (erroneous) matrix, along with a script to load the matrix and call grangercausalitytests (It's actually a tar.bz file, not a PNG file). I'm using statsmodels 0.6.1

![granger-error tar bz](https://cloud.githubusercontent.com/assets/6140840/6863175/19d56256-d466-11e4-8b29-715fbe8a2548.png)

**Comment by josef-pkt** [comment]
check if you have nans or inf in your data.

What operating system and which numpy version do you use?

There is no missing value handling in grangercausality tests and in some LAPACK version the svd can hang.

**Comment by bigoperm** [comment]
Thanks! Removing the NaN's and INF's did the trick.

I'm using numpy 1.8.2 and Ubuntu 14.04.2 LTS
