### ISSUE TITLE
plot_pacf confidence intervals

### ISSUE THREAD

**Issue by fccoelho** [statsmodels/statsmodels#2345]
In the plot_pacf function, the confidence interval (shaded area) is hard-coded to 75% (alpha=.25), I think it should reflect the alpha specified in the call to pacf.

**Comment by josef-pkt** [comment]
It looks like this has been fixed, but I don't find any commit or PR
Trying an example, the confidence interval gets wider as I reduce alpha, so it clearly not ignored
