### ISSUE TITLE
Uniform return value from {,p}acf

### ISSUE THREAD

**Issue by anntzer** [statsmodels/statsmodels#2366]
Currently, `tsa.{,p}acf` can return either a single or multiple values depending on whether some arguments are `None`, which is problematic for functions that just forward arguments to `{,p}acf`, such as `plot_{,p}acf`: the docstring of `plot_acf` mentions
```
alpha : scalar, optional
    If a number is given, the confidence intervals for the given level are
    returned. For instance if alpha=.05, 95 % confidence intervals are
    returned where the standard deviation is computed according to
    Bartlett's formula. If None, no confidence intervals are plotted.
```
but in fact passing `alpha=None` fails altogether:
```
In [4]: tsa.graphics.plot_acf(np.arange(1000), alpha=None)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-641b6cce3e77> in <module>()
----> 1 tsa.graphics.plot_acf(np.arange(1000), alpha=None)

/usr/lib/python3.4/site-packages/statsmodels/graphics/tsaplots.py in plot_acf(x, ax, lags, alpha, use_vlines, unbiased, fft, **kwargs)
     69 
     70     acf_x, confint = acf(x, nlags=nlags, alpha=alpha, fft=fft,
---> 71                          unbiased=unbiased)
     72 
     73     if use_vlines:

ValueError: too many values to unpack (expected 2)
```

Best would probably to always return all return values, defaulting them to None if they are not computed.  In any case, at least the plotting functions need to be fixed.

**Comment by josef-pkt** [comment]
Thanks for reporting.

The behavior of plot_acf is clearly a bug.

The returns of acf and related functions are more difficult to change, because it will not be backwards compatible (breaking user code) and we don't have a consistent policy for returning None instead of a variable number of returns.
(My trend has been to return a Bunch or similar class if we need flexible returns)

**Comment by kiyoto** [comment]
@josef-pkt Fixing the bug here: https://github.com/statsmodels/statsmodels/pull/2552

**Comment by josef-pkt** [comment]
closing here
#2552 fixes the alpha=None bug
#2367 is open for deciding on flexible number of returns
