### ISSUE TITLE
plot_{,p}acf extra arguments

### ISSUE THREAD

**Issue by anntzer** [statsmodels/statsmodels#2369]
Currently, extra arguments to `plot_{,p}acf` are passed directly to the plotting functions, `plot` and `axhline`, as documented.  However, they are also passed to `vlines`, which accepts a different set of keyword arguments (`LineCollection` properties rather than `Line2D` properties), so e.g. something as simple `ls="-"` fails.
In fact, even with `use_vlines=False`, `ls="-"` can fail for a different and more subtle reason: if you start Python3 a couple of times until `list({"ls", "linestyle"}) == ['ls', 'linestyle']` (which depends on hash randomization) and try again setting `ls="-"` (with `use_vlines=False`), this will seemingly have no effect on the plot (i.e. it'll use dots instead of a connected line).  This is because `plot_{,p}acf` calls `kwargs.setdefault("linestyle", "None")` and in this case, the latter entry (as decided by hash ordering) wins.

**Comment by josef-pkt** [comment]
@anntzer Thanks for the feedback.
I'll try to look at it later today.  Using the same keyword options in two different, incompatible plot functions sounds wrong to me.
Are there changes in matplotlib that might have changed the behavior? Or maybe it's just that nobody reported it yet.
