### ISSUE TITLE
X12/X13

### ISSUE THREAD

**Issue by huig-** [statsmodels/statsmodels#2372]
statsmodels.tsa.x13.x13_arima_select_order and x13.x13_arima_analysis give me problems when running a script in python. something about X12PATH or something like that which i have no clue about what is it. maybe you could give a little more documentation of that

**Comment by josef-pkt** [comment]
Hi, 
You need to provide more information.
Which operating system? How did you install x13? Is it on the system path? ...

see `x12path` keyword in http://statsmodels.sourceforge.net/devel/generated/statsmodels.tsa.x13.x13_arima_select_order.html
I don't see any installation instructions right now.

I don't remember the details but didn't have any problems when I tried it on Windows. (I don't have it yet on my new computer.)

**Comment by huig-** [comment]
I am using Ubuntu 14.04 and downloaded x13 from https://www.census.gov/srd/www/x13as/
Currently i solved the issue and worked for me, although i think it could be a little bit more documented. Looking at http://statsmodels.sourceforge.net/stable/tsa.html i don't know what are the arguments to some methods, for example sm.tsa.arima_model.ARIMA has little documentation and at the method 'predict' it isn't very clarifying what 'params' is

**Comment by jseabold** [comment]
The X12 usage is documented in INSTALL. If that's a little buried, and it
would be helpful to document elsewhere, feel free to make a PR.
