### ISSUE TITLE
tsa_arma_0 notebook (sunspot data) is outdated

### ISSUE THREAD

**Issue by anntzer** [statsmodels/statsmodels#2381]
Not so hard to fix (`isinvertible` and `isstationary` are now attributes; `generate_sample` now takes a `nsample` argument instead of `size`) but because the notebook format changed recently I cannot produce a clean patch.

**Comment by josef-pkt** [comment]
related I ran into problems with one of the notebools on robust estimation.

@anntzer Thanks for reporting. 

Eventually we will have to do one noisy switch in format. I guess we still wait a little bit with it.
I'm currently still on the old format AFAIK, I'm seeing downgrade from format 3 to format 2 messages when I open notebooks, but I'm not up to date on ipython notebook development.

I have started to look at cleaning up some other notebooks and I should be able to fix this also.
