### ISSUE TITLE
lillifors/ks_test

### ISSUE THREAD

**Issue by anntzer** [statsmodels/statsmodels#2383]
I would suggest deprecating the two names `statsmodels.stats.diagnostic.{lillifors,kstest_normal}` in favor of `lilliefors`.  The first one because it is a misspelling, the second one because it is a bit confusing, especially given that scipy also provides a `scipy.stats.kstest` which is an *actual* KS test (against a known distribution).

**Comment by josef-pkt** [comment]
lilliefors is a KS test, it only relaxes the assumption of known mean and variance.

I added the lillifors name as a compromise, in case some users know it. I don't really like unqualified names of people as names, and I never remember how to spell it, if I don't have code completion.

names similar to  `ks_xxx`, `ad_xxx` are supposed to be extendable and informative name patterns.

**Comment by josef-pkt** [comment]
However, we need to fix the spelling of lilliefors, I find 4 `lillifors`  in the module, including `lillifors_table`
