### ISSUE TITLE
statsmodels tsa.seasonal_decompose

### ISSUE THREAD

**Issue by gabriellilor** [statsmodels/statsmodels#2391]
Hi,

I am using the function to analyze a data frame with a frequency per minute (T). I get this error. Is there a bug or I am wrong?

Thanks for your time
## Lorenzo

ValueError                                Traceback (most recent call last)
<ipython-input-111-c384980f70b9> in <module>()
      1 #decomposizione
----> 2 res = sm.tsa.seasonal_decompose(result.p_net)

C:\Python27\lib\site-packages\statsmodels-0.6.1-py2.7-win32.egg\statsmodels\tsa\seasonal.pyc in seasonal_decompose(x, model, filt, freq)

```
 68 
 69     if pfreq is not None:
```

---> 70         pfreq = freq_to_period(pfreq)
     71         if freq and pfreq != freq:
     72             raise ValueError("Inferred frequency of index and frequency "

C:\Python27\lib\site-packages\statsmodels-0.6.1-py2.7-win32.egg\statsmodels\tsa\tsatools.pyc in freq_to_period(freq)
    655     else:  # pragma : no cover
    656         raise ValueError("freq {} not understood. Please report if you "
--> 657                          "think this in error.".format(freq))
    658 
    659 

ValueError: freq T not understood. Please report if you think this in error.

**Comment by josef-pkt** [comment]
this is either fixed or can now be avoided with the `freq` option
no replicable example to check this
closing
