### ISSUE TITLE
sm.tsa.seasonal_decompose ValueError: freq D not understood. Please report if you think this in error. 

### ISSUE THREAD

**Issue by Kaydannik** [statsmodels/statsmodels#2398]
I have daily pandas timeseries, and got troubles with sm.tsa.seasonal_decompose.

ValueError: freq D not understood. Please report if you think this in error.

Here is full trace 

``` python
print "Content"
print pdobj['inventory']
print "Index"
print pdobj['inventory'].index.inferred_freq
res = sm.tsa.seasonal_decompose(pdobj['inventory'])
```

```
Content
2015-04-13    513252
2015-04-14    418773
2015-04-15    456856
2015-04-16    360104
2015-04-17    328377
2015-04-18    314759
2015-04-19    415740
2015-04-20    479944
2015-04-21    526775
2015-04-22    600212
2015-04-23    536446
2015-04-24    370978
2015-04-25    307273
2015-04-26    351786
2015-04-27    428174
2015-04-28    453368
2015-04-29    392690
2015-04-30    926613
2015-05-01    582624
2015-05-02    470657
2015-05-03    288485
2015-05-04    319590
2015-05-05    517233
2015-05-06    516843
2015-05-07    525178
2015-05-08    451431
2015-05-09    297885
2015-05-10    196790
2015-05-11    451695
2015-05-12    464971
Name: inventory, dtype: int64
Index
D
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-314-45db78ff5a19> in <module>()
     16 print "Index"
     17 print pdobj['inventory'].index.inferred_freq
---> 18 res = sm.tsa.seasonal_decompose(pdobj['inventory'])
     19 
     20 

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-macosx-10.10-x86_64.egg/statsmodels/tsa/seasonal.pyc in seasonal_decompose(x, model, filt, freq)
     68 
     69     if pfreq is not None:
---> 70         pfreq = freq_to_period(pfreq)
     71         if freq and pfreq != freq:
     72             raise ValueError("Inferred frequency of index and frequency "

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-macosx-10.10-x86_64.egg/statsmodels/tsa/tsatools.pyc in freq_to_period(freq)
    655     else:  # pragma : no cover
    656         raise ValueError("freq {} not understood. Please report if you "
--> 657                          "think this in error.".format(freq))
    658 
    659 

ValueError: freq D not understood. Please report if you think this in error.
```

**Comment by Kaydannik** [comment]
After reading this article http://java.dzone.com/articles/seasonal-periods i can understand it better.
So anyway, would be great to do not read freq from pandas object if there is parameter present

**Comment by josef-pkt** [comment]
(I added more formatting to the description.)

I never looked at all how time and date are handled in pandas and statsmodels. But we get `freq` related questions quite often.

Do all the functions have an option for the user to set the `freq` used for the analysis, independently of the pandas `freq` ?
Can we raise an exception if freq not specified by user that points user to provide it, if the inferred `freq` doesn't work or is not the right one for the analysis?

example similar to Hyndman linked in previous comment:
hourly weather data, or half-hour electricity load/usage

**Comment by josef-pkt** [comment]
I don't know if this is BUG, REF or ENH or all of the above (for the label)

**Comment by jseabold** [comment]
Related to #2109.

**Comment by josef-pkt** [comment]
Thanks for the cross-link. I thought there was something similar but didn't check. (I have my head full of mixins and `fit_xxx`)

**Comment by thehongwu** [comment]
@Kaydannik a work around, try to aggregate on month level and adjust date format like
1990-05-01
1990-06-01
...
1990-12-01
then it should be working.

I encountered the same  error

**Comment by bashtage** [comment]
`D` is supported in master, although it assumes a 7-day cycle which may often be wrong.

**Comment by bashtage** [comment]
The workaround @sukhbinder posted is correct, manually set `freq` (now renamed to `period`).
