### ISSUE TITLE
x13 and arima.fit

### ISSUE THREAD

**Issue by huig-** [statsmodels/statsmodels#2408]
Hello all,
Working with some datasets (pandas 'realgdp' dataset) all works just fine. The problem is when using some data created (ex: 1..100), the method x13.select_order returns errors. It seems that it expects some conditions on the time serie which 1..100 doesn't fulfill. 
Also, when using arima.fit in order to get an ARIMAResult object it gives errors with some time series, it says something about giving your own start_params to try to solve that error but when using start_params=[2,0,1] for example it gives you an error about matrix shapes or something.

**Comment by josef-pkt** [comment]
@huig- Hi, this is all much too vague. We need explicit full tracebacks and examples that we can replicate.

In general: There are datasets or series where the underlying model doesn't make sense and it might "break" at some point, raising an exception in the optimization or while calculating some results. By default, a ARMA(p, q) or ARIMA(p, 0 q) assumes that the series is stationary, and might raise an exception if it cannot fit a stationary model to non-stationary data.
There could also be a problem if the data is completely noise free, and the error has zero variance. (I haven't seen a report for ARIMA yet with this.)

X13 might have similar restriction, but I never checked.

I will close this issue unless there is a specific problem to look at.

**Comment by huig-** [comment]
Well, i understand that 1..100 might be a difficult time serie to fit into a stationary model. But i tried also with abs(cos(i))+0.05 with i in 1..80 and also throwed an exception. First i use x13.arima_select_order to get appropiate parameters and then i create the arima object model with that order. The problem normally arises when trying to forecast. The predict method for the arima object is deprecated or something and the documentation suggest to use the ARIMAResult object for that. So i use arima.fit() in order to get an object of that class and then use the predict method. 
I when using arima.fit().predict(..) i got errors in the first call sometimes and other times in the second one. I am using now arima.fit().forecast() which seems to work in the example series i am working with right now. The problem is i am using this for a tool which can receive a time serie with values i don't control, i can only control their range, and i don't want to get an exception or error when i forecast (cause after 300 values for building the time serie, i will forecast and then update the time serie with the real value many times)

**Comment by ChadFulton** [comment]
Closing since the referenced `ARIMA` model is now deprecated.
