### ISSUE TITLE
MAINT: drop usage of scipy.stats.ss

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2424]
`scipy.stats.ss` will be deprecated and removed.

Searching for `from scipy.stats *ss` and similar shows that we still use it.

see https://github.com/scipy/scipy/pull/4914 and related issues

**Comment by rgommers** [comment]
There's also a few times ``from scipy.stats.stats`` that needs cleaning up (that's not a public submodule and will go away at some point).

In most places the ``axis`` keyword isn't even used, so replacing ``ss(x)`` by ``np.sum(x**2)`` is a trivial fix that increases readability.

**Comment by rgommers** [comment]
I'll just do this now - this is an "end of a long day, no real thinking required" kind of todo.

**Comment by josef-pkt** [comment]
Thanks, 
It might be better to use sum with axis = 0 even if it's redundant. sum over all axis is a problem that is more difficult to detect (because scalars don't raise shape mismatch). and ss defaults to axis=0

**Comment by rgommers** [comment]
that makes sense. done in gh-2426
