### ISSUE TITLE
Doc/Bug: plot_acf only allows integer lags argument.

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#2430]
The signature of `plot_acf` is:

```python
def plot_acf(x, ax=None, lags=None, alpha=.05, use_vlines=True, unbiased=False,
            fft=False, **kwargs):
```

where the documentation suggests:

```python
"""
lags : array_like, optional
        Array of lag values, used on horizontal axis.
        If not given, ``lags=np.arange(len(corr))`` is used.
"""
```

But in fact only integer arguments are allowed. I guess either the docs should be changed to specify integer arguments or the code should be changed to allow an array. I can submit a PR for either option.

My preference is for the latter option since it doesn't require too much of a change and might be useful (the particular use case I'm thinking of is that you may not want the zeroth lag plotted, since it's always 1).

**Comment by ChadFulton** [comment]
Here's the code snippet to replicate:

```python
import numpy as np
from statsmodels.graphics.tsaplots import plot_acf
x = np.random.normal(size=100)
plot_acf(x, lags=np.arange(10))
```

results in:

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-7-947f75034fab> in <module>()
          2 from statsmodels.graphics.tsaplots import plot_acf
          3 x = np.random.normal(size=100)
    ----> 4 plot_acf(x, lags=np.arange(10))

    /.../statsmodels/statsmodels/graphics/tsaplots.py in plot_acf(x, ax, lags, alpha, use_vlines, unbiased, fft, **kwargs)
         66     else:
         67         nlags = lags
    ---> 68         lags = np.arange(lags + 1) # +1 for zero lag
         69 
         70     acf_x, confint = acf(x, nlags=nlags, alpha=alpha, fft=fft,

    TypeError: only length-1 arrays can be converted to Python scalars

**Comment by josef-pkt** [comment]
`acf` doesn't support anything besides integer nlags. 
Is there a usecase for plotting anything else than `np.arange(nlags)`?

**Comment by ChadFulton** [comment]
I guess this would be in symmetry to `acorr_ljungbox`, which has the following to say about lags:

```python
"""
lags : None, int or array_like
    If lags is an integer then this is taken to be the largest lag
    that is included, the test result is reported for all smaller lag length.
    If lags is a list or array, then all lags are included up to the largest
    lag in the list, however only the tests for the lags in the list are
    reported.
"""
```

The only thing I have considered doing with it is excluding the zeroth lag. I suppose you might want to "zoom in" on some section, but that may not be done frequently enough to have code to do that.

**Comment by josef-pkt** [comment]
`acorr_ljungbox` is a hypothesis test where we might not want to see all results (long list).  Also, there should be other options like conditional tests which I never implemented.

I think for acf and similar we never found enough reason not to calculate the full list, especially when fft is fast.

However, I think adding a `drop_zerolag` option (or something like that) might a good idea for the plot function.

(I never checked what the plot would look like with a very large number of lags, since I never thought of an application where that would be interesting. The plot might be crowded.)

**Comment by josef-pkt** [comment]
I don't feel strongly either way about adding lags as array. 
I don't think it will be used much, but it would be easy to implement just for the plotting, i.e. calculate full acf and index with the lags index array.

**Comment by ptrcarta** [comment]
This is old, but thanks because it can be useful to visualize seasonal correlations. For examples:
```
plot_acf(ts, lags=np.arange(5)*7)
```
to visualize the weekly correlations on a daily time series

**Comment by bashtage** [comment]
This is fixed in master.

![image](https://user-images.githubusercontent.com/5585221/57531588-c8257300-7331-11e9-9270-e730e6b65e4f.png)
