### ISSUE TITLE
Importing into WSGI hangs Apache

### ISSUE THREAD

**Issue by nils-werner** [statsmodels/statsmodels#2439]
Assuming you have a virtualenv in `/home/you/webapps/venv` and a project root in `/home/you/webapps/venv/project`.

Try the following `wsgi.py`

    import statsmodels.stats

and a WSGI deamon declaration like

    WSGIDaemonProcess project user=you group=yours python-path=/home/you/webapps/venv/project:/home/you/webapps/venv/lib/python2.7/site-packages
    WSGIScriptAlias /project /home/you/webapps/venv/project/wsgi.py

    <Location /project>
            WSGIProcessGroup project
    </Location>

    <Directory /home/you/webapps/venv/project>
            WSGIScriptReloading On
            <Files wsgi.py>
                    Allow from all
                    Require all granted
            </Files>
    </Directory>

in your `/etc/apache2/sites-enabled/default.conf` or wherever your server is configured.

You should see a error 500 (because there is no `application` variable set in `wsgi.py`) but instead the connection simply stalls.

**Comment by nils-werner** [comment]
Actually, it appears to be `scipy` which is being imported by `sm`.

**Comment by nils-werner** [comment]
For future reference, a `WSGIScriptAlias` line like

    WSGIScriptAlias /project /home/you/webapps/venv/project/wsgi.py process-group=project application-group=%{GLOBAL}

seems to fix it.

Note that the ubiquitous hint

    WSGIApplicationGroup %{GLOBAL}

did not help.

**Comment by josef-pkt** [comment]
@nils-werner   Thanks for providing also an answer   (not that I really know what you're talking about)
