### ISSUE TITLE
Sourceforge domain being blocked by Ublock Origin

### ISSUE THREAD

**Issue by ispmarin** [statsmodels/statsmodels#2450]
Hi all,
The Sourceforge domain has been blocked by Ublock Origin, so the documentation is not accessible for those users. Given the latest reported problems with Sourceforge (as seen on the links below), maybe it should be considered moving the docs from there?

http://arstechnica.com/information-technology/2015/06/sourceforge-locked-in-projects-of-fleeing-users-cashed-in-on-malvertising/

https://mail.gnome.org/archives/gimp-developer-list/2015-May/msg00144.html

https://forum.filezilla-project.org/viewtopic.php?t=36662

**Comment by josef-pkt** [comment]
Did they block the entire domain?
I don't see a reason why the documentation on sourceforge should be blacklisted.

I don't see any problems with our documentation on sourceforge right now, except it's not being updated. It always works well for me, but I'm currently not using any blockers in Chrome or Firefox.

**Comment by mangecoeur** [comment]
Ran into this problem. Seems like a good time to move to ReadTheDocs or similar...

**Comment by josef-pkt** [comment]
That's kind of silly. That also blocks numpy and scipy which are on sourceforge.
I don't like to be forced to choose the web server because of some blacklisting when it's not justified.

**Comment by josef-pkt** [comment]
I guess we have too much custom build on top of the sphinx docs for readthedocs. The alternative is most likely github, which means they are becoming the monopolist.

**Comment by mangecoeur** [comment]
How come there is a lot of extra build?

**Comment by josef-pkt** [comment]
We have a top page that can be used to select version, and we still have customized rendering of notebook examples.
And, AFAIK, readthedocs doesn't build websites with personalized headers and so on. 
The website itself that is uploaded to sourceforge is in a separate repo on github.

**Comment by mangecoeur** [comment]
You can definitely build for multiple versions on RTD (http://read-the-docs.readthedocs.org/en/latest/features.html) , I think there is some customization of styling (not sure how much, compared to what is needed)

**Comment by ispmarin** [comment]
I believe that both numpy and scipy are not hosted on Sourceforge, are you referring to these docs? 
http://docs.scipy.org/doc/

Not familiar with how RTD will build the docs and agree that maybe monopoly is not the best answer, but I still think that some alternative would be interesting, given that Sourceforge is a zombie now.

**Comment by josef-pkt** [comment]
scipy and numpy have the download files on sourceforge and the bandwidth is pretty large for monthly downloads.

sourceforge is not a zombie yet, there are still too many open source projects there. For now, I would wait until the dust settles, and then revisit the issue and make a decision in Fall.

**Comment by jseabold** [comment]
The docs are updated mainly with an rsync, so it's no problem to move
domains if someone wants to deal with those issues.

**Comment by ariddell** [comment]
The Python Software Foundation also provides space for documentation at pythonhosted.org e.g., https://pythonhosted.org/setuptools/

**Comment by dogbertius** [comment]
@mangecoeur That's news to me. I had always assumed SF was a reputable site.

> mangecoeur said: Yes they blocked the entire sourceforge.net , on the basis (I imagine) that many of the downloads now on SF come bundled with adware/spyware

Do you have some examples I could take a look at? Is this just unscrupulous s/w authors, or is it something from the top down (ie: directly from SF staff), like the CNET bloat/spy/mal ware bundling debacle? 

 * http://www.infoworld.com/article/2618688/antimalware/security-pros-slam-cnet-download-com-s-bundling.html
 * http://www.bleepingcomputer.com/forums/t/510527/cnet-and-malware/
