### ISSUE TITLE
BUG/REF ARIMAX  initial observations of x in differencing

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2476]
The first observation in an ARIMA with differencing is not used. however if it is nan then I get a LAPACK message

`Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.`
`Intel MKL ERROR: Parameter 5 was incorrect on entry to DLASCL.`

example exog is a pandas DataFrame diff()

**Comment by bashtage** [comment]
This now raises missingdataerror, which seems clear and users can easily fix.
