### ISSUE TITLE
numpy warnings

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2480]
https://travis-ci.org/statsmodels/statsmodels/jobs/68748936

after enabling warning in tests, we see many
`DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future`

**Comment by rgommers** [comment]
That's going to turn into an error at some point in the future, would be good to fix.....

**Comment by josef-pkt** [comment]
Ok, given our long release intervals I add it to the todo list for 0.7
