### ISSUE TITLE
BUG?  dependency or python version specific warnings

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2493]
The user and other warning about correctly working functions or models are version specific on TravisCI

https://travis-ci.org/statsmodels/statsmodels/builds/69166094
found while debugging warnings in PR #2490

similar to fixes in PR #2490 there could be subtle differences in behavior in python 3 that is not enough to trigger failures (or we don't have strict enough test coverage)

one case
#2492 in stats multicomp - this is just noise
We catch the first case that causes a warning, but not the second case.

My guess is that there is a difference in the settings for filterwarning across version for "default" (warn once) versus "always".

They might all be just noise

**Comment by bashtage** [comment]
@josef-pkt This is fixed in PR #2988

**Comment by josef-pkt** [comment]
closing, related new issue #3163
