### ISSUE TITLE
test with different dtypes, was: family.Binomial integer division

### ISSUE THREAD

**Issue by wesm** [statsmodels/statsmodels#25]
Original Launchpad bug 675631: https://bugs.launchpad.net/statsmodels/+bug/675631
Reported by: josef-pktd (joep).

family.Binomial.initialize uses integer division, that produces an exception when endog is an integer.

fixed in my branch josef-gsoc and will merge to devel

return y*1./self.n

we need tests for dtypes of inputs. I don't think we have many checks for these

error case reported by Sol on mailinglist 2010-11-15

**Comment by josef-pkt** [comment]
the oldest issue with dtypes around :(
