### ISSUE TITLE
Kernel crash for sm.tsa.Arma(data).fit()

### ISSUE THREAD

**Issue by mtmvu** [statsmodels/statsmodels#2509]
http://statsmodels.sourceforge.net/stable/examples/notebooks/generated/tsa_arma_0.html

I followed this example but get stucked at line 8: 

> At line 2699 of file scipy/optimize/lbfgsb/lbfgsb.f
> Internal Error: printf is broken
> RUNNING THE L-BFGS-B CODE
> 
> Machine precision =
#### Version and main components
- Spyder Version:  2.3.4
- Python Version:  3.4.3
- Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux
#### Optional dependencies

pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.1.0 (OK)
zmq >=2.1.11    :  14.6.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.4.2 (OK)

I also have the latest cython package installed.

**Comment by jseabold** [comment]
This sounds like it might be a scipy issue. Can you run

```
from scipy import optimize
optimize.test()
```

**Comment by josef-pkt** [comment]
I saw several problems recently with printf in lbfgsb, use iprint=0 and check permission for file creation and access in the working directory.

I didn't try to investigate any details, but I switched to `solver='bfgs'` for some ARIMA examples in a notebook to avoid crashes with permission errors.

**Comment by MarcusAllen** [comment]
@jseabold 
it failed : 

>...................................................................................../home/*/miniconda3/lib/python3.4/site-packages/scipy/optimize/minpack.py:604: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)
.............F.........................................................................................................................................................K.................................................................Running unit tests for scipy.optimize
NumPy version 1.9.2
NumPy is installed in /home/*/miniconda3/lib/python3.4/site-packages/numpy
SciPy version 0.15.1
SciPy is installed in /home/*/miniconda3/lib/python3.4/site-packages/scipy
Python version 3.4.3 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:29:08) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
nose version 1.3.6


>FAIL: test_lambertw (test_minpack.TestFixedPoint)

>Traceback (most recent call last):
  File "/home/*/miniconda3/lib/python3.4/site-packages/numpy/testing/utils.py", line 602, in chk_same_position
    assert_array_equal(x_id, y_id)
  File "/home/*/miniconda3/lib/python3.4/site-packages/numpy/testing/utils.py", line 739, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/*/miniconda3/lib/python3.4/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

>(mismatch 100.0%)
 x: array(False, dtype=bool)
 y: array(True, dtype=bool)

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/home/*/miniconda3/lib/python3.4/site-packages/scipy/optimize/tests/test_minpack.py", line 474, in test_lambertw
    assert_allclose(xxroot, lambertw(1)/2)
  File "/home/*/miniconda3/lib/python3.4/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/home/*/miniconda3/lib/python3.4/site-packages/numpy/testing/utils.py", line 628, in assert_array_compare
    chk_same_position(x_isnan, y_isnan, hasval='nan')
  File "/home/*/miniconda3/lib/python3.4/site-packages/numpy/testing/utils.py", line 608, in chk_same_position
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

>x and y nan location mismatch:
 x: array(0.2835716452048919)
 y: array((nan+nanj))


>Ran 318 tests in 3.214s

>FAILED (KNOWNFAIL=1, failures=1)

**Comment by jbrockmendel** [comment]
@josef-pkt possibility to create Issue tag for segfaults?  It's likely that most of these are from upstream, but they are worth chasing down to be sure.

**Comment by bashtage** [comment]
This is fixed in master.
