### ISSUE TITLE
MAINT: TravisCI new infrastructure, containers

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2528]
TravisCI shows a legacy warning/comment

Pauli switched for scipy to the new structure
https://github.com/scipy/scipy/pull/5036

We are not compiling any dependencies, so I guess we won't see much time difference.

**Comment by pv** [comment]
Travis-CI seems to promise also faster/more reliable runs due to better cpu scheduling on the new infra... Since statsmodels doesn't seem to be using sudo, transition is probably only adding the `sudo: false`.

**Comment by josef-pkt** [comment]
Thanks @pv we can try that out and switch

**Comment by josef-pkt** [comment]
Thanks @pv we can try that out and switch

**Comment by josef-pkt** [comment]
Silly ipad and a bad connection at the pool

**Comment by bashtage** [comment]
@josef-pkt This is no longer relevant since travis is using docker

**Comment by josef-pkt** [comment]
fixed in #2739
