### ISSUE TITLE
Target IPython Notebook version for examples

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#2530]
It's going to be easier for the NotebookRunner if we target a specific version for the notebooks. Should probably go ahead and convert all of the notebooks. I vote for version 4 to (hopefully) be relatively future proof.

**Comment by jseabold** [comment]
Maybe not. We can actually introspect the notebooks to get the format.

**Comment by kshedden** [comment]
@josef-pkt I came across this, I don:t know if it would be useful here, I haven't tried it yet:

https://pypi.python.org/pypi/runipy

**Comment by josef-pkt** [comment]
Looks like runipy currently only supports format 3 notebooks. 
I have a mix now in my notebooks with both formats 3 and 4.

it seems possible to convert between the two (not tried yet)
http://stackoverflow.com/questions/33246862/converting-ipython-notebooks-from-v4-jupyter-back-to-good-ol-v3
`jupyter nbconvert --to notebook --nbformat 3 mynotebook`

**Comment by JanSchulz** [comment]
This might also be interesting: http://nbsphinx.readthedocs.org/

**Comment by bashtage** [comment]
Should be closable now -- all notebooks have "nbformat": 4

**Comment by josef-pkt** [comment]
@kshedden  Thanks

everything needed to be converted to work with new jupyter doc build, AFAIK
