### ISSUE TITLE
REF: ARMA uses trend as fit argument

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2531]
My guess is that `trend` should be a `__init__` argument. 

I haven't checked, and just saw this while reviewing #1691 and #2526 where param names could change and be wrong if trend argument in repeated call to fit changes.

**Comment by jseabold** [comment]
+1 for moving to `__init__`. I thought we did this already.

**Comment by jseabold** [comment]
Duplicate of #1049.

**Comment by josef-pkt** [comment]
closing as duplicate and adding 0.8 to #1049
