### ISSUE TITLE
ARIMA errors/VAR model error

### ISSUE THREAD

**Issue by mrajancsr** [statsmodels/statsmodels#2534]
Hello, i recently tried to use the ARIMA function in python and noticed differences in values when compared to R's' arima function

example:
x = np.random.normal(0,1,size=2000)
x = x.cumsum()
x = np.diff(x)
sm.tsa.ARMA(x,order=(1,1)).fit()

using R,
I used the same x values that i generated above by calling R functions into python:
r_df = com.convert_to_r_dataframe(pd.DataFrame(x))
%Rpush r_df
%R y1 = ts(r_df)
%R a <- arima(y1,order=c(1,0,1))
%R print(summary(a))

if you notice, the coefficients are completely different for the series.  

Likewise, in the VAR Model, there are some errors.  If you fit a VAR model to two series and use the same VAR model in R, you get completely different set of coefficients.

**Comment by josef-pkt** [comment]
Hi, similar to the comments on the stackoverflow question this is not very informative. 
I just recently compared our ARIMA against Stata and the agreement is very high. However, I don't know much about arima in R.

two possibilities
Are the differences in relative or absolute terms. You are simulating a series without serial correlation (cumsum and diff just cancel), and if the estimated coefficients are 1e-5 or 1e-6 then this might just be minor implementation differences and in the range of the optimization stopping criteria.

If there are large differences in absolute values, e.g. 1e-1, then you need to check the default options in R versus statsmodels. I don't know what the defaults in R are.

**Comment by josef-pkt** [comment]
Also, based on previous issues or stackoverflow questions, there are substantial differences in corner cases, ill conditioned cases and nonstationary time series, because parameter estimates in those cases are not well defined and the treatment and behavior in those cases differs across statistical packages.

**Comment by josef-pkt** [comment]
closing, not enough information
