### ISSUE TITLE
Test cases incorrect in tsa.arima_model.py

### ISSUE THREAD

**Issue by chelleych** [statsmodels/statsmodels#2535]
The testing code under `if __name__ == "__main__":` in `tsa.arima_model.py` does not call ARMA with the model orders and gives the error

``` python
arma = ARMA(y)
TypeError: __init__() missing 1 required positional argument: 'order'
```

**Comment by josef-pkt** [comment]
These are old left-over experimental examples usually during initial development and should be moved to examples if they are useful and deleted if they don't add anything to the already available examples.

**Comment by kiyoto** [comment]
@josef-pkt By examples, are you referring to `examples/tsa/*.py` in this case? I think those seem to be outdated as well (see for example `examples/tsa/ex_arma_all.py`)

Let me know: I might be able to clean stuff up little by little.

**Comment by josef-pkt** [comment]
@kiyoto  Don't bother cleaning up `examples/tsa/*.py` It would take me almost as much time reviewing a PR as cleaning it myself.
I just went through several of those, and parts of them are historical artifacts where I need to decide or figure out if they are completely obsolete or not.

In general: It's more useful for new contributors to add official examples at the top level in the notebooks. In some cases those examples could be largely copied from the internal examples and the unit test cases.

Cleaning up and using internal examples is mainly useful when working on a specific topic and we need example scripts. At least that's true for some of the very old examples like the tsa examples, several other example scripts are in much better condition and it would be relatively easy to clean them up for use in the official documentation.

**Comment by bashtage** [comment]
This seems to be fixed in master.
