### ISSUE TITLE
TST: TravisCI sometimes very slow on old py2.7

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2536]
The python 2.7 version on TravisCI with the old numpy and scipy has errored now several times, on and off, with timeout when the test run takes a very long time
https://travis-ci.org/statsmodels/statsmodels/jobs/70974673

old py 2.7:  43 minutes
latest py 2.7: 14 minutes

There must be a problem with old dependencies with one or some of the tests recently introduced.

investigate ?

**Comment by bashtage** [comment]
@josef-pkt I think this is fixed now

**Comment by josef-pkt** [comment]
I don't remember what solved the specific problem.
The main speedup in TravisCI was Skipper's #2739
