### ISSUE TITLE
MAINT: update version requirements of python and dependencies

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2537]
We haven't updated the version requirements in the documentation in a while, and it doesn't reflect what we are testing.

python version on TravisCI: 2.6, 2.7, 3.3 and 3.4
statsmodels 0.6 supports python 3.2 according to pypi, but we are not testing whether it still works

unit tested versions on TravisCI
https://github.com/statsmodels/statsmodels/blob/master/.travis.yml
scipy still >= 0.11
numpy >= 1.6
pandas >= 0.12 
patsy >= 0.2.1
oldest version tested with py 2.6 only

see comments starting here https://github.com/statsmodels/statsmodels/pull/2533/files#r34624362

**Comment by bashtage** [comment]
I think the minimum versions should be

python 2.7, 3.4 and 3.5 (MPL is dropping 3.3 from testing)
numpy >= 1.7 (3 years ago)
scipy >= 0.13 (3 years old)
pandas >= 0.14 (1 year old, but worth it)
patsy >= 0.3 (1 year old)
matplotlib >= 1.3

@rgommers

**Comment by bashtage** [comment]
The reason is that supporting lots of very old packages has very little benefit these days given the ease which with modern versions can be installed using binary installer across all three major platforms.

**Comment by rgommers** [comment]
Sounds reasonable, although I suspect that @josef-pkt will want to be a bit more conservative. 

Definitely Python 3.2 can go - no one uses that. 2.6/3.3 do have a few users, but we've stopped building Windows and OS X installers for Numpy and Scipy for 2.6 ages ago and no users complained.

**Comment by josef-pkt** [comment]
@yarikoptic What are the LTS versions for numpy, scipy and maybe matplotlib that would be useful to support? 
I assume if anyone updates statsmodels, then they can also update pandas and patsy.

I also think we should increase the minimum versions quite a bit.

@ChadFulton  has some higher requirements for scipy, but that might have to remain optional. (Functionality that only works with scipy > 0.15 or something like that)

The latest numpy compatibility I ran into is vectorized percentile but that requires numpy 1.9. I don't remember other numpy or scipy functions that we could use with an increase in minimum version.

**Comment by bashtage** [comment]
I wouldn't suggest going out of the way to break Python 3.3, but just that it shouldn't get a test build nor official support.  Ditto for 2.6, although it is very easy to write 2.7+ code that breaks on 2.6 (e.g. dict comprehension).

**Comment by josef-pkt** [comment]
@rgommers   Most packages seems to be dropping support for Python 2.6, I think pandas also decided to drop it. I haven't seen problems with Python 3.3  that I remember. We can switch to testing with python 3.5, and drop official support for 3.3. although I guess it will keep working for quite some time.

**Comment by josef-pkt** [comment]
@bashtage   That's my impression also, We will loose support for 2.6 very fast if we don't have it included in TravisCI. (But 2.6. is really old now.)

**Comment by bashtage** [comment]
This can be closed as surpassed by #2978
