### ISSUE TITLE
BUG/Design SARIMAX params is pandas.Series

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2541]
SARIMAX `params` in results is pandas.Series even if I don't use pandas.

`bse` is not

**Comment by ChadFulton** [comment]
Is this still true after the decoupling? It should appropriately use the wrapping classes now. From my test, it seems to be numpy now if pandas isn't used:

```python
endog = np.random.normal(size=100)
mod = sm.tsa.SARIMAX(endog, order=(1,0,1))
res = mod.fit()
print(res.params)
print(type(res.params))
```

    [ 0.52134552 -0.44381714  1.04935706]
    <type 'numpy.ndarray'>

**Comment by josef-pkt** [comment]
I was using a branch that is a few commits behind master. I saw the asarray commit and guess this is fixed.
Another example was the opposite. I used pandas, but bse is an ndarray, on the same branch behind master. Branch is for GLSAR which i was comparing to ARMA and SARIMAX

**Comment by ChadFulton** [comment]
I think both should work correctly now:

```python
np.random.seed(1234)

endog = np.random.normal(size=100)
mod = sm.tsa.SARIMAX(endog, order=(1,0,1))
res = mod.fit()
print(res.params)
print(type(res.params))
print(res.bse)
print(type(res.bse))

print '------'

endog = pd.TimeSeries(np.random.normal(size=100), index=pd.date_range('1980-01-01', periods=100, freq='MS'))
mod = sm.tsa.SARIMAX(endog, order=(1,0,1))
res = mod.fit()
print(res.params)
print(type(res.params))
print(res.bse)
print(type(res.bse))
```

    [ 0.63602381 -0.84542484  0.92326522]
    <type 'numpy.ndarray'>
    [ 0.20134974  0.12867555  0.11103243]
    <type 'numpy.ndarray'>
    ------
    ar.L1    -0.193859
    ma.L1     0.105682
    sigma2    0.952325
    dtype: float64
    <class 'pandas.core.series.Series'>
    ar.L1     1.139310
    ma.L1     1.178701
    sigma2    0.152263
    dtype: float64
    <class 'pandas.core.series.Series'>

**Comment by jbrockmendel** [comment]
@ChadFulton is this still the case?  If not, can this be closed?

**Comment by bashtage** [comment]
Closing, seems fixed.
