### ISSUE TITLE
BUG/ENH tsa ARMA with formulas, from_formula doesn't work

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2547]
http://stackoverflow.com/questions/31483915/arima-from-formula-with-pandas-dataframe

Briefly trying an example, I don't manage to get from_formula to work. Based on a code search, it is not unit tested, and the inherited method is not overwritten.

needs investigation, and most likely some fixes

I haven't checked whether `SARIMAX.form_formula` works

**Comment by josef-pkt** [comment]
As motivation: 
In my recent fixes for ARMA with exog and the comparison to GLSAR, it looks like ARIMAX is a good version of linear model (OLS type) with ARMA errors/residuals. But it looks like it doesn't have all the support yet, it's partially still based on the univariate time series history or tradition.

**Comment by ChadFulton** [comment]
In SARIMAX, it should raise a NotImplementedError.
