### ISSUE TITLE
SARIMAX predict does not actually allow for datetime start/end

### ISSUE THREAD

**Issue by jamesuber** [statsmodels/statsmodels#2553]
Docs indicate it does, but TimeSeriesModel._get_predict_start requires either a string or an int.

**Comment by jaradc** [comment]
I came here to also report that datetime doesn't look to be allowed for the `predict` method of a `<class 'statsmodels.tsa.arima_model.ARIMAResultsWrapper'>` instance which I'm calling `result`.

Example:
This works:
`result.predict(start='2015-10-07', end='2015-10-07')`

This does not work:
`result.predict(start=datetime.date(2015,10,7), end=datetime.date(2015,10,7))`

Error given:
`TypeError: unorderable types: datetime.date() > int()`

**Comment by josef-pkt** [comment]
I don't remember which code SARIMAX shares, but we might have fixed this in the last 2 months or so for ARMA/ARIMA. (this issue is missing labels, so we might have missed this, or missed to close this.)

@jaradc  Which statsmodels version are you using?

**Comment by jaradc** [comment]
When I do pip freeze, in the list, it shows `statsmodels==0.6.1`

**Comment by Namanj** [comment]
Issue raised by jaradc is still there. I'm using statsmodels==0.8.0rc1

**Comment by ChadFulton** [comment]
Thanks for bringing this up!

**Comment by bashtage** [comment]
closing as no longer relevant

```
from statsmodels.tsa.api import SARIMAX
import numpy as np
import pandas as pd
import datetime as dt
y = pd.Series(np.random.standard_normal(1000), index=pd.date_range("1-1-2000",periods=1000,freq="M"))
mod = SARIMAX(y,order=(2,0,1))
res = mod.fit()
res.predict(start=y.index[500].to_pydatetime().date(), end=y.index[-1].to_pydatetime())
```
