### ISSUE TITLE
Interpertating the results from SARIMAX

### ISSUE THREAD

**Issue by jad10d** [statsmodels/statsmodels#2558]
I am trying to wrap my mind around the MA results in my SARIMAX model (p,d,q)=(0,1,10). Basically, I used 4 exogenous variables to explain 1 endogenous variables in its seasonal cycle. From the material I have read, the MA coefficients represent a linear combination of the exogenous impacts on the endogenous variable at the corresponding lag. Here is a summary printout of my results below.

```
Statespace Model Results                           
Dep. Variable:           Inherent_WUE  No. Observations:                 1018
Model:              SARIMAX(0, 1, 10)   Log Likelihood                -378.911
Date:                Thu, 23 Jul 2015 AIC                            785.822
Time:                        15:53:09  BIC                            854.780
Sample:      04-01-2001- 09-30-2006   HQIC                           812.008
                coef         std err         z      P>|z|           [95.0% Conf. Int.]
------------------------------------------------------------------------------
x1            -0.1622      0.020     -8.116      0.000        -0.201    -0.123
x2            -0.1211      0.018     -6.589      0.000        -0.157    -0.085
x3             0.6193      0.031     20.267      0.000         0.559     0.679
ma.L1         -0.4449      0.032    -13.823      0.000        -0.508    -0.382
ma.L2         -0.1089      0.035     -3.138      0.002        -0.177    -0.041
ma.L3         -0.0892      0.035     -2.558      0.011        -0.158    -0.021
ma.L4          0.0124      0.035      0.355      0.723        -0.056     0.081
ma.L5         -0.0654      0.035     -1.885      0.059        -0.133     0.003
ma.L6         -0.0238      0.034     -0.701      0.483        -0.090     0.043
ma.L7          0.0415      0.035      1.176      0.239        -0.028     0.111
ma.L8         -0.0438      0.036     -1.226      0.220        -0.114     0.026
ma.L9          0.0112      0.034      0.327      0.744        -0.056     0.079
ma.L10         0.0122      0.033      0.372      0.710        -0.052     0.076
sigma2         0.1243      0.006     22.428      0.000         0.113     0.135
```

Is my reasoning correct or at least on track to being correct? I would appreciate some thoughts on this matter. Thanks for the help!

**Comment by josef-pkt** [comment]
> the MA coefficients represent a linear combination of the exogenous impacts on the endogenous variable at the corresponding lag

To clarify the terminology: your explanatory variables, x1, x2, x3, are assumed to be exogenous (or predetermined), that is they are assumed not to be correlated with the shocks, or not with the shocks in the current period, depending on the model. The impact of these exogenous variables on the expected value (conditional mean) of the dependent variable is given by the corresponding 3 coefficients. 

The MA term refers to the external shocks to the system, and reflects the impact of all other factors that are not included in the model and are part of the residuals. In your case the shocks of mainly the last 3 periods have a relatively large (?, significant) negative impact on the predicted value of the  dependent variable. What this means in terms of interpretation depends on the context.

In general, AR terms introduce autocorrelation that can last for many periods until they become negligible, pure MA terms on have a short run impact (up to given lag). When both AR and MA terms are present, then it gets a bit more complicated and the best way to see the dynamic impact is to look at the impulse response function or similar.

Lagged impact of explanatory, `exog`, variables is not directly included, but could be included either by the user or as enhancement. 
The best way to understand this version of ARMAX with X is to think of a linear model (like in OLS)
`y = x b`, where the deviations from this linear relationship follow an ARMA process.

**Comment by bashtage** [comment]
Closing as answered.
