### ISSUE TITLE
SUMM: State space PRs, GSOC2015

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#2567]
A summary comment for how to merge the remaining PRs. Here are the outstanding PRs, along with their current status:

- Diagnostics (#2431) - needs unit tests
- Unobserved components (#2432) - ready to merge
- Kalman smoother (#2434) - ready to merge
- Multivariate models (#2563) - needs unit tests, example notebooks, results classes
- Postestimation (#2566) - work in progress

Here is how I think it would be ideal to merge these:

1. Merge diagnostics
2. Merge Kalman smoother
3. Merge post-estimation (I may be able to add some things that depend on the smoother)
4. Merge unobserved components (after updating notebook examples to use the above 3 PRs)
5. Merge multivariate models (after updating notebook examples to use the above 3 PRs)

**Comment by josef-pkt** [comment]
@ChadFulton  thanks for the update and summary. That's very useful.

I will be back in Montreal next week and then can look at it more systematically again. Are there any high priority questions that I should start with?

**Comment by ChadFulton** [comment]
Due to some fixes done in the post-estimation PR, the new preferred order for merging is:

1. Merge post-estimation
2. Merge Kalman smoother
3. Merge diagnostics
4. Merge unobserved components (after updating notebook examples to use the above 3 PRs)
5. Merge multivariate models (after updating notebook examples to use the above 3 PRs)

**Comment by ChadFulton** [comment]
All five of the above are now good to merge. I will work on a fix to the broken-latest-Travis issue.

**Comment by ChadFulton** [comment]
The broken test issue is fixed by #2612. I have done a test run of merging all branches locally, and there aren't any big issues (a couple of small ones of course), so I see no obstacle to merging one by one as described above; I'll rebase and fix the issues and then we can merge the next one, etc.

My opinion is that we should merge all 5 as-is, and then I will go back and do one more PR with release notes and updated notebooks, but we can do something else if preferred.

Hopefully we can get this reviewed and merged soon, as my time is rapidly disappearing.

**Comment by datnamer** [comment]
+1 Looking forward to this

**Comment by josef-pkt** [comment]
Thanks @ChadFulton 
I will start to review and merging this week. (Today is labor day in Canada.)

**Comment by ChadFulton** [comment]
These are now all merged.
