### ISSUE TITLE
BUG/DOC: incorrect name of panel hac cov_types

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2578]
see https://groups.google.com/d/msg/pystatsmodels/Cs-2mlC3C8g/J09aZHHAJQAJ

docstring says:  `'hac-groupsum'`
code uses `'nw-groupsum'`

both in linear model and in standalone cov_type modules

**Comment by huashuai** [comment]
Should we change the docstring to match the code? What else needs to be done? I can send a PR.

**Comment by josef-pkt** [comment]
fixed in #3032 allowing both kinds of name
