### ISSUE TITLE
Source build and install on OS X is only showing very few modules.

### ISSUE THREAD

**Issue by SandeepNaidu** [statsmodels/statsmodels#2579]
Steps:

I am a beginner in using Python for TSA. Had Anaconda packaged 0.6 statsmodels. Wanted SARIMAX functionality and tried building and installing it from source. Build is fine but cannot see any members in the statsmodels package which is built from python shell. The directories are however created fine.

"git clone git://github.com/statsmodels/statsmodels.git"
cd statsmodels
python setup.py build
python setup.py install

In IPython Notebook, tried the following commands

import statsmodels as sm
sm.version
Out[4]: <module 'statsmodels.version' from '/Applications/Anaconda/anaconda/lib/python2.7/site-packages/statsmodels-0.7.0-py2.7-macosx-10.5-x86_64.egg/statsmodels/version.pyc'>

sm.api
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-69e8ef0c9ee6> in <module>()
----> 1 sm.api

AttributeError: 'module' object has no attribute 'api'

sm.tsa
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-2aff8c31cd59> in <module>()
----> 1 sm.tsa

AttributeError: 'module' object has no attribute 'tsa'

**Comment by josef-pkt** [comment]
It looks like you are not using the correct imports for statsmodels

see for example http://stackoverflow.com/questions/31864749/why-cant-i-import-statsmodels-directly/31865348#31865348  and the link to the documentation

check for the patterns with an existing notebook from the documentation examples

**Comment by SandeepNaidu** [comment]
Thanks a ton josef-pkt. That did it!
