### ISSUE TITLE
BUG: need const_idx when user specifies hasconst=True

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2581]
see http://stackoverflow.com/questions/31959838/cov-type-hac-error-statsmodels-0-7-ipython-3-notebook-python-2-7-anaconda-mac

It looks like that if the user specifies `hasconst=True`, then we don't check for explicit constant.

We need `const_idx` in cases like llnull or robust F statistic.

Related: `summary()` also breaks if llnull cannot be calculated because of missing constant, at least in some cases (example current version of GAM)

**Comment by josef-pkt** [comment]
Needs checking. 
I guess this was resolved by setting llnull to nan, but I don't remember if hasconst=True has been checked or tested.

**Comment by bashtage** [comment]
This is no longer an issue in master.
