### ISSUE TITLE
ENH: tsa helper function: innovation algorithm for MA

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2593]
Similar to levinson-durbin for AR, there is an innovation algorithm to recursively compute the MA coefficients and the residual/innovations.

see Brockwell and Davis

I guess this would make good starting values for an MA process, see #1301
and, I guess, it could be used to get an empirical impulse response function.

**Comment by jbrockmendel** [comment]
Closed by #5042?

**Comment by bashtage** [comment]
Implemented in master.
