### ISSUE TITLE
Error with using a dataframe with regularized models

### ISSUE THREAD

**Issue by springcoil** [statsmodels/statsmodels#2595]
import statsmodels.api as sm 
model = sm.regression.linear_model.OLS
mod_nbin = model(train, y_train)
res = mod_nbin.fit(disp=False, maxiter = 200)
model.fit_regularized(self=res.params,alpha=0.1)

I get the following errors:

---

AttributeError                            Traceback (most recent call last)
<ipython-input-132-16e60292970b> in <module>()
      3 mod_nbin = model(train, y_train)
      4 res = mod_nbin.fit(disp=False, maxiter = 200)
----> 5 model.fit_regularized(self=res.params,alpha=0.1)

C:\Users\CoyleP\AppData\Local\Continuum\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py in fit_regularized(self, method, maxiter, alpha, L1_wt, start_params, cnvrg_tol, zero_tol, **kwargs)
    277         """
    278 
--> 279         k_exog = self.wexog.shape[1]
    280 
    281         if np.isscalar(alpha):

C:\Users\CoyleP\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\generic.py in **getattr**(self, name)
   2148                 return self[name]
   2149             raise AttributeError("'%s' object has no attribute '%s'" %
-> 2150                                  (type(self).**name**, name))
   2151 
   2152     def **setattr**(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'wexog'

**Comment by josef-pkt** [comment]
I don't understand your call to `fit_regularized`

`model.fit_regularized(self=res.params,alpha=0.1)`

Why do you use `self` as keyword?  You are calling fit_regularized on the class and not on an OLS instance.  (Interesting question is whether this ever works if we use a different model instance for `self`)

I would expect `model(train, y_train).fit_regularized(alpha=0.1)` to work,where `model` is the OLS class. (I don't remember how much I tried this.)

**Comment by josef-pkt** [comment]
Background:

Only discrete models had a fit_regularized for some time (using an interior point algorithm).

fit_regularized for OLS has been added within the last year and hasn't received much feedback yet. So, we appreciate any comments on how well (or not) it works.  
The plan is to extend the similar feature to other likelihood models in 0.8.

**Comment by springcoil** [comment]
Hi,
I would appreciate extension to other likelihood models in 0.8.
Your example worked - maybe I should submit something to the documentation.
So that people can use it more easily.
ᐧ

On Wed, Aug 19, 2015 at 4:48 PM, Josef Perktold <notifications@github.com>
wrote:

> Background:
>
> Only discrete models had a fit_regularized for some time (using an
> interior point algorithm).
>
> fit_regularized for OLS has been added within the last year and hasn't
> received much feedback yet. So, we appreciate any comments on how well (or
> not) it works.
>
> The plan is to extend the similar feature to other likelihood models in
> 0.8.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/statsmodels/statsmodels/issues/2595#issuecomment-132625089>
> .
>



-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com
