### ISSUE TITLE
Documentation for contrasts

### ISSUE THREAD

**Issue by christian-oreilly** [statsmodels/statsmodels#2613]
I think the documentation for the contrast at  statsmodels/examples/notebooks/contrasts.ipynb is either faulty or very much misleading. Lets compare with equivalent SAS doc (http://www.ats.ucla.edu/stat/sas/webbooks/reg/chapter5/sasreg5.htm). For example, lets compare the definition of the Simple contrast:

In statsmodels : "Like Treatment Coding, Simple Coding compares each level to a fixed reference level. However, with simple coding, the intercept is the grand mean of all the levels of the factors. Patsy doesn't have the Simple contrast included, but you can easily define your own contrasts. To do so, write a class that contains a code_with_intercept and a code_without_intercept method that returns a patsy.contrast.ContrastMatrix instance".  [This looks more like the definition for the Deviantion coding than the Simple coding...]

In SAS: "The results of simple coding are very similar to dummy coding in that each level is compared to the reference level. In the example below, level 4 is the reference level and the first comparison compares level 1 to level 4, the second comparison compares level 2 to level 4, and the third comparison compares level 3 to level 4."

Now, surely enough, if you look at contrast matrix given as example for the Deviant and the Simple coding in  both sources, you'll see that they are inverted in statsmodels!! In statsmodels, the Simple coding is :
[[-0.25 -0.25 -0.25]
 [ 0.75 -0.25 -0.25]
 [-0.25  0.75 -0.25]
 [-0.25 -0.25  0.75]]
where is SAS this is the Deviant coding... and vice versa.

**Comment by josef-pkt** [comment]
@jseabold @njsmith @kshedden 

(not my area, if I can avoid it.)

**Comment by christian-oreilly** [comment]
Just noted where the confusion probably came from: docs in statsmodels follows what is described for contrasts in R at: http://www.ats.ucla.edu/stat/r/library/contrast_coding.htm

Funny to see that two docs hosted both at http://www.ats.ucla.edu/stat/ for two top statistical level environments (R and SAS) show such an discrepancy between each other...!!!

**Comment by josef-pkt** [comment]
Ok, unless we have a strict preference for one or the other, then the status quo wins.

It would be useful, then, if you could add a comment to the documentation that this is not a definition or naming convention that is shared across all statistics packages.

(Eg. cloglog in R is actually loglog, and we follow the Stata definition of cloglog for GLM links)

**Comment by christian-oreilly** [comment]
Ok... with further reading it start to make sense. The key part in the SAS doc is the following paragraph 

"This page will illustrate two ways that you can conduct analyses using these coding schemes: 1) using proc glm with estimate statements to define "contrast" coefficients that specify levels of the categorical variable that are to be compared, and 2) using proc reg. When using proc reg to do contrasts, you first need to create k-1 new variables (where k is the number of levels of the categorical variable) and use these new variables as predictors in your regression model.  Method 1 uses a type of coding we will call "contrast coding" while method 2 uses a type of coding we will call "regression coding". "

R uses what SAS call "regression coding" (and not what they call "contrast coding") and StatsModels follows R approach. Further, numerically, the "Simple contrast coding" is identical to the "Deviation regression coding" and vice versa. So, although it might be a bit confusing, all docs are technically correct (as far as I can say). Thus, I must apologize for not reading thoroughly the docs before posting.  Nevertheless, I would still suggest adding a cautionary note in the introductory paragraph of the "constrat" page of StatsModels doc to warn the users that these "contrasts" are equivalent to what is defined in SAS as "regression coding" but not equivalent to what they define as "contrast coding".
