### ISSUE TITLE
ImportError: cannot import name pinv_extended

### ISSUE THREAD

**Issue by colinhiggins** [statsmodels/statsmodels#2618]
Traceback:

---

ImportError                               Traceback (most recent call last)
<ipython-input-262-6030a6549dc0> in <module>()
----> 1 import statsmodels.api as sm

/Users/colin/anaconda/lib/python2.7/site-packages/statsmodels/api.py in <module>()
      3 from . import tools
      4 from .tools.tools import add_constant, categorical
----> 5 from . import regression
      6 from .regression.linear_model import OLS, GLS, WLS, GLSAR
      7 from .regression.quantile_regression import QuantReg

/Users/colin/anaconda/lib/python2.7/site-packages/statsmodels/regression/**init**.py in <module>()
----> 1 from .linear_model import yule_walker
      2 
      3 from statsmodels import NoseWrapper as Tester
      4 test = Tester().test

/Users/colin/anaconda/lib/python2.7/site-packages/statsmodels/regression/linear_model.py in <module>()
     46 
     47 from statsmodels.compat.numpy import np_matrix_rank
---> 48 from statsmodels.tools.tools import add_constant, chain_dot, pinv_extended
     49 from statsmodels.tools.decorators import (resettable_cache,
     50                                           cache_readonly,

ImportError: cannot import name pinv_extended

---

Occurred after installing statsmodels via conda (or vai pip after uninstalling with conda) on Mac OSX 10.10.5
statsmodels 0.6.1
scipy 0.15.1
patsy 0.4.0
numpy 1.9.2
python 2.7.10

**Comment by josef-pkt** [comment]
looks like this got lost without any reply

It's old, and I don't see why there should be a import error tools.tools.pinv_extended exists in the module

closing, reopen if it shows up again
