### ISSUE TITLE
out of sample R^2

### ISSUE THREAD

**Issue by jimmyyu168** [statsmodels/statsmodels#2622]
Hi, 

For OLS in statsmodels, what's the best way to compute out of sample R^2 after doing in sample fitting by calling sm.OLS(y, X).fit()? Is there any function that I can call directly?

Thanks a lot!

Zhiming

**Comment by nickos556** [comment]
Hi very interested in this feature!

**Comment by bashtage** [comment]
There are no functions for this, but the code is straightforward and small.
