### ISSUE TITLE
ENH/BUG mosaic plot with empty cells

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2623]
e.g. add a bit of noise

https://github.com/cogstat/cogstat/commit/c90249dbad82eb7edf97a56240a400993da5376d

there was an example somewhere with mosaic plot that didn't look nice because of empty cells (stackoverflow ?)

**Comment by bashtage** [comment]
This is fixed in master in the sense that 0 values draw ok.
