### ISSUE TITLE
ENH: add scipy minimize to optimizers

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2629]
just an idea and for transition to new interface in scipy.optimize

If we add the generic `minimize`, then we get new algorithms for free, and also those that are not currently covered.
We could handle all the options through `**kwds` or `optimize_kwds`

I'm thinking of an example where we want to impose an inequality restriction that might be binding. Currently we only consider cases where domain constraints force the parameters to be in the interior via transformation.

We would also get the newer `newton` methods which are not wrapped by us.

Also for the future, we might want to think about how we can take advantage of the new least squares (and M-estimation) solvers from this years scipy GSOC.

**Comment by josef-pkt** [comment]
This might be easy because it can follow the existing pattern, but it still requires work.

**Comment by huashuai** [comment]
I would like to try this as my first PR. Something I want to clarify: my understanding is to add a new help function like `_fit_minimize` and call it from `_fit`, is that correct?

**Comment by josef-pkt** [comment]
@huashuai  Thanks that would be great.

The last optimizer that was added was basinhopping in #932

> my understanding is to add a new help function like _fit_minimize and call it from _fit, is that correct

Yes, I think that's all it takes, plus adding it to the main docstrings, and adding some unit tests. 
I haven't worked much with the new scipy minimize yet. If anything is unclear just ask, and I will try to understand the details.

It would be great to get also optimizers with constraints, but we don't have any examples for that yet.

**Comment by kshitij10496** [comment]
I would like to work on it if @huashuai is not working on it.
Ping @josef-pkt

**Comment by Inoryy** [comment]
@josef-pkt Is this ticket still relevant? If yes, then I'd like to take a jab at it.
I'm assuming the bulk of the work would be done in `statsmodels/base/model.py`?

**Comment by josef-pkt** [comment]
This is still completely open. Nobody worked on it as far as I could tell.

So picking this up would be great.
base/model.py makes the connection to the likelihoodmodels. The main module to add a new wrapper is base/optimizer.py  which would need a `_fit_minimize` I guess.

The latest extension to a scipy optimizer was basinhopping (to have a global optimizer)
https://github.com/statsmodels/statsmodels/pull/932/files
which might be useful to see the pattern for adding a scipy optimizer.

If there are questions, then I can look into it. I didn't work on the details when those were added.

Thanks

**Comment by David-Xilo** [comment]
@josef-pkt I saw that the function _fit_minimize is already done. Is this issue still open?

**Comment by josef-pkt** [comment]
@David-Xilo Thanks for pointing this out

minimize option was added in #3193
