### ISSUE TITLE
LaTeX formulas on the Time Series Filters examples notebook are not rendered

### ISSUE THREAD

**Issue by kaiminglee** [statsmodels/statsmodels#2635]
On http://statsmodels.sourceforge.net/devel/examples/notebooks/generated/tsa_filters.html the LaTeX formulas (starting from "Hodrick-Prescott Filter") are not rendered correctly. (They seem to be enclosed between [ ... ] instead of between $$ ... $$. 

The corresponding notebook on Github (https://github.com/statsmodels/statsmodels/blob/master/examples/notebooks/tsa_filters.ipynb) is correct, so it's unclear where the errors on the website came from.

**Comment by jbrockmendel** [comment]
@josef-pkt tag for docs or maybe even TeX?

**Comment by josef-pkt** [comment]
It looks like this has been fixed, the html page of the notebook looks correct.
