### ISSUE TITLE
REL: 0.6.2 compatibility fixes ?

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2671]
If we manage to do releases again, then a 0.6.2 compat-fix release for numpy and pandas comptibility and some missing python 3 compatibility would be very helpful.

We also need to backport some fixes to the (unreleased) 0.7 branch

**Comment by zepu-zhang** [comment]
I saw the latest official release is 0.6.1 from Dec 2014. 'setup.py' sets version to 0.8.0. There is nothing that I see after 0.6.1. 'pip install' knows only up to 0.6.1. Is there any plan for the next release? Lack of regular release is very negative to a library's adoption.

**Comment by bashtage** [comment]
@josef-pkt Looks close-able since 0.6.2 isn't likely to be released ever.

**Comment by josef-pkt** [comment]
@bashtage  thanks, closing
