### ISSUE TITLE
BUG statespace test failures with numpy 1.10, array contiguity

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2672]
Running current master with numpy  1.10 has some test failures that seem to be related to fortran contiguity

https://travis-ci.org/statsmodels/statsmodels/jobs/86260894

running statespace tests on my computer , I get the following

Ran 593 tests in 26.455s
FAILED (SKIP=8, errors=67, failures=2)

a large number with identical error message like this

```
======================================================================
ERROR: statsmodels.tsa.statespace.tests.test_sarimax.Test_arma_trend_ct.test_predict
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\statsmodels\tsa\statespace\tests\test_sarimax.py", line 956, in test_predict
    predict = result.predict(start=10, end=20, dynamic=10)
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\statsmodels\base\wrapper.py", line 95, in wrapper
    obj = data.wrap_output(func(results, *args, **kwargs), how)
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\statsmodels\tsa\statespace\sarimax.py", line 1948, in predict
    start=start, end=end, exog=exog, dynamic=dynamic, **kwargs
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 1900, in predict
    start, end+out_of_sample+1, dynamic, **kwargs
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\statsmodels\tsa\statespace\kalman_filter.py", line 1524, in predict
    endog, self.k_states, self.k_posdef, **model_kwargs
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\statsmodels\tsa\statespace\kalman_filter.py", line 212, in __init__
    k_endog, k_states, k_posdef, **kwargs
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\statsmodels\tsa\statespace\representation.py", line 315, in __init__
    setattr(self, name, scope[name])
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\statsmodels\tsa\statespace\representation.py", line 56, in __set__
    value = self._set_vector(obj, value, shape)
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\statsmodels\tsa\statespace\representation.py", line 80, in _set_vector
    self.name, value.shape, shape[0], obj.nobs
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\statsmodels\tsa\statespace\tools.py", line 374, in validate_vector_shape
    ' rows, got %d' % (name, nrows, shape[0]))
ValueError: Invalid dimensions for observation intercept vector: requires 21 rows, got 1
```
and these two

```
======================================================================
FAIL: statsmodels.tsa.statespace.tests.test_mlemodel.test_numpy_endog
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\
site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\
site-packages\statsmodels\tsa\statespace\tests\test_mlemodel.py", line 478, in t
est_numpy_endog
    assert_equal(endog.flags['F_CONTIGUOUS'], False)
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\
site-packages\numpy\testing\utils.py", line 354, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: True
 DESIRED: False

======================================================================
FAIL: statsmodels.tsa.statespace.tests.test_representation.test_bind
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\
site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\
site-packages\statsmodels\tsa\statespace\tests\test_representation.py", line 628
, in test_bind
    assert_raises(ValueError, lambda: mod.bind(np.asfortranarray(np.arange(10).r
eshape(10,1))))
  File "C:\Users\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\
site-packages\numpy\testing\utils.py", line 1099, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
AssertionError: ValueError not raised by <lambda>
```

**Comment by josef-pkt** [comment]
@ChadFulton  Do you have time for looking at this?

My guess is that a numpy function doesn't return the same contiguity anymore, either Fortran or C order, or whatever your code assumes. (Based on that I just discovered that column_stack is not Fortran contiguous anymore as it was in 1.6, and it looks like contiguity test fail in the above.

**Comment by ChadFulton** [comment]
I'll try to get to it this week, maybe this weekend. I'm guessing you're right, I've run into contiguity issues in the past across different Numpy versions.

**Comment by ChadFulton** [comment]
There are also BSE errors for the VAR models, and one other error:

    ======================================================================
    FAIL: statsmodels.tsa.vector_ar.tests.test_var.TestVARResults.test_irf_coefs
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/miniconda/envs/statsmodels-test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/travis/miniconda/envs/statsmodels-test/lib/python2.7/site-packages/statsmodels-0.8.0-py2.7-linux-x86_64.egg/statsmodels/tsa/vector_ar/tests/test_var.py", line 171, in test_irf_coefs
        self._check_irfs(self.irf.irfs, self.ref.irf)
      File "/home/travis/miniconda/envs/statsmodels-test/lib/python2.7/site-packages/statsmodels-0.8.0-py2.7-linux-x86_64.egg/statsmodels/tsa/vector_ar/tests/test_var.py", line 178, in _check_irfs
        assert_almost_equal(ref_irfs, res_irfs)
      File "/home/travis/miniconda/envs/statsmodels-test/lib/python2.7/site-packages/numpy/testing/utils.py", line 494, in assert_almost_equal
        return assert_array_almost_equal(actual, desired, decimal, err_msg)
      File "/home/travis/miniconda/envs/statsmodels-test/lib/python2.7/site-packages/numpy/testing/utils.py", line 886, in assert_array_almost_equal
        precision=decimal)
      File "/home/travis/miniconda/envs/statsmodels-test/lib/python2.7/site-packages/numpy/testing/utils.py", line 663, in assert_array_compare
        raise AssertionError(msg)
    AssertionError: 
    Arrays are not almost equal to 7 decimals
    (shapes (6,), (6, 3) mismatch)
     x: recarray([�?, �;�:B�ѿ](�D����������,
           ��L��������ƿC�3Y�?, O�����N;�j���8���H��,
           �N�A�������T��B;��pٿ, 9m�;_���J��...
     y: array([[ 1.       ,  0.       ,  0.       ],
           [-0.2794347, -0.100468 , -1.9709737],
           [-0.0469873, -0.1728197,  0.0436493],...
    ----------------------------------------------------------------------

**Comment by josef-pkt** [comment]
That's a numpy bug with views of recarray already fixed in numpy master. (I guess we only fix it by skipping the affected tests on this numpy version, there aren't many recarray users.)

Thanks

**Comment by jusic** [comment]
I ran also to this issue while trying to run the last SARIMAX example (Dynamic Forecasting) from `statsmodels/examples/notebooks/statespace_sarimax_stata.ipynb` with the latest master.

With the latest NumPy 0.10.1, the prediction/forecast functions fail with observation matrix size errors, but with NumPy 1.9.2 there are no problems.

**Comment by PierreBdR** [comment]
There are two problems here due to corrections made in numpy 0.10. Note that everything is consistent with the documentation much earlier, and so it was a bug in numpy:

1 - an array can be both C and F contiguous if all but one dimension is of size 1. This means that an array of shape (1,10) or (10,1) will always be both C and F contiguous. If you think about it, it makes sense. However, as this is used in the library to distinguish between 10 1-D points and 1 10-D point, we have a problem. My current solution (see #2679) is to only test if an array if F contiguous or not and ignore the C-contiguous flag. This means that for 10 1-D points, you need to always create an array of shape (1,10).
2 - the `view` method of recarray used to return an ndarray. Again, this was against what the documentation claimed. The behaviour is now consistent with the documentation and it returns a recarray. However, in a few places the `view` method is used to get an `ndarray` view ... this can be easily done by adding a second argument `np.ndarray` to the call (or the named version: `type=np.ndarray`)

I added the corrections to PR on version detection so tests pass. But we can either split them or rename the other PR.

**Comment by jseabold** [comment]
Are these failures replicable? I'm unable to replicate on OS X with conda. I see only a precision error in `test_dynamic_factor`.

```
|10040 $ conda list
# packages in environment at /Users/sseabold/.miniconda3/envs/statsmodels-dev:
#
appnope                   0.1.0                    py27_0    defaults
decorator                 4.0.4                    py27_0    defaults
ipython                   4.0.1                    py27_0    defaults
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0    defaults
nose                      1.3.7                    py27_0    defaults
numpy                     1.10.2                   py27_0    defaults
openssl                   1.0.2d                        0    defaults
pandas                    0.17.1              np110py27_0    defaults
path.py                   8.1.2                    py27_1    defaults
patsy                     0.4.0               np110py27_0    defaults
pexpect                   3.3                      py27_0    defaults
pickleshare               0.5                      py27_0    defaults
pip                       7.1.2                    py27_0    defaults
python                    2.7.11                        0    defaults
python-dateutil           2.4.2                    py27_0    defaults
python.app                1.2                      py27_4    defaults
pytz                      2015.7                   py27_0    defaults
readline                  6.2                           2    defaults
scipy                     0.16.1              np110py27_0    defaults
setuptools                19.1.1                   py27_0    defaults
simplegeneric             0.8.1                    py27_0    defaults
six                       1.10.0                   py27_0    defaults
sqlite                    3.8.4.1                       1    <unknown>
tk                        8.5.18                        0    <unknown>
traitlets                 4.0.0                    py27_0    defaults
wheel                     0.26.0                   py27_1    defaults
zlib                      1.2.8                         0    <unknown>
```

**Comment by jseabold** [comment]
Or is this fixed in master with the skips?

**Comment by josef-pkt** [comment]
No, nothing is skipped yet. 
I just ran the statespace testsuite again with numpy 1.10.1 with current and recent master and I'm seeing the nans now from #2738

Also, maybe a clue:
I get a warning that there is a shape mismatch between endog and exog, unless that's the one that #2737 fixes

```
........................................M:\josef_new\eclipse_ws\statsmodels\stat
smodels_py34_pr\statsmodels\tsa\statespace\sarimax.py:987: VisibleDeprecationWar
ning: boolean index did not match indexed array along dimension 0; dimension is
123 but corresponding boolean dimension is 112
  exog = exog[~np.isnan(endog)]
M:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\tsa\statespa
ce\sarimax.py:989: VisibleDeprecationWarning: boolean index did not match indexe
d array along dimension 0; dimension is 123 but corresponding boolean dimension
is 112
  trend_data = trend_data[~np.isnan(endog)]
```

this is before the nan testfailures which are in  statsmodels.tsa.statespace.tests.test_varmax not with sarimax.

**Comment by jseabold** [comment]
I wonder if something got fixed in `1.10.2`? I'm not fully caught up yet. 

I'm going to see if I can replicate in a container. 

I do see that warning though.

**Comment by josef-pkt** [comment]
It cannot be only a numpy 1.10.2 issue, because Chad's PR hung with 1.10.2 earlier today
https://travis-ci.org/statsmodels/statsmodels/jobs/97999777

**Comment by jseabold** [comment]
I replied to this on #2739. 

> It could even be something that's fixed in newer gcc (it could be a lot of things). The one in the default travis environment is fairly old.

**Comment by josef-pkt** [comment]
I just upgraded the python version I ran before with numpy 1.10.1 to 1.10.2 (no other changes) and all the nan failures are gone.

I have only one minor failure left in statespace, plus the warnings as before

```
======================================================================
FAIL: statsmodels.tsa.statespace.tests.test_dynamic_factor.TestDynamicFactor_ar2
_errors.test_mle
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\josef\Downloads\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\
site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "M:\josef_new\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\tsa\
statespace\tests\test_dynamic_factor.py", line 478, in test_mle
    assert_allclose(res.llf, self.results.llf, atol=1e-3)
  File "C:\Users\josef\Downloads\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\
site-packages\numpy\testing\utils.py", line 1359, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Users\josef\Downloads\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\
site-packages\numpy\testing\utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0.001

(mismatch 100.0%)
 x: array(606.6677549871745)
 y: array(607.4201043440738)
```

This might be then pretty much the end of this, if latest numpy and reasonably new Ubuntu are fine.

The question who and what caused these failures that only show up in one combination of packages and machines, but that's not really our business.

**Comment by jseabold** [comment]
There are some notes in 1.10.2 that are possibly related. I haven't kept up much with this lately.

https://github.com/numpy/numpy/blob/master/doc/release/1.10.2-notes.rst#compatibility-notes

**Comment by bashtage** [comment]
@josef-pkt I think this is fixed now.

**Comment by josef-pkt** [comment]
The problem did not show up anymore. We can open a new issue if there are still some version combinations that cause problems.

closing
