### ISSUE TITLE
Wrong return value for statsmodels.tsa.stattools.levinson_durbin

### ISSUE THREAD

**Issue by andreavicere** [statsmodels/statsmodels#2700]
The documentation states that the last column of the return value phi contains the AR estimates with added a leading 1.
However, in the code one reads, before the return
    pacf_[0] = 1.
so it seems that a leading 1 has been placed in the wrong variable.
As a check, the entry phi[:,-1] results identically zero.

**Comment by josef-pkt** [comment]
I need to look at the actual results. I thought this has enough test coverage that it should be correct, unless it's in a part that we don't use.

Do you have a runnable example so I don't have to find one?

**Comment by josef-pkt** [comment]
AFAICS, there is no test coverage for this. Only pacf seems to be used from levinson_durbin.
So bug is very likely.

I think `pacf_[0] = 1.`  is correct because the 1 is for lag 0.

I'm not sure or don't remember about the phi.

**Comment by andreavicere** [comment]
Sorry, I will provide a test example as soon as possible; I need to extract a runnable piece of code from a larger project, and I cannot right now.
However, it seems reasonable to have a leading 1 also in phi[:,-1], as stated in the documentation, since this is a column returning the final AR coefficients, and this would make them readily usable in scipy.signal.lfilter, which wants the leading 1.

**Comment by andreavicere** [comment]
A correction; actually the phi coefficients would have to be negated, before inserting a leading 1, if they were to be used as AR coefficients in filtering; I promise, I will provide an example, don't spend time on this before I send one!

**Comment by josef-pkt** [comment]
It will be possible to just use a sample dataset or test case for something else for this.

One thing that we have to watch out for with ar coefficients is whether they are left side or right side, i.e. if they should be the negative if we add them to the lag polynomial for lfilter.
We use both ar lag polynomial and ar_coeffs with  `ar = [1, - ar_coeffs]` when we switch representation in various models and helper functions.

**Comment by josef-pkt** [comment]
simultaneous comments :)

**Comment by andreavicere** [comment]
Correct, the phi parameters appear to be RHS, and adding a leading 1 would be inconsistent, whereas adding a leading -1 would make things even more confusing for the end user!
Perhaps the cleanest solution is to fix the documentation about the return value phi. But again, I'll send an example tomorrow, after meeting my deadline.

**Comment by josef-pkt** [comment]
As a test case Yule-Walker and levinson_durbin should give the same arcoeffs, except for numerical noise, e.g. `class TestPACF(CheckCorrGram):` for pacf.

**Comment by josef-pkt** [comment]
check for 0.9. this issue didn't have labels and got lost
