### ISSUE TITLE
plot_acf and plot_pacf strange behavior subplot

### ISSUE THREAD

**Issue by mmngreco** [statsmodels/statsmodels#2703]
Plotting with plot_acf returns a duplicate acf:
![plot_acf](http://i.imgur.com/VlIom79.png)

But If I store in a variable works correctly:
![](http://imgur.com/jNN3quE.png)

## Here gist for context:
https://gist.github.com/mmngreco/db9f6df0629346aba806

**Comment by PierreBdR** [comment]
This is an issue with IPython, not statsmodels. And there is nothing we can do. Try this in your notebook:

```
%pylab inline
f = figure()
plot([1,2,3])
f
```

You will see the figure twice. As soon as the last element of a block evaluate to a figure, IPython will show that figure. But as soon as a figure is created in a block, it will also show that figure. So if both are true, the figure will be shown twice!

**Comment by mmngreco** [comment]
Yes, I tried run the script and works the same way... so thanks for the reply. :+1:  :-)

**Comment by josef-pkt** [comment]
All our plot functions are supposed to return the figure instance, which causes this as Pierre explained.
A common workaround if the plot function is last in a cell, is to assign to a name or to nothing, 
`_ = plot_acf(...)`
