### ISSUE TITLE
Problems in python combining the libraries datetime, pyplot and statsmodels

### ISSUE THREAD

**Issue by ghost** [statsmodels/statsmodels#2709]
I have a strange problem using datetime in some plots when I import statsmodels. The first plot in the code is working fine, but something goes wrong if I try to plot again after importing statsmodels althoug I don't use it.

It seems that the second plot use the data until the day and doesn't takes into account the hours. Am I doing something wrong or it is a bug? How can I solve this?

Thank You.

``` python
import matplotlib.pyplot as plt
import datetime

y=[datetime.datetime(2015,11,19,18,0,0),datetime.datetime(2015,11,19,19,0,0)]
plt.plot(y)
plt.show()

import statsmodels.api as smapi

plt.plot(y)
plt.show()
```

Thes first plot is: 
![firstcase](https://cloud.githubusercontent.com/assets/15923911/11297192/11cbdffa-8f77-11e5-9006-8a752b7a574b.png)

And the second one:
![secondcase](https://cloud.githubusercontent.com/assets/15923911/11297196/1a93b518-8f77-11e5-8bb2-26504465df68.png)

**Comment by josef-pkt** [comment]
Seems to work correctly with recent (not latest mpl) versions
