### ISSUE TITLE
use httplib2 for caching downloaded data files ?

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#272]
Skipper recommended https://groups.google.com/group/pystatsmodels/browse_thread/thread/5bfe1e45b3336765?hl=en

http://pypi.python.org/pypi/httplib2/

80,000 downloads looks pretty good

**Comment by jbrockmendel** [comment]
I’ve seen requests_cache used for this recently.

**Comment by bashtage** [comment]
Downloaded data files are cached.
