### ISSUE TITLE
Wrap outlier Test to make it consistent to outliertest in car (R package)

### ISSUE THREAD

**Issue by decisionstats** [statsmodels/statsmodels#2727]
FEATURE REQUEST 

consider doing this

def outlierTest(x):
    outl=x.outlier_test()
    print (outl.loc[outl['bonf(p)'] != 1])

where x is <statsmodels.regression.linear_model.RegressionResultsWrapper> created by 

import statsmodels.formula.api as sm
result = sm.ols(formula="medv ~ crim + zn + nox + ptratio + black + rm ", data=boston).fit()

Basically as a modeller I just want to see what outliers are so I can either delete them or make them into a new dataset to model differently

**Comment by josef-pkt** [comment]
(issue got lost because of missing labels)

It should be possible to get the index if the returns are not sorted, i.e. `order=False`

(However, looking at the code, I think there is a bug or order=False and the original pandas index is available. AFAICS the data is sorted but not the pandas index.)

**Comment by josef-pkt** [comment]
I added a cutoff option in #3971, however we to differences to car outlierTest
It defaults to None, which means all observations are returned. (which also makes it backwards compatible)
Also, the return will be empty if there are no observations below the cutoff.
https://www.rdocumentation.org/packages/car/versions/2.1-6/topics/outlierTest

the options are now available in the OLSResults method
