### ISSUE TITLE
Simpler way for multicollinearity checking

### ISSUE THREAD

**Issue by decisionstats** [statsmodels/statsmodels#2728]
Given a model given by a few variables

In [6]:

import statsmodels.formula.api as sm

import statsmodels.formula.api as sm
​
In [7]:

result = sm.ols(formula="medv ~ crim + zn + nox + ptratio + black + rm ", data=boston).fit()

result = sm.ols(formula="medv ~ crim + zn + nox + ptratio + black + rm ", data=boston).fit()
​
In [12]:

result
Out[12]:
<statsmodels.regression.linear_model.RegressionResultsWrapper at 0xaaf1db6c>

How can i make a function vif(result) such that i get the same results as from car (R package) that gives me the variance inflation factor for each variable ( thus telling me which variable to drop for multicollinearity)

**Comment by davidwarshaw** [comment]
VIF is calculated by auxiliary regression, so not dependent on the actual fit. IMHO, diagnostics like this are a good motivation for breaking out the design matrix.
See below:
```
from patsy import dmatrices
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

# Break into left and right hand side; y and X
y, X = dmatrices(formula="medv ~ crim + zn + nox + ptratio + black + rm ", data=boston, return_type="dataframe")

# For each Xi, calculate VIF
vif = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

# Fit X to y
result = sm.OLS(y, X).fit()
```

**Comment by josef-pkt** [comment]
@davidwarshaw 
You can also just reuse the `exog` of the model, which has the advantage of keeping the formula information inside the model.
But if you suspect problems, then using dmatrices initially and fix any multicollinearity problems beforehand, and then use the corrected formula in the model, is a good approach.

(The formula information is used in a few places like predict and t_test/wald_test, and the plan is to provide more automatic support based on the formula information in future.)

**Comment by shamim-io** [comment]
Can you give a code sample for the same?

**Comment by v-bhardwaj** [comment]
Hello,

Could you please elaborate on how to Check multicollinearity among independent variables in data in jupyter python . 
i have a clean data set but before applying any model, i want to remove the variables having high collinearity among them .

**Comment by PriyatamNayak** [comment]
any update??
