### ISSUE TITLE
statsmodels.formula.api.logit raises error very hard to debug for newbies

### ISSUE THREAD

**Issue by freeseek** [statsmodels/statsmodels#2733]
**edit:**
related issues
#878 bool in OLS  (uninformative exception)
#2181 bool in GLM-Binomial

(reverse direction 1-0 if boolean, not possible to fix in backwards compatible way)
We also have patsy issues for fixing this more systematically (don't convert endog) that I don't find right now.

**edit** 
similar things happens in GLM binomial with string categories, except that it doesn't raise an exception and just interprets the 2-D endog as counts.
It even seems to work with more than 2 categories interpreted as first-versus-rest binary.
https://stackoverflow.com/questions/48312979/how-does-statsmodels-encode-endog-variables-entered-as-strings/48314666#48314666

original:

---

The following code:

```
import pandas as pd, numpy as np, statsmodels.formula.api as smf
df = pd.DataFrame(np.random.randn(1000,2), columns=list('AB'))
df['C'] = ((df['B'] > 0)*1).apply(str)
lmf = smf.logit('C ~ A', df).fit()
```

Gives the following error:

> ValueError: operands could not be broadcast together with shapes (1000,2) (1000,) 

As shown in a couple of stackoverflow instances:

[http://stackoverflow.com/questions/22716521/](http://stackoverflow.com/questions/22716521/)
[http://stackoverflow.com/questions/30314188/](http://stackoverflow.com/questions/30314188/)

This error is very hard to debug for newbies. The issue is that the response variable is not numerical. If this was caught in the code of the function statsmodels.formula.api.logit and a proper error reported, it would save people a lot of time debugging their code and getting to the right fix for their code, which could look something like this:

```
df.replace(to_replace={'C' : {'1': 1, '0': 0}}, inplace = True)
lmf = smf.logit('C ~ A', df).fit()
```

**Comment by josef-pkt** [comment]
I added prio-high to get a solution in soon.

patsy provides now more information about categorical encoding but that is only for the design matrix exog. The only information about the endog is in the name of the orig_exog and ynames in `.data`.
Given that it currently raises an exception, we don't have backwards compatibility problems in contrast to GLM-Binomial.

I think we can do string matching on the ynames for "[0]" and "[1]" to detect boolean conversion and fix it directly in discrete BinaryModel both for Logit and Probit.

```
mod.data.orig_endog.columns
Index(['C[0]', 'C[1]'], dtype='object')

mod.data.ynames
['C[0]', 'C[1]']
```

I didn't look at the actual code yet.

Other categoricals are more ambiguous, and I'm not sure we want a convention, e.g. always use second as "1" or raise an exception in all other cases than yname endswith "[0]" and "[1]".

**Comment by josef-pkt** [comment]
related #2601 and maybe others

**Comment by Irene-GM** [comment]
This same error also happens using the `seasonal_decomposition` function for time-series analysis. The array `vegetation` is an array of 108 rows and 34 columns of type float64. They represent the vegetation index in 34 locations in a monthly-basis between 2006 and 2014.  

```
init_date = datetime.datetime(2006, 1, 1)
vegetation = np.array(lveg)[:,1:109].T
print(vegetation.dtype) # This prints type float64
df = pd.DataFrame(vegetation)
df.index = pd.DatetimeIndex(freq="m", start=init_date, periods=108)
res = sm.tsa.seasonal_decompose(df)
```

The execution of this `sm.tsa.seasonal_decompose(df)` line, produces the following error that I dont know how to solve, even with the hint provided in this same thread:


```
Traceback (most recent call last):
  File "M:/Documents/workspace/Algorithms/TimeSeries/test_signal_decomposition.py", line 43, in <module>
    res = sm.tsa.seasonal_decompose(df)
  File "C:\Python34\lib\site-packages\statsmodels\tsa\seasonal.py", line 108, in seasonal_decompose
    resid = detrended - seasonal
ValueError: operands could not be broadcast together with shapes (108,34) (108,) 

Process finished with exit code 1
```

Any clue on why is this happening?

**Comment by josef-pkt** [comment]
@Irene-GM  I think the function works only for 1-dimensional data. All the unit test cases are 1-D.Try to loop over the 34 columns.
Based on briefly browsing the code, I think the function can be made to work for 2-D, however the default broadcasting is on rows, i.e a pure numpy input might currently work if it's 2-D but transposed. If that works it should not be supported because the default should be axis=0.
(I'm a bit surprised it doesn't raise earlier)

This is not related to the issue in the description here and should be a new issue.

**Comment by Irene-GM** [comment]
@josef-pkt Thanks for your quick response! I opened [a new issue here](https://github.com/statsmodels/statsmodels/issues/2821) to avoid messing up threads.

**Comment by josef-pkt** [comment]
To this issue:
The easiest would be to raise immediately an exception if endog is 2d in `disctete_model.BinaryModel.__init__`.

For most users it would work using `endog[:, -1]` or `1 - endog[:,0]` for the binary models if endog is 2-d. This would work for Boolean, or any other things like strings that are like 0, 1, but would be just a convention for general string labels where the highest (alphabetical or whatever patsy uses) level would be the modeled "success" and the lowest level the reference case.
Based on a brief check (*) MNLogit also uses the first level as reference case.
(*) I don't see it in the docstring.
MNLogit use tools.categorical for the conversion which uses np.unique (alphabetical or natural sorting I guess).

```
>>> df['C2'] = ((df['B'] > 0)*1).apply(str).map({'0':'fail', '1':'success'})
>>> mod2 = smf.logit('C2 ~ A', df)
>>> mod2.data.orig_endog
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 2 columns):
C2[fail]       1000  non-null values
C2[success]    1000  non-null values
dtypes: float64(2)

>>> mod2.data.frame
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 4 columns):
A     1000  non-null values
B     1000  non-null values
C     1000  non-null values
C2    1000  non-null values
dtypes: float64(2), object(2)

>>> mod2.endog_names
['C2[fail]', 'C2[success]']
```

**Comment by josef-pkt** [comment]
Note: for fixing up `model.endog_names` which is the same as `model.data.ynames`

```
>>> mod2.endog_names is mod2.data.ynames
True
```

**Comment by josef-pkt** [comment]
OK, current suggestion:

in discrete `BinaryModel.__init__` we fix endog and endog names with second column, and raise if it has more than 2 columns. (We don't support one against all others. Users can create a binary endog if they want that.)

I also just saw #837 for MNLogit reference category.

**Comment by josef-pkt** [comment]
postponed to 0.10
status-quo wins for another release over breaking backwards-compatibility without enough certainty.
