### ISSUE TITLE
BUG/ENH:  proportions_ztest  with 2d count 

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2734]
count with two values is interpreted as two sample test
According to the docstring nobs needs to be of the same shape as count, but it's not checked and return incorrect results if nobs is scalar.
There is one sum in the calculation that calculates the pooled variance which requires that nobs has full length.

Also, there is no asarray for count and nobs and it raises an exception if they are lists.

ENH: this only allows pooled variance, not a constrained mle variance (if value != zero).

ENH: we could vectorize this, I think, which would be useful for sample size or power calculations.

**Comment by dhpiyush** [comment]
@josef-pkt So it should raise error if the shape of count is not equal to nobs ??

**Comment by josef-pkt** [comment]
No, I think if nobs is scalar, then we assume that it's the same nobs for all counts, and expand.

**Comment by josef-pkt** [comment]
bug/problems fixed by #3058  for 0.8

new issue #3720 for enhancement ideas
