### ISSUE TITLE
correlate() got an unexpected keyword argument 'old behavior': Auto Regressive (AR) model using Maximum Likelihood Estimator in pandas dataframe: 

### ISSUE THREAD

**Issue by lmsanch** [statsmodels/statsmodels#2736]
I have a subset of a pandas dataframe that contains a time series I want to analyze with an AR or ARIMA model using statsmodel:

    data_sci = H_Clinton_social_vector.Florida

The data looks like this:   

    Date
        2015-09-28     587
        2015-10-05     582
        2015-10-12     606
        2015-10-19     698

My AR model is created like this, aggregating the time series on a weekly basis:
 
    ar_model = sm.tsa.AR(data_sci, freq='W')
    ar_model
    <statsmodels.tsa.ar_model.AR at 0x1178f5490>

Next, I want to do a Maximum Likelihood Estimator (MLE) fit of the AR parameters, with a half year lag:

    ar_res = ar_model.fit(maxlag=26, method='mle')

I get the following results:

    correlate() got an unexpected keyword argument 'old behavior'

I don't understand what the problem is, which I assume is related to the auto correlation of the data, due the correlate() argument. There is high autocorrelation in my data so this should be ok.

[![autocorrelation of dataset][1]][1]

I am not very familiar with stasmodels, and prefer avoding coding an AR or ARIMA model from scratch. My statsmodel is 0.6.1. and numpy is 1.10.1

  [1]: http://i.stack.imgur.com/mUBgr.png

**Comment by josef-pkt** [comment]
Can you upgrade to statsmodels master?

There are some compatibility problems with numpy 1.10, most of which have been fixed in master a short time ago. (There is still one problem left but that's in code that wasn't part of statsmodels 0.6, and we haven't yet found the source of the problem.)

**Comment by lmsanch** [comment]
Thank you. Problem solved and step by step solution documented here: http://stackoverflow.com/questions/34377683/auto-regressive-ar-model-using-maximum-likelihood-estimator-in-pandas-datafram/34387031#34387031
