### ISSUE TITLE
Clarify conditional vs. maximum likelihood in AR/ARMA

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#274]
Now conditional and maximum likelihood refers to the estimation procedure. However, it should also apply to the intended model given exogenous variables (even in the case of constant-only exog). When we specify exogenous variables now for an "ARMAX" model we are estimating a regression model with ARMA errors. Ie.,

```
L(phi)(y _t- X_tB) = L(thetai)e_t
```

or

```
Y_t = X_tB + mu_t
L(phi)mu_t = L(theta)e_t
```

This is true whether or not the mode was estimated with exact or conditional MLE. However, it is more correct when we specify a conditional model to mean that we are modeling the conditional mean of y_t given its own past. Assuming that the conditional mean can be described as linear combination of exogenous variables, this is

```
L(phi)y_t = X_tB + L(theta)e_t
```

Right now, for a constant only, you can go back and forth between the two models, by taking the mean of the model and multiplying the conditional constant by 1 - sum(arparam). E.g.

``` python
from statsmodels.datasets.macrodata import load
from statsmodels.tsa.arima_model import ARMA

cpi = load().data['cpi'].diff()

# conditional MLE with a constant
# the constant parameter is actually the 'exact MLE' definition of the mean given above
res = ARMA(cpi).fit(order=(4,1, method='css')

# get the condtional MLE mean
res.params[0] * (1 - res.arparams.sum())
```

This is, however, just a special case and is can't work for exog != 1.

**Comment by bashtage** [comment]
AR and ARMA are both deprecated.
