### ISSUE TITLE
SUMM/ENH: migrate pandas stats models

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2745]
see also #2302 for MovingOLS

The models in pandas.stats have now been deprecated. https://github.com/pydata/pandas/issues/6077

We should add some things in statsmodels and check that we have roughly the same functionality
- fama_macbeth: there is no equivalent in statsmodels, example and test case is in pandas issue
  https://github.com/pydata/pandas/issues/6077#issuecomment-34592683
  I guess we can initially move it largely the way it is, get it to work, and refactor later if we want a more generic solution. (IIRC, I have seen similar models in other contexts.)
- OLS obsolete, I guess we have already everything covered (and more than pandas)
- Moving/Rolling and Expanding OLS:  I haven't looked in a long time. 
  Ignore and let users use generic rolling methods, or write specific code?  
- Panel data: AFAIR, pandas only has fixed effects, which is just OLS with dummies (e.g. use patsy). 
  We have open issues to concentrate out the fixed effects dummies #2568, see also #2710 (sparse matrices)
  Panel robust covariance matrices need some cleanup, independently of this.
  Econometrics panel data support with two random effects is in PR. #1133
  MixedLM has more general mixed effects structure that also covers now crossed effects.
- VAR: I guess it's covered by VAR in statsmodels, but I never compared.

Not clear: missing value handling, balanced panel structure, there might be some details or options that don't work the same way.

**Comment by RedPandaHat** [comment]
If I might throw in a vote -- we use rolling OLS a great deal, and it would be helpful to still have this available via a simple function call.

**Comment by josef-pkt** [comment]
@RedPandaHat   votes and usecases are useful for the design.
AFAIU, the simplest case would just be a loop using pandas rolling_apply. 

My two main design question (I haven't looked yet), are

- what do we need to keep from each regression.
- how much special code should we add to speed up the calculations.

and related to speed:
- some faster methods will be numerically less stable than the full OLS estimate in each window.
  Is trading off numerical precision in "not nice" problems for increase speed worth the effort?

related design for recursive (expanding) ols using the new statespace models is also still a bit open #2830

**Comment by cycourtot** [comment]
@josef-pkt I also agree with @RedPandaHat I use the rolling OLS quite a lot. I couldn't get rolling_apply to work for some reasons. (It felt like it was applying the function to each columns of my DF independently).

**Comment by Liam3851** [comment]
Adding another vote. pandas' implementation doesn't appear at a glance to incredibly optimized (much of the rolling code is in Python, not Cython, for example), but nonetheless the rolling implementation is about 50x faster than running the individual regressions in statsmodels currently.
