### ISSUE TITLE
SARIMAX model order identification not possible

### ISSUE THREAD

**Issue by eduedix** [statsmodels/statsmodels#2757]
Can you please clarify the following situation? I am trying to build a model with SARIMAX including exog variables and having difficulties to determine the orders as I do not have access to regression errors.

For a SARIMAX model, the linear regression errors from endog vs exog are fit to SARIMA order&seasonal_order. My question is, how can the user know which model orders to fit without being able to access these regression errors and plotting their ACF etc?

I could not find an explanation to this problem in the following example.
https://github.com/statsmodels/statsmodels/blob/master/examples/notebooks/statespace_sarimax_stata.ipynb

Thanks in advance.

**Comment by ChadFulton** [comment]
I would typically use a regular OLS regression and then perform ACF etc. on the residuals. Does that work for you or is there some other issue that I'm missing?

**Comment by eduedix** [comment]
That is what i tried, too. But it seems I am missing something.

Example:
The following works well and model_resid parameters can be estimated fine with MLE.
```
res = sm.OLS(df_scaled['power'], df_scaled[['air_temperature', 'humidity', 'sun_angle', 'cloudiness']]).fit()
model_resid = sm.tsa.statespace.SARIMAX(res.resid, order=(2,1,1), seasonal_order=(0,1,1,24)).fit(disp=0)
```

In theory the code above and below should do the same thing, but the following model cannot be estimated due to `Maximum Likelihood optimization failed to converge. Check mle_retvals`.  
```
model = sm.tsa.statespace.SARIMAX(df_scaled['power'], exog=df_scaled[['air_temperature', 'humidity', 'cloudiness', 'sun_angle']], order=(2, 1, 1), seasonal_order=(0,1,1,24)).fit(disp=0)
```

Why don't they produce similar results?

Thanks again.

**Comment by ChadFulton** [comment]
Those models are not equivalent. Since you have a integrated time series you likely have a spurious regression in the first stage if you use OLS without controlling for the trending nature of the series / errors.

You may want to check to see why the optimization didn't converge, e.g.

```
print model.mle_retvals
```

If the model simply needs more iterations, then you can use `fit(disp=0, maxiter=1000)` (or whatever number of iterations is required). If the likelihood is flat or the optimizer isn't making good progress, you may want to re-evaluate the model you're using.

**Comment by ChadFulton** [comment]
What I had meant earlier was that in some cases you can use the ACF etc. of the residuals to think about the model order, etc. for the SARIMA component, not that you can split the actual parameter estimation into two steps. I don't know if this is a valid approach with trending series though. In this case, you may be better off doing model selection with information criteria.

**Comment by josef-pkt** [comment]
information criteria are good for model selection, but you can still look at acf and pacf of the differenced or detrended series. If there is overdifferencing, then the corresponding lag, one or seasonal, will have a negative correlation.

I'm not sure what happens, when we difference both seasonal and lag 1. I never looked at the process that this implies.

**Comment by eduedix** [comment]
Thanks for clarifications. :+1:
