### ISSUE TITLE
BUG/ENH: Statespace: Simulation / impulse response functions with time-varying state space matrices.

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#2760]
Currently the `simulate` and `impulse_responses` response functions for state space models are not very helpful when there are time-varying system matrices because they always start the simulation / IRF using the time zero matrices (but confusingly also requires specifying new time-varying matrices also).

The starting point for fixing this will be to add a `start` argument dictating the time-point from which the simulation / impulse response begins, and the logic for when additional time-varying matrices are required will then need to take that into account.

**Comment by ngaurav** [comment]
Hi, I would like to work on this.

I need a little help regarding the documentation. I used the makefile in the docs folder to generate the docs. Here is a screenshot of statespace module documentation.
<img width="804" alt="screen shot 2016-02-06 at 4 20 46 pm" src="https://cloud.githubusercontent.com/assets/12483343/12866260/24e26032-ccee-11e5-848f-071844eaf9ae.png"> 
As you can see the markup is not rendered, may I request you to tell me how to generate a well rendered documentation. Using web inspector, I found that those lines are inside <span class="math"></span>. I guess that some javascript file(probably jsMath) is used to render that markup language. It will be best if you can give some links to use the library which renders this markup language.

**Comment by ngaurav** [comment]
Hi @ChadFulton ,

Actually latex was not installed on my local machine. So I just changed the sphinx math extension from pngmath to mathjax and the rendering issue disappeared. Everything is fine now.

**Comment by ChadFulton** [comment]
Hi, apologies for the delay, it would be great to get some help with this! It sounds like you have the documentation working now, but let me know if you have questions about the state space package, etc.
