### ISSUE TITLE
ENH: Statespace: New / improved Kalman filter, smoother, simulation smoother

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#2761]
Currently the state space library in Statsmodels has a Cython-based conventional Kalman filter and a pure-python conventional Kalman smoother. This issue collects notes about integrating the following features (references to DK refer to Durbin and Koopman, 2012); all features are in Cython:

- State smoother (DK 4.4)
- Disturbance smoother (DK 4.5)
- Simulation smoother (DK 4.9)
- Univariate treatment for all of the above (Kalman filter, state smoother, disturbance smoother, and simulation smoother) (DK 6.4)
- Collapsed treatment, used with large observation vectors, for all of the above (DK 6.5)

These features have already been written and can be found at https://github.com/dismalpy/dismalpy/tree/master/dismalpy/ssm in the Cython files. I have a working paper describing the use of the state space library when these features are available which can be found at http://pages.uoregon.edu/cfulton/files/fulton_dismalpy_2015.pdf; essentially the plan would be to Find/Replace "DismalPy" with "Statsmodels" once these changes are integrated.

Benefits include:

- Allows multivariate models with many (hundreds) endog variables (univariate and/or collapsed approaches)
- Allows fast simulation of or sampling from any state space time series process (simulation smoother)
- Required for possible future implementations of EM algorithm (fast smoother)
- Required for possible future implementation of analytic score (fast smoother)
- Required for some types of Bayesian estimation like Gibbs sampling (simulation smoother)

There are a couple of challenges that will have to be dealt with:

- Dependencies: these features require a more recent Scipy than is required by Statsmodels generally, so these won't (immediately) replace the existing state space code but will have to reside alongside it.
- Build process: right now these libraries use custom Cython definitions for the Fortran BLAS/LAPACK functions, but recently Scipy incorporated all of these definitions into the main package (https://github.com/scipy/scipy/pull/4021), so it might be nice for future maintenance to use theirs as long as Scipy 0.16.0 could be used as the base dependency.

These would probably be integrated slowly and across several PRs so that each step could be well-tested.

**Comment by josef-pkt** [comment]
sounds good, 
reminder: You can add Labels to issues and PRs now.

As I mentioned before: I don't have problems with adding features that require a more recent scipy, but if it's too new, then we need to have it optional.
Maintaining two (or three versions) in cython for some years might be burdensome. When you open the PRs you can decide or we can discuss what the best way is to add the new features without dropping the existing ones for older scipy versions.

BTW: If you haven't seen it yet. The latest Lapack version dropped some functions but they have a transitional compatibility layer in scipy, AFAIU.
