### ISSUE TITLE
ENH: Statespace: Allow missing data with Kalman smoother

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#2768]
Currently the pure-python Kalman smoother does not allow missing data in `endog`, though the Kalman filter does allow it.

(Aside: the Kalman smoother proposed in #2761 would already allow for missing data, but that won't be incorporated for a while and in any case it won't be fully compatible across all supported Statsmodels versions)

**Comment by josef-pkt** [comment]
@ChadFulton  general tip: when you fix a bug, then you can close the issue automatically by using `closes #xxxx` in the commit message. This also provides automatic linking of the issue to the relevant commit.
