### ISSUE TITLE
ENH: Automatic lag selection in KPSS test

### ISSUE THREAD

**Issue by N-Wouda** [statsmodels/statsmodels#2781]
As per #2775 and #2749, the number of lags to be used for the test are currently either set by the user, or selected by a rule of thumb (Schwert, 1989). `adfuller` has the option to select them via an information criterion, maybe we should allow something similar in `kpss` as well?

The current warning message for an out-of-bounds p-value is displayed only once (Python default), and is of type `UserWarning`. Should we set it to be raised every time instead? What would be an appropriate warning type?

Leaving this here for future reference, as discussed in the PRs.

**Comment by josef-pkt** [comment]
Do you know of references about which method is recommended or usually used for automatic lag selection?

AFAIU:
Because lag is only used for the HAC Newey/West variance estimation, this will be different from what is currently in `autolag` used by adfuller which selects the AR lag in a regression.

**Comment by N-Wouda** [comment]
Not sure is this is very useful, but this provides a lot of references that may be worth looking into when I find the time for it: [stats.SE](http://stats.stackexchange.com/questions/174149/how-to-determine-the-appropriate-number-of-lags-when-using-newey-west-or-hac-s).

**Comment by JimVaranelli** [comment]
@josef-pkt - I enjoyed the White + Zivot-Andrews project so was looking for some bite-sized open issues and this one caught my eye. I can provide an implementation for the Hobijn (Newey-West/Andrews) auto bandwidth method if there is interest here. It has been verified against SAS 9.3 and I can provide a number of test cases.

Hobijn, B., Frances, B.H., and Ooms, M. (2004). Generalizations of the KPSS-test for stationarity. Statistica Neerlandica, 52: 483-502.

**Comment by JimVaranelli** [comment]
This was a straightforward enhancement I will submit a PR in the next day or two. As an example of why this is important, I attached a chart showing the finite-sample (<200 obs) size distortion using both the Schwert rule-of-thumb and the Hobijn autolag method. While the Hobijn method still shows significant size distortion it is significantly better than the Schwert method. Unfortunately KPSS test is not well-behaved at very small samples (<50 obs) where a lot of our models reside. As a matter of fact, the size distortion at 25 samples is still 15% with no lags...and as the chart shows, size distortion is almost 100% using Schwert at 25 samples!

![kpsslags](https://user-images.githubusercontent.com/39306965/53500669-cd845880-3a78-11e9-9fba-d451a7ac6f06.png)

**Comment by JimVaranelli** [comment]
Please see implementation at my github: https://github.com/JimVaranelli/KPSS-autolag. It uses 5 unit tests from the statsmodels.datasets which were verified against SAS 9.3.

**Comment by JimVaranelli** [comment]
Submitted PR: https://github.com/statsmodels/statsmodels/pull/5522
