### ISSUE TITLE
ISLR Datasets

### ISSUE THREAD

**Issue by AlJohri** [statsmodels/statsmodels#2792]
I was unable to load some of the ISLR ([An Introduction to Statistical Learning with Applications in R](http://www-bcf.usc.edu/~gareth/ISL/) by Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani) datasets.

https://cran.r-project.org/web/packages/ISLR/ISLR.pdf

This is the code I attempted to use:

```
sm.datasets.get_rdataset("Wage", "ISLR").data
```

Am I misunderstanding the `get_rdataset` command?

**Comment by josef-pkt** [comment]
It looks like the ISLR datasets are not included.

statsmodels only has the download function. 
You need to file an issue with the repo of  @vincentarelbundock to include ISLR datasets
https://github.com/vincentarelbundock/Rdatasets

I'm closing this because there is nothing we can do.
