### ISSUE TITLE
How do I set the regularization parameter in AdditiveModel?

### ISSUE THREAD

**Issue by alichaudry** [statsmodels/statsmodels#2808]
After fitting a `sm.sandbox.gam.AdditiveModel` on a medium-sized dataset (8000 samples x 47 features), I'm getting some really funny results. All my `results.offset` and `results.mu` items are on the (insane) order of e+145. To be precise, between the order of e+120 to e+151.

I'm wondering whether this is because of an unconstrained optimization, because I don't remember ever specifying the regularization parameter lambda (or C = 1/lambda). Is this not part of the build yet, or is something else the problem?

As a side-note, I'm able to run very simple datasets through the GAM and they work as they should. (150 samples x 2-3 features; randomly generated.)

**Comment by josef-pkt** [comment]
The gam in the sandbox is an ancient version that doesn't have all the pieces for GAM (no splines at the time), and I only fixed it a bit before knowing much about GAM.

The new version is in #2744 but still has some problems and will be merged in the near future.

patsy has splines that can be used in formulas in case you can work with unpenalized splines and restricting the number of knots.

**Comment by alichaudry** [comment]
I see. TBH, I don't have much experience with GAMs either. I do know they work well on the kind of data I have, so I wanted to give them a shot.

If I read you correctly, you're saying that GAMs don't come with a regularization parameter? I don't see any lambda or C regularization in #2744.  

I'll try #2744 and see if that works. What class here corresponds to `AdditiveModel` from the old sandbox?

**Comment by alichaudry** [comment]
Actually, I think I see it. It's the `alpha` parameter, right? That controls the regularization? In class `GLMGam`.

If this is true, where would I choose the smoother from?
