### ISSUE TITLE
BUG missing, incorrect documentation

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2810]
checking the doc build (I didn't build the notebooks)

some errors in python examples
- [x] https://github.com/statsmodels/statsmodels/blob/master/docs/source/statespace.rst seems to be missing several new models @ChadFulton 
- [ ] ...  to be found

errors during sphinx build
- contingency tables
- ??? (list is on other computer)

**Comment by ChadFulton** [comment]
Yes! I plan to get to this soon and also I think the statespace notebooks are not up to date (maybe even broken in parts).

**Comment by josef-pkt** [comment]
http://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.RegressionResults.get_prediction.html  no returns parameters sections

**Comment by josef-pkt** [comment]
MixedLM has a large number of convergence warnings
http://www.statsmodels.org/dev/examples/notebooks/generated/mixed_lm_example.html

@kshedden Are those warnings expected, internal, does the user need to see them?

**Comment by kshedden** [comment]
#2832 addresses the convergence warnings.

**Comment by bashtage** [comment]
Seems to be fixed.
