### ISSUE TITLE
REF: move PCA to a new `multivariate` folder

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2819]
PCA is a full model version, and is traditional categorized under `multivariate`. So `multivariate` should be the permanent location, even if there is nothing else there right now.

(e.g. see https://github.com/JuliaStats/MultivariateStats.jl  for a list)

Given that PCA has been in master for a year (and the never released 0.7), we might want to deprecate the current module location.

what else goes into multivariate?:
scikit-learn has more of the relevant classes. So it's not urgent for us unless there is a statistics part to add. The biggest item would be factor analysis, I guess.
The only (IIRC) item that I have right now are the main parts of canonical correlation, especially with tests on eigen values or rank. Also MANOVA is related.
(possible alternative location for the hypothesis tests is a `stats.multivariate` module)

**Comment by josef-pkt** [comment]
@bashtage

**Comment by josef-pkt** [comment]
@kshedden   Do you know of anything that should get higher priorities in this area?

**Comment by kshedden** [comment]
Perhaps Multidimensional Scaling (MDS).

**Comment by josef-pkt** [comment]
I don't know anything about MDS, the Wikipedia page references
http://scikit-learn.org/stable/modules/generated/sklearn.manifold.MDS.html

**Comment by theaverageguy** [comment]
What is the final call for this @josef-pkt ?

**Comment by bashtage** [comment]
Multivariate seems reasonable.  Not sure it maters much since `PCA` is exposed through api.
