### ISSUE TITLE
cannot import name kalman_loglike

### ISSUE THREAD

**Issue by fgilbert01** [statsmodels/statsmodels#2852]
Hello,

I am trying to run Statsmodels 0.8 development version and I have the following error "cannot import name kalman_loglike" when the code does " from . import kalman_loglike."

The library is in the correct folder on my computer.

**Comment by ChadFulton** [comment]
Have you setup the package?

i.e. have you run one of `python setup.py install` or `python setup.py build_ext -i`?

**Comment by fgilbert01** [comment]
Hello Chad,

 

I consider myself a beginner with Python. After running setup.py, it worked.

 

Thank you.

 

Francois Gilbert

**Comment by ChadFulton** [comment]
Great! Glad it works.

**Comment by lingyaw** [comment]
Hi,
I am also a beginner of python and got same problem. I downloaded statsmodels-master and used "pip3 Cython install" to intall Cython, It was " Successfully installed Cython-0.29.6
". Then I tried "python3 setup.py install". Then I got the following errors. T_T...

/home/liwa/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/liwa/REEK_TEST/2019_03_22/fitvalue/statsmodels-master/statsmodels/tsa/statespace/_tools.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/test-easy-install-28843.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.6/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.
