### ISSUE TITLE
Which model shall I use, and do fitting in "Two-stage Estimator"?

### ISSUE THREAD

**Issue by jenifferYingyiWu** [statsmodels/statsmodels#2855]
After I have estimated the means and variances of errors. 
   How to implement the two-stage estimator by machine learning?
    Shall I separate the target items from training set and testing set?
If I separate them from train and test, then which model shall I use, and do fitting?
     
       So, could you pls give me some suggestions and recommend some python codes?

**Comment by josef-pkt** [comment]
Can you be more specific?
Which two-stage estimator? Which model?

What king of estimation problem?

statsmodels is doing mostly statistics and econometrics, maybe you wanted scikit-learn for machine learning?

**Comment by jenifferYingyiWu** [comment]
![screenshot from 2016-03-15 13 43 42](https://cloud.githubusercontent.com/assets/16315452/13768762/81ca0a3c-eab4-11e5-9de6-329270b6c39f.png)

     The two-stage estimator is above.
I have estimated the means and variances of errors.
Shall I separate the target items from training set and testing set?

     So, which machine learning model shall I use, and do fitting?

Thanks!

**Comment by josef-pkt** [comment]
There is not enough context, which kind of data which kind of likelihood function. 
There are many two step estimators. But I don't see how this relates to prediction, in equ (3).
