### ISSUE TITLE
ValueError: freq T not understood. Please report if you think this in error. (seasonal_decompose)

### ISSUE THREAD

**Issue by debasishdebs** [statsmodels/statsmodels#2856]
Hi, 
I was trying out seasonal_decompose to decompose my time series. The data is perfect time series with frequency of '2T' i.e. 2 Minutes. From file **tsatools.py** (site-pkgs\statsmodels\tsa\tsatools.py), in line 655, I added the following.
_    elif freq == 'T':
        return 60_24_7_52_
I added this from the following inference:
_Freq A means 1 year hence it returns 1.
Q means quaterly and hence returns 4
M means monthly and hence returns 12 and so on.
Therefore, T means per minute, hence 60__24_7*365_

When I do the above, I get following error:
**ValueError: Inferred frequency of index and frequency don't match. This function does not re-sample**
From line 70 in seasonal.py (statsmodel\tsa\seasonal.py)
Because : variable freq is : <2 * Minutes>
And variable pfreq is  2T 524160.

I mean seasonal decompose should be able to decompose timeseries of 1min frequency, and something seems to have changed. Please have a look at it, and let me know if I'm missing anything.

**Comment by josef-pkt** [comment]
I think you can specify freq for the length of the season directly in the call to `seasonal_decompose`.
I haven't looked at how the current frequency detection works.

Aside: Do you really have an annual season? There might be inherent problems with 6 million observations per season. You need quite a few seasons to estimate a seasonal component.

**Comment by debasishdebs** [comment]
Hi. Thanks for response. Well, I did manually try passing my frequency as 'T' in seasonal_decompose() but faced the same error. "Frequency T not recognized.".

Regarding annual season, do you mean seasonality repeating once a year? If so then no. Actually I dont have any seasonality in my data. I was able to decompose time series of same 1 min interval before I updated my package I guess, so it seems there might have been a bug arised by mistake in update.

**Comment by josef-pkt** [comment]
@debasishdebs  freq keyword can take a number for the seasonal length, e.g. 12 for monthly data and annual season https://github.com/statsmodels/statsmodels/issues/2820#issuecomment-185257480
I think that should also work with pandas Series.

> Actually I dont have any seasonality in my data.

What does seasonal_decompose do if you don't have seasonality?

**Comment by debasishdebs** [comment]
@josef-pkt I think seasonal decompose only takes charecters in 'freq' param. Like T for 1 min interval data, A for 1 year interval data and so on right? I can be wrong but that was what I could infer. Anyways, statsmodel  seasonal_decompose() has automatic way to identify your frequency in data, so even if not explicitely passing the freq shouldn't be issue right?

Regarding your last doubt, well, it did split into 2 parts, trend, seasonality and residual, but my seasonality plot showed that I didnt have any seasonality and same thing was repeated every timestamp and only trend and residual information were useful.

**Comment by josef-pkt** [comment]
AFAIR, the algorithm doesn't identify the seasonal length. That has to be given or inferred from the datatime frequency. (E.g. monthly weather data has annual seasonality, so default is 12, quarterly economics data has annual seasonality so freq=4.) If the seasonality doesn't correspond to the inferred length, then the seasonal decomposition wouldn't work.

Based on what I remember.

**Comment by debasishdebs** [comment]
But, I have some decomposition plots which I generated, and they also didn't have any seasonality, and it automatically inferred its corresponding freq. 

Let us say, my data doesn't have any seasonality, and it is at 1 minute interval, then according to you seasonal_decompose wont work right? I just want us to be in same page.

**Comment by josef-pkt** [comment]
I don't know what your data looks like. Does the plot of your data indicate any cyclical/seasonal behavior? How many observations do you have in total in your sample?

It could be that the function essentially does only a trend decomposition if there is no seasonality. But I think it should still remove a seasonal effect even if that is close to zero. (Similar to including dummy variables in a regression that all have essentially zero coefficients.)

**Comment by davidljung** [comment]
I'm seeing a similar error for daily data passed as a pandas DataFrame with an index constructed thus:

`df.index = pd.date_range(start=df.DATE.min(), end=df.DATE.max())`

then:
```
sm.tsa.seasonal_decompose(df.G).plot()
Traceback (most recent call last):

  File "<ipython-input-405-2c53a7f20c1a>", line 1, in <module>
    sm.tsa.seasonal_decompose(df.G).plot()

  File "C:\AppData\Local\Continuum\Anaconda2\lib\site-packages\statsmodels\tsa\seasonal.py", line 70, in seasonal_decompose
    pfreq = freq_to_period(pfreq)

  File "C:\AppData\Local\Continuum\Anaconda2\lib\site-packages\statsmodels\tsa\tsatools.py", line 657, in freq_to_period
    "think this in error.".format(freq))

ValueError: freq D not understood. Please report if you think this in error.
```

It appears to ignore the freq parameter if passed in this case (as I get this same error regardless of what or if I pass in freq=).

Thanks!

**Comment by davidljung** [comment]
Related to https://github.com/statsmodels/statsmodels/issues/2109

**Comment by davidljung** [comment]
Workaround when passing Pandas.Series (i.e. a DataFrame column), is to pass the raw underlying numpy array, using `.values`, so that it doesn't attempt to extract the frequency and fail, then use freq= parameter.

e.g.
``
df = .. DataFrame of daily data ..

sm.tsa.seasonal_decompose(df.G.values, freq=365)  

``

**Comment by CastleDream** [comment]
> Hi,
> I was trying out seasonal_decompose to decompose my time series. The data is perfect time series with frequency of '2T' i.e. 2 Minutes. From file **tsatools.py** (site-pkgs\statsmodels\tsa\tsatools.py), in line 655, I added the following.
> _ elif freq == 'T':
> return 60_24_7_52_
> I added this from the following inference:
> _Freq A means 1 year hence it returns 1. Q means quaterly and hence returns 4 M means monthly and hence returns 12 and so on. Therefore, T means per minute, hence 60__24_7*365_
> 
> When I do the above, I get following error:
> **ValueError: Inferred frequency of index and frequency don't match. This function does not re-sample**
> From line 70 in seasonal.py (statsmodel\tsa\seasonal.py)
> Because : variable freq is : <2 * Minutes>
> And variable pfreq is 2T 524160.
> 
> I mean seasonal decompose should be able to decompose timeseries of 1min frequency, and something seems to have changed. Please have a look at it, and let me know if I'm missing anything.

I just look at the source code，and I think the seasonal_decompose can only receive unit time，you can find this function in statsmodels\tsa\tsatools.py，the 'freq' in dataframe is not apply to seasonal_decompose directly,it will be shifted by the following function .
def freq_to_period(freq):
    """
    Convert a pandas frequency to a periodicity

    Parameters
    ----------
    freq : str or offset
        Frequency to convert

    Returns
    -------
    period : int
        Periodicity of freq

    Notes
    -----
    Annual maps to 1, quarterly maps to 4, monthly to 12, weekly to 52.
    """
    if not isinstance(freq, offsets.DateOffset):
        freq = to_offset(freq)  # go ahead and standardize
    freq = freq.rule_code.upper()

    if freq == 'A' or freq.startswith(('A-', 'AS-')):
        return 1
    elif freq == 'Q' or freq.startswith(('Q-', 'QS-')):
        return 4
    elif freq == 'M' or freq.startswith(('M-', 'MS')):
        return 12
    elif freq == 'W' or freq.startswith('W-'):
        return 52
    elif freq == 'D':
        return 7
    elif freq == 'B':
        return 5
    elif freq == 'H':
        return 24
    else:  # pragma : no cover
        raise ValueError("freq {} not understood. Please report if you "
                         "think this is in error.".format(freq))

**Comment by bashtage** [comment]
If using a non-supported frequency, you can override by manually setting `freq` (now renamed to `period` in master)

**Comment by LoveenDyall** [comment]
What would I need if my freq in Pandas DF was 100S?

**Comment by bashtage** [comment]
What is the period of your data?  1 day? if so it would be 24*3600/100. It is one year (ignoring leap years) it would be 365*24*3600/100.

**Comment by bashtage** [comment]
For clarity, monthly uses 12 since there are 12 months in a year and the period is assumed to be annual. Quarterly uses 4 for the same reason. 'D' uses 7 since it assumes that the full period is one week.

**Comment by LoveenDyall** [comment]
so I'm generating a time series using TimeSynth: with fixed num_samples (e.g. 40,000) and sample_rate (1/100 sec), I find the total time of time signal = num_samples / sample_rate.

Timesynth time signal is also supplied a frequency =>
if I set 50 windows across total_time, then freq = ((+- 10%) * window_count) / total_time

so i guess my period is (+- 10%) * window_count)

**Comment by LoveenDyall** [comment]
is it just a case of re defining 1/100 sec to 1/100 days for instance. then computing total_time in seconds against sample_rate converted to seconds?

**Comment by KirannBhavaraju** [comment]
@bashtage Thanks for the above responses.. I really don't understand how the algorithm dynamically assumes the periods. For example in cases of these pandas `freq` -> `A,Q,M,W` the periodicity is `1,4,12,52` respectively, meaning there are those many entries before the next period begins.. so if the data is of weekly frequency, there would be 52 individual rows `seasonal_decompose()` has to consider before assuming that the seasonal component is calculated again. All this is under the inherent assumption that period is **yearly**.

But in cases of pandas `freq` -> `D,B` the periodicity is returned as `7,5` respectively, here the inherent assumption is that the period is **weekly** since there are 7 days in a week and 5 in a business week.

In cases of pandas `freq` -> `H` the periodicity is returned as `24`, here the inherent assumption is that the period is **daily** since there are 24 hours in a day.

While this same warning still occurs in `0.13.0`, because there is no hardcoded integer returned for pandas frequency of `T`, which period do i assume?
If i assume there is daily periodicity in my data: the period is `60*24 = 1440`, since there are 1440 mins in a day.
If i assume there is weekly periodicity in my data: the period is `7*60*24 = 10080`, since there are 10080 mins in a full week.
If i assume there is non leap yearly periodicity in my data: the period is `365*60*24 = 525600` since there are `525600` mins in an year.

Are these calculations correct ? 

P.S. I hope this answer clarifies many things for future readers.

**Comment by bashtage** [comment]
> While this same warning still occurs in `0.13.0`, because there is no hardcoded integer returned for pandas frequency of `T`, which period do i assume?

Utimately you have to think about your data and how often you would expect deterministic patterns to repeat. You can do with using the `period` parameter to specify an appropriate period for your data. 

Your calculations look right to me.

**Comment by KirannBhavaraju** [comment]
@bashtage Thanks for the confirmation. However, could you throw some light on why the assumption of period changes in the native implementation from Yearly to weekly to daily... ?

**Comment by bashtage** [comment]
It is because these are nearly always exact.  There are always 4 quarters or 12 months in a year. There are also only 52 full weeks in a year. There are 5/7 days in a business/standard week.  24 hours in a day (except for DST adjustments).   Ultimately these are just some simply defaults that can be overwritten using `period`.

**Comment by KirannBhavaraju** [comment]
Thanks for the explanation, but i still am not completely sure.. if that completely explains why the periods change, i mean there are 1440 minutes in a day, but then the actual question was why is it assumed by default that if the pandas frequency is in 'H' then the data inherently has a daily periodicity and if the pandas freq is 'D' then it is assumed by the library that the data is inherently periodic weekly? Sorry if it isn't making any sense, I don't know how else to ask this question.. 

With that being said, I am glad there is an option to overwrite. But things are clear after your explanation a little bit. 👍🏼
