### ISSUE TITLE
fit_regularized returns the string 'True' in mle_retvals object for 'coverged'

### ISSUE THREAD

**Issue by bryangraham** [statsmodels/statsmodels#2857]
When fitting a logit model using the fit_regularized option I notice that mle_retvals dictionary returns the string 'True' instead of the boolean True after a successful convergence. Discovered this error when trying to deal with some exception handling.

**Comment by kshedden** [comment]
The relevant line is here:

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/base/l1_slsqp.py#L102

also here:

https://github.com/statsmodels/statsmodels/blob/f3077577a983fc16217c77d98618510e7eebd66c/statsmodels/base/l1_cvxopt.py#L125

I believe everywhere else in statsmodels, `converged` holds a boolean, but here it returns a string.  The use of the string 'True' was probably done intentionally to maintain type consistency. 

It should probably be changed for consistency.

**Comment by josef-pkt** [comment]
refactored in #3940
