### ISSUE TITLE
BUG: _ar_predict_out_of_sample produces ValueError

### ISSUE THREAD

**Issue by ethankruse** [statsmodels/statsmodels#2863]
I tried searching for this, but couldn't find anything. It seems to be a corner case, so maybe not hugely important, but I don't know what's going on. Let me know if this has already been addressed.

Anyway, I'm using version 0.6.1 and getting the following error:

```
import numpy as np
import statsmodels as sm
x = np.zeros(100)
model = sm.tsa.api.AR(x, missing='drop')
modfit = model.fit(maxlag=30, ic=None, method='cmle')
mod2 = modfit.predict(start=31, end=101, dynamic=False)
```

producing:

```
File "/astro/apps6/anaconda2.0/lib/python2.7/site-packages/statsmodels/base/wrapper.py", line 92, in wrapper
return data.wrap_output(func(results, *args, **kwargs), how)

File "/astro/apps6/anaconda2.0/lib/python2.7/site-packages/statsmodels/tsa/ar_model.py", line 796, in predict
predictedvalues = self.model.predict(params, start, end, dynamic)

File "/astro/apps6/anaconda2.0/lib/python2.7/site-packages/statsmodels/tsa/ar_model.py", line 237, in predict
out_of_sample)

File "/astro/apps6/anaconda2.0/lib/python2.7/site-packages/statsmodels/tsa/ar_model.py", line 58, in _ar_predict_out_of_sample
fcast = mu + np.dot(arparams, endog[i:i+p])

ValueError: shapes (29,) and (30,) not aligned: 29 (dim 0) != 30 (dim 0)
```

I say this is a corner case because my code is not _supposed_ to be returning all 0s, and when you replace the np.zeros with random.randn it works fine. So it seems to be a problem with the entire input being a constant value.

**Comment by josef-pkt** [comment]
Thanks for the report, and especially for example and full traceback

Strange error, I might have expected that it could raise an exception because of the zero variance. (nans because of ZeroDivision ?)

(The only possible similar case that I remember was related to the check that there is already a constant included, but I think that was only with exog. Maybe something messing up the `trend` setting and consequently the parsing of params.)

**Comment by josef-pkt** [comment]
I tried this with current master and it does not fail
the prediction `mod2` in example is all zeros

Looks like fixed somewhere
I'm closing this. Reopen or open a new issue if there are related problems
