### ISSUE TITLE
Test failure for Sandybridge OpenBLAS kernel - test precision?

### ISSUE THREAD

**Issue by matthew-brett** [statsmodels/statsmodels#2876]
We are in the middle of testing the scipy numerical libraries with OpenBLAS:

* https://github.com/matthew-brett/manylinux-builds/issues/4
* https://mail.scipy.org/pipermail/numpy-discussion/2016-March/075206.html

We have found a couple of test errors in current statsmodels, on just one of the OpenBLAS kernels.

https://github.com/matthew-brett/manylinux-builds/issues/4#issuecomment-203038517

```
======================================================================
FAIL: statsmodels.tsa.statespace.tests.test_dynamic_factor.TestDynamicFactor_general_errors.test_bse_approx
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/matthew-brett/manylinux-testing/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/matthew-brett/manylinux-testing/venv/lib/python2.7/site-packages/statsmodels/tsa/statespace/tests/test_dynamic_factor.py", line 376, in test_bse_approx
    assert_allclose(bse[-10:], self.true['var_oim'][-10:], atol=1e-4)
  File "/home/travis/build/matthew-brett/manylinux-testing/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/home/travis/build/matthew-brett/manylinux-testing/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.0001
(mismatch 10.0%)
 x: array([  2.142085e-04,   1.307592e-02,   2.915582e-01,   4.320433e-01,
         7.689779e-04,   1.742122e-02,   2.201651e-02,   5.543138e-04,
         1.456134e-02,   1.707097e-02])
 y: array([  2.142100e-04,   1.307587e-02,   2.916752e-01,   4.320406e-01,
         7.689900e-04,   1.742173e-02,   2.201610e-02,   5.543500e-04,
         1.456365e-02,   1.707167e-02])
======================================================================
FAIL: statsmodels.tsa.statespace.tests.test_sarimax.TestFriedmanStateRegression.test_mle
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/matthew-brett/manylinux-testing/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/matthew-brett/manylinux-testing/venv/lib/python2.7/site-packages/statsmodels/tsa/statespace/tests/test_sarimax.py", line 746, in test_mle
    atol=1e-1, rtol=1e-1
  File "/home/travis/build/matthew-brett/manylinux-testing/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/home/travis/build/matthew-brett/manylinux-testing/venv/lib/python2.7/site-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.1, atol=0.1
(mismatch 33.3333333333%)
 x: array([   0.970836,    0.299662,  103.355682])
 y: array([  0.934849,   0.309059,  93.224973])
----------------------------------------------------------------------
Ran 4548 tests in 2554.303s
FAILED (SKIP=164, failures=2)
```

I can replicate on a recent Linux machine with (in a virtualenv):

```
python -m pip install -U pip
pip install -f https://d9a97980b71d47cde94d-aae005c4999d7244ac63632f8b80e089.ssl.cf2.rackcdn.com numpy scipy pandas nose cython
pip install https://github.com/statsmodels/statsmodels/archive/eed4ae5a90a1d1ac312c24bbebf2bff88fe87da9.zip
OPENBLAS_VERBOSE=2 OPENBLAS_CORETYPE=sandybridge nosetests statsmodels.tsa.statespace.tests.test_dynamic_factor statsmodels.tsa.statespace.tests.test_sarimax
```

I noticed the very liberal precision you are using here.  Is it possible this difference is within reasonable floating point limits?

**Comment by matthew-brett** [comment]
Thanks.   Can you give any more details on why you think it is the fault of the tests?   I'm asking because we might need to put in a bug report to OpenBLAS if the difference for this kernel compared to others is more than it should be.

**Comment by matthew-brett** [comment]
Assuming that this is just numerical precision, PR #2878 slightly relaxes the thresholds on the failing tests - is that reasonable?

**Comment by xianyi** [comment]
@matthew-brett , if you think this is a potential OpenBLAS bug, please create an OpenBLAS issue.

**Comment by matthew-brett** [comment]
@xianyi - thank you.   I don't understand this code well enough to follow where the precision errors are coming from.  @ChadFulton, who wrote the code, thinks it's reasonable to attribute this to numerical error.  So, I don't think we have any good evidence yet that this is really a bug in OpenBLAS rather than some acceptable precision difference in the calculation.

**Comment by josef-pkt** [comment]
for the FriedmanStateRegression failure:

cross linking to difficult optimization problems or convergence failures #1649

My guess, based on a brief look at the unit tests, is that this is a difficult optimization problem that is not well behaved. In those cases small numerical noise can have quite large effects on the final outcome. (If the params are not well identified, then it can still be the case that the predictions are very close.)
Given that the calculations are quite elaborate and have many moving parts, it's not possible to tell whether the numerical noise is within tolerance or might be caused by a small bug that only shows up in messy cases.

**Comment by ChadFulton** [comment]
Yes, these tests have had their tolerances reduced several times due to numerical problems across platforms. I recently improved a lot of these tests, but these are still messy computations. Probably the best solution is to find better optimization problems to use as unit tests.
