### ISSUE TITLE
Update Dependencies on http://statsmodels.sourceforge.net/developer.html

### ISSUE THREAD

**Issue by bfcondon** [statsmodels/statsmodels#2880]
The page http://statsmodels.sourceforge.net/developer.html currently lists the dependencies as:

Dependencies¶
Python >= 2.5, including Python 3.x
NumPy (>=1.4)
SciPy (>=0.7)
Pandas >= 0.7.1
Cython >= 15.1, Optional but recommended when building from source.

Optional Dependencies
Matplotlib is needed for plotting functions and running many of the examples.
Nose is required to run the test suite.

but they should probably be updated to the list in the documentation (/home/brendan/statsmodels/docs/source/install.rst)

Dependencies

```

* `Python <https://www.python.org>`__ >= 2.6, including Python 3.x 
* `NumPy <http://www.scipy.org/>`__ >= 1.5.1
* `SciPy <http://www.scipy.org/>`__ >= 0.9.0
* `Pandas <http://pandas.pydata.org/>`__ >= 0.7.1
* `Patsy <https://patsy.readthedocs.org>`__ >= 0.3.0
* `Cython <http://cython.org/>`__ >= 20.1, Needed if you want to build the code from github and not a source distribution. You must use Cython >= 0.20.1 if you're on Python 3.4. Earlier versions may work for Python < 3.4.

Optional Dependencies
```
- `Matplotlib <http://matplotlib.org/>`__ >= 1.1 is needed for plotting functions and running many of the examples. 
- If installed, `X-12-ARIMA <http://www.census.gov/srd/www/x13as/>`__ or `X-13ARIMA-SEATS <http://www.census.gov/srd/www/x13as/>`__ can be used for time-series analysis.
- `Nose <https://nose.readthedocs.org/en/latest>`__ is required to run the test suite.
- `IPython <http://ipython.org>`__ >= 1.0 is required to build the docs locally.

**Comment by josef-pkt** [comment]
Thanks for finding.

I wasn't aware of this page. I think it would be better to delete that section and point to a single location where we have the version requirements.
This duplication is a prime source for having outdated documentation.
http://statsmodels.sourceforge.net/devel/install.html#dependencies seems to be more current.

(The only reliable source of information are the TravisCI unit test settings.)

**Comment by jbrockmendel** [comment]
URL in OP is a 404. Alternative URL given by @josef-pkt lists out of date dependencies.

**Comment by bashtage** [comment]
These are up to date
