### ISSUE TITLE
ENH: New Seasonal TimeSeries Model:TBATS/BATS/MTBATS

### ISSUE THREAD

**Issue by Leoyzen** [statsmodels/statsmodels#2893]
A new timeseries forecast/decompose model based on Rob.J.Hyndman's paper. #2892 
http://robjhyndman.com/papers/complex-seasonality/

It is the same as the tbats model of R's forecast package.

TBATS: Trigonometric, Box-Cox, ARMA Error, Trend and Seasonal
BATS:Box-Cox, ARMA Error, Trend and Seasonal
MTBATS: The same as TBATS but with multiple error mod(similar with UnobservedComponents)

Feature:
- Long Seasonality forecast (such as minutes data)
- Complex seasonality based on trigonometric transform(such as multiple seasonality/non-interger periods)
- BoxCox transform
- arma error
- exog support
- Kalman Smoothing based on awesome state space framework
- less coefs estimation than standard exponention smooth

Tools:
- Fourier Seasonal tools (can be used in any time series model with exog support)

**Comment by davidljung** [comment]
This would be great.  Right now I'm using PyPer to wrap calls to R's tbats implementation.

**Comment by josef-pkt** [comment]
@davidljung   If you are familiar with this, then it would be very helpful if you could give PR #2892  a test drive and help with the review. That would speed up the merge. (also, there are no unit tests yet.)

I'm not familiar with this, and it will take me some time to look at it. I don't know whether @ChadFulton  is familiar with this.

**Comment by ChadFulton** [comment]
Somehow I missed that PR completely, I'll take a look at it.

**Comment by Leoyzen** [comment]
@ChadFulton The first problem of the model is the single error state space implement.
I think it should be write based on cython extension of existed framework, but I haven't done yet.So just a simple class which we discussed before.

I will write some ipython notebook to introduce the model first.

**Comment by Leoyzen** [comment]
@ChadFulton I got some problem with the variance initialization of the model, can u plz have a look?

**Comment by bashtage** [comment]
There is a Python implementation of BATS/TBATS:

https://github.com/intive-DataScience/tbats
