### ISSUE TITLE
MixedLMResults.resid broken when vc_formula used

### ISSUE THREAD

**Issue by bburan** [statsmodels/statsmodels#2901]
[example_data.txt](https://github.com/statsmodels/statsmodels/files/232593/example_data.txt)

Sample data attached. Use with the following code:

    x = pd.io.parsers.read_csv('example_data.txt') 
    m = smf.MixedLM.from_formula('sf~area*phase*stream', data=x, groups=x['cell'],
                                 vc_formula={'target': '0+target'})
    fit = m.fit()
    fit.resid

Traceback:

    /home/bburan/bin/anaconda3/envs/notebook/lib/python3.5/site-packages/statsmodels/base/wrapper.py in __getattribute__(self, attr)
         33             pass
         34 
    ---> 35         obj = getattr(results, attr)
         36         data = results.model.data
         37         how = self._wrap_attrs.get(attr)
    
    /home/bburan/bin/anaconda3/envs/notebook/lib/python3.5/site-packages/statsmodels/tools/decorators.py in __get__(self, obj, type)
         95         if _cachedval is None:
         96             # Call the "fget" function
    ---> 97             _cachedval = self.fget(obj)
         98             # Set the attribute in obj
         99             # print("Setting %s in cache to %s" % (name, _cachedval))
    
    /home/bburan/bin/anaconda3/envs/notebook/lib/python3.5/site-packages/statsmodels/regression/mixed_linear_model.py in resid(self)
       2132         fixed effects and the predicted random effects.
       2133         """
    -> 2134         return self.model.endog - self.fittedvalues
       2135 
       2136 
    
    /home/bburan/bin/anaconda3/envs/notebook/lib/python3.5/site-packages/statsmodels/tools/decorators.py in __get__(self, obj, type)
         95         if _cachedval is None:
         96             # Call the "fget" function
    ---> 97             _cachedval = self.fget(obj)
         98             # Set the attribute in obj
         99             # print("Setting %s in cache to %s" % (name, _cachedval))
    
    /home/bburan/bin/anaconda3/envs/notebook/lib/python3.5/site-packages/statsmodels/regression/mixed_linear_model.py in fittedvalues(self)
       2113             ix = self.model.row_indices[group]
       2114 
    -> 2115             mat = [self.model.exog_re_li[group_ix]]
       2116             for c in self.model._vc_names:
       2117                 if group in self.model.exog_vc[c]:
    
    TypeError: 'NoneType' object is not subscriptable

    ---> 97             _cachedval = self.fget(obj)
         98             # Set the attribute in obj
         99             # print("Setting %s in cache to %s" % (name, _cachedval))

    /home/bburan/bin/anaconda3/envs/notebook/lib/python3.5/site-packages/statsmodels/regression/mixed_linear_model.py in fittedvalues(self)
       2113             ix = self.model.row_indices[group]
       2114 
    -> 2115             mat = [self.model.exog_re_li[group_ix]]
       2116             for c in self.model._vc_names:
       2117                 if group in self.model.exog_vc[c]:

TypeError: 'NoneType' object is not subscriptable

**Comment by kshedden** [comment]
Should be fixed in #2903, let us know if not.
