### ISSUE TITLE
TST:  test_lme.TestMixedLM.test_regularized slow or stalls with scipy 0.12

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2907]
The older python 2.7 version on TravisCI is slow and takes much longer than the newer versions.

Sometimes test_lme.TestMixedLM.test_regularized finishes slowly (based on watching the TravisCI progress), and a few times it stalled. e.g. https://travis-ci.org/statsmodels/statsmodels/jobs/125724307
It stalled first in a PR that doesn't change any non-doc code (#2905)

Because there are no problems on travis with recent versions of dependencies (numpy, scipy, ...), it doesn't look like anything serious, but worth investigating. Is there anything fragile in the tests? 

And, it's a reason to start dropping old numpy and scipy versions.

**Comment by kshedden** [comment]
My experience was that the tests involving numeric differentiation are
quite slow, and the others are fairly fast.  These are already marked as
slow.  I don't recall any speed issues with the regularized testing, but I
will look into that.

Kerby

**Comment by josef-pkt** [comment]
Because the tests run pretty fast on newer version of dependencies, I guess it's not a real problem with the calculations but more likely it is something that might throw off less robust algorithms.
My guess would be that it has to be related to scipy. (optimize ?) or maybe linalg libraries (quick check the old version used libgfortran 1.0, the newer versions use libgfortran 3.0)

**Comment by josef-pkt** [comment]
@kshedden   Can you skip this unit test on older scipy version similar to the other ones that cause problems with those versions?

one out of every few TravisCI test runs hangs on the `TestMixedLM.test_regularized` test but only on the python 2.7 with scipy 0.12 version (numpy 1.7)

```
statsmodels.regression.tests.test_lme.TestMixedLM.test_regularized ... 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
