### ISSUE TITLE
TST: matplotlib warns too many open windows

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2910]
https://travis-ci.org/statsmodels/statsmodels/jobs/125880942

This is from a test run with matplotlib 1.5.1 that is slow and hits the TravisCI timeout limit

there are a few more like these

```
statsmodels.tsa.statespace.tests.test_structural.test_random_trend ... /home/travis/miniconda2/envs/statsmodels-test/lib/python3.5/site-packages/matplotlib/pyplot.py:516:  
RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot  
interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much  
memory. (To control this warning, see the rcParam `figure.max_open_warning`). 
  max_open_warning, RuntimeWarning)
```

**Comment by ChadFulton** [comment]
I do create a bunch of plots in `test_structural` and `test_dynamic_factor`, but I explicitly close those plots with `plt.close(fig)`.

This warning first occurs at:

    statsmodels.graphics.tests.test_regressionplots.TestPlot.test_plot_fit ... ok
    statsmodels.graphics.tests.test_regressionplots.TestPlot.test_plot_oth ... ok
    statsmodels.graphics.tests.test_regressionplots.TestPlotFormula.test_one_column_exog ... ok
    statsmodels.graphics.tests.test_regressionplots.TestPlotFormula.test_plot_fit ... ok
    statsmodels.graphics.tests.test_regressionplots.TestPlotFormula.test_plot_oth ... ok
    statsmodels.graphics.tests.test_regressionplots.TestPlotPandas.test_plot_fit ... ok
    statsmodels.graphics.tests.test_regressionplots.TestPlotPandas.test_plot_oth ...
    /home/travis/miniconda2/envs/statsmodels-test/lib/python3.5/site-packages/matplotlib/pyplot.py:516:
    RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot
    interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too
    much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
    max_open_warning, RuntimeWarning)

Most of the tests in `test_regressionplots` also close their plots, but not all of them. I'm trying to run down which test is the culprit .

**Comment by ChadFulton** [comment]
Actually turns out the issue is in `test_mosaicplot.py`. None of those tests explicity close their figures.
