### ISSUE TITLE
Replace Panel with xarray

### ISSUE THREAD

**Issue by bfcondon** [statsmodels/statsmodels#2917]
In the latest Pandas documents, they note that Panel will be deprecated in favor of xarray.  This is not pressing, but I think it would be best to use xarray or a DataFrame with a multiindex when building functionality for panel data.

http://pandas.pydata.org/pandas-docs/version/0.18.0/whatsnew.html#to-xarray

**Comment by josef-pkt** [comment]
I looked at it a while ago in the context of absorbing categorical variables or crossed fixed effects in panel data. 
Besides n-dimensional dataframe analog, it has also good dask integration that might help us for out of core calculation.

However, unless there is a specific use case, I don't think it's urgent to add support for it.

I haven't looked at the details of the panel pandas integration and current pandas stats yet. However, the initial implementation should all use the *long* format with a 2-dimensional dataframe.
Current functionality in statsmodels just requires extra arrays for groups and time labels which are used similarly to multi-index.
The Panel PR uses mostly multi-indices with usage hidden behind a `group`by handling class. But there is still some pandas `Panel` class used somewhere (which I never tried to understand).

**Comment by bashtage** [comment]
Closing as no action.  I don't think there is capacity to use or need for xarray currently
