### ISSUE TITLE
SARIMAX get_prediction with simple_difference

### ISSUE THREAD

**Issue by TomAugspurger** [statsmodels/statsmodels#2939]
I'm a bit confused about the interaction between SARIMAX's `simple_difference` parameter and the results from `get_prediction`. Example notebook [here](https://gist.github.com/7c87c26542db41f094673cb3b30174a1) shows the issue.

Fitting a SARIMAX on the stata wpi1 dataset

``` python
mod_s = sm.tsa.statespace.SARIMAX(data['wpi'], trend='c', order=(1,1,1),
                                  seasonal_order=(1, 1, 1, 12),
                                  simple_differencing=True)
res_s = mod_s.fit()
```

My confusion comes from the `pred_s = res_s.get_prediction()` results. We transformed the dataset with simple differencing _prior_ to fitting, so the forecast results are
1. Differenced (once for d=1, 12 periods for D=12)
2. Shifted either 12 or 13 periods (not sure) which, probably 13.

So a forecast that should be for January 2013 in the original dataset, ends up being labeled as Feb. 2014 in the transformed dataset.

My question: Should the results from `res_s.get_prediction()` be inverse-transformed (shifted by d + D periods and un-differenced). If not, I can submit a PR updating the documentation.

**Comment by josef-pkt** [comment]
my guess (I haven't looked at the example)

Having the wrong date label looks wrong. If we have labels, then they should be for the actual date/index. Is there a reason, or is this a bug in attaching the index again?

for the rest, there should be options, e.g. ARIMA has `typ="level"`

**Comment by josef-pkt** [comment]
What's the reason for simple_differencing?  Is the "non-simple" differencing as part of the statespace model supposed to do the same.

AFAICS: prepare_data is changing/pre-processing endog and exog, but, most likely doesn't change the label/index in `.data`
predict is all inherited, and does not have the special code for the inverse transformation as does ARIMA. 
Also, if the endog and exog in the data are changed, then there might be some missing untransformed level information that is not stored anymore, like original initial values that are differenced away.

**Comment by josef-pkt** [comment]
(BTW: I will give a short presentation in 3 weeks with focus on ARMA/SARIMAX, so I'm interested this time to figure out some examples.)

**Comment by TomAugspurger** [comment]
> What's the reason for simple_differencing?

I was going off of @ChadFulton's notebook [here](http://www.statsmodels.org/dev/examples/notebooks/generated/statespace_sarimax_stata.html) to estimate a seasonal ARIMA.
I think simple_differencing=False is generally preferable. I was just doing both to compare and was confused by the prediction output.

I think I agree with you that the mislabelling of points (forecasts being matched with the shifted dates) is more surprising / wrong than the level stuff.

BTW I'm putting together a post [here](http://nbviewer.jupyter.org/gist/TomAugspurger/3e9676fe8b92715071efc01c3264419c) on pandas for manipulating time series and statsmodels for modeling them.
It's pretty similar to Chad's notebooks, but at a more intro-level and skips over a bunch of details.
Not sure if any of that would be useful for your presentation, but feel free to take whatever.

**Comment by josef-pkt** [comment]
@TomAugspurger  thanks that notebook will be very helpful for me, especially given that I don't know a lot of pandas.

Right now I cannot run the examples because my statespace part in statsmodels is messed up. Most likely I didn't recompile after some changes.

It's up to Chad, but my impression is that it's not worth duplicating the retransformation code from ARIMA to SARIMAX given that non-simple differencing handles this use case already. (unless there is a simple way to share the code and just call the corresponding ARIMA functions)

**Comment by josef-pkt** [comment]
(I will have to do the monthly or bi-monthly shutdown of open windows and running processes before Windows lets me recompile any extensions. So, no statespace examples for me today.)

**Comment by ChadFulton** [comment]
I agree that this is a bug with the date attachment, probably something in `prepare_data` that I missed when using simple differencing and a time series index. Thanks for the report! I'll track it down and get a PR to fix this issue.

**Comment by ChadFulton** [comment]
This PR should fix the issue. To make sure it's doing what you would expect: with the new code, you would not have to do the `shift(-12)` part in the last plot of your notebook. Is that what you expected?

Also, I checked against Stata and this PR makes the dates in line with their predict function.

**Comment by TomAugspurger** [comment]
> To make sure it's doing what you would expect: with the new code, you would not have to do the shift(-12) 

Yep, and the `.shift(-12)` may have needed to bee a `.shift(-13)` since we had the non-seasonal `d=1` to go with the seasonal `d=13`. Just glancing at your PR, it looks like that should be good. Thanks!

**Comment by josef-pkt** [comment]
@TomAugspurger  general pandas question: Does pandas raise an exception if index and data array have different lengths?   
Specifically, I would have expected and exception with the dates/index mismatch.

**Comment by TomAugspurger** [comment]
@josef-pkt generally yes. When using the `pd.Series()` or `pd.DataFrame` constructors the data array and index must have the same length. I haven't looked at the code, but I'm guessing it used a slice on the index and data like `:len(self.endog) - d - D`. So they're both the correct length, but that slice on the index needs to be shifted `d + D`.

**Comment by josef-pkt** [comment]
Thanks, The code for the wrapping is somewhere in base for data, I guess but didn't look. It could be that the generic data handling code uses a slice automatically to handle other cases/models.

**Comment by ChadFulton** [comment]
I won't have time this weekend to think about if it's possible to do something using the ARIMA transformation code (or something else) to easily get prediction in terms of the original data, but I'll take a look on Monday.

**Comment by baharian** [comment]
I apologize for reviving an old(-ish) thread, but is the behavior of SARIMAX (from the most recent codebase) with `simple_differencing = True` correct when `.forecast()` is used?
For example, if I have a daily time series which terminates on, say, 2016-11-30, and I use `simple_differencing = True` when constructing a SARIMAX model with $d = 1$ and $D = 1$, and if i want to forecast for 7 days in the future, from 2016-12-01 to 2016-12-07, then would the output of `.forecast(7)` represent time span that I want OR because I have differenced twiced (d and D) the output actually represents the forecast for 2016-12-08 to 2016-12-16?

**Comment by ChadFulton** [comment]
The output of `forecast` will always be directly after the sample, so in your case, the first forecast value will always correspond to the date 2016-12-01 (and if you're using Pandas data, then it *should* be the case that the date index of the first forecast is 2016-12-01).

Another thing that is important to know, though, is that if you use `simple_differencing=True` then the series you will be forecasting is not the `endog` variable you put in, instead it will be the differenced version. If you have `simple_differencing=False`, then you will be forecasting `endog` itself.

In your case, if using `simple_differencing=True`, your last observation in the sample will effectively be:
`(1 - L)(1 - L^s) y_T = (1 - L - L^s - L^(s+1)) y_T = y_T - y_(T-1) - Y_(T-s) - Y_(T-s-1)`.

Then the first forecast, associated with the date index 2016-12-01, will be a forecast of:
`(1 - L) (1 - L^s) y_(T+1) = y_(T+1) - Y_T - Y_(T-s+1) - Y_(T-s)`.

By contrast, if using `simple_differencing=False`, then the first forecast, associated with the date index 2016-12-01, will be a forecast of: `y_(T+1)`.

See http://nbviewer.jupyter.org/gist/ChadFulton/9b2e7293960fac4032190da4881d20bc for an illustration of this.

**Comment by baharian** [comment]
@ChadFulton Thank you so much for clarifying this. I didn't know `simple_differencing = True` would be forecasting the differenced version of `endog`, and that is exactly what caused my confusion in the first place, because my forecasts with and without this argument looked very different! The notebook was very helpful as wel.
May I suggest this behavior to be added to statsmodels' documentation?

**Comment by bashtage** [comment]
Appears to be fixed in master and explained in the docstring.
