### ISSUE TITLE
seasonal_decompose deprecation warning from numpy

### ISSUE THREAD

**Issue by mhooreman** [statsmodels/statsmodels#2958]
Hello,

It seems that seasonal decompose suffers of a deprecation warning coming from numpy.

It can be reproduced using the example documented here: http://statsmodels.sourceforge.net/0.6.0/release/version0.6.html#seasonal-decomposition:

The code:

```python
import statsmodels.api as sm
dta = sm.datasets.co2.load_pandas().data
dta.co2.interpolate(inplace=True)
res = sm.tsa.seasonal_decompose(dta.co2)
```

Results in:
```
[...]/statsmodels/tsa/filters/filtertools.py:28: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
    return np.r_[[np.nan] * head, x, [np.nan] * tail]
```

Versions:
- Numpy: 1.11.0  (latest from pip)
- Statsmodels: 0.6.1 (latest from pip)
- Python: 3.5.1 (manually compiled on virtual environment)

Best regards.

**Comment by thequackdaddy** [comment]
Hello,

I'm a small contributer to statsmodels--and know far less than other people around here--but the official version on pip and conda are quite old compared to what's in master. This code seems to run fine (with no errors) on my Anaconda 4.0.0, python 3.5.1 windows machine.

```python
In [1]: import statsmodels.api as sm
   ...: dta = sm.datasets.co2.load_pandas().data
   ...: dta.co2.interpolate(inplace=True)
   ...: res = sm.tsa.seasonal_decompose(dta.co2)

In [2]: import statsmodels

In [3]: import numpy

In [4]: statsmodels.__version__
Out[4]: '0.8.0.dev0+fd90132'

In [5]: numpy.__version__
Out[5]: '1.10.4'
```

**Comment by josef-pkt** [comment]
@thequackdaddy  thanks for checking

AFAIR, this was among the compatibility fixes that were made a few months ago.

**Comment by mhooreman** [comment]
Thanks.

What are the plans to release it to pip? I use it on a production server,
and so I'm hesitating a lot before installing a non released version.

Best regards.

2016-05-22 17:41 GMT+02:00 Josef Perktold <notifications@github.com>:

> @thequackdaddy <https://github.com/thequackdaddy> thanks for checking
>
> AFAIR, this was among the compatibility fixes that were made a few months
> ago.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/statsmodels/statsmodels/issues/2958#issuecomment-220838990>
>



-- 

Michaël Hooremanmichael@hooreman.be - http://www.hooreman.be
