### ISSUE TITLE
'MixedLMResults' object has no attribute 're_params'

### ISSUE THREAD

**Issue by 00tau** [statsmodels/statsmodels#2961]
In difference to the documentation [1] the class MixedLMResults has no attribute re_params.

```
In [449]: result.re_params
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-449-6c53a17ec896> in <module>()
----> 1 result.re_params

/home/moebius/software/python-environments/nmf/lib/python3.4/site-packages/statsmodels/b
ase/wrapper.py in __getattribute__(self, attr)
     33             pass
     34
---> 35         obj = getattr(results, attr)
     36         data = results.model.data
     37         how = self._wrap_attrs.get(attr)

AttributeError: 'MixedLMResults' object has no attribute 're_params'
```

I am using version

```
In [453]: sm.version.full_version
Out[453]: '0.6.1'
```

Minimal example

```
import statsmodels.formula.api as smf
rfit = smf.mixedlm('value ~ 1', groups=dat['officer'], data=dat).fit()
print(rfit.summary(alpha=.01))

rfit.fe_params
rfit.re_params
```

where dat is a DataFrame which looks as follows

```
   officer  value
0        0     76
1        0     65
2        0     85
3        0     74
4        1     59
5        1     75
6        1     81
7        1     67
8        2     49
9        2     63
10       2     61
11       2     46
12       3     74
13       3     71
14       3     85
15       3     89
16       4     66
17       4     84
18       4     80
19       4     79
```

How do I get the random effects parameters? I am in particular interested in estimating the intraclass correlation. If you already happened to code this somewhere, let me know!

Cheers,
Thomas

[1] http://statsmodels.sourceforge.net/stable/generated/statsmodels.regression.mixed_linear_model.MixedLMResults.html

[2] https://en.wikipedia.org/wiki/Intraclass_correlation#Modern_ICC_definitions:_simpler_formula_but_positive_bias

**Comment by kshedden** [comment]
Hello Thomas,

Does rfit.random_effects work for you?

MixedLM is fairly new and we made some major modifications about a year ago
when we added support for variance components.  If possible it would be
better to use the code from statsmodels master on github.

Kerby

**Comment by thequackdaddy** [comment]
I was able to replicate his error master. 

```python
In [2]: import pandas as pd

In [3]: dat = pd.read_csv('data.csv')

In [4]: import statsmodels.formula.api as smf

In [5]: rfit = smf.mixedlm('value ~ 1', groups=dat['officer'], data=dat).fit()

In [6]: rfit.re_params
Traceback (most recent call last):

  File "<ipython-input-6-9d93bff9fa5f>", line 1, in <module>
    rfit.re_params

  File "C:\Anaconda3\lib\site-packages\statsmodels-0.8.0-py3.5-win-amd64.egg\statsmodels\base\wrapper.py", line 35, in __getattribute__
    obj = getattr(results, attr)

AttributeError: 'MixedLMResults' object has no attribute 're_params'


In [7]: import statsmodels.api as sm

In [8]: sm.version.full_version
Out[8]: '0.8.0.dev0+fd90132'
```

**Comment by kshedden** [comment]
I don't remember the history on this but I think at some point we switched
from re_params to random_effects.  We probably just need to update the docs.

Kerby

**Comment by 00tau** [comment]
Given the random one-way ANOVA model of the example:
  y_ij = μ + μ_i + ε_ij  with  μ_i ~ N(0, λ^2)  and  ε_ij ~ N(0, σ^2)

I am looking for the variance estimates of λ^2 (often called the homogeneity) and σ^2 (variance of the residuals). The `rfit.random_effects` gives me the estimates of the μ_i. It seems to be that σ^2 = `result.params[-1:]`. Is this correct? How do I get an estimate of λ^2?

PS. I may be able to switch to github-master; I will do so soon.

**Comment by kshedden** [comment]
Below is an example that illustrates how this works.  The ``scale`` value given in the top of the summary output, or as `result.scale` is the variance of the independent error terms (epsilon in your notation).  In the summary output below, ``Group RE`` is the variance of the group random effect (a.k.a. random intercept, lambda^2 in your notation).  MixedLM uses a reparameterized likelihood internally, so ``result.params`` is hard to interpret.  To get the random effects variance parameters, use ``result.cov_re``.

The ICC would be `result.cov_re[0,0] / (result.cov_re[0,0] + result.scale)`, which should be around 0.7 in the example below.

```
import statsmodels.api as sm
import numpy as np

ngrp = 1000 # Number of groups                                                                                                                       
gsize = 20  # Number of observations per group                                                                                                       
rsd = 2     # SD of errors                                                                                                                           
gsd = 3     # SD of group means                                                                                                                      
mn = gsd*np.random.normal(size=ngrp)
gmn = np.kron(mn, np.ones(gsize))
y = gmn + rsd*np.random.normal(size=ngrp*gsize)
gr = np.kron(np.arange(ngrp), np.ones(gsize))
x = np.ones(ngrp * gsize)
model = sm.MixedLM(y, x, groups=gr)
result = model.fit()
```

```
          Mixed Linear Model Regression Results
=========================================================
Model:            MixedLM Dependent Variable: y          
No. Observations: 20000   Method:             REML       
No. Groups:       1000    Scale:              4.0166     
Min. group size:  20      Likelihood:         -44222.7198
Max. group size:  20      Converged:          Yes        
Mean group size:  20.0                                   
----------------------------------------------------------
             Coef.  Std.Err.    z    P>|z|  [0.025  0.975]
----------------------------------------------------------
const        0.009     0.098  0.088  0.930  -0.184   0.202
Group RE     9.501     0.222                              
=========================================================
```

**Comment by kshedden** [comment]
Just a note that I'm getting an error on master when I run ``result.random_effects`` in the above examples.  It looks like the names are not being set.

**Comment by 00tau** [comment]
Thanks for the explanation of the summary output. I can see why you call the residual variance 'Scale', but I wouldn't have guessed it. To summarise: `result.scale` and `result.cov_re` are my friends instead of `result.params`.

I have realised that `result.cov_re` in your example is either a pandas.DataFrame or numpy.ndarray depending on whether y is a pandas.Series or a numpy.ndarray. This means that reference to the homogeneity changes: From `result.cov_re[0,0]` to `result.cov_re.ix[0,0]`. Is this as intended?

PS. Now using sm.version.full_version: '0.8.0.dev0+fd90132'

**Comment by kshedden** [comment]
I don't understand the wrappers that handle type conversions of return values very well.

@josef-pkt -- should `result.cov_re` always be a data frame?

**Comment by josef-pkt** [comment]
about the pandas wrapper.
in general: 
numpy in -> numpy out
pandas in -> pandas out

this uses pandas if at least one of endog or exog is a pandas object IIRC. 
(there could be other data types also, but I think we only have numpy and pandas fully supported right now)

The advantage of returning numpy ndarrays is for users that don't use pandas directly, and for us when we use a model as internal tool for, for example, auxiliary regression.

**Comment by MaxGhenis** [comment]
I think there's still a documentation issue: http://www.statsmodels.org/dev/generated/statsmodels.regression.mixed_linear_model.MixedLMResults.random_effects.html#statsmodels.regression.mixed_linear_model.MixedLMResults.random_effects says `random_effects` is a function, and http://www.statsmodels.org/dev/generated/statsmodels.regression.mixed_linear_model.MixedLMResults.html#statsmodels.regression.mixed_linear_model.MixedLMResults says that `re_params` is an attribute of `MixedLMResults`, but I get the following (`m` is a model):

    m.random_effects()

> TypeError: 'dict' object is not callable

    m.re_params

> AttributeError: 'MixedLMResults' object has no attribute 're_params'

    m.random_effects  # Produces the dictionary of random effects.

I'm on version 0.8.0.

**Comment by kshedden** [comment]
Thanks for the report.

I think the issue with `random_effects` being misdocumented as a function
is due to it being a cached attribute.  I'm not sure if we have a way to
fix that right now.

I think the docstring that says `re_params` should say `cov_re` in its
place.  I will look into it and fix if needed.
