### ISSUE TITLE
BUG: Function anova_lm gives unexpected/wrong results

### ISSUE THREAD

**Issue by 00tau** [statsmodels/statsmodels#2966]
From reading the docs [1], I assume that anova_lm implements the so-called 'general linear test approach', i.e., when I would like to test against a hypothesis that involves one or more model parameters to be not null, I define a *full* model and test this model against a *restricted* version, where all of these parameters are null. The example of the docs is applying this approach when testing for statistical interaction. I will be using the same example:

```
import pandas as pd
from statsmodels.compat import urlopen
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm
from scipy.stats import f

url = 'http://stats191.stanford.edu/data/salary.table'
fh = urlopen(url)
salary = pd.read_table(fh)
salary.E = salary.E.astype('category')
salary.M = salary.M.astype('category')
salary.dtypes

# The full model -- with interaction
full = ols('S ~ E * M + X', data=salary, eval_env=1).fit()
full.summary()

# The reduced model -- with no interaction
reduced = ols('S ~ E + M + X', data=salary, eval_env=1).fit()
reduced.summary()

# Calculate the p-value by hand
fstats = (reduced.ssr - full.ssr) / (reduced.df_resid - full.df_resid) / (reduced.ssr / reduced.df_resid)
pvalue = 1 - f.cdf(fstats, dfn=(reduced.df_resid - full.df_resid), dfd=full.df_resid)
fstats, pvalue # 19.9419584168, 1.08264167142e-06

# Here is the f-statistic and p-value in the implemented anova table: These are
# not as expected!
tuple(anova_lm(reduced, full).ix[1, 'F':]) # 696.84446608239034, 3.0255035879658417e-31

import statsmodels.api as sm
sm.version.full_version # 0.6.1
```

Either I have misunderstood the intention of the function anova_lm (which I think I don't) or there is a bug in this function.

[1] http://statsmodels.sourceforge.net/stable/examples/notebooks/generated/interactions_anova.html

PS. Sorry, haven't had the time yet, to install the github-master version of statsmodels.

**Comment by josef-pkt** [comment]
Can you check what result you get if you replace division by `reduced.ssr` with division by `full.ssr`?

IIRC it should use the full or largest ssr in  the denominator.

This is based on a quick look. If that's not the reason, then I need to look more closely later today.

**Comment by 00tau** [comment]
You have remembered the formula correctly ... sorry for the fuss.

```
# Calculate the p-value by hand
#fstats = (reduced.ssr - full.ssr) / (reduced.df_resid - full.df_resid) / (reduced.ssr / reduced.df_resid)
fstats = (reduced.ssr - full.ssr) / (reduced.df_resid - full.df_resid) / (full.ssr / full.df_resid)
pvalue = 1 - f.cdf(fstats, dfn=(reduced.df_resid - full.df_resid), dfd=full.df_resid)
print(fstats, pvalue) # 1.99124697884 0.179151390274
```

**Comment by 00tau** [comment]
Just realised that this still doesn't yield the correct result!

**Comment by josef-pkt** [comment]
What's the conclusion? Why the last discrepancy?
given that you closed it again

**Comment by 00tau** [comment]
I typed to fast. I do get the same f-statistic but a different p-value.

**Comment by 00tau** [comment]
Just a note for why I got a different p-value in the example. The discrepancy in p-values appears as for large f-test values the survival function and '1-cdf' are not numerical  equivalent for large 2nd-degrees of freedom.

```
from scipy.stats import f

# These yield the same values
1 - f.cdf(500, 5, 10)
f.sf(500, 5, 10)

# These are don't. anova_lm implements f.st.
1 - f.cdf(500, 5, 30)
f.sf(500, 5, 30)
```
