### ISSUE TITLE
@.tsa.statespace.MLEModel Param bug: unexpected keyword arg complex_step

### ISSUE THREAD

**Issue by CrystalCastle92** [statsmodels/statsmodels#2970]
Hey i've fixed the issue locally (as in my application i am not passing this param) but complex_step is not a guaranteed arg yet is not checked for in the below modified method call, hope this helps.

version 0.8.0

mlemodel.py @640
        # NM: here i go dicking around in base code ....
        # self.update(params, transformed=True, complex_step=complex_step) complex_step is not guaranteed 
        self.update(params, transformed=True)

**Comment by ChadFulton** [comment]
Thanks for the bug report! I can't duplicate it though, can you give an example? Based on the if-else block above, it looks like `complex_step` should always be set.

**Comment by gmanser** [comment]
I had the same problem when using tsa.statespace.MLEModel -> TypeError: update() got an unexpected keyword argument 'complex_step'

The error occurs when working through these examples:
The AR(2) example here: http://www.statsmodels.org/dev/statespace.html

Bayesian example here: http://pages.uoregon.edu/cfulton/posts/state_space_mh.html

But not this example:
Local linear trend: http://www.statsmodels.org/dev/examples/notebooks/generated/statespace_local_linear_trend.html

**Comment by juneshuoyang** [comment]
@CrystalCastle92 Can you please let me know how you fixed issue locally? Thank you! I had the same bug -- unexpected keyword arg complex_step

**Comment by ChadFulton** [comment]
Hi, this is bug in the documentation, which hasn't been updated to reflect recent changes. The issue is that the `update` method must pass through `**kwargs` in the the super().update()` call. So for example, in the case of the AR(2) model in the official documentation, above, it currently reads:

```python
def update(self, params, transformed=True):
    params = super(AR2, self).update(params, transformed)
    # ...
```

it should instead read:

```python
def update(self, params, transformed=True, **kwargs):
    params = super(AR2, self).update(params, transformed, **kwargs)
    # ...
```

that's because `complex_step` is now a keyword argument passed to `update`.

**Comment by juneshuoyang** [comment]
@ChadFulton Thanks for the note. I am working on the example on page 26 of the documentation.
def update(self, params, transformed=True, **kwargs):
      params = super(BaseMLELocalLevel, self).update(params, transformed, **kwargs)
After doing the similar thing you suggested, the error msg becomes: filter() got an unexpected keyword argument 'complex_step'

p.s. I find your documentation is pretty useful, as I am learning ssm thru Koopman's book and trying some hands-on projects thru your written guidance. I would appreciate it if this is a sound resolution to this issue. Thanks!

**Comment by ChadFulton** [comment]
You need two asterisks: `**kwargs` is correct, `*kwargs` is not.

Glad to hear that this is useful to you.

**Comment by juneshuoyang** [comment]
@ChadFulton Thanks for the prompt response first. I did ** in my code. Sorry, typo in my comment. But the filter() error comes in.

p.s. Yay. I like the way you illuminated Posterior Simulation and the reference you mentioned! Thanks.

**Comment by ChadFulton** [comment]
I see. If you're implementing the `filter` and `smooth` methods, they also require including a `**kwargs` argument and passing it to any `super` calls, that should fix your issue.

**Comment by juneshuoyang** [comment]
@ChadFulton Thank you for your response. The fact is that I only want to use .loglike for posterior simulation and .update. But, maybe in the packages, these two functions invoke other functions like filter function? I have mastery in other programming languages. It's my first time to touch python and have no clue how to solve this problem as a whole. Do you think editing the script in the package or download a previous version of statsmodels can help? I am in the midst of a research project and when I started learning ssm I thought your package documentation is the most informational one I could find. I would really appreciate your thought on this matter. Thanks.

**Comment by ChadFulton** [comment]
Can you post your code as well as the exact statsmodels version you're using?

**Comment by juneshuoyang** [comment]
@ChadFulton The code is exact what is written in page 26 (BaseMLELocalLevel) of the documentation. I installed development version of statsmodels thru the way you recommended in Appendix A. I installed them on Oct 14. Also, during the loading process, this happened:
File "/Users/zsx/py2june/exe/python3/lib/python3.5/site-packages/dismalpy/ssm/compat/dynamic_factor.py", line 21, in <module>
    from statsmodels.tools.pca import PCA
ImportError: No module named 'statsmodels.tools.pca'
I removed the line 21 in the listed file. Then dismalpy can then be loaded successfully.

**Comment by ChadFulton** [comment]
Hi, that documentation is for a package that was used as a stop-gap while the features became mature enough for inclusion to statsmodels itself. Everything in that package has now been included in statsmodels, although I haven't updated the documentation.

The main change is that everywhere you see `dp.ssm` you should replace it with `sm.tsa.statespace` (assuming you did `import statsmodels.api as sm`)

**Comment by jbrockmendel** [comment]
@ChadFulton is this closable?  if not, is it actionable?

**Comment by ChadFulton** [comment]
Thanks @jbrockmendel, I think this is closeable, but can be reopened if necessary.
