### ISSUE TITLE
FAQ/BUG: segfault in matplotlib with vector_ar and others

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#2976]
this test segfaults for me consistently when running the tsa test suite
`statsmodels.tsa.vector_ar.tests.test_var.TestVARResults.test_plot_cum_effects`
latest WinPython with python 3.4.4, `WinPython-64bit-3.4.4.2` which has matplotlib 1.5.1
Windows 8.2

VAR is all in Python, so there shouldn't be a segfault from our side.

(Before that I got a "kernel died" in the notebook that I'm preparing, but that could possible be my problem with ARMA compilation.)

matplotlib has been segfaulting for about a year on my two computers in several functions and unit tests.

running the unittests for statsmodels.graphics it segfaults at

```
statsmodels.graphics.tests.test_gofplots.TestTopLevel.test_qqplot_2samples_ProbP
lotObjects ... alloc: invalid block: 0000000013632B40: a0 13
```

**Comment by josef-pkt** [comment]
There is something **fishy** with closing plots in matplotlib.
I added many `plt.close('all')` to the unit tests that segfault in #3158
Now the test suite finishes without segfault.

**Comment by bashtage** [comment]
@josef-pkt I think this is fixed.

**Comment by josef-pkt** [comment]
#4913 uses agg backend for all plotting unit tests which doesn't segfault on my computer even if plots are not immediately closed.
