### ISSUE TITLE
Cannot insantiate md.tsa.kalmanf.kalmanfilter.StateSpaceModel

### ISSUE THREAD

**Issue by DeliciousHair** [statsmodels/statsmodels#2983]
```
In [24]: sm.version.full_version
Out[24]: '0.6.1'
```

I only just 'discovered' this module today, so sorry if this is a really dumb question but...

To help understand the ins and outs of this module I have been looking at `statsmodels/statsmodels/tsa/kalmanf/kalmanfilter.py`, and discovered this:

```
class StateSpaceModel(object):
    """
    <snip>
    """
    def __init__(self, endog, exog=None, **kwargs):
        dict.__init__(self, kwargs)
        self.__dict__ = self
```

which ends up failing exactly as I would expect it to (MWE):

```
import numpy as np

dummy_data = np.arange(100)

dummy_model= sm.tsa.kalmanf.kalmanfilter.StateSpaceModel(dummy_data)

```
Which leads to the error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-40-e1cbc13cebc0> in <module>()
----> 1 dummy_model = sm.tsa.kalmanf.kalmanfilter.StateSpaceModel(dummy_data)

/usr/local/lib/python3.4/dist-packages/statsmodels/tsa/kalmanf/kalmanfilter.py in __init__(self, endog, exog, **kwargs)
    277     """
    278     def __init__(self, endog, exog=None, **kwargs):
--> 279         dict.__init__(self, kwargs)
    280         self.__dict__ = self
    281 

TypeError: descriptor '__init__' requires a 'dict' object but received a 'StateSpaceModel'
```

Am I totally missing something here? It is quite possible

**Comment by josef-pkt** [comment]
Note, this is the old version of the kalmanfilter and it is only used for ARMA/ARIMA, and AFAIK has never been really generalized.

The new version which is a very general framework for linear statespace models and with several models already on top of it, is not in the 0.6.1 release, and you would need to use master.
documentation is here http://www.statsmodels.org/dev/statespace.html
some example notebooks are here http://www.statsmodels.org/dev/examples/index.html#statespace and the notebooks are in the source under `docs\example\notebooks`

**Comment by DeliciousHair** [comment]
Ah, OK--upgrading to master now and leaving this confusion behind :-)

Thanks!
