### ISSUE TITLE
How far is a release of 0.7.0 away?

### ISSUE THREAD

**Issue by springcoil** [statsmodels/statsmodels#2990]
Just a general question - how far is a release of 0.7.0 away?

**Comment by bashtage** [comment]
Skipping 0.7.0 and going to 0.8.0.  When 0.8.0 happens is another question...

**Comment by springcoil** [comment]
Can someone answer that one?

**Comment by bashtage** [comment]
Only @josef-pkt knows.

**Comment by josef-pkt** [comment]
I think we try to get ready for an `rc1` by next weekend, or Monday in a week. (After that I will not have much time or not enough internet time for a month while I'm in Europe.)

AFAICS we don't have any release blockers anymore. Testing on various machines also is almost all green. There are several smaller fixes that should still go in. And a few larger things can still go in if they get ready for merging. The rest we just postpone or we will never get a release.

**Comment by springcoil** [comment]
Agreed - :+1: for that. I didn't see any release blockers, and a release
candidate helps improve interest.

On Sun, Jun 12, 2016 at 4:39 PM, Josef Perktold <notifications@github.com>
wrote:

> I think we try to get ready for an rc1 by next weekend, or Monday in a
> week. (After that I will not have much time or not enough internet time for
> a month while I'm in Europe.)
>
> AFAICS we don't have any release blockers anymore. Testing on various
> machines also is almost all green. There are several smaller fixes that
> should still go in. And a few larger things can still go in if they get
> ready for merging. The rest we just postpone or we will never get a release.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/statsmodels/statsmodels/issues/2990#issuecomment-225438553>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA8DiCdDnetPIJK-2aHIYv2iXw1zqK4Kks5qLBongaJpZM4Iv42L>
> .
>



-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by bashtage** [comment]
@springcoil 0.8rc1 has been tagged and should make its way to PyPI.  Still a while until 0.8 (month)

**Comment by jbrockmendel** [comment]
Can this be closed?

**Comment by bashtage** [comment]
Hope so.  @josef-pkt

**Comment by josef-pkt** [comment]
thanks for the reminder
