### ISSUE TITLE
Unused variable maparam

### ISSUE THREAD

**Issue by AshishBora** [statsmodels/statsmodels#2998]
maparam defined in [3] [here](http://statsmodels.sourceforge.net/stable/examples/notebooks/generated/tsa_arma_1.html) seems unused.

Possible intended usage is
`maparams = np.r_[1, maparams]`

**Comment by josef-pkt** [comment]
It took me a long time to figure out what you mean: missing `s` in `maparams`

Yes, that's a typo.

The process is still an ARMA, and however ARMA(2, 1) 
sd of innovation 0.65, and ma coefficient 0.54 which is close to the results in the summary

Thanks, do you want to open a PR to fix it?

**Comment by AshishBora** [comment]
Sure. I have created a PR. Thanks.
