### ISSUE TITLE
ImportError: No module named 'statsmodels.tsa.statespace'

### ISSUE THREAD

**Issue by deepnadevkar** [statsmodels/statsmodels#3010]
I am trying to fit an Unobserved Components model and am following the example here: 
http://nbviewer.jupyter.org/gist/ChadFulton/9ec4aaa13841bbdbe4df/

But, when I run this --> from statsmodels.tsa.statespace import structural <-- I am getting an import error:
ImportError: No module named 'statsmodels.tsa.statespace'

I have tried uninstalling and re-installing statsmodels and it didn't help. If I just import statsmodels.api as sm, I get no errors. Also, other models within statsmodels have worked just fine. 

Please help ASAP! 

Thanks!

**Comment by josef-pkt** [comment]
This requires statsmodels master, It is not in statsmodels 0.6.1

You need to upgrade if your are using 0.6.1

**Comment by deepnadevkar** [comment]
Thanks for your prompt response! I upgraded to statsmodels-0.7.0. Now when I try to run the same line of code: from statsmodels.tsa.statespace import structural, I am getting a different error:
ImportError: cannot import name 'structural'

Your help is much appreciated! 

Thanks

**Comment by ChadFulton** [comment]
Please update to the master branch, which should be statsmodels-0.8.0

**Comment by deepnadevkar** [comment]
That worked! Thanks so much!

**Comment by ChadFulton** [comment]
Great!
