### ISSUE TITLE
Unobserved Components Model -- issue with out-of-sample forecasting using get_predictions() and forecasts

### ISSUE THREAD

**Issue by deepnadevkar** [statsmodels/statsmodels#3011]
Hi there,

I am using an unobserved components model to predict something over time. The model seemed to fit well, but when I am using the following code to make predictions, I am getting an error:
The code is below:

%matplotlib inline
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(10,4))

# Perform dynamic prediction and forecasting
ndynamic = 5
predict_res = res.predict(alpha=0.05, dynamic=endog['Total Minutes_Amazon'].shape[0]-ndynamic, full_results=True)

predict = predict_res.forecasts
cov = predict_res.forecasts_error_cov

I am getting an AtrributeError:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-fec3e115e09f> in <module>()
      7 predict_res = res.predict(alpha=0.05, dynamic=endog['Total Minutes_Amazon'].shape[0]-ndynamic, full_results=True)
      8 
----> 9 predict = predict_res.forecasts()
     10 cov = predict_res.forecasts_error_cov
     11 

//anaconda/lib/python3.5/site-packages/pandas/core/generic.py in __getattr__(self, name)
   2358                 return self[name]
   2359             raise AttributeError("'%s' object has no attribute '%s'" %
-> 2360                                  (type(self).__name__, name))
   2361 
   2362     def __setattr__(self, name, value):

AttributeError: 'Series' object has no attribute 'forecasts'

Please advice on how to get both in-sample predictions and out-of-sample forecasts. 
Thank you!

**Comment by ChadFulton** [comment]
Thanks for the report. The `full_results=True` specification for `predict` is no longer used. Instead, you'll want to use `get_prediction()` which will provide you with a prediction object that includes the forecast and the standard errors. So you will want to do something like:

```python
predict = res.get_prediction(dynamic=endog['Total Minutes_Amazon'].shape[0] - ndynamic)
predict = predict.predicted_mean
se = predict.se_mean
```

I know I have some old notebooks out there which still have the `full_results` specification - can you let me know which one you're looking at so that I can fix it?

**Comment by deepnadevkar** [comment]
Ah that makes sense. The predict.predicted_mean worked and gave forecasts for each time point, but the predict.se_mean raised an error. I checked out the documentation again, but didn't find anything that worked in order to get the standard errors. Could you please check to see what exactly it is now called? 

Also, the notebook that I was referencing is here: http://pages.uoregon.edu/cfulton/posts/state_space_python.html

I am trying to create that exact plot that you have at the end, but would also like to add my out-of-sample forecasts to it. 

Thanks again for all the great work! This package is so much better than the R version.

**Comment by deepnadevkar** [comment]
Actually, the se_mean worked as well. It was an error on my part!

**Comment by ChadFulton** [comment]
Great! Glad you are finding the package useful. Please let us know if you find any more bugs or if there are improvements that occur to you. I've also updated the page at that link to have correct code.

Thanks.
