### ISSUE TITLE
Unobserved Components Model -- issue with out-of-sample forecasting 

### ISSUE THREAD

**Issue by deepnadevkar** [statsmodels/statsmodels#3065]
Hi there,

I was able to make one-step ahead predictions with this model using the get_predictions() method. I also need to make out-of-sample forecasts. My in-sample data is weekly. The head of the dataframe looks like this:

![screen shot 2016-06-21 at 2 37 26 pm](https://cloud.githubusercontent.com/assets/11262596/16241890/ca2401ba-37bd-11e6-8a22-b2eff5c47cb0.png)

When I used the get_forecast(steps = 12) to make forecasts for 12 weeks into the future, I am getting the following error:

forecast = res.get_forecast(steps = 12)
Error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-161-6f6d53569a20> in <module>()
----> 1 forecast = res.get_forecast(steps = 12)

//anaconda/lib/python3.5/site-packages/statsmodels-0.8.0-py3.5-macosx-10.5-x86_64.egg/statsmodels/tsa/statespace/mlemodel.py in get_forecast(self, steps, **kwargs)
   2313         else:
   2314             end = steps
-> 2315         return self.get_prediction(start=self.nobs, end=end, **kwargs)
   2316 
   2317     def predict(self, start=None, end=None, dynamic=False, **kwargs):

//anaconda/lib/python3.5/site-packages/statsmodels-0.8.0-py3.5-macosx-10.5-x86_64.egg/statsmodels/tsa/statespace/mlemodel.py in get_prediction(self, start, end, dynamic, **kwargs)
   2257 
   2258         # Handle start and end (e.g. dates)
-> 2259         start = self.model._get_predict_start(start)
   2260         end, out_of_sample = self.model._get_predict_end(end)
   2261 

//anaconda/lib/python3.5/site-packages/statsmodels-0.8.0-py3.5-macosx-10.5-x86_64.egg/statsmodels/tsa/base/tsa_model.py in _get_predict_start(self, start)
    132                         (str(start), str(dtstart)))
    133 
--> 134         self._set_predict_start_date(start)
    135         return start
    136 

//anaconda/lib/python3.5/site-packages/statsmodels-0.8.0-py3.5-macosx-10.5-x86_64.egg/statsmodels/tsa/base/tsa_model.py in _set_predict_start_date(self, start)
    107         if start == len(dates):
    108             self.data.predict_start = datetools._date_from_idx(dates[-1],
--> 109                                                     1, self.data.freq)
    110         elif start < len(dates):
    111             self.data.predict_start = dates[start]

//anaconda/lib/python3.5/site-packages/statsmodels-0.8.0-py3.5-macosx-10.5-x86_64.egg/statsmodels/tsa/base/datetools.py in _date_from_idx(d1, idx, freq)
     77     offset. For now, this needs to be taken care of before you get here.
     78     """
---> 79     return d1 + idx * _freq_to_pandas[freq]
     80 
     81 def _idx_from_dates(d1, d2, freq):

TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

Could you please help? 

Thanks!

**Comment by ChadFulton** [comment]
I can't replicate, so I'm guessing there's some frequency issue here. What is the frequency of the DataFrame index?

**Comment by ChadFulton** [comment]
Also please post the code you're using to instantiate the model so I can see what the specification is.

**Comment by ChadFulton** [comment]
Clearly a bug somewhere, though, thanks for reporting it.

**Comment by deepnadevkar** [comment]
The freq of the date index is 7 days (weekly). I posted a screenshot of my dataframe in case you wanted to see it. I am using the following code to instantiate a local level model:

![screen shot 2016-06-22 at 10 09 13 am](https://cloud.githubusercontent.com/assets/11262596/16269763/a61a8b6e-3861-11e6-812b-ec2d338dfcf5.png)

The diagnostic and components plots look like this:

![screen shot 2016-06-22 at 10 09 33 am](https://cloud.githubusercontent.com/assets/11262596/16269771/b893e0d8-3861-11e6-9978-63bf7beee389.png)

![screen shot 2016-06-22 at 10 09 48 am](https://cloud.githubusercontent.com/assets/11262596/16269777/c567ff2e-3861-11e6-92d3-0d6ecc993ea8.png)

Finally, I also tried using the get_prediction() method to get both in-sample and out-of-sample predictions. This method doesn't raise an error, but as you will see in the plot below, something doesn't seem right. First of all, it fits the in-sample observations EXACTLY without any prediction error. And secondly, the out-of-sample forecasts are all the exact same value, which doesn't seem right either. 

![screen shot 2016-06-22 at 10 10 38 am](https://cloud.githubusercontent.com/assets/11262596/16269851/16b6ff10-3862-11e6-80a9-7a11b334dfa0.png)

I would really appreciate your help! Sorry for keep on bugging you with this model. 

Thanks!!

**Comment by ChadFulton** [comment]
Please let me know the result of:

```python
print(data.index.freq)
```

Also, since your model is just a random walk, the results you're seeing aren't surprising. The model itself has no real predictive power - it's just saying that the process follows a random walk, so the best guess of tomorrow is just whatever happened today.

What should be happening is that the predicted series should be a lagged version of the data series. I can't quite tell from the code you posted, but I'm guessing that you haven't put the the right date index for the predictions.

Try doing:

```python
print(predictions.head())
print(data['Total Minutes_Amazon'].head())
```

**Comment by deepnadevkar** [comment]
Okay, the result of print(data.index.freq) was None.

Also,

![screen shot 2016-06-22 at 11 37 10 am](https://cloud.githubusercontent.com/assets/11262596/16272960/b5c25aae-386d-11e6-8c43-01986cd67100.png)

Yes, I'm still trying to understand the nuances of the model and the parameters. Thanks again!

**Comment by ChadFulton** [comment]
I'll take another look at this in an hour or two. In the meantime, can you try reindexing your data to actually have a weekly frequency (i.e. so data.index.freq is no longer None) and see if that works? I'm guessing the problem here has to do with a frequency of None confusing the code.

**Comment by deepnadevkar** [comment]
Ah, that worked!! Thanks so much and sorry for all the trouble. I will work on fine-tuning my model now to get the best fit. :)

**Comment by ChadFulton** [comment]
Great! This is definitely a bug, and I appreciate you reporting it.

From a brief look, I think it used to be the case that Pandas data without a frequency used to raise an error when the model was instantiated, but something changed in recent Pandas versions so that's no longer true.

**Comment by deepnadevkar** [comment]
I see, well thanks for clarifying!

**Comment by auvo1001** [comment]
Hello, just FYI, I encountered the same problem with SARIMAX. I'd report it here so that the fix could also be applied there. Thanks.

**Comment by Anupama7** [comment]
@ChadFulton please look once at my code and help me out.
Thanks in advance :)

**Comment by ChadFulton** [comment]
Can you post a replicable example? It's hard to know what's going on just from seeing the code.

Also, what version of Statsmodels are you using?
