### ISSUE TITLE
Logic swapped for cooks distance/dffits in influence_plot?

### ISSUE THREAD

**Issue by jspeis** [statsmodels/statsmodels#3103]
I was looking at the [code for influence_plot] (https://github.com/statsmodels/statsmodels/blob/6903819080ea2ddddcf2cb4aca20ecb1cfbfe35e/statsmodels/graphics/regressionplots.py#L765-768)

and I happened to notice the following block:
```python
    if criterion.lower().startswith('dff'):
        psize = infl.cooks_distance[0]
    elif criterion.lower().startswith('coo'):
        psize = np.abs(infl.dffits[0])
```

but should that be the other way around? i.e.:

```python
    if criterion.lower().startswith('dff'):
        psize = np.abs(infl.dffits[0])
    elif criterion.lower().startswith('coo'):
        psize = infl.cooks_distance[0]
```

**Comment by josef-pkt** [comment]
Thanks for finding and reporting.  (I don't know why I didn't reply during my vacation.)
I'm fixing this this week for 0.8
