### ISSUE TITLE
SARIMAX predict ValueError : Wrong number of items passed xxx, placement implies yyy

### ISSUE THREAD

**Issue by updiversity** [statsmodels/statsmodels#3105]
Not sure if this is a bug or a wrong usage of the "predict" method.

When I train the model, everything looks to work properly

```
mod = tsa.statespace.SARIMAX(prodn, order=(0,1,0), seasonal_order=(0,0,1,12))
results = mod.fit()
print (results.summary())
```

> 
>                                  Statespace Model Results                                 
> ==========================================================================================
> Dep. Variable:                                  y   No. Observations:                  372
> Model:             SARIMAX(0, 1, 0)x(0, 0, 1, 12)   Log Likelihood                -788.613
> Date:                            Wed, 13 Jul 2016   AIC                           1581.226
> Time:                                    09:04:31   BIC                           1589.064
> Sample:                                01-01-1970   HQIC                          1584.339
>                                      - 01-01-1970                                         
> Covariance Type:                              opg                                         
> ==============================================================================
>                  coef    std err          z      P>|z|      [0.025      0.975]
> ------------------------------------------------------------------------------
> ma.S.L12       0.6292      0.041     15.520      0.000       0.550       0.709
> sigma2         4.0434      0.248     16.320      0.000       3.558       4.529
> ===================================================================================
> Ljung-Box (Q):                      458.03   Jarque-Bera (JB):                45.00
> Prob(Q):                              0.00   Prob(JB):                         0.00
> Heteroskedasticity (H):               3.41   Skew:                            -0.59
> Prob(H) (two-sided):                  0.00   Kurtosis:                         4.23
> ===================================================================================
> 
> Warnings:
> [1] Covariance matrix calculated using the outer product of gradients (complex-step).
> 

However, when I try to get some predictions

`
results.predict()
`

I got this error message:

[---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-93-9788863e7ccb> in <module>()
----> 1 results.predict()

/home/vagrant/.virtualenvs/venvpy3/lib/python3.4/site-packages/statsmodels/base/wrapper.py in wrapper(self, *args, **kwargs)
     93             obj = data.wrap_output(func(results, *args, **kwargs), how[0], how[1:])
     94         elif how:
---> 95             obj = data.wrap_output(func(results, *args, **kwargs), how)
     96         return obj
     97 

/home/vagrant/.virtualenvs/venvpy3/lib/python3.4/site-packages/statsmodels/tsa/statespace/sarimax.py in predict(self, start, end, exog, dynamic, **kwargs)
   1919 
   1920         return super(SARIMAXResults, self).predict(
-> 1921             start=start, end=end, exog=exog, dynamic=dynamic, **kwargs
   1922         )
   1923 

/home/vagrant/.virtualenvs/venvpy3/lib/python3.4/site-packages/statsmodels/tsa/statespace/mlemodel.py in predict(self, start, end, dynamic, **kwargs)
   2352         # Perform the prediction
   2353         prediction_results = self.get_prediction(start, end, dynamic, **kwargs)
-> 2354         return prediction_results.predicted_mean
   2355 
   2356     def forecast(self, steps=1, **kwargs):

/home/vagrant/.virtualenvs/venvpy3/lib/python3.4/site-packages/statsmodels/base/wrapper.py in __getattribute__(self, attr)
     39             obj = data.wrap_output(obj, how[0], *how[1:])
     40         elif how:
---> 41             obj = data.wrap_output(obj, how=how)
     42 
     43         return obj

/home/vagrant/.virtualenvs/venvpy3/lib/python3.4/site-packages/statsmodels/base/data.py in wrap_output(self, obj, how, names)
    411             return self.attach_cov(obj)
    412         elif how == 'dates':
--> 413             return self.attach_dates(obj)
    414         elif how == 'columns_eq':
    415             return self.attach_columns_eq(obj)

/home/vagrant/.virtualenvs/venvpy3/lib/python3.4/site-packages/statsmodels/base/data.py in attach_dates(self, result)
    549         # May be zero-dim, for example in the case of forecast one step in tsa
    550         if squeezed.ndim < 2:
--> 551             return Series(squeezed, index=self.predict_dates)
    552         else:
    553             return DataFrame(result, index=self.predict_dates,

/home/vagrant/.virtualenvs/venvpy3/lib/python3.4/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    227                                        raise_cast_failure=True)
    228 
--> 229                 data = SingleBlockManager(data, index, fastpath=True)
    230 
    231         generic.NDFrame.__init__(self, data, fastpath=True)

/home/vagrant/.virtualenvs/venvpy3/lib/python3.4/site-packages/pandas/core/internals.py in __init__(self, block, axis, do_integrity_check, fastpath)
   3815         if not isinstance(block, Block):
   3816             block = make_block(block, placement=slice(0, len(axis)), ndim=1,
-> 3817                                fastpath=True)
   3818 
   3819         self.blocks = [block]

/home/vagrant/.virtualenvs/venvpy3/lib/python3.4/site-packages/pandas/core/internals.py in make_block(values, placement, klass, ndim, dtype, fastpath)
   2516                      placement=placement, dtype=dtype)
   2517 
-> 2518     return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
   2519 
   2520 # TODO: flexible with index=None and/or items=None

/home/vagrant/.virtualenvs/venvpy3/lib/python3.4/site-packages/pandas/core/internals.py in __init__(self, values, placement, ndim, fastpath)
     88             raise ValueError('Wrong number of items passed %d, placement '
     89                              'implies %d' % (len(self.values),
---> 90                                              len(self.mgr_locs)))
     91 
     92     @property

ValueError: Wrong number of items passed 372, placement implies 371
](url)

**Comment by ChadFulton** [comment]
Thanks for the report. I can't seem to replicate it myself doing:

```python
import numpy as np
import pandas as pd
import statsmodels.api as sm

index = pd.date_range('1970-01-01', periods=100, freq='T')
x = pd.Series(np.random.normal(size=100), index=index)
mod = sm.tsa.SARIMAX(x, order=(0,1,0), seasonal_order=(0,0,1,12))
res = mod.fit()
res.predict()
```

Can you describe your data a little bit more, or if possible give an example of data / code that throws the exception? Thanks!

**Comment by updiversity** [comment]
Hi,

using your example, if I don't specify a date range index:  

`
x = pd.Series(np.random.normal(size=100))
`

I got the same error message. Does it means that I am forced to specify an index in that way ? I was not expecting it but this is fine.

Thanks for the quick reply

**Comment by ChadFulton** [comment]
This is another instance of #3068. Thanks for the report!
