### ISSUE TITLE
No Confidence Intervals for SARIMAX Forecast

### ISSUE THREAD

**Issue by benjaminbelmudez** [statsmodels/statsmodels#3108]
Hey,

I am using the function SARIMAX from statsmodels 0.8.0 with an exogenous variable. It seems that the methods get_prediction() and subsequently conf_int() do not work out-of-the box when used with an exogenous variable, is that correct?

I get the following error message: "ValueError: Forecasting for models with time-varying obs_intercept matrix requires an updated time-varying matrix for the period to be forecasted."

**Comment by ChadFulton** [comment]
Thanks for this report! This is definitely a bug, and it needs to be fixed before 0.8 is released.
