### ISSUE TITLE
FAQ: Time series support in Statsmodels

### ISSUE THREAD

**Issue by pcdinh** [statsmodels/statsmodels#3109]
Hi,

I learned from /r/datascience 

> I didn't know they finally added SARIMA support to statsmodels. That being said, having time series support with just ARIMA and basic exponential smoothing is like having a standard statistics package with nothing but standard linear and logistic regression. There's basically no support for ARCH and GARCH models, no support for incorporating transfer functions, and no support for multiple seasonal trends. Although somehow, R doesn't have support for the last one either but SAS does.

https://www.reddit.com/r/datascience/comments/4siy0n/learning_time_series_analysis/d5cbp3c

I am quite new to statsmodels. Is his statement true to current features of statsmodels? If it is the case, is the any plan to support the missing parts?

Thanks

**Comment by ChadFulton** [comment]
There are some true things about that statement and some false things, as
well as a dose of that commenter's opinions. Here's an update on the
Statsmodels time series library.

- The emphasis in econometric time series generally is on ARIMA models, and
they're used a huge amount.
- Statsmodels v0.6.x also has support for VAR models, which are again huge
workhorses in econometric time series.
- I don't know the whole story here, but ARCH and GARCH are implemented in
the "arch" package by one of the major statsmodels contributors. I'm not
sure why it's not in Statsmodels itself, but does it need to be? Not all of
R time series is in a single package.
- The commenter seems to think that transfer functions and multiple
seasonal trends are very important time series models, and maybe they are
in some particular discipline, but they're not universally considered to be
basic models everyone must support. Stata, for example, doesn't support
them (except through their state space framework, but see below).

Starting with v0.8 (which has a release candidate out, and hopefully will
be released in August), statsmodels will get:

- SARIMAX models, as the commenter noted
- A general framework for state space models; this can incorporate any
linear / Gaussian time series model you want, including transfer functions
and multiple seasonal trends.
- Unobserved components, dynamic factors, and VARMAX models.
- Also, introduced are Markov switching regressions and autoregressions,
which are non-linear Gaussian models. This is a good example of something
that is quite hard to find implemented in R.

In the future (v0.9?), we can expect:

- Markov switching state space models, which opens up a huge range of
non-linear Gaussian models

So ultimately, I think Statsmodels will very soon incorporate a huge range
of important time series models. On the other hand, I'm sure that for
certain disciplines there are specific models which are not implemented. Of
course we would be delighted to get contributions from individuals in those
fields!

Chad

**Comment by josef-pkt** [comment]
I think the last paragraph of Chad is a good summary. Time series is now one of the strong areas in statsmodels with pretty good coverage of models. But as in all groups of models, there is always a large number of features still missing. How soon new features are added depends on the availability of contributors/contributions and on our priorities.

> no support for incorporating transfer functions, and no support for multiple seasonal trends

one point is that we don't have SARIMA, we have SARIMAX, which means transfer functions and multiple seasonal trends are not build-in but can to a large extend be written on top of it. IIRC, Hyndman hat a post about using fourier series or similar to model multiple seasonal trends, especially if one of the season lengths is very large.

**Comment by bashtage** [comment]
Closing as answered.
