### ISSUE TITLE
BUG: t-test summary confidence interval range always shows [0.025      0.975]

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#3116]
Regardless of the given alpha, printed confidence interval range in t_test summary is [0.025      0.975], although the actual confidence interval itself does change appropriately.

Given:

```python
np.random.seed(1234)
endog, exog = np.random.normal(size=(2, 100))
res = sm.OLS(endog, exog).fit()
test_res = res.t_test('x1 = 0')
```

then

```python
print(test_res.summary(alpha=0.05))
```

produces:

                                 Test for Constraints                             
    ==============================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
    ------------------------------------------------------------------------------
    c0             0.0822      0.102      0.807      0.421      -0.120       0.284
    ==============================================================================

but:

```python
print(test_res.summary(alpha=0.482))
```

produces:

                                 Test for Constraints                             
    ==============================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
    ------------------------------------------------------------------------------
    c0             0.0822      0.102      0.807      0.421       0.010       0.154
    ==============================================================================

**Comment by ChadFulton** [comment]
Presumably in `contrast.py:L148` the call to `summary_params` needs to have the `alpha` argument:

```python
summ = summary_params((self, self.effect, self.sd, self.statistic,
                                   pvalues, self.conf_int(alpha)),
                                  yname=yname, xname=xname, use_t=use_t,
                                  title=title)
```

**Comment by josef-pkt** [comment]
Yes, `summary_params` and `summary_params_frame` have an `alpha` keyword which was left out.

**Comment by josef-pkt** [comment]
summary_params_frame doesn't use alpha in the column names, name is generic
`'Conf. Int. Low', 'Conf. Int. Upp.'`
