### ISSUE TITLE
Confusing code in KDEMultivariateConditional.pdf method disagrees with documentation

### ISSUE THREAD

**Issue by fsaad** [statsmodels/statsmodels#3118]
In the function [kernel_density.KDEMultivariateConditional.pdf](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/nonparametric/kernel_density.py#L481-L531) there is disagreement between the documentation, which uses `f(X|Y) = f(X,Y)/f(Y)` and the code, which is computing `f(X,Y)/f(X)`. Now, lines 526-528 do suggest that the denominator is the right value (the pdf of the exogenous variables) so it might be worth clarifying the situation.

**Comment by josef-pkt** [comment]
Thanks for reporting, Do you want to open a PR to fix it?

It looks like a mistake in the documentation in the pdf method. The class docstring has the correct conditional p(y|x).
The documentation should also mention that y is endog and x is exog in the method arguments,.
