### ISSUE TITLE
datetime conflict with matplotlib

### ISSUE THREAD

**Issue by ocehugo** [statsmodels/statsmodels#3121]
Hi, just reposting this from the matplotlib issue 6796.

[ 1.5.1 , 3.5, OSX] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
[ pip ] How did you install Matplotlib and Python (pip, anaconda, from source ...)
[0.6.1] statsmodels

The issue is that the import of statsmodels break compatibility with standard matplotlib plotting, since statsmodels overwrite the datetime namespace (or Pandas). This cause the following bug when using the Pandas datetime.

```python
TypeError: float() argument must be a string or a number, not 'datetime.date'
```

How to reproduce:
```python
import datetime
import matplotlib.pyplot as plt
import statsmodels.api as sm

#this works
x = [datetime.date(1678,1,1) + datetime.timedelta(days=i) for i in range(10)]
plt.plot(x,range(10))
#this do not
x = [datetime.date(1677,1,1) + datetime.timedelta(days=i) for i in range(10)]
plt.plot(x,range(10))
```

without the ```statsmodels.api as sm``` both lines works.

I would expect that just importing a function from the package would not override the defaults ones.

**Comment by ocehugo** [comment]
Hi just realize that this should be at pandas.

**Comment by josef-pkt** [comment]
cross-ref
https://github.com/matplotlib/matplotlib/issues/6796#issuecomment-233859722
https://github.com/pydata/pandas/issues/13713
