### ISSUE TITLE
DESIGN: Support for dates in tsa

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#3124]
Currently support for dates is functional in a couple of primary use cases, but I think has a large number of corner cases where the behavior is at least undocumented, but in many case raises exceptions, particularly during `forecast` calls. I can give details of some of these cases in a later post.

I was hoping to see if there was a consensus on what date support ought to look like. Some discussion is already available at #1345. Here are some notes on current behavior; I'll give more thoughts on my proposed solutions when I have time (tonight or this weekend), but I'm curious about others' thoughts

**Currently**:

First, `TimeSeriesModel` receives date information in three ways
1. If `endog` or `exog` is Pandas: it checks `self.data.row_labels`
2. It accepts the `dates` keyword argument for explicitly passing a date index
3. It accepts the `freq` keyword argument for explicitly passing a frequency.

With that information, it saves two model attributes:
- `self.data.dates`, which is a DatetimeIndex
- `self.data.freq`, which is a frequency string as defined by Pandas

`self.data.dates` is filled in first by checking the `dates` keyword; if that is not filled in, then  `self.data.row_lables` is attempted. In either case, it is coerced to a `DatetimeIndex` using `pandas.to_datetime`.
- **Question**: no warning or exception is given if `dates` keyword conflicts with the endog or exog index. Is this desired behavior?

`self.data.freq` is filled in first by checking the `freq` keyword; if that is not filled in, then it attempts to infer the frequency using `pandas.tseries.api.infer_freq`.
- **Question**: dates and freq can be set independent of each other; so `self.data.dates` could be a `DatetimeIndex` with frequency `'AS'` while `self.data.freq` could be e.g. `5T`. Is this desired behavior?
- **Question**: similarly, `self.data.dates` can be `None` and `self.data.freq` can be set, or vice-versa. Is this desired behavior?

Currently, the exceptions that Statsmodels explicitly raises are:
- If the `pandas.to_datetime` call raises a `ValueError`, then: `raise ValueError("Given a pandas object and the index does not contain dates")`
- With #3083, an exception would also be raised if, _prior_ to the `pandas.to_datetime` call, the dates object (either from the `dates` keyword argument or from `self.data.row_labels`) was a numeric index.
- If the `pandas.tseries.api.infer_freq` raises any exception, then: `raise ValueError("Frequency inference failed. Use freq keyword.")`

I believe the primary interface for _using_ the dates are the `_get_dates_loc`, `_get_predict_start`, and `_get_predict_end`, `_make_predict_dates` methods. (What I describe is the behavior assuming #3083 gets accepted):

`_get_dates_loc(self, dates, date)`: just a slim wrapper that returns `dates.get_loc(date)`.

`_get_predict_start(self, start)`: here, the documentation suggests that `start` can be a string or an integer (it's not clear what the behavior would be if it was a different type)
- Uses `self.data.dates` in the `_get_dates_loc` call to convert string `start` to integer index.
- Does not appear to use `self.data.freq`, except in the `datetools._date_from_idx` call within `_set_predict_start_dates`.

`_get_predict_end(self, end)`:
- Uses `self.data.dates` in the `_get_dates_loc` call to see if a string `start` is an integer index within the current dataset.
- Combines the last element of `self.data.dates` and `self.data.freq` to construct the new index.
- **Question**: I guess this is the possible use case for not requiring `self.data.dates` and `self.data.freq` to line up: as long as you have something called `freq` and some "end date", you can make an index for forecasted data.

**Comment by ChadFulton** [comment]
Here are some specific things it seems to me that we need to decide:

**Specific questions**:

1. Should we keep all three ways to specify dates?
2. If more than one specification is given, should we check for a conflict?
3. If there is a conflict, should a warning or exception be given?
4. If we allow `self.data.dates` and `self.data.freq` to be potentially different, what are the roles for each of those objects?
5. Should we allow Pandas indexes that are not dates? From our previous discussion, it seems clear that we should allow at the least monotonically increasing integer indexes, but what other ones? Should we allow arbitrary indexes? This is related to (6), below
6. What is the rule for creating new indexes for out-of-sample forecasts when we don't have nice indexes (by "nice" index, I mean either an integer index or a date index with a defined frequency)?

**Comment by ChadFulton** [comment]
Another question (that I guess partly depends on the answers to the other questions) is what deprecation / removal process should be used for this.

Part of the problem is that there are a large number of cases that currently have undocumented or inconsistent or "without warning" behavior, depending on the specific combination of the `endog` index and the `dates`, and `freq` keyword arguments.

**Comment by ChadFulton** [comment]
Another question:

(7) If we allow other types of Pandas indexes aside from `DatetimeIndex`, how do we know which Pandas indexes (taken from `self.data.row_labels`) should be coerced to `DatetimeIndex` (e.g. a Pandas index with date strings that hasn't been parsed yet) and which should be left alone (e.g. left as a "row labels" Pandas index)?

**Comment by josef-pkt** [comment]
@ChadFulton  Can you send the issue to the statsmodels mailing list and a message pointing to the discussion to the pydata/pandas mailing list?
@TomAugspurger  and others might have an opinion about this.

(I'm flying back to Montreal tomorrow and won't have time to think about this for at least a few days.)

My general opinion is: less magic in statsmodels and more explicit conversions by users.
that is, force users to disambiguate between datetimes with freq and arbitrary indices.

**Comment by josef-pkt** [comment]
another general comment:
The current version of date/time handling was written by Skipper mostly when date/times were still in the early stages in numpy and pandas.
If there is now "one obvious way" to specify datetimes, then the models wouldn't need to support lots of different conversions anymore.

**Comment by ChadFulton** [comment]
>  Can you send the issue to the statsmodels mailing list and a message pointing to the discussion to the pydata/pandas mailing list?

Good idea.

> My general opinion is: less magic in statsmodels and more explicit conversions by users.
that is, force users to disambiguate between datetimes with freq and arbitrary indices.

I agree with this also.

> another general comment:
The current version of date/time handling was written by Skipper mostly when date/times were still in the early stages in numpy and pandas.
If there is now "one obvious way" to specify datetimes, then the models wouldn't need to support lots of different conversions anymore.

I'm hopeful that this is the case and the state of Pandas / Numpy is now such that we can eliminate a lot of the handling we used to have to do.

**Comment by ChadFulton** [comment]
Cross reference #1345 for some discussion about the combination of date support when there are missing values.

**Comment by ChadFulton** [comment]
Here is a set of possible proposals that I have come up with: https://gist.github.com/ChadFulton/a550625ac5f7f3da228f523e8b395790

I lay out the situation as I understand it and describe 5 specific issues that I think need to be decided. For each of the 5 issues, I list some reasonable options that I was able to come up with.

- Most of the options for each issue are compatible with the options for the other issues, but some are incompatible (I try to note where they are).
- Most of the options have some degree of backwards-incompatible behavior; I think actually most of that is to-be-expected since the existing behavior is inconsistent.

Here are my preferences from most preferred to least preferred (as you will see, my most preferred options often err towards stricter behavior, Statsmodels doing less, and unfortunately to a somewhat higher degree of backwards incompatibility):

1. 1-strict, 1-strict-specify, 1-missing-freq (1-missing isn't really operable right now, would need more details)
2. 2-raise, 2-warn-limit, 2-warn-numpy (these are unnecessary if 1-strict-specify is adopted)
3. 3-pandas, 3-pandas-dates
4. 4-raise, 4-mostly-raise, 4-warn-precedence (these are unnecessary if 3-pandas is adopted)
5. 5-strict, 5-attempt-flag, 5-string-datetime, 5-attempt

If there are other good options I haven't thought of (surely there are) or problems with the proposed options, please let me know!

**Comment by josef-pkt** [comment]
I haven't thought about it yet enough. I just ran into integer/generic time index for Stata that I needed for a generic simulated dataset
`tsset idx, generic`

**Comment by ChadFulton** [comment]
See https://github.com/statsmodels/statsmodels/issues/3212#issuecomment-259772769 for another example of why a date overhaul is a good idea.

That issue can't easily be fixed because ARIMA models have defined some custom behavior to handle data without frequencies, but it doesn't apply to any other model and it makes it hard to alter the base behavior without breaking the custom ARIMA behavior.

**Comment by josef-pkt** [comment]
based on comment in 3268:

Chad, given that there wasn't any feedback, I think it is up to you. Given that you are now the main (only?) maintainer for time handling, I think you implement the solution that looks good or reasonable to you.
I'm pretty much out of the topic again, but your preferred strict version sounds good to me (without trying to think about all the details). We can always loosen up if there are specific use cases, but I think "strict" rules reduces the ambiguous guessing which ways are allowed.

**Comment by ChadFulton** [comment]
This was resolved in #3272.
