### ISSUE TITLE
Installation from source on archlinux

### ISSUE THREAD

**Issue by suleymanov** [statsmodels/statsmodels#3130]
Good afternoon,

I'm facing installation problems of the most recent version of statsmodels on Arch Linux. Here is my log:

Cythonizing sources
statsmodels/nonparametric/linbin.pyx has not changed
statsmodels/nonparametric/_smoothers_lowess.pyx has not changed
statsmodels/tsa/regime_switching/_hamilton_filter.pyx.in has not changed
statsmodels/tsa/kalmanf/kalman_loglike.pyx has not changed
statsmodels/tsa/statespace/_statespace.pyx.in has not changed
running build
running build_py
copying statsmodels/version.py -> build/lib.linux-x86_64-2.7/statsmodels
package init file 'statsmodels/tsa/vector_ar/data/__init__.py' not found (or not a regular file)
running build_ext
building 'statsmodels.tsa.regime_switching._hamilton_filter' extension
C compiler: gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -fPIC

compile options: '-I/usr/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c'
gcc: statsmodels/tsa/regime_switching/_hamilton_filter.c
In file included from /usr/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /usr/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from statsmodels/tsa/regime_switching/_hamilton_filter.c:274:
/usr/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: предупреждение: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-2.7/statsmodels/tsa/regime_switching/_hamilton_filter.o -L/usr/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/statsmodels/tsa/regime_switching/_hamilton_filter.so
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/../../../../lib/crti.o: нераспознанное перемещение (0x2a) в разделе «.init»
/usr/bin/ld: final link failed: Некорректное значение
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/../../../../lib/crti.o: нераспознанное перемещение (0x2a) в разделе «.init»
/usr/bin/ld: final link failed: Некорректное значение
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
error: Command "gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-2.7/statsmodels/tsa/regime_switching/_hamilton_filter.o -L/usr/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/statsmodels/tsa/regime_switching/_hamilton_filter.so" failed with exit status 1

Any help appreciated.

**Comment by bashtage** [comment]
Could be a libc bug. See

https://github.com/golang/go/issues/13678

Almost certainly something archlinux specific since it works on Ubuntu and RHEL.

**Comment by josef-pkt** [comment]
doesn't look like anything we can or need to do, closing
