### ISSUE TITLE
Confusion in documentation for `OLSResults`

### ISSUE THREAD

**Issue by mortonjt** [statsmodels/statsmodels#3131]
Looking at the `statsmodels.regression.linear_model.OLSResults.ess` object

The variables [`ess`](http://statsmodels.sourceforge.net/devel/generated/statsmodels.regression.linear_model.OLSResults.ess.html) and [`ssr`](http://statsmodels.sourceforge.net/devel/generated/statsmodels.regression.linear_model.RegressionResults.ssr.html) are a little confusing at first glance - particularly because there is no documentation on it.  Only after I started creating toy examples did I realize that `ess` probably stood for "explained sum of squares" and `ssr` probably stood for "sum of squares residuals".

This is a little misleading, since `ssr` typically stands for "sum of squares regression" in the literature.  But I don't think this would be a problem as long as there is documentation to refer to.  

Is this documented somewhere else outside of the links I referred to?  Otherwise, mind if I could push in a small PR to fix this?

**Comment by josef-pkt** [comment]
cached attributes are or should be documented in the class docstrung, e.g.
http://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.RegressionResults.html

If something is not there, then it's a documentation bug that needs to be reported and fixed.

The original reason that cached attributes don't have docstrings was that they didn't work with sphinx processing or rendering (maybe 5 to 7 years ago)

**Comment by mortonjt** [comment]
Ahh.  Perfect.  Looks like those variables are documented there.  Thanks!
