### ISSUE TITLE
On Bash on Ubuntu on Windows 10, fit() is crashing

### ISSUE THREAD

**Issue by srinath29** [statsmodels/statsmodels#3142]
Hi
I was building a model using GLSAR . 
Under Windows 10 and Linux, building the model and calling fit() on it is working fine but when I am using 
Bash on Ubuntu on Windows 10 model.fit() is crashing with the following error 
```
OMP: Error #100: Fatal system error detected.
OMP: System error #22: Invalid argument
Aborted (core dumped)
```
Please let me know if I can give more details on it

statsmodels version is 0.6.1

**Comment by josef-pkt** [comment]
Check if you have nans in the dataset. The behavior if there are nans depends on the underlying BLAS/LAPACK linear algebra libraries. However, even then there should be a warning issued by some linalg libraries, so, I guess nan alone will likely not be able to explain this.

What does "Bash on Ubuntu on Windows 10" mean? 
If you get clean answers on Windows and on Linux, maybe it is a bug in "Bash on Ubuntu on Windows 10".

Also, do you get this only with a specific dataset or also with random datasets?

**Comment by srinath29** [comment]
Hi
I was researching on it , same bug has been opened here 
https://github.com/Microsoft/BashOnWindows/issues/785

It is not about Nans . 
Recently Microsoft implemented [bash](http://www.hanselman.com/blog/VIDEOHowToRunLinuxAndBashOnWindows10AnniversaryUpdate.aspx) in Windows 10. So I am using that.

**Comment by josef-pkt** [comment]
Thanks for the link. That's good as reference when this shows up again.

Given that this not directly related to statsmodels and we cannot do anything about this, I'm closing this issue.
