### ISSUE TITLE
"Jeffreys" misspelled as "Jeffrey's"

### ISSUE THREAD

**Issue by Kodiologist** [statsmodels/statsmodels#3167]
The documentation for [`statsmodels.stats.proportion.proportion_confint`](http://statsmodels.sourceforge.net/devel/generated/statsmodels.stats.proportion.proportion_confint.html) describes an option as "Jeffrey’s Bayesian Interval". The interval in question is named after the Jeffreys prior, which itself is named after Harold Jeffreys. The option itself should then be named `jeffreys`, not `jeffrey`.

**Comment by josef-pkt** [comment]
Thanks for pointing this out.

I'm not very good in spelling names. option needs to be fixed
