### ISSUE TITLE
VAR: lags=0 and select_order()

### ISSUE THREAD

**Issue by yogabonito** [statsmodels/statsmodels#3216]
While writing tests for the VAR-framework I noticed that `select_order()` does not take into account any deterministic terms (see bug 2 in the this [gist](https://gist.github.com/yogabonito/784bb4e4a36515c04e2a4518e8d348de)). Also, fitting a VAR leads to an exception if `lags=0` and `trend="nc"` (see bug 1 in the same gist). Shall the VAR-framework even work for `lags=0` (as this would mean "no autoregression")

**Comment by josef-pkt** [comment]
It would be good to have lags=0 working (at least the basic results) so it can be used as reference case for order selection with consistent definitions (loglike, IC, ...), e.g.  #1262 and related added it for ARIMA.

If there is no constant/trend and no exog and lags=0, then there is no model at all and params are empty. I don't think we have that as a special case anywhere.

**Comment by josef-pkt** [comment]
Based on `blame` the bug that select_order was not taking trend into account was fixed by yogabonito in VECM GSOC merge

an empty model still raises an exception in fit

```
model = VAR(data)
est = model.fit(maxlags=0, trend="nc")

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-6ffc99743af7> in <module>()
      1 model = VAR(data)
----> 2 est = model.fit(maxlags=0, trend="nc")

m:\...\statsmodels\tsa\vector_ar\var_model.py in fit(self, maxlags, method, ic, trend, verbose)
    635                                self.data.xnames[k_trend:]
    636 
--> 637         return self._estimate_var(lags, trend=trend)
    638 
    639     def _estimate_var(self, lags, offset=0, trend='c'):

m:\...\statsmodels\tsa\vector_ar\var_model.py in _estimate_var(self, lags, offset, trend)
    683         y_sample = endog[lags:]
    684         # Lutkepohl p75, about 5x faster than stated formula
--> 685         params = np.linalg.lstsq(z, y_sample)[0]
    686         resid = y_sample - np.dot(z, params)
    687 

C:\...\python-3.4.4.amd64\lib\site-packages\numpy\linalg\linalg.py in lstsq(a, b, rcond)
   1887     a, bstar = _to_native_byte_order(a, bstar)
   1888     s = zeros((min(m, n),), real_t)
-> 1889     nlvl = max( 0, int( math.log( float(min(m, n))/2. ) ) + 1 )
   1890     iwork = zeros((3*min(m, n)*nlvl+11*min(m, n),), fortran_int)
   1891     if isComplexType(t):

ValueError: math domain error
```

**Comment by josef-pkt** [comment]
A zero lag model with at least one explanatory variable seems to work

e.g. the following produces full summary, with no nans
```
est = model.fit(maxlags=0, trend="c")
print(est.summary())
``
