### ISSUE TITLE
Problem in ARIMA endog change - using new data for prediction

### ISSUE THREAD

**Issue by mininaNik** [statsmodels/statsmodels#3233]
I want to fit ARIMA model on y1 series as follows:

      import statsmodels.tsa.arima_model as arima
      arima_model = arima.ARIMA(y1,order=(1, 0, 1)).fit()

and then I want to change the y1 (endog) to y2 with equal length. The reason is that I have y2 series and  I want to do the prediction by using fitted parameters from above model and the data form y2.
I changed the endog and orig_endog as follows:

        arima_model.data.endog = y2
        arima_model.data.orig_endog = y2

But it doesn't have any effect. I mean even if I set all values of endog and orig_endog to zero the predicted values don't change and it seems that it is working on y1 yet.

could someone help me to learn how to fit the model on one series and then use the fitted model for predicting future on a new series?

**Comment by ChadFulton** [comment]
You may find my answer to this question helpful: https://github.com/statsmodels/statsmodels/issues/2788

**Comment by mininaNik** [comment]
Thank you @ChadFulton . I am using statsmodels 0.6.1. I use ARIMA model. When I want to call filter an give the parameters as input (this line of code: res = mod.filter(training_res.params)), I get the following error 'ARIMA' object has no attribute 'filter'. Do you know what should I do?

**Comment by mininaNik** [comment]
I found my answer. Thank you.

**Comment by pedromorfeu** [comment]
Hi @mininaNik, I'm interested in your solution. Can you please share?

We are trying to re-feed the model with new data and predict over it. Something like what can be done in R using `forecast` package's `Arima` method and `model` parameter (https://cran.r-project.org/web/packages/forecast/forecast.pdf):

> model: Output from a previous call to Arima. If model is passed, this same model is
> fitted to y without re-estimating any parameters

**Comment by MaxKHK** [comment]
@ChadFulton I am sorry, but is there any way to do it not with SARIMAX? As I understand SARIMAX is fit using completely different approach than ARIMAX model. When I train SARIMAX I get completely different results than ARIMAX model on same data with same set up.

**Comment by ChadFulton** [comment]
> I am sorry, but is there any way to do it not with SARIMAX?

No, there is no way to do this with another model (e.g. you can't do it with `sm.tsa.ARIMA`). 

> As I understand SARIMAX is fit using completely different approach than ARIMAX model.

In general they use the same approach, although in rare cases it can depend on exactly what you're doing.  Also, they may have different starting parameters which can affect the final parameter estimates.

> When I train SARIMAX I get completely different results than ARIMAX model on same data with same set up.

In general, this shouldn't happen. If you like, feel free to post your data and code and I can take a look.
