### ISSUE TITLE
Large gap between real and fitted values - ARIMA

### ISSUE THREAD

**Issue by mininaNik** [statsmodels/statsmodels#3235]
I fit an ARIMA mode on my data as follows:

```
   mod = arima.ARIMA(data,order=(orders[0], orders[1], orders[2]))
   res = mod.fit()
```

I got model orders for autoarima function in R. When I plot fitted values and real data, I see a large gap between fitted and real values. I changed many parameters for fitting like trend, method, and solver but it didn't help. How should it be fixed? 

![6app_trend-fittedmodel_arima_](https://cloud.githubusercontent.com/assets/17245428/19316839/4798cf48-90a3-11e6-9485-2f1a6d61e667.png)

**Comment by ChadFulton** [comment]
I suspect this is because `fittedvalues` are predictions of the differenced series. If you want predictions in terms of the original series, you can do:

```python
fittedvalues = res.predict(typ='levels')
```

**Comment by bashtage** [comment]
Closing as answered.
