### ISSUE TITLE
ENH: Need convergence flag for ARIMA models

### ISSUE THREAD

**Issue by dragonator4** [statsmodels/statsmodels#3236]
ARMA model results have a convergence flag in `mod_res.mle_retvals`, but ARIMA model results do not have anything to indicate convergence. The flag is very useful during model selection, and in general to figure out if a model has successfully converged.

**Comment by josef-pkt** [comment]
(issue didn't have labels and got lost)

needs checking, base.optimizer._fit_lbfgs  adds `"converged"` to the retvals, so it should be there

**Comment by josef-pkt** [comment]
this looks obsolete
was changed in #2522 which was only released in 0.8
