### ISSUE TITLE
BUG: memory error with hessian, cov_type in GLM

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3242]
using `cov_type="HC0"` raises a memory error if nobs is a bit larger (e.g. nobs = 80,000)
https://groups.google.com/forum/#!msg/pystatsmodels/WHkb4kwkLyw/tYJ5IxJuAQAJ

AFAIR, the problem is the numerical derivative in hessian_factor.

I'm not sure whether there are any related changes already in master. needs checking and fixing if it's still present.

Essentially, this makes hessian and cov_type unusable for datasets that are not small.
It needs either analytical derivatives, a new numerical derivative function or using optionally the expected information matrix in the sandwich.

**Comment by thequackdaddy** [comment]
This isn't a problem for me using master...

**Comment by josef-pkt** [comment]
this has been fixed by using analytical derivatives, AFAICS as part of #1961
