### ISSUE TITLE
BUG: NegativeBinomial link does not subclass Link

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3244]
it's currently not relevant because nothing is inherited, but the NegativeBinomial link should subclass `Link`, currently it subclasses `object` directly

(I had changed the other link classes when I added cov_type, but inheritance of numerical derivatives became obsolete when Kerby added analytical derivatives to the links.)

**Comment by rishabmarkand** [comment]
This has perhaps been fixed by e8e4966. Maybe we can close this issue now.

**Comment by josef-pkt** [comment]
Thanks for pointing this out

closing, fixed by #3370

**Comment by josef-pkt** [comment]
forgot to close
