### ISSUE TITLE
loc and scale ignored for ProbPlots

### ISSUE THREAD

**Issue by paberr** [statsmodels/statsmodels#3254]
I found that supplying my own loc and scale parameters to ProbPlot does not have any effect.
Inspecting the code, I suspect the following lines to be responsible for this:

```
        elif distargs or loc == 0 or scale == 1:
            self.dist = dist(*distargs, **dict(loc=loc, scale=scale))
            self.loc = loc
            self.scale = scale
        else:
            self.dist = dist
            self.loc = loc
            self.scale = scale
```
It seems like the check should rather be `elif distargs or loc != 0 or scale != 1`

Also, trying to just supply my own dist object as norm(loc=loc, scale=scale) did not work, since the code is trying to call `self.fit_params = dist.fit(data)` even though `fit` is set to `False`.

**Comment by groceryheist** [comment]
This isn't the only problem with ProbPlot. Passing distargs to ProbPlot seems quite broken.  

    from scipy import stats
    import statsmodels.api as sm
    params = (10,0,2)
    data = stats.lognorm.rvs(100,*params)
    pp = sm.ProbPlot(data,"lognorm",fit=False,distargs=params)


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1659-70fdc874452a> in <module>()
      3 params = (10,0,2)
      4 data = stats.lognorm.rvs(100,*params)
----> 5 pp = sm.ProbPlot(data,"lognorm",fit=False,distargs=params)

~/venv/lib/python3.5/site-packages/statsmodels/graphics/gofplots.py in __init__(self, data, dist, fit, distargs, a, loc, scale)
    145                 self.dist = dist(loc=0, scale=1)
    146         elif distargs or loc == 0 or scale == 1:
--> 147             self.dist = dist(*distargs, **dict(loc=loc, scale=scale))
    148             self.loc = loc
    149             self.scale = scale

/usr/lib/python3/dist-packages/scipy/stats/_distn_infrastructure.py in __call__(self, *args, **kwds)
    766 
    767     def __call__(self, *args, **kwds):
--> 768         return self.freeze(*args, **kwds)
    769     __call__.__doc__ = freeze.__doc__
    770 

/usr/lib/python3/dist-packages/scipy/stats/_distn_infrastructure.py in freeze(self, *args, **kwds)
    763 
    764         """
--> 765         return rv_frozen(self, *args, **kwds)
    766 
    767     def __call__(self, *args, **kwds):

/usr/lib/python3/dist-packages/scipy/stats/_distn_infrastructure.py in __init__(self, dist, *args, **kwds)
    431 
    432         # a, b may be set in _argcheck, depending on *args, **kwds. Ouch.
--> 433         shapes, _, _ = self.dist._parse_args(*args, **kwds)
    434         self.dist._argcheck(*shapes)
    435         self.a, self.b = self.dist.a, self.dist.b

TypeError: _parse_args() got multiple values for argument 'loc'

**Comment by bashtage** [comment]
These are both fixed in master.
