### ISSUE TITLE
Better documentation for MixedLM results table

### ISSUE THREAD

**Issue by TheChymera** [statsmodels/statsmodels#3255]
Hi, I'm very happy to have come across your python implementation of MixedLM. I have, however, a number of questions regarding the outputs table. In short I'm wondering:

* why the table reports z (and not t values).
* whether the p-values are multiple comparison corrected.
* why the standard error is equal for all factors except the intercept.
* whether H0 (for which z amd p-values are given) for the intercept is indeed `intercept == 0` and for all other factors indeed `factor == intercept`.

I would not like to cross-post, but I go into [more detail on this an provide example tables and figures on a Stack Exchange question](http://stats.stackexchange.com/questions/244000/understand-summary-from-statsmodels-mixedlm-function). I had thought that was the best place to ask, but nobody took notice.

**Comment by kshedden** [comment]
Horea -- I will respond to this at stack exhange.

Kerby

**Comment by TheChymera** [comment]
@kshedden If I have further questions about usage/documentation, would you prefer I address them here or on stack exchange?

**Comment by kshedden** [comment]
I will usually see it if it goes to stackexchange or crossvalidated.

There is also a google group

https://groups.google.com/forum/#!forum/pystatsmodels

Kerby
