### ISSUE TITLE
[ARMA] Predict model gives "Wrong number of items passed X, placement implies Y"

### ISSUE THREAD

**Issue by k0pernicus** [statsmodels/statsmodels#3268]
Hi,

I fitted my ARMA model using the Dataframe below, and try to predict the next 60 days:
```
>>> print(endog_products)
2014-06-17    1.0
2014-06-19    0.0
2014-06-20    0.0
2014-06-21    0.0
2014-06-22    0.0
2014-06-23    0.0
2014-06-24    0.0
2014-06-25    2.0
2014-06-26    2.0
2014-06-27    3.0
2014-06-28    3.0
2014-06-29    0.0
2014-06-30    0.0
2014-07-01    3.0
2014-07-02    2.0
2014-07-03    2.0
2014-07-04    1.0
2014-07-05    1.0
2014-07-06    0.0
2014-07-07    1.0
2014-07-08    1.0
2014-07-09    1.0
2014-07-10    1.0
2014-07-11    4.0
2014-07-12    1.0
2014-07-13    1.0
2014-07-14    0.0
2014-07-15    2.0
2014-07-16    1.0
2014-07-17    0.0
2014-07-18    1.0
2014-07-19    1.0
2014-07-20    0.0
2014-07-21    0.0
2014-07-22    3.0
2014-07-23    3.0
2014-07-24    2.0
2014-07-25    2.0
2014-07-26    0.0
2014-07-27    1.0
2014-07-28    0.0
2014-07-29    1.0
2014-07-30    0.0
2014-07-31    1.0
2014-08-01    0.0
```

This is my code to fit the model, and it works great:
```
arma_order = arma_order_select_ic(endog_products, ic=['aic', 'bic', 'hqic'], trend='c', fit_kw=dict(method='css-mle'))
p = arma_order.aic_min_order[0]
q = arma_order.aic_min_order[1]
arma_model = ARMA(endog_products, freq='D', order=(p, 0, q))
arma_res = arma_model.fit() 
```

When I try to predict the next 60 days using this code (`prediction_values = arma_res.predict(start=prelearning_date, end=max_date)`), Python returns this error: `Error when computing ARMA model for product 3035668: Wrong number of items passed 106, placement implies 107`.

I don't understand what this error means.
I checked on Google and on issues but I don't find some issues that are corresponding to my problem.

Thanks a lot for your answers.

**Comment by josef-pkt** [comment]
What version of statsmodels are you using?

AFAIR, there were some bugs in ARMA predict with exog in 0.6, that have been fixed since then.

**Comment by k0pernicus** [comment]
This is my current version of `statsmodel`:

```
>>> pip3 show statsmodels
Name: statsmodels
Version: 0.6.1
Summary: Statistical computations and models for use with SciPy
Home-page: http://statsmodels.sourceforge.net/
Author: Skipper Seabold, Josef Perktold
Author-email: pystatsmodels@googlegroups.com
License: BSD License
Location: /usr/local/lib/python3.5/dist-packages
Requires: patsy, pandas
```

**Comment by k0pernicus** [comment]
Also, I don't use the `exog` parameter...

**Comment by josef-pkt** [comment]
Sorry, reading too fast early in the morning while being distracted.

what are your p, q and prelearning_date, max_date?
Also copy the full traceback so we see where it errors.

I don't remember seeing this, AFAIK there were similar problems only when predicting with exog, and date parsing for begin/end was restrictive.

**Comment by k0pernicus** [comment]
No problem, thank you a lot to comment my problem :-)

My `p` and `q` variables are `(2, 1)` (computed using `arma_order_select_ic`), `prelearning_date` is set to `2014-06-17` and `max_date` to `2014-09-30`.

This is the full traceback:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-b91c1712463c> in <module>()
     66         print("[Product %s] Date %s to %s" % (product, prelearning_date, max_date))
     67 
---> 68         prediction_values = arma_res.predict(start=prelearning_date, end=max_date)
     69 
     70         sum_current_products = current_products[:STUDIED_PERIOD].cumsum()

/usr/local/lib/python3.5/dist-packages/statsmodels/base/wrapper.py in wrapper(self, *args, **kwargs)
     90         results = object.__getattribute__(self, '_results')
     91         data = results.model.data
---> 92         return data.wrap_output(func(results, *args, **kwargs), how)
     93 
     94     argspec = inspect.getargspec(func)

/usr/local/lib/python3.5/dist-packages/statsmodels/base/data.py in wrap_output(self, obj, how, names)
    373             return self.attach_cov(obj)
    374         elif how == 'dates':
--> 375             return self.attach_dates(obj)
    376         elif how == 'columns_eq':
    377             return self.attach_columns_eq(obj)

/usr/local/lib/python3.5/dist-packages/statsmodels/base/data.py in attach_dates(self, result)
    501 
    502     def attach_dates(self, result):
--> 503         return TimeSeries(result, index=self.predict_dates)
    504 
    505 

/usr/local/lib/python3.5/dist-packages/pandas/core/series.py in __init__(self, *args, **kwargs)
   2965                       FutureWarning, stacklevel=2)
   2966 
-> 2967         super(TimeSeries, self).__init__(*args, **kwargs)
   2968 
   2969 # ----------------------------------------------------------------------

/usr/local/lib/python3.5/dist-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    241                                        raise_cast_failure=True)
    242 
--> 243                 data = SingleBlockManager(data, index, fastpath=True)
    244 
    245         generic.NDFrame.__init__(self, data, fastpath=True)

/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py in __init__(self, block, axis, do_integrity_check, fastpath)
   4066         if not isinstance(block, Block):
   4067             block = make_block(block, placement=slice(0, len(axis)), ndim=1,
-> 4068                                fastpath=True)
   4069 
   4070         self.blocks = [block]

/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py in make_block(values, placement, klass, ndim, dtype, fastpath)
   2683                      placement=placement, dtype=dtype)
   2684 
-> 2685     return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
   2686 
   2687 # TODO: flexible with index=None and/or items=None

/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py in __init__(self, values, placement, ndim, fastpath)
    107             raise ValueError('Wrong number of items passed %d, placement '
    108                              'implies %d' % (len(self.values),
--> 109                                              len(self.mgr_locs)))
    110 
    111     @property

ValueError: Wrong number of items passed 105, placement implies 106
```

**Comment by k0pernicus** [comment]
(I updated my first comment, I try to predict the next 60 days, not 45 days)

**Comment by josef-pkt** [comment]
This is in the pandas wrapper, not in the ARIMA code.

This looks the same as or similar to #3105 and related issues and fixes
@ChadFulton   What's the status of this?  I haven't paid much attention recently.

@k0pernicus  which pandas version do you use?

**Comment by k0pernicus** [comment]
Ok, thanks a lot for your help @josef-pkt! 
My pandas version:
```
pip3 show pandas
Name: pandas
Version: 0.19.1
Summary: Powerful data structures for data analysis, time series,and statistics
Home-page: http://pandas.pydata.org
Author: The PyData Development Team
Author-email: pydata@googlegroups.com
License: BSD
Location: /usr/local/lib/python3.5/dist-packages
Requires: numpy, python-dateutil, pytz
```

**Comment by ChadFulton** [comment]
It's hard to be sure what's going on without knowing the exact index type and frequency of your data (I see the data there, but I can't tell if that's a string index, or a DatetimeIndex and if so if it has a defined `freq` argument), but there were a number of fixes since 0.6 related to recent Pandas versions, and from some quick tests I suspect the code would work with 0.8, but I can't be positive.

**Comment by ChadFulton** [comment]
@josef-pkt This doesn't seem like the exact same issue as #3105 since @k0pernicus is explicitly passing a frequency argument to `ARMA`, but it's probably related.

I am fully in favor of moving forward on #3124 so that in the future (0.9?) we can have sane date handling :) The only issue is deciding which of the proposals (or if there is a better one I didn't come up with) to move forward on. If there's no interest, I can just start implementing with the one I prefer, which I called "1-strict, 1-strict-specify, 1-missing-freq", but other people may know better than me.

**Comment by josef-pkt** [comment]
To investigate further and have a test case for #3124, we need a reproducible bug with statsmodels master.
Given that it's somewhere in the interaction with pandas, there are too many possibilities to guess what might be wrong, including that statsmodels 0.6 is not pandas compatible in this, and including the possibility of bugs or problems on the pandas side (which I thought only affected nano-seconds.)

**Comment by k0pernicus** [comment]
Thank you @josef-pkt and @ChadFulton.
So, do I need to upgrade my version of statsmodels?
I tried to upgrade it using `pip3` but the version `6.1` is actually the last version...

```
>>> pip3 install --upgrade --no-deps statsmodels
Requirement already up-to-date: statsmodels in /usr/local/lib/python3.5/dist-packages
>>> pip3 show statsmodels
Name: statsmodels
Version: 0.6.1
Summary: Statistical computations and models for use with SciPy
Home-page: http://statsmodels.sourceforge.net/
Author: Skipper Seabold, Josef Perktold
Author-email: pystatsmodels@googlegroups.com
License: BSD License
Location: /usr/local/lib/python3.5/dist-packages
Requires: pandas, patsy
```

**Comment by ChadFulton** [comment]
There hasn't yet been a release of version 0.8, but you can install via pip+git, for example: `pip install git+https://github.com/statsmodels/statsmodels.git`

**Comment by k0pernicus** [comment]
Great, thanks!

**Comment by k0pernicus** [comment]
Hey @ChadFulton, @josef-pkt, I tried the new version of `statsmodels` (`statsmodels==0.8.0`) and... it doesn't work neither :-/

I have always this error when fitting my ARMA model for some data...
Any new feedbacks about this problem please?

**Comment by ChadFulton** [comment]
Can you post a minimum replicating example, along with the exception message? Also, can you post the results of `python -c 'from statsmodels import version; print(version.version)'`?

I'm going to try and get all of these issues worked out, so I appreciate you continuing to report the bugs.

**Comment by k0pernicus** [comment]
Sorry for the long delay - I will close the issue now since it's been a long time since I've opened it... and can't remember exactly the project I was working on 😬 

Thanks for the help 👋

**Comment by ChadFulton** [comment]
No problem and thanks for following up and closing the issue.
