### ISSUE TITLE
Documentation missing attribute

### ISSUE THREAD

**Issue by ahaug1289** [statsmodels/statsmodels#3279]
The documentation page for statsmodels.regression.linear_model.RegressionResults (http://statsmodels.sourceforge.net/devel/generated/statsmodels.regression.linear_model.OLSResults.html) is missing the fact that the attribute ".tvalues" exists. It mentions a method ".tvalues()" but there is no mention that .tvalues exists, even when it is a standard aspect of the summary output.

**Comment by josef-pkt** [comment]
It's confusing, but I don't know of a work around to get rid of the parenthesis.

Many items that are listed as methods like `.tvalues()` are actually cached attributes (properties, descriptors) that we access without the parenthesis. The parenthesis are added by sphinx when rendering the documentation.

this is supposed to have the full list of (cached) attributes
http://www.statsmodels.org/devel/generated/statsmodels.regression.linear_model.RegressionResults.html
but I don't see `tvalues` there

**Comment by bashtage** [comment]
This is fixed in master.
