### ISSUE TITLE
Error running Cython when building the new version of statsmodels

### ISSUE THREAD

**Issue by k0pernicus** [statsmodels/statsmodels#3286]
Hi there,
I try to upgrade my 0.6.1 version of statsmodels passing by `pip+git`:
```
pip3 install --upgrade --no-deps git+https://github.com/statsmodels/statsmodels.git
```

Unfortunately, it fails when upgrading the new version:
```
Collecting git+https://github.com/statsmodels/statsmodels.git
  Cloning https://github.com/statsmodels/statsmodels.git to /tmp/pip-z6omg6cq-build
Installing collected packages: statsmodels
  Found existing installation: statsmodels 0.6.1
    Uninstalling statsmodels-0.6.1:
      Successfully uninstalled statsmodels-0.6.1
  Running setup.py install for statsmodels ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-z6omg6cq-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bs8at_4g-record/install-record.txt --single-version-externally-managed --compile:
    Cythonizing sources
    Processing statsmodels/nonparametric/linbin.pyx
    Processing statsmodels/nonparametric/_smoothers_lowess.pyx
    Processing statsmodels/tsa/statespace/_kalman_filter.pyx.in
    Processing statsmodels/tsa/statespace/_representation.pyx.in
    Processing statsmodels/tsa/statespace/_statespace.pyx.in
    Processing statsmodels/tsa/statespace/_tools.pyx.in
    Processing statsmodels/tsa/statespace/_kalman_smoother.pyx.in
    Traceback (most recent call last):
      File "/tmp/pip-z6omg6cq-build/tools/cythonize.py", line 215, in <module>
        main()
      File "/tmp/pip-z6omg6cq-build/tools/cythonize.py", line 211, in main
        find_process_files(root_dir)
      File "/tmp/pip-z6omg6cq-build/tools/cythonize.py", line 203, in find_process_files
        process(cur_dir, fromfile, tofile, function, hash_db)
      File "/tmp/pip-z6omg6cq-build/tools/cythonize.py", line 174, in process
        processor_function(fromfile, tofile)
      File "/tmp/pip-z6omg6cq-build/tools/cythonize.py", line 95, in process_tempita_pyx
        tmpl = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 25930: ordinal not in range(128)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-z6omg6cq-build/setup.py", line 545, in <module>
        generate_cython()
      File "/tmp/pip-z6omg6cq-build/setup.py", line 90, in generate_cython
        raise RuntimeError("Running cythonize failed!")
    RuntimeError: Running cythonize failed!

    ----------------------------------------
  Rolling back uninstall of statsmodels
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-z6omg6cq-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-bs8at_4g-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-z6omg6cq-build/
```

I don't understand that error because my `Cython` package is the latest (`Cython==0.25.1`) - maybe anyone can help me with this error: ` 'ascii' codec can't decode byte 0xe2 in position 25930: ordinal not in range(128)`?
Thanks a lot

**Comment by ChadFulton** [comment]
Hi, thanks for the report. Can you post the error you're receiving?

**Comment by k0pernicus** [comment]
I just update my post - sorry for this "Cmd + Enter" mistake ;-)

**Comment by ChadFulton** [comment]
Great, thanks! Can you also post your python version and operating system?

**Comment by k0pernicus** [comment]
Yep - this is the response of `uname -a`: `Linux 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`.
My Python version and pip version:
```
>>> python3 --version
Python 3.5.2
>>> pip3 --version
pip 9.0.1 from /usr/local/lib/python3.5/dist-packages (python 3.5)
```

**Comment by ChadFulton** [comment]
Thanks! I'll try to take a look at this tonight. We recently added the file that appears to be causing the issue.

**Comment by ChadFulton** [comment]
My initial attempt to replicate on a new Ubuntu 16.04 VM this evening was unsuccessful (meaning that statsmodels was successfully installed :), but that was using Python 2.7.12, and since the issue is a unicode error it'll probably bite when I try it again in python 3, hopefully tomorrow.

**Comment by ChadFulton** [comment]
I just tried and was able to successfully install Statsmodels on a brand new Ubuntu 16.04 VM, with:

- `uname -a`: `Linux 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- `python3 --version`: `Python 3.5.2`
- `pip3 --version`: `pip 9.0.1 from /home/user/.local/lib/python3.5/site-packages (python 3.5)`

**Comment by ChadFulton** [comment]
I guess we're using different Ubuntu versions - are you using 16.10?

**Comment by k0pernicus** [comment]
Thanks a lot @ChadFulton, I am using this version of Ubuntu: `Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-47-generic x86_64)`.
That's weird because I can't update `statsmodels` again...
I tried to update also my `pip3` packages but each is already updated :-/

**Comment by josef-pkt** [comment]
just a shot in the dark (not that I know anything)

Can the difference come form the `locale`? i.e. the file is read with different encodings.
Do pyx.in files need a utf-8 declaration?


specifically: it looks like the dash is a special character (I often have encoding problems copying references names and similar)

```
>>> txt[25930:25940]
b'\xe2\x80\x93Frazier'
```

```
>>> txt[25900:25940]
b'# Multivariate modified Bryson\xe2\x80\x93Frazier'
```

In this case the dash can be replaced by ascii dash and we don't need utf-8

**Comment by ChadFulton** [comment]
That sounds right to me Josef. That copy-paste gets me every time. Thanks for doing the check for me. I'll try to fix this and push a fix this evening.

**Comment by ChadFulton** [comment]
Since it's just a one character change, I will merge the PR right away. I also swept the files for non-ASCII characters (`pcregrep --color='auto' -n '[^\x00-\x7F]' *`, from http://stackoverflow.com/questions/3001177/how-do-i-grep-for-all-non-ascii-characters-in-unix) for my future reference), and that appears to be the only problematic one in my recent additions (`statespace` and `regime_switching`).

**Comment by ChadFulton** [comment]
Actually, now that I think about it, I'll leave this open and hopefully @k0pernicus can confirm that the fix worked.

**Comment by k0pernicus** [comment]
Thanks a lot @ChadFulton and @josef-pkt, it works now :-)
You're awesome!
