### ISSUE TITLE
Robust Linear Models web page broken example and formula

### ISSUE THREAD

**Issue by Berowne** [statsmodels/statsmodels#3287]
Hi 
the RLM web page has broken formula (I.E. and Firefox on Win7).
Also the code is failing to generate at input line 27.
AttributeError                            Traceback (most recent call last)
<ipython-input-206-605f8dff1422> in <module>()
----> 1 kde = sm.nonparametric.KDE(fat_tails)
      2 kde.fit()
      3 fig = plt.figure(figsize=(12,8))
      4 ax = fig.add_subplot(111)
      5 ax.plot(kde.support, kde.density);

AttributeError: 'module' object has no attribute 'KDE'

http://statsmodels.sourceforge.net/stable/examples/notebooks/generated/robust_models_1.html

**Comment by josef-pkt** [comment]
the new version is here,
http://www.statsmodels.org/dev/examples/notebooks/generated/robust_models_1.html
 it uses on line 27
kde = sm.nonparametric.KDEUnivariate(fat_tails)

Can you check if that notebook works for you, and report back?
The most recent notebooks are available in the repo on github. 

The sourceforge site is either out of date or refers to older versions of statsmodels. I don't remember when KDE has been changed, but it has been some years.

**Comment by Berowne** [comment]
Hey Joe

I guess you can't trust google to provide the latest search results. 

I'm Still getting errors further down the page

Faithfully, 
Berowne

**Comment by bashtage** [comment]
@josef-pkt This can be closed.  It has been fixed in master and there are no doc build errors for this notebook.

**Comment by josef-pkt** [comment]
Thanks @bashtage
