### ISSUE TITLE
ARMA/ARIMA prediction fails when start and end are datetime objects

### ISSUE THREAD

**Issue by alikashmar** [statsmodels/statsmodels#3312]
I ran across this issue and I thought I should probably report it. I built an ARIMA model using a pandas data frame and tried to make predictions using datetime objects for start and end.  That failed with the error: 

```
/usr/lib/python2.7/site-packages/statsmodels-0.6.1-py2.7-linux-x86_64.egg/statsmodels/tsa/arima_model.pyc in predict(self, params, start, end, exog, dynamic)
    730             # also return error estimates and confidence intervals
    731             # but how? len(endog) is not tot_obs
--> 732             out_of_sample += end - start + 1
    733             return _arma_predict_out_of_sample(params, out_of_sample, resid,
    734                                                k_ar, self.k_ma, self.k_trend,

TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'int'
```
Here's the code I used:
```
start_date = datetime.strptime('2016-09-30T23:48:39','%Y-%m-%dT%H:%M:%S')
start_date -= timedelta(minutes = start_date.minute % 5, seconds = start_date.second % 60)
end_date = start_date + timedelta(minutes=30)

arima_mod = sm.tsa.ARIMA(data, order=(5,0,1), freq = DateOffset(minutes=5), missing = 'drop').fit()
arima_mod.predict(start_date, end_date, dynamic=True) # fails
arima_mod.predict(start_date.__str__(), end_date.__str__(), dynamic=True) # works
arima_mod.predict('2016-09-30 23:30:00', '2016-10-01 00:00:00', dynamic=True) # works
```

**Comment by ChadFulton** [comment]
This behavior should be fixed in master, although there is not yet a release with it. e.g. the following code works for me:

```python
import numpy as np
import pandas as pd
import statsmodels.api as sm
from datetime import datetime, timedelta

index = pd.DatetimeIndex(start='2016-09-30T23:00:00', periods=100, freq='5min')
data = pd.Series(np.random.normal(size=100), index=index)

start_date = datetime.strptime('2016-09-30T23:48:39','%Y-%m-%dT%H:%M:%S')
start_date -= timedelta(minutes = start_date.minute % 5, seconds = start_date.second % 60)
end_date = start_date + timedelta(minutes=30)

arima_mod = sm.tsa.ARIMA(data, order=(5,0,1), freq='5T', missing = 'drop').fit()
arima_mod.predict(start_date, end_date, dynamic=True) # fails
```

and produces:

```
2016-09-30 23:45:00    0.086675
2016-09-30 23:50:00    0.199556
2016-09-30 23:55:00   -0.170287
2016-10-01 00:00:00    0.144832
2016-10-01 00:05:00   -0.264337
2016-10-01 00:10:00   -0.005096
2016-10-01 00:15:00   -0.145015
Freq: 5T, dtype: float64
```

**Comment by josef-pkt** [comment]
closing given that it looks like it has been fixed

**Comment by jorgeloaiza** [comment]
¿Wthat does this error mean, when i try to predict ,in ARIMA model?
TypeError: predict() missing 1 required positional argument: 'params'

This is code:
x=np.linspace(0,len(sumas_mayo_junio_2015)-1,len(sumas_mayo_junio_2015))
np.random.seed(12)
ruido = np.random.randn(*x.shape)
gpx = x.reshape(x.shape[0], 1)#convierte en un vector columna
gpy = (ruido+sumas_mayo_junio_2015).reshape(x.shape[0], 1)
model = ARIMA(gpy, order=(5,1,0))
model_fit = model.fit(disp=0)
print(model_fit.summary())
y_estimados=model.predict(start=1464,end=1464,typ='levels')
y_estimados.shape

**Comment by josef-pkt** [comment]
the `model` doesn't know the params so those have to be provided.
the results instance `model_fit` has params and they are not required to be provided by the user.

that is, use the results instance:
`y_estimados=model_fit.predict(start=1464,end=1464,typ='levels')`

**Comment by jorgeloaiza** [comment]
Hello josef
You refers to "model_fit.params", that is to say, y_estimados=model.predict(model_fit.params,start=1464,end=1487,typ='levels',dynamic= True)

right?

**Comment by josef-pkt** [comment]
No, use what I wrote, there is no params argument when `results.predict` is used

**Comment by josef-pkt** [comment]
I copied your start, end. 
Those you will have to adjust and add whatever other options like dynamic you want.
The main point is to use the results instance that you called model_fit

**Comment by jorgeloaiza** [comment]
Josef, i use "model_fit.params" and It works. The firs parameter of predict is array-like
http://www.statsmodels.org/dev/generated/statsmodels.tsa.arima_model.ARIMA.predict.html#statsmodels.tsa.arima_model.ARIMA.predict

Thanks

**Comment by josef-pkt** [comment]
@jorgeloaiza  I know that model.predict(results.params, ...) works, but that is mostly internal. The recommended ways is to use the results instance. In some cases or models, there can be some additional processing and wrapping in the results.predict method that is not in the model.predict method.
(In the simple cases results.predict just calls model.predict adding the params, but that's not guaranteed to always be the case.)

**Comment by jorgeloaiza** [comment]
Ok.
What amount must  p,d,q have?

**Comment by ChadFulton** [comment]
@jorgeloaiza you may want to try asking your question on the statsmodels mailing list or on a site like stack exchange, since it doesn't seem like your questions are related to this bug report.
