### ISSUE TITLE
Arima prediction problem

### ISSUE THREAD

**Issue by Nicolas99-9** [statsmodels/statsmodels#3340]
I'm trying to predict one month ahead the number of passengers.
http://imgur.com/0K13Vc9
my model : arma_mod = sm.tsa.ARIMA(df.passengers, order=(4,0,4))
When I call "predict" the predicted values are always close to zero.  
![f4k9g](https://cloud.githubusercontent.com/assets/16637853/21467294/b971cb64-c9e8-11e6-9c46-22ab8a8d3be5.png)

**Comment by josef-pkt** [comment]
Your model doesn't look like it's coming from statsmodels. I'm pretty sure, we don't have a model signature like that.
To me the graph looks like the model is estimated without a constant, and forces the mean to be zero (but then there would be negative predictions).
???

**Comment by Nicolas99-9** [comment]
Sorry I copy/paste the wrong line ;( . 
After a few predictions, the values are similar to : 
0.00929492560381
0.0524866054704
0.130836897634
0.149995561274
0.194545065065
0.174476568992
0.178399165414
0.930096804572
0.0499489865472
0.00135351068936
-0.0191560190712
0.724088167474
-0.135395265796
0.658149149537
-0.16113614179
-0.141370544662
-0.0671600693877
-0.0499563460017

**Comment by josef-pkt** [comment]
I'm pretty sure that there is a missing constant for the mean, but given that it is not our function, I have no idea what you did.

**Comment by josef-pkt** [comment]
Can you provide a working example?
This looks like a missing option to me, maybe typ='levels' in predict, or some other model misspecification.

closing for now
