### ISSUE TITLE
problem in argument "alpha" in statsmodels.stats.outliers_influence?

### ISSUE THREAD

**Issue by roykev** [statsmodels/statsmodels#3344]
hi 
I call the following code: 
st, data, ss2 = summary_table(re, **alpha=0.01**) # note the alpha is not the default
it then calls 
#(line 702 in outliers_influence.py)
predict_se, predict_ci_low, predict_ci_upp = wls_prediction_std(res) # note that alpha is not passed 
then it gets to 
(# line 27 in predstd.py) 
def wls_prediction_std(res, exog=None, weights=None, **alpha=0.05**) # not that alpha receives the default 0.05 again 

so it seems that no matter how i change the value of alpha it has no effect on the result..
thank you

**Comment by josef-pkt** [comment]
Thanks,
I am currently on a skiing trip and will look into it next year. 
Is this with 0.6.1? I don't remember if we had changes related to this since then.

**Comment by roykev** [comment]
Thank you so much for getting back so promptly.
Yes, the version I’m using is 0.6.1 (python 3.5)
BTW when I’m in a debug mode and force the value of alpha in the function to be 0.01 (i.e., override it) it works well. So imho it is a matter of parameter passing to the functions
 
All the best and happy new year

**Comment by josef-pkt** [comment]
That's still this way in master. Mean confint looks correct, but prediction interval is wrong.
Quick fix that we can backport is just forwarding the alpha.
Later, this can use the new get_prediction.
