### ISSUE TITLE
statespace ljung-box in summary, lag too large ?

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3381]
statsmodels.tsa.statespace.mlemodel MLEResults.summary uses ljungbox with default maxlag which is most likely too large.

`lb = self.test_serial_correlation(method='ljungbox')`

see #286  
related PR #3360 changes default for standalone function if 40 is too large

Hyndman's rule of thumb should be better http://robjhyndman.com/hyndsight/ljung-box-test/

Note, not backwards compatible, but it's not even released yet.

**Comment by josef-pkt** [comment]
@ChadFulton  any opinion on this?

**Comment by ChadFulton** [comment]
It does Hyndman's rule of thumb looks good to me; I think there's no problem changing the summary default (and fixing the incorrect docstring!). I can make a PR unless @zveryansky wants to.

Separate from this issue is that the summary doesn't allow setting the `lag` option (or other options for other reported tests), and does not even report what was used. I don't know if that's something to change, or if further / more specific diagnostic tests are something that users can do if they want to.

**Comment by josef-pkt** [comment]
Based on the summary format, it looks like there is still space to add "xx lags" or a variation of it.

I'm not sure about options, generically we would need `**kwargs` in that case. But improvements to summary options are still needed. Durbin-Watson in OLS doesn't make much sense if it's cross-section data and ljung-box would be better than DW even in OLS.

**Comment by zveryansky** [comment]
@josef-pkt @ChadFulton 
I will fix it.
Just to make it clear:
1) in #286 and #3360 we decided to change default behavior to Hyndman's rule of thumb and some docstrings updates
2) add "lags" to summary

Am I correct?

**Comment by josef-pkt** [comment]
@zveryansky 
to summarize:
We leave the stata like default as you have it in #3360 for the ljung-box function itself, the corresponding statespace method should use the same min.

When we actually use it and need just one number as in statespace summary, then we use the Hyndman default. We also add Hyndman default as recommendation to the docstring.
extra issue: @ChadFulton  can we detect seasonality to switch default? e.g. in SARIMAX, or do we stick with the non-seasonal Hyndman default?

to 2. we use the proper (Hyndman) `lags` in the ljung-box call, but I would leave out for now the additional issue about how to add keyword options to the summary signature itself.
The number of lags used can be added to the description/name of statistic in summary

**Comment by ChadFulton** [comment]
We can detect seasonality in specific models, but not in the `MLEModel` class. If I'm reading Hyndman correctly, if there is seasonality he wants `lags = min(2m, T / 5)` where `m` is the seasonal period.

In `SARIMAX`, we could do the following to modify for seasonality:

(I haven't actually run this code, but it should be pretty close to this):

```python
def test_serial_correlation(self, method, lags=None):
    if lags is None and self.k_seasons > 0:
        lags = min(2 * self.k_seasons, self.nobs / 5)
    return super(SARIMAXResults, self).test_serial_correlation(self, method, lags=lags):
```

and for `UnobservedComponents`:

```python
def test_serial_correlation(self, method, lags=None):
    if lags is None and self.seasonal_period > 0:
        lags = min(2 * self.seasonal_period, self.nobs / 5)
    return super(UnobservedComponentsResults, self).test_serial_correlation(self, method, lags=lags):
```

**Comment by josef-pkt** [comment]
That sounds like we could just to an hasattr(self, 'k_season')  hasattr(self, 'seasonal_period') check in MLEModel, and we don't have to change subclasses, unless they override the summary.

**Comment by ChadFulton** [comment]
> That sounds like we could just to an hasattr(self, 'k_season') hasattr(self, 'seasonal_period') check in MLEModel, and we don't have to change subclasses, unless they override the summary.

That sounds like a better idea.

We can also standardize on one of the attribute names and migrate the other class to use that terminology (we can still maintain the old attribute for a while for backwards compatibility, depending on if we care about that for state space yet).

**Comment by josef-pkt** [comment]
I'm a big fan of consistent namings :)

**Comment by ChadFulton** [comment]
Is `seasonal_period` the better name? I know that R uses `frequency` in this context (e.g. http://robjhyndman.com/hyndsight/seasonal-periods/), but I think that is somewhat incorrect terminology.

i.e. we would say that a weekly seasonal effect has a period of 7 days per cycle (`period=7`), and a frequency of 1 cycle per 7 days (`frequency=1/7`).

**Comment by josef-pkt** [comment]
Definitely not frequency because it also collides with `freq` for dates (and I never remember if this is the length or 1 / length seasons per period.)

I like something that explicitly refers to number of periods, The best I can come up with would be `season_length`  that would avoid conflicting jargon across fields. But I think `seasonal_periods` (maybe better plural) would also be good.

**Comment by bashtage** [comment]
@ChadFulton Was this ever resolved?  Is a resolution still desired?
