### ISSUE TITLE
OLS.fit_regularized parameter estimates are random

### ISSUE THREAD

**Issue by mortonjt** [statsmodels/statsmodels#3393]
I have noticed that when I try to run regularized regression with the OLS model, there is a bit of randomness to the parameter estimation.  The estimates are all within the same order of magnitude, but I can't seem to isolate the source of randomness.

Are there known numerical issues with this module?  

I'll try to bring up a simple toy example of how this happens in a bit.

**Comment by kshedden** [comment]
Are you using a recent master or the last release?  There are a lot of
tests for this and none of them show any instability that I can see.

**Comment by mortonjt** [comment]
@kshedden sorry for the delay - it was a little awkward trying to figure out how to upload large datasets.

I do think I have figured the problem after tinkering with other modules using regularization.
From what I gather, the regularization parameter (i.e. alpha) needs to be tuned to make sure that the optimization converges.  With sufficiently small values of alpha, I'm able to get somewhat stable estimators.
