### ISSUE TITLE
Fitting new data to dynamic factor model

### ISSUE THREAD

**Issue by lsuttle** [statsmodels/statsmodels#3403]
I am trying to use a dynamic factor model in a machine learning pipeline. As such, I need to fit new data (test data) to my existing model (which is trained on training data). I can't seem to find the method or necessary parameters to create this method.

**Comment by ChadFulton** [comment]
It would be helpful if you gave us some more details, or perhaps some example code that is not working the way that you want it to. I guess you must be talking about the `sm.tsa.DynamicFactor` model?

If you want to use the parameters fitted from one dataset and apply them to another dataset, maybe to get smoothed estimates of the factors or something, you could do the following:

```python
# Datasets
data_training = ...
data_new = ...

# Fit a dynamic factor model on the training dataset
mod_training = sm.tsa.DynamicFactor(data_training, k_factors=1, factor_order=1)
res_fitted_training = mod_training.fit()

# Create a new model with the new dataset
mod_new = sm.tsa.DynamicFactor(data_new, k_factors=1, factor_order=1)

# Perform Kalman smoothing using the fitted parameters
res_smoothed_new = mod_new.smooth(fitted_training.params)
```

**Comment by lsuttle** [comment]
Sorry to be so vague, I didn't have sample code because I couldn't figure out which method would even be close to what I was going for. 

I think that smooth() and params were what I was trying to get at. I was trying to fit it into a machine learning pipeline like one would a PCA, but wasn't able to figure out how to get the model parameters from the training model out in order to use the same model on the test data. So in your words, get the parameters fitted for one dataset and apply them to another dataset.

**Comment by lsuttle** [comment]
Just tested, this is what I needed, thank you!

**Comment by ChadFulton** [comment]
Great! Glad it helped.
