### ISSUE TITLE
BUG possibly index handling in predict

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3409]
http://stackoverflow.com/questions/42007862/messy-fitted-line-plot

(I'm not sure what's going on, but it looks wrong. I look into it later today.)
maybe some index sorting issue

That's a serious bug in 0.8 if confirmed.

**Comment by josef-pkt** [comment]
looks like patsy is returning a dataframe sorted by index, which messes up the indexing

```
>>> from patsy import dmatrix
>>> exog = dmatrix(model1.model.data.design_info.builder,
...                            df1.X, return_type="dataframe")
>>> exog[:5]
   Intercept  np.log(X)
0        1.0  -0.272921
1        1.0  -1.213598
2        1.0  -1.522849
3        1.0  -0.196802
4        1.0  -0.587657
```

I guess we don't have any unit tests where index of exog is not sorted.

**Comment by josef-pkt** [comment]
if I sort the data, so that index remains sorted, then there is no problem.

So, it looks like patsy's sorting by index messes things up and we don't compensate.
This is a 0.8 bug introduce in #3149
Before we used the array return from dmatrix.

I guess I don't understand what pandas `reindex` does. We need to get it back to the original  index, including rows that patsy dropped because of the nan handling.

**Comment by TomAugspurger** [comment]
> looks like patsy is returning a dataframe sorted by index, which messes up the indexing

@josef-pkt it's a bit stranger than that. patsy seems to sort *only* when a `Series` is passed as `exog`.

```python
# series
In [97]: dmatrix(model1.model.data.design_info.builder,
    ...: ...                            df1['X'], return_type="dataframe")  # notice the single square brackets
    ...:
    ...:
    ...:
/Users/tom.augspurger/Envs/py3/bin/ipython:1: DeprecationWarning: The DesignInfo.builder attribute is deprecated starting in patsy v0.4.0; distinct builder objects have been eliminated and design_info.builder is now just a long-winded way of writing 'design_info' (i.e. the .builder attribute just returns self)
  #!/Users/tom.augspurger/Envs/py3/bin/python3
Out[97]:
     Intercept  np.log(X)
0          1.0  -4.418309
1          1.0  -0.343142
2          1.0  -0.650836
3          1.0  -0.433331
4          1.0  -0.144629
..         ...        ...
```

and a DataFrame

```python

In [98]: dmatrix(model1.model.data.design_info.builder,
    ...: ...                            df1[['X']], return_type="dataframe")  # double, slice with a list
    ...:
    ...:
/Users/tom.augspurger/Envs/py3/bin/ipython:1: DeprecationWarning: The DesignInfo.builder attribute is deprecated starting in patsy v0.4.0; distinct builder objects have been eliminated and design_info.builder is now just a long-winded way of writing 'design_info' (i.e. the .builder attribute just returns self)
  #!/Users/tom.augspurger/Envs/py3/bin/python3
Out[98]:
     Intercept  np.log(X)
110        1.0  -7.486706
62         1.0  -5.666838
364        1.0  -5.138395
835        1.0  -4.928871
539        1.0  -4.850536
..         ...        ...
```

> I guess I don't understand what pandas reindex does. We need to get it back to the original index, including rows that patsy dropped because of the nan handling.

You understand `.reindex` correctly, but patsy's (buggy?) handling of series vs dataframe causes the problem.

**Comment by josef-pkt** [comment]
@TomAugspurger Thanks for checking this
Then converting any Series to a DataFrame before sending it to patsy would fix this. ?

**Comment by TomAugspurger** [comment]
Oh, I think it's even strange still... (and maybe not a patsy bug). This looks fine

```python
In [104]: exog2 = pd.DataFrame({"X": [1, np.nan, 3]}, index=[10, 3, 1])

In [105]: dmatrix(model1.model.data.design_info.builder, exog, return_type="dataframe")
     ...:
Out[105]:
    Intercept  np.log(X)
10        1.0   0.000000
1         1.0   1.098612
```

This returns what I'm guessing is the original data, nothing to do with `exog`

```python
In [106]: dmatrix(model1.model.data.design_info.builder, exog.X, return_type="dataframe")
     ...:
     ...:
/Users/tom.augspurger/Envs/py3/bin/ipython:1: DeprecationWarning: The DesignInfo.builder attribute is deprecated starting in patsy v0.4.0; distinct builder objects have been eliminated and design_info.builder is now just a long-winded way of writing 'design_info' (i.e. the .builder attribute just returns self)
  #!/Users/tom.augspurger/Envs/py3/bin/python3
Out[106]:
     Intercept  np.log(X)
0          1.0  -4.418309
1          1.0  -0.343142
2          1.0  -0.650836
3          1.0  -0.433331
4          1.0  -0.144629
..         ...        ...
995        1.0  -0.044815
996        1.0  -0.699111
997        1.0  -1.139896
998        1.0  -0.568481
999        1.0  -1.016991

[1000 rows x 2 columns]
```

> Then converting any Series to a DataFrame before sending it to patsy would fix this. ?
Yep. `exog.to_frame()` should do it if we have a series. I can make a PR tonight.

**Comment by josef-pkt** [comment]
general question:
Is there a pandas DataFrame equivalent of `asarray`, i.e. convert to DataFrame if it is not one, return it unchanged if it is a DataFrame already?   to avoid an explicit isinstance Series check?

**Comment by josef-pkt** [comment]
BTW: I don't see any patsy DeprecationWarning in spyder, or in the test run

about unit tests for this
AFAICS, the easiest location will be at the end of `statsmodels\formula\tests\test_formula.py`
(I don't see a case in "statsmodels\base\tests\test_generic_methods.py" that would match.)

**Comment by TomAugspurger** [comment]
> Is there a pandas DataFrame equivalent of asarray, i.e. convert to DataFrame if it is not one, return it unchanged if it is a DataFrame already?

Easiest is probably `DataFrame(exog)`. That will take `exog.name` if it's a Series.

> BTW: I don't see any patsy DeprecationWarning in spyder, or in the test run

I don't see it when calling `model1.predict`. Just when accessing it directly.
