### ISSUE TITLE
REF: Removal of deprecated objects for 0.9

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#3433]
I notice that there are some objects that had been deprecated that are now due for removal:

- `jac` in `model.py` and `discrete_model.py`.
- `stand_mad` in `robust_linear_model.py`, `robust/scale.py`
- `rank` in `tools.py`
- `get_logdet` in `vector_ar/util.py`
- I can't quite tell, but possibly `cochrans_q`, `mcnemar`, `symmetry_bowker`, in `sandbox/stats/runs.py`?

Shall I remove them?

**Comment by josef-pkt** [comment]
That's not urgent. We can still leave them for a bit.  (I will have to look at the usage for each case.)

**Comment by ChadFulton** [comment]
Okay, sounds good.

**Comment by jbrockmendel** [comment]
18 months later... follow up on this?

**Comment by jbrockmendel** [comment]
@ChadFulton has this been addressed/closable?

**Comment by bashtage** [comment]
Going to close in favor of newer issues on deprecations.  These do need to go.
