### ISSUE TITLE
MAINT: x13  unclosed file warning

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3452]
running the unit tests after a fresh install upgrade of statsmodels 0.8.0, I get a unclosed file warning
```
C:\...\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-pac
kages\statsmodels\tsa\x13.py:570: ResourceWarning: unclosed file <_io.BufferedRe
ader name=5>
  start=start, freq=freq, prefer_x13=prefer_x13)
```

When I run the tsa or x13 tests again, then no warning shows up.

test run with `nosetests  statsmodels.xxx` on commandline

**Comment by bashtage** [comment]
Fixed in master.
