### ISSUE TITLE
DOC: statsmodels.org not generating documentation formulas

### ISSUE THREAD

**Issue by thequackdaddy** [statsmodels/statsmodels#3464]
Congrats on getting the release out.

Not sure if this belongs here or statsmodels.github.io project

Some of the fancy latex formulas aren't rendering...

Take a look here:

http://www.statsmodels.org/stable/glm.html

Or here:

http://www.statsmodels.org/stable/generated/statsmodels.genmod.families.family.NegativeBinomial.html#statsmodels.genmod.families.family.NegativeBinomial

![image](https://cloud.githubusercontent.com/assets/8186432/22765016/96078cbc-ee33-11e6-87b8-4523cb7ceb01.png)

**Comment by TomAugspurger** [comment]
Thanks. My local version is OK, so they're being generated correctly. Something with what I uploaded or what's being served by Github. I'll take a look now.

**Comment by TomAugspurger** [comment]
@thequackdaddy I believe it's fixed now. Still not entirely sure why they were excluded originally.

**Comment by thequackdaddy** [comment]
Looks great. Thank you!

(Side note, is there documentation on how to build the docs? Just curious.)

**Comment by TomAugspurger** [comment]
The readme at https://github.com/statsmodels/statsmodels/tree/master/docs  has some info (hopefully not too out of date).

**Comment by thequackdaddy** [comment]
Ahh that's what i was looking for. Thanks.
