### ISSUE TITLE
More statsmodels.org problems

### ISSUE THREAD

**Issue by thequackdaddy** [statsmodels/statsmodels#3466]
Hello,

There's a few more missing images on statsmodels.org that I've stumbled across....

1. The logo on the top left is missing
2. After you "View Code" the "close" button is missing

![image](https://cloud.githubusercontent.com/assets/8186432/22789041/765253e2-eea7-11e6-932d-0e6f91784f4f.png)

3. The examples page images are missing:
http://www.statsmodels.org/stable/examples/index.html

4. The "Module Index" link on the index page goes nowhere:

![image](https://cloud.githubusercontent.com/assets/8186432/22790743/cf13cfce-eeac-11e6-8b16-f52c9d9f2f6d.png)

http://www.statsmodels.org/stable/py-modindex.html

Thanks!

**Comment by TomAugspurger** [comment]
Static images (your 2 and 3) have been fixed. Same issue as last night with git ignoring those files for some reason. Probably some config on my computer.

The "close" image thing is a problem with the build. I'll fix that later.

No idea about the index yet.

**Comment by bashtage** [comment]
The index is strange.  It is really hard to get the module index to build for some reason unless you use something heavy handed like `sphinx-autodoc`

**Comment by bashtage** [comment]
Tom's name is also in the docs:

http://www.statsmodels.org/stable/examples/notebooks/generated/ols.html

**Comment by thequackdaddy** [comment]
I think all these issues are resolved.

**Comment by thequackdaddy** [comment]
@TomAugspurger may be helpful here... 

I was looking at this page:

https://www.statsmodels.org/stable/glm.html#module-statsmodels.genmod.families.family

Experimenting with this on my Mac, I *think* the reason for the fact that `cloglog`, `logit`, and `log` not having links in this page are that sphinx is being run in a case insensitive environment. I realized that Macs, by default, use a case insensitive file system. 

Is this something we should look at. I suppose it wouldn't be the end of the world if we just deprecated `cloglog`, `log`, and `logit` link functions as they are just aliases of others...

**Comment by josef-pkt** [comment]
We have some others like pca PCA that have name conflicts in case insensitive systems.

**Comment by bashtage** [comment]
The solution is simple: use Doctr to automatically build the docs, both stable (on tags) and devel (on master commit) on Travis.

**Comment by thequackdaddy** [comment]
As an FYI, I built the docs using doctr on my personal repo. Available in html format [here](https://thequackdaddy.github.io/smdoc/devel/).

Works pretty well... both PCA and the link functions I menioned above don't have case conflicts.

xref #4696

**Comment by TomAugspurger** [comment]
What's the status with doctr builds? Do we just need to configure permissions to push to statsmodels.github.io?

**Comment by bashtage** [comment]
They need to be setup in travis to build and push to devel on master builds and to build and push to stable on tagged builds.

**Comment by bashtage** [comment]
I think on a tag you would need to deploy twice, once to stable and once to version-XXXX for archival purposes.

**Comment by thequackdaddy** [comment]
Is that better than a symbolic link?

**Comment by bashtage** [comment]
Not better, just easier since nothing else required. Git is happy with 2 identical copies of the same pages since are dupe refs.

**Comment by josef-pkt** [comment]
I'm closing this
#4696 added doctr usage and automatic built

The new docbuild uses now travis as computer location in the Warnings in notebooks.
e.g. http://www.statsmodels.org/dev/examples/notebooks/generated/ols.html
