### ISSUE TITLE
Take down old docs at sourceforge?

### ISSUE THREAD

**Issue by alimanfoo** [statsmodels/statsmodels#3467]
I just googled statsmodels after hearing about the new release, and top hit was to old docs on sourceforge http://statsmodels.sourceforge.net/. I was pretty confused for a while there. Maybe take down the old docs or redirect to the new docs?

**Comment by bashtage** [comment]
Sounds like a good idea to me.  Or better would be to redirect to www.statsmodels.org (ideally with 301 if possible so google will stop using it)

**Comment by josef-pkt** [comment]
they are redirecting to the www.statsmodels.org now, changed by Skipper a while ago
