### ISSUE TITLE
Why I got 'The computed initial AR coefficients are not stationary' while using aic_min_order?

### ISSUE THREAD

**Issue by bluemandora** [statsmodels/statsmodels#3505]
I generate some data like [1, 6, 1, 6, 1, 6] and add noises under normal distribution. I use `arma_order_select_ic` to select order. Then aic_min_order is used to fit the ARMA model. Sometime the model works well. But sometimes it raises ValueError.
`ValueError: The computed initial AR coefficients are not stationary`
Here is my code.

```
import statsmodels.api as sm
import numpy as np
x = [1 if i%2 == 0 else 6 for i in range(50)]
eta = np.random.normal(0, 0.01, 50)
x = x + eta
res = sm.tsa.stattools.arma_order_select_ic(x, ic=['aic']) 
print res.aic_min_order
model = sm.tsa.ARMA(x, res.aic_min_order).fit(disp = 0)
print model.predict(45, 55)
```
Do I miss something or ARMA don't fit this kind of data？

**Comment by josef-pkt** [comment]
I had answered on stackoverflow before seeing this issue
---


ARMA is designed for stationary processes and by default imposes stationarity on the parameter estimates.

Your data is not stationary, i.e. it the lag polynomial has a seasonal unit root. The usual treatment is to use seasonal differencing or a deterministic seasonal pattern for example with dummy variables or splines.

Statsmodels has currently no automatic season detection and model selection, but SARIMAX can be used for seasonal integrated ARMA processes.
---

Related question, can we turn of the check and estimate a ARMA without stationarity constraint?

**Comment by ChadFulton** [comment]
> Related question, can we turn of the check and estimate a ARMA without stationarity constraint?

I think the answer is yes; in AR and ARMA you can pass `transparams=False` to `fit`, and in `SARIMAX` you can use `enforce_stationarity=False` and / or `enforce_invertibility=False` in construction.

In ARMA, though, the `transparams` argument does not affect starting parameter estimation, which still raises an exception if non-stationary or non-invertible starting parameters are found. I'm guessing that's what happened here, and that the actual error raised was:

> ValueError: The computed initial AR coefficients are not stationary
You should induce stationarity, choose a different model order, or you can
pass your own start_params.

So one could potentially use ARMA to fit a non-stationary or non-invertible model, but I think you'd have to generate your own starting parameters and also pass `transparams=False`.

**Comment by bashtage** [comment]
Closing as answered.
