### ISSUE TITLE
Documentation Notebooks contain Errors "ModuleNotFoundError: No module named 'pandas_datareader'"

### ISSUE THREAD

**Issue by schlichtanders** [statsmodels/statsmodels#3517]
Dear statsmodels team,
Thanks a lot for your documenting notebooks - for me it is the best resource to get started.

However, it seems that your html generation pipeline is run on a system without the package ``pandas_datareader``. This leads to multiple broken notebooks on http://www.statsmodels.org/devel/examples/index.html

For example [look here](http://www.statsmodels.org/devel/examples/notebooks/generated/statespace_structural_harvey_jaeger.html), however this applies generally to all notebooks.

**Comment by josef-pkt** [comment]
@schlichtanders  thanks for reporting

@TomAugspurger any information about this?

**Comment by TomAugspurger** [comment]
Whoops, `pandas_datareader` is an optional dependency that I forgot to install in my environment when I built the docs. I'll get it added to the `setup.py` extras for docs as well.

**Comment by TomAugspurger** [comment]
@schlichtanders I've pushed a rebuild of the docs. The examples using pandas-datareader are now fixed, thanks.

#3524 adds it as an dependency for building the docs.

**Comment by schlichtanders** [comment]
Thanks for updating the docs!

I just found another dependency missing - maybe an automated check for erros in the documentation notebook is useful to prevent these kind of bugs:
```
ModuleNotFoundError: No module named 'nose'
```

**Comment by josef-pkt** [comment]
@schlichtanders  where did you find the missing `nose`?
nose is a dependency to run the tests, but I thought it's not used otherwise.
However, because the tests require nose, there is no check at all where nose is used.

**Comment by schlichtanders** [comment]
it is in the markov autoregression notebook <http://www.statsmodels.org/dev/examples/notebooks/generated/markov_autoregression.html>
