### ISSUE TITLE
garch loglike correctness

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3535]
It's entirely possible that the code is right and I'm forgetting something about how GARCH loglikelihood is supposed to work, but [this](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/sandbox/tsa/garch.py#L632) looks fishy:

`        llike  =  -0.5 * (np.sum(np.log(sigma2),axis)
                          + np.sum(((self.endog)**2)/sigma2, axis)
                          +  nobs*np.log(2*np.pi))
`

I expected some type of residuals instead of self.endog for the sum of squares.  Is this as intended?

Same thing in two other loglike definitions in that module.

**Comment by josef-pkt** [comment]
I haven't looked at GARCH in years, and Kevin @bashtage  has now the arch package https://pypi.python.org/pypi/arch

to the specific issue:
`endog = resid`
The way I was thinking about this and implemented it is for the case where we have separability between mean and variance/dispersion. I read somewhere that almost all GARCH models are separable, except mean in garch (?) or joint parameter restriction.
At the time I didn't know anything about exponential family of distributions, nor the exact conditions or cases when we have separability.

The analogy is estimating a linear model with heteroscedasticity (HetGLS) where we alternate between estimating the mean and dispersion model. In this case an ARMA-GARCH model would need to alternate between estimating the weighted ARMA model to get the residuals and feed them as endog into GARCH.
The log-likelihoods could be combined to a joint MLE.

However, AFAIR, I never got to the combined or iteration part. 
So in the normal quasi-likelihood case: Estimating ARMA without weights provides a consistent, although inefficient, estimator, GARCH can then be used on the residuals. That last step is what I was trying to solve.

**Comment by josef-pkt** [comment]
(running the `main` in the garch module produces 14 figures, after `plt.show()` and raises exception for refactoring victims. seems it still works a bit  
"statsmodels\sandbox\tsa\examples\ex_mle_garch.py" has a copy of the same garch examples which don't raise an exception without the rpy examples)

**Comment by jbrockmendel** [comment]
Thanks for taking a look.  I'm still not following, will have to do some reading.  Maybe something special is happening in self.geth(params) that explains it.

**Comment by bashtage** [comment]
It looks broadly correct to me for a gaussian log likelihood.
