### ISSUE TITLE
adfuller unexpectedly using all available cores

### ISSUE THREAD

**Issue by lcapalleja** [statsmodels/statsmodels#3542]
I was testing out a variety of functions from sm.tsa in an iPython notebook including adfuller.  Everything was proceeding as normal and I had used adfuller a variety of times with different data sets.  I changed the data I was looking at and noticed that adfuller was suddenly running extremely slow.  I investigated deeper and found that all calls to adfuller were engaging every available CPU.  I am able to reproduce in new iPython kernel and in python shell with different data sets as well as random data.  I cannot get any other function to do this yet I can get adfuller to do it everytime from multiple environments with different data and with different settings for args regression and autolag.

Simplest reproducible example below.
```
import numpy as np
import statsmodels.api as sm

x = np.random.rand(10000)

adf_result = sm.tsa.adfuller(x, regression='c', autolag='BIC')
```

Versions:
statsmodels 0.6.1
numpy 1.11.1
python 3.5.2

Hardware:
Windows Server 2012 R2
2X Intel Xeon E5-2699 v3 (36 cores in total)
64 GB RAM

**Comment by bashtage** [comment]
This is probably due to matrix inversion and the use of a mulththreaded BLAS. If you compute a svd on a largish matrix then you will see the same.

**Comment by josef-pkt** [comment]
See #2914 for restricting the number of cores used by the lapack/blas libraries

Adfuller computes a large numer of ols models if maxlag is not restricted

**Comment by lcapalleja** [comment]
That's a helpful comment. I found that a different process was running in the background which was using approximately 13 cores. Once that process was ended, adfuller performance returned to normal. The speed for a n=1000 series is 20X faster without the background process.

My understanding of multi-processing engines isn't that great but it seems like a 20X reduction in performance shouldn't be caused by 13/36 cores being taken up by another process. Could mulththreaded BLAS be making some bad assumptions around resource availability? I.E. does multithreaded BLAS think that there are 36 cores available when there are only 23, and consequently lose significant performance by waiting for those resources to free up?

**Comment by josef-pkt** [comment]
I don't know how the linalg libraries handle this, but there might be a bottleneck in moving the data around if your other process is also memory intensive. There were some articles or blog posts about "starving CPUs".

**Comment by lcapalleja** [comment]
@josef-pkt thank you. I must have posted my previous comment a few seconds after yours.

I read the email thread and found I was using mkl, which does indeed try to use all available cores.

```
import mkl
mkl.get_max_threads()
```

was giving 36 so I reduced it ...

```
mkl.set_num_threads(8)
```
Works like a charm.

The other process was indeed memory hungry, steadily using about 17GB. But I had about 15-20GB free at any given time when I was getting the previous results. So I think it was mainly a CPU issue.

**Comment by arose13** [comment]
[Here's a solution ](https://stackoverflow.com/a/48665619/2399894)

Only hopefully this fixes all scenarios and system you may be on. 

1. Use `numpy.__config__.show()` to see if you are using OpenBLAS or MKL

From this point on there are a few ways you can do this.

2.1. The terminal route `export OPENBLAS_NUM_THREADS=1` or `export MKL_NUM_THREADS=1`

2.2 (This is my preferred way) In your python script `import os` and add the line `os.environ['OPENBLAS_NUM_THREADS'] = '1'` or `os.environ['MKL_NUM_THREADS'] = '1'`.

*NOTE* when setting `os.environ[VAR]` the number of threads must be a string!

There are probably other options besides openBLAS or MKL but step 1 will help you figure that out.

**Comment by bashtage** [comment]
Closing as answered.  The behavior is expected.

**Comment by GF-Huang** [comment]
This trap is very harmful.
