### ISSUE TITLE
Performance: ProbPlot always fits 

### ISSUE THREAD

**Issue by lorentzenchr** [statsmodels/statsmodels#3547]
In statsmodels.graphics.gofplots `class ProbPlot`, method `__init__` always fits, even with `fit=False`.

**Comment by josef-pkt** [comment]
AFAICS from reading the current code.

The fit is always called, but the fit_params are not used, or at least not added to the distribution instance.
This looks like fit is redundant but the distribution still corresponds to the user provided options without fit.

However, the `fit_params` are used in `sample_percentiles` to standardized the data, so we still get the loc-scale adjustment base on the fitted model. The `sample_percentiles` are used in do_plot, but combined with the non-fitted distribution instance `self.dist`.

I'm not sure what this means, i.e. what does the plot really show if fit=False. Is it just standardizing the plot axis, or actually mixing fitted and preset distributions?
