### ISSUE TITLE
Fisher Information Sign

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3548]
The information method [here](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/generalized_linear_model.py#L542) returns self.hessian(...) instead of -self.hessian(...).

It looks like the [hessian](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/generalized_linear_model.py#L512) method is flipping the sign on what I would otherwise expect.

If hessian is coming back flipped, this would explain the "# TODO check sign, why minus?" [here](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/generalized_linear_model.py#L612).

**Comment by josef-pkt** [comment]
possibly a mixup between maximizing log-likelihood and minimizing negative loglikelihood.

However, we have unit tests for the estimation, so it's not clear to me what's going on. I'm not able to see sign mistakes when browsing the code.

**Comment by josef-pkt** [comment]
(aside: I just saw that hessian has `observed` keyword, but AFAIR we don't use EIM. Needs to be connected to fit and cov_type options.)
