### ISSUE TITLE
UnobservedComponentsResults - How to populate?

### ISSUE THREAD

**Issue by Stogie03** [statsmodels/statsmodels#3550]
I have run a UCM model and want to use the model to predict X days into the future. I see in the documentation that the UnobservedComponentsResults class has this ability, but I can not seem to getmy fit model into the Results class so I can use the predict/forecast functions?

How is this intending to be used?

my code snippet:
`unrestricted_model = {
        'level': 'lltrend', 'cycle': True, 'ar': 1, 'damped_cycle': False, 'irregular': True, 'stochastic_level': True,
        'stochastic_trend': True, 'stochastic_cycle':True, 'seasonal_period':26 
}
ucm_model=structural.UnobservedComponents(endog=np.array(ucmInput.total_units),
                                        exog=np.array(ucmInput[exog_var]), **unrestricted_model)
ucm_res = ucm_model.fit(method='powell')

ucm_res_obj=structural.UnobservedComponentsResults(ucm_model,unrestricted_model, ucm_res)
`

**Comment by josef-pkt** [comment]
In your code `ucm_res` should be the results instance with the corresponding predict/forecast methods.
There is no need to construct it yourselves.

**Comment by Stogie03** [comment]
Thank you josef!
