### ISSUE TITLE
Undefined name k_ar

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3552]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/vector_ar/var_model.py#L343

```
    def predict(self, params, start=None, end=None, lags=1, trend='c'):
        """
        Returns in-sample predictions or forecasts
        """
        if start is None:
            start = k_ar
```

k_ar isn't defined here.  Should it be defaulting to "lags"?

**Comment by josef-pkt** [comment]
Looks fishy to me.

my guess is that there shouldn't be a `lags`, 
lags and k_ar should be defined by the model, and correspond to shape of params.

i.e. i expect that this raises an exception if lags != self.k_ar corresponding to params

**Comment by josef-pkt** [comment]
that is, we need to check usage and test cases to see how this is **supposed** to work

**Comment by jbrockmendel** [comment]
In context, it looks very much like "lag" is the intended value here:


    
    def predict(self, params, start=None, end=None, lags=1, trend='c'):
        """
        Returns in-sample predictions or forecasts
        """
        if start is None:
            start = k_ar

        # Handle start, end
        start, end, out_of_sample, prediction_index = (
            self._get_prediction_index(start, end))

        if end < start:
            raise ValueError("end is before start")
        if end == start + out_of_sample:
            return np.array([])

        k_trend = util.get_trendorder(trend)
        k = self.neqs
        k_ar = lags


It's just a matter of k_ar being defined in the wrong order (in fact, I now remember fixing this was in a [PR](https://github.com/statsmodels/statsmodels/pull/3515/commits/0545e780c9004b8b6c3e10f76dccb8eba9d514c9) a couple weeks ago).



> lags and k_ar should be defined by the model, and correspond to shape of params.
> 
> i.e. i expect that this raises an exception if lags != self.k_ar corresponding to params
> 

I think this ties in to a bigger issue with a bunch of the VAR/AR/ARMA/etc models: what attributes get bound at what point.  There are a handful of "TODO" comments scattered about that suggest this issue has come up before.

This method is in the VAR class, which does not have a k_ar attribute.  The fit() method allows the user to choose the k_ar (via "ic" and "maxlags"), which then becomes an attribute of the VARResults object.

nobs depends on k_ar, and self.nobs gets set inside the call to fit().  This is pretty benign, and commenting it out doesn't appear to break any tests.  Just on principle, I like being able to look at `__init__` and see exactly what attributes to expect.  This becomes a bigger issue in ar_model and arima_model.  But this comment is long enough; that can wait for another day.

**Comment by josef-pkt** [comment]
> I think this ties in to a bigger issue with a bunch of the VAR/AR/ARMA/etc models: what attributes get bound at what point. There are a handful of "TODO" comments scattered about that suggest this issue has come up before.

We became stricter over time with setting model/data specific attributes in `__init__`. However, the core of these tsa models were written before that when we thought allowing it to be an argument in fit provides more computational efficiency or easier specification search. (e.g. A pure ARMA(p, q) does not need to create data for a specific p and q, it just defines the filter length. However, VAR needs to create the full design matrix for specific number of lags.)

**Comment by jbrockmendel** [comment]
NameError no big deal.  Closing.
