### ISSUE TITLE
some questions about 'lmer'

### ISSUE THREAD

**Issue by liushunge** [statsmodels/statsmodels#3553]
what does lmer(responce ~ factor1*factor2 + (factor1*factor2 | subject) + (factor1*factor2| item), data) mean?
and 
what does lmer(responce ~ factor1*factor2 + (factor1+factor2 | subject) + (factor1+factor2| item), data) mean?

**Comment by josef-pkt** [comment]
this is not a statsmodels question, you need to ask this on a R mailing list or stackoverflow
