### ISSUE TITLE
get_rdataset is broken

### ISSUE THREAD

**Issue by craighagerman** [statsmodels/statsmodels#3554]
Seems that get_rdataset() function is broken

```python
>>> import statsmodels

>>> statsmodels.__version__
 '0.8.0'

>>> duncan = statsmodels.datasets.get_rdataset("Duncan", "car")
...

ValueError: Dataset Duncan was not found.
```

Other rdatasets raise the same not found error.

**Comment by sarah-mcl** [comment]
I also get this error with get_rdataset().  Tested with "Moore" and "Duncan" datasets.

**Comment by josef-pkt** [comment]
Thanks for reporting, 

It looks like github has changed the url
from
'https://raw.github.com/vincentarelbundock/Rdatasets/master/csv/car/Duncan.csv'
to 
'https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/car/Duncan.csv'

When I open the `raw.github.com` csv url in the browser, then it redirects to `raw.githubusercontent.com`
but most likely urlopen does not follow the redirect (or something like that)

@sarah-mcl   I think those are the cached zipped csv files. Did you get those in the past, or from the fresh install? If the Moore file is cached, then calling get_rdataset again should just use that one and not open any web page, IIRC.

**Comment by josef-pkt** [comment]
This might require a 0.8.1 bugfix release since many examples rely on this, even though it's not essential for using statsmodels for statistical analysis.

**Comment by sarah-mcl** [comment]
@josef-pkt Those files appear when I run line 2 of the following code:
`In [1]: import statsmodels.api as sm`
`In [2]: moore = sm.datasets.get_rdataset("Moore", "car", cache=True)`

I also get the "dataset not found" error.  If I try the command again, with cache=True or cache=False, I still get the error.

**Comment by josef-pkt** [comment]
@sarah-mcl   I just checked also, and even a file that I had cached from before still raises the exception. So the code tries the url open even if file is cached.

AFAICS, based on a quick google search urlopen does not allow following redirects. (recommendation on stackoverflow is requests package.)

Also, I don't see a simple workaround besides copying the entire get_rdataset function and adjusting the base github url.

**Comment by josef-pkt** [comment]
Maybe it's not the redirect and url at all.

Vincent's repo doesn't have the doc/rst files anymore. So the website content is broken and maybe not our script.
(I'm working with debugger now and it fails with url `https://raw.github.com/vincentarelbundock/Rdatasets/master/doc/car/rst/Duncan.rst`
)

**Comment by sarah-mcl** [comment]
@josef-pkt I did as you suggested and copied the get_rdataset function (and the other functions in the util.py file), and adjusted the base github url.  I still got the "dataset not found" error though. 

`data_base_url = ("https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/"+package+"/")`
`docs_base_url = ("https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/doc/"+package+"/rst/")`

With the updated urls the data is read correctly, but the doc is not.
`doc, _ = _get_data(docs_base_url, dataname, cache, "rst")`
returns the "dataset not found" error, and when I try to browse to the docs url myself, the page won't load.

**Comment by vincentarelbundock** [comment]
I will try to fix this upstream soon. Sorry for the trouble.

**Comment by josef-pkt** [comment]
@sarah-mcl thanks for checking
see my last comment. Vincent deleted the rst files that we need to add the meta information.

I guess the short term workaround is to construct the csv url and use pandas.
I haven't checked whether that differs from the dataframe after `get_rdataset` 

```
>>> import pandas as pd
>>> url = 'https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/car/Duncan.csv'
>>> duncan = pd.read_csv(url)
>>> duncan.head()
   Unnamed: 0  type  income  education  prestige
0  accountant  prof      62         86        82
1       pilot  prof      72         76        83
2   architect  prof      75         92        90
3      author  prof      55         90        76
4     chemist  prof      64         86        90

>>> duncan.dtypes
Unnamed: 0    object
type          object
income         int64
education      int64
prestige       int64
dtype: object
```

maybe `get_rdataset` needs a refactoring and update

**Comment by vincentarelbundock** [comment]
I added rst files back to the upstream repo. Could you try again to see if that fixes the issue?

Thanks!

@craighagerman @sarah-mcl @josef-pkt

**Comment by sarah-mcl** [comment]
@vincentarelbundock Works for me now! Thanks!

**Comment by josef-pkt** [comment]
works for me also

@vincentarelbundock Thanks

given that meta info in `__doc__` and title could be optional, we should try except protect the loading of the `rst` files, then we would only require the csv files and have meta info optional if available.
But that will not happen until a new release.

**Comment by vincentarelbundock** [comment]
well now that I know that people use those files, I just won't remove them. Also, I wrote a simple bash script, so it's trivial to maintain now (the old version was a pain).

**Comment by simonduane** [comment]
I'm new to statsmodels and started by reading https://www.statsmodels.org/stable/gettingstarted.html#
Frustrated to find that the very first example doesn't work at the line
In [4]: df = sm.datasets.get_rdataset("Guerry", "HistData").data
Since this issue breaks the tutorial part of the online documentation, I think that it deserves a higher priority. It's gone unfixed for a year now.

**Comment by guihigashi** [comment]
get the docs as HTML 
```
287:     docs_base_url = ("https://raw.github.com/vincentarelbundock/Rdatasets/"
288:                     "master/doc/"+package+"/")
295:     doc, _ = _get_data(docs_base_url, dataname, cache, "html")
```
and... in jupyter notebook
```
import statsmodels.api as sm
from IPython.core.display import display, HTML

duncan_prestige = sm.datasets.get_rdataset("Duncan", "car")
display(HTML(duncan_prestige.__doc__))
```

**Comment by simonduane** [comment]
What does
...+package+...
refer to in line 288?
I literally did what you said and, of course, got
NameError: name 'package' is not defined
Thanks in anticipation

**Comment by vincentarelbundock** [comment]
@simonduane sorry, I think this was my fault. Can you try again?

**Comment by simonduane** [comment]
Excellent - that's fixed it. Many thanks!

Happy to have helped ;-)

**Comment by yuanzhaoYZ** [comment]
It looks like github has changed the url again.
from
'https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/car/Duncan.csv'
to
'https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/carData/Duncan.csv'

**Comment by bashtage** [comment]
This works, just need to use the correct data set name, e.g.,

`duncan = statsmodels.datasets.get_rdataset("Duncan", "carData")`
