### ISSUE TITLE
can't run the latest master build, also would like to submit changes, how?

### ISSUE THREAD

**Issue by EdStone** [statsmodels/statsmodels#3555]
Hi All:
I would like to start adding type hints (PEP 484 and PEP526) and submitting back.
I cloned the master repo and tried to run a simple example, filed.
What do you suggest (i.e. which version branch / tag should I check out, etc.) in order to actually (successfully) run the examples, make appropriate changes and then submit a pull request.

Not sure if relevant, when I do conda install in Windows all examples work well; when I clone out the master from git and run the same examples, I get many errors (even tag v0.8.0).

Thank you,
E

**Comment by josef-pkt** [comment]
If you check out the source, then you need cython and a C compiler to build the extensions and install statsmodels.

It would be best to just start with one module and see whether and how it works.

two possible problems
- type hints are ugly and make the code less readable
- one of the main "types" is `array_like` which is anything that can be converted to an array by np.asarray, see numpy documentation guide for some of the type shortcuts used in docstrings.
  Also, we fully support  pandas Series or DataFrames besides numpy arrays in the models. 

https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

**Comment by bashtage** [comment]
This is likely fixed in master, and old.  Please reopen if you still have this issue.
