### ISSUE TITLE
statsmodels 0.8.0 is missing smf.WLS.fit_regularized 

### ISSUE THREAD

**Issue by Sadrpour** [statsmodels/statsmodels#3559]
I have been using statsmodels 0.6.0 and was able to train models using
```
import statsmodels.api as smf
smf.WLS.fit_regularized()
```
This allowed me to fit a weighted least squares estimation with L1/L2 regularization.
I recently upgraded to statsmodels 0.8.0 to access improved time series models, but do not see the WLS regularized module anymore. 

In statsmodels 0.8.0 we have:
```
import statsmodels.api as smf
smf.OLS.fit_regularized()
```
which is not the same thing and missing the weight parameters. How can i apply smf.WLS.fit_regularized() in statsmodels 0.8.0

**Comment by kshedden** [comment]
This may be something that happened when we made fit_regularized more generic, I will try to look into it later today.

**Comment by Sadrpour** [comment]
Dr. Shedden thank you much, we are trying to use statsmodels 0.8.0 in production and your response will help us move forward. By the way, i was in your Stats650 class, an amazing class, you are one of the smartest people i have met.
