### ISSUE TITLE
How to save only the predicting method?

### ISSUE THREAD

**Issue by youjin2** [statsmodels/statsmodels#3564]
Hi.
I'm currently trying to fit the OLS and using it for prediction.

import statsmodels.api as sma
ols = sma.OLS(myformula, mydata).fit()
with open('ols_result', 'wb') as f:
pickle.dump(ols ,f)

However, my data set is about 5GB and OLSResults takes about 6GB memory.
It's the problematic part because i want to share the model.predict() with other environments, but moving and loading 6GB file takes too much time.

with open('ols_result', 'wb') as f:
pickle.dump(ols.predict ,f)

This code does not solved my situation. (it also takes 6GB)

Is there any way to save only the predicting part of the model?

**Comment by josef-pkt** [comment]
I replied to the other issue.
Why did you start a new issue?  (issues can be edited)

**Comment by youjin2** [comment]
Sorry, i'm not familiar with a GitHub and made a mistake..

**Comment by josef-pkt** [comment]
I'm closing this one in favor of #3563 because I already started to comment there.
You can edit comments and description if necessary.

**Comment by youjin2** [comment]
thx :)
