### ISSUE TITLE
BUG: discrete countmodel predict with exposure and offset

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3565]
It looks like this an issue a while back: https://github.com/statsmodels/statsmodels/issues/1609

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/discrete/discrete_model.py#L715

```
class CountModel(DiscreteModel):
    def __init__(self, endog, exog, offset=None, exposure=None, missing='none',
                 **kwargs):
        super(CountModel, self).__init__(endog, exog, missing=missing,
                                         offset=offset,
                                         exposure=exposure, **kwargs)
        if exposure is not None:
            self.exposure = np.log(self.exposure)
```

I was confused as to why we would set self.exposure to [the log of] its previous value instead of using the argument.  Tracing through all of the `super`s, it looks like the argument exposure gets attached as self.exposure back in base.model.Model._handle_data.

On the One-Obvious-Way principal, I tried replacing the `self.exposure` with `exposure`, and found that a test breaks: discrete.tests.test_discrete.test_formula_missing_exposure

I've spent some time trying to track this down and haven't figured it out.  If you can confirm that it is as intended, it'll save me some time.

A few lines later in the `predict` method, the exposure and offset arguments look like they are ignored again: https://github.com/statsmodels/statsmodels/blob/master/statsmodels/discrete/discrete_model.py#L748
```
        if exog is None:
            exog = self.exog
            offset = getattr(self, 'offset', 0)
            exposure = getattr(self, 'exposure', 0)
```

If it'll be accepted, I'll volunteer to refactor these to reduce redirection and increase transparency.  I cringe a little bit every time I see a `delattr`.

**Comment by josef-pkt** [comment]
The logic in `predict` looks correct to me (maybe). The fact that we store log-exposure as attribute `exposure` is a annoyance, but refactoring that will have to wait. I guess the initial intention was to save on having to repeatedly log the same array during optimization and usage (that's #1609, extending/refactoring exposure is #3491 with associated comments in other issues on var_weights versus exposure)

to predict: offset and exposure are added in the linear prediction in the return lines.
exposure can be 0 or something, If exog is None, then we use the attached attributes.

However, I just see that if either offset or exposure are not None, but exog is None, then offset and exposure arguments in predict are ignored. Is this what you mean?

**Comment by josef-pkt** [comment]
BTW: offset is missing in the discrete_models outside of count models and still needs to be added. (#2107 seems to be the only related issue for that)

**Comment by jbrockmendel** [comment]
> However, I just see that if either offset or exposure are not None, but exog is None, then offset and exposure arguments in predict are ignored. Is this what you mean?

Yes, that's exactly what I was referring to for the `predict` method.

As to the `__init__` question, I tracked down why the test was breaking and it had to do with the inputs being truncated upstream when they contain an `np.nan`.

**Comment by josef-pkt** [comment]
ignoring offset and exposure if exog is None is a bug in that case. A PR with fix would be good.

GLM.predict looks like handles it correctly but the if and and and conditions are maybe more complicated than necessary.
