### ISSUE TITLE
statsmodels sourceforge

### ISSUE THREAD

**Issue by denadai2** [statsmodels/statsmodels#3573]
When I search statsmodel I often arrive at http://statsmodels.sourceforge.net/, which is an old version of the website (where we have development version 0.7).

Is it possible to redirect/remove this website? :)

**Comment by josef-pkt** [comment]
I have no idea about setting up redirecting websites.

It's annoying, I always have to edit the url after a google search.

**Comment by denadai2** [comment]
I don't know sourceforge so much but I think you can just do this http://stackoverflow.com/questions/5411538/redirect-from-an-html-page
and remove the other pages. In some weeks google will delete the old website from the indexes

**Comment by josef-pkt** [comment]
This was fixed a while ago. Skipper had added the redirect to the sourceforge page
