### ISSUE TITLE
DEPR: pd.WidePanel is no more

### ISSUE THREAD

**Issue by jreback** [statsmodels/statsmodels#3580]
from https://travis-ci.org/pandas-dev/pandas/jobs/215035109

We removed ``WidePanel`` (just use ``Panel``) from pandas in 0.20.0-dev (upcoming), though has long been deprecated.

This showed up in our doc-build (as example of using statsmodels). You should just be able to remove it I think.

cc @TomAugspurger 

```
>>>-------------------------------------------------------------------------
Exception in /tmp/doc/source/basics.rst at block ending on line 755
Specify :okexcept: as an option in the ipython:: block to suppress this message
AttributeErrorTraceback (most recent call last)
<ipython-input-140-2592b91fd0e2> in <module>()
      1 (bb.query('h > 0')
      2    .assign(ln_h = lambda df: np.log(df.h))
----> 3    .pipe((sm.poisson, 'data'), 'hr ~ ln_h + year + g + C(lg)')
      4    .fit()
      5    .summary()
/home/travis/build/pandas-dev/pandas/pandas/core/generic.py in pipe(self, func, *args, **kwargs)
   2850                                  'argument' % target)
   2851             kwargs[target] = self
-> 2852             return func(*args, **kwargs)
   2853         else:
   2854             return func(self, *args, **kwargs)
/home/travis/miniconda3/envs/pandas/lib/python3.5/site-packages/statsmodels/base/model.py in from_formula(cls, formula, data, subset, drop_cols, *args, **kwargs)
    153 
    154         tmp = handle_formula_data(data, None, formula, depth=eval_env,
--> 155                                   missing=missing)
    156         ((endog, exog), missing_idx, design_info) = tmp
    157 
/home/travis/miniconda3/envs/pandas/lib/python3.5/site-packages/statsmodels/formula/formulatools.py in handle_formula_data(Y, X, formula, depth, missing)
     61                                return_type='dataframe', NA_action=na_action)
     62     else:
---> 63         if data_util._is_using_pandas(Y, None):
     64             result = dmatrices(formula, Y, depth, return_type='dataframe',
     65                                NA_action=na_action)
/home/travis/miniconda3/envs/pandas/lib/python3.5/site-packages/statsmodels/tools/data.py in _is_using_pandas(endog, exog)
     97 def _is_using_pandas(endog, exog):
     98     # TODO: Remove WidePanel when finished with it
---> 99     klasses = (pd.Series, pd.DataFrame, pd.WidePanel, pd.Panel)
    100     return (isinstance(endog, klasses) or isinstance(exog, klasses))
    101 
AttributeError: module 'pandas' has no attribute 'WidePanel'
<<<-------------------------------------------------------------------------
```

**Comment by jreback** [comment]
xref https://github.com/pandas-dev/pandas/pull/10892

**Comment by josef-pkt** [comment]
This might require a statsmodels 0.8.1 when the next pandas is released. 
Based on the traceback it looks like it's in the regular data handling path even if WidePanel is never used. In that case no model would work with pandas anymore.

We must have missed this deprecation in 0.8.

short term workaround would be if pandas just keeps the name WidePanel with an exception in the `__init__` that it doesn't exist anymore.

(I didn't look at the code, just reading the traceback.)

**Comment by jreback** [comment]
we're you planning an 0.8.1 anyway? timetable?

**Comment by jreback** [comment]
I think I will revert this removal anyhow and just do it in the next major version (but would appreciate fixing statsmodels too in any event)

**Comment by josef-pkt** [comment]
We were not planning an 0.8.1 because nothing serious enough came up yet.
(There is one regression compare to 0.8rc in fit_regularized that got reported a few days ago.)

However, this one would be very serious. The `_is_using_pandas` utility function is used in many places in core parts. It just includes the name of WidePanel as possible pandas class.

These are parts where we explicitly check isinstance instead of duck typing.

```
def _is_using_pandas(endog, exog):
    # TODO: Remove WidePanel when finished with it
    klasses = (pd.Series, pd.DataFrame, pd.WidePanel, pd.Panel)
    return (isinstance(endog, klasses) or isinstance(exog, klasses))
```

I just saw your new comment. All the `WidePanel` cases were (supposed to be) fixed for 0.8, except we missed this one. 
As I mentioned only the existence of the name/class is required.

We are planning to get an 0.9 out by summer.

**Comment by gfyoung** [comment]
1) @josef-pkt : What is the status of a `0.9` release (it is beginning of July now)

2) @jreback : Does your comment regarding pushing the deprecation removal (see <a href="https://github.com/statsmodels/statsmodels/issues/3580#issuecomment-289236770">here</a>) to the next release still stand?  Should we just flag its removal for 0.21 and proceed with it?

**Comment by josef-pkt** [comment]
The plan is to release statsmodels 0.9 at the end of summer, something like end of August or beginning of September.

**Comment by jreback** [comment]
@josef-pkt any timing on a 0.9.0 release?
