### ISSUE TITLE
_score_nbin optimization

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3582]
Running the tests locally, I see `discrete_model.NegativeBinomial._score_nbin` stands out as a hotspot.  It is taking about 28 seconds, almost 7% of the runtime.  More surprising is that the profiler is attributing almost all of that to `_score_nbin` itself and not to calls made from within the function.  For the moment I am assuming that the cost is actually in the calls to `scipy.special.digamma` and that the reporting is misleading.

It turns out that there is a cython implementation of digamma reachable via `cimport scipy.special.cython_special.psi as digamma`.  Supposedly.  I haven't been able to get it to work, but someone with stronger cython-fu might have better luck.

**Comment by josef-pkt** [comment]
In general, without having looked at the detail.

cython is only really useful if we have expensive python loops. I assume in this case using cython would not improve much since a vectorized digamma and the cython digamma would take about the same time, i.e. the loop is already in C from using the special function.

special.digamma and special.psi are the same function IIUC.

**Comment by josef-pkt** [comment]
for benchmarking: a comparison with complex step derivative would be interesting.

I just saw that score_obs wasn't rewritten to use the analytical formula

```
    def score_obs(self, params):
        sc = approx_fprime_cs(params, self.loglikeobs)
        return sc
```

`score_obs(params).sum(0)` should be the same as `score(params)` at at least 1e-13 precision (I guess)

**Comment by jbrockmendel** [comment]
>`_score_nbin` does a lot of duplicate computation, which is expensive if digamma is expensive

You're right, so there's some low-hanging fruit there.  It turns out I had already made that change in the branch that produced those profiling results, so it may still warrant looking at.

> I just saw that score_obs wasn't rewritten to use the analytical formula

Good catch.  I don't see that showing up in the >1s portion of the profile results.

**Comment by jbrockmendel** [comment]
> special.digamma and special.psi are the same function IIUC.

Yes.  The only reason this observation might have been useful is because special.cython_special doesn't export the "digamma" alias, so it might be easy to overlook.  Sounds like it's worth de-duplicating the calls to digamma, but otherwise this is a non-issue until someone starts using this heavily.

**Comment by josef-pkt** [comment]
> I don't see that showing up in the >1s portion of the profile results.

`score_obs` might not be used much in the unit tests. It is only used for sandwich cov_types for now (AFAIR) and not every model is tested, given that it's mostly generic code (It looks like neg bin is tested for cluster robust).
