### ISSUE TITLE
Run SARIMAX on single core

### ISSUE THREAD

**Issue by pranavbahl2308** [statsmodels/statsmodels#3583]
I want to run SARIMAX models for multiple time series in parallel but the model seems to be running some underlying process in parallel. Due to that the parallel processing I am doing is stepping over the toes of already implemented parallel processing in SARIMAX.
Is there any way I can run the SARIMAX algorithm over single core.

**Comment by josef-pkt** [comment]
most likely it's the blas/lapack library set up for multi core. AFAIK we don't have explicit multicore computation in the statespace models

see #2914

**Comment by pranavbahl2308** [comment]
Thanks a lot, changing the mkl setting made it work as expected.

**Comment by josef-pkt** [comment]
Good, closing given we have the FAQ issue

**Comment by udaykiranreddykondreddy** [comment]
@pranavbahl2308  can i find the mkl setting i'm also facing the same issue
