### ISSUE TITLE
Tests for VAR and SVAR?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3587]
Before trying to implement anything new in these areas, I'm trying to get the test coverage up so I can confidently avoid Creative Destruction.

The biggest untested blocks I see are `svar_model.SVARResults.sirf_errband_mc`, along with `var_model.VARResults.irf_errband_mc`.  Are there canonical examples I can use to write tests against?

**Comment by josef-pkt** [comment]
better test coverage in VAR would be very good. SVAR has little AFAIR. (I have no idea about the status of dynamic with zero test coverage.)

However, VECM #3246 should be merged within the next few weeks, or sooner depending on review time. You might want to check there for any overlap and changes related to the VAR. There are several changes so VAR can be used with VECM.

There is also a VAR cleanup PR #3028. I don't think that can be merged as is, but it has some changes that would be good to merge. Maybe you find some overlap there that would help.

(Personal aside: When I started out with learning numpy/scipy and fixing scipy stats, then by a rough guess it was 50% writing unit tests, 40% bughunting and detective work (including figuring out what something was supposed to be and to) and 10% actually changing or writing code.)

**Comment by jbrockmendel** [comment]
I'll take a look at those PRs before moving forward.

**Comment by jbrockmendel** [comment]
Following up on this, are #3246 and #3028 still imminent?  I'd like to go full-steam-ahead on the various non-statespace [...]AR[...] models.
