### ISSUE TITLE
Coverage for Cython code?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3588]
I've been trying to get coverage to report on the cython code in tsa.statespace etc, but [these](http://blog.behnel.de/posts/coverage-analysis-for-cython-modules.html) instructions are getting me nowhere.  Anyone else have experience with this?

**Comment by bashtage** [comment]
I have also found coverage impossible on complex Cython files.  Only the toy examples seem to work.

**Comment by jbrockmendel** [comment]
I've made some progress on this front, would like to implement it in statsmodels.  Before moving forward I'd like to get buy-in.

cc: @ChadFulton

**Comment by bashtage** [comment]
Do you have a branch?  Would like to see as I never got it working.

**Comment by bashtage** [comment]
I think it is a good idea.

**Comment by jbrockmendel** [comment]
Haven't implemented it for statsmodels (have recently grown gunshy about supplying labor without explicit pre-approval #3985), but got it mostly-working in another project after tinkering with [this](https://medium.com/@dfdeshom/better-test-coverage-workflow-for-cython-modules-631615eb197a).  Here are the relevant bits of the tox.ini and setup.py:

```
[testenv:coverage]
setenv=
	linetrace=TRUE
	CYTHON_TRACE=TRUE
	CYTHON_TRACE_NOGIL=TRUE
commands=
	coverage erase
	python setup.py build_ext --inplace --force
	pytest --cov-config .coveragerc --cov=pdsm
```

The idea being to run with coverage just for this testenv and otherwise compile without the extra overhead.  That part still has some kinks to work out.

```
linetrace = os.environ.get('linetrace', False)
CYTHON_TRACE = str(int(bool(linetrace)))

directives = {'linetrace': False}
macros = []
if linetrace:
    # https://pypkg.com/pypi/pytest-cython/f/tests/example-project/setup.py
    directives['linetrace'] = True
    macros = [('CYTHON_TRACE', '1'), ('CYTHON_TRACE_NOGIL', '1')]

exts = [
    Extension("pdsm.tslibs.conversion",
              sources=["tslibs/conversion.pyx"],
              include_dirs=[np.get_include()],
              define_macros=macros),
    [...]
    ]

setup(
    [...]
    ext_modules=cythonize(exts, compiler_directives=directives),
    [...]
    )
```

**Comment by ChadFulton** [comment]
I definitely agree that coverage would be a great thing to have.

**Comment by ChadFulton** [comment]
> Before moving forward I'd like to get buy-in.

> I definitely agree that coverage would be a great thing to have.

I guess I should add that the main caveat is that it is not a particular interest of *mine* at the moment, so maybe you could tell me what your expectations for me would be, so that I can let you know if I will be able to fulfill them, before you do too much work :)

**Comment by jbrockmendel** [comment]
> tell me what your expectations for me would be

Moral support mostly.

**Comment by ChadFulton** [comment]
> Moral support mostly.

I can definitely give that. My hope for an easy PR would be that the changes would be essentially outside the Cython code? Does that sound like what you're expecting?

**Comment by ChadFulton** [comment]
>  an easy PR

(easy to review and hopefully merge, that is. I gather that getting the coverage setup may not be easy at all!)

**Comment by jbrockmendel** [comment]
I may circle back to this, but for the time being am pretty discouraged from putting effort into "code quality".

**Comment by ChadFulton** [comment]
Well that's understandable, but my moral support will remain if you get a chance to.
