### ISSUE TITLE
Typo in heteroskedasticity test?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3593]
From tsa.mlemodel.MLEResults.test_heteroskedasticity, it looks like `pval_upper`is used [for](https://github.com/statsmodels/statsmodels/blob/8d5c8f2df31f7a5ab6ad0b23907d2965acb58b40/statsmodels/tsa/statespace/mlemodel.py#L2232) [both](both) of the one-sided tests.  Should one of these be `pval_lower`?
```
                # Calculate the one- or two-sided p-values
                alternative = alternative.lower()
                if alternative in ['i', 'inc', 'increasing']:
                    p_value = pval_upper(test_statistic)
                elif alternative in ['d', 'dec', 'decreasing']:
                    test_statistic = 1. / test_statistic
                    p_value = pval_upper(test_statistic)
                elif alternative in ['2', '2-sided', 'two-sided']:
                    p_value = 2 * np.minimum(
                        pval_lower(test_statistic),
                        pval_upper(test_statistic)
                    )
```

In the subset of tests I am running locally, the 'increasing' case is not getting hit, so that is my guess for where the typo is.

**Comment by josef-pkt** [comment]
In the `'decreasing'` case the test_statistic is inverted. So this looks correct to me. 
test statistic is ratio of variances AFAICS

**Comment by josef-pkt** [comment]
However, there is a bug if there are nans.

If there are unequal number of nans in the first and second sample, then the nobs and dfs are not the same, so inverting the test statistic is not enough if `numer_dof != denom_dof`

Dropping the inversion of test_statistic and using pval_lower should fix it.

**Comment by jbrockmendel** [comment]
Yep, I completely missed that inversion.

**Comment by ChadFulton** [comment]
> However, there is a bug if there are nans.

Yes, thanks for pointing this out.

**Comment by ChadFulton** [comment]
Also @jbrockmendel, I wanted to echo something @josef-pkt said in another issue - I really appreciate you looking over the code!
