### ISSUE TITLE
Ignoring rownames/colnames inputs?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3594]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/base/data.py#L513

```
    def attach_generic_columns_2d(self, result, rownames, colnames=None):
        colnames = colnames or rownames
        rownames = getattr(self, rownames, None)
        colnames = getattr(self, colnames, None)
        return DataFrame(result, index=rownames, columns=colnames)
```

Should the `getattr` calls be a fallback in case the arguments are None?

**Comment by josef-pkt** [comment]
I'm not sure, and I'm also not sure what you mean. I never looked at those details. 
I guess that the arguments are the attribute names, while after the getattr call, the same "names" refer to the content of the attributes. If there are not attributes, then pandas is creating default names/labels.

AFAIK, this is specifically written for cov_params, and it works, AFAIR.

Most likely not a bug, but those parts get refactored whenever different use cases show up.

**Comment by jbrockmendel** [comment]
Another mistake on my part.  I was confusing `getattr(self, rownames, None)` with `getattr(self, 'rownames', None)`.  I'll go sit in the corner for a bit.

**Comment by josef-pkt** [comment]
I'm glad someone is reviewing the code, even if there are a few false positives.
(Maybe next time I can ask you a question.)

Also, it's useful to find "suspicious" code, because we might get bitten by it in future enhancements even if it works for current use cases.
