### ISSUE TITLE
scikits.statsmodels does not install on python3

### ISSUE THREAD

**Issue by LuisBL** [statsmodels/statsmodels#3598]
The official documentation https://scikits.appspot.com/statsmodels says that "scikits.statsmodels has been ported and tested for Python 3.2." but I get:

```
$ pip install scikits.statsmodels
Collecting scikits.statsmodels
   Using cached scikits.statsmodels-0.3.1.tar.gz
   Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dbu7u2oo/scikits.statsmodels/setup.py", line 96
        print "debug import success GIT_REVISION", GIT_REVISION
                                            ^
    SyntaxError: Missing parentheses in call to 'print'
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dbu7u2oo/scikits.statsmodels/
```

http://stackoverflow.com/questions/43255148/scikits-statsmodels-can-not-be-installed-with-pip-python-3-5

**Comment by TomAugspurger** [comment]
http://www.statsmodels.org/stable/index.html is the home of the documentation, so you `pip install statsmodels`

[PyPI](https://pypi.org/project/statsmodels/#files) has wheels for 3.4+. I don't know the lowest version of python 3 that's officially supported.
