### ISSUE TITLE
cannot access SARIMAX

### ISSUE THREAD

**Issue by Dan195** [statsmodels/statsmodels#3600]
I have the following lines of code 
`import statsmodels.api as sm
arima200 = sm.tsa.SARIMAX(ts_train, order=(2,0,0))`

and am getting the error `AttributeError: module 'statsmodels.tsa.api' has no attribute 'SARIMAX'`

Am i importing SARIMAX incorrectly?

**Comment by ChadFulton** [comment]
What version of Statsmodels are you using (`import statsmodels.api as sm`, then `print(sm.version.version)`? SARIMAX is only available in 0.8.0 and above.

**Comment by Dan195** [comment]
I am using 0.8.0, which is why im slightly confused. Sorry, I intended to include that in the initial comment.

**Comment by ChadFulton** [comment]
Can you double check the version.version output? Just to make sure the imported library is the 0.8 one.

**Comment by Dan195** [comment]
Yes. I am getting 0.8.0. I tried `print(sm.version.version)` and `!pip freeze`. 

This is my full code snippet. 
`]:




#Model Estimation
# Fit the model
import statsmodels.api as sm 
arima200 = sm.tsa.SARIMAX(ts_train, order=(2,0,0))
model_results = arima200.fit()
model_results.summary()



---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-58-b844b9994ae7> in <module>()
      1 #Model Estimation
      2 # Fit the model
----> 3 import statsmodels.api as sm
      4 arima200 = sm.tsa.SARIMAX(ts_train, order=(2,0,0))
      5 model_results = arima200.fit()

AttributeError: module 'statsmodels' has no attribute `

**Comment by ChadFulton** [comment]
It looks like probably Statsmodels has not been installed correctly since it looks like it's not even importing `statsmodels.api`.

I recommend uninstallying statsmodels and re-installing it.

**Comment by josef-pkt** [comment]
@Dan195 Do you have a local file (on the python patth) that is called `statsmodels.py`?
If so. it would shadow the package.

**Comment by Dan195** [comment]
I did, It appeared that I was somehow missing the sarimax.py ffile after going through my statsmodels directory and comparing it to GitHub. Thanks for the help Chad and Joseff!

**Comment by sindarknave** [comment]
This happened to me too! Reinstalling in pip hasn't worked. @Dan195, did you have to pull from the statsmodels git repo directly?

**Comment by Dan195** [comment]
@sindarknave when I pulled or tried to import it, all of the files except for the sarimax.py file pulled properly. I ended up copying the code from the sarimax.py file and creating my own sarimax.py file inside the otherwise properly-structured statsmodel folder.
