### ISSUE TITLE
Dynamic Factor PCA Before Exog OLS?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3607]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/statespace/dynamic_factor.py#L475

In the case where both `k_factors>0` and `k_exog>0`, we run PCA on the raw `endog`, then use the residuals from that as the `endog` in the next step when we run OLS on `self.exog`.  It isn't obvious to me that the PCA should come before the OLS.  Is there a reference for this?

**Comment by ChadFulton** [comment]
I think this is just an easy ad-hoc method to get starting parameters. If there's a better way, that's great too.

**Comment by jbrockmendel** [comment]
OK, if this doesn't affect the estimated parameters, it's not a big deal.  I do think it's worth thinking about whether the factors should be orthogonalized to the exog regressors.  For explanatory-style metrics, we clearly want to 'take out' the exog.  But if we're forecasting and the exog regressors have some autocorrelation, excluding them from the factors can be lossy.  (and including them in the factors effectively makes them not-exog).

**Comment by josef-pkt** [comment]
I have no idea what labels would be appropriate here

**Comment by jbrockmendel** [comment]
I think Chad's original point is correct and this can be closed.

Though if we want to make Dynamic Factor models plug-and-play, we need a decent answer for #3828.
