### ISSUE TITLE
Minor documentation bug in new state space model tools.

### ISSUE THREAD

**Issue by gbrunick** [statsmodels/statsmodels#3610]
Throughout the various new state space models classes and methods, the variable `k_posdef` is described as:

The dimension of a guaranteed positive definite covariance matrix describing the shocks in the **measurement equation**,

but it seems that this is actually rank of the shocks that evolve the transition / state equations.

In [47]: sm.version.full_version
Out[47]: '0.8.0'

**Comment by ChadFulton** [comment]
You're absolutely right - thanks for letting us know!

**Comment by ChadFulton** [comment]
Thanks for the reminder, fixed in #5105.
