### ISSUE TITLE
website hard to find?

### ISSUE THREAD

**Issue by amueller** [statsmodels/statsmodels#3619]
Google mostly finds http://statsmodels.sourceforge.net/.
I think you can fix that using canonical URLs https://support.google.com/webmasters/answer/139066?hl=en

**Comment by jseabold** [comment]
I can setup the redirect on sourceforge.

**Comment by jseabold** [comment]
I set up the 301 redirects, so this should fix itself.

This means we lost our [main project landing page](https://github.com/statsmodels/statsmodels-website/blob/master/index.rst) at statsmodels.sourceforge.net. If that's a big deal, I can make a PR to statsmodels.github.io, but no one was keeping up with the news, etc.

Re-open if there are any issues.

**Comment by josef-pkt** [comment]
Thanks Skipper

I checked some google searches and they are all correctly redirected.

**Comment by amueller** [comment]
thanks :)
