### ISSUE TITLE
Ridge regression gives wrong and inconsistent results.

### ISSUE THREAD

**Issue by haominwen** [statsmodels/statsmodels#3624]
statsmodel.api.OLS.fit_regularized goes through a shortcut when L1_wt is 0. However, that shortcut gives a wrong result when alpha is an array instead of a constant. The following code illustrates this issue with statsmodels version 0.8.0.
```python
import statsmodels.api as sm
import numpy as np
X = np.random.randn(1000, 100)
b = np.random.randn(100)
y = np.dot(X, b) + np.random.randn(1000) + 1 # y.mean() == 1.2861581555386801
res = sm.OLS(y, sm.add_constant(X)).fit_regularized(alpha=np.array([0] + [1e10] * 100), L1_wt=1e-8)
print('correct:', res.params[0]) # res.params[0] == 1.28615815554, which is correct.
sm.add_constant(X)).fit_regularized(alpha=np.array([0] + [1e10] * 100), L1_wt=0)
print('wrong:', res.params[0]) # res.params[0] == -0.00191408618425, which is wrong.
```

There is another peculiarity when L1_wt is zero. statsmodel.api.OLS.fit_regularized().params is a numpy array when L1_wt is zero. However, it becomes a pandas Series when L1_wt is not zero. This is inconsistent and confusing.

**Comment by kshedden** [comment]
Thanks for the report.  I just pushed a PR to address the first part of this.  The calculation we used before only worked when alpha was a constant vector, or a scalar.

I'll need to look further into the second issue.
