### ISSUE TITLE
VAR bpow optimization & floating point issue

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3630]
This should have a very low priority.

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/vector_ar/var_model.py#L1194

```
        # memoize powers of B for speedup
        # TODO: see if can memoize better
        B = self._bmat_forc_cov()
        _B = {}
        def bpow(i):
            if i not in _B:
                _B[i] = np.linalg.matrix_power(B, i)

            return _B[i]
```

We can get ~25% bump by making bpow recursive.  The benchmark I'm using is taken from the real-life use case.  There's a downside I'll get to below, which may actually be a more important issue globally.

```
# Arbitrary parameter choices
neqs = 10
steps = 30
B = np.random.randn(neqs, neqs)
B = np.matrix(B)

def current(B):
	""" Current implementation"""
	_B = {}
	def bpow(i):
		if i not in _B:
			_B[i] = np.linalg.matrix_power(B, i)
		return _B[i]
	return (bpow, _B)

def recursive(B):
	""" Recursive implementation"""
	_B = {0: np.linalg.matrix_power(B, 0), 1: B}
	def bpow(i):
		if i not in _B:
			_B[i] = bpow(i-1) * B
			# _B[i] = np.linalg.matrix_power(B, i)
		return _B[i]
	return (bpow, _B)

def usage(bpow):
	for h in range(2, steps+1):
		for i in range(h):
			Bi = bpow(h - 1 - i)
			for j in range(h):
				Bj = bpow(h - 1 - j)

def usage_current():
	(bpow, _B) = current(B)
	return usage(bpow)

def usage_recursive():
	(bpow, _B) = recursive(B)
	return usage(bpow)
```

Timing these two:

```
>>> timeit.timeit(usage_current, number=1000)
14.542560815811157
>>> timeit.timeit(usage_recursive, number=1000)
10.452023983001709
```

This is not a call that is made super-often, so a difference of 4 ms is not a big deal.  The numerical difference between the two methods could point to a bigger issue though:

```
>>> (bpow1, _B1) = current(B)
>>> (bpow2, _B2) = recursive(B)
# Fill the caches...
>>> usage(bpow1)
>>> usage(bpow2)

>>> (_B1[29]-_B2[29])[:5,:5]
matrix([[ -64.    ,  224.    ,   36.    ,   48.    ,  192.    ],
        [   0.    ,  -96.    ,  -12.    ,   -8.    , -128.    ],
        [  15.25  ,  -49.    ,   -3.9375,   -9.75  ,  -45.    ],
        [   8.    ,  -96.    ,  -36.    ,    0.    ,    0.    ],
        [ -40.    ,   64.    ,   20.    ,  -16.    ,   64.    ]])

>>> bdiff = _B1[29]-_B2[29]
>>> np.abs(bdiff).sum()
7424.4375
```

Up-casting B to `np.float128` (platform specific, so problematic) reduces the discrepancy to 2.61395263671875.  For the curious, if we take `_C1[29]` to be the "correct" answer, `_B1[29]` and `_B2[29]` are off by (Euclidean dist) 802.62 and 874.839, respectively.  So it looks like they're splitting the difference pretty well.

Are there other (more important) places where matrix powers are being computed repeatedly?

**Comment by josef-pkt** [comment]
Just another thought: using eigenvalue decomposition and power for eigenvalues might be more precise (which might be what some version of matrix_power does, I haven't checked)

The confidence intervals for impulse response functions are computed with bootstrap. In cases like that small speedups could still have a large effect if they have to be recomputed inside the bootstrap loop.

**Comment by jbrockmendel** [comment]
The eigenvalue decomposition approach is a good idea, especially for this kind of case when we are going to be calculating many matrix powers so the up-front cost can be defrayed.  I don't have a strong intuition for how it effects the precision, the exponentiation step should be much faster.

Implementing this method and profiling the tsa.vector_ar tests makes one thing very clear: matplotlib is taking the overwhelming majority of the test time.  Using the existing `matrix_power`, the tests run in 6.155s, of which 4.235 is in `fig.add_subplot`.  With the eig approach, total is 5.930 of which 4.290 is `fig.add_subplot`.  (This is from one run each, clearly with too much noise for comparisons to be meaningful).  5 calls to `G` are negligible at .012 and .014 seconds, respectively.  I think the tests mostly go out to 10 periods, so it may be worth trying out longer cases.

It looks like `np.linalg.matrix_power` has a clever trick to cut down on the number of matrix multiplications they do, but it doesn't use the eigenvalue approach.

**Comment by jbrockmendel** [comment]
It turns out that the matrix exponentiation here is not remotely the bottleneck of the `_omega_forc_cov` function.  The number of matrix exponentials we calculate with `bpow` is `steps-1`.  But the number of calls to `chain_dot` and `np.trace` scales with `steps**3` (more specifically, `(steps-1) * steps * (2*(steps-1)+1) / 6`).

In addition to caching the `Bi` values, we can cache the results of the `np.trace` call.  Doing this, using one of the existing test cases I see speed-ups starting starting around 15% for steps=3 and growing to 59% by steps=15.  Note that the size of this cache should only grow with `steps**2`.

**Comment by jbrockmendel** [comment]
Performance-wise this turns out to be trivial, the real action is in caching intermediate results, see #3859.
