### ISSUE TITLE
variance_inflation_factor should be clarified

### ISSUE THREAD

**Issue by jcheong0428** [statsmodels/statsmodels#3637]
The variance_inflation_factor is only correct when you give a matrix that includes an intercept. 
When you give a matrix that does NOT have an intercept you get erroneous VIF values 
that are inconsistent than the linear algebra method of obtaining VIFs 
by  np.diag(np.linalg.inv(df),0)

see screenshot below .

![screen shot 2017-05-02 at 6 27 18 pm](https://cloud.githubusercontent.com/assets/12897766/25641998/070c8d64-2f65-11e7-89c9-fc3df91bba31.png)

**Comment by josef-pkt** [comment]
this is a duplicat of #2376 with explanation and further cross-links 
closing this one
