### ISSUE TITLE
docs html, htmlhelp include source again, or not

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#364]
For 0.4.3 the htmlhelp doesn't include the source anymore, my guess is it's the same for the html

I don't know when or why we started to have the source in the html, and I don't know why it disappeared again.

On scipy-dev mailing list, someone was asking for including the source in the scipy documentation, using statsmodels as positive example.

Main disadvantage is that the size of the html or htmlhelp increases quite a lot.

**Comment by bashtage** [comment]
HTML has this. HTMLhelp (chm) is not produced.
