### ISSUE TITLE
CLN: Any reason not to use `six`?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3648]
Large parts of `compat` could be outsourced to `six`, which is already a dependency (indirectly via pandas--> dateutil --> six).  Is there any reason not to use that and 

Related: there's a bunch of legacy code, much of it in `sandbox`, that is no longer used.  Is trimming this down on the horizon?

**Comment by josef-pkt** [comment]
about six: We are only using a small part of Python (especially not much from the standardlib) and need only a small part of six. IIRC, we followed scipy and just included the compat parts that we need directly. 
It has required low maintenance overall, and in a few years we can drop python 2.

(I'm not sure if I remember correctly, but I think we are closer to python 3 than six is which has a python 2 bias. I.e. we don't need function that work in python 3 as they do in python 2. We want function that are native in python 3 and also run in python 2 but maybe not exactly in the same way. E.g. I always assume that some things, like range or dict.items(), are iterators and I don't much care that that they are lists in python 2, at a small performance loss in python 3. )

about the sandbox: I think we had the discussion before. Large parts of the sandbox is not obsolete. And I don't think it's worth the effort at the moment to decide what to delete. Also there are "weird" parts of the sandbox used in the wild.

**Comment by jbrockmendel** [comment]
> IIRC, we followed scipy

Makes sense.

> about the sandbox: I think we had the discussion before

I had a misconception that `sandbox` was for WIP code that was intended to be merged into the "main" codebase.  In the previous discussion you clarified that it was the other way around.  If we discussed its destiny, I've forgotten that discussion.

From #3515:
> The sandbox is like stalled PRs, that we wrote in the early years of statsmodels. Some is obsolete or superseded by newer code or by new packages outside of statsmodels. Some of it can likely be picked up again at some point. Some of it is like an 85% finished PR that just needs some final cleaning and adding missing unit tests. Some of it is dead because it's unlikely that someone is getting interested in it again.

No question a lot of my motivation here is an irrational urge to clean.  For the rest, it would be genuinely helpful to know which code is defunct and which is just a little TLC from being finished.

> Large parts of the sandbox is not obsolete. And I don't think it's worth the effort at the moment to decide what to delete.

Not going to keep pushing here.  But I'm maintaining an open offer to put in the labor for at least some of the low-hanging fruit.  Specifically, there are a non-trivial number of places where code is clearly never reached.  #3552 and #3558 are about code that would raise `NameError` if ever reached.  #3515 cleaned up some of these in `tsa`, but that never got accepted so I didn't move on to the other directories.

From #3515 
> I think outside of the sandbox almost all if __name__ == '__main__' should be gone by now.

I'll keep an eye out for these and make PRs deleting any I find.  If nothing else we can figure out which if any merit converting to examples or test cases.
