### ISSUE TITLE
SVAR intended to subclass VAR?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3664]
`SVAR` subclasses `TimeSeriesModel`, but calls `select_order`, which is a `VAR` method.  It would be pretty natural for `SVAR` to inherit from `VAR`.  Is this intended?

**Comment by josef-pkt** [comment]
I didn't look at that, however I guess that SVAR doesn't need to subclass VAR.

One of the main differences between VAR and SVAR is that we have a closed form linear algebra solution for the first and we need nonlinear optimization for the second. I think this requires quite large differences in the model setup.

We split VAR into several classes so they can be reused and they modularize the functionality. So, it should be possible to reuse large parts of the common features of VAR, SVAR and whatever else has similar features without having to rely on subclassing the main model.

Just a guess. We would have to compare if there is enough in common.

**Comment by jbrockmendel** [comment]
AttributeError no big deal, closing.
