### ISSUE TITLE
Module 'statsmodels.tsa.api' has no attribute 'statespace'

### ISSUE THREAD

**Issue by AnaCnGarcia** [statsmodels/statsmodels#3679]
Hi! Im trying to use SARIMAX but I keep getting this error.

statsmodel version is 0.6.1

My code is the following:

`mod = sm.tsa.statespace.SARIMAX(y,
                                order=param,
                                seasonal_order=(1,1,0),
                                enforce_stationarity=False,
                                enforce_invertibility=False)

results = mod.fit()`

The error I get is:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-59-54020ee860ed> in <module>()
----> 1 mod = sm.tsa.statespace.SARIMAX(y,
      2                                 order=param,
      3                                 seasonal_order=(1,1,0),
      4                                 enforce_stationarity=False,
      5                                 enforce_invertibility=False)

AttributeError: module 'statsmodels.tsa.api' has no attribute 'statespace'

Appreciate the help.

Thank you.

**Comment by ChadFulton** [comment]
State space models were introduced in version 0.8, so you'll have to update your statsmodels to use them.

**Comment by AnaCnGarcia** [comment]
Thank you @ChadFulton !

**Comment by josef-pkt** [comment]
nothing to do here, so closing
