### ISSUE TITLE
DOC: Broken link in sw

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3680]
The docstring in sandwich_covariance refers to

http://pubs.amstat.org/doi/abstract/10.1198/jbes.2010.07136

which is not loading for me.  Any idea what used to be there?  I can take a look for a replacement and/or substitute.

Tangentially related: what does "HCCM" stand for?

**Comment by josef-pkt** [comment]
searching for the doi 

http://dx.doi.org/10.1198/jbes.2010.07136

amstat are now published by T&F
http://www.tandfonline.com/doi/abs/10.1198/jbes.2010.07136

**Comment by josef-pkt** [comment]
HC stands for Heteroscedasticity Consistent, like HC0, HC1 are standard abbreviation

so I gues HCCM is heteroscedasticity consistent covariance matrix.

Skipper started this and I never thought about it.
