### ISSUE TITLE
test_whiteness overlap with test_serial_correlation?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3683]
`mlemodel.MLEResults` has a [test_serial_correlation](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/statespace/mlemodel.py#L2254) method.  `var_model.VARResults` has a a [test_whiteness](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/vector_ar/var_model.py#L1374) method. 

Each of these is testing a null of zero autocorrelation.  The mlemodel version looks more formal than the var_model version.  On the flip side, it looks like the var_model version looks at cross-auto-correlation where mlemodel does not.

So the question: is `test_serial_correlation` effectively a beefed-up version of `test_whiteness`?

Note: This came to my attention because `test_whiteness` isn't hit in tests.

**Comment by josef-pkt** [comment]
test_whiteness doesn't look like a proper test.
test_serial_correlation only checks univariate autocorrelation.

I'm not sure we have a proper multivariate serial correlation test anywhere.
(at least one version I looked at would be using functions on the full vector autocorrelation matrix.)

**Comment by jbrockmendel** [comment]
> test_whiteness doesn't look like a proper test.

Agreed.  I'd like to subsume it into something more formal. (And ideally move it up the hierarchy to something like tsa_model, since nothing about it is VAR-specific).

> test_serial_correlation only checks univariate autocorrelation.

Presumably @ChadFulton had a reason for doing it that way.  Maybe he can weigh in.  `test_serial_correlation` calls `acorr_ljungbox` which calls `tsa.stattools.acf`, which only handles the univariate case.  `var_model._compute_acov` implements the multivariate case, albeit without the same bells and whistles as `acf`.

> I'm not sure we have a proper multivariate serial correlation test anywhere.

So a proper test would be of a joint hypothesis that the entire autocorrelation matrix (tensor?) is zero, right?  It looks like Ljung-Box has a multivariate [extension](http://faculty.wcas.northwestern.edu/~lchrist/course/assignment2/mvq.pdf).  I'll need to look at this more carefully, but implementing it looks pretty straightforward.
