### ISSUE TITLE
Problem when trying to use ztest_ind

### ISSUE THREAD

**Issue by RattanaChhin** [statsmodels/statsmodels#3694]
Dear statsmodels experts,

I am so new to Python and I try to use statsmodels to solve my problem. 
I am trying to do ztest using ztest_ind module under stats class. 

Note: I install statsmodels under miniconda and my OS is Debian linux. 

Following is my test code.

>>import statsmodels.api as sm
>>from statsmodels.stats import weightstats as sms # for ztest
>>import numpy as np

>>ddf = np.random.rand(100)
>>ddo = np.random.uniform(0.1,10.,100)
>>z,p = sms.CompareMeans(ddf,ddo).ztest_ind()

Then I got the following error:

_Traceback (most recent call last):
  File "test_statsmodels.py", line 9, in <module>
    z,p = sms.CompareMeans(ddf,ddo).ztest_ind()
  File "/home/rattana06/miniconda2/lib/python2.7/site-packages/statsmodels/stats/weightstats.py", line 940, in ztest_ind
    stdm = self.std_meandiff_pooledvar
  File "/home/rattana06/miniconda2/lib/python2.7/site-packages/statsmodels/tools/decorators.py", line 193, in __get__
    val = self.getter(obj)
  File "/home/rattana06/miniconda2/lib/python2.7/site-packages/statsmodels/stats/weightstats.py", line 834, in std_meandiff_pooledvar
    var_pooled = ((d1.sumsquares + d2.sumsquares) /
AttributeError: 'numpy.ndarray' object has no attribute 'sumsquares'_

*** Below is the function on line 834 based on the warning log:

    @OneTimeProperty
    def std_meandiff_pooledvar(self):
        '''variance assuming equal variance in both data sets

        '''
        #this uses ``_var`` to use ddof=0 for formula

        d1 = self.d1
        d2 = self.d2
        #could make var_pooled into attribute
        var_pooled = ((d1.sumsquares + d2.sumsquares) /
                          #(d1.nobs - d1.ddof + d2.nobs - d2.ddof))
                          (d1.nobs - 1 + d2.nobs - 1))
        return np.sqrt(var_pooled * (1. / d1.nobs + 1. /d2.nobs))

I try to find function "sumsqaures " inside the module, it's really exist. 
However, python seem not be able to call that function to use. 
it seems like python confuse it with resources in numpy.

    @OneTimeProperty
    def sumsquares(self):
        '''weighted sum of squares of demeaned data'''
        return np.dot((self.demeaned**2).T, self.weights)

How can I solve this problem ? Thank you in advance.

**Comment by jbrockmendel** [comment]
This tentatively looks like a bug.  To confirm (and hopefully solve your problem), can you try changing the `d1.sumsquares + d2.sumsquares` on line 834 to `(d1**2).sum() + (d2**2).sum()` and see if that fixes it?

**Comment by RattanaChhin** [comment]
Dear jbrockmendel, 

Following you suggestion, it works perfectly now. 
At the mean time, can I know what is dynamic of function 'from_data' ? I just want to know if I need to put this function before the input data to all statsmodel modules or not ? 
Thank you very much.

**Comment by josef-pkt** [comment]
The main class `CompareMeans` takes instances of the univariate class as arguments not the data directly. As a convenience to avoid having to create three instances, there is the `from_data` method.

Similarly our main models have a `from_formula` as a method that is used if a user provides a formula and dataframe instead of the required arrays.

Otherwise, there are only a few places where we have `from_xxx` methods as a convenient way of creating an instance of a class. Most classes take data arrays or dataframes directly.

BTW: this is more a user question that fits better on stackoverflow or the mailing list.

**Comment by RattanaChhin** [comment]
Dear Josef-pkt, 

Thank you very much for your explanation. I understand it now.

Best,

**Comment by josef-pkt** [comment]
@RattanaChhin  FYI  
If you want to just compute a ztest, then there is also a standalone function `ztest`,   
standalone ttest functions are also in scipy.stats.  
The classes like CompareMeans are a bit more complicated to use, but they provide more optional results at the same time (without having to recompute everything from scratch).

**Comment by RattanaChhin** [comment]
@josef-pkt , 

Yes, that's a more convenient of statsmodels if we understand its dynamic. I think statsmodels consist of some other powerful statistical models, that is very useful.
Thank to your team's great work.

**Comment by josef-pkt** [comment]
I don't think there is anything to do here, closing
