### ISSUE TITLE
BUG? offset and exposure in discrete CountModel predict

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3698]
(While looking at some margin issues for #3696)
see related to margins https://github.com/statsmodels/statsmodels/issues/2164#issuecomment-303904095

based on reading the code, if exog is not equal to self.exog, then offset and exposure are not correctly included in predict.  AFAIR, we had some similar changes to fix this in GLM.

**Comment by jbrockmendel** [comment]
Where is this occurring?  #3569 was in that neighborhood.

**Comment by josef-pkt** [comment]
I guess I'm wrong in this, and didn't think carefully enough.
