### ISSUE TITLE
formula for logit

### ISSUE THREAD

**Issue by Sammers21** [statsmodels/statsmodels#3729]
Hi, guys! Your lib is so cool!

I have a problem with setting up stat model like this:
![image](https://cloud.githubusercontent.com/assets/16746106/26577616/a417d9d4-4535-11e7-90c1-743e4c8f58b1.png)

So, firstly to estimate this model i have used this approach
```python
df = pd.DataFrame({
    "class_1": class_1,
    "class_2": class_2,
    "class_3": class_3,
    "sex": sex,
    "survived": survived
})

smf.logit(formula="P(C(survived)==1)/P(C(survived)==0)~ exp(C(sex)+C(class_1)+C(class_2)+C(class_3))", data=df)
```
But it does not seem to work ang generates a lot of excetions.
![image](https://cloud.githubusercontent.com/assets/16746106/26577914/ac12911e-4536-11e7-8897-fb099f46b164.png)

Can someone suggest how I can  make correct formyla for this formula?

P.S. all values  class_1, class_2, class_3, sex and survived can be either 1 or 0.

**Comment by kshedden** [comment]
The formula should just be:

survived ~ C(sex)+C(class_1)+C(class_2)+C(class_3)

The family and link function for logit are not written explicitly, they
default to what you are using, but can be modified by passing the family
argument.

Kerby

**Comment by Sammers21** [comment]
@kshedden, now it seems to works. But what about OLS and probit regression model?

**Comment by kshedden** [comment]
I'm not sure what your question is... but in general you define the general
class of models through the class name, logit is for logistic regression,
ols is for linear models fit by least squares, etc.  Many models are
implemented, for basic regression analysis ols and glm are two of the main
ones.  In glm you specify the family and I think probit is one of the
options.

Kery

**Comment by josef-pkt** [comment]
nothing to do here, so I'm closing this
(FAQ label to have a quick overview for type of issue)
