### ISSUE TITLE
Giving a vector of variables in obs_intercept in sm.tsa.statespace.MLEModel

### ISSUE THREAD

**Issue by as4456** [statsmodels/statsmodels#3736]
Hi,
I am trying to estimate a state space model of the below form,
y(t) = Z\*alpha(t)+ B*x(t) + u(t) 
alpha(t) = T\*alpha(t-1) + c + v(t).
the dimensions of B is (2\*7) matrix and x(t) is (7\*1) matrix.
where,
y(t)=[y(t),q(t)]'
x(t)=[y(t-1),y(t-2),q(t-1),q(t-2),q(t-5),r(t),s(t)]'

Could you tell me how to pass B\*x(t) as obs_intercept i.e d(t) in the statsmodels state space representation.

**Comment by josef-pkt** [comment]
Are Z and T parameters?

AFAIK, the only model with multivariate endog are VARMAX type models. But in this case it looks a bit like a factor model. (IIRC, Chad has some examples of factor models or factor augmented VAR)

@ChadFulton  knows better and has an extensive description on the statespace framework and how to build models on top of it: http://www.chadfulton.com/files/fulton_statsmodels_2017_v1.pdf

**Comment by as4456** [comment]
Z and T are the design and transition matrices respectively. If you see, the state space representation explained in statsmodels here:
http://www.statsmodels.org/stable/statespace.html.
you will notice that B\*x(t) is d(t) (obs_intercept) in statsmodels.
My issue is how to give x(t) when defining the state space matrices.
This type of example is not explained in the reference pdf or statespace examples

**Comment by ChadFulton** [comment]
I assume you're creating a custom state space model here? If so, then you would set this in the `update` function in the usual way.

Lets suppose that you have stored your x(t) data in a variable `self.weak_exog`, and suppose that this array shaped `(nobs, 7)`.

The matrix `B` consists of 14 new parameters, which you will need to include in your model in the usual way (e.g. by setting values for them in `start_params`, and optionally in `param_names`, and setting up any transformations you require for them in `transform_params` and `untransform_params`).

I'll assume that these are the last 14 parameters of your model (but you can use obvious modifications if they're somewhere else), and I'll assume that you ordered them so that `params[-14:].reshape(2, 7)` gives you the matrix `B`

Then in `update`, you would do something like:

```python
B = params[-14:].reshape(2, 7)
self['obs_intercept'] = np.dot(B, self.weak_exog.T)
```

**Comment by as4456** [comment]
Thanks for the explaining this.

**Comment by ChadFulton** [comment]
No problem - does that work for your case? Should I close this issue?

**Comment by as4456** [comment]
I have to try but you can close this.

**Comment by ChadFulton** [comment]
I will close it for now, but feel free to re-open if you need to.

**Comment by as4456** [comment]
I have another issue related to ordering of params when passing starting_params and giving names.

I currently assume the params to be estimated as they appear in the measurement and transition eqn.
The state space is of the form as shown in the attached image, where y(t) is the observation vector and alpha(t) is the state vector

![statespace_representation](https://cloud.githubusercontent.com/assets/8718176/26788568/99cf615e-49db-11e7-8c0d-09a2c5dc2a25.png)


I currently assume the params to be estimated in this order:
[a1,a2,b3,b1,b2,b4,b5,sigma1,sigma2,g,sigma4]

I dont think this is correct as I am getting NaNs in the results for stderr and others. I have attached the image for the results as well the class which I have created for this.
![results](https://cloud.githubusercontent.com/assets/8718176/26788573/9f96a606-49db-11e7-85b0-06e875657521.PNG)


Do I need to order params like this
[a1,a2,b1,b2,b3,b4,b5,g,sigma1,sigma2,sigma4] 

Is there a way to know if I am estimating params in correct order.

The sample code


`import numpy as np
import pandas as pd
import statsmodels.api as sm


class Statespace1(sm.tsa.statespace.MLEModel):
    def __init__(self, endog,exog):
        # Model order
        k_states = k_posdef = 3

        # Initialize the statespace
        super(Statespace1, self).__init__(
            endog, k_states=k_states, k_posdef=k_posdef,
            initialization='approximate_diffuse',
            loglikelihood_burn=k_states
        )

        self.exog=exog
        # Initialize the matrices
        self.ssm['transition'] = np.array([[1,0,0],[1,0,0],[0,1,0]])
        self.ssm['selection'] = np.eye(k_states)
        # Cache some indices
        self._state_cov_idx = ('state_cov',) + np.diag_indices(k_posdef)

    @property
    def param_names(self):
        return ['stg1.a1', 'stg1.a2', 'stg1.b3','stg1.b1','stg1.b2','stg1.b4','stg1.b5','stg1.sigma1','stg1.sigma2','stg1.g','stg1.sigma4']

    @property
    def start_params(self):
        return [1.252658,-0.31179,0.04816,0.84268,0.34833,-0.00130,0.005416,0.787,0.82769,0.73884,0.241499]

    def transform_params(self, unconstrained):
        constrained = np.zeros(unconstrained.shape,unconstrained.dtype)
        constrained[0]=unconstrained[0]
        constrained[1]=unconstrained[1]
        constrained[2]=unconstrained[2]
        constrained[3]=unconstrained[3]
        constrained[4]=unconstrained[4]
        constrained[5]=unconstrained[5]
        constrained[6]=unconstrained[6]
        constrained[9]=unconstrained[9]
        constrained[[7,8,10]]=[unconstrained[x]**2 for x in [7,8,10]]
        return constrained

    def untransform_params(self, constrained):
        unconstrained=np.zeros(constrained.shape,constrained.dtype)
        unconstrained[0]=constrained[0]
        unconstrained[1]=constrained[1]
        unconstrained[2]=constrained[2]
        unconstrained[3]=constrained[3]
        unconstrained[4]=constrained[4]
        unconstrained[5]=constrained[5]
        unconstrained[6]=constrained[6]
        unconstrained[9]=constrained[9]
        unconstrained[[7,8,10]]=[constrained[x]**0.5 for x in [7,8,10]]
        return unconstrained

    def update(self, params, *args, **kwargs):
        params = super(Statespace1, self).update(params, *args, **kwargs)
        self.weak_exog=self.exog
        # Observation covariance
        self.ssm['obs_cov',0,0] = params[7]
        self.ssm['obs_cov',1,0] = params[8]
        self.ssm['state_cov',0,0] = params[10]
        self.ssm['design'] = np.array([[1, -params[0],-params[1]],[0,-params[2],0]])
        state_intercept=np.array([params[9],0,0])
        self.ssm['state_intercept'] = state_intercept[:,np.newaxis]
        B = np.array([[params[0],params[1],0,0,0,0,0],[params[2],0,params[3],params[4],1-params[3]-params[4],params[5],params[6]]])
        self['obs_intercept'] = np.dot(B, self.weak_exog.T)`

**Comment by ChadFulton** [comment]
There's no "correct" order of params - you just need to make sure that you use one order consistently; especially make sure that the order in`transform_params` is the same as in `update`.

The order you have above in `update` looks to me like [a1, a2, b3, b1, b2, b4, b5, sigma_1^2, sigma_2^2, g, sigma_4^2], and that looks consistent with `transform_params`, so I think you're okay, but you should make sure that's what you want.

**Comment by as4456** [comment]
Thanks for clearing the doubt.
