### ISSUE TITLE
linear_model code paths

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3740]
The way df_model and df_resid are set in regression.linear_model.RegressionModel is kind of disjointed.  In `fit` it [checks](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/regression/linear_model.py#L302) whether `self._df_model` and `_df_resid` are  non-None:

```
        if self._df_model is None:
            self._df_model = float(self.rank - self.k_constant)
        if self._df_resid is None:
            self.df_resid = self.nobs - self.rank
```

But RegressionModel [uses](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/regression/linear_model.py#L193) properties for df_model and df_resid, so checking-and-setting _df_model is *almost* equivalent to just accessing `_ = self.df_model`:

```
@property
    def df_model(self):
        """
        The model degree of freedom, defined as the rank of the regressor
        matrix minus 1 if a constant is included.
        """
        if self._df_model is None:
            if self.rank is None:
                self.rank = np_matrix_rank(self.exog)
            self._df_model = float(self.rank - self.k_constant)
        return self._df_model
```
The only difference AFAICT between the existing version versus accessing the property is that if somehow `self.rank` is None, the existing version will raise a TypeError.  Is this an intentional design decision?  If not, any objection to changing those two lines to just access the property (decreasing the # of places attributes get set)?

Checking `self._df_resid` could be similarly simplified (or in fact ommitted).  In the case of this check, it looks like accessing `_ = self.df_resid` would be exactly identical to the current check/set.

Last question on this topic.  Unless the user specifically changes changes `df_model` to something non-standard, we will have `df_resid = nobs - rank = nobs - (df_model + k_constant)`.  The expression on the right is equivalent to `df_resid` almost* globally across the code-base.

So from an internal-consistency standpoint, it would be really nice to set `df_resid` to `nobs - (df_model + k_constant)` in line 218 (and 305 if we don't change this to just go through the property).  But in this case, what is the correct thing to do?

\* After implicitly imputing k_constant = 1 in cases where 1 is subtracted instead of k_constant.  NegativeBinomial, Multinomial, and sandbox.panel.mixed make small adjustments to what otherwise behaves like `k_constant` for discussion purposes.

Also an aesthetic issue: I'm seeing an issue with syntax-highlighting in regression.linear_model.  SublimeText doesn't recognize the docstring to RegressionResults as being closed until the end of the file.  I can fix this by removing the "r" at the beginning of the docstring.  Is there anything about the TeX etc that makes the "r" necessary?  Not at all a big deal.

**Comment by josef-pkt** [comment]
(just two points for now, I need to look after dinner)

I think the df_model property was added to support lazy evaluation of rank, but I'm not sure whether things have been piecewise refactored or there is an overall consistent design. my guess is the former

raw docstrings `r"""` make LATEX more readable because we don't need to escape/double the backslash `\\` `\pi` instead of `\\pi`

**Comment by jbrockmendel** [comment]
> I think the df_model property was added to support lazy evaluation of rank, but I'm not sure whether things have been piecewise refactored or there is an overall consistent design. my guess is the former

The property design is one that I like [quite a bit](https://github.com/statsmodels/statsmodels/pull/3725) and will push for on another day.  For now the relevant questions are whether the risk of TypeError is intentional and choosing between the two implementations of `df_resid` in the non-standard case.

**Comment by josef-pkt** [comment]
I haven't figured out all of your comment, so another background explanation, AFAIU:
@guyrt in #1092 streamlined some of the linear algebra, especially we get the rank as a byproduct of the fit method, at least for the default pinv for free. So we can avoid computing rank twice. So we assign `._df_xxx` in fit. But in case fit hasn't set the df, and computed the rank yet, we can fall back on the direct computation in the property.

There is a code duplication, two places that can compute the rank, df_resid, df_model. I guess we could restrict it to only the rank, and let the attributes handle the _df_resid and _df_model, but then, I think, we would need a `rank` property to fall back on explicit computation if fit hasn't set it.
That's no principal difference in the pattern but it restricts it to fewer attributes.

**Comment by jbrockmendel** [comment]
I'll try to clarify.  There are two separate issues: I) how/where to set these attributes, and II) exactly how to define `df_resid`.  

Part I) Suppose that lines 302-305 (block-quoted at the top of the original post) are replaced with:

```
    _ = self.df_model
    _ = self.df_resid
```

The claim is that the the only case in which this is *not* equivalent to the status quo is when `self._df_model` is None and `self.rank` is None, in which case a TypeError would be raised.  So this part of the question boils down to: In this scenario, is raising `TypeError` the appropriate behavior?

It looks like the easiest way for this to happen is pass an un-supported string for the `method` arg.  There are other ways that would be pretty hard to do unintentionally.

Part II) In the most common case, neither _df_model nor _df_resid will have been set, so 302-305 will be equivalent to:

```
    self.df_model = float(self.rank) - self.k_constant
    self.df_resid = self.nobs - self.rank
```

An alternative way we could set `df_resid` in this case would be:

```
    self.df_resid = self.nobs - (self.df_model + self.k_constant)
```

These two options are equivalent in this (very common) special case where `_df_model` was not already set (or if it were already set to `float(self.rank) - self.k_constant`).  The question here is: which version of `df_resid` do we want to use in the complementary case?

The question of which variant is "correct" will depend on *why* `_df_model` was set manually, so I think the guiding principle here should be internal consistency.  AFAICT *every* place in the code where `df_resid` is set is analogous to the second version.  Next week I'll roll out a few small PRs that will demonstrate this.
