### ISSUE TITLE
BUG: QuantileRegression raises if singular exog in irrelevant part

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3746]
see https://stackoverflow.com/questions/44379010/statsmodel-quantile-regression-valueerror/44379390#44379390

It raises with a shape mismatch during IRLS because the initial beta for the convergence check is using matrix_rank instead of exog.shape[1] for the number of parameters. The exception is difficult/impossible to understand unless we or the users look at the code.

It might have a standard pinv solution if the exog is rank deficient when we fix this. But, that needs checking.
i.e. I think it should behave more like IRLS in GLM and RLM if possible.

**Comment by prcastro** [comment]
I can still reproduce the bug with the latest version

**Comment by josef-pkt** [comment]
I'm closing this as duplicate of #2597
