### ISSUE TITLE
Doubt in smoothed_state attribute in MLEResults

### ISSUE THREAD

**Issue by as4456** [statsmodels/statsmodels#3748]
@ChadFulton 
Hi Chad,
Sorry to bother you again.

I create a custom MLE model and estimate params using MLE as below:

mod=SomeModel(endog=df[endog],exog=df[exog])
results=mod.fit(disp=False)

I want to know what is the attribute smoothed_state in MLEResults stands for.
i.e results.smoothed_state

I want to get the Smoothed state vector. Does the above represent that
or do I need to call smooth method separately by passing the estimated params from above as below:

ks_smooth=mod.smooth(results.params.values)
ks_smooth.smoothed_state

**Comment by ChadFulton** [comment]
Yes, `results.smoothed_state` contains the smoothed state vector. `fit` automatically calls `smooth` at the MLE parameters.

(by the way, some these questions are probably better for the mailing list, since they're more like usage questions than bugs).

**Comment by as4456** [comment]
Thanks for explaining this as well as the suggestion of the mailing list.

**Comment by bashtage** [comment]
Closing as answered.
