### ISSUE TITLE
kpss & adfuller interpretation

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3750]
I'm having trouble understanding some outputs from tsa.stattools.kpss.

```
from statsmodels.tsa import api as tsa
import pandas as pd
import pandas_datareader as pdr

df = pdr.DataReader(["CPIAUCSL", UNRATE"], "fred", start=pd.Timestamp("1900-01-01"))
# CPI and Unemployment, going as far back as we can get

cpi = df['CPIAUCSL'].dropna()
unrate = df['UNRATE'].dropna()
# Fortunately the nulls are all contiguous

tsa.adfuller(unrate)
# (-3.0429270526801928, 0.031075405974681617, 12, 820, [snip], -408.2036614684273)
tsa.adfuller(cpi)
# (2.1138194194179709, 0.99880376411834015, 15, 828, [snip], 442.58497014896011)

tsa.kpss(unrate)
# (0.64570549334187344, 0.018481318787102415, 21, [snip])
tsa.kpss(cpi)
# (3.8262685151601485, 0.01, 21, [snip])

```

For adfuller, the 2nd value returned is the p-value associated with the null that there *is* a unit root.  For kpss, the 2nd value returns is the p-value associated with the null of stationarity.  

The adfuller results make sense to me: we should reject the null that unemployment has a unit root, and overwhelmingly not-reject the null that CPI has a unit root.

The kpss results I don't get.  It looks like we are rejecting the null of stationarity for both.  We're pretty strongly rejecting unemployment being either stationary or unit-root.  Is there a third option I'm forgetting?

**Comment by josef-pkt** [comment]
(AFAIU, I never used kpss)
maybe options because the defaults are different, kpss has default stationarity around a constant mean while adf uses as default a constant drift (stochastic trend). kpss might just reject the constant mean hypothesis.
The lag length selection methods also differ.

My main guess would be stationarity with structural breaks. Also, unrate might have an effect from the lower bound, e.g. behaves log(urate) in a similar way? 
(Not sure about how this works: Short run and long run behavior could be different, if the lags don't capture it, and we have some kind of long run mean/trend process.)

**Comment by ChadFulton** [comment]
On Thu, Jun 8, 2017 at 7:20 PM, jbrockmendel <notifications@github.com>
wrote:

> I'm having trouble understanding some outputs from tsa.stattools.kpss.
>
> from statsmodels.tsa import api as tsa
> import pandas as pd
> import pandas_datareader as pdr
>
> df = pdr.DataReader(["CPIAUCSL", UNRATE"], "fred", start=pd.Timestamp("1900-01-01"))
> # CPI and Unemployment, going as far back as we can get
>
> cpi = df['CPIAUCSL'].dropna()
> unrate = df['UNRATE'].dropna()
> # Fortunately the nulls are all contiguous
>
> tsa.adfuller(unrate)
> # (-3.0429270526801928, 0.031075405974681617, 12, 820, [snip], -408.2036614684273)
> tsa.adfuller(cpi)
> # (2.1138194194179709, 0.99880376411834015, 15, 828, [snip], 442.58497014896011)
>
> tsa.kpss(unrate)
> # (0.64570549334187344, 0.018481318787102415, 21, [snip])
> tsa.kpss(cpi)
> # (3.8262685151601485, 0.01, 21, [snip])
>
>
> For adfuller, the 2nd value returned is the p-value associated with the
> null that there *is* a unit root. For kpss, the 2nd value returns is the
> p-value associated with the null of stationarity.
>
> The adfuller results make sense to me: we should reject the null that
> unemployment has a unit root, and overwhelmingly not-reject the null that
> CPI has a unit root.
>
> The kpss results I don't get. It looks like we are rejecting the null of
> stationarity for both. We're pretty strongly rejecting unemployment being
> either stationary or unit-root. Is there a third option I'm forgetting?
>
>
> I'm not an expert on these things, but as I understand it, the fact that
these tests don't always (or often) agree was actually a point in favor of
KPSS in the original paper.

Other thoughts:

- ADF test is for I(1); I don't think unemployment rate looks I(1), but CPI
does.

- The KPSS test is a test for trend-stationarity. When I do simple
detrending with constant and time trend, neither series look stationary, so
this seems pretty reasonable.

**Comment by josef-pkt** [comment]
> these tests don't always (or often) agree was actually a point in favor of KPSS in the original paper.

but I would have expected that we get this if neither rejects, e.g. because we don't have enough power, and therefore "favor" the null hypothesis, whichever it is.

**Comment by jbrockmendel** [comment]
Post-Mortem FWIW:

I chose these examples because the contrast between them persistence-wise is pretty stark.  But maybe unemployment has enough medium-term persistence to not be entirely obvious.  Next attempt to grok this is to simulate 10k observations of an AR(1) with coefficient 0.3, then take cumsum to get a definitely-integrated series.

The first thing I learned is that `kpss` is much faster than `adfuller`.

The output of both makes sense with the simulated data:
```
>>> tsa.kpss(stationary)[:2]
(0.15188063340157976, 0.1)
>>> tsa.kpss(integrated)[:2]
(79.058240134447502, 0.01)
# 0.02888798713684082 seconds

>>> tsa.adfuller(stationary)[:2]
(-232.55647526951944, 0.0)
>>> tsa.adfuller(integrated)[:2]
(-0.67191068570419166, 0.853891776751043)
# 37.5179 seconds
```

The p-values are hitting some cutoffs in `kpss`, but these all make sense.  In small samples (for values of "small" that are still pretty generous by macro standards) adfuller still looks pretty good, while the cutoffs make kpss problematic:

```
>>> tsa.adfuller(stationary[:800])[:2]
(-22.034834234788402, 0.0)
>>> tsa.adfuller(integrated[:800])[:2]
(-2.6836555828341782, 0.07690952173432096)

>>> tsa.kpss(stationary[:800])[:2]
(0.046869154958612352, 0.1)
>>> tsa.kpss(integrated[:800])[:2]
(0.24297119177885357, 0.1)

>>> tsa.kpss(integrated[:800], 'ct')[:2]
(0.2479168577742506, 0.01)

>>> stationary += 1
>>> integrated = stationary.cumsum()
>>> tsa.kpss(stationary[:800])[:2]
(0.046869154958612699, 0.1)
>>> tsa.kpss(integrated[:800])[:2]
(3.7276116834117339, 0.01)
```

**Comment by jbrockmendel** [comment]
I simulated data under the null of `kpss` and couldn't match the critical values hard-coded in the function.  Looking at the [paper](http://www.portalaction.com.br/sites/default/files/SeriesTemporais/planilhas/kpps_test.pdf), there are a couple of caveats about the size and power that we might want to consider at some point.

```
Only for T >= 200 do we find appreciable power without the
risk of very substantial size distortions. 
```

Probably unrelated: both the function and the paper use default lags of `12*(nobs/100)**(1./4)`.  But an offhand remark earlier on the authors say that `lags` should be $o(T^{.5})$.  Fourth-root satisfies that, but it isn't obvious to me why that is special.

**Comment by josef-pkt** [comment]
@bashtage wrote kpss and it is in his arch package

I never looked at the details for kpss (but maybe I will when I'm back in Montreal in three weeks).
adfuller does by default a lag search, which makes it much slower, maxlag regressions instead on one regression.

**Comment by bashtage** [comment]
It should be noted that the outputs from `tsa.kpss` do no match what is in `arch`.  I recommend using the one in `arch`.

For example,
```
KPSS(cpi)
Out[17]: 
<class 'arch.unitroot.unitroot.KPSS'>
"""
    KPSS Stationarity Test Results   
=====================================
Test Statistic                  3.831
P-value                         0.001
Lags                               21
-------------------------------------

Trend: Constant
Critical Values: 0.74 (1%), 0.46 (5%), 0.35 (10%)
Null Hypothesis: The process is weakly stationary.
Alternative Hypothesis: The process contains a unit root.
"""
```

and

```
 tsa.kpss(cpi)
c:\git\statsmodels\statsmodels\tsa\stattools.py:1258: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
Out[16]: 
(3.8314064503689491,
 0.01,
 21,
 {'1%': 0.739, '10%': 0.347, '2.5%': 0.574, '5%': 0.463})
```

**Comment by bashtage** [comment]
@jbrockmendel In `arch` I simulated the set of critical values so that I could have p-values ranging from .1% to 100%.  My simulation was much larger than that in KPSS, and it produced similar numbers as KPSS except that the lower percentiles were slightly larger, which is probably due to the skew in the distribution and the sample size differences (50k vs 100,000k (or .05m vs 100m)).

Code is here.

https://github.com/bashtage/arch/blob/master/arch/unitroot/critical_values/simulation/kpss_critical_values_simulation.py

**Comment by jbrockmendel** [comment]
AFAICT the code matches what's in the paper.  My motivation was to get a finer/wider grid, which @bashtage evidently already did.  I'll take a look at that and see how my results compare to those.

**Comment by jbrockmendel** [comment]
@bashtage It looks like `simulate_kpss` is implicitly setting the `lags` parameter to 0.  I was defaulting to setting `lags = int(12 * (nobs/100.)**(1/4.))`.  Is there a reason not to include the sampling variation in the autocovariance terms?

**Comment by bashtage** [comment]
The asymptotic distribution only depends on a consistent estimator.  Since these are supposed to be asymptotic values. there is no need to add extra noise in estimating them.

**Comment by jbrockmendel** [comment]
From page 165 of KPSS:

```
For consistency of $s^2(l)$, it is necessary that the lag truncation
parameter $l\to \infty$ as $T\to\infty$.  The rate $l = o(T^{\frac{1}{2}})$
will usually be satisfactory under both the null [e.g. Andrews (1991)] and
the alternative [see section 4 below].
```

IIURC, the simulation is using white noise data, while the test statistic allows for autocorrelation (which is an un-estimated nuisance parameter).

Even if we grant that I'm just confused and the asymptotics are correct as-is, aren't there cases where we should be preferring the finite-sample critical values?  Or do nuisance parameters make that a can of worms we want to avoid?

**Comment by bashtage** [comment]
The claim from the paper is under an assumption of some unspecified
autocorrelated process. What is actually important is that the variance
estimator has to be consistent for the long run variance of y. The specific
variance estimator isn't that important and can take many forms - the kpss
test statistic doesn't depend on a particular long run variance estimator,
and so any estimator that converges at the same rate or higher as the one
used will work.

The problem with finite sample in this case is that one needs to also
account for the stationary process underlying the data if one wanted some
finite sample corrections.  This is hard to adequately describe since and
covariance stationary process can be used.
