### ISSUE TITLE
DOC: Prediction Results, Contrast Results, where in the docs

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3753]
do we have a docstring for the instance returned by get_prediction, e.g. GLM ?

there is no see also in the get_prediction docstring http://www.statsmodels.org/dev/generated/statsmodels.genmod.generalized_linear_model.GLMResults.get_prediction.html

I guess similar for contrast results returned by t_test, ...

**Comment by josef-pkt** [comment]
most likely postpone to 0.10, but maybe some improvement (better docs) possible now

**Comment by Juanlu001** [comment]
The prediction results were added to the docs, but the fact that the `get_prediction` method of some results objects returns a wrapper has not been updated, see for instance:

http://www.statsmodels.org/devel/generated/statsmodels.tsa.statespace.sarimax.SARIMAXResults.get_prediction.html?highlight=forecast

but:

https://github.com/statsmodels/statsmodels/blob/3caea9258dc5986178c1ea255db2b14256443c84/statsmodels/tsa/statespace/mlemodel.py#L2388-L2389

Does this deserve its own issue? @lpcampoy
