### ISSUE TITLE
Orthogonalization Using Impact Restrictions

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3756]
VARProcess supports `orth_ma_rep` given an orthogonalization matrix `P`, but in applications solving for `P` can take some work.  I'm interested in a feature allowing users to specify impact restrictions a la Blanchard-Quah.

The questions: Would such a feature find a home in statsmodels?  Would anyone besides me be interested in it?  Does it already exist somewhere I'm not aware of?

**Comment by josef-pkt** [comment]
I'm not a user in this neighborhood. @ChadFulton ?

However, we had a similar request before for generalized impulse response function, so there is a demand and possibility to extend this
https://groups.google.com/d/msg/pystatsmodels/BqMqOIghN78/A3CpDH6_h5AJ
#2068

related, but I didn't go too much into the details. SVAR is missing long run restrictions that Stata has.
