### ISSUE TITLE
DOC: Not clear what "freq" is doing

### ISSUE THREAD

**Issue by silentsnooc** [statsmodels/statsmodels#3758]
For me it is not obvious what the `freq` parameter of [`statsmodels.tsa.sesonal_decomposition`](http://www.statsmodels.org/dev/generated/statsmodels.tsa.seasonal.seasonal_decompose.html) is supposed to do.

> **freq**: `int`, optional Frequency of the series. Must be used if x is not a pandas object. Overrides default periodicity of x if x is a pandas object with a timeseries index.

Does this actually mean the sampling rate per time unit? 

I've added this question [on stackoverflow](https://stackoverflow.com/questions/44550921/seasonal-decomposition-valueerror-freq-l-not-understood) on top of another issue.

**Comment by josef-pkt** [comment]
ambiguous terminology in and across fields.

AFAIR, it is the cycle length, that is the number of periods in the seasonal cycle
monthly data with annual cycle would be 12. 

(BTW: the `period` in your stackoverflow question is a string, which is not supported)

**Comment by silentsnooc** [comment]
@josef-pkt Thank you for clarification!

One additional note: In the docs there's also 

> This is a naive decomposition. More sophisticated methods should be preferred.

but no further suggestions _what_ to use instead. In case `statsmodels` has other methods implemented one might want to reference them there.

BR; Stefan

**Comment by silentsnooc** [comment]
@josef-pkt I updated my question [on stackoverflow](https://stackoverflow.com/questions/44550921/seasonal-decomposition-valueerror-freq-l-not-understood) and I am using now Int64 indices. However, it appears that _nanoseconds_ are not recognized here?

**Comment by josef-pkt** [comment]
about "more sophisticated methods":  I'm not sure what Skipper had in mind. He wrote this function.

@ChadFulton  Is there anything "see also" or that can be pointed to in statespace, e.g. uc ?
The statespace models are mostly "causal" using pas observations. I don't know if any of the smoothing versions would work.

**Comment by josef-pkt** [comment]
It is likely that some time scales are not supported. That is why an explicit freq should override any pandas time index for freq.

What would be a "natural" or obvious cycle length for nanoseconds?  I never heard of any, and then we cannot default to any `freq`.

**Comment by silentsnooc** [comment]
I understand. Well, I ended up using integer indices and set `freq` explicit like you're suggesting. What you say makes sense. :)

**Comment by ChadFulton** [comment]
> @ChadFulton Is there anything "see also" or that can be pointed to in statespace, e.g. uc ?
The statespace models are mostly "causal" using pas observations. I don't know if any of the smoothing versions would work.

Yes, we could point to UC. It's less straightforward to use, but may allow more flexible seasonal specifications.

I guess we could also point to X13, except that I don't know much about it.

**Comment by josef-pkt** [comment]
I just got confused again between `freq` and season length or number of periods per seasonal cycle in the VECM PR.
I think we need to make this clearer and possible change the keyword to something explicit that indicated number of periods per seasonal cycle.
That is, I think we should distinguish more clearly and be more explicit between the freq of a time index (i.e. time units used) and the implied seasonal number of periods. The conversion is defined in
`from statsmodels.tsa.tsatools import freq_to_period`

AFAIU, in seasonal_decompose we don't care about the time units `freq` directly, all we need and use is the number of periods per seasonal cycle. Using the same name `freq` for both is just confusing.

**Comment by silentsnooc** [comment]
@josef-pkt I'm quite happy to see that I wasn't the only one. I actually kept working on the output coming from `seasonal_decompose` for a day until realizing that I've set the parameter wrongly. :D

So, in the end, I hope pointing out the ambiguity does in fact help! :)

**Comment by josef-pkt** [comment]
@silentsnooc 

> So, in the end, I hope pointing out the ambiguity does in fact help!

Yes, it helps. I'm a big fan of good, self-explanatory names. But sometimes it is difficult to see the user or outside perspective when we are too caught up in the details and familiar with the code.
(And choosing names is a lot or work.)

**Comment by silentsnooc** [comment]
@josef-pkt I totally agree. I sometimes manage to confuse myself with variable names as well. I think there's no programmer that does not experience this issue :D

**Comment by bashtage** [comment]
This has been renamed to `period` for consistency and correctness.
