### ISSUE TITLE
Exceptions in examples "Markov switching dynamic regression models" and "Markov switching autoregression models"

### ISSUE THREAD

**Issue by aweinstein** [statsmodels/statsmodels#3761]
The examples ["Markov switching dynamic regression models"](http://www.statsmodels.org/stable/examples/notebooks/generated/markov_regression.html) and ["Markov switching autoregression models"](http://www.statsmodels.org/stable/examples/notebooks/generated/markov_autoregression.html#Markov-switching-autoregression-models), as display in the website, are throwing the following exception:

**Markov switching dynamic regression models:**
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-cedfcf1aafb9> in <module>()
      1 # Get the federal funds rate data
----> 2 from statsmodels.tsa.regime_switching.tests.test_markov_regression import fedfunds
      3 dta_fedfunds = pd.Series(fedfunds, index=pd.date_range('1954-07-01', '2010-10-01', freq='QS'))
      4 
      5 # Plot the data

/private/tmp/statsmodels/statsmodels/tsa/regime_switching/tests/test_markov_regression.py in <module>()
     14                                               markov_regression)
     15 from numpy.testing import assert_equal, assert_allclose, assert_raises
---> 16 from nose.exc import SkipTest
     17 
     18 

ModuleNotFoundError: No module named 'nose'
```
**Markov switching autoregression models:**
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-e430f57bb8bb> in <module>()
      1 # Get the RGNP data to replicate Hamilton
----> 2 from statsmodels.tsa.regime_switching.tests.test_markov_autoregression import rgnp
      3 dta_hamilton = pd.Series(rgnp, index=pd.date_range('1951-04-01', '1984-10-01', freq='QS'))
      4 
      5 # Plot the data

/private/tmp/statsmodels/statsmodels/tsa/regime_switching/tests/test_markov_autoregression.py in <module>()
     14 from statsmodels.tsa.regime_switching import markov_autoregression
     15 from numpy.testing import assert_equal, assert_allclose, assert_raises
---> 16 from nose.exc import SkipTest
     17 
     18 current_path = os.path.dirname(os.path.abspath(__file__))

ModuleNotFoundError: No module named 'nose'
```

**Comment by bashtage** [comment]
I suppose nose is required to run the examples (`pip install nose`)

**Comment by aweinstein** [comment]
@bashtage Yes, but notice that the exceptions appear in the StatsModels web page. I'm not running this in my local machine. 

Check these links:
- http://www.statsmodels.org/stable/examples/notebooks/generated/markov_regression.html
- http://www.statsmodels.org/stable/examples/notebooks/generated/markov_autoregression.html

**Comment by josef-pkt** [comment]
I thought we had a recent issue about additional dependencies when building the docs, but don't find it.
It looks like this hasn't been fixed for our doc build.

**Comment by josef-pkt** [comment]
@TomAugspurger Do you remember if this was changed?

**Comment by bashtage** [comment]
IC - then nose is also doc build requirement apparently.

**Comment by TomAugspurger** [comment]
I thought I recalled a similar issue, but I can't find it at the moment.

I'm do a rebuild of the docs when I get a chance this weekend.

**Comment by josef-pkt** [comment]
this might be resolved, and we use pytest now, but I'm not sure

**Comment by ChadFulton** [comment]
I made a PR which stops using the data from the unit test folder, and instead downloads it from Stata's website. I don't know if that's preferable, but it's a possible fix.
