### ISSUE TITLE
BUG/TST: errors in statespace test run, and many test warnings

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3769]
**update** no errors or failures after recompiling, but still large number of invalid values in linalg

I don't know if this means much.

I copied the checkout directory including the compiled extensions and pyc files from desktop to notebook and ran the test suite in idle, just as a check whether this works.
AFAICS, I use the same winpython on desktop and notebook
(small complication, the testrun was in a folder copied by Eclipse when importing a project)
(desktop is Windows 8, notebook is Windows 7)

result is

Ran 5786 tests in 1153.032s
FAILED (SKIP=53, errors=37, failures=1)
<nose.result.TextTestResult run=5786 errors=37 failures=1>

log file:
https://gist.github.com/josef-pkt/2ce423a6c969a840f9c8bc4d254804f3

AFAIR, I have seen warnings with `det` also before "RuntimeWarning: invalid value encountered in det"

**Comment by humford** [comment]
Is this a brand new issue? As in, might this be localized to just this version of WinPython? I'm not getting this problem with the most recent version from the project website.

**Comment by josef-pkt** [comment]
This is mostly invalid,  I needed to recythonize and recompile, then all statespace tests pass and no errors or failures. (I.e. I had copied an inconsistently compiled build)

However, I still get a large number of RuntimeWarnings, e.g.
```
C:\...\WinPython-64bit-3.4.4.5Qt5\python-3.4.4.amd64\lib\site-
packages\numpy\linalg\linalg.py:1776: RuntimeWarning: invalid value encountered
in det
  r = _umath_linalg.det(a, signature=signature)
```

**Comment by bashtage** [comment]
These appear to be fixed in master.
