### ISSUE TITLE
BUG: linting, code analysis tool

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3771]
A new continuous integration site

https://lgtm.com/projects/g/statsmodels/statsmodels/alerts/

Looks like it would be worth looking at more closely. (Especially, I don't have currently code analysis in Eclipse)

one case close to the top of the list

```
        return self.family.loglike(mu, self.endog, self.exog, self.iweights,
                                   scale)
Too many arguments in call to method Gaussian.loglike; should be no more than 4.
```

that's in `def loglike_mu` which has the wrong arguments for family.loglike, and I assume is not used nor unit tested.

**Comment by josef-pkt** [comment]
another interesting error category
`53 alerts of Potentially uninitialized local variable in 30 files`
variables defined in ifs or loops, but not be defined if that path is not traversed.
insufficient test coverage for "unusual" cases.
`

**Comment by jbrockmendel** [comment]
closeable?

**Comment by bashtage** [comment]
Yes.  We have integration now (that we mostly ignore) and linting.
