### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by JoshuaC3** [statsmodels/statsmodels#3776]
From the [installation page](http://www.statsmodels.org/dev/install.html) I found the install instructions misleading. The install did not work with the _dev at the end but worked without it.

> Windows Nightly Binaries¶
> 
> If you are not able to follow the build instructions below, we occasionally upload builds of the GitHub repository to https://anaconda.org/statsmodels/statsmodels. This version can be installed using conda
> 
> conda install -c statsmodels statsmodels=0.8.0_dev

Also, it would be worth wrapping this in a code wrapper like the other command lines

![image](https://user-images.githubusercontent.com/11645712/27427123-c6653e20-5735-11e7-8d6e-7ab65c79b5c0.png)

**Comment by josef-pkt** [comment]
needs checking, I don't have any recent experience with this to say anything

**Comment by bashtage** [comment]
@josef-pkt This can be closed -- docs have been updated.
