### ISSUE TITLE
FAQ-Maintainer windows build scripts removal

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3780]
this is just a link to old maintenance files that are removed from the repo mainly for building on Windows.
#3461

They are possibly of interest for the pattern.

**Comment by jbrockmendel** [comment]
There are a lot of "Issues" like this that might make more sense in e.g. a page on the GH wiki tab.  Not a huge deal, and I know its convenient to quickly stash info in an Issue, but to the extent that Issues represent Things Needing Attention, these are a bit in the way.

**Comment by bashtage** [comment]
Release building has improved 1000%, so these are no longer relevant.
