### ISSUE TITLE
selection of lag parameter in VAR model

### ISSUE THREAD

**Issue by tryfonch** [statsmodels/statsmodels#3826]
I want to select the lag parameter p when I .fit(p) my VAR model. I use the .select_order(maxlags) to find the order of lag. I set the max lags to be a relatively big number e.g. 15.
The result I get is the following: {'aic': 1, 'bic': 0, 'fpe': 1, 'hqic': 0}

However, after looking at the result summary, I can see that all my prob values of the coefficients are way above 0.05 (I fit a VAR(2) model), above 0.5 and in some cases 0.8. This does not seem very intuitive. Given that all of the variable coefficients seem to be of significance isn't it contradicting to the .select_order() result? 

I used a .diff() function to every column of my dataframe before applying the model in order to make it stationary (also checked them using the adf test and are indeed I(1)).

**Comment by josef-pkt** [comment]
pvalues > 0.05 means that the coefficients are NOT significant at alpha=0.05
so large pvalues confirm that those lags are redundant and should be dropped.

In the VAR in diffs this means that your processes are essentially random walks.

Note, we have now VECM for the case when some of the integrated processes are cointegrated.

**Comment by tryfonch** [comment]
Thanks @josef-pkt for the reply.

I guess I misinterpreted the results. So far (I am using statsmodels for the first time) I have used the VAR and VARMAX model and this is how I interpreted the results.

In the VAR model I do NOT REJECT the coefficients with prob values more than, say, 0.05 (the [0.025 - 0.975] interval is not provided), whereas in the VARMAX model I do  NOT REJECT the coefficients with P>|z| values less than, say, 0.05 (makes sense given that 0 belongs in the [0.025 - 0.975] interval). 

Are both of my interpretations wrong? If yes what is the null hypothesis for the coefficient estimation, aren't they considered to be equal to 0?

**Comment by josef-pkt** [comment]
Your second part is incorrect, if I understand you correctly.

We do not reject the null hypothesis if the pvalue is above 0.05 or similar threshold; and we reject if the p-value is small, i.e. less than 0.05 or whatever alpha is chosen.
This is always the case.
By default all null hypotheses for tvalues and pvalues in the models are that the coefficients are zero.

This is equivalent to having zero in the corresponding confidence interval (in cases where p-values and confidence intervals are based on the same statistic and method for hypothesis tests. This is not always the case, but it is for the estimated coefficients)
