### ISSUE TITLE
stsaplots.plot_pacf vs stattools.pacf

### ISSUE THREAD

**Issue by Jerry-kiwi** [statsmodels/statsmodels#3827]
http://www.statsmodels.org/dev/generated/statsmodels...
http://www.statsmodels.org/dev/generated/statsmodels...
Both descriptions says, that "method : ‘ywunbiased’ (default)"

But in fact^
stattools.pacf using ywunbiased
plot_pacf using ywmle

**Comment by josef-pkt** [comment]
Thanks for reporting

I think the plot_xxx functions should have the same defaults as the xxx functions to avoid confusion.
(I haven't looked yet at the details.)
