### ISSUE TITLE
Pre-Testing for Stationarity in Dynamic Factor Models?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3828]
This question pertains to model specification in general and `tsa.statespace.dynamic_factor` in particular.  Motivated in part by the appendix of the [FRED-MD](https://research.stlouisfed.org/wp/more/2015-012) dataset, which describes which of the 100+ variables get logged and/or differenced.

IIRC estimating a FAVAR on non-stationary data means you're Gonna Have a Bad Time.  Non-stationary --> undefined second moments --> PCA isn't consistent because there is nothing to converge *to*.

Is there a standard procedure for specifying a dynamic factor model without a-priori information about integration/co-integration?

**Comment by ChadFulton** [comment]
I think you have a good point, and this is an interesting topic.

However, I'm not sure that this is any worse for our particular DFM model than e.g. an ARMA model where people might pass non-stationary data. The VAR transition in the DFM model is constrained in estimation to be stationary in the `transform_params` method, so if this is inappropriate, MLE probably won't converge and the transition matrix will get eigenvalues approaching 1.

I was curious, so I threw together this notebook: http://nbviewer.jupyter.org/gist/ChadFulton/30dc02868b6ad35a6b439ac78eb932a5

Does this make you more or less worried about our existing DFM model?

**Comment by jbrockmendel** [comment]
> Does this make you more or less worried about our existing DFM model?

Neither.  I'm not at all concerned about the _implementation_ of DFM here; you've been thorough.

> The VAR transition in the DFM model is constrained in estimation to be stationary

That's a VAR where the vectors are the principle components right?  My concern is that the PCA will not be well-defined/well-behaved.

The approaches I've thought of are:

1) Before running the DFM test for (co-)integration, take differences as necessary to render the inputs stationary.
2) Be informally pseudo-Bayesian and run and ensemble of specifications for different levels of integration.  
3) Be actually-Bayesian and make judgement calls about what differencing.  This is basically the approach taken in the FRED-MD appendix mentioned above.

Right now this last one seems like the most viable approach; I'd like to find a way to be more formal/methodical about it.

**Comment by ChadFulton** [comment]
I think you're right about this, but I should mention that our implementation of DFM was mostly included for feature parity with Stata. It does implement a DFM model, but it's hobbled since the number of parameters makes estimation by scoring infeasible for even a moderate number of observed variables. We could fix this by implementing the EM algorithm, but since we don't have that I don't know how much time we want to spend on the model.

That's not to say that something like this wouldn't be nice to have, but it might be better to be done in combination with a more powerful underlying DFM model?
