### ISSUE TITLE
BUG: mice imputer fails after upgrading to numpy 1.13

### ISSUE THREAD

**Issue by anisfeld** [statsmodels/statsmodels#3843]
It appears that the latest numpy does not allow the following behavior:
df[col].iloc[row_index] = np.array([[a],[b]])
where row_index is a (2,) np.array.

mice.update_all() fails when more than two values are missing and this occurs at line 395 where 
_store_changes() calls self.data[col].iloc[ix] = vals.

ValueError: shape mismatch: value array of shape (2,1) could not be broadcast to indexing result of shape (2,)

CALL STACK: using statsmodels==0.8.0
~/anaconda2/envs/py36/lib/python3.6/site-packages/statsmodels/imputation/mice.py in update_all(self, n_iter)
    413         for k in range(n_iter):
    414             for vname in self._cycle_order:
--> 415                 self.update(vname)
    416 
    417         if self.history_callback is not None:

~/anaconda2/envs/py36/lib/python3.6/site-packages/statsmodels/imputation/mice.py in update(self, vname)
   1003 
   1004         self.perturb_params(vname)
-> 1005         self.impute(vname)
   1006 
   1007 

~/anaconda2/envs/py36/lib/python3.6/site-packages/statsmodels/imputation/mice.py in impute(self, vname)
    986         # Wrap this in case we later add additional imputation
    987         # methods.
--> 988         self.impute_pmm(vname)
    989 
    990 

~/anaconda2/envs/py36/lib/python3.6/site-packages/statsmodels/imputation/mice.py in impute_pmm(self, vname)
   1078 
   1079         imputed_miss = np.array(endog_obs[iz])
-> 1080         self._store_changes(vname, imputed_miss)
   1081 
   1082 

~/anaconda2/envs/py36/lib/python3.6/site-packages/statsmodels/imputation/mice.py in _store_changes(self, col, vals)
    393         ix = self.ix_miss[col]
    394         if len(ix) > 0:
--> 395             self.data[col].iloc[ix] = vals
    396 
    397 

~/anaconda2/envs/py36/lib/python3.6/site-packages/pandas/core/indexing.py in __setitem__(self, key, value)
    177             key = com._apply_if_callable(key, self.obj)
    178         indexer = self._get_setitem_indexer(key)
--> 179         self._setitem_with_indexer(indexer, value)
    180 
    181     def _has_valid_type(self, k, axis):

~/anaconda2/envs/py36/lib/python3.6/site-packages/pandas/core/indexing.py in _setitem_with_indexer(self, indexer, value)
    617             self.obj._consolidate_inplace()
    618             self.obj._data = self.obj._data.setitem(indexer=indexer,
--> 619                                                     value=value)
    620             self.obj._maybe_update_cacher(clear=True)
    621 

~/anaconda2/envs/py36/lib/python3.6/site-packages/pandas/core/internals.py in setitem(self, **kwargs)
   3201 
   3202     def setitem(self, **kwargs):
-> 3203         return self.apply('setitem', **kwargs)
   3204 
   3205     def putmask(self, **kwargs):

~/anaconda2/envs/py36/lib/python3.6/site-packages/pandas/core/internals.py in apply(self, f, axes, filter, do_integrity_check, consolidate, **kwargs)
   3089 
   3090             kwargs['mgr'] = self
-> 3091             applied = getattr(b, f)(**kwargs)
   3092             result_blocks = _extend_blocks(applied, result_blocks)
   3093 

~/anaconda2/envs/py36/lib/python3.6/site-packages/pandas/core/internals.py in setitem(self, indexer, value, mgr)
    756             # set
    757             else:
--> 758                 values[indexer] = value
    759 
    760             # coerce and try to infer the dtypes of the result

ValueError: shape mismatch: value array of shape (2,1) could not be broadcast to indexing result of shape (2,)

**Comment by josef-pkt** [comment]
this was recently fixed in master #3768
next release should be coming in a month or so.
If you can change your installed statsmodels version as temporary solution, then it is a very small change in 3768

thanks for reporting

closing as duplicate and fixed.
