### ISSUE TITLE
DOC missing notebook in online documentation 

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3846]
two notebooks are in the notebooks folder but don't have (html) pages in online doc

"\notebooks\glm_weights.ipynb"
"\notebooks\distributed_estimation.ipynb"

https://github.com/statsmodels/statsmodels.github.io/tree/master/0.8.0/examples/notebooks/generated

distributed_estimation: errors in linalg
glm_weights: I don't know what the problem is, maybe it's more recent than doc-build

**Comment by bashtage** [comment]
AFAIK there is only `distributed_estimation` is broken notebook,

**Comment by bashtage** [comment]
This is fixed in 0.9.0, so closeable.
