### ISSUE TITLE
Why SARIMAX get_forecast() always give a straight line?

### ISSUE THREAD

**Issue by hcuny** [statsmodels/statsmodels#3852]
Hi,

I have removed the rolling mean and differenced weekly component from the original TS in advance, and the residual can be seemed stationary. When I apply SARIMAX to the residual part, it is ok doing the fitting (as well as the get_predict()), but when trying to predict out of sample time points, it always return a straight line... What could be wrong? Thanks.

**Comment by ChadFulton** [comment]
If you don't have a trend in your model, then once the transitory effects die out (which could be quite fast depending on the estimated parameters and how close the final predicted value is to the estimated mean), the prediction is simply the mean, so a straight line.

**Comment by hcuny** [comment]
Thanks, there's still yearly seasonality in my data, I can't find a way to tune the parameter for seasonal ARIMA,  should the seasonal component something like (P,D,Q,365)?

**Comment by ChadFulton** [comment]
Unfortunately, SARIMAX is not well-suited to large seasonal patterns. setting S=365 would probably take a lot of memory and computation time, and would not necessarily even give good results.

**Comment by hcuny** [comment]
Thank you so much for answering, that saves me lot of time.

**Comment by QuentinPletinckx** [comment]
Hello, I have the same problem and am fairly new to statsmodels. Is there any way to remedy the situation ? Thanks

**Comment by QuentinPletinckx** [comment]
Yes, I saw it but I do not know what the transitory effect is...

**Comment by ChadFulton** [comment]
> Yes, I saw it but I do not know what the transitory effect is...

This means that the forecasts for ARIMA models can be thought of as having two parts: a short-run (transitory) component, and a long-run component.

The long-run component is the mean of the series, and the forecast will always move to it over time - this is the straight line you mentioned. If your model includes a add a trend or a seasonal effect, then this component could be more complex than a straight line.

The short-run (or transitory) component is how the path of the forecast as it moves from the last datapoint in your sample to the long-run component. These will be different from the straight line, but depending on the estimated parameters and how close the final predicted value is to the estimated mean, they might only be visible for the first few forecasted periods.
