### ISSUE TITLE
AR.predict

### ISSUE THREAD

**Issue by ALF3000** [statsmodels/statsmodels#3861]
Hi, I have trouble using the autoregressive model class to predict some data : in the doc, it reads AR.predict takes parameters as input, but where can I get the value of the parameters ?

I was thinking that the paramters were stored in the model, but after looking inside the code, it looks like they aren't, which I find puzzling.

Here is a script illustrating my attempt :

import numpy as np
from statsmodels.tsa.ar_model import AR

x=np.random.randn(312)
ar_model=AR(x)
ar_model.fit(1)
xfitted=ar_model.predict()          # here there should be something like params
xfitter=ar_model.predict([1,-.1]) # this works but those are not the optimal parameters : where are they

**Comment by josef-pkt** [comment]
Sorry, this got lost, and not labels.

The ar_model is not changed inplace in `fit` and the model instance does not have any estimation results,
`fit` returns a Results instance that has the params and other estimation results
The pattern is the same across all Models.

The correct usage 

```
>>> result = ar_model.fit(1)
>>> result.predict()[:5]
array([ 0.06024867, -0.11587118, -0.08330599, -0.13458941,  0.04708917])
>>> result.params
array([-0.01604465, -0.0530873 ])
```
