### ISSUE TITLE
pandas.core.datetools module is deprecated

### ISSUE THREAD

**Issue by Jai-GAY** [statsmodels/statsmodels#3868]
..\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
version = '0.8.0'

**Comment by TomAugspurger** [comment]
https://github.com/statsmodels/statsmodels/issues/3617 and fixed in https://github.com/statsmodels/statsmodels/pull/3618

**Comment by stonebig** [comment]
hi all. It gest imported for me to have these 2 fixes in statsmodels . From what branch should I recompile statsmodels if you don't do a release  ?

**Comment by TomAugspurger** [comment]
master.
