### ISSUE TITLE
A bug When  I used coins function

### ISSUE THREAD

**Issue by JeiWang** [statsmodels/statsmodels#3870]
<img width="1107" alt="2017-08-16 2 40 43" src="https://user-images.githubusercontent.com/31062344/29353751-dbc1f982-829d-11e7-9d62-8eca71be28a6.png">
The left is a result on JoinQuant, the right is a result from my own python (anacoda).  I have tried many times.  I can't get why...........

**Comment by bashtage** [comment]
Don't you need a `np.random.seed(#)` to get the same values?
