### ISSUE TITLE
DOC/BUG: duplicate section in docstrings (build error on Debian)

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3873]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=868977
last comment:
```
reading sources... [ 19%] generated/statsmodels.genmod.families.family.Family

Exception occurred:
  File "/usr/lib/python2.7/dist-packages/numpydoc/docscrape.py", line 343, in _parse
    raise ValueError(msg)
ValueError: The section Notes appears twice in the docstring of None in None.
```

AFAICS: `families.Family.weights` docstring has two section headers for  "Notes". The second should be deleted.

all other methods have at most one Notes section header.

I assume that usually this results in a warning and didn't stop the doc build.

**Comment by josef-pkt** [comment]
@yarikoptic    this should be an easy fix for Debian

**Comment by yarikoptic** [comment]
@josef-pkt  - did gmail swallow my emails to you with the subject "any plans for Mar 21-24"? ;)
