### ISSUE TITLE
MAINT: doc build fails/stops on travis

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#3875]
https://travis-ci.org/statsmodels/statsmodels/builds/265820201

The doc build fails in master. It started after adding a PR with csv file and no code. So, it is not related to our changes, but some build environment must have changed.

(we also have pandas deprecation warnings about assigning to copy)

**Comment by bashtage** [comment]
Somthign seems to be wrong in 1.6.3.  I'm also seeing docbuild problems in other projects.

**Comment by josef-pkt** [comment]
@bashtage  Thanks for confirming. 

Would temporarily pinning the version number of sphinx help to get green again?

**Comment by bashtage** [comment]
I think it should: <=1.6.2 should work.

**Comment by bashtage** [comment]
Instead of pinning sphinx I removed the multithreaded building which shows up as -j 2 in the Makefile

**Comment by josef-pkt** [comment]
I removed `-j 2` in PR3880, and we don't have a problem anymore, so far.

Thanks @bashtage 

closing, we could add `-j 2` back in when sphinx is fixed, but without it the docbuild takes 15 minutes on travis which is ok.
