### ISSUE TITLE
BUG: Cannot access confidence intervals for MNLogit's  parameters

### ISSUE THREAD

**Issue by josepablog** [statsmodels/statsmodels#3883]
I don't think this has been reported here, but others had this [issue](https://stackoverflow.com/questions/44593718/valueerror-must-pass-2-d-input-when-trying-to-return-statsmodels-mnlogit-confid). 

After I train a MNLogit object:
```
baseline_model = MNLogit.from_formula(baseline_f, df_train)
baseline_fit   = baseline_model.fit()

```

Though the summary() returns the confidence interval, I get an exception with: `baseline_fit.conf_int()`

**Comment by josepablog** [comment]
This is the stack trace:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-153-ec117fdc81f1> in <module>()
----> 1 baseline_fit.conf_int()

//anaconda/lib/python2.7/site-packages/statsmodels/base/wrapper.pyc in wrapper(self, *args, **kwargs)
     93             obj = data.wrap_output(func(results, *args, **kwargs), how[0], how[1:])
     94         elif how:
---> 95             obj = data.wrap_output(func(results, *args, **kwargs), how)
     96         return obj
     97 

//anaconda/lib/python2.7/site-packages/statsmodels/base/data.pyc in wrap_output(self, obj, how, names)
    405     def wrap_output(self, obj, how='columns', names=None):
    406         if how == 'columns':
--> 407             return self.attach_columns(obj)
    408         elif how == 'rows':
    409             return self.attach_rows(obj)

//anaconda/lib/python2.7/site-packages/statsmodels/base/data.pyc in attach_columns(self, result)
    522             return Series(result, index=self.param_names)
    523         else:  # for e.g., confidence intervals
--> 524             return DataFrame(result, index=self.param_names)
    525 
    526     def attach_columns_eq(self, result):

//anaconda/lib/python2.7/site-packages/pandas/core/frame.pyc in __init__(self, data, index, columns, dtype, copy)
    295             else:
    296                 mgr = self._init_ndarray(data, index, columns, dtype=dtype,
--> 297                                          copy=copy)
    298         elif isinstance(data, (list, types.GeneratorType)):
    299             if isinstance(data, types.GeneratorType):

//anaconda/lib/python2.7/site-packages/pandas/core/frame.pyc in _init_ndarray(self, values, index, columns, dtype, copy)
    452         # by definition an array here
    453         # the dtypes will be coerced to a single dtype
--> 454         values = _prep_ndarray(values, copy=copy)
    455 
    456         if dtype is not None:

//anaconda/lib/python2.7/site-packages/pandas/core/frame.pyc in _prep_ndarray(values, copy)
   5490         values = values.reshape((values.shape[0], 1))
   5491     elif values.ndim != 2:
-> 5492         raise ValueError('Must pass 2-d input')
   5493 
   5494     return values

ValueError: Must pass 2-d input
```

**Comment by josef-pkt** [comment]
sorry I missed this.

There are some things that don't work for MNLogit because params is 2-D and conf_int() is 3-D

 IIRC As workaround to get the conf_int is to use the unwrapped results is to access the results without the pandas wrapper which is just numpy arrays `baseline_fit.model.conf_int()`

some discussion on related issues starts around here https://github.com/statsmodels/statsmodels/issues/3651#issuecomment-300511723

**Comment by jvanneck** [comment]
hi Joseph, thanks for your time on this, I tried your work around and got this error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-109-748d466806c9> in <module>()
----> 1 res.model.conf_int()

AttributeError: 'MNLogit' object has no attribute 'conf_int'

My code was:

**Comment by josef-pkt** [comment]
Sorry, I made a mistake.

`res._results.conf_int()` uses the results instance underneath the wrapper that returns numpy arrays.
The model instance  `res.model` doesn't know anything about confidence intervals.

you can also check the repr or type of `res._results` to make sure.

**Comment by jvanneck** [comment]
It works like a dream!

**Comment by josef-pkt** [comment]
I just saw that there is code in margins for MNLogit to create pandas conf_int with multi-index, 
added in PR #3311
#3309 (initial issue, closed), 
#3314 (open issue for options for names or naming conventions used in multi-index)

**Comment by bashtage** [comment]
Fixed in master.
