### ISSUE TITLE
how to pzplot AR model results?

### ISSUE THREAD

**Issue by Fankbai** [statsmodels/statsmodels#3885]
I can display pole-zero after AR processing using Matlab:

> n = ar(data, 4)
> pzplot(n) 

the type of n is idpoly.

I could't address how to display the pole-zero figure, using statsmodels model and [control model ](https://github.com/python-control/python-control), when i switch it on python, like 

> mdl = sta.AR(data ).fit(maxlag=4, ic='aic', trend='nc')
> control.pzmap(mdl)

**Comment by josef-pkt** [comment]
I don't remember or know the signal terminology.

ARMA/ARIMA has the code for computing the complex roots of the lag polynomials. If it is not available for AR, then the same type of code could be used.

how to go to a pole-zero plot I don't know.

based on a quick look control.pzmap takes a system instance with pole and zero methods, so this would need to be the estimated AR coefficients would need to be converted. However, their plot is currently  just a basic scatter plot. https://github.com/python-control/python-control/blob/master/control/pzmap.py#L72  (BSD-3 licensed)

**Comment by josef-pkt** [comment]
The AR lag-polynomial is np.concatenate(([1], -results.params])) if results.params only has the ar coefficients, otherwise a slice is needed.
scipy has some conversion code, but I don't know how much that applies to discrete time systems, given that the AR model estimates the discrete time model.

**Comment by Fankbai** [comment]
@josef-pkt @cwrowley, thanks. The pzmap need calculate the pole and zero, which parameter, both of them, should be 'sys'(a linear system) type.

typically a linear system is a fraction, includes denominator and nominator, that a 'sys' type like this:
**sys = ([den], [nom])**
 
 so that i try this(MATLAB):
> n = ar(data, 4)
> % get the coefficiants
> A = n.a                    % as the denominator
> B = 1                        % as the nominator
> sysInput = tf(A, B)    % as the sys typycal
> pzplot(sysInput)

followed this idea, I try this:

> A = mdl.params
> B= 1  
> ipt = control.tf(A,B)
> pzmap(ipt)

it seems work, but the figure:
*MATLAB result*
![MATLAB result](https://user-images.githubusercontent.com/10338671/29740875-acdc4efa-8a50-11e7-80d6-3f469288cd96.png)
*Python result*
![python result](https://user-images.githubusercontent.com/10338671/29740872-99543fa0-8a50-11e7-8e35-6c76d66895a5.png)

**Comment by Fankbai** [comment]
thank you @josef-pkt  and [Christopher Felton ](https://www.dsprelated.com/showcode/244.php), **Jesus, hand it!**.
**matlab figure**
![2017-08-26_080415](https://user-images.githubusercontent.com/10338671/29741186-1ff26356-8a57-11e7-8a68-212ce1de8bb1.png)
**Python figure**
![2017-08-26_080347](https://user-images.githubusercontent.com/10338671/29741187-27298c94-8a57-11e7-9d85-ed41b4e5ccb4.png)

，
