### ISSUE TITLE
Major bug in statsmodels.stats.sandwich_covariance.S_hac_simple

### ISSUE THREAD

**Issue by brianvanleeuwen** [statsmodels/statsmodels#3896]
I think there may be a significant bug here: https://github.com/statsmodels/statsmodels/blob/d0af408e00032e5ca5d325629409fb8be80f8eca/statsmodels/stats/sandwich_covariance.py#L402 

 (s + s.T) should be divided by two such that L402 is:

`S += weights[lag] * (s + s.T) / 2`

This can cause the results to be incorrect by a significant amount.

Additionally, I think there may be a more minor bug here:
https://github.com/statsmodels/statsmodels/blob/d0af408e00032e5ca5d325629409fb8be80f8eca/statsmodels/stats/sandwich_covariance.py#L401

`s` should be scaled to account for the drop in the number of observations used, e.g. `s = np.dot(x[lag:].T, x[:-lag]) * (x.shape[0]/x[lag:].shape[0])`.

**Comment by bashtage** [comment]
It should not be divided by 2 since there are 2 covariance, Yt, Yt+h and Yt and Yt-h.

**Comment by bashtage** [comment]
The second isn't a bug either.  If you want the estimator to be >=0 then you must use same sample size for all.

**Comment by josef-pkt** [comment]
Here is the test coverage, there is no "cosmetic" coverage, comparison results are Stata (and Gretl for some cases)
https://codecov.io/gh/statsmodels/statsmodels/compare/d0af408e00032e5ca5d325629409fb8be80f8eca...bf85618dcfcd491261dbd8ea73bebe7850b2f383/src/statsmodels/stats/sandwich_covariance.py

**Comment by brianvanleeuwen** [comment]
@bashtage, that is not consistent with L398: `S = weights[0] * np.dot(x.T, x)`

**Comment by bashtage** [comment]
That is because there is only one covariance of Yt with Yt.  Think about this, what is var(Y(t) + Y(t+1)), assuming Y is covariance stationary so that var(Y(t))=var(Y(t+1))?

**Comment by brianvanleeuwen** [comment]
Thanks, @bashtage, it is not completely clear to me, but I'll close this issue for now.  Thank you for reviewing it.

It is not obvious to me that both the covariance of Yt and Yt+h and the covariance of Yt and Yt-h should contribute (i.e. s+s.T rather than just s or s.T).  Do you have a recommendation for reference material to learn more about this topic?

**Comment by bashtage** [comment]
Section 5.9 of my notes covers this type of estimator

https://www.kevinsheppard.com/images/5/56/Chapter5.pdf

**Comment by brianvanleeuwen** [comment]
Thanks
