### ISSUE TITLE
SARIMAXRESULTS: cant forecast with series exog

### ISSUE THREAD

**Issue by Demyxter** [statsmodels/statsmodels#3907]
Hey there. Using the sarimax / sarimaxresults.forecast functions, i noticed something strange:

In the sarimax function, if i opt to use exogenous variables, you check its type, and if its not a Dataframe, transform it in one:

# Exogenous data
        self.k_exog = 0
        if exog is not None:
            exog_is_using_pandas = _is_using_pandas(exog, None)
            if not exog_is_using_pandas:
                exog = np.asarray(exog)

            # Make sure we have 2-dimensional array
            if exog.ndim < 2:
                if not exog_is_using_pandas:
                    exog = np.atleast_2d(exog).T
                else:
                    exog = pd.DataFrame(exog)

However, in the sarimaxresults.forecast, such operation seems to not be done. As such, if i pass a .series exogenous, i am able to fit my model, but cannot get predictions done using the same .series.

        if isinstance(steps, (int, long)):
            end = self.nobs+steps-1
        else:
            end = steps
        return self.predict(start=self.nobs, end=end, **kwargs)

Is this intended?

This is my first time using this site, and relatively new to programming in general, so pardon me for any mistakes.

**Comment by ChadFulton** [comment]
I'm not sure what you're trying to do - can you post a code sample with what you'd like to see work?

**Comment by Demyxter** [comment]
I'm trying to predict sales of a certain product based on predictors such as month, number of working days,gdp,number of workers etc:

    Master = pd.read_csv('...')

    idx = pd.date_range('01/01/2012',freq='M',periods=61)
    Master.index = idx

    Predictors = Master[['MONTH' ,'N_WORKING_DAYS', 'N_WORKERS', 'GDP']
    to_predict = Master['SALES_50472']

    TrainingSize = int(0.8*to_predict.shape[0])
    TestSize = to_predict.shape[0] - TrainingSize

    mod = SARIMAX(to_predict[:TrainingSize],exog=Predictors['MONTH'][:TrainingSize],order=
    (1,1,0),enforce_invertibility=False,trend='c')
    res = mod.fit(disp=0)

    frc =res.forecast(TestSize,exog=Predictors['MONTH'][TrainingSize:] )


From which i get:

     Traceback (most recent call last):
      line 22, in <module>
        frc =res.forecast(TestSize,exog=Predictors['MONTH'][TrainingSize:] )
      File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\base\wrapper.py", line 95, in 
    wrapper
        obj = data.wrap_output(func(results, *args, **kwargs), how)
      File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 
    2396, in forecast
        return self.predict(start=self.nobs, end=end, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 
    2369, in predict
        prediction_results = self.get_prediction(start, end, dynamic, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\sarimax.py", line 
    1903, in get_prediction
        str(exog.shape)))

    ValueError: Provided exogenous values are not of the appropriate shape. Required (13, 1), got (13,).

However, if i transform the exogenous values to a dataframe before trying to forecast:

    `  frc =res.forecast(TestSize,exog=pd.Dataframe(Predictors['MONTH'])[TrainingSize:] )`

I get the forecast.

So, i'm guessing that this is due to the exogenous values in .forecast being required to be a 2dim dataframe, instead of a 1dim series. I might be wrong, though. What is happening here?

**Comment by ChadFulton** [comment]
> So, i'm guessing that this is due to the exogenous values in .forecast being required to be a 2dim dataframe, instead of a 1dim series. I might be wrong, though. What is happening here?

You're exactly right. We should make this more convenient for users by allowing passing 1-dimensional objects, but right now 2-dimensional objects are required.

**Comment by mareean3** [comment]
> 
> 
> I'm trying to predict sales of a certain product based on predictors such as month, number of working days,gdp,number of workers etc:
> 
> ```
> Master = pd.read_csv('...')
> 
> idx = pd.date_range('01/01/2012',freq='M',periods=61)
> Master.index = idx
> 
> Predictors = Master[['MONTH' ,'N_WORKING_DAYS', 'N_WORKERS', 'GDP']
> to_predict = Master['SALES_50472']
> 
> TrainingSize = int(0.8*to_predict.shape[0])
> TestSize = to_predict.shape[0] - TrainingSize
> 
> mod = SARIMAX(to_predict[:TrainingSize],exog=Predictors['MONTH'][:TrainingSize],order=
> (1,1,0),enforce_invertibility=False,trend='c')
> res = mod.fit(disp=0)
> 
> frc =res.forecast(TestSize,exog=Predictors['MONTH'][TrainingSize:] )
> ```
> 
> From which i get:
> 
> ```
>  Traceback (most recent call last):
>   line 22, in <module>
>     frc =res.forecast(TestSize,exog=Predictors['MONTH'][TrainingSize:] )
>   File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\base\wrapper.py", line 95, in 
> wrapper
>     obj = data.wrap_output(func(results, *args, **kwargs), how)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 
> 2396, in forecast
>     return self.predict(start=self.nobs, end=end, **kwargs)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 
> 2369, in predict
>     prediction_results = self.get_prediction(start, end, dynamic, **kwargs)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\sarimax.py", line 
> 1903, in get_prediction
>     str(exog.shape)))
> 
> ValueError: Provided exogenous values are not of the appropriate shape. Required (13, 1), got (13,).
> ```
> 
> However, if i transform the exogenous values to a dataframe before trying to forecast:
> 
> ```
> `  frc =res.forecast(TestSize,exog=pd.Dataframe(Predictors['MONTH'])[TrainingSize:] )`
> ```
> 
> I get the forecast.
> 
> So, i'm guessing that this is due to the exogenous values in .forecast being required to be a 2dim dataframe, instead of a 1dim series. I might be wrong, though. What is happening here?

Can you please explain me how can I create a 2 dimensional dataframe? I am new to python. Many thanks.

**Comment by josef-pkt** [comment]
using series for predict is broken in general #6509

IIRC, this worked for me:

`df = pd.DataFram(series_1d, columns="my_name")`

**Comment by mareean3** [comment]
I'm getting the same error. I'm new to Python but I cannot understand why and how can I declare two dimensional data frames.

    exog = exog.reshape(required_exog_shape)
ValueError: cannot reshape array of size 285 into shape (45,5)

ValueError: Provided exogenous values are not of the appropriate shape. Required (45, 5), got (57, 5).

**Comment by ChadFulton** [comment]
The problem that @Demyxter was describing in this issue has been fixed (maybe in #6280? or maybe earlier)

> using series for predict is broken in general #6509

For `SARIMAX`, series still work, I think. For example, the following works for me:

```python
import statsmodels.api as sm
import pandas as pd

# Get the macro dataset
dta = sm.datasets.macrodata.load_pandas().data
dta.index = pd.date_range('1959Q1', '2009Q3', freq='QS')

endog = dta['realgdp'].iloc[:-12]
exog_insample = dta['realgovt'].iloc[:-12]
exog_forecast = dta['realgovt'].iloc[-12:]

mod = sm.tsa.SARIMAX(endog, order=(1, 1, 0), exog=exog)
res = mod.fit()

assert isinstance(exog_forecast, pd.Series)
res.forecast(12, exog=exog_forecast)
```

**Comment by ChadFulton** [comment]
@mareean3 if you are forecasting 45 periods, you can only give the `forecast` method 45 periods worth of data. From the error messages you're posting, it looks like you are trying to give the `forecast` method 57 periods worth of data, which is too much.

**Comment by ChadFulton** [comment]
Closing, since the original issue is now fixed.

**Comment by mareean3** [comment]
I followed your script step by step. Many thanks for your patience.
But now I have this error:

f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 57 elements, new values have 56 elements

**Comment by mareean3** [comment]
Dear ChadFulton
The context: 


> 
> 
> @mareean3 if you are forecasting 45 periods, you can only give the `forecast` method 45 periods worth of data. From the error messages you're posting, it looks like you are trying to give the `forecast` method 57 periods worth of data, which is too much.

Dear ChadFulton
This error is persistent

df= pd.read_csv(filepath, index_col=0)
#using pandas to read the csv file which contains one sheet, 7 columns, first column is the year (period 1961-2017)
the next columns have the dependent and independent (endogenous and exogenous variables)

df.index = pd.date_range('1961', '2017', freq='A')

# declare the index as you recommended
# Then declare endogenous and exogenous variables

endog = df['emi'].iloc[:-11]
exog_insample = df[[ 'gdp' ,'pop', 'fincons', 'gni']].iloc[:-11]
exog_forecast = df[[ 'gdp' ,'pop', 'fincons', 'gni']].iloc[-11:]

#run the SARIMAX (with train and test periods)

mod = sm.tsa.SARIMAX(endog, order=(0,1,0), seasonal_order=(1, 0, 0, 12),enforce_invertibility=False,trend='c', exog=exog_insample)
res = mod.fit()
print(res.summary())

#now using the "predict" to forecast for the next 50 years
pred = res.get_prediction(start=pd.to_datetime('2017'), end=pd.to_datetime('2050'), exog=exog_forecast[[ 'gdp' ,'pop', 'fincons', 'gni']], dynamic=True)

Erors: 

exog = exog.reshape(required_exog_shape)
ValueError: cannot reshape array of size 44 into shape (44,4)
...
str(exog.shape)))
ValueError: Provided exogenous values are not of the appropriate shape. Required (44, 4), got (11, 4).

What should I do to correct the shape?
