### ISSUE TITLE
Please support Python3

### ISSUE THREAD

**Issue by tillea** [statsmodels/statsmodels#3909]
Hi,
the Debian package of statsmodels received a [bug report](https://bugs.debian.org/cgi-bin/729956) requesting suport for Python3.  This was in end of 2013.  I think it would be time to consider Python3 for the next release of statsmodels.
Kind regards, Andreas.

**Comment by josef-pkt** [comment]
That's a problem of Debian packaging.
statsmodels has supported python 3 for many years. 
I haven't used python 2 in several years.  Most likely we will drop support for python 2 within the next few years.)

**Comment by josef-pkt** [comment]
closing, Debian seems to have statsmodels for python 3 now.
