### ISSUE TITLE
REF: sm.compat bytes-or-unicode type

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3927]
This is a reminder to follow up on #3806

**Comment by ChadFulton** [comment]
The idea is that the referenced PR uses the following shim for Py3 string compatibility:

```
try: unicode
except NameError: unicode = str
```

and @josef-pkt suggested that this would be better in a compatibility library.

**Comment by jbrockmendel** [comment]
Another option would be to recognize that statsmodels already has an implicit dependency on `six`, and where needed just use `import six.text_type as unicode`

**Comment by bashtage** [comment]
What is wrong with string_type?
