### ISSUE TITLE
TST: Less Verbose Test Logs?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3930]
This is a pretty minor quibble, but when going through Travis logs, scrolling through thousands of lines of 
```
statsmodels.tests.foo.bar.test_baz... OK
```
takes a while to load.  I'm not sure exactly what config would need to be changed, but it'd be nice if passing tests just printed `.` and the log was more focused on warnings/errors.

If there is consensus on this, I'll volunteer to figure out how to make it work.

**Comment by josef-pkt** [comment]
No, we cannot remove which tests are running from the log, or we will not see where it gets stuck, e.g.
https://ci.appveyor.com/project/josef-pkt/statsmodels/build/1.0.2263/job/rxjds2fudtx6ojn0

The verbose nosetest setting was longer than this pytest setting and the testlog had to be loaded as raw file. nosetests verbose printed every test in the log and not just modules like pytest. 
(One reason for verbose in nosetests was also to see warnings directly in the log which helped to identify which test might have problems. One other reason to have the list of tests in the log was to check occasionally whether a specific test was actually run.)

Where I don't know yet what to do, is about the verbose default error/failure message of pytest. It always takes me some time just to find what the test failure actually is, which is hiding in the middle of the verbose code quotes.  Sometimes it's useful to see the calling sequence but most of the time it is time wasting noise for me.

I played with several settings for changing the pytest output locally, but don't have enough experience yet with pytest to have a convincing opinion. (maybe I get used to or find some other use for the other pytest "noise")
