### ISSUE TITLE
endog, exog -> y, x

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#395]
Heard more feedback that endog and exog are a stumbling block for new users. These were people who know stats, they just don't come from econometrics background. I think we should deprecate and move to using y,x.

**Comment by arondes** [comment]
What about "Response" and "Predictor"?

**Comment by jseabold** [comment]
I continue to receive grief about this from pretty much every single person I talk to about statsmodels. Almost anything would be better than the current situation.

**Comment by argriffing** [comment]
Alongside the `exog` and `endog` variables, statsmodels needs `yodog` variables that have a recursive dependence structure.

**Comment by josef-pkt** [comment]
@argriffing  what's a `yodog`?   how do you spell that?

**Comment by argriffing** [comment]
It also needs `updog`. I'll probably be deleting these comments soon.

**Comment by mmagnuski** [comment]
Although I am not new statsmodels user I have to say everytime I look up the docs and see endog and exog I wonder why such confusing (or at least uncommon) naming is retained.

**Comment by ndas1971** [comment]
Then we have 'instruments'  containing both included and excluded exogenous variables!!

**Comment by josef-pkt** [comment]
`instruments` I think is fine, that's a general term, with relatively clear definition.
endogenous variables that are in `exog` are still a naming problem, where I haven't found a good name yet that I like for more than one day.

In text I usually use "explanatory variables", but `explan` sounds a bit ugly as a name.

x, y, z, w, greek letters and similar are ruled out. I struggle way to much with articles and textbooks across fields where authors use idiosyncratic letters without mentioning each time what they stand for.
(And there are lower case, upper case, curly, bold x, with hat, with tilde, with two hats that all mean something different, as defined in chapter 2)
and no unicode letters in spite of them looking "cute" in Julia, as long as you don't have to type it or read it without a text book or article at hand.

```
res = WLS2(y_curly, X_bold, w_hat, kappa=1.5).fit()
y_curly_hat = res.fittedvalues
```

**Comment by bashtage** [comment]
Despite not liking this, it is never going to change given the pervasiveness of it.

**Comment by javadba** [comment]
One person was against this and it stayed as that one person wanted it.
