### ISSUE TITLE
Error while saving UCM model using pickle (Python3.6)

### ISSUE THREAD

**Issue by guptanitzz** [statsmodels/statsmodels#3953]
I have to create multiple ucm models which is to be used later on for prediction. So , I am trying to save them. Tried several methods but none of them is working . Below is the error 

```
**/anaconda/lib/python3.6/site-packages/statsmodels/base/wrapper.py in save(self, fname, remove_data)
     70             self.remove_data()
     71 
---> 72         save_pickle(self, fname)
     73 
     74     @classmethod

/anaconda/lib/python3.6/site-packages/statsmodels/iolib/smpickle.py in save_pickle(obj, fname)
     13     """
     14     with get_file_obj(fname, 'wb') as fout:
---> 15         cPickle.dump(obj, fout, protocol=-1)
     16 
     17 

TypeError: can't pickle statsmodels.tsa.statespace._statespace.dStatespace objects_**
```

Any work around this error?

**Comment by ChadFulton** [comment]
Thanks for the report - which version of Statsmodels are you using? I think this has been fixed in master, but that fix was not in the 0.8 release.

**Comment by guptanitzz** [comment]
Thanks for the quick reply .  Statsmodel installed in my system is 0.8  release. From where can i access the master ?

**Comment by bashtage** [comment]
You need to install from source.  You can either download the zip from  the repo or run the commands

```
git clone https://github.com/statsmodels/statsmodels
cd statsmodels
python setup.py install
```

You will need a compiler compatible with your OS and python version.

**Comment by guptanitzz** [comment]
Thanks for the instructions. It's working now

**Comment by bashtage** [comment]
Is this broken?  It shouldn't be since it is tested in master.

**Comment by guptanitzz** [comment]
statsmodels (0.8.0)

**Comment by bashtage** [comment]
You need to install from master for your Python 3.6 just like above.  The
fix hasn't been released but should be out in the next month.

**Comment by josef-pkt** [comment]
the rc1 is out and needs checking by users
 https://pypi.org/project/statsmodels/0.9.0rc1/

**Comment by bashtage** [comment]
Readme should lose the "quotes" around most of the links.

**Comment by vjVaidya** [comment]
I do not know how but here is what solved my problem: 
Previously: 
Anaconda updated from 5.1 -> 5.2
statsmodel 0.8 -> 0.9
python 3.5 -> 3.6
This issue persisted. 

Now: 
Unistall Anaconda3-5.1
Install Anaconda3-5.2.0-Windows-x86_64 which has python 3.6 integrated and the issued was solved. 

**I can now guess that somehow the updates from the older Conda version were causing issues. A fresh installation resolved the issue. I know that a fresh installation is not always a good solution but this might a worst case scenario solution.** 

Cheers guys.

**Comment by bashtage** [comment]
@ChadFulton This can be closed.

**Comment by SupunDileepa** [comment]
use statsmodels version 0.9.0

**Comment by SupunDileepa** [comment]
use statsmodels version 0.9.0
