### ISSUE TITLE
How to get prediction within the dates provided in sample but with different exog variable values

### ISSUE THREAD

**Issue by fawad-khalil** [statsmodels/statsmodels#3969]
I want to get prediction based on different exog variable values but those prediction dates are contained in the timeseries used when training the model and some out-of-sample dates. When I do so I get the error:

> **"Provided exogenous values are not of the appropriate shape. Required (364, 78), got (455, 78)."**

Here the difference in the shape is because the get_prediction() method is not accepting the exog variable rows which have the date contained in training timeseries.

I am using get_prediction() method with start, end, dynamic = True, full_results = True, exog parameters. 

Is there any other method for this kind of task?

Python 3.6.2

**Comment by josef-pkt** [comment]
You didn't mention which model you use. Can you provide a reproducible example?

**Comment by fawad-khalil** [comment]
I am using sarimax model .

```
from statsmodels.tsa.statespace.sarimax import SARIMAX
import pandas as pd

datelist = pd.date_range(pd.to_datetime('2012-12-31'), periods = 100).tolist()
date_df = pd.DataFrame(datelist, columns = ['dates'])
endog= pd.concat([date_df, pd.DataFrame(np.random.randint(0,100,size=(100, 1)), columns=list('a'))], axis = 1)

exog = pd.concat([date_df, pd.DataFrame(np.random.randint(0,100,size=(100, 1)), columns=list('b'))], axis = 1)

endog.index = endog.dates
endog = endog.drop(['dates'], axis = 1)

exog.index = exog.dates
exog = exog.drop(['dates'], axis = 1)

sarimax_model = SARIMAX(endog = endog,
                                order = (0, 0, 0),
                                exog = exog,
                                seasonal_order=(1, 0, 0, 12),
                                enforce_stationarity=True,
                                enforce_invertibility=False)

sarimax_result = sarimax_model.fit()

#this does not seem to work if exog_test has indices starting from 2013-02-18 to 2013-05-31
#this is what i am trying to achieve
prediction4 = sarimax_result.get_prediction(start = 50, end = 152, dynamic = True, full_results = True, exog = exog_test)


```

**Comment by fawad-khalil** [comment]
may be there would be plus minus of one or two in start and end parameter values  in the line 

`prediction4 = sarimax_result.get_prediction(start = 50, end = 152, dynamic = True, full_results = True, exog = exog_test)`

But case scenario is same as described.

**Comment by fawad-khalil** [comment]
Please check my updated comment of example code.

**Comment by fawad-khalil** [comment]
@josef-pkt are you able to replicate the error?

**Comment by ChadFulton** [comment]
Cross reference #3907

This is not a bug *per se*, in the sense that it is expected behavior - the `exog` passed to predict is expected to be the *additional* exog required for the forecasted periods only.

However, this seems like an important enhancement since there is no reason it shouldn't work, and given the improvements to indexes generally and date handling in `tsa`, it should be straightforward to fix.

**Comment by ChadFulton** [comment]
In your example, I think you're suggesting that the following code would produce an error:

```python
exog_test = pd.Series(np.arange(103), index=pd.DatetimeIndex(start='2013-02-18', end='2013-05-31', freq='D'))
prediction4 = sarimax_result.get_prediction(
    start=50, end=152, dynamic=True, full_results=True, exog=exog_test)
```

the solution is to use the following:

```python
exog_test = pd.Series(np.arange(103), index=pd.DatetimeIndex(start='2013-02-18', end='2013-05-31', freq='D'))
prediction4 = sarimax_result.get_prediction(
    start=50, end=152, dynamic=True, full_results=True, exog=exog_test[-53:, None])
```

**Comment by fawad-khalil** [comment]
@ChadFulton but that would take only last 53 exog_test rows. The problem is I need prediction on first ones also. I have seen the inner code of package modules and I also noticed that this functionality has not been added. But I am in hurry now and will work on it when I get time if not solved then.

**Comment by ChadFulton** [comment]
The predict functions in these models are designed for in-sample prediction and out-of-sample forecasting. They are not immediately meant for application to completely separate datasets.

Take a look at #3623 and at https://github.com/statsmodels/statsmodels/issues/2788#issuecomment-175209448

**Comment by fawad-khalil** [comment]
Then I don't understand what's the purpose of providing exog dataset. However, thanks for your response. :)

**Comment by ChadFulton** [comment]
The purpose is for out-of-sample forecasting. For example, if I estimate an AR model, then the model is self-contained and I can forecast any number of periods. However, if I estimate an ARX model, then the model requires specification of the exogenous variable for any new periods, and forecasting requires the user to specify the new (out-of-sample) `exog` variables.

**Comment by Akshat12071207** [comment]
> The purpose is for out-of-sample forecasting. For example, if I estimate an AR model, then the model is self-contained and I can forecast any number of periods. However, if I estimate an ARX model, then the model requires specification of the exogenous variable for any new periods, and forecasting requires the user to specify the new (out-of-sample) `exog` variables.


Let me correlate this to my doubt, 

I have my endog variable from **2009-03-01 to 2020-03-01**, quarterly and I have my exog variables for the same date range.
I passed my endog and exog variables in the SARIMAX model and fitted the model. There were no errors. However, when i tried to FORECAST **(from 2020-06-01 to 2021-03-01)** my endog variable using SARIMAX, an error popped up saying i need to pass exog variable for the OUT of Sample forecast.

I mean, I dont have the future values of my **EXOG** variables. Does it mean I won't be able to do forecast with SARIMAX? 



```
`from statsmodels.tsa.statespace import sarimax

my_order = (a, 1, b)
my_seasonal_order =( 0, 1, 1, 4)

arima = sarimax.SARIMAX(tra,order=my_order, seasonal_order=my_seasonal_order,exog=exogen_train).fit()

fore = 8
arima.forecast(fore,dynamic = True)

ValueError: Out-of-sample operations in a model with a regression component require additional exogenous values via the `exog` `argument.``
```

**Comment by bashtage** [comment]
You need to provide the next 8 steps ahead of exogen_train, or the forecasts of these.

**Comment by Akshat12071207** [comment]
> You need to provide the next 8 steps ahead of exogen_train, or the forecasts of these.

Alright, Thank-you very much for you prompt response!
