### ISSUE TITLE
The compat modules should use absolute imports

### ISSUE THREAD

**Issue by abalkin** [statsmodels/statsmodels#3975]
The [statsmodels.compat.collections](https://github.com/statsmodels/statsmodels/blob/a88830efc3a99cfbe0ebc9fbfd77820fe748fc59/statsmodels/compat/collections.py#L7) imports the namesake standard library module without requesting absolute imports.  While it seems to work in many cases, it causes a problem to packages that override `__import__`.  See enlnt/pyq#18.

Please consider adding

```python
from __future__ import absolute_import
```
to the compat modules.

**Comment by josef-pkt** [comment]
Our related packages numpy, pandas, scipy have the future import, but not the python compat modules

**Comment by josef-pkt** [comment]
However, AFAICS, both ordereddict and counter are in python 2.7, so the collections compat is not needed anymore.

**Comment by abalkin** [comment]
I looked in [setup.py](https://github.com/statsmodels/statsmodels/blob/a88830efc3a99cfbe0ebc9fbfd77820fe748fc59/setup.py#L179) and you seem to still support 2.6.  It may be time to drop it given that numpy and scipy did so recently.

**Comment by josef-pkt** [comment]
We did drop it, at least we stopped including python 2.6 in our unit tests.
However, unless we explicitly remove python 2.6 compatible code, statsmodels will still work with python 2.6 for most parts, with maybe just a few exceptions. 
(I have no idea right now, given that I haven't even used python 2.7 in a long time.)
