### ISSUE TITLE
DISC: arfreq/mafreq return when empty

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3978]
From arima_model, similar elsewhere:

```
    @cache_readonly
    def mafreq(self):
        r"""
        Returns the frequency of the MA roots.

        This is the solution, x, to z = abs(z)*exp(2j*np.pi*x) where z are the
        roots.
        """
        z = self.maroots
        if not z.size:
            return
        return np.arctan2(z.imag, z.real) / (2*pi)
```

If we got rid of the `if not z.size` clause, we'd just return an empty array.  Having a single return type would improve consistency.

Thoughts?

**Comment by josef-pkt** [comment]
depends on where it is used. We often use `None` as a sentinel for `not available` or `not applicable`. Whether empty array works depends on the implementation details, especially numpy and pandas treatment of empty array_likes.

Most of our optional things have a type: "either None or <xxx>"   where xxx could be an array or something.
