### ISSUE TITLE
coefs/params consistency

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3979]
There is a potential inconsistency in AR/ARMA/ARIMA/.../VAR in nomenclature for `coefs` vs `params`.

For the purposes of this post, I'm going to treat the following relationships as describing the canonical nomenclature:

```
arparams = np.r_[1, -arcoefs]
arcoefs = -arparams[1:]
maparams = np.r_[1, macoefs]
macoefs = maparams[1:]
```

while it isn't actually used at the moment, it is worth noting that this can be extended to include the VAR case with:
```
arparams = np.r_[np.eye(neqs), -arcoefs]
arcoefs = -arparams[1:]
```

AFAICT this naming convention is not followed consistently.

From `arima_process.ArmaProcess`:
```
    def __init__(self, ar=None, ma=None, nobs=100):
        if ar is None:
            ar = np.array([1.])
        if ma is None:
            ma = np.array([1.])
        self.ar = np.asarray(ar)
        self.ma = np.asarray(ma)
        self.arcoefs = -self.ar[1:]
        self.macoefs = self.ma[1:]
        self.arpoly = np.polynomial.Polynomial(self.ar)
        self.mapoly = np.polynomial.Polynomial(self.ma)
```

Here a third set of names ma/ar is introduced, but arcoefs/macoefs are defined as expected.  But in `ArmaProcess.from_estimation`:

```
        arcoefs = model_results.arparams
        macoefs = model_results.maparams
        nobs = nobs or model_results.nobs
        return cls(np.r_[1, -arcoefs], np.r_[1, macoefs], nobs=nobs)
```

So ArmaProcess and ArmaModel will _never_ agree on the nomenclature.  Also not a big deal, but the docstrings in ArmaProcess reverse coefs<-->params.

`ar_model` doesn't have anything in the namespace that takes a stand on this, but usage within functions uses arparams in places that "should" be arcoefs.

`arima_model` is not consistent, but leans towards using `arparams` where it "should" use `arcoefs`

There are some similar names in sarimax, varmax, and that's where I stopped looking.

Of course for VAR and SVAR they are just named `params`.

So the arbitrarily chosen "canonical" nomenclature chosen above turned out to be pretty uncommon.  I'd like to standardize these relationships.  Any thoughts?

**Comment by josef-pkt** [comment]
difficult

`params` is usually our standard terminology in estimation Models. Processes and distributions (outside of tsa) have often a different `param`eterization.  I used coefs in the process to distinguish process parameters defined in the lagpolynomials from the coefficient estimated by the Model as `params`.

Model estimation is the dominant usage, so we need `params` and some variation for parts of the overall params like arparams, maparams exogparams or whatever we have.
`coefs` is not a generic term for us and it is not used across the board, so what it means can be context dependent or should be avoided.

So this
```
arcoefs = model_results.arparams
macoefs = model_results.maparams
ar, ma = np.r_[1, -arcoefs], np.r_[1, macoefs]
```
made/makes kind of sense to me: The estimated `arparams` and `maparams` (subsets of `params`), are the `coef`ficients in the lag polynomial, but the full `ar` `ma` lag polynomials are extended by the leading 1.

**Comment by jbrockmendel** [comment]
Yah this is tough.

The solution may be to standardize `ar`, `arcoefs`, `ma`, `macoefs` and try use `arparams/maparams` only in model estimates.  Where feasible, we can use `np.polynomial.Polynomial` objects to be extra-unambiguous.
