### ISSUE TITLE
conda can't get statsmodels=0.8.0_dev

### ISSUE THREAD

**Issue by tsando** [statsmodels/statsmodels#3982]
As per this documentation http://www.statsmodels.org/dev/install.html It says one can get the dev version as `conda install -c statsmodels statsmodels=0.8.0_dev` with `conda` but I get a `PackageNotFoundError` as follows:

```
$ conda install -c statsmodels statsmodels=0.8.0_dev
Fetching package metadata ...............

PackageNotFoundError: Packages missing in current channels:

  - statsmodels 0.8.0_dev*

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/statsmodels/win-64
  - https://conda.anaconda.org/statsmodels/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch
```

Any ideas how I can get the latest compiled master branch? I am unable to compile it from source and get all source of errors when I try to use it from the git cloned repo directly... thanks.

**Comment by ThulasiKrishna** [comment]
Hi, Is this issue fixed or still persists?

**Comment by bashtage** [comment]
Closing.  This is old and as far as we know, this is working. Reopen if this issue persists.
