### ISSUE TITLE
min version?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#3999]
Has 2.6 been dropped yet?  If so, we can get rid of compat.collections

**Comment by josef-pkt** [comment]
see #3975 for recent fix in there and discussion.

We have dropped support for python 2.6 and stopped CI testing, but didn't explicitly remove compatibility. (i.e. old code most likely still works, recent code or enhancements use features that are not py 2.6 compatible)
I think we wait until after 0.9 to explicitly remove py 2.6 compat features.

**Comment by bashtage** [comment]
Yes, 2.6 is dropped. IMO it is mistake to not immediately welcome code clean-up and modernization efforts for unsupported versions.  I think pandas has it right in terms of speed.  For example, 0.9 should only explicitly support 2.7 and 3.5+, probably Numpy 1.9+, and the last 3 or so versions of SciPy.
