### ISSUE TITLE
tools.linalg.pinv2 unused

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4027]
has it been supplanted by something upstream?

**Comment by jbrockmendel** [comment]
Also `lstsq`.

**Comment by jbrockmendel** [comment]
`linalg.logdet_symm` is used a couple of times, but appears to be about equivalent to `np.linalg.slogdet(x)[1]`, and the latter ~2x faster.

**Comment by jbrockmendel** [comment]
`tools.rootfinding.brentq_expanding` is used once in `stats.power` (which itself is nearly-unused).  Can brentq_expanding be supplanted by something modern from scipy?

**Comment by josef-pkt** [comment]
`power` is not nearly-unused.
It's a feature in itself, e.g #4022
scipy rootfinders don't have a direct equivalent of `tools.rootfinding.brentq_expanding` and I wrote it specifically to handle `power` rootfinding

I don't know about the other ones without checking.

**Comment by jbrockmendel** [comment]
> `power` is not nearly-unused.  It's a feature in itself

Poor word choice; my bad.  I'm trying to identify the subset of stats+tools that is needed by base+regression+discrete+tsa+genmod+robust (and to a lesser extent duration+multivariate+nonparametric..., though I'm less familiar with those).

**Comment by josef-pkt** [comment]
Every once in a while I'm looking at adding `power` computation to the models :)
But that looks still far away. I don't have an overview and only some vague ideas.

What is higher on my priority but doesn't directly link code, is to find and document hypothesis tests in `Models` and in `stats` functions that are equivalent (except for small sample corrections) and use that more extensively for unit tests.

**Comment by jbrockmendel** [comment]
`compat.testing.example`

**Comment by jbrockmendel** [comment]
arima_model._unpack_order

**Comment by jbrockmendel** [comment]
stattools._safe_arma_fit, stattools.arma_order_select_ic

**Comment by jbrockmendel** [comment]
tsa.varma_process._Var, VarmaPoly, varfilter, ar2lhs, ar2full (pretty much all of varma_process)
