### ISSUE TITLE
SUMM: Topic Week - Internal Consistency

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4030]
- Model/Results attributes consistency
   - `GLMResults._endog` --> `self.endog` or just `self.model.endog` #4028
   - some Results classes attach `endog, exog, nobs,...`, others don't.
   - Results attributes getting pinned to models #4016, #3984
   - Attributes in FooResultsWrapper #3920 
   - Make `**kwargs` explicit where possible, validation #3890, #4019, #2163
   - Avoid creating new attributes outside of `__init__`.  Ideally avoid changing things in-place.  #3787.
    - LikelihoodModelResults object has no attribute mle_retvals #3708
    - "J" in GEEMargins?  #3671
    - cov_struct.Nested AttributeError 'vcomp_coeff'  #3668
    - fit_regularized has no get_prediction, cov_params #3626
    - PoissonZiGMLE: predict not implemented?  #3496
    -  AR/ARMA/... avoid `set_sigma2` pattern; avoid setting model attributes that are really Result attributes during `fit`.
    - VAR, trend needs to be in `__init__` #2273 (this one is tough but would be a huge win)
   - required attributes of models and results #1970

- Class Hierarchy
   - VARResults, SVARREsults, VECMResults don't subclass Results (TODO: double-check).
   - `DiscreteResults.__init__` doesn't call `super(...)`
   - This makes it harder to reason about what attributes can consistently be expected to exist in a Results instance.
   - SVAR should subclass VAR, will raise AttributeError in `fit` if `select_order` is reached.
   - tsa.statespace has some special handling for model.data.  Life would be better if special cases were mainlined.
   - MICEResults subclasses LikelihoodModelResults, but MICE does not subclass Model.  So MICEResults.model does not behave as expected.  #3324

- `get_robustcov_results`
  - Defined in several places; There Can Be Only One #4014
  - Usually called in `FooResults.__init__`, but sometimes called in `FooModel.fit` #4025
  - Small differences between the versions in linear_model vs base.covtype
  - Small differences between the versionsin regime_switching vs statespace

- Naming Consistency
   - Lots of places in sandbox and tsa that don't follow naming conventions #4015
   - `self.y` --> `self.endog` in e.g. VARResults
  - Naming of weights arguments in WLS #3891 
   - orig_endog vs endog_lagged vs... #3689
   - `regressor` vs `exog` for IV, 2SLS? #2248

- Degrees of Freedom
    - mixed_linear_model doesn't define df_model, aic/bic define their own `df` variables #3742
    - when to use k_exog vs rank?  #1928
    - when to use `# assumes constant`?  Make this explicit
    - GEE cases not tested?  #3726
    - aic in AR/ARIMA/... #3574
    - df_resid in ar/arima/var_model  #3568
    - ddof for models #2799
    - arma as `_ic_df_model` that is just df_model+1, deprecate/remove

- Modernization
    - Min versions #3999 
    - Functions that are no longer used because upstream versions are available #4008
    - cythonize may now be handled upstream, need to check.
    - deprecate lower-case link classes #3462
    - replace panel with xarray #2917

- flake8 cleanup and related
   - many `if __name__ == "__main__"` blocks should be removed; some of them can be turned into tests
   - Some base class methods just `pass` instead of raising NotImplementedError or AbstractMethodError
    - Some places print instead of warn #3163
    - lots of commented out print statements
    - 1-letter variable names

- Remove
    - sandbox functions that have been replaced #3442
    - removal of deprecated objects for 0.9 #3443
    - large parts of `statsmodels.tools` and `statsmodels.stats` are never used in the "core", may belong in sandbox.  The idea being to have a clear separation between "actively-maintained, thoroughly tested" and "not that".
    - summary vs summary2: highlander style

- Other
    - MixedLinearModel setting params.fe_params inconsistently #3660
    - Can parts of miscmodels be subsumed into discrete.count_models?  #3738
    - Some types of tests return HypothesisTestResults or something, most dont
    - Functions with multiple return types/shapes (usually tuples of differing lengths)
    - sandbox functions imported by non-sandbox belong in non-sandbox
    - tools._testing vs tools.testing?
    - To make maintenance easier medium-long term, can we make some things explicitly internal so as to avoid backward-compat concerns?

**Comment by josef-pkt** [comment]
Thanks for this overview list.

It's more like a SUMMSUMM than what will be digestible in one topic week.
Several or many of the issues will need considerable time, either because of setup cost to figure out what's going on and what's supposed to be going on, or because it takes time to check and write unit tests. Some might be pretty straight forward, and some are waiting for design decisions, and some might not be possible to change/fix.

**Comment by bashtage** [comment]
Well considered list.  These clean ups will really help IMO.

**Comment by josef-pkt** [comment]
One clarification:

> large parts of statsmodels.tools and statsmodels.stats are never used in the "core", may belong in sandbox. 

Large parts of statsmodels.stats are standalone functions similar to scipy.stats and are part of the core functionality of statsmodels in their own right. 
All functions and classes in the `api` are supposed to have the basic verifying unit tests. Some functions are pretty settled, some parts are "construction zone".
Other functions are in support of models that (at least theoretically) apply to several model types.
e.g. #3954 throwing in more PRs that mainly stalled because of missing API and scope decisions. (Do we want classes that contain everything or a collection of standalone functions as in scipy.)

Also `stats` is a very heterogeneous collection of tools and functionality, and a bit of a default location if we don't find a good place to put something.

**Comment by bashtage** [comment]
One could examine test coverage when considering whether a function belongs in the main or should be demoted to sandbox.

**Comment by josef-pkt** [comment]
Or write the missing unit tests.
Given that github, in contrast to git, does not follow moving code across modules, I became reluctant to move code across files or move files. (svn/trac was still much better for digging through the history than github is.)
https://codecov.io/gh/statsmodels/statsmodels/tree/master/statsmodels/stats

**Comment by jbrockmendel** [comment]
> It's more like a SUMMSUMM than what will be digestible in one topic week. [...] Some might be pretty straight forward, and some are waiting for design decisions

Yah, looking it over again its a pretty imposing list.  My preference would be to get the low-hanging fruit (e.g. the flake8 section) by delegating review/merge responsibilities for "sufficiently obvious" fixes to Chad/Kevin/[?].  The limiting factor there is who you trust to judge "sufficiently obvious".

> Large parts of statsmodels.stats are standalone functions similar to scipy.stats and are part of the core functionality of statsmodels in their own right.

As in #4027, poor word choice on my part.  The thought was/is to identify the subset of tools+stats that is relied upon by base+tsa and the most commonly-used Model/Results classes.  This subset should be a focus for QA efforts.

**Comment by ChadFulton** [comment]
> tsa.statespace has some special handling for model.data. Life would be better if special cases were mainlined.

I don't doubt you're correct, but I can't immediately find anything that seems particularly special - can you point me to the pieces you're thinking about?

**Comment by jbrockmendel** [comment]
> can you point me to the pieces you're thinking about?

The main place is in sarimax.prepare_data:

```
            # Reset the ModelData datasets and cache
            self.data.endog, self.data.exog = (
                self.data._convert_endog_exog(endog, exog))

            # Reset indexes, if provided
            new_length = self.data.endog.shape[0]
            if self.data.row_labels is not None:
                self.data._cache['row_labels'] = (
                    self.data.row_labels[orig_length - new_length:])
```

Distant runners-up are a) setting `self.data = model.data` in `MLEResults.__init__` and b) setting `self.data.param_names = self.param_names` in a handful of places.  All pretty benign really.

Basically anything that shows up when grepping for "\.data" is something that ideally would be hidden as an implementation detail.  The fact that you have to access `self.data.orig_endog` or `self.data.dates` in a bunch of places is _completely_ harmless, but the world would be a happier place if it were unnecessary.
