### ISSUE TITLE
Use requests+requests_cache for datasets.utils?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4033]
Also noticed in some of the datasets files unix-style paths.  Do the load() funcs all work on windows?

**Comment by josef-pkt** [comment]
no idea about requests, but I guess not important enough to add another required dependency

about unix-style path names on Windows:
I never ran into problems, and Windows accepts backward and forward slashes as path separators. (However, many application programs don't.)

**Comment by jbrockmendel** [comment]
> but I guess not important enough to add another required dependency

 Yah on second thought this is a "if doing it from scratch..." suggestion, not a change suggestion.

> about unix-style path names on Windows

Neat, good to know.
