### ISSUE TITLE
remove iolib.tests.test_pickle 

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4034]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/iolib/tests/test_pickle.py

It looks like this contains one test that just pickles/unpickles `lrange(10)`... and looks platform-specific.

This file can be removed.

**Comment by josef-pkt** [comment]
It looks to me it's part of the unit test for the save load  pickle function that should be run on travis and appveyor and there are no test failures there

**Comment by jbrockmendel** [comment]
Oh, duh.  I was totally misreading what it was testing.  My bad.
