### ISSUE TITLE
test_whiteness vs test_whiteness_new

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4036]
We should resolve this before the next release, or else we'll be stuck with the status quo for a long time.

VARResults.test_whiteness is not an actual hypothesis test.  VARResults.test_whiteness_new is.  We should replace test_whiteness with test_whiteness new, not have the second name in the namespace.

**Comment by josef-pkt** [comment]
We won't be stuck with it, test_whiteness is old, test_whiteness_new is "experimental".
I'm not sure whether we need to deprecate the old function before replacing it.

**Comment by jbrockmendel** [comment]
So... can we just remove the old one and rename the new one?

**Comment by josef-pkt** [comment]
That depends on the deprecation decision, and whether the new function is a permanent solution.
i.e. we shouldn't break backwards compatibility twice in a row.

**Comment by jbrockmendel** [comment]
> i.e. we shouldn't break backwards compatibility twice in a row.

1) um... werent you just recently saying that things arent set in stone or semi-stone?  In case the metaphor was unclear, the extra inertia that comes from backward-compat concerns is what I was referring to.

2) Avoiding breaking backwards compat is the whole reason why I suggested addressing this _before_ the next release.

**Comment by jbrockmendel** [comment]
So... Get rid of the broken version yah?
