### ISSUE TITLE
test_simulate segfaults

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4040]
https://ci.appveyor.com/project/josef-pkt/statsmodels/build/1.0.2337/job/o0h557h3n21x3fn7

I thought this was resolved a while back.  Was that wrong?  Have any of our Windows-users been able to duplicate this locally?

**Comment by josef-pkt** [comment]
I'm closing this as duplicate of #3988 
It was never consistently replicated on any local machine. 
Unsolved Mysteries.
