### ISSUE TITLE
SUMM/ENH: resurrecting copulas

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4046]
(no immediate plans, but we don't have an issue, it's mentioned in just a few issues)

application to pairs trading https://www.quantopian.com/posts/statistical-arbitrage-using-gaussian-copula
(comment recommends ICA https://www.hindawi.com/journals/isrn/2013/434832 )
some background on pairs trading using cointegration or copulas  https://www.quantconnect.com/tutorials/pairs-trading-strategy/

https://statsletters.com/2016/10/19/trying-out-copula-packages-in-python-i/
https://statsletters.com/2016/11/16/trying-out-copula-packages-in-python-ii/
https://github.com/lia-statsletters/notebooks/blob/master/Copula%20packages%20continuation.ipynb
the second blog post, (ii), uses the old code in statsmodels sandbox
quote: "However as it is, is quite flexible. Is good that the developers decided to keep it anyway."
(an argument for not just deleting stale code in the sandbox)
(Note: the notebook repo has a GPL license)

There would be a long way to catch up with more recent developments which went more into vines and nested copulas (last time I checked) which are a bit more difficult to implement (efficiently).

However, it would be possible to get the basics. Either following up on the sandbox with unit tests comparing to R, or emphasis on special cases, e.g. bivariate normal and t copulas. 
(Integration code of ... is now BSD licensed, scipy has only the generic multivariate normal cdf Fortran code, but we should be able to get relatively  efficient/fast bivariate normal and t cdf.)

Of interest besides financial applications are cases with discrete or mixed continuous-discrete multivariate models.

**Comment by josef-pkt** [comment]
only partially related, but a good answer with a list of python packages for quantitative finance
https://quant.stackexchange.com/questions/34275/equivalent-to-matlabs-financial-toolbox-in-python/34278

**Comment by josef-pkt** [comment]
adding a reference because it showed up on the google search, I haven't looked at it beyond title

Irannezhad, Elnaz, Carlo G. Prato, Mark Hickman, and Afshin Shariat Mohaymany. A Copula-Based Joint Discrete-Continuous Model of Road Vehicle Type and Shipment Size. No. 17-05892. 2017.
http://docs.trb.org/prp/17-05892.pdf

**Comment by lia-statsletters** [comment]
Hi! I wrote the notebooks and came here to say: resurrecting copulas? yes please! There is also very good material in this book: "Quantitative Risk Management: Concepts, Techniques and Tools" by Alexander J. McNeil, Rüdiger Frey and Paul Embrechts, published by Princeton University Press in 2015" and in qrmtutorial.org.

**Comment by jmatthewpeters** [comment]
I'd like to help with this if I can.  I would love to have something like [https://cran.r-project.org/web/packages/copula/copula.pdf]( R copula Package ) [https://datascienceplus.com/modelling-dependence-with-copulas/]  I'm trying to replicate a project that was written in R that uses that package and while I think what is here is good enough, I'd be willing to help out if I can (I haven't built many python libraries).

**Comment by josef-pkt** [comment]
It would be great if you (and anyone else) would move this forward.

One of the first things that would be needed are unit tests against R to check that those functions are correct. Also a rough roadmap for missing pieces would be useful to see what is needed to make this useful. When I wrote this I mainly focused on pdf and cdf, and the general setup for Archimedean and extreme value copulas. I guess adding fit (and rvs ?) would be important.
Then it would be easier to incrementally add more features.

I just looked for a while through my old (2011) folders to see what else I did. I have one more commit in my local repo that is not in the statsmodels sandbox. I don't find any additional example scripts or code that I might have written.
(I have 500 pdf files with copula in the name in my old folders, but it looks like I did more reading articles than writing code. )

**Comment by josef-pkt** [comment]
A general warning:
We are not allowed to translate code that is released under GPL or any other license that is not BSD compatible, unless we have explicit permission to do so.

**Comment by jmatthewpeters** [comment]
Ok, I will need some guidance on how you want the tests to look, if there is some standards already for statsmodels I can look them up or if you want to point me to them.  I can't imagine just translating anything, I don't really like the structure for the R code.  I like the approach so some of the more complicated functions, but they used mathematica to derive some of the functions and I can use sympy for it. I can't guarantee how fast I can get stuff done but at least I can work on it.

**Comment by josef-pkt** [comment]
(I found a file where I had used sympy to try out obtaining derivatives for some copula functions. Mathematica online is also pretty good.)

for unit tests
background reading is the numpy testing guidelines which is roughly followed by most packages in this area, although there are idiosyncratic differences, e.g. we have many classes
https://github.com/numpy/numpy/blob/master/doc/TESTS.rst.txt

for many unit test we use test classes when we need to check many different attributes or results.
However, the simplest cases are just hardcoding the corresponding number from R and compare them to the statsmodels function with `assert_allclose` from numpy testing.
e.g. https://github.com/statsmodels/statsmodels/blob/master/statsmodels/stats/tests/test_proportion.py#L500

For example for the current copula code you could get the pdf and cdf at several values from R.
If there are many cases and it gets repetitive, then storing the results separately and using a loop or parameterized test will reduce copy-paste tasks. (e.g. in Stata and R I use export scripts if there are too many cases to do it by hand.)

**Comment by josef-pkt** [comment]
I added the commit that I found with the example for some of the Archimedean copulas
#5076

It adds the derivatives to the archimedean copula transform classes, but I don't remember why we need them.

**Comment by josef-pkt** [comment]
I checked that the basic things in `copula` are working, but didn't verify by comparing to other packages.
I merged the extra commit in #5076, and added some comments on my interpretation of the copula code.

I need to go back to other projects, but I can spend more time on this if there are questions or if I need to help with implementing parts of it.

**Comment by jmatthewpeters** [comment]
Thank you. I'm slowly getting up to speed on some of its and will work on some tests and comparisons to R.  I'm just going to need some time to figure out how to replicate the test cases in R and then translate that to here.

**Comment by josef-pkt** [comment]
adding a link (I didn't read the details)
random sample of t-copula
https://stackoverflow.com/questions/51536478/simulation-of-t-copula-in-python/53491296

**Comment by tupui** [comment]
@josef-pkt As discussed over at scipy, I propose to add an interface to construct joint distributions. We would have 2 cases: *(i)* marginals are independents; *(ii)* there is a dependency. The dependency can be modelled using the copula in statsmodels. So I propose something in that direction:

```python
import numpy as np


class JointDistribution:
    def __init__(self, dists, copula=None, seed=None):
        self.rng = np.random.default_rng(seed)
        self.dists = dists
        self.copula = copula
        self.d = len(self.dists)

    def random(self, n):
        if self.copula is None:
           # this means marginals are independents
            sample = self.rng.random((n, self.d))
        else:
            sample = self.copula.random(n)  # sample the copula
    
        for i, dist in enumerate(dists):
            sample[:, i] = dist.ppf(0.5 + (1 - 1e-10) * (sample[:, i] - 0.5))
        return sample
```

**Comment by josef-pkt** [comment]
I don't remember much about how the copulas work in the implementation. Also I don't find my references anymore.

I'm looking at the R package (for the first time, AFAIR) and it seems to have similar structure, with separate elements for transformation, copula and copula base distribution including marginals.
https://cran.r-project.org/web/packages/copula/copula.pdf

It looks like I never wrote pdf and rvs methods for copula mv distributions.

One point to your JointDistribution: it's better not to mix independence and different types of distributions. It's better to create separate classes, e.g. IndependenceCopula, instead of using branching inside the functions.

Related: I have been working on another resurrect and extend part of sandbox distributions, generating new univariate classes of distributions through nonlinear transformation.
I got stuck a bit in conflicting parameterization across references and across differently named distributions that are just reparameterizations of each other. I don't have a clean generic distribution class yet, but generating random variables is trivial once the `transform`s are implemented.

If you need mainly `rvs` for copula based multivariate distributions, then (AFAIR), they can be implemented much more easily than the rest of the copula methods.

Writing unit tests for the specific copula transforms in the sandbox might be relatively easy, if, as it looks like, R copula package allows access to the individual parts that make up a mv Copula distribution.

**Comment by tupui** [comment]
If we just want to be able to use the copula for this transformation purpose, then yes only `rvs` would be needed. From https://github.com/blent-ai/pycopula it seems fairly simple to add the basics copula. I did not check the correctness of the math, but here is what I wrote based on this package:

```python
class GaussianCopula:
    def __init__(self, mean=None, cov=1):
        self.density = stats.norm()
        self.mv_density = stats.multivariate_normal(mean=mean, cov=cov)

    def random(self, n):
        x = self.mv_density.rvs(size=n)
        return self.density.cdf(x)


class GumbelCopula:
    def __init__(self, theta=2):
        self.theta = theta

    def random(self, n):
        u = np.random.random((n, 2))
        v = stats.levy_stable.rvs(1./self.theta, 1., 0,
                                  np.cos(np.pi / (2 * self.theta))**self.theta,
                                  size=(n, 1))        
        return np.exp(-(-np.log(u) / v)**(1. / self.theta))
```

**Comment by josef-pkt** [comment]
Note, pycopula is not license compatible, it's GPL, LGPL

Another question, based on another question of your on scipy issues: 
Do you want support for halton sequences and quasi-random numbers? 
We should be able to get for at least some of the copulas the bivariate or multivariate inverse transform, i.e. from multivariate uncorrelated, independent uniform to copula dependent random variables with uniform margins.

I looked a bit through some literature yesterday. There is too much that I don't know or don't remember to fill in the major gaps in the current code. Without a lot more work, we will only get partial support for some copulas.
e.g. multivariate t copula random variables are easy even for multivariate, all other methods are difficult.
Some copulas will not get rvs without numerical function inversion at each point and will be slow using generic support if we get that.

**Comment by tupui** [comment]
> Note, pycopula is not license compatible, it's GPL, LGPL

Indeed. Either way I would not have copy anything from here, but just looking at how things are done as an example.

> Another question, based on another question of your on scipy issues:
> Do you want support for halton sequences and quasi-random numbers?

If possible yes. I would like to allow to give a random uniform sampling. This way the user can user existing samplings.

> We should be able to get for at least some of the copulas the bivariate or multivariate inverse transform, i.e. from multivariate uncorrelated, independent uniform to copula dependent random variables with uniform margins.
> I looked a bit through some literature yesterday. There is too much that I don't know or don't remember to fill in the major gaps in the current code. Without a lot more work, we will only get partial support for some copulas.
> e.g. multivariate t copula random variables are easy even for multivariate, all other methods are difficult.
> Some copulas will not get rvs without numerical function inversion at each point and will be slow using generic support if we get that.

Do you think we/I could do a PR and provide a skeleton with just a few copula (something like: independant, gaussian, multivariate t, gumbel)? Then we could call for help/contributions from devs of the other copula packages. They could be interested in having copula in a stable package like statsmodels. I am not a specialist on copula at all, but I think I could ping some people to give a hand if we start this.

**Comment by josef-pkt** [comment]
I think we can provide unit tested pieces but without full copula support, i.e. have missing methods that raise NotImplementedError.

For example if the current transformation and skeleton classes have unit tests, then they can move out of the sandbox.

Similarly, in #7246 (univariate transformation of random variables) I'm planning to provide mainly the transformation, which can easily be used for rvs generation. Some parameter handling is unclear, especially because I subclass scipy distributions, and clearing that up has to wait until I figure out regression models using those tranformed distributions.

**Comment by josef-pkt** [comment]
aside: it looks like pdf for gaussian and t-copula only needs univariate ppf, at least in the bivariate copula case
https://en.wikipedia.org/wiki/Copula_(probability_theory)#List_of_copula_density_functions_and_applications

Archimedean density needs first and second derivative (or second derivative of inverse function) to compute density, assuming generator is twice differentiable and density does not have singular points (absolutely continuous wrt. Lebesque measure)
see Nelson p. 128 equ (4.3.6)
in general under differentiability: density is second cross derivative in bivariate case.
(I'm shaky with theory for those parts, I don't remember having worked with derivatives in multivariate distributions. How do we get conditional density f(u | v) ? )

**Comment by tupui** [comment]
> I think we can provide unit tested pieces but without full copula support, i.e. have missing methods that raise NotImplementedError.
> 

Ok great so I propose to start a PR with what I have and we can move from there. I will give you commit rights to make it easier.

**Comment by tupui** [comment]
Here is a nice ressource with expressions of inverse transforms: https://www.uni-ulm.de/fileadmin/website_uni_ulm/mawi2/dokumente/preprint-server/2007/0710_preprintmariushofert.pdf

I need to clean a bit what I have but I will push a draft PR tmr.

**Comment by tupui** [comment]
@josef-pkt I created a draft PR. I put most common copula here (Frank, Clayton, Gumbel, Gaussian, Student). I just added a `random` method for now as my goal was to use it for sampling. There might be other functions defined in `sandbox.distributions.copula` that could be integrated. I let you be the judge here 😉

**Comment by josef-pkt** [comment]
to extreme value copulas: I needed to read around a bit to remember how this goes

overview article I had used is https://arxiv.org/abs/0911.1015  now published as a book chapter
formulas are from Genest 2009, but hidden in section 4, article is mainly about other theoretical results

reading up some more in various book chapters

my implementation is based on Pickand's dependence function (my EV `transforms`)
alternative construction or characterization is by tail dependence function

Beirlant et al. Statistics of Extremes book has many pieces but from the focus of extreme value theory, copulas are spread across chapters
another book (?) has a good list of ev copulas in appendix, but based on tail dependence function, not Pickands dependence fn
(now my acrobat reader is frozen)

**Comment by tupui** [comment]
Ok so you mean we should add some other copula for extreme value?

As for the pdf and cdf (if we say it's really needed), there is some work in https://github.com/sdv-dev/Copulas/blob/master/copulas (MIT). We could take this as a base, what do you think? I will try to do this for some copulas when I have some time.

**Comment by josef-pkt** [comment]
I have been trying the last few days to get an overview again.

I think we need some generic classes like CopulaArchimedean and something for extreme value copulas, currently only a function copula_bv_ev, and then some specific classes that implement copula specific attributes and methods.

For some methods and properties we need restrictions on the copula like differentiability for pdf, "strictness" (I don't remember definition) to only have a continuous and no singular component(*1), and monotonicity restrictions to extend bivariate to multivariate copulas (*2).

(*1) AFAIR, TransfClayton checkargs restriction is for "strict" case, non-strict case is not included.
(*2) current archimedean transform include `is_completly_monotonic` but I don't remember where I got that from.

copula families

- elliptical: 
  - multivariate gaussian and t copulas, only pdf/logpdf and `rvs` at beginning
  - bivariate, maybe add numerical integration
  - currently no other elliptical families
  - extras: kendall's tau and spearman's rho, bivariate or multivariate ?
- Archimedean
  - already has pdf generically
  - need extra methods like kendalls tau, generic requires numerical integration, explicit in some cases
 - Extreme Value copulas
   - construction through Pickands dependence function
   - pdf/logpdf might need to be copula specific, I don't remember having seen a formula based on Pickands dep function
   - other properties, e.g. tail dependence as function of Pickands dependence, kendall's tau, ... ?

To check random number generation it would be good to have some gof tests, statsmodels doesn't have general multivariate gof tests (including cases where we don't have the bivariate cdf available). 
Some statistics like kendall's tau can also be compared between simulated data and theoretical copula property.

other supporting code: some plotting functions would be nice, e.g. I don't remember how to do 2-dim contour plots.

**Comment by josef-pkt** [comment]
I want to move the `transfroms` into a separate module `transforms_copula`

archimedean transforms, Pickands dependence functions are monotonic, but decreasing, and mostly follow "Transforms" pattern. (I used now `transform` as method name in univariate transforms instead of `evaluate`, Links only have `__call__`. I like `transform` better now. )
EV transforms are currently only functions. I don't remember having sees a use of derivatives.

Aside: 
copulas (?), or archimedean copulas, can be transformed, i.e. we can add an extra transform layer
e.g. `copula_power_mv_archimedean` adds a hard coded power transform to an archimedean copula
AFAICS, we could merge this into a chained `transform`, i.e. transformed Pickands dependence function

**Comment by tupui** [comment]
Ok, this seems like a huge task. TBH I don't know much about all these and would for sure make mistakes without noticing it. Still, I can continue the work I started on the architecture side.

From what you wrote, I can create 3 classes: `ArchimedianCopula`, `EllipticalCopula` and `ExtremeCopula`. But should they inherit from a base `Copula`? Or this would replace what I did? Let me know about the architecture you have in mind and I will map it. In the meantime I will add the `pdf`, `cdf` to the classes I made.

**Comment by josef-pkt** [comment]
clayton looks wrong compared to R copula package, the transform might be inverted, or something

(for univariate transforms, I wrote unit test functions for internal consistency, including derivatives)

**Comment by tupui** [comment]
> clayton looks wrong compared to R copula package, the transform might be inverted, or something
> 
> (for univariate transforms, I wrote unit test functions for internal consistency, including derivatives)
> 
> gumbel agrees for both copula cdf and pdf
> 
> ```
> cg = CopulaArchimedean(cop.TransfGumbel())
> cg.cdf([0.5, 0.5], args=(2,)), cg.pdf([0.5, 0.5], args=(2,))
> ```
> 
> Frank agrees for cdf, but not for pdf

Are you talking about what I coded in `statsmodels.distributions.joint_distribution`? Or about what's in `sandbox`?

I added the `pdf` (`logpdf`), `cdf` for all the copulas. Just not sure about `Gaussian` and `Student`, I have to check this.

**Comment by tupui** [comment]
What do you mean by it agrees? If I do the same thing with the new code I have:

```python
import numpy as np
from statsmodels.distributions.joint_distribution import GumbelCopula, FrankCopula, ClaytonCopula

cg = GumbelCopula(2)
cg.pdf(np.array([[0.5, 0.5]])), cg.cdf(np.array([[0.5, 0.5]]))
 (array([5.6030066]), array([2.66514414]))

cf = FrankCopula(2)
cf.pdf(np.array([[0.5, 0.5]])), cg.cdf(np.array([[0.5, 0.5]]))
 (array([1.08197671]), array([2.66514414]))

 cc = ClaytonCopula(2)
 cc.pdf(np.array([[0.5, 0.5]])), cg.cdf(np.array([[0.5, 0.5]]))
 (array([1.48100365]), array([2.66514414]))
```

**Comment by josef-pkt** [comment]
I'm trying to verify the generator code and generic copulas in the sandbox. 
There are at least some bugs in transform or derivatives.

hussler reiss agrees with R
cop.copula_bv_ev(0.5, 0.9, cop.transform_hr, args=(0.5,))

`tawn` in R and my 2 versions might represent different copulas, my versions seem to have more parameters.
I don't see much description of EV copulas in the R docs.

I don't see whether my `joe` EV copula is in R copula.

**Comment by tupui** [comment]
Ah ok 👍 . Let me know if I should copy the generator code then. Shall I also add a fit method to compute theta using `stats.kendalltau`?? I've seen that in `copulas`.

**Comment by josef-pkt** [comment]
We need a collection of formulas, a method in the copulas to get the theoretical tau implied by the copula, and spearman rho were available. A few copulas might have invertible functions for tau to estimate theta from the empirical kendalltau.

**Comment by tupui** [comment]
> We need a collection of formulas, a method in the copulas to get the theoretical tau implied by the copula, and spearman rho were available. A few copulas might have invertible functions for tau to estimate theta from the empirical kendalltau.

Ok but the more we add things like this, the more we actually copy `copulas`. They have a `fit` function to get `theta` from an empirical sample using tau. I can copy/adapt this over.

**Comment by josef-pkt** [comment]
the extreme value package in R `evd` has a list of bivariate EV copulas,
Their copula names are mostly not based on authors of copulas, so maybe we can pick something like those.

**Comment by josef-pkt** [comment]
possible idea: we should have a uniform on [0,1] ot linear cdf distribution so we can have a Copula is a special case of CopulaDistribution with uniform margins.

**Comment by josef-pkt** [comment]
I just found a bug in tawn/alog dependence function copied from a typo in the article :(
Genest, Segers section 4.3 case (b) mixes up and interchanges two of the indices for asymmetry parameters psi_1, psi_2.
(The formula doesn't look symmetric in pattern, )

after fixing it transform_tawn has return limited to interval [0, 1] and matches R evd also in the asymmetric case.

**Comment by josef-pkt** [comment]
another messy detail

clayton in `copula` package is ψ(t) = (1 + t)**(−1/θ) in docstring for `copFamilies`
which differs from Nelson. I have a missing division by theta in the sandbox version.

However, Hofert's article on sampling nested copulas uses phi for the inverse generator, like Joe, but opposite of Nelsen.

`copFamilies` doesn't specify what phi is. or how copula relates to phi

Fun, Fun, Fun :(

This means, when copying formulas from some article or book, we better check which direction phi or phi_inverse goes.

**Comment by tupui** [comment]
Mmm sounds like trouble to check the correctness...

But what is the actual need? What people (what are we expecting) are actually going to do? Because we might not need to implement all this if in the end nobody is using this it. Genuinely asking the question, I have no clue.

**Comment by josef-pkt** [comment]
I'm a big fan of **generic** code.
That makes it much easier to extend and to add new cases than if we hardcode hundreds of special cases from scratch each time.

example GLM: any new method added to GLM works immediately with a large number of models. Adding methods to `discrete` models that hard code most parts, requires adjustments to special cases, or rewriting the hardcoded parts in a more reusable way.

Nelsen textbook lists 22 Archimedean copula generators. 
In the best case, you add a new generator transformation class and you have full support for the corresponding copula and copula distribution.
Only a few copulas are interesting and commonly used enough to spend the effort of hardcoding pieces (which will often also improve performance)

**Comment by josef-pkt** [comment]
two more

https://github.com/DanielBok/copulae  includes some other parts like empirical copula (with beta pdf)

https://github.com/vinecopulib/pyvinecopulib  python based on c++ code (has also wrappers to other languages)

**Comment by tupui** [comment]
I used the first ressource to start with my initial implementation. But in the end I found the book of Joe2015 to have everything.

**Comment by josef-pkt** [comment]
R package `copBasic` has a nice list of helper functions, empirical copulas and other copula function like transformation, survival function, survival copula, ...

documentation looks very good and includes relevant formulas and inline references 
https://cran.r-project.org/web/packages/copBasic/index.html

**Comment by tupui** [comment]
Sure but you're walking along copyright infringement as the package is under GPL2...

**Comment by josef-pkt** [comment]
We can use documentation and unit tests. We don't look at the code. (same for most R packages, but most don't have good docstrings for the details.)

Some things I saw just, makes the definitions clearer and we can write unit tests.
e.g. survival function, survival copula, co-copula
simple, slightly confusing definitions, where I feel more comfortable if I have a package to write unit tests against.

similar, copBasic has 3 power transformation of copulas, copula package also has some copula transformations.
(useful to transform symmetric/exchangable copulas into asymmetric copulas)

**Comment by tupui** [comment]
We can use and compare our values to the output, but the documentation is also licensed. Most people don't bother to use a proper licensing for their doc and just license the whole thing with the same license, but still. If having a look at a licensed code to figure something out and code yourself the solution is not ok, then the same apply for the doc if covered under the same terms.

**Comment by josef-pkt** [comment]
No, we can read documentation without problems. Copyright for documentation means we cannot copy the documentation itself. (e.g. We can read scientific articles and use them, but we cannot plagiarize them.)

It does not affect writing code after reading the documentation, otherwise we would never be allowed to look at documentation of proprietary packages like Matlab, SAS, SPSS, Stata and ...

**Comment by tupui** [comment]
Well nobody will come here to annoy us... So just for the sack of the discussion. But if the documentation is licensed under GPL's terms, it's GPL. There are other license which are more appropriate to properly distribute doc, and almost no package have a separate license for the doc. What is commonly done by people is another story I am afraid. As for the articles, here as well it's the far west as nobody really reads the copyright of any paper which is different from one journal to the other.

**Comment by josef-pkt** [comment]
But facts and definitions cannot be copyrighted. Whatever copyright is assigned, doesn't matter.
e.g. random google find: copyrightability of short phrases https://fairuse.stanford.edu/2003/09/09/copyright_protection_for_short/

for example from copBasic surfuncCOP docstring:
```
Compute the joint survival function for a copula (Nelsen, 2006, p. 33), which is defined as
C_bar(u; v) = Pr[U > u; V > v] = 1 - ...
```

Nothing original, copyrightable in there.

**Comment by ChadFulton** [comment]
> But facts and definitions cannot be copyrighted. 

Another good example of this is recipes for food. Anyone is free to publish their own cookbook with a collection of any recipes.

This is also one of the reasons why companies maintain trade secrets - the fundamental elements of many trade secrets (e.g. algorithms, these days) often can't be copyrighted.

**Comment by tupui** [comment]
See this for the recipe, not that simple 😉: https://www.copyright.gov/circs/circ33.pdf As always, this is a question of understanding and subjective to the appreciation of the judge. But I just wanted to ensure you saw this R library was under GPL and hence it should be dealt with care.

**Comment by tupui** [comment]
> See this for the recipe, not that simple 😉: https://www.copyright.gov/circs/circ33.pdf As always, this is a question of understanding and subjective to the appreciation of the judge. Also remember that copyright laws are different from one country to another.

But I just wanted to ensure you saw this R library was under GPL and hence it should be dealt with care.

**Comment by bashtage** [comment]
In the US at least, the Google vs Oracle made it pretty clear that API documentation is not copyrighted.  So if one wanted to write a work-alike package, that would probably be OK under current US case law.

**Comment by tupui** [comment]
> In the US at least, the Google vs Oracle made it pretty clear that API documentation is not copyrighted. So if one wanted to write a work-alike package, that would probably be OK under current US case law.

Sure sure, but here we are not talking about naming things the same. But read the doc or have a look at some other work to figure out how it works and how we can replicate. Which is quite different.

**Comment by josef-pkt** [comment]
That's the same as in the recipe case in your linked pdf.

The original, artistic presentation of a recipe can be copyrighted, but not the ingredients and procedure to replicate the dish. 

Also, except for a few computational hints, e.g. for corner cases, nothing in the documentation of packages like copula, copBasic is original methods. If there were a copyright on methods/procedures/definitions, then it would be copyright be the original authors. However, that (methods, definitions, theorems, ...) is not copyrightable because it would kill science.

**Comment by josef-pkt** [comment]
closing

we still have updated open issues
general:
#8635 missing parts and extensions
#7258 some notes and references
and other issues for specific extensions
