### ISSUE TITLE
test build/matrix

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4080]
Noticed two things when looking at Travis:

1) We're testing against pandas as old as 0.14.x, which was released end of 2014.  They're about to release 0.21.0.  It might be time to bump the version there.

2) cython build takes about 4 minutes which looks like about 20% of the runtime.  Since the cython code is rarely changed, maybe there is a way to cache the build artifacts?

**Comment by bashtage** [comment]
1. I fully support radically updating the dependencies.  With the exception of Python 2.7, I think NumPy/SciPy/Pandas that is > 2 years old should not be explicitly supported.   For example, requiring SciPy >= 0.16 simplifies the statespace code. 

2. I don't think Travis test time is just a problem.  One could just as easily shave as much time by skipping a small minority of tests on most of the platforms.   This said, it is a free to do in a repeatable manner, why now.  It is adds a lot of complexity for 4 minutes, I'd think profiling tests (pytest --durations=50 statsmodels), adding @slow to the worst offenders, and adding --skip-slow to most of the runs would be much easier.

**Comment by josef-pkt** [comment]
My impression is that test times are slow when conda connection is slow and because of pytest, not inherently to our unit tests.
Last time I checked when we had slow test runs, then a large amount of time was spent even before any tests were actually run.

**Comment by bashtage** [comment]
conda definitely can make things slow, although when the main conda server is up it is fast since Travis uses caching. 

pytest takes 25s on my computer from being called until the first test is run, so this isn't a major source of the test time.  The rewritten AST is generated during this step, so it isn't especially costly to produce. 

> Last time I checked when we had slow test runs, then a large amount of time was spent even before any tests were actually run.

IIRC this was because nose was calling classes and there were some slow setup methods that were being repeatedly invoked. This is gone now.

**Comment by jbrockmendel** [comment]
I've been looking through the tests trying to sort out smoke-like tests from solid-seeming ones, I'm seeing a lot of `fit` and `fit_regularized` calls `setup_class` methods.  A whole bunch of these seem to be repeated fittings of the same handful of models.  My impression is that pytest fixtures may be able to make some of these more re-usable.
