### ISSUE TITLE
tsatools.add_trend ptp mismatch?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4084]
Maybe I need more caffeine, but [this](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/tsatools.py#L100) looks off:

```
            col_const = np.logical_and(np.any(np.ptp(np.asanyarray(x), axis=0) == 0, axis=0),
                                       np.all(x != 0.0, axis=0))
```

The second condition here `np.all(x!= 0, axis=0)` looks like it should be `not np.all(x == 0, axis=0)`, at least if the goal is to match the logic in the case just above this line.

**Comment by josef-pkt** [comment]
they all have to be non-zero and constant, so looks fine to me
`np.any(x != 0.0, axis=0)` would work also in combination with the first condition and stop early, if any are non-zero

but to me it looks like this doesn't make sense, the first any should be outside., ptp already is a reduce operation.

**Comment by jbrockmendel** [comment]
Yep, duh, thanks.

> and stop early, if any are non-zero

It'd be slightly more efficient, and would match the case ~4 lines above.  But not worth clogging up the PR queue.

**Comment by josef-pkt** [comment]
I think there is a bug in the line you copied, needs checking.
