### ISSUE TITLE
KeyError?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4110]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tools/decorators.py#L103

```
            try:
                _cache[name] = _cachedval
            except KeyError:
                setattr(_cache, name, _cachedval)
```

What's the scenario in which a KeyError is raised here?

**Comment by jbrockmendel** [comment]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tools/decorators.py#L127

**Comment by josef-pkt** [comment]
I'm not sure. I never reviewed that code in all details, just that it works as advertised.
