### ISSUE TITLE
tools.decorators.OneTimeProperty

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4111]
Seems like a near-duplicate of cache_readonly, and is pretty darn neglected.  Its only use is in stats.weightstats, and there is a duplicate definition in sandbox.archive.linalg_decomp_1.

This class should be removed.

**Comment by josef-pkt** [comment]
Needs more investigation given that it is heavily used in weightstats.
I thought this was too magic, IIRC, and I don't remember why I used in in weightstats. If it hasn't caused problems in weightstats all this years, then maybe it is not so fragile after all. (But DescrStatsW is a simple class and not tied into any class hierarchy in contrast to the models.)
