### ISSUE TITLE
Use ANOVA to test treatment effect in longitudinal measurement

### ISSUE THREAD

**Issue by TheChymera** [statsmodels/statsmodels#4123]
I have some measurements with a rather comprehensive design - 5 measurement time points (first one is baseline, and the subsequent ones various treatment phases). I would like to get a p-value giving the probability of observing at least as strong a discrepancy between the treatment and control groups in the treatment time points if there was no treatment effect.

I know, it already sounds a bit like a mouthful. But what I am particularly uncertain about is whether this can be adequately expressed in an ANOVA `fit.f_test()` contrast.

I have put the code (also shown below) together with some data in a self-contained minimal example, [**here**](http://chymera.eu/debug/statsmodels/anova_treatment_session_effect.tar.gz).

Now, what I am trying to do here is jointly testing:

* that there is some sort of effect for the sessionXtreatment group interaction on the session variable values corresponding to the treatment phases and the treatment variable value corresponding to the treatment group,
* that there is no net effect of control group treatment effect and the treatmentXsession interaction on the session variable values corresponding to the treatment phases and the treatment variable value corresponding to the control group.

I do this via the following code:

```
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

subjectdf = pd.read_csv('data.csv')

model = smf.mixedlm("t ~ Session * treatment", subjectdf, groups=subjectdf["subject"])
fit = model.fit()
report = fit.summary()

print(fit.params)
print(report)

omnibus_tests = np.eye(len(fit.params))[1:-1]
omnibus_tests = np.delete(omnibus_tests, (4), axis=0)
omnibus_tests = omnibus_tests[:5]
omnibus_tests[4,5] = 1
omnibus_tests[4,6] = -0.25
omnibus_tests[4,7] = -0.25
omnibus_tests[4,8] = -0.25
omnibus_tests[4,9] = -0.25
print(omnibus_tests)

anova = fit.f_test(omnibus_tests)
print(anova)
```

which gives me the following output:

```
Intercept                                 6.055918
Session[T.ofMaF]                          9.379469
Session[T.ofMcF1]                         6.168209
Session[T.ofMcF2]                         3.861367
Session[T.ofMpF]                         -2.804001
treatment[T.Vehicle]                     -0.445232
Session[T.ofMaF]:treatment[T.Vehicle]    -9.398200
Session[T.ofMcF1]:treatment[T.Vehicle]   -7.415294
Session[T.ofMcF2]:treatment[T.Vehicle]   -6.436954
Session[T.ofMpF]:treatment[T.Vehicle]     0.134415
Group Var                                 0.222033
dtype: float64
                      Mixed Linear Model Regression Results
==================================================================================
Model:                      MixedLM          Dependent Variable:          t       
No. Observations:           36               Method:                      REML    
No. Groups:                 9                Scale:                       6.7142  
Min. group size:            2                Likelihood:                  -69.8972
Max. group size:            5                Converged:                   Yes     
Mean group size:            4.0                                                   
----------------------------------------------------------------------------------
                                       Coef.  Std.Err.   z    P>|z|  [0.025 0.975]
----------------------------------------------------------------------------------
Intercept                               6.056    1.432  4.228 0.000   3.249  8.863
Session[T.ofMaF]                        9.379    2.364  3.968 0.000   4.746 14.013
Session[T.ofMcF1]                       6.168    2.008  3.071 0.002   2.232 10.105
Session[T.ofMcF2]                       3.861    1.832  2.107 0.035   0.270  7.452
Session[T.ofMpF]                       -2.804    2.008 -1.396 0.163  -6.740  1.132
treatment[T.Vehicle]                   -0.445    2.019 -0.221 0.825  -4.402  3.512
Session[T.ofMaF]:treatment[T.Vehicle]  -9.398    3.316 -2.834 0.005 -15.897 -2.899
Session[T.ofMcF1]:treatment[T.Vehicle] -7.415    2.662 -2.786 0.005 -12.632 -2.198
Session[T.ofMcF2]:treatment[T.Vehicle] -6.437    2.535 -2.539 0.011 -11.406 -1.468
Session[T.ofMpF]:treatment[T.Vehicle]   0.134    2.738  0.049 0.961  -5.233  5.502
Group Var                               1.491    0.753                            
==================================================================================

[[ 0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    1.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    1.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    1.   -0.25 -0.25 -0.25 -0.25  0.  ]]
<F test: F=array([[ 7.23833912]]), p=0.00023083260820329446, df_denom=26, df_num=5>
```

Or should I rather be testing something like:

```
[[ 0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    1.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    1.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.    0.   -1.    0.    0.    0.    0.  ]
 [ 0.    0.    1.    0.    0.    0.    0.   -1.    0.    0.    0.  ]
 [ 0.    0.    0.    1.    0.    0.    0.    0.   -1.    0.    0.  ]
 [ 0.    0.    0.    0.    1.    0.    0.    0.    0.   -1.    0.  ]]
```
?

But ideally I would also want to test, that there is no mean effect of `treatment[T.Vehicle]`.

**Comment by kshedden** [comment]
If I understand this (not sure I do), there must be an omitted reference category for the Session variable (i.e. Session is a categorical variable with 5 levels).  Your first contrast matrix specifies that all the session effects are equal to each other in the treatment (non-vehicle) group.  In the control (vehicle) group, the average of effects for the 4 non-omitted session categories is equal to the effect for the omitted session category.

Your second contrast matrix is equivalent to just setting parameters 1-9 (counting from 0) to zero, since, only the row space of the contrast matrix matters, and this matrix can be row-reduced to the identity, padded with two extra columns of zeros (one on the left, one on the right).  I don't think that is what you want.

I don't think we have tested MixedLM with F-tests, although it might work in this case.  The test will be carried out using an internal reparameterization of the model, which is not the parameterization used to specify the model.  However the fixed effects part is the same, so again it might be OK here.

Also, there is a lot of literature on setting degrees of freedom for F-tests with mixed models.  We are not doing anything fancy here, just counting parameters.

**Comment by TheChymera** [comment]
> If I understand this (not sure I do), there must be an omitted reference category for the Session variable (i.e. Session is a categorical variable with 5 levels).

I'm not sure this is what's happening here (and therefore that the rest of your reply addresses this issue correctly). As far as I understand, the first level of the variable ends up corresponding to the intercept, and the way to specify an ANOVA test (whether there is any effect along the levels of one variable) is defining an F-test where all of the non-intercept (so in this case 4) levels get their own contrast where each of them is set to one. I am getting this from a past discussion [here](https://github.com/statsmodels/statsmodels/issues/3262#issuecomment-258755887) as well as from the [FEAT guide](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FEAT/UserGuide#ANOVA:_1-factor_4-levels). This would actually be the very opposite of modelling a scenario where:

> the average of effects for the 4 non-omitted session categories is equal to the effect for the omitted session category.

Or are we just confusing H0 and H1? It seems to me like your statement is exactly what I am looking to reject.

Well, almost exactly, that is. I am also looking to test that this is also not happening in the control group. But I'm still not sure how this is best included in the F-contrast.

**Comment by josef-pkt** [comment]
I'm also not sure I fully understand

However, your two objectives in `Now, what I am trying to do here is jointly testing` seem to me to go in opposite direction. 
We only have point null hypothesis available, that is H0 is either there is no effect or there is an affect equal to specified values.

Given a null of no effect, you would like to reject in the first bullet point (there is some effect), but you want to not reject in the second bullet point (there is no significant effect).
I don't think you can jointly test two hypothesis that go in opposite directions.

Your second constraint matrix, AFAIU: 
The first part is that there is no session effect in the control group, the second part is that there is no (vehicle) treatment effect in any of the sessions.
So AFAIU you would like to not reject the first part, but reject the second part.
Instead if the null hypothesis is rejected, then it can be either because there is a session effect also in the control group or because there is a vehicle treatment effect in at least one of the sessions.
My guess would be that you want to split it and not reject the first part and reject the second.

**Comment by TheChymera** [comment]
Hmmmm, I don't see how the null hypothesis contradicts itself. Basically I would like to get a contrast for the treatmentXsession effect on the substance level of the treatment variable - but of course that would become less meaningful the more of a treatmentXsession effect could be seen on the vehicle level of the treatment variable.

There has to be some way to control for this on the level of the contrast. There's a lot of valuable information in having a control group, but I feel it's not evaluated if my F-contrast is just:

```
[[ 0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    1.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    1.    0.    0.    0.    0.    0.    0.  ]]
```

**Comment by josef-pkt** [comment]
@kshedden 

> Your second contrast matrix is equivalent to just setting parameters 1-9 (counting from 0) to zero,, since, only the row space of the contrast matrix matters, and this matrix can be row-reduced to the identity

Is there a way to do this automatically and write a helper function to "simplify" or reduce a contrast matrix?
In the specific case, the 5th column has only zeros, so I think the main effect, treatment[T.Vehicle], is left unrestricted.

**Comment by josef-pkt** [comment]
@TheChymera 

AFAIU Kerby's reduction in the contrast matrix your second contrast in the initial comment is that there is no session effect. The equivalent contrast with identity and some dropped rows sets every parameter that includes `session` to zero.

I didn't say the contrast in the two parts of the second contrast matrix contradict each other. I was thinking that this is not what you want given that you would like the null hypothesis to go in opposite directions in the two parts.

This contrast matrix encodes the null hypothesis that there is no session effect in the non-vehicle reference group, (without restricting the session effect in the vehicle group.)
AFAIU, you would prefer not to reject this null
```
[[ 0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    1.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    1.    0.    0.    0.    0.    0.    0.  ]]
```

The null hypothesis for the following contrast is that the treatment effect of vehicles compared to the reference group is zero in all session. But given that it leaves the main effect of treatment[T.Vehicle]  unrestricted. the null hypothesis is equivalent to that there is no session effect in the vehicle group.
AFAIU, you would prefer to reject this null, and conclude that the treatment effect is not constant across sessions
```
[[ 0.    1.    0.    0.    0.    0.   -1.    0.    0.    0.    0.  ]
 [ 0.    0.    1.    0.    0.    0.    0.   -1.    0.    0.    0.  ]
 [ 0.    0.    0.    1.    0.    0.    0.    0.   -1.    0.    0.  ]
 [ 0.    0.    0.    0.    1.    0.    0.    0.    0.   -1.    0.  ]]
```

Adding the main effect restriction, the null hypothesis would be that there is no vehicle treatment effect at all, (leaving the session pattern unrestricted). 
```
[[ 0.    0.    0.    0.    0.    1.    0.    0.    0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.    0.   -1.    0.    0.    0.    0.  ]
 [ 0.    0.    1.    0.    0.    0.    0.   -1.    0.    0.    0.  ]
 [ 0.    0.    0.    1.    0.    0.    0.    0.   -1.    0.    0.  ]
 [ 0.    0.    0.    0.    1.    0.    0.    0.    0.   -1.    0.  ]]
```

**Comment by TheChymera** [comment]
I believe this has been resolved, thank you.
