### ISSUE TITLE
FAQ:why my  installation procedure always exit with code one

### ISSUE THREAD

**Issue by SoWhereAreYou** [statsmodels/statsmodels#4124]
it is on win64 and i'm chinese.please help me..  i am crazying
this is the log
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Istatsmodels/src -Ic:\users\毛嘉诚\appdata\local\programs\python\python36\lib\site-packages\numpy\core\include -Ic:\users\ 毛嘉诚\appdata\local\programs\python\python36\include -Ic:\users\毛嘉诚\appdata\local\programs\python\python36\include -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt" /Tcstatsmodels/tsa/kalmanf/kalman_loglike.c /Fobuild\temp.win-amd64-3.6\Release\statsmodels/tsa/kalmanf/kalman_loglike.obj
    kalman_loglike.c
    c:\users\毛嘉诚\appdata\local\programs\python\python36\include\pyconfig.h(222): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Istatsmodels/src -Ic:\users\毛嘉诚\appdata\local\programs\python\python36\lib\site-packages\numpy\core\include -Ic:\users\毛嘉诚\appdata\local\programs\python\python36\include -Ic:\users\毛嘉诚\appdata\local\programs\python\python36\include -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt" /Tcstatsmodels/tsa/kalmanf/kalman_loglike.c /Fobuild\temp.win-amd64-3.6\Release\statsmodels/tsa/kalmanf/kalman_loglike.obj" failed with exit status 2

    ----------------------------------------
Command "c:\users\毛嘉诚\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\毛嘉诚\\AppData\\Local\\Temp\\pip-build-zdb8gxcp\\statsmodels\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ 毛嘉诚\AppData\Local\Temp\pip-8m6ewylp-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\毛嘉诚\AppData\Local\Temp\pip-build-zdb8gxcp\statsmodels\

**Comment by bashtage** [comment]
Try opening `VS2015 x64 Native Tools Command Prompt` and running setup in this command prompt.

**Comment by bashtage** [comment]
Did this work?

**Comment by SoWhereAreYou** [comment]
yes， thank  you
i  dont know how to  comment a comment so i just close it
