### ISSUE TITLE
GLMs and LMMs are using multiple cores

### ISSUE THREAD

**Issue by arose13** [statsmodels/statsmodels#4134]
GLM and Linear Mixed Model fitting is using multiple cores when fitting. I have the newest version running in Miniconda's Python3. I can't tell if this is intentional or not.

**Comment by josef-pkt** [comment]
It's the behavior of the linear algebra libraries like MKL that default to multi processing
see #2914 #3542

I'm closing this as duplicate and the two issues are labeled as FAQ and stay open
