### ISSUE TITLE
Interface for tsa.acf and tsa.graphics.plot_acf differs

### ISSUE THREAD

**Issue by ispmarin** [statsmodels/statsmodels#4154]
The interface for the function `tsa.acf` uses the parameter `nlags` while the function `tsa.graphics.tsa.plot_acf` uses the parameter `lags`.

**Comment by josef-pkt** [comment]
I don't remember the details or reason.
Based on the docstring and implementation of the `lags` option in `plot_acf`, those two are different, lags is more general than nlags, and allows for an arbitrary array of lags, while acf nlags specifies a fixed number of consecutive lags.

**Comment by bashtage** [comment]
Closing as by design.
