### ISSUE TITLE
`tsa.graphics.plot_acf` generates the graph twice when using on Jupyter notebook

### ISSUE THREAD

**Issue by ispmarin** [statsmodels/statsmodels#4155]
When using the function `tsa.graphics.plot_acf` on a Jupyter notebook, the graph is printed twice:

    %matplotlib inline
    import statsmodels.api as sm
    import matplotlib.pyplot as plt
    plt.style.set('ggplot')
    # plots twice the same graph
    sm.tsa.graphics.plot_acf(df, lags=48)
    # plots only once
    ax = sm.tsa.graphics.plot_acf(df, lags=48)

**Comment by josef-pkt** [comment]
the duplicate plot display is a notebook "feature", not a bug
see #1265 
(I reopened 1265 as FAQ issue because it took me some time to find the related issues.)

nothing we can or want to do about it.

**Comment by pirmoradian** [comment]
Put **semicolon** at the end of your plot function to solve the problem.

**Comment by SwatiInd** [comment]
@pirmoradian : thanks for your suggestion.

**Comment by bashtage** [comment]
Or assign the output to a variable.

**Comment by SwatiInd** [comment]
Thanks @bashtage

**Comment by MaiMeng1204** [comment]
> Put **semicolon** at the end of your plot function to solve the problem.

Amazing! Thanks @pirmoradian

**Comment by edwardmoradian** [comment]
Thanks @pirmoradian
