### ISSUE TITLE
autolag hardcoded in tsa.stattools.coint

### ISSUE THREAD

**Issue by alexHub27** [statsmodels/statsmodels#4162]
The variable autolag is hardcoded when the call to tsa.stattools.adfuller is made so that 

c1 = coint(y0, y1, trend='c', method='aeg', maxlag=None, autolag='aic',return_results=None)

gives the same result as

c2 = coint(y0, y1, trend='c', method='aeg', maxlag=None, `autolag=None,return_results=None)`

**Comment by bashtage** [comment]
Seems to be fixed in master.
