### ISSUE TITLE
pval in tsa.stattools.coint is false

### ISSUE THREAD

**Issue by alexHub27** [statsmodels/statsmodels#4163]
c =  coint(y0, y1, trend='c', method='aeg', maxlag=None, autolag='aic',return_results=None)

with c[1] the pvalue associated to the process.

However, c[1] is the result of another MacKinon test (made after the one done in tsa.stattools.adfuller). It is therefore unnecessary AND false N should equals 1 and not k_vars

**Comment by bashtage** [comment]
This appears to fixed in master.
