### ISSUE TITLE
FAQ-D/BUG/TST: change matplotlib backend in unit tests - prevent segfaults

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4166]
The segfaults with matplotlib seems to be coming back with each new plot. This time multivariate.tests.test_factor.test_plot.
The segfault happens with both, when running with nosetests and with pytest.

None of the usual plt.close(fig) or plt.close('all') worked to remove the segfault.

Switching the backend works, i.e. I added plt.switch_backend('Agg')

```
try:
    import matplotlib.pyplot as plt
    missing_matplotlib = False
    plt.switch_backend('Agg')

except ImportError:
    missing_matplotlib = True
```

I guess this has permanent effect, and would change the user backend if tests are run in interpreter. So it's not a change without side effects.

switching to 'pdf' also works but tight_layout uses Agg.

**Comment by bashtage** [comment]
CLosing since this doesn't appear to be a bug, and CI has been running smoothly for a good while now.
