### ISSUE TITLE
Missing distributions namespace and ECDF function after upgrading to version 0.8.0

### ISSUE THREAD

**Issue by jlandercy** [statsmodels/statsmodels#4173]
### Problem Description

I use a lot the `ECDF` function from the `statsmodels` package. After upgrading to version `0.8.0` I could not find it any more. I had a look the code, it seems the whole namespace `distributions` has vanished. But it is still referenced in [documentation][1].

[1]: http://www.statsmodels.org/stable/generated/statsmodels.distributions.empirical_distribution.ECDF.html#statsmodels.distributions.empirical_distribution.ECDF

### MCVE

Bellow a Minimal Complete Verifiable Example illustrating what is going wrong:

```python
>>> import statsmodels as sm
>>> sm.distributions.empirical_distribution.ECDF([5,3,2,1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'statsmodels' has no attribute 'distributions'
>>> sm.__version__
'0.8.0'
```

### Questions:

 - Is the function gone in this version or forever?
 -  Is there another place where we should look for this function?

**Comment by josef-pkt** [comment]
I think just your import is wrong

`import statsmodel` does NOT load any subpackages
e.g. direct import from actual module
`from statsmodels.distributions.empirical_distribution import ECDF`

or through the api

```
import statsmodels.api as sm
sm.distributions.ECDF
```

**Comment by jlandercy** [comment]
Yes, sorry I always forget this api call. Thank you. You may close this issue.

**Comment by josef-pkt** [comment]
If you mainly need ECDF, then the direct import from the module will be much faster.

`import statsmodels.api as sm` can be very slow

That's the reason for our usage of the `api` structure
