### ISSUE TITLE
scipy 1.0.0 breaks with statsmodels 0.8.0

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4185]
llr_pvalue calls scipy.stats.chisqprob which no longer exists

**Comment by JWarmenhoven** [comment]
https://docs.scipy.org/doc/scipy/reference/release.0.17.0.html#deprecated-features
_scipy.stats.chisqprob is deprecated. This is an alias. stats.chi2.sf should be used instead._

**Comment by jbrockmendel** [comment]
Sure would be nice if calling LogitResult.summary() didn't raise an AttributeError...
