### ISSUE TITLE
discrete_margins uses deprecated kwarg

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4186]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/discrete/discrete_margins.py#L475

discrete_margins.py:474: FutureWarning: the 'all' keyword is deprecated, use 'use_all' instead

**Comment by josef-pkt** [comment]
(just to mention: I will be back next weekend (from a ski-trip) and will look then at what still has to go into 0.9.)

**Comment by jbrockmendel** [comment]
I've basically given up on contributing here, but just a reminder that if you were willing to delegate then things like "0.8.1" would be viable.
