### ISSUE TITLE
Incorrect sentence in documentation on endogeneity

### ISSUE THREAD

**Issue by baogorek** [statsmodels/statsmodels#4199]
I enjoyed the Statsmodels write-up on endogeneity:
http://www.statsmodels.org/dev/endog_exog.html

until the bottom when I read the sentence:

"if the error terms are autocorrelated, then OLS does not have good statistical properties (is inconsistent) "

which gave me pause b/c I didn't think the penalty was inconsistency. I went back and consulted the text  _A Guide to Econometrics_  by Peter Kennedy. Below is an excerpt from the Second Edition, p 116: 

> "This reasoning can be extended to show that the lagged dependent variable is correlated with all of the  past disturbances. However, it is not correlated with the current or future disturbances; thus, although the lagged dependent variable is not independent of the disturbance vector, it is contemporaneously independent of the disturbance. This means that, although beta_OLS is a biased estimator of beta it is consistent..."

Biased but consistent. I'd argue that this point is worth clarification, since inconsistency implies that no amount of data can ever allay the bias - a bad situation to be in!

**Comment by josef-pkt** [comment]
Yes, it needs to be corrected if it is incorrect.
However, I think your quote refers to the case when errors are serially independent. In that case, lagged endog are uncorrelated with current and future disturbances (lagged endog are predetermined). 
If errors are serially correlated, then past endog are correlated with future disturbances.

I would have to check to verify this.
@bashtage Do you remember how this goes for consistency?

**Comment by josef-pkt** [comment]
@baogorek Thanks for the comment. I'm glad somebody enjoys endogeneity.

**Comment by bashtage** [comment]
Autocorrelated errors do not result in inconsistency of estimators as long as the relatively weak condition of E[X \epsilon]=0 is still true.

**Comment by josef-pkt** [comment]
I don't find anything quickly in Greene.
What I was thinking of is that we cannot use OLS to consistently estimate an ARMA model
https://stats.stackexchange.com/questions/280714/using-ols-to-estimate-an-arma1-1
So the coefficient of a lagged endogenous variable cannot be consistently estimated if errors are autocorrelated.

However, our ARMA and SARIMAX are linear model plus (S)ARMA errors.
if we have exog in ARMAX, then those coefficient could be consistently estimated by OLS if they are uncorrelated with the residual which, IIRC, requires some strong or strict exogeneity. 
(I skipped over most details when I learned this, but it is eg. the reason for the search for instruments in GMM estimation for dynamic panel data which violates strong exogeneity and that GEE doesn't allow for lagged variables.)

**Comment by bashtage** [comment]
When you have a lagged dependent variable, then autocorrelation will almost
always result in inconsistency.  When you have only exogenous regressors,
and if these are unconditionally uncorrelated with the residuals, then
parameters can be consistent.

**Comment by josef-pkt** [comment]
Example for explanatory variables that are strictly exogenous are deterministic variables like trend or seasonal dummies or seasonal polynomials. VECM distinguishes between deterministic and exogenous variables, where the assumption for exogeneity of random variables are pretty tough.

And this issue reminds me that we should add the statistics term, missing completely at random MCAR, for exogeneous dropout to the example. AFAIK, that term is not used much in econometrics.

**Comment by baogorek** [comment]
Not sure if you can borrow any of this (surprisingly rich) documentation from Mathworks.com on [Dynamic and Correlation Effects](https://www.mathworks.com/help/econ/examples/time-series-regression-viii-lagged-variables-and-estimator-bias.html?requestedDomain=true#d119e5988). In their words, if there's only a "dynamic effect" (no contemporaneous correlation between y_(t-1) and e_t) then OLS can consistently estimate the coefficient of the lagged dependent variable. If there is a "correlation effect," then there will be persistent bias. @bashtage, the latter sounds like what you were describing - lagged dependent regressor + remaining autocorrelation in the residuals.

**Comment by AhmedIssa11** [comment]
I can take this as my first contribution. can you specify what needs to be corrected?

**Comment by josef-pkt** [comment]
I'm not sure what should be done here. The statements in docs are correct.

**Comment by baogorek** [comment]
I think I logged this. Give me just a little time and I’ll try to make my
case on the wording. I went through an endogeneity phase and I’m a little
rusty

**Comment by baogorek** [comment]
Everything is correct as written, and I appologize for the red herring, but I would suggest modifying

*"However, if the error terms are autocorrelated, then"*

to

*"However, if the error terms are autocorrelated in the presense of lagged dependent variables, then,"*

so that this sentence stands alone rather than relying on its predecessor.

Just to check empirically, I wrote a quick and dirty simulation in R (sorry) for y_t = rho * y_{t-1} + e_t where e_t was an autocorrelated series with adjustable AR parameter. The long run bias definitely increases with the residual autocorrelation.

```
# User input -----
N <- 10000
rho <- .8
epsilon_autocor <- .5
# End user input

epsilon <- arima.sim(N, model=list(ar = c(epsilon_autocor)))

y_vec <- c()
y <- 0
for (t in 1:N) {
  y <- rho * y + epsilon[t]
  y_vec <- c(y_vec, y)
}

df <- data.frame(y=y_vec, lag_y=c(0, y_vec[1:(N-1)]))

summary(lm(y ~ lag_y, data=df))
# Question: is the coefficient for lag_y close to rho?
```
