### ISSUE TITLE
Release wheels for Windows

### ISSUE THREAD

**Issue by uranusjr** [statsmodels/statsmodels#4203]
I searched the tracker and didn’t find anything, and figured I’d just ask. Having no wheels on Windows means there are some non-trival setup required for newcomers. Statsmodels is great for introducing Python to non-programmers, between who Windows is the prevalent operating system. Also there’s #3195 being unmerged that presents yet another chance for newcomers to trip on.

Building on Windows is pretty trivial if you know how to do it. I set up a minimal Build Tools for VS 2017 and compilation on both 3.5 and 3.6 works like a breeze. Since there is already Windows CI (Appveyor) set up, wheels should be easy to produce on it. I’m would be very glad to provide any information on this issue, but unfortunately not very familiar with how things are done here, so would need some pointers on how I should send the artefacts where so they can be released.

**Comment by jbrockmendel** [comment]
@josef-pkt repeating bashtage, closeable

**Comment by jbrockmendel** [comment]
@bashtage as you noted, this is closable
