### ISSUE TITLE
BUG/ENH: GLM negative resid_dev

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4208]
During running of monte carlos for GLM residuals with var_weights I ran into negative resid_dev which caused warning for invalid value in sqrt.
negative values where around -1e-15 or -5e-15

storing for now a changeset so I can switch branches, in families/family.py

```
@@ -413,10 +413,13 @@ class Poisson(Family):
            resid\_dev_i = 2 * var\_weights_i * (endog_i * \ln(endog_i /
            \mu_i) - (endog_i - \mu_i))
         """
         endog_mu = self._clean(endog / mu)
         resid_dev = endog * np.log(endog_mu) - (endog - mu)
+        #if (resid_dev < 0).any():
+        #    print(resid_dev[resid_dev < 0])
+        resid_dev = np.clip(resid_dev, 0, np.inf)
         return 2 * var_weights * resid_dev
 
     def loglike_obs(self, endog, mu, var_weights=1., scale=1.):
         r"""
         The log-likelihood function for each observation in terms of the fitted
```

**Comment by thequackdaddy** [comment]
I think that's a regression introduced here:

https://github.com/statsmodels/statsmodels/commit/6b8a24b68f8b1ade2dcba7740d7f96a4e2ca6739#diff-20016798d17fceba2ff1d3dfec9f2e61

**Comment by thequackdaddy** [comment]
What is more correct? `clip(resid, 0, np.inf)` or `np.sign(endog - mu) * resid`? Before, we were doing the `np.sign(endog - mu)` it looks like. Should we revert to that? Easy to update.

**Comment by josef-pkt** [comment]
I need to check after dinner

I think np.sign is needed to get the correct sign of `results.resid_deviance`, but the temp variable `resid` is supposed to be nonnegative.

**Comment by josef-pkt** [comment]
AFAICS, in your deviance refactoring you only moved the computation around. 
I don't see anything that would have prevented invalid terms in the sqrt in resid_deviance before.
I guess it is not an easy corner case to run into and it only showed up a few times in my Monte Carlo.

(However, what I didn't see before:
Because you took the common part out of the family resid_dev into GLM results, the one in family are not really proper deviance residuals anymore. That might need another look to see whether changing it that way is ok)

**Comment by josef-pkt** [comment]
for the redefinition of resids in family
We might come back to the discussion we had about making it more similar to scipy.stats.distributions.
i.e. use a leading underscore for the family specific parts and put the common parts in the method without leading underscore.
I will look at and think about it tomorrow. I just started to try out Bayesian Mixed GLM.

Based on a brief check, families don't have unit tests for themselves, they are tested as part of GLM, and so are not guaranteed in their behavior as standalone. (essentially private ?)
