### ISSUE TITLE
when doint OLS with refit=True, the model is still penalized

### ISSUE THREAD

**Issue by maxbellec** [statsmodels/statsmodels#4213]
I ran the following code. Since X is constant, the best linear model would have as weight the mean of y, i.e. `2.`.
The L1-penalized model should give `y.mean() - alpha`, so `1.`. When running OLS with `refit=False`, I expected the resulting model to have a weight of `1`. Which it does. When I run with `refit=True`, as I understand in the documentation, there should be no penalization, so I should get a weight of `2.`.

See code below.

```
import numpy as np
import statsmodels.api as sm

X = np.ones(5)
y = np.arange(5)

model = sm.OLS(y, X)

y.mean() # 2.

ols.fit_regularized(alpha=1, L1_wt=1, refit=True).params
# gives [1.], seems wrong

ols.fit_regularized(alpha=1, L1_wt=1, refit=False).params
# gives [1.], as expected

ols.fit_regularized(alpha=0, L1_wt=1).params
# gives [2.], as expected
```

**Comment by jorgecarleitao** [comment]
I think that either the documentation is not sufficiently clear or you did not understand it:

From what I understood from the code on the `fit_elasticnet` function, when `refit=True`, the fit has 2 steps:

1. fit the model with penalization
2. fit a new model removing features whose coefficients are zero

The statement `The refitted model is not regularized` in the documentation refers to the fit in step 2. Step 1 is always a penalized fit.

Could this interpretation of the documentation explain your issue?

**Comment by maxbellec** [comment]
when reading `The refitted model is not regularized`, I expect the output of `fit_regularized(.., refit=True)` to be the output of what you describe as step 2, an un-regularized model (where some features might have been removed). In my example (where no feature have been removed), I expect `fit_regularized(..., refit=True)` to output the same result as an un-regularized model.
