### ISSUE TITLE
sophisticated seasonal_decompose

### ISSUE THREAD

**Issue by znavoyan** [statsmodels/statsmodels#4221]
Hi,

In the documentation of statsmodels.tsa.seasonal.seasonal_decompose methods it was written that this is a naive decomposition. More sophisticated methods should be preferred. 

Do you have implemented such methods? Or if not, can you please point some implementation or article ?

Thanks in advance.
Zaven.

**Comment by josef-pkt** [comment]
see my comments here https://stackoverflow.com/questions/47076771/statsmodels-seasonal-decompose-what-is-naive-about-it

I don't know what Skipper had in mind when he initially implemented seasonal_decompose and wrote that comment, and I'm not familiar with the literature.

We don't have any other seasonal decomposition methods directly, but models like UnobservedComponents, Holt-Winters (now in master) and similar allow for more flexible modelling of trend and seasonal components. Another option for modeling the seasonal components especially with many periods per seasonal cycles or multiple seasons are using splines or fourier series for it.

**Comment by josef-pkt** [comment]
also, I have seen this a while ago but never looked at it more closely
https://github.com/jrmontag/STLDecompose

**Comment by bashtage** [comment]
statsmodels now has STL.
