### ISSUE TITLE
statsmodels.api.tsa.SARIMAX fails to recognize numpy.int32 in seasonal_orders

### ISSUE THREAD

**Issue by neuneck** [statsmodels/statsmodels#4224]
In statsmodels version 0.8.0, when the `statsmodels.api.tsa.SARIMAX` constructor is called with a `numpy.int32` type argument, a TypeError is raised, because the constructor tries to call `len` on it.

Code snippet

    import statsmodels as sm
    import numpy as np
    data = [1,0, -1, 0, 1, 0, -1, 0, 1, 0, -1, 0]
    p = np.int32(2)
    orders = [p, 0, 0]
    seasonal_orders = [p, 0, 0, 2]
    arima_model = sm.api.tsa.SARIMAX(data, order = orders, seasonal_order = seasonal_orders)

This issue can be circumvented by explicit type conversion before calling the constructor. However, I feel that numpy int types should be recognized properly.

Note, this is my first bug report, so please bear with me, if it is lacking.

**Comment by ChadFulton** [comment]
Hi! Thanks very much for the bug report, and sorry for the delay in response. I am unable to replicate, so I am guessing that this was fixed by 89c93a95.
