### ISSUE TITLE
HoltWinters issue

### ISSUE THREAD

**Issue by Gasia44** [statsmodels/statsmodels#4225]
I am trying to use the holtwinters model:

import holtwinters
model =  holtwinters.ExponentialSmoothing(ts_train, trend = 'add', seasonal= 'add', seasonal_periods=1440)
model _fit = model .fit()
model_fit.predict(start='2018-01-01', end='2018-01-20')

and I am getting the following error: 
'ExponentialSmoothing' object has no attribute '_get_prediction_index'
I went through the code and couldn't find the implementation of '_get_prediction_index'.
Can you please suggest what to do? 
Thanks in advance.

**Comment by josef-pkt** [comment]
Can you make a reproducible example?

According to the code `_get_prediction_index` is inherited from tsa.base.tsa_model.TimeSeriesModel which is the super class of ExponentialSmoothing.
And it looks like this case is covered by the unit tests.

**Comment by Gasia44** [comment]
Thank you for making it clear. I reinstalled the package and now everything is working well.
Thanks again.

**Comment by sheetal100789** [comment]
Can you tell me exactly which package you reinstalled? 

I am getting the same error. Thanks in advance.
