### ISSUE TITLE
FAQ-D/TST: specific filters in catch_warnings in unit tests

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4231]
AFAICS, our catch_warnings in unit test use a blanket filter and not only for specific categories that is expected to occur

```
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
```

similar to Exception, I think we should catch only the warning that is expected.
numpy.testing has a helper function, but that is too recent and not available in older numpy

related to #3845 and #4229

**Comment by josef-pkt** [comment]
related

pytest.warns does **not** silence the Warning. I don't see an option to silence it, google search and pytest docs come up empty on it.

`with pytest.warns(ValueWarning):`

**Comment by jbrockmendel** [comment]
`tm.assert_produces_warning`

**Comment by bashtage** [comment]
silence a warning using

```
with pytest.warns(None):  # eats all warnings w/o a test
    code_that_warns()
```

In recent pytest it catches and silences all warnings that are tested for.
