### ISSUE TITLE
error while downloading statsmodel for time series

### ISSUE THREAD

**Issue by gunjanth** [statsmodels/statsmodels#4259]
![error](https://user-images.githubusercontent.com/21117188/36367186-93e1f316-1577-11e8-98b0-c451a846617f.PNG)
…]()

**Comment by gunjanth** [comment]
I am unable to figure the error at the end.
I have update my numpy as well.
Any help will be appreciated

**Comment by bashtage** [comment]
Hopefully, this has been solved by now.  Closing. Reopen a new issue if it still persists.
