### ISSUE TITLE
How to fit multiple series with ARIMA model?

### ISSUE THREAD

**Issue by yeren1989** [statsmodels/statsmodels#4275]
I have multiple series data, say, from the same statistical process, and wanna to fit an ARIMA model with them, but it seems that the api only supports one series as input.
Is there any way to do that? And when i have a trained ARIMA model, how can i make an in-sample prediction of another series instead of the one used to train the model?

**Comment by ChadFulton** [comment]
There is currently no built-in model that allows this. However, you can construct a custom state space model to do it.

- See the jupyter notebook I posted in #4145 for an example of how to do this for mutliple AR models, it's not too hard to extend this to allow for multiple ARIMA models.
- See some additional discussion in #4249 about extending the example in the notebook of #4145, where I give some tips about how you might include exogenous variables too

**Comment by bashtage** [comment]
Closing as answered.

**Comment by noname34** [comment]
> I have multiple series data, say, from the same statistical process, and wanna to fit an ARIMA model with them, but it seems that the api only supports one series as input.
> Is there any way to do that? And when i have a trained ARIMA model, how can i make an in-sample prediction of another series instead of the one used to train the model?



Hi there,

Are you the author of this post on Github? #4275

I have been stuck for days and have exactly the same problem that you described in this post.
Have you been able to find a way to fit a traditional regression model such as ARIMA giving multiple chunks of time series as input?

Sorry for disturbing but if you have found a solution, I would really appreciate it.

Thank you in advance for your support!
Best regards,
