### ISSUE TITLE
Contributing to Statsmodels as part of GSoC 2018.

### ISSUE THREAD

**Issue by virmht** [statsmodels/statsmodels#4285]
Hello Mentors and Developers,

I am Viral Mehta, a student at BITS Pilani, Hyderabad Campus. I went through the [Statsmodels GSoC 2018 ideas page](https://github.com/statsmodels/statsmodels/wiki/Google-Summer-of-Code-2018) and found all the projects to be very interesting.
I found the projects:
1. Add Maximum Likelihood Models for other distributions - Survival and Failure Times
2. Survival Models
3. Post-estimation Inference and diagnostic tests especially for GLM
4. Automatic Forecasting
to be especially interesting.

I would love to contribute to Statsmodels and participate in GSoC 2018.

I have been working on statistics and machine learning since a long time and I have used statsmodels many times for my tasks.

You can know more about me on:

Linkedin: https://in.linkedin.com/in/viral-mehta-b76093102
GitHub: https://github.com/virmht

I do have some open source experience and I would like to try my hand by implementing a small new feature and/or resolving bugs.
I will be extremely thankful if someone could guide me regarding the same.

Thanking you.

Regards,
Viral Mehta.

**Comment by josef-pkt** [comment]
Hi Viral
general discussion should go on the mailing list. We can use github issues for specific proposals, topics and related discussion and design issues.
