### ISSUE TITLE
gsoc 2018 -discussion -Automatic Forecasting

### ISSUE THREAD

**Issue by kanav-raina** [statsmodels/statsmodels#4286]
Hello ,
I am a student  and i see that this community is gearing up for Gsoc this year.This community does work in the field of my interest . I would love to become an active contributor .I had look at ideas page and the project titled '' Automatic Forecasting" intrigues me.Since i have not worked with this community before ,i would like to get started with some simple contributions .

Plz tell me from where should i start

**Comment by ChadFulton** [comment]
Glad to hear you're interested! This kind of general thing is best discussed on the mailing list (https://groups.google.com/forum/#!forum/pystatsmodels).

**Comment by kanav-raina** [comment]
ok thanks for the reply,
