### ISSUE TITLE
SARIMAX ar_params/ma_params giving incorrect results for non-consecutive lags

### ISSUE THREAD

**Issue by NowanIlfideme** [statsmodels/statsmodels#4289]
When using non-consecutive lags with SARIMAX, i.e. tuples for p or q, the resultant ar_params and ma_params aren't cut off correctly from all the others. I haven't tested with the combination, or with P/Q, but likely the same happens there.

statsmodels full_version == '0.8.0'

Example below.

```
>>> import statsmodels.api as sm
>>> import numpy as np
>>> import pandas as pd
>>> dta = sm.datasets.sunspots.load_pandas().data
>>> sss = lambda x : pd.Timestamp(str(int(x)) + "-01-01")
>>> dta = dta.set_index(pd.DatetimeIndex(dta["YEAR"].apply(sss)))
>>> del dta['YEAR']
>>> endog = dta['SUNACTIVITY']
>>> order1 = (3,0,0)
>>> mod1 = sm.tsa.SARIMAX(endog, order=order1).fit(disp=0)
>>> order2 = ((1,0,1), 0, 0)
>>> mod2 = sm.tsa.SARIMAX(endog, order=order2).fit(disp=0)
>>> order3 = ((0,0,1), 0, 0)
>>> mod3 = sm.tsa.SARIMAX(endog, order=order3).fit(disp=0)
>>> print(mod1.params)
ar.L1       1.559285
ar.L2      -0.787745
ar.L3       0.130519
sigma2    349.730362
dtype: float64
>>> print(mod2.params)
ar.L1       1.148138
ar.L3      -0.279352
sigma2    428.185631
dtype: float64
>>> print(mod3.params)
ar.L3        0.616523
sigma2    2516.393448
dtype: float64
>>> print(mod1.arparams)
[ 1.55928508 -0.78774548  0.13051884]
>>> print(mod2.arparams)
[  1.14813810e+00  -2.79352080e-01   4.28185631e+02]
>>> print(mod3.arparams)
[  6.16522707e-01   2.51639345e+03]
```

Off-topic: what is the correct term for this kind of AR process? Just a constrained AR(max_lag)? Partial autoregression?

**Comment by ChadFulton** [comment]
Thank you very much for the report, it is greatly appreciated!

I have created a PR to fix this (#4291).

I guess I would call them restricted AR or constrained AR, but I'm not sure if there's an "official" terminology.

**Comment by NowanIlfideme** [comment]
Another, related issue I ran into just now was the inconsistency of the model.params depending on the input (endog/exog) type: pd.Series if the input was pandas, and np.ndarray if the input was numpy. 

I understand this might be to allow users without pandas imported to use the objects... but pandas is a requirement for statsmodels, so I don't quite understand why that would be necessary.

Anyways, thanks for the quick fix!

**Comment by ChadFulton** [comment]
> Another, related issue I ran into just now was the inconsistency of the model.params depending on the input (endog/exog) type: pd.Series if the input was pandas, and np.ndarray if the input was numpy.

> I understand this might be to allow users without pandas imported to use the objects... but pandas is a requirement for statsmodels, so I don't quite understand why that would be necessary.

Yes I can see what you mean. I think this is the general Statsmodels policy, and it might now be hard to change for backwards compatibility reasons. @josef-pkt am I remembering that right?

**Comment by josef-pkt** [comment]
That the return type, pandas or numpy or ... (not yet), depends on the input type is intentional and wouldn't be changed even if there were no backwards compatibility considerations.

The main reason is that even though pandas is required, not everyone or not every usecase uses pandas. For example internally we use numpy arrays and need results in numpy arrays. The same for packages that use statsmodels with mainly numpy arrays. If callers use numpy arrays, then obviously they are not using pandas in that usecase.
