### ISSUE TITLE
TST: scipy version check for skipif

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4296]
What's the canonical way?

I guess using
`from distutils.version import LooseVersion`

Trying to find an example

 statsmodels.regression.tests.test_lme 
tests are skipped in scipy 1.0.0   (AFAICS)
```
v = scipy.__version__.split(".")[1]
old_scipy = int(v) < 16
```

statsmodels.stats.tests.test_power.test_power_solver_warn()  is skipped for all scipy versions that we support
`SM_GT_10 = LooseVersion(scipy.__version__) >= '0.10'`

**Comment by jbrockmendel** [comment]
closeable?

**Comment by bashtage** [comment]
Does not seem obviously relevant.
