### ISSUE TITLE
One more for the WTF pile

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4326]
Is there any earthly reason for [this](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/stats/tests/test_diagnostic.py#L724) to exist in test_diagnostic:

```
def grangertest():
    #> gt = grangertest(ginv, ggdp, order=4)
    #> gt
    #Granger causality test
    #
    #Model 1: ggdp ~ Lags(ggdp, 1:4) + Lags(ginv, 1:4)
    #Model 2: ggdp ~ Lags(ggdp, 1:4)

    grangertest = dict(fvalue=1.589672703015157, pvalue=0.178717196987075,
                       df=(198,193))
```

**Comment by josef-pkt** [comment]
most likely: test driven development with limited human memory

I got many test results out of R and Gretl (at the time I didn't have a Stata license) and most likely forgot about it when I implemented grangercausalitytests
https://github.com/statsmodels/statsmodels/pull/145/files#diff-e212f843a99429dd1ec80f3c0525322e
or maybe I just forgot to add the call and assert for grangercausalitytests

needs checking if current grangercausality unit test coverage is good enough.

(It's easier to export many R results in one session than get used to R for many short periods.)
(Nobody reviews PRs with 12000 lines of mixed changes.)
