### ISSUE TITLE
Failign test_getframe_smoke

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4330]
statsmodels.multivariate.tests.test_factor.test_getframe_smoke is failing locally:

```>       assert_(isinstance(ldf, pd.formats.style.Styler))
E       AttributeError: 'module' object has no attribute 'formats'
```

Looks like the kind of thing that would super easy to fix in a 0.8.1.

**Comment by josef-pkt** [comment]
which pandas version do you use? What's the full traceback?

factor analysis was only added a few months ago and is not in 0.8.

**Comment by jbrockmendel** [comment]
0.22.0

**Comment by josef-pkt** [comment]
You need to figure out why it fails for you.
AFAICS, we have pandas 0.22.0 on both appveyor and travis without failing tests
