### ISSUE TITLE
Test class in test_var unused

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4338]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/vector_ar/tests/test_var.py#L33

Nice test class.  Sure would be swell if there were some tests.

**Comment by josef-pkt** [comment]
Once upon a time there was a test case
https://github.com/statsmodels/statsmodels/blob/30cebd922e98bc41f0ea35f8e2164c936148d57a/scikits/statsmodels/tsa/var/tests/test_var.py#L75

I didn't try to find which commit made it disappear. github interface is not so nice for walking up and down a file history.
