### ISSUE TITLE
SARIMAX     LinAlgError: Non-positive-definite forecast error covariance

### ISSUE THREAD

**Issue by danparla** [statsmodels/statsmodels#4342]
I am new to github so if i need to add additional information please let me know.
The error comes up when I am adding this variable to my exogenous variables. 
Its the standard deviation from the mean of prices.
deviationmean
count 3.300000e+02 
mean -2.994238e-17 
std 1.001519e+00 
min -5.021758e+00 
Dtype : float64
with no missing values.
length of endog and exog  are the same.
Using statsmodels version 0.8.0

LinAlgError                               Traceback (most recent call last)
<ipython-input-119-8b2ef7930c8a> in <module>()
      1 mod=SARIMAX(endog=monthly, exog= monthlyprices2,order= (1,1,1,12))
----> 2 results=mod.fit()
      3 results.summary()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py in fit(self, start_params, transformed, cov_type, cov_kwds, method, maxiter, full_output, disp, callback, return_params, optim_score, optim_complex_step, optim_hessian, **kwargs)
    444                                            full_output=full_output,
    445                                            disp=disp, callback=callback,
--> 446                                            skip_hessian=True, **kwargs)
    447 
    448         # Just return the fitted parameters if requested

~\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\base\model.py in fit(self, start_params, method, maxiter, full_output, disp, fargs, callback, retall, skip_hessian, **kwargs)
    449                                                        callback=callback,
    450                                                        retall=retall,
--> 451                                                        full_output=full_output)
    452 
    453         #NOTE: this is for fit_regularized and should be generalized

~\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\base\optimizer.py in _fit(self, objective, gradient, start_params, fargs, kwargs, hessian, method, maxiter, full_output, disp, callback, retall)
    182                             disp=disp, maxiter=maxiter, callback=callback,
    183                             retall=retall, full_output=full_output,
--> 184                             hess=hessian)
    185 
    186         optim_settings = {'optimizer': method, 'start_params': start_params,

~\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\base\optimizer.py in _fit_lbfgs(f, score, start_params, fargs, kwargs, disp, maxiter, callback, retall, full_output, hess)
    376                                          callback=callback, args=fargs,
    377                                          bounds=bounds, disp=disp,
--> 378                                          **extra_kwargs)
    379 
    380     if full_output:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py in fmin_l_bfgs_b(func, x0, fprime, args, approx_grad, bounds, m, factr, pgtol, epsilon, iprint, maxfun, maxiter, disp, callback, maxls)
    191 
    192     res = _minimize_lbfgsb(fun, x0, args=args, jac=jac, bounds=bounds,
--> 193                            **opts)
    194     d = {'grad': res['jac'],
    195          'task': res['message'],

~\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, **unknown_options)
    326             # until the completion of the current minimization iteration.
    327             # Overwrite f and g:
--> 328             f, g = func_and_grad(x)
    329         elif task_str.startswith(b'NEW_X'):
    330             # new iteration

~\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\optimize\lbfgsb.py in func_and_grad(x)
    272         def func_and_grad(x):
    273             f = fun(x, *args)
--> 274             g = _approx_fprime_helper(x, fun, epsilon, args=args, f0=f)
    275             return f, g
    276     else:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\optimize\optimize.py in _approx_fprime_helper(xk, f, epsilon, args, f0)
    626         ei[k] = 1.0
    627         d = epsilon * ei
--> 628         grad[k] = (f(*((xk + d,) + args)) - f0) / d[k]
    629         ei[k] = 0.0
    630     return grad

~\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\optimize\optimize.py in function_wrapper(*wrapper_args)
    290     def function_wrapper(*wrapper_args):
    291         ncalls[0] += 1
--> 292         return function(*(wrapper_args + args))
    293 
    294     return ncalls, function_wrapper

~\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\base\model.py in <lambda>(params, *args)
    427 
    428         nobs = self.endog.shape[0]
--> 429         f = lambda params, *args: -self.loglike(params, *args) / nobs
    430         score = lambda params, *args: -self.score(params, *args) / nobs
    431         try:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py in loglike(self, params, *args, **kwargs)
    640             kwargs['inversion_method'] = INVERT_UNIVARIATE | SOLVE_LU
    641 
--> 642         loglike = self.ssm.loglike(complex_step=complex_step, **kwargs)
    643 
    644         # Koopman, Shephard, and Doornik recommend maximizing the average

~\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tsa\statespace\kalman_filter.py in loglike(self, loglikelihood_burn, **kwargs)
    684             loglikelihood_burn = self.loglikelihood_burn
    685         kwargs['results'] = 'loglikelihood'
--> 686         return np.sum(self.filter(**kwargs)[loglikelihood_burn:])
    687 
    688     def loglikeobs(self, loglikelihood_burn=None, **kwargs):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tsa\statespace\kalman_filter.py in filter(self, filter_method, inversion_method, stability_method, conserve_memory, tolerance, loglikelihood_burn, results, complex_step)
    643 
    644         # Run the filter
--> 645         kfilter()
    646 
    647         # We may just want the loglikelihood

statsmodels\tsa\statespace\_statespace.pyx in statsmodels.tsa.statespace._statespace.dKalmanFilter.__call__ (statsmodels/tsa/statespace/_statespace.c:56348)()

statsmodels\tsa\statespace\_statespace.pyx in statsmodels.tsa.statespace._statespace.dKalmanFilter.__next__ (statsmodels/tsa/statespace/_statespace.c:56516)()

statsmodels\tsa\statespace\_statespace.pyx in statsmodels.tsa.statespace._statespace.dinverse_univariate (statsmodels/tsa/statespace/_statespace.c:53100)()

LinAlgError: Non-positive-definite forecast error covariance matrix encountered at period 1

**Comment by ChadFulton** [comment]
Thanks for the bug report!

My first guess is bad starting parameters, can you report the results of:

```python
mod=SARIMAX(endog=monthly, exog= monthlyprices2,order= (1,1,1,12))
print(mod.start_params)
```


If that doesn't turn anything up, then it would be really helpful if you could post the data you're using, unless its confidential.

**Comment by ChadFulton** [comment]
Side note: Also, the `order` argument is for the non-seasonal, component, and it only pays attention to the first three elements. I'm not sure if you wanted`seasonal_order= (1,1,1,12)`?

**Comment by bashtage** [comment]
Closing as answered and since no follow-up.
