### ISSUE TITLE
should TestWaldAnoveOLSNoFormula subclass something?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4343]
base.tests.test_generic_methods

Granted its actually mangled as T_estWaldAnoveOLsNoFormula (instead of being xfailed (see #4079) like it should be) so its actually dead code anyway.  But in principle, should it subclass something?

**Comment by josef-pkt** [comment]
I think that the `T_estWaldAnoveOLsNoFormula` can be deleted
TestWaldAnovaOLS has a test_noformula method so the separate class looks redundant

If there was an intention to add more unit tests, then they can be added from scratch. There is not enough information in `T_estWaldAnoveOLsNoFormula` that would be helpful for that.

**Comment by jbrockmendel** [comment]
Fixed in one of my recent PRs, closing.
