### ISSUE TITLE
Should check_confidenceintervals methods get called?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4344]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/regression/tests/test_regression.py#L864

**Comment by josef-pkt** [comment]
looks obsolete, left over from earlier version where the test delegated to the subclass method, i.e. can be deleted AFAICS

**Comment by jbrockmendel** [comment]
Thanks.  I'll remove this downstream.

**Comment by josef-pkt** [comment]
what is downstream?

**Comment by jbrockmendel** [comment]
github.com/jbrockmendel/sm2
