### ISSUE TITLE
Exogenous parameters method missing in SARIMAX.results?

### ISSUE THREAD

**Issue by RomFas** [statsmodels/statsmodels#4352]
It seems that, while I'm able to extract autoregressive and moving average parameters from my trained model, through arparams() and maparams() methods in SARIMAX.results, I cannot find any way to extract the exogenous parameters. 
More specifically, from the following model:
```
                            Statespace Model Results
===================================================================
Dep. Variable:                     HR   No. Observations:                  829
Model:               SARIMAX(1, 0, 3)   Log Likelihood                2547.714
Date:                Sat, 17 Mar 2018   AIC                          -5083.428
Time:                        22:29:18   BIC                          -5055.107
Sample:                    01-01-1970   HQIC                         -5072.567
                         - 01-01-1970
Covariance Type:                  opg
===================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
SBP_0          0.0009      0.000      6.384      0.000       0.001       0.001
ar.L1          0.9971      0.001    874.955      0.000       0.995       0.999
ma.L1          0.6313      0.025     25.082      0.000       0.582       0.681
ma.L2          0.2466      0.034      7.308      0.000       0.180       0.313
ma.L3          0.0769      0.038      2.046      0.041       0.003       0.150
sigma2         0.0001   4.33e-06     30.391      0.000       0.000       0.000
===================================================================================
Ljung-Box (Q):                       99.06   Jarque-Bera (JB):               464.42
Prob(Q):                              0.00   Prob(JB):                         0.00
Heteroskedasticity (H):               1.02   Skew:                             0.63
Prob(H) (two-sided):                  0.90   Kurtosis:                         6.44
===================================================================
```
I need value 0.0009 from the exogenous input SBP_0. There is probably an obvious way that I'm missing.

**Comment by josef-pkt** [comment]
I think you can always access the full `params` array, results.params[0] ? 
I think the lag coefficients are split out to compute some time series attributes.
(more details are up to Chad)

**Comment by RomFas** [comment]
Yeap, that definately works, although many different models are trained automatically, with more exogenous variables every time, therefore, a method like arparams() and maparams() would have been convenient if it existed. Thanks!

**Comment by ChadFulton** [comment]
Yes, we just put in the `arparams` etc. for some of the AR/MA lag polynomial stuff. I agree that it would be nice to have a helper method for the other types of parameters also, or at least the exog ones.

> Yeap, that definately works, although many different models are trained automatically, with more exogenous variables every time, therefore, a method like arparams() and maparams() would have been convenient if it existed. Thanks!

One option for now is:

```python
# ... (create mod)
res = mod.fit()

# Extract the parameters
params = {}
start = end = 0
for name in res.param_terms:
    end += res.model_orders[name]
    params[name] = res.params[start:end]
    start += res.model_orders[name]
params['exog']
```

(in fact there is a private property of the SARIMAXResults object that already has what you want, but I don't want to advertise it since it is currently private)

**Comment by RomFas** [comment]
Well that was fast, thanks guys!
