### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by RD193** [statsmodels/statsmodels#4362]
![bandicam 2018-03-19 22-17-41-447](https://user-images.githubusercontent.com/18684799/37619919-7b1057f8-2bc3-11e8-8280-1f6ab4089bc0.jpg)
This error was ocupated during instalation of package/ Also get this, bu still can't import library:
![bandicam 2018-03-19 22-23-01-233](https://user-images.githubusercontent.com/18684799/37620216-3beb83da-2bc4-11e8-81d9-718a63abaa64.jpg)

**Comment by jbrockmendel** [comment]
Does this problem still occur?

**Comment by RD193** [comment]
I don't know because I didn't try any more.

**Comment by bashtage** [comment]
We will close then. Reopen if you try again and have problems.
