### ISSUE TITLE
SARIMAX.forecast() output question/general use question

### ISSUE THREAD

**Issue by jmwoloso** [statsmodels/statsmodels#4368]
Hello,

I have a general question regarding how to use a trained SARIMAX (and/or ARIMAX) model to forecast out-of-sample time periods. I have differenced my training data to make it stationary, but the forecast outputs from my SARIMAX and ARIMAX models produce negative values which I'm assuming are predictions of the differences rather than totals. How do I get the totals for each day instead of differences (assuming it is outputting differences)? It is also not clear to me when I should use `predict` versus `forecast`.

I've included the resources below to help you re-create what I'm seeing.

`script`
[github.py.zip](https://github.com/statsmodels/statsmodels/files/1830868/github.py.zip)

`training_data`
[training_data.csv.zip](https://github.com/statsmodels/statsmodels/files/1830875/training_data.csv.zip)

`exogenous_out_of_sample_data`
[out_of_sample_exogenous_data.csv.zip](https://github.com/statsmodels/statsmodels/files/1830877/out_of_sample_exogenous_data.csv.zip)

Thank you for any assistance!

**Comment by josef-pkt** [comment]
>  I have differenced my training data to make it stationary

In general it's better to let SARIMAX (or similarly ARIMA) handle the differencing, then differencing is supported for predicting the level. Transformations of endog by users, like differencing or taking log, are not directly supported because the model does not know what the user did.

> predict versus forecast

`forecast` is an easier to use special case of `predict` when we want to predict/forecast starting from the end of the sample used in fit. `predict` also has options for in sample "forecasts", i.e. prediction based on the history at a specific in-sample date, but using parameter estimates based on the full fit sample.

**Comment by jmwoloso** [comment]
@josef-pkt Thank you very much for the fast response! Allowing`SARIMAX` to handle the differencing definitely took care of the problem with negative output for that case.

Doing the same with `ARIMAX` however still has me confused. It would appear using the `forecast` method produces an array of arrays. 

What are the components that make up the array of arrays?

Also, the `predict` method of `ARIMAX` still produces some negative outputs even when I let it handle the differencing as you suggest.

Any thoughts?

I've attached my updated usage script for your convenience:

[github_v2.py.zip](https://github.com/statsmodels/statsmodels/files/1831024/github_v2.py.zip)

**Comment by josef-pkt** [comment]
ARIMA.predict has a `typ` keyword which unfortunately defaults to 'linear'. Using `typ='level' provides the level forecast/prediction (i.e. appropriately cumsum'ed)
http://www.statsmodels.org/dev/generated/statsmodels.tsa.arima_model.ARIMA.predict.html

I'm not sure about the SARIMAX details. SARIMAX has more options and is better maintained than ARIMA, but I don't have as much experience with it,

**Comment by jmwoloso** [comment]
@josef-pkt Thank you very much, that's awesome! I really appreciate your help!
