### ISSUE TITLE
Add GARCH + plus flexible enhancements

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#437]
From a discussion with @escheffel.

"GARCH(1,1) is nice to have, but as a macroeconomist I recently needed a tailored solution for a so-called AR(1)-MARCH(1,1) model (what a mouthful). Essentially an autoregressive order one mean-in-garch model.

x(t)=mu+rho_x(t-1)+gamma_sigma^2(t)+e(t)
sigma^2(t)=delta+alpha*e(t-1)+betta$sigma^2(t-1)+epsilon(t)

Difference from normal GARCH(1,1) is rho_x(t-1) AND gamma_sigma^2(t) both in the mean equation"

**Comment by bashtage** [comment]
Use `arch` package.
