### ISSUE TITLE
Non-corresponding method name in proportion_confint() method

### ISSUE THREAD

**Issue by davoudian** [statsmodels/statsmodels#4376]
On the documentation site:
http://www.statsmodels.org/dev/generated/statsmodels.stats.proportion.proportion_confint.html#statsmodels.stats.proportion.proportion_confint

it states that to implement the jeffreys bayesian interval, one should use something like:
``proportion_confint(count, nobs, alpha=0.05, method='jeffreys')``

however in line 118 of the actual proportion.py file, it actually uses
``proportion.proportion_confint(count, nobs, alpha=0.05, method='jeffrey')``

the documentation should be updated to fix this discrepancy

**Comment by josef-pkt** [comment]
Which source proportion.py file are you looking at?

`jeffreys` is the correct spelling, which I had misspelled in the original version, as someone pointed out, but it has been fixed.

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/stats/proportion.py#L115
```
    # method adjusted to be more forgiving of misspellings or incorrect option name
    elif method[:4] == 'jeff':
```

I decided to use only the first four letters to avoid that users need to do a spell check.

**Comment by josef-pkt** [comment]
based on the PR #3170 this should be changed already in 0.8

**Comment by davoudian** [comment]
Thanks josef, I had been using an older version.
