### ISSUE TITLE
xfail syntax in test_glm_weights

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4381]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/tests/test_glm_weights.py#L201

```
    @pytest.mark.xfail(reason='Known to fail')
    def test_basic(cls):
        super(cls, TestGlmPoissonPwNr).test_basic(cls)
```

Skipping over the fact that "test_basic" is a poorly-scoped test in the parent class and the fact that "cls" should be "self" here:

a) "Known to fail" is not a helpful xfail message
b) Are the super args reversed here?

**Comment by josef-pkt** [comment]
> Are the super args reversed here?

That's a bug
https://github.com/statsmodels/statsmodels/commit/c1da9f8c7a179bedb549fd0419a7ba681974a85f

unit test is for a feature, prob_weights, that is not implemented yet.

**Comment by josef-pkt** [comment]
I already fixed this in an open PR, which I expect to finish today
https://github.com/statsmodels/statsmodels/pull/4235/files#diff-66cde8475575e9d162bd8f401857caf7

**Comment by jbrockmendel** [comment]
Appears fixed, albeit still doesnt have a useful xfail message.  Closing.
