### ISSUE TITLE
initialize or _initialize

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4398]
Some models have an `_initialize` in addition to `initialize`.  Any reason for this?  What's the logic for what goes in these vs in `__init__`?

**Comment by josef-pkt** [comment]
AFAIR without looking, the main idea behind using an extra method is to give subclasses the chance to override add something in the initialization without having to having to override `__init__`.

**Comment by jbrockmendel** [comment]
You're right that it's unfortunate that the extra method exists at all, but the question here is about the inconsistent naming initialize vs _initialize

**Comment by josef-pkt** [comment]
Which models have `_initialize`?   I checked a few and they all have only `initialize`

> You're right that it's unfortunate that the extra method exists at all

It's not unfortunate that the extra `initialize` method exists. it's by design.

**Comment by josef-pkt** [comment]
miscmodel.TLinearModel has `initialize` but no `__init__`.

I don't remember any details right now, but I recently wrote a `class GLMNonlinear(GLM)` that also defines a `initialize` method.

**Comment by jbrockmendel** [comment]
RobustLinearModel and _NegativeBinomial have `_initialize` methods.

**Comment by josef-pkt** [comment]
> RobustLinearModel and _NegativeBinomial have _initialize methods.

AFAICS, the method could be renamed in both cases, and let super call initialize.
