### ISSUE TITLE
vecm tests are a mess

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4405]
jmulti parsing code is super-redundant.

**Comment by josef-pkt** [comment]
That's not an informative issue description.

I didn't care enough during PR review to even look at that for more than 5 seconds.
But test coverage is good, AFAIR.

**Comment by jbrockmendel** [comment]
Supposing someone wanted to step through these tests to troubleshoot #4436, it would be _super helpful_ to have tests that vaguely resembled "test cases", rather than one giant block of code to run.
