### ISSUE TITLE
cl.exe failing when installing statsmodel

### ISSUE THREAD

**Issue by sanchit-agarwal** [statsmodels/statsmodels#4407]
I am getting a compiler error when trying to install statsmodel using pip.

`error: Command "cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Istatsmodels/src -IC:\Users\funky\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\include -IC:\Users\funky\AppData\Local\Programs\Python\Python36\include -IC:\Users\funky\AppData\Local\Programs\Python\Python36\include -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Include" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tcstatsmodels/tsa/kalmanf/kalman_loglike.c /Fobuild\temp.win-amd64-3.6\Release\statsmodels/tsa/kalmanf/kalman_loglike.obj" failed with exit status 127`

I am on Windows 10 Enterprise. 64 bit architecture. I am using python 3.6

**Comment by bashtage** [comment]
Closing since no follow-up.  Please reopen if this continues.
