### ISSUE TITLE
Wrappers for scipy.stats?

### ISSUE THREAD

**Issue by hoechenberger** [statsmodels/statsmodels#4409]
Hello, a couple years back, @josef-pkt suggested it might be an option

> to add wrapper functions for scipy.stats in statsmodels, that could use both pandas and scipy.stats.

(https://github.com/pandas-dev/pandas/issues/4557#issuecomment-22914589)

I would like to bring up this idea again.

Background:
I've been introducing several colleagues to Python & pandas lately; however running some frequently required statistical tests of our scientific domain (neuroscience / psychology) is experienced as painful. I figured the main source of confusion and frustration is that in our workflow, data is usually stored in pandas `DataFrames`, and while `DataFrame`-aware plotting solutions exist (most notably seaborn), performing simple stats like an ordinary t-test feels kind of awkward because `scipy.stats` is _not_ `DataFrame`-aware. For just comparing two columns it's simple:

```python
t, p = scipy.stats.ttest_rel(df['A'], df['B'])
```

but it quickly gets rather ugly (IMHO) when performing `groupby` actions to run tests on subgroups with the intention of getting back a nicely-shaped `DataFrame` with the results:

```python
def ttest(data):
    t, p = scipy.stats.ttest_rel(data['A'], data['B'])
    result = pd.Series(dict(t=t, p=p))
    return result

df.groupby('C').apply(ttest)
```

It just seems unnecessarily complicated, and having to leave the `DataFrame`-aware sphere (i.e., using tests from `scipy.stats`) feels disruptive.

Now my preferred approach would be to have wrappers for `scipy.stats` built directly into pandas:
```python
df.groupby('C').ttest_rel('A', 'B')
```
but [this is now out of the project's scope](https://github.com/pandas-dev/pandas/issues/4557#issuecomment-346796053).

So I thought, as per @josef-pkt's previously mentioned suggestion, the next-best approach could be adding more `scipy.stats` wrappers to statsmodels? Maybe something along the lines of,

```python
sm.ttest_rel('A', 'B', data=df)
```

Yet, this would still be a little confusing (to beginners) when applied to `grouby` objects:

```python
df.groupby('C').apply(lambda x: sm.ttest_rel('A', 'B', data=x))
```

So maybe invoking `groupby` from within statsmodels – as is done e.g. in `AnovaRM`, albeit for obviously different reasons – would be the most user-friendly solution:

```python
sm.ttest_rel('A', 'B', groupby=['C'], data=df)
```

This would return a `DataFrame` (or similar object / table) including

- groups
- test statistics
- degrees of freedom
- p-vaues
- (potentially number of skipped / remove `NA` entries?)

_Please not that I only used `ttest_rel` in all above examples because this was the first common test I could think of; but the same would also apply to other types of t-tests, correlations, etc._

I would like to hear what you think about these ideas, and if there'd be any chance on ever getting such functionality included in statsmodels? I'd be willing to help with the implementation, but don't really know where to start...

Thanks,

–Richard

**Comment by josef-pkt** [comment]
I am still in favor of supporting this in statsmodels.

However, API design might not be easy, because both function argument and return types have then several different versions.
Currently, we have problems supporting interactive use, returning a results class with all information, and library use with minimal returns in the form of a tuple.


AFAICS, the following also works if the function ttest returns a Series
`df.groupby('C')['A', 'B'].apply(ttest)`

```
import numpy as np
import pandas as pd
from scipy import stats

def ttest(data):
    t, p = stats.ttest_rel(data.iloc[:, 0], data.iloc[:, 1])
    result = pd.Series(dict(t=t, p=p))
    return result

np.random.seed(987126)
nobs = 100
df = pd.DataFrame([0, -0.5, 0.5] + np.random.randn(nobs, 3), columns=['A', 'B', 'D'])
df['C'] = np.array('a b c d e'.split())[np.repeat(np.arange(5), 20)]

print(df.groupby('C')['A', 'B'].apply(ttest))
print(df.groupby('C')['A', 'D'].apply(ttest))
print(df.groupby('C')['D', 'A'].apply(ttest))
```

**Comment by josef-pkt** [comment]
About groupby keywords in function or classes:

Stata and SAS have something like this (or strata) in some of the functions/procedures.
In general I'm very skeptical that they are worth the code complication given that in most cases pandas or similar can easily be used for this.
The main problem is that it is recursive, that is we have a loop inside the function or model that loops over itself. So, to keep it simpler we need an extra function for the core computation for a single group.
Then, it might be easier to add a wrapper code that extends or applies pandas groupby to stats functions that are not covered by pandas.

For example Stata has a `by` prefix that I never used, but sounds similar to running a groupby over arbitrary commands that are supported..

**Comment by josef-pkt** [comment]
a possible more generic addition to pandas would be to support named tuples and convert them to a series.

e.g. if I use the scipy.stats named tuples return directly, then groupby returns an object dataframe with the named tuple as element

```
def ttest2(data):
    result = stats.ttest_rel(data.iloc[:, 0], data.iloc[:, 1])
    return result
```

However, the type of the named tuple is the actual named tuple class, so there is no easy instance check.

```
>>> df.groupby('C')['D', 'A'].apply(ttest2)[0]
Ttest_relResult(statistic=2.3524003301495293, pvalue=0.029584648719464722)

>>> type(df.groupby('C')['D', 'A'].apply(ttest)[0])
<class 'scipy.stats.stats.Ttest_relResult'>
>>> type(df.groupby('C')['D', 'A'].apply(ttest)[0]).mro()
[<class 'scipy.stats.stats.Ttest_relResult'>, <class 'tuple'>, <class 'object'>]
```

I'm not a fan of named tuples (as a developer), but they have a private attribute that can be used to convert to a dict and then to a Series. (I have no idea why asdict is private, but I didn't find another way to get a dict or Series.)

```
def ttest3(data):
    result = stats.ttest_rel(data.iloc[:, 0], data.iloc[:, 1])
    return pd.Series(result._asdict())
```

**Comment by hoechenberger** [comment]
Hi @josef-pkt, sorry for the late response, I was on vacation and didn't have time to respond earlier. :)

> I am still in favor of supporting this in statsmodels.

Great to hear!

> However, API design might not be easy, because both function argument and return types have then several different versions.
> Currently, we have problems supporting interactive use, returning a results class with all information, and library use with minimal returns in the form of a tuple.

I see. This is really something I do not have insight into, so thanks for filling me in on these details!

> 
> AFAICS, the following also works if the function ttest returns a Series
> df.groupby('C')['A', 'B'].apply(ttest)

Yes, this does work indeed, but I wouldn't say this syntax is pretty, nor very intuitive :) (Not that you ever claimed it was…)

> About groupby keywords in function or classes:
> 
> Stata and SAS have something like this (or strata) in some of the functions/procedures.
> In general I'm very skeptical that they are worth the code complication given that in most cases pandas or similar can easily be used for this.
> The main problem is that it is recursive, that is we have a loop inside the function or model that loops over itself. So, to keep it simpler we need an extra function for the core computation for a single group.

Yes, I agree so far.

> Then, it might be easier to add a wrapper code that extends or applies pandas groupby to stats functions that are not covered by pandas.

I am not quite sure I understand your proposal. Are you saying – contrary to what was mentioned above – that we could indeed support a `(group)by` argument in statsmodels, and internally use pandas' groupby to do the split-apply-combine heavy-lifting? Because that would have been my approach of choice :) Or am I misunderstanding what you wrote?

> a possible more generic addition to pandas would be to support named tuples and convert them to a series.

I'd thought about this too, but:

> However, the type of the named tuple is the actual named tuple class, so there is no easy instance check.

I'm afraid that's a deal breaker. However, I searched the pandas issue tracker and could not find a related issue, so it might in fact be worth asking the pandas devs?

Then again, the returned results would not include (imho vital) information like degrees of freedom, which I would definitely want to add to the output.

**Comment by josef-pkt** [comment]
> df.groupby('C')['A', 'B'].apply(ttest)

Actually, I find this pretty logical, use dataframe df groupby C and apply ttest for columns A and B.
But, if ttest doesn't return the required Series, then a lambda or extra function is needed.

> I am not quite sure I understand your proposal. Are you saying – contrary to what was mentioned above – that we could indeed support a (group)by argument in statsmodels, and internally use pandas' groupby to do the split-apply-combine heavy-lifting?

I meant that we implement a statsmodels groupby function that wraps/uses other functions for the computation.
sm.groupby(ttest, ...)
which could also be a statsmodels internal function just for the implementation.

The main question is API and code duplication: i.e. 
Do we create a new public function for each wrapped function, e.g. those in scipy.stats that are not available in statsmodels or do we create a generic wrapper like the above sm.groupby?
How do we handle different argument types and different return types? i.e. with separate function or multiple argument structures (e,g, related to OLS versus ols = OLS.from_formula)

Another, older, motivation to duplicate scipy.stats functions is to provide more returns than scipy.stats does. So far this was motivated by returning a results instance with more information, like degrees of freedom or which p-value distribution, and a `__str__` or summary.)

**Comment by hoechenberger** [comment]
>> df.groupby('C')['A', 'B'].apply(ttest)

> Actually, I find this pretty logical, use dataframe df groupby C and apply ttest for columns A and B.
> But, if ttest doesn't return the required Series, then a lambda or extra function is needed.

So the "simplest" approach would be to have a wrapper function that actually returns a `Series`, but we'd rather generate a statsmodels "results class" instead. What about supporting an `as_series()` method then?

```python
class TtestResults(...):
    ...
    def as_series(self):
        return pd.Series(...)

def ttest(..., as_series=False):
    ...
    result = TtestResults(...)

    if not as_series:
        return result
    else:
        return result.as_series()

df.groupby('C')['A', 'B'].apply(ttest, as_series=True)
```

Not too sexy though… but would do the job?

> I meant that we implement a statsmodels groupby function that wraps/uses other functions for the computation.
> sm.groupby(ttest, ...)
> which could also be a statsmodels internal function just for the implementation.

Ah, now I understand. This sounds quite reasonable indeed.

So we could have sth. like:

```python
def _ttest(a, b):
    """Do the actual t-test.
    """
    ...
    return TtestResults(...)


def ttest(a, b, data=None, groupby=None):
    if data is None:
        return _ttest(a, b)

    if groupby is None:
        return _ttest(data[a], data[b])
    else:
        return sm._groupby(_ttest, args=(data[a], data[b]), by=groupby)
```

The questions is _what_ `sm._groupby()` would actually return? A list of `Summary` or `Results` objects? A `DataFrame`? What would the API look like in the latter case? Following my previous proposals, it could look like:

```python
def _ttest(a, b, as_series):
    """Do the actual t-test.
    """
    ...
    r =  TtestResults(...)
    if not as_series:
        return r
    else:
        return r.as_series()


def _groupby(func, func_args, by, return_dataframe):
    results = []
    for group in by:
        ...
        r = func(func_args)
        results.append(r)
    
    if not return_dataframe:
        return results
    else:
        return gen_df_from_results(results)


def ttest(a, b, data=None, as_series=False, groupby=None):
    if data is None:
        return _ttest(a, b, as_series)

    if groupby is None:
        return _ttest(data[a], data[b], as_series)
    else:
        if as_series:
            return_dataframe = True
        else:
            return_dataframe = False
        
        return sm._groupby(_ttest, args=(data[a], data[b], as_series), by=groupby,
                           return_dataframe=return_dataframe)
```

Or we have sth like a `GroupbySummary` object with a `as_dataframe()` method or so?

> The main question is API and code duplication: i.e.
> Do we create a new public function for each wrapped function, e.g. those in scipy.stats that are not available in statsmodels or do we create a generic wrapper like the above sm.groupby?

The first proposal (separate public functions for each wrapped function) would be the easiest to start with; however it would indeed cause some code duplication. But maybe that's acceptable for a beginning and can be refactored later?

> How do we handle different argument types and different return types? i.e. with separate function or multiple argument structures (e,g, related to OLS versus ols = OLS.from_formula)

No idea on this one.

> Another, older, motivation to duplicate scipy.stats functions is to provide more returns than scipy.stats does. So far this was motivated by returning a results instance with more information, like degrees of freedom or which p-value distribution, and a __str__ or summary.)

Yes, this seems very reasonable and is also one of the my motivations. Although I'm wondering if it wouldn't be too hard to add this to SciPy itself?

Phew… that's really a lot of questions and uncertainties!

**Comment by josef-pkt** [comment]
Another idea:

We expand the requirement for the new or wrapping functions to also work with xarray (and indirectly with dask arrays) and possibly later to other dataframe_likes.
If we manage to make this also available for out-of-memory computation, then it would be worth quite a bit of code duplication, IMO. 

If we start with hypothesis test in scipy.stats, then the pattern of the function API would be all similar, i.e. they all have the same return dimension, in contrast to including, e.g., correlatation matrices that have 2-D returns. There are also not a huge number of those.

For example, we could add those functions then into a new module statsmodels.stats.groupbystats.

**Comment by josef-pkt** [comment]
just another thought

groupby is very similar to vectorized version of those functions when the individual samples/groups don't have the same number of observations. 
The groupby is more difficult than vectorization in many case, but we already have a vectorized results class that we use for the LikelihoodModelResults.t_test return.

Also, if we collect all the summary statistics, then we can return also the full params or contrast table as in ContrastResults for model based t_test, e.g. including confidence intervals. That would be possible for a later extension to wrapping a plain t_test. (I don't think it that would be available anytime soon, if ever, for the nonparametric hypothesis tests in scipy.stats.)

**Comment by josef-pkt** [comment]
related aside: I was just looking at http://xarray.pydata.org/en/stable/dask.html?highlight=dask#automatic-parallelization which does spearman with xarray and dask, but without scipy.

I would keep the 3 t-test separate at the beginning. In some cases I merged them in statsmodels, but in this case it is easier to begin with 3 separate implementation, e.g. When we drop missing values, then we drop them independently in ttest_ind, but row-wise (or for the difference array) in ttest_rel.

Some R functions have mixed those 3 t-tests together and the signature becomes messier, but we could still merge them later.

**Comment by josef-pkt** [comment]
It's not so easy to decide on the design without prototypes for several functions.
We might want to implement several patterns discussed in previous comments.
E.g. functions like the t-test are easy to implement from scratch with all extra options and returns. Some other functions in scipy.stats, especially some of the non-parametric tests, will not be easy, and for those using an internal generic groupby wrapper will be more convenient. It will not be useful to reimplement  fishers test or kendall tau correlation and maybe one of the normality tests.

(If I think longer about merging different t-tests, I'm getting more positive towards it, the main disadvantage is that some keywords are test specific.)

**Comment by hoechenberger** [comment]
I just came across a new package, [pingouin](https://pingouin-stats.org), that should cover most of the use cases we intended to address by wrappers support for `scipy.stats`... Will take a closer look at it!

**Comment by josef-pkt** [comment]
@hoechenberger 
In the Acknowledgement it says that some functions are translated from other packages. Given that some of those packages are not license compatible, the license for those functions cannot be BSD-3

**Comment by hoechenberger** [comment]
@josef-pkt Wow, good point. I didn't think of that. I will get in touch with the author and let him know about this potential problem.
