### ISSUE TITLE
py_kim_smoother dimensions

### ISSUE THREAD

**Issue by qlai** [statsmodels/statsmodels#4431]
hello i m trying to run a MarkovRegression with changing transition probabilities (exog_tvtp) 
```
toy= sm.tsa.MarkovRegression(np.arange(10)*1., 
                             k_regimes=2, 
                             exog = np.arange(30).reshape(10, 3) *1.,
                             trend = 'c',
                             order = 0,
                            exog_tvtp=np.arange(10) + 3.,
                                                        switching_exog = True, 
                                                        switching_variance = True)
toy.fit()


```

and have been getting errors in the kim_smoother:

> IndexError:  index 9 is out of bounds for axis 3 with size 9

(the SVD doesnt converge if I remove the exog_tvtp but this is a toy example to illustrate the dimension issue)
Could someone please point out why? Thank you!!

**Comment by ChadFulton** [comment]
Thanks for the report! However, this code runs for me with both version 0.8 and the version in Github master. Are you sure this code exactly is producing an error for you?

Also, it would be helpful if you could provide the full traceback of the exception.
