### ISSUE TITLE
VARResults._Omega_forc_cov, _bmat_forc_cov unused

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4433]
_bmat_forc_cov is used only by _omega_forc_cov, and omega_forc_cov's only use is commented-out in `forecast_cov`.  Are either of these useful?  Document or delete.

**Comment by josef-pkt** [comment]
My guess is that they are useful if they are used.
Both refer to Luetkepohl, so it needs checking what they are useful for.

My guess based on a brief look at the methods, is that those should be used to add parameter uncertainty to `forecast_cov`, which is currently not taken into account (neither is it in ARIMA, and I don't know about statespace models).

i.e. unfinished, but would be useful if someone works on the ENH.
