### ISSUE TITLE
seasonal_decompose shape mismatch

### ISSUE THREAD

**Issue by viveksck** [statsmodels/statsmodels#4438]
When trying to decompose a simple timeseries, I get a shape mismatch error in seasonal_decompose. I am hitting this error: https://stackoverflow.com/questions/42364901/seasonal-decompose-operands-could-not-be-broadcast-together-with-shapes-on-a-se?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa.  Note that I am already using statsmodels version 0.8.0 and pandas version 0.20.2. The stackoverflow conversation seems to have suggesed these versions fixed the issue for original reporter, but it looks like there still is a bug, since I am hitting it.

Trying to decompose the below results in:

ValueError                                Traceback (most recent call last)
<ipython-input-118-548d8d8dd7cf> in <module>()
      1 s=s.resample('W').pad()
      2 print s
----> 3 res=seasonal.seasonal_decompose(s)

/home/vvkulkarni/postdoc/local/lib/python2.7/site-packages/statsmodels/tsa/seasonal.pyc in seasonal_decompose(x, model, filt, freq, two_sided)
     99         detrended = x / trend
    100     else:
--> 101         detrended = x - trend
    102 
    103     period_averages = seasonal_mean(detrended, freq)

ValueError: operands could not be broadcast together with shapes (9,) (97,) 

res.plot()

This is "s" that is passed to seasonal_decompose.

2015-09-06    0.898750
2015-09-13    0.960740
2015-09-20    1.114529
2015-09-27    0.925981
2015-10-04    1.036009
2015-10-11    0.888222
2015-10-18    1.073268
2015-10-25    0.950488
2015-11-01    0.890973
Freq: W-SUN, dtype: float64

**Comment by josef-pkt** [comment]
Can you make a working example that I can quickly run to check if this is still a problem in master?

There were more changes since 0.8, but if there is still a problem then we should fix it fast, otherwise it would have to wait for 0.10.

**Comment by viveksck** [comment]
Just load the series attached in the  pickle file (attached) and call seasonal decompose. Just unzip the file and use the pickle file. 
[bug_seasonal.zip](https://github.com/statsmodels/statsmodels/files/1886825/bug_seasonal.zip)

s=pickle.load(open('bug_seasonal.pkl'))
res=seasonal.seasonal_decompose(s)

**Comment by josef-pkt** [comment]
pickles are version dependent, it doesn't load in my python 3.4 that I'm using for development and maintenance.

**Comment by bashtage** [comment]
seasonal_decompose is buggy for short time series that contains less than a full cycle.

**Comment by bashtage** [comment]
seaonal_decompose now requires two complete cycles, which is the same as R.
