### ISSUE TITLE
GLM docstring has 2 Attributes sections

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4447]

**Comment by josef-pkt** [comment]
Something changed in sphinx. I saw a while ago that those are now duplicate.
I haven't updated my sphinx yet to replicate locally.

**Comment by jbrockmendel** [comment]
Note the two sections are not identical, so it is not trivial to just go remove one of them.

**Comment by bashtage** [comment]
It looks like the second is right and the first is wrong, or at best, incomplete.
