### ISSUE TITLE
[WTF] inconsistently-defined `cloneattr` in ResultMixin.bootstrap

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4452]
in ResultsMixin.bootstrap:

```
                for attr in self.model.cloneattr:
                    setattr(fitmod, attr, getattr(self.model, attr))
```

It looks like `self.cloneattr` is set in miscmodels.count_model, but nowhere else.

Users/contributors should not have to guess what attributes exist on model/results objects.

**Comment by josef-pkt** [comment]
try to write informative issue headers.
It's very difficult to go through the issue (or PR) list and figure out which is which and what is what.

There are old issues on cloning, and there are still unresolved design issues how to replicate models and results. (However, I think there are other attributes now used for this outside of GenericLikelihood)

**Comment by jbrockmendel** [comment]
Sure, will edit title.  I don't expect any of these to get fixed so am mostly opening them to have GH references to point to when raising downstream.

**Comment by josef-pkt** [comment]
see #4676 for example usage by user defined subclasses
#4679  for refactoring GenericLikelihoodModel
