### ISSUE TITLE
GenericLikelihoodModel.initialize sets self.score to approx_fprime

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4453]
... I don't think that's going to work.

**Comment by jbrockmendel** [comment]
Also, sure would be nice if `fixed_paramsmask` was set in a predictable way.

**Comment by josef-pkt** [comment]
needs review

E.g. I haven't looked at`fixed_paramsmask` in many years
AFAIK, it didn't get implemented much outside of GenericLikelihoodModels, but it has a unit tested example use case
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/miscmodels/tmodel.py#L59

(equality constraints for nonlinear optimization are another medium/long term wishlist item. fit_constrained only allows constraints on the parameters associated with exog.)

**Comment by josef-pkt** [comment]
> base.model was uniformly in good condition

GenericLikelihoodModel is intentionally the "dirty" cousin of LikelihoodModel. It is supposed to have a default for everything except loglike, while the cleaner LikelihoodModel assumes that the subclasses provide all the missing pieces.

This does not mean that it has to be very dirty, and it could get another **round**.
Another issue that is open is that some of the GenericLM things can be moved to LM.

(e.g. I also just found that df_resid, df_model defautls don't work in a simple scipy.stats.distribution wrapper, on mailing list.)
