### ISSUE TITLE
SARIMAX help please

### ISSUE THREAD

**Issue by denizn** [statsmodels/statsmodels#4456]
When I am fitting the model I am using demand data which is observed data which is the value I want to forecast for the future.
For exogenous variables should I input only "train" or should I include "test data during fitting?

mod = sm.tsa.statespace.SARIMAX(train['demand'],
                                exog=train_large.drop('demand',axis=1),
                                order=min_index[0],
                                seasonal_order=min_index[1],
                                enforce_stationarity=False,
                                enforce_invertibility=False,
                               )
results = mod.fit()
predictions=results.predict(params=[0,0,1],exog=test_large.drop('demand',axis=1),end='2018-04-08')

**Comment by ChadFulton** [comment]
When you use `results.predict`, you do not need to pass in parameters. To predict with `exog`, you need to pass `exog` values for time period that is being forecast.

For example, if your `train` dataset goes through 2018-03-31 and you are predicting through 2018-04-08 then the `exog` dataset you pass to `results.predict` should exactly for the period 2018-04-01 to 2018-04-08.

**Comment by deniznoah** [comment]
Chad,

Very clear, thanks!

In terms of "multiplicative" variables. Is there a way do define them in the regression?

I have promotions in my data which would mean the "discount percentage" exogenous variable I am passing into would more likely have a "multiplicative impact". How would I be able to implement that into this model?

Thank you for your help,
Deniz.

**Comment by deniznoah** [comment]
Also, does SARIMAX automatically remove seasonality or do I need to use seasonal_decompose? I am very confused about which order the model works.

Is it trend=>seasonality=>external regressors?

**Comment by ChadFulton** [comment]
> In terms of "multiplicative" variables. Is there a way do define them in the regression?
> 
> I have promotions in my data which would mean the "discount percentage" exogenous variable I am passing into would more likely have a "multiplicative impact". How would I be able to implement that into this model?

SARIMAX is a linear model, so exogenous regressors can only enter in linearly. If all of your regressors were multiplicative, you might try a log transformation.

> Also, does SARIMAX automatically remove seasonality or do I need to use seasonal_decompose? I am very confused about which order the model works.

SARIMAX can model seasonality if you use the `seasonal_order` argument.

> Is it trend=>seasonality=>external regressors?

It doesn't work in a particular order, everything is modeled simultaneously.

**Comment by deniznoah** [comment]
Chad,

Thank you very much for this.

Any tips on how would I do the log transformation?

Thank you,
Deniz.

**Comment by deniznoah** [comment]
Also, what if I use the x^2 instead of x for external regressors. Would that work?

**Comment by deniznoah** [comment]
Lets say i have promo percentage and number of stores. I would like to square (1/(1-pp)) * #of stores and use it in my Sarimax as an external regressor. Does this make sense ?

**Comment by ChadFulton** [comment]
> Also, what if I use the x^2 instead of x for external regressors. Would that work?

Yes, that would work.

> Lets say i have promo percentage and number of stores. I would like to square (1/(1-pp)) * #of stores and use it in my Sarimax as an external regressor. Does this make sense ?

Any regressor you can construct can be used as part of `exog`, so that sounds like it would work to me.

**Comment by ChadFulton** [comment]
This very much depends on your application, there is no "standard way" to do this. However, if you believe that your data follows the following pattern:

y_t = x_t^b * eps_t

where x_t are your exogenous variables and eps_t is distributed log normal, then you could take logs of each side:

log y_t = b * log(x_t) + log eps_t

Practically, the only change you'd need would just be to pass log y_t as `endog` and log x_t as `exog.

But again, I don't know what your application is, or what kind of multiplicative effects you think may exist, or if this would be appropriate.

**Comment by deniznoah** [comment]
Chad,

I am trying to forecast demand in retail depending on different periods (Christmas, Easter) and promotions. However I get negative values at times. How would I be able to enforce positivity in this model?

Thank you,
Deniz

**Comment by ChadFulton** [comment]
> I am trying to forecast demand in retail depending on different periods (Christmas, Easter) and promotions. However I get negative values at times. How would I be able to enforce positivity in this model?

One option is to model the `np.log` of the variable, and then transform the forecasts back to the original space using `np.exp`.

**Comment by deniznoah** [comment]
Would I have to use np.log on the history of the variable I am trying to forecast? Do I need to alter any other variables (External regressors)?

Thanks!

**Comment by deniznoah** [comment]
Chad,

When I am trying to fit the model I get below error which I could not understand. Can you please help me with what I should be doing?

Thanks,

ValueError                                Traceback (most recent call last)
<ipython-input-170-86a5df04e925> in <module>()
     85                                 )
     86 
---> 87 results = mod.fit(maxiter=200)
     88 
     89 predictions = results.forecast(steps=horizon,exog=exogg.asfreq('7D'))

~\AppData\Local\Continuum\anaconda3\envs\data\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py in fit(self, start_params, transformed, cov_type, cov_kwds, method, maxiter, full_output, disp, callback, return_params, optim_score, optim_complex_step, optim_hessian, **kwargs)
    401         """
    402         if start_params is None:
--> 403             start_params = self.start_params
    404             transformed = True
    405 

~\AppData\Local\Continuum\anaconda3\envs\data\lib\site-packages\statsmodels\tsa\statespace\sarimax.py in start_params(self)
   1007             self._conditional_sum_squares(
   1008                 endog, self.k_seasonal_ar, self.polynomial_seasonal_ar,
-> 1009                 self.k_seasonal_ma, self.polynomial_seasonal_ma
   1010             )
   1011         )

~\AppData\Local\Continuum\anaconda3\envs\data\lib\site-packages\statsmodels\tsa\statespace\sarimax.py in _conditional_sum_squares(endog, k_ar, polynomial_ar, k_ma, polynomial_ma, k_trend, trend_data)
    899             if k_ar > 0:
    900                 cols = polynomial_ar.nonzero()[0][1:] - 1
--> 901                 X = np.c_[X, lagmat(endog, k_ar)[r:, cols]]
    902             if k_ma > 0:
    903                 cols = polynomial_ma.nonzero()[0][1:] - 1

~\AppData\Local\Continuum\anaconda3\envs\data\lib\site-packages\statsmodels\tsa\tsatools.py in lagmat(x, maxlag, trim, original, use_pandas)
    377         dropidx = nvar
    378     if maxlag >= nobs:
--> 379         raise ValueError("maxlag should be < nobs")
    380     lm = np.zeros((nobs + maxlag, nvar * (maxlag + 1)))
    381     for k in range(0, int(maxlag + 1)):

ValueError: maxlag should be < nobs

**Comment by ChadFulton** [comment]
> Would I have to use np.log on the history of the variable I am trying to forecast?

You would use `np.log` on the variable you're passing to SARIMAX. So instead of:

```python
y = [your original data]
mod = sm.tsa.SARIMAX(y)
res = mod.fit()

forecasts = res.forecast(10)
```

You would do:

```python
logy = np.log(y)
mod = sm.tsa.SARIMAX(y)
res = mod.fit()

forecasts = np.exp(res.forecast(10))
```

> Do I need to alter any other variables (External regressors)?

This depends on your data and the underling model you have in mind. SARIMAX with `exog` is just regression with SARIMA errors, so you'd have the same considerations as you would with any regression model specified in logs versus levels.

**Comment by deniznoah** [comment]
Did you mean logy instead of y here?

logy = np.log(y)
mod = sm.tsa.SARIMAX(**logy**)
res = mod.fit()

forecasts = np.exp(res.forecast(10))

**Comment by ChadFulton** [comment]
> Did you mean logy instead of y here?

Yes exactly, thanks!

**Comment by deniznoah** [comment]
Chad,

Would I have to take the np.log of every external regressor that I am feeding in as well?

I have done exactly as you described and it did get rid of negatives; however, I also noticed that it got rid of the peaks it used to have. Is this normal?

Thank you,
Deniz.

**Comment by deniznoah** [comment]
Also, would I be able to make partial log transformation to keep some regressors multiplicative and some as additive?

Thank you,
Deniz

**Comment by deniznoah** [comment]
Chad,

I have made the log transformation and the model started to work extremely well all of a sudden.

It just gives below error "divide by zero encountered in log" on some SKUs that have occasional "zero" data. What would be the best way to solve it?

C:\Users\ndnu2\AppData\Local\Continuum\anaconda3\envs\data\lib\site-packages\statsmodels\base\model.py:496: ConvergenceWarning:

Maximum Likelihood optimization failed to converge. Check mle_retvals

C:\Users\ndnu2\AppData\Local\Continuum\anaconda3\envs\data\lib\site-packages\statsmodels\tools\numdiff.py:96: RuntimeWarning:

invalid value encountered in maximum

Deniz

**Comment by josef-pkt** [comment]
> Also, would I be able to make partial log transformation to keep some regressors multiplicative and some as additive?

regressors can be log transformed purely from an application context, i.e. what makes sense. There is no requirement to log all or None, and dummy variables cannot be log transformed anyway.

>It just gives below error "divide by zero encountered in log" on some SKUs that have occasional "zero" data. What would be the best way to solve it?

One common approach if there are zeros in the observations, is to add 1 before taking the log, i.e. log(1 + y).

**Comment by ChadFulton** [comment]
> One common approach if there are zeros in the observations, is to add 1 before taking the log, i.e. log(1 + y).

This is a good idea.

Another approach (if these errors are appearing when you're taking the log of the `endog` variable) might be to replace the zero values in the dataset with `np.nan`. In this case, it will be as if that observation was "missing", which I think is conceptually consistent the log transformation, since by doing that you're excluding from your domain the possibility of observations that are truly equal to zero.

**Comment by deniznoah** [comment]
I have been trying different AIC levels to fit my model and use it to forecast.

For this case, I am sharing below, the model selected was [(0, 1, 1), (1, 0, 0, 52)].

The problem I have currently is that it the base of the forecast is much much higher than the current one. Can you please help me understand which parameter I should modify? Is it the moving average?

![download](https://user-images.githubusercontent.com/35758436/39736684-88fc98fe-52c4-11e8-984b-15e43f17f651.png)

**Comment by jbrockmendel** [comment]
closeable?
