### ISSUE TITLE
anaconda3-4.2.0+python3.5 +ImportError: cannot import name 'getargspec'

### ISSUE THREAD

**Issue by datadiviner** [statsmodels/statsmodels#4466]
----> 2 from statsmodels.graphics.tsaplots import plot_acf
      3 plot_acf(data).show()

D:\Anaconda3\lib\site-packages\statsmodels\graphics\tsaplots.py in <module>()
      6 from statsmodels.compat.pandas import sort_values
      7 from statsmodels.graphics import utils
----> 8 from statsmodels.tsa.stattools import acf, pacf
      9 
     10 

D:\Anaconda3\lib\site-packages\statsmodels\tsa\stattools.py in <module>()
     10 from scipy import stats
     11 
---> 12 from statsmodels.regression.linear_model import OLS, yule_walker
     13 from statsmodels.tools.tools import add_constant, Bunch
     14 from statsmodels.tsa.tsatools import lagmat, lagmat2ds, add_trend

D:\Anaconda3\lib\site-packages\statsmodels\regression\__init__.py in <module>()
----> 1 from .linear_model import yule_walker
      2 
      3 from statsmodels import NoseWrapper as Tester
      4 test = Tester().test

D:\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py in <module>()
     51                                           cache_readonly,
     52                                           cache_writable)
---> 53 import statsmodels.base.model as base
     54 import statsmodels.base.wrapper as wrap
     55 from statsmodels.emplike.elregress import _ELRegOpts

D:\Anaconda3\lib\site-packages\statsmodels\base\model.py in <module>()
      8 from statsmodels.stats.contrast import ContrastResults, WaldTestResults
      9 from statsmodels.tools.decorators import resettable_cache, cache_readonly
---> 10 import statsmodels.base.wrapper as wrap
     11 from statsmodels.tools.numdiff import approx_fprime
     12 from statsmodels.tools.sm_exceptions import ValueWarning, \

D:\Anaconda3\lib\site-packages\statsmodels\base\wrapper.py in <module>()
      3 
      4 import numpy as np
----> 5 from statsmodels.compat.python import get_function_name, iteritems, getargspec
      6 
      7 class ResultsWrapper(object):

ImportError: cannot import name 'getargspec'

**Comment by bashtage** [comment]
This is no longer an issue in master.
