### ISSUE TITLE
Whats the point of ConstrastResults.__array__?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4470]

**Comment by josef-pkt** [comment]
interesting question: Can this be useful for something? e.g. asarray(tres)

I think that predates statsmodels and has never been removed.

**Comment by jbrockmendel** [comment]
Thanks.  I'll remove this downstream, will make a PR here circa 2028.

**Comment by jbrockmendel** [comment]
Accept a PR removing this?
