### ISSUE TITLE
FAQ: tsa.stattools.q_stat and acorr_ljungbox

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4472]

**Comment by kaoutaar** [comment]
However, they don't provide the same result. Anyone has an idea why is this ?

**Comment by bashtage** [comment]
`acorr_ljungbox  is current and more general. `q_stat` shoule be deprecated and removed eventually.

**Comment by bashtage** [comment]
These two are difference and take different inputs.
