### ISSUE TITLE
WLS fit_regularized

### ISSUE THREAD

**Issue by ghost** [statsmodels/statsmodels#4475]
I have no problem using WLS.fit() or OLS.fit_regularized() but what I really want is WLS.fit_regularized. When I try that I get the following: AttributeError: 'WLS' object has no attribute 'fit_regularized'. Has this not been implemented?

**Comment by jbrockmendel** [comment]
It looks like WLS.fit_regularized exists in master, but not in 0.8.0 (the most recent release).
