### ISSUE TITLE
Johansen's cointegration test

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#448]
asked for in  http://stackoverflow.com/questions/12186994/johansen-cointegration-test-in-python

one implementation http://www.spatial-econometrics.com/coint/johansen.m
("Anyone is free to use these routines, no attribution (or blame) need be placed on the author/authors." instead of an recognized license)

**Comment by esvhd** [comment]
So glad to have found this page. Since I've been trying to do the some conversion from matlab based on the same source code... 

It would be great if this can be added to the next statsmodels release. Watching this space...

**Comment by georgewatts** [comment]
I too would like to know if this is actively being worked on. Happy to commit hours to help with development if necessary.

**Comment by josef-pkt** [comment]
@georgewatts Nobody is currently working on it. We have a proposal for GSOC for VECM, but any decisions are still weeks away.
The idea would be to build the full VECM model instead of doing the calculations inside the hypothesis test function.

I was thinking of putting this (#453) in the statsmodels.sandbox so it's at least available.
The two main things are, first, to check the option and p-values. I'm not sure anymore that we don't have a case that might not have correct p-values (i.e. more cases than in the original tables)
Checking this against an independent implementation like R or Stata or some other package would be useful. 
(I also never checked whether there are newer, updated tables for the critical values or for p-values in the literature.)

The second item is to review the API. AFAIR, there is an extra return or parameter that is not really necessary in this implementation.

I can look at it if someone helps out with the work, especially with respect to verifying the results.
Based on the earlier feedback, the implementation of the test itself is pretty good.

Thanks

**Comment by tsando** [comment]
Can anyone advice how I can install a version of statsmodels with this test? I installed the latest stable release 0.8.0 for python 3.5 but the module `vecm` isn't part if `vectort_ar` and there seems to be a lot of dependencies. Thanks for your help!

**Comment by jengelman** [comment]
@tsando vecm has been merged into master, build from source and try the following:

`from statsmodels.tsa.vector_ar.vecm import coint_johansen`

**Comment by tsando** [comment]
thanks for the note @jengelman -  it's great to know this has happened at last! btw, after which version has this been merged?

**Comment by M-oplo** [comment]
@vivanov879 @josef-pkt @jseabold  @FCJW @esvhd 
I got the same error.
May I ask how would you do lag order selection? I used AIC / BIC criterion to select the lag oder of a time series, and lag is returned by [ADF test](https://www.statsmodels.org/stable/generated/statsmodels.tsa.stattools.adfuller.html) result. And I used the returned value as 'lag' input in the Johansen test. Below is my code:

from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.vector_ar.vecm import coint_johansen
# get lag from ADF test
lag_oder = adfuller(series)[2]
# pass lag to johansen test
johansen = coint_johansen(seriesGroup, 0, lag)

Any comments? Thanks in advance!
