### ISSUE TITLE
statsmodels/statsmodels/tsa/vector_ar/dynamic.py has outdated functions in pandas

### ISSUE THREAD

**Issue by ifancycoding** [statsmodels/statsmodels#4480]
There is an error when I use "DynamicVAR":
AttributeError: module 'pandas' has no attribute 'ols'

**Comment by jbrockmendel** [comment]
DynamicVAR is de-facto unsupported/deprecated.

**Comment by jengelman** [comment]
@ifancycoding Removing DynamicVAR is on the to-do list for the next release (see #3866).  I would recommend switching to VARMAX (and the state space framework in general), which have almost all of the same features, and the rest (like nice plots of state evolution) are works in progress (see #4182).

**Comment by ifancycoding** [comment]
Thank you for your work！

**Comment by robbiemu** [comment]
how do you get an expanding window with VARMAX ?
