### ISSUE TITLE
vecm coint_johansen resid definition

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4486]
This may be entirely correct, but it looks weird to me and may merit a comment explaining what its doing (i.e. that it is intentional):

```
    def resid(y, x):
        if x.size == 0:
            return y
        r = y - np.dot(x, np.dot(np.linalg.pinv(x), y))
        return r
```

That looks _almost_ like an OLS residual.  Is there another name for this kind of residual?

**Comment by josef-pkt** [comment]
This is just a standard multivariate OLS residual, or orthogonal projection. 
(This function should exist already several times.)

(coint_johansen is mostly "imported" code, that I wrote separately, and hasn't been better integrated with VECM yet.)

**Comment by jbrockmendel** [comment]
> This is just a standard multivariate OLS residual, or orthogonal projection

OK.  I'm used to seeing the residual as `Y - X(X'X)^-1X'Y`; this may merit a comment for the next reader.

> coint_johansen is mostly "imported" code, that I wrote separately, and hasn't been better integrated with VECM yet

If it doesn't have a strong attachment to this module, I strongly advocate a `tsa.unitroot` module with this and other unit root-related tests currently located in tsastats.

And in the name of decency: #4487.
