### ISSUE TITLE
holtwinters.py define additive/multiplicative error?

### ISSUE THREAD

**Issue by noklam** [statsmodels/statsmodels#4489]
@tvanzyl  Thanks for the contribution. Is there a way to define the error as multiplicative or additive? I only find parameters for Trends and Seasonality.

Having experience with the ets() function in R. Which should have 3 parameters for Errors, Trends, and Seasonality, and it will automatically choose the best combination, it there an easy way to achieve this? Thanks!

https://github.com/robjhyndman/forecast/blob/master/R/ets.R

**Comment by tvanzyl** [comment]
Unfortunately at this point the model doesn't allow you to specify the type of error. Also we do not automatically pick a model for you. Instead you would have to loop through the models.

**Comment by s-scherrer** [comment]
The new ETS implementation in statsmodels/tsa/exponential_smoothing/ets.py implements both error models.
