### ISSUE TITLE
coint_johansen returned object has unhelpful names

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4496]
```
    result = Holder()
    # estimation results, residuals
    result.rkt = rkt
    result.r0t = r0t
    result.eig = a
    result.evec = d
    result.lr1 = lr1
    result.lr2 = lr2
    result.cvt = cvt
    result.cvm = cvm
    result.ind = aind
    result.meth = 'johansen'
```

I can make guesses as to what `eig`, `evec`, and `meth` are.  For the rest I'd have to look at the function docstring.  As a stand-alone object the returned Holder is otherwise opaque.

**Comment by jbrockmendel** [comment]
... the docstring mixes "meth" --> "method".

And if I don't happen to have the reference textbook in front of me, I'm out of luck,

**Comment by bashtage** [comment]
Fixed in master.

**Comment by bashtage** [comment]
As much as can be done.
