### ISSUE TITLE
statsmodels versionning

### ISSUE THREAD

**Issue by farquet** [statsmodels/statsmodels#4503]
Hello,
People are looking forward to see the 0.9 release. It seems it will be out soon, but there will be a gap of 2 years between 0.8 and 0.9.
It would interesting to use SemVer (https://semver.org/) as a rule for the next releases. That would give more frequent releases and bug fixes, allow deprecation warnings in the minor releases before the jump to the next big release, reduce the pressure from the numpy people and the risk of breaking changes for the users, etc.
Reasons are numerous for more frequent releases and I hope this could be something the statsmodels team would consider.

**Comment by TomAugspurger** [comment]
I think the main bottleneck is lack of developers / maintainers who have time to issue a release. More build automation (https://github.com/statsmodels/statsmodels/issues/4058) or any funding for developers would be more helpful.

**Comment by jbrockmendel** [comment]
@farquet if you need something to hold you over [sm2](https://github.com/jbrockmendel/sm2) might be helpful.  It's a fork intended to serve as a 0.8.x for `x!=0`.

**Comment by josef-pkt** [comment]
Our version numbering is fine, but as Tom pointed out our release management is understaffed (as are many other maintenance and review tasks).

The idea of more frequent releases is good, but fails so far because of ...

**Comment by josef-pkt** [comment]
closing because there are other issues that also discussed release frequency and similar.
