### ISSUE TITLE
Roadmap release 0.10

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4507]
collecting smaller things that I'm postponing to 0.10

- [ ] #1880 GLM family, make link check optional

**Comment by josef-pkt** [comment]
I started a new project 0.9 which makes it simpler to add items https://github.com/statsmodels/statsmodels/projects/9

**Comment by bashtage** [comment]
This ship has sailed. Will need a new milestone, and someone to work on it.
