### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by JackCaster** [statsmodels/statsmodels#4531]
I have noticed that the documentation on the [website](http://www.statsmodels.org/stable/) is outdated and does not reflect the changes made on the source. 
For example, in [Using formulas with models that do not (yet) support them](http://www.statsmodels.org/stable/example_formulas.html#using-formulas-with-models-that-do-not-yet-support-them) there is a mistake about how to get a design matrix instead of a dataframe. This was fixed in #4180, but the documentation has not been updated accordingly. Can I help in any way?

**Comment by josef-pkt** [comment]
Unfortunately the doc build hasn't been updated in a long time.
We have automatic build on travis-ci, but currently we don't have the supporting code to automatically push it to the github website.

(The complete docs can only be built on a case sensitive operating system. I'm on Windows and it breaks for modules, functions or classes that are only distinguishable by case.)

**Comment by JackCaster** [comment]
I am on MAC. I could build the documentation, get the html code and create a pull request [here](https://github.com/statsmodels/statsmodels.github.io). Would that work?

**Comment by josef-pkt** [comment]
The new docs should be ready in 2 or 3 days, then it would be very helpful if the docs are updated.
We should have then the docs for 0.9 (rc) and for 0.10 as the new devel.

**Comment by josef-pkt** [comment]
I just released 0.9.0 https://pypi.org/project/statsmodels/
So now it would be good to have the new documentation.

volunteer?

**Comment by TomAugspurger** [comment]
Taking a look now. Will do a build if all goes well.

I can also take a look at getting doctr up and running. I think I had a branch somewhere.

**Comment by TomAugspurger** [comment]
Built and uploaded in https://github.com/statsmodels/statsmodels.github.io/commit/cf6a83bfce51c31767338112fda2de832134cf74.

Should be live now.

**Comment by enlighter** [comment]
So is this issue resolved, or does further work need to be done under this issue?

**Comment by bashtage** [comment]
@josef-pkt This can be closed.
