### ISSUE TITLE
FutureWarning from pandas

### ISSUE THREAD

**Issue by mikkokotila** [statsmodels/statsmodels#4562]
Do you have plans to do something about using the datetools in order to avoid the FutureWarning as per below:

```
/Users/mikko/dev/a_test/lib/python2.7/site-packages/statsmodels/compat/pandas.py:56: 

FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
```

It seems to come from statsmodels/compat/pandas.py

**Comment by TomAugspurger** [comment]
Fixed in master by https://github.com/statsmodels/statsmodels/pull/3618

A release candidate is being worked on, hopefully ready soon. Follow the mailing list for updates: https://groups.google.com/forum/#!forum/pystatsmodels

**Comment by mikkokotila** [comment]
Thanks! :)
