### ISSUE TITLE
MAINT: release 0.9rc1 to 0.9 final

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4573]
things that should be checked or changed for 0.9.0 final

- maintainer in setup show up as authors on pypi - switch to "Statsmodels developers"
- check attribution of rotation code, add more explicit attribution if missing/incomplete
- for 0.9 release to pypi from tag and not from branch ? Does it make a difference?
-

- add power notebook #4091

**Comment by jbrockmendel** [comment]
closeable?

**Comment by bashtage** [comment]
#4091seems to be far from ready, and the original author has no time to pick it up.

> check attribution of rotation code, add more explicit attribution if missing/incomplete

Which code is this?

**Comment by bashtage** [comment]
No longer relevant.
