### ISSUE TITLE
BUG: t_test, f_test and wald_test have unused `scale` argument

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4589]
AFAICS, the scale argument is never used inside those methods.

maybe left over from a previous version
The same end result can be achieved by providing rescaled covp instead of scale for temporary changes or cov_type in fit for permanent scaling of cov_params.

cov_params method also has scale argument, which is ignored if cov_params_default is an attribute. so maybe this was intended to be used in the call to cov_params.

AFAIR, I never ran into a issue or example where we want to change the scale for the Wald tests.

**Comment by bashtage** [comment]
Closed by #5614
