### ISSUE TITLE
NaN-robust PCA?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4592]
Standard PCA assumes no-missing-data.  There are some generalizations that are robust to missing data.  Does statsmodels have one of these hidden somewhere?

I'd look myself if there were a reliable way to [distinguish](https://github.com/statsmodels/statsmodels/issues/4423) usable code from everything else (and a predictable relationship between what a [function does](https://github.com/statsmodels/statsmodels/pull/4477) and [where it is located](https://github.com/statsmodels/statsmodels/pull/4467)).

**Comment by josef-pkt** [comment]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/multivariate/pca.py#L63

(I merged it but didn't play with this part of it.)

pandas also has cov functions that include missing handling.

**Comment by bashtage** [comment]
`PCA` support using the E-M algorithm to handle missing data.
