### ISSUE TITLE
BUG/ENH: fit_regularized elasticnet does not show non-convergence

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4607]
I didn't get results with GLM fit_regularized with alpha=0 that match the unpenalized fit.

The problem is that maxiter was reached before convergence. There is no warning or `converged` attribute or mle_retvals to show the information about convergence status.

If I start with the unpenalized res.params as start_values, then fit_regularized returns immediately.

(I'm using Star98 dataset with GLM-Binomial with and without counts, using proportions and no n_trials)

**Comment by choforito84** [comment]
I had this same problem using High dimensional data (p=4088, n=71). Any update?

**Comment by kshedden** [comment]
Closed by #6697
