### ISSUE TITLE
Possibility of "Contrib" section for modules with GPL license?

### ISSUE THREAD

**Issue by ashimb9** [statsmodels/statsmodels#4615]
Hi -- As the title suggests, would the statsmodels team be open to a "contrib" section in the manner of [Scikit Learn contrib](https://github.com/scikit-learn-contrib) for packages with copy-left and/or non-BSD3 licenses (although that is of course not exactly the purpose of sklearn contrib). To be more specific, I am working on porting over some non-parametric regression packages from R to Python but they are all GPL licensed and since I will use their source as a guide I will of course have to license the Python version as GPL too. However, before going into too much detail regarding which specific packages etc. I was wondering if you guys were conceptually open to the idea. In any case, I would much appreciate any feedback. Thank you.

**Comment by josef-pkt** [comment]
I don't think that's a good idea for us, it's too dangerous for license contamination.

There are some packages separate from statsmodels that are essentially translation from R to Python, or sometimes from the underlying Fortran code in R to a Python wrapped Fortran code.
I essentially ignore those packages when I see them on github, except for maybe spot checking which methods are covered if the documentation is not explicit enough.

The main point is that we are supposed to not look at the code and we cannot review it if we want to implement something similar in Python under BSD or MIT.

For smaller R packages with one or only a few authors, those authors were  in some cases willing to give permission to translate under BSD/MIT, However, I think that will not be possible for any large packages that has seen many authors or contributors over the lifetime of the package.

Its unfortunate for us that GPL versus BSD/MIT is not a two-way street, but with statsmodels and other packages for statistics/data analysis in Python, in Julia, and some other packages, it is starting to look better for our license neighborhood. (E.g. one of our social contributions is that everyone can look and copy our GLM code which I have seen referenced or copied in several places.)

But there are still large gaps where I would love to translate R code for specific parts or have access to translated version, but that's just not possible.

**Comment by bashtage** [comment]
I think GPL will need to be a different package.
