### ISSUE TITLE
BUG: GLM fit_irls  wls_method hard coded

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4626]
I don't know what's going on here.

In current master fit method is hard coded as 'lstsq'

```
            wls_results = reg_tools._MinimalWLS(
                    wlsendog,
                    wlsexog,
                    self.weights).fit(method='lstsq')
```

I thought I had changed this to using wls_method option

https://github.com/statsmodels/statsmodels/pull/4021/files#diff-724e15f4019b2a24906f6b271d67e370L1103

needs checking to see what's going on (or if my memory is wrong)

**Comment by josef-pkt** [comment]
I guess this is a mistake in a rebase, maybe merge conflict resolution

this commit reverted the wls_method
https://github.com/statsmodels/statsmodels/commit/78dcce22993de5b11e07f8636e3e474c535707ac

**Comment by thequackdaddy** [comment]
Whoops. I have no idea why I would’ve done that.

I’ll make a PR ago revert.

**Comment by josef-pkt** [comment]
I think these problems easily happen during merge conflict resolution.
It is (almost) impossible to check this in a unit test because we don't get the information about what method was actually used.
