### ISSUE TITLE
Tracking issue for pip install test failures

### ISSUE THREAD

**Issue by matthew-brett** [statsmodels/statsmodels#4657]
Wheel builder here:

* https://github.com/MacPython/statsmodels-wheels

Current test results at:

* https://travis-ci.org/MacPython/statsmodels-wheels
* https://ci.appveyor.com/project/matthew-brett/statsmodels-wheels
* https://ci.appveyor.com/project/matthew-brett/statsmodels/build/1.0.6

Issues for all platforms, with pip:

* [ ]  #4656

Issues for Linux / macOS:

* [ ]  #4645 
* [ ]  #4643

For Windows:

* [ ]  #4672 
* [ ]  #4673 
* [ ]  #4674  
* [ ]  #4675

**Comment by josef-pkt** [comment]
@matthew-brett Thanks for collecting these

I labeled them as backport candidates.

My guess is that there are no bugs in the code. The tsa are most likely convergence problems and fragile unit tests.
I expect that only the imputation failure will require some code refactoring. #4648 

I will most likely look at the tsa cases next week. 
(The VAR/VECM unit tests are a inconvenient for a quick investigation because they are run in a loop over many models. It either needs installing a failing version to be able to get the break point in pdb, or extract the example from the unit tests.)

**Comment by matthew-brett** [comment]
Thanks for doing that.  Please let me know if there is anything I can do to help.

**Comment by josef-pkt** [comment]
Actually, there is something that you could do so I can test this.
I don't have a setup with OpenBLAS and I rely for most version testing on appveyor and travis. For versions that I don't have installed locally, I just have to guess about possible fixes.

It would be helpful if you could make a PR against statsmodels master with the `appveyor.yml` and `.travis.yml` that using the failing versions and tests against statsmodels master and PRs of it. 
We will not merge it into master, but we could use those to test possible fixes.

**Comment by matthew-brett** [comment]
Did you see #4652 ?  I can look at doing the same the for Appveyor ...

**Comment by josef-pkt** [comment]
No, I hadn't looked at 4652. I haven't caught up with all recent activity on github yet.

Thanks, looks good

**Comment by matthew-brett** [comment]
I added Windows pip testing to #4652 . This also revealed that y'all were not testing 32-bit Python 2 with conda - see: https://github.com/statsmodels/statsmodels/pull/4652/files#diff-180360612c6b8c4ed830919bbb4dd459R15

**Comment by josef-pkt** [comment]
We had windows 32-bit python for a while. We dropped it after some failure. 
I thought nobody is using 32-bit Python anymore.

Thanks

**Comment by josef-pkt** [comment]
aside: checking for 32/54 bit for SkipTests

`is_64bits = sys.maxsize > 2**32`
which seems to be more reliable than platform.architecture
https://docs.python.org/3/library/platform.html#platform.architecture

**Comment by matthew-brett** [comment]
I think 32-bit Python is still fairly common on Windows.  Running a [BigQuery check](https://packaging.python.org/guides/analyzing-pypi-package-downloads/) just now, for the last 30 days of downloads (counts | filename):

```
70636 | numpy-1.14.3-cp36-none-win_amd64.whl
38883 | numpy-1.14.3-cp36-none-win32.whl
```

So - 32-bit is still > 35% of Windows downloads.

Here's the BigQuery SQL

```
#standardSQL
SELECT
 COUNT(*) AS downloads,
 file.filename
FROM `the-psf.pypi.downloads*`
WHERE file.project = 'numpy'
  AND details.installer.name = 'pip'
  -- Only query the last 30 days of history
  AND _TABLE_SUFFIX
    BETWEEN FORMAT_DATE(
      '%Y%m%d', DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY))
    AND FORMAT_DATE('%Y%m%d', CURRENT_DATE())
GROUP BY
 file.filename
ORDER BY
 downloads DESC
LIMIT
 1000
```

**Comment by matthew-brett** [comment]
I've refactored the Windows issue into separate issues, one per failure.  Updated with the results if pip install testing on current statsmodels master.

**Comment by bashtage** [comment]
@matthew-brett Are any of these still going?

**Comment by thequackdaddy** [comment]
I think most of this is fixed now, but there's a new set of challenges. 

I did a brief PR to the statsmodels-wheels repo to pin pandas. It seems pandas backwards compatibility is broken. 

https://travis-ci.org/MacPython/statsmodels-wheels/builds/529342368
https://ci.appveyor.com/project/matthew-brett/statsmodels-wheels/builds/24366391

So things that are delicate. Seems like they pass randomly. 

* statsmodels/datasets/tests/test_utils.py:20: in test_get_rdataset - Seems to have connectivity issues
* statsmodels/base/tests/test_generic_methods.py:109: in test_zero_constrained - Small loss of precision
* statsmodels\tsa\vector_ar\tests\test_svar.py:71: in test_irf - Very small tolerance. 

Things I can't get to work...
* statsmodels/tsa/tests/test_arima.py:2274: in test_arima_exog_predict - Seems to have reasonably generous tolerance, but it doesn't pass on Mac builds at all.

**Comment by bashtage** [comment]
I think you have to use Numpy 1.16 to help with open blas issues.  All x64
pass on azure (2.7 3.5 3.6 3.7) using pip.

**Comment by bashtage** [comment]
These are all fixed, and wheels build fine for now.
