### ISSUE TITLE
Error iterating through params in SARIMAX.untransform_params. Statsmodels-0.9.0rc1

### ISSUE THREAD

**Issue by xenerizes** [statsmodels/statsmodels#4660]
A trouble occures with `fit` method for data of order (3, 0, 2)x(0, 0, 0, 0). There is no exogenous variables, and there are 200 observations of endogenous one. I'm not familiar with the topic enough, so I use default parameters and pass only series and order (which is computed with `arma_order_select_ic` and `adfuller`).

Anyway, it doesn't look like it is my fault. I was sure that if `start_params` (or input data) are not good , there will be a warning saying that explicitly (or the problem will be guessable). But after calling `fit()` I see this:
```
Traceback (most recent call last):
  File "/home/jool/runos-forecast/scripts/errors.py", line 13, in run
    algorithm.run()
  File "/home/jool/runos-forecast/forecast/algorithm/simple.py", line 12, in fit_model
    self.model.auto()
  File "/home/jool/runos-forecast/forecast/models/sarimax/sarimax.py", line 44, in auto
    self.model = model_type.fit(disp=False)
  File "/home/jool/.local/lib/python3.5/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 430, in fit
    start_params = self.untransform_params(np.array(start_params))
  File "/home/jool/.local/lib/python3.5/site-packages/statsmodels/tsa/statespace/sarimax.py", line 1472, in untransform_params
    unconstrained[start] = constrained[start]**0.5
IndexError: index 5 is out of bounds for axis 0 with size 3
```
`start_params` and `param_names` are `[  9.22257381e-01   7.94835431e-02   4.43433098e+11]` and `['ar.L1', 'ma.L1', 'sigma2']`.

In `untrasform_params` method the following happens: 
1. `mle_regression` is False, so `start` and `end` values remain zeros
2. `k_ar_params` is 3, and we get value 3 for both variables.
3. `k_ma_params` is 2, and, wow, both variables values became 5.
4. seasonal parameters and some others don't change anything
5. and, finally, `state_error` is True, and we are trying to access index 5 of array with length 3.

I don't know if it is a trouble of my incompetence in model initialization, or SARIMAX selects and computes wrong number of parameters, or an iterating algorithm is bad. I can't guess it by seeing such traceback from the library depths. 

Of course, I'm interested in solution of my particular problem, but the issue is that there should be more reasonable error message.

The data used: https://gist.github.com/xenerizes/0606554fc97045b3f742897ad24393c6

**Comment by xenerizes** [comment]
Thanks for explanation about parameters.

I define model like this: https://github.com/xenerizes/runos-forecast/blob/master/forecast/models/sarimax/sarimax.py#L28
Even with additional parameters removed (with data and order only), I have an error (as it is described) on my data. On other series there are no errors.

I tried to pass order explicitly (as numbers) to my auto() method, and it worked well... Why doesn't my auto() method work? How should I pass order and how should not?

**Comment by ChadFulton** [comment]
Hi @xenerizes, thanks for the report. It's hard for me to tell what exactly is breaking down here, since there seem to be quite a few moving parts.

But at the heart of the issue, you wrote:

> start_params and param_names are [ 9.22257381e-01 7.94835431e-02 4.43433098e+11] and ['ar.L1', 'ma.L1', 'sigma2'].

This should not be the case for an SARIMAX(3, 0, 2)x(0, 0, 0) model. I'm wondering if you're somehow trying to apply starting parameters from an SARIMAX(1, 0, 1)x(0, 0, 0) to your model.

It's hard to guess too much more, since your traceback includes:

>   File "/home/jool/runos-forecast/forecast/models/sarimax/sarimax.py", line 44, in auto
    self.model = model_type.fit(disp=False)

But I guess you are working with a newer version of the file than in the repository you linked, since the `sarimax.py` file in the repository is only 37 lines long?

**Comment by josef-pkt** [comment]
I looked only briefly at your code:

One structural problem with your `auto` method is that `start_params` needs to match the actual SARIMAX order. 
If you use the select_order option, then start_params needs to correspond to the model with the selected order, or be None.

**Comment by josef-pkt** [comment]
An aside to your selection code:
using ARIMA to select the seasonal order will not work because SARIMAX multiplies the lag polynomials and adds the seasonal lag power, ie. 
seasonal order (1, 0, 0) refers to the ar lag one season ago, while ARIMA would have the actual lag one season length periods ago
(AFAIR)

**Comment by xenerizes** [comment]
Thanks for the answers!

@ChadFulton 
>  I'm wondering if you're somehow trying to apply starting parameters from an SARIMAX(1, 0, 1)x(0, 0, 0) to your model.

Probably I am. One of my series is of that order. It was helpful, thanks. 
>  the sarimax.py file in the repository is only 37 lines long

Oh, I didn't noticed. There are some non-committed changes, where model is defined before calling fit(). The problem was in fit().

@josef-pkt Thanks a lot for explanation about seasonal order! I haven't tested this code yet, and you saved me from further errors.

**Comment by xenerizes** [comment]
Now I see, the problem was in my code. Thanks you all for the quick help! 

I wish you would someday add more reasonable error message than just IndexError from the depths. I mean, if the problem is in wrong number of parameters, it would save a lot of time for newbies like me.

**Comment by bashtage** [comment]
Closing as answered.
