### ISSUE TITLE
BLD: build versus install versus binary requirements

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4662]
Just some issues based on the recent discussions.

In general we assume that our dependencies especially numpy and scipy are already installed before building or installing statsmodels.

Our minimum versions are for the case when build and install uses the same numpy and scipy.

Binaries are only compatible forward from the numpy that was used when building the binaries. As it turned out we have the same or similar requirement in 0.9 for scipy.
It is not clear to me what the scipy ABI compatibility for BLAS/LAPACK will be in 0.10.

In 0.9 we have most likely also a version issue with the cython generated code. Most likely our sdist require a compatible scipy, i.e. >= 0.16 (when linalg cython interface changed) or maybe >= 1.01 (scipy installed when building sdist. 
The latter scipy >=1.01 for the sdist is unlikely, because I build and installed it successfully in an older python with an older scipy during local testing of the rc1.

One useful feature to have is that install from wheels raises if the installed numpy and scipy are too old. That doesn't seem to happen currently.
Setting proper install requires minimum versions for the wheels would help, except pip would upgrade numpy and scipy instead of raising about the incompatibility.

(aside
pandas added to setup.py
`python_requires='>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*',`
This means if you pip install pandas, then it deletes your old python and installs the latest python version.
... or maybe pip does that only with user packages 
:)

**Comment by bashtage** [comment]
This is no longer an issue with the current setup.py
