### ISSUE TITLE
qqplot not giving correct output when both loc and scale parameters are specified for a normal distribution.

### ISSUE THREAD

**Issue by babinu-uthup-4JESUS** [statsmodels/statsmodels#4695]
Version information has been attached as a a text file
[version_info.txt](https://github.com/statsmodels/statsmodels/files/2054811/version_info.txt)
[code_snippet.txt](https://github.com/statsmodels/statsmodels/files/2054820/code_snippet.txt)

[sm_qqplot_bug.pdf](https://github.com/statsmodels/statsmodels/files/2054869/sm_qqplot_bug.pdf)

Feel free to reach out to me if you need more details.

**Comment by josef-pkt** [comment]
Hi,

I'm sorry about this, but that is a known problem that needs more time to be fixed.
https://github.com/statsmodels/statsmodels/issues/3981#issuecomment-334509011
It's too complicated for a quick-fix and I haven't taken the time yet to work through all the details and figure out what design we need to handle all options.

**Comment by babinu** [comment]
Cool, thank you very much for your comment.

I can do a temporary workaround  by standardizing the data prior to making a qqplot.

Thanks
Babinu

**Comment by bashtage** [comment]
This has been fixed in master

![image](https://user-images.githubusercontent.com/5585221/69798282-f5037f80-11c8-11ea-9bb5-b6345eba0586.png)
