### ISSUE TITLE
NotImplementedError when fitting BinomialBayesMixedGLM.

### ISSUE THREAD

**Issue by jpilorget** [statsmodels/statsmodels#4700]
Hi! When I try tu replicate the example given in the docs ([this one](http://www.statsmodels.org/dev/generated/statsmodels.genmod.bayes_mixed_glm.BinomialBayesMixedGLM.html#statsmodels.genmod.bayes_mixed_glm.BinomialBayesMixedGLM)) using a dataset with synthetic data I get a NotImplemented Error.
I'm using the 0.9.0 version As I said I used the exact same code and created a synthetic dataset.
Is there something wrong with the fit() method or am I doing something wrong?
Thanks!

**Comment by josef-pkt** [comment]
try `fit_map`
it looks like `fit` is not defined in the model and it has just the inherited NotImplemented version
