### ISSUE TITLE
TypeError: cannot perform reduce with flexible type

### ISSUE THREAD

**Issue by sophiashahid** [statsmodels/statsmodels#4708]
i am using numpy version: '1.13.3' and ubuntu version : 16.04.4
 i am getting this errror . TypeError: cannot perform reduce with flexible type
my traindata is :scipy.sparse.csr.csr_matrix
and my test data is : numpy.ndarray
i am trying hubberREgressor () on features selected after kbest select on count vecterizer matrix.
Here is my stack Trace :  
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/sklearn/linear_model/huber.py in fit(self, X, y, sample_weight)
    264                 maxiter=self.max_iter, pgtol=self.tol, bounds=bounds,
--> 265                 iprint=0)
    266         except TypeError:

/usr/local/lib/python3.5/dist-packages/scipy/optimize/lbfgsb.py in fmin_l_bfgs_b(func, x0, fprime, args, approx_grad, bounds, m, factr, pgtol, epsilon, iprint, maxfun, maxiter, disp, callback, maxls)
    192     res = _minimize_lbfgsb(fun, x0, args=args, jac=jac, bounds=bounds,
--> 193                            **opts)
    194     d = {'grad': res['jac'],

/usr/local/lib/python3.5/dist-packages/scipy/optimize/lbfgsb.py in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, **unknown_options)
    327             # Overwrite f and g:
--> 328             f, g = func_and_grad(x)
    329         elif task_str.startswith(b'NEW_X'):

/usr/local/lib/python3.5/dist-packages/scipy/optimize/lbfgsb.py in func_and_grad(x)
    277         def func_and_grad(x):
--> 278             f = fun(x, *args)
    279             g = jac(x, *args)

/usr/local/lib/python3.5/dist-packages/scipy/optimize/optimize.py in function_wrapper(*wrapper_args)
    291         ncalls[0] += 1
--> 292         return function(*(wrapper_args + args))
    293 

/usr/local/lib/python3.5/dist-packages/scipy/optimize/optimize.py in __call__(self, x, *args)
     62         self.x = numpy.asarray(x).copy()
---> 63         fg = self.fun(x, *args)
     64         self.jac = fg[1]

/usr/local/lib/python3.5/dist-packages/sklearn/linear_model/huber.py in _huber_loss_and_gradient(w, X, y, epsilon, alpha, sample_weight)
     57     w = w[:n_features]
---> 58     n_samples = np.sum(sample_weight)
     59 

/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py in sum(a, axis, dtype, out, keepdims)
   1833     return _methods._sum(a, axis=axis, dtype=dtype,
-> 1834                          out=out, **kwargs)
   1835 

/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py in _sum(a, axis, dtype, out, keepdims)
     31 def _sum(a, axis=None, dtype=None, out=None, keepdims=False):
---> 32     return umr_sum(a, axis, dtype, out, keepdims)
     33 

TypeError: cannot perform reduce with flexible type

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-139-41c618e3c802> in <module>()
      1 h = HuberRegressor()
----> 2 predict= h.fit(X_train_selected, y_train)
      3 prediction=h.predict(X_test_selected)
      4 
      5 acc = rmsle(y_test, prediction)

/usr/local/lib/python3.5/dist-packages/sklearn/linear_model/huber.py in fit(self, X, y, sample_weight)
    268                 _huber_loss_and_gradient, parameters,
    269                 args=(X, y, self.epsilon, self.alpha, sample_weight),
--> 270                 bounds=bounds)
    271         if dict_['warnflag'] == 2:
    272             raise ValueError("HuberRegressor convergence failed:"

/usr/local/lib/python3.5/dist-packages/scipy/optimize/lbfgsb.py in fmin_l_bfgs_b(func, x0, fprime, args, approx_grad, bounds, m, factr, pgtol, epsilon, iprint, maxfun, maxiter, disp, callback, maxls)
    191 
    192     res = _minimize_lbfgsb(fun, x0, args=args, jac=jac, bounds=bounds,
--> 193                            **opts)
    194     d = {'grad': res['jac'],
    195          'task': res['message'],

/usr/local/lib/python3.5/dist-packages/scipy/optimize/lbfgsb.py in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, **unknown_options)
    326             # until the completion of the current minimization iteration.
    327             # Overwrite f and g:
--> 328             f, g = func_and_grad(x)
    329         elif task_str.startswith(b'NEW_X'):
    330             # new iteration

/usr/local/lib/python3.5/dist-packages/scipy/optimize/lbfgsb.py in func_and_grad(x)
    276     else:
    277         def func_and_grad(x):
--> 278             f = fun(x, *args)
    279             g = jac(x, *args)
    280             return f, g

/usr/local/lib/python3.5/dist-packages/scipy/optimize/optimize.py in function_wrapper(*wrapper_args)
    290     def function_wrapper(*wrapper_args):
    291         ncalls[0] += 1
--> 292         return function(*(wrapper_args + args))
    293 
    294     return ncalls, function_wrapper

/usr/local/lib/python3.5/dist-packages/scipy/optimize/optimize.py in __call__(self, x, *args)
     61     def __call__(self, x, *args):
     62         self.x = numpy.asarray(x).copy()
---> 63         fg = self.fun(x, *args)
     64         self.jac = fg[1]
     65         return fg[0]

/usr/local/lib/python3.5/dist-packages/sklearn/linear_model/huber.py in _huber_loss_and_gradient(w, X, y, epsilon, alpha, sample_weight)
     56     sigma = w[-1]
     57     w = w[:n_features]
---> 58     n_samples = np.sum(sample_weight)
     59 
     60     # Calculate the values where |y - X'w -c / sigma| > epsilon

/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py in sum(a, axis, dtype, out, keepdims)
   1832             return sum(axis=axis, dtype=dtype, out=out, **kwargs)
   1833     return _methods._sum(a, axis=axis, dtype=dtype,
-> 1834                          out=out, **kwargs)
   1835 
   1836 

/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py in _sum(a, axis, dtype, out, keepdims)
     30 
     31 def _sum(a, axis=None, dtype=None, out=None, keepdims=False):
---> 32     return umr_sum(a, axis, dtype, out, keepdims)
     33 
     34 def _prod(a, axis=None, dtype=None, out=None, keepdims=False):

TypeError: cannot perform reduce with flexible type

Can anyone help?

**Comment by josef-pkt** [comment]
wrong package, I think you want to discuss this with scikit-learn, not statsmodels
