### ISSUE TITLE
Cannot cast ufunc subtract output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

### ISSUE THREAD

**Issue by ankittri7** [statsmodels/statsmodels#4709]
The cast ufunc occurs while out of sample forecasting from a pickle file. There is no error while fitting the data. Following is the sample code:

`def forecast_fit(df):            
  series=df
  X = series.values
  train=X
  model = ARIMA(X, order=(1,0,1))
  model_fit = model.fit(disp=0)
  model_fit.save('model.pkl')
forecast_fit(df)
#Out of sample forecasts
loaded = ARIMAResults.load('model.pkl)
forecast = loaded.forecast(steps=17)[0]        #error_occurs_here
df=pd.DataFrame(forecast, columns=[i+'_hat'])  
`
[data.xlsx](https://github.com/statsmodels/statsmodels/files/2067232/data.xlsx)

Uploaded the data for replicating the error.

**Comment by bashtage** [comment]
Arrays are assumed to be doubles. This needs more enforcement, but the correct solution is always to cast to np.double.
