### ISSUE TITLE
Can't get value with SARIMAX forecastq

### ISSUE THREAD

**Issue by samuel-1985** [statsmodels/statsmodels#4710]
Hi

I am working with SARIMAX forecast to get real predictions for the future, I mean for the dates that I do not have the data. I am working on Example #4 of the notebook with Friedman.dta of stata.

When I type:
# Dataset
>>> raw = pd.read_stata('/home/raminsalimi19902407/friedman2.dta')
>>> raw.index = raw.time
>>> data = raw.ix[:'1981']

# Variables
>>> endog = data.ix['1959':, 'consump']
>>> exog = sm.add_constant(data.ix['1959':, 'm2'])

# Fit the model
>>> mod = sm.tsa.SARIMAX(endog=endog, exog=exog, order=(1,0,1))
>>> fit_res = mod.fit()
>>> mod = sm.tsa.SARIMAX(endog.ix[:'1978-01-01'], exog.ix[:'1978-01-01'], order=(1,0,1))
>>> res = mod.filter(fit_res.params)

#dynamic predictions
>>> forec = res.forecast(dynamic=True, steps=120)
#print(forec)

It gives me the following error but I do not understand why we need exog argument in the first place?
ValueError: Out-of-sample forecasting in a model with a regression component requires additional exogenous values via the `exog` argument.

After that, I changed the last line to the following:
>>> forec = res.forecast(dynamic=True, steps=120, exog=exog.ix['1978-01-01':])
It gave me the following error which is understandable because only the next 16 elements exist in exog.ix['1978-01-01':]
ValueError: Provided exogenous values are not of the appropriate shape. Required (120, 2), got (16, 2).

Now, my question is if I have a dataset and I want to finally do real forecast(and NOT validation) for the dates that are not in my endog and exog (because I want to forecast for those dates), what should I do?

Even, from the very beginning, I tried to add several rows of NANs corresponding to ['1982-01-01', '1982-04-01', '1982-07-01'] but at the point I fit the model, it gave error:
# Dataset
>>> raw = pd.read_stata('/home/raminsalimi19902407/friedman2.dta')
>>> raw.index = raw.time
>>> data = raw.ix[:'1981']

## and endog columns or series of the dataframe.
>>> d1 = {'col1': [np.nan, np.nan, np.nan]}
>>> index = ['1982-01-01', '1982-04-01', '1982-07-01']
>>> df = pd.DataFrame(d1, index=index)
>>> df2 = pd.concat([data, df])

# Variables
>>> endog = df2['consump']
>>> exog = sm.add_constant(df2['m2'])

# Fit the model
>>> mod = sm.tsa.SARIMAX(endog=endog, exog=exog, order=(1,0,1))
>>> fit_res = mod.fit()

LinAlgError: Array must not contain infs or NaNs

I would appreciate if you point where I am doing this wrong

**Comment by Akshat12071207** [comment]
Hey, I am having the same doubt. Why do we need exog variables when we are forecasting future values? I am show the same error. 
This issue has been closed, I am assuming that you an answer. Kindly let me know too, how did you solve this?

**Comment by bashtage** [comment]
> Why do we need exog variables when we are forecasting future values?

Does your model have exog?  If so, you need future values of these or forecasts of these to forecast your variable.
