### ISSUE TITLE
windows and linux different

### ISSUE THREAD

**Issue by gucasbrg** [statsmodels/statsmodels#4737]
process this code 

```
from statsmodels.tsa.arima_model import ARIMA
import math
X=[21.0, 33.0, 11.0, 60.0, 39.0, 25.0, 23.0, 33.0, 87.0, 105.0, 81.0, 97.0, 72.0, 90.0, 91.0, 107.0, 98.0, 118.0, 101.0, 85.0, 153.0, 117.0, 110.0, 145.0, 182.0, 173.0, 164.0, 220.0, 125.0, 274.0, 160.0, 232.0, 108.0, 179.0, 199.0, 122.0, 185.0, 168.0, 213.0]
best_cfg=[4,1,2]
try:
    model = ARIMA(X, order=best_cfg)
    model_fit = model.fit(disp=0)
except:
    model = ARIMA(X, order=[1,1,0])
    model_fit = model.fit(disp=0)
model_fit.forecast()[0][0]
```

window result:(array([117.15292151]), array([72.17877122]), array([[-24.31487052, 258.62071355]]))
linux result:(array([nan]), array([nan]), array([[nan, nan]]))

statsmodels version are same,0.9.0 and Python 3.6.5 is anaconda3.

**Comment by kenjioman** [comment]
I am running Linux with statsmodels 0.9.0, Python 3.6.5, anaconda3 and my final output (to `model_fit.forcast()`) is:
(array([189.985092]),
 array([30.64831909]),
 array([[129.91549039, 250.0546936 ]])).

Granted, it also gave the warning `HessianInversionWarning: Inverting hessian failed, no bse or cov_params available`.  Just figured I'd provide another data-point on a different system.

**Comment by bashtage** [comment]
I get identical results on Linux (64 bit) and Windows (64 bit).

**Comment by gucasbrg** [comment]
linux:
![linux](https://user-images.githubusercontent.com/3182658/41449791-cbff09ea-7095-11e8-97de-0e317c155e91.png)
windows:
![windows](https://user-images.githubusercontent.com/3182658/41449792-cc61d25a-7095-11e8-99b8-5f29a249358d.png)

**Comment by josef-pkt** [comment]
my guess is that it is more likely openblas versus mkl
@gucasbrg  can you check which linalg libraries your linux and windows are using.

another thing to try is to use the Windows params as start_params on Linux to see if it is a convergence problem.

another diagnostic is to look at results.mle_retvals and results.mle_settings but I don't know if those are saved for ARMA.

Also are the SARIMAX results for the same model.

My guess is that the (4, 1, 2) model is overparameterized and given the HessianInversionWarning will not be estimated robustly, i.e. numerical noise can throw off the optimization.

**Comment by josef-pkt** [comment]
another issue: what are the scipy versions? Are they the same?

you can also try different optimizers, e.g. `solver="nm"`
However, lbfgs which is the default in ARIMA hasn't changed much in scipy, so I think there are no larger differences across scipy versions.

**Comment by bashtage** [comment]
Closing, no action.
