### ISSUE TITLE
importing issue -  ImportError: cannot import name '_representation'

### ISSUE THREAD

**Issue by lightnino** [statsmodels/statsmodels#4756]
Hi i have reviewed all issues related to importing issues, especially the ones with name'_representation'. 
I have tried out the suggested solutions reported in previous issues such as upgrade all statsmodels,pandas, scipy, numpy,etc. but still run into the same issue. 

Currently i have the versions as followed: 
numpy 1.14.10
scipy 1.1.0
patsy 0.4.1
pandas 0.23.0
statsmodels 0.9.0

When i try 
import statsmodels .api as sm, i received the error:
 File "C:\Users\chzhu\AppData\Local\Continuum\anaconda3\envs\myenv\lib\site-packages\statsmodels\tsa\statespace\tools.py", line 59, in set_mode
    from . import (_representation, _kalman_filter, _kalman_smoother,

ImportError: cannot import name '_representation'

- any suggestion regarding how the issue should be resolved? Shall I  downgrade it to some numpy/scipy/pandas version that is compatible with the package? 

Thanks very much for your help.

**Comment by lightnino** [comment]
Issue was resolved by completely reinstalling all modules related.

**Comment by shintojoseph1234** [comment]
This issue was solved for me by installing the github repository version directly

`pip3 install git+https://github.com/statsmodels/statsmodels.git`
