### ISSUE TITLE
genfromdta and unicode

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#476]
Stata doesn't support unicode. When passing off strings that have non-ascii characters it gives them encoded as latin-1. Should we try to decode these as latin-1 when passing them back from genfromdta or let the user take care of it? If not, you will have strings like

```
name = "D\xfcsseldorf"
```

which can give you some problems without decoding and getting a unicode object

```
name = name.decode('latin-1')
```

If we do this, we'll always be passing back strings as unicode objects. Maybe it should be an option, as_unicode.

Note that this will only work for the latin-1 character subset. If you have a true utf-8 character (e.g., Czech characters, etc.) stata will go ahead and (silently!) step on these for you. We can't do anything about that.

**Comment by bashtage** [comment]
This should defer to pandas.read_stata or pandas.DataFrame.to_stata, which are both heavily used and partially support unicode.
