### ISSUE TITLE
statsmodels.formula.api

### ISSUE THREAD

**Issue by yiorgos1973** [statsmodels/statsmodels#4761]
statsmodels.formula.api looses methods of logit like summary, params, pvalues and more after running a programme with sklearn imports. After uninstalling and reinstalling with conda the statsmodels the methods reappeared but then again disappeard after running the same programme. 
The imports of my programme are:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix
import statsmodels.formula.api as smf
import statsmodel.api as sm

**Comment by josef-pkt** [comment]
closing, I don't see anything that we could do.

reopen and provide more information if we need to fix something in statsmodels.
