### ISSUE TITLE
Holt-Winters/SES AICc formula ???

### ISSUE THREAD

**Issue by picerx** [statsmodels/statsmodels#4762]
aicc = aic + (2 * (k + 2) * (k + 3)) / (self.nobs - k - 3)  #line 735 @holtwinters.py

VS 

return -2. * llf + 2. * df_modelwc * nobs / (nobs - df_modelwc - 1.) #from eval measures

**Comment by amilyalways** [comment]
I meet the same problems. the formula of aicc leads to the "ZeroDivisionError: division by zero " error.

**Comment by josef-pkt** [comment]
I looked a bit at the definition
The aicc definition for holt-winters is in one of the writings by Hyndman, but I didn't see a reference that justifies it.
The eval_measure definition is a reformulation of the standard aicc formula e.g. as shown in Wikipedia.

If `(self.nobs - k - 3)` is not > zero, then the degrees of freedom is not large enough to get a meaningful aicc in this definition. I haven't checked how `k` is determined in this case. Hyndman just mentions that it includes all parameters, which would mean that the model is overparameterized to get reliable estimates of the parameters, i.e. not enough degrees of freedom.

**Comment by ritvikGarg** [comment]
I am facing the same issue.
Anybody with the solution ?
