### ISSUE TITLE
adfuller : difference in documentation page and examples on what the null hypothesis is

### ISSUE THREAD

**Issue by ssikdar1** [statsmodels/statsmodels#4764]
In the documentation page for adfulller: http://www.statsmodels.org/dev/generated/statsmodels.tsa.stattools.adfuller.html#statsmodels.tsa.stattools.adfuller

```
The null hypothesis of the Augmented Dickey-Fuller is that there is a unit root, with the alternative that there is no unit root. 
```
and in examples it says: 
See example notebook

However in the example ipynb here:

http://www.statsmodels.org/dev/examples/notebooks/generated/tsa_arma_0.html

at the bottom example using the adfuller test the comment reads:

```
P-value of the unit-root test, resoundly rejects the null of no unit-root.

print(sm.tsa.adfuller(cpi)[1])
0.990432818833742
```
So the example is assuming the null hypothesis is that there is no unit root.

Probably the ipynb needs to be fixed?

**Comment by josef-pkt** [comment]
Yes, the notebook needs to be fixed.

For interpretation: adfuller does not test against a cyclical alternative, so it could still be possible that there is a deterministic cycle instead of a unit root.
