### ISSUE TITLE
MAINT: gitignore univariate_diffuse_pyx

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4765]
@ChadFulton 

AFAICS, `_univariate_diffuse_pyx` in _filters and _smoothers should be added to gitignore. ?
There is also a _initialization.pyx that shows up as file not in repo.
**edit** _initialization.pyx is only on my desktop but not in my notebook, so it might be a file that I had forgotten to delete on my desktop

(I needed to manually delete all created files to build the extensions inplace and those three files show up in gitgui as unstaged.)

**Comment by ChadFulton** [comment]
Yes, all three of those should be ignored! I will submit a PR tonight
