### ISSUE TITLE
MAINT:  travis problems

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4776]
two python 2.7 on travis ci have been failing/stopping for a few days

https://travis-ci.org/statsmodels/statsmodels/jobs/399525081

strange thing is that it is supposed to install numpy 1.11 but numpy 1.14 shows up
There is a second package numpy-base in the wrong version

```

The following NEW packages will be INSTALLED:
...
    numpy:            1.11.3-py27hcd700cb_6  
    numpy-base:       1.14.3-py27h0ea5e3f_1  
```

**Comment by thequackdaddy** [comment]
see https://github.com/conda/conda/issues/7481

**Comment by josef-pkt** [comment]
#4777 specifies the version for numpy-base, and changes numpy version in one test environment
