### ISSUE TITLE
MAINT: travis explicitly specify MKL or OpenBLAS

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4779]
Right now it looks a bit random which test environment on Travis gets MKL and which gets OpenBLAS. Most likely there is also a mismatch that numpy and scipy don't have the same linalg library.

It is possible to explicitly specify which linalg library should be used

https://github.com/ContinuumIO/anaconda-issues/issues/9519
https://github.com/qutip/qutip/pull/876

We should keep at least some environments with OpenBLAS because it has different test failures thank MKL.
Aside: We could add which linalg library is used to the test output, as @thequackdaddy did for one of his branches.

**Comment by thequackdaddy** [comment]
xref #4780

**Comment by josef-pkt** [comment]
added as part of #4823
