### ISSUE TITLE
Formual Variable Names with Spaces

### ISSUE THREAD

**Issue by TheChymera** [statsmodels/statsmodels#4783]
I have quite a few dataframes which contain Columns with spaces in their names. I have found it impossible to reference these in statsmodels formulas, e.g. `Sprout Length ~ Treatment * Postoperative Day` or `'Sprout Length' ~ Treatment * 'Postoperative Day'`. Is there any way to do this, or do I have to rename the columns?

**Comment by josef-pkt** [comment]
use patsy's quote Q in the formula 
http://patsy.readthedocs.io/en/latest/builtins-reference.html#patsy.builtins.Q

**Comment by TheChymera** [comment]
Thanks!

**Comment by TheChymera** [comment]
@josef-pkt what do I need to do if I want to treat a variable whose name contains a space as categorical?

Neither `Q("C(Depth rel. skull [mm])")` nor `C("Depth rel. skull [mm]")` seem to work, and fail with

```
patsy.PatsyError: Error evaluating factor: NameError
```

**Comment by josef-pkt** [comment]
try the Q inside the C: `C(Q("my name"))` which is my best guess

**Comment by adityaraute** [comment]
But why should I have to use `patsy` for this? Wouldn't it be better to incorporate this into `statsmodel`?

**Comment by josef-pkt** [comment]
@adityaraute 

statsmodels delegates the formula handling to patsy, or in future formulaic.
You can use the `Q` or similar features of patsy directly when using formulas with statsmodels. 

The reference above is mainly for the documentation. patsy has good documentation and the statsmodels documentation only illustrates some parts of it. For the details the user has to look at the patsy documentation.
