### ISSUE TITLE
BUG: k_params in SARIMAX

### ISSUE THREAD

**Issue by chanhsienlin** [statsmodels/statsmodels#4789]
statsmodels.tsa.statespace.sarimax.py (version 0.9.0)

class SARIMA
def __init__(...)
...
        # Number of parameters
        self.k_params = (
            self.k_ar_params + self.k_ma_params +
            self.k_seasonal_ar_params + self.k_seasonal_ar_params +
            self.k_trend +
            self.measurement_error + 1
        )
...

self.k_seasonal_ar_params + self.k_seasonal_ar_params

should be self.k_seasonal_ar_params + self.k_seasonal_ma_params ?

**Comment by ChadFulton** [comment]
Thanks very much! You're absolutely right.

**Comment by ChadFulton** [comment]
Thanks @chanhsienlin!
