### ISSUE TITLE
TypeError: seasonal_decompose() got an unexpected keyword argument 'extrapolate_trend'

### ISSUE THREAD

**Issue by carkar7** [statsmodels/statsmodels#4793]
Im getting an error when trying to use the extrapolate trend argument. It had worked perfectly in the past. Error seems to have started after installing fbprophet

**Comment by josef-pkt** [comment]
That’s not much information to go on.
Check that you still have the correct version of statsmodels.

**Comment by josef-pkt** [comment]
closing, I don't see how this could be any problem caused by statsmodels.

reopen and provide more information if there is something we need to fix
