### ISSUE TITLE
ValueError when print summary

### ISSUE THREAD

**Issue by w158rk** [statsmodels/statsmodels#4794]
When I use the ols to analyze a data set containing 43 entries, I get the ValueError as followed.

### code
```　
import pandas as pd
import numpy as np
from sklearn import preprocessing
from statsmodels.formula.api import ols

data=pd.read_csv("digit.csv")
Y=data[['Order']]

X_num=data[['Money','Host','Client','Potential']]
X_dummy=data[['Loc_1','Loc_2','Type_1','Type_2','Type_3','Type_4']]

X_num=preprocessing.scale(X_num)
X_num=pd.DataFrame(X_num)
X_num.columns=['Money','Host','Client','Potential']

final = pd.concat([X_num, Y, X_dummy], axis=1)
print (final.head())

formula = 'Order~Money+Host+Client+Potential+Loc_1+Loc_2+Type_1+Type_2+Type_3+Type_4'
results = ols(formula,data=final).fit()
print (results.summary())
```

### output

``` bash
      Money      Host    Client  Potential Order     Loc_1     Loc_2    Type_1    Type_2    Type_3    Type_4
0 -0.466650  0.483166 -0.302053  -0.483973     1 -0.320256  0.320256 -0.658281  1.439246 -0.586302 -0.362738
1 -0.551443 -0.385523 -0.742334  -0.483973     0 -0.320256  0.320256  1.519109 -0.694808 -0.586302 -0.362738
2  2.012625 -0.240741 -0.522194  -0.612434     0 -0.320256  0.320256 -0.658281  1.439246 -0.586302 -0.362738
3  0.183837  0.338385 -0.302053  -0.227049     0 -0.320256  0.320256 -0.658281  1.439246 -0.586302 -0.362738
4  0.306282  0.483166  1.734246  -0.355511     1 -0.320256  0.320256 -0.658281 -0.694808  1.705606 -0.362738
Traceback (most recent call last):
  File "final.py", line 29, in <module>
    print (results.summary())
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/regression/linear_model.py", line 2376, in summary
    top_right = [('R-squared:', ["%#8.3f" % self.rsquared]),
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/decorators.py", line 97, in __get__
    _cachedval = self.fget(obj)
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/regression/linear_model.py", line 1543, in rsquared
    return 1 - self.ssr/self.centered_tss
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/tools/decorators.py", line 97, in __get__
    _cachedval = self.fget(obj)
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/regression/linear_model.py", line 1515, in ssr
    return np.dot(wresid, wresid)
ValueError: shapes (43,5) and (43,5) not aligned: 5 (dim 1) != 43 (dim 0)

```

**Comment by josef-pkt** [comment]
It look like order is interpreted as categorical.
Convert it to numeric.

**Comment by josef-pkt** [comment]
I'm closing this, this works as indented, although not really informative in error message

see #4771 for vectorized OLS, and related issues for MultivariateOLS

**Comment by MJimitater** [comment]
So what is the solution to this?

**Comment by josef-pkt** [comment]
OLS only supports univariate endog (unless we only want params)

So, either make sure endog is univariate, e.g. don't specify a categorical endog, or switch to multivariate model, e.g. in package `linear_models`.

**Comment by josef-pkt** [comment]
Based on the traceback above, `wresid` and therefore `endog` is 2-dim (43,5)
If "order" is interpreted by patsy as categorical with 5 levels, then it will convert it to a 2-dim dummy variable array with 5 columns.

**Comment by MJimitater** [comment]
@josef-pkt Thanks for your quick reply!

Okay I checked, and endog is definitely univarite.

Im just not getting anywhere with whatever Im trying..

I've attached the error message and the endog/exog data, perhaps you could take a quick look.. I'd be very grateful



![screenshot1](https://user-images.githubusercontent.com/26901261/68710078-3411be00-0597-11ea-8ff9-6b11986f0bd6.png)

![screenshot2](https://user-images.githubusercontent.com/26901261/68710080-3411be00-0597-11ea-93c6-b75a7ed5f67e.png)

[dataframe.zip](https://github.com/statsmodels/statsmodels/files/3838182/dataframe.zip)

**Comment by josef-pkt** [comment]
check `model.endog.shape`

**Comment by MJimitater** [comment]
Good catch! 
`model.endog.shape` gives me `(942, 922)`

But Im still thinking how about how this can happen! Any idea?

**Comment by josef-pkt** [comment]
look at the `dtypes` of your dataframe. The csv file has a numeric column, but maybe there is something strange in reading it in.

For example if it is dtype object or string, then AFAIK patsy will treat it as categorical

**Comment by josef-pkt** [comment]
Does pandas interpret scientific notation like `1.6472836292952922e-05` as numeric? I never tried.

**Comment by MJimitater** [comment]
Spot on @josef-pkt !!! THANK YOU FOR YOUR HELP!!!

Yes, the `dtype` of the numeric column in the csv wasn't at all numeric, it was object.

A simple `pd.to_numeric()` did the trick!

Thanks again, best greets from Germany
