### ISSUE TITLE
BUG: ExponentialSmoothing fails with ZeroDivisionError

### ISSUE THREAD

**Issue by abhishekkaranth** [statsmodels/statsmodels#4796]
For the model parameters
`ExponentialSmoothing(arr, trend='add', damped=False, seasonal='add', seasonal_periods=5)`
where` len(arr) = 12`, the fit of model fails with ZeroDivisionError.

The issue is caused while calculating aicc of the model since it is calculated as:
```
k = m * seasoning + 2 * trending + 2 + 1 * damped
aicc = aic + (2 * (k + 2) * (k + 3)) / (self.nobs - k - 3)
```
In this case:
```
self.nobs = 12
k = 9
```
This can happen with other dataset as well.
Should the model fail in such cases? Even if yes, we can throw better errors I feel.

**Comment by ChadFulton** [comment]
Thanks for the report! Yes, I think that in this case the model should run, and we can set the aicc to `np.inf`.
