### ISSUE TITLE
PoissonBayesMixedGLM.from_formula fails with TypeError

### ISSUE THREAD

**Issue by TheChymera** [statsmodels/statsmodels#4807]
Given this [minimal self-contained example](http://chymera.eu/debug/statsmodels/multi_longitudinal_treatment_bayes.zip), and statsmodels f94f26f162d76d5e7ba3da6d7e8c8513bc9a4604 I cannot use the `statsmodels.genmod.bayes_mixed_glm.PoissonBayesMixedGLM.from_formula` function.

The traceback is:

```
Traceback (most recent call last):
  File "model.py", line 6, in <module>
    model = PoissonBayesMixedGLM.from_formula(formula, ['subject'], df)
  File "/usr/lib64/python3.5/site-packages/statsmodels/genmod/bayes_mixed_glm.py", line 1090, in from_formula
    vc_names=vc_names)
TypeError: from_formula() got an unexpected keyword argument 'vcp_names'
```

**Comment by kshedden** [comment]
`vc_formula` needs to be a dictionary mapping labels to formulas, like below.  But you seem to have uncovered some issues with the Poisson model, which I have not worked with much.  Below is a working
example in the logistic case.

```
import pandas as pd                                                                                                                          
from statsmodels.genmod.bayes_mixed_glm import PoissonBayesMixedGLM, BinomialBayesMixedGLM                                                   
                                                                                                                                             
df = pd.read_csv('data.csv')                                                                                                                 
formula = "value ~ treatment : day"                                                                                                          
df.value = 1*(df.value > 4)                                                                                                                  
model = BinomialBayesMixedGLM.from_formula(formula, {'subject': '0 + C(subject)'}, df)                                                              
fit = model.fit_map()                                                                                                                        
print(fit.summary()) 
```

**Comment by TheChymera** [comment]
> `vc_formula` needs to be a dictionary mapping labels to formulas

Can you perhaps explain this or provide more examples? Like what kind of features does this expanded model provide as opposed to just lising the variables for which I want a random effect? Additionally, what would be the difference between ` {'subject': '0 + C(subject)'}`, ` {'subject': 'C(subject)'}`, ` {'subject': 'subject'}`, and ` {'subject': '0 + subject'}`

Additionally, what is the meaning of  `df.value = 1*(df.value > 4) `?

Not least of all, judging by the output table:

```
                       Binomial Mixed GLM Results
========================================================================
                          Type Post. Mean Post. SD   SD  SD (LB) SD (UB)
------------------------------------------------------------------------
Intercept                    M    -3.4083   1.0724                      
treatment[Substance1]:day    M     1.0203   0.2491                      
treatment[Substance2]:day    M     1.1278   0.2628                      
treatment[Substance3]:day    M    -0.7471   0.9758                      
treatment[water]:day         M     0.9961   0.2462                      
subject                      V   -12.0000   1.0000 0.000   0.000   0.000
========================================================================
Parameter types are mean (M) and variance (V)
Posterior mean/SD are for logged V parameters
```

It looks like a SD but no CI is provided, does this mean that the model is inappropriate for nonparametric analysis? Also, is there any way to get significance values for this model?

**Comment by TheChymera** [comment]
@kshedden I guess the original issue is resolved, so closing. But I'd really be curious about more info. Let me know if this is better asked elsewhere.

**Comment by kshedden** [comment]
@TheChymera the issues you identified should be fixed now in PR #4809.  I will merge in 1-2 days after I review it again.

The output you should get from this (using your data and model) is copied below.  The basic story here is that there isn't much evidence for a subject effect.  Under the Laplace approximation, the subject variance is essentially estimated to be 0, which leads to convergence warnings that I removed below.  The variational Bayes method uses a different approximation, which yields a small but nonzero estimate of the SD for subjects (0.072).

Since the Laplace method is on the boundary of the parameter space, the standard errors (posterior SD values) are probably not meaningful.

```
                       Poisson Mixed GLM Results
========================================================================
                          Type Post. Mean Post. SD   SD  SD (LB) SD (UB)
------------------------------------------------------------------------
Intercept                    M     0.7328   0.1829                      
treatment[Substance1]:day    M     0.1877   0.0363                      
treatment[Substance2]:day    M     0.1949   0.0361                      
treatment[Substance3]:day    M     0.0741   0.0387                      
treatment[water]:day         M     0.2057   0.0360                      
subject                      V   -12.0000   1.0000 0.000   0.000   0.000
========================================================================
Parameter types are mean structure (M) and variance structure (V)
Variance parameters are modeled as log standard deviations

                       Poisson Mixed GLM Results
========================================================================
                          Type Post. Mean Post. SD   SD  SD (LB) SD (UB)
------------------------------------------------------------------------
Intercept                    M     0.7332   0.0343                      
treatment[Substance1]:day    M     0.1869   0.0125                      
treatment[Substance2]:day    M     0.1940   0.0123                      
treatment[Substance3]:day    M     0.0728   0.0171                      
treatment[water]:day         M     0.2049   0.0119                      
subject                      V    -2.6311   0.2251 0.072   0.046   0.113
========================================================================
Parameter types are mean structure (M) and variance structure (V)
Variance parameters are modeled as log standard deviations
```

**Comment by TheChymera** [comment]
@kshedden actually, I was looking to treat the subject as a random factor. I was interested to find out more about the treatment:day interactions. Should I have specified the model differently?

Is there any way to determine how significant the difference between each treatment[Treatment*]:day effect is compared to treatment[water]:day ?

**Comment by kshedden** [comment]
In your model, you are treating subject as a random factor (i.e., there is a distribution of random intercepts for the subjects).  This distribution has mean 0, and a variance that is estimated from the data.  Under the Laplace approach to fitting the model, the estimated variance is 0.  Under the VB approach to fitting the model, the estimated variance is 0.072^2.

For any mixed effects model with random intercepts, random slopes, etc., (where "random" means that the population is divided into groups and each group gets an independent draw from the random intercept, slope, ... distributions), you never want an intercept in the variance formula, i.e. you always want "0 + C(x)" not just "C(x)".  This is true for all variance models in `MixedLM` and in `BayesMixedGLM`.

Sometimes you can drop the `C(...)` depending on whether Patsy recognizes the variables as a factor, e.g. `0 + x` is fine if `x` is a string but not if `x` is a float or integer.

**Comment by kshedden** [comment]
A variance formula is resolved to a design matrix such that every column of the design matrix is multiplied by an independent draw from the random effects distribution.

So if you use `i: "0 + C(group)"`, the design matrix would look something like this:

```
1 0 0
1 0 0
0 1 0
0 1 0
0 0 1
0 0 1
...
```

(where for illustration I am using groups of size 2).  If the realized random effects are `c1, c2, c3`, then the contribution to the first group is `c1`, the contribution to the second group is `c2`, etc.

If you were to use `i: "C(group)"` then the design matrix would be something like this:

```
1 0 0
1 0 0
1 1 0
1 1 0
1 0 1
1 0 1
...
```

If the realized random effects were `c1, c2, c3`, then the contribution to the first group would be `c1`, to the second group would be be `c1+c2`, etc.  This gives the first group a different variance than the other groups, and creates a correlation among all the groups.

As you probably know, when working with mean structures, the two parameterizations are equivalent, but this is not true for variance structures.  In the first (correct) case, the marginal variance among the first three groups is

```
v  0  0
0  v  0
0  0  v
``` 

where `v = var(c_j)`, which does not depend on `j`.  In the second (incorrect) case, the marginal variance among the first three groups is

```
2v   v    v
v    v    v
v    v    v
```

which is probably not what you want.

**Comment by kshedden** [comment]
To compare each non-water treatment to the water treatment, I would change the mean structure formula to something like this:

```
formula = "value ~ C(treatment, Treatment(reference='water')) * day"   
```

This will give you a point estimate and standard deviation for the baseline (day=0) level of substances 1, 2, 3 relative to water, and for the day slope of substances 1, 2, 3, relative to water. 

This is a Bayesian analysis based on the posterior distribution of the structural parameters and random effects given the data.

**Comment by FedericaLionetto** [comment]
Hi everyone,

I have read that the issue regarding "vcp_names" was closed, but is the problem solved? I am experiencing the same issue actually, please find the code and the first entries of the dataframe below:

    from statsmodels.genmod.bayes_mixed_glm import PoissonBayesMixedGLM, 
    BinomialBayesMixedGLM

    formula = 'total_days_AU_MS ~ 1 + n_relapse_xmt'

    glm_model = PoissonBayesMixedGLM.from_formula(formula=formula, 
                                              vc_formulas={'f.id.site':'0 + C(f.id.site)'}, 
                                              data=X)
    glm_results = glm_model.fit_map()
    print(glm_results.summary())

Any clue? Thank you for your help!

<img width="185" alt="Capture" src="https://user-images.githubusercontent.com/9050516/54300327-f0585600-45bc-11e9-919e-ac7a47448c25.PNG">

**Comment by kshedden** [comment]
I don't have any problems with the version currently in master (since September 2018).  I extended your code a bit to be a working example.  The results match the population structure pretty well.

```
import numpy as np                                                                                                              
import pandas as pd                                                                                                             
from statsmodels.genmod.bayes_mixed_glm import PoissonBayesMixedGLM, BinomialBayesMixedGLM                                      
                                                                                                                                
n = 1000                                                                                                                        
m = 50 # Number of groups                                                                                                       
grp = np.random.randint(0, m, n)                                                                                                
grp_efx = np.random.normal(size=m)                                                                                              
n_relapse_xmt = np.random.normal(size=n)                                                                                        
lpr = grp_efx[grp] + n_relapse_xmt                                                                                              
mn = np.exp(lpr)                                                                                                                
total_days_AU_MS = np.random.poisson(mn)                                                                                        
X = pd.DataFrame({"total_days_AU_MS": total_days_AU_MS,                                                                         
                  "f_id_site": grp,                                                                                             
                  "n_relapse_xmt": n_relapse_xmt})                                                                              
                                                                                                                                
formula = 'total_days_AU_MS ~ 1 + n_relapse_xmt'                                                                                
                                                                                                                                
glm_model = PoissonBayesMixedGLM.from_formula(formula=formula,                                                                  
                vc_formulas={'f_id_site': '0 + C(f_id_site)'}, data=X)                                                          
glm_results = glm_model.fit_map()                                                                                               
print(glm_results.summary())  
```

```
                 Poisson Mixed GLM Results
============================================================
              Type Post. Mean Post. SD   SD  SD (LB) SD (UB)
------------------------------------------------------------
Intercept        M     0.0263   0.1203                      
n_relapse_xmt    M     0.9947   0.0237                      
f_id_site        V    -0.2097   0.1082 0.811   0.653   1.007
============================================================
Parameter types are mean structure (M) and variance
structure (V)
Variance parameters are modeled as log standard deviations
```

**Comment by luxexmachina** [comment]
@kshedden Could you please share your platform details? I tried to run your example code and got the 'vcp_names' error.

**Comment by kshedden** [comment]
I am running this on the statsmodels master branch from github.  I just checked the example above again, and it works for me with the current master.  This was a statsmodels issue, so I don't think other platform details are relevant, but I am running python 3.5.2, numpy 1.16.1, pandas 0.24.1.

**Comment by yudiaspen** [comment]
@luxexmachina @FedericaLionetto
pip uninstall statsmodel
then download the master branch from github
in the downloaded folder run python3 setup.py install
then you are good to go
