### ISSUE TITLE
Gamlss prediction zero/one inflated beta regression with random term

### ISSUE THREAD

**Issue by Hallo951** [statsmodels/statsmodels#4818]
Hi,

i am working with gamlss only recently. I would like to model with gamlss vegatation coverage data including random terms. The best distributions for this are the zero inflated beta distribution (family: BEZI), one inflated beta distribution (family: BEOI), beta distribution (family: BE) and the beta inflated distribution (family: BEINF). The random term was included in the formula with "random (variable)". The Fit (model creation) works wonderfully (fast and robust) and the results look very good.

I would now like to apply the sample-based models to new areas in the context of habitat modeling and perform a 10-fold cross-validation. And here is my problem. After a long search, I discovered that the predict function of gamlss currently does not predict for models with a random factor (Source: http://www.gamlss.com/wp-content/uploads/2015/07/FlexibleRegressionAndSmoothingDraft-1.pdf , Page 107).

Question 1:
Is there any practical way to get an overall prediction of new data using the gamlss models where there is a random factor and an inflated distribution?

Question 2:
How do I get an overall forecast? For example, if I use the gamlss prediction function for a beta inflated distribution, I get output for mu (beta part), nu (zero part), and tau (ones part). So I have 3 different results. How do I get a total result / overall forecast?

Question 3:
If there is no way to change my plans with gamlss, which r-package can do this?

Thx... :)

**Comment by josef-pkt** [comment]
AFAICS, you got the wrong bug tracker, this is for statsmodels in Python and not GAMLSS in R

**Comment by CeresBarros** [comment]
I know this issue has been closed due to being in the wrong package, but I have the exact same question and can't find the answer anywhere, so @Hallo951  I was wondering if you ever found the answer to your question?
Thanks and sorry for spamming the statsmodels crew.
