### ISSUE TITLE
Installing statsmodels on Python3.7 + Pipenv 2018.7.1

### ISSUE THREAD

**Issue by majaldm** [statsmodels/statsmodels#4822]
I'm trying to install statsmodels on a Windows system, inside a virtual environment created with pipenv. This is the line I'm using:

    python -m pip install --upgrade --no-deps statsmodels

Python 3.7, Pipenv v2018.7.1 and Cython 0.28.4 are installed, and I get the following error : 

    Exception: Cython-generated file 'statsmodels/tsa/kalmanf/kalman_loglike.c' not found.
            Cython is required to compile statsmodels from a development branch.
            Please install Cython or download a source release of statsmodels.

Is there a solution for this problem or a compatible version I can fall back to?

**Comment by josef-pkt** [comment]
I think you need to use the source from github. The `sdist` includes the cython generated c files which are most likely incompatible with python 3.7.
Installing from github source (tag or master) requires cython and a compatible Microsoft C compiler on Windows.

We don't have testing for python 3.7 yet.

**Comment by majaldm** [comment]
Installing from git works fine, this is the command I used:

    python -m pip install --upgrade --no-deps git+https://github.com/statsmodels/statsmodels.git

For people who never did this before, you need the VisualStudio Build Tools Installed WITH the SDK for your operating system. Refer to this table for versions: https://www.scivision.co/python-windows-visual-c++-14-required/.

**Comment by DotPin** [comment]
I did install this package with next command:

sudo apt install python3-statsmodels

and it's work :)
