### ISSUE TITLE
Is PytestTester needed?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4833]
bunches of `__init__` files have 

```
from statsmodels import PytestTester
test = PytestTester()
```

and it isn't clear to me what these do.  What do these do?

**Comment by josef-pkt** [comment]
see https://github.com/statsmodels/statsmodels/issues/4245#issuecomment-362951092 and that issue
I will close this as duplicate of #4245

**Comment by jbrockmendel** [comment]
Thanks.
