### ISSUE TITLE
Make CI “failure” actually meaningful

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#4836]
At the moment a red “x” contains no useful information AFAICT.

**Comment by josef-pkt** [comment]
I got an email privately that LGTM has currently problems with building/analyzing statsmodels. Hopefully, the will fix it soonish.

**Comment by jbrockmendel** [comment]
Can it be disabled in the interim?

**Comment by jbrockmendel** [comment]
There are a couple of travis tests that are failing a ton because of network errors.  Can we disable them or point them toward a more reliable URL?
