### ISSUE TITLE
Estimate meta-analysis fixed-effect using smf.mixedlm

### ISSUE THREAD

**Issue by amirmasoudabdol** [statsmodels/statsmodels#4854]
Hi,

I'm quite baffled by the `mixedlm` and I'm wondering if someone can help me with it. I'm trying to estimate the fixed-effect estimate of several studies. My Dataframe looks like this:

```
>>> df[['yi', 'vi']].head()

	yi	        vi
0	0.405978	0.729500
1	0.186255	1.049197
2	0.697798	0.959012
3	0.456475	1.376878
4	0.342341	0.682404
```

`yi` is the effect size and `vi` is the variance of each effect. I can easily solve this by building this model `smf.WLS(df.yi, np.ones(len(df)).transpose(), weights = 1 / df.vi)`, and fitting it. However, I cannot figure out if it's possible to get the same results with the `mixedlm`. I think I cannot figure out how to translate the WLS to the `patsy` formula, and feed in the variances.

I've tried a few combinations but I cannot get the fixed intercept, `mixedlm(formula = 'yi ~ 1 + vi', data = df)` doesn't seem to produce what I want, and I think I'm actually asking `mixedlm` to fit the slope of the `vi` as well, which is not what I want. I think I need to use something like `yi ~ 1` but then I cannot include the weights.

Cheers,
Amir.

**Comment by kshedden** [comment]
It looks to me like you are calculating an inverse variance weighted mean.  This can be obtained most directly with `DescrStatsW`, although as you point out `WLS` can also be used.

Mixed models are typically used for data with correlated responses.  This might arise in a network meta analysis but I don't see any correlation structure in your example. 

In general, mixed models are not very flexible when it comes to handling heteroscedasticity.  I don't see mixed modeling as being a useful approach for you here.

**Comment by amirmasoudabdol** [comment]
Thanks for the reply. I was starting to guess that it's not possible apparently since I've tried many parameters combinations and didn't manage to build the model. I think the reason was mainly to generalize the code in such a way that I can formulate both fixed- and random-effect into one function. But I guess, that's not necessary and I can just do it simpler this way.

I didn't know about the `DescrStatsW`, and it is in fact what I want. Thanks 👍

**Comment by josef-pkt** [comment]
`weights` in `DescrStatsW` have a case/frequency weight interpretation, so results might not be correct for variance weights.
