### ISSUE TITLE
MAINT: drop nose dependency

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4867]
I think we can drop nosetest dependency and convert over to only supporting pytest

triggered by discussion on numpy mailing list about which more advanced features of pytest to use in unit tests.

personal note: 
My transition period for switching from nosetests to pytest as a test runner is essentially over. I got used to the more verbose output of pytest and have been using it locally almost exclusively for some time now

**Comment by jbrockmendel** [comment]
+1

**Comment by bashtage** [comment]
Testing against old numpy requires master, and supporting NumPy >= 1.11 requires retaining nose as a test dependency.

**Comment by josef-pkt** [comment]
@bashtage  Do we need nose inside statsmodels or only as dependency of numpy testing in older version of numpy?
that is, can we drop our nose code and run with pytest only on latest numpy and pandas, and with the additional nose dependency on older numpy and pandas?

**Comment by bashtage** [comment]
All nose imports should be removable from statsmodels directly.  I suppose it can be dropped as a testing dependency in the sense that SM doesn't depend on it, although NumPy < 15 might if using something older then latest.

There are only a tiny handful of imports of nose in master.  These can all be dropped.

**Comment by jbrockmendel** [comment]
IIRC nose is used by `np.testing.dec` and `np.testing.assert_raises`, both of which we should be using the pytest alternatives for anyway.
