### ISSUE TITLE
ZeroDivisionError given by endog length in statsmodels.tsa.holtwinters.ExponentialSmoothing.fit()

### ISSUE THREAD

**Issue by g8a9** [statsmodels/statsmodels#4878]
Hi,
I was using the ExponentialSmoothing class, fitting an **endog array of length 5**. The method raises a **ZeroDivisionError**, here it is the relevant part of the stack:
```python
File "/Users/giuseppe/development/time_series_forecasting/exp_smoothing.py", line 125, in forecast_sliding_window
    model_fit = ExponentialSmoothing(window, trend=None, seasonal=None).fit(smoothing_level=0.8)
  File "/Users/giuseppe/development/time_series_forecasting/venv/lib/python3.6/site-packages/statsmodels/tsa/holtwinters.py", line 594, in fit
    use_boxcox=use_boxcox, lamda=lamda, remove_bias=remove_bias)
  File "/Users/giuseppe/development/time_series_forecasting/venv/lib/python3.6/site-packages/statsmodels/tsa/holtwinters.py", line 735, in _predict
    aicc = aic + (2 * (k + 2) * (k + 3)) / (self.nobs - k - 3)
ZeroDivisionError: division by zero
```
As far as I can understand, the problem is created by these lines in **holtwinters.py**:
```python
...
733 k = m * seasoning + 2 * trending + 2 + 1 * damped
734 aic = self.nobs * np.log(sse / self.nobs) + (k) * 2
735 aicc = aic + (2 * (k + 2) * (k + 3)) / (self.nobs - k - 3)
...
```

- *self.nobs* is equivalent to the length of input endog array: 5. 
- *k*, in my case of Simple Exponential Smoothing (*seasoning, trending and damped* are 0) is 2. 

Also, what happens if the divider is negative (e.g. trying to fit an endog array of 3 values)? Does it invalidate results given by the model?

**Comment by bashtage** [comment]
This is a known problem.  Reports/Fixes in Issues/PR #4796 , #4825 , #4845
