### ISSUE TITLE
BLD: Replace LGTM with Codacy

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#4894]
LGTM seems to be having significant problems providing any insights. [Codacy](https://www.codacy.com/)  is a good alternative that is free to OSS.

**Comment by jbrockmendel** [comment]
Related #4836

**Comment by ChadFulton** [comment]
+1 from me (although I think I remember Josef saying LGTM we working on
fixing some of their problems?)

**Comment by josef-pkt** [comment]
It has been already two weeks, and their log shows a memory exceeded error.
(Earlier today I tried to see whether there is an option to skip some checks but it doesn't seem be possible. Then I got distracted with family related things.)

I would like to, at least temporarily, disable the LGTM checks for now, We can add Codacy to see how well that works.

**Comment by josef-pkt** [comment]
I enabled codacy 
https://app.codacy.com/project/josef-pkt/statsmodels/dashboard
3481 total issues
163288 total LoC

as with LGTM the main interesting item will be changes introduced by PRs.

**Comment by josef-pkt** [comment]
"Powered by PyLint"

**Comment by josef-pkt** [comment]
I looked at the codacy results for "new issues" in several of my PRs and it's pretty informative, even when I don't agree with whether the "violation" is and issue

**Comment by jbrockmendel** [comment]
The section on duplicated code is nice

**Comment by josef-pkt** [comment]
as extra info that I had forgotten to add:
I had revoked, for now, the LGTM access to the statsmodels github account, so we don't see the non-working fails.

**Comment by jbrockmendel** [comment]
It looks like there may be a setting sections where some things can be customized.  Two checks that I'd advocate turning off:

- complaints in tests of the form "this doesn't need to be a method, could just be a function"
- dont use `assert` because it can be optimized away

**Comment by bashtage** [comment]
You can use .codacy.yml to remove checks
