### ISSUE TITLE
SARIMAX get_prediction results very different depending on prediction start

### ISSUE THREAD

**Issue by bobbejaan** [statsmodels/statsmodels#4902]
I am testing the SARIMAX algorithm, with a very simple system. There is one exogenous variable moving from 0 to 1, and the endogenous variable just follows a first order response.
![image](https://user-images.githubusercontent.com/33159391/44080178-8d38425e-9fab-11e8-8a2d-038c09c9f068.png)

At 2018-03-15 the input goes from 0 to 1 and the output starts to rise at the same time. I am trying 2 cases:
- Starting the dynamic prediction after the output starts to rise (e.g. at 2018-03-16). This gives the expected result. The prediction and the actuals are close to each other.
![image](https://user-images.githubusercontent.com/33159391/44080360-180e6a02-9fac-11e8-933e-058867b8f484.png)
- Starting the dynamic prediction just before the output starts to rise (e.g. at 2018-03-14). For some reason, now the prediction gives very different results, although the model should be the same.
![image](https://user-images.githubusercontent.com/33159391/44080474-689dbd74-9fac-11e8-84dd-cb8135afa356.png)

It looks like the get_prediction method is not correctly using the exogenous variable information in its prediction. What can be done to make the prediction more accurate for the second case?

Here are some snippets of the code:
`mod = sm.tsa.statespace.SARIMAX(endog, exog, order=(1, 1, 1))`
`res = mod.fit(disp=True)`
`startPredDate = '2018-03-16'`
`predict_dy = res.get_prediction(dynamic=startPredDate)`
`predict_dy_ci = predict_dy.conf_int()`

` # Graph`
` fig, ax = plt.subplots(figsize=(9,4))`
` ax.set(title='Modeled response', xlabel='Time', ylabel='output')`
 `# Plot data points`
`endog.plot(ax=ax,  label='Observed')`
    
`# Plot predictions`
` predict_dy.predicted_mean.loc[startPredDate:].plot(ax=ax, style='g', label='Dynamic forecast')`
`ci = predict_dy_ci.loc[startPredDate:]`
`ax.fill_between(ci.index, ci.iloc[:,0], ci.iloc[:,1], color='g', alpha=0.1)`

**Comment by ChadFulton** [comment]
The main issue here is that our SARIMAX is a "regression with SARIMA" errors, and you're looking for the other kind of SARIMAX model (see e.g. https://robjhyndman.com/hyndsight/arimax/).

Here's a notebook that shows what I mean, and how the other kind of model works the way you're expecting it to:

https://gist.github.com/ChadFulton/fac61cc2b2cb07eddfa3e87babb6e9cc

Unfortunately, we don't have a built-in class in Statsmodels that supports the case you're thinking of, although that would be a nice addition if you were interested in one. For example, a general transfer function class might be nice.

**Comment by bobbejaan** [comment]
Thank you sir!

I used a different workaround to allow for dynamic regression/prediction, which is by using an array of delayed exogenous values in the model. For example:

`def addExogShift(exog_in, n):` 
`         exog = exog_in` 
`         for i in range(1,n):` 
`             exog_i = exog_in.shift(i)` 
`             exog_i[0:i] = exog_in[0]` 
`             exog = pd.concat([exog, exog_i],axis=1)` 
`         return exog` 
    
` exog = addExogShift(exog0, 20)`
`mod = sm.tsa.statespace.SARIMAX(endog, exog, order=(1,1,1))`
![image](https://user-images.githubusercontent.com/33159391/44207472-b675bd00-a15d-11e8-8593-67d789201dad.png)

Of course this workaround has a some drawbacks. But it does allow to use the current implementation of the SARIMAX model as a dynamic regressor. 
But yes, having a transfer function class would be a great addition!

**Comment by ChadFulton** [comment]
Yep, that works great!
