### ISSUE TITLE
AR Model AIC problem

### ISSUE THREAD

**Issue by patkru** [statsmodels/statsmodels#4904]
I am comparing various AR models (`statsmodels.tsa.api.AR`), that differ by `maxlag` param (from 1 to 
300). My series is ~400 observations long.

The AIC drops magicly around the lag=180. I investigated a little bit, and I see that this is because of the fact that the `sigma2` drops to 0 at this level, so np.log(sigma2) starts acting weird (btw. shouldn't it go to -inf instead of -60?). The plot below shows AIC (blue line) vs. sigma2 (orange line) and np.log(sigma2) (green line).

![aic](https://user-images.githubusercontent.com/36115376/44093322-7f9f27e8-9fd3-11e8-9062-202b28f63d20.png)

I am not certainly sure, but I think there's something wrong with calculation of sigma2 over here. It drops to 0 at some point, which is almost impossible using empirical data. [The docstring of *class ARResults*](https://www.statsmodels.org/dev/_modules/statsmodels/tsa/ar_model.html#AR) says:

> aic : float
>        Akaike Information Criterion using Lutkephol's definition.
>        :math:`log(sigma) + 2*(1 + k_ar + k_trend)/nobs`

but the formula below is:

> @cache_readonly
>     def aic(self):
>         #JP: this is based on loglike with dropped constant terms ?
>         # Lutkepohl
>         #return np.log(self.sigma2) + 1./self.model.nobs * self.k_ar
>         # Include constant as estimated free parameter and double the loss
>         return np.log(self.sigma2) + 2 * (1 + self.df_model)/self.nobs

You can see, that the docstring says about sigma and the code uses sigma2 instead. Maybe it's just an inconsistency without real effect, but I was trying to find out what is wrong and that is the only thing that I noticed. Did not have enough time to test the formula calculating sigma2.

If you cannot reproduce the error yourself I can try to make up some data similar to mine.

**Comment by bashtage** [comment]
Are you sure that ~400 isn't actually 360?  If you are using OLS, then using 180 lags loses 180 observations so that there are 180 variables and 180 observations.

**Comment by patkru** [comment]
@bashtage you were right, that was the case and I did not notice that. Sorry for the confusion.
