### ISSUE TITLE
Enable Rolling Builds in Appveyor

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#4918]
@josef-pkt Rolling Builds will auto cancel pending PR builds when there is a new commit in the PR, so that only the latest commit will be built.  This is a useful setting given the time to build on appveyor.   This can be enabled in the main settings page of your appveyor account .

**Comment by josef-pkt** [comment]
Thanks, I changed the setting to rolling builds

I thought that was the default before, but the last few days I manually cancelled appveyor jobs  (when newer job of same PR was scheduled) to reduce the backlog.
