### ISSUE TITLE
REF/TST: use https in webuse

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4928]
we get intermittent test failure in `webuse` with bad gateway

maybe switching to https helps, which seems what github uses

`https://github.com/statsmodels/statsmodels/blob/master/statsmodels/datasets`

**Comment by jbrockmendel** [comment]
For the tests it might be worth mocking out the request.  Or xfail in the case of a network error.

**Comment by josef-pkt** [comment]
it already checks whether internet is available.
We had several problems with it in the past, but we should only catch minimal, expected problems.
It's difficult to distinguish expected problems, e.g. with network, from bugs.

**Comment by bashtage** [comment]
I think this is in the dataset-recarray PR
