### ISSUE TITLE
Model Simulations Not Following Predicted Mean Confidence Interval

### ISSUE THREAD

**Issue by WillFuks** [statsmodels/statsmodels#4951]
(this is a follow up of [this question](https://stackoverflow.com/questions/51881148/simulating-time-series-with-unobserved-components-model/51904036#51904036) in SO, it was getting too big so maybe here it's more appropriate)

I've generated this dataset:

```
import numpy as np
from statsmodels.tsa.statespace.structural import UnobservedComponents
from statsmodels.tsa.arima_process import ArmaProcess
from matplotlib import pyplot as plt

np.random.seed(12345)
ar = np.r_[2, 0.9]
ma = np.array([1])
arma_process = ArmaProcess(ar, ma)

X = 100 + arma_process.generate_sample(nsample=100)
y = 1.2 * X + np.random.normal(size=100)

plt.plot(X, label='X')
plt.plot(y, label='y')
plt.axvline(69, linestyle='--', color='k')
plt.legend();
```
![so_generated_data](https://user-images.githubusercontent.com/20802819/44406793-e98bc800-a532-11e8-8528-09f4e93036ed.png)

So I fit a Unobserved Model and try to simulate some series following the trained model params:

```
X_pre = X[:70]
X_post = X[70:]
y_pre = y[:70]
y_post = y[70:]

model = UnobservedComponents(
  endog=y_pre,
  level='llevel',
  exog=X_pre
)

f_model = model.fit()

mod1 = UnobservedComponents(
    np.zeros(len(X_post)),
    level='llevel',
    exog=X_post,
    initial_variance=1
)

sim = mod1.simulate(f_model.params, len(X_post))
plt.plot(sim, label='simul')
plt.plot(y_post, label='y')
plt.legend();
```
![so_simulated_y](https://user-images.githubusercontent.com/20802819/44408100-0d044200-a536-11e8-9779-362aff9d1c60.png)

But for some reason all the simulations ends up being lower than `y_post`. I wonder if this is the expected behavior. I imagined that most of the simulations would lie somewhere between the forecast predicted mean and its confidence interval but in practice all simulations fall beneath the lower confidence interval.

For what I could test, we have to use `initial_variance=1` as otherwise the simulations ends up way off the expected value. I wonder if maybe there's still some parameter we need to use in order for most of the simulations to lie in the 95% confidence interval.

I'm using Python3, statsmodels 0.9.0, running inside ipython docker image.

**Comment by ChadFulton** [comment]
Hey great news! Thanks!
