### ISSUE TITLE
TST: pytest different behavior running all or only specific tests

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#4965]
It's the first time in a long time that I run the entire test suite instead of by directory or modules.

I get many failures when running the entire test suite, but they don't show up when I run individual subpackages, folders or modules.

It's not clear to me what's going on, and entire test runs take a long time to quickly investigate.
(I ran the test suite on the commandline with `pytest path_to_statsmodels` but the windows shell shows at the end only a very small part of the output. During the run I got results like
```
..\eclipse_ws\statsmodels\statsmodels_py34_pr\statsmodels\genmod\tests\test_gee.
py .......F.F.F....F...F....F.FFFFF.FFFF....E.....F
```

running `statsmodels.test()` in IDLE, I get
` 140 failed, 6328 passed, 130 skipped, 4 xfailed, 1 xpassed, 470 error in 1403.47 seconds `
with e.g. the same fails as above for test_gee.py

**Comment by bashtage** [comment]
Examples?

Try
```
pytest statsmodels --skip-examples
```


I regularly run the full suite without issues.

**Comment by josef-pkt** [comment]
maybe my pytest is too old, folder name: `pytest-3.0.3.dist-info`
warnings capture in pytest mentions added in 3.1
(I didn't find any options to change the behavior, and going through the pytest docs seems to show things that don't work for my version.)
(I'm not going to run entire test suite on a regular basis anyway)

**Comment by bashtage** [comment]
Probably too old.  Warnings are suppressed by default when using .test() methods.

**Comment by jbrockmendel** [comment]
Possibly related #5110

**Comment by josef-pkt** [comment]
Not closed, 
We only found a few problems with missing random seed when using a random test sequence.

The problem that I had in this issue with running all unit tests locally is different, and is most likely a setup problem or it requires a newer pytest.
I will eventually try again and get a newer pytest, but not for now.

**Comment by josef-pkt** [comment]
I updated to pytest 3.8 and the failures are gone

`>pytest path_to_statsmodels\statsmodels -r a --skip-examples > pytest_20180916_1.log.txt 2>&1`

I have fails that are all in knockoff with cvxopt which is buggy in my older version
` 12 failed, 6979 passed, 167 skipped, 4 xfailed, 1 xpassed, 268 warnings in 929.00 seconds `

**Comment by josef-pkt** [comment]
see also #5215 minimum version for pytest
