### ISSUE TITLE
test_edgeworth "stolen verbatim from scipy/stats/tests/test_continuous_extra.py"

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5009]
Is the code under test also copied?

**Comment by josef-pkt** [comment]
I don't remember but you can look through the git history.
scipy.stats and statsmodels share code and share(d) maintainer and developers, statsmodels pr is by Evgenyi when he was already a scipy maintainer. 
(some of the original code is in sandbox.distributions and comes from the time when I was working on scipy and starting with statsmodels.)

there is also other code that was written for scipy and then added verbatim or not to statsmodels.
