### ISSUE TITLE
How to automatically judge the seasonality of a time series?

### ISSUE THREAD

**Issue by Icarus0xff** [statsmodels/statsmodels#5033]
Hi,
Forgive my poor English.

I can decompose a time series by  `seasonal_decompose`, but how could I automatically judge the seasonality of the time series? All I want is a function like below:

```
INPUT: a time series
OUTPUT: if this has periodic, then return 1
```

**Comment by bashtage** [comment]
This doesn't exist.  The simplest methods in master are seasonal_decompos or STL, followed by the `plot()` function on the result instance that is produced, and then to use graphical inspection.
