### ISSUE TITLE
adding info on rsquared type in .summary() when no intercept

### ISSUE THREAD

**Issue by bertrandhaut** [statsmodels/statsmodels#5078]
The computation of R² is different (centered/uncentered) depending on the presence of an intercept.

While this is clear in the .rsquared() documentation, this can be suprising for people using only the .summary() function.

Maybe it can useful to add a mention somewhere in the output of .summary() that it is an "uncentered" R².

I see two possibilities:
- additional warning at the end of the output
- adding "'(uncentered)" just next to the "R-squared" label

```
OLS Regression Results                            
==============================================================================
Dep. Variable:                Lottery   R-squared (uncentered):          0.348
Model:                            OLS   Adj. R-squared (uncentered):     0.333
Method:                 Least Squares   F-statistic:                     22.20
Date:                Mon, 14 May 2018   Prob (F-statistic):           1.90e-08
Time:                        21:48:09   Log-Likelihood:                -379.82
No. Observations:                  86   AIC:                             765.6
Df Residuals:                      83   BIC:                             773.0
Df Model:                           2                                         
Covariance Type:            nonrobust   
```

If you think it's a good idea, I can try to propose a Pull Request.

**Comment by josef-pkt** [comment]
The idea sounds good to me.
Based on your output, there is enough space for adding it directly (possibility 2)

PR to add this will be welcome
RegressionResults.summary looks easy to change
summary2 might need a bit of digging to where the default is defined (I haven't looked for it)

**Comment by josef-pkt** [comment]
added in #5083
