### ISSUE TITLE
check for possible 0*log(0)

### ISSUE THREAD

**Issue by wesm** [statsmodels/statsmodels#51]
Original Launchpad bug 681444: https://bugs.launchpad.net/statsmodels/+bug/681444
Reported by: josef-pktd (joep).

discretemod still has several cases that could possibly end up with 0*log(0)

Poisson is protected with np.clip

many other logs are unprotected, I don't think we have test cases, or how close to zero or one it is possible to get in different cases.

exog*beta is a float type and might not get close enough to zero to create a problem (?)

**Comment by josef-pkt** [comment]
closing this, there might be more specific issues now. One task will be to use scipy's function `xlogy` eventually
