### ISSUE TITLE
sm.examples.t_est_rlm --> supposed to be a test?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5100]

**Comment by josef-pkt** [comment]
"Example from robust test_rlm, fails on Mac"

Based on the docstring comment was taken from a unit test and it was used to investigate some unit test failures. I guess the unit test is still there.

**Comment by jbrockmendel** [comment]
> Based on the docstring comment was taken from a unit test and it was used to investigate some unit test failures

so... this appears to exist as a test in `test_rlm.TestRlm`, and it running the file on OSX now it passes.  So this file is now unnecessary?

**Comment by jbrockmendel** [comment]
> Those example files contained my fast response examples.

Which is great.  But its in a directory called "examples" that is released to users.  Users might look at that and get the idea that the directory contains examples...

**Comment by jbrockmendel** [comment]
Closing in favor of #5145.
