### ISSUE TITLE
Large numbers of pytest setup failures

### ISSUE THREAD

**Issue by matthew-brett** [statsmodels/statsmodels#5108]
Running wheel tests on master, getting large numbers of failures like the following:

```
item = <Function 'test_orig'>
    def pytest_runtest_setup(item):
        if 'slow' in item.keywords and item.config.getoption("--skip-slow"):
            pytest.skip("skipping due to --skip-slow")
    
>       if 'slow' not in item.keywords and item.config.getoption("--only-slow"):
E       ValueError: no option named 'only_slow'
```

https://travis-ci.org/MacPython/statsmodels-wheels/jobs/424705784

Maybe an API change in pytest?

**Comment by bashtage** [comment]
Probably need to check that conftest.py is being copied.  It should be at statsmodels/conftest.py.

**Comment by bashtage** [comment]
Bug in pytest: pytest-dev/pytest#1596

**Comment by bashtage** [comment]
What triggered the bug was that we moved conftest.py to be inside statsmodels.

**Comment by matthew-brett** [comment]
Looks like a six-legged feature, no?  At least it's not clear it's going to get fixed / changed in the near future.

**Comment by bashtage** [comment]
Will need to do what pandas-wheels does for testing:

https://github.com/MacPython/pandas-wheels/blob/master/config.sh

**Comment by bashtage** [comment]
pandas has the same structure so it must be addressable.

**Comment by bashtage** [comment]
This command doesn't quite work right.  Once #5120 has been merged, the correct test command will be

`python -c 'import statsmodels; statsmodels.test(exit=True)'`

to ensure that a failure exits with a non-zero exit code.

**Comment by jbrockmendel** [comment]
#5120 has been merged; closeable?

**Comment by matthew-brett** [comment]
Yes, closable, indeed, closing.
