### ISSUE TITLE
DeprecationWarnings for invalid escapes in CI

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5131]
In Travis logs I'm seeing a bunch of 
```
<unknown>:370: DeprecationWarning: invalid escape sequence \J
<unknown>:462: DeprecationWarning: invalid escape sequence \(
<unknown>:470: DeprecationWarning: invalid escape sequence \(
<unknown>:473: DeprecationWarning: invalid escape sequence \s
<unknown>:474: DeprecationWarning: invalid escape sequence \s
<unknown>:477: DeprecationWarning: invalid escape sequence \s
<unknown>:14: DeprecationWarning: invalid escape sequence \e
/home/travis/build/statsmodels/statsmodels/statsmodels/tsa/vector_ar/tests/JMulTi_results/parse_jmulti_vecm_output.py:216: DeprecationWarning: invalid escape sequence \d
  str_number = "-?\d+\.\d{3}"
/home/travis/build/statsmodels/statsmodels/statsmodels/tsa/vector_ar/tests/JMulTi_results/parse_jmulti_vecm_output.py:217: DeprecationWarning: invalid escape sequence \)
  regex_est = re.compile(str_number + "[^\)\]\}]")
```

Some of these I can track down and fix, but in particular the `\J` ones need to be done by someone else.  AFAICT these are caused by tons of places around the code where something like `  File "C:\Josef\_progs\Subversion\scipy-trunk_after\trunk\dist\scipy-0.9.0.dev6` is put inside a docstring as a way to comment it out.

(23 occurrences of ":\Josef" across the codebase, some of them just commented-out instead of in docstrings.  A few in actual code.  28 more for ":\josef")

Anyone want to take bets on what I think should be done with these?

**Comment by josef-pkt** [comment]
In general this means that the `\` is not escaped.
The easies fix, if there or more backslashes in the docstring is to use a raw string, e.g. `r"""`

**Comment by jbrockmendel** [comment]
For some of them that works.  There is at least one case in docstrings where there is an unfortunate mix between single and double backslashes.

For the "\J"s I don't plan to address them myself, but will periodically ask that someone non-me find a better long-term way of representing whatever useful information they contain.
