### ISSUE TITLE
Use close_figures fixture to do have_matplotlib check?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5161]
Tons of test files do this exact same check:

```
try:
    import matplotlib.pyplot as plt
    have_matplotlib = True
except ImportError:
    have_matplotlib = False
```

Couldn't that be done within `close_fixtures`?

**Comment by jbrockmendel** [comment]
Sounds not worth the hassle, closing.

**Comment by bashtage** [comment]
I just implemented it and will push the branch in a minute.
