### ISSUE TITLE
Speed up the cross-correlation function

### ISSUE THREAD

**Issue by hernan3009** [statsmodels/statsmodels#5199]
Dears,

I noticed that the computation of the cross corrlation function is extremely slower than the autocorrelation function.

It seems to me that this is because of two reasons, but I am not an expert in the field: 
* acf function lets fix the nlags parameter and ccf does not, the latter compute every lag (commonly unneceary)
* acf 'does a trick' with FFT while ccf does not.

Is it possible to speed up the ccf?

**Comment by josef-pkt** [comment]
It's possible to add all the same methods as in adf to ccf.

I guess, without looking, that acf and ccf could share most of the code
