### ISSUE TITLE
typing error?

### ISSUE THREAD

**Issue by franchesoni** [statsmodels/statsmodels#5212]
https://www.statsmodels.org/dev/_modules/statsmodels/tsa/stattools.html#pacf

in the code says

...
        ret = pacf_yw(x, nlags=nlags, method='mle')
    elif method in ['ld', 'ldu', '**ldunbiase**', 'ld_unbiased']:
        acv = acovf(x, unbiased=True)
...
which leads to an error when using 'ldunbiased' as method

**Comment by jbrockmendel** [comment]
Looks like you’re right.  PR to fix would be welcome

**Comment by bashtage** [comment]
Fixed in master.
