### ISSUE TITLE
TST/BLD: pytest minimum version

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#5215]
Why do we require a pytest minimum version of 3.6?

https://github.com/statsmodels/statsmodels/blame/master/setup.cfg#L5

I commented it out locally in my checkout so I can keep running with an old pytest.

**Comment by josef-pkt** [comment]
@bashtage

**Comment by bashtage** [comment]
I think there was a fix that cane in at 36 but don't fit recall.  Otoh upgrading pytest is pretty simple

**Comment by bashtage** [comment]
This is the reason:

```
Revamp the internals of the pytest.mark implementation with correct per node handling which fixes a number of long standing bugs caused by the old design. This introduces new Node.iter_markers(name) and Node.get_closest_mark(name) APIs. Users are strongly encouraged to read the reasons for the revamp in the docs, or jump over to details about updating existing code to use the new APIs. (#3317)
```

to ensure that we don't hit these issues when using custom marks.

**Comment by josef-pkt** [comment]
Ok, I will update pytest soon.
pytest 3.6 is in the latest two Debian, so this should be fine without extra works
https://packages.debian.org/search?keywords=python3-pytest

**Comment by jbrockmendel** [comment]
closeable?

**Comment by bashtage** [comment]
No longer correct or relevant.
