### ISSUE TITLE
CI: use azure pipelines?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5231]
Over at pandas they’re setting it up.

Could widen the set of tested configs or take pressure off the bottlenecks.

**Comment by josef-pkt** [comment]
Also there is a discussion on the numpy mailing list.

As usual it is better to wait for others to figure out the problems, then we can add it.

**Comment by kaylangan** [comment]
I'm a Program Manager on Azure Pipelines. Let me know if I can help or if you have any suggestions.

**Comment by jdbohrman** [comment]
> I'm a Program Manager on Azure Pipelines. Let me know if I can help or if you have any suggestions.

I just started playing with Azure Pipelines. I've been an AWS guy for awhile but I'm enjoying what you guys offer.

**Comment by kaylangan** [comment]
> > I'm a Program Manager on Azure Pipelines. Let me know if I can help or if you have any suggestions.
> 
> I just started playing with Azure Pipelines. I've been an AWS guy for awhile but I'm enjoying what you guys offer.

That's great to hear! Feel free to send any questions or feedback my way!

**Comment by josef-pkt** [comment]
automatically created PR is #5423

**Comment by jbrockmendel** [comment]
Closed by #5617
