### ISSUE TITLE
Problem in statsmodel.api.OLS

### ISSUE THREAD

**Issue by panranyang** [statsmodels/statsmodels#5236]
I guess there's something wrong about degree of freedom, which affect F-statistic and some others,

About df_model,  as far as I can see,  it equals the number of  regressors (exclude intercept). instead, when I use the function, OLS(y_vector(n*1), x_matrix(n*p), hasconst=False), it gives me df_model=p-1, while hasconst=True, it gives me df_model= p-2.

I think df_model equals number of regressors(exclude intercept) instead of the number -1.

Maybe I'm wrong about it, I will be very thankful to receive your opinions

**Comment by josef-pkt** [comment]
I don't see anything suspicious in the code
`df_model = self.rank - self.k_constant`

Check that k_constant is zero in your example and that rank is the same as the number of columns of exog.
If your exog is singular, than df_model and df_resid corresponds to the rank and not the number of explanatory variables.

**Comment by panranyang** [comment]
Thanks , Dr. Perktold. It's the singular problem. I should have read the code carefully!
