### ISSUE TITLE
VAR VECM Tracking Issue

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#5243]
A tracking issue for all VAR and VECM-related posts.

**PRs**
- [ ] #815
- [ ] #2869 
- [ ] #3028
- [ ] #5244

**Issues**
- [ ] #3434
- [ ] #4535
- [ ] #99
- [ ]  #671
- [ ] #365
- [ ] #234
- [ ] #189
- [ ] #153
- [ ] #142
- [ ] #379
- [ ] #382
- [ ] #395
- [ ] #756
- [ ] #757
- [ ]  #769
- [ ] #813
- [ ] #851
- [ ] #1065
- [ ] #1217
- [ ] #3568
- [ ] #3562
- [ ] #3434
- [ ] #3388
- [ ] #3368
- [ ] #3260
- [ ] #3240
- [ ] #3775
- [ ] #3803 
- [ ] #3209
- [ ] #3154
- [ ] #3143
- [ ] #3133
- [ ] #3132
- [ ] #3115
- [ ] #3109
- [ ] #3089
- [ ] #3025
- [ ] #3009
- [x] #2976
- [ ] #2933
- [ ] #2276
- [ ] #2342
- [ ] #2355
- [ ] #2414
- [ ] #2625
- [ ] #2648
- [ ] #2745
- [ ] #2838
- [ ] #2355
- [ ] #2274
- [ ] #2273
- [ ] #2270
- [ ] #2207
- [ ] #2206
- [ ] #2068
- [ ] #1731
- [ ] #1675
- [ ] #1217
- [ ] #1065
- [ ] #3137

**Comment by jbrockmendel** [comment]
#5244

**Comment by bashtage** [comment]
Closing as not longer needed.
