### ISSUE TITLE
MNLogit: ValueError: operands could not be broadcast together with shapes (17,) (17,2) 

### ISSUE THREAD

**Issue by lxxwin** [statsmodels/statsmodels#5247]
Two issues: 
- summary2 had a bug that had been fixed already in 0.9
- another case of memory error with MNLogit margeff #4158

**original**

always meet this problem when use the .summary() or .summary2()

Optimization terminated successfully.
         Current function value: 0.131978
         Iterations: 351
         Function evaluations: 352
         Gradient evaluations: 352
Traceback (most recent call last):

  File "<ipython-input-1-9ab889583086>", line 1, in <module>
    runfile('C:/Users/Administrator/Desktop/try2.py', wdir='C:/Users/Administrator/Desktop')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Administrator/Desktop/try2.py", line 97, in <module>
    print(mdl.fit(method='bfgs',maxiter=10000000000000000).summary2())

  File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py", line 3043, in summary2
    confint[i])

  File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\iolib\summary2.py", line 336, in summary_params
    conf_int = results.conf_int(alpha)

  File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py", line 2983, in conf_int
    cols=cols)

  File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\base\model.py", line 1685, in conf_int
    lower = self.params - q * bse

ValueError: operands could not be broadcast together with shapes (17,) (17,2)

**Comment by lxxwin** [comment]
I use the mnlogit regression of statsmodels

**Comment by lxxwin** [comment]
I have checked. There's no missing values in the raw data.

**Comment by jtweeder** [comment]
Hey @lxxwin can you provide some more context on your data (or at least part) and also how you are calling mnlogit?  Version of statsmodels you have would also be helpful.

I just tried to recreate on statsmodels 0.9.0 without a problem.
```Python
from statsmodels.discrete.discrete_model import MNLogit as mnl
import pandas as pd

exec_data =sm.datasets.cpunish.load_pandas().data

#Make outcome binary, and pick some predictors
Y = (exec_data['EXECUTIONS'] >= 3).replace([True,False],[1,0])
X = exec_data[['PERBLACK','SOUTH','DEGREE']]

#build model and summary
mnl(Y, X).fit().summary()
```
![image](https://user-images.githubusercontent.com/31365056/45921697-0b54d380-be80-11e8-9a52-95fd863e4b3f.png)

I even tried to change Y into a two-column output with no issues.
```Python
Yby2 = pd.get_dummies(Y)

#build model and summary
mnl(Yb2, X).fit().summary2()
```
![image](https://user-images.githubusercontent.com/31365056/45921759-8ec2f480-be81-11e8-8c5d-1113263dba71.png)

**Comment by lxxwin** [comment]
@jtweeder  v94 C(v13)+C(v18)+C(v64)+C(v87) are category variables
                   v23+v102+v159+v165+v166 are continuous variables    (10 columns)
The dataset is very large with more than 60,000,000 rows.  

import pandas as pd
from scipy import *
df = pd.read_stata(r'C:\Users\Administrator\Desktop\data-simp-complet.dta')
print(df.head())

vars = ['v94','v13','v18','v64','v87','v23','v102','v159','v165','v166']
dt = df[vars]
print(dt.tail())

from patsy import dmatrices
Y,X= dmatrices('v94 ~ C(v13)+C(v18)+C(v64)+C(v87)+v23+v102+v159+v165+v166',data = dt, return_type = 'dataframe')
print(Y.head())
print(X.head())

import statsmodels.api as st
# MNL
mdl = st.MNLogit(Y, X)
mdl_fit = mdl.fit(method='bfgs',maxiter=10000000000000000)
### print model summary ###
print (mdl_fit.params)
print (mdl_fit.summary2())
### marginal effects ###
print (mdl_fit.get_margeff().summary())

print('finish11')

**Comment by lxxwin** [comment]
statsmodels version 0.8.0

**Comment by jbrockmendel** [comment]
MNLogit summary is known broken.  I think also conf_int.

**Comment by lxxwin** [comment]
@ChadFulton  @Josef Perktold   @Skipper Seabold  @Ralf Gommers    @Vincent Arel-Bundock    @Wes McKinney

**Comment by lxxwin** [comment]
> MNLogit summary is known broken. I think also conf_int.

Any solutions?

**Comment by lxxwin** [comment]
I have run a logit model before with a different DV(0-1 variable) and the same IV as mnlogit, also the same dataset. The summary can be printed out successfully.

**Comment by josef-pkt** [comment]
Note, the bug was in summary2 and was fixed for 0.9 #3661 
`summary` didn't have that bug

the original example used `summary2`, jtweeder used `summary`

There are still some bugs left in mnlogit because it uses 2-dim params, e.g. pandas confint don't work, numpy array confint are 3-dim. (see open issues for those)

**Comment by josef-pkt** [comment]
@lxxwin If you upgrade to 0.9, can you check the other things that you use and might not work.
For example I'm not sure about the status of mnlogit margeff.summary()
The only issue I can find is for memory problems in larger dataset mnlogit margeff, but I don't know if mnlogit margeff has enough unit tests, and don't remember whether I had checked an example.

If this issue is only for the mnlogit summary2, then we can close this issue as duplicate and already fixed.

**Comment by lxxwin** [comment]
> @lxxwin If you upgrade to 0.9, can you check the other things that you use and might not work.
> For example I'm not sure about the status of mnlogit margeff.summary()
> The only issue I can find is for memory problems in larger dataset mnlogit margeff, but I don't know if mnlogit margeff has enough unit tests, and don't remember whether I had checked an example.
> 
> If this issue is only for the mnlogit summary2, then we can close this issue as duplicate and already fixed.

Thanks a lot. I'm now trying statsmodels 0.9.0.

**Comment by lxxwin** [comment]
> @lxxwin If you upgrade to 0.9, can you check the other things that you use and might not work.
> For example I'm not sure about the status of mnlogit margeff.summary()
> The only issue I can find is for memory problems in larger dataset mnlogit margeff, but I don't know if mnlogit margeff has enough unit tests, and don't remember whether I had checked an example.
> 
> If this issue is only for the mnlogit summary2, then we can close this issue as duplicate and already fixed.

Oh, I also meet memory problems in logit margeff.

**Comment by josef-pkt** [comment]
@lxxwin 
the memory error is #4158
It would be useful if you could add some information in a comment there about the size of your dataset, number of observations and shape of `params`, i.e. number of choices in endog and number of exog.

The memory consumption problem might not be fixed very fast, because margeff is based on some complex/complicated code that I only got partway through in understanding it.

**Comment by lxxwin** [comment]
> > `@ChadFulton @josef-pkt @jseabold @rgommers @vincentarelbundock @wesm`
> 
> @lxxwin please do not ping that many people (it's considered a bit rude...). Maintainers who are currently active are subscribed to this repo anyway.

I'm so sorry, I've deleted it.

**Comment by lxxwin** [comment]
> @lxxwin
> the memory error is #4158
> It would be useful if you could add some information in a comment there about the size of your dataset, number of observations and shape of `params`, i.e. number of choices in endog and number of exog.
> 
> The memory consumption problem might not be fixed very fast, because margeff is based on some complex/complicated code that I only got partway through in understanding it.


I've tried statsmodels 0.9, and the bug in summary2 was indeed fixed for 0.9.
For the logit model, there are 2 categories in y. (named v95, binary categoricals) 
There are 9 independent variables
C(v13)+C(v18)+C(v64)+C(v87) are category variables (with 4,3,5,3 categories respectively)
v23+v102+v159+v165+v166 are continuous variables (Numeric type)
more than 60,000,000 records. (Df Residuals)
I want to get the margeff of each independent variable. (get_margeff().summary())
The RAM of my computer is 80G.

I also meet memory problems in mnlogit margeff.
Only the dependent variable is different. (v94 with 4 categories)

**Comment by josef-pkt** [comment]
The dataset would be too large for my computers anyway.
We are barely get use to that many observations. My informal target is to be able to handle generically without problems somewhere in the 5 to 10 million range.

However, the width of your dataset is not large, 3 or 4 times 17 should work without problems, cov_params of 51 by 51
So, I think in this case it would be mainly splitting up the reduce which I guess is a sum or mean over all observations.

Is there a way to see where the memory error occurs?

**Comment by lxxwin** [comment]
I'm considering splitting up the dataset or just drop some observations but I didn't find a suitable way yet. It costs me several hours to run a logit or mnlogit model over the dataset. Sorry I didn't keep the detailed results of memory error. I remember it's an error like the valueerror above, showing where the memory error occurs. I will test margeff again when my computer is idle if necessary, and put the memory error result here.

**Comment by josef-pkt** [comment]
I'm closing this, reported bug was already fixed, memory error has separate issue
