### ISSUE TITLE
BUG: GEEResults fittedvalues ignores offset and exposure

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#5253]
GEEResults.fittedvalues uses explicit computation instead of going through predict

```
    @cache_readonly
    def fittedvalues(self):
        """
        Returns the fitted values from the model.
        """
        return self.model.family.link.inverse(np.dot(self.model.exog,
                                                     self.params))
```

all the resids are defined in terms of fittedvalues and will have the same behavior as consequence

this is incorrect in case of offset and inconsistent definition for exposure
GLM uses the correctly defined mu=predict() including user provided offset and exposure.

found when I tried to get an overview about how fittedvalues are defined
https://github.com/statsmodels/statsmodels/issues/37#issuecomment-424019626

**Comment by josef-pkt** [comment]
I haven't checked what is in the unit tests for GEE with offset.

**Comment by josef-pkt** [comment]
@kshedden Is there a reason why fittedvalues is defined this way that I missed?

**Comment by rebecca-palmer** [comment]
This _looks_ like it has an easy fix:
```
--- statsmodels-0.11.0.orig/statsmodels/genmod/generalized_estimating_equations.py
+++ statsmodels-0.11.0/statsmodels/genmod/generalized_estimating_equations.py
@@ -2000,8 +2000,7 @@ class GEEResults(base.LikelihoodModelRes
         """
         Returns the fitted values from the model.
         """
-        return self.model.family.link.inverse(np.dot(self.model.exog,
-                                                     self.params))
+        return self.model.predict(self.params)
 
     @Appender(_plot_added_variable_doc % {'extra_params_doc': ''})
     def plot_added_variable(self, focus_exog, resid_type=None,
```
...but given that it's a wrong-results bug over a year old, does having not done that already imply it isn't that easy?  (I haven't tested it yet.)

Sort of related: **GLM**Results.fittedvalues' docstring says it's the linear predictor; since it isn't, we should probably stop saying that.
```
--- statsmodels-0.11.0.orig/statsmodels/genmod/generalized_linear_model.py
+++ statsmodels-0.11.0/statsmodels/genmod/generalized_linear_model.py
@@ -1564,8 +1564,7 @@ class GLMResults(base.LikelihoodModelRes
     @cached_data
     def fittedvalues(self):
         """
-        Linear predicted values for the fitted model.
-        dot(exog, params)
+        Predicted values for the fitted model.
         """
         return self.mu
 
```

**Comment by kshedden** [comment]
I don't think there is a good reason for this.  We should fix it.
