### ISSUE TITLE
CI: lint.sh new-files check fails locally

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5259]
Running lint.sh locally gives:

```
/bin/bash lint.sh
inside lint.sh
Linting all files with limited rules
Linting known clean files with strict rules
fatal: --unshallow on a complete repository does not make sense
Linting newly added files with strict rules
[long list of lint complaints]
```

AFAICT it is considering everything to be a newly-added file in this context.
Downstream I still get the "fatal: --unshallow on a complete repository does not make sense" line without the lint complaints, but end up with return code 0.

**Comment by bashtage** [comment]
Is everything in the checkout vs master is considered new.  I consider this file to be a CI tool and so was only worried about it working correctly there.

**Comment by bashtage** [comment]
The reason why you are likely seeing many files is that your master is not up-to-date.  The new files check compares the branch to origin/master and anything that is not in origin/master is considered new. If origin/master is up-to-date, this does not happen.

**Comment by jbrockmendel** [comment]
> I consider this file to be a CI tool and so was only worried about it working correctly there.

That's fair.  On the flip side, it would be helpful to be able to run locally before pushing, just like with the unit tests.

**Comment by bashtage** [comment]
#5263 fixes this I think.

**Comment by bashtage** [comment]
I think it works right as long as origin/master is up-to-date with upstream/master

**Comment by jbrockmendel** [comment]
This now works; closing.
