### ISSUE TITLE
sirf_errband_mc / error message #svar

### ISSUE THREAD

**Issue by mk1564** [statsmodels/statsmodels#5280]
Hi,

I get error message when I try to find error band of my SVAR model. "shape mismatch: value array of shape (0,) could not be broadcast to indexing result of shape (0,4,4)" Can you guys help me out? 

> ValueError                                Traceback (most recent call last)
<ipython-input-208-fd4534490cf8> in <module>()
----> 1 result.sirf_errband_mc(orth=False, repl=1000, T=10,signif=0.05, seed=None, burn=100, cum=False)
~\Anaconda3\lib\site-packages\statsmodels\tsa\vector_ar\svar_model.py in sirf_errband_mc(self, orth, repl, T, signif, seed, burn, cum)
    721                 if i < 10:
    722                     sol = SVAR(sim, svar_type=s_type, A=A_pass,
--> 723                                B=B_pass).fit(maxlags=k_ar)
    724                     g_list.append(np.append(sol.A[A_mask].tolist(),
    725                                             sol.B[B_mask].tolist()))
~\Anaconda3\lib\site-packages\statsmodels\tsa\vector_ar\svar_model.py in fit(self, A_guess, B_guess, maxlags, method, ic, trend, verbose, s_method, solver, override, maxiter, maxfun)
    183         return self._estimate_svar(start_params, lags, trend=trend,
    184                                    solver=solver, override=override,
--> 185                                    maxiter=maxiter, maxfun=maxfun)
    186 
    187 
~\Anaconda3\lib\site-packages\statsmodels\tsa\vector_ar\svar_model.py in _estimate_svar(self, start_params, lags, maxiter, maxfun, trend, solver, override)
    253                                                     solver=solver,
    254                                                     maxiter=maxiter,
--> 255                                                     maxfun=maxfun)
    256         A_mask = self.A_mask
    257         B_mask = self.B_mask
~\Anaconda3\lib\site-packages\statsmodels\tsa\vector_ar\svar_model.py in _solve_AB(self, start_params, maxiter, maxfun, override, solver)
    357         A_len = len(A[A_mask])
    358 
--> 359         A[A_mask] = start_params[:A_len]
    360         B[B_mask] = start_params[A_len:]
    361 
ValueError: shape mismatch: value array of shape (0,) could not be broadcast to indexing result of shape (0,4,4)

**Comment by mk1564** [comment]
Here is my model.

> `A = np.asarray([[1, 0, 0,0],['E', 1, 0,0],['E', 'E', 1,0],['E', 'E', 'E',1]])`
`B = np.asarray([['E', 0, 0,0], [0, 'E',0, 0], [0, 0, 'E',0],[0,0,0,'E']])`
`model = SVAR(df[['r','gm','gp','gy']], svar_type='AB', A=A, B=B)`
`result = model.fit(maxlags=1,maxiter=500, maxfun=500)`
`result.sirf_errband_mc(orth=False, repl=1000, T=10,signif=0.05, seed=None, burn=100, cum=False)`

so A_mask is going to be

> `array([[False, False, False, False],
       [ True, False, False, False],
       [ True,  True, False, False],
       [ True,  True,  True, False]])`

**Comment by josef-pkt** [comment]
@mk1564 
I tried a simple example with your setting with random numbers, but for me it fails already earlier.
I'm using python 3.4 and have problems with bytes versus strings. my numpy is 1.11.2

```
(Pdb) A_pass
array([[b'1', b'0', b'0', b'0'],
       [b'E', b'1', b'0', b'0'],
       [b'E', b'E', b'1', b'0'],
       [b'E', b'E', b'E', b'1']], 
      dtype='|S1')
(Pdb) A_mask
array([[False, False, False, False],
       [ True, False, False, False],
       [ True,  True, False, False],
       [ True,  True,  True, False]], dtype=bool)
(Pdb) A_pass == 'E'
False
(Pdb) A_pass == b'E'
array([[False, False, False, False],
       [ True, False, False, False],
       [ True,  True, False, False],
       [ True,  True,  True, False]], dtype=bool)
```

What are your python, numpy and statsmodels version?

Given that there are no unit tests for sirf_errband_mc, it is likely that there are still some basic python 3 incompatibilities.

**Comment by josef-pkt** [comment]
A changes dtype

the A array created by the user code is U(nicode)

```
array([['1', '0', '0', '0'],
       ['E', '1', '0', '0'],
       ['E', 'E', '1', '0'],
       ['E', 'E', 'E', '1']], 
      dtype='<U11')
```

SVARResult.sirf_errband_mc recreates it as S1 bytes array

**Comment by josef-pkt** [comment]
irf plot seems to work also

```
>>> irf = result.irf()
>>> irf.plot()
<matplotlib.figure.Figure object at 0x00000000060BE828>
>>> irf.plot(stderr_type='mc')
<matplotlib.figure.Figure object at 0x000000000C8A3BE0>
```

But I have no idea whether the numbers are correct.

So quickfix seems to be to recreate A and B with the same dtype S or U in sirf_errband_mc.
The better fix would be to store the original user provided A and B and use it directly instead of recreating it.

(Based on quick bughunting in those lines that cause problems without trying to understand larger parts of SVAR. I haven't looked at it in quite some time, and never at IRF for SVAR.)

**Comment by josef-pkt** [comment]
AFAICS, there is not caching of the MonteCarlo results. repeated calls to irf.plot perform a new simulation each time.
Because there are options for irf and irf.plot, we cannot simply store the results, i.e. they would only be valid for the last set of options, until we memoize for given arguments.

**Comment by mk1564** [comment]
Thank you for your comment! So do you mean I need to create A like

`A1 = np.array([[1, 0, 0,0],['E', 1, 0,0],['E', 'E', 1,0],['E', 'E', 'E',1]],dtype='|S1')`?

**Comment by josef-pkt** [comment]
Because we will be dropping Python 2.7 within the next one or two years, it is better to stick with unicode

The change that I made locally is in sirf_errband_mc  in svar_model.py lines 677 and 678

```
@@ -672,12 +672,12 @@ class SVARResults(SVARProcess, VARResults):
...
-        A_pass = np.zeros(A.shape, dtype='|S1')
-        B_pass = np.zeros(B.shape, dtype='|S1')
+        A_pass = np.zeros(A.shape, dtype='<U11') #'|S1')
+        B_pass = np.zeros(B.shape, dtype='<U11') #'|S1')
```

**Comment by josef-pkt** [comment]
that's strange because there was no change in fit.

I opened #5285 to see how the fix works across python and numpy versions.
