### ISSUE TITLE
MAINT: Release 0.10

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#5290]

**Comment by josef-pkt** [comment]
backwards compatibility break in 0.9, need to mention in release notes for 0.10
GLM NegativeBinomial scale default has changed to 1, see #5277

**Comment by josef-pkt** [comment]
we only have 19 merged PRs with milestone:0.10 and ENH label
https://github.com/statsmodels/statsmodels/pulls?q=is%3Apr+milestone%3A0.10+is%3Amerged+label%3Atype-enh

23 merged PRs with BUG label
out of 225 merged PRs

96 out of the 225 merged PRs with milestone:0.10 have no labels !!!
https://github.com/statsmodels/statsmodels/pulls?page=4&q=is%3Apr+milestone%3A0.10+is%3Amerged+no%3Alabel

**Comment by ChadFulton** [comment]
> 96 out of the 225 merged PRs with milestone:0.10 have no labels !!!

Looks like a number of these are mine - I'll work on that :)

**Comment by bashtage** [comment]
Closing since 0.10.0rc2 is out.
