### ISSUE TITLE
special Latex characters are not escaped in some table cells with Summary.as.latex()

### ISSUE THREAD

**Issue by jmviz** [statsmodels/statsmodels#5297]
With statsmodels 0.9.0:

Modifying the example from #2862:

```python
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf

dat = sm.datasets.get_rdataset("Guerry", "HistData").data

# Rename 'Lottery' column to 'Lottery_'
dat.rename(columns = {'Lottery':'Lottery_'}, inplace = True)

results = smf.ols('Lottery_ ~ Crime_prop + np.log(Pop1831)', data=dat).fit()

print(results.summary().as_latex())
```

The printed Latex successfully escapes the underscore in `Crime_prop`:

`\textbf{Crime\_prop}     &       0.0029  &        0.001     &     3.887  &         0.000        &        0.001    &        0.004     \\`

 but does not escape the underscore in Lottery_:

`\textbf{Dep. Variable:}    &     Lottery_     & \textbf{  R-squared:         } &     0.351   \\`

I therefore can't produce a valid latex table when the dependent variable has an underscore.

**Comment by josef-pkt** [comment]
this got lost without labels.
AFAICS, there is no recent PR that fixed this.

bump for 0.10
