### ISSUE TITLE
statsmodels.tsa.statespace.sarimax.SARIMAXResults.predict

### ISSUE THREAD

**Issue by welcometodata** [statsmodels/statsmodels#5298]
Why does predict function always start with 0? Is it not a misleading result?

data = pd.Series(range(10))
model = sm.tsa.statespace.SARIMAX(data, order=(0,1,0))
predictions = model.fit(disp=False).predict()
print(predictions) 
            0    0.0
            1    0.0
            2    1.0
            3    2.0
            4    3.0
            5    4.0
            6    5.0
            7    6.0
            8    7.0
            9    8.0

**Comment by welcometodata** [comment]
Thanks for the clarification. But is there an index problem here? 
As you said, the first observation and prediction are both zero. However; the index of this prediction is 1, whereas the index of the first observation is zero. Should I shift the prediction values up?

**Comment by ChadFulton** [comment]
> As you said, the first observation and prediction are both zero. However; the index of this prediction is 1, whereas the index of the first observation (in case of df) is zero.

No, the index of the prediction of the first observation is zero, and the index of the first observation is also zero.

What I was describing is the data used *to make* the predictions. So e.g. the value of the prediction at index 1 is the prediction of the second observation, after having observed the first observation.

**Comment by welcometodata** [comment]
Thanks!
