### ISSUE TITLE
TSA differencing

### ISSUE THREAD

**Issue by clham** [statsmodels/statsmodels#5312]
In ARIMA and SARIMAX, when a difference is specified, a simple row-over-row difference is taken. For my topic area (finance), this was unexpected. I would have expected a log-diff. An example use-case would be to put in a vector of stock prices, and get a pct change back out. Just difference the series isn't sufficient (a first difference still isn't stationary-ish).

Would anyone be amenable to accepting a PR with either 1) a kwarg to take the log-diff rather than a simple diff or 2) just a note in the documentation?

**Comment by ChadFulton** [comment]
Thanks for the suggestion!

There has been some work in a number of areas to allow for specifying a Box-Cox transformation - we don't have this built-in yet, but I think that this might be the most natural way to introduce the possibility of a log transformation.

As an aside, all of the packages that I'm aware of do simple differencing - is there one that you use that performs log-diff by default?

**Comment by clham** [comment]
I don’t know of one, I just spent a bunch of time figuring out why I wasn’t getting what I was expecting. What also threw me was there was an arg for “simple differencing” (it is aptly naked however!). Is there a “lower skill” way I can help here?

**Comment by clham** [comment]
Makes sense.  Thanks!

**Comment by clham** [comment]
Makes sense.  Thanks!

**Comment by josef-pkt** [comment]
The originial option 2) is always possible.
Improving docstrings if there are things that are unclear in the documentation, or improving or adding notebook examples would always be helpful.

Eg. I don't know how much we have about backtransforming in terms of supporting code and documentation. E.g. backtransforming the log prediction/forecast will not get the mean or expected value, assuming a correctly specified distribution, it would be a lognormal model in terms of original endog.
