### ISSUE TITLE
Passing distargs to ProbPlot doesn't work.

### ISSUE THREAD

**Issue by groceryheist** [statsmodels/statsmodels#5323]
from scipy import stats
    import statsmodels.api as sm
    params = (10,0,2)
    data = stats.lognorm.rvs(100,*params)
    pp = sm.ProbPlot(data,"lognorm",fit=False,distargs=params)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1659-70fdc874452a> in <module>()
      3 params = (10,0,2)
      4 data = stats.lognorm.rvs(100,*params)
----> 5 pp = sm.ProbPlot(data,"lognorm",fit=False,distargs=params)

~/venv/lib/python3.5/site-packages/statsmodels/graphics/gofplots.py in __init__(self, data, dist, fit, distargs, a, loc, scale)
    145                 self.dist = dist(loc=0, scale=1)
    146         elif distargs or loc == 0 or scale == 1:
--> 147             self.dist = dist(*distargs, **dict(loc=loc, scale=scale))
    148             self.loc = loc
    149             self.scale = scale

/usr/lib/python3/dist-packages/scipy/stats/_distn_infrastructure.py in __call__(self, *args, **kwds)
    766 
    767     def __call__(self, *args, **kwds):
--> 768         return self.freeze(*args, **kwds)
    769     __call__.__doc__ = freeze.__doc__
    770 

/usr/lib/python3/dist-packages/scipy/stats/_distn_infrastructure.py in freeze(self, *args, **kwds)
    763 
    764         """
--> 765         return rv_frozen(self, *args, **kwds)
    766 
    767     def __call__(self, *args, **kwds):

/usr/lib/python3/dist-packages/scipy/stats/_distn_infrastructure.py in __init__(self, dist, *args, **kwds)
    431 
    432         # a, b may be set in _argcheck, depending on *args, **kwds. Ouch.
--> 433         shapes, _, _ = self.dist._parse_args(*args, **kwds)
    434         self.dist._argcheck(*shapes)
    435         self.a, self.b = self.dist.a, self.dist.b

TypeError: _parse_args() got multiple values for argument 'loc'

_Originally posted by @groceryheist in https://github.com/statsmodels/statsmodels/issues/3254#issuecomment-429678252_

**Comment by bashtage** [comment]
This is fixed in master, in the sense that it produces a helpful error message and explains what is wrong.

**Comment by bashtage** [comment]
The code at the top raises:

```
TypeError: Initializing the distribution failed.  This can occur if distargs contains loc or scale. The distribution initialization command is:
dist(10, 0, 2, loc=0, scale=1)
```

The correct call is 
```
pp = sm.ProbPlot(data,"lognorm",fit=False,distargs=params[:1],loc=0,scale=2)
```
