### ISSUE TITLE
Compare variances among two distributions

### ISSUE THREAD

**Issue by TheChymera** [statsmodels/statsmodels#5337]
I have two 1D arrays, and I observe that one of them has a higher spread than the other. I would like to describe this effect both in terms of magnitude, and giving it a significance value, so that anybody looking to reproduce this has a significance estimate.

I am unsure:

* Whether it is possible/“correct” at all to assign significance in a descriptive effort (this is not an a priori hypothesis)
* Whether a ratio of Standard Deviations is appropriate (and whether a significance can somehow be determined from it).

I seem t have come across the [`HetGoldfeldQuandt`](http://nipy.bic.berkeley.edu/nightly/statsmodels/doc/html/generated/statsmodels.stats.diagnostic.HetGoldfeldQuandt.html#statsmodels.stats.diagnostic.HetGoldfeldQuandt) class from statsmodels, but I was unable to figure out how to use it:

```
a = het_goldfeldquandt.run(
        y=myarray1,
        x=myarray2,
        )
```

gives me

```
TypeError: run() got multiple values for argument 'y'
```

Many other call attempts are also giving me errors regarding argument numbers. Do you have any examples for using this class and its associated function?

**Comment by josef-pkt** [comment]
use the scipy.stats functions, bartlett and levine
het_goldfeldquant is a hypothesis/specification test for regression models, i.e. AFAIR it's equivalent to the bartlett test when we split the observations in OLS into two subsamples.

bartlett is very sensitive to deviation from normality (in contrast to the t_test), and levene is better in that case.

I started to also add variance hypothesis tests that are robust to deviation from normality and to outliers to statsmodels, but AFAIR they are not merged.

**Comment by josef-pkt** [comment]
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mood.html has the list of functions in the See Also
I don't remember about the others like ansari or mood.
fligner is the one-way anova analogue for variances (k sample comparison)

**Comment by TheChymera** [comment]
@josef-pkt thank you :)

Is there, however any other way to characterize this effect other than a p-value? I am simply trying to describe how certain one could be to see this effect again on other data. The effect is not part of my a priori hypothesis, but otherwise very strong (with the aforementioned tests p-values from 0.0017 to 4.98e-09).

**Comment by TheChymera** [comment]
Thank you :)
