### ISSUE TITLE
controlling number of cores

### ISSUE THREAD

**Issue by rontomer** [statsmodels/statsmodels#5344]
Hello

I am trying to control the number of cores used in statsmodel GLM with no luck
Already tried the suggestion in https://github.com/statsmodels/statsmodels/issues/3542  and in https://github.com/statsmodels/statsmodels/issues/2914 
None of them worked.
I am working on Ubuntu 14.04
Any other suggestions?

Thanks
Tomer

**Comment by josef-pkt** [comment]
Which BLAS/LAPACK library are you using?

It might be better to ask on stackoverflow, unless there is somebody reading here that knows more about these problems.

**Comment by rontomer** [comment]
@josef-pkt 
is that what you mean?
```
openblas_info:
	define_macros = [('HAVE_CBLAS', None)]
	libraries = ['openblas', 'openblas']
	language = c
	library_dirs = ['/usr/local/lib']
blas_mkl_info:
	NOT AVAILABLE
openblas_lapack_info:
	define_macros = [('HAVE_CBLAS', None)]
	libraries = ['openblas', 'openblas']
	language = c
	library_dirs = ['/usr/local/lib']
lapack_mkl_info:
	NOT AVAILABLE
blas_opt_info:
	define_macros = [('HAVE_CBLAS', None)]
	libraries = ['openblas', 'openblas']
	language = c
	library_dirs = ['/usr/local/lib']
blis_info:
	NOT AVAILABLE
lapack_opt_info:
	define_macros = [('HAVE_CBLAS', None)]
	libraries = ['openblas', 'openblas']
	language = c
	library_dirs = ['/usr/local/lib']
```

**Comment by josef-pkt** [comment]
Did you resolve this?

A related link
https://stackoverflow.com/questions/51256738/multiple-instances-of-python-running-simultaneously-limited-to-35/51257384#51257384

The answer mentions "however, OpenBLAS ignores OPENBLAS_NUM_THREADS and GOTO_NUM_THREADS when compiled with USE_OPENMP=1"

So, it might be more tricky than just `export OPENBLAS_NUM_THREADS=1`

**Comment by bashtage** [comment]
You can use 

https://github.com/joblib/threadpoolctl

to robustly control the number of threads, even locally to a set of calls.

**Comment by bashtage** [comment]
Closing as answered.  Please reopen if this is an issue.

**Comment by GF-Huang** [comment]
How about if I using `adfuller` with `ipyparallel`? `ipyparallel` use multiple `ipython` instance, do I need to set limitation on each `ipython` instance?
