### ISSUE TITLE
TST: Random failure with Test_MVN_MVT_prob.test_mvn_mvt_3

### ISSUE THREAD

**Issue by thequackdaddy** [statsmodels/statsmodels#5354]
Example here:

https://travis-ci.org/statsmodels/statsmodels/jobs/447560388

weird thing is, it looks like it passes, but it fails:

```
>       assert_almost_equal(probmvt_R, probmvt, 4)
E       AssertionError: 
E       Arrays are not almost equal to 4 decimals
E        ACTUAL: 0.9522146
E        DESIRED: 0.95226795752678328
```

Seems like its equal to 4 decimals, no? 

Should we just loosen tolerance or change to `assert_allclose`? 

ref #5197 which mentions same failure

**Comment by josef-pkt** [comment]
> Should we just loosen tolerance or change to assert_allclose?

both
using assert_allclose the atol can be increase by half a decimal.
