### ISSUE TITLE
Import in Python 2.7.15 fails with undefined symbol: PyUnicodeUCS4_DecodeUTF8

### ISSUE THREAD

**Issue by rakshesh26** [statsmodels/statsmodels#5371]
I am trying to use ExponentialSmoothing from statsmodels in my implementation. It works fine with Anaconda, but when I import it in my VM, which has Python 2.7.15 running on RHEL 7, it fails with below error:
(<type 'exceptions.ImportError'>, ImportError('/home/custom/enet/lib/python2.7/site-packages/statsmodels/tsa/kalmanf/kalman_loglike.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8',))

statsmodels needs scipy and numpy. I tried re-compiling Python with UCS4 support, but then, when I compile statsmodels, it gives an error saying numpy needs UCS2!! So it reaches a deadlock.
I have installed all relevant packages needed for statsmodels.

**Comment by bashtage** [comment]
Closing since no follow-up.  Please reopen if this continues.
