### ISSUE TITLE
Holtwinters multiplicative trend error

### ISSUE THREAD

**Issue by welcometodata** [statsmodels/statsmodels#5376]
Hello,

I am trying to fit an Exponential Smoothing model to my time series data. However, when I state trend='mul', I am getting an error pointing to _exponential_smoothers.pyx. Is it due to me or is there a problem in the module?

Moreover, I realize that there are reports on _exponential_smoothers.pyx like:
" ENH: Fix starting bug in mul trend
Ensure multiplicative trend is always positive
.......
Fix buggy test due to inapporpriate starting values for multiplicative trend"

Could you please explain it? Does it stem from starting values of some optimization algorithms?

Finally, does the default values of HoltWinters fit 'Simple Exponential Smoothing" to the given data?

**Comment by bashtage** [comment]
What is the precise error you are seeing?

**Comment by welcometodata** [comment]
Truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all(),

which points to 
"if (self.trend == 'mul' or self.seasonal == 'mul') and np.any(endog <= 0.0): "

**Comment by bashtage** [comment]
What is the precise command you are running?

**Comment by welcometodata** [comment]
For instance:
model = ExponentialSmoothing(data, trend="mul").fit()
predictions = model.predict(start=0, end=143)

**Comment by bashtage** [comment]
What is data, in particular, type and shape?  Ideally, you would post a self-contained, runnable example that will reproduce the error. 

I can't reproduce using Series or DataFrame as data.

**Comment by welcometodata** [comment]
You're right, sorry for missing arguments. 
As a basic example, I tried it with "International airline passengers data sets", which you can also find on [https://datamarket.com/data/set/22u3/international-airline-passengers-monthly-totals-in-thousands-jan-49-dec-60#!ds=22u3&display=line](url)

**Related code**
import pandas as pd
from statsmodels.tsa.api import ExponentialSmoothing
data = pd.read_csv('./international-airline-passengers.csv')
model = ExponentialSmoothing(data, seasonal="mul", seasonal_periods=12).fit()
predictions = model.predict(start=0, end=143)

**Errors**
File "....", line 10, in <module>
    model = ExponentialSmoothing(data, seasonal="mul", seasonal_periods=12).fit()

  File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\holtwinters.py", line 391, in __init__
    if (self.trend == 'mul' or self.seasonal == 'mul') and (endog <= 0.0).any():

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 1573, in __nonzero__
    .format(self.__class__.__name__))

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by welcometodata** [comment]
> Your data is bad. The example you posted doesn't even produce this error. Instead it raises:
> 
> `ValueError: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).`
> 
> This works as expected (against SM master)
> 
> ```python
> import pandas as pd
> from statsmodels.tsa.api import ExponentialSmoothing
> data = pd.read_csv('./international-airline-passengers.csv')
> # Needed since data has NaNs and 2 columns
> data = data.set_index('Month').dropna()
> model = ExponentialSmoothing(data, seasonal="mul", seasonal_periods=12).fit()
> predictions = model.predict(start=0, end=143)
> ```

Could you please try it with the data? You do not need to drop any column, actually.
[international-airline-passengers.zip](https://github.com/statsmodels/statsmodels/files/2569985/international-airline-passengers.zip)

**Comment by bashtage** [comment]
I ran it with the data from the page you linked to.

Works fine with that data too, with one small change:
```
import pandas as pd
from statsmodels.tsa.api import ExponentialSmoothing
data = pd.read_csv('./international-airline-passengers.csv')
# Needed since data has NaNs and 2 columns
data = data.astype('double')  # Do not use int64
model = ExponentialSmoothing(data, seasonal="mul", seasonal_periods=12).fit()
predictions = model.predict(start=0, end=143)

In [10]: predictions
Out[10]:
1949-01-01    118.800133
1949-02-01    122.083716
1949-03-01    131.931875
1949-04-01    125.643918
1949-05-01    116.695539
1949-06-01    130.449039
```

**Comment by welcometodata** [comment]
Hello,

Thanks a lot for your replies. As you mentioned before, the problem was stemming from version. I upgraded it to master and it works now.

**Comment by arobertsonithree** [comment]
Hi I'm having exact same problem. I have version 0.9. If I understand above correctly I need 'master' to make this work. But I can't work out where to get master from. I'm using anaconda and pycharm.
