### ISSUE TITLE
BUG: wald_test_terms pvalues are object dtype

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#5393]
I'm in the middle of a wald_test_terms unit test and `assert_allclose` raises an exception because pvalues is an object array.

I have no idea why I get this column with dtype `object`. My numpy and pandas are
```
(Pdb) numpy.__version__
'1.11.2'
(Pdb) pandas.__version__
'0.19.1'
```

```
(Pdb) wtt.pvalues
array([array(2.4177954286934585e-05), array(0.8749260421663413),
       array(0.013354203928405244), array(0.1622975309255346)], dtype=object)

(Pdb) wtt.table['pvalue']
fuel      2.4177954286934585e-05
drive         0.8749260421663413
weight      0.013354203928405244
hp            0.1622975309255346
Name: pvalue, dtype: object

(Pdb) wtt.table['pvalue'].values
array([array(2.4177954286934585e-05), array(0.8749260421663413),
       array(0.013354203928405244), array(0.1622975309255346)], dtype=object)

(Pdb) type(wtt.table)
<class 'pandas.core.frame.DataFrame'>

(Pdb) np.asarray(wtt.table['pvalue'])
array([array(2.4177954286934585e-05), array(0.8749260421663413),
       array(0.013354203928405244), array(0.1622975309255346)], dtype=object)

(Pdb) wtt.table.dtypes
statistic        float64
pvalue            object
df_constraint      int64
dtype: object
```

**Comment by josef-pkt** [comment]
It looks like in model.LikelihoodModelResults.wald_test_terms, the pvalue is a 1 element array instead of a scalar. Adding a `.item()` to pvalue solves this.

`row = [wt.statistic.item(), wt.pvalue.item(), constraint.shape[0]]`

The unit tests for wald_test_terms don't catch this because it uses a loop instead of comparing the array of all hypothesis tests.
` statsmodels.base.tests.test_generic_methods`  function `compare_waldres`

In the unit test that I am writing for GAM, I test a slice of pvalues.

Somewhere we need to squeeze before getting to pandas

```
>>> stats.chi2.sf(5,5)
0.41588018699550794
>>> stats.chi2.sf([5], 5)
array([ 0.41588019])
>>> stats.chi2.sf(5,[5])
array([ 0.41588019])
```

**Comment by jbrockmendel** [comment]
> The minimal fix is now in my GAM PR

@josef-pkt did this fix get merged?  if so, is it specifically tested?

**Comment by jbrockmendel** [comment]
If not, can you provide more information to a MCVE https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by josef-pkt** [comment]
the fix is in master
I don't think there is anything to do until we run into similar problems again, i.e. when we need to check the shape of returns from hypothesis tests.

closing
