### ISSUE TITLE
Roadmap release 0.11

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#5406]
(starting a new roadmap, main tracker for changes in a release are in milestone)
(previous content moved to #6187 )

**Comment by bashtage** [comment]
SM really needs a release.  What is the **minimum** set of things that **must** be done before a release could be cut (even if it is imperfect)?

**Comment by stonebig** [comment]
Being compatible with coming scipy-1.3.0 (removal of deprecated links  in script.misc), would be another minimum. It's in trunk already

**Comment by bashtage** [comment]
Master is already compatible with scipy-1.3.0.  It is tested and passes against 1.4.0 which is the development branch, see https://api.travis-ci.org/v3/job/528368812/log.txt for the loc (search for scipy).

**Comment by josef-pkt** [comment]
I finally got the latest visual studio tools and compilation worked out of the box
using WinPython WPy64-3740

I get one failure in a notebook with rpy2 and many warnings and a lot of xfailed

`= 1 failed, 8829 passed, 159 skipped, 142 xfailed, 4 xpassed, 246 warnings in 13
54.45 seconds =`

**Comment by bashtage** [comment]
Closing since this doesn't appear to be relevant, and there are both milestone and projects for 0.11
