### ISSUE TITLE
Using Sarimax models with trend on new data

### ISSUE THREAD

**Issue by mickash** [statsmodels/statsmodels#5412]
From good search it looks like you field help requests here. If not, my apologies. 

We are implementing Sarimax models as part of an industrial analytics project, where the processes behind the time series can be turned on and off. Individual sequences we call runs. We want to be able to generate a model from a run and then use this model to predict (near-) future values for new runs (we allow a period where no predictions are sought to generate an initial time series sequence for predictions). Although we do multi-step ahead forecasting, it is only through MCMC over a number of models. So we only need single step-ahead forecasting from the statsmodels Sarimax models.

Our code for generating the original model from training data is equivalent to:

```
def fit_model (Y,X,order,seasonal_order,trend):
      model = sm.tsa.statespace.SARIMAX(
                Y,
                X,
                order=order,
                seasonal_order=seasonal_order,
                trend=trend,
                enforce_stationarity=True,
                enforce_invertibility=True
                )        
      result = model.fit()
      return model,result
```

And our code for generating predictions given current data is equivalent to:

```
def predict_next (original_model,original_results,new_Y,new_X,current_X):
      predict_model = sm.tsa.statespace.SARIMAX(
                new_Y,
                new_X,
                order=original_model.order,
                order=original_model.seasonal_order,
                trend=original_model.trend,
                enforce_stationarity=True,
                enforce_invertibility=True
                )        
      predict_results = predict_model.filter(original_results.params)  
      forecast=predict_results.get_forecast(1,exog=current_X)   
      return forecast.predicted_mean[0]
```

Testing indicates that this does not work as desired unless the new data is identical to the original data. Even using the last n (say 100) rows of the original data does not work (in particular, trend is lost). We can provide data outputs if desired.

We assume that the issue involves the state of the underlying state-space model. But we have not been able to find what to do in the documentation. Any help much appreciated!

/ Mike

**Comment by ChadFulton** [comment]
Hi Mike,

At first glance, it looks like your code is already doing the right thing, but it's tough to diagnose what's going on without a few more details. At least it would be useful to know what your specifications are, but if you can post a replicable example with the results you're getting and a description of how they aren't what you expect, that would be even better.

**Comment by mickash** [comment]
Hi Chad,

Thanks for answering. I've recreated the 'problem' and the code is included below. It is quite a bit as this occurs in a MCMC simulation of a system, so I recreated that machinery. The Sarimax models only need to do one-step ahead forecasting.

As I said in the original post, basically the forecast trend flattens unexpectedly. It is not when using other data (as I suggested previously), but rather it seems to occur when the data set passed to the second model (the one created for predicting on new data) is small. We didn't expect to see this sort of behavior, and assumed we were doing something wrong. It would be nice if you could at least tell us that this is not an issue with the library, and even better if you could tell us we are missing something that will fix it!

For example, here are the forecast trends for the (3-variable) system generated by the example code with random seed. The first three are predicting trend for new data with 800 rows:

![image](https://user-images.githubusercontent.com/44157556/49747013-c54f2500-fca2-11e8-85e1-75b93d048d08.png)

![image](https://user-images.githubusercontent.com/44157556/49747091-eb74c500-fca2-11e8-9511-d5558e7c74f6.png)

![image](https://user-images.githubusercontent.com/44157556/49747108-f29bd300-fca2-11e8-8830-ce80a5765107.png)

The next three forecasting trends for new data with 100 rows. You can see the trend is much flatter:

![image](https://user-images.githubusercontent.com/44157556/49747131-fe879500-fca2-11e8-9f06-b8f707272f9a.png)

![image](https://user-images.githubusercontent.com/44157556/49747137-047d7600-fca3-11e8-9d77-3723d5531db8.png)

![image](https://user-images.githubusercontent.com/44157556/49747144-09422a00-fca3-11e8-82c4-77052b378d95.png)

Finally forecasting trends for new data with 10 rows. Even flatter...

![image](https://user-images.githubusercontent.com/44157556/49747182-1d862700-fca3-11e8-94a4-5bd823ddcc82.png)

![image](https://user-images.githubusercontent.com/44157556/49747215-34c51480-fca3-11e8-974e-02d36f68712b.png)

![image](https://user-images.githubusercontent.com/44157556/49747235-41496d00-fca3-11e8-8959-9e1708109f5b.png)

Admittedly, these are within confidence intervals, but as this repeatedly occurs it seems the models have a real bias towards flat trends when forecasting on smaller data.

All the best,

Mike

```
import numpy as np
import scipy.stats
import matplotlib.pyplot as plt
import statsmodels.api as sm

def get_test_data(n=1000,bias0=0,trend=2,trend_coefficient=.01,seed=0,mc_runs=5):
    if not seed is None:
        np.random.seed(seed)
    rnd=np.random.normal(bias0,1,n+10)
    rnd2=np.random.random(n+10)
    rnd3=np.random.random(n+10)
    x1=np.array([pow(i*trend_coefficient,trend) + np.mean(rnd[i:(i+3)]) for i in range(n)]).reshape(n,1)
    x2=np.array([rnd2[i]+x1[i-1] for i in range(1,n+1)]).reshape(n,1)
    x3=np.array([np.mean(rnd3[i:(i+3)]) for i in range(n)]).reshape(n,1)
    for i in range(1,n):
        x3[i]=x3[i]+.1*x3[i-1]-.25*x2[i-1]
    out=np.concatenate((x1,x2,x3),axis=1)
    return out

def get_data(s1=0,s2=1,trend_coef=.01):
    df1=get_test_data(seed=s1,trend_coefficient=trend_coef)
    df2=get_test_data(seed=s2,trend_coefficient=trend_coef)
    return df1,df2

# Just wrapping the Sarimax constructor
def make_model(df,index,exog_indices,order) :
    # Exogenous variables are one time slice prior.        
    return sm.tsa.statespace.SARIMAX(
                df[1:,index],
                df[:-1,exog_indices],
                order=order,
                seasonal_order=(0,0,0,0),
                trend='ct',
                enforce_stationarity=True,
                enforce_invertibility=True
                )

    
class analysis_results:
    def __init__(self,samples,df,start_from,forecast):
        self.samples=samples
        self.df=df
        self.start_from=start_from
        self.forecast=forecast        

    def _analyze_samples(self,index):
        mu=[np.mean(self.samples[:,i,index]) for i in range(self.forecast)]
        sigma=[np.std(self.samples[:,i,index]) for i in range(self.forecast)]
        lower_ci=scipy.stats.norm(mu,sigma).ppf(.025)
        upper_ci=scipy.stats.norm(mu,sigma).ppf(.975)
        return mu,sigma,lower_ci,upper_ci
        
    def plot(self,index):
        mu,sigma,lower_ci,upper_ci=self._analyze_samples(index)
        
        back=min(self.start_from,self.forecast)        
        plt_data=np.zeros((back+self.forecast,4))
        plt_data[:back,0]=self.df[self.start_from-back:self.start_from,index] # Lower CI
        plt_data[back:,0]=lower_ci
        plt_data[:back,1]=self.df[self.start_from-back:self.start_from,index] # Mean
        plt_data[back:,1]=mu
        plt_data[:back,2]=self.df[self.start_from-back:self.start_from,index] # Upper CI
        plt_data[back:,2]=upper_ci
        plt_data[:,3]=self.df[self.start_from-back:self.start_from+self.forecast,index] # Actual

        plt.plot(plt_data)
        
class manual_system:
    def __init__ (self,df,exog0,exog1,exog2,ord0,ord1,ord2):
        # It is assumed that df has 1000 rows
        # Generate original model using first 800 rows of data
        self.m0 = make_model(df[:800,],0,exog0,ord0)
        self.m1 = make_model(df[:800,],1,exog1,ord1)
        self.m2 = make_model(df[:800,],2,exog2,ord2)
        self.r0=self.m0.fit()
        self.r1=self.m1.fit()
        self.r2=self.m2.fit()
        
        # Get the std deviation of residuals on the remaining 200 rows of data
        # Exogenous variables are one time slice back
        f0=self.r0.get_forecast(200,exog=df[799:999,exog0]).predicted_mean
        f1=self.r1.get_forecast(200,exog=df[799:999,exog1]).predicted_mean
        f2=self.r2.get_forecast(200,exog=df[799:999,exog2]).predicted_mean
        self.sd0=np.std(f0-df[800:,0])
        self.sd1=np.std(f1-df[800:,1])
        self.sd2=np.std(f2-df[800:,2])

        # Store information
        self.exog0=exog0
        self.exog1=exog1
        self.exog2=exog2
        self.ord0=ord0
        self.ord1=ord1
        self.ord2=ord2
    
    def get_mc_samples(self,forecast,df,start_from,mc_runs):
        samples=np.zeros((mc_runs,forecast,3))
        # Generate monte carlo runs
        simulated_data=np.zeros((start_from+forecast,3))
        simulated_data[:start_from,:]=df[:start_from,:]
        for mc_run in range(mc_runs):
            simulated_data[start_from:,:]=0
            for i in range(forecast):
                tm0 = make_model(simulated_data[:start_from+i,:],0,self.exog0,self.ord0)
                tm1 = make_model(simulated_data[:start_from+i,:],1,self.exog1,self.ord1)
                tm2 = make_model(simulated_data[:start_from+i,:],2,self.exog2,self.ord2)
                tr0=tm0.filter(self.r0.params)
                tr1=tm1.filter(self.r1.params)
                tr2=tm2.filter(self.r2.params)
                mu0=tr0.get_forecast(1,exog=simulated_data[start_from+i-1,self.exog0].reshape((1,len(self.exog0)))).predicted_mean
                mu1=tr1.get_forecast(1,exog=simulated_data[start_from+i-1,self.exog1].reshape((1,len(self.exog1)))).predicted_mean
                mu2=tr2.get_forecast(1,exog=simulated_data[start_from+i-1,self.exog2].reshape((1,len(self.exog2)))).predicted_mean
                val0=np.random.normal(mu0,self.sd0)
                val1=np.random.normal(mu1,self.sd1)
                val2=np.random.normal(mu2,self.sd2)
                next_row=[val0,val1,val2]
                simulated_data[start_from+i,:]=next_row
            samples[mc_run,:,:]=simulated_data[start_from:,:]
        return samples

    def analyze(self,df,predict_from,hist_start,mc_runs,forecast):
        samples=self.get_mc_samples(forecast,df[hist_start:,:],predict_from-hist_start,mc_runs)
        return analysis_results(samples,df[hist_start:,:],predict_from-hist_start,forecast)
 
def run_example (seed1=0,seed2=1,trend_coef=.01,mc_runs=10):
    # We get some synthetic data
    df1,df2=get_data(seed1,seed2,trend_coef)

    # Hard code exogenous variables and orders of models to use:
    exog0=[1,2]
    exog1=[0]
    exog2=[0]
    ord0=(0,1,1)
    ord1=(2,0,2)
    ord2=(0,0,2)

    # Create the system of three sarimax models.
    sys=manual_system(df1,exog0,exog1,exog2,ord0,ord1,ord2)
    
    #return sys,df2

    # Here we predict the next 20 cases in the second data set, starting at case 800,
    # with rows 0:800 included when we construct the Sarimax model
    results1=sys.analyze(df2,800,hist_start=0,mc_runs=mc_runs,forecast=20)
    
    # If we look at the trend analysis, everything looks good :)
    plt.figure(0)
    results1.plot(0)    
    plt.figure(1)
    results1.plot(1)    
    plt.figure(2)
    results1.plot(2)    
    
    # Here we predict the next 20 cases in the second data set, starting at case 800,
    # with only rows 700:800 included when we construct the Sarimax model
    results2=sys.analyze(df2,800,hist_start=700,mc_runs=mc_runs,forecast=20)

    # Now we are in trouble: The trend is much weaker in our simulations
    plt.figure(3)
    results2.plot(0)    
    plt.figure(4)
    results2.plot(1)    
    plt.figure(5)
    results2.plot(2)    
        
    # Finally we predict the next 20 cases in the second data set, starting at case 800,
    # with only rows 790:800 included when we construct the Sarimax model
    results3=sys.analyze(df2,800,hist_start=790,mc_runs=mc_runs,forecast=20)

    # Now we are in trouble: The trend gone entirely
    plt.figure(6)
    results3.plot(0)    
    plt.figure(7)
    results3.plot(1)    
    plt.figure(8)
    results1.plot(2)    
```

**Comment by mickash** [comment]
I should perhaps make clear that the 3 sets of graphs are forecasts for the same data, with models that contain the same parameters. The only difference is the amount of prior data based to the model that we filter the trained parameters on in order to get the result object used for predictions. 

I understand that this prior data matters insofar as it will play a role in the errors used for moving average terms. If I understand the underlying state-space implementation right this will show up in that the Markov chain (Kalam filter) will need time to 'forget' its initial state (and to estimate latent variables associated with each time point?). But these are big differences, and appear to be affecting the slope of the trend, which I am surprised to see (but that may just be poor intuition about what is happening).

**Comment by ChadFulton** [comment]
Unfortunately, this example is too complex for me to easily see what's going on. Can you give an example with a fixed dataset and just one model? Ideally along the lines of the following:

```python
# Construct the dataset
y = ...
x1 = ...
x2 = ...
x3 = ...
x = np.c_[x1, x2, x3]

endog = y[:end_estimate]
exog = x[:end_estimate]

# Fit the model
mod = sm.tsa.SARIMAX(endog, exog=exog, order=(0, 0, 2), trend='ct')
res = mod.fit()

# Perform forecasting exercise
simulated_data = ...
mc_runs = ...
forecast = ..

for mc_run in range(mc_runs):
    for j in range(forecast):
        ...

# Produce plots
...
```

**Comment by mickash** [comment]
Yes - it was a lot. Apologies. I think I have the issue well defined now. So the steps of the general for working with different data is:

1. Construct an original model from training data.
2. Use this original model to fit a result object to obtain parameters.
3. Construct a new model from new data, using order & other hyper-parameters from the original model.
4. Generate a new result object from the new model using filter.
5. Use the new result object to make predictions & forecasts etc

What is happening is that the data used in step (3) influences the output of forecasts in step (5). This is unfortunate but presumably because this data is being used to estimate moving average values.

But analysis shows that not only are they different, but where both the original and new data is generated by the same process, the expected values of using different amounts of data (different lead in sizes to the final data case) in step three leads to differences in the *expected* values of the forecast in step 5. You can run your own t tests on the output of the second function in the code below.

Essentially, the amount of data given to the new model in step 3 biases the forecast estimate! 
- Is this behavior expected, or does it indicate a bug in statsmodels? 
If it is expected:
- What is causing it? 
- Can the bias be avoided (e.g. can we examine statistics of parameters somewhere to know when sufficient data is used)?
- Can the bias be quantified and adjusted for? 
 
```
import numpy as np
import statsmodels.api as sm
def run_example (seed1,seed2,trend_order=2,trend_coef=.01,mc_runs=10,pred_from=800):
    # We get some synthetic data
    def make_df(seed=None,n=1000):
        if not seed is None:
            np.random.seed(seed)
        rnd=np.random.normal(0,1,n+10)
        return np.array([pow(i*trend_coef,trend_order) + np.mean(rnd[i:(i+3)]) for i in range(n)]).reshape(n,1)        
    df1=make_df(seed1)
    df2=make_df(seed2)

    # Make the original model & results objects from df1
    mod_original=sm.tsa.statespace.SARIMAX(df1[:,0],None,(0,1,1),seasonal_order=(0,0,0,0),trend='ct',enforce_stationarity=True,enforce_invertibility=True)
    res_original=mod_original.fit()

    # Make a new model from elements 0:800 of df2, and filter params from original results objects to create new results object 1.
    mod_new1=sm.tsa.statespace.SARIMAX(df2[:800,0],None,(0,1,1),seasonal_order=(0,0,0,0),trend='ct',enforce_stationarity=True,enforce_invertibility=True)
    res_new1=mod_new1.filter(res_original.params)

    # Make a new model from elements 700:800 of df2, and filter params from original results objects to create new results object 2.
    mod_new2=sm.tsa.statespace.SARIMAX(df2[700:800,0],None,(0,1,1),seasonal_order=(0,0,0,0),trend='ct',enforce_stationarity=True,enforce_invertibility=True)
    res_new2=mod_new2.filter(res_original.params)

    # Generate and return one step ahead forecasts from new results objects 1 & 2.
    f1=res_new1.get_forecast(1).predicted_mean[0]
    f2=res_new2.get_forecast(1).predicted_mean[0]
    
    return [f1,f2]

def run_n_examples(n=200):
    res=np.array([run_example(seed1=None,seed2=None) for i in range(n)])
    return res

```

**Comment by josef-pkt** [comment]
General question about a potential problem in transferring trend across datasets.
I don't know whether this can explain the behavior here, and how exactly this is implemented.

trend is based on an internal index and forecasting continues from the last trend index. The constant is for the case when the trend index is zero.
How does the forecasting method figure out which trend to use with a new dataset?
If trend were in exog, then it would be the responsibility of the user to define the appropriate exog/trend for the new forecasting period.

**Comment by ChadFulton** [comment]
Thanks for posting the simpler example!

- For this example, @josef-pkt is correct - the main problem is that trend counts from t=0 in each of the models, whereas I think you are expecting it to start from t=700 in the third model.

- However, I think this isn't best thought of as a "trend" problem, in the sense that your trend still gives the correct slope, regardless of where it counts from. Instead, you can think of this as an "intercept" problem, in the sense that you need to correctly specify the t=0 behavior.

- In your example, you can replace the last model with the following:

```python
mod_new2=sm.tsa.statespace.SARIMAX(df2[700:800,0],None,order,seasonal_order=(0,0,0,0),trend='ct',enforce_stationarity=True,enforce_invertibility=True)
params = res_original.params.copy()
params[0] += params[1] * 700  # fix the intercept
res_new2=mod_new2.filter(params)
```

- One other note here is that you are estimating a constant in an integrated I(1) model - in such a model, a constant term is not identified. So I would recommend the following:

```python
# Make the original model & results objects from df1
mod_original = sm.tsa.statespace.SARIMAX(df1[:,0], order=(0, 1, 1), trend='t')
res_original = mod_original.fit()

# Make a new model from elements 0:800 of df2, and filter params from original results objects to create new results object 1.
mod_new1 = sm.tsa.statespace.SARIMAX(df2[:800,0], order=(0, 1, 1), trend='t')
res_new1 = mod_new1.filter(res_original.params)

# Make a new model from elements 700:800 of df2, and filter params from original results objects to create new results object 2.
mod_new2=sm.tsa.statespace.SARIMAX(df2[700:800,0], order=(0, 1, 1), trend='ct')
params = np.r_[0, res_original.params.copy()]
params[0] = params[1] * 700
res_new2 = mod_new2.filter(params)
```

Note that since you are *specifying* the constant in the third model, and not estimating it, the lack of identification is not a problem.

**Comment by rpgoldman** [comment]
This posting was very helpful to me in trying to figure out how to apply time series models to new data.  I'm somewhat of a novice using time series methods, but it seems like this would be a common use case, especially anywhere there's a process that's temporally extended, but stops and starts in episodes that need to be examined.
I couldn't find any general tutorial on how to apply trained statsmodels time series models to new data, and it seems fairly complex, involving cracking open internal objects.  It's also very difficult to search for on the internet, because it resists keyword search (the words like "new data" are too common to narrow things down to what one is really looking for).
So if anyone was interested, it would be a great contribution to write such a tutorial.

**Comment by bashtage** [comment]
A notebook summarizing this would is welcome.

**Comment by Maedeh-af** [comment]
Hello @ChadFulton ,
I have a train and test set and I want to do prediction on test set and fit the model just once. Is this part of code correct ?  
  ```
    kwargs = {'order': (2, 1, 2), 'trend':'n'}
    model = sm.tsa.statespace.SARIMAX(train, **kwargs, initialization='approximate_diffuse')
    params = model.fit().params
    res = model.fit()
    preds = []
    for obs in test.values:
        observations = [model.data.endog[-1], obs]
        model = sm.tsa.statespace.SARIMAX(observations, **kwargs)
        model.initialize_known(res.predicted_state[:, -2], res.predicted_state_cov[:, :, -2])
        res = model.smooth(params)
        fcast = res.forecast()
        preds.append(fcast)
        params = res.params
```

**Comment by ChadFulton** [comment]
Hi @Maedeh-af, we have made this process easier in v0.11 of Statsmodels. I recommend taking a look at https://www.statsmodels.org/devel/examples/notebooks/generated/statespace_forecasting.html, particularly the "Cross validation" section.
