### ISSUE TITLE
AttributeError: 'module' object has no attribute 'threshold'

### ISSUE THREAD

**Issue by giacomomarchioro** [statsmodels/statsmodels#5417]
Hi all,
I am trying to reproduce example for threshold function explained in [scipy.stats.threshold:](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.threshold.html)

```
a = np.array([9, 9, 6, 3, 1, 6, 1, 0, 0, 8])
from scipy import stats
stats.threshold(a, threshmin=2, threshmax=8, newval=-1)
```
Got an attribute Error:
AttributeError: 'module' object has no attribute 'threshold'

in scipy 1.1.0.

**Comment by josef-pkt** [comment]
wrong issue tracker

scipy.stats.threshold has been deprecated and removed
https://github.com/scipy/scipy/issues/617
