### ISSUE TITLE
BLD/MAINT: cython language level

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#5422]
cython seems to require setting a py2 py3 language level

https://travis-ci.org/statsmodels/statsmodels/jobs/466817528
```
/home/travis/miniconda/envs/statsmodels-test/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/travis/build/statsmodels/statsmodels/statsmodels/tsa/kalmanf/kalman_loglike.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
```

related scipy issue for dropping py 2.7 and setting cython language level
https://github.com/scipy/scipy/pull/9582

**Comment by josef-pkt** [comment]
@ChadFulton @bashtage 

Do we need to change something now while we still support both py2 or py3, or do we wait until we drop py 2.7?

**Comment by bashtage** [comment]
Makes no difference.  Might as well set to 3 and be done with it.

**Comment by bashtage** [comment]
no difference here...if you use strings/bytes/unicode/etc then it can.

**Comment by josef-pkt** [comment]
@jakirkham Nothing has been changed yet for the cython code in statsmodels, AFAIK.
Note, scipy dropped python 2.7 in master, while we have not decided yet in which version we drop python 2.7 support, not in 0.10, and maybe not yet in 0.11.

**Comment by bashtage** [comment]
Fixed in master.
