### ISSUE TITLE
Reference for OLSInfluence Cook's distance

### ISSUE THREAD

**Issue by andportnoy** [statsmodels/statsmodels#5427]
Could you please provide a more detailed reference for this formula? I'm assuming the Eubank is Randall L. Eubank, but can't figure out what book/paper this is from.

https://github.com/statsmodels/statsmodels/blob/7634b409c2d65d9f9fcd77d0d3a047136c8d2dfe/statsmodels/stats/outliers_influence.py#L1241-L1243

**Comment by josef-pkt** [comment]
This is copied from OLSInfluence, i.e. written a long time ago.
This should be in any related reference, e.g. unit tests for OLS were written against SAS.
I was reading Eubank's textbook at the time, which seems to be what this comment refers to.
https://books.google.ca/books/about/Nonparametric_Regression_and_Spline_Smoo.html?id=q0ZZDwAAQBAJ&printsec=frontcover&source=kp_read_button&redir_esc=y#v=onepage&q=cooks%20distance&f=false

I currently don't have access to the book to check.

**Comment by andportnoy** [comment]
@josef-pkt @bashtage Thank you!
