### ISSUE TITLE
extract / compute moving average from fitted SARIMAX

### ISSUE THREAD

**Issue by galenwilkerson** [statsmodels/statsmodels#5429]
hi, 

I have a SARIMAX results wrapper (computed using pyramid auto_arima), see below.

Suppose I want to take only the MA (moving average) component of this model (for example for plotting).  How do I reach into the model and access the MA computation?

Thanks in advance!

```
model = auto_arima_model.arima_res_
type(model)

statsmodels.tsa.statespace.sarimax.SARIMAXResultsWrapper

model.maparams

array([-0.49168544])

model.summary()

 Statespace Model Results Dep. Variable: 	y 	No. Observations: 	248
Model: 	SARIMAX(0, 1, 1)x(0, 0, 1, 52) 	Log Likelihood 	-1410.094
Date: 	Mon, 17 Dec 2018 	AIC 	2828.188
Time: 	11:40:41 	BIC 	2842.225
Sample: 	0 	HQIC 	2833.839
	- 248 		
Covariance Type: 	opg 		
	coef 	std err 	z 	P>|z| 	[0.025 	0.975]
intercept 	1.1816 	2.974 	0.397 	0.691 	-4.647 	7.010
ma.L1 	-0.4917 	0.041 	-11.978 	0.000 	-0.572 	-0.411
ma.S.L52 	0.1402 	0.088 	1.584 	0.113 	-0.033 	0.314
sigma2 	5293.4667 	242.298 	21.847 	0.000 	4818.571 	5768.362
Ljung-Box (Q): 	39.96 	Jarque-Bera (JB): 	1704.79
Prob(Q): 	0.47 	Prob(JB): 	0.00
Heteroskedasticity (H): 	0.52 	Skew: 	1.24
Prob(H) (two-sided): 	0.00 	Kurtosis: 	15.63
```

**Comment by ChadFulton** [comment]
I'm not sure exactly what you mean by the moving average component, so I first want to double-check that you're using the model that you think you are:

What you are fitting here is what Wikipedia refers to as a [moving-average model](https://en.wikipedia.org/wiki/Moving-average_model), and this is distinct from computing a [moving average](https://en.wikipedia.org/wiki/Moving_average).

What you are fitting is a model which is a moving average in the (unobserved) *disturbances*:

y(t) = a(1) eps(t-1) + a(52) eps(t-52) + eps(t)

(where eps(t) is an unobserved disturbance process)

This is in contrast to, for example, an exponentially weighted moving average, like:

ema(t) = a y_t + (1 - a) ema_{t-1}

Are you intending to fit a model of the first type?

**Comment by galenwilkerson** [comment]
I'm a bit new to ARIMA models, so I appreciate your patience.

Hmm, let's see.  Let's ignore the S and X of SARIMAX (from statsmodels).  This is an ARIMA model.  So, I'm using auto_arima to give me an ARIMA.  

ARIMA has AR auto-regressive, I integrative, and MA moving-average components.  That means the fitted model ARIMA model has coefficients that it multiplies by what it thinks is the moving average, based on the order of the MA (usually called q).  

So, if q = 1 we have this:

![image](https://user-images.githubusercontent.com/208536/50142719-1070c580-02ab-11e9-8383-491839d2805f.png)

So, suppose I have access to all the various coefficients in a fitted statsmodels ARIMA (or SARIMAX) model.  How can I use these coefficients to obtain the moving average itself?

Thanks for any help or explanation.
best

**Comment by ChadFulton** [comment]
Okay great - so the question is what you mean by "the moving average itself". Using your q=1 example, we have:

xt=μ+wt+θ1wt−1

what time series are you wanting to plot estimates of?

- E[μ+wt+θ1wt−1] ?
- E[u + θ1wt−1] ?
- E[θ1wt−1] ?
- or something else?

where E[ . ] denotes expectation (since the wt are unobserved).

Is there some reference that you've found that plots a particular moving average from the output of this type of model?

**Comment by josef-pkt** [comment]
Given that the model in the initial question only has MA terms, the moving average might be just the one step ahead prediction, i.e. `results.predict()` 
But I have never seen a split into separate MA and AR contribution for general ARMA models.

I'm closing this as not clear what the question is.
