### ISSUE TITLE
BUG: Augmented dickey-fuller test with fewer than 9 observations.

### ISSUE THREAD

**Issue by sbnbari** [statsmodels/statsmodels#5432]
Hi 
i'm trying the dickey fuller test on yearly data and want to make it stationary but im unable to do it. i have applied that test on monthly and daily but getting an error while applying the ADF on yearly data which i'm going to use for my ARIMA model. your help will be much appreciated.
![error1](https://user-images.githubusercontent.com/36491007/50255186-c7bf2680-03e8-11e9-9d81-f12e34ab1172.PNG)
data with yearly basis trends in the above picture
![error2](https://user-images.githubusercontent.com/36491007/50255228-f0dfb700-03e8-11e9-97da-7b4de09a27bc.PNG)

**Comment by ChadFulton** [comment]
Thanks! This does look like a bug in `adfuller`, which is that if you try to run the test with fewer than 9 observations without specifying `maxlag`, it gives an error when trying to make `lagmat`.

As a side note, I think that after your rolling mean you only have 7 observations, and I suspect that the ADF test has very low power in this case, and may not be a useful guide in practice.

**Comment by ChadFulton** [comment]
In the meantime, you can make this work by specifying `maxlag=4` in your `adfuller` call.
