### ISSUE TITLE
RMSE and MAPE value nan while plotting timeseries ARIMA model

### ISSUE THREAD

**Issue by sbnbari** [statsmodels/statsmodels#5433]
hi 
I am working on ARIMA im trying to plot the last timeseries prediction graph of the model but RMSE AND MAPE value on the graph is coming as nan and ploting my df graph ...i think i am making some error in the last line of the code ...
![error3](https://user-images.githubusercontent.com/36491007/50262166-ade10c00-0407-11e9-95a8-31c5693b0f00.PNG)
your help will be much appreciated.

**Comment by josef-pkt** [comment]
check your prediction error computation before plotting it.
My guess is that the pandas index expands the time series and includes nans, and `sum`, and np.sum, do not ignore nans.

**Comment by josef-pkt** [comment]
I'm closing this, because it doesn't look like a problem with statsmodels

Reopen if there is a problem
