### ISSUE TITLE
forecasting graph in ARIMA Model

### ISSUE THREAD

**Issue by HaseebTariq7** [statsmodels/statsmodels#5434]
Hello 

I am trying to make forecasting graph with ARIMA Model. It's giving me output but it's not correct. it's giving me a straight forecasting line. I have attached code and graph visualisation please have a look and suggest me solution.
Many Thanks

CODE
![forecasted 1](https://user-images.githubusercontent.com/45848222/50301948-75ded500-04aa-11e9-9704-b350f984dc4e.PNG)
![forecasted 2](https://user-images.githubusercontent.com/45848222/50301951-75ded500-04aa-11e9-9f64-10b1f7b15219.PNG)

FORECASTING GRAPH
![forecasted](https://user-images.githubusercontent.com/45848222/50301660-c3a70d80-04a9-11e9-8eca-f2d1bbf3d4f0.PNG)

**Comment by ChadFulton** [comment]
ARMA models converge back to the mean relatively quickly unless they are very close to a unit root, so I don't think this is incorrect.

**Comment by HaseebTariq7** [comment]
> ARMA models converge back to the mean relatively quickly unless they are very close to a unit root, so I don't think this is incorrect.

Can you please explain more about it?
Because I am very confused about it I don't know about why it's predicting like this?
and why it's having FORECASTED LINE is Straight?

**Comment by ChadFulton** [comment]
The forecast line is not straight - if you look closely you can see that the first few forecasts bounce around a little bit, before converging to zero.

To understand what I mean about converging back to the mean, consider an AR(1) model:

y(t) = a * y(t-1) + e

The parameter `a` is the autoregressive coefficient, and in a typical (stationary) model, it is constrained to be between -1 and 1.

The prediction of y(t+1) will be:

y(t+1) = a y(t)

The prediction of y(t+2) will be:

y(t+2) = a y(t+1) = a^2 y(t)

and so on.

Now, suppose that you estimate a = 0.5, and the last datapoint in your sample is y(T) = 800. Then your predictions will be:

y(T + 1) = 400
y(T + 2) = 200
y(T + 3) = 100
y(T + 4) = 50
...
y(T + 12) = 0.195
...
y(T + 24) = 0.000048

Hope that helps.

**Comment by bashtage** [comment]
Closing since the question has been answered. No action needed.
