### ISSUE TITLE
How to use `IV2SLS.from_formula`

### ISSUE THREAD

**Issue by spring-haru** [statsmodels/statsmodels#5436]
I want to use `statsmodels.sandbox.regression.gmm.IV2SLS.from_formula`, but how to write a formula is not obvious from the [webpage](https://www.statsmodels.org/stable/generated/statsmodels.sandbox.regression.gmm.IV2SLS.from_formula.html#statsmodels.sandbox.regression.gmm.IV2SLS.from_formula). I wonder if someone can show me examples of formulas, distinguishing **dependent variable**, **exogenous regressors**, **endogenous regressors** and **instrumental variables**. Your help would be greatly appreciated.

**Comment by josef-pkt** [comment]
my guess is that `IV2SLS.from_formula` is not specifically supported, i.e. inherited but doesn't take special features of the model into account.
Note: IV2SLS does not distinguish among regressors. All endogenous regressors need to be added to `exog`, all exogenous regressors need to be added to instruments.
(i.e. exogenous regressors are their own instrument, written in analogy to IVGMM.)


(I should be able to look into it in a few days. prio-elevated as reminder to check this)

Kevin's linearmodels package https://pypi.org/project/linearmodels/ should handle this more completely than IV2SLS.

**Comment by spring-haru** [comment]
Thanks for your info.
Wishing you a happy new year!

**Comment by bashtage** [comment]
Closing, no action.

**Comment by ginward** [comment]
I have the same question ...
