### ISSUE TITLE
BLD: Unable to lint

### ISSUE THREAD

**Issue by bksahu** [statsmodels/statsmodels#5447]
I am unable to use the lint.sh for linting.

## Steps to Reproduce
```
$ /bin/bash lint.sh
inside lint.sh
```
Only that one line is executing.

## System: 
Ubuntu 16.04
Python 3.7
Pip 18.1 with flake8

**Comment by ChadFulton** [comment]
Due to the way we have the CI builds set up, the linter won't do anything unless the environmental variable $LINT is set to a truthy value.

For example, in my shell (Mac OS X), it works if I run: `LINT=true ./lint.sh` as a single command.

**Comment by ChadFulton** [comment]
(closing, since I think this will solve the problem, but re-open if not).

**Comment by ChadFulton** [comment]
Thanks! That is very much appreciated.
