### ISSUE TITLE
update() method in UnobservedComponents doesn't work ?

### ISSUE THREAD

**Issue by cerlymarco** [statsmodels/statsmodels#5456]
I fit a simple UnobservedComponents model:

`UCM_mod = sm.tsa.UnobservedComponents(air.log_pass, level='local linear trend', seasonal=12)`
`UCM_fit = UCM_mod.fit()`

The convergence is OK and 4 params was fitted (i see them with `UCM_fit.params`). 
Then i try to update the params with `UCM_fit.update([param1,param2,param3,param4]) `
but nothing appens. I think that this method'll return an array with the updated paramethers and will update the model in order to give the possibility to refit it, is it correct?

**Comment by ChadFulton** [comment]
The `update` method updates the state space representation with new parameters, it does not refit the model.

If you get new data, then the best way to refit the model is to create a new model object with the updated dataset, and then call `fit` using the parameters from the original model fit as starting parameters. e.g.:

```python
original_data = [ ... ]
mod1 = sm.tsa.UnobservedComponents(original_data, 'llevel', ...)
res1 = mod1.fit()

# ... later
new_data = [ ... ]
mod2 = sm.tsa.UnobservedComponents(original_data, 'llevel', ...)
res2 = mod2.fit(start_params=res1.params)
```
