### ISSUE TITLE
TST: innovation algo fails on one travis

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#5457]
`test_innovations_algo_filter_kalman_filter[ar_params5-ma_params5-1.123]`
fails with what looks like a precision issue on master, e.g. https://travis-ci.org/statsmodels/statsmodels/jobs/477508395

also from the code snippet in the failure message it looks like there is no random seed set for this unit test

problem with parameterized tests: the tests draws random numbers separately for all parameter configurations.

**Comment by josef-pkt** [comment]
fails also in one appveyor, py 2.7
https://ci.appveyor.com/project/josef-pkt/statsmodels/builds/21525361/job/pqn7br6se9c24r56

**Comment by josef-pkt** [comment]
bump, stilll randomly failing
https://travis-ci.org/statsmodels/statsmodels/jobs/482499211

**Comment by thequackdaddy** [comment]
https://github.com/statsmodels/statsmodels/blob/da9d7e9431095025d6bd66d25cb87d46220769fe/statsmodels/tsa/innovations/tests/test_arma_innovations.py#L22-L30

Would it make sense to add a `np.random.seed` here?

**Comment by ChadFulton** [comment]
Yes! Sorry, I missed this issue originally!

**Comment by bashtage** [comment]
This has been fixed AFAICT.
