### ISSUE TITLE
exception = cannot copy sequence with size 37 to array axis with dimension 371

### ISSUE THREAD

**Issue by Trailmaster** [statsmodels/statsmodels#5465]
Hello , 
Please help me  , the exception : 
exception = cannot copy sequence with size 37 to array axis with dimension 371
is occurring at following line of code in holtwinters.py - 

p[:] = [init_alpha, init_beta, init_gamma, l0, b0, init_phi] + s0

here, p[:] contains ndarray of size 371 having 0.0 value in each cell ,and  and "[init_alpha, init_beta, init_gamma, l0, b0, init_phi] + s0" contains list with size 37 .
I'm performing forecasting on time series

**Comment by josef-pkt** [comment]
Is this with 0.9 release or with master?
There has been many changes/refactorings in master since 0.9.
If it is with master, then we need a reproducible example. My main guess, not having looked closely at the code, is that there is some input type or format that is not supported.
