### ISSUE TITLE
load got an unexpected keyword argument 'as_pandas'

### ISSUE THREAD

**Issue by RonLek** [statsmodels/statsmodels#5468]
I was trying to reproduce the Examples code for Linear Regression from the docs (http://www.statsmodels.org/devel/regression.html#examples). On executing
`spector_data = sm.datasets.spector.load(as_pandas=False)`
I get the error 
`TypeError: load() got an unexpected keyword argument 'as_pandas'`

Here is the screenshot of the code and the error:
![](https://i.postimg.cc/sX1XnPnW/Screenshot-110.png)

When I tried using the method `load_pandas()` without any arguments it works correctly.

Not sure if `as_pandas` has been deprecated and has been replaced with `load_pandas()` instead.

**Comment by josef-pkt** [comment]
`load` for datasets has been refactored to use pandas instead of numpy recarrays. #4853
This will be new in 0.10, based on the PR, i.e. the `devel` docs should be corrected.

I guess we missed to update those cases in the docs.

**Comment by josef-pkt** [comment]
or maybe it's the other way around: Are you using 0.9?

The `devel` docs should be for master/0.10dev and might not be correct for 0.9.

**Comment by RonLek** [comment]
@josef-pkt I think you're right. It's the other way round. I'm using 0.9. I guess the docs online have been updated before the release. Thanks for the quick reply!

**Comment by josef-pkt** [comment]
You can look at the `stable` docs which are for the released version http://www.statsmodels.org/stable/
The `devel` docs are now automatically updated with and for master.
