### ISSUE TITLE
KaplanMeier.test_diff in survival2 raises IndexError

### ISSUE THREAD

**Issue by kshedden** [statsmodels/statsmodels#547]
An index error occurs at this line when calling KaplanMeier.test_diff (only for certain data sets):

dk = dk[:,list(tind)]

It appears to be easily fixed by changing this line (4 lines up)

if np.max(tind) != len(dk):

to this:

if np.max(tind) > len(dk)-1:

This occurs in two different places, once in the "if self.censoring == None" condition and once in the following "else" condition.

**Comment by josef-pkt** [comment]
Needs to be checked against whatever version of survival2 will be the final PR to be merged.
I don't think anything will happen for 0.7
