### ISSUE TITLE
qqplot() returns two plots 

### ISSUE THREAD

**Issue by StevenLi-DS** [statsmodels/statsmodels#5493]
version: `0.9.0`

**Expected Behavoir:** 
Call  `.qqplot()` in an interactive enviorment will returns one plot.

**Actaul Behavoir:**
In an interactive environment, `.qqplot()` [function][1] keeps returning two identical plots if the user doesn't call `plt.show()` or assign the returned `fig` to a variable. If the user assigns the returned plot to a variable, the plot will still display (but only one plot). 

[1]: https://www.statsmodels.org/0.9.0/generated/statsmodels.graphics.gofplots.qqplot.html#statsmodels.graphics.gofplots.qqplot

![image](https://user-images.githubusercontent.com/33796896/52654570-42279680-2ec0-11e9-9e26-8e200d96a531.png)

**Comment by josef-pkt** [comment]
duplicate issue, 
There is nothing that we want to do about this behavior of jupyter notebooks

The easiest is to end with a semicolon
see https://github.com/statsmodels/statsmodels/issues/1265#issuecomment-383336489

**Comment by StevenLi-DS** [comment]
Sorry about that. I searched it before opening and didn't realize that this happens to all plot functions.
