### ISSUE TITLE
DOC: Incomplete Binomial docstring on endog format

### ISSUE THREAD

**Issue by nathanntg** [statsmodels/statsmodels#5519]
I know there are some active discussions about revising the GLM Binomial implementation (see #5282), but in the mean time I wanted to highlight a somewhat confusing note in the documentation:

https://github.com/statsmodels/statsmodels/blob/7a33ef0ba2900f8e1d27fbd052c7a28d5a626342/statsmodels/genmod/families/family.py#L799

The documentation explains that there are three ways to pass endogenous variables to the Binomial GLM, but does not elaborate what those three ways are.

I'm happy to write a few sentences elaborating and submit a pull request if that helps. I _believe_ the three ways are as follows:

* A vector of 0 or 1 values (indicating failure or success respectively).
* A vector of proportions, indicating the proportion of successes, with parameter `freq_weights` containing the number of trials for each row.
* A `N × 2` matrix, where values in the first column represent the success count and values in the second column represent the failure count.

Thanks!

**Comment by josef-pkt** [comment]
This two are the ways that existed for a long time

- A vector of 0 or 1 values (indicating failure or success respectively).
- A N × 2 matrix, where values in the first column represent the success count and values in the second column represent the failure count.

There are equivalent ways now after the introduction of weights. There are some comparison of different ways of specifying the same basic models in notebooks that we made during the weights addition. 

- A vector of proportions, indicating the proportion of successes, with parameter freq_weights containing the number of trials for each row.
This needs to use `var_weights` and not `freq_weights`. This is the main version that R's GLM uses, AFAIR.

`var_weights` are used when endog is the mean of response values for observations that have the same exog (but not necessarily the same endog).
`freq_weights` are used when cases are replicated, i.e. combining observations that have the same exog AND the same endog.

Improvements to the documentation is welcome.
