### ISSUE TITLE
extract the estimated standard deviation of innovation in python arima.fit

### ISSUE THREAD

**Issue by yl-hz** [statsmodels/statsmodels#5527]
I wonder how I can get the return value of the estimated standard deviation (the estimated SD of noise) after running m.tsa.ARMA(X, (0, 1)).fit(trend='nc', disp=0). I know that by using print(ma1_model.summary()), we can get the table where it shows  S.D. of innovations.
![image](https://user-images.githubusercontent.com/48391886/54076238-59676300-4277-11e9-9fb9-ca62627b7edb.png)
But I also want the value of S.D. of innovations for further calculation. How can I directly store it in a variable like what we can do to get the maximum likelihood estimator using "ma1_model.params"? And also for the value of log-likelihood shown in the table?

**Comment by ChadFulton** [comment]
You can access the estimated variance using the `sigma2` attribute (with the standard deviation its square root). For example:

```python
mod = sm.tsa.ARMA(endog, order=(1, 0))
res = mod.fit()
print(res.sigma2)
```

**Comment by yl-hz** [comment]
It works and the number matches! Thank you so much!

**Comment by yl-hz** [comment]
> You can access the estimated variance using the `sigma2` attribute (with the standard deviation its square root). For example:
> 
> ```python
> mod = sm.tsa.ARMA(endog, order=(1, 0))
> res = mod.fit()
> print(res.sigma2)
> ```

It works and the number matches! Thank you so much!

**Comment by ChadFulton** [comment]
Great!
