### ISSUE TITLE
statsmodels.tsa.statespace.structural.UnobservedComponents issue in pyspark

### ISSUE THREAD

**Issue by jane0213** [statsmodels/statsmodels#5533]
When passing string parameter for "level", always get complain in for "https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/statespace/structural.py"
about line 510 " self.trend * 0x08 | " with  error message "invalid operator | for int and unicode".

No problem running in local Spark but complain in production Spark environment, because 'level' variable is passed in as string but override as int inside the code, so wondering is that due to parallelized processing causing variable type inconsistency?

**Comment by ChadFulton** [comment]
Thanks for this report - that is an interesting case. Can you give a simple example that would trigger the problem in the production environment?

**Comment by jane0213** [comment]
Environment is Python 2.7
`
import statsmodels.api as sm
list_num_users = [1, 2, 3, 4, 5, 5, 6, 7]
model_params = {
    'level': 'local linear trend', 'cycle': True, 'damped_cycle': True, 'stochastic_cycle': True
}
user_mod = sm.tsa.UnobservedComponents(list_num_users, **model_params)
user_res = user_mod.fit(method='powell', disp=False)`

Error won't be triggered if change the code as below only using True/False input:

`model_params = {'level': True,
                    'trend': True,
                    'irregular': True,
                    'stochastic_level': True,
                    'stochastic_trend': True,
                    'cycle': True,
                    'damped_cycle': True,
                    'stochastic_cycle': True
                    }`

**Comment by bashtage** [comment]
If it only happens in spark, then it is probably some sort of pickling issue.

**Comment by bashtage** [comment]
Since Python 2.7 is no longer a development target, this is being closed.  If you can reproduce in Python 3, please open a new issue.
