### ISSUE TITLE
BUG: ARIMA SVD doesn't converge

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#5534]
See [this stackoverflow question](https://stackoverflow.com/questions/55109912/).

Reproducible example:

```python
import statsmodels.api as sm
values = [-1.45, -9.04, -3.64, -10.37, -1.36, -6.83, -6.01, -3.84, -9.92, -5.21,
          -8.97, -6.19, -4.12, -11.03, -2.27, -4.07, -5.08, -4.57, -7.87, -2.80,
          -4.29, -4.19, -3.76, -22.54, -5.87, -6.39]

mod = sm.tsa.ARIMA(values, order=(7, 0, 0))
res = mod.fit()
```

produces:

    ~/projects/statsmodels/statsmodels/tsa/tsatools.py:610: RuntimeWarning: invalid value encountered in true_divide
      (1+np.exp(-params))).copy()
    ~/projects/statsmodels/statsmodels/tsa/tsatools.py:612: RuntimeWarning: invalid value encountered in true_divide
      (1+np.exp(-params))).copy()
    ---------------------------------------------------------------------------
    LinAlgError                               Traceback (most recent call last)
    <ipython-input-1-ce8f66834cd0> in <module>
          5 
          6 mod = sm.tsa.ARIMA(values, order=(7, 0, 0))
    ----> 7 res = mod.fit()

    ~/projects/statsmodels/statsmodels/tsa/arima_model.py in fit(self, start_params, trend, method, transparams, solver, maxiter, full_output, disp, callback, start_ar_lags, **kwargs)
        957                                        maxiter=maxiter,
        958                                        full_output=full_output, disp=disp,
    --> 959                                        callback=callback, **kwargs)
        960         params = mlefit.params
        961 

    ~/projects/statsmodels/statsmodels/base/model.py in fit(self, start_params, method, maxiter, full_output, disp, fargs, callback, retall, skip_hessian, **kwargs)
        464                                                        callback=callback,
        465                                                        retall=retall,
    --> 466                                                        full_output=full_output)
        467 
        468         # NOTE: this is for fit_regularized and should be generalized

    ~/projects/statsmodels/statsmodels/base/optimizer.py in _fit(self, objective, gradient, start_params, fargs, kwargs, hessian, method, maxiter, full_output, disp, callback, retall)
        189                             disp=disp, maxiter=maxiter, callback=callback,
        190                             retall=retall, full_output=full_output,
    --> 191                             hess=hessian)
        192 
        193         optim_settings = {'optimizer': method, 'start_params': start_params,

    ~/projects/statsmodels/statsmodels/base/optimizer.py in _fit_lbfgs(f, score, start_params, fargs, kwargs, disp, maxiter, callback, retall, full_output, hess)
        408                                      callback=callback, args=fargs,
        409                                      bounds=bounds, disp=disp,
    --> 410                                      **extra_kwargs)
        411 
        412     if full_output:

    ~/miniconda3/envs/python3/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py in fmin_l_bfgs_b(func, x0, fprime, args, approx_grad, bounds, m, factr, pgtol, epsilon, iprint, maxfun, maxiter, disp, callback, maxls)
        197 
        198     res = _minimize_lbfgsb(fun, x0, args=args, jac=jac, bounds=bounds,
    --> 199                            **opts)
        200     d = {'grad': res['jac'],
        201          'task': res['message'],

    ~/miniconda3/envs/python3/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, **unknown_options)
        333             # until the completion of the current minimization iteration.
        334             # Overwrite f and g:
    --> 335             f, g = func_and_grad(x)
        336         elif task_str.startswith(b'NEW_X'):
        337             # new iteration

    ~/miniconda3/envs/python3/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py in func_and_grad(x)
        278     if jac is None:
        279         def func_and_grad(x):
    --> 280             f = fun(x, *args)
        281             g = _approx_fprime_helper(x, fun, epsilon, args=args, f0=f)
        282             return f, g

    ~/miniconda3/envs/python3/lib/python3.7/site-packages/scipy/optimize/optimize.py in function_wrapper(*wrapper_args)
        298     def function_wrapper(*wrapper_args):
        299         ncalls[0] += 1
    --> 300         return function(*(wrapper_args + args))
        301 
        302     return ncalls, function_wrapper

    ~/projects/statsmodels/statsmodels/base/model.py in f(params, *args)
        438 
        439         def f(params, *args):
    --> 440             return -self.loglike(params, *args) / nobs
        441 
        442         if method == 'newton':

    ~/projects/statsmodels/statsmodels/tsa/arima_model.py in loglike(self, params, set_sigma2)
        778         method = self.method
        779         if method in ['mle', 'css-mle']:
    --> 780             return self.loglike_kalman(params, set_sigma2)
        781         elif method == 'css':
        782             return self.loglike_css(params, set_sigma2)

    ~/projects/statsmodels/statsmodels/tsa/arima_model.py in loglike_kalman(self, params, set_sigma2)
        788         Compute exact loglikelihood for ARMA(p,q) model by the Kalman Filter.
        789         """
    --> 790         return KalmanFilter.loglike(params, self, set_sigma2)
        791 
        792     def loglike_css(self, params, set_sigma2=True):

    ~/projects/statsmodels/statsmodels/tsa/kalmanf/kalmanfilter.py in loglike(cls, params, arma_model, set_sigma2)
        647             loglike, sigma2 =  kalman_loglike.kalman_loglike_double(y, k,
        648                                     k_ar, k_ma, k_lags, int(nobs), Z_mat,
    --> 649                                     R_mat, T_mat)
        650         elif issubdtype(paramsdtype, np.complex128):
        651             loglike, sigma2 =  kalman_loglike.kalman_loglike_complex(y, k,

    kalman_loglike.pyx in statsmodels.tsa.kalmanf.kalman_loglike.kalman_loglike_double()

    kalman_loglike.pyx in statsmodels.tsa.kalmanf.kalman_loglike.kalman_filter_double()

    ~/miniconda3/envs/python3/lib/python3.7/site-packages/numpy/linalg/linalg.py in pinv(a, rcond)
       1936         return wrap(res)
       1937     a = a.conjugate()
    -> 1938     u, s, vt = svd(a, full_matrices=False)
       1939 
       1940     # discard small singular values

    ~/miniconda3/envs/python3/lib/python3.7/site-packages/numpy/linalg/linalg.py in svd(a, full_matrices, compute_uv)
       1610 
       1611         signature = 'D->DdD' if isComplexType(t) else 'd->ddd'
    -> 1612         u, s, vh = gufunc(a, signature=signature, extobj=extobj)
       1613         u = u.astype(result_t, copy=False)
       1614         s = s.astype(_realType(result_t), copy=False)

    ~/miniconda3/envs/python3/lib/python3.7/site-packages/numpy/linalg/linalg.py in _raise_linalgerror_svd_nonconvergence(err, flag)
        104 
        105 def _raise_linalgerror_svd_nonconvergence(err, flag):
    --> 106     raise LinAlgError("SVD did not converge")
        107 
        108 def _raise_linalgerror_lstsq(err, flag):

    LinAlgError: SVD did not converge

The proximate cause seems to be that after a while, BFGS suggests some extreme parameters, jumping from:

    [ -2.19499998 -10.42001802   1.18077056  -2.44187301   1.28260439
      -0.92432099  -0.50057343]

to, in the next step:

    [ -824.12489599  -811.27748556  -810.98323322 -1484.64165179
      -595.64216211  -248.92713132 -1118.43471031]

(both of these are untransformed versions of the parameters).

**Comment by jcdang** [comment]
I found an issue with the [AR Transparams](https://github.com/statsmodels/statsmodels/blob/599c76251354958bb72625c80eb9a3152167b680/statsmodels/tsa/tsatools.py#L619-L622)

I'm thinking this code should be replaced with:
```
newparams = np.tanh(params/2)
tmp = np.tanh(params/2)
```
I tested and it still didn't converge but it didn't raise an error.


```
 This problem is unconstrained.

 Bad direction in the line search;
   refresh the lbfgs memory and restart the iteration.

 Line search cannot locate an adequate point after 20 function
  and gradient evaluations.  Previous x, f and g restored.
 Possible causes: 1 error in function or gradient evaluation;
                  2 rounding error dominate computation.
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            8     M =           12

At X0         0 variables are exactly at the bounds

At iterate    0    f=  3.15310D+00    |proj g|=  8.96953D+02
  ys=-2.536E-05  -gs= 6.918E-05 BFGS update SKIPPED

At iterate    5    f=  3.15310D+00    |proj g|=  8.72633D+02
  ys=-3.086E-07  -gs= 3.652E-07 BFGS update SKIPPED

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    8      6     75      2     2     0   8.726D+02   3.153D+00
  F =   3.1530951320531133     

ABNORMAL_TERMINATION_IN_LNSRCH                              

 Cauchy                time 0.000E+00 seconds.
 Subspace minimization time 0.000E+00 seconds.
 Line search           time 0.000E+00 seconds.

 Total User time 0.000E+00 seconds.
```

**Comment by ChadFulton** [comment]
Interesting!! Is it really an issue with the current code (like the current code is wrong in some way), or is it just that tanh is better? And, is tanh better?

**Comment by jcdang** [comment]
(1 - e^-x)/(1 + e^-x) is mathematically equivalent to tanh(x/2).  The current code is flawed in that it doesn't handle limits well in regards to float precision.  Numpy's tanh function provides the expected behavior.  It's probably faster too.

**Comment by ChadFulton** [comment]
Oh very nice. Would you mind submitting a PR?

**Comment by jcdang** [comment]
#5569 For your review.

**Comment by bashtage** [comment]
Seems #5569 fixed this.  Reopen if it did not.
