### ISSUE TITLE
NotImplementedError on ConditionalLogit

### ISSUE THREAD

**Issue by emilmirzayev** [statsmodels/statsmodels#5536]
Hi! 
Is there a method for making predictions based on ConditionalLogit model?

When I run
```python
from sklearn.model_selection import train_test_split
from sklearn import metrics
data = data.replace([np.inf, -np.inf], np.nan)
data = data.fillna(0)


train_id, test_id = train_test_split(unique_ids, test_size = 0.25, random_state = 0)
train_dataset = data[data["individual"].isin(train_id)]
test_dataset = data[data["individual"].isin(test_id)]

X_train_full = train_dataset[full_model_var_names]
y_train_full = train_dataset["choice"]
X_test_full = test_dataset[full_model_var_names]
y_test_full = test_dataset["choice"]

model_full = ConditionalLogit(y_train_full, X_train_full, groups = train_dataset["individual"])
result_full = model_full.fit(method= "lbfgs")

predictions = result_full.predict(X_train)
```
I get **NotImplementedError**

```python
result_full.predict(exog = X_test_full, groups = test_dataset["individual"])
Traceback (most recent call last):

  File "<ipython-input-18-69c31c80e601>", line 1, in <module>
    result_full.predict(exog = X_test_full, groups = test_dataset["individual"])

  File "c:\users\emirzayev\appdata\local\programs\python\python37-32\lib\site-packages\statsmodels-0+unknown-py3.7-win32.egg\statsmodels\base\model.py", line 1013, in predict
    **kwargs)

  File "c:\users\emirzayev\appdata\local\programs\python\python37-32\lib\site-packages\statsmodels-0+unknown-py3.7-win32.egg\statsmodels\base\model.py", line 202, in predict
    raise NotImplementedError

```

**Comment by kshedden** [comment]
Conditional models are limited in terms of making predictions.  The premise
of the model is that there are cluster-specific fixed effects, but these
are not estimated.  This means that when you go to make a prediction, you
can't account for these fixed effects.  So on the first pass with this, I
intentionally did not implement a prediction method.

We could have one, with the caveat that it only should be used to make
relative comparisons within clusters.

You could easily get these via the following:

linpred = np.dot(model.exog, result.params)
prob = 1 / (1 + np.exp(-linpred))

I didn't get a chance to follow up further on your convergence
difficulties.  Are they resolved?

**Comment by emilmirzayev** [comment]
Hi!
about my other question recently, the convergence one, it is resolved. There were times that MLE part was not converging due to large size (this is what I assume to be the problem) and when I switched to LBFGS as algo for optimizing, it could converge better and faster..
About the solution you provided, it works. However, as you already mentioned, such models are unable to predict unseen data, and therefore, ROC curve is useless.

What can you advise in such cases? How to summarize model accuracy in the most efficient way?

**Comment by kshedden** [comment]
Thanks for the report regarding the algorithm.  

As far as I know, these models are used to estimate effects for research purposes while controlling for stable confounders at the cluster level.  They are not primarily motivated by the goal of doing prediction.

The log odds ratio parameters are a safe way to estimate covariate effects while minimizing confounding (from stable confounders).   If the odds ratio for age is 1.2, this means that comparing two people who are one year apart in age, and who are identical in terms of all other covariates in the model, and who are in the same cluster, the older person will have 20% greater odds (of whatever the outcome is) than the younger person.

Not only are the cluster-level "intercepts" not estimated, but there is not even an overall intercept.  Thus on the probability scale, what you get from these models could be very far from the actual probability.  In fact, I don't think it makes sense to look at the results on the probability scale.

**Comment by bashtage** [comment]
Closing since appears all issues addressed.
