### ISSUE TITLE
tsa Regime switching model does not forecast

### ISSUE THREAD

**Issue by shouryasal** [statsmodels/statsmodels#5537]
<b>model.forecast()</b> throws NotImplementedError for regime switching model. It is not giving out of sample predictions.  
<b>model.predict()</b> only gives in sample predictions.

**Comment by ChadFulton** [comment]
Yes, unfortunately, out-of-sample forecasting is not implemented for regime switching models.  Contributions would be very welcome, if you're interested.

**Comment by dimcarien** [comment]
Hi ChadFulton,

I didn't understand your previous comment. I tried to do a forecasting/prediction, and I read your code:
`def predict(self, params, start=None, end=None, probabilities=None, conditional=False)`

I'm aim at computing Value-at-Risk. Can you help me to fix my code below please?
```
dta_kns = ret-mu
dta_kns.plot()
mod_kns = sm.tsa.MarkovRegression(dta_kns, k_regimes=3, trend='nc', switching_variance=True)
res_kns = mod_kns.fit()
print(res_kns.summary())
q_kns = mod_kns.distribution.ppf([0.05])
forecasts_kns = res_kns.predict()
cond_mean_kns = forecasts_kns.mean
cond_var_kns = forecasts_kns.var
value_at_risk_kns = - cond_mean_kns.values - np.sqrt(cond_var_kns).values * q_kns[None, :]
print("value_at_risk_kns =",value_at_risk_kns)
```
1st question: is there any distribution asumption for Markov Regime Switching GARCH?
2nd question: how can I compute the left quantile?

Thanks for reading me

**Comment by ChadFulton** [comment]
As mentioned in your other issue, this model is not for Markov switching GARCH.

Second, the `res_kns.predict` method does not compute out-of-sample forecasts, it only computes in-sample predictions. As I mentioned above, we do not currently support out-of-sample forecasting in the Markov switching models.

**Comment by hamzas8** [comment]
Has out of sample forecasting not been implemented yet?

model.forecast() still throws the error.

**Comment by mvlvrd** [comment]
I have an implementation of the MS-AR and MS-R `forecast` methods and would like to make a PR. However, I have no access to external implementations against to which test the results. I would appreciate any hints.
