### ISSUE TITLE
SARIMAX - ValueError : maxlag should be < nobs error

### ISSUE THREAD

**Issue by skalapatapu** [statsmodels/statsmodels#5555]
I am getting error saying "maxlag should be < nobs" when I ran SARIMAX.

 **mod_sl_ar = sm.tsa.statespace.SARIMAX(train[var],exog=train[arimax_vars],order= [0,1,2]  , seasonal_order= [0,1,1,52]  ,mle_regression=True).fit()
  predictions = mod_hl_ar.forecast(len(test),exog=test[arimax_vars], dynamic= True)**

 File "C:\Users\skalapatapu\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py", line 401, in lagmat
    raise ValueError("maxlag should be < nobs")

ValueError: maxlag should be < nobs
 
Total data points: 166
Len of train: 139
Len of test: 23 
The frequency of my data is 52, as I want predictions on a weekly level. I do have data for every week, there are no missing values. 
order = [0,1,2]
seasonal = [0,1,0,52]
Taking into consideration: If you have an SARIMAX (p,d,q)x(P,D,Q,s) model, a quick back-of-the-envelope calculation suggests that you need at least:
d + D*s + max(3*q + 1, 3*Q*s + 1, p, P*s) + 1 observations

I'm going to need 209 observations. But I don't have so much data available.

When I make Q=0, it works. But then it means I'm removing my seasonality. 

Could anyone please suggest how to go about it now? These issues don't arise with R though.

**Comment by ChadFulton** [comment]
The problem here is with computing starting parameters for the `fit` command. You can solve this problem by using:

```python
mod_sl_ar = sm.tsa.statespace.SARIMAX(train[var],exog=train[arimax_vars],order= [0,1,2] , seasonal_order= [0,1,1,52] ,mle_regression=True)
start_params = np.r_[[0] * (mod_sl_ar.k_params - 1), 1]
res_sl_ar = mod_sl_ar.fit(start_params=start_params)
predictions = res_hl_ar.forecast(len(test),exog=test[arimax_vars], dynamic= True)
```

However, I think you may not have enough data for this specification to be particularly useful - you are likely to overfit. This is why the "rule of thumb" suggests that you should use more data with such a model.

**Comment by skalapatapu** [comment]
Hi Chad,
Thank you for the reply. I get the below error while running the code..

res_sl_ar = mod_sl_ar.fit(start_params=start_params)
C:\Users\skalapatapu\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tsa\statespace\tools.py:602: RuntimeWarning: divide by zero encountered in true_divide
  x = r / ((1 - r**2)**0.5)
Traceback (most recent call last):

  File "<ipython-input-637-f42a68ef97af>", line 1, in <module>
    res_sl_ar = mod_sl_ar.fit(start_params=start_params)

  File "C:\Users\skalapatapu\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 451, in fit
    start_params = self.untransform_params(np.array(start_params))

  File "C:\Users\skalapatapu\AppData\Local\Continuum\anaconda3\lib\site-packages\statsmodels\tsa\statespace\sarimax.py", line 1481, in untransform_params
    unconstrained[start] = constrained[start]**0.5

IndexError: index 8 is out of bounds for axis 0 with size 8
