### ISSUE TITLE
ARIMA.predict()

### ISSUE THREAD

**Issue by KunalBasnet** [statsmodels/statsmodels#5559]
I have been trying to work with the predict function of ARIMA

Funtion:-
start_index = '2015-12-26'
end_index = '2016-02-14'
print(results_AR.predict(start=start_index,
end=end_index))

Error:-KeyError: 'only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices'

**Comment by emilmirzayev** [comment]
It seems, `statsmodels.tsa.arima_model.ARIMAResults` fails to parse the string you provided to a proper datetime. Have you tried to parse it yourself? you can use `datetime` for that?

**Comment by KunalBasnet** [comment]
Also have used the datetime function for converting the string to datetime still the same error.

**Comment by bashtage** [comment]
Could you provide a runnable example the produces the error?

**Comment by bashtage** [comment]
Closing as answered. Please reopen if the issue persists.
