### ISSUE TITLE
[QUESTION] Making RuntimeWarning throw an error

### ISSUE THREAD

**Issue by emilmirzayev** [statsmodels/statsmodels#5568]
Hi! 
this question is also related to #5482, but it is a bit different. 
Is there a feature which can make so that, `RuntimeWarning` breaks the code?
I need it to throw an error and stop the execution.
Pseudo example
```python
import statsmodels
statsmodels.warnings(warnings_break_the_code = True)
```
Something like this maybe?

**Comment by kshedden** [comment]
Does this work?

```
import warnings
warnings.simplefilter("error")
```

**Comment by emilmirzayev** [comment]
Yes it does! Thank you

I didn't know that I could do it on python level, instead of library level
