### ISSUE TITLE
BUG: suspicious behavior of dynamic predictions in SARIMAX

### ISSUE THREAD

**Issue by vss888** [statsmodels/statsmodels#5571]
Let us assume that we have an `SARIMAX` object `model` and `SARIMAXResults` object `sr` which is a result of the following call `sr = model.filter(someParameters)`. 

What we see is that if one calls `sr.get_prediction(start=i, end=i, dynamic=1).predicted_mean[0]` one gets one result, and if one calls `sr.get_prediction(start=i, end=i+1, dynamic=1).predicted_mean[0]` one gets a different result (in our use case, the difference could be up to 10%). However, we believe that the two results should be identical since it is the same prediction but done one additional step further. It is possible that some information gets unintentionally overwritten during the second call.

Please, let us know if the behavior is as expected and if it is then why are the 2 results different?

Thank you for your help!

**Comment by ChadFulton** [comment]
Thanks for the report. Unfortunately, I can't replicate; e.g.:

```python
import numpy as np
import pandas as pd
import statsmodels.api as sm
dta = sm.datasets.macrodata.load_pandas().data
dta.index = pd.date_range(start='1959-01-01', end='2009-07-01', freq='QS')

mod = sm.tsa.SARIMAX(dta.infl.values, exog=np.ones_like(dta.infl), trend='t')
res = mod.filter([1, 1, 0.5, 1.])

i = 5
print(res.get_prediction(start=i, end=i, dynamic=1).predicted_mean[0])
print(res.get_prediction(start=i, end=i+1, dynamic=1).predicted_mean[0])
```

gives:

    6.655
    6.655

Is it possible that there's a minimal example that replicates the problem?

**Comment by vss888** [comment]
Sorry, we have found the reason of the difference on our side.

**Comment by ChadFulton** [comment]
Thanks for following up on this.
