### ISSUE TITLE
Restrict model parameters for exogenous inputs

### ISSUE THREAD

**Issue by Ekkerh** [statsmodels/statsmodels#5574]
Hi!

Is it possible to restrict a model parameter connected to an exogenous input? e.g. only positive values are allowed. The model in the attached picture is fitted with:

`mod = sm.tsa.SARIMAX(endog = endog, exog = exog, order=(1,0,0), seasonal_order=(1, 0, 0, 24)) # create SARIMAX-model`
`res = mod.fit(disp=False,maxiter=600,start_params=theta_history[0]) # fit model`

The estimated parameter connected to the first exogenous input in this example is -0.0033. Is it somehow possible to restrict the parameter outputs for example such that in this case only positive parameters are allowed?

![image](https://user-images.githubusercontent.com/44063833/56643121-a5346700-6681-11e9-8f92-12eca179b2a0.png)

**Comment by ChadFulton** [comment]
It is possible to do this by creating a subclass of `SARIMAX` and defining a new parameter transformation that forces a particular parameter to be positive. An example of requiring the first parameter to be positive is:

```python
class RestrictedSARIMAX(sm.tsa.SARIMAX):
    def transform_params(self, unconstrained):
        constrained = super(RestrictedSARIMAX, self).transform_params(unconstrained)
        constrained[0] = constrained[0]**2
        return constrained
    def untransform_params(self, constrained):
        unconstrained = super(RestrictedSARIMAX, self).untransform_params(constrained)
        unconstrained[0] = unconstrained[0]**0.5
        return unconstrained
```

As an example, the standard `SARIMAX` estimate for the first autoregressive parameter is negative:

```python
endog = sm.datasets.nile.load_pandas().data.diff().iloc[1:]

mod1 = sm.tsa.SARIMAX(endog, order=(1, 0, 0))
res1 = mod1.fit()
print(res1.params)
```

    ar.L1        -0.397537
    sigma2    23485.596586
    dtype: float64

Using the restricted class, we can force it to be positive:

```python
mod2 = RestrictedSARIMAX(endog, order=(1, 0, 0))
res2 = mod2.fit()
print(res2.params)
```

    ar.L1     4.527149e-09
    sigma2    2.799736e+04
    dtype: float64

But notice that basically the optimizer just set the constrained parameter to be as close to zero as possible while still being positive, and I imagine that is what would happen in your example also.

**Comment by Ekkerh** [comment]
Thank you very much!

**Comment by Ekkerh** [comment]
At first it seemed to work just fine but now I realised that sometimes when I am fitting the model, the estimated model parameters are "nan".

![image](https://user-images.githubusercontent.com/44063833/56786984-9d9ccb80-6803-11e9-90e6-d0ccf16874b8.png)

I am now restricting all the exogenous model parameters to positive values:
```
class RestrictedSARIMAX(sm.tsa.SARIMAX):
    def transform_params(self, unconstrained):
        constrained = super(RestrictedSARIMAX, self).transform_params(unconstrained)
        for i in range(0,n_inputs):
            constrained[i] = constrained[i]**2
        return constrained
    def untransform_params(self, constrained):
        unconstrained = super(RestrictedSARIMAX, self).untransform_params(constrained)
        for i in range(0,n_inputs):
            unconstrained[i] = unconstrained[i]**0.5
        return unconstrained
```

and then I fit the model:
```
mod = RestrictedSARIMAX(endog = endog, exog = exog, order=(1,0,0), seasonal_order=(1, 0, 0, 24)) # create SARIMAX-model
res = mod.fit(disp=False,maxiter=600,start_params=theta_history[0]) # fit model
```

It seems like the "nan" model parameters are due to the parameter restrictions since I have not had this problem before. As you may see, I am always using the model parameters from the previous fitting as the start parameters when fitting the model. May this be a contributing reason to why the estimated parameters are "nan" (parameters approaching zero)? Will it be problematic if there are several model parameters that are very close to zero? Would it be better to restrict the parameters not only to be positive but >epsilon?

**Comment by Ekkerh** [comment]
If it would be a solution to restrict the model parameters to >epsilon, how would it be done? Idid not quite understand what is happening in your example. Would this do the job?:
```
class RestrictedSARIMAX(sm.tsa.SARIMAX):
	def transform_params(self, unconstrained):
		constrained = super(RestrictedSARIMAX, self).transform_params(unconstrained)
		for i in range(0,n_inputs):
			constrained[i] = constrained[i]**2+epsilon
		return constrained
	def untransform_params(self, constrained):
		unconstrained = super(RestrictedSARIMAX, self).untransform_params(constrained)
		for i in range(0,n_inputs):
			unconstrained[i] = unconstrained[i]**0.5
		return unconstrained
```

Or woud one also have to modify the `untransform_params` function is some way?

**Comment by ChadFulton** [comment]
This is probably because `start_params` gives you negative starting values for the exog, which get "untransformed" into NaN when you take the square root.

In `untransform_params`, try replacing:

```python
        unconstrained[0] = unconstrained[0]**0.5
```

with:

```python
        unconstrained[0] = np.abs(unconstrained[0])**0.5
```

**Comment by Ekkerh** [comment]
Thank you!

It has now been runnin for some time and it seems like it is working well!
