### ISSUE TITLE
Just a Suggest 

### ISSUE THREAD

**Issue by lwsdegithub** [statsmodels/statsmodels#5575]
Hi, I suggest that the predict() function can predict a interval of y , provide a para, "95%","90", or others! 
Thank you!

**Comment by josef-pkt** [comment]
We decided to keep `predict` as a simple method, that doesn't do extra work and just returns an array or Series. when we want to do for example a cross-validation.

However, extra information like confidence intervals are available in the `get_prediction` method.

Confidence or prediction intervals are not available for all models, and the definition and options vary by model. The returns also depend on the model.

**Comment by sursu** [comment]
@josef-pkt, fair enough. 2 questions:

1. Does get_prediction output "confidence" and "prediction" intervals as does the [`predict`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/predict.lm.html) function in R?

2. What does the `what` argument do in `summary_frame([what, alpha])` used to summarize a `PreditictionResult`?

**Comment by josef-pkt** [comment]
`what` in summary_frame is not there anymore in current code.

closing
