### ISSUE TITLE
URLs containing https://www.statsmodels.org/dev/ return 404 file not found errors

### ISSUE THREAD

**Issue by nickpowersys** [statsmodels/statsmodels#5576]
The dev URLs appear in the first page of Google search results with enough frequency that there should be a non-negligible number of 404 errors occurring, based on Google site analytics or other tools.

It appears that all urls beginning with https://www.statsmodels.org/dev/ return 404's.

The URL https://www.statsmodels.org/dev/ itself returns a 404.

**Comment by nickpowersys** [comment]
As an example, in searching for

lagmat statsmodels

the top result is https://www.statsmodels.org/dev/generated/statsmodels.tsa.tsatools.lagmat.html

**Comment by thequackdaddy** [comment]
This will be fixed by #5322 ... sphinx had a change and crashed. The doctr run then just deleted all the documentation. 

I need to do some cleanup on #5322 and will focus on that later today/tonight. Then we can merge to fix this.

**Comment by nickpowersys** [comment]
That's good to know. This may be covered in that cleanup, but just for completeness, there are urls with "devel" instead of "dev" that appear in some places. I was using Duckduckgo, searched for "params arma statsmodels" and came across this URL that had a 404,

http://www.statsmodels.org/devel/generated/statsmodels.tsa.arima_model.ARIMA.html

**Comment by thequackdaddy** [comment]
I think this is fixed now. Closing.
