### ISSUE TITLE
Simple Exponential Smoothing : the optimized "alpha" is zero?

### ISSUE THREAD

**Issue by Michany** [statsmodels/statsmodels#5577]
Hi there.
When I was performing the *Simple Exponential Smoothing*, the optimized $\alpha$ is always zero.

It turns out that the *brute force* method to find the optimal $\alpha$ works. In my sample data it equals to 0.113166.
```
            # Have a quick look in the region for a good starting place for alpha etc.
            # using guestimates for the levels
            txi = xi & np.array(
                [True, True, True, False, False, True] + [False] * m)
            bounds = np.array([(0.0, 1.0), (0.0, 1.0), (0.0, 1.0),
                               (0.0, None), (0.0, None), (0.0, 1.0)] + [(None, None), ] * m)
            res = brute(func, bounds[txi], (txi, p, y, l, b, s, m, self.nobs, max_seen),
                        Ns=20, full_output=True, finish=None)
```

But after that, the program continues to search for an optima that is preciser:
```
                # Take a deeper look in the local minimum we are in to find the best
                # solution to parameters
                res = minimize(func, p[xi], args=(
                    xi, p, y, l, b, s, m, self.nobs, max_seen), bounds=bounds[xi])
```
After this step, the optimal $\alpha$ becomes zero.

Tried many times. Maybe something goes wrong with the inner process of the `scipy.optimize.minimize` function?

**Comment by bashtage** [comment]
Is the objective better at alpha=0?

**Comment by Michany** [comment]
Tks. Actually the optima should be 0.113166 by brute force method when I manually set Ns=200

I don't have any idea why `minimize()` function won't work. 

Anyway, I think under most circumstances the brute force method can provide a desired solution, in a short time. 
So... maybe brute force is fine for me~
