### ISSUE TITLE
NotImplementedError in MANOVA

### ISSUE THREAD

**Issue by mahyar-osn** [statsmodels/statsmodels#5578]
Hi there, 
I am trying to use the MANOVA on my data. From a stackoverflow page I realized this was recently implemented. 
However, when I try to fit my model, I receive the NotImplementedError. 
Any help would be appreciated.

An example of how I am using this class:

`a = np.random.randn(1000, 2)`
`b = np.random.randn(1000, 4)`
`manova = MANOVA(a, b)`
`manova.fit()`

And the error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hpc_htom/mosa004/zincvenv-py3/lib/python3.5/site-packages/statsmodels/base/model.py", line 194, in fit
    raise NotImplementedError
NotImplementedError

Many thanks.

**Comment by bashtage** [comment]
You don't fit, you just test. See the test code here for an example:

https://github.com/statsmodels/statsmodels/blob/4c601f679913428e6feca44402de38997c69e08b/statsmodels/multivariate/tests/test_manova.py#L28

**Comment by mahyar-osn** [comment]
Aha true! Great that makes sense now. Thanks!
