### ISSUE TITLE
Does SARIMAXResults.predict miss the exog?

### ISSUE THREAD

**Issue by xuruilong100** [statsmodels/statsmodels#5579]
The `SARIMAXResults.get_prediction` method can deal with `exog`, but in the `SARIMAXResults.predict` method, there is not `exog`.

**Comment by ChadFulton** [comment]
It is part of the kwargs for predict; you can still pass it in (and if your
model includes exog, then it will raise an exception if you don’t pass it
in).

**Comment by xuruilong100** [comment]
Thank You. `statsmodels` is nice!

**Comment by ChadFulton** [comment]
Thanks!
