### ISSUE TITLE
Escape error when exporting summary table of multiple OLS regressions to latex

### ISSUE THREAD

**Issue by jinhoffen** [statsmodels/statsmodels#5580]
I am trying to save the output of `summary_col` to a latex file. It should work with `as_latex`, but I am getting an escape error.

Minimal example:

	import pandas as pd
	import statsmodels.formula.api as smf
	from statsmodels.iolib.summary2 import summary_col
	x = [1, 3, 5, 6, 8, 3, 4, 5, 1, 3, 5, 6, 8, 3, 4, 5, 0, 1, 0, 1, 1, 4, 5, 7]
	y = [0, 1, 0, 1, 1, 4, 5, 7,0, 1, 0, 1, 1, 4, 5, 7,0, 1, 0, 1, 1, 4, 5, 7]
	d = { "x": pd.Series(x), "y": pd.Series(y)}
	df = pd.DataFrame(d)
	df['xsqr'] = df['x']**2  
	mod = smf.ols('y ~ x', data=df)
	res = mod.fit()
	print(res.summary())
	df['xcube'] = df['x']**3  

	mod2= smf.ols('y ~ x + xsqr', data=df)
	res2 = mod2.fit()
	print(res2.summary())

	mod3= smf.ols('y ~ x + xsqr + xcube', data=df)
	res3 = mod3.fit()
	print(res2.summary())

	dfoutput = summary_col([res,res2,res3],stars=True)
	print(dfoutput)
	print(dfoutput.as_latex())

The error output is:

	Traceback (most recent call last):
	  File "**/lib/python3.7/sre_parse.py", line 1021, in parse_template
	    this = chr(ESCAPES[this][1])
	KeyError: '\\m'

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "test.py", line 24, in <module>
	    print(dfoutput.as_latex())
	  File "**/lib/python3.7/site-packages/statsmodels/iolib/summary2.py", line 226, in as_latex
	    tab = re.sub(to_replace,'\midrule\n\midrule\n', tab)
	  File "**/lib/python3.7/re.py", line 192, in sub
	    return _compile(pattern, flags).sub(repl, string, count)
	  File "**/lib/python3.7/re.py", line 309, in _subx
	    template = _compile_repl(template, pattern)
	  File "**/lib/python3.7/re.py", line 300, in _compile_repl
	    return sre_parse.parse_template(repl, pattern)
	  File "**/lib/python3.7/sre_parse.py", line 1024, in parse_template
	    raise s.error('bad escape %s' % this, len(this))
	re.error: bad escape \m at position 0 (line 1, column 1)

I am using stats models 0.9.0 with python 3.7 on a Mac. Your help would be much appreciated.

**Comment by bashtage** [comment]
This is already fixed in master. You can either install master or wait until the next release.

**Comment by jinhoffen** [comment]
Thank you for your quick help.
