### ISSUE TITLE
Documentation build fails due to failed imports

### ISSUE THREAD

**Issue by EJEP** [statsmodels/statsmodels#5598]
#### Describe the bug

I have been trying to build the latest version of the documentation. When I run `make html` I get the following exception: `ImportError: cannot import name 'asunicode_nested' from 'statsmodels.compat.python'`. On looking in `statsmodels/compat/python.py` there is no such name. However `statsmodels/compat/__init__.py` attempts to import `asunicode_nested`.

#### Code Sample, a copy-pastable example if possible

Run `make html` in the `docs` directory.

#### Expected Output

The documentation to build without errors.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``sm.show_versions()`` here below this line]

```
>>> import statsmodels.api as sm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ejp/statsmodels/statsmodels/__init__.py", line 10, in <module>
    from statsmodels.tools.sm_exceptions import (ConvergenceWarning, CacheWriteWarning,
  File "/home/ejp/statsmodels/statsmodels/tools/__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "/home/ejp/statsmodels/statsmodels/tools/tools.py", line 4, in <module>
    from statsmodels.compat.python import reduce, lzip, lmap, asstr2, range, long
  File "/home/ejp/statsmodels/statsmodels/compat/__init__.py", line 1, in <module>
    from .python import (  # noqa:F401
ImportError: cannot import name 'asunicode_nested' from 'statsmodels.compat.python' (/home/ejp/statsmodels/statsmodels/compat/python.py)
```

</details>

**Comment by EJEP** [comment]
There are similar errors for `asbytes_nested`, `strchar`, `isfileobj`, `open_latin1`, `input`, `getexception`, `advance_iterator`, `callable`, `get_function_name`. Each was found by deleting the previous failed import from `statsmodels/compat/__init__.py`

**Comment by EJEP** [comment]
On removing these the documentation seems to build successfully.

**Comment by bashtage** [comment]
This is fixed in master.  Was a bug I introduced a few hours ago.

**Comment by EJEP** [comment]
I only forked the repository a few hours ago so I must have grabbed it after it broke but before the fix!

**Comment by EJEP** [comment]
The documentation build correctly now.
