### ISSUE TITLE
sm.GLM().fit().llf returns nan

### ISSUE THREAD

**Issue by amaeckelberghe** [statsmodels/statsmodels#5603]
#### Describe the bug

I'm trying to run some GLM models with a Binomial family. The fit() method is able to calculate the coefficients, but returns a nan values of Log-Likelihood (and therefore also for aic). I would like to perform my model selection based on the llf and aic values of the fitted models, but currently this is not possible. When googling for the issue I had the feeling this is an older issue that never has been fully completed, but maybe I don't have the full view on the topic:
* https://github.com/statsmodels/statsmodels/issues/42
* https://github.com/statsmodels/statsmodels/issues/3337

#### Code Sample
I'm using version 0.9.0 of statsmodels

```python
import statsmodels.api as sm

scotland = sm.datasets.scotland.load()
glm = sm.GLM(scotland.endog, scotland.exog, family=sm.families.Binomial())
results = glm.fit()
print(results.sumary())

```

#### Expected Output

I expected to see no error messages and see an llf value in the summary table of results.summary().

Instead:
```python
>>> results = glm.fit()
...\site-packages\statsmodels\genmod\families\family.py:880: RuntimeWarning: divide by zero encountered in true_divide
   n_endog_mu = self._clean((1. - endog) / (1. - mu))
>>> print(results.summary())
...\site-packages\statsmodels\genmod\families\family.py:932: RuntimeWarning: divide by zero encountered in true_divide
   special.gammaln(n - y + 1) + y * np.log(mu / (1 - mu)) +
...\site-packages\statsmodels\genmod\families\family.py:932: RuntimeWarning: invalid value encountered in add
   special.gammaln(n - y + 1) + y * np.log(mu / (1 - mu)) +
...\site-packages\statsmodels\genmod\families\family.py:933: RuntimeWarning: divide by zero encountered in log
   n * np.log(1 - mu)) * var_weights
...\site-packages\statsmodels\genmod\families\family.py:933: RuntimeWarning: invalid value encountered in add
   n * np.log(1 - mu)) * var_weights

```
It still returned the output table with the coefficients and everything, but the llf value is nan.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>
![statsmodels_error](https://user-images.githubusercontent.com/36659848/57068035-e6a3c280-6cd0-11e9-8d5f-71556fdc4ebb.PNG)

INSTALLED VERSIONS
------------------
Python: 3.7.3.final.0
Statsmodels

Installed: 0.9.0 (C:\Users\MaeckelbergheAH\AppData\Local\Programs\Python\Python37-32\lib\site-packages\statsmodels)
Required Dependencies

cython: Not installed
numpy: 1.16.3 (C:\Users\MaeckelbergheAH\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy)
scipy: 1.2.1 (C:\Users\MaeckelbergheAH\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy)
pandas: 0.24.2 (C:\Users\MaeckelbergheAH\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pandas)
    dateutil: 2.8.0 (C:\Users\MaeckelbergheAH\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dateutil)
patsy: 0.5.1 (C:\Users\MaeckelbergheAH\AppData\Local\Programs\Python\Python37-32\lib\site-packages\patsy)
Optional Dependencies

matplotlib: 3.0.3 (C:\Users\MaeckelbergheAH\AppData\Local\Programs\Python\Python37-32\lib\site-packages\matplotlib)
    backend: TkAgg 
cvxopt: Not installed
joblib: Not installed
Developer Tools

IPython: Not installed
    jinja2: 2.10.1 (C:\Users\MaeckelbergheAH\AppData\Local\Programs\Python\Python37-32\lib\site-packages\jinja2)
sphinx: 1.8.1 (C:\Users\MaeckelbergheAH\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sphinx)
    pygments: 2.3.1 (C:\Users\MaeckelbergheAH\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pygments)
nose: Not installed
pytest: Not installed
virtualenv: 16.5.0 (C:\Users\MaeckelbergheAH\AppData\Local\Programs\Python\Python37-32\lib\site-packages)

</details>

**Comment by kshedden** [comment]
scotland.endog is not binary, so it doesn't make sense to use logistic regression.

Just as an illustration, the following works

```
glm = sm.GLM(scotland.endog>60, scotland.exog, family=sm.families.Binomial())
```

**Comment by josef-pkt** [comment]
GLM and the binary models in discrete should work for continuous endog variables as long as they are in (0, 1) interval.

This is a valid Quasi-MLE.
But llf/loglike does not specify a correct likelihood in this case and cannot be used as such, e.g. for likelihood ratio tests. And we need to use robust cov_type like HC

**Comment by amaeckelberghe** [comment]
Thanks both and my apologies for raising this issue. I'm closing the issue now.
