### ISSUE TITLE
DOCS: parameters of same type are displayed incorrectly

### ISSUE THREAD

**Issue by EJEP** [statsmodels/statsmodels#5618]
#### Describe the bug

The documentation for function parameters of the same type are not displayed correctly. An example of the current documentation (for the function `ttest_ind`) is shown in this image:
![current_docs](https://user-images.githubusercontent.com/22224469/57181734-4647cc80-6e8f-11e9-8716-357234bf450a.png). 

There is a similar problem for other functions.

The expected documentation is shown in this image:
![expected_docs](https://user-images.githubusercontent.com/22224469/57181747-72634d80-6e8f-11e9-8aa7-e8e482eadf85.png)

The second argument is shown as the type in the first image.

The section of the docstring for the current documentation is 

```
x1, x2 : array_like, 1-D or 2-D
        two independent samples, see notes for 2-D case
```

If the space between `x1` and `x2` is removed then the expected documentation is generated.

The current format follows the numpy docstring standard so I expect the problem is somewhere in the generation of the html.

**Comment by bashtage** [comment]
x1 and x2 need to be on separate lines each with their own explanation.  I don't think what you want to possible. 

PR to fix welcome.
