### ISSUE TITLE
deprecation bug in statsmodels-0.9.0 when testing scipy-1.3.0rc

### ISSUE THREAD

**Issue by stonebig** [statsmodels/statsmodels#5619]
#### Describe the bug

scipy-1.3.0rc has removed a lot of old links in "scipy.misc".

example of no more supported code:
````
\statsmodels\distributions\edgeworth.py in <module>
      5 import numpy as np
      6 from numpy.polynomial.hermite_e import HermiteE
----> 7 from scipy.misc import factorial
      8 from scipy.stats import rv_continuous
      9 import scipy.special as special

ImportError: cannot import name 'factorial' from 'scipy.misc' (.....\python-3.7.3.amd64\lib\site-packages\scipy\misc\__init__.py)
````

It's solved in trunk since june 2018 https://github.com/statsmodels/statsmodels/commit/7e60df8ece46707e4795e2617106894bace65843#diff-80ca192493d5984b20fa9ad4e733185e

==> Could we have a new official release before scipy-1.3.0 is final ?

**Comment by bashtage** [comment]
This is fixed in master, and yes, a new release is far overdue. In the meantime, you can use master if you need to upgrade to 1. 3.0.

**Comment by bashtage** [comment]
The new release schedule needs an dedicated issue that isn't reporting a bug that has been fixed. You comment in #5406 to make the case for a new release.

**Comment by stonebig** [comment]
is "python setup.py bdist_wheel" enough on master ? do I nedd something to trigger a cython compilation ?

**Comment by bashtage** [comment]
Yes, that build extensions and then packages them.  You might need to ensure that cython, numpy, and scipy are installed before running this, although I think I fixed that in master too (so that you can install into an empty venv now).
