### ISSUE TITLE
Any model support partial_fit like sklearn?

### ISSUE THREAD

**Issue by pahome** [statsmodels/statsmodels#5624]
Dataset is huge now, so learning incrementally is very important for some users.

Is there any model supporting feature like partial_fit in sklearn?

thx

**Comment by kshedden** [comment]
We have this:

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/base/distributed_estimation.py

It has not been extensively used, tested, or documented.  Feedback is welcome.

**Comment by thequackdaddy** [comment]
Also of potential interest...

http://www.statsmodels.org/devel/large_data.html
