### ISSUE TITLE
Predictions for fitted AR-style models with new endogenous information

### ISSUE THREAD

**Issue by patricksheehan** [statsmodels/statsmodels#5665]
#### Is your feature request related to a problem? Please describe
I'm having trouble finding a concise way to generate predictions for a fitted SARIMAX-type model with new exogenous AND endogenous data.

Here's a concrete example:
- I make predictions every hour
- I'm able to retrain my models every day
- I get access to new endogenous information after every hour

#### Describe the solution you'd like
I'd like to be able to input an endogenous series in addition to the exogenous series I use for predictions between re-training of the model

#### Describe alternatives you've considered
I could in theory fit a model, pull the coefficients, and manually predict 1 step ahead with a model trained more steps backwards, but this seems like a good feature.

#### Additional context
The motivation is mostly for backtesting/cross-validation. Simulating the online-style environment requires frequent retraining which makes testing over many test periods quite computationally expensive

**Comment by patricksheehan** [comment]
Also if someone has a better intermediate solution that would be welcome!

**Comment by ChadFulton** [comment]
We recently added some new features to make this more convenient. Some examples are available here: https://www.statsmodels.org/devel/examples/notebooks/generated/statespace_forecasting.html

Based on the description here, I think this would be a case for the `extend` results method.
