### ISSUE TITLE
DEPR: Is sandbox.formula supplanted by patsy?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5688]
It doesn't import patsy, which makes me think (along other sandbox-related clues) that it was started before patsy was used, and is never going to be made usable.  @josef-pkt can you comment on this speculation?

If it can be removed, then sandbox.examples.ex_formula can be removed, along with a bunch of invalid-escapes in docstring'd-out code.

That would also put us on a path towards removing utils_old and contrast_old.

cc @bashtage

**Comment by josef-pkt** [comment]
formula handling is supplanted by patsy, it's the precursory version that was in `stats.models`.

But there are some extra functions that I never understood because I'm not a statistician, e.g. the check for estimability.

**Comment by jbrockmendel** [comment]
> But there are some extra functions that I never understood because I'm not a statistician, e.g. the check for estimability.

In sandbox.formula?  It isn't obvious which function(s) you're referring to.  (odds are very low of me understanding, but worth a shot)
