### ISSUE TITLE
User error: Accidental push

### ISSUE THREAD

**Issue by thequackdaddy** [statsmodels/statsmodels#5706]
I accidentally pushed something I wanted to test to master. Not sure the best approach to undo it. Sorry! I noticed from the macpython tests, xdist works very nicely on Mac so wanted to see if I could get that to work on our travis. 

Feel free to reset hard, or just add a commit to undo it. I'll try to be less stupid.

**Comment by josef-pkt** [comment]
Master should never be rebased or force pushed, unless it's a serious emergency.

Just make a new commit that reverts the change

**Comment by bashtage** [comment]
Not worth the pain. If it breaks will need another commit to revert the change. If it works, then it can stay in.

**Comment by bashtage** [comment]
We should protect sm master.

**Comment by thequackdaddy** [comment]
I agree. Sorry again.
