### ISSUE TITLE
DISC: Make `arch` usage "official"?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5718]
Going through old issues, ARCH/GARCH come up a lot, and in most of these the user is pointed towards the `arch` package. (#437, #1270, #5441)

Should that delegation be made "official" in some sense?  Among other things that would mean replacing sandbox.tsa.garch with a big note pointing users towards `arch`.

**Comment by bashtage** [comment]
I'm +1 on this.
