### ISSUE TITLE
Naming clarification: ex_foo.py vs try_foo.py?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5719]
@josef-pkt is there a meaningful distinction?

**Comment by josef-pkt** [comment]
yes, approximately
`try_foo` are usually when I'm starting out and have preliminary examples and investigation. 
`ex_foo` are at a later stage when I try to write a cleaner example, but usually still run into problems and need changes in the code.

That's just the general intention. Some try_xxx using existing code might be relatively clean to check a specific feature. Some ex_xxx might turn messy when I get side tracked or run into more serious problems

**Comment by jbrockmendel** [comment]
Thanks
