### ISSUE TITLE
numpydoc or napoleon 

### ISSUE THREAD

**Issue by thequackdaddy** [statsmodels/statsmodels#5725]
In the long, long ago, we quietly switched from using numpydoc to napoleon in #3473. 

Napoleon seems to be more forgiving than numpydoc. My attempt to revert to numpydoc required a few changes to the docstrings. But napolean seems to mess up some things... 

For example, the GLM docs the Attributes section is messed up. 

https://www.statsmodels.org/dev/generated/statsmodels.genmod.generalized_linear_model.GLM.html#statsmodels.genmod.generalized_linear_model.GLM

The Attributes section starts with `df_model`. Notice its all messed up. (There's a separate issue where the attributes section is listed twice in the actual docstring... but that's a separate issue. Removing the duplicate section results in the same messed-up formating). 

I reverted to using numpydoc, and I see some other problems. 

https://thequackdaddy.github.io/statsmodels.github.io/devel/generated/statsmodels.genmod.generalized_linear_model.GLM.html#statsmodels.genmod.generalized_linear_model.GLM

There "Methods" section is duplicated. 

In both versions, there is an Attributes section on the way bottom of the page that shows documentation for the attributes that are inherited. I can't find good examples on how this should work. I have no idea how to debug/fix this yet. 

So the million dollar questions...
1. Do we use numpydoc or napolean 
2. Anyone have any idea how to either fix the messed up "Attributes" section in napolean or the duplicated methods section in numpydoc?

**Comment by josef-pkt** [comment]
I didn't realize that we were not using numpydoc anymore.
Are numpy and scipy still using numpydoc?
I would prefer to stick with the original authors of the numpy doc style, but I have not really looked at the details for this in a long time.

In the original numpy doc version we avoided the Attributes section in the class docstring. Cached attributes were at the time not handled correctly in the autogenerated option for Attributes.

**Comment by bashtage** [comment]
napoleon seems to have an issue when a class has properties and an attribute section. It puts the properties in the attributes and turns the attributes into a dictionary.

**Comment by bashtage** [comment]
Both a somewhat buggy, marginally maintained pieces of code, so take your pick.
