### ISSUE TITLE
TST: is `pdf_output` ever used or likely to be used in the future?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5767]
Going through looking for incorrectly not-running tests, code that depends on `pdf_output` is presenting a bunch of false-positives.  If it isn't going to be used, it would be helpful to trim it.

**Comment by josef-pkt** [comment]
pdf_output is a developer tool to store the plots during testing.
mostly by Kerby, but I think also some other developers used pdf output for plots

The unit tests for plots are just smoke tests, so having a quick way to check whether plots **look right** is useful.

(in related unit testing: I once tried to use matplotlib testing tools that compare generated plots with saved plots, but don't remember if that used pdf or png. )

**Comment by jbrockmendel** [comment]
> I once tried to use matplotlib testing tools that compare generated plots with saved plots, but don't remember if that used pdf or png.

I've tried this too; IIRC it produced pngs.  Never really got it working to my satisfaction.  My attempt to spin a check-against-verified-image test function didn't pan out either.  This may just be A Hard Problem.
