### ISSUE TITLE
Add interpretations for different method in the doc of LogitResults.get_margeff

### ISSUE THREAD

**Issue by StevenLi-DS** [statsmodels/statsmodels#5811]
I suggest that we can add the interpretations for different `method` in the [doc](http://www.statsmodels.org/devel/generated/statsmodels.discrete.discrete_model.LogitResults.get_margeff.html#statsmodels.discrete.discrete_model.LogitResults.get_margeff) of `LogitResults.get_margeff`.

![Snipaste_196](https://user-images.githubusercontent.com/33796896/58669329-d26fd700-8309-11e9-9dc9-26afb1106e2b.png)

https://www.stata.com/manuals13/rmargins.pdf

**Comment by bashtage** [comment]
PRs welcome. Perhaps in Notes rather in the parameters docstring.

**Comment by StevenLi-DS** [comment]
@bashtage Would it be a good idea to add a new label like "PR Wanted" or something to the issues in case that folks want to contribute.

**Comment by jbrockmendel** [comment]
Thie label idea sounds like a good one.  Making it easier for would-be contributors to identify what is actionable would encourage more first-timers.

**Comment by joybhallaa** [comment]
Is anybody working on this?
Can I work on it?

**Comment by bashtage** [comment]
@joybhallaa Please do.

**Comment by joybhallaa** [comment]
@bashtage, @StevenLi-DS  , the link in the first comment is broken, and I can't find the documentation for `LogitResults.get_margeff`

**Comment by bashtage** [comment]
http://www.statsmodels.org/devel/generated/generated/statsmodels.discrete.discrete_model.LogitResults.get_margeff.html

**Comment by joybhallaa** [comment]
I'm sorry, I can't work on this issue as I am swamped with Univ & an internship.

**Comment by emilmirzayev** [comment]
@bashtage , I would like to take this one if it's free. 
I think maybe mentioning the effects in docstring and writing some additional notes as in STATA for further info

**Comment by bashtage** [comment]
Would you like me to assign it to you?

**Comment by emilmirzayev** [comment]
Please, go ahead
