### ISSUE TITLE
 'ARMAResults' object has no attribute 'get_forecast'

### ISSUE THREAD

**Issue by Doopies** [statsmodels/statsmodels#5813]
statsmodels      0.9.0

My code:
arma_mod80 = sm.tsa.ARMA(dta,(8,0)).fit()
x=arma_mod80.get_forecast(steps= 10,alpha =0.05)

Error message:
Traceback (most recent call last):
  File "C:/Users/qi.wang/PycharmProjects/forf/ex.py", line 34, in <module>
    x=arma_mod80.get_forecast(steps= 10,alpha =0.05)
  File "C:\Users\qi.wang\AppData\Local\Programs\Python\Python37\lib\site-packages\statsmodels\base\wrapper.py", line 35, in __getattribute__
    obj = getattr(results, attr)
AttributeError: 'ARMAResults' object has no attribute 'get_forecast'

**Comment by Doopies** [comment]
Python Version: 3.7.3

**Comment by bashtage** [comment]
Is it not just **forecast**, as in `x=arma_mod80.forecast(steps= 10,alpha =0.05)`

**Comment by bashtage** [comment]
See here: https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima_model.ARMAResults.forecast.html?highlight=forecast#statsmodels.tsa.arima_model.ARMAResults.forecast

**Comment by evelynLorca** [comment]
@Doopies how do you solve?
I'm having AttributeError: 'VARResults' object has no attribute 'get_forecast' error
I hope you can to share me a solution
