### ISSUE TITLE
DES: autolag option in diagnostic tests - accurate power/size?

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5817]
`stats.diagnostics.het_arch` (actually `sandbox.stats.diagnostic.het_arch`) has an option to provide `autolag` and choose the lag order to use via either AIC or BIC.  This option is not present in the R implementation FinTS:ArchTest that `het_arch` is tested against.  (The Matlab [docs](https://www.mathworks.com/help/econ/engles-arch-test.html) reference using an aic/bic to choose the lags)

The question: does using a IC to choose the lag order affect the distribution of the test statistic?  Intuitively it seems akin to running multiple tests.

There is one test in `test_diagnostic.test_het_arch2` that passes `autloag='aic'`.  That test looks OK assuming that conditioning on the results of the model selection does not affect the distribution of the test statistic.

**Comment by bashtage** [comment]
In principle lag length selection is a very bad idea when testing for
serial correlation. In large samples BIC will always select a model with 0
lags when the null is true. This is a bad feature. Other methods such as
AIC or tstat have a very high probability of selecting 0, although they
could select 1.

This is a misfeature and should be deprecated and then removed.

**Comment by josef-pkt** [comment]
AFAICS, the test has a lower bound of 1 lag when using AIC or BIC, i.e. best model with at least one lag.

If the Null is true, then having a small model sounds like  a good feature because it reduces the noise from many lags.

I don't remember why I added autolag option, but it's not the default.

**Comment by jbrockmendel** [comment]
> If the Null is true, then having a small model sounds like a good feature because it reduces the noise from many lags.

Sort of, but it also means you're running a much lower-powered test than you probably intend/expect.

> I don't remember why I added autolag option, but it's not the default.

It's still in the public API, and the docstring/docs incorrectly suggest that it has been verified against R results.

**Comment by josef-pkt** [comment]
Why do you think it has lower power?

The function has been verified against R, but not all options. You can rephrase.
In many cases we don't have the same options as other packages, and sometimes not the same default or small sample corrections. But the overlapping cases can still be verified.

**Comment by bashtage** [comment]
This is not a power issue it is a size issue. There is no way post model selection size will be correct using classical model selection with unmodified test statistics.

Should be deprecated and removed. This is nonstandard. Users can always do this if they really want it.

**Comment by bashtage** [comment]
This has been fixed.
