### ISSUE TITLE
DES/DISC: Params class for AR (and likely ARIMA)

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5822]
There are numerous long-standing problems coming from the fact that AR/ARIMA/VAR have trend and k_ar set in `fit` rather than in `__init__`.  The bug(s) I'm working on ATM have to do with retained state when `model.fit` is called with different parameters.

For the time being I'm assuming that changing the `__init__/fit` signatures is a non-starter.

The approach that would be most elegant (if it worked...) would be to make an ARMAParams class (similar to MixedLMParams).  This could subclass `np.ndarray` and would just need to provide the metadata `k_ar` and `k_trend` telling the model how to interpret the array that it sees.  So inside e.g. `AR._loglike_mle` instead of setting `k_ar = self.k_ar` it would set `k_ar = params.k_ar`.

The problem with this approach is that the scipy optimizer calls effectively `params = np.array(params)`, dropping this information before passing it to loglike/score/hessian.

Any other ideas?

**Comment by ChadFulton** [comment]
> The approach that would be most elegant (if it worked...) would be to make an ARMAParams class (similar to MixedLMParams).

I will have something like this very soon. However, what I have in mind won't solve the problems with the existing models that you're thinking about here. Still, you may want to wait for me to submit the WIP PR to think about this further.

**Comment by josef-pkt** [comment]
AFAIR Chad uses a params class in the statespace models. I suggested something similar would be useful for VAR.

I think subclassing numpy ndarray is just painful and should be avoided. `params` itself should stay just a plain array, or pandas Series on the user side.

What we need is the meta information about how the `params` array is converted to the internal model representation, i.e. the splitup into components for AR, MA, exog, deterministic, trend, ....

**Comment by jbrockmendel** [comment]
> Still, you may want to wait for me to submit the WIP PR to think about this further.

Sounds good.  No shortage of things to work on in the interim.

> I think subclassing numpy ndarray is just painful and should be avoided. params itself should stay just a plain array, or pandas Series on the user side.

I'm not married to subclassing `ndarray`; doing so is a workaround that lets us get further into the scipy optimizers before failing because it can be preserved under `np.asanyarray`.

> What we need is the meta information about how the params array is converted to the internal model representation, i.e. the splitup into components for AR, MA, exog, deterministic, trend, ....

Yep.  Attaching it to the params object directly doesn't work unless we can avoid having it clobbered by `params = np.array(params)`.

Attaching the metadata to the Model object (the status quo) works fine at the fit/loglike etc level, but fails at the Results level because the Model is mutated by additional fit calls.

We could add `k_trend`, `method` etc to the signatures of the relevant ARModel methods and have the Results object set self.method at `__init__` (ATM it references `self.model.method` within its own methods).  This can probably be made to work, but I'm still troubleshooting this approach.

If there is a viable way to get the metadata directly into `params` that would be nice since the params would be self-contained and self-descriptive.  But I've hit a wall on this.

Brainstorm: we could implement a `Model.copy()` method and instead of attaching the original to the ARResults object we could attach a copy (which in principle wouldn't be re-fit).

**Comment by josef-pkt** [comment]
> Attaching the metadata to the Model object (the status quo) works fine at the fit/loglike etc level, but fails at the Results level because the Model is mutated by additional fit calls.

params class doesn't help with having the wrong information in the model for fit arguments.
or that params class would blow up to contain a lot of model information.


> Brainstorm: we could implement a Model.copy() method and instead of attaching the original to the ARResults object we could attach a copy (which in principle wouldn't be re-fit).

too fragile if we don't make a deep copy and
memory consumption too large if we do make a deep copy

I struggle with recreating models in fit_constrained and similar, but there it is to create a new model with some changes made to the model. 
The `copy` method never went beyond the "just another idea" stage.

**Comment by jbrockmendel** [comment]
You've raised some objections to the ideas suggested so far.  Any other alternatives you want to propose?

**Comment by josef-pkt** [comment]
If it is still worth fixing AR/ARIMA given the new statespace, then the extra fit kwds that define state of the model need to go into `__init__`.
But that also needs a solution for the model/lag search that is currently implemented in those models.

I don't see how a params class would help for this.

Other fit kwds should not be part of the model state and be attached to the results instance, and possibly provided by the results instance when calling model methods.
e.g. we started to move `scale` in GLM to be an optional argument of the model methods.
In that case the state/attributes in the model is only relevant within fit, but not changed when fit is finished.

**Comment by jbrockmendel** [comment]
> then the extra fit kwds that define state of the model need to go into __init__.

This is the best solution internal-consistency-wise.  Would that be accepted? (assuming a decent solution to the next paragraph is identified)

> But that also needs a solution for the model/lag search that is currently implemented in those models.

Three options come to mind:
- keep model/lag search where they are, but have them return new Model objects (klunky, but maintains namespace)
- module-level functions for model/lag search (better scope-wise, but could be awkward if it requires passing a lot of args)
- a new class (ModelSelector?) that would be constructed similar to how AR/ARIMA/VAR are now (clearest separation of concerns for greenfield implementation, but it would be entirely new pattern within sm)

**Comment by josef-pkt** [comment]
I have no clear idea what the best way would be to do lag search in AR/ARMA/ARIMA.
Cleanest is a separate function or method that creates new model instances. But that might be computationally pretty inefficient in some cases.
We also have PRs from last years GSOC that did the model search for tsa. If that is available, then it might also be possible to deprecate the ic lag search.

I am cheating in GAM and use a way that is not supported for public usage but that avoids recreating models during the search for the best penalization weights, i.e. it has small computational overhead but uses a current implementation detail.

**Comment by ChadFulton** [comment]
See #5827 for some thoughts on this topic.
