### ISSUE TITLE
numerical derivative precision

### ISSUE THREAD

**Issue by argriffing** [statsmodels/statsmodels#583]
I found [this note](http://statsmodels.sourceforge.net/devel/examples/generated/example_gmle.html#numerical-precision) about numerical derivative precision in the statsmodels gmle example, so for fun I checked it with [automatic differentiation](http://en.wikipedia.org/wiki/Automatic_differentiation) using the development version of [algopy](https://github.com/b45ch1/algopy).

I found that the analytical derivatives agree with the statsmodels output rather than with the R output, so it is possible that in this case statsmodels is more accurate than R.  I'm not sure how to check it more carefully.

https://github.com/b45ch1/algopy/blob/master/documentation/sphinx/examples/neg_binom_regression.py
https://github.com/b45ch1/algopy/blob/master/documentation/sphinx/examples/neg_binom_regression.rst

**Comment by josef-pkt** [comment]
closing in favor of a newer issue on automatic differentiation #7500
