### ISSUE TITLE
FAQ: Only merge doc or bug fixes until 0.10.0 release

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#5840]
The second RC for 0.10.0 has been tagged, and so the master branch should only have essential fixes (bugs or doc) merged. Ideally, features and any other cleaning/maintenance should wait until after 0.10.0 is released (which I hope could be in a week or two). 

This request is driven by the release strategy: we now release from master and then branch maintenance/v0.10.0 after the initial release.

**Comment by thequackdaddy** [comment]
Here are some wheels...


[statsmodels-0.10.0rc2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl)
--
[statsmodels-0.10.0rc2-cp27-cp27mu-manylinux1_i686.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp27-cp27mu-manylinux1_i686.whl)
[statsmodels-0.10.0rc2-cp27-cp27mu-manylinux1_x86_64.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp27-cp27mu-manylinux1_x86_64.whl)
[statsmodels-0.10.0rc2-cp27-none-win32.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp27-none-win32.whl)
[statsmodels-0.10.0rc2-cp27-none-win_amd64.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp27-none-win_amd64.whl)
[statsmodels-0.10.0rc2-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl)
[statsmodels-0.10.0rc2-cp35-cp35m-manylinux1_i686.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp35-cp35m-manylinux1_i686.whl)
[statsmodels-0.10.0rc2-cp35-cp35m-manylinux1_x86_64.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp35-cp35m-manylinux1_x86_64.whl)
[statsmodels-0.10.0rc2-cp35-none-win32.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp35-none-win32.whl)
[statsmodels-0.10.0rc2-cp35-none-win_amd64.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp35-none-win_amd64.whl)
[statsmodels-0.10.0rc2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl)
[statsmodels-0.10.0rc2-cp36-cp36m-manylinux1_i686.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp36-cp36m-manylinux1_i686.whl)
[statsmodels-0.10.0rc2-cp36-cp36m-manylinux1_x86_64.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp36-cp36m-manylinux1_x86_64.whl)
[statsmodels-0.10.0rc2-cp36-none-win32.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp36-none-win32.whl)
[statsmodels-0.10.0rc2-cp36-none-win_amd64.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp36-none-win_amd64.whl)
[statsmodels-0.10.0rc2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl)
[statsmodels-0.10.0rc2-cp37-cp37m-manylinux1_x86_64.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp37-cp37m-manylinux1_x86_64.whl)
[statsmodels-0.10.0rc2-cp37-none-win32.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp37-none-win32.whl)
[statsmodels-0.10.0rc2-cp37-none-win_amd64.whl](https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/statsmodels-0.10.0rc2-cp37-none-win_amd64.whl)

**Comment by bashtage** [comment]
Thanks, uploaded now.

**Comment by bashtage** [comment]
Is the i686 py37 Linux missing or not built anymore?

**Comment by thequackdaddy** [comment]
I couldn't get pandas to build on i686 py37 for Linux. I gave up. I doubt that's a big demographic.

**Comment by bashtage** [comment]
Thanks. I suppose if you are on i686/37 and you can build pandas, then you can build statsmodels too.

**Comment by bashtage** [comment]
If there are no objections, I will finalize the release early next week.

**Comment by ChadFulton** [comment]
That sounds fantastic to me. Many thanks to you and everyone else for pushing this release forward.

**Comment by bashtage** [comment]
0.10.0 has been released.  Only sdist is on PyPI.  Wheels should follow in the next day or so.

@thequackdaddy Could you trigger a wheel build?

**Comment by bashtage** [comment]
I'm going to close this since it is no longer applicable.

**Comment by thequackdaddy** [comment]
@bashtage Wheels are here...

https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/

scroll down until you see the 0.10.0 ones. 

Looking through the docs [here](https://github.com/MacPython/statsmodels-wheels), [this script](https://github.com/MacPython/terryfy/blob/master/wheel-uploader) shoudl actually make this easy for you.

**Comment by bashtage** [comment]
Thanks. All up.
