### ISSUE TITLE
FAQ Installing the 0.10.0 release candidate

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#5845]
The second release candidate for 0.10.0 is available on PyPI. 

You can install it using

```
pip install --pre statsmodels==0.10.0rc2
```

This version works with the latest release of SciPy (1.3.0).

**Comment by PrimozGodec** [comment]
Hey. When do you plan to make a stable release? It is critical to have it in order to include statmodels to another package as a requirement. The previous version is not compatible with scipy=1.3.0.

**Comment by bashtage** [comment]
Next 48 hours

**Comment by PrimozGodec** [comment]
@badgley that is awesome. :)

**Comment by bashtage** [comment]
0.10.0 has been released.  Only sdist is on PyPI.  Wheels should follow in the next day or so.

**Comment by PrimozGodec** [comment]
That was fast thank you. :)
