### ISSUE TITLE
DOC: redundant/conflicting datasets readmes

### ISSUE THREAD

**Issue by jbrockmendel** [statsmodels/statsmodels#5855]
- datasets.README.txt is copied from an old scikit-learn.
- sandbox/dataset_notes.rst both references scikits.statsmodels and bzr
- docs/source/datasets/dataset_proposal.rst documenting a proposal accepted long long ago?
- docs/source/dev/dataset_notes.rst except for the exhortation to get permission in the sandbox version, this appears to dominate the other.

Can we get this down to a Single Source of Truth?

**Comment by bashtage** [comment]
docs/source/dev/dataset_notes.rst seems to be the dominant one, although there appears to be different information in docs/source/datasets/dataset_proposal.rst that should be incorporated into a single source.

**Comment by bashtage** [comment]
Happy if you want to take the best and make a single one.

**Comment by jbrockmendel** [comment]
will take a look.

BTW just rebased a handful of CLN PRs.  In particular 5692 would be great to get in so we can finally lint for invalid escapes
