### ISSUE TITLE
Issue with Roy's greatest root

### ISSUE THREAD

**Issue by jlevy44** [statsmodels/statsmodels#5862]
I'm getting this when running MANOVA:
```
results.loc["Roy's greatest root", 'Value'] = fn(eigv1.max())
  File "numpy/core/_methods.py", line 28, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation maximum which has no identity
```
Seems to be a numpy error? But not sure if there's a quick fix, or the option to just choose which manova tests to run. Thanks!
```
numpy==1.15.4
```

**Comment by bashtage** [comment]
Can you provide a self-contained example that produces this issue?

**Comment by jlevy44** [comment]
I think I may have switched the endogenous and exogenous variables.
