### ISSUE TITLE
Logit does not carry-over variable names from patsy when reporting

### ISSUE THREAD

**Issue by EdmundsEcho** [statsmodels/statsmodels#5864]
#### Describe the bug

[A clear and concise description of what the bug is. This should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Code Sample, a copy-pastable example if possible

```python
model = "t_included ~ "
model += "state + specialtyRollup01 + amag_sf_pre + sars_istarget + mcaid_low + mcaid_high "
model += "+ intra_only + intra_only_branded + decile_pre_intrarosa + decile_pre_branded + decile_pre_generic"

y, X = dmatrices(model, data=dw, return_type='dataframe')

mod = sm.Logit(y, X)                      # describe the model
res = logit_mod.fit(maxiter=1000)         # fit the model
print(res.summary())                      # view the summary
# Your code here

```
**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output
Summary with the name of the variables on the far left column.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

![Screen Shot 2019-06-11 at 4 37 00 PM](https://user-images.githubusercontent.com/11245417/59304923-2910d580-8c67-11e9-94a8-08709af92080.png)
<details>
[paste the output of ``sm.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
Python: 3.7.3.final.0
OS: Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

Statsmodels
===========

Installed: 0.9.0 (/Users/edmund/Documents/Lucivia/TKXS/AMAG-2018/TKXS/Notebooks-latest/env/lib/python3.7/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.16.4 (/Users/edmund/Documents/Lucivia/TKXS/AMAG-2018/TKXS/Notebooks-latest/env/lib/python3.7/site-packages/numpy)
scipy: 1.2.0 (/Users/edmund/Documents/Lucivia/TKXS/AMAG-2018/TKXS/Notebooks-latest/env/lib/python3.7/site-packages/scipy)
pandas: 0.24.2 (/Users/edmund/Documents/Lucivia/TKXS/AMAG-2018/TKXS/Notebooks-latest/env/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.0 (/Users/edmund/Documents/Lucivia/TKXS/AMAG-2018/TKXS/Notebooks-latest/env/lib/python3.7/site-packages/dateutil)
patsy: 0.5.1 (/Users/edmund/Documents/Lucivia/TKXS/AMAG-2018/TKXS/Notebooks-latest/env/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.1.0 (/Users/edmund/Documents/Lucivia/TKXS/AMAG-2018/TKXS/Notebooks-latest/env/lib/python3.7/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 0.13.2 (/Users/edmund/Documents/Lucivia/TKXS/AMAG-2018/TKXS/Notebooks-latest/env/lib/python3.7/site-packages/joblib)

Developer Tools
================

IPython: 7.5.0 (/Users/edmund/Documents/Lucivia/TKXS/AMAG-2018/TKXS/Notebooks-latest/env/lib/python3.7/site-packages/IPython)
    jinja2: 2.10.1 (/Users/edmund/Documents/Lucivia/TKXS/AMAG-2018/TKXS/Notebooks-latest/env/lib/python3.7/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.4.2 (/Users/edmund/Documents/Lucivia/TKXS/AMAG-2018/TKXS/Notebooks-latest/env/lib/python3.7/site-packages/pygments)
nose: Not installed
pytest: 4.6.3 (/Users/edmund/Documents/Lucivia/TKXS/AMAG-2018/TKXS/Notebooks-latest/env/lib/python3.7/site-packages)
virtualenv: Not installed
</details>

**Comment by bashtage** [comment]
What happens if you use `Logit.from_formula`

**Comment by EdmundsEcho** [comment]
Thank you bashtage -- you can close this issue; I had a typo in my model reference!
