### ISSUE TITLE
ExponentialSmoothing model predict return nan value

### ISSUE THREAD

**Issue by tianhao960** [statsmodels/statsmodels#5867]
#### Describe the bug

ExponentialSmoothing model predict method return nan forecast value, 
and done some debug ,found model.level, model.slope, model.season may contain nan/inf value that cause the forecast value is nan/inf.

#### Code Sample, a copy-pastable example if possible

```python
 # in holtwinters.py file:

        if seasonal == 'mul':
            for i in range(1, self.nobs + 1):
                l[i] = y_alpha[i - 1] / s[i - 1] + \
                    (alphac * trended(l[i - 1], dampen(b[i - 1], phi)))
                if trending:
                    b[i] = (beta * detrend(l[i], l[i - 1])) + \
                        (betac * dampen(b[i - 1], phi))
                s[i + m - 1] = y_gamma[i - 1] / \
                    trended(l[i - 1], dampen(b[i - 1], phi)) + \
                    (gammac * s[i - 1])

the detrend method will cause a 0/0, return nan
```

<details>

versin 0.9.0

</details>

**Comment by bashtage** [comment]
Can you provide a runnable example that will trigger this issue?  While it is helpful to see the relevant code, it is also useful to understand under what conditions this will be produced.

**Comment by tianhao960** [comment]
hi, bashtage:
below is an example which pred is nan:

data = [1.90163934,1.78688526,2.,1.88524592,1.81967211,1.88524592
        ,1.88524592,1.93442619,1.96721315,1.95081973,1.95081973,1.95081973
        ,1.90163934,1.93442619,1.80327868,1.83606553,1.91803276,2.04918027
        ,1.96721315,2.03278685,2.18032789,1.93442619,1.95081973,1.93442619
        ,1.98360658,2.03278685,2.31147552,2.03278685,1.95081973,2.19672132
        ,2.,2.40983605,2.32786894,2.08196711,2.13114762,2.16393447
        ,2.14754105,2.16393447,2.14754105,2.24590158,2.06557369,2.,2.
        ,2.06557369,1.93442619,2.,2.24590158,2.24590158,2.18032789
        ,2.26229501,2.42622948,2.01639342,1.96721315,2.04918027,2.29508185
        ,2.24590158,2.22950816,2.19672132,2.5573771,2.5573771,2.47540975
        ,2.4426229,2.37704921,2.34426236,2.09836054,2.06557369,1.98360658
        ,2.01639342,2.01639342,1.98360658,2.32786894,2.42622948,2.24590158
        ,2.18032789,2.19672132,2.13114762,2.09836054,2.27868843,2.50819683
        ,1.98360658,2.04918027,2.39344263,2.57377052,2.34426236,2.14754105
        ,2.42622948,2.24590158,2.31147552,2.39344263,2.19672132,2.13114762
        ,2.42622948,2.75409842,2.70491815,2.57377052,2.49180317,2.45901632
        ,2.31147552,2.5573771,2.60655737]
    #print data

    data_len = len(data)
    train_data = data[0:int(data_len * 0.8)]
    test_data = data[int(data_len * 0.8):]

    print 'train data size %s, test data size %s' % (len(train_data), len(test_data))


    period = 3

    model = ExponentialSmoothing(np.array(train_data), trend='mul', seasonal='mul', seasonal_periods=period).fit()

    pred = model.predict(start=len(train_data), end=len(train_data)+len(test_data))
    print pred

**Comment by tianhao960** [comment]
the output of the program:
train data size 80, test data size 20
/Users/wenbin/anaconda2/lib/python2.7/site-packages/statsmodels/tsa/holtwinters.py:185: RuntimeWarning: invalid value encountered in double_scalars
  b[i - 1]**phi)) + (gammac * s[i - 1])
/Users/wenbin/anaconda2/lib/python2.7/site-packages/statsmodels/tsa/holtwinters.py:185: RuntimeWarning: divide by zero encountered in double_scalars
  b[i - 1]**phi)) + (gammac * s[i - 1])
/Users/wenbin/anaconda2/lib/python2.7/site-packages/statsmodels/tsa/holtwinters.py:675: RuntimeWarning: invalid value encountered in double_scalars
  trended(l[i - 1], dampen(b[i - 1], phi)) + \
[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
  nan  nan  nan  nan  nan  nan]

**Comment by bashtage** [comment]
In master, this is what I get

```
pred
Out[13]: 
array([2.21473178, 2.15435914, 2.16705945, 2.22125391, 2.16070348,
       2.17344119, 2.22779525, 2.16706651, 2.17984173, 2.23435585,
       2.17344827, 2.18626111, 2.24093577, 2.17984883, 2.1926994 ,
       2.24753507, 2.18626823, 2.19915665, 2.2541538 , 2.19270654,
       2.20563291])
```

You should upgrade to master, or you can install the release candidate using `pip install --pre statsmodels==0.10.0rc2`

**Comment by tianhao960** [comment]
ok, I'll try the master, and by the way, do we consider provide a API which predict 1 step forward, and take the actual value to adjust the params, and predict next one, something like a auto regression. 
Thanks

**Comment by bashtage** [comment]
I that is probably best for userspace rather than internal.

**Comment by bashtage** [comment]
I'm going to close. It if you want to discuss an enhancement, it would be best it if was in its own thread.
