### ISSUE TITLE
 import statsmodels.tsa.api as smt not working in colab

### ISSUE THREAD

**Issue by KrShivendu** [statsmodels/statsmodels#5871]
####  import statsmodels.tsa.api as smt not working in colab

[Most of the scipy modules/functions are not getting imported in colab.]

#### import statsmodels.tsa.api

```python
import statsmodels.tsa.api

```

#### Expected Output
Import of stastmodels api should be successful
#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``sm.show_versions()`` here below this line]
---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

<ipython-input-63-411ef5239fad> in <module>()
----> 1 import statsmodels.api as sm; sm.show_versions()

3 frames

/usr/local/lib/python3.6/dist-packages/statsmodels/distributions/edgeworth.py in <module>()
      5 import numpy as np
      6 from numpy.polynomial.hermite_e import HermiteE
----> 7 from scipy.misc import factorial
      8 from scipy.stats import rv_continuous
      9 import scipy.special as special

ImportError: cannot import name 'factorial'

</details>

**Comment by bashtage** [comment]
See #5759
