### ISSUE TITLE
plot_partregress_grid function has a bug when use gird

### ISSUE THREAD

**Issue by yoongu0929** [statsmodels/statsmodels#5873]
#### Describe the bug
when I use grid param as 
**sm.graphics.plot_partregress_grid(result_wine, grid=(5,4), fig=fig)**
error occurs as 
"local variable 'title_kwargs' referenced before assignment"

so I looked up the code plot_partregress_grid function
```python
if grid is not None:
        nrows, ncols = grid
    else:
        if len(exog_idx) > 2:
            nrows = int(np.ceil(len(exog_idx)/2.))
            ncols = 2
            title_kwargs = {"fontdict" : {"fontsize" : 'small'}}
        else:
            nrows = len(exog_idx)
            ncols = 1
            title_kwargs = {}
```
if I put grid, the "title_kwargs" does not initialized.
so at the bottom, when plot_partregress called, it occurs error

#### Code Sample, a copy-pastable example if possible

```python
if grid is not None:
        nrows, ncols = grid
        title_kwargs = {"fontdict" : {"fontsize" : 'small'}}
    else:
        if len(exog_idx) > 2:
            nrows = int(np.ceil(len(exog_idx)/2.))
            ncols = 2
            title_kwargs = {"fontdict" : {"fontsize" : 'small'}}
        else:
            nrows = len(exog_idx)
            ncols = 1
            title_kwargs = {}

```
**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``sm.show_versions()`` here below this line]

</details>

**Comment by bashtage** [comment]
Happy to accept a PR if you want to write one. If not, could you provide an example that shows the function being called that raises? This makes it easier to see the issue.

**Comment by yoongu0929** [comment]
Hi, 
So  i called 
sm.graphics.plot_partregress_grid(result_wine, grid=(5,4), fig=fig)
to see more plots in one row.(default is 2),

model_wine = sm.OLS(y, X)
result_wine = model_wine.fit()

this is the data i put into sm.graphics.plot_partregress_grid function.

Thank you.

**Comment by bashtage** [comment]
Could you make a self-contained example, ideally one that uses simulated data so that it can be copied and pasted to produce the bug?

**Comment by yoongu0929** [comment]
So This is the sample code that produce the bug

```
from sklearn.datasets import load_boston
import statsmodels.api as sm

boston = load_boston()

dfX0 = pd.DataFrame(boston.data, columns=boston.feature_names)
dfX = sm.add_constant(dfX0)
dfy = pd.DataFrame(boston.target, columns=["MEDV"])
df = pd.concat([dfX, dfy], axis=1)

model_boston = sm.OLS(dfy, dfX)
result_boston = model_boston.fit()

fig = plt.figure(figsize=(8, 20))
sm.graphics.plot_partregress_grid(result_boston, grid=(5,4), fig=fig)
fig.suptitle("")
plt.show()
```

I attached code in below

Thank you,
