### ISSUE TITLE
Forecasting with tsa.MarkovRegression in order to compute Value-at-Risk

### ISSUE THREAD

**Issue by dimcarien** [statsmodels/statsmodels#5874]
Hi ChadFulton,

I tried to do a forecasting/prediction with tsa.MarkovRegression, and I read your code:
`def predict(self, params, start=None, end=None, probabilities=None, conditional=False)`

I'm aim at computing Value-at-Risk. Can you help me to fix my code below please?
```
dta_kns = ret-mu
dta_kns.plot()
mod_kns = sm.tsa.MarkovRegression(dta_kns, k_regimes=3, trend='nc', switching_variance=True)
res_kns = mod_kns.fit()
print(res_kns.summary())
q_kns = mod_kns.distribution.ppf([0.05])
forecasts_kns = res_kns.predict()
cond_mean_kns = forecasts_kns.mean
cond_var_kns = forecasts_kns.var
value_at_risk_kns = - cond_mean_kns.values - np.sqrt(cond_var_kns).values * q_kns[None, :]
print("value_at_risk_kns =",value_at_risk_kns)
```
1st question: is there any distribution asumption for Markov Regime Switching GARCH?
2nd question: how can I compute the left quantile?

Thanks for reading me

**Comment by dimcarien** [comment]
> Hi ChadFulton,
> 
> I tried to do a forecasting/prediction, and I read your code:
> `def predict(self, params, start=None, end=None, probabilities=None, conditional=False)`
> 
> I'm aim at computing Value-at-Risk. Can you help me to fix my code below please?
> 
> ```
> dta_kns = ret-mu
> dta_kns.plot()
> mod_kns = sm.tsa.MarkovRegression(dta_kns, k_regimes=3, trend='nc', switching_variance=True)
> res_kns = mod_kns.fit()
> print(res_kns.summary())
> q_kns = mod_kns.distribution.ppf([0.05])
> forecasts_kns = res_kns.predict()
> cond_mean_kns = forecasts_kns.mean
> cond_var_kns = forecasts_kns.var
> value_at_risk_kns = - cond_mean_kns.values - np.sqrt(cond_var_kns).values * q_kns[None, :]
> print("value_at_risk_kns =",value_at_risk_kns)
> ```
> 
> 1st question: is there any distribution asumption for Markov Regime Switching GARCH?
> 2nd question: how can I compute the left quantile?
> 
> Thanks for reading me

**Comment by bashtage** [comment]
This most if not a MS Garch.  It is a MS Regression -- that is, a OLS with state-dependent parameters.
