### ISSUE TITLE
unhandled 0 division in the denominator, line275 in robust_linear_model.py

### ISSUE THREAD

**Issue by jasonlocal** [statsmodels/statsmodels#5878]
#### Describe the bug

[A clear and concise description of what the bug is. This should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Code Sample, a copy-pastable example if possible

```python
# Your code here that produces the bug
# This example should be self-contained, and so not rely on external data.
# It should run in a fresh ipython session, and so include all relevant imports.
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

</details>

**Comment by jasonlocal** [comment]
Describe the bug: 
In robust_linear_model.py, there is unhandled zero division on line 275, I've noticed that if I pass in a DataFrame with perfect linear model fit with 0 residual, then the program hangs and never finishes.

See the following for my example DataFrame(['FCFSales', 'const']being endogenous, ['BNRMTE02] being exdogenous ) 

         FCFSales     const    BNRMTE02
1       -0.217126      1.0      -498.484443
2       NaN              1.0       42.849964
3     -0.217126      1.0     -331.402878
4    -0.217126       1.0      88.030700
5       NaN             1.0       315.760558
6    -0.217126      1.0       -81.354436
7    -0.217126      1.0      -73.195943
8     NaN              1.0     -105.151041
9     -0.217126    1.0      1.082872
10     NaN            1.0    -100.000000


The program hangs with error message:
/NImounts/NiNoSnapDev/medusa_egg_cache/27-3/s/statsmodels-0.8.0-py2.7-linux-x86_64.egg/statsmodels/robust/robust_linear_model.py:284: RuntimeWarning: divide by zero encountered in divide
  self.weights = self.M.weights(wls_results.resid/self.scale)
/NImounts/NiNoSnapDev/medusa_egg_cache/27-3/s/statsmodels-0.8.0-py2.7-linux-x86_64.egg/statsmodels/robust/norms.py:190: RuntimeWarning: invalid value encountered in less_equal
  return np.less_equal(np.fabs(z), self.t)

**Comment by bashtage** [comment]
FWIW You can edit posts, so could you edit the first one and use the code block (which is demarkated with triple ticks)?

Kevin
