### ISSUE TITLE
slow install from pypi

### ISSUE THREAD

**Issue by csweaver** [statsmodels/statsmodels#5882]
#### Describe the bug

Installation of version 0.10.0 from pip takes > 2 minutes (significantly longer than previous versions which were on the order of seconds). 

Both on python version 3.6 and 3.7. This is on Mac OSX v 10.14.5 in a fresh python venv. 
#### Code Sample, a copy-pastable example if possible

```bash
pip install statsmodels # takes > 2 min
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

Installing from pip should take on the order of seconds, like previous versions.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
Python: 3.7.1.final.0
OS: Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: None

Statsmodels
===========

Installed: 0.10.0 (/Users/charlotteweaver/Documents/Git/cellxgene/hjsh/lib/python3.7/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.16.4 (/Users/charlotteweaver/Documents/Git/cellxgene/hjsh/lib/python3.7/site-packages/numpy)
scipy: 1.3.0 (/Users/charlotteweaver/Documents/Git/cellxgene/hjsh/lib/python3.7/site-packages/scipy)
pandas: 0.24.2 (/Users/charlotteweaver/Documents/Git/cellxgene/hjsh/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.0 (/Users/charlotteweaver/Documents/Git/cellxgene/hjsh/lib/python3.7/site-packages/dateutil)
patsy: 0.5.1 (/Users/charlotteweaver/Documents/Git/cellxgene/hjsh/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: Not installed
cvxopt: Not installed
joblib: Not installed

Developer Tools
================

IPython: Not installed
    jinja2: Not installed
sphinx: Not installed
    pygments: Not installed
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by csweaver** [comment]
0.10.0rc2 installs quickly too, this is only an issue with 0.10.0

**Comment by bashtage** [comment]
There are no wheels available.  These will be made available in the next 24
hours.

**Comment by bashtage** [comment]
Wheels are available for OSX, Linux and Windows (3.x to follow soon)

**Comment by csweaver** [comment]
Thanks! Guess I was too quick on the draw.
