### ISSUE TITLE
ENH: Out of Sample Prediction with statespace

### ISSUE THREAD

**Issue by mdfrench84** [statsmodels/statsmodels#5885]
I've estimated an ARIMA model on a training period using statespace.  For each day in my out of sample data, I'd like to produce forecasts for each of the h subsequent time steps.

I've adapted the following example:
[https://nbviewer.jupyter.org/gist/ChadFulton/d744368336ef4bd02eadcea8606905b5](url)

Is the only way to create rolling, multi-step forecasts to:
1) define a new model with the new data
2) initialize it with the state from the fitted model
3) inserting the parameters fitted on the training set
4) produce the forecast 

Are these still the correct steps to backtest model accuracy? Or does there exist a more elegant solution?  My implementation of those steps are below.

```python
mod = sm.tsa.statespace.SARIMAX(df.loc[df.balancedate <= oos_split_date][endo_var],
                                exog = df.loc[df.balancedate <= oos_split_date][exo_vars],
                                order=order,
                                trend = 'n',
                                enforce_stationarity=False,
                                enforce_invertibility=False,
                                time_varying_regression = False,
                                mle_regression = True)

training_res = mod.fit()

h=7
oos_split_date = date(x,y,z)

for i in range(1, len(test.date)):
    run_date = oos_split_date + timedelta(i)
    hist = df.loc[df.date < run_date]
    endog_hist = hist[endo_var]
    exog_hist = hist[exo_vars]
    exog_fut = df[(df.date >= run_date) & (df.date < run_date)][exo_vars]
    
    mod = sm.tsa.statespace.SARIMAX(endog_hist, exog=exog_hist, order=order,
                                    #seasonal_order=seasonal_order,
                                    trend = 'n',
                                    time_varying_regression = False,
                                    mle_regression = True)
    mod.initialize_known(training_res.predicted_state[:, -2], training_res.predicted_state_cov[:, :, -2])
    res = mod.filter(training_res.params)

    temp = pd.DataFrame()
    temp['yhat'] = res.get_forecast(steps = h, exog = exog_fut).predicted_mean
    temp['run_date'] = run_date
    temp['horizon'] = [i for i in range(0,h)]
    preds = pd.concat([preds, temp], axis = 0)
```

**Comment by ChadFulton** [comment]
Yes, that looks like the best that can be done right now. It is on our list of priorities to get a better solution for this kind of application, but unfortunately nothing is available so far.

**Comment by ChadFulton** [comment]
Closing the issue, since I think the answer has been given, but feel free to continue posting if you have other questions about this issue.
