### ISSUE TITLE
acorr_breusch_godfrey Value Error

### ISSUE THREAD

**Issue by monstrorivas** [statsmodels/statsmodels#5886]
When using statsmodels.stats.diagnostic.acorr_breusch_godfrey and passing a Results instance. I am getting the following ValueError

```
in acorr_breusch_godfrey(results, nlags, store)
    499         nlags = int(nlags)
    500
--> 501     x = np.concatenate((np.zeros(nlags), x))
    502
    503     #xdiff = np.diff(x)

ValueError: all the input arrays must have same number of dimensions
```

Looking at the error it looks like a bug to me, since the nlags will most likely be different than the length of the x (the residuals from the results instance). Thus, input arrays don't have the same number of dimensions

**Comment by josef-pkt** [comment]
which model are you using, which results class?
What's the dimension of your x?

AFAIR, x should be 1-dim, and then concatenates without problems with a 1-dim `np.zeros(nlags)`.

**Comment by monstrorivas** [comment]
I am using `statsmodels.tsa.api.VAR` to create my model.
```
from statsmodels.tsa.api import VAR
model = VAR(df)
results = model.fit(ic='bic')
```
x has the dimension of the dataframe which is multivariate.

Based on the comment above, it looks like I'm probably not passing the correct results instance. What class should I use?

**Comment by josef-pkt** [comment]
diagnositc functions like statsmodels.stats.diagnostic.acorr_breusch_godfrey where written for the univariate endog case.
VAR and similar are multivariate. We only have the diagnostics in tsa vector_ar and in statespace for those.

AFAIR, I never looked at a multivariate extension of acorr_breusch_godfrey, but don't remember if there is something similar already in tsa for the multivariate case

**Comment by josef-pkt** [comment]
A quick google search shows that there is a literature for breush godfrey for VAR with implementation in R
https://stats.stackexchange.com/questions/301225/breusch-godfrey-lm-test-returning-different-results-in-vars-and-lmtest

for VAR we have https://www.statsmodels.org/dev/generated/statsmodels.tsa.vector_ar.var_model.VARResults.test_whiteness.html

**Comment by monstrorivas** [comment]
I took a stab at implementing the breush godfrey test for VAR in python (using statsmodels VAR). If interested I can share for integration into statsmodels

**Comment by bashtage** [comment]
Well tested PRs are always welcome
