### ISSUE TITLE
Incorrect result of robust location estimator "Hampel"

### ISSUE THREAD

**Issue by hippke** [statsmodels/statsmodels#5887]
#### Describe the bug

When estimating the robust Hampel location parameter in 1D data, I get two different results from two statsmodels APIs. Both should be identical.

#### Code to reproduce:

```python
import numpy as np
from statsmodels.robust.norms import estimate_location, Hampel
from statsmodels.api import RLM

data = [1, 1.1, 1.2, 1.3, 5, 10]
flat = np.ones(len(data))
norm = Hampel(a=1.7, b=3.4, c=8.5)

loc1 = estimate_location(data, scale=flat, norm=norm)
print(loc1, 'estimate_location')
loc2 = RLM(data, flat, M=norm).fit().params[0]
print(loc2, 'RLM')
```
#### Output
1.5799996777966925 estimate_location
2.8043320475468114 RLM

#### Expected Output
Both results should be identical. The number of iteration is not the cause for this, which I have checked with any number of integer iterations until convergence (here: 9 iter for 1e-6 tol).

**Comment by josef-pkt** [comment]
my quick guess is that the scale is different in the two cases and so they don't estimate the same model.

RLM always estimates the scale. It might be possible to replicate the RLM result with `estimate_location` if the same (RLM results) scale is used.

**Comment by josef-pkt** [comment]
in contrast to OLS, the estimates of the mean parameters change with varying scale in RLM.
