### ISSUE TITLE
Add namedtuple like arrays to OLS/WLS/GLS diagnostics

### ISSUE THREAD

**Issue by pacificgilly1992** [statsmodels/statsmodels#5888]
The results from the fit functions of OLS/WLS/GLS classes are given as a numpy array (e.g. `pvalues`). I would find this helpful if the output was given as a namedtuple, or some other array_like structure, which could be indexed with a string. 

This should be easily implemented and is backwards compatible as integer indexing is also supported using namedtuples.

Using `pvalues` as an example and assuming a linear regression model with endog and exog being 1D numpy arrays, we can get the output as so:

`sms.fit.pvalues(x1=<x1_pvalue>, const=<const_pvalue>)`

The names in the namedtuple (e.g. x1, const) can be changed to be consistent with the names given to fitting classes.

Overall, this would make it easy to get the statistical diagnostics relating to the correct dimension more easily, rather than having to check manually each time.

**Comment by josef-pkt** [comment]
If you use pandas for the data, specifically exog, then the returned results are pandas Series that can be indexed by the name. 

If you use numpy arrays for the data, then there is no information about names of explanatory variables.

AFAIK, named tuples would not be useful because you cannot simply use numpy to do followup computations with it, e.g. even a simple `significant = results.pvalues < 0.05` wouldn't work.

**Comment by pacificgilly1992** [comment]
I didn't realise that pandas would do the same thing as what I mentioned. That's very good to know!

For numpy arrays, couldn't you just use the standard names, like `const`, `x1`, `x2`, etc. Thats the name you see in `results.summary()`. Or even use numpy record array?

**Comment by josef-pkt** [comment]
numpy recarrays are on the way out for data handling, pandas and similar works much better.
We still have some support for recarrays from before pandas became popular, but that support will be removed soon(ish).

Essentially we and most data handling in python converged on pandas or pandas compatible structures as the main tool for this. So, there is not much point in adding or keeping some additional messy structures.

**Comment by bashtage** [comment]
Going to close since the only possible path would be to use pandas for all outputs, but I don't think this is feasible now.
