### ISSUE TITLE
MAINT: Update dependencies.

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#5890]
Our [dependencies policy](https://www.statsmodels.org/stable/install.html#dependencies) is to keep dependencies lagged about 1.5 - 2 years. Now that 0.10 is out, this means we should update our dependencies, since we're about 3 years out right now.

Happy to make a PR once agreement is achieved.

Options for increased dependencies:

- Numpy: 1.13 (June 2017) or 1.14 (Jan 2018)
- Scipy: 0.19 (June 2017) or 1.0.0 (October 2017)
- Pandas: 0.20 (May 2017) or 0.21 (October 2017)
- Cython: 0.26 (July 2017) or 0.27 (September 2017)

I lean towards the later options for Scipy, Pandas, and Cython, and I'm ambivalent between the two Numpy options.

I don't have a lot of experience with the Patsy use. 0.5.0 was released in January 2018, the first release in 3 years. Maybe someone else can suggest whether this would be worthwhile pushing up our minimum to.

**Comment by ChadFulton** [comment]
A couple of things I forgot to mention:

I guess when we do update the official dependencies, we should also update what we're testing against to drop out the now-obsolete dependencies. I can do that in the PR.

Also, I think we should update our Python 3 dependency to Python 3.5 (currently 3.4). It's not written in our policy in the dependencies section, but I believe that we had been planning to make this change after the 0.10 release. The only question is whether core contributors are still working in Python 3.4. I think I remember that you might have been, @josef-pkt. Would this be okay?

**Comment by Juanlu001** [comment]
Regarding patsy:

> unfortunately patsy has been essentially unmaintained for years now

https://github.com/pydata/patsy/issues/149#issuecomment-501162870

**Comment by bashtage** [comment]
I've seen that. As long as it ain't broken then it can stay external. It
mostly means no new features.

**Comment by bashtage** [comment]
These are in master now.
