### ISSUE TITLE
x13 Support for Weekly Frequency

### ISSUE THREAD

**Issue by hcars** [statsmodels/statsmodels#5900]
#### Is your feature request related to a problem? Please describe
While using the x13 library to do auto.arima, I ran into a problem where the statsmodel code would crash for my series's weekly frequency.

#### Describe the solution you'd like
I would like support for weekly time series in the x13 library.

#### Describe alternatives you've considered
There weren't good alternatives to do auto arima with statsmodels besides porting this portion of our project over to R.

#### Additional context
Sorry for forgetting to fill out my last template.

**Comment by bashtage** [comment]
Can you provide a simple example using simulated data that produces the crash?

**Comment by ChadFulton** [comment]
X13 itself does not support data at a weekly frequency, so it seems
unlikely that there will be a fix here (and unlikely that moving to R would
help if you are still planning to use X13). But maybe I’ve misunderstood
what you’re wanting to do.

**Comment by hcars** [comment]
I see, thank you, Chad.
