### ISSUE TITLE
OLS.fit_regularized() keyword arguments are overridden 

### ISSUE THREAD

**Issue by quantvol** [statsmodels/statsmodels#5902]
It appears kwargs specified by the user in OLS.fit_regularized() get overridden by the defaults here:

https://github.com/statsmodels/statsmodels/blob/ae3c9133de222f200f11ee3e38de3bb7d93772fd/statsmodels/regression/linear_model.py#L994

Thanks!

**Comment by kshedden** [comment]
Yes, it should be defaults.update(kwargs).  I will fix it now.
