### ISSUE TITLE
Off-by-one error / loose dtype checking in KPSS statistic

### ISSUE THREAD

**Issue by timstaley** [statsmodels/statsmodels#5925]
#### Describe the bug

Arguably the KPSS code has a couple of issues. Firstly, there's no check whether the input array has suitable dtype, which can result in some weird error messages.
Second, I _think_ there's an off-by-one error in the internal function `_sigma_est_kpss`, but it only actually causes an exception in a weird edge-case highlighted by the object dtype.

(If you look at the indexing here:
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/stattools.py#L1733
Then you'll see that in the edge case `nobs==lags`, and for the last iteration in the loop we are computing `np.dot` on two empty arrays. The return value in this case is dtype dependent, it defaults to 0 for anything numeric, but if it happens to be an object-array we get None and the line of maths below breaks.)

NB, I don't have access to Kwiatkowski et al. (1992), so can't verify the original equation for myself.

#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
from statsmodels.tsa.stattools import kpss

# Confusing error one:
boring_data = np.full(20, 0).astype(object)
kpss(boring_data, lags="auto")

# Confusing error two, hits possible off-by-one error in _sigma_est_kpss:
weird_data = array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0])

kpss(weird_data.astype(object), lags="auto")

```

Both those kpss calls result in an exception.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.6.5.final.0
OS: Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

Statsmodels
===========

Installed: 0.10.0 (/home/staley/.virtualenvs/snippets/lib/python3.6/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.14.3 (/home/staley/.virtualenvs/snippets/lib/python3.6/site-packages/numpy)
scipy: 1.1.0 (/home/staley/.virtualenvs/snippets/lib/python3.6/site-packages/scipy)
pandas: 0.21.0 (/home/staley/.virtualenvs/snippets/lib/python3.6/site-packages/pandas)
    dateutil: 2.7.2 (/home/staley/.virtualenvs/snippets/lib/python3.6/site-packages/dateutil)
patsy: 0.5.1 (/home/staley/.virtualenvs/snippets/lib/python3.6/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 2.2.2 (/home/staley/.virtualenvs/snippets/lib/python3.6/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: Not installed

Developer Tools
================

IPython: 6.3.1 (/home/staley/.virtualenvs/snippets/lib/python3.6/site-packages/IPython)
    jinja2: 2.10 (/home/staley/.virtualenvs/snippets/lib/python3.6/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.2.0 (/home/staley/.virtualenvs/snippets/lib/python3.6/site-packages/pygments)
pytest: Not installed
virtualenv: 16.0.0 (/home/staley/.virtualenvs/snippets/lib/python3.6/site-packages)

</details>

**Comment by bashtage** [comment]
> (If you look at the indexing here:
> https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/stattools.py#L1733
> Then you'll see that in the edge case `nobs==lags`, and for the last iteration in the loop we are computing `np.dot` on two empty arrays. The return value in this case is dtype dependent, it defaults to 0 for anything numeric, but if it happens to be an object-array we get None and the line of maths below breaks.)

The bug is the missing limit on `lags` that makes sure it is smaller than nobs.  The code is correct for a Newey-West estimator.
