### ISSUE TITLE
could not find a version that satisfies the requirement statsmodels

### ISSUE THREAD

**Issue by mujdeayik** [statsmodels/statsmodels#5955]
I have got Python 3.7 64 bit. And have downloaded the statsmodels package from github. Using command window I am trying to install the statsmodels package from the directory where I have downloaded (D:/pipdir/statsmodels-master). 

c:\users...>python -m pip install --no-index --find-links="D:/pipdir/statsmodels-master"" --user statsmodels

Then I have the error: Could not find a version that satisfies the requirement statsmodels (from versions :) 

Could anyone suggest a solution please?

**Comment by bashtage** [comment]
If you have a clones repo, just

```
cd D:/pipdir/statsmodels-master
python setup.py install
```

```
cd D:/pipdir/statsmodels-master
pip install .
```

**Comment by mujdeayik** [comment]
Thanks Kevin, having done what you have said, now i got another error: OSError: [WinError 193] %1 is not a valid Win32 application.

**Comment by bashtage** [comment]
It sounds like you have a 32 bit version of Windows which cannot run 64-bit python.

**Comment by bashtage** [comment]
What command are you running, specifically? Please post the full log.

**Comment by mujdeayik** [comment]
I am just running the install.py file from pycharm, having defined the correct working directory.

Import os
os. system (‘“python setup.py install’”)

**Comment by bashtage** [comment]
Just run it from the terminal.

**Comment by bashtage** [comment]
Closing since I suspect this worked.

**Comment by mujdeayik** [comment]
Thanks Kevin, it actually worked with whl files. All the best
