### ISSUE TITLE
AttributeError: 'VARMAXResults' object has no attribute 'apply'

### ISSUE THREAD

**Issue by Chichilele** [statsmodels/statsmodels#5959]
#### Describe the bug
On a fitting results, apply and append throw an Attribute error:
    [VARMAXResults.apply](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.varmax.VARMAXResults.apply.html)
    [VARMAXResults.append](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.varmax.VARMAXResults.append.html)

 errors:

    AttributeError: 'VARMAXResults' object has no attribute 'apply'

    AttributeError: 'VARMAXResults' object has no attribute 'append'
#### Code sample 
```python
    import statsmodels.api as sm
    ## train
    model = sm.tsa.VARMAX(endog=endog_train, exog=exog_train, order=order)
    results = model.fit(maxiter=maxiter, disp=disp, method=method)

    ## test
    test_pred = results.apply(endog_text, exog=exog_test)
    test_pred = results.append(endog_text, exog=exog_test)
```
Is cumputing it manually from `results.coefficient_matrices_var` the only way to test results over a test set (new unseen data) ?

#### Expected Output

Should be able to apply fitted model (results) to new unseen data.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

  | id | date | awdr | awnd | prcp | snwd | tavg | tmax | tmin | wesd | wsfi
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
USS0005J10S | 2016-09-06 | 18.0 | 210.0 | 0.0 | 0.0 | 98.0 | 166.0 | 29.0 | 0.0 | 22.0
USS0005J10S | 2016-09-07 | 16.0 | 246.0 | 0.0 | 0.0 | 94.0 | 164.0 | 34.0 | 0.0 | 16.0
USS0005J10S | 2016-09-08 | 21.0 | 221.0 | 0.0 | 0.0 | 101.0 | 175.0 | 33.0 | 0.0 | 17.0
USS0005J10S | 2016-09-09 | 19.0 | 219.0 | 0.0 | 0.0 | 62.0 | 128.0 | 1.0 | 0.0 | 15.0
USS0005J10S | 2016-09-10 | 16.0 | 256.0 | 0.0 | 0.0 | 82.0 | 172.0 | -6.0 | 0.0 | 13.0

</details>

**Comment by ChadFulton** [comment]
The extend and apply methods were only recently added to the development version of Statsmodels and are not yet available in a release (i.e. the are not in v0.10).

You can install Statsmodels development version from Github, otherwise these features will be available in v0.11 (although we do not have a timeline for when this release will be).

Closing since there is not much more to be done, but feel free to follow up if you have questions.

**Comment by Chichilele** [comment]
Thanks for the answer! It makes sense now, I'm excited to try it out.

Let me know if I should post the following somewhere else:
Trying to find these weights I found `params` [here](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.mlemodel.MLEResults.html#statsmodels.tsa.statespace.mlemodel.MLEResults). 

So under `results.params` there are the lagged variable weights along with beta associated to exog vars. However there is only 1 beta weight per exog variable. 

### Question
Is the VARMAX implementation considering any lag for `exog` variables ?

**Comment by ChadFulton** [comment]
> Is the VARMAX implementation considering any lag for exog variables ?

We don't have an option for automatically creating lagged `exog` variables, but you can pass any `exog` data you want in, including both contemporaneous and lagged versions of them.
