### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by raffam** [statsmodels/statsmodels#5970]
#### Describe the bug

Running `pip3 install statsmodels` on Windows fails to install statsmodels, because the compilation fails

Here is the relevant part of the log of the compilation
<details>
    copying statsmodels\tsa\vector_ar\tests\results\e6.dat -> build\lib.win32-3.7\statsmodels\tsa\vector_ar\tests\results
    UPDATING build\lib.win32-3.7\statsmodels/_version.py
    set build\lib.win32-3.7\statsmodels/_version.py to '0.10.0'
    running build_ext
       Creating library build\temp.win32-3.7\Release\statsmodels/tsa/innovations\_arma_innovations.cp37-win32.lib and object build\temp.win32-3.7\Release\statsmodels/tsa/innovations\_arma_innovations.cp37-win32.exp
    LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
    MSVCRT.lib(chandler4gs.obj) : error LNK2001: unresolved external symbol __except_handler4_common
    build\lib.win32-3.7\statsmodels\tsa\innovations\_arma_innovations.cp37-win32.pyd : fatal error LNK1120: 1 unresolved externals
    error: Command "D:\WinPrograms\VisualStudio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /nodefaultlib:libucrt.lib ucrt.lib /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:d:\\winprograms\\python3\\lib\\site-packages\\numpy\\core\\lib /LIBPATH:d:\winprograms\python3\libs /LIBPATH:d:\winprograms\python3\PCbuild\win32 /LIBPATH:D:\WinPrograms\VisualStudio\2019\Community\VC\Tools\MSVC\14.21.27702\ATLMFC\lib\x86 /LIBPATH:D:\WinPrograms\VisualStudio\2019\Community\VC\Tools\MSVC\14.21.27702\lib\x86 /LIBPATH:D:\Windows Kits\10\lib\10.0.18362.0\ucrt\x86 /LIBPATH:D:\Windows Kits\10\lib\10.0.18362.0\um\x86 npymath.lib /EXPORT:PyInit__arma_innovations build\temp.win32-3.7\Release\statsmodels/tsa/innovations/_arma_innovations.obj /OUT:build\lib.win32-3.7\statsmodels\tsa\innovations\_arma_innovations.cp37-win32.pyd /IMPLIB:build\temp.win32-3.7\Release\statsmodels/tsa/innovations\_arma_innovations.cp37-win32.lib" failed with exit status 1120

    ----------------------------------------
Command "d:\winprograms\python3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Raffaele\\AppData\\Local\\Temp\\pip-install-ujz0f94b\\statsmodels\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Raffaele\AppData\Local\Temp\pip-record-ok3_icd5\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Raffaele\AppData\Local\Temp\pip-install-ujz0f94b\statsmodels\
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
</details>

[This Stackoverflow question](https://stackoverflow.com/questions/31867018/unresolved-external-symbol-except-handler4-common-in-visual-studio-2015) point out that we should include vcruntime.lib to solve the problem, but I am not sure whether something else is going on

I have Windows 10 and Visual Studio 2019 Community Edition. Python version is
`Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32`

#### Code Sample, a copy-pastable example if possible

```
pip3 install statsmodels
```

**Comment by bashtage** [comment]
First, we recommend using 64 bit Python and there are wheels available for this platform.

Second, if you must use 32 bit, then you have to have the Visual studio 2015 build tools installed.  You need to rerun the vs 2019 installer and make sure these are installed. See https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by raffam** [comment]
I have installed the 64bit version of python and installation succeeded using wheels

**Comment by bashtage** [comment]
There is also a 32 bit wheel available now.
