### ISSUE TITLE
ARIMA Lag Selection

### ISSUE THREAD

**Issue by Jacyle** [statsmodels/statsmodels#5981]
#### Is your feature request related to a problem? Please describe
I'm trying to re-write SAS code into a python script. SAS allows for me to select specific lags (ex, p = (1,3,6)) vs. lag order (ex, p = 6).

#### Describe the solution you'd like
I would like to be able to select specific lags for the ARIMA model.

**Comment by bashtage** [comment]
Use SARIMAX.
