### ISSUE TITLE
32 bit wheels failing over on statsmodels wheels

### ISSUE THREAD

**Issue by thequackdaddy** [statsmodels/statsmodels#5993]
#### Describe the bug

The linux 3.5 and 3.6 32 bit builds are failing because of an uncaught warning. Does anyone have any idea why this would be? Anything change with warnings on 32 bit systems? 

The Windows 32 bit builds seem to be fine. 

(cron job) https://travis-ci.org/MacPython/statsmodels-wheels/builds/560978928
(my attempt) https://travis-ci.org/thequackdaddy/statsmodels-wheels/builds/561402830
(my attempt) https://ci.appveyor.com/project/thequackdaddy/statsmodels-wheels/builds/26122430

I doubt we have very many linux 32 bit users. We could just end support for that too.

**Comment by thequackdaddy** [comment]
My guess is that the error is not being tripped here... 

https://github.com/statsmodels/statsmodels/blob/32011b6b5e89e1e9d8061cd210406790d4ee7430/statsmodels/base/model.py#L1292-L1306

Reading this and the failing test code... 

https://github.com/statsmodels/statsmodels/blob/32011b6b5e89e1e9d8061cd210406790d4ee7430/statsmodels/base/tests/test_generic_methods.py#L255-L263

I *think* the tvalues part should have already been cached, so I'm wondering if this is an issue with `norm.sf` or `t.sf`. Not sure and setting up a i686 linux instance is really not something I'm too interested in at the moment. Only a theory.

**Comment by bashtage** [comment]
I think it is a bug in one of the libraries that is being used. It isn't possibly the res1.tvalues is called earlier since res1 has only been defined a few lines above.  Could you bump the final dot version so that 1.14.0->1.14.6?

**Comment by bashtage** [comment]
Another option could be to use `with np.errstate(invalid='warn')` as a context manager around this, although it shouldn't be necessary.

**Comment by thequackdaddy** [comment]
You don’t think it’s an issue with the lack of a warning from norm.sf or t.sf?

**Comment by bashtage** [comment]
I think these runtime warnings all come from NumPy.

**Comment by thequackdaddy** [comment]
So I upgraded to even the newest numpy/scipy and still get the errors. 

I think this was actually introduced quite recently... but we didn't notice it because we don't test on 32 bit linux. 

https://github.com/statsmodels/statsmodels/commit/3d14a28e39d078cf72b607ba0289aee11da9b82d#diff-111b086716e2864b120e1f451a7829f2

**Comment by bashtage** [comment]
We could simply skip these tests on 32-bit unix.

**Comment by bashtage** [comment]
@jbrockmendel I think the p-value checks are wrong in the sense that SciPy doesn't universally produce them. I get them on Windows but on Linux (checked both 32 bit and 64 bit). These need to be rolled back.

**Comment by bashtage** [comment]
Windows

"""
python -c "import numpy;import scipy.stats;scipy.stats.norm.cdf(numpy.array([numpy.nan]))"
C:\Anaconda\lib\site-packages\scipy\stats\_distn_infrastructure.py:877: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
C:\Anaconda\lib\site-packages\scipy\stats\_distn_infrastructure.py:877: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
C:\Anaconda\lib\site-packages\scipy\stats\_distn_infrastructure.py:1748: RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= self.b) & cond0
"""

Linux (no ouput)
"""
(base) ➜  System32 python -c "import numpy;import scipy.stats;scipy.stats.norm.cdf(numpy.array([numpy.nan]))"           (base) ➜  System32 
"""

**Comment by thequackdaddy** [comment]
Should we report this to the fine folks over on scipy?

**Comment by bashtage** [comment]
Could be worth a shot, although this won't help us here.  I suspect this is due to compiler specific issues and platform libraries.  I'll report it.

**Comment by jbrockmendel** [comment]
> These need to be rolled back.

Yep, looks like.  Question is: do we suppress them in the tests or in the method?
