### ISSUE TITLE
BUG: Subclassing pandas CacheReadonly breaks doc strings

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#6024]
@jbrockmendel The attributes that you wrapped in cached_value and cached_data do not have docstrings. See

https://www.statsmodels.org/devel/generated/statsmodels.regression.linear_model.RegressionResults.html?highlight=regressionresults#statsmodels.regression.linear_model.RegressionResults

note the missing tvalues and pvalues.

Also note the missing pearson_chi2 from 
 https://www.statsmodels.org/devel/generated/statsmodels.genmod.generalized_linear_model.GLM.html?highlight=pearson_chi2

**Comment by jbrockmendel** [comment]
Hmm I thought this was addressed a while ago.  I'll take a look

**Comment by bashtage** [comment]
Works fine if you don't subclass, so something is happening in the interaction of Cython extension types and python classes.

**Comment by bashtage** [comment]
The older CacheReadonly are also broken and don't expose `func` like a property should.  The breaks some use, and so the only way we can keep using CacheReadonly is to vendorize pandas for versions that don't expose `func`.

**Comment by bashtage** [comment]
This matters since it is impossible to call the underlying function when wrapped in an old `CacheReadonly`, as in `LikelihoodModel.tvalues.func(arg)` which doesn't work on 0.21 and 0.22 (not sure about 0.23), but does work in 0.24.

**Comment by jbrockmendel** [comment]
This has been sitting in my inbox for a while.  I'm kind of inclined to let it resolve itself when the min pandas version catches up.  Thoughts?  Downside is that I can't go get rid of the data_attr patttern until then.

**Comment by bashtage** [comment]
I think this is as fixed as it needs to be.
