### ISSUE TITLE
RegressionResults does not include attributes of all results included in summary()

### ISSUE THREAD

**Issue by dutch-rob** [statsmodels/statsmodels#6025]
#### Describe the bug

RegressionResults does not include attributes of all results included in summary().
E.g. the  summary() gives standard errors of coefficients as part of a text string but RegressionResults does not provide those standard errors as usable numbers.

It does provide HC0_se ... HC3_se. However, the documentation of those attributes refers to another place in the documentation that I could not find.
After some googling I found a paper (http://afhayes.com/public/BRM2007.pdf) that appears to explain those attributes as "heteroskedasticity-consistent standard error estimators". (I didn't know about that, so thanks for that!) 

#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import statsmodels.api as sm

nsample = 100
x = np.linspace(0, 10, 100)
X = np.column_stack((x, x**2))
beta = np.array([1, 10., 100.])
e = np.random.normal(size=nsample)

X = sm.add_constant(X)
y = np.dot(X, beta) + e

model = sm.OLS(y, X)
results = model.fit()
print(results.summary())
```
#### Expected Output

print(results.se)

**Comment by bashtage** [comment]
The attribute you are looking for is (strangely) named `bse`, rather than simply `se` or better `std_err`. Try `print(results.bse)`.

See https://www.statsmodels.org/stable/generated/statsmodels.regression.linear_model.RegressionResults.bse.html#statsmodels.regression.linear_model.RegressionResults.bse

**Comment by dutch-rob** [comment]
Hi Kevin,
Thanks very much!
So this was all only about documentation.
I noticed that I should have found bse() among the methods listed in the documentation (sorry!!) but it is not listed among the attributes, while the example you suggested does work well. 
Best regards,
Rob
