### ISSUE TITLE
Can't bundle using pyinstaller because of the "test" function in the "__init__.py".

### ISSUE THREAD

**Issue by ozeno** [statsmodels/statsmodels#6029]
Currently when I try to use pyinstaller to bundle a project which has a statsmodels dependency I get an error about "from ._version import get_versions" because of the other import statement in api.py "from .\_\_init\_\_ import test", pyinstaller adds two entries to it's toc file (a registry of required files) as below. And because of this duplication relative ._version import in \_\_init\_\_.py tries to import from "statsmodels.\_\_init\_\_._version" instead of "statsmodels._version".

Entries from Analysis.toc file:
```
('statsmodels.__init__',
   'c:\\program files\\python37\\lib\\site-packages\\statsmodels\\__init__.py',
('statsmodels',
   'c:\\program files\\python37\\lib\\site-packages\\statsmodels\\__init__.py',
```

Either refactoring the test function out of \_\_init\_\_.py or turning ._version relative import into an absolute import like so "statsmodels._version" seem to solve the issue.

**Comment by bashtage** [comment]
Happy to accept a PR on this.  We don't test using pyinstaller.
