### ISSUE TITLE
SARIMA model fit runs super slowly

### ISSUE THREAD

**Issue by linshi006** [statsmodels/statsmodels#6033]
Hi team i am trying to fit a time series model with seasonal length 365 days and notice it is taking actually over 2 hours to run. The model parameters look like this and historical_dat is a data table with 2k rows.
```
model = SARIMAX(historical_dat, order=(5, 1, 2),seasonal_order=(0, 1, 0, 365),enforce_stationarity=False,
                                enforce_invertibility=False)
```
Actually when i try to fit the model with same parameters in R using R packages, it will only take 15 mins to finish. I am just wondering why it is taking so long and there is any difference between your function and r function (since i also notice the output numbers differ a little bit, like your numbers 0.3% higher than R.)

**Comment by ChadFulton** [comment]
Yes, SARIMAX is unfortunately not fast for models with large seasonal orders, and with order 365 it will be very slow.
