### ISSUE TITLE
SARIMAX memory consumption

### ISSUE THREAD

**Issue by david-waterworth** [statsmodels/statsmodels#6034]
Right at the end of the fit process, SARIMAX is consuming almost 100% of my available memory. It runs for quite some time (using all CPU's) without any increase in memory then it starts to ramp up, and maintains 90% usage. 

Result is a crashed jupyter kernel (but the server stays up and the memory allocated). Restarting jupyter frees the memory.

Code is

```
model = sm.tsa.SARIMAX(x, order=(1,0,0), seasonal_order=(1,0,0,96))

results = model.fit()
print(results.summary())
```
 
x is an pandas array of length 34751

![image](https://user-images.githubusercontent.com/5028974/62091897-7815d700-b2b6-11e9-92f1-8161d5970773.png)

Also using `getsize` from https://stackoverflow.com/a/30316760/2981639 gives

![image](https://user-images.githubusercontent.com/5028974/62092442-836a0200-b2b8-11e9-9ad2-89e8b8a474b3.png)

```
import sys
from types import ModuleType, FunctionType
from gc import get_referents

# Custom objects know their class.
# Function objects seem to know way too much, including modules.
# Exclude modules as well.
BLACKLIST = type, ModuleType, FunctionType


def getsize(obj):
    """sum size of object & members."""
    if isinstance(obj, BLACKLIST):
        raise TypeError('getsize() does not take argument of type: '+ str(type(obj)))
    seen_ids = set()
    size = 0
    objects = [obj]
    while objects:
        need_referents = []
        for obj in objects:
            if not isinstance(obj, BLACKLIST) and id(obj) not in seen_ids:
                seen_ids.add(id(obj))
                size += sys.getsizeof(obj)
                need_referents.append(obj)
        objects = get_referents(*need_referents)
    return size
```

Edit:

This might give an indicator of where it's occurring. If I change the order / seasonal_order parameters SARIMAX can run out of memory before the model solves in which case it dumps the following Traceback.

> ---------------------------------------------------------------------------
> MemoryError                               Traceback (most recent call last)
> <ipython-input-24-d00c66b6c85e> in <module>
>       1 model = sm.tsa.SARIMAX(x, order=(1,1,0), seasonal_order=(1,1,0,96))
>       2 
> ----> 3 results = model.fit()
>       4 print(results.summary())
> 
> ~/.pyenv/versions/3.7.1/envs/machine-learning-3.7.1/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py in fit(self, start_params, transformed, cov_type, cov_kwds, method, maxiter, full_output, disp, callback, return_params, optim_score, optim_complex_step, optim_hessian, flags, **kwargs)
>     488         else:
>     489             res = self.smooth(mlefit.params, transformed=False,
> --> 490                               cov_type=cov_type, cov_kwds=cov_kwds)
>     491 
>     492             res.mlefit = mlefit
> 
> ~/.pyenv/versions/3.7.1/envs/machine-learning-3.7.1/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py in smooth(self, params, transformed, complex_step, cov_type, cov_kwds, return_ssm, results_class, results_wrapper_class, **kwargs)
>     604 
>     605         # Get the state space output
> --> 606         result = self.ssm.smooth(complex_step=complex_step, **kwargs)
>     607 
>     608         # Wrap in a results object
> 
> ~/.pyenv/versions/3.7.1/envs/machine-learning-3.7.1/lib/python3.7/site-packages/statsmodels/tsa/statespace/kalman_smoother.py in smooth(self, smoother_output, smooth_method, results, run_filter, prefix, complex_step, **kwargs)
>     386         results = self.results_class(self)
>     387         results.update_representation(self)
> --> 388         results.update_filter(kfilter)
>     389 
>     390         # Run the smoother
> 
> ~/.pyenv/versions/3.7.1/envs/machine-learning-3.7.1/lib/python3.7/site-packages/statsmodels/tsa/statespace/kalman_filter.py in update_filter(self, kalman_filter)
>    1509         self.filtered_state = np.array(kalman_filter.filtered_state, copy=True)
>    1510         self.filtered_state_cov = np.array(
> -> 1511             kalman_filter.filtered_state_cov, copy=True
>    1512         )
>    1513         self.predicted_state = np.array(
> 
> MemoryError: 
>

**Comment by ChadFulton** [comment]
> Right at the end of the fit process, SARIMAX is consuming almost 100% of my available memory. It runs for quite some time (using all CPU's) without any increase in memory then it starts to ramp up, and maintains 90% usage.

This is to be expected. During the parameter fitting process, it doesn't need too much memory, and then when it creates the results object it produces a lot of auxiliary output that in your case will take quite a bit of memory.

In particular, the results object constructs a number of arrays of size (nobs x k_states x k_states), where k_states grows linearly with the seasonal order. In your case, `k_states = 194` so that you're constructing several arrays of size (34751 x 194 x 194), each of which will be about 10gb.

We do have some options for low-memory usage, but what works will depend a little on what you need to do with the results (e.g. some of them currently don't allow for forecasting afterwards). For example, you will reduce memory by quite a bit with the following:

```python
mod = sm.tsa.SARIMAX(...)
params = mod.fit(return_params=True)

mod.ssm.memory_no_filtered = True
mod.ssm.memory_no_gain = True
mod.ssm.memory_no_smoothing = True
mod.ssm.memory_no_std_forecast = True
res = mod.filter(params)
```

although you'll still have at least one of those large multi-gigabyte arrays.

**Comment by david-waterworth** [comment]
Thanks, yes that helps!

**Comment by ChadFulton** [comment]
Hopefully the combination of #6064 and #6071 will help get the memory consumption down to reasonable levels here. These two allow fitting models with lots of data and then performing out-of-sample forecasting, all with minimal memory consumption.

**Comment by ChadFulton** [comment]
Now that #6071 has been merged, if you want to try for less memory consumption, you can install the development version of Statsmodels from Github and then do the following:

```python
mod = sm.tsa.SARIMAX(...)
res = mod.fit(low_memory=True)
```

and see if that helps.

**Comment by ChadFulton** [comment]
I'll close this since I think this has been helped by #6071. If you end up having time to test this, it would be great to learn how things worked, either way (i.e. it did help, or it did not help).

**Comment by ChadFulton** [comment]
No problem - it would be great to hear anytime you happen to get back to it. Thanks!

**Comment by david-waterworth** [comment]
I've finally had time to look at this again, yes it definitly helps.

The following works (using current HEAD)
```
model=sm.tsa.statespace.SARIMAX(endog=df['residuals'],order=(1,1,0),seasonal_order=(1,0,0,96),enforce_invertibility=False)
results = model.fit(low_memory=True)
```

Your original suggestion (using 10.1) still ran out of memory i.e.

```
params = model.fit(return_params=True)
model.ssm.memory_no_filtered = True
model.ssm.memory_no_gain = True
model.ssm.memory_no_smoothing = True
model.ssm.memory_no_std_forecast = True
results = model.filter(params)
```

endog.shape is (34753,)

**Comment by ChadFulton** [comment]
Great, so it sounds like we are in good shape in the HEAD version?

**Comment by david-waterworth** [comment]
Performance wise yes, although results.resid throws the following

> ~/.pyenv/versions/3.7.1/envs/machine-learning-3.7.1/lib/python3.7/site-packages/statsmodels/base/data.py in attach_rows(self, result)
>     568         # assumes if len(row_labels) > len(result) it's bc it was truncated
>     569         # at the front, for AR lags, for example
> --> 570         squeezed = result.squeeze()
>     571         k_endog = np.array(self.ynames, ndmin=1).shape[0]
>     572         if k_endog > 1 and squeezed.shape == (k_endog,):

**Comment by ChadFulton** [comment]
Thanks for letting us know! It shouldn't raise an AttributeError, but `resid` is not available under `low_memory`.

**Comment by david-waterworth** [comment]
No problems!

**Comment by ChadFulton** [comment]
Although this is something we should maybe should reconsider that, since `resid` is useful for model diagnostics and won't ever be any larger than the original dataset.

**Comment by david-waterworth** [comment]
Can it be computed on demand?

**Comment by ChadFulton** [comment]
Not really - with `low_memory` the fitted values aren't stored either, so you'd have to run the Kalman filter (not the whole parameter fitting, but just the filter using the fitted parameters), and then you'd be back in the original situation of needing to select a low memory option.

**Comment by ChadFulton** [comment]
See #6188 for an issue for discussing what the best default setting for `low_memory` should be.
