### ISSUE TITLE
Documentation implies properties are methods

### ISSUE THREAD

**Issue by david-waterworth** [statsmodels/statsmodels#6035]
The documentation is a little confusing, i.e. [SARIMAXResults](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAXResults.html) has `resid()` under `Methods`, but I think it really should be `resid` under `Properties`?

**Comment by thequackdaddy** [comment]
xref https://github.com/statsmodels/statsmodels/pull/5749/files#diff-612d28cac38f8306be10e9737ea819caR45

This has perplexed me for some time. In essence, resid is a actually a cached method, like a `property`. I thought the code above fixed that, but maybe it didn't.

**Comment by bashtage** [comment]
This is fixed in master.
