### ISSUE TITLE
DOC/BUG: Seasonality in SARIMAX Notebook

### ISSUE THREAD

**Issue by baselactive** [statsmodels/statsmodels#6037]
Can you look at the code at the "**In[7]**" (below) in the documentation https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_sarimax_stata.html
```python
# In[7]
#Fit the model
mod = sm.tsa.statespace.SARIMAX(data['ln_wpi'], trend='c', order=(1,1,1))
```
Prior to this code in the documentation, it is said that, since we want a polynomial that has terms for the 1st and 4th degrees of moving averages, we want to use `ma = (1,0,0,1)`

However, this `ma` part (i.e. `(1,0,0,1)`) is not included in the code above,. I think the order should be like that `order=(1,1,(1,0,0,1))` instead of `order=(1,1,1)` in the above code. So the final code in the box of `In[7]` have to be like that
```python
# In[7]
#Fit the model
mod = sm.tsa.statespace.SARIMAX(data['ln_wpi'], trend='c', order=(1,1,(1,0,0,1)))
```
Can you check it?

**Comment by ChadFulton** [comment]
Thanks very much - you're right, this notebook needs to be updated. Thanks!
