### ISSUE TITLE
BUG: Time-varying state space design matrix in constructor.

### ISSUE THREAD

**Issue by johnk1282** [statsmodels/statsmodels#6040]
Hi -- I'm trying to initialize a state space representation with a time varying design matrix. For example:

import numpy as np
import statsmodels.api as sm

nobs = 100
k_endog = 1
k_states = 2
endog = np.random.normal(0,1,size=(nobs,))
dsn = np.random.normal(0,1,size=(k_endog,k_states,nobs))
sm.tsa.statespace.MLEModel(endog,k_states,design=dsn)

This gives the following error:

ValueError: Invalid dimensions for time-varying design matrix. Requires shape (*,*,0), got (1, 2, 100)

The documentation on the other hand suggests that the design matrix should be k_endog x k_states x nobs. Apologies if I'm missing something obvious.

**Comment by ChadFulton** [comment]
Hey, thanks for reporting this bug!  In the meantime, the workaround for this is to set the time-varying matrix after the object is already constructed:

```python
nobs = 100
k_endog = 1
k_states = 2
endog = np.random.normal(0,1,size=(nobs,))
dsn = np.random.normal(0,1,size=(k_endog,k_states,nobs))
mod = sm.tsa.statespace.MLEModel(endog,k_states)
mod['design'] = dsn
```

**Comment by ChadFulton** [comment]
This should be fixed in master now and will be fixed in the next release. Thanks again for the report.
