### ISSUE TITLE
OLS compare_f_test in parallel

### ISSUE THREAD

**Issue by tgbrooks** [statsmodels/statsmodels#6049]
Though it's not documented, it's perfectly fine to run sm.OLS with `endog` being a 2d array which essentially performs `k` separate linear regressions if `k = endog.shape[1]`. This gives a significant speedup over running them one-by-one (over 100x by one test).

However, running `compare_f_test` on the results of two such regressions then raises an exception. (For this reason, I was considering submitting this as a bug report, not a feature request. But the undocumented nature of running OLS on 2d arrays made me think this would be better.) Analogous suggestions could be made for the other significance-testing functions, though I haven't tested them.

Ideally, the following code would work:
``` python
import numpy
import statsmodels.api as sm

# Random data with two (identical) groups with ten members each
# and there are 1000 repetitions of this setup
data = numpy.random.random( (20, 1000) )
model  = sm.add_constant(numpy.array([0]*10 + [1]*10))
restricted_model = numpy.ones((20,1))

fit = sm.OLS(data, model).fit()
restricted_fit = sm.OLS(data, restricted_model).fit()

# The following raises a ValueError exception
# but should instead have the same results as the method shown below
fs, ps, dfs = fit.compare_f_test(restricted_fit)

## The current way you have to run this, running one at a time:
fs, ps, dfs = numpy.empty(1000), numpy.empty(1000), numpy.empty(1000)
for i in range(1000):
  fit = sm.OLS(data[:,i], model).fit()
  restricted_fit = sm.OLS(data[:,i], restricted_model).fit()
  fs[i], ps[i], dfs[i] = fit.compare_f_test(restricted_fit)
```

**Comment by tgbrooks** [comment]
It's actually a one-line fix from what I can tell. Look [here](https://github.com/statsmodels/statsmodels/blob/727dca48948c54257dda8be4f6d5a2e72d5160d3/statsmodels/regression/linear_model.py#L1655).

``` python
    def ssr(self):
        """Sum of squared (whitened) residuals."""
        wresid = self.wresid
        #was the following:
        #return np.dot(wresid, wresid)
        # Instead:
        return numpy.sum(wresid * wresid, axis=0)
```

I'll try to make a pull-request if this is something that would be accepted.

**Comment by bashtage** [comment]
That is not the same value. Wresid is nobs vector so the dot is a scalar
when K is 1.

**Comment by bashtage** [comment]
What you want is called a multivariate regression. linearmodel has the
function.

**Comment by tgbrooks** [comment]
Thanks for the reply! Not sure what you mean by the first comment. If `endog` is 1 dimensional then `np.sum(wresid * wresid, axis=0)` is also a scalar since wresid is 1 dim. They do differ if `endog` is 2 dimensional, but that is intended, of course.

Is the `_MultivariateOLS` class ready for use yet? It looks incomplete at least in documentation and the leading underscore makes me think it's not meant to be used.

I'm trying the following:
``` python
from statsmodels.multivariate.multivariate_ols import _MultivariateOLS
import numpy

data = numpy.random.random( (20, 1000) )
model  = sm.add_constant(numpy.array([0]*10 + [1]*10))
restricted_model = numpy.ones((20,1))

fit = _MultivariateOLS(data, model).fit()
fit_restricted = _MultivariateOLS(data, restricted_model).fit()
# now what?
```

The `fit` objects seem to have no useful attributes or methods. I don't see the equivalent of `fit.params` to get the regression coefficients or `fit.ssr`. Is it possible to do an F-test on these?

Meanwhile, in case someone else stumbles across this, I'm using the following to perform an F-tests:
``` python
def compare_f_test(fit, restricted):
    # Work-around for statsmodels issue when the endog matrix is 2d
    def ssr(fit):
        return numpy.sum(fit.wresid * fit.wresid, axis=0)
    ssr_full = ssr(fit)
    ssr_restr = ssr(restricted)
    df_full = fit.df_resid
    df_restr = restricted.df_resid

    df_diff = (df_restr - df_full)
    f_value = (ssr_restr - ssr_full) / df_diff / ssr_full * df_full
    p_value = scipy.stats.f.sf(f_value, df_diff, df_full)
    return f_value, p_value, df_diff
```

**Comment by bashtage** [comment]
`linearmodels.system import SUR.multivariate_ls` explicitly handles the multivariate OLS case.  Note that this is in `linearmodels`, not statsmodels. 

`_MultivariateOLS` is very minimal and only used internally as far as I am aware.

**Comment by bashtage** [comment]
> ```python
> numpy.sum(wresid * wresid, axis=0)
> ```

Sorry, I missed the axis argument. It is the same (only slower, but probably not noticeable).

**Comment by bashtage** [comment]
I don't think there is any action.  We don't want something as core as OLS to become multivariate.  If anything, it should be more strict in checking that endog is a single column or 1 1d array. 

We would be happy to see improvement in MultivariteOLS, although that is a big job.

**Comment by tgbrooks** [comment]
Thanks for pointing me in the right direction, I'll try out the linearmodels package.

**Comment by josef-pkt** [comment]
see #4771 and #5382 for vectorized OLS, which is simpler than a full multivariate OLS
