### ISSUE TITLE
DOC: Tool needed to remove parameters from docstrings

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#6068]
#### Is your feature request related to a problem? Please describe
An internal tool is needed to robustly remove parameters from docstring to imrove docstring resuse.  This is along the lines of Appender and Substitution.  Perhaps `Remover` so we could so something like 

`@Appender(Remover(some_func.__doc__, 'unused_parameter'))`

#### Describe the solution you'd like
Remove parameters from a doc string

#### Describe alternatives you have considered
The only use now is manual and will break is the doc string has lines added or removed

#### Additional context
Add any other context about the feature request here.

**Comment by bashtage** [comment]
@jbrockmendel This came up after seeing how you removed a parameter from `AR.predict` to make `ARResults.predict`.  Should be a more reliable way to do this. 

I could also imagine that it would be useful to remove or replace entire sections, e.g., `Notes`. since many docstrings are identical except for some math formulas in the `Notes`

**Comment by jbrockmendel** [comment]
That's a neat idea.  Can you assign this issue to me so I don't lose track of it (ATM I'm leaving emails unread in my inbox and that is not a long-term solution)

**Comment by bashtage** [comment]
Done.

**Comment by bashtage** [comment]
See https://github.com/scipy/scipy/blob/maintenance/1.3.x/scipy/misc/doccer.py#L128

**Comment by bashtage** [comment]
This has been added
