### ISSUE TITLE
Box-Ljung test giving different p-values in R and Python

### ISSUE THREAD

**Issue by fissehab** [statsmodels/statsmodels#6078]
I have code in R and I am translating it to Python for scalability issue to work with PySpark. I am comparing if I get the same results with R and Python. I am fitting auto ARIMA models with exogenous features. When I test the autocorrelation of the residuals using Box-Ljung, I get different p-values but when I compare the residuals, they are very close. R considers degrees of freedom while Python does not. Which way is more appropriate?

The data I used in the code below is available from [here](https://github.com/fissehab/fissehab.github.io/blob/master/Miscellaneous/uschange.csv). As you can see below, the degree of freedom used by R is 5 and the p-value is 0.3017. With Python, it does not use degrees of freedom and the array of the p-values is very high. If I remove the degree of freedom and perform the test with R, I get the same results (0.80958073).
**R**
```
library(forecast)
library(readr)
df = read_csv('uschange.csv')
df = as.matrix(df)
my_fit <- auto.arima(df[,"Consumption"], xreg=df[,"Income"])
checkresiduals(fit, plot = FALSE)
```

> Ljung-Box test data: Residuals from Regression with ARIMA(1,0,2) errors Q* = 6.0465, df = 5, p-value = 0.3017 Model df: 5. Total lags used: 10

**Python**
```
import pandas as pd
from pmdarima.arima import auto_arima
from statsmodels.stats.diagnostic import acorr_ljungbox
df = pd.read_csv("uschange.csv")
arima_model = auto_arima(y = df['Consumption'], 
                  exogenous = df[['Income']],
                  start_p=1, 
                  start_q=1,
                  max_p=3, 
                  max_q=3,
                  seasonal=False,
                  d = None,  
                  error_action='ignore',  
                  suppress_warnings=True, 
                  stepwise=False)
 acorr_ljungbox(arima_model.resid(), lags = 10)
```

The second array below is the p-values:

> (array([0.00775255, 0.04434567, 0.37206872, 0.57959716, 0.87815042, 1.30443762, 1.83487883, 5.90958235, 6.05594458, 6.06726358]),

array([0.92983808, 0.97807118, 0.94595004, 0.9653037 , 0.97178326, 0.97141244, 0.96841158, 0.6573594 , 0.73430632, 0.80958073]))

**Comment by bashtage** [comment]
Are the selected models the same?

**Comment by bashtage** [comment]
R is making some sort of degrees of freedom adjust and the p-value you are seeing is from a chi2 with 5 d.o.f., presumably since the model has 5 parameters.  That is a non-standard choice is not theoretically justified. 

The statsmodels code works as expected and produces a p-value as 1-F(qstat) where F is a chi-square cdf with `lags` df. 

In short, `checkresiduals` does not work correctly in this model. It appears to be desgiend for regressions.

```
Box.test(resid(my_fit),10)

	Box-Pierce test

data:  resid(my_fit)
X-squared = 5.7523, df = 10, p-value = 0.8356
```

is much closer.  

It might be more correct to use 

```
Box.test(resid(my_fit),10,fitdf =3)

	Box-Pierce test

data:  resid(my_fit)
X-squared = 5.7523, df = 7, p-value = 0.569
```

since the selected model is an ARMA(1,2).

**Comment by fissehab** [comment]
but in R, **Box.test(x, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)** where _fitdf_	
number of degrees of freedom to be subtracted if x is a series of residuals. How do I account if the residuals is a series in _acorr_ljungbox?_

**Comment by bashtage** [comment]
You can't in 0.10.1.  I fixed this in master today by adding the argument `model_df`, so if using master you can do 

```
acorr_ljungbox(arima_model.resid(), lags = 10, model_df=sum(order))
```

where order is the order of your model (p,q)

If you are using 0.10.1, you can manually compute the pvalues using `stats.chi2.sf(stat, lag-sum(order))` for any `lag` as long as  lag-sum(order) > 0

**Comment by fissehab** [comment]
Thanks.  What is _stat_ in _stats.chi2.sf(stat, lag-sum(order))_? How do I calculate it? Is it the test statistic I get from _acorr_ljungbox_?

**Comment by bashtage** [comment]
```
from scipy import stats
lj = acorr_ljungbox(arima_model.resid(), lags = 10)
corrected_pval = stats.chi2.sf(lj[-1], 10 - p - q)
```

**Comment by RiwanODN** [comment]
Hello Bashtage, I do not how does work the function acorr_ljungbox.
Indeed, if I set lags=10, is the pvalue for the overall lags (from 1 to 10) or only for the 10th lag?

**Comment by RiwanODN** [comment]
I do not get why on r the p-value for this test is only one value and in python it is an Array?

**Comment by bashtage** [comment]
In statsmodels you get one pvalue for each lag length. 

The command 
```
ljstat, ljpval= acorr_ljungbox(resid, lags = 10)
```
computes the L-J test for lags 1, 2, ..., 10, which is why you get 10 values, and the p-values correspond to these 10 test statistics.
