### ISSUE TITLE
fix_params() not compatible with some gradient-based optimizers

### ISSUE THREAD

**Issue by dieterwang** [statsmodels/statsmodels#6103]
I'm using the `fix_params` [method ](http://www.statsmodels.org/devel/generated/generated/statsmodels.tsa.statespace.varmax.VARMAX.fix_params.html?highlight=fix_params#statsmodels.tsa.statespace.varmax.VARMAX.fix_params) that's new in the `0.11.0dev0+413.ge6632b646` version from github to restrict a few regression coefficients to zero in a VARMAX model. 

It works for: nelder-mead, powell, lbfgs
It fails for: bfgs, newton, cg

Seems to be related to the dimension of the parameter vector during gradient and/or Hessian calculations.

```python
# MWE
y = pd.DataFrame(np.random.randn(100,3), columns=['y1','y2','z'])
X = pd.DataFrame(np.random.randn(100,1), columns=['x'])

mdl = sm.tsa.VARMAX(endog=y, exog=X)
with mdl.fix_params({'beta.x.z': 0}):
    res = mdl.fit(method='bfgs')
```

Below an example when using BFGS. Correct parameter dimension should be 20.
```
~/.conda/envs/ipy75/lib/python3.7/site-packages/scipy/optimize/optimize.py in _minimize_bfgs(fun, x0, args, jac, callback, gtol, norm, eps, maxiter, disp, return_all, **unknown_options)
   1010     gnorm = vecnorm(gfk, ord=norm)
   1011     while (gnorm > gtol) and (k < maxiter):
-> 1012         pk = -numpy.dot(Hk, gfk)
   1013         try:
   1014             alpha_k, fc, gc, old_fval, old_old_fval, gfkp1 = \

ValueError: shapes (20,20) and (21,) not aligned: 20 (dim 1) != 21 (dim 0)

```

**Comment by ChadFulton** [comment]
Thanks very much for the report!

**Comment by ChadFulton** [comment]
I think the problem here was the `score` method wasn't only returning the score for the fixed parameters. Not sure if #6104 will quite do it, but that's the first step.

**Comment by ChadFulton** [comment]
I think that this should work now. If you get a chance to test it out, please let us know how it goes.

**Comment by dieterwang** [comment]
pulled the `0.11.0dev0+433.gb92e72237` commit and tested it out - works like a charm!

**Comment by ChadFulton** [comment]
Great!
