### ISSUE TITLE
DOC: Contributor's Numpy Link Broken

### ISSUE THREAD

**Issue by khs** [statsmodels/statsmodels#6109]
#### Describe the bug

When someone contributes through github, they're told how Numpy commit messages work. However, the link that does so is https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message, which is broken. https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#asking-for-merging is a currently working version. 

#### Code Sample, a copy-pastable example if possible

```python
# Your code here that produces the bug
# This example should be self-contained, and so not rely on external data.
# It should run in a fresh ipython session, and so include all relevant imports.
```

#### Expected Output

A working link.

**Comment by ChadFulton** [comment]
Thanks very much for the note! I guess we probably want the `#writing-the-commit-message` anchor though: https://docs.scipy.org/doc/numpy-1.15.1/dev/gitwash/development_workflow.html#writing-the-commit-message

**Comment by ChadFulton** [comment]
Thanks!
