### ISSUE TITLE
DOC: API Reference Page

### ISSUE THREAD

**Issue by StevenLi-DS** [statsmodels/statsmodels#6112]
I really wish we can add an API Reference page to list all functions and methods available in SM. SM is perhaps the only python package I've used that doesn't have an API reference page.

I think pysal is a good example where all the functions are listed and categorized based on their usage. https://pysal.readthedocs.io/en/latest/api.html  Please take a look.

**Comment by emilmirzayev** [comment]
Upvoting because I also think that would be a good addition.

**Comment by bashtage** [comment]
PRs to provide a better structure are welcome.  The current state is a bit NumPy-like with an introduction and then an API reference:

http://www.statsmodels.org/devel/tsa.html

https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

although both statsmodels and NumPy use a mix of styles that vary between introduced API, just API, or long explainers followed by API in nested pages.

**Comment by StevenLi-DS** [comment]
@bashtage btw, is there any reason why we have such huge font size in the new doc?

**Comment by bashtage** [comment]
I copied material mkdocs which I think looks nice. This is a hack and does
not have responsive font sizes. Really need a clean sheet site design, but
that takes a long time. All of the responsive designs for sphinx are
lacking imo. Numpy is getting a new site so this might provide a good
starting template.

**Comment by bashtage** [comment]
BTW would be very happy to accept any general website improvement up to and
including a new template theme. Might be people out there very good at web
stuff that have a huge comparative advantage.

**Comment by StevenLi-DS** [comment]
accidentally run into the new doc page...man... it looks great! When could we have an official release? I'm gotta do a workshop recently and hopefully I can add a link to it.

Btw, I also have a question for SM's API structure which been puzzled me for a while. For example, for OLS model. the header of the doc page is  `statsmodels.regression.linear_model.OLS`. As a user, i would assume that if I wanna use it. I need:
```python
statsmodels.regression.linear_model.OLS as OLS
```
or 
```python
from statsmodels.regression.linear_model import OLS
```
However, I just need to `import statsmodels.api as sm` and then I could have access to all the functions.. then why not just put ` statsmodels.api.OLS` instead?

**Comment by bashtage** [comment]
The doc page shows that actual location.  In practice, it is best to import from the actual location since it is faster since it will only import the minimum required.  `sm` and `tsa` are convenience functions  that aggregate the more important parts of statsmodels into user-friendly locations. It also help avoid issues like

```
import statsmodels
```

importing the entiriety of the package, which is what would happen if `statsmodels.api` was moved to `statsmodels.__init__`.   `import matplotlib.pyplot as plt` is the same ideas as `import statsmodels.api as sm`.

> accidentally run into the new doc page...man... it looks great! When could we have an official release? I'm gotta do a workshop recently and hopefully, I can add a link to it.

Will be a long time, but statsmodels.org/devel is probably better in all ways for now.

**Comment by bashtage** [comment]
I think this is finished. There is considerably more in the api section of the docs. 

http://www.statsmodels.org/devel/api.html
http://www.statsmodels.org/devel/api.html#import-paths-and-structure

**Comment by StevenLi-DS** [comment]
@bashtage 
I think in the API Import section, maybe we should also mention formula usages like `import statsmodels.formula.api as smf`. What do you think?

**Comment by bashtage** [comment]
I added them. They are not that useful since they all have a generic
docstring.

**Comment by StevenLi-DS** [comment]
@bashtage I just realized that the API page doesn't include statistical tests like t-test, ANOVA, etc. Am I missing something?

**Comment by bashtage** [comment]
Those are not part of the api.  There is a lot that is not in the API.

**Comment by StevenLi-DS** [comment]
An API reference usually lists all the functions a package offers. Is there any reason why we don't include some of them in the reference? 

Btw, I couldn't find `statsmodels.compat`. Am I missing something?

**Comment by bashtage** [comment]
sm.compat is effectively private and is only used to abstract changes in dependencies (e.g., changes in functions accross NumPy 1.14 -- 1.1.7)

The statsmodels API is the friendly entry point for the enduser-facing function. There is a lot does not meet this qualification.
