### ISSUE TITLE
DOC: add the new logo into the About page

### ISSUE THREAD

**Issue by StevenLi-DS** [statsmodels/statsmodels#6128]
Really like the new logo design and please considering put a high-PPI image in the About page so that folks can easily grab it and PR SM to the community.

https://www.statsmodels.org/devel/about.html

Btw, this maybe needs a small fix:
![image](https://user-images.githubusercontent.com/33796896/63630156-d6985180-c5e5-11e9-9792-aff0eab9d8a5.png)

**Comment by bashtage** [comment]
You can find the logo http://www.statsmodels.org/devel/about.html#brand-marks
