### ISSUE TITLE
How is the period calculated?

### ISSUE THREAD

**Issue by ToNorthX** [statsmodels/statsmodels#6139]
I want to know if the period needs to be specified manually? When I didn't specify it, I get an error:
      ValueError: freq T not understood. Please report if you think this is in error.

In addition, can the period be obtained in the code?

**Comment by bashtage** [comment]
Please provide more details into your data and what command you are using.

**Comment by ToNorthX** [comment]
Using seasonal_decompose functions，I did not give the parameter freq. code :
      seasonal_decompose(dta)

Running error:
     ValueError: freq T not understood. Please report if you think this is in error.

Must I give frep parameter?

**Comment by bashtage** [comment]
Yes, you need to provide the length of the period.  If you use the master branch, the keyword is `period`. There are many frequencies where it is not possible to determine the full period.  For example, is the periof of T 60 (1 hour), 1440 (1 day), or 10080 (1 week) (or somethign else)?

http://www.statsmodels.org/devel/generated/statsmodels.tsa.seasonal.seasonal_decompose.html?highlight=seasonal_decompose#statsmodels.tsa.seasonal.seasonal_decompose
