### ISSUE TITLE
multiple linear regression

### ISSUE THREAD

**Issue by ssunabashir** [statsmodels/statsmodels#6141]
hello guys help find where am going wrong in my code
import statsmodels.formula.api as sm
X = np.append(arr = np.ones((50, 1)).astype(int), values = X, axis =1)
X_opt = X[:, [0,1,2,3,4,5]]
regressor_OLS = sm.ols(endog = Y, exog = X_opt).fit()
regressor_OLS.summary()

this is the error am getting 
File "<ipython-input-64-a30cf8cdcb43>", line 1, in <module>
    regressor_OLS = sm.ols(endog = Y, exog = X_opt).fit()

TypeError: from_formula() missing 2 required positional arguments: 'formula' and 'data'

**Comment by bashtage** [comment]
Please see the documentation:

http://www.statsmodels.org/devel/example_formulas.html

You are not using the API correctly.  You need 2 inputs: formula (text) and data (DataFrame).  If you want to use the programtic interface to OLS (w/o a string formula), you need to 

```
import statsmodels.api as sm
sm.OLS(Y,X_opt).fit()
```
