### ISSUE TITLE
KalmanFilter class

### ISSUE THREAD

**Issue by sursu** [statsmodels/statsmodels#6148]
The purpose of the `KalmanFilter` class is somewhat unclear to me.

I am interested in estimating the parameters of the Kalman filter. To my understanding that is not implemented.

Would it be possible to create a short notebook to exemplify how this class can be used?

@ChadFulton

**Comment by ChadFulton** [comment]
The `tsa.statespace.KalmanFilter` class is primarily an internal class used to apply the Kalman filter to a fixed dataset given a fixed set of system matrices.  Its main job is to act as an interface over the Cython class which actually implements the filtering routines.

The `tsa.statespace.MLEModel` class provides an interface for estimating parameters within those system matrices by maximum likelihood. One example for using this class to estimate parameters of an AR(2) model that has been cast into state space form can be found in our documentation: https://www.statsmodels.org/devel/statespace.html#custom-state-space-models.

**Comment by sursu** [comment]
Thank you.

I've read what you've referenced. In particular [Custom state space models](https://www.statsmodels.org/devel/statespace.html#custom-state-space-models) was useful and the [ Local Linear Trend example](statsmodels.org/devel/examples/notebooks/generated/statespace_local_linear_trend.html).

My simple, linear Kalman Filter can be described in these 2 equations:

```
        X = T*X_1 + e,          e ~ N(0,H)
        Y = mu + A*X + w,    w ~ N(0,G)
``` 

Following the Local Linear Trends example I've implemented the following class:

```python
class KalmanFilter(sm.tsa.statespace.MLEModel):
    """Linear Kalman Filter Model"""
    def __init__(self, endog):
        # Model order
        k_states = k_posdef = 1

        # Initialize the statespace
        super(KalmanFilter, self).__init__(
            endog, k_states=k_states, k_posdef=k_posdef,
            initialization='approximate_diffuse',
            loglikelihood_burn=k_states
        )

        # Initialize the matrices
        self.ssm['selection'] = np.eye(k_states)

        # Cache some indices
        self._state_cov_idx = ('state_cov',) + np.diag_indices(k_posdef)

    @property
    def param_names(self):
        return ['A','T','sigma2.M', 'sigma2.P']

    @property
    def start_params(self):
        return [1,1]+[np.std(self.endog)]*2

    def transform_params(self, unconstrained):
        return np.concatenate([unconstrained[:2], unconstrained[2:]**2])

    def untransform_params(self, constrained):
        return np.concatenate([constrained[:2], constrained[2:]**0.5])

    def update(self, params, *args, **kwargs):
        params = super(KalmanFilter, self).update(params, *args, **kwargs)
        
        self.ssm['design'] = np.array([params[0]])
        self.ssm['transition'] = np.array([[params[1]]])
        
        # Observation covariance
        self.ssm['obs_cov',0,0] = params[2]

        # State covariance
        self.ssm[self._state_cov_idx] = params[3]
```

---

**Questions**:

1. Regarding **transform** / **untransform**: it appears to me that when transformed and untransformed the variance parameters will be constrained to [0, infty) in any case.

2. When I simulate some data:
```python
# parameters for simulated data
my_T  = 0.8
my_H  = 1
my_A  = 1
my_G  = 0.5
my_mu = 1

# Generate data
X = np.zeros(1000)
for t in range(1, len(X)):
    X[t] = my_T*X[t-1] + np.sqrt(my_H)*np.random.normal()

Y = my_mu + my_A*X + np.sqrt(my_G)*np.random.normal(size=len(X))
```
And fit the model:
```python
# Setup the model
mod = KalmanFilter(Y-1)

# Fit it using MLE
res = mod.fit(disp=True, maxiter=1000)
print(res.summary())
```
The results display a consistently highger than 1 estimate for `H`. 

3. How do I estimate `my_mu` from above? Should I just assume that the process of nu_t in the example gives always 1? In this way, the coefficient should give me the mu, right?

4. The estimated `sigma2.measurement` and `sigma2.predict` appear to be standard deviations, are they not?

**Comment by ChadFulton** [comment]
> Regarding transform / untransform: it appears to me that when transformed and untransformed the variance parameters will be constrained to [0, infty) in any case.

Yes, that is correct, and actually that's the whole point of the transform / untransform.

> When I simulate some data ... And fit the model ... The results display consistently: A<1 and H>1.

This is because the model you have written down does not uniquely identify the parameters. If you replace `A'=1` and `H'=H * A**2` then you will get a model with identical loglikelihood value (and `H'` will be close to 1).

> How do I estimate my_mu from above?

You would put it in the `obs_intercept` system matrix, like `self.ssm['obs_intercept', 0, 0] = params[5]` (or whatever parameter is supposed to be `my_mu`).

> The estimated sigma2.measurement and sigma2.predict appear to be standard deviations, are they not?

No, based on the way you set up the model, they are variances.

> Can you point me to where in the code is the MLE done? I've looked at the MLEModel class, and at its fit method. But, it appears to be calling another fit function which I don't know where it comes from.

You can look at `LikelihoodModel` in the file `statsmodels/base/model.py` and the `Optimizer` class in the file `statsmodels/base/optimizer.py`.

> In this setting, can I specify another distribution for the deviations?

Unfortunately no, our state space models do not support other distributions yet.

**Comment by sursu** [comment]
Thank you!

> Yes, that is correct, and actually that's the whole point of the transform / untransform.

So, if we look only at the variance parameters: it will search in an unconstrained space, find some values (for the variances), square them and use to evaluate the log-likelihood function. And then take the square root of those parameters to go back to the unconstrained space (which may not be the same value, but you don't really care as long as the the squared value gives the same constrained parameter) to find some other value in the neighborhood (or however the optimized commands).
Finally, the output will return the squared parameters, right?

This is something I'm not sure I understand.
The optimizer could go to some negative value, say `-u`, square it, evaluate the (log) likelihood function, then take square root, and obtain another value than the one it tried, say `u`. Then decide to go in some direction and arrive at a value which might just happen to be `-u`. Then it enters a loop and eventually exits the optimization.
Probably modern optimizers are smart enough not to do that. 

The transformation I'm used to is `exp` and `log`, and surely this gives the same result (maybe different values for the unidentifiable parameters). And the `log` will return you back to the unconstrained space to the same value you've tried.

Do you prefer **2 because it Is less computationally expensive?

---

What is your view on the fact that the the prediction goes outside the prediction CI?

**Comment by ChadFulton** [comment]
> So, if we look only at the variance parameters: it will search in an unconstrained space, find some values (for the variances), square them and use to evaluate the log-likelihood function. And then take the square root of those parameters to go back to the unconstrained space (which may not be the same value, but you don't really care as long as the the squared value gives the same constrained parameter) to find some other value in the neighborhood (or however the optimized commands).
Finally, the output will return the squared parameters, right?

Yes, all of this is correct.

> This is something I'm not sure I understand.
The optimizer could go to some negative value, say -u, square it, evaluate the (log) likelihood function, then take square root, and obtain another value than the one it tried, say u. Then decide to go in some direction and arrive at a value which might just happen to be -u. Then it enters a loop and eventually exits the optimization.
Probably modern optimizers are smart enough not to do that.

This is definitely possible, although in practice I haven't seen it - maybe you're right that modern optimizers are smart enough not to do this.

If it did happen, you would get a warning that the optimizer wasn't making good progress.

> The transformation I'm used to is exp and log, and surely this gives the same result (maybe different values for the unidentifiable parameters). And the log will return you back to the unconstrained space to the same value you've tried.

> Do you prefer **2 because it Is less computationally expensive?

I think that exp / log will probably work just as well. (My only concern would be that exp increases much faster with the argument than **2, and I wonder if that might make it slightly tougher on the optimizer? I have no idea though)

> What is your view on the fact that the the prediction goes outside the prediction CI?

I'm not quite sure - can you post the code you're using to make that graph?

**Comment by bashtage** [comment]
`exp` is dangerous since it is really easy to produce a NaN. In practice, a smoothed version of `exp` should be used that is exponential local to 0 but quadratic in its limits.

**Comment by sursu** [comment]
```python
import numpy as np
import statsmodels.api as sm
import plotly.graph_objects as go

# Simulated data parameters
my_mu = 1
my_A  = 1
my_T  = 0.8
my_G  = 0.5
my_H  = 1

# Generate data
X = np.zeros(1000)
for t in range(1, len(X)):
    X[t] = my_T*X[t-1] + np.sqrt(my_H)*np.random.normal()

Y = my_mu + my_A*X + np.sqrt(my_G)*np.random.normal(size=len(X))

class KalmanFilter(sm.tsa.statespace.MLEModel):
    """Linear Kalman Filter Model"""
    def __init__(self, endog):
        # Model order
        k_states = k_posdef = 1

        # Initialize the statespace
        super(KalmanFilter, self).__init__(
            endog, k_states=k_states, k_posdef=k_posdef,
            initialization='approximate_diffuse',
            loglikelihood_burn=k_states
        )

        # Initialize the matrices
        self.ssm['design'] = np.array([1]) # Fix A to 1
        self.ssm['selection'] = np.eye(k_states)

        # Cache some indices
        self._state_cov_idx = ('state_cov',) + np.diag_indices(k_posdef)

    @property
    def param_names(self):
        return ['μ','T','G','H']

    @property
    def start_params(self):
        return [1, 2] + [np.std(self.endog)]*2

    def transform_params(self, unconstrained):
        return np.concatenate([unconstrained[:3], np.exp(unconstrained[3:])])

    def untransform_params(self, constrained):
        return np.concatenate([constrained[:3], np.log(constrained[3:])])

    def update(self, params, *args, **kwargs):
        params = super(KalmanFilter, self).update(params, *args, **kwargs)
        
        self.ssm['obs_intercept',0,0] = params[0]
#         self.ssm['design'] = np.array([params[1]])
        self.ssm['transition'] = np.array([[params[1]]])

        
        # Observation covariance
        self.ssm['obs_cov',0,0] = params[2]

        # State covariance
        self.ssm[self._state_cov_idx] = params[3]



```

**Comment by ChadFulton** [comment]
I think you're shifting the confidence intervals relative to the predicted values so that they don't line up.

You can directly check that the predicted value lies within the confidence intervals by inspecting the values in `predict.summary_frame()`.

**Comment by sursu** [comment]
You are right, the 3rd `add_scatter` should be:
```python
fig.add_scatter(x = np.concatenate([predict_index[1:], predict_index[:0:-1]]), 
                y = np.concatenate([predict_ci[1:,0], predict_ci[1:,1][::-1]]), fill = 'toself', 
                line_width=0, showlegend=False)
```

Thanks a lot!

**Comment by ChadFulton** [comment]
Great!
