### ISSUE TITLE
How to return the parameters of an optimized simple exponential smoothing model?

### ISSUE THREAD

**Issue by xrzalreadytaken** [statsmodels/statsmodels#6149]
I was running a SimpleExpSmoothing model by the following code：
`fitses = SimpleExpSmoothing(np.asarray(train[item])).fit(optimized=True)`
How can I get the optimized parameter?
Thanks!

**Comment by bashtage** [comment]
statsmodels.org/devel/generated/generated/statsmodels.tsa.holtwinters.SimpleExpSmoothing.fit.html#statsmodels.tsa.holtwinters.SimpleExpSmoothing.fit

returns

http://www.statsmodels.org/devel/generated/statsmodels.tsa.holtwinters.HoltWintersResults.html#statsmodels.tsa.holtwinters.HoltWintersResults

which has an attribute `params`
