### ISSUE TITLE
MANOVA usage

### ISSUE THREAD

**Issue by TheChymera** [statsmodels/statsmodels#6155]
I have tried to use the MANOVA class based on [its description](https://www.statsmodels.org/stable/generated/statsmodels.multivariate.manova.MANOVA.html#statsmodels-multivariate-manova-manova), and I get:

```
Traceback (most recent call last):
  File "manova.py", line 7, in <module>
    model = MANOVA(endog=columns, exog='session')
  File "/usr/lib64/python3.6/site-packages/statsmodels/multivariate/manova.py", line 49, in __init__
    if len(endog.shape) == 1 or endog.shape[1] == 1:
AttributeError: 'list' object has no attribute 'shape'
```

I have uploaded a minimal working example here: http://chymera.eu/debug/statsmodels/manova.zip .

I assume this has to do with specifying the model formula, but I have no idea how I would do that, since I have not found any examples of what should be added to the dependent variable side of the equation. Should I put in all of the variable title fields? Like `<very long string> ~ session`? If so, how should I separate the variable titles in the dependent variable string? 

Put in plain language, what I am trying to do, is determine which of very many measures (correlations in activation between brain area combinations) are sensitive to the session variable.

**Comment by emilmirzayev** [comment]
It should be something like this
```python
MANOVA.from_formula("dependentVariable ~ independent1 + independent2", data = dataframeName)
```

**Comment by TheChymera** [comment]
@emilmirzayev But isn't the entire point of MANOVA that there is more than one dependent variable?

**Comment by TheChymera** [comment]
@emilmirzayev isn't it just an ANOVA if I have a single dependent variable?

**Comment by josef-pkt** [comment]
when not using the formula
endog needs to be numpy array or pandas dataframe. something with shape, and needs to be 2-dim
exog needs to be numeric

The first problem is a bug, we should check shape after converting array_likes to numpy.
But using a list would still be the wrong input.


pure numpy, this works for me

```
# convert exog to dummy in my old fashioned way
ex = (np.asarray(df['session'])[:,None] == np.unique(df['session'])).astype(np.float64)
model = MANOVA(endog=np.asarray(df[columns]), exog=ex)
res = model.mv_test()
print(res.summary())
```
But it looks like this doesn't make much sense, the result statistics look strange
my guess is that it is required that we have more observations than endog.
```
>>> model.endog.shape
(65, 1722)
```

using pandas also seems to work
`model = MANOVA(endog=df[columns], exog=ex)`

**Comment by josef-pkt** [comment]
BTW If there is no good documentation, then looking at the unit test cases often helps

**Comment by TheChymera** [comment]
Thank you, this worked!
