### ISSUE TITLE
Problem loading saved SARIMAX model from .pkl file: Can't get attribute 'FitStopper' 

### ISSUE THREAD

**Issue by willzappa** [statsmodels/statsmodels#6156]
#### Describe the bug

I'm trying to load a fitted SARIMAX model I saved earlier to a .pkl file and I get the following error:
AttributeError: Can't get attribute 'FitStopper' on <module '__main__'>

I'm using Spyder (Python 3.7) with statsmodels version 0.9.0. I can't find the attribute 'FitStopper' in any of the referenced files...any help here?

Thanks,

#### Code Sample, a copy-pastable example if possible

```python
    loadedModel = ARIMAResults.load("savedmodel.pkl")

  File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\base\model.py", line 1865, in load
    return load_pickle(fname)

  File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\iolib\smpickle.py", line 32, in load_pickle
    return cPickle.load(fin)

AttributeError: Can't get attribute 'FitStopper' on <module '__main__'>
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

I expect the saved model to be loaded.

**Comment by bashtage** [comment]
This is not a statsmodels problem.  `FitStopper` is not in statsmodels and does not appear to have ever been.

**Comment by bashtage** [comment]
You really should be used a more up-to-date version of statsmodels.

**Comment by bashtage** [comment]
Closing since not a sm issue.
