### ISSUE TITLE
PCA the sign of eigenvectors does not match with results from Stata

### ISSUE THREAD

**Issue by StevenLi-DS** [statsmodels/statsmodels#6170]
```python
df = webuse('audiometric')
pc = PCA(df[df.columns.drop('id')])
pc.loadings
```

![image](https://user-images.githubusercontent.com/33796896/65255266-94bad800-dacb-11e9-8a99-7597188291fe.png)

page 8 from https://www.stata.com/manuals13/mvpca.pdf
![image](https://user-images.githubusercontent.com/33796896/65255211-7fde4480-dacb-11e9-8449-c3695a2912fa.png)

```
INSTALLED VERSIONS
------------------
Python: 3.7.3.final.0

Statsmodels
===========

Installed: 0.9.0 (C:\Users\liqia\Anaconda3\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: 0.29.7 (C:\Users\liqia\Anaconda3\lib\site-packages\Cython)
numpy: 1.16.2 (C:\Users\liqia\Anaconda3\lib\site-packages\numpy)
scipy: 1.2.1 (C:\Users\liqia\Anaconda3\lib\site-packages\scipy)
pandas: 0.24.2 (C:\Users\liqia\Anaconda3\lib\site-packages\pandas)
    dateutil: 2.8.0 (C:\Users\liqia\Anaconda3\lib\site-packages\dateutil)
patsy: 0.5.1 (C:\Users\liqia\Anaconda3\lib\site-packages\patsy)
```

**Comment by bashtage** [comment]
If 

![image](https://user-images.githubusercontent.com/5585221/65256068-dc0a8e00-daf6-11e9-8cfa-49d19b16cac9.png)

is a matrix of eigenvectors then

![image](https://user-images.githubusercontent.com/5585221/65256103-e62c8c80-daf6-11e9-87eb-a8e03aed45db.png)

is also since 

![image](https://user-images.githubusercontent.com/5585221/65256037-ceed9f00-daf6-11e9-8b7f-992bbed7ecc3.png)

**Comment by StevenLi-DS** [comment]
Is there any way I can convert it? I read the doc, which doesn't seem to have such an option.

Btw, I must miss something, why the eigenvalues are so big? Should I just divide them by 100?

![image](https://user-images.githubusercontent.com/33796896/65256663-e6646200-dacd-11e9-8e49-3a2190b9c626.png)
![image](https://user-images.githubusercontent.com/33796896/65256814-2a576700-dace-11e9-95ac-7ada1a7561ba.png)

**Comment by bashtage** [comment]
Why do you want to convert it? Stata is as wrong as statsmodels.

Depends on whether the eigenvalue are computed from the covariance matrix (x.T@x/nobs) of the inner-product of the data (x.T@x).  They probably differ by a factor of `nobs`.  I assume you have 100 data points.

**Comment by bashtage** [comment]
The choice of sign of an element (usually the upper left) is called a normalization.  We use the normalization that is implicit in the underlying lapack library.

**Comment by bashtage** [comment]
Here is how Stata normalizes:

**The direction (sign) of principal components is not defined. pca returns principal components signed so that `1.T @ v > 0`**

**Comment by StevenLi-DS** [comment]
> They probably differ by a factor of nobs. 

Yeah, you are right. len(df) = 100

> Why do you want to convert it? Stata is as wrong as statsmodels.
Thanks for the explanation. I never looked at how Stata normalized it.
It's really fine for me, but sometimes...you are the only person using Python/SM in your class and trying to convince people to try it...you know...

**Comment by StevenLi-DS** [comment]
btw, this `comp_0` is a little bit confusing even though python is zero-indexing. what do you think?

**Comment by bashtage** [comment]
0 is pretty clear from a python pov.

**Comment by StevenLi-DS** [comment]
I just check the source code but didn't find what I was looking for. The doc states that     

> Note that the principal components are computed using a SVD and so the correlation matrix is never constructed, unless method='eig'.
PCA using the covariance matrix of the data

Does this mean if I wanna perform PCA based on the correlation matrix of the data, I just need to pass `method='eig'`?

**Comment by bashtage** [comment]
No, it is the same calculation only using a method that is faster than computing the correlation and then an computing the eigen decomposition.  You will get the same results in most cases for the two methods (possibly up to a +/-1 sign).

**Comment by StevenLi-DS** [comment]
indeed, I verified the result with the following package.
https://hoggorm.readthedocs.io/en/latest/pca.html

Any plane to add variance explained and cumulative variance explained? The recent workflow is a little bit tedious.

**Comment by StevenLi-DS** [comment]
Btw, do we have an equivalent method/arg for rotation? 
https://discuss.analyticsvidhya.com/t/what-does-rotation-in-pca-do/4277

**Comment by bashtage** [comment]
> Any plane to add variance explained and cumulative variance explained? The recent workflow is a little bit tedious.

Those are already present in `rsquare`. You have to cumulate youeself, but just a cumsum. 

http://www.statsmodels.org/devel/generated/statsmodels.multivariate.pca.PCA.html?highlight=pca#statsmodels.multivariate.pca.PCA

> Btw, do we have an equivalent method/arg for rotation?

Nope.  Not sure what this does from the description there.

**Comment by josef-pkt** [comment]
>Btw, do we have an equivalent method/arg for rotation?

We bundle or include code for rotation, but AFAIK it's still only an option in factor analysis.

**Comment by StevenLi-DS** [comment]
@bashtage my understanding is that it's used to change the loadings for better interpretation https://youtu.be/xNTsAVj0t7U?t=819

**Comment by StevenLi-DS** [comment]
I happened to come across this paper https://www.pnas.org/content/pnas/112/25/7629.full.pdf

**Comment by StevenLi-DS** [comment]
I recently run into this sign problem again. I really think by keeping most of the sign postive is easier to explain the results. Any chance we can change that or add an param?
