### ISSUE TITLE
ARIMAX.filter output

### ISSUE THREAD

**Issue by alialsaq** [statsmodels/statsmodels#6175]
I am doing the following for a 1d array 'x':

```
# Stationarity Test
res = sm.tsa.stattools.adfuller(x)
print(res)
# Identification
my_fit = sm.tsa.stattools.arma_order_select_ic(x, max_ar=4, max_ma=4, ic='aic', trend='c', model_kw=None, fit_kw=None)
print(my_fit['aic_min_order'])
# Estimation
mod = sm.tsa.statespace.SARIMAX(x,order=(3,0,3),seasonal_order=(0,0,0,0))
res = mod.fit(disp=False)
print(res.summary())
# Diagnostics
res.plot_diagnostics(figsize=(13, 5));
# Kalman Filter
my_kalman = mod.filter(x, transformed=True, complex_step=False, cov_type=None, cov_kwds=None, return_ssm=True)
```
Now, how do I get my filtered data? I can't find documentation for what the output class is after filtering.

**Comment by ChadFulton** [comment]
> Now, how do I get my filtered data? I can't find documentation for what the output class is after filtering.

It's not totally clear to me what you mean by the filtered data, but I think you probably want:

```python
res.resid
```

This gives the values after the ARMA filter is applied. More specificallt: the model is an equation of the form:

b(L) y_t = a(L) e_t

and `res.resid` is `e_t`, for a particular assumption about the initial conditions.

**Comment by ChadFulton** [comment]
Closing as answered, but feel free to re-open and/or reply if this didn't solve your issue.
