### ISSUE TITLE
Which test is used for significance (oddsratio_pvalue) in Table2x2 ?

### ISSUE THREAD

**Issue by ljmartin** [statsmodels/statsmodels#6180]
Hi all, thanks for your work on statsmodels. 
The oddsratio_pvalue method of a Table2x2 seems clear enough in the code, but can someone let me know what test is being performed here? Is it a chi-square test?
Going back through the documentation I found this: https://github.com/statsmodels/statsmodels/issues/2607 implying it uses an unconditional exact test but it doesn't look like it. 
Thanks!

**Comment by kshedden** [comment]
The p-value is based on a Wald-type z-test for the standard estimate of the
log odds ratio.  It uses the asymptotic approximation for the standard
error.  It is a large-sample test.  Testing log odds = 0 is the same as
testing for independence of rows/columns using the chi^2 test, difference
of conditional proportions test, the likelihood rato test, or Fisher's
exact test.  If I remember correctly, these tests are all different in
finite samples, but asymptotically equivalent.

**Comment by josef-pkt** [comment]
issue #2607 and similar issues are for additional tests for proportions in one, two or k-sample case.
Those have better small sample properties than wald tests.
In small samples Wald tests for proportions are usually liberal and Fisher's exact tests is conservative.

Those other tests have usually better small sample properties, but are also more sensitive to assumption about the distribution and sampling scheme

**Comment by ljmartin** [comment]
Great - thankyou!
