### ISSUE TITLE
BUG: dynamic factor start_params may be explosive with autoregressive errors

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#6182]
Currently we just take a shortcut in `start_params` where if the error terms are individual ARs, rather than jointly as a VAR, we still estimate a VAR and then take the diagonal elements of each coefficient matrix to get the AR parameters. But these may not lead to stationary models.

**Comment by aghinsa** [comment]
Hey, I'd like to contribute towards this issue,but I'm new to opensource,can you provide some description/way-points to start.Thanks.

**Comment by ChadFulton** [comment]
Thanks @aghinsa! You can start by taking a look at lines 518 - 544 of the file [`statsmodels/tsa/statespace/dynamic_factor.py`](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/statespace/dynamic_factor.py#L518).

Basically, the idea here is that the error terms in the dynamic factor model can be modeled as autocorrelated rather than as white noise. This is specified in the model by setting the `error_order` argument to be greater than zero.

In that case, we need to estimate starting parameters for the autoregressive model that generates those errors. There are two ways to do this: first, we might think that each individual error term follows an AR(p) process, or second we might think that all of the error terms jointly follow a VAR(p) process. This is specified in the model by setting the `error_var` argument to be False (for the individual AR models) or True (for the joint VAR model).

This is what is done in the lines 518 - 544, as follows:

- In lines 518-520 we estimate a VAR model to get starting coefficients for the error transitions.
- In lines 522 - 533 we make sure those coefficients are stationary *for a VAR process*.
- In lines 537 - 538, we set the coefficients in the joint VAR case
- In lines 543 - 544, we set the coefficients in the individual AR(p) case by just taking the diagonal elements of the VAR coefficients, but this isn't always going to work, and that's why this message is here.

So what I think we need to do is put the `if self.error_var` conditional around all of the code in lines 518 - 538, and then create a new procedure for the `else` case.

That alternative procedure should be to get start params for an AR(p) model from each of the columns of `endog` separately. In fact, I would just set up an SARIMAX model and then get that model's `start_params` (i.e. no need to `fit` the model).
