### ISSUE TITLE
DESIGN: state space `low_memory` 

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#6188]
Currently the `low_memory=True` argument to `fit` in state space models performs maximum memory conservation, so that (if I remember right) no Kalman filter output of length `nobs` is stored.

This is particularly useful when `nobs` and `k_states` are both large because the conditional covariance matrix storage has `nobs * k_states**2` elements.

Models fit this way are still useful for forecasting (and e.g. cross-validation-type model selection exercises), since that only depends on the final state estimates, but they can't do much else. For example, they done even have `fittedvalues` or `resid`.

The question here is: should we change `low_memory=True` to allow storing some or all of the `nobs * k_states` vectors. I guess the first thing to add back in would be `fittedvalues` and/or `resid`.

NB: regardless of what is decided for the `low_memory` option, users will still free to select custom memory conservation options directly (e.g. `mod.ssm.memory_no_filtered=True`), but this isn't well documented, and isn't flexible enough right now to allow keeping the `nobs * k_states` arrays while dropping the `nobs * k_states**2` arrays.

**Comment by david-waterworth** [comment]
Would storing  the `fittedvalues` - adding `nobs` memory overhead, and compute the residuals etc on demand be a good compromise? Ideally you'd end up with the same functionality but with a different space / time tradeoff? So store whatever you need to evaluate the filter, and then `resid` etc effectively does a predict, applies the loss function and returns the result without holding a reference.

**Comment by ChadFulton** [comment]
> Would storing the fittedvalues - adding nobs memory overhead, and compute the residuals etc on demand be a good compromise?

Thanks for the input. I agree, this seems like a good idea.

It will probably be best to get this change in for a v0.11 release.

**Comment by ChadFulton** [comment]
> > Would storing the fittedvalues - adding nobs memory overhead, and compute the residuals etc on demand be a good compromise?
> 
> Thanks for the input. I agree, this seems like a good idea.

For simplicity, I think the change that I will implement for v0.11 will be for the default `low_memory` option to store all `k_endog x nobs` arrays (so that is `forecasts`, `forecast_errors`, `standardized_forecast_errors`) and the two `k_states x nobs` arrays (`predicted_state`, and `filtered_state`).

In the PR that I will submit soon, there will be fine grained controls so that users can choose not to store any or all of those, but I think that keeping all of these will work best as the default.

My thinking is that the main problem is the `k_states**2 x nobs` arrays.
