### ISSUE TITLE
BUG: Forecasting SARIMAX with data indexing by Int64Index where simple_differencing=True

### ISSUE THREAD

**Issue by yahalom1** [statsmodels/statsmodels#6193]
**Description**
When forecasting some Sarimax models, that built with Pandas DataFrame indexed by pd.Int64Index and the model build with setting simple_differencing to True the forecast function raise an error.

**Code sample**

```python
import statsmodels.api as sm
import pandas as pd

data = pd.Series([1,2,1,2,1,2,12,1,3,6,4,1,6,5,1,5,3,1,6,5,4,1,6,4,2,3,1,1,2,1,2,3,1,3,2,1,2,3,1,3,2,1,6,5,3,2,1,2])
model = sm.tsa.SARIMAX(data,order=(0,1,1),simple_differencing = True).fit(disp=False)
 
model.forecast()
```
success and give

> 48    0.627449
>dtype: float64.

 But the code 

```python
data = pd.Series([1,2,1,2,1,2,12,1,3,6,4,1,6,5,1,5,3,1,6,5,4,1,6,4,2,3,1,1,2,1,2,3,1,3,2,1,2,3,1,3,2,1,6,5,3,2,1,2])
data.index = pd.Int64Index(data.index)
model = sm.tsa.SARIMAX(data,order=(0,1,1),simple_differencing = True).fit(disp=False)

model.forecast()

```
raise an error

> Traceback (most recent call last):
> 
>   File "<ipython-input-45-87d05bd4ab9b>", line 1, in <module>
>     model.forecast()
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\base\wrapper.py", line 95, in wrapper
>     obj = data.wrap_output(func(results, *args, **kwargs), how)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 2484, in forecast
>     return self.predict(start=self.nobs, end=end, **kwargs)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py", line 2457, in predict
>     prediction_results = self.get_prediction(start, end, dynamic, **kwargs)
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\sarimax.py", line 1894, in get_prediction
>     self.model._get_prediction_index(start, end, index, silent=True))
> 
>   File "C:\ProgramData\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py", line 524, in _get_prediction_index
>     raise KeyError('The `start` argument could not be matched to a'
> 
> KeyError: 'The `start` argument could not be matched to a location related to the index of the data.'

**Comment by ChadFulton** [comment]
Thanks very much for this report!
