### ISSUE TITLE
cvxpot module necessity is not mentioned 

### ISSUE THREAD

**Issue by emilmirzayev** [statsmodels/statsmodels#6196]
#### Describe the bug

When working on #6191 and fitting L1 regression on `OLS.fit_regularized(method = "lasso_sqrt")` this message comes up:
```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py in _sqrt_lasso(self, alpha, refit, zero_tol)
   1036         try:
-> 1037             import cvxopt
   1038         except ImportError:

ModuleNotFoundError: No module named 'cvxopt'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-22-3fd115255e32> in <module>
      1 lasso_results = sm.OLS(endog = df[endog_name], 
      2                        exog = df[exog_names],
----> 3                        missing= "drop").fit_regularized(method= "sqrt_lasso")

~\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py in fit_regularized(self, method, alpha, L1_wt, start_params, profile_scale, refit, **kwargs)
    998                 RegularizedResults, RegularizedResultsWrapper
    999             )
-> 1000             params = self._sqrt_lasso(alpha, refit, defaults["zero_tol"])
   1001             results = RegularizedResults(self, params)
   1002             return RegularizedResultsWrapper(results)

~\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py in _sqrt_lasso(self, alpha, refit, zero_tol)
   1038         except ImportError:
   1039             msg = "sqrt_lasso fitting requires the cvxopt module to be installed"
-> 1040             raise ValueError(msg)
   1041 
   1042         n = len(self.endog)

ValueError: sqrt_lasso fitting requires the cvxopt module to be installed
```
However, neither in the [documentation](https://www.statsmodels.org/stable/generated/statsmodels.regression.linear_model.OLS.fit_regularized.html?highlight=ols%20regularized#statsmodels.regression.linear_model.OLS.fit_regularized), nor in [dependencies section](https://www.statsmodels.org/stable/install.html#dependencies) of statsmodels **cvxpot** is mentioned.

However, in `sm.show_versions()` cvxpot is in dependencies list.

#### Code Sample, a copy-pastable example if possible

```python

lasso_results = sm.OLS(endog = df[endog_name], 
                       exog = df[exog_names], 
                       missing= "drop").fit_regularized(method= "sqrt_lasso")
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
Python: 3.7.4.final.0

Statsmodels
===========

Installed: 0.10.1 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: 0.29.13 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\Cython)
numpy: 1.16.5 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\numpy)
scipy: 1.3.1 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\scipy)
pandas: 0.25.1 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\pandas)
    dateutil: 2.8.0 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\dateutil)
patsy: 0.5.1 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.1.1 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 0.13.2 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\joblib)

Developer Tools
================

IPython: 7.8.0 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\IPython)
    jinja2: 2.10.1 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\jinja2)
sphinx: 2.2.0 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\sphinx)
    pygments: 2.4.2 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages\pygments)
pytest: 5.2.0 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages)
virtualenv: 16.7.5 (C:\Users\Emil Mirzayev\Anaconda3\lib\site-packages)

</details>

**Comment by bashtage** [comment]
Fixed in master.

**Comment by StevenLi-DS** [comment]
I tried to install cvxpot and then realized it's `cvxopt`.

@emilmirzayev could you fix the title in case someone confuses like me...XD

**Comment by josef-pkt** [comment]
that's funny

title changed
