### ISSUE TITLE
Formulas can't be parsed if a number is leading the column name

### ISSUE THREAD

**Issue by Nathan-Furnal** [statsmodels/statsmodels#6200]
```
import pandas as pd
import numpy as np
import statsmodels.api as sm

tmp = pd.DataFrame({'A1':np.random.randint(1,10,100),
                    '1B':np.random.randint(0, 5, 100),
                    'C':np.random.choice(['blue', 'green'], 100),
                     'y': np.random.randint(1, 12, 100)})

sm.OLS.from_formula(formula = 'y ~ A1 + 1B + C', data = tmp)
```

Will return : 

> Traceback (most recent call last):
> 
>   File "C:\Users\natha\Miniconda3\envs\ml\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
> 
>   File "<ipython-input-272-6ec147bf863f>", line 1, in <module>
>     sm.OLS.from_formula(formula = 'y ~ A1 + 1B + C', data = tmp)
> 
>   File "C:\Users\natha\Miniconda3\envs\ml\lib\site-packages\statsmodels\base\model.py", line 159, in from_formula
>     missing=missing)
> 
>   File "C:\Users\natha\Miniconda3\envs\ml\lib\site-packages\statsmodels\formula\formulatools.py", line 65, in handle_formula_data
>     NA_action=na_action)
> 
>   File "C:\Users\natha\Miniconda3\envs\ml\lib\site-packages\patsy\highlevel.py", line 310, in dmatrices
>     NA_action, return_type)
> 
>   File "C:\Users\natha\Miniconda3\envs\ml\lib\site-packages\patsy\highlevel.py", line 165, in _do_highlevel_design
>     NA_action)
> 
>   File "C:\Users\natha\Miniconda3\envs\ml\lib\site-packages\patsy\highlevel.py", line 70, in _try_incr_builders
>     NA_action)
> 
>   File "C:\Users\natha\Miniconda3\envs\ml\lib\site-packages\patsy\build.py", line 689, in design_matrix_builders
>     factor_states = _factors_memorize(all_factors, data_iter_maker, eval_env)
> 
>   File "C:\Users\natha\Miniconda3\envs\ml\lib\site-packages\patsy\build.py", line 354, in _factors_memorize
>     which_pass = factor.memorize_passes_needed(state, eval_env)
> 
>   File "C:\Users\natha\Miniconda3\envs\ml\lib\site-packages\patsy\eval.py", line 474, in memorize_passes_needed
>     subset_names = [name for name in ast_names(self.code)
> 
>   File "C:\Users\natha\Miniconda3\envs\ml\lib\site-packages\patsy\eval.py", line 474, in <listcomp>
>     subset_names = [name for name in ast_names(self.code)
> 
>   File "C:\Users\natha\Miniconda3\envs\ml\lib\site-packages\patsy\eval.py", line 105, in ast_names
>     for node in ast.walk(ast.parse(code)):
> 
>   File "C:\Users\natha\Miniconda3\envs\ml\lib\ast.py", line 35, in parse
>     return compile(source, filename, mode, PyCF_ONLY_AST)
> 
>   File "<unknown>", line 1
>     1 B
>       ^
> SyntaxError: invalid syntax

I'm not sure if this is intended behavior but it did take me by surprise.

Is it a patsy problem ?

**Comment by bashtage** [comment]
Yes, this is a patsy limitation.

**Comment by bashtage** [comment]
Closing since no fix possible.

**Comment by josef-pkt** [comment]
patsy has a `Q`, for quote, operator in the formulas that can be used when the name is not a valid python name.
see patsy documentation, and there are some stackoverflow questions and answers AFAIR
