### ISSUE TITLE
Missing parameter check in anderson_statistic

### ISSUE THREAD

**Issue by david-waterworth** [statsmodels/statsmodels#6207]
I was reading the source for `anderson_statistic` and I notice that [_adnorm.py#L40](https://github.com/statsmodels/statsmodels/blob/727dca48948c54257dda8be4f6d5a2e72d5160d3/statsmodels/stats/_adnorm.py#L40) doesn't properly check arguments inside the `fit==True` branch (there should be a final `else` which throws with a message "fit==True either dist='norm" or Callable"?

**Comment by emilmirzayev** [comment]
Will there be a need for adding also a test for that?

**Comment by josef-pkt** [comment]
Yes to both

There is still a stray print in the callable part. Most likely that branch doesn't have a unit test
