### ISSUE TITLE
Errors: documentation for ARMAprocess

### ISSUE THREAD

**Issue by robsalomone** [statsmodels/statsmodels#6218]
The documentation for the ARMAprocess class is a bit vague in terms of its parametrization, and has some errors in the explanation:
---
<img width="857" alt="Screen Shot 2019-10-27 at 2 24 09 pm" src="https://user-images.githubusercontent.com/37037906/67629099-81b6d700-f8c5-11e9-9b51-75ea27dfcae9.png">
---
(1) Right hand side should have \epsilon_t after the lag polynomial. 
(2) The right hand side should have plus signs in the polynomial (follows directly from line above it). 
(3) Documentation should make clearer that you need to specify directly the terms in the lag polynomial **including** their signs,  eg., (1, -phi_1, -phi_2), and (1, theta_1, theta_2).

Problems just seem to be with the documentation.

**Comment by josef-pkt** [comment]
https://www.statsmodels.org/dev/generated/statsmodels.tsa.arima_process.ArmaProcess.html

yes to all 3
point (3) can also be seen in the example
