### ISSUE TITLE
DOC: misleading comment at sarimax.py says we raise an error, but we actually zero the start_params

### ISSUE THREAD

**Issue by ihadanny** [statsmodels/statsmodels#6224]
at sarimax.py, line 953: 
`If we have estimated non-stationary start parameters but enforce stationarity is on, raise an error` is misleading. Actually the code just warn and then zero out the coefficients `params_ar *= 0`.

**Comment by ChadFulton** [comment]
Thanks for pointing this out. If you have time, it would be great if you could submit a PR to fix this comment.
