### ISSUE TITLE
Sample Prediction of Time Series Data:

### ISSUE THREAD

**Issue by disojn** [statsmodels/statsmodels#6234]
My full code is:

pred = results_default.get_prediction(start=pd.to_datetime('2017-12-22'), dynamic=False)
pred_ci = pred.conf_int()
ax = y['2014':].plot(label='observed')
pred.predicted_mean.plot(ax=ax, label='One-step ahead Forecast', alpha=.7, figsize=(14, 7))
ax.fill_between(pred_ci.index,
                pred_ci.iloc[:, 0],
                pred_ci.iloc[:, 1], color='k', alpha=.2)
ax.set_xlabel('Order Date')
ax.set_ylabel('Technology Sales')
plt.legend()
plt.show()

KeyError                                  Traceback (most recent call last)
pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

KeyError: 1513900800000000000

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2896             try:
-> 2897                 return self._engine.get_loc(key)
   2898             except KeyError:

pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

KeyError: Timestamp('2017-12-22 00:00:00')

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

KeyError: 1513900800000000000

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py in _get_index_label_loc(self, key, base_index)
    425                 if not isinstance(key, (int, long, np.integer)):
--> 426                     loc = self.data.row_labels.get_loc(key)
    427                 else:

~\Anaconda3\lib\site-packages\pandas\core\indexes\datetimes.py in get_loc(self, key, method, tolerance)
   1038                 key = Timestamp(key).tz_convert(self.tz)
-> 1039             return Index.get_loc(self, key, method, tolerance)
   1040 

~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2898             except KeyError:
-> 2899                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2900         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

KeyError: Timestamp('2017-12-22 00:00:00')

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py in _get_prediction_index(self, start, end, index, silent)
    521         try:
--> 522             start, start_index, start_oos = self._get_index_label_loc(start)
    523         except KeyError:

~\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py in _get_index_label_loc(self, key, base_index)
    457             except:
--> 458                 raise e
    459         return loc, index, index_was_expanded

~\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py in _get_index_label_loc(self, key, base_index)
    421             loc, index, index_was_expanded = (
--> 422                 self._get_index_loc(key, base_index))
    423         except KeyError as e:

~\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py in _get_index_loc(self, key, base_index)
    354             # (note that get_loc will throw a KeyError if key is invalid)
--> 355             loc = index.get_loc(key)
    356         elif int_index or range_index:

~\Anaconda3\lib\site-packages\pandas\core\indexes\datetimes.py in get_loc(self, key, method, tolerance)
   1038                 key = Timestamp(key).tz_convert(self.tz)
-> 1039             return Index.get_loc(self, key, method, tolerance)
   1040 

~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2898             except KeyError:
-> 2899                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2900         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

KeyError: Timestamp('2017-12-22 00:00:00')

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-68-086a33670568> in <module>
----> 1 pred = results_default.get_prediction(start=pd.to_datetime('2017-12-22'), dynamic=False)
      2 pred_ci = pred.conf_int()
      3 ax = y['2014':].plot(label='observed')
      4 pred.predicted_mean.plot(ax=ax, label='One-step ahead Forecast', alpha=.7, figsize=(14, 7))
      5 ax.fill_between(pred_ci.index,

~\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\sarimax.py in get_prediction(self, start, end, dynamic, index, exog, **kwargs)
   1892         # Handle start, end, dynamic
   1893         _start, _end, _out_of_sample, prediction_index = (
-> 1894             self.model._get_prediction_index(start, end, index, silent=True))
   1895 
   1896         # Handle exogenous parameters

~\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py in _get_prediction_index(self, start, end, index, silent)
    522             start, start_index, start_oos = self._get_index_label_loc(start)
    523         except KeyError:
--> 524             raise KeyError('The `start` argument could not be matched to a'
    525                            ' location related to the index of the data.')
    526         if end is None:

KeyError: 'The `start` argument could not be matched to a location related to the index of the data.'

Kindly request you to take a look at it.
Thanks and Regards
Disoj

**Comment by disojn** [comment]
Technology.sample(10)

                         | Sales
--Date | --  

2017-01-24 | 110.352
2017-01-27 | 317.898
2015-05-02 | 158.376
2014-07-27 | 238.000
2015-08-08 | 79.990
2017-08-21 | 465.148
2016-05-21 | 2517.836
2017-05-02 | 159.560
2017-05-01 | 48.900
2015-07-31 | 2549.350

where Date is index

**Comment by ChadFulton** [comment]
Thanks for this report. We will need two things to be able to follow up:

1. The example needs to be fully self-contained, meaning that we run exactly the code you have posted and get the error you're reporting.
    a. You need to give all of your code, including the part where you create and fit the model.
    b. You need to post a full dataset that replicates the problem.

2. Please post the results of ``import statsmodels.api as sm; sm.show_versions()``

**Comment by disojn** [comment]
INSTALLED VERSIONS
------------------
Python: 3.7.3.final.0

Statsmodels
===========

Installed: 0.10.1 (C:\Users\disoj\Anaconda3\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: 0.29.6 (C:\Users\disoj\Anaconda3\lib\site-packages\Cython)
numpy: 1.16.2 (C:\Users\disoj\Anaconda3\lib\site-packages\numpy)
scipy: 1.2.1 (C:\Users\disoj\Anaconda3\lib\site-packages\scipy)
pandas: 0.25.1 (C:\Users\disoj\Anaconda3\lib\site-packages\pandas)
    dateutil: 2.8.0 (C:\Users\disoj\Anaconda3\lib\site-packages\dateutil)
patsy: 0.5.1 (C:\Users\disoj\Anaconda3\lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.0.3 (C:\Users\disoj\Anaconda3\lib\site-packages\matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 0.13.2 (C:\Users\disoj\Anaconda3\lib\site-packages\joblib)

Developer Tools
================

IPython: 7.4.0 (C:\Users\disoj\Anaconda3\lib\site-packages\IPython)
    jinja2: 2.10 (C:\Users\disoj\Anaconda3\lib\site-packages\jinja2)
sphinx: 1.8.5 (C:\Users\disoj\Anaconda3\lib\site-packages\sphinx)
    pygments: 2.3.1 (C:\Users\disoj\Anaconda3\lib\site-packages\pygments)
pytest: 4.3.1 (C:\Users\disoj\Anaconda3\lib\site-packages)
virtualenv: Not installed

**Comment by disojn** [comment]
Arima Model:
mod_default = sm.tsa.statespace.SARIMAX(ts,
                                order=(0, 0, 0),
                                seasonal_order=(1, 0 , 1, 12),
                                enforce_stationarity=False,
                                enforce_invertibility=False)

results_default = mod_default.fit()

**Comment by disojn** [comment]
Technology.index
Outputs:

DatetimeIndex(['2014-01-06', '2014-01-09', '2014-01-13', '2014-01-15',
               '2014-01-16', '2014-01-20', '2014-01-26', '2014-02-01',
               '2014-02-02', '2014-02-06',
               ...
               '2017-12-18', '2017-12-21', '2017-12-22', '2017-12-23',
               '2017-12-24', '2017-12-25', '2017-12-27', '2017-12-28',
               '2017-12-29', '2017-12-30'],
              dtype='datetime64[ns]', name='Order Date', length=824, freq=None)

 Validating forecasts
# To help us understand the accuracy of our forecasts, 
# we compare predicted sales to real sales of the time series, and we set forecasts 
# to start at 2017–01–01 to the end of the data.
 pred = results_default.get_prediction(start=pd.to_datetime('2017-01-01'), dynamic=False)
pred_ci = pred.conf_int()
ax = Technology.loc['2014':]['Sales'].plot(label='observed')

pred.predicted_mean.plot(ax=ax, label='One-step ahead Forecast', alpha=.7)

ax.fill_between(pred_ci.index,
                pred_ci.iloc[:, 0],
                pred_ci.iloc[:, 1], color='k', alpha=.2)

ax.set_xlabel('Order Date')
ax.set_ylabel('Technology Sales')
plt.legend()
plt.show()

**Comment by disojn** [comment]
I have all required dependencies are up-to-date as I checked earlier

**Comment by ChadFulton** [comment]
Thank you, but we still cannot narrow this down unless you can provide a full dataset that replicates the problem.  For example, you could post a CSV file along with the code to read it into a Pandas series.

**Comment by disojn** [comment]
Thanks for suggestion, but I am not being able to upload my xls file here.

**Comment by ChadFulton** [comment]
Sorry to hear that. I'm going to close this issue as non-replicable, but feel free to re-open it if you find a dataset that you can upload so that we can replicate your issue.

**Comment by disojn** [comment]
It is a superstore dataset extracted from Tableau Forum community and I have performed the following codes:

**Comment by bashtage** [comment]
You can provide a simulated dataset that produces the same problem. You can
also just include code at the top of your example that simulates data and
then use this data to produce the error.

**Comment by disojn** [comment]
location=("C://Users//disoj//Desktop//Datasets//DATASETS//Superstore.xls")
data_original = pd.read_excel(location)
# categories of sales data
data_original.Category.value_counts()
# copy only the rows related to category = Technology
Technology = data_original.loc[data_original['Category'] == 'Technology']
# data_original range
Technology['Order Date'].min(), Technology['Order Date'].max()
Technology.columns
Output: Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

# columns to drop
cols = ['Row ID', 
        'Order ID', 
        'Ship Date', 
        'Ship Mode', 
        'Customer ID', 
        'Customer Name', 
        'Segment', 
        'Country', 
        'City', 
        'State', 
        'Postal Code', 
        'Region', 
        'Product ID', 
        'Category', 
        'Sub-Category', 
        'Product Name', 
        'Quantity', 
        'Discount', 
        'Profit']

Technology.drop(cols, axis=1, inplace=True)
Technology.columns
Index(['Order Date', 'Sales'], dtype='object')

# Lets check if we have more than one sales data for a date:
temp = Technology.groupby('Order Date')['Sales'].size() 
temp[temp > 1].sort_values(ascending=False)

# aggregate sales by date
Technology = Technology.groupby('Order Date')['Sales'].sum().reset_index()
# Indexing with Time Series Data
Technology = Technology.set_index('Order Date')
Technology.index

Building up ARIMA Model:
mod_default = sm.tsa.statespace.SARIMAX(ts,
                                order=(0, 0, 0),
                                seasonal_order=(1, 0 , 1, 12),
                                enforce_stationarity=False,
                                enforce_invertibility=False)

results_default = mod_default.fit()

pred = results_default.get_prediction(start=pd.to_datetime('2017-01-01'), dynamic=False)
pred_ci = pred.conf_int()
ax = Technology.loc['2014':]['Sales'].plot(label='observed')

pred.predicted_mean.plot(ax=ax, label='One-step ahead Forecast', alpha=.7)

ax.fill_between(pred_ci.index,
                pred_ci.iloc[:, 0],
                pred_ci.iloc[:, 1], color='k', alpha=.2)

ax.set_xlabel('Order Date')
ax.set_ylabel('Technology Sales')
plt.legend()
plt.show()


Error:





---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

KeyError: 1483228800000000000

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2896             try:
-> 2897                 return self._engine.get_loc(key)
   2898             except KeyError:

pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

KeyError: Timestamp('2017-01-01 00:00:00')

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

KeyError: 1483228800000000000

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py in _get_index_label_loc(self, key, base_index)
    425                 if not isinstance(key, (int, long, np.integer)):
--> 426                     loc = self.data.row_labels.get_loc(key)
    427                 else:

~\Anaconda3\lib\site-packages\pandas\core\indexes\datetimes.py in get_loc(self, key, method, tolerance)
   1038                 key = Timestamp(key).tz_convert(self.tz)
-> 1039             return Index.get_loc(self, key, method, tolerance)
   1040 

~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2898             except KeyError:
-> 2899                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2900         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

KeyError: Timestamp('2017-01-01 00:00:00')

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py in _get_prediction_index(self, start, end, index, silent)
    521         try:
--> 522             start, start_index, start_oos = self._get_index_label_loc(start)
    523         except KeyError:

~\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py in _get_index_label_loc(self, key, base_index)
    457             except:
--> 458                 raise e
    459         return loc, index, index_was_expanded

~\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py in _get_index_label_loc(self, key, base_index)
    421             loc, index, index_was_expanded = (
--> 422                 self._get_index_loc(key, base_index))
    423         except KeyError as e:

~\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py in _get_index_loc(self, key, base_index)
    354             # (note that get_loc will throw a KeyError if key is invalid)
--> 355             loc = index.get_loc(key)
    356         elif int_index or range_index:

~\Anaconda3\lib\site-packages\pandas\core\indexes\datetimes.py in get_loc(self, key, method, tolerance)
   1038                 key = Timestamp(key).tz_convert(self.tz)
-> 1039             return Index.get_loc(self, key, method, tolerance)
   1040 

~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2898             except KeyError:
-> 2899                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2900         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.DatetimeEngine.get_loc()

KeyError: Timestamp('2017-01-01 00:00:00')

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-151-a45fecbd6cb3> in <module>
      1 
----> 2 pred = results_default.get_prediction(start=pd.to_datetime('2017-01-01'), dynamic=False)
      3 pred_ci = pred.conf_int()
      4 ax = Technology.loc['2017':]['Sales'].plot(label='observed')
      5 

~\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\sarimax.py in get_prediction(self, start, end, dynamic, index, exog, **kwargs)
   1892         # Handle start, end, dynamic
   1893         _start, _end, _out_of_sample, prediction_index = (
-> 1894             self.model._get_prediction_index(start, end, index, silent=True))
   1895 
   1896         # Handle exogenous parameters

~\Anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py in _get_prediction_index(self, start, end, index, silent)
    522             start, start_index, start_oos = self._get_index_label_loc(start)
    523         except KeyError:
--> 524             raise KeyError('The `start` argument could not be matched to a'
    525                            ' location related to the index of the data.')
    526         if end is None:

KeyError: 'The `start` argument could not be matched to a location related to the index of the data.'
