### ISSUE TITLE
anova_lm

### ISSUE THREAD

**Issue by sunyu90325** [statsmodels/statsmodels#6236]
Hi,
In the analysis of multivariate regression, anova_lm method throws Exception when the number of factors in x is greater than the number of observations in that factor

#### python code
mod = sfa.ols(function,data=dataf)
fit_result = mod.fit()
aov_table = sa.stats.anova_lm(fit_result, typ=1)

#### When I have more columns than rows,  I have this:
18 is # of factors, 16 is # of observation
shapes (18,18) and (16,) not aligned: 18 (dim 1) != 16 (dim 0)

#### This returns the number of observations rather than the number of factors      
q,r = np.linalg.qr(exog)

With the same input, R can produce the correct results.
Thanks.

**Comment by josef-pkt** [comment]
IIUC, you have more explanatory variables and parameters than observations. 
You cannot really have inference in that case because parameters cannot be estimated in the usual sense, df_resid is negative in the full model..

What does R do in this case?

please add the full traceback to see where this actually breaks.

**Comment by sunyu90325** [comment]
Thanks for replying so quick.
Here is the full trace:
Traceback (most recent call last):
  File "C:\Workspaces\disco\trunk\firstPythonProject\com\fireboxtraining\StatFunc.py", line 3088, in <module>
    aov_table = sa.stats.anova_lm(fit_result, typ=1)
  File "C:\Users\ysn8\AppData\Local\Programs\Python\Python37-32\lib\site-packages\statsmodels\stats\anova.py", line 327, in anova_lm
    return anova_single(model, **kwargs)
  File "C:\Users\ysn8\AppData\Local\Programs\Python\Python37-32\lib\site-packages\statsmodels\stats\anova.py", line 80, in anova_single
    n_rows, test, pr_test, robust)
  File "C:\Users\ysn8\AppData\Local\Programs\Python\Python37-32\lib\site-packages\statsmodels\stats\anova.py", line 126, in anova1_lm_single
    sum_sq = np.dot(arr, effects**2)
ValueError: shapes (18,18) and (16,) not aligned: 18 (dim 1) != 16 (dim 0)

**Comment by sunyu90325** [comment]
Here is R input and output. It doesn't complain about the number of observations.

y<-c(0.8147, 0.9058, 0.127, 0.9134, 0.6324, 0.0975, 0.2785, 0.5469, 0.9575, 0.9649, 0.1576, 0.9706, 0.9572, 0.4854, 0.8003, 0.1419)
> x1<-c(1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0)
> x2<-c(1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0)
> x3<-c(1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0)
> x4<-c(1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0)
> x5<-c(1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0)
> x6<-c(1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0)
> x7<-c(1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0)
> x8<-c(1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0)
> x9<-c(1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0)
> x10<-c(1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0)
> x11<-c(1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0)
> x12<-c(1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0)
> x13<-c(1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0)
> x14<-c(1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0)
> x15<-c(1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0)
> x16<-c(1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0)
> x17<-c(1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0)
> 
> mod<-lm(y~x1+x2+x3+x4+x5+x6+x7+x8+x9+x10+x11+x12+x13+x14+x15+x16+x17)
> anova.m<-anova(mod)
> 
> anova.m
Analysis of Variance Table

Response: y
          Df  Sum Sq Mean Sq F value Pr(>F)  
x1         1 0.07829 0.07829  1.9606 0.2964  
x2         1 0.21888 0.21888  5.4815 0.1440  
x3         1 0.01821 0.01821  0.4561 0.5691  
x4         1 0.22071 0.22071  5.5273 0.1431  
x5         1 0.00567 0.00567  0.1420 0.7425  
x6         1 0.28026 0.28026  7.0187 0.1178  
x7         1 0.05299 0.05299  1.3271 0.3684  
x9         1 0.07148 0.07148  1.7900 0.3128  
x10        1 0.59853 0.59853 14.9892 0.0607 .
x11        1 0.04886 0.04886  1.2237 0.3839  
x12        1 0.01451 0.01451  0.3633 0.6079  
x13        1 0.04066 0.04066  1.0183 0.4192  
x14        1 0.07565 0.07565  1.8946 0.3025  
Residuals  2 0.07986 0.03993                 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
> sm<-summary(mod)
> sm$coefficients
              Estimate Std. Error    t value    Pr(>|t|)
(Intercept)  0.6094750 0.04995694 12.2000072 0.006651656
x1          -0.0699500 0.04995694 -1.4002059 0.296421273
x2           0.1169625 0.04995694  2.3412664 0.144035665
x3           0.0337375 0.04995694  0.6753316 0.569080179
x4           0.1174500 0.04995694  2.3510248 0.143086292
x5          -0.0188250 0.04995694 -0.3768245 0.742528138
x6           0.1323500 0.04995694  2.6492817 0.117821794
x7          -0.0575500 0.04995694 -1.1519921 0.368435789
x9           0.0668375 0.04995694  1.3379023 0.312764180
x10         -0.1934125 0.04995694 -3.8715844 0.060703500
x11          0.0552625 0.04995694  1.1062027 0.383889717
x12          0.0301125 0.04995694  0.6027691 0.607907295
x13          0.0504125 0.04995694  1.0091191 0.419155759
x14         -0.0687625 0.04995694 -1.3764354 0.302529508

**Comment by sunyu90325** [comment]
Degree freedom of residual is not negative because there are collinearity in some explanatory variables. Three explanatory variables don't have degree freedom. Maybe the source of the bug is not supporting collinearity. Thanks.

**Comment by josef-pkt** [comment]
It looks like R drops x8 and stops before df_resid becomes 0.

We currently don't do any automatic dropping of variables in the models. It's up to the user to specify a model that can be estimated, and to choose which variables to drop if there are collinearities or not enough degrees of freedom.
We differ in this from R and Stata.

If we fix this in anova_lm type 1, then I think we should just stop when we run out of degrees of freedom.
However, it's not really useful to look at those cases because estimates and hypothesis test are completely unreliable because there is not enough information.

(There are cases when we want to look at saturated models, i.e. models where residuals are all zero, but I don't think we support that in general. I only looked at log-linear GLM-Poisson cases for that, IIRC)

**Comment by sunyu90325** [comment]
I see. Thank you so much for the explanation!

**Comment by ecotner** [comment]
I was having this problem myself and @josef-pkt's comment

> IIUC, you have more explanatory variables and parameters than observations

made me realize that I had an interaction term between two categorical variables in my model that had as many distinct combinations than there were observations. Removing that term solved everything. Thanks!
