### ISSUE TITLE
SIGKILL received wihile fitting SARIMAX model

### ISSUE THREAD

**Issue by alexsmartens** [statsmodels/statsmodels#6238]
#### Describe the bug
`Process finished with exit code 137 (interrupted by signal 9: SIGKILL)`  while fitting `sm.tsa.SARIMAX(y, order=(10, 1, 40), seasonal_order=(0, 0, 0))`. 

More info:
<details>
I have a high frequency dataset re-sampled to 1 data point per minute (original sampling rate 1 point per 2 sec). My dataset has about 80K points. Based on the autocorrelation and partial autocorrelation plots I see a possibility of fitting a model with p up to 30 and q up to 60. I also do not see any seasonality. So, my strategy is to iteratively fit all possible models and pick the best one based on AIC. I receive `SIGKILL` when try fitting `sm.tsa.SARIMAX(y, order=(10, 1, 40), seasonal_order=(0, 0, 0))`. 
I also tested running my code on different machines and the result is the same.
</details>

#### Questions

1) How could I run my code in debug mode to report what the exact problem is?

2) Is there a more efficient or at least faster way to find a good model fit other then iterating through all the possible options?

#### Code Sample, a copy-pastable example if possible

```python
    y = ... # my dataset
    per = 0 
    d = 1
    DD = 0
    sarima_mod_df = pd.DataFrame(columns=["Name", "Model", "Result", "AIC"])  # store models
 
    for p in np.arange(0, 31, 10):
        for q in np.arange(0, 61, 10):
            for PP in range(1):
                for QQ in range(1):
                    if p + q > 0:
                        try:
                            order = (p, d, q)
                            seasonal_order = (PP, DD, QQ, per)
                            sarima_mod = sm.tsa.SARIMAX(y, order=order, seasonal_order=seasonal_order)

                            sarima_res = sarima_mod.fit(disp=0)

                            sarima_mod_df = sarima_mod_df.append(
                                {"Name": "{} {} {} {} {} {} {}".format(p, d, q, PP, DD, QQ, per),
                                 "Model": sarima_mod,
                                 "Result": sarima_res,
                                 "AIC": sarima_res.aic,
                                 }, ignore_index=True)orts.
                        except ValueError as e:
                            ...
```

#### Expected Output
Not receiving  `SIGKILL`

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

```
Statsmodels
===========

Installed: 0.10.1
```

**Comment by ChadFulton** [comment]
I haven't run into this issue before, but it sounds like it may be an out-of-memory issue (based on e.g. https://stackoverflow.com/questions/43268156/process-finished-with-exit-code-137-in-pycharm). 

Probably the best option at the moment is to upgrade to the development version of Statsmodels, and then use the new `low_memory=True` option to `SARIMAX`'s `fit` method. You can see #6034 for some more discussion of the memory issue.

**Comment by ChadFulton** [comment]
> Is there a more efficient or at least faster way to find a good model fit other then iterating through all the possible options?

I haven't seen a lot of discussion about the case when the maximum order is so high. Hyndman & Khandakar (2008) discuss in section 3.2 a "stepwise" algorithm for selecting the model order, but that is for the case that p and q can take values from 0 to 3.

I am planning to include additional support for model selection in Statsmodels, and the first step for that was the introduction of a new ARIMA class (unfortunately this means we have three of them now :(, but hopefully we'll begin deprecating one soon), which is available in `sm.tsa.arima.ARIMA`.

This class combines all the features of SARIMAX but with additional parameter estimators. In your case (since you do not have seasonality), you could use the Hannan-Rissanen estimator for model selection. This will probably be a lot faster, since it's a regression-based estimator, but it likely won't give quite as good parameter estimates as the full maximum likelihood estimates that `SARIMAX` gives.

If you wanted to give this a try, you would replace your model creation and fitting code with the following:

```python
mod = sm.tsa.arima.ARIMA(y, order=order, enforce_stationarity=False, enforce_invertibility=False)
res = mod.fit(method='hannan_rissanen', low_memory=True, cov_type='none')
```

**Comment by alexsmartens** [comment]
Thank you @ChadFulton,  `low_memory=True` solves the problem. 
In my case, SARIMAX behaviour was indeed very similar to  #6034.

I'm thinking about doing a `p,q` grid search with `hannan_rissanen` as coarse grained analysis and then fitting `SARIMAX` with a smaller `p,q` grid. I've got a couple of questions regarding this:

1) Do you think it's a reasonable approach to the problem?

2) If I still want to try fitting `SARIMAX` with large `p,q` to my data, is there any way I can get a feeling of how much RAM I need to avid SIGKILL? Or maybe you have a suggested amount of RAM in mind?

**Comment by ChadFulton** [comment]
> I'm thinking about doing a p,q grid search with hannan_rissanen as coarse grained analysis and then fitting SARIMAX with a smaller p,q grid. I've got a couple of questions regarding this:

I think this seems like a good practical approach to the problem, and it is relatively common: R's `auto.arima` function has a parameter `approximation` that does something similar.

You might also consider, though, that considering models with such large lag orders risks overfitting your data.

> If I still want to try fitting SARIMAX with large p,q to my data, is there any way I can get a feeling of how much RAM I need to avid SIGKILL? Or maybe you have a suggested amount of RAM in mind?

I don't know, since I've not run into the SIGKILL before. However, the default (`low_memory=False`) creates several arrays that have `nobs * k_states**2` elements, where `k_states` is at least equal larger of `p` or `q + 1` in an ARIMA(p, q) model. So this can easily consume a large amount of memory when you have long lag orders.

**Comment by alexsmartens** [comment]
Thanks for your advice!

I keep playing with the model parameters and I've run into the following error:
`statsmodels.tools.sm_exceptions.MissingDataError: exog contains inf or nans`.

Code that produced the error
```
mod = sm.tsa.arima.ARIMA(y, order=(47,1,39), enforce_stationarity=False, enforce_invertibility=False)
res = mod.fit(method='hannan_rissanen', low_memory=True, cov_type='none')
```

Error Log
```
/home/ubuntu/anaconda3/envs/my-env/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:163: ValueWarning: No frequency information was provided, so inferred frequency T will be used.
  % freq, ValueWarning)
/home/ubuntu/anaconda3/envs/my-env/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:163: ValueWarning: No frequency information was provided, so inferred frequency T will be used.
  % freq, ValueWarning)
Traceback (most recent call last):
  File "/home/ubuntu/Projects/katerra/occupancy-detection/build_experiment-dataset.py", line 286, in <module>
    sarima_res = sarima_mod.fit(method="hannan_rissanen", low_memory=True, cov_type="none") #disp=0)
  File "/home/ubuntu/anaconda3/envs/my-env/lib/python3.7/site-packages/statsmodels/tsa/arima/model.py", line 341, in fit
    ma_order=order[2], demean=False, **method_kwargs)
  File "/home/ubuntu/anaconda3/envs/my-env/lib/python3.7/site-packages/statsmodels/tsa/arima/estimators/hannan_rissanen.py", line 170, in hannan_rissanen
    mod_unbias = OLS(Z[max(max_ar_order, max_ma_order):], exog)
  File "/home/ubuntu/anaconda3/envs/my-env/lib/python3.7/site-packages/statsmodels/regression/linear_model.py", line 858, in __init__
    """
  File "/home/ubuntu/anaconda3/envs/my-env/lib/python3.7/site-packages/statsmodels/regression/linear_model.py", line 701, in __init__
    Returns
  File "/home/ubuntu/anaconda3/envs/my-env/lib/python3.7/site-packages/statsmodels/regression/linear_model.py", line 189, in __init__
    class RegressionModel(base.LikelihoodModel):
  File "/home/ubuntu/anaconda3/envs/my-env/lib/python3.7/site-packages/statsmodels/base/model.py", line 236, in __init__
    def score(self, params):
  File "/home/ubuntu/anaconda3/envs/my-env/lib/python3.7/site-packages/statsmodels/base/model.py", line 77, in __init__
    # we don't need 'missing', maybe we need 'hasconst'
  File "/home/ubuntu/anaconda3/envs/my-env/lib/python3.7/site-packages/statsmodels/base/model.py", line 100, in _handle_data
    pass
  File "/home/ubuntu/anaconda3/envs/my-env/lib/python3.7/site-packages/statsmodels/base/data.py", line 667, in handle_data
  File "/home/ubuntu/anaconda3/envs/my-env/lib/python3.7/site-packages/statsmodels/base/data.py", line 83, in __init__
    
  File "/home/ubuntu/anaconda3/envs/my-env/lib/python3.7/site-packages/statsmodels/base/data.py", line 129, in _handle_constant

statsmodels.tools.sm_exceptions.MissingDataError: exog contains inf or nans

Process finished with exit code 1
```

What do you think?

**Comment by ChadFulton** [comment]
Thanks for this report! My first thought was that this looks like a problem with the number of observations versus the given order, but I'm not able to replicate it. What is `y.shape`?

Is there any chance you can share the dataset you're using? Or if it's private, that you could simulate a similar dataset that replicates there error?

**Comment by alexsmartens** [comment]
Here is a sample of the data that I'm working with [my_data_sample.csv](https://drive.google.com/file/d/1hNdI65sRd_MmeK_FpS-Ec4zrQ4gAtW-O/view?usp=sharing). It has readings from a sensor with one minute interval, and I also have higher resolution data if we need it.

With this dataset, I'm seeing this error when the order is `(48, 1, 49)`.
I'm very curious to see your findings

**Comment by ChadFulton** [comment]
Thanks for sharing that! The interesting thing is that it does not produce an error for me. I am using the following code:

```python
import pandas as pd
import statsmodels.api as sm

endog = pd.read_csv('my_data_sample.csv', index_col=[0])['1b']
mod = sm.tsa.arima.ARIMA(endog, order=(48,1,49), enforce_stationarity=False, enforce_invertibility=False)
res = mod.fit(method='hannan_rissanen', low_memory=True, cov_type='none')
print(res.llf)
```
which gives:

```
65457.049356148666
```

Would you mind double-checking if this code produces an error for you?

**Comment by alexsmartens** [comment]
Sorry, that's my bad. I double checked my code and saw that I'm differentiating data for plotting and use this data for model fitting. I will rerun model fitting with the original data.

Meanwhile, here is the code that raises this error:
```
import pandas as pd
import statsmodels.api as sm

endog = pd.read_csv('my_data_sample.csv', index_col=[0])['1b'].diff().dropna()
mod = sm.tsa.arima.ARIMA(endog, order=(48,1,49), enforce_stationarity=False, enforce_invertibility=False)
res = mod.fit(method='hannan_rissanen', low_memory=True, cov_type='none')
print(res.llf)
```

**Comment by ChadFulton** [comment]
Thanks very much! It looks like the problem here is basically an overflow problem.

The details are: the third stage of the Hannan-Rissanen estimator (which removes a bias from the estimators and makes them asymptotically efficient) can be problematic if the estimated coefficients from the second stage of the estimator are non-stationary / non-invertible and you have a long-enough time series. Then the intermediate variable blows up over time, leading to `inf` and then `nan` terms.

The fix will be to check the second stage parameters for invertibility / stationarity, and then only apply the third stage if those checks pass.

Thanks again for passing along the replication data and code!

**Comment by ChadFulton** [comment]
I should have a fix for this soon, but in the meantime you can direct the Hannan-Rissanen method to skip the problematic third step by passing the argument `method_kwargs={'unbiased': False}` to the `fit` method, e.g.:

```python
res = mod.fit(method='hannan_rissanen', low_memory=True, cov_type='none', method_kwargs={'unbiased': False})
```

**Comment by alexsmartens** [comment]
I can replicate `SIGKILL`. It occurs when I run a grid search for `p,q` with `SARIMAX`.  It looks like a memory leak. 

I looked at the free memory plot (over the past 2 hours). Every iteration I observe a drop in free memory until it reaches to 0% and then `SIGKILL` comes into play.  Here's my code:

```
import numpy as np
import pandas as pd
import statsmodels.api as sm

endog = pd.read_csv('my_data_sample.csv', index_col=[0])['1b']

for p in np.arange(23, 41, 1):
    for q in np.arange(23, 41, 1):
        order = (p, 1, q)
        seasonal_order = (0, 0, 0, 0)

        mod = sm.tsa.SARIMAX(endog, order=order, seasonal_order=seasonal_order)
        res = mod.fit(disp=0)
```

Could you try running this code and looking at the free memory usage?

**Comment by bashtage** [comment]
Are you using conda or pip? Could be a Blas leak.

**Comment by alexsmartens** [comment]
By default I use conda, however I used pip to install the development version of Statsmodels

**Comment by alexsmartens** [comment]
Ok, I think I've figured the problem out. It's a purely Python thing. I'm closing the issue, will report back if I see something unusual. Thank you for your help!

### SIGKILL Cause
When an object is reassigned in a loop, the object variable references the new object, but the old object is still in memory until it's explicitly deleted (or the process terminated). 

### Solution
Adding `del mod` and `del res` in the end of each iteration keeps the memory usage in a normal range.

**Comment by ChadFulton** [comment]
Thanks for following up, that's good to know.

**Comment by alexsmartens** [comment]
I've noticed that `hannan_rissanen` `ARIMA`method uses all logical processors, however `SARIMAX` uses only one logical processor. And one way to improve grid search speed with `SARIMAX` in this case is to use all the available processors. Here's a simple code modification to do that:

```
import numpy as np
import pandas as pd
import statsmodels.api as sm
import multiprocessing
from os import getpid
from arima_modeling import prepare_orders

endog = pd.read_csv('my_data_sample.csv', index_col=[0])['1b']

def grid_search(endog, orders):
    print(getpid())
    for order in orders:
        mod = sm.tsa.SARIMAX(endog, order=order[0], seasonal_order=order[1])
        res = mod.fit(disp=0)
        del mod
        del res
    return getpid()

orders = prepare_orders(
    ranges={
        "p": [23, 41, 1],
        "d": 1,
        "q": [23, 41, 1]
    }
)

cpu_cnt = multiprocessing.cpu_count()

# Prepare order and season order combinations for each process
cpu_split_orders = [int(x) for x in np.linspace(0, len(orders), cpu_cnt + 1)]
orders = [orders[cpu_split_orders[i]: cpu_split_orders[i + 1]] for i in range(len(cpu_split_orders) - 1)]

# Run pool of processes
pool = multiprocessing.Pool(cpu_cnt)
run_process = lambda i: pool.apply_async(grid_search, args=(endog, orders[i]))
result_map = list(map(run_process, range(cpu_cnt)))
results = [r.get() for r in result_map]  # list of pids in this case
```
`prepare_orders` function simply creates a list of all the combinations of `order` and `seasonal_order`
