### ISSUE TITLE
BUG: SARIMAX does not work with lists of lags

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#6244]
#### Describe the bug

SARIMAX does not work with directly specifying lags. Appears to have a bug in starting value code.

This is using latest dev (Nov 12, 2019)

#### Code Sample, a copy-pastable example if possible

```python
import statsmodels.api as sm
import statsmodels.tsa.api as tsa 
import numpy as np

proc = tsa.ArmaProcess.from_coeffs([1.8,0,0,-3])
print(np.abs(proc.arroots))
print(proc.isstationary)
sample = 100 + proc.generate_sample(1000)
mod = tsa.SARIMAX(sample, order=([1,4],0, 0), trend='c')
res = mod.fit()
print(res.summary())
```

Produces
```
c:\git\statsmodels\statsmodels\tsa\statespace\sarimax.py:914: RuntimeWarning: overflow encountered in square
  params_variance = (residuals[k_params_ma:]**2).mean()
c:\git\statsmodels\statsmodels\tsa\statespace\sarimax.py:976: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
c:\git\statsmodels\statsmodels\tsa\statespace\tools.py:487: RuntimeWarning: invalid value encountered in double_scalars
  y[k-1, i] = (y[k, i] - y[k, k]*y[k, k-i-1]) / (1 - y[k, k]**2)
c:\git\statsmodels\statsmodels\tsa\statespace\tools.py:489: RuntimeWarning: invalid value encountered in sqrt
  x = r / ((1 - r**2)**0.5)
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-a7c5e4baeb4f>", line 10, in <module>
    res = mod.fit()
  File "c:\git\statsmodels\statsmodels\tsa\statespace\mlemodel.py", line 605, in fit
    start_params = self.untransform_params(start_params)
  File "c:\git\statsmodels\statsmodels\tsa\statespace\sarimax.py", line 1495, in untransform_params
    unconstrained[start] = constrained[start]**0.5
IndexError: index 6 is out of bounds for axis 0 with size 4
```

Simple regular ARs also fail:

```
mod = tsa.SARIMAX(sample, order=([1,2],0, 0), trend='c')
res = mod.fit()
```

#### Expected Output

Estimate the model specified.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.7.5.final.0
statsmodels
===========
Installed: v0.11.0dev0+546.g3b649d1e9 (c:\git\statsmodels\statsmodels)
Required Dependencies
=====================
cython: 0.29.13 (C:\Anaconda\lib\site-packages\Cython)
numpy: 1.17.2 (C:\Anaconda\lib\site-packages\numpy)
scipy: 1.3.1 (C:\Anaconda\lib\site-packages\scipy)
pandas: 0.25.2 (C:\Anaconda\lib\site-packages\pandas)
    dateutil: 2.8.0 (C:\Anaconda\lib\site-packages\dateutil)
patsy: 0.5.1 (C:\Anaconda\lib\site-packages\patsy)
Optional Dependencies
=====================
matplotlib: 3.1.1 (C:\Anaconda\lib\site-packages\matplotlib)
    backend: module://backend_interagg 
cvxopt: Not installed
joblib: 0.13.2 (C:\Anaconda\lib\site-packages\joblib)
Developer Tools
================
IPython: 7.9.0 (C:\Anaconda\lib\site-packages\IPython)
    jinja2: 2.10.3 (C:\Anaconda\lib\site-packages\jinja2)
sphinx: 2.2.1 (C:\Anaconda\lib\site-packages\sphinx)
    pygments: 2.4.2 (C:\Anaconda\lib\site-packages\pygments)
pytest: 5.2.2 (C:\Anaconda\lib\site-packages)
virtualenv: Not installed
</details>

**Comment by bashtage** [comment]
@ChadFulton Something I came across when teaching using sm.

**Comment by ChadFulton** [comment]
Thanks @bashtage!
