### ISSUE TITLE
BLD: Travis for Python 3.8

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#6245]
Am I right in thinking that we will soon need to add a Travis for Python 3.8 and the newest Numpy / Scipy / Pandas versions?

Should this be done prior to v0.11?

**Comment by bashtage** [comment]
We need to wait for conda to have full support. Ideally we shildbtrst 3.8
and drop 3.5 after 0.11.

**Comment by ChadFulton** [comment]
Thanks!
