### ISSUE TITLE
[Not an issue] How to get the State Vector from SARIMAX model?

### ISSUE THREAD

**Issue by Nirmal-Neel** [statsmodels/statsmodels#6256]
After the SARIMAX model is trained, I can find the transition matrix and selection matrix from `SARIMAX.ssm`. Now I am struggling to get the State Vector. Is there any way to find this or to calculate this?

**Comment by ChadFulton** [comment]
If you have code like the following:

```python
mod = sm.tsa.SARIMAX(endog, order=(1, 0, 0), ...)
res = mod.fit()
```

then you can get three different types of state estimates:

- `res.smoothed_state` gives estimates of each state conditional on information from the entire sample (i.e. the estimate of the state vector at time `t` is based on data from periods `1, ..., T`.)
- `res.filtered_state` gives estimates of the state conditional on information from only a given period and before (i.e. the estimate of the state vector at time `t` is based on data from periods `1, ..., t`.)
- `res.predicted_state` gives estimates of the state conditional on information just prior to a given period (i.e. the estimate of the state vector at time `t` is based on data from periods `1, ..., t-1`.)

These will be numpy arrays shaped `k_states x nobs`.

If you have the development version installed, you can also access these from the `states` attribute, like:

```python
res.states.smoothed
```

and this will be an `nobs x k_states` Pandas DataFrame with the appropriate index and column names.

**Comment by Nirmal-Neel** [comment]
Thanks for your explanation. I have one more question. In ARIMA, we can specify the prediction method ('mle', 'css', 'css-mle'), is there any way to specify that in SARIMAX?

**Comment by ChadFulton** [comment]
SARIMAX only has one estimator. A new model class in the development
version of Statsmodels, am.tsa.arima.ARIMA, has all of the features of
SARIMAX but allows a choice of estimator.

However, most alternative estimation methods do not support seasonal models.

**Comment by ChadFulton** [comment]
Closing as answered, but please feel free to follow up with additional questions.

**Comment by Nirmal-Neel** [comment]
Thanks for the answers. I have just one more question. In ARIMA, if we provide method='mle', then it performs KalmanFilter. Is there any way to get the state vector in that scenario. I could find the transition matrix and selection matrix, but not the state vector.

**Comment by ChadFulton** [comment]
No, it doesn't look to me like there's any way to get it from that model.

**Comment by Nirmal-Neel** [comment]
Hi @ChadFulton, I have one more question. Instead of opening one new issue, I am continuing on this.

My question is as follows - 

During the calculation of forecast error for ARIMA model, after getting the psi_vector form arma2ma function, a cumulative sum is applied for `d` times. What is the theory behind this `d` time cumulative sum?

**Comment by bashtage** [comment]
I recommend reading Durbin and Koop, which is an excellent and compact
introduction to the Kalman Filter.

**Comment by Nirmal-Neel** [comment]
Thanks @bashtage .

My another question is that in ARIMA we can get the confidence interval from the forecast function itself. But, for Seasonal ARIMA, we need to call conf_int function. But the returned values from that function is something that I cannot understand. Those are confidence interval of the fitted parameters. How to relate those to the forecast result? Thanks!

**Comment by Nirmal-Neel** [comment]
I could understand the calculation of psi_vector for non-seasonal arima model. But could not understand the same for SARIMAX/VARMAX. Which formula are you using to calculate psi_vector and from which book in case of state space models?

**Comment by Nirmal-Neel** [comment]
Yeah. But I am not able to understand or find the formula in any book to calculate the psi_vector(forecasts_error_cov) for VARMAX.

**Comment by ChadFulton** [comment]
I'm not sure what you're asking, and I don't know what you mean by psi_vector.

In general, VARMAX models are put into state space form, and then the Kalman filter is applied as usual to get all output including the forecast error covariance matrix. To see how these models are put in state space form, you can consult Lütkepohl's (2005) book "New Introduction to Multiple Time Series Analysis", see e.g. chapters 18 and 11.

**Comment by Nirmal-Neel** [comment]
By psi_vector, I am referring to the forecast_error_covariance matrix. I am not finding the formula for this. Sure, I will go through those chapters.

**Comment by ChadFulton** [comment]
This matrix is denoted F_t in equation (4.26) of Durbin and Koopman's book, which shows how it is computed.

**Comment by Nirmal-Neel** [comment]
Thank you so much! That answers my question.
