### ISSUE TITLE
AttributeError: 'SARIMAX' object has no attribute 'get_forecast' / SARIMAX in FLASK

### ISSUE THREAD

**Issue by RonnyAtoche** [statsmodels/statsmodels#6277]
I am trying to build a simple machine learning web App with SARIMAX.

***This is my dataBase file: "dfp_100017_monthly.csv"***

FACTUUR_DATUM,NETTO_GEWICHT_KG
2018-01-31,114.0
2018-02-28,0.0
2018-03-31,24.0
2018-04-30,12.0
2018-05-31,36.0
2018-06-30,528.0
2018-07-31,12.0
2018-08-31,48.0
2018-09-30,0.0
2018-10-31,12.0
2018-11-30,1308.0
2018-12-31,1338.0
2019-01-31,2022.0
2019-02-28,2634.0
2019-03-31,2472.0
2019-04-30,1530.0
2019-05-31,1764.0
2019-06-30,2622.0
2019-07-31,1254.0
2019-08-31,1572.0
2019-09-30,1506.0
2019-10-31,1824.0
2019-11-30,1212.0
2019-12-31,462.0

***End of dataBase file***

***This is my model.py***

import pickle
from pandas import read_csv
import statsmodels.api as sm
import matplotlib.pyplot as plt

plt.style.use('fivethirtyeight')
y = read_csv('/Users/mac/Desktop/OrderPredictions/dfp_100017_monthly.csv', header=0, parse_dates=[0], index_col=0, squeeze=True)

model = sm.tsa.statespace.SARIMAX(y,
                                order=(1, 1, 1),
                                seasonal_order=(1, 0, 0, 12),
                                enforce_stationarity=False,
                                enforce_invertibility=False)
model.fit()

# Saving model to disk
pickle.dump(model, open('model.pkl','wb'))

# Loading model to compare the results
model = pickle.load(open('model.pkl','rb'))

***End of model.py***

***This is my Flask file***

import numpy as np
from flask import Flask, request, jsonify, render_template
import pickle
import warnings
import itertools
import pandas as pd
import numpy as np
import pickle
from pandas import read_csv
import statsmodels.api as sm
import matplotlib.pyplot as plt
from pandas import read_csv
import statsmodels.api as sm
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

app = Flask(__name__)
model = pickle.load(open('model.pkl', 'rb'))

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict',methods=['POST'])
def predict():

    #steps = int(request.form.values())
    pred_uc = model.get_forecast(10)
    output = pred_uc.predicted_mean
    #output = round(prediction[0], 2)

    return render_template('index.html', prediction_text='The price of this car should be $ {}'.format(output))

if __name__ == "__main__":
    app.run()

******End of Flask file*****

Always when I run the "model.py" file,  I get this output:

--------------------------------------------------------
-------------------------------------------------------
/usr/local/bin/python3.7 /Users/mac/Documents/PyCharmProjects/ShampoSalesPrediction/model3.py
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency M will be used.
  % freq, ValueWarning)
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            4     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  3.29522D+00    |proj g|=  9.85808D-02
 This problem is unconstrained.

At iterate    5    f=  3.23824D+00    |proj g|=  9.23758D-03

At iterate   10    f=  3.23808D+00    |proj g|=  4.01070D-04

At iterate   15    f=  3.23805D+00    |proj g|=  7.03312D-03

At iterate   20    f=  3.23539D+00    |proj g|=  4.46151D-02

At iterate   25    f=  3.23342D+00    |proj g|=  2.95277D-05

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    4     27     30      1     0     0   4.416D-06   3.233D+00
  F =   3.2334219180589656     

CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL            

 Cauchy                time 0.000E+00 seconds.
 Subspace minimization time 0.000E+00 seconds.
 Line search           time 0.000E+00 seconds.

 Total User time 0.000E+00 seconds.

Process finished with exit code 0
-----------------------------------------------------------------
-----------------------------------------------------------------

MY FIRST QUESTION IS:

WHY DO I GET THIS? >> ValueWarning: No frequency information was provided, so inferred frequency M will be used.
  % freq, ValueWarning)

On the other hand, a "model.pkl" file was created and when I run the flask app, I get this::

---------------------------------------------------------
--------------------------------------------------------
 * Serving Flask app "app3" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [26/Nov/2019 01:36:21] "GET / HTTP/1.1" 200 -
[2019-11-26 01:36:24,491] ERROR in app: Exception on /predict [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mac/Documents/PyCharmProjects/ShampoSalesPrediction/app3.py", line 29, in predict
    pred_uc = model.get_forecast(10)
AttributeError: 'SARIMAX' object has no attribute 'get_forecast'
127.0.0.1 - - [26/Nov/2019 01:36:24] "POST /predict HTTP/1.1" 500 -

---------------------------------------------------------------
------------------------------------------------------------

SO MY SECOND QUESTION IS:

HOW CAN I SOLVE THIS PROBLEM?? >> AttributeError: 'SARIMAX' object has no attribute 'get_forecast'

PSD: I HAVE INSTALLED STATSMODELS 0.10.2

Thank you in advance!

**Comment by ChadFulton** [comment]
> MY FIRST QUESTION IS:

> WHY DO I GET THIS? >> ValueWarning: No frequency information was provided, so inferred frequency M will be used.
% freq, ValueWarning)

It means that your date index doesn't have an assigned frequency. The model infers that the frequency is probably monthly and uses that, and it lets you know that it is making that assumption.

You can get rid of this warning by adding:

```python
y = y.asfreq('M')
```

> SO MY SECOND QUESTION IS:
> HOW CAN I SOLVE THIS PROBLEM?? >> AttributeError: 'SARIMAX' object has no attribute 'get_forecast'

Right now, you're solving the model but not the results of the `fit` call. In statsmodels, fitting does not modify the model, but instead returns a results object. So you would want to do:

```python
model = sm.tsa.statespace.SARIMAX(y,
order=(1, 1, 1),
seasonal_order=(1, 0, 0, 12),
enforce_stationarity=False,
enforce_invertibility=False)
results = model.fit()

pickle.dump(results, open('results.pkl','wb'))
```

**Comment by RonnyAtoche** [comment]
Oh yeah, I see. It is working now... Thank you so much!

One last question:

When I try to do this in my flask file:

`@app.route('/predict',methods=['POST'])
def predict():


    steps = int(request.form.values())
    pred_uc = model.get_forecast(steps)
    output = pred_uc.predicted_mean
    #output = round(prediction[0], 2)

    return render_template('index.html', prediction_text='The price of this car should be $ {}'.format(output))
`
I get this error:

> * Serving Flask app "app3" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [26/Nov/2019 01:57:07] "GET / HTTP/1.1" 200 -
[2019-11-26 01:57:10,518] ERROR in app: Exception on /predict [POST]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/mac/Documents/PyCharmProjects/ShampoSalesPrediction/app3.py", line 28, in predict
    steps = int(request.form.values())
TypeError: int() argument must be a string, a bytes-like object or a number, not 'generator'
127.0.0.1 - - [26/Nov/2019 01:57:10] "POST /predict HTTP/1.1" 500 -
------------------------------------------------------------------------
-------------------------------------------------------------------------
HOW CAN I CONVERT A GENERATOR INTO A INT ?>>TypeError: int() argument must be a string, a bytes-like object or a number, not 'generator'

STEPS MUST BE "INT", BUT IN request.form.values() I GET A DIFFERENT KIND OF DATA.

THANK YOU SO MUCH IN ADVANCE

**Comment by ChadFulton** [comment]
This is a flask issue. I'm not a flask expert, but I think that you probably want to get a particular form field rather than the list of values from the entire form.

I guess you probably want something like:

```python
steps = int(request.form['form_field_name_here'])
```

**Comment by RonnyAtoche** [comment]
You could not be a Flask expert, but you have great programming knowledge. Your last reply solved the issue. Thank you!

**Comment by ChadFulton** [comment]
Glad I could help!

**Comment by k4der2rg** [comment]
I have a similar issue when trying to deploy SARIMAX model using Flask,
**The error:** 

`if not self.simple_differencing and self._k_trend > 0:
AttributeError: 'SARIMAX' object has no attribute '_k_trend'`

Note that I saved the results of fit() not only the model. the error accrue with both get_forcast() and get_prediction()

What should I do ?
@ChadFulton

**Comment by bashtage** [comment]
You need to match the version in your app that you used to fit the model exactly. Unpickling isn't supported accross versions of statsmodels or Python for us.
