### ISSUE TITLE
Different models description in SARIMAX documentation

### ISSUE THREAD

**Issue by FoxFenya** [statsmodels/statsmodels#6278]
Hello everyone. I have some problem with SARIMAX documentation.
https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_sarimax_stata.html

In first exampe, you write about model ARIMA(1,1,1) and show the formula of this model, but then you show python summary estimarion for other model ARIMA(1,1,(1,4)). 

I've estimated the python model ARIMA(1,1,1) on your data (in article) and get following results:

```
wpi1 = requests.get('https://www.stata-press.com/data/r12/wpi1.dta').content
data = pd.read_stata(BytesIO(wpi1))
data.index = data.t

# Fit the model
mod = sm.tsa.statespace.SARIMAX(data['wpi'], trend='c', order=(1,1,1))
res = mod.fit(disp=False)
print(res.summary())

                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
intercept      0.0943      0.068      1.389      0.165      -0.039       0.227
ar.L1          0.8742      0.055     16.028      0.000       0.767       0.981
ma.L1         -0.4120      0.100     -4.119      0.000      -0.608      -0.216
sigma2         0.5257      0.053      9.849      0.000       0.421       0.630
```
In the documentation you write the formula of model ARIMA(1,1,1) with estimation coefficients and they are not equal with my result. Could you please help me to find out why?

**Comment by bashtage** [comment]
Most importantly, you need to use `data["ln_wpi"]`.  

I don't use an exact match on master bit it is close. The fit I get is a bit worse based on likelihood.  This might be down to platform-specific issues.

**Comment by bashtage** [comment]
Feel free to continue to post in this thread if not clear. I closed since there is no action required since this is not a bug.

**Comment by FoxFenya** [comment]
I'm so sorry, dut I don't understand. Difference in estimation so important. 
In documentation you show 

Δy_t=0.1050+0.8740Δy_(t−1)−0.4206ϵ_(t−1)+ϵ_t
where ϵt∼N(0,0.5226)

if I use data["ln_wpi"], then I get the following model
```
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
intercept      0.0019      0.001      1.660      0.097      -0.000       0.004
ar.L1          0.8209      0.052     15.924      0.000       0.720       0.922
ma.L1         -0.3646      0.097     -3.771      0.000      -0.554      -0.175
sigma2         0.0001   1.01e-05     11.532      0.000    9.71e-05       0.000
```

**Comment by bashtage** [comment]
There are a few typos in that notebook.  I have just fixed them.  This should clarify they correct parameters.

**Comment by bashtage** [comment]
The docs have been fixed. Does this address your issue?

**Comment by FoxFenya** [comment]
Yes. Now everything is clear, thank you very much
