### ISSUE TITLE
Not NAN first point in fitted values and residuals in AR model

### ISSUE THREAD

**Issue by FoxFenya** [statsmodels/statsmodels#6282]
Hello everyone!
May be its not a bug, but, I don't undirstand how you compute starting points in AR model. 
For example:
I want to estimate ar model like:
y=AR(1)+AR(2)+e
get coeficients, fitted values and residuals
If I use, for example EViews, in fitted values and residuals I have first and second point equal NANs, but if I use function SARIMAX, ARIMA or others from statsmodels, I get some values in first and second point.
Please, can you explaind me why its not NANs, or maybe give me some advise about literature to study.

**Comment by bashtage** [comment]
The initial fitted values are produced by the Kalman Filter which can
compute expected value for all observations, even those before the max lag.
These are not normal AR residuals/fitted values and should not be
interpreted as such.

Please search in the github issues.  This has been discussed in other
threads.

**Comment by bashtage** [comment]
Closing since no action.

**Comment by bashtage** [comment]
Stackoverflow stats is also a good resource for more general statistical questions.

**Comment by FoxFenya** [comment]
I'm sorry,but may be you can help me.
How can I estimate model with specific lags (for ex. ARIMA((1,3),0,0) but get normal AR residuals/fitted values? 
I searched in issues, and find out that specific lags estimation can be done only by SARIMAX model, but I can't find any properties for computing normal AR residuals/fitted.

**Comment by bashtage** [comment]
You have to use master to get specific lags in SARIMAX.  This should be available in PyPI in about 6 weeks.

```
import statsmodels.api as sm
y = sm.tsa.ArmaProcess.from_coeffs([.3,0,.3]).generate_sample(1000)
res = tsa.SARIMAX(y,order=((1,3),0,0)).fit()
res.fittedvalues
res.resid
```

**Comment by bashtage** [comment]
Again, you will get `n` residuals, but the first 3 cannot be directly interpreted.
