### ISSUE TITLE
RLS: Preparing for 0.11

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#6284]
@ChadFulton had indicated that he was ready for a release to get the improvement in statespace out the door.  I agree that a release should be made sooner rather than later.  Releasing has become a lot less trouble, and the only major pain point is assembling the list of closed issues, prs and contributors, which can be done using the github API. 

We should really have a single script that gathers this all. The ones available are a bit out of date. 

- [x] Patsy >= 0.5.1 due to bugs on some Python
- [x] Update versions.json
- [x] Initial drft of release note
- [x] Add sections for enhancements and major new features

I would like to have an RC out by the end of the year and to release around Jan 14. 

Thoughts @josef-pkt @kshedden ?  Any issues you feel must be available in a 0.11 release?

**Comment by ChadFulton** [comment]
> @ChadFulton had indicated that he was ready for a release to get the improvement in statespace out the door.

The only substantive PR left for me is #6280, which should be done in the next day or so. The other issues I have for the milestone are just documentation for features that were added without e.g. release notes.

**Comment by bashtage** [comment]
@ChadFulton @kshedden The release notes template is now in master. If you have any major features or important changes that you would like to highlight, please do add it in.

**Comment by ChadFulton** [comment]
I think I have all the features that I want to highlight added into the documentation in #6338 . I also included a draft of notes for `AutoReg`.

I wonder if we want to include something about the following:

- Improved documentation theme & logo (@bashtage)
- Functional SIR (@kshedden)
- Rolling WLS and OLS (@bashtage)
- STL decomposition (@bashtage)
- Zivot-Andrews
- Oaxaca-Blinder decomposition

**Comment by bashtage** [comment]
I'll take a trawl through he closed PRs looking for anything.  I think these should all get a note (I'll write most/all ex SIR, which I hope @kshedden can do).

Should have a RC out this week.

**Comment by bashtage** [comment]
I am going to cut the RC today if there are no objections.

**Comment by jbrockmendel** [comment]
If it affects anything, pandas is aiming for a 1.0 RC early January

**Comment by lycanthropes** [comment]
> I think I have all the features that I want to highlight added into the documentation in #6338 . I also included a draft of notes for `AutoReg`.
> 
> I wonder if we want to include something about the following:
> 
> * Improved documentation theme & logo (@bashtage)
> * Functional SIR (@kshedden)
> * Rolling WLS and OLS (@bashtage)
> * STL decomposition (@bashtage)
> * Zivot-Andrews
> * Oaxaca-Blinder decomposition
Hello, I want to install the version of 0.11 ,but Where can I get this modules ? Such new features is very to my appetite , thank you for doing such work.

**Comment by lycanthropes** [comment]
> > @ChadFulton
> > Hello, I want to install the version of 0.11 ,but Where can I get this modules ? Such new features is very to my appetite , thank you for doing such work.

**Comment by bashtage** [comment]
@jbrockmendel I think we are testing [against rc0 now](https://travis-ci.org/statsmodels/statsmodels/jobs/636612053) and there are no pandas issues (SciPy OTOH).

**Comment by bashtage** [comment]
> Hello, I want to install the version of 0.11 ,but Where can I get this modules ? Such new features is very to my appetite , thank you for doing such work.

`pip install statsmodels=0.11.0rc1`
