### ISSUE TITLE
help

### ISSUE THREAD

**Issue by suraj038** [statsmodels/statsmodels#6295]
#### Describe the bug

[A clear and concise description of what the bug is. This should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Code Sample, a copy-pastable example if possible

```python
# Your code here that produces the bug
# This example should be self-contained, and so not rely on external data.
# It should run in a fresh ipython session, and so include all relevant imports.
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

</details>

**Comment by kangsijueshi** [comment]
statsmodels.api cannot be imported

**Comment by bashtage** [comment]
How did you install statsmodels?

**Comment by bashtage** [comment]
Which OS and Python, and version of sm?

**Comment by kangsijueshi** [comment]
> How did you install statsmodels?

from git

File "C:/Users/user/Documents/t-df/statsmodels/regression/tests/satterthwaite.py", line 1, in <module>

    import statsmodels.api as sm

  File "C:\Users\user\Documents\t-df\statsmodels\api.py", line 11, in <module>

    from .regression.recursive_ls import RecursiveLS

  File "C:\Users\user\Documents\t-df\statsmodels\regression\recursive_ls.py", line 14, in <module>

    from statsmodels.tsa.statespace.mlemodel import (

  File "C:\Users\user\Documents\t-df\statsmodels\tsa\statespace\mlemodel.py", line 32, in <module>

    from .simulation_smoother import SimulationSmoother

  File "C:\Users\user\Documents\t-df\statsmodels\tsa\statespace\simulation_smoother.py", line 9, in <module>

    from .kalman_smoother import KalmanSmoother

  File "C:\Users\user\Documents\t-df\statsmodels\tsa\statespace\kalman_smoother.py", line 10, in <module>

    from statsmodels.tsa.statespace.representation import OptionWrapper

  File "C:\Users\user\Documents\t-df\statsmodels\tsa\statespace\representation.py", line 9, in <module>

    from .tools import (

  File "C:\Users\user\Documents\t-df\statsmodels\tsa\statespace\tools.py", line 16, in <module>

    from . import (_initialization, _representation, _kalman_filter,

ImportError: cannot import name '_initialization'

> Which OS and Python, and version of sm?

win10 and python 3.6

**Comment by bashtage** [comment]
Your build did not succeed. You need the visual studio 2015 build tools
installed to use the code in git. These are available through the vs 2017
or vs 2019 installers.

**Comment by kangsijueshi** [comment]
you mean I can not run it with pycharm?

**Comment by bashtage** [comment]
You need to install from git. This is like any other python package. You
should probably install using conda or pip.

**Comment by kangsijueshi** [comment]
But the package I installed from git was different from the one I installed with pip.(though their versions are the same, but the git one cannot run successfully)

**Comment by bashtage** [comment]
Are you trying to develop in statsmodels?  If so, you should install using pip install -e . from the git repo root.

The question is then, what are you trying to accomplish.

**Comment by kangsijueshi** [comment]
I am trying to realize satterthwaite approximation in mixed linear models by starting a new branch, but i meet problems testing it.
Originally, I developed the new function in the package installed using pip, and met no problem testing it. Now I am trying to push it in git. When testing, I found the difference and met the aforementioned bug.

**Comment by bashtage** [comment]
There is no bug - I work in PyCharm with statsmdodels all the time.  When running from the statsmodels git root, you need extenions built in place.  This is due to how Python handles paths. 

Either `pip install -e .` (prefered) or `python setup.py develop` (doesn't uninstall other versions).
