### ISSUE TITLE
Changing the variable order is not possible when using nested variables.

### ISSUE THREAD

**Issue by fhaust** [statsmodels/statsmodels#6305]
#### Describe the bug

Apparently it is not possible to change the order in which the variables are presented in the summary. 

Specifically I have multiple categorical variables and I want to fit a model without a general intercept:

    result ~ 0 + C(trial):C(gait) + C(marker) + height
    
Now in the summary want to have `trial:gait` as the "base intercept", but for whatever reason `marker` gets elected always. Changing the order of the variables does not change that [1].

The same thing can be observed in `mixedml` and  `BinomialBayesMixedGLM`.

I think this is related to the nested variable `trial:gait`. Using a model without nested variables does not have this problem.

--

#### Code Sample, a copy-pastable example if possible

```python

df = pd.DataFrame({
    'group': [1] * 10 + [2] * 10,
    'var1': np.random.rand(20) > 0.5,
    'var2': np.random.rand(20) > 0.5,
    'var3': np.random.rand(20) > 0.5,
    'var4': np.random.rand(20),
    'result': np.random.rand(20)
})


md = smf.mixedlm(
    'result ~ 0 +  C(var2):C(var3) + C(var1) + var4',
    df,
    groups=df.group
)

mdf = md.fit()

print(mdf.summary())

>>>

                  Mixed Linear Model Regression Results
=========================================================================
Model:                    MixedLM       Dependent Variable:       result 
No. Observations:         20            Method:                   REML   
No. Groups:               2             Scale:                    0.0979 
Min. group size:          10            Likelihood:               -7.5986
Max. group size:          10            Converged:                Yes    
Mean group size:          10.0                                           
-------------------------------------------------------------------------
                               Coef.  Std.Err.   z    P>|z| [0.025 0.975]
-------------------------------------------------------------------------
C(var1)[False]                  0.670    0.264  2.536 0.011  0.152  1.187
C(var1)[True]                   0.524    0.155  3.368 0.001  0.219  0.828
C(var3)[T.True]                 0.040    0.254  0.158 0.874 -0.458  0.539
C(var2)[T.True]:C(var3)[False] -0.165    0.218 -0.757 0.449 -0.593  0.263
C(var2)[T.True]:C(var3)[True]   0.001    0.272  0.005 0.996 -0.531  0.534
var4                            0.048    0.302  0.158 0.874 -0.544  0.640
Group Var                       0.000    0.214                           
=========================================================================                     

```

#### Expected Output

Changing the order of variables should result in an order change in the summary.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.7.3.final.0
OS: Linux 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

Statsmodels
===========

Installed: 0.10.1 (/home/xxx/.conda/envs/ill/lib/python3.7/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.17.2 (/home/xxx/.conda/envs/ill/lib/python3.7/site-packages/numpy)
scipy: 1.3.1 (/home/xxx/.conda/envs/ill/lib/python3.7/site-packages/scipy)
pandas: 0.25.1 (/home/xxx/.conda/envs/ill/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.0 (/home/xxx/.conda/envs/ill/lib/python3.7/site-packages/dateutil)
patsy: 0.5.1 (/home/xxx/.conda/envs/ill/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.1.1 (/home/xxx/.conda/envs/ill/lib/python3.7/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 0.13.2 (/home/xxx/.conda/envs/ill/lib/python3.7/site-packages/joblib)

Developer Tools
================

IPython: 7.8.0 (/home/xxx/.conda/envs/ill/lib/python3.7/site-packages/IPython)
    jinja2: 2.10.1 (/home/xxx/.conda/envs/ill/lib/python3.7/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.4.2 (/home/xxx/.conda/envs/ill/lib/python3.7/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed
</details>

**Comment by bashtage** [comment]
This is probably a patsy issue.

**Comment by fhaust** [comment]
Are *patsy* and *statsmodels* two disjoint groups? That is: should I create another issue there or is it probable that the *patsy* guys notice the issue here?

**Comment by bashtage** [comment]
Patsy has its own repo. You should post there. 

There answer to your coding question is probably here:

https://patsy.readthedocs.io/en/latest/categorical-coding.html

Closing since the variables are created by patsy and statsmodels just uses what patsy returns w/o modification.
