### ISSUE TITLE
differences between AR and SARIMAX equivalent

### ISSUE THREAD

**Issue by tsando** [statsmodels/statsmodels#6309]
I know `statsmodels.tsa.ar_model.AR` will be deprecated but at the moment I am seeing differences in the fitted parameter values of this and the SARIMAX equivalent. For example, according to me these two should be equivalent, and as you can see the fitted parameter values are similar, but not the same, in particular the constant value is more different. Do you know the reason for the difference? Many thanks!

![image](https://user-images.githubusercontent.com/13929456/70142425-1d8bed80-1691-11ea-87d8-038c1d138ce3.png)

vs 

![image](https://user-images.githubusercontent.com/13929456/70142448-28468280-1691-11ea-9180-07f91bcd62e6.png)

**Comment by bashtage** [comment]
http://www.statsmodels.org/devel/generated/generated/statsmodels.tsa.ar_model.AR.fit.html#statsmodels.tsa.ar_model.AR.fit

AR uses OLS by default, and so does not use information in the first 15 observations in your model. SARIMAX uses full MLE and so does.  The samples are not the same and these estimators only converge in the limit (and number of observations goes to infinity).
