### ISSUE TITLE
MAINT: Minimum version for 0.12

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#6352]
This is a placeholder to consider minimum version.  My suggestions are:

* Python: 3.6+: NumPy and pandas have moved to this.  [Nep-29](https://numpy.org/neps/nep-0029-deprecation_policy.html). f-strings.
* NumPy: 1.15+. This will be 2 years old by likely the time that 0.12 would be out. 4 versions initially supported. [Nep-29](https://numpy.org/neps/nep-0029-deprecation_policy.html). 
* SciPy: 1.2+.  This is the first version that was released after NumPy 1.15. Version 1.1 had no point releases and was released before NumPy. 3 versions initially supported.
* pandas: 0.23. This has a point release after 1.15 was released. 3 versions initially supported.
* matplotlib: 2.1. There was no minor of 2.0 after NumPy 1.15 was released.
* patsy: 0.5.1.

Other dependencies stay the same.

**Comment by ChadFulton** [comment]
I agree with this.

A couple of questions:

- Now that minimum version is 3.6, we could use f-strings. Any objection to using them?
- I guess we could already be using `matmul` / `@`. If we're not using them yet, any object to using them?

**Comment by josef-pkt** [comment]
I haven't paid much attention to version issues, so fine with me.

For newer features I think we leave it up to maintainer/developer.

I never used f-strings, and I'm still using mostly python 2 `%` formatting.

I started to use `@` in scripts, but personally I still like `dot` better in code. 
Don't forget to use parenthesis if there are matching matrix sizes to avoid large arrays. We might not have many cases where it matters.

**Comment by bashtage** [comment]
f strings are perfectly fine and IMO should be used whereever possible since they are just so much cleaner,

`f"The model could not be estimated because: {reason}"`

vs

`"The model could not be estimated because: {reason}".format(reason=reason)`

or

`"The model could not be estimated because: %s" % s`

F-strings are especially useful when you have multiple variables in a string.

> I guess we could already be using matmul / @. If we're not using them yet, any objection to using them?

I also think these should be used more rather than less.

Compare 

`Z.T @ X @ (X.T @ X)` with `Z.T.dot(X).dot(X.T.dot(X))`

**Comment by ChadFulton** [comment]
Sounds good, thanks!

**Comment by bashtage** [comment]
A strong argument I read for using more modern paradigms is that old code styles tend to put off newer users who are unfamiliar with Python 2.x syntax but are often more active. I agreed with when it came up in a discussion of NumPy's adoption of newer syntax/replacement of older syntax.  

Not that the goal is to wholesale replace working code, but in the idea of always moving the code in the direction of the best practice.

**Comment by bashtage** [comment]
Seems to have been implemented.
