### ISSUE TITLE
BUG : Cannot cast ufunc subtract output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

### ISSUE THREAD

**Issue by ADI10HERO** [statsmodels/statsmodels#6356]
When running Varmax with default config and following data we get :
" TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('int64') with casting rule 'same_kind' "

```python
import pandas as pd
import numpy as np
from statsmodels.tsa.statespace import varmax
import warnings

class Varmax:

    def __init__(self,y, order):
        self.kwargs = dict(

            exog= None,
            enforce_stationarity=False,
            enforce_invertibility=False,
            trend = 'c', # can be one of ['t','c','ct']
            error_cov_type='unstructured', # can be 
            measurement_error=False,
            trend_offset=1,
        )
        self.model= None
        self.order = order
    
    def fit(self,X,y):
        with warnings.catch_warnings():
            warnings.filterwarnings(action='ignore')
            self.kwargs['trend'] = 't'
            self.model= varmax.VARMAX(endog=y, order=self.order , **self.kwargs)
            self.model.fit()

X= np.random.normal(15,20,20).reshape(10,2)

y= np.random.normal(20,40,20).reshape(10,2)

obj=Varmax(y,order=[1,0])

obj.fit(X,y)
```

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>
INSTALLED VERSIONS
------------------
Python: 3.5.2.final.0
OS: Linux 4.4.0-1099-aws #110-Ubuntu SMP Fri Nov 15 00:08:08 UTC 2019 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

Statsmodels
===========

Installed: 0.10.0 (/usr/local/lib/python3.5/dist-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.16.4 (/home/aditya/.local/lib/python3.5/site-packages/numpy)
scipy: 1.2.2 (/home/aditya/.local/lib/python3.5/site-packages/scipy)
pandas: 0.24.2 (/usr/local/lib/python3.5/dist-packages/pandas)
    dateutil: 2.8.0 (/usr/local/lib/python3.5/dist-packages/dateutil)
patsy: 0.5.1 (/usr/local/lib/python3.5/dist-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.0.3 (/usr/local/lib/python3.5/dist-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 0.13.2 (/usr/local/lib/python3.5/dist-packages/joblib)

Developer Tools
================

IPython: 7.9.0 (/home/aditya/.local/lib/python3.5/site-packages/IPython)
    jinja2: 2.10.1 (/usr/local/lib/python3.5/dist-packages/jinja2)
sphinx: Not installed
    pygments: 2.4.2 (/usr/local/lib/python3.5/dist-packages/pygments)
pytest: 5.0.1 (/usr/local/lib/python3.5/dist-packages)
virtualenv: Not installed

</details>

**Comment by bashtage** [comment]
Fixed in master.

**Comment by bashtage** [comment]
Will be out in 0.11 next month.  You can get the rc now using `pip install statsmodels==0.11.0rc1`.
