### ISSUE TITLE
ENH: Add Prediction Intervals to Holt-Winters class

### ISSUE THREAD

**Issue by samtriolo** [statsmodels/statsmodels#6359]
#### Is your feature request related to a problem? Please describe
I'd like for statsmodels holt-winters (HW) class to calculate prediction intervals (PI).

#### Describe the solution you'd like
Please include a parameter (or method, etc) in the [holt winters class](https://www.statsmodels.org/dev/generated/statsmodels.tsa.holtwinters.ExponentialSmoothing.html) that calculates prediction intervals for the user, including eg upper and lower x / y coordinates for various (and preferably customizable) confidence levels (eg 80%, 95%, etc).

#### Describe alternatives you have considered
It seems there are very few resources available regarding HW PI calculations.  Some only cover certain use cases - eg only additive, but not multiplicative, trend.  So performing the calculations myself in python seemed impractical and unreliable.  The only alternatives I know of are to use the R forecast library, which does perform HW PI calculations.  

#### Additional context
According to one of the more [commonly cited](https://otexts.com/fpp2/ets-forecasting.html) resources on the internet on this topic, HW PI calculations are more complex than other, more common PI calculations.  The same resource (and a couple others I found) mostly point to the [text book](http://www.exponentialsmoothing.net/) (specifically, chapter 6) written by the author of the R library that performs these calculations, to see further details about HW PI calculations.  

####  Additional References
- [The R library](https://www.rdocumentation.org/packages/stats/versions/3.6.1/topics/predict.HoltWinters) that implements holt-winters, including prediction interval calculations.
- Some academic papers that discuss HW PI calculations: [one](https://www.sciencedirect.com/science/article/abs/pii/016920709090103I) and [two](https://core.ac.uk/download/pdf/48532500.pdf)

**Comment by wesleylongsworth** [comment]
This feature is the only reason my team hasn't fully migrated our HW forecasting app from R to Python . We've been successful with R for ~15 months, but have had to spend countless hours working around vague errors from R's forecast package. 

The PI feature is the only piece of code preventing us from fully migrating our enterprise forecasting tool from R to Python and benefiting from Python's much friendlier debugging experience.

**Comment by ChadFulton** [comment]
Thanks for letting us know!

I'll just mention for the pure additive cases, v0.11 has a version of the exponential smoothing models that will allow for prediction intervals, via the model at `sm.tsa.statespace.ExponentialSmoothing`.

Updating the more general model to include them also is something that we'd like to do. In general, I think we can start by adding the versions of them computed via simulation, which is a general method that will work for all models. Then later we could also add the explicit formulas for specific models when they exist, if there is interest in doing so.

**Comment by wesleylongsworth** [comment]
@ChadFulton good to know - our app allows for flexibility between additive and multiplicative seasonal patterns. Would both be supported with the changes you just mentioned?

**Comment by ChadFulton** [comment]
The `sm.tsa.statespace.ExponentialSmoothing` model that is already implemented only supports fully additive models (error, trend, and seasonal).

The simulation approach to prediction intervals - that is not yet implemented - is general to any of the ETS models.

**Comment by s-scherrer** [comment]
@ChadFulton: The simulation approach would be to use the state space formulation described [here](https://otexts.com/fpp2/ets.html) and with random errors as forecast and to estimate the interval from multiple runs, correct?

Are you already working on this or have this implemented somewhere? If not, I could try to implement it, and would appreciate some guidance on where and how.

**Comment by ChadFulton** [comment]
> The simulation approach would be to use the state space formulation described here with random errors as forecast and estimating the interval from multiple runs, correct?

Yes, that's what I was thinking about.

> Are you already working on this or have this implemented somewhere? If not, I could try to implement it, and would appreciate some guidance on where and how.

We don't have an implementation of this right now, but I think it would probably be straightforward. My guess is you'd want to first add a `simulate` method to the `statsmodels.tsa.holtwinters.HoltWintersResults` class, which would simulate future paths of each of the possible models.

Right now, we have the filtering split into separate functions for each of the model cases (see e.g. https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/_exponential_smoothers.pyx#L72 and the other functions in that file), but I think it would be easier to just make one function, similar to what I suggested in #4183 (e.g. https://github.com/statsmodels/statsmodels/pull/4183/files#diff-be2317e3b78a68f56f1108b8fae17c38R34 - this was for the filtering procedure but it would be similar for simulation).

Then once you have `simulate`, prediction intervals just call that method repeatedly and then take quantiles to get the prediction interval.

**Comment by s-scherrer** [comment]
Is there a reference implementation of the simulation that I can use for testing? I didn't find it in the linked R library.

**Comment by ChadFulton** [comment]
I think we can test against the `simulate.ets` function from the `forecast` package. Also, for the linear exponential smoothing models you can test against `sm.tsa.statespace.ExponentialSmoothing`, which allows simulation.

**Comment by s-scherrer** [comment]
Now that we have the simulations, it should be relatively straightforward to construct the prediction intervals. Should that be a separate function, or an optional return value of `predict`?

**Comment by ChadFulton** [comment]
I think the best way would be to keep it similar to the state space models, and so to create a `get_prediction` method that returns a results object.  For example:

```python
mod = sm.tsa.SARIMAX(endog)
res = mod.fit()

pred = res.get_prediction(start=mod.nobs, end=mod.nobs + 5)
```

See the `PredictionResults` object in `statespace/mlemodel.py`. For example, one of the methods is `summary_frame`, which allows creating a summary dataframe that looks like:

```
infl        mean   mean_se  mean_ci_lower  mean_ci_upper
2009Q4  1.780000  1.000000      -0.179964       3.739964
2010Q1  0.890000  1.118034      -1.301306       3.081306
2010Q2  0.445000  1.145644      -1.800421       2.690421
2010Q3  0.222500  1.152443      -2.036247       2.481247
2010Q4  0.111250  1.154137      -2.150816       2.373316
2011Q1  0.055625  1.154560      -2.207270       2.318520
```

**Comment by pritesh1082** [comment]
@s-scherrer  and @ChadFulton  -  I believe "ENH: Add Prediction Intervals to Holt-Winters class" will get added in **0.12** version. Could you please confirm? I'm very naive and hence would like to confirm that these forecast intervals are getting added in **ets.py**. Please correct me if I'm wrong.

Also, could you confirm on the release date?

**Comment by bashtage** [comment]
There is a new class ETSModel that implements this.

**Comment by pritesh1082** [comment]
@bashtage - Hi Kevin, thanks for your response. 

Currently, in my project, I'm using SimpleExpSmoothing model. But since, it doesn't have prediction intervals(95 and 80 % confidence intervals) like we've in R implementation, I was closely following the current issue. 

So now, I tried copying the libraries (ets.py and base.py) on my local set up under
C:\Users\xxxxx\anaconda3\Lib\site-packages\statsmodels\tsa\exponential_smoothing

However, on importing the module, below line in my code, throws an error.
from statsmodels.tsa.exponential_smoothing.ets import ETSModel
`
File "C:\Users\prite\anaconda3\lib\site-packages\statsmodels\tsa\exponential_smoothing\ets.py", line 166, in <module>
    import statsmodels.tsa.exponential_smoothing._ets_smooth as smooth
ModuleNotFoundError: No module named 'statsmodels.tsa.exponential_smoothing._ets_smooth'
]
`
I don't see `_ets_smooth.py` file under `exponential_smoothing`, so wondering what's the issue.

Could you please suggest.

Many thanks!

**Comment by pritesh1082** [comment]
@bashtage - thanks for your response.

**Comment by bashtage** [comment]
You need to install the release candidate.  See #6966

**Comment by pritesh1082** [comment]
thanks!
