### ISSUE TITLE
LinAlgError: SVD did not converge while using arima

### ISSUE THREAD

**Issue by danielpaz6** [statsmodels/statsmodels#6360]
I'm trying to run this code:

```
import pandas as pd
import numpy as np
from statsmodels.tsa.arima_model import ARIMA

data = np.array([347, 347, 347, 347, 347, 347, 347, 347, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, \
 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, \
 345, 345, 344, 314])

model = ARIMA(data, order=(2,1,0))
model_fit = model.fit(disp=0)
output = model_fit.forecast()
yhat = output[0]

yhat
```

and receive this error:

> LinAlgError: SVD did not converge

**Note:** If I remove the last cell in the data ( 314 ) it works just fine.

I wonder why it happens, and how can I solve that problem generally as this is part of my dataset that I need to predict.

**Comment by bashtage** [comment]
1. It might matter to convert your data to floats.  They look like ints.
2. Use SARIMAX instead of ARMIA  (or use tsa.arima.model.ARIMA instead od tsa.arima_model.ARIMA).

**Comment by bashtage** [comment]
Solution is to use the latest release candidate 

```
pip install statsmodels==0.11.0rc1
```

and to use

```
import pandas as pd
import numpy as np
from statsmodels.tsa.arima.model import ARIMA

data = np.array([347, 347, 347, 347, 347, 347, 347, 347, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, \
 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, 345, \
 345, 345, 344, 314])

model = ARIMA(data, order=(2,1,0))
model_fit = model.fit()
output = model_fit.forecast()
yhat = output[0]
```

**Comment by Stratix11** [comment]
Can I somehow install the latest release candidate using conda?

**Comment by bashtage** [comment]
No. You can use pip though: pip install statsmdoels=0.11.0rc1 --upgrade

**Comment by iDeepro** [comment]
I found that putting the code in a try/except block fixed the problem for me and provided expected results.
