### ISSUE TITLE
ENH DOC index pages missing in dev docs

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#6367]
The new dev docs don't have index pages anymore
http://www.statsmodels.org/stable/index.html#indices-and-tables

I'm not looking at them often, but they are still useful, IMO
(e.g. which models have `llnull` and `loglike_obs` http://www.statsmodels.org/stable/genindex.html#L and which have `loglikeobs` :)

**Comment by bashtage** [comment]
They do.  Look at the bottom of the home page. 

https://www.statsmodels.org/dev/genindex.html#L

**Comment by josef-pkt** [comment]
good

I was looking for them on the left side bar and didn't check the home page
