### ISSUE TITLE
BUG: maxlags parameter in VAR model shouldn't effect #exogenous variables in the model

### ISSUE THREAD

**Issue by mkumar73** [statsmodels/statsmodels#6376]
#### Bug description

First, the "maxlags" parameter in VAR.fit() method is misleading. In principle, it should just be the endogenous "lag" value extracted from "select_order" as indicated in the code snippet below.

Second, the maxlags parameters in VAR.fit() should only effect the number endogenous variables based on the maxlag value provided. It should never effect the total number of exogenous variables included in each of the VAR model equation as shown in the example below (in details section).

#### Code Sample

```python
from statsmodels.tsa.api import VAR

# this is just a sample code for illustration purposes.
model = VAR(endog=endo_df, exog=exo_df)
lag_dict = model.select_order(4)
lag = lag_dict.selected_orders['aic']

# lets, say the lag value is 2 in this case
result = model.fit(maxlags=lag)
```
<details>

Example:

Consider a scenario, where the number of exogenous variables is 5, number of endogenous variable is 2 and the I am providing the maxlag parameter value as 2 in VAR.fit() model.

Each of the VAR model for both the endogenous variables should always included 5 exogenous variables in addition to the lagged values of the two endogenous variables.

In my usecase, the maxlag parameter is affecting the total number of exogenous variables included in the model apart from the endogenous variables.

#### Expected Output
Expected equation for the endogenous variables from the VAR model:

```math 
endo_V1 = L1.endo_V1 + L2.endo_V1 + L1.endo_V2 + L2.endo_V2 + exo_V1 + ..... + exo_V5

endo_V2 = L1.endo_V1 + L2.endo_V1 + L1.endo_V2 + L2.endo_V2 + exo_V1 + ..... + exo_V5

```

#### Output of ``import statsmodels.api as sm; sm.show_versions()``
version: '0.10.2'
</details>

**Comment by ChadFulton** [comment]
Thanks for submitted this issue. Can you post a fully replicable example, including data (simulated data is fine if it replicates the problem).

I wasn't immediately able to replicate a change in the number of `exog` variables included in the model coming from the `maxlags` argument.

**Comment by bashtage** [comment]
Are you looking at summary or params? I think summary might not be correct
in 0.10.2.

**Comment by mkumar73** [comment]
@bashtage I am looking at the summary. Is the issue with summary been resolved in later version of statsmodels?
Apart from this, I also want to extract each equation from the VAR model so that I can analyse feature importance separately for each endogenos variable. Could you please comment on that.?

**Comment by mkumar73** [comment]
> Thanks for submitting this issue. Can you post a fully replicable example, including data (simulated data is fine if it replicates the problem).
> 
> I wasn't immediately able to replicate a change in the number of `exog` variables included in the model coming from the `maxlags` argument.

@ChadFulton Please see the [`https://drive.google.com/file/d/1r7b3tR2f-CCe56emjVPhhCYODgG5vD1f/view?usp=sharing`](url) notebook attached for your reference. I have also added comments to explain my queries better in the notebook. 
Thank you.

**Comment by bashtage** [comment]
> Apart from this, I also want to extract each equation from the VAR model so that I can analyse feature importance separately for each endogenos variable. Could you please comment on that.?

There are no methods available that simplify this operation.  You would need to manually use OLS.

**Comment by mkumar73** [comment]
@bashtage thank you for the feedback and resolving exog names issue.
