### ISSUE TITLE
tests for load_pickle and save_pickle

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#638]
pickling is tested through the result instances

There was the original commands for testing the standalone functions commented out in the tests, removed now by PR #637 

Do we need separate test for the stand alone functions?

(opened also to just leave a paper trail)

**Comment by josef-pkt** [comment]
there are basic tests for the save_pickle load_pickle function at statsmodels/statsmodels/iolib/tests/test_pickle.py

as clarification (years later)
The commented out and removed parts were for using the standalone function directly with a results instance instead of using the methods in statsmodels/base/tests/test_shrink_pickle.py:test_pickle_wrapper

**Comment by bashtage** [comment]
These are well tested now from what I can see.
