### ISSUE TITLE
statsmodels.api.tsa.statespace.ExponentialSmoothing models too reactive

### ISSUE THREAD

**Issue by SLeiro** [statsmodels/statsmodels#6393]
#### Describe the bug

The models select are too reactive and does not matches the expected values when 

#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import statsmodels.api as sm
freq =  'W'
df = pd.DataFrame({
            'tim_day_winning_date': pd.date_range(start=pd.to_datetime('2019-08-04') - pd.Timedelta(value=12, unit='W'),
                      end=pd.to_datetime('2019-08-04'), 
                      freq='W'),
            'bid_quantity_ok':[20,25,20,25,20,25,20,25,20,25,20,25,200]
        })
endog = pd.Series(data=df.bid_quantity_ok.ravel(), index=df.tim_day_winning_date).asfreq(freq='W')
end_date = pd.to_datetime('2019-08-04')
start_date = end_date - pd.Timedelta(13, freq)
model = SimpleExponentialSmoothing(freq,  end_date, start_date)
model = sm.tsa.statespace.ExponentialSmoothing(endog, initialization_method='known', initial_level=0.1)
model = model.fit(**fit_params)
X = pd.date_range(start=end_date + pd.Timedelta(1, freq), periods=2, freq='W')
prediction = model.get_prediction(start=X[0], end=X[-1])
predict_ci = prediction.conf_int(alpha=1 - 0.9)
means = prediction.predicted_mean
df_result = means.to_frame().join(predict_ci)
df_result.columns = ['y_hat', 'y_lower', 'y_upper']
df_result
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

The output it around 199 and i was expecting it was near 20 or 25

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

</details>

**Comment by josef-pkt** [comment]
I think this is a feature of ES.

AFAIR, I saw a stackoverflow question like this for R. An outlier in the last position throws of ES and similar.
In an integrated model (that uses diff from the last observation) like a random walk continuous from the last observation, which is an outlier in this case compared to the previous observations.
