### ISSUE TITLE
BUG: sarimax fit-predict values are nan when time series length is 17

### ISSUE THREAD

**Issue by HamidM6** [statsmodels/statsmodels#6396]
#### issue

for time series with length 17, sarimax with order=(1,1,1), seasonal_order=(0,1,0,12), and trend='n'
produces np.nan as fitted and predicted values.

#### Code Sample

```python
import random
import statsmodels.api

y = random.sample(range(100,200), 17)

sarimax_model = statsmodels.api.tsa.statespace.SARIMAX(
                                                            endog = y,
                                                            order = (1,1,1),
                                                            seasonal_order = (0,1,0,12),
                                                            trend = 'n'
                                                       ).fit()

sarimax_model.fittedvalues
sarimax_model.predict(start=len(y), end=len(y)+11)

```
#### Expected Output

above model fails for time series with length < 17 but for time series with length > 17 it behave normal.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
Python: 3.7.1.final.0

Statsmodels
===========

Installed: 0.10.2 (\Local\Continuum\anaconda3\lib\site-packages\statsmodels)

</details>

**Comment by alexpghayes** [comment]
I have also been coming across a number of bizarre behaviors for short time series where the predictions are `nan` at times and reasonable at others. Unfortunately can't share data, but this has been pretty painful, especially when implementing rolling CV; small initial windows can do weird things.

**Comment by ChadFulton** [comment]
This is an area where we can improve.  Examples of problems and what a better solution would look like would be very useful.

**Comment by ChadFulton** [comment]
In this example, it is an issue computing starting parameters that should be relatively easy to fix.
