### ISSUE TITLE
Wrong text in logotype?

### ISSUE THREAD

**Issue by Juanlu001** [statsmodels/statsmodels#6402]
I assume the name of the project is statsmodels, but the logotype says statsmodel (without the final "s"):

![Screenshot_2020-01-10 Introduction — statsmodels](https://user-images.githubusercontent.com/316517/72144650-198e7200-3399-11ea-943a-40b19780b73e.png)

(Latest Firefox on latest Linux Mint)

**Comment by bashtage** [comment]
Where are you seeing this?

**Comment by bashtage** [comment]
This is what I see in Chrome

![image](https://user-images.githubusercontent.com/5585221/72148493-e1872f00-3398-11ea-879c-b2c9997bc623.png)

**Comment by bashtage** [comment]
And latest firefox/windows

![image](https://user-images.githubusercontent.com/5585221/72148550-0d0a1980-3399-11ea-96d0-34ab31aafd2c.png)

**Comment by bashtage** [comment]
This fonts in your logo are also wrong, which is really strange since it is a SVG.

**Comment by Juanlu001** [comment]
Thanks for your quick response, I'm happy to know that this is not an oversight but actually a problem of my crappy browser / OS :sweat_smile: 

I tried Chromium and this has the proper font and full name. I'm not an expert in web fonts / SVG but I'm happy to provide more information. In any case, closing.

**Comment by bashtage** [comment]
Thanks for the follow up. Strange for firefox to render wrong.
