### ISSUE TITLE
RLS: Release Candidate 2 for v0.11.0 is now out

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#6417]
The second (and final) release candidate has been posted to PyPI. Please report any issues here.

**Comment by ChadFulton** [comment]
Thanks for all the work getting this RC2 out!

**Comment by bashtage** [comment]
@ChadFulton @kshedden @josef-pkt I will release later today if there are no objections. There have been no bugs reported, and @kshedden most recent patch seems to need a bit of work.  It can go in a 0.11.1 release in a month or so.

**Comment by ChadFulton** [comment]
Sounds good to me, thanks @bashtage

**Comment by josef-pkt** [comment]
There might be a more serious bug in GLM fit_regularized ridge, that I just saw. one line change if correct.

**Comment by bashtage** [comment]
v0.11.0 is out now.
