### ISSUE TITLE
BUG GLM fit regularized ridge version has wrong "weights", vector alpha

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#6441]
fit_ridge has
```
        def fun(x):
            return -(self.loglike(x) / self.nobs - alpha * np.sum(x**2) / 2)

        def grad(x):
            return -(self.score(x) / self.nobs - alpha * x)
```

which is wrong if alpha is a vector, which is allowed especially for the case when we don't want to penalize the constant.

the negloglike needs to multiply by alpha before computing the squared sum, i.e.

`return -(self.loglike(x) / self.nobs - np.sum(alpha * x**2) / 2)`

**Comment by josef-pkt** [comment]
@kshedden @bashtage

**Comment by bashtage** [comment]
This bug is already in 0.10+, and so while it shoudl should be fixed, it doesn't seem to be a blocker.  Moreover if alpha is an array, then fun(x) is a vector and it is likely that it will blow up.

**Comment by josef-pkt** [comment]
> Moreover if alpha is an array, then fun(x) is a vector and it is likely that it will blow up.

ok, I didn't think of that. Then this is a regular bug that can wait, not a high priority bug that silently returns wrong numbers
