### ISSUE TITLE
ValueError: freq T not understood. Please report if you think this is in error.

### ISSUE THREAD

**Issue by sarahboufelja54** [statsmodels/statsmodels#6463]
#### Describe the bug

[I am reopening this issue because the last thread did not solve my issue: I am working with a huge set of time series, sampled every 1 minute and I would like to run automatically a STL decomposition. However I get stuck on this error: ValueError: freq T not understood. Please report if you think this is in error.
Although I have provided an DateTime index, I keep getting this error and as I am not supposed to know the periodicity of my time series, I should be able to rely on the function to get this info automatically. ]

#### Code Sample, a copy-pastable example if possible

```python
import SciPy as scp
import statsmodels.tsa.seasonal as tsa
toto , lmbd = scp.stats.boxcox(x)
toto.set_index(data['28'].index, inplace=True)
tsa.seasonal_decompose(toto)```
<details>
In the example above data is a data frame of 3000 time series.

#### Expected Output

Outputs the Seasonal and Trend and Residuals for my 3000 time series without specifying explicitly the signal period.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

Installed: 0.10.0 (/Users/.../anaconda3/lib/python3.7/site-packages/statsmodels)

**Comment by bashtage** [comment]
You can just directly provide the period when it isn't understood.

http://www.statsmodels.org/stable/generated/statsmodels.tsa.seasonal.seasonal_decompose.html?highlight=seasonal%20decompose

You need to upgrade to 0.11.0 for this feature.

**Comment by sarahboufelja54** [comment]
Thank you @bashtage , I am looking for an automated way to perform the decomposition, which means I don't want to provide the period manually. I am dealing with thousands of Time series and it would be unfeasible for me to track down every exception. Also, I would really appreciate if you can explain why some periods are not understood from the data. Thank you.

**Comment by bashtage** [comment]
It isn't possible to support `T` since it is ambiguous.  What is a full period?  1 Hour (60), 1 Day (1440), 1 trading day (390 in US equities), 1 5-day Week (7200), a 7-day week, etc.  All you need to be is write your own function which makes freq to the period you want to use, e.g. T->?? and then pass ?? in as period=??.

**Comment by bashtage** [comment]
To be clear, frequencies cannot be converted to the period if the full period is ambiguous. This is mostly a limitation of pandas which only contains frequency and not period information in the index.

**Comment by sarahboufelja54** [comment]
I am afraid my question was snot understood correctly. Had I known my TS periods, there wouldn't be any problem.

**Comment by bashtage** [comment]
The frequency to period conversion is a lookup table.  It is not a statistical method.  It sounds like you want something that can estimate the period, which is not the intention or capability of `seasonal_decompose`.
