### ISSUE TITLE
SARIMAX memory issue

### ISSUE THREAD

**Issue by alexsmartens** [statsmodels/statsmodels#6476]
#### Describe the bug

I developed a simple multiprocessing grid search for searching SARIMAX order. On each iteration, I fit a SARIMAX model and then delete the results (for demonstration purpose in this case). What I've been noticing is that deleting the SARIMAX model and results frees up only some memory from the whole memory that was taken by the object. As the result, I'm the amount of available memory quickly declines and potentially results in SIGKILL. 

I've been trying to find the leak in my code as well as running SARIMAX with different lists of orders and in different code structures, but it did not help. From what I'm seeing, it feels deleting the SARIMAX model and results somehow keeps references to some internal stuff and python garbage collector does not clean it up.
 
#### Code Sample, a copy-pastable example if possible

Dataset: [my_data_sample3.csv](https://drive.google.com/file/d/19DTnMaIHBsTKeDZDLSL6ZmcCJowN1y9-/view?usp=sharing)

```python
import gc
from os import getpid
import datetime as dt
import numpy as np
import pandas as pd
import statsmodels.api as sm
import multiprocessing as mp
import queue as qExcept


def prepare_orders(queue_orders, ranges=None):
    d = 1

    q_cnt = 0
    for p in np.arange(ranges["p"][0], ranges["p"][1], ranges["p"][2]):
        for q in np.arange(ranges["q"][0], ranges["q"][1], ranges["q"][2]):
            if p + q > 0:
                queue_orders.put((p, d, q))
                q_cnt += 1
    return q_cnt


def fit_model(endog, order):
    mod = sm.tsa.SARIMAX(endog, order=order)
    res = mod.fit(disp=0)
    row_model = pd.Series({
        "mod": mod,
        "res": res,
        "AIC": res.aic
    })
    del mod
    del res
    return row_model


def grid_subsearch_sarima(endog, queue_orders, q_len_init):
    pid = getpid()
    t_start = dt.datetime.now()
    print("---> Started process ## {}".format(pid))

    iter_cnt = 0
    while not queue_orders.empty():
        try:
            order = queue_orders.get(timeout=1)
            iter_name = " ".join(map(str, order))
            print("{:.4f}% of the queue items are utilized".format((1 - queue_orders.qsize() / q_len_init) * 100))
            print(">> PID #{} start iter {}: {}".format(pid, iter_cnt + 1, iter_name))

            mod_dict = fit_model(endog, order)
            mod_dict["name"] = iter_name

            iter_cnt += 1
            print("|| PID #{} finished iter {}: {}".format(pid, iter_cnt, iter_name))

            del iter_name
            del order
            for key in ["mod", "res", "AIC"]:
                del mod_dict[key]
            del mod_dict
            gc.collect()
        except qExcept.Empty:
            # Handling empty queue exception
            pass

    t_end = dt.datetime.now()
    print("---> Finished process ## {}, iterations: {}, running time: {}".format(pid, iter_cnt, t_end - t_start))
    return None, None



if __name__ == "__main__":
    endog = pd.read_csv("my_data_sample3.csv", index_col=0, parse_dates=True)
    endog = endog.asfreq(pd.infer_freq(endog.index))

    print("=> START grid search")

    ranges = {
             "p": [0, 20, 1],
             # "d": 1, # defined in the prepare_orders function
             "q": [0, 20, 1],
             }

    m = mp.Manager()
    q_orders = m.Queue()
    q_len_init = prepare_orders(
        q_orders,
        ranges,
    )
    cpu_cnt = mp.cpu_count()

    # Run pool of processes
    pool = mp.Pool(processes=cpu_cnt)
    run_process = lambda i: pool.apply_async(grid_subsearch_sarima, args=(endog, q_orders, q_len_init))
    result_map = list(map(run_process, range(cpu_cnt)))

    results = [r.get() for r in result_map]
    res_mod, res_prob = zip(*results)

    print("=> FINISH grid search")
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

#### Memory usage
Here is my RAM usage plot dropping from 94% of free memory to 0% after about an hour of running this code: 
  <img 
    src="https://user-images.githubusercontent.com/26261714/73227656-2f928580-4142-11ea-9b08-52fa1d5b667f.png"
    alt="Memory usage"
    width="400" 
    height="250"
    hspace="20"/>

[Edit: Added memory plot for running a different order of parameters]
Here is how the first hour memory usage looks like when I run the same code but start my iterations from fitting the most complex models (only the range is reversed, as shown below)
```
    ranges = {
             "p": [20, 0, -1],
             # "d": 1, # defined in the prepare_orders function
             "q": [20, 0, -1],
             }
```
  <img 
    src="https://user-images.githubusercontent.com/26261714/73231540-a5045300-414e-11ea-890c-0bd76cc1cb29.png"
    alt="Memory usage, reversed range order"
    width="500" 
    height="250"
    hspace="20"/>

I have 64GB of RAM and a CPU with 64 threads.

#### Expected Output

The memory would be taken and then returned, something like fluctuation from the same baseline with an increasing amplitude.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``
`0.11.0.dev0+628.g17f7c3481`

**Comment by bashtage** [comment]
Does it happen if you don't use multiprocessing?

**Comment by alexsmartens** [comment]
I'm working on figuring that out. The difficulty is that it takes days to run this code without multiprocessing

**Comment by bashtage** [comment]
I would hope that all that is needed is the trace for a couple of hours.  Especially if you do the reverse version.

**Comment by alexsmartens** [comment]
Thanks for your suggestion @bashtage!
I've tested running the same code without `multiprocessing` as well as with only one process from `multiprocessing`. As it can be seen from the plot below, my maximum ram usage over 8 hrs was 21% and the memory always went back to normal after each iteration.
![image](https://user-images.githubusercontent.com/26261714/73574572-0b85bb80-4444-11ea-947d-ee15979ab935.png)

**There is no memory leak in SARIMAX**, I'm sorry for bringing this question up

**Comment by bashtage** [comment]
It cpuid still be in SARIMAX. When you use multiprocess your end up picking models to pass between workers. I'll leave it closed but it might. crop up again. The experiment would be to crazy, pickle, del, load, and then estimate.

**Comment by ChadFulton** [comment]
Thanks for following up, and sorry for not being more helpful earlier.

One thing (that you may already know about and might not be relevant to your situation) is that if you're just doing model selection, you often don't need all of the results, and you can use the `low_memory=True` option to `fit` (new in v0.11).  You lose some features from the results object when you do that (like confidence intervals, smoothed results, and dynamic in-sample prediction), but you can still do regular in-sample prediction, out-of-sample forecasting, and you can compute e.g. information criteria.

**Comment by alexsmartens** [comment]
@bashtage, @ChadFulton 
_I noticed some unexpected behavior_
when I run out of RAM some processes stop executing and never continue and/or return after that.

_How did I see that_
1) In the end of the runtime, some processes hang and never return
2) I track the number of iterations in each process, and the number of Iterations for these "stuck" processes never change once I run out of memory.

I saw the same behaviour with `SARIMAX` and `arima` fitting.

It feels like an error is silenced somewhere during model fitting. What do you think about that? Is there any why I could check that for sure, maybe generating more logs?

**Comment by ChadFulton** [comment]
Thanks for the report. Unfortunately, this looks like it may be pretty hard to diagnose (at least to me, maybe someone else who knows more will have a good idea).

I can't think of a reason why an error would be silenced - I don't think we have any `try...except` blocks that discard errors, for example.

It's hard to know where to start looking for such a problem - is it something with Scipy's optimizer, for example? Or is it something with the Kalman filter loop? Or something else?

The only hope I think would be to find a reproducible example, but I don't know how hard that will be.

**Comment by alexsmartens** [comment]
> The only hope I think would be to find a reproducible example, but I don't know how hard that will be.

I think I can provide an example. 

What kind of hardware do you have (amount of RAM & \# of cores & (optional) CPU model)? The less RAM you have the easier will it be to replicate the issue. I will try running my example on a similar setup and making sure I can replicate this issue before posting the example

**Comment by bashtage** [comment]
@alexsmartens Did you ever determine whether this was a legit bug or something else?

**Comment by alexsmartens** [comment]
No, I did not. I've been focused on something else over the last few months, sorry

**Comment by bashtage** [comment]
Going to close since no obvious fixes from these experiments.
