### ISSUE TITLE
missing values in PCA

### ISSUE THREAD

**Issue by StevenLi-DS** [statsmodels/statsmodels#6483]
`statsmodel: 0.11.0`

consider the following example: 

```python
import numpy as np
from statsmodels.multivariate.pca import PCA

x = np.random.randn(100)[:, None]
x = x + np.random.randn(100, 100)
x = np.insert(x, 1, np.nan, axis=1)

pc = PCA(x)
```
Returns
`LinAlgError: SVD did not converge`

I would say we should set a default value for `missing`. (or at least change the error msg for users). Meanwhile, by default, we have `standardize=True`, which will also need missing values handling. So right now it seems like the `PCA` does something for the missing value first and then doesn't do anything for the actual pca part? 

* change the error message
* or set a default value for missing values
* add how missing values are handle for  `standardize=True` in the doc.

https://www.statsmodels.org/stable/generated/statsmodels.multivariate.pca.PCA.html

**Comment by bashtage** [comment]
See the option "fill-em".

**Comment by bashtage** [comment]
There are also options to drop rows or drop columns.

**Comment by bashtage** [comment]
Will raise on missing if correct options are not set.
