### ISSUE TITLE
Undocumented (and unused?) `what` parameter in `summary_frame`

### ISSUE THREAD

**Issue by MarcoGorelli** [statsmodels/statsmodels#6489]
I was looking at [the documentation for PredictionResults](https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.PredictionResults.html) and noticed that the method `summary_frame` is listed at the bottom of the page. If I click on it, I see:

> statsmodels.regression.linear_model.PredictionResults.summary_frame
> 
> PredictionResults.summary_frame(what='all', alpha=0.05)[source]

It's clear (I think) that `alpha` is 1 minus the confidence level, but what about `what`?

(am happy to submit a PR to address this, if it's clarified what the intention of the parameter is. Looking at the source code, it appears it's unused)

**Comment by bashtage** [comment]
It does nothing. `summary_frame` seems to have never been completed.

**Comment by bashtage** [comment]
https://www.statsmodels.org/dev/_modules/statsmodels/regression/_prediction.html#PredictionResults.summary_frame

**Comment by bashtage** [comment]
`what` should be deprecated and removed.

**Comment by josef-pkt** [comment]
#2151

The idea was to add optional returns as pandas DataFrame, regular returns are not pandas AFAIR. 
Sometimes I add keywords for future proofness and as signal that something will change, but the anticipation will not always be correct.

In OLS, there isn't much extra in predict. Kerby's simultaneous confidence intervals are not connected.
GLM has a bit more and different get_prediction results.
`discrete` is still missing get_prediction, the zero_inflated predict has many options for `what`.

`summary_frame` could be whatever is useful to users. I often have only a vague idea what users might want.

**Comment by bashtage** [comment]
Fixed
