### ISSUE TITLE
how to predict the future steps when I have done statsmodels.tsa.seasonal.seasonal_decompose ?

### ISSUE THREAD

**Issue by XiaoLaoDi** [statsmodels/statsmodels#6502]
after statsmodels.tsa.seasonal.seasonal_decompose, I get the model.resid, model.seasonal, model.trend， But how to predict the future with the three parts, is there any api I can use?

**Comment by XiaoLaoDi** [comment]
![image](https://user-images.githubusercontent.com/20012774/74208415-734aca80-4cbe-11ea-8ada-ee86d9ee6f70.png)
here is the three parts I got.

**Comment by XiaoLaoDi** [comment]
when I try to use other time series analysis method , such as statsmodels.tsa.holtwinters.Holt, there is a predict() method I can use to forecast the future steps, But I cannot find one in statsmodels.tsa.seasonal.seasonal_decompose.

**Comment by bashtage** [comment]
`seasonal_decompose` is intended for retrospective decomposition. It uses 2-sided windows and so isn't appropriate for forecasting.
