### ISSUE TITLE
In SARIMAX prediction, the exog itself is not for sure.

### ISSUE THREAD

**Issue by xiasummer** [statsmodels/statsmodels#6507]
I found a problem of the SARIMAX model，
If we have a signal source as exog, we can forecast the endog series through SARIMAX model.
While the exog itself might be not certain. How do we deal with that?

----

In my case, I want to predict series A,B and C. 
A, B are ARIMA model, they can be predicted quite well(While the closer to now, the preciser).
C is based on A and B as an ARIMAX model, (A,B) being the 'X' part or exog part. 
But when forecasting, I don't know A, B for sure in all future. Actually I know quite sure for closer A_t and B_t, but not quite sure for further A_t and B_t. 

But in ARIMAX model, we only have "exog", no "exog_ci" or "exog_std_error"  parameter,  meaning you think you know exogs for "SURE". While it's often not the case.

So how do can we make a good forecast with right confidence interval of C, while also consider the confidence interval of A and B?

**Comment by bashtage** [comment]
When forecasting more than 1 step ahead, you replace future values of variables with their expectations, 
For example, if your model is

y[t] = a + b y[t-1] + c x[t-1] + e[t]

then 

E[y[t+2]] = a + b E[y[t+1]]] + c E[x[t+1]]

where E[] is the time-t conditional expectation. The 2-step for y depends on the 1 step forecast of both y and x.

To get confidence intervals correct you would need to use a system estimator such as a VAR.
