### ISSUE TITLE
BUG: Multipletesting/FDR is broken on future NumPy/SciPy

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#6524]
#### Describe the bug

Many failures when testing against future SciPy and NumPy. Seem to be systematic.  There are changes to SciPy's optimizers coming in 1.5 which might be at the root of the issue.

See  https://travis-ci.org/statsmodels/statsmodels/jobs/651893167

**Comment by bashtage** [comment]
ping @josef-pkt @kshedden  in case you have any insights.  Some of the values are way off, for example

```
E            x: array([9.9e-324, 1.5e-323, 2.0e-323, 2.5e-323, 1.2e-002, 1.2e-002])
E            y: array([0.012, 0.012, 0.012, 0.012, 0.012, 0.012])
```

**Comment by bashtage** [comment]
Seems to be fixed.

**Comment by josef-pkt** [comment]
fixed in numpy during development cycle
