### ISSUE TITLE
Save and load methods for kde

### ISSUE THREAD

**Issue by dmey** [statsmodels/statsmodels#6525]
I am looking to save (and later reopen) the parameters computed by [statsmodels.nonparametric.kde.KDEUnivariate](https://www.statsmodels.org/stable/generated/statsmodels.nonparametric.kde.KDEUnivariate.html). Is there a way to save (and load) such data using  statsmodels?

**Comment by bashtage** [comment]
You should be able to pickle them. Does that solve your problem?

**Comment by dmey** [comment]
@bashtage my issue with this is that the object with the underline  data will be saved. Ideally I would like to compute the KDE so that I can discard my original data and only save the parameters. Then at a later stage, reconstruct the KDE and compute the icdf. Otherwise, the icdf, can be computed directly from the data without recurring KDE. Does this make sense?

**Comment by josef-pkt** [comment]
Kernel estimates don't really have parameters, they are smoothing the original data for every case, e.g. for every prediction or for kde at a new point.

One parameter that can be reused is the bandwidth.

However,
In the "fast" version, e.g. when using fft, kde computes the density based on a grid of values and not the original data. 
AFAIK, there is no way to keep just the grid version of the kde.

**Comment by bashtage** [comment]
There are three options:

1. Save the optimized bandwidth, in which case you can recreate the instance without any computation in the further using the same data the estimated optimal bandwidth. You could then produce the same density plot of supply a different set of points to evaluate the density at using the full object.
2. Save the data and CDF/iCDF at the points you used which lets you have these in the future. 
3. Pickle the complete object which lets you restore the pickle and use it.

There doesn't appear to be anything we can do here, so I'm going to close this.
