### ISSUE TITLE
How to change forecasting model in short and far simulation?

### ISSUE THREAD

**Issue by xiasummer** [statsmodels/statsmodels#6529]
#### Is your feature request related to a problem? Please describe
In a forecasting model, we know things will change in short future and long future.
Like asset returns forecasting, in the near future, assets return can contain a "trend" component, but in the long run, all asset returns must stay stable, it will never follow any time trend forever.

#### Describe the solution you'd like
So I want to have different forecasting models for the near and long horizons. 
In the short run, I want preciser forecasting, so I need the trend component, but in the long run, I want to model to "calm down" to a stable band.

In a simulation, I want that feature, in the short run, a SARIMAX model with trend,  while in the long run, a SARIMAX model without trend.

#### Describe alternatives you have considered
No yet.

**Comment by bashtage** [comment]
What you are describing is any covariance stationary ARMA model.  Short-run forecasts may differ from the long-run level, but eventually, the forecast mean reverts.
