### ISSUE TITLE
pip doesn't recognize py2 deprecation from pypi

### ISSUE THREAD

**Issue by nicoa** [statsmodels/statsmodels#6533]
#### Describe the bug
As one [sees on pypi, v0.10.2](https://pypi.org/project/statsmodels/0.10.2/) is the last supported py2-version, under python 2 [version 0.11](https://pypi.org/project/statsmodels/0.11.0/) shouldn't be installed.

#### Code Sample, a copy-pastable example if possible

```bash
(my-env) $ pip install statsmodels
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. …
Collecting statsmodels
  Downloading statsmodels-0.11.0.tar.gz (15.4 MB)
```

#### Expected Output

Expected would be to having 0.10.2 installed.

#### Further Information
please compare [this issue on pandas-gbq](https://github.com/pydata/pandas-gbq/issues/306#issuecomment-568487470) with similar problems.

**Comment by bashtage** [comment]
closed by #6535 and v0.11.1 release
