### ISSUE TITLE
PACF and ACF plots diplays to plots

### ISSUE THREAD

**Issue by karasjoh000** [statsmodels/statsmodels#6538]
ran `plot_acf(diff1)` and `plot_pacf(diff1)`. 
The cell output displays two plots for each function call instead of one.

**Comment by bashtage** [comment]
Just assign the output of the call.  This is an ipyhton feature that shows
the repr is the last line if not assigned. You can use _=plot...
Alternatively don't have the plot as the last line.

**Comment by karasjoh000** [comment]
Do you know how I can save pacf and acf to a pdf?

**Comment by bashtage** [comment]
Use savefig which is attached to any figure instance.  That is more of a matplotlib question.
