### ISSUE TITLE
Bug saving and loading a SARIMAX model incl. solution

### ISSUE THREAD

**Issue by ViktorKnoben** [statsmodels/statsmodels#6542]
I've found a bug when saving and loading a fitted SARIMAX model. The bug can be recreated using the following set of commands (you must use your own models though):

`#Saving the model and resultwrapper`
`outfile = open(main_path+"\\SARIMAX_model.pickle","wb")`
`pickle.dump(SARIMAX_model,outfile)`
`outfile.close()`

`results.save(main_path+"\\SARIMAX_results.pickle")`

`#Loading the model and resultwrapper`
`with open(main_path+"\\SARIMAX_model.pickle","rb") as f:`
`    SARIMAX_model = pickle.load(f)`

`results = sarimax.SARIMAXResultsWrapper.load(main_path+"\\SARIMAX_results.pickle")`

`#Make a prediction`
`pred = results.get_prediction(start = datetime.datetime.strptime("20190302","%Y%m%d"),
                    end = exog_forecast.index.max(),
                    exog = pd.concat([exog_test,exog_validate,exog_forecast]))`

The classes of the objects are `SARIMAX_model.__class__ = statsmodels.tsa.statespace.sarimax.SARIMAX` and `results.__class__ = statsmodels.tsa.statespace.sarimax.SARIMAXResultWrapper`  

The bug occurs once you make an out-of-sample prediction (predicting the future) given your SARIMAX model has a `k_exog>0`. It breaks on line 1915 of `sarimax.py` with the following value error:
`ValueError: all the input array dimensions except for the concatenation axis must match exactly`

Let's analyse the problem in line 1915: `exog = np.c_[self.model.data.orig_exog.T, exog.T].T`. It takes the transpose of the exogeneous data on which the model is trained, vertically concatenates this to the transposed new exogenous data and then transposes it back again. Unfortunately the exogeneous data on which it is trained also contains a column containing the predictions of the SARIMAX model, hence we have a excess column. 

The solution becomes: `exog = np.c_[self.model.data.orig_exog.iloc[:,:-1].T, exog.T].T` . I'm happy to report this only took me several days to fully comprehent the nature of the error :D.

Hopefully this is of help to someone,

**Comment by bashtage** [comment]
Can you provide a copy and pastable demo of the problem?  Helps a lot.

**Comment by ViktorKnoben** [comment]
You're in luck as I've found a similar code on the official documentation. Borrowing a bit I came to the following example.

`import numpy as np`
`import pandas as pd`
`from scipy.stats import norm`
`import statsmodels.api as sm`
`import matplotlib.pyplot as plt`
`from datetime import datetime`
`import requests`
`from io import BytesIO`

`air2 = requests.get('https://www.stata-press.com/data/r12/air2.dta').content`
`data = pd.read_stata(BytesIO(air2))`
`data.index = pd.date_range(start=datetime(data.time[0], 1, 1), periods=len(data), freq='MS')`
`data['lnair'] = np.log(data['air'])`
`data = data.iloc[:100,:]`

`# Fit the model`
`mod = sm.tsa.statespace.SARIMAX(data['lnair'], order=(2,1,0), seasonal_order=(1,1,0,12),exog=data.loc[:,["air","t"]], simple_differencing=True)`
`res = mod.fit(disp=False)`

`outfile = open("E:\\SARIMAX_model_test.pickle","wb")`
`pickle.dump(mod,outfile)`
`outfile.close()`

`res.save("E:\\test.pickle")`

Then using a clean environment:
`import numpy as np`
`import pandas as pd`
`from scipy.stats import norm`
`import statsmodels.api as sm`
`import matplotlib.pyplot as plt`
`from datetime import datetime`
`import requests`
`from io import BytesIO`

`air2 = requests.get('https://www.stata-press.com/data/r12/air2.dta').content`
`data = pd.read_stata(BytesIO(air2))`
`data.index = pd.date_range(start=datetime(data.time[0], 1, 1), periods=len(data), freq='MS')`
`data['lnair'] = np.log(data['air'])`
`data = data.iloc[:100,:]`

`with open("E:\\SARIMAX_model_test.pickle","rb") as f:`
`    SARIMAX_model = pickle.load(f)`

`results = sarimax.SARIMAXResultsWrapper.load("E:\\test.pickle")`

`start=data.index.min()`
`end=data.index.max()`
`exog=data.loc[:,["air","t"]]`

`prediction = res.get_prediction(start=start,end=end,exog=exog.iloc[1:,:])`

This yield a correct value error: `ValueError: Provided exogenous values are not of the appropriate shape. Required (44, 2), got (43, 2).`

If one adjusts the last line to: `prediction = res.get_prediction(start=start,end=end,exog=exog)` and this should work, but doesn't. It yields the error: `ValueError: all the input array dimensions except for the concatenation axis must match exactly`

**Comment by bashtage** [comment]
Unfortunately, even without pickling, this demo doesn't work.

```
import pickle
from datetime import datetime
from io import BytesIO

import numpy as np
import pandas as pd
import requests

import statsmodels.api as sm

air2 = requests.get('https://www.stata-press.com/data/r12/air2.dta').content
data = pd.read_stata(BytesIO(air2))
data.index = pd.date_range(start=datetime(data.time[0], 1, 1), periods=len(data), freq='MS')
data['lnair'] = np.log(data['air'])
data = data.iloc[:100, :]
# Fit the model
mod = sm.tsa.statespace.SARIMAX(data['lnair'], order=(2, 1, 0), seasonal_order=(1, 1, 0, 12),
                                exog=data.loc[:, ["air", "t"]], simple_differencing=True)
res = mod.fit(disp=False)
outfile = open("SARIMAX_model_test.pickle", "wb")
start = data.index.min()
end = data.index.max()
exog = data.loc[:, ["air", "t"]]
prediction = res.get_prediction(start=start, end=end, exog=exog.iloc[1:, :])
```

**Comment by ViktorKnoben** [comment]
Give me a second, I will look into the issue

**Comment by bashtage** [comment]
You have `d=1` so the first observation is lost.

**Comment by bashtage** [comment]
You also have a seasonality of `12`.

```
start=data.index[13]
prediction = res.get_prediction(start=start,end=end,exog=exog.iloc[1:,:])
```

**Comment by bashtage** [comment]
This works as expected:

```
import pickle
import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.tsa.statespace import sarimax
from datetime import datetime
import requests
from io import BytesIO

air2 = requests.get('https://www.stata-press.com/data/r12/air2.dta').content
data = pd.read_stata(BytesIO(air2))
data.index = pd.date_range(start=datetime(data.time[0], 1, 1), periods=len(data), freq='MS')
data['lnair'] = np.log(data['air'])
data = data.iloc[:100,:]

# Fit the model
mod = sm.tsa.statespace.SARIMAX(data['lnair'], order=(2,1,0), seasonal_order=(1,1,0,12),exog=data.loc[:,["air","t"]], simple_differencing=True)
res = mod.fit(disp=False)

outfile = open("SARIMAX_model_test.pickle","wb")
pickle.dump(mod,outfile)
outfile.close()

res.save("test.pickle")

del res, mod, air2, data

air2 = requests.get('https://www.stata-press.com/data/r12/air2.dta').content
data = pd.read_stata(BytesIO(air2))
data.index = pd.date_range(start=datetime(data.time[0], 1, 1), periods=len(data), freq='MS')
data['lnair'] = np.log(data['air'])
data = data.iloc[:100,:]

with open("SARIMAX_model_test.pickle","rb") as f:
    SARIMAX_model = pickle.load(f)

res = sarimax.SARIMAXResultsWrapper.load("test.pickle")

start=data.index[13]
end=data.index.max()
exog=data.loc[:,["air","t"]]

prediction = res.get_prediction(start=start,end=end,exog=exog.iloc[1:,:])
```

**Comment by ViktorKnoben** [comment]
Next time, could you specify what you've changed? 

And I can confirm this code works but it doesn't address the issue I've presented. It doesn't do an out-of-sample prediction. Please read my original text thouroughly please.

As of your code, I've adjusted two lines so it gives the expected value error of a mismatch in shape. Then if you alter the last line (as noted in my original comment) you will find my error.

```
import pickle
import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.tsa.statespace import sarimax
from datetime import datetime
import requests
from io import BytesIO

air2 = requests.get('https://www.stata-press.com/data/r12/air2.dta').content
data = pd.read_stata(BytesIO(air2))
data.index = pd.date_range(start=datetime(data.time[0], 1, 1), periods=len(data), freq='MS')
data['lnair'] = np.log(data['air'])
data = data.iloc[:100,:]

# Fit the model
mod = sm.tsa.statespace.SARIMAX(data['lnair'], order=(2,1,0), seasonal_order=(1,1,0,12),exog=data.loc[:,["air","t"]], simple_differencing=True)
res = mod.fit(disp=False)

outfile = open("SARIMAX_model_test.pickle","wb")
pickle.dump(mod,outfile)
outfile.close()

res.save("test.pickle")

del res, mod, air2, data

air2 = requests.get('https://www.stata-press.com/data/r12/air2.dta').content
data = pd.read_stata(BytesIO(air2))
data.index = pd.date_range(start=datetime(data.time[0], 1, 1), periods=len(data), freq='MS')
data['lnair'] = np.log(data['air'])
data = data.iloc[100:,:] # I HAVE CHANGED THIS LINE

with open("SARIMAX_model_test.pickle","rb") as f:
    SARIMAX_model = pickle.load(f)

res = sarimax.SARIMAXResultsWrapper.load("test.pickle")

start=data.index.min() # I HAVE CHANGED THIS LINE
end=data.index.max()
exog=data.loc[:,["air","t"]]

prediction = res.get_prediction(start=start,end=end,exog=exog.iloc[1:,:])
```

Then if you alter the last line to:  ```prediction = res.get_prediction(start=start,end=end,exog=exog.iloc[1:,:])```

**Comment by bashtage** [comment]
> Next time, could you specify what you've changed?

The code you posted was broken.  If helps to get to a solution to provide a code sample that precisely generates the issue. 

> And I can confirm this code works but it doesn't address the issue I've presented. It doesn't do an out-of-sample prediction. Please read my original text thouroughly please.

Please provide a working proof of bug that clearly and succinctly demonstrates the issue.  I can't make sense of the issue you are having which was why I asked for the proof of bug.


> As of your code, I've adjusted two lines so it gives the expected value error of a mismatch in shape. Then if you alter the last line (as noted in my original comment) you will find my error.

I still don't understand the problem.  When I run the code you posted above, I get 
```
ValueError: Provided exogenous values are not of the appropriate shape. Required (44, 2), got (43, 2).

```

this makes sense to me since exog is (43,2) and it wants (44,2)

When I run 
```
prediction = res.get_prediction(start=start,end=end,exog=exog)
```
it works since exog is (44,2).

## What is needed
Please provide a proof of bug that produces
```
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```

**Comment by ChadFulton** [comment]
I am also having a hard time narrowing down what the issue is here.

Can you try the following example code, and let us know if it works?

```python
import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.tsa.statespace.sarimax import SARIMAXResults

# Simulate data
rs = np.random.RandomState(seed=40832)
ix = pd.date_range(start='2000-01', periods=100, freq='M')
X = pd.Series(rs.normal(size=100), index=ix)
Y = 2 * X + rs.normal(size=100)

# Split data
endog1 = Y[:50]
exog1 = X[:50]
endog2 = Y[50:]
exog2 = X[50:]

# Fit and save the model
mod = sm.tsa.SARIMAX(endog1, order=(1,0,0), exog=exog1)
res1 = mod.fit(disp=False)
res1.save("test.pickle")

# In-sample prediction
res1.get_prediction(start=endog1.index[0], end=endog1.index[-1])
# In-sample prediction + out-of-sample forecasting
res1.get_prediction(start=endog1.index[0], end=endog2.index[-1], exog=exog2)
# Out-of-sample forecasting
res1.get_forecast(endog2.index[-1], exog=exog2)

# Load the model
res2 = SARIMAXResults.load("test.pickle")
# In-sample prediction
res2.get_prediction(start=endog1.index[0], end=endog1.index[-1])
# In-sample prediction + out-of-sample forecasting
res2.get_prediction(start=endog1.index[0], end=endog2.index[-1], exog=exog2)
# Out-of-sample forecasting
res2.get_forecast(endog2.index[-1], exog=exog2)
```

**Comment by ViktorKnoben** [comment]
Hello,

Given the workload at my job it might take a short while for me to respond so my apologies in advance :D.

@bashtage from what I could tell the code does work with you, but not with me. From this I took a quick look at my environment and it appears I'm using the previous version. It took a note to try this example / my code with the latest edition. 

@ChadFulton in short the error occurs once I make an out-of-sample prediction using a SARIMAX model with exogeneous variable and multiple seasonalities that were unpickled. To do such a thing one must provide the exogeneous data matching with the prediction timestamps. If I provide a correct set (in terms of the shape) it yields an error. If I (on purpose) alter the shape to force an error it shows this error. This took me on a quest to find the problem which I found in the SARIMAX.py code. Here a concatenate was done for the known exogeneous data and the new, hence they must match. This goes wrong as the known exogeneous data also contains the predicted values (only for the timestamps on which the model was trained). Having removed this column it worked like a charm. Being unable to share my actual code (company property) I need to find an example which is not trivial it appears.

@both of you my appologies for the difficulty but I honestly believe I've found an issue, at the very least in the older version, maybe also in the newer one.

This is on my todolist for today but a response can be expected before this weekend.

**Comment by bashtage** [comment]
@ViktorKnoben We appreciate the bug report.  statsmodels uses volunteer time and so it really helps to have simple, easy to reproduce proof-of-bugs which let us quickly see this issue, and often to quickly fix it.  When we cannot reproduce the bug and have not encountered it ourselves, then it is really hard to fix.

It is a good idea to try 0.11.1, which has a lot of bug fixes from 0.10.x.

**Comment by ViktorKnoben** [comment]
Sigh... Version 0.11.1 is working perfectly and thus explains why you didn't get my errors. Meaning I spent way too much time deep diving the original code (did learn a few neat tricks). Good job on the update ;)

Regards,

Viktor

**Comment by ChadFulton** [comment]
Sorry you had to go through everything, but I'm glad it's working now! And thank you for following up with closing the issue.
