### ISSUE TITLE
Bayesian classifier for categorical data

### ISSUE THREAD

**Issue by Sandy4321** [statsmodels/statsmodels#6548]
can not find Bayesian classifier for categorical data
can not belive you do not have it

especially when we have observations in train data that not present in test data
scikit implementation can not deal with this
https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.CategoricalNB.html#sklearn.naive_bayes.CategoricalNB

**Comment by Sandy4321** [comment]
Bayesian classifier for categorical data when we have observations in test data that not present in train data

**Comment by bashtage** [comment]
statsmodels is a mostly frequentist statistics library that covers more traditional statistical models.  It is not a ML library.  Probably better to ask on scikit learn or stackoverflow.
