### ISSUE TITLE
some database but different position of columns，the result of model have different  residuals

### ISSUE THREAD

**Issue by lu-meng-zhe** [statsmodels/statsmodels#6552]
#### Code Sample, a copy-pastable example if possible

database name :test202001
x12 | x22 | y
100 | 3364 | -2729.68
25 | 2116 | -1770.14
4 | 1156 | -977.004
81 | 2809 | -2281.43
4 | 3136 | -2677.82
4 | 289 | -232.251
64 | 2209 | -1791.53
81 | 1521 | -1175.04
0 | 441 | -368.819
1 | 196 | -156.864
1 | 2304 | -1967.64
16 | 2209 | -1863.53
64 | 100 | 20.1
1 | 784 | -661.956
64 | 676 | -474.684
81 | 256 | -88.404
100 | 900 | -613.1
9 | 1521 | -1283.04
0 | 256 | -209.904
36 | 1600 | -1310.4
9 | 3136 | -2670.32

database name:test202002
x22 | x12 | y
3364 | 100 | -2729.68
2116 | 25 | -1770.14
1156 | 4 | -977.004
2809 | 81 | -2281.43
3136 | 4 | -2677.82
289 | 4 | -232.251
2209 | 64 | -1791.53
1521 | 81 | -1175.04
441 | 0 | -368.819
196 | 1 | -156.864
2304 | 1 | -1967.64
2209 | 16 | -1863.53
100 | 64 | 20.1
784 | 1 | -661.956
676 | 64 | -474.684
256 | 81 | -88.404
900 | 100 | -613.1
1521 | 9 | -1283.04
256 | 0 | -209.904
1600 | 36 | -1310.4
3136 | 9 | -2670.32

code:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import statsmodels.api as sm

filename="test202001"
interestedvar="y"
data=pd.read_excel(filename+'.xlsx',header=0)
X=data.drop([interestedvar],axis=1)
Y=data[interestedvar]
xcolnames=list(X.columns)
model = sm.OLS(Y,sm.add_constant(pd.DataFrame(X[xcolnames]))).fit()
print(model.resid)

filename="test202002"
interestedvar="y"
data=pd.read_excel(filename+'.xlsx',header=0)
X=data.drop([interestedvar],axis=1)
Y=data[interestedvar]
xcolnames=list(X.columns)
model = sm.OLS(Y,sm.add_constant(pd.DataFrame(X[xcolnames]))).fit()
print(model.resid)

**Comment by josef-pkt** [comment]
I get close enough agreement, but parsing the data as strings.

```
np.max(np.abs(model2.resid - model1.resid)), np.max(np.abs(model2.resid / model1.resid - 1))
(2.2737367544323206e-12, 6.746925018674688e-09)
```

If you see larger differences make sure that you actually have the same data. Check the estimate, e.g. summary, that it is the same.

The precision for residuals is not higher because you have almost a perfect fit and the residuals are small relative to y or the fitted values, e.g.

```
np.max(np.abs(model2.resid - model1.resid)) / model.fittedvalues.mean()
-1.8885263091833146e-15
```

condition number is larger than 3000, so you loose also a bit of precision there.

**Comment by bashtage** [comment]
This is an issue with the finite-precision of floating-point numbers. There is nothing statsmodels can do to change the behavior, which is correct.
