### ISSUE TITLE
OLS gives p-value = 0 when it shouldn't

### ISSUE THREAD

**Issue by nadavbra** [statsmodels/statsmodels#6570]
Running the following code:
```python
import numpy as np
import pandas as pd
import statsmodels.api as sm

N = 10000
x1 = np.array([0] + N * [1])
x2 = np.array([-1] + N * [1])
x = pd.DataFrame({'x1': x1, 'x2': x2})
y = 1 + np.random.randn(N + 1)
r = sm.OLS(y, sm.add_constant(x)).fit()
print(r.pvalues)
```

I get the following output:
```
const    0.025318
x1       0.000000
x2       0.366401
dtype: float64
```

As the labels (y) are random and independent of x, I see no reason for x1 to be significant here.

**Comment by bashtage** [comment]
Your regression has reduced rank since const, x1 and x2 are identical for all but 1 observation.  pvalues and all inference quantities are not meaningful.

**Comment by nadavbra** [comment]
const, x1 and x2 are still a full-rank matrix (rank 3). Why is it invalid to have two variables that are identical for all but one observation?
More generally, how can I determine if my dataset is appropriate or not, and whether I can trust the resulted p-value?

**Comment by kshedden** [comment]
If you run `r.summary()` you will get a warning that your condition number is 10^-29

You can see the conditioning of your design matrix like this:

```
_,s,_ = np.linalg.svd(r.model.exog, 0)
```

**Comment by kshedden** [comment]
If you run `r.summary()` you will get a warning that your condition number is 10^-29

You can see the conditioning of your design matrix like this:

```
_,s,_ = np.linalg.svd(r.model.exog, 0)
```

**Comment by nadavbra** [comment]
Is it equivalent to checking the lowest eigenvalue via `r.eigenvals.min()`?
What number should be considered too low?

**Comment by kshedden** [comment]
The condition number is the ratio of the largest to the smallest eigenvalue.  The condition number that is considered here is that of `X'X` (it is the square of the condition number of `X`).

I don't know what would be a good threshold but 1e-10 is the trigger for the warning message:

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/regression/linear_model.py#L2647

**Comment by kshedden** [comment]
Actually, the condition number is computed (see below), but it is the minimum eigenvalue that triggers the warning message.  The minimum eigenvalue is more relevant for detecting when numerical roundoff is likely to be a problem.  The condition number is more relevant for detecting when the statistical uncertainty about the coefficients is very large.

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/regression/linear_model.py#L1823

**Comment by kshedden** [comment]
Statsmodels OLS uses the pseudo-inverse for calculations and will return results (parameter estimates, p-values, etc.) even under perfect collinearity.  The summary message will include a warning, but the p-values are still there, although meaningless.

R detects near or exact collinearity and drops redundant variables.

**Comment by bashtage** [comment]
> const, x1 and x2 are still a full-rank matrix (rank 3). Why is it invalid to have two variables that are identical for all but one observation?

No they are not.

Your matrix looks like

```
[[1 0 -1]
 [1 1 1]
 [1 1 1]
...
]
```
Row Echelon form is
```
[[1 0 -1]
 [0 1 2]
 [0 0 0]
 [0 0 0]]```

This matrix has rank 2.

**Comment by bashtage** [comment]
And for a numeric check
```
np.linalg.matrix_rank(x)
Out[10]: 2
```

**Comment by nadavbra** [comment]
Thank you all for the good tips which helped me resolve this issue, and thank you @bashtage for pointing at my incompetence in calculating matrix ranks ;)

I ended up writing a piece of Python code that automatically detects multicolinearity and quasi-complete separation and removes redundant covariates prior to the use of linear or logistic regression.

**Comment by kshedden** [comment]
My understanding is that the most robust way to detect perfect collinearity (up to finite precision noise) is to use the rank revealing QR (a.k.a. QR with pivoting).  This is in scipy, below (set pivoting=True and mode='economic').  R runs something like this automatically and does not attempt to estimate all parameters in a perfectly collinear model.  We might want to have that as an option at some point.

https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.linalg.qr.html
