### ISSUE TITLE
Cannot access any of the documentation URLs

### ISSUE THREAD

**Issue by jseery** [statsmodels/statsmodels#6572]
#### Describe the bug

I can't reach the statsmodels documentation - I've even tried the backup URLs.

I searched for issues related to the website and documentation, but didn't find anything. Apologies if this is not the right place to raise this, or if others can access without a problem.

#### Code Sample, a copy-pastable example if possible

Paste https://www.statsmodels.org/stable/ into browser, get an error "this site can't be reached".
![image](https://user-images.githubusercontent.com/10521750/76120914-82245480-5fc0-11ea-84f3-e3f632c414d2.png)

Also tried these, with no success, after clearing cookies:
https://statsmodels.github.io/stable/
https://statsmodels.github.io/dev/.

Replicated on 
Brave Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
Safari Version 12.1.2 (14607.3.9)

**Comment by bashtage** [comment]
This is local to your config.  Works here.  Try the site that checks if a
website is down for everyone.

**Comment by bashtage** [comment]
Closing since no action.

**Comment by jseery** [comment]
thanks for the tip - didn't realize that existed. This one seems to confirm it's down for more than just me, at least https://downforeveryoneorjustme.com/statsmodels.org

I am able to access it on mobile, though 🤷‍♂ 

![image](https://user-images.githubusercontent.com/10521750/76121733-56a26980-5fc2-11ea-821e-a4d5c6602667.png)

**Comment by kbattocchi** [comment]
@bashtage I'm hitting this too, both locally as well as in part of my CI pipeline that uses intersphinx to link to the statsmodels documentation (see, e.g., [this failure](https://dev.azure.com/ms/EconML/_build/results?buildId=66794&view=logs&j=7e620c85-24a8-5ffa-8b1f-642bc9b1fc36&t=8118ed36-993d-5011-ddd5-27ae9d3a181c); this worked until within the last day or so).  Any chance you could reopen this issue?

**Comment by kbattocchi** [comment]
Also, it looks like https://statsmodels.github.io/stable/ just redirects to http://www.statsmodels.org/stable/ so it isn't a useful backup if the main statsmodels site is inaccessible.

**Comment by bashtage** [comment]
That isn't a backup site.  That is the host.  statsmodels.org is just a
friendly name that points to GitHub.io.

**Comment by bashtage** [comment]
For now you can get there with.

http://www.statsmodels.org/stable/index.html

Maybe something wrong with the redirect?

**Comment by bashtage** [comment]
Working for me on desktop now.

**Comment by Createdd** [comment]
I have the same error. I would consider this issue closed. Also, the backup sites cannot be reached. I would suggest to not leave this to the user to change the DNS settings to have access to the site.

**Comment by bashtage** [comment]
There is no backup site.  https://www.statsmodels.org is https://statsmodels.github.io.
