### ISSUE TITLE
SARIMA prediction fortecast in high frequency data

### ISSUE THREAD

**Issue by theanto** [statsmodels/statsmodels#6573]
I m trying to use SARIMAX to predict future forecast values. this is my data

2020-01-22 13:30:00 134.808840
2020-01-22 13:45:00 101.113338
2020-01-22 14:00:00 105.134895
2020-01-22 14:15:00 115.315380
I build a model, in this way

results = auto_arima(dataSugar['sugarValue'], seasonal=True, m=7, trace = True)
results.summary()
the summary gives this :

SARIMAX Results
Dep. Variable:  y   No. Observations:   1207
Model:  SARIMAX(0, 1, 3)x(2, 0, [1, 2], 7)  Log Likelihood  -3874.203
Date:   Fri, 06 Mar 2020    AIC 7766.407
Time:   21:57:14    BIC 7812.262
Sample: 0   HQIC    7783.676
- 1207      
Covariance Type:    opg     
coef    std err z   P>|z|   [0.025  0.975]
intercept   0.0298  0.248   0.120   0.905   -0.457  0.516
ma.L1   -0.0624 0.024   -2.581  0.010   -0.110  -0.015
ma.L2   -0.3912 0.023   -17.259 0.000   -0.436  -0.347
ma.L3   -0.0769 0.027   -2.894  0.004   -0.129  -0.025
ar.S.L7 -1.0120 0.024   -42.474 0.000   -1.059  -0.965
ar.S.L14    -0.9861 0.022   -45.078 0.000   -1.029  -0.943
ma.S.L7 1.0219  0.029   34.793  0.000   0.964   1.079
ma.S.L14    0.9794  0.031   31.162  0.000   0.918   1.041
sigma2  35.9620 1.096   32.805  0.000   33.813  38.111
Ljung-Box (Q):  57.10   Jarque-Bera (JB):   231.80
Prob(Q):    0.04    Prob(JB):   0.00
Heteroskedasticity (H): 1.38    Skew:   -0.10
Prob(H) (two-sided):    0.00    Kurtosis:   5.14
So I applied :

model = SARIMAX(df['sugarValue'], order=(0, 1, 3), seasonal_order=(2, 0, 2, 7), enforce_invertibility=False).fit()
and the prediction on test and train set is very nice:

pred = model.predict(start, end)

So I thought that my model is correct (more or less)..in fact, I don't need strictly precision.

But when i try to forecast future values in this way

forecast = model.forecast(steps=96)
My output is very quite similar 

  Prediction
2020-01-24 00:00:00 105.357804
2020-01-24 00:15:00 105.574045
2020-01-24 00:30:00 104.963241
2020-01-24 00:45:00 104.783142
2020-01-24 01:00:00 104.356709

I think this is very bad. Where I wrong? I checked the value and isn't the same, but are pretty similar.

**Comment by ChadFulton** [comment]
It seems like your concern is that the model does not do as good a job forecasting as you were hoping, is that correct?

In general and unless there are strong seasonal effects, ARIMA-type models will converge fairly quickly to a long-term series mean, which means that the forecasts will not change very much after a few periods. You're forecasting 96 periods, and it's not at all surprising that the forecast would not change very much.

Finally, it looks like you're selecting your model using pmdarima's `auto_arima` function. If you think that their function selected a bad model, you might follow up with them.

**Comment by bashtage** [comment]
Sounds like this question has been answered as well as can be done.
