### ISSUE TITLE
statsmodels.org is down

### ISSUE THREAD

**Issue by Andrew62** [statsmodels/statsmodels#6575]
## Statsmodels.org is down
Checked with: https://www.isitdownrightnow.com/statsmodels.org.html 

<img width="577" alt="Screen Shot 2020-03-08 at 4 36 36 PM" src="https://user-images.githubusercontent.com/3361916/76173244-07dc0780-615b-11ea-8187-0479d275a4bc.png">

**Comment by bashtage** [comment]
Seems to be an issue where www is required. 

@josef-pkt Is is possible statsmodels.org also works? Does some setting need to be changed?

**Comment by josef-pkt** [comment]
It works for me both stable and dev
http://www.statsmodels.org/stable

The `www.` is necessary. 
I never managed to figure out how to change the settings to also redirect `statsmodels.org` without the `www.` from my DNS server company.

**Comment by josef-pkt** [comment]
https://www.uptrends.com/tools/uptime for http://www.statsmodels.org

show 7 out of 43 with DNS lookup error, all others are green

isitdown seems to ignore `www`

**Comment by josef-pkt** [comment]
my DNS hosting is gkg.net which is down (and maybe they are going out of business)
I have another 4 years on my subscription :(

https://www.reddit.com/r/msp/comments/fe2g2e/looks_like_gkgnet_registrar_is_down_i_have_to_get/

**Comment by josef-pkt** [comment]
I have the domain registration with gkg since 2009 and it's the first time there is a problem.
It's not clear whether there is some tornado damage or if they are going out of business. 
But the business doesn't look good anymore. 

statsmodels.github.io is up according to www.isitdownrightnow.com

**Comment by josef-pkt** [comment]
uptrends shows now only one region, Göteborg, with connection problems, DNS lookup error.
It looks like the connections are propagating and should mostly work again.

**Comment by bashtage** [comment]
@josef-pkt It would be a good idea to go to statsmodels/statsmodels.github.io > Settings, Scroll Down and tick Enforce HTTPS.

**Comment by josef-pkt** [comment]
@bashtage  I switched it to Enforce HTTPS
thanks

**Comment by josef-pkt** [comment]
I think I managed to redirect statsmodels.org to the same as www.statsmodels.org

Assuming github uses a fixed IP address.
I pointed root `statsmodels.org` directly  to IP 185.199.111.153 and this might not go through the CNAME

**Comment by bashtage** [comment]
Seems fine now.
