### ISSUE TITLE
Change License to MIT

### ISSUE THREAD

**Issue by mysticaltech** [statsmodels/statsmodels#6593]
#### Is your feature request related to a problem? Please describe
I work for a SaaS that only accepts that Devs use libraries using MIT licenses.

#### Describe the solution you'd like
Your license resembles MIT, but it's not mentioned, is it? If it's not, would it be possible to change to MIT so that all of us can use it? Please!

**Comment by bashtage** [comment]
It is an absolutely bog-standard BSD -clause license.

https://opensource.org/licenses/BSD-3-Clause

Can your legal really not handle BSD licenses, give how prominent they are?

**Comment by josef-pkt** [comment]
most of python scientific and data science libraries including numpy, scipy, pandas, sklearn use BSD-3

**Comment by mysticaltech** [comment]
Thanks guys, yes BSD is really good and flexible, I will make sure to convince them! Thank you.
