### ISSUE TITLE
Intercept/constant should be included by default in sm.ols

### ISSUE THREAD

**Issue by amyalee** [statsmodels/statsmodels#6594]
The current behavior of sm.ols defaults to not including an intercept.  This is a problem because the vast majority of the time, and the expected behavior in statistical programming, is to include an intercept term.  

See: https://stats.stackexchange.com/questions/7948/when-is-it-ok-to-remove-the-intercept-in-a-linear-regression-model

**Comment by bashtage** [comment]
This is 100% driven by patsy and so would need to be changed there.  We essentially pass the formula and the dataframe into patsy to get the exog and endog out.

**Comment by josef-pkt** [comment]
This will not happen. Too much of a backwards compatibility break and users can use the formula interface. patsy adds intercept by default and follows R in this.
Our policy has been not to change the user provided exog.

The decision not to add a constant automatically happened more than 10 years ago.

**Comment by bashtage** [comment]
Good point.  Backward compat is also utterly limiting.  I woudl add that it isn't much harder to enter `y ~ 1+ x` rather than just `y ~ x`

**Comment by amyalee** [comment]
It is not that it is hard to add, it is just very surprising (and error-inducing) that for OLS it would default to excluding the intercept term.  That should be the exception (and require an additional step), not the norm.

Would it be possible to add more to the documentation to highlight this behavior?  I have since talked to a number of statisticians that have also been bitten by this.

**Comment by amyalee** [comment]
Also, really appreciate the feedback.  I assumed it would be unlikely to change this due to backward compatibility, but worth a shot.

**Comment by josef-pkt** [comment]
It's mentioned twice in the docstring
https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.OLS.html

and I guess several times in general documentation and examples.
(And many stackoverflow questions where users left out the constant. :)

Also, everyone with a bit of experience should realize that there is no constant/intercept when they see the summary output.

I didn't have a strong opinion either way about adding constant when this was up for discussion 10 to 12 years ago. 
For library use, I think it's good to keep the user being responsible for `exog`. For interactive use, we have the formula interface that does more "hand holding".
(I never liked for example the automatic dropping of variables in Stata and R when there is close to perfect collinearity or other problems like perfect separation.)
