### ISSUE TITLE
Type error when run statsmodel.gmm.fit

### ISSUE THREAD

**Issue by yl-hz** [statsmodels/statsmodels#6595]
I wonder if anyone would like to help me solve this problem:

I defined a momcond class for poisson gmm named "gmm_poisson". When I run the following code, it showed that "TypeError: 'float' object cannot be interpreted as an integer". However, I have no idea what kind of input may be the cause of this error. Is this because I modified the **kwds in the class? If so, may I ask about a solution to it? Thank you so much! 

P.s. "X_N" appearing in line 44 is a [dataframe.](url)

![1](https://user-images.githubusercontent.com/48391886/77024279-7d6a8380-6964-11ea-85fb-e978bb7cb122.png)

**Comment by josef-pkt** [comment]
You need to add the full traceback, so we see where it raises the error
Maybe it's trying to use a float as an array index. But I don't have any guess where it would cause an exception.

Also it's better to use numpy arrays and avoid np.matrix. Using matrix might cause problems when the operations are not compatible with np.array.

An, we prefer code as text to code in a picture

**Comment by josef-pkt** [comment]
inline comment

AFAIU, in lines 11, 12, the first `kwds` assigned to df_X might be anything, like "num_moms" if dictionary is sorted, as in py 3.7?. 
You have `**kwds` and then a "kwds" inside `**kwds`. Even if it's not wrong it's confusing.

**Comment by yl-hz** [comment]
> inline comment
> 
> AFAIU, in lines 11, 12, the first `kwds` assigned to df_X might be anything, like "num_moms" if dictionary is sorted, as in py 3.7?.
> You have `**kwds` and then a "kwds" inside `**kwds`. Even if it's not wrong it's confusing.

Thank you so much for your reply! Please find the full script as follows:
***************************
import pandas as pd
import numpy as np
import statsmodels as sm
import statsmodels.api as smapi
from itertools import groupby
from scipy.optimize import SR1
import scipy.optimize
from statsmodels.sandbox.regression.gmm import GMM

url1 = 'https://github.com/yl-hz/eg_repo/blob/master/data1.csv'

X_N = pd.read_csv(url1, header = 0, encoding = "ISO-8859-1")


#%%
class gmm_poisson(GMM):

    def __init__(self, *args, **kwds):

        super(gmm_poisson, self).__init__(*args, **kwds)
        
        for key, value in kwds.items():
            self.df_X = value    # df_X is a dataframe
            break

    def momcond(self, params):
        
        
        b1, b2, b3, b4, b5, b6 = params
        my_beta = np.transpose(np.matrix([b1, b2, b3, b4, b5, b6]))
        
        endog = np.array(self.endog) # y
        
        exog  = np.array(self.exog) # X
        
        self.df_X['y_i'] = self.df_X.groupby('id')['counts'].transform('mean')
        
        self.df_X['lambda_it'] = np.array((np.exp(np.matrix(exog)*my_beta)).flat)
        self.df_X['lambda_i'] = self.df_X.groupby('id')['lambda_it'].transform('mean')
        
        
        aux_error = np.transpose(np.matrix([0.0]*self.k_moms))
        
        for i in range(self.k_moms):
            self.df_X['aux_error'] = exog[:,i]*\
            (endog-self.df_X['y_i']*self.df_X['lambda_it']/self.df_X['lambda_i'])
            aux_error[i,0] = self.df_X['aux_error'].sum()

        
        error = np.column_stack(aux_error)
    
        return error     

#%% 
        
covariates = ['var1','var2','var3', 'var4', 'var5','var6']
model = gmm_poisson(X_N['counts'], X_N[covariates], num_moms=6, num_param=6, kwds={"first":X_N}, instrument=None)
beta0 = np.array([0.00000000003]*len(covariates))
res = model.fit(beta0, maxiter=10, optim_method='nm', wargs=dict(centered=False))
print(res.summary())
        
***********************

1. About np.matrix and np.array: I wonder if there is better way to perform matrix wise multiplication with np.array. (I don't want element-wise multiplication here)

2. As for **kwds and kwds: I feel that I am not understanding **kwds well--I only want to add an extra input to the GMM function (i.e. a dataframe), so I simply add it to kwds. May I ask what's the proper way to carry this out? 

Thank you so much! I really appreciate it a lot!

P.S. please find the error info below:
![image](https://user-images.githubusercontent.com/48391886/77027727-6a0fe600-696d-11ea-8039-f31e2a5c785f.png)

**Comment by josef-pkt** [comment]
check whether `model.nmoms` is float or integer or nan. 
It might be float which is not allowed in np.eye and np.zeros
I guess there is no type check for this in GMM, but I don't see yet why it would be float.

about matrix product with arrays:
since Python 3.5, there is `@` for matrix multiplications, e.g. `x @ y` for np.arrays.
I'm still using mostly the `dot` method, e.g. `x.dot(y)` which sounds more english than math to me.

about `kwds`:
I would at least use different names, and not the same name meaning two different things.

**Comment by josef-pkt** [comment]
model.nmoms is most likely nan

the keyword for GMM is `k_moms`

i.e. change `num_moms` to `k_moms`, which will be attached in GMM as `nmoms`

similarly, the keyword for the number of params is `k_params` (not `num_param`)
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/sandbox/regression/gmm.py#L475

`model = gmm_poisson(X_N['counts'], X_N[covariates],k_moms=6, k_params=6, kwds={"first":X_N}, instrument=None)`

**Comment by yl-hz** [comment]
Thank you so much for your reply! But I still have some other bugs. I have just changed the class as follows:

*************************
class gmm_poisson(GMM):

    def __init__(self, *args, **kwds):

        super(gmm_poisson, self).__init__(*args, **kwds)
        
        for key, value in kwds.items():
            if key == "first":
                self.df_X = value.copy()
                break

    def momcond(self, params):
        
        
        b1, b2, b3, b4, b5, b6 = params
        my_beta = np.transpose(np.matrix([b1, b2, b3, b4, b5, b6]))
        
        endog = np.array(self.endog) # y
        
        exog  = np.array(self.exog) # X
        
        self.df_X['y_i'] = self.df_X.groupby('id')['counts'].transform('mean')
        
        self.df_X['lambda_it'] = np.array((np.exp(np.matrix(exog)*my_beta)).flat)
        self.df_X['lambda_i'] = self.df_X.groupby('id')['lambda_it'].transform('mean')
        
        
        aux_error = np.transpose(np.matrix([0.0]*self.k_moms))
        
        for i in range(self.k_moms):
            self.df_X['aux_error'] = exog[:,i]*\
            (endog-self.df_X['y_i']*self.df_X['lambda_it']/self.df_X['lambda_i'])
            aux_error[i,0] = self.df_X['aux_error'].sum()

        
        error = np.column_stack(aux_error)
    
        return error     

#%% 
        
covariates = ['var1','var2','var3', 'var4', 'var5','var6']
model = gmm_poisson(X_N['counts'], X_N[covariates], k_moms=6, k_param=6, kwds={"first":X_N}, instrument=None)
beta0 = np.array([0.00000000003]*len(covariates))
res = model.fit(beta0, maxiter=10, optim_method='nm', wargs=dict(centered=False))
print(res.summary())
 
********************************

However, there occurs a new error:
*******
Traceback (most recent call last):

  File "<ipython-input-16-e2746b8410e3>", line 4, in <module>
    res = model.fit(beta0, maxiter=10, optim_method='nm', wargs=dict(centered=False))

  File "C:\Users\ly\Anaconda3\lib\site-packages\statsmodels\sandbox\regression\gmm.py", line 679, in fit
    optim_args=optim_args)

  File "C:\Users\ly\Anaconda3\lib\site-packages\statsmodels\sandbox\regression\gmm.py", line 920, in fititer
    optim_args=optim_args)

  File "C:\Users\ly\Anaconda3\lib\site-packages\statsmodels\sandbox\regression\gmm.py", line 772, in fitgmm
    **optim_args)

  File "C:\Users\ly\Anaconda3\lib\site-packages\scipy\optimize\optimize.py", line 409, in fmin
    res = _minimize_neldermead(func, x0, args, callback=callback, **opts)

  File "C:\Users\ly\Anaconda3\lib\site-packages\scipy\optimize\optimize.py", line 552, in _minimize_neldermead
    fsim[k] = func(sim[k])

  File "C:\Users\ly\Anaconda3\lib\site-packages\scipy\optimize\optimize.py", line 293, in function_wrapper
    return function(*(wrapper_args + args))

  File "C:\Users\ly\Anaconda3\lib\site-packages\statsmodels\sandbox\regression\gmm.py", line 835, in gmmobjective
    moms = self.momcond_mean(params)

  File "C:\Users\ly\Anaconda3\lib\site-packages\statsmodels\sandbox\regression\gmm.py", line 1073, in momcond_mean
    momcond = self.momcond(params)

  File "<ipython-input-15-37ebf97cf4ea>", line 22, in momcond
    self.df_X['y_i'] = self.df_X.groupby('id')['counts'].transform('mean')

AttributeError: 'gmm_poisson' object has no attribute 'df_X'
******************
May i ask why df_X is not found as I have defined it in __init__?

Besides, as for kwds: if I change it to another name (e.g. full_df), then it shows that "full_df not found"

Thank you so much!

**Comment by josef-pkt** [comment]
I think you are still mixing up `kwds` inside `kwds`

try dropping the second kwds, i.e. use

`model = gmm_poisson(X_N['counts'], X_N[covariates], k_moms=6, k_param=6, first=X_N, instrument=None)`

check docs for `**kwds` in python to understand what's going on

**Comment by yl-hz** [comment]
It works! Thank you so much for your help and all the references you provide! I appreciate it a lot!
