### ISSUE TITLE
ARIMA fit with missing values

### ISSUE THREAD

**Issue by misterguick** [statsmodels/statsmodels#6596]
Hi,

I'm trying to forecast temperatures from a time series with missing values. As mentionned in [this issue](https://github.com/statsmodels/statsmodels/issues/2551), missing values are handled for the endogenous as stated in 

> They are essentially imputed via the Kalman filter, but, given the model, the imputation is optimal (i.e. is the conditional expectation).

I simply use
```
model = ARIMA(train_set['data_temperature'], order=(5, 1, 0))
model = model.fit(disp=0, method="statespace")
```

I get the following traceback

> Traceback (most recent call last):
  File "D:\Anaconda\envs\big_data\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-68-c6fcc5454b59>", line 1, in <module>
    question1.arima(event_dict)
  File "D:\Onedrive\A. Université\2019-2020\Big data project\question1.py", line 1049, in arima
    model = model.fit(disp=0, method="statespace")
  File "D:\Anaconda\envs\big_data\lib\site-packages\statsmodels\tsa\arima_model.py", line 1200, in fit
    callback, start_ar_lags, **kwargs)
  File "D:\Anaconda\envs\big_data\lib\site-packages\statsmodels\tsa\arima_model.py", line 986, in fit
    start_ar_lags)
  File "D:\Anaconda\envs\big_data\lib\site-packages\statsmodels\tsa\arima_model.py", line 572, in _fit_start_params
    start_params = self._fit_start_params_hr(order, start_ar_lags)
  File "D:\Anaconda\envs\big_data\lib\site-packages\statsmodels\tsa\arima_model.py", line 553, in _fit_start_params_hr
    if p and not np.all(np.abs(np.roots(np.r_[1, -start_params[k:k + p]]
  File "<__array_function__ internals>", line 6, in roots
  File "D:\Anaconda\envs\big_data\lib\site-packages\numpy\lib\polynomial.py", line 245, in roots
    roots = eigvals(A)
  File "<__array_function__ internals>", line 6, in eigvals
  File "D:\Anaconda\envs\big_data\lib\site-packages\numpy\linalg\linalg.py", line 1058, in eigvals
    _assertFinite(a)
  File "D:\Anaconda\envs\big_data\lib\site-packages\numpy\linalg\linalg.py", line 218, in _assertFinite
    raise LinAlgError("Array must not contain infs or NaNs")
numpy.linalg.LinAlgError: Array must not contain infs or NaNs

I started wondering wheter my will to use time series with missing values made sense and I come across [this topic ](https://stats.stackexchange.com/questions/346225/fitting-arima-to-time-series-with-missing-values) that also states that it should be possible.

Here is a [plot ](https://imgur.com/dxRz3Sw)of the time series I'm working on (with in red the missing values).

Thank you for your help !

**Comment by ChadFulton** [comment]
Thanks for your message. The short answer is that you need to use `sm.tsa.arima.ARIMA` to fit your model (or `sm.tsa.SARIMAX`), and *not* `sm.tsa.ARIMA`.

Apologies, since this is obviously confusing. `sm.tsa.ARIMA` is a legacy model that we are in the process of replacing with `sm.tsa.arima.ARIMA`, but we have to go through a long deprecation cycle, since the old `sm.tsa.ARIMA` class is still in widespread use.

**Comment by misterguick** [comment]
Thanks ! That was exactly on point.

For people having the same issue, is was importing using
`        from statsmodels.tsa.arima_model import ARIMA
`
The new model can be imported using
`        from statsmodels.tsa.arima.model import ARIMA
`

**Comment by Dianaumd** [comment]
I would like to ask a question regarding to the missing value handling. I did the following experiments to have a better understanding. Do you mind helping me to understand the missing value handling for endog variable?
Missing value in the beginning of the series:
(1) There are three missing values in the beginning of the series y, tsa.arima.ARIMA(y, order(1, 0, 1) (2)Removed the three missing value in the beginning y_removed, tsa.arima.ARIMA(y_removed, order(1, 0, 1). The parameter estimation results are exactly the same. 

Missing value in the middle of the series:
(1) There are three missing values in the middle of the series y, tsa.arima.ARIMA(y, order(1, 0, 1) (2)Removed the three missing value in the beginning y_removed, tsa.arima.ARIMA(y_removed, order(1, 0, 1). The parameter estimation results are different. 

Missing value in the end of the series:
(1) There are three missing values in the end of the series y, tsa.arima.ARIMA(y, order(1, 0, 1) (2)Removed the three missing value in the beginning y_removed, tsa.arima.ARIMA(y_removed, order(1, 0, 1). The parameter estimation results are different. 

When d is set to be greater than 0, the parameter estimation results in the three scenarios above don't match. 

Thanks!

**Comment by ChadFulton** [comment]
Missing values at the beginning or end of the series should make no difference.  Missing values in the middle of the series should not be dropped, because that changes the effect of any time dependence in the model.

**Comment by iocuydi** [comment]
How do we specify endogenous missing values to be imputed by the Kalman filter? For example If I have time series of length 15, with items 8-12 missing, how do I specify these? If I just omitted them, it would look no different then a complete time series of length 10. Do we insert null for missing values? 
i.e.
`
[1,2,3,4,5,6,7,None, None, None, None, None, 13, 14, 15]
`

**Comment by ChadFulton** [comment]
> How do we specify endogenous missing values to be imputed by the Kalman filter?

You should use `np.nan` values:

`y = [1,2,3,4,5,6,7,np.nan,np.nan,np.nan,np.nan,np.nan, 13, 14, 15]

**Comment by iocuydi** [comment]
When using np.nan, I get this error:
`
    raise MissingDataError('exog contains inf or nans')
statsmodels.tools.sm_exceptions.MissingDataError: exog contains inf or nans
`

My exogenous data is list of onehot encoded vectors for the time series, coding for day of the week, holidays, etc. There are no inf or nan values in this list.
Is there a way to impute endogenous values while using a complete set of exogenous values? Despite the missing endogenous values I still have the complete set of exogenous values.

**Comment by iocuydi** [comment]
In the below example, the model works, but if I uncomment the line setting one of the endogenous values to nan, signifying that it is missing, I get the error above. (The endogenous data here is dummy data, but the behavior is the same with my real datasets).


`
import matplotlib.pyplot as plt
import numpy as np
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima_model import ARIMA
import pandas as pd
import random



def onehot_week(i):
    a = [0,0,0,0,0,0,0,0]

    a[i % 7] = 1
    if i == 35 or i == 47:
        a[7] = 1
    return a


data_endog = [3000, 10000, 31,  6220, 68, 10, 39, 12335, 37, 43, 53, 40, 12000, 360, 6, 48, 84595, 5, 31153, 83, 67026, 48792, 1,  28,33,  210, 280, 90000, 6400, 45, 46, 511, 30800, 494, 52, 483]
#data_endog[10] = np.nan
data_exog = [onehot_week(i) for i in range(len(data_endog))]


model = ARIMA(data_endog, order=(1,0,1), exog=data_exog)
model_fit = model.fit(disp=0)
print(model_fit.summary())
`

**Comment by bashtage** [comment]
You are on old statsmodels. `arima_model.ARIMA` has been removed and is no longer supported.  You need to use `statsmodels.tsa.arima.model.ARIMA`.  It is also strongly recommended to upgrade to 0.13.2.

```python

# SM 0.13.2 code

import matplotlib.pyplot as plt
import numpy as np
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima.model import ARIMA
import pandas as pd
import random

def onehot_week(i):
    a = [0,0,0,0,0,0,0,0]

    a[i % 7] = 1
    if i == 35 or i == 47:
        a[7] = 1
    return a

data_endog = [3000, 10000, 31,  6220, 68, 10, 39, 12335, 37, 43, 53, 40, 12000, 360, 6, 48, 84595, 5, 31153, 83, 67026, 48792, 1,  28,33,  210, 280, 90000, 6400, 45, 46, 511, 30800, 494, 52, 483]
#data_endog[10] = np.nan
data_exog = [onehot_week(i) for i in range(len(data_endog))]

model = ARIMA(data_endog, order=(1,0,1), exog=data_exog)
model_fit = model.fit()
print(model_fit.summary())

```

**Comment by iocuydi** [comment]
Looks like that worked! Thought I was on latest but I kept getting an old version because of a python 3.5 env. 

Thanks for your help!!

Is there a guide for migration/1-1 mapping of functionality? Have some more code that seems to fail on plot_predict, forecast, etc. but can just look at docs if not


```
fitted = model.fit(disp=-1)

# Forecast
fc, se, conf = fitted.forecast(FORECAST_QTY, exog=exogdatatest, alpha=0.05)  # 95% conf
abf = input('forcesated')
abf = input(fc)
# Make as pandas series
fc_series = pd.Series(fc, index=dftest.index)
lower_series = pd.Series(conf[:, 0], index=dftest.index)
upper_series = pd.Series(conf[:, 1], index=dftest.index)

# Plot
plt.figure(figsize=(12,5), dpi=100)
plt.plot(df, label='training')
plt.plot(dftest, label='actual')
plt.plot(fc_series, label='forecast')
plt.fill_between(lower_series.index, lower_series, upper_series,
                 color='k', alpha=.15)
plt.title('Forecast vs Actuals')
plt.legend(loc='upper left', fontsize=8)
plt.show()


# Actual vs Fitted
model_fit.plot_predict(dynamic=False)
plt.show()
```
