### ISSUE TITLE
cannot import name 'shamilton_filter_log' 

### ISSUE THREAD

**Issue by parment1** [statsmodels/statsmodels#6597]
Dear all,

I have the following error while importing statsmodels into PyCharm. I have installed the latest version of statsmodels through pip: statsmodels-0.11.0rc1

> ''ImportError: cannot import name 'shamilton_filter_log' from 'statsmodels.tsa.regime_switching._hamilton_filter'

Could not figure out what's the issue.

Thank you 

Regards
T

**Comment by bashtage** [comment]
That is not the latest version.  Please install 0.11

**Comment by bashtage** [comment]
I'm going to close this but please feel free to post any related issues here.
