### ISSUE TITLE
BUG: statsmodels.regression.linear_model.OLS.fit_regularized fails to generate correct answer

### ISSUE THREAD

**Issue by ZhiqingXiao** [statsmodels/statsmodels#6604]
#### Describe the bug

`statsmodels.regression.linear_model.OLS.fit_regularized` does not work when `alpha` is a list and `L1_wt=0`.

`statsmodels.regression.linear_model.OLS.fit_regularized` with `alpha` being a list of `0` does not match `statsmodels.regression.linear_model.OLS.fit`.

#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import statsmodels.regression.linear_model as linear_model
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([1, 2, 3])
model = linear_model.OLS(y, X)
results = model.fit_regularized(alpha=[0, 0, 0], L1_wt=0.)
print(results.params)
```

The error message:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-81-767ef847f3da> in <module>
      4 y = np.array([1, 2, 3])
      5 model = linear_model.OLS(y, X)
----> 6 results = model.fit_regularized(alpha=[0, 0, 0], L1_wt=0.)

D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\statsmodels\regression\linear_model.py in fit_regularized(self, method, alpha, L1_wt, start_params, profile_scale, refit, **kwargs)
   1044 
   1045         if L1_wt == 0:
-> 1046             return self._fit_ridge(alpha)
   1047 
   1048         # If a scale parameter is passed in, the non-profile

D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\statsmodels\regression\linear_model.py in _fit_ridge(self, alpha)
   1141             params = np.dot(v, params)
   1142         else:
-> 1143             vtav = self.nobs * np.dot(vt, alpha[:, None] * v)
   1144             d = np.diag(vtav) + s2
   1145             np.fill_diagonal(vtav, d)

TypeError: list indices must be integers or slices, not tuple
```

#### Expected Output

It should print `[-0.05555556  0.11111111  0.27777778]`, which is the output of the following code:

```python
import numpy as np
import statsmodels.regression.linear_model as linear_model
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([1, 2, 3])
model = linear_model.OLS(y, X)
results = model.fit()
print(results.params)
```

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.8.1.final.0

statsmodels
===========

Installed: 0.11.0 (D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: 0.29.15 (D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\Cython)
numpy: 1.18.1 (D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\numpy)
scipy: 1.4.1 (D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\scipy)
pandas: 1.0.1 (D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\pandas)
    dateutil: 2.8.1 (D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\dateutil)
patsy: 0.5.1 (D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.1.3 (D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 0.14.1 (D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\joblib)

Developer Tools
================

IPython: 7.12.0 (D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\IPython)
    jinja2: 2.11.1 (D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\jinja2)
sphinx: 2.4.0 (D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\sphinx)
    pygments: 2.5.2 (D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\pygments)
pytest: 5.3.5 (D:\ProgramData\Anaconda3\envs\tfnightly\lib\site-packages\pytest)
virtualenv: Not installed

</details>

**Comment by kshedden** [comment]
Thanks, it looks like we just need to include an `asarray` somewhere.

**Comment by ZhiqingXiao** [comment]
@kshedden Thanks for your attention. I think I may try to fix it myself as well.
