### ISSUE TITLE
BUG : fail to use time-varying obs_cov

### ISSUE THREAD

**Issue by ChenChingChih** [statsmodels/statsmodels#6606]
#### Describe the bug
I am trying to use statsmodel to build a Mixed-Frequency VAR model (Mariano & Murasawa. (2010)) , however, but I fail to use time-varying `obs_cov`.  If I replace it with a time-invariant obs_cov, such as `self['obs_cov'] = np.eye(nv)`, it works.

#### Code Sample

    # Mixed-Frequency VAR
    from abc import ABC
    import statsmodels.api as sm
    import numpy as np
    import matplotlib.pyplot as plt
    np.random.seed(42)
    
    
    # Global parameters
    nburn = 0
    nsim = 100
    
    
    class MFVAR(sm.tsa.statespace.MLEModel, ABC):
        def __init__(self, endog):
            dummy_quarterly_obs = dummy_generator()
            n1 = 1   # number of quarterly variables (y)
            n2 = 1   # number of monthly variables (x)
            ns = (n1+n2)*5  # number of state variables
            tlen, nv = endog.shape   # number of observed v. & time length
            # actually, nv = n1+n2
            self.n1, self.n2, self.ns, self.nv = n1, n2, ns, nv
    
            super().__init__(endog, k_states=ns, k_posdef=nv,
                             initialization='stationary')
    
            # 1. time-varying design matrix Z[t]
            z0 = block_diag(1.0/3.0, 1.0, n1, n2)
            z1 = block_diag(2.0/3.0, 0.0, n1, n2)
            z2 = block_diag(1.0, 0.0, n1, n2)
            z3 = block_diag(2.0/3.0, 0.0, n1, n2)
            z4 = block_diag(1.0/3.0, 0.0, n1, n2)
            z = np.column_stack((z0, z1, z2, z3, z4))
            z0_u = block_diag(0.0, 1.0, n1, n2)
            z_u = np.column_stack((z0_u, np.zeros((nv, nv*4))))
            z_time = np.zeros((nv, ns, tlen))
            for t in range(tlen):
                if dummy_quarterly_obs[t]:
                    z_time[:, :, t] = z
                else:
                    z_time[:, :, t] = z_u
            self['design'] = z_time
    
            # # 2. time-varying observation disturbance H[t]
            # when y is observable
            h = np.zeros((nv, nv))
            # when y is unobservable
            h_u = block_diag(1.0, 0.0, n1, n2)  # random variable N(0, 1)
            h_time = np.zeros((nv, nv, tlen))
            for t in range(tlen):
                if dummy_quarterly_obs[t]:
                    h_time[:, :, t] = h
                else:
                    h_time[:, :, t] = h_u
            self['obs_cov'] = h_time
            # self['obs_cov'] = np.eye(nv)
    
            # 3. time-invariant selection matrix R
            self['selection'] = np.eye(ns, nv)
    
        def update(self, params, transformed=True, **kwargs):
            n1, n2, ns, nv = self.n1, self.n2, self.ns, self.nv
            # nv = n1 + n2
            # ns = 5 * nv
    
            # 4. time-invariant transition matrix T
            var_coef = params[:nv**2].reshape(nv, nv)
            var_coef = np.column_stack((var_coef, np.zeros((nv, nv*4))))
            self['transition'] = np.row_stack((var_coef, np.eye(nv*4, ns)))
    
            # 5. time-invariant state covariance Q
            tril_state_cov = vec_tril(params[nv**2:])   # lower-triangular matrix
            self['state_cov'] = tril_state_cov @ tril_state_cov.transpose()
    
        @property
        def start_params(self):
            phi_11, phi_12, phi_21, phi_22 = 0.4, 0., 0., 0.8   # initial guess
            sig_11, sig_12, sig_22 = 1.0, 0., 1.0
            return np.array([phi_11, phi_12, phi_21, phi_22, sig_11, sig_12, sig_22])
    
    
    def block_diag(a, b, n1, n2):
        """
        Create block diagonal matrix of this form:
         a*I |  0
        -----+-----
         0   |  b*I
         The size of the upper left corner is (n1, n1)
         The size of the lower right corner is (n2, n2)
        """
        upper_left = np.identity(n1)*a
        lower_right = np.identity(n2)*b
        upper_right = np.zeros((n1, n2))
        lower_left = np.zeros((n2, n1))
        upper = np.column_stack((upper_left, upper_right))
        lower = np.column_stack((lower_left, lower_right))
        z0 = np.row_stack((upper, lower))
        return z0
    
    
    def vec_tril(x, order='C'):
        """
        Reverse half-vectorization into a triangular matrix in the order of C or F(ortran)
        If x is complex, ivech(x) is conjugate symmetric.
        That is, ivech(x) = ivech(x).transpose().conj()
        """
        r = len(x)
        n = np.int((np.sqrt(1+8*r)-1)/2)
        if all(np.isreal(x)):
            a_mat = np.zeros((n, n))
        else:
            a_mat = np.zeros((n, n), 'complex')
        if order == 'C':
            d = np.tril_indices(n)
            a_mat[d] = x
        else:
            a_mat[:, 0] = x[0:n]
            oldindex = n
            for ii in np.arange(1, n):
                newindex = oldindex + n - ii
                a_mat[ii:n, ii] = x[oldindex:newindex]
                oldindex = newindex
        return a_mat
    
    
    def dummy_generator():
        dummy = [1, 0, 0]*nsim
        dummy = np.array(dummy, dtype=int)
        return dummy
    
    
    def data_generator():
        # % artificial data
        phi_11, phi_12, phi_21, phi_22 = 0.5, 0., 0., 0.5  # initial guess
        sig_11, sig_12, sig_22 = 0.5, 0.0, 0.5
        params = [phi_11, phi_12, phi_21, phi_22, sig_11, sig_12, sig_22]
        params = np.array(params)
        model_true = MFVAR(np.zeros((nsim*3, 2)))
        consumption = model_true.simulate(params, nsim*3)  # % consumption
        # consumption = np.delete(consumption, np.arange(burn))
        return consumption
    
    
    # SS fit
    data_consumption = data_generator()
    model = MFVAR(data_consumption)
    res = model.fit()
    print(res.summary())
    

    

### Your code here that produces the bug
 File "C:\Users\Anaconda3\lib\site-packages\statsmodels\tsa\statespace\simulation_smoother.py", line 169, in _simulate
    np.r_[measurement_shocks.ravel(), state_shocks.ravel()],

AttributeError: 'NoneType' object has no attribute 'ravel'

**Comment by ChadFulton** [comment]
This looks like it was maybe fixed in #6280. Can you try updating your statsmodels to v0.11 and see if that fixes the problem?

**Comment by ChadFulton** [comment]
Well I guess in v0.11 it raises a different exception. I'll take a look

**Comment by ChadFulton** [comment]
Indeed this is a bug, still in v0.11.  Thanks for the report!

**Comment by ChadFulton** [comment]
If you can update to the latest ("master") version of statsmodels from the github repository, please let us know if this fixed your issue.

**Comment by ChenChingChih** [comment]
@ChadFulton Can I use `conda install -c conda-forge statsmodels` to update to the latest version

**Comment by ChadFulton** [comment]
Unfortunately not. Typically we'd recommend installing the "master" branch from Github with pip, e.g.:

```
pip install git+git://github.com/statsmodels/statsmodels.git
```

There are a couple of other bug fixes that we made recently or are in the works, and it may make sense to make another point release of v0.11.

**Comment by ChenChingChih** [comment]
First, I remove statsmodels, `conda remove statsmodels`,
then use pip to install `pip install git+https://github.com/statsmodels/statsmodels.git`, 
however, it pops up error `Could not build wheels for statsmodels which use PEP 517 and cannot be installed directly`, and so I upgrade setuptools wheel,
`pip install --upgrade pip setuptools wheel`
But, the same error came...  `Could not build wheels for statsmodels which use PEP 517 and cannot be installed directly`



pip --version
pip 20.0.2 from C:\User\Anaconda3\lib\site-packages\pip (python 3.7)

**Comment by ChenChingChih** [comment]
I found[#6454](https://github.com/statsmodels/statsmodels/issues/6454#issuecomment-605368594) discussed similar issue and so I ask the installation problem under it.
If I can install from source, I would that you know is time-varying `obs_cov` works on my computer as soon as possible! 
Thanks again and a lot! @ChadFulton

**Comment by ChenChingChih** [comment]
@ChadFulton I got the results finally!!!
Thanks a lot for fixing it very quikly~
    Casting complex values to real discards the imaginary part
      a_mat[d] = x
                               Statespace Model Results                           
    ==============================================================================
    Dep. Variable:           ['y1', 'y2']   No. Observations:                  300
    Model:                          MFVAR   Log Likelihood                -630.330
    Date:                Sat, 28 Mar 2020   AIC                           1274.660
    Time:                        17:46:18   BIC                           1300.587
    Sample:                             0   HQIC                          1285.036
                                    - 300                                         
    Covariance Type:                  opg                                         
    ==============================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
    ------------------------------------------------------------------------------
    param.0        0.2448      0.212      1.157      0.247      -0.170       0.659
    param.1        0.0266      0.121      0.220      0.826      -0.210       0.263
    param.2        0.1734      0.089      1.944      0.052      -0.001       0.348
    param.3        0.4742      0.067      7.056      0.000       0.343       0.606
    param.4        0.6028      0.124      4.865      0.000       0.360       0.846
    param.5       -0.0804      0.079     -1.012      0.312      -0.236       0.075
    param.6        0.4629      0.030     15.410      0.000       0.404       0.522
    ===================================================================================
    Ljung-Box (Q):                45.95, 37.12   Jarque-Bera (JB):           0.08, 7.60
    Prob(Q):                        0.24, 0.60   Prob(JB):                   0.96, 0.02
    Heteroskedasticity (H):         1.16, 0.99   Skew:                       0.03, 0.33
    Prob(H) (two-sided):            0.46, 0.95   Kurtosis:                   2.94, 3.41
    ===================================================================================
    
    Warnings:
    [1] Covariance matrix calculated using the outer product of gradients (complex-step).

**Comment by ChadFulton** [comment]
Great!

By the way, you may want to replace:

```python
    if all(np.isreal(x)):
        a_mat = np.zeros((n, n))
    else:
        a_mat = np.zeros((n, n), 'complex')
```

with

```python
a_mat = np.zeros((n, n), dtype=x.dtype)
```

since if you have an array with a complex dtype, but where the complex part is zero, `np.real` will return `True`, although you want the dtype to be complex. i.e. `np.isreal(np.array([1, 2, 3]) + 0j)` returns `True`.

**Comment by ChenChingChih** [comment]
Thanks! @ChadFulton  This bugs bothers me last night when I get some matrix is invertible....
