### ISSUE TITLE
maxlag should be < nobs error in AR model

### ISSUE THREAD

**Issue by charlesmodi** [statsmodels/statsmodels#6609]
import pandas as pd
from pandas import datetime
import matplotlib.pyplot as plt

def parser(x):
    return datetime.strptime(x,'%Y-%m')

sales = pd.read_csv('trends_crypto_63_10_17.CSV',index_col=0, parse_dates=[0] ,date_parser=parser)

sales.head()

sales.plot()

from statsmodels.graphics.tsaplots import plot_acf
plot_acf(sales)    
#this data is stationary becuse 2nd point directly 0.00 and then negitive

#stationary
sales.head()

sales.describe()

sales.shift(1)

sales_diff = sales.diff(periods=1)

sales_diff = sales_diff[1:]
sales_diff.head()

plot_acf(sales_diff)

sales_diff.plot()

X = sales.values
train = X[0:5] # 5 data as train data
test = X[5:]  # 3 data as test data
predictions = []

train.size

test.size

#AR(Auto Regressive model)
from statsmodels.tsa.ar_model import AR
from sklearn.metrics import mean_squared_error
model_ar = AR(train)
model_ar_fit = model_ar.fit()

**ValueError: maxlag should be < nobs**

**Comment by bashtage** [comment]
AR is not longer suported. Use AutoReg.
