### ISSUE TITLE
Sampling of zero-inflated models with high means is very slow

### ISSUE THREAD

**Issue by Bolzano-Weierstrass** [statsmodels/statsmodels#6617]
Hi,

I’ve been using the zero-inflated distributions of StatsModels for a while. Works well! I have notice that the sampling is particularly slow when the mean(parameter mu) is high.

When timing the sampling from two zipoisson with a mean of 10 and 10000. We notice that the sampling is slower when the mean is greater.

```
import timeit
import statsmodels.distributions as sm

print(timeit.timeit('sm.zipoisson(mu=10000, w=0.3).rvs(size=100)', number=10, setup="import statsmodels.distributions as sm"))
print(timeit.timeit('sm.zipoisson(mu=10, w=0.3).rvs(size=100)', number=10, setup="import statsmodels.distributions as sm"))
```
The above snippet of code returns the following two lines with :
```
368.92
0.81
```
I have tested on W10 and OSX with StatsModels `v0.11.1` and `0.10.1` respectively with SciPy `1.3.1` under the hood.

Sampling from a `zipoisson` with `mu = 10000`(or any big `mu`) is very very slow. After profiling and looking at the code of the `.rvs()` method of StatsModels class `zipoisson_gen` that inherits from SciPy’s `rv_discrete`, I think that the slowdown comes from the use of the inverse cdf algorithm in SciPy’s`.rvs()` to generate samples from the `pmf` and a uniform distribution.

SciPy often overwrites this method with a quicker way to compute the samples depending on the distribution.s 
I thought we could do this for `zipoisson` and `zinegbin` by multiplying a binary vector with a vector from the non-zero-inflated distribution; something like:
```
        # Bernouilli of parameter 1-w
zero_inflated_sampling = np.random.binomial(1, 1 - w, size=size)
        # then we sample from the Poisson of parameter mu
distibution_sampling = np.random.poisson(mu, size=size)
        # we multiply both to obtain the Zero-inflated Poisson
samples = zero_inflated_sampling * distibution_sampling
```
This is more than a thousand time faster and still complies with the definition of a zero-inflated distribution.
I’d be interested to look at it. What are your thoughts?
Thanks

**Comment by josef-pkt** [comment]
We are definitely interested in adding additional methods to the distributions.

We didn't implement rvs because the code/PR was only focused on estimation, and we didn't have a sampling usecase.

Also cdf could be implemented in an efficient way using the mixing.

Generalized Poisson might be more difficult, it's not available in numpy/scipy, and I never looked at distribution properties other than loglike/pdf

**Comment by Bolzano-Weierstrass** [comment]
While working on this issue, I noticed a weird behavior from `test_count_model.py`.

With the latest master branch all tests are green(40s to test this file). 
The `nobs`(l _215_, l _318_ & l _430_ in the code) variables that dictate the size of the `exog` and `endog` of the testing scenario are set to 200, 200 and 500 for `zip`, `zigp` and `zinb`. If we set them to 2000, 2000 and 5000 then six tests are failing(50s to test). If we set them to 20000, 20000 and 50000 then four tests are failing(200s to test). So simply changing nobs sparks failures.


I found what I believe are small bugs in the tests code to resolve four of the six failing tests; so that 20000, 20000 and 50000 is all green now.
 
I still got an issue with two of them, one in `zigp` and one in `zinb`:

```
________________________________ TestZeroInflatedGeneralizedPoisson_predict.test_mean _________________________________

self = <statsmodels.discrete.tests.test_count_model.TestZeroInflatedGeneralizedPoisson_predict object at 0x0000019265143F98>

    def test_mean(self):
        assert_allclose(self.res.predict().mean(), self.endog.mean(),
>                       atol=1e-4, rtol=1e-4)
E       AssertionError:
E       Not equal to tolerance rtol=0.0001, atol=0.0001
E
E       Mismatch: 100%
E       Max absolute difference: 0.00171753
E       Max relative difference: 0.00190731
E        x: array(0.902218)
E        y: array(0.9005)

statsmodels\discrete\tests\test_count_model.py:329: AssertionError
```
 and 

```
self = <statsmodels.discrete.tests.test_count_model.TestZeroInflatedNegativeBinomialP_predict object at 0x0000019265295438>

    def test_predict_generic_zi(self):
        # These tests do not use numbers from other packages.
        # Tests are on closeness of estimated to true/DGP values
        # and theoretical relationship between quantities
        res = self.res
        endog = self.endog
        exog = self.res.model.exog
[...]
        probs_main_unique = res.predict(exog=[[1, 0], [1, 1]],
                                        exog_infl=np.asarray([[1], [1]]),
                                        which='prob-main')
        probs_main = res.predict(which='prob-main')
        probs_main[[0,-1]]
        assert_allclose(probs_main_unique, probs_main[[0,-1]],  rtol=1e-10)
>       assert_allclose(probs_main_unique, 1 - prob_infl, atol=0.01)
E       AssertionError:
E       Not equal to tolerance rtol=1e-07, atol=0.01
E
E       Mismatch: 100%
E       Max absolute difference: 0.01677652
E       Max relative difference: 0.01973709
E        x: array([0.833223, 0.833223])
E        y: array(0.85)

statsmodels\discrete\tests\test_count_model.py:504: AssertionError
```
The weird part is that those two tests are not failing for 200, 200, 500 nor  20000, 20000 and 50000 but are indeed failing for  2000, 2000 and 5000. 

I've seen on #3928 that it is not the first time and I don't really know if those error margins are acceptable or if it shows a real failure somewhere in the code of count models.

**Comment by josef-pkt** [comment]
we don't have confidence intervals and standard errors for those predictions yet. so it's difficult to tell what the precision should be.

If just a few cases fail, then it could be just "unlucky" random numbers.

AFAIR, `sm.distributions.zinegbin.rvs` has not been separately verified. I don't know how good that one is with generic rvs.

**Comment by josef-pkt** [comment]
reopening, I think we can get explicit rvs methods that should be much faster except in still slow GeneralizedPoisson.

I'm currently working in PR  #7929 adding get_distribution.
rvs for ZI models still looks very slow
