### ISSUE TITLE
grangercausalitytests won't take [x] as input

### ISSUE THREAD

**Issue by lilly-chen** [statsmodels/statsmodels#6618]
#### Describe the bug

Hi, i want to customize the lags used in the granger causality tests, instead of range from 1 to the maxlag.

in the document example, it says can use the following to acheive that:
` gc_res = grangercausalitytests(data, [4])`

However, when i try to run the line, it will give me an error of TypeError: can only concatenate list (not "int") to list

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-8b0e8361ec76> in <module>
      1 a = 1
----> 2 gc_res = sm.tsa.stattools.grangercausalitytests(data_sub, maxlag=[[2]], verbose=False)

/mnt/eider_environments/EiderPythonRuntime/local/apollo/env/EiderPythonRuntime/lib/python3.7/site-packages/statsmodels/tsa/stattools.py in grangercausalitytests(x, maxlag, addconst, verbose)
    843     x = np.asarray(x)
    844 
--> 845     if x.shape[0] <= 3 * maxlag + int(addconst):
    846         raise ValueError("Insufficient observations. Maximum allowable "
    847                          "lag is {0}".format(int((x.shape[0] - int(addconst)) /

TypeError: can only concatenate list (not "int") to list
```

**Comment by josef-pkt** [comment]
which statsmodels version are you using?

works for me in the branch I'm using right now (based on master a month or two ago)

statsmodels.__version__
'v0.12.0.dev0+89.g28073ee.dirty'

**Comment by josef-pkt** [comment]
according to the commit it needs at least v0.11.0 
option was added in #6008

**Comment by lilly-chen** [comment]
> which statsmodels version are you using?
> 
> works for me in the branch I'm using right now (based on master a month or two ago)
> 
> `statsmodels.__version__`
> 'v0.12.0.dev0+89.g28073ee.dirty'

my version is '0.9.0'

**Comment by lilly-chen** [comment]
> statsmodels.__version__

i update the version. it works now. Thanks you so much!

**Comment by josef-pkt** [comment]
that's good
