### ISSUE TITLE
Feature Request: Inclusion of Beta Regression

### ISSUE THREAD

**Issue by bhishanpdl** [statsmodels/statsmodels#6619]
I was doing some data science in financing and came up with beta regression.
In "R" there is a built-in package to do beta regression which is great. But I mainly work in
python and it's undesirable to learn a whole language just to do one kind of regression,
especially when there are lots of models already implemented in statsmodels and scikit-learn.

I am aware that traditionally we can do logistic regression followed by linear regression
to simulate as closely as beta simulation alternative, but it would really be great if 
this great library `statsmodels` implements in first hand.

Some more information:

- [github gist by user brentp](https://gist.github.com/brentp/089c7d6d69d78d26437f)
- [R package betareg](https://cran.r-project.org/web/packages/betareg/betareg.pdf)

**Comment by josef-pkt** [comment]
we have an "80%" PR #2030 #4238

based on my latest comments there, it needs better unit test coverage, and likely improved optimization.

There is little test coverage on extras, i.e. results attributes and methods. But given we have now zero inflated count data which also have two exog, some of this might work better now in the inherited classes.

Logit and discrete GLM models work also with continuous data, so they can be used similarly to beta regression. (using a robust cov_type for quasi-maximum likelihood)

**Comment by bhishanpdl** [comment]
Thanks Joseph for the response. I hope it will be implemented soon.
