### ISSUE TITLE
zivot_andrews autolag issue

### ISSUE THREAD

**Issue by lbsurfer** [statsmodels/statsmodels#6624]
I have been using statsmodels for my dissertation over the last few weeks. I think I found a bug in both the statstool.zivot_andrews function and possibly the string_like function.

I used the following function call and got the following error

Input: print(stattools.zivot_andrews(1d_array_to_check,autolag='AIC'))

Output: anaconda3\lib\site-packages\statsmodels\tools\validation\validation.py", line 363, in string_like raise ValueError(msg)

ValueError: If not None, autolag must be one of: 'AIC', 'BIC', 't-stat'

i was able to fix the issue by modifying the zivot_andrews call in the following way:

line 1980: autolag = string_like(autolag, 'autolag', options=('aic', 'bic', 't-stat'), optional=True)

this is important because line 1986 calls

adf_res = adfuller(x, maxlag=maxlag, regression='ct',autolag=autolag)

and adfuller expects options=('aic', 'bic', 't-stat') not options=('AIC', 'BIC', 't-stat')

I tested the string_like function and it also seems to have issues with strings of capital letters for some reason. This might be a python version issue? See the sm.show_versions() dump below.

INSTALLED VERSIONS
------------------
Python: 3.7.6.final.0

statsmodels
===========

Installed: 0.11.1 

Required Dependencies
=====================

cython: 0.29.15 
numpy: 1.18.1 
scipy: 1.4.1 
pandas: 1.0.1 
    dateutil: 2.8.1 
patsy: 0.5.1 

Optional Dependencies
=====================

matplotlib: 3.1.3 
cvxopt: Not installed
joblib: 0.14.1

Developer Tools
================

IPython: 7.12.0 
    jinja2: 2.11.1 
sphinx: 2.4.0 
    pygments: 2.5.2 
pytest: 5.3.5 
virtualenv: Not installed

**Comment by bashtage** [comment]
Thanks for reporting.  Fixed in master.  The solution is to always use lower internally, so options should be in the check in zivot andrews ("aic","bic","t-stat")
