### ISSUE TITLE
Clustered standard errors: only 2 groups are supported??

### ISSUE THREAD

**Issue by tomdavidoff** [statsmodels/statsmodels#6634]
I find that trying to run clustered standard errors, I get a "ValueError: only two groups are supported." But clustered standard errors should be fine with many clusters. I have about 300 clusters X 30 observations each.
Reproducing code example:

print(sm.OLS.from_formula('price_change ~ log_F_permits + log_A_permits + C(year) + C(metro)',data=data_frame).fit(cov_type="cluster",cov_kwds={"groups":metro}).summary())

The regression works fine with the .fit() part empty. But when run with these parts (a bunch of metro areas in a panel with about 30 observations per cluster), I get: the following

data_frame is populated by the variables listed above.

Traceback (most recent call last):
File "Documents/williams/scripts/annual.py", line 102, in
print(sm.OLS.from_formula('price_change ~ log_F_permits + log_A_permits + C(year) + C(metro)',data=data_frame).fit(cov_type="cluster",cov_kwds={"groups":metro}).summary())
File "/usr/lib/python3.8/site-packages/statsmodels/regression/linear_model.py", line 342, in fit
lfit = OLSResults(
File "/usr/lib/python3.8/site-packages/statsmodels/regression/linear_model.py", line 1556, in init
self.get_robustcov_results(cov_type=cov_type, use_self=True,
File "/usr/lib/python3.8/site-packages/statsmodels/regression/linear_model.py", line 2464, in get_robustcov_results
raise ValueError('only two groups are supported')
ValueError: only two groups are supported
#2 ~/Documents/williams/scripts/annual.py_ou

```python
# Your code here that produces the bug
# This example should be self-contained, and so not rely on external data.
# It should run in a fresh ipython session, and so include all relevant imports.
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

</details>

**Comment by bashtage** [comment]
You can have any number of groups.  You can only do two way, that is have
two distinct sets of groups, for example industry and state.

**Comment by tomdavidoff** [comment]
Thanks. If my data is
metro_data a dictionary
"y" : [12,100,54,...]
"metro" : [1,1,1,3,3,3,12,12,12,...]
"X" : [12,29,44,...]
How would I correctly specify that I want standard errors clustered on metro without getting that error?
Thanks

**Comment by josef-pkt** [comment]
what exactly is `metro` ?

I guess you want `{groups: data_frame["metro"]}`

i.e. `metro` should be a numpy array or a pandas series (I guess that's also supported)

**Comment by tomdavidoff** [comment]
That's exactly what I want, but however I write metro, {groups: data_frame["metro]}, {"groups":metro}, {"groups":'metro'}, I get the same error. I don't think it's that the code thinks I am referring to something other than the array -- code seems to work equally well with lists and arrays. data_frame["metro"] is a series of integer (or string, doesn't affect outcome) group id's for observations.

**Comment by tomdavidoff** [comment]
I am going to close this. I think I may have been sloppy -- my point about irrelevance of data_frame['metro'] data type seems to be wrong. I am getting a different error when I change that.

**Comment by josef-pkt** [comment]
my guess is that somewhere your groups id gets converted to a row vector, 

you can try plain numpy array
`{"groups": np.asarray(data_frame["metro"])}`

and check that `np.asarray(data_frame["metro"])` is a 1-d array

**Comment by tomdavidoff** [comment]
Thanks. The new error message is:
ValueError: The weights and list don't have the same length.
I saw a comment in the code about a transpose working for some reason, but np.asarray(data_frame['metro']).T gives that same error:
ValueError: The weights and list don't have the same length.
And I do not have any missing values

**Comment by josef-pkt** [comment]
Where is that ValueError raised?

What you can check is using the model without cov_type and see whether it has the same number of observations as your groups array/series.

**Comment by tomdavidoff** [comment]
You nailed it. Didn't think there could be missing values, but there were. Thanks.
