### ISSUE TITLE
BUG: Inconsistencies in underlying state space model of holtwinters.ExponentialSmoothing

### ISSUE THREAD

**Issue by s-scherrer** [statsmodels/statsmodels#6635]
#### Short explanation

The statsmodels implementation of exponential smoothing in `holtwinters` implicitly uses the additive error state space models. Fits and calculations of information criteria are based on this and might be wrong when users assume the multiplicative error model.

#### Background

Up to recently, the statsmodels implementation of exponential smoothing in `holtwinters` did not use an explicit state space model. Fitting the model parameters and initial state was and is done by minimizing the sum of squared residuals, where `residuals = data - predicted`. This is currently implemented in the `SMOOTHERS`.

However, minimizing the sum of residuals with `residuals = data - predicted` really only makes sense when using an additive error model,
```
y_t = yhat_t + e_t,
```
 with `e_t = y_t - yhat_t ~ N(0, sigma**2)`. In this case, negative log-likelihood is
```
l = n * log(SSE/n),
```
so minimizing SSE is the same as minimizing negative log-likelihood.

When using a multiplicative error model, the state space model is 
```
y_t = yhat_t * (1 + e_t) = yhat_t + yhat_t * e_t.
```
In this case, `e_t = (y_t - yhat_t) / (yhat_t) ~ N(0, sigma**2)`. Therefore, the residuals should be `residuals = (data - prediction)/prediction`. In this case, negative log-likelihood is (see [Hyndman et al. 2002 (PDF)](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.468.7646&rep=rep1&type=pdf), equations (7) and (9)):
```
l = n * log(SSE/n) + 2 * sum(log(yhat))
```
with `SSE = sum((y - yhat) / yhat)`.

In the R package `forecast` (or the newer version, `fable`), the residuals are calculated as proposed above, that is, they are different for additive and multiplicative error models. Also, the default criterion used for optimizing the parameters is log likelihood.

#### How this affects the current implementation

With the introduction of state space simulations in #6560, it is now possible to choose between an additive and a multiplicative error model for simulations. However, fits are still performed implicitly using the additive model. Similar, information criteria are calculated using the likelihood of the additive model.

Users of `simulate` with `error="mul"` will therefore get imperfect fits and wrong information criteria for the model they assume to be using.

#### How this could be fixed

Fixing would require some changes behind the curtain, especially in the smoothers, but more importantly, it would require the user to specify the error model **before** the fit. An additional keyword argument in the `ExponentialSmoother` constructor with `"add"` as default value would be backwards compatible.

**Comment by ChadFulton** [comment]
I agree, this is a good idea. Does this imply we need to rewrite the smoothers? One thing to keep in mind is that the versions actually called during fitting are written in Cython, so that that can be compiled for speed. Cython isn't too hard to pick up, so rewriting would still be doable, even if you haven't seen it before.

**Comment by s-scherrer** [comment]
> Does this imply we need to rewrite the smoothers?

I think so. I'm familiar with Cython, so I guess that won't be a problem. In my opinion, there are two ways to go:

1) Change the smoothers to return negative log-likelihood, and fix the information criteria calculations - this would be pretty straightforward.

2)  I saw that `ExponentialSmoothing` inherits from `base.LikelihoodModel`, which already has a `fit` implementation that is maximizing the `loglike` method, so I thought about implementing `loglike` for the `ExponentialSmoothing` class. Then we could call the super class `fit` inside `ExponentialSmoothing.fit` to do the optimization. This would probably be an almost complete refactoring of the existing code and would probably take me more time, but I think it could reduce the complexity of the code (for example, I could avoid the code duplication that we have now with the smoothers and `_predict`), and make more use of the inheritance structure.

In both cases I would again use the implementation in the `forecast` package as reference for testing.
What is your preferred way to go?

**Comment by ChadFulton** [comment]
This is somewhat up to you, especially given that (2) seems like more work. I think either one of these options would make a great improvement to our exponential smoothing models.

Personally, I lean towards (2), because I would like to see us move towards a more uniform API and set of features that the current exponential smoothing models don't always implement (e.g. I would like to see it with a similar API / feature set as `sm.tsa.statespace.ExponentialSmoothing`). With that in mind, if you do want to take on (2) then I would encourage creating a completely new model class, since otherwise you would likely yourself restricted by the API design of the current setup.

**Comment by ChadFulton** [comment]
Although if you prefer to take on (2) and keep it within the existing model structure, that is also fine with me.

**Comment by s-scherrer** [comment]
I think the route of creating a completely new model class is the best way to go, and I'm quite motivated to do this, even if it might be more effort.

Where should I put the new model class? Conceptually it would make sense to me to put it in `statespace`.

I was reading a bit through your exponential smoothing implementation and the `statsmodels.tsa.statespace.MLEModel` and `statsmodels.tsa.statespace.MLEResults` class and found that there are quite a few methods that I would also want to use and I could just copy, e.g. the information criteria in the results class, or `fix_params`, but maybe it is better to put all this in a new base class?

**Comment by ChadFulton** [comment]
> I think the route of creating a completely new model class is the best way to go, and I'm quite motivated to do this, even if it might be more effort.

That's great.  I've got a lot on my plate at the moment outside of Statsmodels, but I'll help as much as I can, and hopefully be able to help more in a week or two.

> Where should I put the new model class? Conceptually it would make sense to me to put it in statespace.

I would put it in `tsa/exponential_smoothing`.  I made that directory with the idea in mind that I would eventually do what you're planning to do.

> I was reading a bit through your exponential smoothing implementation and the statsmodels.tsa.statespace.MLEModel and statsmodels.tsa.statespace.MLEResults class and found that there are quite a few methods that I would also want to use and I could just copy, e.g. the information criteria in the results class, or fix_params, but maybe it is better to put all this in a new base class?

This is a good idea. For now, why don't you subclass `MLEModel` and `MLEResults` and override where necessary?  Later we can see how best to factor out the base results.  But if you run into problems with this approach, we can adjust course if necessary.
