### ISSUE TITLE
Document nan-handling policies for acf()

### ISSUE THREAD

**Issue by anntzer** [statsmodels/statsmodels#6641]
#### Describe the bug

tsa.stattools.acf() currently documents the `missing` kwarg as taking the following values for nan-handling: [‘none’, ‘raise’, ‘conservative’, ‘drop’].  It isn't too difficult to see what "none" does (it returns nan if there's a nan in the time series) and to guess that "raise" raises an exception if there's a nan, but it would be useful to document better what "drop" and "conservative" do.  I guess "drop" just "compresses" out the nans from the time series first and "conservative" drops out the terms in the summation that are nan, but I'm not even sure of that?  Also, especially for "conservative", it would be nice if there was some reference to the literature as to how to handle such data (e.g., when centering the data, would it make sense to center only the data that will participate in the summation for a given lag?).

#### Code Sample, a copy-pastable example if possible

N/A

#### Expected Output

N/A

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

0.11.1

**Comment by anntzer** [comment]
thanks!

**Comment by bashtage** [comment]
Thanks for reporting.
