### ISSUE TITLE
ENH: automatic lag selection for Box-Pierce, Ljung-Box

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#6645]
see also #286

Based on abstract, the following article sounds interesting to avoid that users have to decide on lag used in the acorr test.

Escanciano, J. Carlos, and Ignacio N. Lobato. 2009. “An Automatic Portmanteau Test for Serial Correlation.” Journal of Econometrics, Recent Advances in Time Series Analysis: A Volume Honouring Peter M. Robinson, 151 (2): 140–49. https://doi.org/10.1016/j.jeconom.2009.03.001.

(I didn't look closely at it)

**Comment by bashtage** [comment]
closed by #6785
