### ISSUE TITLE
Error Co-variance matrix - Different Regression Models.

### ISSUE THREAD

**Issue by andrewczgithub** [statsmodels/statsmodels#6646]
Hi All!
@dougalsutherland @alno @bavardage 

I am just wondering is there easy to get the **error co-variance matrix of different regression**n model or **the co variance of the residuals.**

**This is usually know as Sigma?**

I am using the error covariance matrix in a study i am doing for university.

Kind regards and thanks,
Andrew

**Comment by josef-pkt** [comment]
for which models?

Models with univariate endog like OLS, GLM, only have residual variance because they are just 1-dim.
All models provide the residuals that can be used for further analysis.

**Comment by andrewczgithub** [comment]
hi @josef-pkt !! thank you so much for your help!

I am trying to re create the below paper and it asks for the calculation of the residual co-variance matrix?

https://arxiv.org/pdf/1803.01381.pdf

I am a bit confused about what this term is?

Kind regards and thanks,
Andrew

**Comment by bashtage** [comment]
In that paper you have a residual covariance because you have `n` portfolio, n > 1. `linearmodels` supports multivariate regression and some specific asset model estimators.
