### ISSUE TITLE
Implement a plot.figure(figsize=(w, h)) or an argument to allow figure size to be specified

### ISSUE THREAD

**Issue by andreamoro** [statsmodels/statsmodels#6648]
#### Is your feature request related to a problem? Please describe
The plot method allows the figure to be changed by importing the base matplotlib class and using the rcParams only.

#### Describe the solution you'd like
It would be nicer having a `plot.figure = [w, h]` or a `plot(figuresize=[w, h])` method to get that changed

#### Additional context
To date I have had never a need to import the matplotlib library on its own, and doing it just to set the figure size doesn't sound optimal.

**Comment by josef-pkt** [comment]
I found `figure.set_` methods in matplotlib when I wanted to change the figsize in my latest notbook

```
fig = res3.plot_forest()
fig.set_figheight(6)
fig.set_figwidth(6)
```

(plot_forest is in my PR, but has the same pattern as the existing statsmodels plot functions, delegates to dot_plot)

**Comment by josef-pkt** [comment]
I also wished several times that our plot functions had figsize as keyword. Most of the time I don't remember how to do it and then have to look it up each time.

**Comment by PabloIsCoding** [comment]
Not sure if this is the general case but I've seen an ax parameter that gives you full control over everything in the plot. For instance if you have some array x:

```python
fig, ax = plt.subplots(figsize=(18,18))
sm.graphics.tsa.plot_acf(x, ax=ax);
```

That works, and you have the `fig` and `ax` variables to tweak anything you want

**Comment by bashtage** [comment]
The fix is `fig.set_size_inches(18.5, 10.5)`.

```
import numpy as np
import statsmodels.api as sm

x = np.random.standard_normal(1000)
fig = sm.graphics.tsa.plot_acf(x)
```

![image](https://user-images.githubusercontent.com/5585221/81788568-a50c4100-94fa-11ea-9198-7bda9156e5b1.png)


If a feature is easy to access using `set` or by initializing a `Figure` directly, we shouldn't duplicate it.
