### ISSUE TITLE
Time trend orders in augmented Dickey Fuller unit root test

### ISSUE THREAD

**Issue by ArthurRenault** [statsmodels/statsmodels#6651]
Hello,

Currently the function _adfuller_ supports only 4 different time trends, cf doc below:
>     regression : {'c','ct','ctt','nc'}
>         Constant and trend order to include in regression.
> 
>         * 'c' : constant only (default).
>         * 'ct' : constant and trend.
>         * 'ctt' : constant, and linear and quadratic trend.
>         * 'nc' : no constant, no trend.

I would be happy to work on the generalisation for a trend of an arbitrary order.

However, I had a look at the code and I'm not sure on the best way to implement this feature. Indeed, for trend order greater than 2 it becomes unhandy to use strings. I would rather specify the trend order using an int but this implies an in-depth change of the tool function _add_trend_.

What are your thoughts on this?

**Comment by bashtage** [comment]
Each time trend needs its own set of critical values, and so this isn't straightforward.  There are few time series that are quadratic stationary and so I don't ext bring to cubic or higher has much value.  Do you have a specific use case of "ct3", or generally "ct_n_"?

**Comment by ArthurRenault** [comment]
I am working on data from sensors. The values measured drift over time for various reasons (temperature, sensor distortion, etc). In my use case, sensor drift is not easy to model and I do not know beforehand what stationarity "ct_n" I am looking for.

I end up fitting polynomials of different order on my data, then computing the residuals and last checking for stationarity with the augmented Dickey Fuller test on the residuals.

I think what I did is similar to what the function _adfuller_ does when 'regression' is specified but perhaps I am wrong.

**Comment by bashtage** [comment]
The problem with this approach is that anything beyond ct2 requires custom critical values and p-value surfaces.   Even adding one is a non-trivial undertaking, and I don't think it is meaningfully possible to funny generalize ADF.

**Comment by bashtage** [comment]
I don't think this is something statsmodels can support given the impossibility of having critical values for the general case.
