### ISSUE TITLE
Handle pathlib paths with `get_file_obj`

### ISSUE THREAD

**Issue by giuliobeseghi** [statsmodels/statsmodels#6652]
#### Is your feature request related to a problem? Please describe
I'm trying to read a statsmodels.tsa.statespace.sarimax.SARIMAXResults pickle file I've saved. I'd like to pass a pathlib.Path object as I find it easier to handle (I work with different machines, Mac and Windows).

#### Describe the solution you'd like
The function `open` already supports pathlib objects. Why not using it?

You could replace `statsmodels.iolib.openfile.get_file_obj` with:

```python
if _is_string_like(fname):
    return _open(fname, mode, encoding)
try:  # try opening it with 'open'
    return open(fname, mode, encoding)
except TypeError:  # else, maybe return context manager (please check if it's always TypeError)
    try:
        # Make sure the object has the write methods
        if 'r' in mode:
            fname.read
        if 'w' in mode or 'a' in mode:
            fname.write
    except AttributeError:
        raise ValueError('fname must be a string or a file-like object')
    return EmptyContextManager(fname)
```

This is just a suggestion though :)

**Comment by bashtage** [comment]
A PR would be welcome for this enhancement.

**Comment by giuliobeseghi** [comment]
I've never done it, but I can try. Is there a guide about it?

**Comment by giuliobeseghi** [comment]
@bashtage it seems it failed :(
