### ISSUE TITLE
got multiple values for argument 'constraints', 'bounds'

### ISSUE THREAD

**Issue by emailhy** [statsmodels/statsmodels#6655]
#### Describe the bug
error happens when provide "bounds" or "constraints" option for scipy minimize

#### Code Sample, a copy-pastable example if possible

```python
~/anaconda3/lib/python3.7/site-packages/statsmodels/base/optimizer.py in _fit_minimize(f, score, start_params, fargs, kwargs, disp, maxiter, callback, retall, full_output, hess)
    273 
    274     res = optimize.minimize(f, start_params, args=fargs, method=kwargs['min_method'],
--> 275                             jac=score, hess=hess, callback=callback, options=options)
    276 
    277     xopt    = res.x

~/anaconda3/lib/python3.7/site-packages/scipy/optimize/_minimize.py in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    616     elif meth == 'slsqp':
    617         return _minimize_slsqp(fun, x0, args, jac, bounds,
--> 618                                constraints, callback=callback, **options)
    619     elif meth == 'trust-constr':
    620         return _minimize_trustregion_constr(fun, x0, args, jac, hess, hessp,

TypeError: _minimize_slsqp() got multiple values for argument 'constraints'

```
<details>

This happens when a keyword argument is specified that overwrites a positional argument. 
as scipy minimize already has bounds, constraints in the signature, and the options pass the bunds and constraints again. 

It should handled the same way as jac and hess, thank you
</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

Run without give error

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>
statsmodels
===========

Installed: 0.11.1 
</details>

**Comment by josef-pkt** [comment]
Which model?
Can you make up a simple example that we can run?

This was never checked.

aside: standard asymptotic theory for inference doesn't apply if the parameter can be at the boundary of the parameter space, i.e. if there are possibly binding inequality constraints.

**Comment by emailhy** [comment]
according to the docs: [optimizer](https://www.statsmodels.org/stable/optimization.html)
this should affect glm and all other models which can apply scipy optimizer .

The problem is due to the mismatch of the base/optimizer.py 
which put bounds, and constraints into the "options" and then pass to scipy's optimizer
"options", but scipy has already has named args in its arg list, so cause the bunds and constraints
be pass multiple times, 

i verified by modified the optimizer.py 

get the bounds and constraints from the kwargs and not put them into the options.
optimize.minimize(..., bounds=bounds, constraints=constraints, callback=callback, options=options)

then it will work, 

Thanks for this great package

**Comment by emailhy** [comment]
Here is a minimal example
```
import numpy as np
import statsmodels.api as sm
from scipy import stats
from matplotlib import pyplot as plt

data2 = sm.datasets.scotland.load()
data2.exog = sm.add_constant(data2.exog, prepend=False)

bnds = tuple([(0, None)]*7)

glm_gamma = sm.GLM(data2.endog, data2.exog, family=sm.families.Gamma())
glm_results = glm_gamma.fit(method='minimize', min_method='SLSQP', bounds = bnds)
print(glm_results.summary())

**Comment by josef-pkt** [comment]
Thanks 

I'm getting the correpsonding bounds error for the example
`TypeError: _minimize_slsqp() got multiple values for argument 'bounds'`

this works, and imposes nonnegativity constraints in example
```
glm_results = glm_gamma.fit(method='lbfgs', bounds=bnds)
print(glm_results.summary())
```

**Comment by josef-pkt** [comment]
our `_fit_lbfgs`
uses `bounds = kwargs.setdefault('bounds', [(None, None)] * len(start_params))` to get the separate keyword argument.

@emailhy can you option a PR with your fix, and some unit tests?

**Comment by emailhy** [comment]
@josef-pkt 
I submitted the PR, but it seems one last check failed at get r dataset.   Please review, thanks

**Comment by emailhy** [comment]
@josef-pkt 
I fixed all the format issues in my pull request,  Thank you.

**Comment by emailhy** [comment]
Hi @josef-pkt, Is there anything else I need to add, the PR passed all checks and all comments has been addressed.  Please guide for next step. Thank you.

**Comment by Kvothe-The-Bloodless** [comment]
I think there is a related bug:

```
from scipy.optimize import rosen, rosen_der, rosen_hess
bounds = [(0,1.6), (0, 1.6), (0, 1.4), (0, 1.4), (0, 1.4)]
result = scipy.optimize.shgo(rosen, bounds, options={'jac':rosen_der,'hess':rosen_hess})
```
gives 

`TypeError: _minimize_slsqp() got multiple values for argument 'jac'`

Do you agree? Is there a work around?

**Comment by emailhy** [comment]
@Kvothe-The-Bloodless , that is scipy's bug,  but you are right, same reason
