### ISSUE TITLE
How to get whole number or integer output of GLM poission

### ISSUE THREAD

**Issue by ramdhan1989** [statsmodels/statsmodels#6658]
I have the dataset where the target is count of data. GLM.predic poisson or negative binomial produce float number. Is there anyway to get the integer prediction? I think it will help prediction more accurate especially when dealing with small number of count daa. Thanks

**Comment by bashtage** [comment]
Predictions from discrete models are not discrete, they are continuous, since they are the parameter of the underlying distribution.  For example, the prediction from a logit is a number between 0 and 1, but is never 0 or 1. This is the probability of a 1.

**Comment by ramdhan1989** [comment]
So, if we want to get integer values, just rounding the prediction? Or we can do something with poisson distribution to get back the int value (outside the model) ?

**Comment by bashtage** [comment]
You are welcome to round it but theoretically that would only hurt forecasting performance.
