### ISSUE TITLE
State Space Model: Non-positive-definite forecast error covariance matrix encountered

### ISSUE THREAD

**Issue by jktis** [statsmodels/statsmodels#6660]
I am trying to replicate the state space Local Level example described [here](http://www.chadfulton.com/fulton_statsmodels_2017/) or slightly differently in the [docs](https://www.statsmodels.org/stable/examples/notebooks/generated/statespace_local_linear_trend.html). No matter which notation I follow, I get the following error

```
Traceback (most recent call last):
  File "statsmodels/tsa/statespace/_filters/_inversions.pyx", line 411, in statsmodels.tsa.statespace._filters._inversions.dinverse_univariate
ZeroDivisionError: float division

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/s/Documents/StateSpaceModels/example_estimation.py", line 46, in <module>
    print(nile_model.loglike([15099.0,1469.1]))
  File "/home/s/Documents/StateSpaceModels/venv/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 889, in loglike
    loglike = self.ssm.loglike(complex_step=complex_step, **kwargs)
  File "/home/s/Documents/StateSpaceModels/venv/lib/python3.7/site-packages/statsmodels/tsa/statespace/kalman_filter.py", line 977, in loglike
    kfilter = self._filter(**kwargs)
  File "/home/s/Documents/StateSpaceModels/venv/lib/python3.7/site-packages/statsmodels/tsa/statespace/kalman_filter.py", line 900, in _filter
    kfilter()
  File "statsmodels/tsa/statespace/_kalman_filter.pyx", line 2000, in statsmodels.tsa.statespace._kalman_filter.dKalmanFilter.__call__
  File "statsmodels/tsa/statespace/_kalman_filter.pyx", line 2080, in statsmodels.tsa.statespace._kalman_filter.dKalmanFilter.__next__
  File "statsmodels/tsa/statespace/_filters/_inversions.pyx", line 413, in statsmodels.tsa.statespace._filters._inversions.dinverse_univariate
numpy.linalg.LinAlgError: Non-positive-definite forecast error covariance matrix encountered at period 1
```
Here the code in the notation of the example in the docs. (Following the notation in the tutorial link above produced the same error)
```
import numpy as np
import pandas as pd 
import statsmodels.api as sm 

nile = sm.datasets.nile.load_pandas().data['volume']
nile.index = pd.date_range('1871', '1970', freq='AS')

class LocalLevel(sm.tsa.statespace.MLEModel):

    def __init__(self, endog):
        k_states = k_posdef = 1
        super().__init__(endog, 
            k_states = k_states,
            k_posdef = k_posdef,
            initialization='approximate_diffuse',
            loglikelihood_burn=k_states)

        self.ssm['design', 0, 0] = 1.0
        self.ssm['transition', 0, 0] = 1.0
        self.ssm['selection', 0,0] = 1.0 

        @property
        def param_names(self):
            return ['obs.var', 'level.var']

        @property
        def start_params(self):
            return [1.0, 1.0]

        def transform_params(self,params):
            return params**2

        def untransform_params(self,params):
            return params**0.5

        def update(self, params, *args, **kwargs):
            params = super().update(params, *args, **kwargs)

            self.ssm['obs_cov', 0,0] = params[0]
            self.ssm['state_cov', 0,0] = params[1]

nile_model = LocalLevel(nile)

print(nile_model.loglike([15099.0,1469.1]))
```
This happened in both the conda environment which uses statsmodel version 0.9.0 and in my virtual environment with version 0.11.1 using python 3.7.

**Comment by ChadFulton** [comment]
Hello,

The problem here seems to be that you are indenting all of the properties
and methods too much.  Right now, they are all being defined local to the
`__init__` method, but they should be defined as part of the class.

The following should work:

import numpy as np
import pandas as pd
import statsmodels.api as sm

nile = sm.datasets.nile.load_pandas().data['volume']
nile.index = pd.date_range('1871', '1970', freq='AS')

class LocalLevel(sm.tsa.statespace.MLEModel):

    def __init__(self, endog):
        k_states = k_posdef = 1
        super().__init__(endog,
            k_states = k_states,
            k_posdef = k_posdef,
            initialization='approximate_diffuse',
            loglikelihood_burn=k_states)

        self.ssm['design', 0, 0] = 1.0
        self.ssm['transition', 0, 0] = 1.0
        self.ssm['selection', 0,0] = 1.0

    @property
    def param_names(self):
        return ['obs.var', 'level.var']

    @property
    def start_params(self):
        return [1.0, 1.0]

    def transform_params(self,params):
        return params**2

    def untransform_params(self,params):
        return params**0.5

    def update(self, params, *args, **kwargs):
        params = super().update(params, *args, **kwargs)

        self.ssm['obs_cov', 0,0] = params[0]
        self.ssm['state_cov', 0,0] = params[1]

nile_model = LocalLevel(nile)

print(nile_model.loglike([15099.0,1469.1]))

Best,
Chad

**Comment by jktis** [comment]
Oh Wow. I am so sorry that I bothered you with this. I stared at this for half a day an did not see that did not indent the class methods properly. Thanks for your quick reply!

**Comment by ChadFulton** [comment]
No problem, glad we could help.
