### ISSUE TITLE
[Question] Reference explaining fields in the model summary

### ISSUE THREAD

**Issue by tashrifbillah** [statsmodels/statsmodels#6672]
Can I be pointed to any reference that explains the fields in the [summary](https://www.statsmodels.org/stable/examples/notebooks/generated/glm.html#Fit-and-summary):

```
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:           ['y1', 'y2']   No. Observations:                  303
Model:                            GLM   Df Residuals:                      282
Model Family:                Binomial   Df Model:                           20
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -2998.6
Date:                Fri, 21 Feb 2020   Deviance:                       4078.8
Time:                        13:56:08   Pearson chi2:                 4.05e+03
No. Iterations:                     5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.0168      0.000    -38.749      0.000      -0.018      -0.016
x2             0.0099      0.001     16.505      0.000       0.009       0.011
x3            -0.0187      0.001    -25.182      0.000      -0.020      -0.017
```

Particular interest is on `std err          z      P>|z|      [0.025      0.975]` and the following fields:

```
Df Residuals:                      282
Df Model:                           20
Scale:                          1.0000
Log-Likelihood:                -2998.6
Deviance:                       4078.8
Pearson chi2:                 4.05e+03
```

P.S. I am new to statsmodel package and GLM.

**Comment by josef-pkt** [comment]
most of them have a brief description in the docstring
https://www.statsmodels.org/dev/generated/statsmodels.genmod.generalized_linear_model.GLMResults.html

For general explanations you need to look at a description or textbook for Generalized Linear Model.
e.g. what is deviance in GLM.

` std err z P>|z| [0.025 0.975]` are the same for parameter table in all models:
parameter estimate, 
standard error of the parameter estimate,
pvalue for the hypothesis that the parameter is zero either based on normal (z) or t-distribution,
confidence interval using the same distribution

**Comment by tashrifbillah** [comment]
Following the docstring and a book, I figured out some of the variables. Among the ones I couldn't figure yet:

- what property of the `res` should I access to know if it is normal (z) or t-distribution?
- how do you calculate the z values or t values?

**Comment by josef-pkt** [comment]
there is a `use_t` attribute and option, If False, then the normal distribution is used (and the chi2). If True, then t and F distributions are used.
Default in models except linear models like OLS is use_t=False.

We always call it `tvalues`, but it applies to both, `tvalues = params / bse`
`bse` are the standard errors for the parameter estimate, name is old and has never been changed

**Comment by tashrifbillah** [comment]
Thanks. [These](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/base/model.py#L1331) properties definitions were helpful. So is `tvalues = params / bse` a form of 
(xbar - mu) / {s / sqrt(n)} as shown [here](https://en.wikipedia.org/wiki/Student%27s_t-distribution#How_the_t-distribution_arises)? 
I noticed `bse_ = np.sqrt(np.diag(self.cov_params()))` which can be analogous to the `s` above so asking.

**Comment by josef-pkt** [comment]
similar to `(xbar - mu) / {s / sqrt(n)}` but with mu = 0 
tvalues and pvalues are for the hypothesis that the params (mu in the simple case) is zero.

Note GLM is a bit different because we have a link function to transform params and linear prediction into units corresponding to y, e.g. binary Logit assumes y is in [0, 1]

**Comment by tashrifbillah** [comment]
Found confidence interval estimation [here](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/base/model.py#L2051).

**Comment by tashrifbillah** [comment]
`use_t` is specified through [fit()](https://www.statsmodels.org/dev/generated/statsmodels.genmod.generalized_linear_model.GLM.fit.html#statsmodels.genmod.generalized_linear_model.GLM.fit) method.

**Comment by tashrifbillah** [comment]
@josef-pkt , can you point me to the function that estimates `Log-Likelihood:                -536.82` in the summary? I traced it back to [this](https://github.com/statsmodels/statsmodels/blob/828ce7a51528dfd2e042f2a18c9fac321d0569da/statsmodels/base/model.py#L886) line but `nloglikeobs` refers to a bunch of functions.

**Comment by josef-pkt** [comment]
The loglike evaluated at the estimator is `llf`
see     `def llf(self):` line 1634 for GLMResults

I don't know or remember why it doesn't just call `GLM.loglike` with `results.params`

**Comment by tashrifbillah** [comment]
Actually, I think you pointed us on step behind what I already referenced. So asking again, which nloglikeobs function [this](https://github.com/statsmodels/statsmodels/blob/828ce7a51528dfd2e042f2a18c9fac321d0569da/statsmodels/base/model.py#L890) line resolves to?

**Comment by josef-pkt** [comment]
You are already in GenericLikelihoodModels. That's a base class different from the official models.
It is meant for subclassing when the user wants to specify a new likelihood model.

examples and test cases are in statsmodels.miscmodels.

loglikeobs or nloglikeobs needs to be provided by the subclass

**Comment by tashrifbillah** [comment]
This is what I was looking for:
https://github.com/statsmodels/statsmodels/blob/828ce7a51528dfd2e042f2a18c9fac321d0569da/statsmodels/genmod/families/family.py#L555

**Comment by tashrifbillah** [comment]
Hi @josef-pkt ,

I have a couple of conceptual questions:
```
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:           ['y1', 'y2']   No. Observations:                  303
Model:                            GLM   Df Residuals:                      282
Model Family:                Binomial   Df Model:                           20
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -2998.6
Date:                Fri, 21 Feb 2020   Deviance:                       4078.8
Time:                        13:56:08   Pearson chi2:                 4.05e+03
No. Iterations:                     5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
```
* Which parameter(s) should I be looking at to understand the quality of fit?
* You already mentioned about `P>(z)`:
> pvalue for the hypothesis that the parameter is zero either based on normal (z) or t-distribution

   So does that mean the higher the pvalue an estimated parameter has:
    - the more is its effect on the response?
    - the less it can be ignored in the model?

**Comment by tashrifbillah** [comment]
Can I be pointed out to the theory of BIC? The formula used [here](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/generalized_linear_model.py#L1663) doesn't match with [this](https://en.wikipedia.org/wiki/Bayesian_information_criterion#Gaussian_special_case).

**Comment by josef-pkt** [comment]
see also #1733
Bic uses a specific definition based on deviance from the GLM literature. They rank models the same way, but have a different constant.

**Comment by tashrifbillah** [comment]
Thanks, waiting for your insight on my conceptual questions.
I found a metric [R^2](http://statistics.ats.ucla.edu/stat/mult_pkg/faq/general/Psuedo_RSquareds.htm) though.

**Comment by josef-pkt** [comment]
> Which parameter(s) should I be looking at to understand the quality of fit?

pseudo Rsquared is similar to Rsquared on OLS as a measure similar to variation explained.
pearson_chi2 / df_resid works as measure for overall goodness of fit and excess dispersion in models where scale is fixed at 1.

we should have an llnull pvalue, for a test that all slope coefficients are zero.

other measures and diagnostic tests go into specific direction to check whether the model is not incorrectly specifed, But there is not much available yet for GLM

> So does that mean the higher the pvalue an estimated parameter has:
- the more is its effect on the response?
- the less it can be ignored in the model?

kind of, but reversed
High tvalue and low pvalue means the coefficient is significant and contributes to the fit of the model. The null hypothesis is that the coefficient is zero, so a large p-value means we don't have evidence that it is nonzero, i.e. that it has an effect on the response variable.

However, there is a big distinction between statistically significant and "important" or significant in terms of subject matter.
If you have a large sample size, then small coefficients might be statistically significant, but they might not be "relevant", i.e. only have a tiny effect or predictive power.

high multicollinearity makes interpretation of statistics for individual parameters difficult, e.g. they could be insignificant individually, but statistically significant jointly

**Comment by tashrifbillah** [comment]
[llr, llr_pvalue, and prsquared](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/base/model.py#L2457) don't seem implemented. On the other hand, thanks for correcting me on my understanding of pvalues corresponding to the null hypothesis.

> pseudo Rsquared is similar to Rsquared on OLS as a measure similar to variation explained.

Did you mean it would be inappropriate to take just `Rsquared` for interpretation? I am asking because, for my data where GLM fitting is poor, I see a factor of 10 difference between `Rsqaured` (order of 0.01) and `pRsquared` (order of 0.001).

> But there is not much available yet for GLM

Can looking at the graphs demonstrated [here](https://www.statsmodels.org/stable/examples/notebooks/generated/glm.html#Plots) be a good resort?

**Comment by tashrifbillah** [comment]
Hi @josef-pkt , following up on my latest question. Thank you.

**Comment by tashrifbillah** [comment]
Also, I have been studying the relating between Chi2 statistic and null hypothesis. Can you check my interpretation of `llr_pvalue`:

The higher the `llr_pvalue`, the more confidently we can accept the null hypothesis i.e. fitted model is independent of the observation. So for the goodness of fit, we care about having a low `llr_pvalue`.

**Comment by tashrifbillah** [comment]
Hi @josef-pkt , still waiting to hear your insight. Thanks.

**Comment by tashrifbillah** [comment]
Hi @josef-pkt , still waiting to hear your insight. Thanks.

**Comment by tashrifbillah** [comment]
UCLA stats has one interpretation about why R squared is invalid and pseudo R squared is valid:
>When analyzing data with a logistic regression, an equivalent statistic to R-squared does not exist.  The model estimates from a logistic regression are maximum likelihood estimates arrived at through an iterative process.  They are not calculated to minimize variance, so the OLS approach to goodness-of-fit does not apply.  However, to evaluate the goodness-of-fit of logistic models, several pseudo R-squareds have been developed.

However, I am not doing logistic regression rather a linear one. On the other hand, I see the statsmodels converge after some number of iterations:
```
Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                   32
Model:                            GLM   Df Residuals:                       24
Model Family:                   Gamma   Df Model:                            7
Link Function:          inverse_power   Scale:                       0.0035843
Method:                          IRLS   Log-Likelihood:                -83.017
Date:                Fri, 21 Feb 2020   Deviance:                     0.087389
Time:                        13:56:10   Pearson chi2:                   0.0860
No. Iterations:                     6
```

 So, although the type of regression does not substantiate the use of pseudo R squared in statsmodel, I guess the iterative nature of the algorithm does.

**Comment by bashtage** [comment]
This appears to have been answered.
