### ISSUE TITLE
`KDEUnivariate.fit()` crashes on particular data

### ISSUE THREAD

**Issue by H2CO3** [statsmodels/statsmodels#6679]
#### Describe the bug

Hi, and thanks for making statsmodels!

I encountered an exception which I think is a bug. The `nonparametric.kde.KDEUnivariate` class throws an exception when I try to fit it on a specific piece of data. The data contains several equal values, however it is not "singular", there are different values in the array, too. Please see the reproducer below.

#### Code Sample

```python
import numpy as np
import statsmodels
from statsmodels.nonparametric.kde import KDEUnivariate

print('Numpy:', np.__version__)
print('Statsmodels:', statsmodels.__version__)
print()

x = np.array([4.59511985, 4.59511985, 4.59511985, 4.59511985, 4.59511985, 4.59511985, 4.59511985, 4.59511985, 4.59511985, 4.59511985, 5.67332327, 6.19847872, 7.43189192])
kde = KDEUnivariate(x)
kde.fit()
```

#### Expected Output

The `kde.fit()` method call should fit the model without throwing an exception.

#### Actual output

```
Numpy: 1.18.3
Statsmodels: 0.11.1

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/statsmodels/nonparametric/kde.py", line 451, in kdensityfft
    bw = float(bw)
ValueError: could not convert string to float: 'normal_reference'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "repr.py", line 11, in <module>
    kde.fit()
  File "/usr/local/lib/python3.7/site-packages/statsmodels/nonparametric/kde.py", line 140, in fit
    clip=clip, cut=cut)
  File "/usr/local/lib/python3.7/site-packages/statsmodels/nonparametric/kde.py", line 453, in kdensityfft
    bw = bandwidths.select_bandwidth(X, bw, kern) # will cross-val fit this pattern?
  File "/usr/local/lib/python3.7/site-packages/statsmodels/nonparametric/bandwidths.py", line 174, in select_bandwidth
    raise RuntimeError(err)
RuntimeError: Selected KDE bandwidth is 0. Cannot estimate density.
```

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.7.6.final.0
OS: Darwin 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.11.1 (/usr/local/lib/python3.7/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.18.3 (/usr/local/lib/python3.7/site-packages/numpy)
scipy: 1.4.1 (/usr/local/lib/python3.7/site-packages/scipy)
pandas: 1.0.3 (/usr/local/lib/python3.7/site-packages/pandas)
    dateutil: 2.7.5 (/usr/local/lib/python3.7/site-packages/dateutil)
patsy: 0.5.1 (/usr/local/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.2.1 (/usr/local/lib/python3.7/site-packages/matplotlib)
    backend: MacOSX 
cvxopt: Not installed
joblib: 0.14.1 (/usr/local/lib/python3.7/site-packages/joblib)

Developer Tools
================

IPython: Not installed
    jinja2: Not installed
sphinx: Not installed
    pygments: Not installed
pytest: 5.3.4 (/usr/local/lib/python3.7/site-packages/pytest)
virtualenv: 16.6.0 (/usr/local/lib/python3.7/site-packages)

</details>

**Comment by bashtage** [comment]
This is the correct behavior. You have asked it to compute the bandwidth for you and it computes a bandwidth of 0, in which case the KDE cannot be estimated. In these cases, the user needs to provide a bandwidth estimate.

**Comment by bashtage** [comment]
Maybe not; simple fix is to ensure that sigma > 0.

**Comment by H2CO3** [comment]
Thanks a lot!
