### ISSUE TITLE
SARIMAX statsmodels interpretation of intercept - Python

### ISSUE THREAD

**Issue by dinhtrang24** [statsmodels/statsmodels#6683]
I am using SARIMAX method in statmodels package, Python to estimate coefficients for ARIMA model. Here is the link I refer to: https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_sarimax_stata.html#

I have a question related to the example 1 in the above link. 
Below is the summary of ARIMA(1,1,1) from that link. 

![Screen Shot 2020-05-04 at 12 04 57 PM](https://user-images.githubusercontent.com/51695009/80962202-7ad4c800-8e04-11ea-9000-a91a1a4fb910.png)

As can be shown from the table, the intercept = 0.0943. But I do not understand why in the following equation of process, they have the intercept = 0.1050.

1. Could you let me know how to figure out this value?
2. In which situation, should we include intercept in our model?
3. I've read an explanation of constants in R by Rob Hyndman (https://otexts.com/fpp2/arima-r.html). Is the constant in R equivalent to intercept in SARIMAX Python?

Thank you so much in advance!

**Comment by bashtage** [comment]
It changed due to an improvement in SARIMAX and has not been fixed in the
text.
