### ISSUE TITLE
KPSS Interpolation warning 

### ISSUE THREAD

**Issue by andreamoro** [statsmodels/statsmodels#6684]
#### Describe the bug

A warning is printed out when the function is recalled, but the message is misleading and doesn't lead to resolution.

#### Code Sample, a copy-pastable example if possible

```python
from statsmodels.tsa.stattools import kpss

kpss(df.Passengers, nlags=12)
```
<details>

In executing the code above I receive the following warning 

```
/Users/andreamoro/.pyenv/versions/3.8.2/lib/python3.8/site-packages/statsmodels/tsa/stattools.py:1685: InterpolationWarning: p-value is smaller than the indicated p-value
  warn("p-value is smaller than the indicated p-value", InterpolationWarning)
```

However it is not clear how I can define a p-value the function will use to compare.

</details>

#### Expected Output

From the given message, I would expect a method or a property to set the p-value.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.8.2.final.0
OS: Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

statsmodels
===========

Installed: 0.11.1 (/Users/andreamoro/.pyenv/versions/3.8.2/lib/python3.8/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.18.3 (/Users/andreamoro/.pyenv/versions/3.8.2/lib/python3.8/site-packages/numpy)
scipy: 1.4.1 (/Users/andreamoro/.pyenv/versions/3.8.2/lib/python3.8/site-packages/scipy)
pandas: 1.0.3 (/Users/andreamoro/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pandas)
    dateutil: 2.8.1 (/Users/andreamoro/.pyenv/versions/3.8.2/lib/python3.8/site-packages/dateutil)
patsy: 0.5.1 (/Users/andreamoro/.pyenv/versions/3.8.2/lib/python3.8/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.2.1 (/Users/andreamoro/.pyenv/versions/3.8.2/lib/python3.8/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 0.14.1 (/Users/andreamoro/.pyenv/versions/3.8.2/lib/python3.8/site-packages/joblib)

Developer Tools
================

IPython: 7.14.0 (/Users/andreamoro/.pyenv/versions/3.8.2/lib/python3.8/site-packages/IPython)
    jinja2: 2.11.2 (/Users/andreamoro/.pyenv/versions/3.8.2/lib/python3.8/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.6.1 (/Users/andreamoro/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by bashtage** [comment]
It is just a bad warning message.  It should say something like `The p-value of the test statistic is less than the minimum value in the table, and so id set the the smallest p-value in the table (.001)`  (I would need to check the .001.)

**Comment by rcyost** [comment]
Is there a way to mute the warning?

**Comment by bashtage** [comment]
You can use warnings.simplefilter to silence specific warnings.
