### ISSUE TITLE
STL Trend Smoother Default

### ISSUE THREAD

**Issue by rac359** [statsmodels/statsmodels#6701]
The STL parameters include a parameter for the trend smoother component, with the default being:

1.5 * period

In Cleveland's 1990 paper, he suggests the default trend smoother to be greater than or equal to:

1.5 * period / (1 - (1.5 / seasonal_smoother))

See page 18 [here](https://search.proquest.com/openview/cc5001e8a0978a6c029ae9a41af00f21/1?pq-origsite=gscholar&cbl=105444)

Is there a reason 1.5 * period was selected over Cleveland's suggestion?

**Comment by bashtage** [comment]
The code is an exact translation of the fortran source and so does what the
code does, not what the paper says.

**Comment by rac359** [comment]
Thanks for your comment Kevin.

I found the original Fortran [here](https://www.netlib.org/a/stl). When looking through it, you can see the line:

nt = (1.5*newnp)/(1 - 1.5/newns) + 0.5

where nt is the trend component. The equation is the Fortran seems to mirror Cleveland's paper much more closely than the simplified 1.5 * period.

Unless there's a different/earlier version of the Fortran that I'm missing?

**Comment by bashtage** [comment]
I suppose it comes from this comment:

```
The value of nt should be an odd integer greater than or equal to 3;
-a value of nt between 1.5*np and 2*np is recommended.
-As nt increases the values of the trend component become smoother.
```

**Comment by bashtage** [comment]
If seasonal is at least 7, then this makes little difference since the 1.5 goes to about 1.9.  It can make a non-trivial change if seasonal is 3.
