### ISSUE TITLE
Use of qqplot in analyzing goodness of fit

### ISSUE THREAD

**Issue by tashrifbillah** [statsmodels/statsmodels#6703]
Does anyone know what would be the slope of an OLS line in [qqplot](https://www.statsmodels.org/stable/examples/notebooks/generated/glm.html#Plots) for perfect normal distribution? See the text in Jeff Gill's book as referenced [here](https://www.statsmodels.org/stable/glm.html#references):

![image](https://user-images.githubusercontent.com/35086881/81611138-8ac24e00-93a8-11ea-8d1a-a0cca016473c.png)

![image](https://user-images.githubusercontent.com/35086881/81611175-9746a680-93a8-11ea-8f2f-f0d224593e58.png)

From the text `with slope equal to the mean of the normal variates`, I infer it to be zero but that does not appear to be anywhere close to the slope of OLS line in the third plot.

**Comment by tashrifbillah** [comment]
I think the perfect slope would be equal to the standard deviation of the residuals (normal variates), not mean.

**Comment by josef-pkt** [comment]
Yes, it is the standard deviation, or `scale` in scipy.stats.distributions.

If the data were standardized by mean and scale, then the slope would be 1.

**Comment by tashrifbillah** [comment]
So should we assume the author made a mistake?

**Comment by josef-pkt** [comment]
Yes, AFAIU, inverting standardizing a variable, the regression line in this plot should be

y_hat = mean_y + scale * ppf_normal

If we use the nonstandardized normal distribution N(mean, scale**2) on the horizontal axis, then the slope is 1 and origin is at zero.
(In our qqplot there was an ambiguity about whether we use standardized or loc-scale distribution on the horizontal axis.)
