### ISSUE TITLE
Inconsistent results after using ARMA

### ISSUE THREAD

**Issue by SasukeBansal** [statsmodels/statsmodels#6718]
We are trying to fit the ARMA on the time series data but getting different results on different devices (i.e. each user is getting different predictions after fitting the data).

```
df_arma = df['var']
model = ARMA(df_arma, order= (3, 1))
results = model.fit()
print(results.predict())

```
Even though we are using the same version of the statsmodel library, but are still facing the issue.

Here is sample output from 2 different users. Also, tried setting same random seed for the different users.

![image](https://user-images.githubusercontent.com/32007887/82057659-510f8100-96e1-11ea-817b-d5701806f09f.png)
![image](https://user-images.githubusercontent.com/32007887/82057714-5bca1600-96e1-11ea-96c7-479dc7ddb44f.png)

We have also tried generating the output on different sets of variables, but are getting the issue for each of the variables.

**Comment by bashtage** [comment]
Please edit the issue to report your issue.

**Comment by SasukeBansal** [comment]
> Please edit the issue to report your issue.

Edited the issue.

**Comment by bashtage** [comment]
Don't use ARMA. Use SARIMAX. ARMA is being retired and isn't actively maintained.

**Comment by bashtage** [comment]
Do you still see the issue with SARIMAX?

**Comment by SasukeBansal** [comment]
> Do you still see the issue with SARIMAX?

Thanks. SARIMAX does not have the issue.
