### ISSUE TITLE
warning if extensions not build

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#672]
just saw this https://gist.github.com/beOn/4970435

```
    Warning: The C extension could not be compiled, speedups are not enabled.    Plain-Python installation succeeded.Successfully installed Shapely
```

I was thinking about creating a function to check whether extensions are used, and one that checks/prints versions of dependencies. (pymvpa has the later)

we could also print a warning on install, I think it's silent now.

**Comment by bashtage** [comment]
@josef-pkt This isn't possible with the dependence on extensions now.  Can be closed.

**Comment by bashtage** [comment]
This is no longer relevant since the extensions are not required.
