### ISSUE TITLE
No module named 'statsmodels.tools'

### ISSUE THREAD

**Issue by sathya9897** [statsmodels/statsmodels#6724]
#### Describe the bug
i have installed the latest version 0.11.1 using pip and when i do
`import statsmodels.api as sm`
or
`from statsmodels import robust`
gives me an error saying
`No module named 'statsmodels.tools'`

i did `dir(statsmodels)` and this was the log
```
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_version', 'debug_warnings', 'test']
```

I tried installing it multiple times after uninstalling and using a no-cache flag as well.
I have a windows 10 machine.

What's wrong and how can it be fixed?

**Comment by bashtage** [comment]
Are you using statsmodels through pdmarima?

**Comment by sathya9897** [comment]
No. I have directly installed it as a global module using pip. No virtual env.

**Comment by bashtage** [comment]
It is not usually a good idea to use system python. Have you tried
anaconda?

**Comment by sathya9897** [comment]
No. Can just use virtual environment instead of anaconda? would that suffice?

**Comment by bashtage** [comment]
A virtual env should work.  Which python are you using? 3.6, 3.7?

**Comment by bashtage** [comment]
Also what happens when you enter 

```
from statsmodels import tools
```

**Comment by Ritik2604** [comment]
I think he didnt install python latest version completely he left some of files to download

**Comment by bashtage** [comment]
Going to close since there is no action. If you still have issues, you can continue posting in this thread.

**Comment by Dmonzer** [comment]
Did you figure out how to fix it? I am having this issue at the moment. I have used statsmodels before, but I am installing it in a new environment now, and I am having the same error.

**Comment by Dmonzer** [comment]
it was just that I had storage issues and the module was installed partially. Solved it.
