### ISSUE TITLE
Add another nan-handling method in acf()

### ISSUE THREAD

**Issue by anntzer** [statsmodels/statsmodels#6729]
#### Is your feature request related to a problem? Please describe

#6641/#6726 revealed that `acf(..., missing="conservative")` did not behave as I would have hoped, and I would thus like to request a new nan-handling policy.  Specifically, it would seem reasonable to have a policy where the n-th lag acf of `t` is computed as something like `np.nanmean(t[:n] * t[-n:])` (with the correct centering and rescaling), i.e. dropping the nan terms in the sum (which "conservative" does, by setting them to zero) but also in the denominator when computing the mean.  The final rescaling should also be done by `np.nanmean(t**2)`, i.e. here too nans should be dropped from the denominator.

#### Describe the solution you'd like
Add a `missing="???"` policy to `acf()` which implements the approach above.  Name up to bikeshedding...

#### Describe alternatives you have considered
None that I can think of.

#### Additional context
N/A

**Comment by bashtage** [comment]
I think this is already done. 

If `x` is the original series, an x0 is the series with NaN replaced by 0, then the mean is estimated as ```
not_missing = ~np.isnan(x)
mean = x0.sum() / not_missing.sum()
x0[not_mising] -= mean
```

Explainer could probably be improved.

**Comment by anntzer** [comment]
I haven't checked the math of the implementation, but at least from a documentation point of view, "replaces missing with zero" (the current explanation) is not the same as "dropping nan terms *both* from the numerator and the denominator" I think(?)

**Comment by bashtage** [comment]
I have fixed the docs and directly tested that the conservative method is exactly this. The standard estimator only using nan-ops.

**Comment by anntzer** [comment]
Great, thanks!
