### ISSUE TITLE
glm logit confidence intervals  categorical covariates difference with R 

### ISSUE THREAD

**Issue by telferm57** [statsmodels/statsmodels#6734]
When running a test glm  on a cutdown version of Pima diabetes dataset in which I have binned the ages into [20-39], [40-59], [> 59] I get some difference on the confidence intervals, particularly the > 59 age bin categorical variables. I think both R and sm are using the profiling likelihood method for calculating CI's. Just want to check if this is a known issue before I submit the code and data 

#### Code Sample, a copy-pastable example if possible

```python
# Your code here that produces the bug
# This example should be self-contained, and so not rely on external data.
# It should run in a fresh ipython session, and so include all relevant imports.
```
<details>
formula is: 

```
Outcome ~ C(Age_Group, Treatment(reference= "20-39")) + BloodPressure + Pregnancies + Skin_Thickness + Insulin + Glucose + BMI + DiabetesPedigreeFunction
```
percentage difference in 95L between statsmodels and R confint :
```
BMI                                                    0.051793
BloodPressure                                          0.010021
C(Age_Group, Treatment(reference="20-39"))[T.40-59]    0.241648
C(Age_Group, Treatment(reference="20-39"))[T.>59]     -3.546027
DiabetesPedigreeFunction                               0.777237
Glucose                                                0.039396
Insulin                                                0.000000
Intercept                                              0.000000
Pregnancies                                            0.065877
Skin_Thickness                                        -0.004914

```

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

confidence intervals from sm to be with 0.5% of R (is this reasonable?) 

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------

Python: 3.7.5.final.0
statsmodels

Installed: 0.11.0 (C:\Users\mtelfer\PycharmProjects\venv\lib\site-packages\statsmodels)

Required Dependencies

cython: Not installed

numpy: 1.18.0 (~\venv\lib\site-packages\numpy)

scipy: 1.1.0 (~\venv\lib\site-packages\scipy)

pandas: 0.24.2 (~\venv\lib\site-packages\pandas)

dateutil: 2.8.1 (~\venv\lib\site-packages\dateutil)

patsy: 0.5.1 (~\venv\lib\site-packages\patsy)
</details>

**Comment by josef-pkt** [comment]
statsmodels is using Wald confidence intervals, not likelihood intervals.
We don't have those yet. They are waiting in a PR.
(We will also get score test confidence intervals but those are waiting in another PR)

**Comment by telferm57** [comment]
AH, right , thanks for quick response - for some reason I had thought that had been merged ... I'll recheck (but the SE's match,  so probably  it will OK)

**Comment by telferm57** [comment]
yep all OK, thanks
