### ISSUE TITLE
The first element of ARIMA residuals is very large

### ISSUE THREAD

**Issue by Vaneshieh** [statsmodels/statsmodels#6736]
Hello,

Hope all is well with you.

I'm using ARIMA model to deal with SPY price. I found the first element in the model residuals is very large. I don't know if I select some parameters of the model incorrectly. Is there anyone who can help? Thank you very much.

arima = sm.tsa.statespace.SARIMAX(train,order=(1,1,1),seasonal_order=(0,0,0,0),trend='c',
                                 enforce_stationarity=False, enforce_invertibility=False,).fit()
arima.summary()

resid = pd.Series(arima.resid,index=df['date'][0:Train_samples])
res_df = pd.DataFrame(resid,columns=['resid'])
res_df.sort_values(by='resid',ascending=False).head()

The first five elements:
resid
--
127.495000
3.489213
3.319568
3.096821
2.75770

train[0:5]
array([127.495, 127.7  , 128.04 , 127.71 , 128.02 ])

It seems the first residual is the same as the first train sample. 

Is it because I used the first difference? So the model cannot measure the first element well?

**Comment by Vaneshieh** [comment]
Hello,

Hope all is well with you.
I'm using ARIMA model to model spy stock price. When I

**Comment by bashtage** [comment]
This is because you have lags 1, 12 and 13 in your model and so there is no data available to fit the first observation. Please search for related issues, this has been discussed before.
