### ISSUE TITLE
replicate R's mantelhaen.test with statsmodels.stats.contingency_tables.StratifiedTable().oddsratio_pooled

### ISSUE THREAD

**Issue by brandonlind** [statsmodels/statsmodels#6737]
I'm having trouble reproducing the odds ratio output from R's `mantelhaen.test` function - `mantelhaen.test()$estimate`.

Across different tests i perform, the `oddsratio_pool` matches with some of the R function outputs, while the rest do not. But if I switch columns or rows in my stratified tables, I can get the the R output for the tests that I previously could not reproduce, but now the previous tests I did reproduce are incorrect.

Is it as simple as updating the following method?:
```
    def oddsratio_pooled(self):
        """
        The pooled odds ratio.

        The value is an estimate of a common odds ratio across all of the
        stratified tables.
        """

        if sum(self._bc) <= sum(self._ad):
            odds_ratio = np.sum(self._ad / self._n) / np.sum(self._bc / self._n)
        else:
            odds_ratio = np.sum(self._bc / self._n) / np.sum(self._ad / self._n)

        return odds_ratio
```

Any other suggestions as to why I'm only getting the odds ratio from `mantelhaen.test` some of the time?

Thanks!

**Comment by josef-pkt** [comment]
has this been cleared up? Is there anything that we need to look at for statsmodels?

I was using StratifiedTable recently to compare with R meta-analysis packages and didn't see any disagreement or problems.

**Comment by brandonlind** [comment]
Yeah, sorry. I was comparing to my colleague's R code. They were handling contingency table columns differently which is what lead to the inconsistency.
