### ISSUE TITLE
DOC: metaanalysis1 and quasibinomial are missing from examples

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#6741]
metaanalysis1 and quasibinomial are missing from examples

@kshedden I'm not sure where these should go.

**Comment by josef-pkt** [comment]
quasibinomial belongs to genmod, next to GLM examples

metaanalysis1 belongs in stats. 
I haven't added my recent stats PRs to docs yet.
(I will need to review and add to docs for those stats PRs before a release)

**Comment by bashtage** [comment]
Fixed.
