### ISSUE TITLE
Question: Do all ARMA/ARIMA examples in docs have lookahead bias?

### ISSUE THREAD

**Issue by smabie** [statsmodels/statsmodels#6750]
If I just use the `predict()` function (like in the examples), it seems to me that we're predicting values based on data we used to generate the parameters of the model Let's say that every day I get some new time series data and I want to predict the next days data. What is the best way to do this?

Do I need to have a rolling window and fit and then forecast one step ahead over and over again? 

What if instead of a rolling window, I want to fit the parameters based on training data and then use it on out of sample data? How would I do this? Could someone give me some code samples? It doesn't seem like statsmodel makes this easy. I find it confusing that all this emphasis is placed on the predict function, when it seems to me that the results are necessarily invalid. Unless predict only uses samples in the past to fit the model? But I don't think that is true because fitting is relegated to a different method. 

Edit: I found this is the documentation:

```
Note: These are technically in-sample since the data we are forecasting was used to estimate parameters. Producing OOS forecasts requires two models. The first must exclude the OOS period. The second uses the predict method from the full-sample model with the parameters from the shorter sample model that excluded the OOS period.
```

Could someone give me an example of how to do this? Is the following correct?

```
arma = tsa.ARMA(in_sample, (2, 2)).fit()
arma.initialize(tsa.ARMA(out_sample, (2, 2)), arma.params)
```

**Comment by bashtage** [comment]
When you use `forecast` and a result then you get out-of-sample forecasts. After you estimate parameters from the initial model. you can call `extend` to add new data.

**Comment by smabie** [comment]
Is there a reason why this method does not seem to exist for ARMA? Should I just use ARIMA with a differencing order of 0?

**Comment by smabie** [comment]
I just tried, but statsmodel automatically generates an ARMAResultsWrapper object when d=0. How do I access extend with ARMA?

**Comment by bashtage** [comment]
Don't use ARMA/ARIMA, these are defacto deprecated.  Use SARIMAX.

**Comment by bashtage** [comment]
SARIMAX with order (p,0,q), no exog and no seasonal is an ARMA(P,Q)

**Comment by bashtage** [comment]
You can also use statsmodels.tsa.arima.ARIMA if you are using the development version. This is a special-cased SARIMAX model that removes the S and X bits. Other than a bit of simplicity, there are no gains AFAIK to using the stripped version.

**Comment by smabie** [comment]
Ah okay, thanks a bunch!
