### ISSUE TITLE
Possible typo on  the page

### ISSUE THREAD

**Issue by pawarbi** [statsmodels/statsmodels#6754]
[On this page](https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.exponential_smoothing.ExponentialSmoothing.html) under notes, it's written that _the statespace exponential smoothing is worse than sm.tsa.ExponentialSmoothing_ There is no sm.tsa.ExponentialSmoothing class. Did you mean sm.tsa.holtwinters.ExponentialSmoothing ? Please clarify and please add a link to the referenced class.

Thanks

**Comment by bashtage** [comment]
It should just say `tsa.ExponentialSmoothing` which uses the canonical reference to `import statsmodels.tsa.api as tsa`.
