### ISSUE TITLE
ImportError: cannot import name 'Appender' from 'statsmodels.compat.pandas'

### ISSUE THREAD

**Issue by shikhnu** [statsmodels/statsmodels#6760]
After installing pmdarima tried below query:

from pmdarima import auto_arima
import warnings
warnings.filterwarnings('ignore')

ImportError: cannot import name 'Appender' from 'statsmodels.compat.pandas'

updated pandas version: 1.0.3
statsmodels: 0.11.1

Need Help

**Comment by bashtage** [comment]
What happens if you directly try and import statsmodels.api or statsmodels.tsa.api?

**Comment by shikhnu** [comment]
It is sorted. Just uninstalled  statsmodels and reinstalled it.
