### ISSUE TITLE
Weighted IV2SLS

### ISSUE THREAD

**Issue by MaxGhenis** [statsmodels/statsmodels#6761]
#### Is your feature request related to a problem? Please describe
I'd like to use observation weights in IV2SLS models.

#### Describe the solution you'd like
An optional argument to specify weights, as in WLS.

#### Describe alternatives you have considered
[`linearmodels IV2SLS`](https://bashtage.github.io/linearmodels/iv/iv/linearmodels.iv.model.IV2SLS.html#linearmodels.iv.model.IV2SLS) accepts weights, as do R's [`AER ivreg`](https://www.rdocumentation.org/packages/AER/versions/1.2-9/topics/ivreg) and [`lfe felm`](https://www.rdocumentation.org/packages/lfe/versions/2.8-5/topics/felm).

**Comment by bashtage** [comment]
Just use linearmodels.

**Comment by MaxGhenis** [comment]
In general, if functionality is available in `linearmodels`, will it not be added to `statsmodels`? I need to use `stargazer` so pending https://github.com/bashtage/linearmodels/issues/270 or https://github.com/mwburke/stargazer/issues/26 I'll probably have to use R for missing features.

**Comment by bashtage** [comment]
There are no plans to move linearmodels to statsmodels. You can probably
write a simple wrapper that will fake a statsmodels object enough for
stargazer so that you can use linearmodels in it too.
