### ISSUE TITLE
BUG: Future failures due to changes in SciPy optimize

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#6771]
#### Describe the bug

https://travis-ci.org/github/statsmodels/statsmodels/jobs/693651513
`test_full_output_false` and `test_full_output` both failing on scipy: 1.5.0rc1. 

Will need a fix soon.

@josef-pkt @ChadFulton @kshedden Should probably have a SM release in the next month or so.

**Comment by josef-pkt** [comment]
I opened a scipy issue with my guess for a missing squeeze.
@bashtage  Can you the tests with scipy rc to see what the failure is ( whether it's really a squeeze)?

**Comment by josef-pkt** [comment]
the failure is in asserting the shape of xopt, i.e. params, not in fopt as I thought initially.

The failing unit test essentially checks that there is still the inconsistency or bug in the return shape of fmin_powell for xopt.
Getting a scalar, not atleast_1d, params breaks the hessian computation and `method="powell"` breaks our `fit` if there is only a single parameter.

It's still open whether fmin_powell will be changed in scipy, but we need to change this unit test.

The bug in fit with `method="powell"`  for single params can be worked around by users by using the `minimize` option as fit method which should work (not verified yet)

**Comment by bashtage** [comment]
closed by e20483ff8e7710ea2023336e7fee5bb1b0242dbe
