### ISSUE TITLE
arima_model or arima.model, two classes, lots of confusion

### ISSUE THREAD

**Issue by andreamoro** [statsmodels/statsmodels#6772]
I was looking at some examples yesterday night to solve an issue re invertibility and then I noticed the presence of arima_model and arima.model which is confusing.

The latter seems to be the master class, and the first the wrapper, but the lack of documentation doesn't help.

I just find this out as a chance because of the enforce_inversability param that is missing on the first.

**Comment by bashtage** [comment]
arima_model is deprecated.  You should be arima.model.

**Comment by bashtage** [comment]
https://www.statsmodels.org/devel/generated/statsmodels.tsa.arima_model.ARIMA.html?highlight=arima#statsmodels.tsa.arima_model.ARIMA

**Comment by andreamoro** [comment]
Well, as far as I can see the 0.11.1 is still the current version, with the 0.12 being in dev. Would you recommend to use that?

**Comment by bashtage** [comment]
TSA is pretty fast moving so in most application of TSA I recommend dev.

**Comment by andreamoro** [comment]
Ok thanks. Can you point me in the direction of some guides that could explain how to solve the invertibility issue?
I have a differenced ts dataset, but over a certain lag I get the error message either with AR or MA telling me my set is not stationary at that time. 
Since I'm learning these days, do you have anything that can support in that respect?

**Comment by bashtage** [comment]
I suspect you are running into issues where models are not well identified. This can happen when models have too many lags.  You can ignore these messages and are likely to not choose these models when using any reasonable model selection method (AIC/BIC or Cross-validation).

**Comment by bashtage** [comment]
Closing since no action; doesn't mean I'm cutting off the conversation.

**Comment by andreamoro** [comment]
>> I suspect you are running into issues where models are not well identified. 
Not sure here.
>> This can happen when models have too many lags. 
Well, if my understanding is correct - so please feed me in if incorrect - a lag is the time between each notable spike.
Since I have a ds with weekly data, my lag is 7, but the lag is also diminishing with time.

Guess the PACF below could explain?
![image](https://user-images.githubusercontent.com/5256583/83687789-8fb39f80-a5ec-11ea-8752-9ad27c84ff2d.png)

>>> You can ignore these messages and are likely to not choose these models when using any reasonable model selection method (AIC/BIC or Cross-validation).
I completely lost you here on what should i do.

The only thing I know is that by looking at the RSME of the ds (a 2 years daily data set), I ended up choosing the following hyper parameter as ones with the less margin of errors.
p = 13, d = 0, q = 15, s = 21

However, it's over 2 hours that the computer is running and I don't see anything. Just the fan that is running at an higher speed.
I even don't know how long it will take to complete.

Any chance to know?

I have this in the terminal output. I'm not sure what I am reading there.

![image](https://user-images.githubusercontent.com/5256583/83688040-06e93380-a5ed-11ea-8ab2-c13a652bc124.png)]

Should iterate reach 57 (from the current 5)?
Any chance to speed up the operations?

Thank you very much for the support.

**Comment by ChadFulton** [comment]
> The only thing I know is that by looking at the RSME of the ds (a 2 years daily data set), I ended up choosing the following hyper parameter as ones with the less margin of errors.
p = 13, d = 0, q = 15, s = 21
> However, it's over 2 hours that the computer is running and I don't see anything. Just the fan that is running at an higher speed.
I even don't know how long it will take to complete.

Estimating models with long seasonal effects is computationally demanding; see for example my answer to [this stackoverflow question](https://stackoverflow.com/questions/61548583/why-sarima-has-seasonal-limits/61583317#61583317). One way to get around that, if you don't have any missing values in your data, is the following:

```python
mod = sm.tsa.arima.ARIMA(endog, order=(p, d, q), seasonal_order=(P, D, Q, s))
res = mod.fit(method='innovations_mle', low_memory=True, cov_type='none')
```

The long seasonal delay in the PACF you posted makes me think that you'd be better off with seasonal differencing, and I wonder if you might want to try a much simpler model, like:

```python
mod = sm.tsa.arima.ARIMA(endog, order=(2, 0, 0), seasonal_order=(1, 1, 0, 7))
```

>> You can ignore these messages and are likely to not choose these models when using any reasonable model selection method (AIC/BIC or Cross-validation).
> I completely lost you here on what should i do.

I think @bashtage is saying that alternative model selection techniques - like minimizing the AIC / BIC, or using out-of-sample cross-validation techniques - will probably lead you to a more reasonable model.

One reason for that is that adding additional AR or MA terms will almost always decrease the RMSE, so it is useful to peform model selection using information criteria that penalize each additional parameter.

**Comment by bashtage** [comment]
You appear to have an AR(1), seasonal MA(1), so order=(1,0,0) and seasonal_order=(0,0,1,7).

**Comment by andreamoro** [comment]
Thanks @ChadFulton & @bashtage, really appreciated. 

To make it useful, can you please help me understanding how you arrived to your parameter selection?

**Comment by bashtage** [comment]
Consistent negative PACF at lags 7, 14, 21 suggests a 7 day seasonality. MA with positive coefficient produces all negative PACF values, so use this at the seasonal freq. You then appear to have a little short run dynamics at the observation freq, so an AR(1) to soak that up.

**Comment by andreamoro** [comment]
Hi @bashtage I can ultimately get the negativity and the seasonal bit. That was clear to me even without looking at the PACF.

What I am after, and apologies for abusing of your time but I'm learning these days, is:
a) you mentioned MA being positive. But the plot above is for a PACF which is my understanding is plots the AR. So how can you see the MA there?
b) You applied a Q=1. This goes back to point a), but also you applied this to the seasonal_components only. Why not using both the same values for the p,d,q and P,D,Q?
C) you applied a p param of 1, but I was so far understood I always have to choose the one that goes next to 0, or say at the beginning of the blue area. And 1 does not; eventually it would have been a 3. This I cannot understand.

Thanks again for your time in supporting my learning.

**Comment by andreamoro** [comment]
So plaid around with values a tiny bit ... and ended up to obtain something that I feel it is good, but your opinion is appreciated.

![image](https://user-images.githubusercontent.com/5256583/83845023-5c663300-a708-11ea-996e-eb2a43280f0a.png)

**Comment by bashtage** [comment]
Q=21 cannot be right.  WIth S=7, Q=21 implies that you model has MA lags 7,14,...,21*7 it.  I am surprised shocked that p=13 is a good choice.  This seems far too high. 

> you mentioned MA being positive. But the plot above is for a PACF which is my understanding plots the AR. So where do you see the MA there?

a. A persistent, decay in the  PACF indicates that you need an MA. If the PACF cuts off sharply after M lags, then you need an AR(M). 
b. Seasonal adds lags at the seasonal freq, so with S=7, Q=1 adds in lag 7 of the error. 
c. I guessed p=1, but it could be some other small number. Have you tried minimizing the AIC or BIC over p=1,2,...,13?  What does it choose?

**Comment by andreamoro** [comment]
Thanks again for feeding in.

> Q=21 cannot be right. ... I am surprised shocked that p=13 is a good choice. This seems far too high.

So here are the two full PACF and ACF plots

![image](https://user-images.githubusercontent.com/5256583/83854619-44e27680-a717-11ea-83b0-1e8861cbc5aa.png) 

Judging from your explanation, no, I don't see that to be right. The plot shows MA lags 7, 13 and probably nothing else. So guess that my Q has to be one of these two?

As for p=13, I may be wrong. I was thought to choose the first item that goes next to zero but not fall in the blue area. Is this correct?
In this respect I should choose 3. So yes, 13 was mostly an attempt to see what else I was getting out of it.

**What have I done to determine the right combination (chance are my approach is totally wrong)?**

I'm at the moment leaning on two ways to determine how much good the results are: 
- A visual inspection (weak method  considering the plots similarity), 
- An average of the difference between the forecast and the real data. The closest to reality must suggest the correct one I guess. 

I got the following to continue our conversation, if you have some spare time.

To determine the best parameter combination I ran a grid search with the ARIMA model, using the RSME as the coefficient to suggest the best one.

|p|d|q|RSME|
|-|-|-|-|
|3|0|4|18.248%|
|3|1|4|17.966%|
|3|1|0|18.171%|
|4|0|4|18.247%|
|4|1|4|17.968%|
|4|0|5|18.194%|
|4|1|5|18.108%|
|6|0|4|18.195%|
|6|1|4|18.059%|
|9|0|10|18.466%|
|9|1|10|18.278%|
|13|0|15|18.488%|
|13|1|15|18.261%|
|13|0|21|18.423%|
|13|1|21|18.317%|

With some of the above combinations, I did run the a SARIMA and got the following averaged difference. 

|p|d|q|P|D|Q|s|avg % diff from real data|
|-|-|-|-|-|-|-|-|
|3|1|4|3|1|4|7|22.13%|
|4|1|4|4|1|4|7|8.62%|
|6|1|4|6|1|4|7|17.76%|
|6|0|0|0|1|4|7|31.83%|
|6|0|0|0|0|4|7|60.67%|
|6|0|4|0|0|4|7|61.17%|
|13|1|0|0|1|21|7|22.32%|

Have to say, that despite the above, when looking at the prediction graph, some of them resulted very unrealistic, like the one for the combination p = 4; d = 1; q = 4; P = 4; D = 1; Q = 4; s = 7;

![image](https://user-images.githubusercontent.com/5256583/83869938-a8779e80-a72d-11ea-887b-ce6309bd2686.png)

Whereas some that have an higher RSME have in fact resulted better visually and in terms of average difference.

![image](https://user-images.githubusercontent.com/5256583/83870098-ed033a00-a72d-11ea-9606-9a5a43debb39.png)

I guess I need to look at the AIC and BIC you mentioned. But they have never been mentioned over this course. Any place where I should start from?


> a. A persistent, decay in the PACF indicates that you need an MA. If the PACF cuts off sharply after M lags, then you need an AR(M).

Are you suggesting the two are mutually exclusive, so if I have an MA I cannot have an AR and vice-versa?
Is M the first value at 0?
A general question here: you have drawn your conclusions only from the PACF. Is this ok, or should both be used? Or one exclude the other?

> b. Seasonal adds lags at the seasonal freq, so with S=7, Q=1 adds in lag 7 of the error.

Is the Q here correct, or was it meant to be D?
If correct, is the principle to have Q+=1 for each recorded lag in the PACF?

**Comment by andreamoro** [comment]
Hi @bashtage, can I kindly ask your last input on the above?

**Comment by bashtage** [comment]
Trends are notoriously difficult to forecast especially over long horizons.  It is common to damp any trend estimate possibly to 0 if it is not statistically different from 0.
