### ISSUE TITLE
Add Root Mean Square Percentage Error to evaluation measures

### ISSUE THREAD

**Issue by peterprescott** [statsmodels/statsmodels#6773]
#### Is your feature request related to a problem? Please describe
There are many cases in which a Percentage Error is a more appropriate measure of model fit than an Absolute Error.

#### Describe the solution you'd like
I have added a simple Root Mean Square Percentage Error function, for which I am ready to make a pull request.

#### Additional context
The only complexity is handling zero values. My function includes a parameter in which the user is able to specify whether they would like the zero-value case to return `np.nan` (default) or some other value.

**Comment by bashtage** [comment]
Fixed in master.
