### ISSUE TITLE
AttributeError when calling OLSResults.resid after calling OLS.fit() in one line, but not over two lines

### ISSUE THREAD

**Issue by o-P-o** [statsmodels/statsmodels#6783]
#### Bug description

There is an inconsistency that occurs between 

1. Calling `OLS(y, x).fit()` on a single line and then generating the OLSResults object, and

2. Calling `lm=OLS(y, x)` on one line, and then `lm.fit()` on a second line and then generating the OLSResults object.

Case (2) results in an error when applying methods of the OLSResults object, but case (1) does not. Sample below.

#### Code Sample

```
import pandas as pd
from statsmodels.datasets import get_rdataset
from statsmodels.regression import linear_model
from statsmodels.tools import add_constant

data = get_rdataset("Boston", package="MASS", cache=False)
df = data.data

df['lstat2'] = df.lstat ** 2

X = df.filter(['lstat', 'lstat2'], axis=1)
X = add_constant(X, prepend=True)
y = df.medv

# Case 1 (works fine)
model1 = linear_model.OLS(y, X)
output1 = model1.fit()
params1, covs1 = output1.params, output1.normalized_cov_params
results1 = linear_model.OLSResults(model1, params1, covs1)
residuals1 = results1.resid

# Case 2 (AttributeError)
model2 = linear_model.OLS(y, X).fit()
params2, covs2 = model2.params, model2.normalized_cov_params
results2 = linear_model.OLSResults(model2, params2, covs2)
residuals2 = results2.resid
```

Error message:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-302-ea72a870a1a7> in <module>
     24 params2, covs2 = model2.params, model2.normalized_cov_params
     25 results2 = linear_model.OLSResults(model2, params2, covs2)
---> 26 residuals2 = results2.resid

pandas/_libs/properties.pyx in pandas._libs.properties.CachedProperty.__get__()

~/opt/anaconda3/envs/ml_lessons/lib/python3.8/site-packages/statsmodels/regression/linear_model.py in resid(self)
   1605     def resid(self):
   1606         """The residuals of the model."""
-> 1607         return self.model.endog - self.model.predict(
   1608             self.params, self.model.exog)
   1609 

~/opt/anaconda3/envs/ml_lessons/lib/python3.8/site-packages/statsmodels/base/wrapper.py in __getattribute__(self, attr)
     34             pass
     35 
---> 36         obj = getattr(results, attr)
     37         data = results.model.data
     38         how = self._wrap_attrs.get(attr)

AttributeError: 'OLSResults' object has no attribute 'endog'
```

#### Expected Output

The code should produce no output, but variables `residuals1` and `residuals2` should be equal.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>
INSTALLED VERSIONS
------------------
Python: 3.8.3.final.0
OS: Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:47:48 PST 2020; root:xnu-6153.101.6~16/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: en_GB.UTF-8

statsmodels
===========

Installed: 0.11.1 (/Users/oliverprice/opt/anaconda3/envs/ml_lessons/lib/python3.8/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.18.1 (/Users/oliverprice/opt/anaconda3/envs/ml_lessons/lib/python3.8/site-packages/numpy)
scipy: 1.4.1 (/Users/oliverprice/opt/anaconda3/envs/ml_lessons/lib/python3.8/site-packages/scipy)
pandas: 1.0.3 (/Users/oliverprice/opt/anaconda3/envs/ml_lessons/lib/python3.8/site-packages/pandas)
    dateutil: 2.8.1 (/Users/oliverprice/opt/anaconda3/envs/ml_lessons/lib/python3.8/site-packages/dateutil)
patsy: 0.5.1 (/Users/oliverprice/opt/anaconda3/envs/ml_lessons/lib/python3.8/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.1.3 (/Users/oliverprice/opt/anaconda3/envs/ml_lessons/lib/python3.8/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 0.15.1 (/Users/oliverprice/opt/anaconda3/envs/ml_lessons/lib/python3.8/site-packages/joblib)

Developer Tools
================

IPython: 7.14.0 (/Users/oliverprice/opt/anaconda3/envs/ml_lessons/lib/python3.8/site-packages/IPython)
    jinja2: 2.11.2 (/Users/oliverprice/opt/anaconda3/envs/ml_lessons/lib/python3.8/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.6.1 (/Users/oliverprice/opt/anaconda3/envs/ml_lessons/lib/python3.8/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed
</details>

**Comment by bashtage** [comment]
Model 2 is not a model but is a result.  The model is lost since you don't attach it to any variable. I don't know why you are creating an OLS result.  When you call OLS.fit() it returns an OLSResult (which is Wrapped for pandas compat).

**Comment by bashtage** [comment]
Closing since no action from us.
