### ISSUE TITLE
Datetime frequency

### ISSUE THREAD

**Issue by ikramelmbarki** [statsmodels/statsmodels#6787]
Hello everybody, I'm working on my final project and 
I wanna apply SARIMAX on my data but first, I need to study the trend, seasonality...
I tried to set the date column as an index and sort the values and i wanna change the frequency of the data i tried all the StackOverflow methods but i can't change the "None" value.
This is my data :
https://drive.google.com/file/d/1E3sIqScyy6zzjE5_ZX5pF4605bgSmFaa/view?usp=sharing
This is when i sort the values of the index
![image](https://user-images.githubusercontent.com/57155043/83979194-72404780-a904-11ea-8e34-13c3d9e15d56.png)
and this is the error :
![image](https://user-images.githubusercontent.com/57155043/83979222-9ef45f00-a904-11ea-8e23-3f9b529ffe26.png)
Thank you in advance, I really appreciate your effort
Note: The data is not preprocessed

**Comment by ChadFulton** [comment]
Please post a code sample, it's not clear to me what you're trying to do.

**Comment by ikramelmbarki** [comment]
data=pd.read_excel("drive/My Drive/Resultat.xls",index_col='Date d’engagement',parse_dates=True)
data=data.sort_index(axis=0)
from statsmodels.tsa.seasonal import seasonal_decompose
result = seasonal_decompose(data_test['Montant engagé'])
result.plot();
![image](https://user-images.githubusercontent.com/57155043/83983180-269d9600-a924-11ea-8343-0c11b3ab5535.png)

and when i try to change the frequency 
data.index.freq = 'Y'
i get an error

**Comment by ikramelmbarki** [comment]
this it the date(index)vs the target
![image](https://user-images.githubusercontent.com/57155043/83983201-577dcb00-a924-11ea-9b6e-6ff144c87372.png)

**Comment by ChadFulton** [comment]
1. Your data does not have a frequency and you cannot give it a frequency, because it has multiple observations at the same dates (for example, on 10/18/2011 there are two observations). 

2. You may want to read the Pandas documentation on time series objects (https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#overview) to understand what a frequency is.  In particular, you said above that you tried to set `data.index.freq = 'Y'`, which would correspond to one observation each year. I don't think that's what you want.

**Comment by ChadFulton** [comment]
Closing because this does not appear to be a bug in Statsmodels.

**Comment by ikramelmbarki** [comment]
> 1. Your data does not have a frequency and you cannot give it a frequency, because it has multiple observations at the same dates (for example, on 10/18/2011 there are two observations).
> 2. You may want to read the Pandas documentation on time series objects (https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#overview) to understand what a frequency is.  In particular, you said above that you tried to set `data.index.freq = 'Y'`, which would correspond to one observation each year. I don't think that's what you want.

if the data has no frequency so i can't apply the time series algorithms to forecast? what should i do to forecast the future? split it to year,day,month..

**Comment by bashtage** [comment]
You can treat is regular in observation space by replacing the index with a RangeIndex(0, len(y)). Alternatively, you could aggregate it to an actual frequency, e.g., daily, and then model the aggregated series.

**Comment by ikramelmbarki** [comment]
> You can treat is regular in observation space by replacing the index with a RangeIndex(0, len(y)). Alternatively, you could aggregate it to an actual frequency, e.g., daily, and then model the aggregated series.

can you give me a practical example please
