### ISSUE TITLE
What's the meaning of the result of grangercausalitytests?

### ISSUE THREAD

**Issue by lk337** [statsmodels/statsmodels#6795]
When I use statsmodels' grangercausalitytests, the result is like this:
gc_res2 = grangercausalitytests(data, 10)

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=28.7248 , p=0.0000  , df_denom=198, df_num=1
ssr based chi2 test:   chi2=29.1600 , p=0.0000  , df=1
likelihood ratio test: chi2=27.2295 , p=0.0000  , df=1
parameter F test:         F=28.7248 , p=0.0000  , df_denom=198, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=18.9880 , p=0.0000  , df_denom=195, df_num=2
ssr based chi2 test:   chi2=38.9498 , p=0.0000  , df=2
likelihood ratio test: chi2=35.5873 , p=0.0000  , df=2
parameter F test:         F=18.9880 , p=0.0000  , df_denom=195, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=13.5015 , p=0.0000  , df_denom=192, df_num=3
ssr based chi2 test:   chi2=41.9812 , p=0.0000  , df=3
likelihood ratio test: chi2=38.0914 , p=0.0000  , df=3
parameter F test:         F=13.5015 , p=0.0000  , df_denom=192, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=10.9646 , p=0.0000  , df_denom=189, df_num=4
ssr based chi2 test:   chi2=45.9467 , p=0.0000  , df=4
likelihood ratio test: chi2=41.3192 , p=0.0000  , df=4
parameter F test:         F=10.9646 , p=0.0000  , df_denom=189, df_num=4

I use command: gc_res2 = grangercausalitytests(data, 4)

The x1 and x2 in data have passed the ADF test, which show that they are both stationary.
What I want to ask is, how to understand the output(the result)?
for example, in number of lags (no zero) 4,
ssr based F test:         F=10.9646 , p=0.0000  , df_denom=189, df_num=4
does it mean that X2(t-4)'s impact to X1(t)  is none because the p value < 0.05 and the coefficient of  X2(t-4) to X1(t) is zero ? ( base on F test )
If I want to say, X2 is the granger causeto X1, the  p value in all numbers of lags should be < 0.05 or 0.01(fixed before do this test), right? and if anyone of (numbers of lags 1, or 2 or 31, or any ) these's p value > fixed value, we shouldn't reject the null hypothesis that X2 isn't the granger causeto X1, right?
I'm not sure whether my understanding is right...

**Comment by josef-pkt** [comment]
The test is that the (cross-effect) coefficients for **all** lags up to provided maxlag are jointly zero.

So rejecting with 4 lag, means that at least one of the 4 lag coefficients of x2 on x1 is significantly different from zero. It's a joint F or Chisquare test and not a test for one individual coefficient.

Choosing the number of lags in the general case is not easy. (I don't remember rules or recommendations for granger causality.)
It should be large enough to capture possible non-zero coefficients, but if it's too large, then the test looses power.

**Comment by lk337** [comment]
> The test is that the (cross-effect) coefficients for **all** lags up to provided maxlag are jointly zero.
> 
> So rejecting with 4 lag, means that at least one of the 4 lag coefficients of x2 on x1 is significantly different from zero. It's a joint F or Chisquare test and not a test for one individual coefficient.
> 
> Choosing the number of lags in the general case is not easy. (I don't remember rules or recommendations for granger causality.)
> It should be large enough to capture possible non-zero coefficients, but if it's too large, then the test looses power.

Thanks very much!
So, in the example I gave, X2 is the granger cause to X1, right? Because the p value<0.05 (fixed), I should reject the hypothesis that X2 is not the granger cause to X1. The result of "number of lags (no zero) 4"  stands for the test result for X2(t-1~t-4) to X1(t) 【not X2(t-4) to X1(t)】, and p<0.05 situation means that  at least someone of X2(t-1~t-4)'s coefficient of x2 on x1 is significantly different from zero.

Is my understanding true?

**Comment by lk337** [comment]
> The test is that the (cross-effect) coefficients for **all** lags up to provided maxlag are jointly zero.
> 
> So rejecting with 4 lag, means that at least one of the 4 lag coefficients of x2 on x1 is significantly different from zero. It's a joint F or Chisquare test and not a test for one individual coefficient.
> 
> Choosing the number of lags in the general case is not easy. (I don't remember rules or recommendations for granger causality.)
> It should be large enough to capture possible non-zero coefficients, but if it's too large, then the test looses power.

Thanks very much!
So, in the example I gave, X2 is the granger cause to X1, right? Because the p value<0.05 (fixed), I should reject the hypothesis that X2 is not the granger cause to X1. The result of "number of lags (no zero) 4" stands for the test result for X2(t-1,t-2,t-3,t-4) to X1(t) [ not X2(t-4) to X1(t) ], and p<0.05 situation means that at least someone of X2(t-1,t-2,t-3,t-4)'s coefficient of x2 on x1 is significantly different from zero.

Is my understanding true?

**Comment by josef-pkt** [comment]
Yes, this is correct.

I'm closing this issue because there is no action required. 
If you have more questions or comments, then you can continue in this issue.

**Comment by lk337** [comment]
OK, thanks!

> Yes, this is correct.
> 
> I'm closing this issue because there is no action required.
> If you have more questions or comments, then you can continue in this issue.
