### ISSUE TITLE
how to run a glm func without a DeprecationWarning？

### ISSUE THREAD

**Issue by gangao** [statsmodels/statsmodels#6807]
hello， 
Following is my code, and what i want is to use a freq_weights in logit regression.
I find a method to do that which is using a GLM function as the code shows.
The code runs successfully but throws up a Deprecation Warning. (DeprecationWarning: Calling Family(..) with a link class as argument is deprecated.)
How to get rid of this warning? Thanks a lot.

```
import statsmodels.api as sm
spector_data = sm.datasets.spector.load_pandas()
x_var = spector_data.exog
x_var = sm.add_constant(x_var)
x_var['wt'] = x_var.apply(lambda x: np.random.randint(1,10), axis=1)
model = sm.GLM(spector_data.endog,  x_var.iloc[:, x_var.columns != 'wt'], \
               family=sm.families.Binomial(sm.families.links.logit), freq_weights=x_var['wt'])
```

**Comment by josef-pkt** [comment]
add parenthesis to create a logit link instance, instead of using the class itself

`family=sm.families.Binomial(sm.families.links.logit()`

**Comment by gangao** [comment]
> add parenthesis to create a logit link instance, instead of using the class itself
> 
> `family=sm.families.Binomial(sm.families.links.logit())`

It works!! Many thanks~

**Comment by accolombini** [comment]
Excelent!
But in this case:
family=sm.families.NegativeBinomial(sm.genmod.families.links.log))
Deprecation Warning. (DeprecationWarning: Calling ...
Can you help me?

**Comment by accolombini** [comment]
It worked for me
family=sm.families.NegativeBinomial(sm.families.links.log()))
