### ISSUE TITLE
Out-of-sample likelihood of UnobservedComponents models

### ISSUE THREAD

**Issue by alexpghayes** [statsmodels/statsmodels#6814]
Hey there. My end goal is to evaluate the stationarity of a time series by comparing the likelihood of a white noise process (i.e. `UnobservedComponents` model with `level = 'deterministic constant'`) and a plausible non-stationary model for the same series, in my case either a local level model or a random walk.

I would like to do this by computing an out-of-sample likelihood ratio statistic, if possible using the same sort of recursive forecasting as outlined in https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_forecasting.html. However, instead of using RMSE as my score function, I want to use log-likelihood, for increased statistical efficiency. 

Given that `get_forecast()` allows me to compute a confidence interval, I presume that there is some built-in machinery I can leverage to calculate the predictive likelihood of a point forecast as opposed to its RMSE. Any pointers on how to do this would be appreciated; there's a lot happening in the `statespace` module and I haven't quite grasped how the classes work just yet.

Here's a short example demonstrating an in-sample likelihood calculation. If you can point out how to calculate the predictive likelihood on `test` that would be ideal!

``` python
import statsmodels.api as sm
import pandas as pd

sunspots = sm.datasets.sunspots.load_pandas().data

sunspots.columns = ['year', 'activity']
sunspots.year = pd.to_datetime(sunspots.year, format='%Y')

sunspots = sunspots.set_index('year').asfreq('AS')

train = sunspots.query('year < 2000')
test = sunspots.query('year >= 2000')

estimator = sm.tsa.UnobservedComponents(
    endog=train.activity,
    level='deterministic constant'
)

estimates = estimator.fit(method='powell', disp=False)

# in-sample likelihood on train
print(estimates.llf)
>>> -1532.6247359972863
```

**Comment by ChadFulton** [comment]
It sounds like you want to evaluate the likelihood of the test sample using the parameters estimates from the training sample, is that right? If so, then you can use the `extend` method from the results class:

```python
mod = sm.tsa.UnobservedComponents(train, ...)
res_train = mod.fit()
res_test = res.extend(test)
print(res_test.llf)
```

Note that in computing the log-likelihood for the test sample, this uses two pieces of information from the training sample: (1) the estimated parameters, and (2) the estimate of the unobserved state vector at the end of the training sample.

**Comment by alexpghayes** [comment]
Wonderful, thank you!

**Comment by ChadFulton** [comment]
Glad to help!

Also, I should mention that if you only want to evaluate the test sample on the parameters but *not* on the estimate of the unobserved state vector at the end of the training sample, then you can use the `apply` method in place of `extend`:

```python
mod = sm.tsa.UnobservedComponents(train, ...)
res_train = mod.fit()
res_test = res.apply(test)
print(res_test.llf)
```
