### ISSUE TITLE
Different results for linear regression based on conda environment

### ISSUE THREAD

**Issue by jdjame** [statsmodels/statsmodels#6815]
# Summary:
 I have noticed different results of the parameters I get as output when running simple linear regression (with ordinary least squares) on the qiime conda environment and other conda environments. I came across this issue when I ran code in a conda environment and got drastically different results than when I ran it in other conda environments. I am curious to know if anyone can give me a reason for this difference 
# Specifics: 
The two environments used were a qiime2-2020.2 environment (python 3.6.7, ```statsmodels==0.11.1```, ```scikit-learn==0.22.1```, and ```numpy===1.18.1```) and a standard  base conda environment (python 3.7.4, ```statsmodels==0.11.1```, ```scikit-learn==0.21.3```, and ```numpy===1.17.2```). My issue is that in the qiime environment, both statsmodels.api.OLS and sklearn.linear_model.LinearRegression give different values when fitted on the same input.  
# Sample code 
The following is some code that I use to observe the differenced in both. Here, *x.csv* is a csv of the design matrix used to fit and and *y.csv* is a csv of the response variable. The aim is for the code to fit 14 parameters (using ordinary least squares) on 303 samples. 
```
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd 
x= pd.read_csv("x.csv", delimiter=',',encoding='utf-8',index_col=0,low_memory=False)
y=pd.read_csv("y.csv", delimiter=',',encoding='utf-8',index_col=0,low_memory=False)
model = sm.OLS(y,x) res = model.fit()
print(res.params)
model=LinearRegression(fit_intercept=False).fit(x,y) print(model.coef_)
print((abs(res.params -model.coef_[0]).sum()))
``` 
# Results 
So right off the bat, we get different results when running this script the qiime environment and the base environment. The difference in the two is quite significant (for some parameters, the solutions differ by up to 27 orders of magnitude). When I looked into this further, it seems that all other environments I have run this script on have the same output as the base environment. Furthermore, within these agreeing environments, the sum of the absolute differences between the parameters estimated through sklearn and statsmodels is never greater that 1e-14 which is expected. However, in the qiime environment, this sum of differences is ~0.60. Recap:
| package\env                                                       | qiime  | base   |
|-------------------------------------------------------------------|--------|--------|
| python                                                            | 3.7.4  | 3.6.7  |
| pandas                                                            | 0.25.1 | 0.25.3 |
| scikit-learn                                                      | 0.22.1 | 0.21.3 |
| statsmodels                                                       | 0.11.1 | 0.11.1 |
| numpy                                                             | 1.17.2 | 1.18.1 |
| difference between statsmodels estimate  and scikit-lean estimate | .60    | 1e-14  |

 # Question 
I would welcome any explanation for the discrepancy between the **qiime** environment and the other conda environments. I am curious to know if this is an effect of the python version I am using or something completely different.

**Comment by bashtage** [comment]
Are the statsmodels parameters consistent across the two environments?

**Comment by bashtage** [comment]
statsmodels depends on NumPy which in turn depends on a blas library. In most conda environments blas is provided by MKL (Intel).  Can you tell if the MKL libraries are different?

**Comment by josef-pkt** [comment]
What are condition number and smallest eigenvalues in the dataset `x`?

Numerical noise in the underlying linalg libraries should only be relevant in ill conditioned cases.
(AFAIR statsmodels uses numpy.linalg. and sklearn used scipy.linalg. )

your sklearn version differs across environments.
Compare params across environments also for sklearn.

**Comment by jdjame** [comment]
@bashtage They were different. The base environment was running blas 1.0 whereas the qiime environment was running blas 2.12. I updated the blas package in the base environment and now I see the same results in both environments. 
Now my question is how do I know which parameters are "correct"? Just because there is a package update doesn't mean that the true minimizing parameters should change this drastically right?
Thanks for your help!

**Comment by bashtage** [comment]
In most cases, the latest blas should provide the most accurate results.  If you have doubt you could compute the coefficients using different methods: `np.linalg.solve(x.T@x, x.T@y)`, `np.linalg.lstsq(x,y)`, `np.linalg.pinv(x) @ y`.  These may use different parts of the blas library and so any meaningful differences (outside of numerical noise) provide a hint that the blas is bugged.

Blas libraries try hard to be fast, and sometimes make optimization mistakes. IN either case, you should install mkl in condo environments as this has performance at least as good as OpenBLAS and has had fewer issues in recent memory.
