### ISSUE TITLE
BUG: error in append for ARIMA model with trend

### ISSUE THREAD

**Issue by Beich2010** [statsmodels/statsmodels#6816]
#### Describe the bug

ARIMA strange behavior depending on order of d. Am I completely wrong that it should work in both cases ? It casts origin_exog  to another size so size of feature does not fit anymore.
 

#### Code Sample, a copy-pastable example if possible

<details>

import pandas as pd
import statsmodels.api as sm
from pandas._libs.tslibs.timestamps import Timestamp

def forecast_with_arima(ar=1, d=0, ma=0):
    train = pd.DataFrame({'to_forecast': {Timestamp('2014-01-01 02:00:00'): 10.0, Timestamp('2014-01-02 02:00:00'): 5.8,
                                          Timestamp('2014-01-03 02:00:00'): 7.8,
                                          Timestamp('2014-01-04 02:00:00'): 8.8}})
    test = pd.DataFrame({'to_forecast': {Timestamp('2014-01-05 02:00:00'): 5.7, Timestamp('2014-01-06 02:00:00'): 7.9,
                                         Timestamp('2014-01-07 02:00:00'): 9.9, Timestamp('2014-01-08 02:00:00'): 8.8}})

    train.index = pd.DatetimeIndex(train.index.values, freq=train.index.inferred_freq)
    test.index = pd.DatetimeIndex(test.index.values, freq=test.index.inferred_freq)

    train.loc[(train.index >= '1-01-2013 02:00:00'), 'feature'] = 1
    test.loc[(test.index >= '1-01-2013 02:00:00'), 'feature'] = 1

    results = sm.tsa.arima.ARIMA(
        train['to_forecast'],
        exog=train[['feature']],
        order=(ar, i, ma)).fit()

    forecast = results.append(test['to_forecast'], exog=test[['feature']], refit=False)
    test['hat'] = forecast.fittedvalues

if __name__ == '__main__':
    print("Start forecast with i=1")
    # this works
    forecast_with_arima(d=1)
    print("forecast with i=1 done")

    print("Start forecast with i=0")
    # this not
    forecast_with_arima(d=0)
    print("forecast with i=0 done")

</details>

#### Expected Output

Works with d = 1 but not with d = 0.
My expectation would be it should work in both cases.

#### Real Output

Start forecast with d=1
forecast with d=1 done
Start forecast with d=0
Traceback (most recent call last):
  File "/home/user/Dokumente/folder/bug_statsmodels/statsmodels_bug.py", line 39, in <module>
    forecast_with_arima(d=0)
  File "/home/user/Dokumente/folder/bug_statsmodels/statsmodels_bug.py", line 25, in forecast_with_arima
    forecast = results.append(test['to_forecast'], exog=test[['feature']], refit=False)
  File "/home/user/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 3665, in append
    allow_mix=True)
  File "/home/user/anaconda3/lib/python3.7/site-packages/statsmodels/tsa/statespace/tools.py", line 319, in concat
    raise ValueError('Columns must match to concatenate along'
ValueError: Columns must match to concatenate along rows.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.7.6.final.0
OS: Linux 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64
byteorder: little
LC_ALL: None
LANG: de_DE.UTF-8

statsmodels
===========

Installed: 0.11.1 (/home/user/anaconda3/lib/python3.7/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.20 (/home/user/anaconda3/lib/python3.7/site-packages/Cython)
numpy: 1.18.5 (/home/user/anaconda3/lib/python3.7/site-packages/numpy)
scipy: 1.4.1 (/home/user/anaconda3/lib/python3.7/site-packages/scipy)
pandas: 1.0.1 (/home/user/anaconda3/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.1 (/home/user/anaconda3/lib/python3.7/site-packages/dateutil)
patsy: 0.5.1 (/home/user/anaconda3/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.2.2 (/home/user/anaconda3/lib/python3.7/site-packages/matplotlib)
    backend: Qt5Agg 
cvxopt: Not installed
joblib: 0.15.1 (/home/user/anaconda3/lib/python3.7/site-packages/joblib)

Developer Tools
================

IPython: 7.15.0 (/home/user/anaconda3/lib/python3.7/site-packages/IPython)
    jinja2: 2.11.2 (/home/user/anaconda3/lib/python3.7/site-packages/jinja2)
sphinx: 3.1.1 (/home/user/anaconda3/lib/python3.7/site-packages/sphinx)
    pygments: 2.6.1 (/home/user/anaconda3/lib/python3.7/site-packages/pygments)
pytest: 5.4.3 (/home/user/anaconda3/lib/python3.7/site-packages/pytest)
virtualenv: Not installed

</details>

**Comment by bashtage** [comment]
`exog` is not transformed and so must have the correct size when differencing (d=1) and not (d=0).  You are most likely 1 observation short.

**Comment by Beich2010** [comment]
Thank you for the quick answer, but i don't understand your point. Why the columns do not fit. I thought isn't about the numbers of observations it's about the columns which are not identical.
![screenshot](https://user-images.githubusercontent.com/25321403/85425610-ae68de80-b579-11ea-8531-09aaa4ef75f6.png). Here the new exog is compared with the old one of the model and it has an 'const' column now. Where does it come from? The error is raised in the line below.

**Comment by bashtage** [comment]
const comes from `trend="c"` which is the default. You are passing `exog=train[['feature']]` in your constructor.

**Comment by bashtage** [comment]
Can you post a complete, runnable exam that reproduces the issue? Feel free to simulate your training data.

**Comment by Beich2010** [comment]
```python
import pandas as pd
import statsmodels.api as sm
from pandas._libs.tslibs.timestamps import Timestamp


def forecast_with_arima(ar=1, d=0, ma=0):

    train = pd.DataFrame({'to_forecast': {Timestamp('2014-01-01 02:00:00'): 10.0, Timestamp('2014-01-02 02:00:00'): 5.8,
                                          Timestamp('2014-01-03 02:00:00'): 7.8,
                                          Timestamp('2014-01-04 02:00:00'): 8.8}})

    test = pd.DataFrame({'to_forecast': {Timestamp('2014-01-05 02:00:00'): 5.7, Timestamp('2014-01-06 02:00:00'): 7.9,
                                         Timestamp('2014-01-07 02:00:00'): 9.9, Timestamp('2014-01-08 02:00:00'): 8.8}})

    train.index = pd.DatetimeIndex(train.index.values, freq=train.index.inferred_freq)
    test.index = pd.DatetimeIndex(test.index.values, freq=test.index.inferred_freq)

    train.loc[(train.index >= '1-01-2013 02:00:00'), 'feature'] = 1
    test.loc[(test.index >= '1-01-2013 02:00:00'), 'feature'] = 1


    results = sm.tsa.arima.ARIMA(
        train['to_forecast'],
        exog=train[['feature']],
        order=(ar, d, ma)).fit()

    forecast = results.append(test['to_forecast'], exog=test[['feature']], refit=False)
    test['hat'] = forecast.fittedvalues


if __name__ == '__main__':
    print("Start forecast with d=1")
    # this works
    forecast_with_arima(d=1)
    print("forecast with d=1 done")

    print("Start forecast with d=0")
    # this not
    forecast_with_arima(d=0)
    print("forecast with d=0 done")



```

this should be completly runnable, it gives the same error as shown in first comment. The training and test data are already randomly chosen and reproduce the error.

**Comment by ChadFulton** [comment]
Thanks @bashtage and @Beich2010 for looking into this!  It looks like for the `ARIMA` model, the `append` procedure has mixed up the input `exog` array that the user gave with the augmented `exog` array that includes the `trend` term.

This only shows up here for the d=0 case because the default is `trend='c'` for d=0, and `trend='n'` for d>0.
