### ISSUE TITLE
Note rather than warn about heteroscedastic-robust standard errors in regression summary

### ISSUE THREAD

**Issue by MaxGhenis** [statsmodels/statsmodels#6821]
#### Is your feature request related to a problem? Please describe
Specifying heteroscedastic-robust errors doesn't warrant a warning in my view:
![image](https://user-images.githubusercontent.com/6076111/85773608-e3d50f80-b6d2-11ea-8a54-e95e9dcabf7f.png)

I understand that this is for equivalence with non-robust standard errors:
![image](https://user-images.githubusercontent.com/6076111/85774835-159aa600-b6d4-11ea-8f83-4ed3bad4e6bb.png)

#### Describe the solution you'd like
Make this a note rather than a warning, at least for robust (if not for non-robust as well).

#### Describe alternatives you have considered
None

#### Additional context
N/A

**Comment by josef-pkt** [comment]
That's a bug. The warning note should show up only for nonrobust cov_type.
If the users chooses a robust cov_type, then we should assume they know what they are doing.

**Comment by josef-pkt** [comment]
I misunderstood. It's not a bug. The message is correct.

The main reason I added it was as "educational tool" given that robust standard errors are not very common outside of economics and a very few other fields

**Comment by josef-pkt** [comment]
But still, the message is not really necessary for robust cov_types

**Comment by bashtage** [comment]
I agree that warning is the wrong term.
