### ISSUE TITLE
holtwinters SimpleExpSmoothing's out-of-sample  forcast calculations are wrong

### ISSUE THREAD

**Issue by royqh1979** [statsmodels/statsmodels#6823]
#### Describe the bug

In the [statsmodels tutorial](https://www.statsmodels.org/stable/examples/notebooks/generated/exponential_smoothing.html#Simple-Exponential-Smoothing), the out-of-sample  forecast values of "Simple Exponential Smoothing" are wrong.  

In the tutorial, three different fitted models is used to  forecast out-of-sample values. In each forecast , the fitted model will forecast 3 out-of-sample values, but the 3 values is the same. This can be seen clearly in **[the tutorial's plot](https://www.statsmodels.org/stable/_images/examples_notebooks_generated_exponential_smoothing_6_0.png)**, the last three dots of the same color will form a horizontal line.

And if you try the codes in the tutorial, you will find whatever value n you fill in the forecast() method, it will only return n same values. So it must be wrong.

**Comment by bashtage** [comment]
SES forecasts are always the same  value for any horizon. These three only differ since the model's smoothing parameter differs.

**Comment by theadammurphy** [comment]
This seems like quite an unhelpful forecasting model then. Is there any way to make forecasts with this (or another smoothing type) model that produces different values? I'm thinking one that can be fed the most recent value of the validation set and use it to update its prediction?

**Comment by bashtage** [comment]
> Is this because it is a linear model and supposed to be built on stationary data?

No. It is because this is a fundamental property of SES which is an integrated MA(1), and so all forecasts are the same. 

> Is there any way to make forecasts with this (or another smoothing type) model that produces different values? I'm thinking of one that can be fed the most recent value of the validation set and use it to update its prediction?

The forecasts differ based on the data.  The only sense that they are the same is that the time-t forecast for period t+h is the same value for all h>=1.  If you update to time t+1 with new data, the forecast value changes.

**Comment by theadammurphy** [comment]
Wonderful, thanks!

> If you update to time t+1 with new data, the forecast value changes.

Does statsmodels have a way to do this automatically? For example, it would be great if I could pass in a validation set and have the model make predictions on that. Currently, I am doing it manually.

**Comment by bashtage** [comment]
No, there are no simple methods to train a model and then produce forecasts for a range of test data in a single call.  Some methods, namely the statespace ones, support `append` and `extend` but you still need to loop yourself.

**Comment by theadammurphy** [comment]
That's a shame. Perhaps I am missing something but making forecasts on test data was the reason I turned to statsmodels. Is this functionality planned? Or is it deliberately not included because that isn't the intended use of statsmodels?

**Comment by bashtage** [comment]
You can make forecasts, and forecast/prediction is a feature of models. You just need to loop to do so when you have a test/train split.
