### ISSUE TITLE
STL Decompose with deterministic seasonality

### ISSUE THREAD

**Issue by fgvenegas** [statsmodels/statsmodels#6824]
Hi I wanna know if there is a way to calculate seasonality (with STL decompose from statsmodels.tsa.seasonal.STL) in a deterministic way like it's done in this r package with the parameter s.window: https://www.rdocumentation.org/packages/forecast/versions/8.12/topics/forecast.stl

Greetings.

**Comment by bashtage** [comment]
STL is available. You will have to provide to glue to take the deseasonalized data, then fitting the ARIMA or Exp smoother, and then reseasonalizing.

**Comment by fgvenegas** [comment]
Thanks!
