### ISSUE TITLE
REF: Empirical autocovariance is not unbiased even when dividing by n-k

### ISSUE THREAD

**Issue by freli005** [statsmodels/statsmodels#6833]
There is a flag `unbiased` when computing empirical autocovariance, e.g. here
https://www.statsmodels.org/devel/generated/statsmodels.graphics.tsaplots.plot_acf.html
(I suspect that this plotting function inherits this from some underlying function used to compute the ACF?)

However, the empirical autocovariance function is not unbiased even if we divide by n-k, so I wonder if this option should be removed, or at least renamed? See e.g. page 27 in https://www.stat.pitt.edu/stoffer/tsa4/tsa4.pdf

**Comment by ChadFulton** [comment]
We should do this, thanks for submitting this issue.

**Comment by ChadFulton** [comment]
This will likely need to be deprecated for a couple of versions before the old argument can be removed, since it's been around since this function was first introduced.

**Comment by bashtage** [comment]
Should replace the keyword with something like `df_adjusted`
