### ISSUE TITLE
Problem with p_values in acf functions

### ISSUE THREAD

**Issue by lmsanch** [statsmodels/statsmodels#6851]
I have some code where I want to plot the ac for a times series. The code is the following:
`_ = sm.graphics.tsa.plot_acf(benchmark.momentum_score_d60, lags=30, alpha=0.05)`
Which correctly displays the following graph:
<img width="419" alt="Screen Shot 2020-07-02 at 10 31 05 PM" src="https://user-images.githubusercontent.com/3156487/86425656-bdefd200-bcb3-11ea-8376-a4539bde91a9.png">
However, I need to calculate optimal lags, BIC criteria, and other metrics. For that I need pvalues, qstats, etc. This code should provide the results I need:
`sm.graphics.tsa.acf(benchmark.momentum_score_d60, qstat=True, alpha=0.05, nlags=30)`. 
According to the documentation, it should return:
```
Returns
-------
acf : ndarray
    The autocorrelation function.
confint : ndarray, optional
    Confidence intervals for the ACF. Returned if alpha is not None.
qstat : ndarray, optional
    The Ljung-Box Q-Statistic.  Returned if q_stat is True.
pvalues : ndarray, optional
    The p-values associated with the Q-statistics.  Returned if q_stat is
    True.
```
Which returns:
```
(array([1.        , 0.99263731, 0.97991958, 0.96326654, 0.94356406,
        0.92084753, 0.8962924 , 0.87027724, 0.84317582, 0.81497825,
        0.78597775, 0.75626062, 0.72606524, 0.69560872, 0.66499756,
        0.6343498 , 0.60376057, 0.57324583, 0.54283262, 0.51254813,
        0.48242455, 0.45249685, 0.42279732, 0.39336106, 0.36423607,
        0.33550523, 0.30721426, 0.27940903, 0.25214568, 0.22547554,
        0.19939887]),
 array([[1.        , 1.        ],
        [0.96351037, 1.02176425],
        [0.92971756, 1.0301216 ],
        [0.89884961, 1.02768347],
        [0.86790739, 1.01922074],
        [0.83579121, 1.00590385],
        [0.80316152, 0.98942328],
        [0.77009524, 0.97045925],
        [0.73677315, 0.94957849],
        [0.70305046, 0.92690604],
        [0.66912401, 0.9028315 ],
        [0.63500474, 0.8775165 ],
        [0.60087172, 0.85125875],
        [0.56689237, 0.82432506],
        [0.53313054, 0.79686457],
        [0.49966775, 0.76903184],
        [0.46656717, 0.74095396],
        [0.43381649, 0.71267517],
        [0.40141793, 0.68424731],
        [0.36937658, 0.65571968],
        [0.33770468, 0.62714441],
        [0.30641902, 0.59857468],
        [0.27553514, 0.5700595 ],
        [0.24507263, 0.54164948],
        [0.21506502, 0.51340712],
        [0.18558156, 0.4854289 ],
        [0.15665497, 0.45777355],
        [0.12831886, 0.43049921],
        [0.10061778, 0.40367359],
        [0.07359209, 0.37735898],
        [0.04723171, 0.35156603]]),
 array([ 4464.52560133,  8816.34574993, 13022.43986039, 17059.12437894,
        20904.63031424, 24548.58936272, 27984.84422135, 31211.12733324,
        34225.89824863, 37030.54973742, 39627.70254382, 42022.13159595,
        44220.3806648 , 46229.85825463, 48058.78746581, 49715.94965883,
        51210.16640232, 52550.3365966 , 53745.40756047, 54804.36744442,
        55736.22212537, 56549.94753771, 57254.4662809 , 57858.65433498,
        58371.39912558, 58801.4124155 , 59157.18828419, 59446.98614601,
        59678.77229886, 59860.08597086]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

```
Everything looks fine, but the p-values which is all zeros. I am assuming these outputs should give me all I need to recreate the first chart, but, where are the values represented by the shaded blue area in the graph? Is this a bug or am I missing something?
 
Both statsmodel autocorrelation and pandas autocorrelation functions are adapted from matplotlib, so I don't know if this is a bug in statsmodel or matplotlib, or something is "lost in translation".  Also, I noticed some ambiguity in the definitions, i.e: "returned if **q_stat** is True", but the argument is called **qstat**.

Thanks

**Comment by bashtage** [comment]
The confidence interval is centered around the act, so to get a 0-centered confidence interval, just take 

```
out = act(...)
ci[1] - ci[0][:,None]
```

**Comment by lmsanch** [comment]
@bashtage you said centered around the act. What is act? I think I am missing something. Maybe an example would help. acf[29] is 0.19939887, and the ci for that value is  [0.04723171, 0.35156603]. How can the shaded blue range for acf[29] in the graph can be derived from the values here?

**Comment by bashtage** [comment]
act->acf

```
In [60]: np.array([0.04723171, 0.35156603]) - 0.19939887
Out[60]: array([-0.15216716,  0.15216716])
```

**Comment by lmsanch** [comment]
@bashtage Thanks so much; I was clearly confused.
Cheers!

**Comment by bashtage** [comment]
You are welcome.

**Comment by josef-pkt** [comment]
pvalues are zero or very small because correlation is very large and no correlation is rejected at all lags
