### ISSUE TITLE
ARIMAX: distributed lags of an exogenous variable (question) 

### ISSUE THREAD

**Issue by sanjadzeletovic** [statsmodels/statsmodels#6857]
I am trying to implement the ARIMAX model that includes distributed lags of an exogenous variable, such as:
![CodeCogsEqn](https://user-images.githubusercontent.com/58711198/86604389-510a5f80-bf73-11ea-9103-92ef4985cea1.gif)

Is there a workaround for this approach?

**Comment by bashtage** [comment]
You just make an `exog` array with your lags, and drop any missing observations.


Something like
```
exog = pd.concat([u.shift(i) for i in range(i, p+1)], axis=1)
```

**Comment by sanjadzeletovic** [comment]
Thank you for the reply. Could you please clarify the idea? If I do that, I will be regressing each coefficient of the past exog. lag from the previous Nsample-nlag value?

For example, if my vector of past exogenous values is: [ 10 9 8 7 6 5 4 3 2 1], my array should be:
t-1: [9 8 7 6 5 4 3 2 1]
t-2: [8 7 6 5 4 3 2 1]
t-3: [7 6 5 4 3 2 1]
....

Where the t-i-th coefficient is estimated based on the values of the i-th row? It this is the case, how will it be avoided to include in the t-2 lag the portion explained by the t-1 lag?

**Comment by bashtage** [comment]
Using np.arange(10) as your exog, your exog array, after dropping missing, should look like

```
2 1 0
3 2 1
4 3 2
5 4 3
6 5 4
7 6 5
8 7 6
```

This means that y[9] would be regressed on `8 7 6` plus ARMA terms, y[8] on `7 6 5` and so on.

**Comment by bashtage** [comment]
Closing since there is no action from us. Please feel free to ask questions.
