### ISSUE TITLE
check outdated docstring notes

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#686]
cov_hac says it's only tested for nlag=0

after adding tests, I didn't go through all the docstrings.

This is not just in sandwich_covariances, but also in other `stats` functions

**Comment by jseabold** [comment]
I don't see that the comments in this are still relevant. `compare_j` looks ok, and I didn't notice anything about tests in the sandwich covariances docstrings. Grepping for tests and tested didn't turn up much in the rest of the directory that I noticed.
