### ISSUE TITLE
VAR - How to get one-step ahead static forecast?

### ISSUE THREAD

**Issue by dinhtrang24** [statsmodels/statsmodels#6863]
Hi, I do time series forecasting with VAR model. What I would like to be doing is, training the models with a training data, and use the model to generate one-step static forecast with a test data (take actual values to make next step forecast). So far, my code is shown as follows:

import statsmodels.api as sm
model = sm.tsa.VARMAX(train_data, order=(2, 0), trend='c')
model_result = model.fit(maxiter=1000, disp=False)
model_result.summary()

model_result.forecast(steps=7)

I believe this is a dynamic forecast (take previously forecasted values). Providing that the data is transformed into a stationary series by differencing, how can I use the same model estimated from the training data to try on the new unseen data in order to make 1 step-ahead static forecast?

I realize that it is possible to do that with SARIMAX #2788. Is it possible to do with VAR in a similar way?

**Comment by bashtage** [comment]
I don't think VAR supports producing multiple one-step (or h-step) forecasts with a fixed set of parameters. There is a trick though to simplify it.  

```
res = VAR(y[:ntrain]).fit(1)
mod = VAR(y)
forecasts = mod.predict(res.params)
```

where `forecast[i]` is the 1-step forecast using y[i-1]

**Comment by bashtage** [comment]
I'm going to close since there is no action for us.  VAR needs a top to bottom rewrite to support the more common set of features and API common to time series models.

**Comment by bilgd** [comment]
Hello, I saw the workaround above - however, it only seems to work when there is one lag. If the model I'd like to fit has more than one lag, how would I go about doing this? Thanks for the help!
