### ISSUE TITLE
GLM - On entry to DLASCL parameter number 4 had an illegal value

### ISSUE THREAD

**Issue by eholland6** [statsmodels/statsmodels#6866]
#### Describe the bug

I am attempting to model data using GLM to predict a continuous, non-normal variable. I have attempted to build the model using Gamma, Poisson, and Tweedie, but each time receive the following error message:

ValueError: On entry to DLASCL parameter number 4 had an illegal value

For Gamma I tried using link = log in case there was a divide by 0 error issue propagating somewhere behind the scenes, but that did not resolve the issue.

I saw similar issues with ARIMA and checked my data for NaNs and Infs and did not find any 

#### Code Sample, a copy-pastable example if possible

gamma_model = sm.GLM(y_train, X_train, family=sm.families.Gamma(sm.families.links.log)) 
gamma_results = gamma_model.fit() 

#### Expected Output

I expect the model to fit and then for me to be able to print the summary results

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]
NSTALLED VERSIONS

------------------

Python: 2.7.11.final.0

OS: Linux 2.6.32-754.25.1.el6.x86_64 #1 SMP Wed Nov 20 15:07:26 EST 2019 x86_64

byteorder: little

LC_ALL: en_US.UTF-8

LANG: None

 

Statsmodels

===========

 

Installed: 0.9.0 (/d/ny0726as01/d1/dataiku_installers/dataiku-dss-5.1.7-pyucs2/python.packages/statsmodels)

 

Required Dependencies

=====================

 

cython: Not installed

numpy: 1.15.4 (/d/ny0726as01/d1/dataiku_installers/dataiku-dss-5.1.7-pyucs2/python.packages/numpy)

scipy: 1.1.0 (/d/ny0726as01/d1/dataiku_installers/dataiku-dss-5.1.7-pyucs2/python.packages/scipy)

pandas: 0.23.4 (/d/ny0726as01/d1/dataiku_installers/dataiku-dss-5.1.7-pyucs2/python.packages/pandas)

    dateutil: 2.7.5 (/d/ny0726as01/d1/dataiku_installers/dataiku-dss-5.1.7-pyucs2/python.packages/dateutil)

patsy: 0.5.1 (/d/ny0726as01/d1/dataiku_installers/dataiku-dss-5.1.7-pyucs2/python.packages/patsy)

 

Optional Dependencies

=====================

 

matplotlib: 2.2.3 (/d/ny0726as01/d1/dataiku_installers/dataiku-dss-5.1.7-pyucs2/python.packages/matplotlib)

    backend: module://ipykernel.pylab.backend_inline

cvxopt: Not installed

joblib: Not installed

 

Developer Tools

================

 

IPython: 5.5.0 (/d/ny0726as01/d1/dataiku_installers/dataiku-dss-5.1.7-pyucs2/python.packages/IPython)

    jinja2: 2.10 (/d/ny0726as01/d1/dataiku_installers/dataiku-dss-5.1.7-pyucs2/python.packages/jinja2)

sphinx: Not installed

    pygments: 2.3.1 (/d/ny0726as01/d1/dataiku_installers/dataiku-dss-5.1.7-pyucs2/python.packages/pygments)

nose: Not installed

pytest: Not installed

virtualenv: Not installed
</details>

**Comment by josef-pkt** [comment]
The error message is a nan or inf in the linalg package.
What is not clear is whether the nan or inf or whether it is created during the computation.

Does it raise in `fit`?
Do you get any zero division or similar numerical warning before the linalg error?
Try Gaussian with linear link (default) to see whether it is a link transformation causing problems.
check `np.all(np.isfinite(gamma_model.endog))` and `np.all(np.isfinite(gamma_model.exog))`

You are using an old statsmodels. But if there is a problem with the data, then updating will likely not help.

try other optimizers, for example `gamma_model.fit(method="bfgs", start_irls=0)`

If the inf or nan is created by statsmodels, then this might be a corner case in the domain of the functions. AFAIK, we clip for most of those cases, but possibly not for all

**Comment by bashtage** [comment]
Please use 0.11.1 or master. We no longer support 0.9. You will need to use
Python 3.5 for 0.11.1 or python 3.6 or later for master.

**Comment by bashtage** [comment]
Please let us know if you continue to have problems with the latest release.
