### ISSUE TITLE
fit() and fit_regularized() gives different results

### ISSUE THREAD

**Issue by shifwang** [statsmodels/statsmodels#6898]
#### Describe the bug

Given the documentation, I expect fit() and fit_regularized() to yield same results. But the results are different.

#### Code Sample, a copy-pastable example if possible

```python
import statsmodels.api as sm
model = sm.GLM([0, 1, 4, 2], [[0, 1,1], [0.2, 2,1], [-1, 3,1], [-1, 2,1]],
               family=sm.families.Poisson(), opt_method='irls')

print(model.fit().predict( [[0, 1,1], [0.2, 2,1], [-1, 3,1], [-1, 2,1]]))

print(model.fit_regularized().predict( [[0, 1,1], [0.2, 2,1], [-1, 3,1], [-1, 2,1]]))
```

#### Expected Output

The two results should be the same but I see:

```python
[0.31715408 0.73570493 4.31715408 1.6299869 ]
[0.34102418 0.68779369 4.1954308  1.77598756]
```

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

INSTALLED VERSIONS
------------------
Python: 3.7.7.final.0
OS: Linux 5.3.0-1019-aws #21~18.04.1-Ubuntu SMP Mon May 11 12:33:03 UTC 2020 x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8

statsmodels
===========

Installed: 0.11.1 (/home/ubuntu/anaconda3/lib/python3.7/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.15 (/home/ubuntu/anaconda3/lib/python3.7/site-packages/Cython)
numpy: 1.18.1 (/home/ubuntu/anaconda3/lib/python3.7/site-packages/numpy)
scipy: 1.4.1 (/home/ubuntu/anaconda3/lib/python3.7/site-packages/scipy)
pandas: 1.0.3 (/home/ubuntu/anaconda3/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.1 (/home/ubuntu/anaconda3/lib/python3.7/site-packages/dateutil)
patsy: 0.5.1 (/home/ubuntu/anaconda3/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.2.2 (/home/ubuntu/anaconda3/lib/python3.7/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 0.14.1 (/home/ubuntu/anaconda3/lib/python3.7/site-packages/joblib)

Developer Tools
================

IPython: 7.13.0 (/home/ubuntu/anaconda3/lib/python3.7/site-packages/IPython)
    jinja2: 2.11.1 (/home/ubuntu/anaconda3/lib/python3.7/site-packages/jinja2)
sphinx: 2.4.4 (/home/ubuntu/anaconda3/lib/python3.7/site-packages/sphinx)
    pygments: 2.6.1 (/home/ubuntu/anaconda3/lib/python3.7/site-packages/pygments)
pytest: 5.4.1 (/home/ubuntu/anaconda3/lib/python3.7/site-packages/pytest)
virtualenv: Not installed

**Comment by kshedden** [comment]
It's not converging.  It you use maxiter=300 you will get identical results.  We should give a convergence warning.

**Comment by kshedden** [comment]
There is a convergence warning in the current master.  But I don't get a warning with version 0.11.1.  So this must have been fixed at some point.

**Comment by shifwang** [comment]
I see. Thank you!
