### ISSUE TITLE
Issues with docstring example of OaxacaBlinder

### ISSUE THREAD

**Issue by croth1** [statsmodels/statsmodels#6899]
https://github.com/statsmodels/statsmodels/blob/1212616d27ab820d303377f0bcf421cd3f46c289/statsmodels/stats/oaxaca.py#L95-L103

This piece of documentation seems to have a couple of problems:

- `data = sm.datasets.ccards.load()` -> `data = sm.datasets.ccard.load()`
- `sm.OaxacaBlinder` does not seem to be valid way to access `OaxacaBlinder` for me.
- `sm.OaxacaBlinder(df.endog, df.exog, 3, hasconst = False)`: `df` -> `data`

This worked for me:

```python
>>> import numpy as np 
>>> from statsmodels.stats.oaxaca import OaxacaBlinder

>>> data = sm.datasets.ccard.load() 

>>> model = OaxacaBlinder(data.endog, data.exog, 3, hasconst = False) 
>>> model.two_fold().summary() 
```

Also note that the output in the [documentation](https://www.statsmodels.org/stable/generated/statsmodels.stats.oaxaca.OaxacaBlinder.html) renders strangely:

![image](https://user-images.githubusercontent.com/15384900/88033010-1130a400-cb3f-11ea-9be2-aa18ddc59ba8.png)

xref: https://stackoverflow.com/questions/62995753/modules-missisng-in-statsmodels-python-oaxacablinder

**Comment by bashtage** [comment]
Fixed in master. Thanks.
