### ISSUE TITLE
BUG: AdditiveGamSmoother.transform fails for 1-D arrays

### ISSUE THREAD

**Issue by badge** [statsmodels/statsmodels#6916]
#### Describe the bug

Passing a 1-D numpy array, or a pandas DataFrame or Series as the `x` parameter to `BSplines` succeeds in returning a `BSplines` instance, but then fails to transform the same `x` when passed as the argument to `BSplines.transform`

#### Code Sample

```python
import numpy as np
import pandas as pd
from statsmodels.gam.smooth_basis import BSplines

x = np.linspace(0, 1, 100)
df = pd.DataFrame(dict(x1=x, x2=x))

splines = BSplines(x, [6], [3])
splines.transform(x)

df_splines = BSplines(df, [6, 6], [3, 3])
df_splines.transform(df)

series_splines = BSplines(df["x1"], [6], [3])
series_splines.transform(df["x1"])
```
- A 1-D ndarray raises `IndexError: too many indices for array`
- A DataFrame raises `TypeError: '(slice(None, None, None), 0)' is an invalid key`
- A Series raises `ValueError: Can only tuple-index with a MultiIndex`

#### Expected Output

Transformed arrays

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>
INSTALLED VERSIONS
------------------
Python: 3.7.5.final.0

statsmodels
===========

Installed: 0.11.1

Required Dependencies
=====================

cython: 0.29.21
numpy: 1.18.5
scipy: 1.5.0
pandas: 0.25.3
    dateutil: 2.8.1
patsy: 0.5.1

Optional Dependencies
=====================

matplotlib: 3.2.2
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 0.16.0

Developer Tools
================

IPython: 7.16.1
    jinja2: 2.11.2
sphinx: 3.1.2
    pygments: 2.6.1
pytest: 5.4.3
virtualenv: 16.7.8

</details>

**Comment by bashtage** [comment]
Seems to be a bug.

**Comment by josef-pkt** [comment]
Most of the transform handling is done in GAM and GAMResults classes.
AFAIR, we didn't check the spline classes much for standalone usage.

GLMGamResults. predict uses GLMGamResults._tranform_predict_exog for transform handling.
I don't see any reshape there for 1-D.  (might be also a bug, or a different behavior)
