### ISSUE TITLE
AR model returns only NaNs as out-of-sample predictions

### ISSUE THREAD

**Issue by gcompagnoni** [statsmodels/statsmodels#6918]
#### Describe the bug

With a simple AR model, making predictions for points outside the sample values yields only NaNs.
Trying to predict only in-sample points works correctly.
Similar code with different data works correctly, suggesting that something is amiss in the training data; however, I do not understand what.

#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import statsmodels.tsa.api as tsa

hours = pd.period_range(start='2020/06/17 23', end='2020/07/01 23', freq='H').strftime(
    '%Y/%m/%d %H')
income = [20, 0, 0, 0, 0, 0, 5, 5, 50, 90, 0, 80, 120, 145, 30, 55, 40, 85, 95, 130, 70, 20, 70,
          100, 80, 0, 0, 0, 0, 0, 0, 25, 0, 0, 20, 75, 70, 190, 20, 90, 245, 110, 170, 85, 110, 140,
          0, 0, 40, 10, 40, 0, 0, 0, 80, 0, 0, 60, 60, 110, 125, 70, 115, 110, 100, 40, 50, 80, 80,
          200, 10, 0, 100, 0, 50, 0, 0, 0, 0, 0, 0, 50, 65, 100, 80, 20, 20, 40, 50, 30, 125, 140,
          20, 100, 80, 0, 0, 0, 0, 0, 0, 0, 5, 40, 120, 120, 30, 30, 0, 20, 20, 115, 110, 0, 255,
          10, 80, 0, 60, 70, 50, 0, 0, 0, 0, 0, 0, 25, 35, 10, 20, 0, 0, 50, 70, 115, 50, 110, 25,
          170, 20, 60, 25, 0, 45, 20, 0, 0, 0, 0, 10, 70, 40, 100, 50, 5, 100, 20, 60, 20, 10, 115,
          195, 115, 110, 70, 0, 0, 0, 50, 5, 20, 0, 5, 170, 130, 55, 50, 0, 0, 150, 140, 90, 80, 50,
          20, 80, 120, 120, 30, 70, 10, 30, 25, 0, 0, 0, 0, 0, 85, 0, 10, 100, 110, 145, 190, 190,
          135, 80, 35, 70, 80, 95, 130, 25, 0, 25, 20, 0, 5, 0, 0, 0, 20, 15, 130, 70, 50, 90, 70,
          90, 160, 80, 60, 160, 60, 30, 50, 50, 50, 40, 10, 0, 0, 0, 0, 20, 20, 10, 60, 30, 0, 50,
          5, 45, 10, 90, 130, 140, 275, 50, 40, 100, 120, 20, 70, 0, 0, 0, 0, 40, 130, 70, 60, 45,
          50, 230, 90, 50, 140, 95, 80, 320, 120, 180, 30, 120, 0, 30, 5, 0, 0, 0, 5, 20, 25, 90,
          40, 0, 40, 10, 140, 30, 20, 60, 165, 105, 75, 30, 30, 120, 0, 50, 40, 10, 40, 5, 0, 40,
          55, 20, 5, 40, 20, 40, 210, 20, 115, 70, 0, 190, 135, 115, 140, 70, 50, 70]

df = pd.Series(income, index=hours)
print('NaN values in training?', df.isna().any())
ar = tsa.AutoReg(df, lags=168, trend='n').fit()
# everything works fine
insample_week = ar.predict(start='2020/06/25 00', end='2020/07/01 23')
print(insample_week)
# all values are NaN
outsample_week = ar.predict(start='2020/07/02 00', end='2020/07/08 23')
print(outsample_week)
# even addings just one hour to the training sample gives only NaNs
one_hour_outsample=ar.predict(start='2020/06/25 00', end='2020/07/02 00')
print(one_hour_outsample)
```

#### Expected Output

The output series should contain valid predictions

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.7.6.final.0
statsmodels
===========
Installed: 0.11.1 (C:\Users\Giovanni\AppData\Local\Programs\Python\Python37\lib\site-packages\statsmodels)
Required Dependencies
=====================
cython: Not installed
numpy: 1.19.0 (C:\Users\Giovanni\AppData\Roaming\Python\Python37\site-packages\numpy)
scipy: 1.5.1 (C:\Users\Giovanni\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy)
pandas: 1.0.5 (C:\Users\Giovanni\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas)
    dateutil: 2.8.1 (C:\Users\Giovanni\AppData\Local\Programs\Python\Python37\lib\site-packages\dateutil)
patsy: 0.5.1 (C:\Users\Giovanni\AppData\Local\Programs\Python\Python37\lib\site-packages\patsy)
Optional Dependencies
=====================
matplotlib: 3.2.2 (C:\Users\Giovanni\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib)
    backend: TkAgg 
cvxopt: Not installed
joblib: 0.15.1 (C:\Users\Giovanni\AppData\Roaming\Python\Python37\site-packages\joblib)
Developer Tools
================
IPython: 7.16.1 (C:\Users\Giovanni\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython)
    jinja2: 2.11.2 (C:\Users\Giovanni\AppData\Local\Programs\Python\Python37\lib\site-packages\jinja2)
sphinx: Not installed
    pygments: 2.6.1 (C:\Users\Giovanni\AppData\Local\Programs\Python\Python37\lib\site-packages\pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by bashtage** [comment]
pandas-dev/pandas#35406 is the culprit.  As a work-around, you can use an int index which means you have to manually compute start and end.


Fix is to use

```
    def attach_dates(self, result):
        squeezed = result.squeeze()
        k_endog = np.array(self.ynames, ndmin=1).shape[0]
        if k_endog > 1 and squeezed.shape == (k_endog,):
            squeezed = np.asarray(squeezed)[None, :]
        # May be zero-dim, for example in the case of forecast one step in tsa
        if squeezed.ndim < 2:
            out = Series(squeezed)
            out.index = self.predict_dates
            return out
        else:
            return DataFrame(result, index=self.predict_dates,
                             columns=self.ynames)
```

**Comment by bashtage** [comment]
I think the easy solution is to call pd.to_datetime on your index to make sure it is a datetime index and then make sure it has a freq of H

**Comment by bashtage** [comment]
This is fixed in master
