### ISSUE TITLE
RLS: Release 0.12

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#6924]
The change log for 0.12 has been merged into master.  If there are no blockers, I would like to have it finalized before the end of August.  

- [ ] Add to JSON
- [x] #6937
- [x] #6926
- [x] #6925
- [x] #6911 
- [x] #6909  
- [x] #6897 
- [x] #6892 
- [x] #6882 
- [x] #6805 superseded by #6925 
- [x] #6801 
- [X] #6774 superseded by #6926 
- [ ] #6769 
- [x] #6649 via #6938
- [x] #6630 
- [x] #6568 Decision needed
- [X] #6791

**Comment by bashtage** [comment]
@ChadFulton @josef-pkt @kshedden could you list any PRs you feel are essential for 0.12?

**Comment by thequackdaddy** [comment]
Do you want to update the version history json file?

**Comment by bashtage** [comment]
I suppose once there is a release then 0.12 will need to go into the site repo.

**Comment by ChadFulton** [comment]
> The change log for 0.12 has been merged into master. If there are no blockers, I would like to have it finalized before the end of August.

Sounds great to me!

> @ChadFulton [...] could you list any PRs you feel are essential for 0.12?

I will do this soon.

I also have one new large PR that I will hopefully create in the next day or so, to get included for the release.

**Comment by josef-pkt** [comment]
#6568 shouldn't go in this release. 
It's a backwards compatibility break that users wouldn't realize if they don't see or ignore warnings.

**Comment by josef-pkt** [comment]
#6791 should still go in, I'm pretty sure the bug fix is correct.

**Comment by josef-pkt** [comment]
I'm out of town and away from computer for the next 4 days.

**Comment by bashtage** [comment]
The docs are close now.  Happy if anyone wants to write highlights now.

**Comment by ChadFulton** [comment]
Looks great, thanks! I will write the following highlights this evening:

- Time Series Analysis: New exponential smoothing models `ETSModel`
- State space models:
    - `DynamicFactorMQ`
    - Computation of the "news"
    - Simulation smoothing via cholesky factor algorithm
    - Chandrasekhar recursions

**Comment by ChadFulton** [comment]
> I will write the following highlights this evening:
> 
> * Time Series Analysis: New exponential smoothing models `ETSModel`
> * State space models:
>   
>   * `DynamicFactorMQ`
>   * Computation of the "news"
>   * Simulation smoothing via cholesky factor algorithm
>   * Chandrasekhar recursions

Done in #6950.

**Comment by bashtage** [comment]
I will rc0 late this evening Europe time or tomorrow morning unless there are any objections.

**Comment by ChadFulton** [comment]
> I will rc0 late this evening Europe time or tomorrow morning unless there are any objections.

Awesome, thanks so much for getting all of this organized.

**Comment by bashtage** [comment]
rc0 is out now

```
pip install statsmodels==0.12.0rc0
```
