### ISSUE TITLE
AttributeError: 'SARIMAX' object has no attribute '_k_trend'

### ISSUE THREAD

**Issue by sumalathaColumbus** [statsmodels/statsmodels#6929]
I built a weekly sales forecasting model using SARIMA. I saved a pkl file and calling from a separate python file to execute the pkl model. it is working fine from my local. But after loading the pkl file and the same python file into remote server, I tried to execute the same. Now I am getting this error. Please suggest me to resolve this. my local spyder version: 3. and the remote server spyder version is 4.0.1

Below is the code of my python to use pkl file.

filename = f'{PATH}/Model/salesForecastModel_weekly.pkl'
model = ARIMAResults.load(filename)
# model = pickle.load(open(filename,'rb'))
print(date_sales)
y = date_sales['sales'].resample('W').mean()
pred_uc = model.get_forecast(steps=54)
pred_sales = pred_uc.predicted_mean

**Comment by bashtage** [comment]
Are the statsmodels versions identical?

**Comment by sumalathaColumbus** [comment]
> Are the statsmodels versions identical?

on my local, it is 0.10.1 and in the remote server, it is 0.11

**Comment by bashtage** [comment]
They must be identical to use pickling.

**Comment by bashtage** [comment]
We make no guarantees that attributes are identical across versions (especially private ones).

**Comment by sumalathaColumbus** [comment]
Thank you so much. it worked.
