### ISSUE TITLE
Unable to install the statsmodels library

### ISSUE THREAD

**Issue by thysw95** [statsmodels/statsmodels#6930]
Hi there. I am experiencing a very annoying problem while trying to install this library.

I have installed all the dependancies, according to the website:
https://www.statsmodels.org/0.9.0/install.html#python-3-5

And i have MS c++ compiler, ms build tools, visual studio 2019 community and the v14 c++ MS compiler installed, along with hopefully the correct version of python. 

When i run "pip install statsmodels", the following error is shown:

(Top)
`ERROR: Command errored out with exit status 1:
   command: 'c:\python27\python.exe' 'c:\python27\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'c:\users\thyswe~1\appdata\local\temp\tmprwqg18'
       cwd: c:\users\thyswe~1\appdata\local\temp\pip-install-nubdl1\statsmodels`

(Bottom)

`error: Command "C:\Users\Thys Wentzel\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -DCYTHON_TRACE_NOGIL=0 -Ic:\users\thyswe~1\appdata\local\temp\pip-build-env-a00olw\overlay\Lib\site-packages\numpy\core\include -Ic:\\users\\thyswe~1\\appdata\\local\\temp\\pip-build-env-a00olw\\overlay\\Lib\\site-packages\\numpy\\core\\include -Ic:\python27\include -Ic:\python27\PC /Tcstatsmodels/tsa/_stl.c /Fobuild\temp.win-amd64-2.7\Release\statsmodels/tsa/_stl.obj" failed with exit status 2`

(I only copied certain sections that looked like it described the error)

Additional information:
 I do have several c++ redistributables installed if a conflict might exist
 I do have cython installed
 I tried installing it through anaconda, to no avail
 Attempting to build the setup.py file from the source code produces the same error
 I am struggling to find the correct .whl version for windows 10 64x that wouldn't cause an incompatibility error 

Can somebody please help?

**Comment by kshedden** [comment]
According to the log you attached, you are using python 2.7.  You need at least python 3.6.

**Comment by thysw95** [comment]
Ok thanks that seems to have been the problem. I did have python 3.7.5 installed as well, but for some reason it was using the outdated version. 

I just did a quick check if the module is being imported properly in a python program and it seems to be working!
