### ISSUE TITLE
statespace MLEModel with 2 dimensional input

### ISSUE THREAD

**Issue by zeina-abuaisheh** [statsmodels/statsmodels#6955]
Hello all,

I have a model which inherits sm.tsa.statespace.MLEModel, the model looks like LocalLinearTrend class with some few changes.
As a first test, I started with one dimensional input (distance), which works fine, Now as a second test I would like to have a 2 dimensional input (x,y) position, but the model doesn't accept 2 dimensional inputs, could you please tell me how this works using sm.tsa.statespace?

Thanks a lot

**Comment by ChadFulton** [comment]
Yes, you should be able to do this, but I'm not sure what you mean by "the model doesn't accept 2 dimensional inputs".

Can you post a code sample?

**Comment by zeina-abuaisheh** [comment]
```
class StateSpaceModel(sm.tsa.statespace.MLEModel):
    def __init__(self, endog):
        # Model order
        k_states = k_posdef = 2

        # Initialize the statespace
        super(StateSpaceModel, self).__init__(
            endog, k_states=k_states, k_posdef=k_posdef,
            initialization='approximate_diffuse',
            loglikelihood_burn=k_states
        )

        # Initialize the matrices
        self.ssm['design'] = np.array([1, 0])
        self.ssm['transition'] = np.array([[1, 1],
                                       [0, 1]])
        self.ssm['selection'] = np.array([[1, 0],
                                         [0, 1]])

        # Cache some indices
        self._state_cov_idx = ('state_cov',) + np.diag_indices(k_posdef)

    @property
    def param_names(self):
        return ['sigma2.measurement', 'sigma2.level', 'sigma2.trend']

    @property
    def start_params(self):
        return [np.std(self.endog), np.std(self.endog), 0]

    def transform_params(self, unconstrained):
        return unconstrained**2

    def untransform_params(self, constrained):
        return constrained**0.5

    def update(self, params, *args, **kwargs):
        params = super(StateSpaceModel, self).update(params, *args, **kwargs)

        # Observation covariance
        self.ssm['obs_cov',0,0] = params[0]

        # State covariance
        self.ssm[self._state_cov_idx] = params[1:]


def model_LDS(observations, model_option = "path"):   
        mod = StateSpaceModel(observations)
        res = mod.fit(disp=False)
```

What I mean here is that observations can only be either the x coordinate or the y coordinate (so the size of observations is Nx1 where N is the number of observations), but I was unable to find a way where I could have both x,y as an input (i.e, Nx2 instead of Nx1)

**Comment by ChadFulton** [comment]
You can easily adapt this model to multiple inputs, but how to do it depends on what the model you have in mind is. The model will automatically handle passing an Nx2 array as the `endog` argument, but you will need change the state space matrices (for example, the design matrix must be 2x2) and potentially add parameters (for example, you will probably need a measurement error term for each variable).

For example, if you wanted a common trend model, you could do:

```python
class StateSpaceModel(sm.tsa.statespace.MLEModel):
    def __init__(self, endog):
        # Model order
        k_states = k_posdef = 2

        # Initialize the statespace
        super(StateSpaceModel, self).__init__(
            endog, k_states=k_states, k_posdef=k_posdef,
            initialization='approximate_diffuse',
            loglikelihood_burn=k_states
        )

        # Initialize the matrices
        self.ssm['design'] = np.eye(2)
        self.ssm['transition'] = np.array([[1, 1],
                                       [0, 1]])
        self.ssm['selection'] = np.array([[1, 0],
                                         [0, 1]])

        # Cache some indices
        self._state_cov_idx = ('state_cov',) + np.diag_indices(k_posdef)

    @property
    def param_names(self):
        return ['sigma2.measurement.1', 'sigma2.measurement.2',
                'sigma2.level', 'sigma2.trend']

    @property
    def state_names(self):
        return ['level', 'trend']
    
    @property
    def start_params(self):
        std = np.std(self.endog, axis=0)
        return np.r_[std, 1e-2, 1e-2]

    def transform_params(self, unconstrained):
        return unconstrained**2

    def untransform_params(self, constrained):
        return constrained**0.5

    def update(self, params, *args, **kwargs):
        params = super(StateSpaceModel, self).update(params, *args, **kwargs)

        # Observation covariance
        self.ssm['obs_cov'] = np.diag(params[:2])

        # State covariance
        self.ssm[self._state_cov_idx] = params[2:]

```

For example, you would use this like:

```python
dta = sm.datasets.macrodata.load_pandas().data
dta.index = pd.period_range(start='1959Q1', end='2009Q3', freq='Q')
endog = np.log(dta[['realgdp', 'realgovt']]).diff().iloc[1:] * 100

mod = StateSpaceModel(endog)
res = mod.fit()

res.states.smoothed['level'].plot()
```

**Comment by zeina-abuaisheh** [comment]
Thanks so much, this is exactly what I want to.

What if I have KxNx2  as input where K is the number of objects, N is the number of observations and 2 is (x,y).
And I want the model to calculate one global 'sigma2.measurement.1' and one global 'sigma2.measurement.2' for all of these objects, rather than calculating 'sigma2.measurement.1' and 'sigma2.measurement.2' for each of them?

Thanks a lot

**Comment by ChadFulton** [comment]
The model only accepts N x M datasets, so you'd need to reshape your KxNx2 into N x (k * 2) data, and then set the rest of the state space matrices appropriately.

If you want only a single variance term, that's no problem, you'd just do something like:

```python
# Observation covariance
self.ssm['obs_cov'] = params[0] * np.eye(self.k_endog)
```

**Comment by ChadFulton** [comment]
> If you want only a single variance term, that's no problem, you'd just do something like:
> 
> ```python
> # Observation covariance
> self.ssm['obs_cov'] = params[0] * np.eye(self.k_endog)
> ```

Ah, I see that's not what you were looking for. Instead, you'd want something like:

```python
# Observation covariance
# sigma2.measurement.1
for i in range(0, self.k_endog, 2):
    self.ssm['obs_cov', i, i] = params[0]

# sigma2.measurement.2
for i in range(1, self.k_endog, 2):
    self.ssm['obs_cov', i, i] = params[1]
```

**Comment by zeina-abuaisheh** [comment]
`The model only accepts N x M datasets, so you'd need to reshape your KxNx2 into N x (k * 2) data, and then set the rest of the state space matrices appropriately.`
Thanks so much for your answer, I see know

`Ah, I see that's not what you were looking for. Instead, you'd want something like:`

Yeah exactly this is what I wanted "having the same covariance"

**Comment by ChadFulton** [comment]
Great - I'm going to close this issue as answered, but feel free to follow up if you have additional questions.

**Comment by zeina-abuaisheh** [comment]
Sorry for disturbing you again.

Is this a right code if the input is x,y,z ?


`

import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt
from data_preprocess import *
import os
import pickle
import scipy.stats
import pandas as pd


class StateSpaceModel(sm.tsa.statespace.MLEModel):
    def __init__(self, endog):
        # Model order
        k_states = k_posdef = 2

        # Initialize the statespace
        super(StateSpaceModel, self).__init__(
            endog, k_states=k_states, k_posdef=k_posdef,
            initialization='approximate_diffuse',
            loglikelihood_burn=k_states
        )

        # Initialize the matrices
        self.ssm['design'] = np.array([[1, 0],
                                       [1, 0],
                                       [1, 0]])
        self.ssm['transition'] = np.array([[1, 1],
                                           [0, 1]])
        self.ssm['selection'] = np.array([[1, 0],
                                          [0, 1]])

        # Cache some indices
        self._state_cov_idx = ('state_cov',) + np.diag_indices(k_posdef)

    @property
    def param_names(self):
        return ['sigma2.measurement.1', 'sigma2.measurement.2','sigma2.measurement.3',
                'sigma2.level', 'sigma2.trend']

    @property
    def state_names(self):
        return ['level', 'trend']

    @property
    def start_params(self):
        std = np.std(self.endog, axis=0)
        return np.r_[std, 1e-2, 1e-2]

    def transform_params(self, unconstrained):
        return unconstrained ** 2

    def untransform_params(self, constrained):
        return constrained ** 0.5

    def update(self, params, *args, **kwargs):
        params = super(StateSpaceModel, self).update(params, *args, **kwargs)

        # Observation covariance
        self.ssm['obs_cov'] = np.diag(params[:3])

        # State covariance
        self.ssm[self._state_cov_idx] = params[3:]



if(__name__=="__main__"):

    endog  = np.array([[3,5,6],[6,7,4],[9,5,3]])
    mod = StateSpaceModel(endog)
    res = mod.fit()
    print(res.summary())
`


Also, Is it possible to have a unique 'sigma2.measurement' even though the input is x,y,z ?

**Comment by ChadFulton** [comment]
> In my case, I have x,y coordinates and I want to predict each of them. In the code you proposed, the prediction works for the x part of it but not the y, do you know how to get a model that can predict both?

Can you expand on what you mean here? Are you thinking about the `predict` / `forecast` results methods? If so, they will produce predictions for all of the observed variables.

For example, following the code I posted above, you could get predictions for the next 5 periods via:

```python
res.forecast(steps=5)
```

which gives:

```
         realgdp  realgovt
2009Q4 -0.206891 -0.000306
2010Q1 -0.207197 -0.000306
2010Q2 -0.207502 -0.000306
2010Q3 -0.207808 -0.000306
2010Q4 -0.208114 -0.000306

**Comment by zeina-abuaisheh** [comment]
For example,
Let's say I have the following x,y coordinates:

```
[[-108.22058049  191.49785863]
 [-108.23108881  191.43326844]
 [-108.24159713  191.36867824]
 [-108.25210545  191.30408804]
 [-108.26259288  191.24056202]
 [-108.2730803   191.17703599]
 [-108.28356772  191.11350996]
 [-108.29405515  191.04998394]
 [-108.30450954  190.98744612]
 [-108.31496394  190.92490831]]
```

When I predict i.e. `  predicted_results = res.get_prediction() using the model you proposed, I get the following results:

```
[[ 0.00000000e+00  0.00000000e+00]
 [ 8.12613075e+01  1.89481888e+02]
 [-1.08241597e+02 -1.05083202e-02]
 [-1.08252105e+02 -1.05083202e-02]
 [-1.08262614e+02 -1.05083202e-02]
 [-1.08273091e+02 -1.04969054e-02]
 [-1.08283571e+02 -1.04906222e-02]
 [-1.08294056e+02 -1.04885608e-02]
 [-1.08304543e+02 -1.04878338e-02]
 [-1.08314979e+02 -1.04685276e-02]]
```

If we take a look at the results, we see that it makes sense for the x coordinate's results but not for the y

However, If I predict each of them separately using the following model 

```
class StateSpaceModel(sm.tsa.statespace.MLEModel):
    def __init__(self, endog):
        # Model order
        k_states = k_posdef = 2

        # Initialize the statespace
        super(StateSpaceModel, self).__init__(
            endog, k_states=k_states, k_posdef=k_posdef,
            initialization='approximate_diffuse',
            loglikelihood_burn=k_states
        )

        # Initialize the matrices
        self.ssm['design'] = np.array([1, 0])
        self.ssm['transition'] = np.array([[1, 1],
                                       [0, 1]])
        self.ssm['selection'] = np.array([[1, 0],
                                         [0, 1]])

        # Cache some indices
        self._state_cov_idx = ('state_cov',) + np.diag_indices(k_posdef)

    @property
    def param_names(self):
        return ['sigma2.measurement', 'sigma2.level', 'sigma2.trend']


    @property
    def start_params(self):
        return [np.std(self.endog), np.std(self.endog), 0]

    def transform_params(self, unconstrained):
        return unconstrained**2

    def untransform_params(self, constrained):
        return constrained**0.5

    def update(self, params, *args, **kwargs):
        params = super(StateSpaceModel, self).update(params, *args, **kwargs)

        # Observation covariance
        self.ssm['obs_cov',0,0] = params[0]

        print("**************************8",params[0])

        # State covariance
        self.ssm[self._state_cov_idx] = params[1:]
```


I get results that make sense

**Comment by ChadFulton** [comment]
It's impossible to speculate without an example that I can replicate. Most often when results are counter-intuitive, there is an error in setting up the matrices of the state space system. I suggest that you create the model and then pass some known parameters to the `update` method. Then, take a look at each of the state space matrices and make sure that they contain the values that you think they ought to. For example, you can print them:

```python
print(mod['obs_intercept'])
print(mod['design'])
print(mod['obs_cov'])
print(mod['state_intercept'])
print(mod['transition'])
print(mod['selection'])
print(mod['state_cov'])
```

**Comment by zeina-abuaisheh** [comment]
Thanks a lot for the advice. I will take a look at that and try to understand deeper, maybe something in the matrices has to be changed
