### ISSUE TITLE
Release Candidate for statsmodels 0.12.0 is out

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#6966]
The first Release Candidate for 0.12.0 is out. The release will likely follow in 2 weeks, depending on bug reports and fixes.

Install the Release Candidate using

```
pip install statsmodels==0.12.0rc0
```

**Comment by shahwaiz14** [comment]
Pretty trivial...you are missing a `=`, so to install its `pip install statsmodels==0.12.0rc0`

**Comment by bashtage** [comment]
Thanks.

**Comment by bashtage** [comment]
@ChadFulton @josef-pkt I plan on releasing 0.12.0 on Friday if there are no showstoppers.  

- [ ] Update change log
- [ ] Update javascript

**Comment by ChadFulton** [comment]
> I plan on releasing 0.12.0 on Friday if there are no showstoppers.

Let me know if I can help/

**Comment by josef-pkt** [comment]
I'm writing short descriptions of the stats additions for the release notes. I will push them later today.

**Comment by bashtage** [comment]
Release 0.12 has been cut.
