### ISSUE TITLE
Notebook example "Seasonality in time series data" has bugged Latex

### ISSUE THREAD

**Issue by baogianghoangvu** [statsmodels/statsmodels#6975]
#### Describe the bug

The ["Unobserved components (frequency domain modeling)" section in "Seasonality in time series data"  notebook](https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_seasonal.html#Unobserved-components-(frequency-domain-modeling)) has a markdown cell of latex that fails to render.

Checked on Firefox 79.0 (64-bit) and Chrome 84.0.4147.105 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/30065865/90725820-f0e53800-e2ea-11ea-8669-44dd401ce5ae.png)

#### Code Sample, a copy-pastable example if possible

I believe the issue is caused by a double Latex closing `$$` in the markdown cell, [lines L147-L148 in the mentioned notebook](
https://github.com/statsmodels/statsmodels/blame/b6af4263d6ad6de4ebf45d9200fcc95d3afc44e1/examples/notebooks/statespace_seasonal.ipynb#L147-L148)

```latex
$$
$$
```
#### Expected Output

Latex code renders like [the notebook in the repository](https://github.com/statsmodels/statsmodels/blob/master/examples/notebooks/statespace_seasonal.ipynb)
![image](https://user-images.githubusercontent.com/30065865/90727086-eb88ed00-e2ec-11ea-8da6-3d553c3de70b.png)

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

Not applicable.

**Comment by bashtage** [comment]
Thanks.
