### ISSUE TITLE
how can I use het_breushpagan()?

### ISSUE THREAD

**Issue by koyurion** [statsmodels/statsmodels#6989]
Hi, the version of my statsmodels  is   0.10.1.

I want to use the het_breushpagan() as follow, but meet some troubles. 
![image](https://user-images.githubusercontent.com/32454333/91120776-08486a80-e6c9-11ea-81b6-6683ad061151.png)

I search the issues' history and find it has been deleted after V0.9

So, how can I use it in V0.10?

Thanks

**Comment by josef-pkt** [comment]
spelling breusch with a "c"  (I had made the same mistake when I wrote the function, but the spelling was fixed in version 0.9

https://www.statsmodels.org/dev/generated/statsmodels.stats.diagnostic.het_breuschpagan.html

**Comment by koyurion** [comment]
@josef-pkt Thank you so much!

**Comment by bashtage** [comment]
Please use at least 0.11 or better 0.12.0rc0. This function has been improved since 0.10.

**Comment by koyurion** [comment]
@bashtage , Thanks for the hint! It works fine now!
