### ISSUE TITLE
Forecasting in Statsmodel

### ISSUE THREAD

**Issue by zeina-abuaisheh** [statsmodels/statsmodels#6995]
Hello,

Let's say I have the following State Space model: https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_local_linear_trend.html

To forecast in the future, this is done:
`forecast = res.get_forecast('2007')`

Let's say I want to forecast step by step rather than multi-steps at once, for example I want to forecast first the value in 2005, then 2006, then 2007 (separately), rather than forecasting all of them together, how is this possible in statmodels? I was looking for the forecasting equations but I was unable to find them.

Thanks a lot

**Comment by bashtage** [comment]
Assuming you have annual data:

1. Fit model using data until 2004, then do a 1-step forecast
2. Fit model using data until 2005, then do a 1-step forecast
3. ...

**Comment by zeina-abuaisheh** [comment]
But what if I want to fit the model until 2004, and then forecast 1-step for 2005, one step for 2006 and one step for 2007, separately?

**Comment by zeina-abuaisheh** [comment]
In fact the idea is to have a 1-step forecast at each time (assuming that I have data until 2004), then I want to perform 1-step forecast, and then verify if a certain condition is satisfied, then again 1-step forecast then  verify if a certain condition is satisfied and so on

**Comment by ChadFulton** [comment]
In state space models, the forecasts for any time horizon are produced by iterating a one-step-ahead forecasting rule. This rule comes from the transition equation:

a[t+1] = T a[t]

If you were adding additional data, then you would want to do as @bashtage suggested, but if you're not, then it sounds like it should already do what you're looking for.

**Comment by bashtage** [comment]
This is all that you need. 

```
forecasts = []
res = SARIMAX(data[:"2004"], order=(2,0,0)).fit()
forecasts.append(res.forecast(1))
res = SARIMAX(data[:"2005"], order=(2,0,0)).fit()
forecasts.append(res.forecast(1))
res = SARIMAX(data[:"2006"], order=(2,0,0)).fit()
forecasts.append(res.forecast(1))
...
```

or as a loop

```
forecasts = []
for end in np.arange(2004, 2008): #2004, ..., 2007
    res = SARIMAX(data[:str(end)], order=(2,0,0)).fit()
    forecasts.append(res.forecast(1))
```

**Comment by bashtage** [comment]
Closing since no changes needed. Please feel free to continue posting if this isn't clear. stackoverflow is also a good place to get general usage help with statsmodels.

**Comment by zeina-abuaisheh** [comment]
Thanks a lot for the suggestions, but for you, you are adding a new data, fitting the model and then doing the one-step forecasting.

How can I do this without adding new data?

I want something like

```
forecasts = []
while (constraint):
    forecast = res.forecast(1)
    forecasts.append(forecast)
```

so I want each time to add one more forecast (but without adding new data, assuming they are missed or in a forecast context)

**Comment by ChadFulton** [comment]
Unless you're doing this for a huge number of periods, it's probably going to be fast enough just to do:

```python
forecasts = []
h = 1
while (constraint):
    forecast = res.forecast(h)
    forecasts.append(forecast[-1])
    h += 1
```

If that doesn't meet your needs, you can do the following:

```python
forecasts = []
forecast_res = res
while (constraint):
    forecast = forecast_res.forecast(1)
    forecasts.append(forecast)
    forecast_res = forecast_res.extend(forecast)
```

**Comment by zeina-abuaisheh** [comment]
Thanks for your answer, indeed I am doing it for a huge number of periods, otherwise I would have used your first proposal.

As for the second one, I get the following error when I extend forecast_res:

```
<statsmodels.tsa.statespace.mlemodel.MLEResultsWrapper object at 0x7f7f4e725ac8>
    forecast_res = res_distance_to_cam.extend(forecast)
  File "/home/zeina/anaconda3/envs/pymc3-kalman/lib/python3.6/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 3765, in extend
    mod = self.model.clone(endog, exog=exog, **kwargs)
  File "/home/zeina/anaconda3/envs/pymc3-kalman/lib/python3.6/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 245, in clone
    raise NotImplementedError
NotImplementedError
```

**Comment by ChadFulton** [comment]
If you are using a custom state space model, then you will need to define the `clone` method in the model class in order to use things like `extend`. The `clone` method makes it possible to copy the current model specification to a different dataset.

If your model follows the usual setup (e.g. the first argument is `endog` and the remaining arguments are keywords), then there is a helper method that you can use, `_clone_from_init_kwds`. To use it:

1. Set a property `_init_keys` at the end of `__init__` to be a list of all extra arguments (arguments other than `endog` and `exog`).
2. If your model uses `exog` variables, then define the following `clone` method:

```python
def clone(self, endog, exog=None, **kwargs):
    return self._clone_from_init_kwds(endog, exog=exog, **kwargs)
```

otherwise if you don't have `exog`, you can use:

```python
def clone(self, endog, **kwargs):
        return self._clone_from_init_kwds(endog, **kwargs)
```

**Comment by zeina-abuaisheh** [comment]
Hello, thanks so much for your answer.

I wanted to update you that I defined the clone method and it worked perfectly after it.

Thanks so much for your help, so much appreciated

**Comment by ChadFulton** [comment]
Glad we could help.

**Comment by zeina-abuaisheh** [comment]
May I know what are the main equations that are used to implement `get_forecast`?

I tried the two last equations on page 30 of the following document
https://arxiv.org/pdf/1910.03558.pdf
But they don't lead to the same answers as the ones given by `get_forecast`

**Comment by ChadFulton** [comment]
Yes, we implement the same Kalman filter prediction and updating equations, although ours are slightly more general (we allow for an intercept in the observation and transition equations, and we separate the covariance matrix into a selection matrix R and a covariance matrix Q), and they have a typo in the time subscript for the mean in the prediction step.

Note that forecasts are of the observed variables and not the states, so to achieve the forecast at a particular horizon, you need to iterate the prediction equation and then premultiply by the design matrix.

Our Kalman filter is pretty well tested, so I'm guessing that the error is in the manual computations.

**Comment by zeina-abuaisheh** [comment]
Hello Chad,

Thanks so much for your answer, I really appreciate all of your help.

I will check this, I haven't per-multiplied by the design matrix so maybe the error comes from there.

Thanks again,
Best regards,
Zeina
