### ISSUE TITLE
BLD: windows build on appveyor, azur fails

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#7012]
current windows build fails in building cython extensions on appveyor (py 3.8) and azure pipelines all python versions

` TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'`

https://dev.azure.com/statsmodels/statsmodels-testing/_build/results?buildId=2820&view=logs&j=e25bc218-3ed4-536b-d0ee-1005e51efe54&t=051d04d6-4be6-5c50-da23-c5f4f33372ce

https://ci.appveyor.com/project/josef-pkt/statsmodels/builds/34952353/job/itym5d83fycgctyo

I rebased my PR #6971 on master, but it didn't change anything.

**Comment by josef-pkt** [comment]
this is a problem with latest setuptools version

scipy issues for same problem

https://github.com/scipy/scipy/pull/12795
https://github.com/scipy/scipy/pull/12798

**Comment by bashtage** [comment]
Probably just wait it out.

**Comment by josef-pkt** [comment]
we can pin `"setuptools<50.0"` in the meantime to have green CI
