### ISSUE TITLE
ETSModel get_prediction bug if start date is greater than dataset

### ISSUE THREAD

**Issue by yss-nw** [statsmodels/statsmodels#7018]
The get_prediction method encounters an error if the start date is after the end of the dataset.

import numpy as np
import pandas as pd
from statsmodels.tsa.api import ETSModel
values = np.arange(100)* (1+np.random.randn(100)/10)
dates = [np.datetime64('today') + np.timedelta64(-101+i) for i in range(100)]
x_train = pd.Series(values, index=dates)
x_train = x_train.asfreq(freq='D', method='bfill')
fit1 = ETSModel(x_train, seasonal_periods=7, trend='add').fit()
works = fit1.get_prediction(start=np.datetime64('today')- np.timedelta64(5), end=np.datetime64('today')+ np.timedelta64(5))
err = fit1.get_prediction(start=np.datetime64('today'), end=np.datetime64('today')+ np.timedelta64(5))

  File "\Anaconda3\lib\site-packages\statsmodels\tsa\exponential_smoothing\ets.py", line 2234, in __init__
    start : (end + 1)

ValueError: could not broadcast input array from shape (0) into shape (6)

**Comment by pratyushsharan** [comment]
@bashtage I had a look at this and looks like this error was not caught inside _handle_prediction_index:
`        # if end was outside of the sample, it is now the last point in the
        # sample
        if start > end + out_of_sample + 1:
            raise ValueError(
                "Prediction start cannot lie outside of the sample."
            )`
I think the logic to handle error is wrong here and have generated a pull request for the same #7039. Can you see if this would solve the issue?

**Comment by pratyushsharan** [comment]
@bashtage I've generated a pull request #7040 that'll resolve this issue. Can you have a look and see if this works?
