### ISSUE TITLE
BUG: SARIMAX with both exog and trend broken for h=1

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#7019]
This was introduced in v0.12, and is based on too-aggressive checking for a constant column in `exog` when there is also a constant trend.

```python
np.random.seed(1234)

y = np.random.normal(size=100)
x = np.random.normal(size=100)

mod = sm.tsa.SARIMAX(y, exog=x, order=(1, 0, 0), trend='c')
res = mod.smooth([-1., 0.5, 0.5, 1.0])
res.forecast(1, exog=[10.3])
```

```
~/projects/statsmodels/statsmodels/tsa/arima/specification.py in __init__(self, endog, exog, order, seasonal_order, ar_order, diff, ma_order, seasonal_ar_order, seasonal_diff, seasonal_ma_order, seasonal_periods, trend, enforce_stationarity, enforce_invertibility, concentrate_scale, trend_offset, dates, freq, missing)
    387             # If we already have a constant column, raise an error
    388             if np.any(col_const):
--> 389                 raise ValueError('A constant trend was included in the model'
    390                                  ' specification, but the `exog` data already'
    391                                  ' contains a column of constants.')

ValueError: A constant trend was included in the model specification, but the `exog` data already contains a column of constants.
```

**Comment by ChadFulton** [comment]
This is because to get the time-varying state space matrices, a `clone` is made for only the extended periods. The clone tries to validates the specification, but in the h=1 case, there's only 1 period, and so the `exog` in the forecast period is the same as a constant term. A similar thing would happen if forecasting with h > 1 if the given `exog` was constant over the forecast period.

Solution will be to not validate the specification when creating a clone to extend time-varying state space matrices, since whenever we do this, we're taking some parameter values as given, andthere's no identification problem between an intercept and constant `exog`.

**Comment by mloning** [comment]
Hi, just to have an idea, what's the likely time line for the`0.12.1` release with this patch?

**Comment by ChadFulton** [comment]
> Hi, just to have an idea, what's the likely time line for the0.12.1 release with this patch?

Thanks for this comment. I would like to release v 0.12.1 with this patch and a couple of others by the end of October (earlier would be better, but maybe not feasible).

**Comment by mloning** [comment]
Thanks @ChadFulton for the reply, that helps us plan ahead!

**Comment by ovrt4848** [comment]
I believe this is still broken for the "extend" functionality.  If you have a trend term already and non-constant exogenous variables, if you try to extend the model and one of the extended exogenous variables happens to be constant over that period, I believe it throws an error.  This is an issue with dummy variables.

**Comment by bashtage** [comment]
@ovrt4848 Can you open a new issue with a reproducer?
