### ISSUE TITLE
Get prediction interval for Holt, SimpleExpSmoothing  and ExponentialSmoothing class

### ISSUE THREAD

**Issue by an5ir** [statsmodels/statsmodels#7029]
#### Is your feature request related to a problem? Please describe
I wish to extract prediction interval from forecast of Holt, SimpleExpSmoothing and ExponentialSmoothing class

#### Describe the solution you'd like
If we do the following:
```
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.api import ExponentialSmoothing, SimpleExpSmoothing, Holt
%matplotlib inline

data = [446.6565,  454.4733,  455.663 ,  423.6322,  456.2713,  440.5881, 425.3325,  485.1494,  506.0482,  526.792 ,  514.2689,  494.211 ]
index= pd.date_range(start='1996', end='2008', freq='A')
oildata = pd.Series(data, index)
fit1 = SimpleExpSmoothing(oildata).fit()
fcast1 = fit1.forecast(3)

fit2 = Holt(oildata).fit()
fcast2 = fit2.forecast(3)

fit3 = ExponentialSmoothing(oildata).fit()
fcast3 = fit3.forecast(3)
```

Can we can get prediction intervals from `fit1`, `fit2`  and `fit3` for `fcast1` , `fcast2` and `fcast3` by doing the following:
```
fit1.get_prediction_intervals()
fit2.get_prediction_intervals()
fit3.get_prediction_intervals()
```

#### Describe alternatives you have considered
I have consider generating my own prediction intervals as suggested [here](https://stackoverflow.com/questions/54736632/how-to-obtain-prediction-intervals-with-statsmodels-timeseries-models)
but as the answer suggest this will not work for multi step forecasts.

Thanks for you time.

**Comment by bashtage** [comment]
Use `ETSModel` (new in 0.12) or `ExponentialSmoothing`  (new in 0.11, improved in 0.12)

**Comment by bashtage** [comment]
Closing since I don't think we will add PI to these classes since they exist in equivalent classes.  You can use one of the statespace-based models to get PI.  

If you have further question, please feel free to post theme here.

**Comment by an5ir** [comment]
thanks
