### ISSUE TITLE
tst bug, pylint mvsk2mnc not defined

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#703]
stats/test_moment_helpers.py line 87
`assert_equal(mvsk2mnc(mc2mvsk(mom[0])), mc2mnc(mom[0]))`

loop was empty and didn't test anything
mvsk2mnc not defined, did it not move when I included this ?

**Comment by jbrockmendel** [comment]
Good thing there are tools to help catch this kind of thing.

**Comment by bashtage** [comment]
Closeable. Not action needed.
