### ISSUE TITLE
N-dimensional State Space model 

### ISSUE THREAD

**Issue by zeina-abuaisheh** [statsmodels/statsmodels#7048]
Hello,

I have been trying to create an n-dimensional state space model to predict x,y,z positions given the velocities as hidden variables,
For instance the given example here is a 2D state space model: https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_local_linear_trend.html

This is my code:

```
"""
Univariate Local Linear Model
"""
class StateSpaceModel(sm.tsa.statespace.MLEModel):
    def __init__(self, endog):
        # Model order
        k_states = k_posdef = 6

        # Initialize the statespace
        super(StateSpaceModel, self).__init__(
            endog, k_states=k_states, k_posdef=k_posdef,
            initialization='approximate_diffuse',
            loglikelihood_burn=k_states
        )

        # Initialize the matrices
        self.ssm['design'] = np.array([1, 0, 1, 0, 1, 0])
        self.ssm['transition'] = np.array([
                                           [1, 1, 0, 0, 0, 0],
                                           [0, 1, 0, 0, 0, 0],
                                           [0, 0, 1, 1, 0, 0],
                                           [0, 0, 0, 1, 0, 0],
                                           [0, 0, 0, 0, 1, 1],
                                           [0, 0, 0, 0, 0, 1]
                                               ])
        self.ssm['selection'] = np.array([[1, 0, 0, 0, 0, 0],
                                          [0, 1, 0, 0, 0, 0],
                                          [0, 0, 1, 0, 0, 0],
                                          [0, 0, 0, 1, 0, 0],
                                          [0, 0, 0, 0, 1, 0],
                                          [0, 0, 0, 0, 0, 1]
                                          ])

        # Cache some indices
        self._state_cov_idx = ('state_cov',) + np.diag_indices(k_posdef)

    @property
    def param_names(self):
        return ['sigma2.measurement1','sigma2.level1', 'sigma2.trend1',
                'sigma2.level2', 'sigma2.trend2', 'sigma2.level3', 'sigma2.trend3']


    @property
    def start_params(self):
        return [np.std(self.endog), np.std(self.endog), 0, np.std(self.endog), 0, np.std(self.endog), 0]

    def transform_params(self, unconstrained):
        return unconstrained**2

    def untransform_params(self, constrained):
        return constrained**0.5

    def update(self, params, *args, **kwargs):
        params = super(StateSpaceModel, self).update(params, *args, **kwargs)
        # Observation covariance
        self.ssm['obs_cov',0,0] = params[0]
        # State covariance
        self.ssm[self._state_cov_idx] = params[1:]

```

As you can see from the transition matrix, dim_0 is x, dim_1 is x's velocity, dim_2 is y, dim_3 is y's velocity, dim_4 is z, and dim_5 is z's velocity. So I want my input to be x,y,z, but when I initialize the input with an array whose size is Nx3 where N is the number of points, I get the following error:
`ValueError: Invalid value for design matrix. Requires a 2- or 3-dimensional array, got 1 dimension`

Can you please explain to me what is wrong here?

Thanks a lot

**Comment by ChadFulton** [comment]
The error is because you're setting the design matrix to be a 1-dimensional array `np.array([1, 0, 1, 0, 1, 0])`, but it should be either a two-dimensional array (`k_endog` x `k_states`) or a three-dimensional array (`k_endog` x `k_states` x `nobs`). It should work to do the following:

```python
self.ssm['design'] = np.array([[1, 0, 1, 0, 1, 0]])
```

**Comment by zeina-abuaisheh** [comment]
When I try your suggestion, I get the following error

`ValueError: Invalid dimensions for design matrix: requires 3 rows, got 1`

**Comment by zeina-abuaisheh** [comment]
This works
```
        self.ssm['design'] = np.array([
                                       [1, 0, 0, 0, 0, 0],
                                       [0, 0, 1, 0, 0, 0],
                                       [0, 0, 0, 0, 1, 0]])
```

**Comment by ChadFulton** [comment]
Looks great.

**Comment by ChadFulton** [comment]
@zeina-abuaisheh  if you have time and interest, it would be great to get an example of tracking a moving object as a Jupyter notebook. I'd be happy to help if you are interested.

So if you are interested in doing that at some point, you can either submit a Pull Request, if you're comfortable with that, or you can create a Github Gist and share it that way.

**Comment by zeina-abuaisheh** [comment]
Hello Chad, so sorry for being late in my reply,
Of course I'd love to contribute to statsmodels (with your help too), does end of October work with you?

**Comment by ChadFulton** [comment]
No problem at all, and thanks for considering contributing! Please follow up on this when it is convenient, and let me know how I can help.

**Comment by zeina-abuaisheh** [comment]
I will, with pleasure
