### ISSUE TITLE
ExponentialSmoothing produces Nans in Python

### ISSUE THREAD

**Issue by muhammad-yasir** [statsmodels/statsmodels#7050]
#### Describe the bug

I am trying to predict the value of next 6 months (i.e. from October to March) based on last 6 months values (i.e. from April to September). However, when I predict the value, all values are NaNs. 

#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from statsmodels.tsa.holtwinters import ExponentialSmoothing

d = {'Month':['April','May','June','July','August','September'],'Value':[2.868,7.205,13.349,20.115,22.769,23.981]}
df = pd.DataFrame(data=d)

model = ExponentialSmoothing(df['Value'],trend='mul',seasonal='mul',seasonal_periods = 6).fit()
predict = model.forecast(6)
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

</details>

**Comment by bashtage** [comment]
Definitely a bug.  Probably because damping is NaN in parameters, even though the model isn't damped.

**Comment by bashtage** [comment]
This halogens because the initial state has a Nan in it.

**Comment by bashtage** [comment]
This has been fixed by making the initialization stricter.
