### ISSUE TITLE
AttributeError: 'OLSResults' object has no attribute '_use_t'

### ISSUE THREAD

**Issue by dex314** [statsmodels/statsmodels#7054]
In an attempt to compare an old version of a pickled model to a re-estimated one, I cam across the error:
AttributeError: 'OLSResults' object has no attribute '_use_t'

The old model was pickled using statsmodels 0.10.1 and the un-pickling is using 0.12.0. It doesnt seem as though the newer statsmodels can find the t-test options even though they are clearly there in the old version. 

I created a work around for my own needs by using the old models other attributes but the issue also stems into the call to "model.conf_int()".

I am fairly certain is not a pickling problem but if this was a change that I missed, please let me know.

#### Code Sample ----------------------------------------------

print("Reestimation using Statsmodels 0.12.0 ...")
print(ols_fit.summary().tables[1]) ## new model prints fine
print("Old Model From Pickle with Statsmodel 0.10.1 ...") 
print(old_model.summary().tables[1]) ## old model cant find the t-score arguments

#### Output and Error ------------------------------------------
Reestimation using Statsmodels 0.12.0 ...
Old Model From Pickle with Statsmodel 0.10.1 ...

AttributeError                            Traceback (most recent call last)
<ipython-input-130-10f743675dd0> in <module>
      2 # print(ols_fit.summary().tables[1]) ## new model prints fine
      3 print("Old Model From Pickle with Statsmodel 0.10.1 ...")
----> 4 print(old_model.summary().tables[1]) ## old model cant find the t-score arguments

~\Anaconda3\lib\site-packages\statsmodels\regression\linear_model.py in summary(self, yname, xname, title, alpha)
   2632                              yname=yname, xname=xname, title=title)
   2633         smry.add_table_params(self, yname=yname, xname=xname, alpha=alpha,
-> 2634                               use_t=self.use_t)
   2635 
   2636         smry.add_table_2cols(self, gleft=diagn_left, gright=diagn_right,

~\Anaconda3\lib\site-packages\statsmodels\base\model.py in use_t(self)
   1332     def use_t(self):
   1333         """Flag indicating to use the Student's distribution in inference."""
-> 1334         return self._use_t
   1335 
   1336     @use_t.setter

AttributeError: 'OLSResults' object has no attribute '_use_t'

**Comment by josef-pkt** [comment]
pickling/unpickling across statsmodels versions is NOT supported.

Pickling depends on the details of the classes and it would make it impossible (*) to improve models in newer versions.
(*) or very difficult if there is a way to support it

**Comment by dex314** [comment]
@josef-pkt Thank you Josef. Thats the direction I assumed this would go but figured I will post anyway just incase.
