### ISSUE TITLE
sm.add_constant() does not work for a single observation

### ISSUE THREAD

**Issue by nfiroozyeexos** [statsmodels/statsmodels#7057]
#### Description of the 'bug'

sm.add_constant() will take a dataframe and add an initial column 'const' with 1.0 in it. If, however, the dataframe happens to have a single observation in it, it does not add a constant to the dataframe. 

#### Code Sample

```python
import statsmodels.api as sm
import pandas as pd
print(sm.add_constant(pd.DataFrame({'a':3,'b':2}, index=[0])))

# output is
#     a  b
# 0  3  2

print(sm.add_constant(pd.DataFrame({'a':[3,2],'b':[2,1]}, index=[0,1])))

# output is
#     const    a  b
# 0     1.0     3  2
# 1     1.0     2  1
# It should run in a fresh ipython session, and so include all relevant imports.
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

sm.add_constant() is exceptionally basic but I would expect it should behave the same way under all conditions, and not have to have condition handling based on the shape of the input dataframe. 

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
Python: 3.7.7.final.0
OS: Linux 5.3.0-1035-aws #37-Ubuntu SMP Sun Sep 6 01:17:09 UTC 2020 x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8

statsmodels
===========

Installed: v0.13.0.dev0+22.g7d727fd1b (/home/nfiroozye/dev/statsmodels/statsmodels)

Required Dependencies
=====================

cython: 0.29.15 (/home/nfiroozye/bin/anaconda3/envs/spacval/lib/python3.7/site-packages/Cython)
numpy: 1.18.1 (/home/nfiroozye/bin/anaconda3/envs/spacval/lib/python3.7/site-packages/numpy)
scipy: 1.4.1 (/home/nfiroozye/bin/anaconda3/envs/spacval/lib/python3.7/site-packages/scipy)
pandas: 1.1.0 (/home/nfiroozye/bin/anaconda3/envs/spacval/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.1 (/home/nfiroozye/bin/anaconda3/envs/spacval/lib/python3.7/site-packages/dateutil)
patsy: 0.5.1 (/home/nfiroozye/bin/anaconda3/envs/spacval/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.1.3 (/home/nfiroozye/bin/anaconda3/envs/spacval/lib/python3.7/site-packages/matplotlib)
    backend: Qt5Agg
cvxopt: 1.2.5 (/home/nfiroozye/bin/anaconda3/envs/spacval/lib/python3.7/site-packages/cvxopt)
joblib: 0.14.1 (/home/nfiroozye/bin/anaconda3/envs/spacval/lib/python3.7/site-packages/joblib)

Developer Tools
================

IPython: 7.13.0 (/home/nfiroozye/bin/anaconda3/envs/spacval/lib/python3.7/site-packages/IPython)
    jinja2: 2.11.1 (/home/nfiroozye/bin/anaconda3/envs/spacval/lib/python3.7/site-packages/jinja2)
sphinx: 2.4.4 (/home/nfiroozye/bin/anaconda3/envs/spacval/lib/python3.7/site-packages/sphinx)
    pygments: 2.6.1 (/home/nfiroozye/bin/anaconda3/envs/spacval/lib/python3.7/site-packages/pygments)
pytest: 5.4.1 (/home/nfiroozye/bin/anaconda3/envs/spacval/lib/python3.7/site-packages/pytest)
virtualenv: Not installed

</details>

**Comment by bashtage** [comment]
This is expected. When you have a single observation the columns appear constant. You need to change `has_constant='skip'` to `has_constant='add'` to override.

**Comment by bashtage** [comment]
I think there is nothing else to do here.  Feel free to continue to post if there are other issues.
