### ISSUE TITLE
ENH: Add support for inequality constraints in LS estimators

### ISSUE THREAD

**Issue by luoluoluoluojunxi** [statsmodels/statsmodels#7060]
i want to use LinearRegression by statsmodel . and i need to creat model than sure the params >0 ,but i can't find any args can do that.

**Comment by bashtage** [comment]
The regression estimators do no support inequality constraints since inference in these models is non-standard and so any results would not be correct.

**Comment by emailhy** [comment]
@luoluoluoluojunxi  you can try use .fit() with "minimize" as optimization methods, the spicy optimizer allow you to pass the inequality constraints, however it may impact the assumption for linear regression.

**Comment by josef-pkt** [comment]
see #1382 and other previous issues

closing this as duplicat
