### ISSUE TITLE
Interactions of categorical variables

### ISSUE THREAD

**Issue by annika-stechemesser** [statsmodels/statsmodels#7062]
Hello, 
I have a problem with including interaction terms of categorical variables. Say var1 (levels a,b,c) and var2 (levels 1,2,3) are both categorical. If I run the regression y~x+var1:var2 I obtain, in addition to var1:var2 also a:var2, b:var2, c:var2 as variables in the regression. 

It gets even more confusing when I want to actually have interactions for each category (the goal would be to have a:1, a:2, a:3, b:1 etc.). However, if I run y~x+C(var1):C(var2) I get these interactions but ALSO coefficients for a,b,c individually in my regression. In my understanding of the documentation that should not happen with the : operator? 

I tried to run y~x+C(var1):C(var2)-var1-var2 instead but this did not help. I also tried to use the star operator and manually remove all unwanted combinations which also did not work. 

For numerical data there seems to be no problem. It would be great to get some advice on this issue! 
Thank you!

**Comment by bashtage** [comment]
The first sounds right. Interactions of categorical variables should where the first has n1 and the second has n2 categories should result in a model with n1*n2 - 1 (for the constant) terms.

Can you provide a simple example of the model that are you trying to estimate?

**Comment by annika-stechemesser** [comment]
Hi, 
I have made a toy dataset: 
![image](https://user-images.githubusercontent.com/33522265/94543223-0d5d8400-024a-11eb-8173-b435852eda54.png)

I use the score as the dependent and the cuteness as the independent variable and want to include animal-color fixed effects (i.e. get one coefficients for each combination of animal and color). 

I run: a = sm.ols(formula = 'score~cuteness+C(animal):C(color)', data = toy_data).fit()

Which yields: 
![image](https://user-images.githubusercontent.com/33522265/94543598-8c52bc80-024a-11eb-9c77-cc79b16d684e.png)

However, I did not want to include color as a predictor by itself? The output suggests that the model that was actually fitted is score~cuteness+C(color) + C(animal):C(color).

I hope this clarifies the problem... thank you for your help!

**Comment by bashtage** [comment]
What happens if you add `-C(color)` to the formula?

**Comment by annika-stechemesser** [comment]
Sadly nothing changes at all. If I run a = sm.ols(formula = 'score~cuteness+C(animal):C(color)-C(color)', data = A).fit() I get exactly the same result...

**Comment by bashtage** [comment]
The model that you are getting appears to be equivalent.  You have 3 categories in each, so the product would be 9 variables.  But then you have a constant, so remove 1, and then you have the variables them selves, so remove one for orange and one for yellow, and you then get 6 interactions.  So you have 9 terms or 9 terms, and so the model fit is equivalent, you just need to manually compute the 9 interaction effects from the 9 terms (excl cuteness).

**Comment by annika-stechemesser** [comment]
I'm not sure I understand what you mean. Even though the shape of the design matrix might be the same, surely it matters which columns it uses? How can the model be equivalent? Also in my actual model I have a lot more than 9 terms which would make it quite uncomfortable to compute them by hand... Is there now way to model this precisely with statsmodels?

**Comment by bashtage** [comment]
As long as the span of the matrices are the same, then the model is the
same. As for interpretation, you can write a simple program to sort that
out I suspect.

Ultimately this is how patsy handles things, since statsmodels defers
completely to patsy.  The patsy documentation may have some hints.

**Comment by bashtage** [comment]
I am going to close since there is nothing for us to change here.  Please feel free to continue to post if there are things that are unclear.

**Comment by josef-pkt** [comment]
@annika-stechemesser 

You need to remove the constant to get only interacted effect without any left out reference level, ie. `-1`

try 'score~cuteness+C(animal):C(color) - 1'

**Comment by annika-stechemesser** [comment]
Thank you so much that worked!

**Comment by Himanshujayswal** [comment]
Once the model is build with the interaction of variables..

pred=res.predict(# what should I give here?)

**Comment by josef-pkt** [comment]
If you used formula interface, then `predict` takes a dataframe (or dict) with the same column names as the original exog.
The data in the dataframe will be transformed in the same way as the original exog in the formula.
