### ISSUE TITLE
One Step Ahead Predictions with ExponentialSmoothing

### ISSUE THREAD

**Issue by dtoniolo** [statsmodels/statsmodels#7077]
#### The problem
I have a time series divided in two consecutive `train` and `test` partitions. I need the model to perform well in one step ahead predictions. However, there seems to be no way to do this without refitting the model.

#### Code
I test the model in this toy example:
```{python}
from statsmodels.tsa.holtwinters import Holt

data = load_data_from_somewhere()
n = data.size
train = data[:0.8*n]
test = data[0.8*n:]
mod = Holt(train)
fitted_mod = mod.fit(smoothing_level=.5, smoothing_slope=.05)
```
at this point, if `fitted_mod` where a state space model, i could do the following (related to what's explained [here](https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_forecasting.html#Cross-validation), but without the cross validation):
```{python}
complete_mod = Holt(data)
fitted_complete_mod = complete_mod.filter(fitted_mod.params)
pred = fitted_complete_mod.predict(start=0.8*n)
# then compute metrics like MSE between pred and train
```
however, this is not possibile with `Holt`: the `filter` method fails. I can find no other way to do this. I'd like to make it clear that I **do not want** to refit the parameters, instead I wish to keep the same ones from the train fit.

#### Additional problem
As explained in the [user guide](https://www.statsmodels.org/dev/tsa.html#exponential-smoothing), Exponential Smoothing are not compatible, in general, with the state space formulation. For this reason, three different implementations are provided.

The `Hold` instance provided here should be of class `statsmodels.tsa.holtwinters.Holt`, but is of type `statsmodels.tsa.statespace.structural.UnobservedComponents` instead. I do not now how this behaviour is possible and generates inconsistency, because `fitted_complete_mod` is of type `statsmodels.tsa.holtwinters.results.HoltWintersResultsWrapper`, instead of the `statsmodels.tsa.statespace.structural.UnobservedComponentsResultsWrapper` one would expect as output of the `fit` method of an `UnobservedComponents`.

#### Solution

There should be a clearer distinction between the classes of incompatible objects. Moreover, there should be a clear way to create an exponential smoothing model with some predefined parameters.

#### Note
If what I have described above is intended behaviour, then I apologise for opening the issue. If this is the case, I'd like to write a documentation page like [this one](https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_forecasting.html#Cross-validation) so that other users won't repeat my mistake.

**Comment by ChadFulton** [comment]
> this is not possibile with Holt: the filter method fails. I can find no other way to do this. I'd like to make it clear that I do not want to refit the parameters, instead I wish to keep the same ones from the train fit.

I suggest using the new exponential smoothing class, `sm.tsa.ETSModel`. For example, you could do:

```python
import statsmodels.api as sm

data = load_data_from_somewhere()
n = data.size
n_train = int(0.8 * n)
train = data[:n_train]
test = data[n_train:]
mod = sm.tsa.ETSModel(train, trend='add')
with mod.fix_params({'smoothing_level': 0.5, 'smoothing_trend': 0.05}):
    fitted_mod = mod.fit()
fitted_mod.summary()
```

and then

```python
complete_mod = sm.tsa.ETSModel(data, trend='add')
fitted_complete_mod = complete_mod.smooth(fitted_mod.params)
pred = fitted_complete_mod.predict(start=n_train)
# then compute metrics like MSE between pred and train
```

**Comment by ChadFulton** [comment]
> The Hold instance provided here should be of class statsmodels.tsa.holtwinters.Holt, but is of type statsmodels.tsa.statespace.structural.UnobservedComponents instead. I do not now how this behaviour is possible and generates inconsistency, because fitted_complete_mod is of type statsmodels.tsa.holtwinters.results.HoltWintersResultsWrapper, instead of the statsmodels.tsa.statespace.structural.UnobservedComponentsResultsWrapper one would expect as output of the fit method of an UnobservedComponents.

I think that this is probably some error in your code.  The `Holt` and `UnobservedComponents` classes have nothing to do with each other.

**Comment by ChadFulton** [comment]
Closing as answered, but feel free to follow up with comments if you have additional questions.

**Comment by dtoniolo** [comment]
Thanks you, really. The class issue was really a problem of my code, so no bug in the library. I'm sorry for opening a useless issue report, I'll check my code better next time, and I'll use the `sm.tsa.ETSModel` class from now on.

Thank you for your awesome work for `statsmodels`, being able to ditch `R` and have basically all the statistical tools I need in one package, with consistent syntax, is priceless.

**Comment by ChadFulton** [comment]
No problem. Also, I think the idea of an example notebook showing forecasting with exponential smoothing models is a great idea. If you happen to write something up (ideally using `ETSModel`), I think that could make a nice addition to the documentation.
