### ISSUE TITLE
Name "mean" in summary_frame function conflicts with Pandas "mean"

### ISSUE THREAD

**Issue by silvavn** [statsmodels/statsmodels#7082]
#### Describe the bug

Dataframe returned by PredictionResults.summary_frame has a key "mean", which is a conflict with pandas Dataframe.mean. One can't read the values of that column because pandas thinks its a function.

#### Code Sample, a copy-pastable example if possible

<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

Key should not be `mean` but another significant name.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
Python: 3.7.7.final.0

statsmodels
===========

Installed: 0.12.0 (C:\Users\Victor\Anaconda3\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: 0.29.21 (C:\Users\Victor\Anaconda3\lib\site-packages\Cython)
numpy: 1.18.5 (C:\Users\Victor\Anaconda3\lib\site-packages\numpy)
scipy: 1.4.1 (C:\Users\Victor\Anaconda3\lib\site-packages\scipy)
pandas: 0.24.1 (C:\Users\Victor\AppData\Roaming\Python\Python37\site-packages\pandas)
    dateutil: 2.8.1 (C:\Users\Victor\Anaconda3\lib\site-packages\dateutil)
patsy: 0.5.1 (C:\Users\Victor\Anaconda3\lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.3.1 (C:\Users\Victor\Anaconda3\lib\site-packages\matplotlib)
    backend: Qt5Agg
cvxopt: Not installed
joblib: 0.16.0 (C:\Users\Victor\Anaconda3\lib\site-packages\joblib)

Developer Tools
================

IPython: 7.17.0 (C:\Users\Victor\Anaconda3\lib\site-packages\IPython)
    jinja2: 2.11.2 (C:\Users\Victor\Anaconda3\lib\site-packages\jinja2)
sphinx: 3.2.1 (C:\Users\Victor\Anaconda3\lib\site-packages\sphinx)
    pygments: 2.6.1 (C:\Users\Victor\Anaconda3\lib\site-packages\pygments)
pytest: 6.0.1 (C:\Users\Victor\Anaconda3\lib\site-packages\pytest)
virtualenv: Not installed

</details>

**Comment by bashtage** [comment]
You can always use sf["mean"].

**Comment by bashtage** [comment]
Closing as this is the most meaningful name, and dictionary access can always be used.
