### ISSUE TITLE
DOC: Log base of the proportional hazards model is not documented

### ISSUE THREAD

**Issue by tgbrooks** [statsmodels/statsmodels#7083]
Documentation for [PHReg](https://www.statsmodels.org/stable/generated/statsmodels.duration.hazard_regression.PHReg.html) does not make it clear what base is being used for the logarithm in model. From a naive reading of the code, it appears that a natural logarithm is used, but this should be checked and included in the documentation for clarity. This matters for the purpose of interpreting effect sizes as reported in the `params` attribute of the regression fit.

**Comment by kshedden** [comment]
I'm certainly not opposed to adding a comment to this effect.  In general, logarithms are uniquitous in statistics and in statsmodels, and they are always natural logs except in very rare exceptional cases that should be documented.  All other packages and literature about statistical modeling conform to this convention.

**Comment by josef-pkt** [comment]
closing this, natural log is general convention, unless explicitly stated otherwise
