### ISSUE TITLE
GMM AttributeError: 'DataFrame' object has no attribute 'xnames'

### ISSUE THREAD

**Issue by ebehii** [statsmodels/statsmodels#7087]
#### Describe the bug

Using the gmm class  results in an AttributeError: 'DataFrame' object has no attribute 'xnames'

This seems to be due to the first line of the _fix_param_names function in line 515 of gmm.py:
        xnames = self.data.xnames

So far, I've gotten around it by commenting out line 696:         
      self._fix_param_names(params, param_names=None)

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.7.9.final.0

statsmodels
===========

Installed: 0.12.0

Required Dependencies
=====================

cython: 0.29.21 
numpy: 1.19.1 
scipy: 1.5.2 
pandas: 1.1.2 
    dateutil: 2.8.1 
patsy: 0.5.1 

Optional Dependencies
=====================

matplotlib: 3.3.1 
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 0.17.0 

Developer Tools
================

IPython: 7.18.1 
    jinja2: 2.11.2 
sphinx: 3.2.1 
    pygments: 2.7.1
pytest: 6.1.0 
virtualenv: Not installed
</details>

**Comment by josef-pkt** [comment]
There is something else wrong. `model.data` should be an instance of one of our data classes and not a DataFrame.

Can you show your setup how you create the model, specifically how you provide the data?
Did you use `data` as a keyword when creating the class?

At the end of all `**kwds` are just attached with `self.__dict__.update(kwds)` and so override any already existing attributes.
This provides flexibility, but currently there is no safeguard that an important model attribute isn't unintentionally overwritten.

**Comment by josef-pkt** [comment]
file search

We often use `self.__dict__.update(kwds)` in results classes where we control it's creation.

more public classes
- GenericLikelihoodModel uses unprotected `self.__dict__.update` but before calling `super().__init__`
- `base._constraints.LinearConstraints` uses it, but I guess that's only internal (if we don't transmit user kwargs)
- tsa x13 has `self.__dict__.update` in `Spec.set_options` but there users needs to check what's supported by x13 package

**Comment by ebehii** [comment]
You're right! I passed a dataframe into model.data. Changing that solved the problem. Thanks!
