### ISSUE TITLE
ImportError: cannot import name 'iterkeys'

### ISSUE THREAD

**Issue by anindya5** [statsmodels/statsmodels#7097]
`from pmdarima.arima import auto_arima`

pmdarima only installed statsmodels 0.11.1

This code creates the error

ImportError                               Traceback (most recent call last)
<ipython-input-84-13081f3c87cf> in <module>
      4 import pickle
      5 import numpy as np
----> 6 from pmdarima.arima import auto_arima

~/anaconda3/envs/local_env_wow_t4/lib/python3.6/site-packages/pmdarima/__init__.py in <module>
     49 
     50     # Stuff we want at top-level
---> 51     from .arima import auto_arima, ARIMA, AutoARIMA, StepwiseContext, decompose
     52     from .utils import acf, autocorr_plot, c, pacf, plot_acf, plot_pacf, \
     53         tsdisplay

~/anaconda3/envs/local_env_wow_t4/lib/python3.6/site-packages/pmdarima/arima/__init__.py in <module>
      4 
      5 from .approx import *
----> 6 from .arima import *
      7 from .auto import *
      8 from .utils import *

~/anaconda3/envs/local_env_wow_t4/lib/python3.6/site-packages/pmdarima/arima/arima.py in <module>
      9 from sklearn.utils.validation import check_array
     10 
---> 11 from statsmodels import api as sm
     12 
     13 from scipy.stats import gaussian_kde, norm

~/anaconda3/envs/local_env_wow_t4/lib/python3.6/site-packages/statsmodels/api.py in <module>
     12 from .regression.quantile_regression import QuantReg
     13 from .regression.mixed_linear_model import MixedLM
---> 14 from .genmod import api as genmod
     15 from .genmod.api import (GLM, GEE, OrdinalGEE, NominalGEE, families,
     16                          cov_struct,

~/anaconda3/envs/local_env_wow_t4/lib/python3.6/site-packages/statsmodels/genmod/api.py in <module>
      5 ]
      6 from .generalized_linear_model import GLM
----> 7 from .generalized_estimating_equations import GEE, OrdinalGEE, NominalGEE
      8 from .bayes_mixed_glm import BinomialBayesMixedGLM, PoissonBayesMixedGLM
      9 from . import families

~/anaconda3/envs/local_env_wow_t4/lib/python3.6/site-packages/statsmodels/genmod/generalized_estimating_equations.py in <module>
     39 from statsmodels.genmod import families
     40 from statsmodels.genmod.generalized_linear_model import GLM
---> 41 from statsmodels.genmod import cov_struct as cov_structs
     42 
     43 import statsmodels.genmod.families.varfuncs as varfuncs

~/anaconda3/envs/local_env_wow_t4/lib/python3.6/site-packages/statsmodels/genmod/cov_struct.py in <module>
      7 http://www.stata.com/manuals13/xtxtgee.pdf
      8 """
----> 9 from statsmodels.compat.python import iterkeys, itervalues
     10 from statsmodels.compat.pandas import Appender
     11 

ImportError: cannot import name 'iterkeys'

**Comment by bashtage** [comment]
You have some wrong versions on your path.

Remove your statsmodels y running 

```
pip uninstall statsmodels -y
```
until you see

WARNING: Skipping statsmodels as it is not installed.

and then run

```
pip install statsmodels==0.11.1
```

**Comment by bashtage** [comment]
Feel free to continue to post, but there is no bug to fix here, so closing.
