### ISSUE TITLE
Child process spawned on import

### ISSUE THREAD

**Issue by xolerick** [statsmodels/statsmodels#7098]
#### Describe the bug

Upon importing "import statsmodels.api as sm" the subprocess is being spawned without even referring to the library. That can be proven by: 
current_process = psutil.Process()
children = current_process.children(recursive=True)
for child in children:
    logging.info('Child pid is {} going to kill it!'.format(child.pid))

The issue comes big as an example where the company I currently work for uses special containerized tasks and this subprocess is not terminating gracefully at all. What I had to do to work around it is:
for child in children:
    logging.info('Child pid is {} going to kill it!'.format(child.pid))
    os.kill(child.pid, signal.SIGKILL)
    logging.info("killed it!")

Otherwise the program takes way to long to respond. Or cannot properly finish and times out. 

#### Code Sample, a copy-pastable example if possible
```python
logger.info("Starting up")

current_process = psutil.Process()
children = current_process.children(recursive=True)
for child in children:
    logging.info('Child pid is {} going to kill it!'.format(child.pid))
    os.kill(child.pid, signal.SIGKILL)
    logging.info("killed it!")

current_process = psutil.Process()
children = current_process.children(recursive=True)
logging.info("second iteration of children")
for child in children:
    logging.info('Child pid is {}'.format(child.pid))
    
logging.info("done with child pids")
return "hello world"


# Your code here that produces the bug
import statsmodels.api as sm
import psutil
current_process = psutil.Process()
children = current_process.children(recursive=True)
for child in children:
    logging.info('Child pid is {} going to kill it!'.format(child.pid))

# This example should be self-contained, and so not rely on external data.
# It should run in a fresh ipython session, and so include all relevant imports.
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
Python: 3.7.1.final.0

statsmodels
===========

Installed: 0.12.0 (C:\Users\ktcariap\PycharmProjects\Capacity v2\venv\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.19.2 (C:\Users\ktcariap\PycharmProjects\Capacity v2\venv\lib\site-packages\numpy)
scipy: 1.3.0 (C:\Users\ktcariap\PycharmProjects\Capacity v2\venv\lib\site-packages\scipy)
pandas: 1.1.3 (C:\Users\ktcariap\PycharmProjects\Capacity v2\venv\lib\site-packages\pandas)
dateutil: 2.8.1 (C:\Users\ktcariap\PycharmProjects\Capacity v2\venv\lib\site-packages\dateutil)
patsy: 0.5.1 (C:\Users\ktcariap\PycharmProjects\Capacity v2\venv\lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.3.2 (C:\Users\ktcariap\PycharmProjects\Capacity v2\venv\lib\site-packages\matplotlib)
backend: TkAgg
cvxopt: Not installed
joblib: 0.17.0 (C:\Users\ktcariap\PycharmProjects\Capacity v2\venv\lib\site-packages\joblib)

Developer Tools
================

IPython: Not installed
jinja2: Not installed
sphinx: Not installed
pygments: Not installed
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by bashtage** [comment]
I cannot reproduce on Ubuntu.  

I fixed your code:

```
import logging
import psutil
import signal

logger = logging.getLogger()

logger.info("Starting up")
logger.setLevel(logging.INFO)
current_process = psutil.Process()
children = current_process.children(recursive=True)
for child in children:
    logging.info('Child pid is {} going to kill it!'.format(child.pid))
    os.kill(child.pid, signal.SIGKILL)
    logging.info("killed it!")

current_process = psutil.Process()
children = current_process.children(recursive=True)
logging.info("second iteration of children")
for child in children:
    logging.info('Child pid is {}'.format(child.pid))

logging.info("done with child pids")


# Your code here that produces the bug
import statsmodels.api as sm
import psutil
current_process = psutil.Process()
children = current_process.children(recursive=True)
for child in children:
    logging.info('Child pid is {} going to kill it!'.format(child.pid))

```

When I run this I see
```
(base) ➜  temp python tester.py
INFO:root:second iteration of children
INFO:root:done with child pids
```

**Comment by bashtage** [comment]
AFAICT `statsmodels` does not create any subprocesses on import, nor should it.

**Comment by bashtage** [comment]
Going to close since it is not reproducible.
