### ISSUE TITLE
ar_model confidence intervals for prediction

### ISSUE THREAD

**Issue by sailinz** [statsmodels/statsmodels#7111]
It stated in the source code that this is a todo item for ar_model.py: # TODO: consider returning forecast errors and confidence intervals?

I try to reuse the related functions in arima_modal but in vain. The confidence interval is very large. Could you kindly suggest how to calculate the confidence interval for AR? 

Below is my attempt: 

```
def _forecast_error(self, sigma2, arparams, steps):
        ar_coef = np.r_[1, -arparams]
        ma_rep = arma2ma(ar_coef,np.ones(1), lags=steps)
        fcasterr = np.sqrt(sigma2 * np.cumsum(ma_rep ** 2))
        return fcasterr   

def _forecast_conf_int(self, forecast, fcasterr, alpha):
        const = norm.ppf(1 - alpha / 2.)
        conf_int = np.c_[forecast - const * fcasterr,
                         forecast + const * fcasterr]
        return conf_int
```

Calling the function: modelAR is an ARResults instance and pred_result is derived from the returned value of ARResults.predict
  
```
modelAR = AR(training_data).fit()
modelAR, pred_result = modelAR.predict(start=pred_start, end=pred_start+timedelta(minutes = pred_interval))
pred_result = pred_result.to_frame()
pred_result.index = pd.to_datetime(pred_result.index)
pred_result.columns = ['value_col']       
pred_error = self._forecast_error(modelAR.sigma2, modelAR.params, pred_result.shape[0])

conf_int = self._forecast_conf_int(pred_result['value_col'].array, pred_error, 0.05)
```

Many thanks for your help!

**Comment by bashtage** [comment]
AR is deprecated and won't get any further updates.  `AutoReg` or `S`/`ARIMA` are the future.

**Comment by bashtage** [comment]
Closing since no path forward in AR.
