### ISSUE TITLE
RLS: Release v0.12.1

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#7115]
We need to produce a bug fix release v0.12.1.  Backport issues are:

- [x] #7016
- [x] #7017
- [x] #7020
- [x] #7025
- [x] #7028
- [x] #7040
- [x] #7052 - an ENH
- [x] #7055
- [x] #7073
- [x] #7088
- [x] #7090
- [x] #7093
- [x] #7109
- [x] #7116
- [x] #7118 

Other bugs fixed before release

- [x] #7120

I would like to release this soon, so please update if there are other PRs that should be merged into maintanance/v0.12.x.

**Comment by bashtage** [comment]
Anything for 0.12.1 should have the backport label.

**Comment by ChadFulton** [comment]
Thanks. I'll merge all the backport PRs into the maintenance branch and write up release notes this week, with a plan to release v0.12.1 at the end of October.

**Comment by ChadFulton** [comment]
@bashtage do we need to get #7118 in? It has a change to a new file (ordinal model) so I can't backport the commits directly, but I'm happy to make a new commit with the other changes, if we should include it in v0.12.1.

**Comment by ChadFulton** [comment]
> do we need to get #7118 in? It has a change to a new file (ordinal model) so I can't backport the commits directly, but I'm happy to make a new commit with the other changes, if we should include it in v0.12.1.

I went ahead and backported the commit minus the change to the nonexistent file, so no need to follow up unless this was the wrong thing to do.

**Comment by ChadFulton** [comment]
If all is well, then tomorrow night I will:

1. Merge the release notes into master: #7122
2. Merge the cherry-picked backport commits into maintenance/0.12.x: #7121 
3. Tag v0.12.1 from maintenance/0.12.x
4. Release v0.12.1 on Github (for draft, see https://github.com/statsmodels/statsmodels/releases/tag/untagged-bff004691c3818a6d2be) with the source code as assets.

However, I am not sure about the process for e.g. PyPi or Conda Forge releases. @bashtage do you have time to help with these?

Finally, if anyone spots that I am doing something wrong, please let me know.

**Comment by bashtage** [comment]
Can you hold off on tagging until we make sure this branch is passing wheel building?

**Comment by bashtage** [comment]
Test build at MacPython/statsmodels-wheels#51

**Comment by bashtage** [comment]
Wheels are all good, so feel free to tag when you are ready.

**Comment by ChadFulton** [comment]
Thanks very much @bashtage.

I have tagged v0.12.1 and now published the release on Github.
