### ISSUE TITLE
Lilliefors test in Python is returning different results wrt Matlab

### ISSUE THREAD

**Issue by angystallone** [statsmodels/statsmodels#7124]
In Seismology, it is a common practice to implement the Lilliefors test to find the minimum magnitude value _mc_ above which the (magnitude-frequency) distribution is exponential. When implementing the Lilliefors test in Python, I get a value for _mc_ which is much lower than the one returned in Matlab. I suspect this is due to a different implementation of the Lilliefors test. See codes below to reproduce.

**Python**
```
from numpy import loadtxt
from statsmodels.stats.diagnostic import lilliefors as lillie

mag = loadtxt('data.txt')

mmin = 0.0
upperlim = 40

for i in range(int(mmin * 10), upperlim, 1):
    magsel = ([mgev for mgev in mag if mgev >= float(i/10)])
    magselmin = [x - float(i/10) for x in magsel]
    kstest, pvalue_lilli = lillie(magselmin, dist='exp')
    if pvalue_lilli < 0.05:
        continue
    else:
        break

mc = float(i/10)
pval = pvalue_lilli
```

**Matlab**
```
mag = load('data.txt');

mmin = 0.0 ;
upperlim = 40;

for i = round(mmin * 10) : upperlim
    magsel = mag(mag >= i/10);
    magselmin = magsel - i/10;
    [~, pvalue_lilli] = lillietest(magselmin, 'Distribution','exponential');
    if pvalue_lilli < 0.05
        continue
    else
        break
    end
end

mc = i/10
pval = pvalue_lilli        

```

<details>

INSTALLED VERSIONS
------------------
Python: 3.7.5.final.0
OS: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: None
Statsmodels
===========
Installed: 0.10.2 (/usr/local/lib/python3.7/site-packages/statsmodels)
Required Dependencies
=====================
cython: Not installed
numpy: 1.17.2 (/usr/local/lib/python3.7/site-packages/numpy)
scipy: 1.3.1 (/usr/local/lib/python3.7/site-packages/scipy)
pandas: 0.25.3 (/usr/local/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.0 (/usr/local/Cellar/graph-tool/2.29_1/libexec/lib/python3.7/site-packages/dateutil)
patsy: 0.5.1 (/usr/local/lib/python3.7/site-packages/patsy)
Optional Dependencies
=====================
matplotlib: 3.1.1 (/usr/local/Cellar/graph-tool/2.29_1/libexec/lib/python3.7/site-packages/matplotlib)
Backend MacOSX is interactive backend. Turning interactive mode on.
    backend: MacOSX 
cvxopt: Not installed
joblib: 0.14.1 (/usr/local/lib/python3.7/site-packages/joblib)
Developer Tools
================
IPython: Not installed
    jinja2: Not installed
sphinx: Not installed
    pygments: Not installed
pytest: Not installed
virtualenv: Not installed

</details>

[data.txt](https://github.com/statsmodels/statsmodels/files/5459480/data.txt)

**Comment by bashtage** [comment]
We have different p-values.  Ours have been computed using a much larger simulation than what MATLAB used.

What do you see when you check the p-value for a specific sample?

**Comment by angystallone** [comment]
In MATLAB the p-value is 0.5, while in Python is 0.2. Why is that?

**Comment by bashtage** [comment]
Can you post the data?

**Comment by bashtage** [comment]
It is possible that these are both upper limits of the p-value range

**Comment by angystallone** [comment]
Sure, you find the data in the main comment above (attachment: "**data.txt**"). Let me know if you have troubles to download it.

**Comment by bashtage** [comment]
In the full dataset I get

```
(0.26692823873330873, 0.0009999999999998
```

So the p-values is  0.001, which is the lower bound.

**Comment by bashtage** [comment]
What statsmodels version are you using?

**Comment by bashtage** [comment]
MATLAB Agrees

```
>> [a,b,c]=lillietest(mag, 'Distribution','exponential')
Warning: P is less than the smallest tabulated value, returning 0.001. 
> In lillietest (line 210) 

a =

     1


b =

   1.0000e-03


c =

    0.2669
```

**Comment by angystallone** [comment]
> What statsmodels version are you using?

0.10.2 (/usr/local/lib/python3.7/site-packages/statsmodels)

**Comment by bashtage** [comment]
That is ancient. littlefors was rewritten in 0.12. You should be using 0.12, which is the only version that we support.

Going to close since there is nothing to do. If you have issues once you upgrade, please let us know in a new thread.

**Comment by angystallone** [comment]
Ok, thank you!

**Comment by angystallone** [comment]
Sorry @bashtage, but after upgrading statsmodels to 0.12, I still get a p-value=0.2

**Comment by bashtage** [comment]
I think your upgrade didn't work. What does

import statsmodels
print(statsmodels.__version__)

show?


This is what I get
```
from numpy import loadtxt
from statsmodels.stats.diagnostic import lilliefors as lillie

mag = loadtxt('data.txt')

mmin = 0.0
upperlim = 40
lillie(mag,dist="exp")
Out[16]: (0.26692823873330873, 0.0009999999999998899)
```

**Comment by angystallone** [comment]
The version is 0.12.1

Have you tried to reproduce the issue following the code in the main comment?

**Comment by bashtage** [comment]
```
pval
Out[18]: 0.6102275346424259
```

**Comment by bashtage** [comment]
MATLAB truncates at 0.5.

**Comment by bashtage** [comment]
0.12.1 was literally just released and there are no wheels.  Perhaps try a 

```
pip install statsmodels==0.12.0
```

or use conda.

**Comment by angystallone** [comment]
Now my statsmodels version is  0.12.0
However, running the code above, I still get mc = 1.4 and p-value = 0.2

**Comment by bashtage** [comment]
Something is wrong with your install.  I think somehow python is picking up the system installed function rather than the more recent release.  

Can you try using conda (Anaconda)?

**Comment by angystallone** [comment]
**Solved**! You were right: for some reasons, PyCharm did not really install the new statsmodels version, even though it said so. I solved the problem by manually updating it (Preferences --> Project Interpreter --> statsmodels --> Install package).
Now I get the same results as you.
Thank you for your help!
