### ISSUE TITLE
DEPR: statsmodel, patsy deprecation warning: from collections import Mapping

### ISSUE THREAD

**Issue by iamtodor** [statsmodels/statsmodels#7139]
While running `pytest -v tests/` I am getting:
```
/venv/lib/python3.8/site-packages/patsy/constraint.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Mapping
```

From what I found, patsy is being used internally by statsmodel.

```
Python: 3.8.2.final.0
OS: Darwin 19.6.0 Darwin Kernel Version 19.6.0

cython: Not installed
numpy: 1.19.4
scipy: 1.5.3
pandas: 1.0.5
dateutil: 2.8.1
patsy: 0.5.1
```

**Comment by bashtage** [comment]
This is patsy, not statsmodels.  You can report it on the patsy github tracker

https://github.com/pydata/patsy

**Comment by iamtodor** [comment]
@bashtage Thank you for the reply. I see that patsy is no longer maintained - the last commit was 2 years ago. Therefore I am sure patsy won't fix it :)
Due to this warning, statsmodels might stop work with python 3.9

**Comment by bashtage** [comment]
Someone needs to fork patsy or convince the maintainer to bring them on as an owner.

**Comment by bashtage** [comment]
It is already fixed in master. Easiest solution would be to get a master release as 0.5.2.

The alternative is to see if formulaic is ready.
