### ISSUE TITLE
statsmodels.tsa.stattools.adfuller: UnboundLocalError: local variable 'bestlag' referenced before assignment

### ISSUE THREAD

**Issue by gyllila** [statsmodels/statsmodels#7146]
from statsmodels.tsa.stattools import adfuller
adf = adfuller(x, regression=‘c’, autolag=‘t-stat’)

Sometimes comes error message:
UnboundLocalError: local variable ‘bestlag’ referenced before assignment 

I found the reason: when using t-stat, bestlag is only assigned, when the last lag becomes significant the first time, so if no lag has a significant t-value, then bestlag is never assigned

I fixed this bug this way: open the file stattools.py and find the lines:
elif method == “t-stat”:
  #stop = stats.norm.ppf(.95)
  stop = 1.6448536269514722
Then add here following two lines:
  bestlag = startlag
  icbest = np.abs(results[startlag].tvalues[-1])

This way, the code won’t crash again and t-stat simply uses no lag when there is no significant value

**Comment by gyllila** [comment]
Copy and paste the following code to reproduce the issue (this issue only occurs to certain data, so I did not manage to show full code in the last post):

from statsmodels.tsa.stattools import adfuller
import numpy as np
np.random.seed(7)
x = np.random.randn(8)
adf = adfuller(x, regression=‘c’, autolag=‘t-stat’)
print(adf[1])

**Comment by bashtage** [comment]
Which version of statsmodels? This has been fixed in master and in 0.12.1 (possible 0.12.0).  Please upgrade.

**Comment by gyllila** [comment]
Thank you. Is there a quick way to show the version of statsmodels? I installed it as part of anaconda last month.

**Comment by bashtage** [comment]
’’’
import statsmodels
statsmodels.__version__
’’’

**Comment by gyllila** [comment]
Thank you, the current version works well 👍
