### ISSUE TITLE
method signature of "predict" for regression predictions (mean, confidence interval, prediction interval)

### ISSUE THREAD

**Issue by kurtforrester** [statsmodels/statsmodels#719]
I am a new user of the statsmodels module and use it for a very limited case performing OLS regression on mostly continuous data. 

I have however found an area that I feel could be improved, at least in terms of my current workflow.

Below is my workflow and how I would like to see the predict method work. 
1. do some basic regression
2. print the results

``` python
model = ols('LREO_recovery ~ HREO_recovery', df)
results = model.fit()
print results.summary()
```

As for communicating the results I produce some scatter plots and line plots of the regressed mean. Ideally, I would like to include, without much additional code, the confidence interval of the mean and a prediction interval for new observations. 

I have been reading on the R-project website and based on the call signature for their OLS predict I have come up with the following example (written in pseudo-python) as an enhanced predict method.

``` python
results.predict(values=values, interval=None, level=0.95)

# values : array-like or DataFrame
# interval : single value in [None,"confidence","prediction","both"]
# level :  float, list or tuple where [level_ci, level_pi]

```

I am aware there may be other use cases for the other regression techniques of which I not currently familiar with as I only use OLS, but this is a starting point (or end).

If if the predict method is called with the following signature:

``` python
results.predict()
```

or,

``` python
results.predict(values=array)
results.predict(values=DataFrame)
```

then the predict method would behave as it currently does.

Alternatively, if the method is called with any of the following signatures,

``` python
results.predict(values=DataFrame, interval="confidence", level=0.95)
# above call would return a DataFrame which includes the columns 'mean',
# 'uci', 'lci' for each of the observation points in the supplied DataFrame 
# at a 95 % confidence interval.

results.predict(values=DataFrame, interval="prediction", level=0.90)
# above call would return a DataFrame which includes the columns 'mean',
# 'upi', 'lpi' for each of the observation points in the supplied DataFrame 
# at a 90 % prediction interval.

results.predict(values=DataFrame, interval="both", level=(0.95, 0.90))
# above call would return a DataFrame which includes the columns 'mean',
#  'uci', 'lci', 'upi', 'lpi' for each of the observation points in the 
# supplied DataFrame at a 95 % confidence interval for the mean 
# and a 90 % prediction interval for a new observation.

results.predict(values=DataFrame, interval="both", level=0.95)
# above call would return the same as the example previous but 
# the PI and CI levels would both be 0.95.

```

the behaviour I would like to see would happen as noted in the comments. The cases presented above would also hold for when an array is supplied and the returned object could/would be an array or record array.

Any thoughts or comments? I would classify myself as a software user but would offer my time to assist in the development if this has any traction and direction.

**Comment by josef-pkt** [comment]
I'm closing this as outdated

the pattern is now to have `get_prediction` methods to include standard errors and confidence/prediction intervals
`predict` stays unchanged with just predicting expected values or similar statistics.
