### ISSUE TITLE
seasonal_decomposition with pandas:  freq T not understood. Please report if you think this is in error.

### ISSUE THREAD

**Issue by urands** [statsmodels/statsmodels#7194]
seasonal_decomposition don't support some periods like: 30min 15min 1min
![image](https://user-images.githubusercontent.com/1263969/101098829-a99e6100-35d4-11eb-93e1-ee54977614f8.png)

**Comment by ChadFulton** [comment]
Currently, `seasonal_decompose` will automatically select a period for the seasonal component according to the following map:

```python
{
    'A': 1,
    'Q': 4,
    'M': 12,
    'W': 52,
    'D': 7,
    'B': 5,
    'H': 24
}
```

If you have any other frequency, then we don't have a built-in rule to automatically select the period, so you must specify the `period` argument.

For example, if you are assuming that the seasonal period is an hour (i.e. repeats every 60 minutes), then you would do something like:

```python
seasonal_decompose(x_train, period=60)
```

**Comment by ChadFulton** [comment]
Closing since nothing to do, but feel free to follow up.
