### ISSUE TITLE
MAINT: future for Travis unit testing

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#7201]
Travis CI is dropping free support for open source packages
https://groups.google.com/g/pystatsmodels/c/509vmT4wWAE/m/38Kku3uYCAAJ

I had sent them an email about getting a free time allocation. The response was that it is only for `.com`, and that `.org` will be discontinued. We still have a `.org` account and I didn't switch (yet).

Based on the response of other packages, scikit-learn, numpy, scipy, it doesn't look like anyone is getting enough free time allocation to continue using it as before.

So we will have to mostly or completely switch away from Travis. 
We have already large part of the testing on azure. appveyor also still works as always.

I'm keeping `.org` on travis for now because it's still working.

**Comment by bashtage** [comment]
Azure is the only way IMO.

**Comment by josef-pkt** [comment]
Do we need to make any changes when Travis stops working for us?
It looks like we already have everything covered in Azure.

**Comment by bashtage** [comment]
Azure needs to become more flexible.  It (and Appveyor) runs latest releases so it is easy to create backward compact issues w/o Travis.

**Comment by josef-pkt** [comment]
https://travis-ci.org/github/statsmodels/statsmodels shows now the header:
`Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.`

**Comment by josef-pkt** [comment]
@bashtage We don't have automatic doc build for `devel` anymore, do we?

last update according to history of `devel` was on March 25
https://github.com/statsmodels/statsmodels.github.io/commits/master/devel

**Comment by bashtage** [comment]
You should try and migrate to see if it will resume.  But I suspect travis is dead.  Will need to get it working again before release; I am using github actions in my own projects to build docs which works well enough.

**Comment by josef-pkt** [comment]
Can we use github actions for the statsmodels docs?

I worry about surprise bills when switching to travis.com. It might be feasible if we only use it for doc builds.

**Comment by bashtage** [comment]
.com is free as long as you are on the free plan.  It will probably run out of credits though.

GH actions should be usable, although it is more complex than what I've been doing since I push to a branch rather than another repo.

**Comment by josef-pkt** [comment]
closing, we dropped travisci
