### ISSUE TITLE
ENH: Fixed parameters in Hannan-Rissanen

### ISSUE THREAD

**Issue by madhushree14** [statsmodels/statsmodels#7202]
#### Describe alternatives you have considered
A clear and concise description of any alternative solutions or features you have considered.

#### Additional context
Add any other context about the feature request here.

**Comment by madhushree14** [comment]
Assigning the enhancement to myself.

**Comment by ChadFulton** [comment]
Thanks for opening this issue. How are things going?

**Comment by ChadFulton** [comment]
For reference, here is the note about this PR from a previous issue, #6159:

>> Hi Chad,
>I would like to pick up the "Support for fixed parameters". would you please share some more details on this enhancement?
>
>That would be much appreciated, thanks!
>
>First, a little background (maybe you already know this, but just in case you haven't run into this feature before). In our models, all of the parameters are typically estimated by maximum likelihood. But in some cases, you might want to "fix" one of the parameters to a particular value, and then estimate the *other* parameters by maximum likelihood. A simple example is:
>
>```python
>endog = np.random.normal(size=100)
>
># AR(1) model with an intercept
>mod = sm.tsa.SARIMAX(endog, order=(1, 0, 0), trend='c')
>
># Suppose we want to estimate the AR(1) coefficient, but we want to specify the intercept to be 0.5
>with mod.fix_params({'intercept': 0.5}):
>    res = mod.fit()
>print(res.summary())
>```
>
>this results in:
>
>```
>                               SARIMAX Results                                
>==============================================================================
>Dep. Variable:                      y   No. Observations:                  100
>Model:               SARIMAX(1, 0, 0)   Log Likelihood                -146.547
>Date:                Thu, 10 Dec 2020   AIC                            297.094
>Time:                        19:44:35   BIC                            302.305
>Sample:                             0   HQIC                           299.203
>                                - 100                                         
>Covariance Type:                  opg                                         
>=====================================================================================
>                        coef    std err          z      P>|z|      [0.025      0.975]
>-------------------------------------------------------------------------------------
>intercept (fixed)     0.5000        nan        nan        nan         nan         nan
>ar.L1                -0.1595      0.096     -1.655      0.098      -0.348       0.029
>sigma2                1.0972      0.144      7.631      0.000       0.815       1.379
>===================================================================================
>Ljung-Box (L1) (Q):                   0.13   Jarque-Bera (JB):                 2.30
>Prob(Q):                              0.72   Prob(JB):                         0.32
>Heteroskedasticity (H):               1.26   Skew:                            -0.37
>Prob(H) (two-sided):                  0.50   Kurtosis:                         2.97
>===================================================================================
>
>Warnings:
>[1] Covariance matrix calculated using the outer product of gradients (complex-step).
>```
>
>A more complete set of examples can be found in this notebook: https://www.statsmodels.org/stable/examples/notebooks/generated/statespace_fixed_params.html.
>
>This feature is available in state space models (and also in the new `ETSModel` class), but it's not yet been implemented for all of the new ARIMA-type estimators referenced here (including Innovations MLE, Hannan-Rissanen, and GLS).
>
>I think the easiest place to get started would be adding fixed parameters to the Hannan-Rissanen estimator, which is the `hannan_rissanen` function in the file `statsmodels/tsa/arima/estimators/hannan_rissanen.py`. The basic idea here, is that ultimately the parameters are estimated by least squares (see lines 121 and 141), and so fixing certain parameter values is straightforward.
>
>To see why it is straightforward with OLS, consider the following regression equation:
>
>`y = a + b x_1 + c x_2 + e`
>
>If we want to fix `b = 2`, then the equation is `y = a + 2 x_1 + c x_2 + e` or we can rewrite it as a different regression
>
>`z = a + c x_2 + e`
>
>where we have created the new variable `z` according to `z = y - 2 x_1`.
>
>So basically, what I suggest is the following:
>
>1. Create a new Github issue (e.g. `ENH: Fixed parameters in Hannan-Rissanen`) for a more convenient location for discussion and advice going forwards.
>
>2. Add a new argument `fixed_params` to `hannan_rissanen`, which should accept a dictionary with parameter names as keys and the fixed numbers as values.
>
>3. In each case (lines 121 and 141), if there are fixed parameters, you need to remove the columns that correspond to those parameters from the `exog` arrays being passed to `OLS` (e.g. in line 121, the `lagged_endog` variable is passed as the `exog` argument), multiply them by the given fixed parameter value, and then subtract that to create a new endogenous variable (i.e. like the `z` I mentioned above).
>
>Also, for the first attempt, I would just raise a `NotImplementedError` if `unbiased=True` (since I haven't really thought about fixed parameter values in this case).
>
>Thanks!

**Comment by ChadFulton** [comment]
> Hi Chad, could you please help me how to identify the corresponding column when removing the parameter from the 2d array?

Sure! So to start, I would pull the `exog` array out of the `OLS` call, like:

```
exog = np.c_[lagged_endog[ix:], lagged_resid]
```

Now the `fixed_params` argument should be a dictionary with parameter names as keys and the fixed numbers as values, so you need to map parameter names to columns of `exog`.

The parameter names associated with the columns of this full `exog` array are given by `spec.param_names` (where `spec` is defined in line 91).

So for each `key, value` pair in `fixed_params`, you just need to get the index of `key` in `spec.param_names`, and that will tell you the column in `exog`.

**Comment by madhushree14** [comment]
Hi Chad, 
after subtraction, the array should be passed as the new exog to the OLS right?

**Comment by ChadFulton** [comment]
You'll be creating both a new `endog` and a new `exog`:

- The new `endog` is the `z` I described in my earlier post, so it will end up being something like `new_endog = endog - fixed_params['ar.L1'] * exog[:, 0] - ...`
- The new `exog` is the original `exog` but with fewer columns, since you need to remove the columns associated with the fixed parameters (these are the same columns that were subtracted from `endog`)

Hope that helps

**Comment by madhushree14** [comment]
Hi Chad, I have made the required changed,,,, kindly review once

**Comment by ChadFulton** [comment]
I think you still need to create a pull request so that we can review your code.
