### ISSUE TITLE
Question about SARIMA initialization

### ISSUE THREAD

**Issue by guilhermebodin** [statsmodels/statsmodels#7204]
Hello, not a bug or a feature request just a question about the implementation.

Why does it happen that in the P1 matrix, the first state covariance we get different results in this case?

```python
import numpy as np
import pandas as pd
import statsmodels.api as sm
from datetime import datetime
import requests
from io import BytesIO

air2 = requests.get('https://www.stata-press.com/data/r12/air2.dta').content
data = pd.read_stata(BytesIO(air2))
data.index = pd.date_range(start=datetime(data.time[0], 1, 1), periods=len(data), freq='MS')
data['lnair'] = np.log(data['air'])

# Fit the model
mod = sm.tsa.statespace.SARIMAX(data['lnair'], order=(1,1,0), seasonal_order=(1,1,0,12))
res = mod.fit(disp=False)
print(res.summary())
np.matrix(res.model.ssm._statespace.initial_state_cov)
res.filtered_state_cov[:, :, 0]
```

For `np.matrix(res.model.ssm._statespace.initial_state_cov)` we get the diagonal of non-arma states with the diagonal of `1e6` the same as we see in the book of Koopman chapter 5.6.2. But in `res.filtered_state_cov[:, :, 0]` some of the rows and columns of non-arma states are different.

First column of  `np.matrix(res.model.ssm._statespace.initial_state_cov)` :
```python
        [ 1.00000000e+06,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00]
```

First column of  `res.filtered_state_cov[:, :, 0]` :
```python
      [ 5.00000001e+05,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -4.99999999e+05, -1.07899852e-03, -8.73854715e-09,
         2.33345165e-08, -6.23100904e-08,  1.66386450e-07,
        -4.44301244e-07,  1.18641629e-06, -3.16808392e-06,
         8.45972509e-06, -2.25899788e-05,  6.03219536e-05,
        -1.61077534e-04, -7.01598574e-05]
```

The same happens with non seasonal models

```python
mod = sm.tsa.statespace.SARIMAX(data['lnair'], order=(2,1,1))
res = mod.fit(disp=False)
print(res.summary())
np.matrix(res.model.ssm._statespace.initial_state_cov)
res.filtered_state_cov[:, :, 0]
```
First column of  `np.matrix(res.model.ssm._statespace.initial_state_cov)` :
```python
[ 1.00000000e+06,  0.00000000e+00,  0.00000000e+00]
```

First column of  `res.filtered_state_cov[:, :, 0]` :
```python
[ 0.01135731, -0.01135731,  0.0087693 ]
```

I am interested in these kinds of implementations and am currently trying to do some of them in Julia (https://github.com/LAMPSPUC/StateSpaceModels.jl)

**Comment by ChadFulton** [comment]
Hi @guilhermebodin, nice to hear from you, and it's nice to see the work you're doing on state space models in Julia.

If I understand right, maybe this is just a misunderstanding of our variable naming strategy. What we do is:

- P_t -> `predicted_state_cov`
- P_{t|t} -> `filtered_state_cov`

So that `res.predicted_state_cov[..., 0] == res.filter_results.initial_state_cov`.

Does that clear things up?

**Comment by guilhermebodin** [comment]
Yes! Thanks a lot @ChadFulton! The naming is perfect, I think I got confused after some numerical errors I am facing in my development and tried debugging with statsmodels.

Thanks for the state space implementations, I am learning a lot with them.
