### ISSUE TITLE
[Question] OLS with less parameters than exog variables

### ISSUE THREAD

**Issue by 4aHxKzD** [statsmodels/statsmodels#7207]
Is there a way to define a model where the number of parameters is less than the number of exog variables?
For example:

``` python
y = x_1 * beta  + x_2 + noise
```
where `beta` is the parameter and `x_1` and `x_2` are the exog variables.

**Comment by bashtage** [comment]
Just regress

y - x1 ~ 1 + x2

**Comment by bashtage** [comment]
Closing as answered.  This is a standard transformation of regression models.

**Comment by 4aHxKzD** [comment]
thanks dude

**Comment by josef-pkt** [comment]
In GLM and some discrete models there is an `offset` option for this. 

But in the linear case, the above is all we need, except you have to add it back to the prediction to get the original y.
