### ISSUE TITLE
Results of STL decomposition differ from R function `stl()`

### ISSUE THREAD

**Issue by AlainOUYANG** [statsmodels/statsmodels#7212]
#### Results of STL decomposition differ from R function `stl()`

Recently I started to use statsmodels for conducting STL decomposition and I found some difference between the results from Python `statsmodels.tsa.seasonal.STL` and from R function `stl()`in the famous `forecast` library. Here is my code in Python and in R. The data I use is the `co2` dataset that I extracted from R.

#### Code Sample

CO2 dataset: [co2.txt](https://github.com/statsmodels/statsmodels/files/5705693/co2.txt)

Python code:

```python
import pandas as pd
from statsmodels.tsa.seasonal import STL
co2 = pd.read_csv('co2.txt')
res = STL(co2.x, period=12, seasonal=7).fit()
print(res.trend.head())
```

R code:

```R
library(forecast)
res = stl(co2, s.window = 7)
print(trendcycle(res)[1:5])
```

Here is the results I got.

Output from Python:

```Python console
0    315.337913
1    315.424206
2    315.511371
3    315.599196
4    315.687369
Name: trend, dtype: float64
```

Output from R:

```R console
[1] 315.3221 315.4107 315.4993 315.5880 315.6770
```

There is some slight difference between these 2 implementations. Is that caused by the reason that you explained in the notes in [the documentation](https://www.statsmodels.org/dev/generated/statsmodels.tsa.seasonal.STL.html#statsmodels.tsa.seasonal.STL)?

> Derived from the NETLIB fortran written by [1]. The original code contains a bug that appears in the determination of the median that is used in the robust weighting. This version matches the fixed version that uses a correct partitioned sort to determine the median.

I also made a more complete comparison which you can download here: [difference stl python r.xlsx](https://github.com/statsmodels/statsmodels/files/5705715/difference.stl.python.r.xlsx)

Please kindly help. Thanks!

**Comment by bashtage** [comment]
I think that is the difference.  The version in statsmodels is faithful to the fortran and is tested against it.

**Comment by bashtage** [comment]
Closing since nothing for us to do as devs.  But feel free to ask related questions.

**Comment by AlainOUYANG** [comment]
Thank you for the quick reply!
Btw, is there any possible way to replicate the same functionality of R? I know that increase devs' work but maybe it's better to provide a choice to the user (at least mark in the notes that their results can differ from the one get from R).

**Comment by bashtage** [comment]
PRs for documentation are welcome.  R is not the reference implementation, so it doesn't make sense to replicate their deviations from the reference.

**Comment by AlainOUYANG** [comment]
I see. Thanks for your help!
