### ISSUE TITLE
Statsmodels Memory Error although free RAM using MixedLM fit

### ISSUE THREAD

**Issue by bobbyhaze** [statsmodels/statsmodels#7214]
i am facing the following problem. I am fitting a mixed linear model with statsmodels using ```smf.mixedlm```. I have gene expression data and i am fitting one model per gene over several conditions. The code works perfectly fine until one gene, where i have 107 rows with 6 observations. There i get the following memory error tracing to a numpy array in the statsmodels code:
```
Traceback (most recent call last):
  File "LMM.py", line 77, in <module>
    model=smf.mixedlm("value ~ variable + Sequence", temp, groups='Accession',re_formula="~Sequence")
  File "C:\Users\Kevin\.conda\envs\Keras_with_python_3_6\lib\site-packages\statsmodels\regression\mixed_linear_model.py", line 1025, in from_formula
    formula, data, *args, **kwargs)
  File "C:\Users\Kevin\.conda\envs\Keras_with_python_3_6\lib\site-packages\statsmodels\base\model.py", line 194, in from_formula
    mod = cls(endog, exog, *args, **kwargs)
  File "C:\Users\Kevin\.conda\envs\Keras_with_python_3_6\lib\site-packages\statsmodels\regression\mixed_linear_model.py", line 811, in __init__
    self._lin, self._quad = self._reparam()
  File "C:\Users\Kevin\.conda\envs\Keras_with_python_3_6\lib\site-packages\statsmodels\regression\mixed_linear_model.py", line 1325, in _reparam
    quad.append(np.zeros((k_tot, k_tot)))
MemoryError: Unable to allocate 68.8 MiB for an array with shape (3003, 3003) and data type float64
```
However, when i check my RAM usage during the calculations i never allocate more than 6GB out of 16GB. I tried running the code on a server that has 100GB RAM available with the same result. 

My code looks as follows:
```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from scipy.stats import ttest_ind
import warnings
from DynaTMT.DynaTMT import PD_input
from sklearn.metrics import roc_curve, RocCurveDisplay, auc
import statsmodels.formula.api as smf
import sys

if __name__ == "__main__":
    warnings.filterwarnings("ignore")
    print(sys.maxsize)
    wd = "C://Users/Kevin/Desktop/MassSpec/Ecoli_spike_in/"
    Peptide_data=pd.read_excel(wd+"test_01.xlsx",header=0, engine="openpyxl")
    channels=[col for col in Peptide_data.columns if 'Abundance:' in col] 
    Peptide_data = Peptide_data.dropna(subset=channels)
## Add Noise to the data for testing
    for peptide in Peptide_data.index:
        mean = Peptide_data.loc[peptide,channels].mean()
        noise = np.random.normal(mean, 0.5, [len(channels),1]) - mean
        
        Peptide_data.loc[peptide,channels] =     Peptide_data.loc[peptide,channels] + noise.flatten()

    Peptides_for_LM = Peptide_data[channels]
    Peptides_for_LM['Species']=Peptide_data['Species Names']
    Peptides_for_LM['Sequence']=Peptide_data['Annotated Sequence']
    Peptides_for_LM['Accession']=Peptide_data['Master Protein Accessions']
    del Peptide_data
    melted_Peptides=Peptides_for_LM.melt(id_vars=['Accession','Species','Sequence'],value_vars=channels)
    del Peptides_for_LM
    melted_Peptides.replace(to_replace=channels, value=['Ctrl','Ctrl','Ctrl','1.15','1.15','1.15','1.5','1.5','1.5','2','2'],inplace=True)
    melted_Peptides=melted_Peptides[melted_Peptides['variable'].str.contains('Ctrl|1.5')]
    melted_Peptides['value']=np.log2(melted_Peptides['value'])
    melted_Peptides=melted_Peptides.dropna()

    grouped=melted_Peptides.groupby(by=['Accession'])
    result_dict_LMM={}
    for i in grouped.groups:
        temp=grouped.get_group(i)
        print(i)
        model=smf.mixedlm("value ~ variable + Sequence", temp, groups='Accession',re_formula="~Sequence")
        try:
            result=model.fit()
            df = result.summary().tables[1]
            try:
                a=[]
                a.append(float(df.iloc[1,3]))
                a.append(list(temp['Species'])[0])
                result_dict_LMM[i]=a
            except ValueError:
                print("Error with: "+i)
        except:
            pass
```
The data frame after filtering looks like this:
```
Accession       Species                Sequence variable     value
0  Q15149-1  Homo sapiens      [R].LAEVEAALEK.[Q]     Ctrl  3.768618
1  Q15149-1  Homo sapiens    [R].LEDLLQDAQDEK.[E]     Ctrl  3.744776
2  Q15149-1  Homo sapiens  [R].LQEAGILSAEELQR.[L]     Ctrl  3.688177
3  Q15149-1  Homo sapiens    [K].LQNVQIALDYLR.[H]     Ctrl  3.346011
4  Q15149-1  Homo sapiens      [R].LLEAAAQSTK.[G]     Ctrl  4.522910
[462 rows x 5 columns]
```

I tried the code with Python 3.6 and 3.8 using:
```
patsy==0.5.1
scipy==1.4.1
statsmodels==0.11.0
pandas==1.1.0
numpy==1.18.1
```

Can anyone please help with that problem? As i said, the same code works perfectly fine until that one array. 

Have a nice day :)

**Comment by kshedden** [comment]
Can you explain how Sequence and Accession are related, i.e. is one nested in the other?

I don't think you want re_formula="~Sequence".  That will give you a separate variance parameter for every Sequence, and an independent realization of those random effects for every Accession.

Perhaps vc_formula="0+C(Sequence)" would be more what you want.  This will have a single variance parameter but independent realizations for every Sequence within every Accession value.

**Comment by bobbyhaze** [comment]
Hi Kerby,

The sequences are part of the Accession and can be counted as repeated measures of the same Accession item. However, each of the sequence items has different physical properties, resulting in a different intercept for each item (those are measured also in replicates). Each of the sequences in addition has a different slope in response to the condition (```variable``` in this case). The variance for each sequence might also be different, but this is what i wanted to test, to see if this model would gain additional statistical power in a ground truth dataset i measured.

**Comment by kshedden** [comment]
I think it makes sense to use groups="Accession" and vc_formula="0+C(Sequence)".  This is a two-level variance components model with three variance parameters: Accession variance, Sequence variance, and unexplained variance.

If y(i, j, k) is the k'th measurement for the j'th sequence in the i'th accession group, then the model is
 
y(i, j,k) = mu + a(i) + b(i,j) + e(i,j,k)

where a(i) ~ N(0,  v1), b(i,j) ~ N(0, v2) and e(i,j,k) ~ N(0, v3), where the a(i), b(i,j) and e(i,j,k) are mutually independent.

The only parameters in the model are v1, v2, v3, and the intercept mu.

If you use re_formula="~Sequence" then every sequence has a different variance, and there are arbitrary correlations among the sequence effects.  This leads to a huge number of parameters, which is why you were getting a memory error.

**Comment by bobbyhaze** [comment]
Thanks, thats exactly what i wanted.
