### ISSUE TITLE
Does 'adfuller' default to 'maxlag' or 'autolag' criterion when both are specified?

### ISSUE THREAD

**Issue by eflopez1** [statsmodels/statsmodels#7238]
Apologies for the relatively simple question. In the event that a value is entered for 'maxlag' and for 'autolag' in the function

`statsmodels.tsa.stattools.adfuller`

which does the test default to? Thanks.

**Comment by josef-pkt** [comment]
AFAIR, maxlag defines the upper bound for lags used with autolag any value except None. So both are used

if autolag = None, then maxlag is the only lag used without lag search. 

if maxlag is None, then a default depending on nobs is used with autolag
