### ISSUE TITLE
`STLForecastResults` object can't be pickled

### ISSUE THREAD

**Issue by joshlk** [statsmodels/statsmodels#7248]
#### Describe the bug

`STLForecastResults` object can not be pickled. It raises the following error:

```
TypeError: no default __reduce__ due to non-trivial __cinit__
```

It's useful to be able to pickle results objects when using multi-processing and persisting results.

#### Code Sample, a copy-pastable example if possible

```python
from statsmodels.tsa.forecasting.stl import STLForecast
from statsmodels.tsa.arima.model import ARIMA
import numpy as np
import pickle

# Create a `STLForecastResults` object
endog = np.arange(10)
regr = STLForecast(endog, ARIMA, period=2)
results = regr.fit()

# Try and pickle
pickle.dumps(results)
```

Output:

```
TypeError: no default __reduce__ due to non-trivial __cinit__
```

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.7.7.final.0
OS: Darwin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.12.1 (/opt/anaconda3/lib/python3.7/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.21 (/opt/anaconda3/lib/python3.7/site-packages/Cython)
numpy: 1.19.2 (/opt/anaconda3/lib/python3.7/site-packages/numpy)
scipy: 1.5.2 (/opt/anaconda3/lib/python3.7/site-packages/scipy)
pandas: 1.1.5 (/opt/anaconda3/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.1 (/opt/anaconda3/lib/python3.7/site-packages/dateutil)
patsy: 0.5.1 (/opt/anaconda3/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.3.2 (/opt/anaconda3/lib/python3.7/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 1.0.0 (/opt/anaconda3/lib/python3.7/site-packages/joblib)

Developer Tools
================

IPython: 7.19.0 (/opt/anaconda3/lib/python3.7/site-packages/IPython)
    jinja2: 2.11.2 (/opt/anaconda3/lib/python3.7/site-packages/jinja2)
sphinx: 3.4.1 (/opt/anaconda3/lib/python3.7/site-packages/sphinx)
    pygments: 2.7.3 (/opt/anaconda3/lib/python3.7/site-packages/pygments)
pytest: 6.2.1 (/opt/anaconda3/lib/python3.7/site-packages/pytest)
virtualenv: 20.2.2 (/opt/anaconda3/lib/python3.7/site-packages/virtualenv)

</details>

**Comment by joshlk** [comment]
Wow that’s the quickest bug fix I’ve seen in a long time! Amazing

**Comment by bashtage** [comment]
Fortunately I'd done this a lot fo different extension modules.
