### ISSUE TITLE
hpfilter 2d array support 

### ISSUE THREAD

**Issue by Auto-Ken** [statsmodels/statsmodels#7253]
bk filter and cf filter in same category support 2d array. But hp filter doesn't.
Any reason to be unable to expand input array dimension?

![image](https://user-images.githubusercontent.com/38831582/104419787-4ed92b80-55bc-11eb-9550-fd9d1f326a32.png)

**Comment by bashtage** [comment]
No reason, just a lack of implementation.  I think these just use loops internally and so there isn't much of a gain to having 2d inputs.
