### ISSUE TITLE
Documentation - one sided or two sided

### ISSUE THREAD

**Issue by TomMaullin** [statsmodels/statsmodels#7261]
Apologies, I wasn't sure where to leave this feedback but I am using the `fwe` correction from the `statsmodels.stats.multitest` and could not tell from the documentation: does the `statsmodels.stats.multitest` assume the P-values are for one-tailed or two-tailed hypotheses? 

Thank you for your help.

**Comment by josef-pkt** [comment]
pvalue corrections do not directly depend on the hypothesis, that is it applies to both one-sided and two sided hypothesis/alternatives.
Some of them have assumption on the correlation across hypothesis tests of the underlying test statistics.

**Comment by TomMaullin** [comment]
In the case of Bonferroni for example, does `statsmodels` reject using alpha/(number of tests) from one tail (i.e. reject wherever p<alpha/(number of tests)) or does it reject using alpha/(2*(number of tests)) from each tail (i.e. wherever p<alpha/2*(number of tests) and 1-p<alpha/2*(number of tests))?

**Comment by josef-pkt** [comment]
The pvalue itself already contains the two-sided versus one-sided adjustment. two-sided = 2 * min(one-sided).
pvalue correction does not change or revert that.

So, Bonferroni corrected pvalue is just `pvalue / number_of_tests`, and reject if that is, say, <=0.05 for 5% FWER
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/stats/multitest.py#L148

**Comment by TomMaullin** [comment]
Ah okay - great I see thank you!
