### ISSUE TITLE
TST/BUG: chisquare test with new scipy raises exception, tail observations are ignored in unit test 

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#7267]
test failure with future scipy
https://dev.azure.com/statsmodels/statsmodels-testing/_build/results?buildId=3091&view=logs&j=d3aeec9b-5735-51da-6bfa-db4d86dad819&t=4a8eef27-4d92-5b93-41e2-3d1348afd29c

observed and predicted don't add up to 1 closely enough

```
self = <statsmodels.discrete.tests.test_discrete.TestGeneralizedPoisson_underdispersion object at 0x7f25270c6d30>

    def test_predict_prob(self):
        res = self.res
        endog = res.model.endog
        freq = np.bincount(endog.astype(int))
    
        pr = res.predict(which='prob')
        pr2 = sm.distributions.genpoisson_p.pmf(np.arange(6)[:, None],
                                        res.predict(), res.params[-1], 1).T
        assert_allclose(pr, pr2, rtol=1e-10, atol=1e-10)
    
        from scipy import stats
>       chi2 = stats.chisquare(freq, pr.sum(0))
```

failure is exception raised now by scipy

```
>               raise ValueError(msg)
E               ValueError: For each axis slice, the sum of the observed frequencies must agree with the sum of the expected frequencies to a relative tolerance of 1e-08, but the percent differences are:
E               0.0014010692380163618
```

**Comment by josef-pkt** [comment]
I'm going to fix this soon, either renormalize as quickfix, or add the missing have a more accurate pmf

My guess is that the last cell in PR should include the `sf` value for non-observed cells, or renormalize and consider as truncated distribution.

(for unit tests it doesn't matter much, statistical noise is much larger than numerical imprecision from truncation)

**Comment by bashtage** [comment]
I opened an issue on scipy for this. I don't think their food is
technically correct but I also think they won't change.

**Comment by josef-pkt** [comment]
I saw your issue.
The threshold is debatable, but the idea in scipy is to prevent user error in specification of arguments.

**Comment by josef-pkt** [comment]
I just saw that there is a second test failure in `pre` release environment

scipy.stats.skew raises

```
        m3 = moment(a, 3, axis)
        with np.errstate(all='ignore'):
>           zero = (m2 <= (np.finfo(m2.dtype).resolution * a.mean(axis))**2)
E           AttributeError: 'float' object has no attribute 'dtype
```

scipy skew is called from our jarque_bera, which is called from stats.descriptivestats

```
statsmodels/stats/descriptivestats.py:450: in <lambda>
    lambda x: list(jarque_bera(x.dropna())), result_type="expand"
statsmodels/stats/stattools.py:123: in jarque_bera
    skew = stats.skew(resids, axis=axis
```

I don't see anything wrong, mabye/likely a bug in scipy.
jarque_bera uses np.asarray, so pandas shouldn't be involved when calling skew.

**Comment by josef-pkt** [comment]
the second failure with scipy seems to come from calling skew with an empty array
https://github.com/scipy/scipy/issues/13410
