### ISSUE TITLE
statsmodels module 'statsmodels.multivariate.api' has no attribute 'multivariate_ols'

### ISSUE THREAD

**Issue by moonj94** [statsmodels/statsmodels#7268]
#### Describe the bug

As described, there is no attribute multivarate_ols for me. I have python 3.7.7 statsmodel 0.12.1

#### Code Sample, a copy-pastable example if possible

```python
# Your code here that produces the bug
# This example should be self-contained, and so not rely on external data.
# It should run in a fresh ipython session, and so include all relevant imports.
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

I wish to see the function existent and allowing me to perform multivariate regression
but instead I see
`statsmodels module 'statsmodels.multivariate.api' has no attribute 'multivariate_ols'`

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
Python: 3.7.7.final.0
OS: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: en_CA.UTF-8
LANG: en_CA.UTF-8

statsmodels
===========

Installed: 0.12.1 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.19.2 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/numpy)
scipy: 1.6.0 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/scipy)
pandas: 1.2.0 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.1 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/dateutil)
patsy: 0.5.1 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.3.2 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: 1.2.0 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/cvxopt)
joblib: 1.0.0 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/joblib)

Developer Tools
================

IPython: 7.18.1 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/IPython)
    jinja2: 2.11.2 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/jinja2)
sphinx: 3.2.1 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/sphinx)
    pygments: 2.7.4 (/Users/jaemoon/opt/anaconda3/envs/phd/lib/python3.7/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed
</details>

**Comment by kshedden** [comment]
For some reason it is called _MultivariateOLS.  You can see how to use it from the test file:

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/multivariate/tests/test_multivariate_ols.py

**Comment by moonj94** [comment]
I understand its called _MUltivariateOLS, but when I type in:
`from statsmodels.multivariate.multivariate_ols import _MultivariateOLS`

It shows the error `statsmodels module 'statsmodels.multivariate.api' has no attribute 'multivariate_ols'`
so I can't even get to the _MultivariateOLS

**Comment by moonj94** [comment]
and is it possible to regularize a SUR model? I can't seem to find any options for that.

**Comment by bashtage** [comment]
No.  Ridge/Lasso have not been implemented.

**Comment by kshedden** [comment]
I don't know what is the issue with your import.  Our test suite has exactly the line that you are using `from statsmodels.multivariate.multivariate_ols import _MultivariateOLS` and we never release with failing tests.  Also, there is no mention of `multivariate_ols` in the api file.

**Comment by moonj94** [comment]
could it be that I am using python 3.7.7? 

and I was just going by this page:
https://www.statsmodels.org/stable/generated/statsmodels.multivariate.multivariate_ols._MultivariateOLS.html#statsmodels.multivariate.multivariate_ols._MultivariateOLS

**Comment by jseabold** [comment]
Your python version shouldn't matter here. Closing this, as I'm unable to replicate the error with the same environment. You might try uninstalling and re-installing statsmodels in your environment. You might also check the folder where statsmodels is installed. Poke around in there and see if that file is indeed there. Feel free to re-open, if you still think it's a bug somewhere.
