### ISSUE TITLE
fit() got an unexpected keyword argument 'trend' when using ARIMA.fit()

### ISSUE THREAD

**Issue by antoinecomp** [statsmodels/statsmodels#7289]
#### Describe the bug

I am using an ARIMA model of statsmodels version 0.12.1 in order to predict the trend of a Pandas Series. According to [the docs](https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima_model.ARIMA.fit.html) It seems that we need to provide a few parameters in order to fit the model. So I provided parameters `method` and `trend` but when compiling the latter wasn't expected to be provided ...

#### Code Sample, a copy-pastable example if possible

Indeed with the values `[2599.  2599.  3998.  3998.  1299.  1499.  1499.  2997.5  749.5]` and the model:

```python
    import statsmodels.tsa.arima.model as smt
    import pandas as pd
    ts = pd.DataFrame('something')
    print(ts.values)
    ranges = range(1, 5)
    for difference in ranges:
        # try:
        tmp_model = smt.ARIMA(ts.values, order=(list(ranges), difference, list(ranges))).fit(method='mle', trend='nc')
```

Indeed, it returns:

```
(venv) C:\Users\antoi\Documents\Programming\Learning\DataScience\futureSales>python main.py
main.py:16: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  "item_cnt_day"].agg({
0.12.1
[2599.  2599.  3998.  3998.  1299.  1499.  1499.  2997.5  749.5]
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    tmp_model = smt.ARIMA(ts.values, order=(list(ranges), difference, list(ranges))).fit(method='mle', trend='nc')
TypeError: fit() got an unexpected keyword argument 'trend'
```

<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

</details>

**Comment by bashtage** [comment]
The new ARIMA requires trend to be passed when you create the model.

```
 smt.ARIMA(ts.values, order=(list(ranges), difference, list(ranges)),trend='n').fit(method='mle')
```

Note "n" not "nc".
