### ISSUE TITLE
There was a problem about packaging StatsModels

### ISSUE THREAD

**Issue by gongtian1234** [statsmodels/statsmodels#7294]
When I packaged the py file containing the StatsModels in the Conda environment，the resulting exe file will work well in the conda environment.But when I try to execute the same EXE file in CMD, I get an error that the EXE has stopped running.And after many of my tests, it was almost certain that this was due to the packaging of the StatsModels, and when I removed the reference to the StatsModels, it worked in both environments.I wonder how this kind of problem should be solved. Thanks.

**Comment by bashtage** [comment]
You probably need to make sure you include things like BLAS and LAPACK libraries.

**Comment by bashtage** [comment]
You probably want to ask on a repo dedicated to packaging since we don't have support running statsmodels any other way than through Python in an installation.
