### ISSUE TITLE
ARIMAX Time Series Error: "LinAlgError: SVD did not converge"

### ISSUE THREAD

**Issue by Shane-McCallum** [statsmodels/statsmodels#7295]
Hey folks! My familiarity with python and Arima is rather amateur. I am hoping you all could take a look at my notebook here and let me how to fix the SVD issue with my ARIMAX model. I am trying to test to see if S&P index has an exogenous relationship with Gold. 

When I run my cross-validation function to find the best p,d, and q values I get 5, 1, 5:

`Train-Test-Split:
maindf['diffGLD'] = maindf['GLD(USD)'].diff()
maindf['diffSPX'] = maindf['SPX(USD)'].diff()
date = maindf.index
maindf['SPX_lag']=maindf['diffSPX'].shift()
maindf.dropna(inplace=True)
GLD_end = maindf['GLD(USD)']
SPX_ex = maindf['SPX_lag']
m = len(GLD_end)
size = int(len(GLD_end)*0.8)
train, test = GLD_end[0:size], GLD_end[size:m]
ex_train, ex_test = SPX_ex[0:size], SPX_ex[size:m]
date_test = date[size:]

def evaluate_arimax_model(y, X, model_order):
    model_arimax = ARIMA(endog = y, exog=X, order=model_order).fit()
    AIC = model_arimax.aic
    BIC = model_arimax.bic
    LLF = model_arimax.llf
    RMSE = RMSEfromResid(model_arimax.resid)
    return([AIC, BIC, LLF, RMSE])

warnings.filterwarnings("ignore")
p_values = [0,1,2,3,4,5]
d_values = [1]
q_values = [0,1,2,3,4,5]
data = list()
for p in p_values:
    for d in d_values:
        for q in q_values:
            order = (p,d,q)
            try:
                [AIC, BIC, LLF, RMSE] = evaluate_arimax_model(train, ex_train, order)
                data.append([order,AIC, BIC, LLF, RMSE])
            except:
                continue

ARIMAX_Models = pd.DataFrame(data,columns=['ARIMAX', 'AIC', 'BIC', 'Maximum Log-Likelihood', 'RMSE'],dtype=float)

evaluate_arimax_model(train, ex_train, order)
ARIMAX_Models.sort_values(by=['RMSE'])

ARIMAX | AIC | BIC | Maximum Log-Likelihood | RMSE
(5, 1, 5) | 4368.207337 | 4425.432261 | -2171.103669 | 8.849900`

But when I enter those in for the test model:

`history = [x for x in train]
his_u = ex_train
predictions = list()
data=list()
test_index = list()
for t in range(len(ex_test)):
    model_arimax = ARIMA(endog = history,exog=his_u, order=(5, 1, 5)).fit(disp=0)
    output = model_arimax.forecast(steps=1, exog=ex_test.iloc[[t]])
    yhat = output[0]
    predictions.append(yhat)
    history.append(test[t])
    test_index.append(t)
    his_u = ex_train.append(ex_test.iloc[test_index])
    data.append([date_test[t], test[t], yhat])
    
RMSE = (mean_squared_error(test, predictions))**0.5
arima_results = pd.DataFrame(data,columns=['Period','Actual Price', 'Predicted Price'],dtype=float)
print('Test RMSE: %.3f' % RMSE)`

I get this error:

`LinAlgError: SVD did not converge`

Here is a link to the notebook in it's current state:
https://github.com/Shane-McCallum/Gold-Time-Series-comparison/blob/master/THE%20WORK%20BOOK.ipynb

I will be eternally grateful for any and all help!

**Comment by ChadFulton** [comment]
Can you replace `from statsmodels.tsa.arima_model import ARIMA` (this is the old ARIMA model) with `from statsmodels.tsa.arima.model import ARIMA` (this is a newer ARIMA model) and see what happens?

(It probably still won't work, but we might get a clearer error message with the newer version of the model).

**Comment by ChadFulton** [comment]
Any update here?

**Comment by Shane-McCallum** [comment]
> Any update here?

Hey, sorry I didn't think anyone had responded! So I did what you suggested, and the new version of ARIMA.fit() doesn't have a disp argument, so I removed it from .fit(). Here is the code, and here is the output

`# For predicting from grid search cv
from sktime.performance_metrics.forecasting import smape_loss
history = [x for x in train]
his_u = ex_train
predictions = list()
data=list()
test_index = list()
for t in range(len(ex_test)):
    model_arimax = ARIMA(endog = history,exog=his_u, order=(2, 1, 1)).fit()
    output = model_arimax.forecast(steps=1, exog=ex_test.iloc[[t]])
    yhat = output[0]
    predictions.append(yhat)
    history.append(test[t])
    test_index.append(t)
    his_u = ex_train.append(ex_test.iloc[test_index])
    data.append([date_test[t], test[t], yhat])


RMSE = (mean_squared_error(test, predictions))**0.5
arima_results = pd.DataFrame(data,columns=['Period','Actual Price', 'Predicted Price'],dtype=float)
print('Test RMSE: %.3f' % RMSE)`

`ValueError                                Traceback (most recent call last)
~\anaconda3\lib\site-packages\pandas\core\indexes\range.py in get_loc(self, key, method, tolerance)
    350                 try:
--> 351                     return self._range.index(new_key)
    352                 except ValueError as err:

ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-34-f2057b836f27> in <module>
      9     model_arimax = ARIMA(endog = history,exog=his_u, order=(2, 1, 1)).fit()
     10     output = model_arimax.forecast(steps=1, exog=ex_test.iloc[[t]])
---> 11     yhat = output[0]
     12     predictions.append(yhat)
     13     history.append(test[t])

~\anaconda3\lib\site-packages\pandas\core\series.py in __getitem__(self, key)
    822 
    823         elif key_is_scalar:
--> 824             return self._get_value(key)
    825 
    826         if is_hashable(key):

~\anaconda3\lib\site-packages\pandas\core\series.py in _get_value(self, label, takeable)
    930 
    931         # Similar to Index.get_value, but we do not fall back to positional
--> 932         loc = self.index.get_loc(label)
    933         return self.index._get_values_for_loc(self, loc, label)
    934 

~\anaconda3\lib\site-packages\pandas\core\indexes\range.py in get_loc(self, key, method, tolerance)
    351                     return self._range.index(new_key)
    352                 except ValueError as err:
--> 353                     raise KeyError(key) from err
    354             raise KeyError(key)
    355         return super().get_loc(key, method=method, tolerance=tolerance)

KeyError: 0`

**Comment by bashtage** [comment]
This is an error in the way you are accessing the exogenous variable in the forecast.  The statsmodels code works as expected here.

**Comment by bashtage** [comment]
This is the offending line: `yhat = output[0]`.  You should inspect output and use the correct indexer.

**Comment by Shane-McCallum** [comment]
> This is the offending line: `yhat = output[0]`. You should inspect output and use the correct indexer.

I am sorry but I am relatively new to all of this and not entirely sure why that would be the issue when it works on the old model? Would you be able to show me the proper writing for the new model?

**Comment by Shane-McCallum** [comment]
Here is [The Notebook](https://github.com/Shane-McCallum/ARIMAX-Gold-and-S-P500-Time-Series/blob/master/THE%20WORK%20BOOK.ipynb) if you have a minute to take a look.

**Comment by bashtage** [comment]
`output` has changed type and is now a pandas Series.  Before it was an numpy array (I suspect).  Just take a look at output so you can get the right indexer.

**Comment by Shane-McCallum** [comment]
> `output` has changed type and is now a pandas Series. Before it was an numpy array (I suspect). Just take a look at output so you can get the right indexer.

Hmm, not sure how to inspect it. Couldn't I just do `yhat = np.array(output[0])` ?

**Comment by Shane-McCallum** [comment]
Also, yhat = output[0] works fine for the ARIMA model, but throws an error using the ARIMAX model.

**Comment by bashtage** [comment]
They are totally separate models. statsmodels.tsa.arima.model.ARIMA is unmaintained and is being removed. Its replacement is the one @ChadFulton recommended.  We don't expect that the identical code should work.  You might want to start with a  tutorial on pandas. The 10-minute guide is a good place.

**Comment by Shane-McCallum** [comment]
> They are totally separate models. statsmodels.tsa.arima.model.ARIMA is unmaintained and is being removed. Its replacement is the one @ChadFulton recommended. We don't expect that the identical code should work. You might want to start with a tutorial on pandas. The 10-minute guide is a good place.

Well, your wrong, statsmodels.tsa.arima.model.ARIMA is the maintained and current model. What I am saying is that yhat = output[0] works when I run my ARIMA model (ARIMA(endog = history, order=(2, 1, 1)).fit()), but not the ARIMAX model (ARIMA(endog = history,exog=his_u, order=(2, 1, 1)).fit()).

**Comment by bashtage** [comment]
Yes, you are correct.  It is https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima_model.ARIMA.html?highlight=arima#statsmodels.tsa.arima_model.ARIMA that is deprecated.  

Why does it not work?

**Comment by Shane-McCallum** [comment]
I get that odd key error again, but inly when running it with an exogenous variable.

**Comment by ChadFulton** [comment]
Your `history` variable is a Python list, but your `his_u` variable is a Pandas Series. If you pass in any Pandas input, Statsmodels returns Pandas output. When you do not include `his_u` (just the ARIMA version), you have not passed in any Pandas input, and we return a numpy array. When you do include `his_u` (the ARIMAX version), you have passed in Pandas input, so we return Pandas output.

**Comment by Shane-McCallum** [comment]
> Your `history` variable is a Python list, but your `his_u` variable is a Pandas Series. If you pass in any Pandas input, Statsmodels returns Pandas output. When you do not include `his_u` (just the ARIMA version), you have not passed in any Pandas input, and we return a numpy array. When you do include `his_u` (the ARIMAX version), you have passed in Pandas input, so we return Pandas output.

Okay, that makes sense. So simple solution would to make ex_train a numpy array, right? The statsmodels page suggest the exog variable be an array-like variable. But converting it with np.array(ex_train) doesn't seem to resolve the issue either.

**Comment by Shane-McCallum** [comment]
I decided to make it an easier to access and edit if you want to mess with it. Here is the [Kaggle notebook](https://www.kaggle.com/thelastwhitekid/arimax-gold-and-s-p500-time-series) working with the old version of the ARIMA and ARIMAX models. Still gets the `LinAlgError: SVD did not converge` but otherwise works is I keep pdq relatively low.

**Comment by ChadFulton** [comment]
> So simple solution would to make ex_train a numpy array, right? ... But converting it with np.array(ex_train) doesn't seem to resolve the issue either.

You can check what you are passing to the function using `print(type(his_u))` just before the call.

Here is an example showing the current behavior, which is working as intended:

```python
import statsmodels.api as sm
y = sm.datasets.macrodata.load(True).data
train = y.iloc[:-1]
test = y.iloc[-1:]

# Endog is numpy, no exog
y = train['infl'].to_numpy()
res1 = sm.tsa.arima.ARIMA(y).fit()
fcast1 = res1.forecast(1)
print('Endog is numpy, no exog')
print('Forecast is', type(fcast1))
print(fcast1, "\n")

# Endog is Pandas, no exog
y = train['infl']
res2 = sm.tsa.arima.ARIMA(y).fit()
fcast2 = res2.forecast(1)
print('Endog is Pandas, no exog')
print('Forecast is', type(fcast2))
print(fcast2, "\n")

# Endog is numpy, exog is numpy
y = train['infl'].to_numpy()
X = train['realint'].to_numpy()
X_test = test['realint'].to_numpy()
res3 = sm.tsa.arima.ARIMA(y, exog=X).fit()
fcast3 = res3.forecast(1, exog=X_test)
print('Endog is numpy, exog is numpy')
print('Forecast is', type(fcast3))
print(fcast3, "\n")

# Endog is numpy, exog is Pandas
y = train['infl'].to_numpy()
X = train['realint']
X_test = test['realint']
res4 = sm.tsa.arima.ARIMA(y, exog=X).fit()
fcast4 = res4.forecast(1, exog=X_test)
print('Endog is numpy, exog is Pandas')
print('Forecast is', type(fcast4))
print(fcast4, "\n")
```

yields

```
Endog is numpy, no exog
Forecast is <class 'numpy.ndarray'>
[3.96331182] 

Endog is Pandas, no exog
Forecast is <class 'pandas.core.series.Series'>
202    3.963312
dtype: float64 

Endog is numpy, exog is numpy
Forecast is <class 'numpy.ndarray'>
[7.30539389] 

Endog is numpy, exog is Pandas
Forecast is <class 'pandas.core.series.Series'>
202    7.305394
dtype: float64 
```

**Comment by Shane-McCallum** [comment]
Alright, I am trying my best to rewrite it and adapt it . Everything I am doing is throwing one error or another, and I haven't even been able to rewrite it and show you the original error for this thread! Here's what I got so far:
```
history = [x for x in train]
his_u = ex_train.to_numpy()
predictions = list()
data=list()
test_index = list()
print(type(his_u))
for t in range(len(ex_test)):
    model_arimax = ARIMA(endog = history,exog=his_u, order=(2, 1, 1)).fit()
    output = model_arimax.forecast(steps=1, exog=ex_test.iloc[[t]])
    yhat = output[0]
    predictions.append(yhat)
    history.append(test[t])
    test_index.append(t)
    his_u = ex_train.append(ex_test.iloc[test_index])
    data.append([date_test[t], test[t], yhat])
```
class is numpy.ndarray
Error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\anaconda3\lib\site-packages\pandas\core\indexes\range.py in get_loc(self, key, method, tolerance)
    350                 try:
--> 351                     return self._range.index(new_key)
    352                 except ValueError as err:

ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-60-8f307705d5b0> in <module>
      9     model_arimax = ARIMA(endog = history,exog=his_u, order=(2, 1, 1)).fit()
     10     output = model_arimax.forecast(steps=1, exog=ex_test.iloc[[t]])
---> 11     yhat = output[0]
     12     predictions.append(yhat)
     13     history.append(test[t])

~\anaconda3\lib\site-packages\pandas\core\series.py in __getitem__(self, key)
    822 
    823         elif key_is_scalar:
--> 824             return self._get_value(key)
    825 
    826         if is_hashable(key):

~\anaconda3\lib\site-packages\pandas\core\series.py in _get_value(self, label, takeable)
    930 
    931         # Similar to Index.get_value, but we do not fall back to positional
--> 932         loc = self.index.get_loc(label)
    933         return self.index._get_values_for_loc(self, loc, label)
    934 

~\anaconda3\lib\site-packages\pandas\core\indexes\range.py in get_loc(self, key, method, tolerance)
    351                     return self._range.index(new_key)
    352                 except ValueError as err:
--> 353                     raise KeyError(key) from err
    354             raise KeyError(key)
    355         return super().get_loc(key, method=method, tolerance=tolerance)

KeyError: 0
```
which made me notice `ex_test.iloc[[t]]` which would probably through the key error again, so I fixed ex_test:
```
history = [x for x in train]
his_u = ex_train.to_numpy()
exog = ex_test.to_numpy()
predictions = list()
data=list()
test_index = list()
print(type(exog))
for t in range(len(ex_test)):
    model_arimax = ARIMA(endog = history,exog=his_u, order=(2, 1, 1)).fit()
    output = model_arimax.forecast(steps=1, exog=exog.iloc[[t]])
    yhat = output[0]
    predictions.append(yhat)
    history.append(test[t])
    test_index.append(t)
    his_u = ex_train.append(ex_test.iloc[test_index])
    data.append([date_test[t], test[t], yhat])
```
Error:
```
<class 'numpy.ndarray'>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-65-20cb5f833784> in <module>
      9 for t in range(len(ex_test)):
     10     model_arimax = ARIMA(endog = history,exog=his_u, order=(2, 1, 1)).fit()
---> 11     output = model_arimax.forecast(steps=1, exog=exog.iloc[[t]])
     12     yhat = output[0]
     13     predictions.append(yhat)

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'
```
 Makes sense, so if I remove the .iloc, how can I keep it iterating? the hole point of this function is for me to be able to plot the comparison between the true value and test values on a graph. 

And I would have to return it into a series to be appended to ex_train and reassign to his_u.

I really do appreciate the help guys, this is been a huge learning experience for me.

![screenshot-www kaggle com-2021 02 18-13_53_51](https://user-images.githubusercontent.com/63820731/108420249-c8ce8700-71f0-11eb-95a1-92703b1d2654.png)
