### ISSUE TITLE
ExponentialSmoothing forecast generate identical results

### ISSUE THREAD

**Issue by alexanderhudym** [statsmodels/statsmodels#7307]
ExponentialSmoothing forecast generate identical results

input = [23.0, 333.0, 400.0, 450.0]
output = [315.457828, 315.457828, 315.457828, 315.457828]

code
`
model = ExponentialSmoothing(input)
fitted = model.fit(smoothing_level=0.2)
forecast = fitted.forecast(steps=4)
`

**Comment by bashtage** [comment]
ExponentialSmoothing produces random walk forecasts, eo Et[Y(t+h)] = Y-hat(t) for all h.
