### ISSUE TITLE
PatsyError: model is missing required outcome variables

### ISSUE THREAD

**Issue by harishkpathak** [statsmodels/statsmodels#7313]
#### While doing the multiple regression was using the feature selection based on P values. The below code is throwing Model is missing error.

```
import statsmodels.formula.api as sm
def backwardElimination(x, Y, sl, columns):
    numVars = len(x[0])
    for i in range(0, numVars):
        regressor_OLS = sm.ols(Y, x).fit()
        maxVar = max(regressor_OLS.pvalues).astype(float)
        if maxVar > sl:
            for j in range(0, numVars - i):
                if (regressor_OLS.pvalues[j].astype(float) == maxVar):
                    x = np.delete(x, j, 1)
                    columns = np.delete(columns, j)
                    
    regressor_OLS.summary()
    return x, columns
SL = 0.05
churn_details_modeled, selected_columns = backwardElimination(churn_details.iloc[:,1:].values, churn_details.iloc[:,0].values, SL, selected_columns)
```
#### Code Sample, a copy-pastable example if possible

```python
# Your code here that produces the bug
# This example should be self-contained, and so not rely on external data.
# It should run in a fresh ipython session, and so include all relevant imports.
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `master`. If your problem has been fixed in an unreleased version, you might be able to use `master` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the master branch of this repository? It helps the limited resources if we know problems exist in the current master so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

</details>

**Comment by bashtage** [comment]
Somethign is wrong here. Why are you using the formula interface without a formula?


This is not correct.
```
regressor_OLS = sm.ols(Y, x).fit()
```

**Comment by harishkpathak** [comment]
For multiple regression, it was for electing the features based on P values and found this formula in many places.  I was using it to compare the P-values and delete those variables more than significance value =0.5.

Any suggestion on how to do this?

**Comment by bashtage** [comment]
You need to use `OLS` from `statmodels.api` when you are using `OLS(y,x)`. `ols` from `statsmodels.formulas.api` requires the syntax `ols(data, formula)` where formula is a string and data is a DataFrame.
