### ISSUE TITLE
BUG: describe / Description do not return percentiles

### ISSUE THREAD

**Issue by manfred2020** [statsmodels/statsmodels#7316]
hello,

i'm unable to get percentiles with these functions:

https://www.statsmodels.org/stable/generated/statsmodels.stats.descriptivestats.describe.html#statsmodels.stats.descriptivestats.describe

https://www.statsmodels.org/stable/generated/statsmodels.stats.descriptivestats.Description.html#statsmodels.stats.descriptivestats.Description

percentiles are not in the default output (every other statistic is) and i get no output if i explicitly choose to only return percentiles.

i'm using python 3.7.9, statsmodels 0.12.2, pandas 1.2.1.

input is a pandas dataframe: 
![grafik](https://user-images.githubusercontent.com/62308730/107402717-9643d080-6b04-11eb-8671-7526859267be.png)

statistics i get (default): 
![grafik](https://user-images.githubusercontent.com/62308730/107402550-6268ab00-6b04-11eb-9a85-f6973183da20.png)

**Comment by manfred2020** [comment]
has anyone ever used or tested this function? couldn't find anything on the internet...

please check it. it seems that 'percentiles' does not work.

**Comment by ChadFulton** [comment]
Thanks for reporting this. This is indeed a bug, where this function never returns percentiles. In fact the default should be to return percentiles for `(1, 5, 10, 25, 50, 75, 90, 95, 99)`, but they never show up.

The problem is that the list of statistics in `_stats` only includes the word `'percentiles'` but does not include the actual index values associated with them (e.g. `'1%', '5%'`, etc.), and then when `_reorder` is called, those elements get dropped.

Should be easy to fix.

**Comment by michaldanaj** [comment]
Hi, I fixed it. But I'm not a developer and I've never contributed in any opensource project, so I need a few days to understand what to do next.

**Comment by ChadFulton** [comment]
Hi @michaldanaj thanks for looking at this. I already have a PR that fixes this issue (see #7321), so maybe you could take a look at what I did there and see if it matches with what you were thinking.

**Comment by michaldanaj** [comment]
I have a different solution. Yours is much shorter.

I've uploaded fixed module here:
https://github.com/michaldanaj/statsmodels/blob/main/descriptivestats.py

**Comment by ChadFulton** [comment]
Thank you for posting that - I think that your solution is much better than mine. If you get a chance to submit a Pull Request, that would be great. Have you submitted a Pull Request before?

**Comment by michaldanaj** [comment]
Yes, but long time ago. 
But testing with compiling from source code is too much for me :) If we omit this step, I can read how to do make a Pull Request and try to make it.
I have cloned main branch locally. So, should I switch to new branch, fork project, push my branch to Github, and make Pull Request?

Nevertheless, I think it would by faster, even for you, if you just incorporate my code into yours :)
