### ISSUE TITLE
BUG: ExponentialSmoothing error for estimated initialization_method with fewer than 10 observations

### ISSUE THREAD

**Issue by josterpi** [statsmodels/statsmodels#7319]
Using Holt-Winters models for less than 10 observations works when `initialization_method=None` but fails with `initialization_method='estimated'` even though "estimated" is the default.

```python
import pandas as pd
from statsmodels.tsa.api import ExponentialSmoothing
data = [456.2713,  440.5881, 425.3325,  485.1494,  506.0482,  526.792 ,  514.2689,  494.211 ]
index= pd.date_range(start='2000', end='2008', freq='A')
oildata = pd.Series(data, index)
ExponentialSmoothing(oildata, initialization_method='estimated').fit()
```

This results in the error: `ValueError: Cannot use heuristic method with less than 10 observations.`

#### Expected Output

I expect to get the same result as if I had used `ExponentialSmoothing(oildata).fit()` which is a warning,

`FutureWarning: After 0.13 initialization must be handled at model creation`

and a result `<statsmodels.tsa.holtwinters.results.HoltWintersResultsWrapper at 0x7f2611dde4f0>`

#### Preliminary research

The problem appears to be in [ExponentialSmoothing._initialize()](https://github.com/statsmodels/statsmodels/blob/59962a5407bf9c5e5be8d481b39a727fe3a6a122/statsmodels/tsa/holtwinters/model.py#L419-L431) where, if the initialization method is `None`, it issues a warning and then returns. However, if the initialization method is "estimated", it gets picked up at the [bottom of the method](https://github.com/statsmodels/statsmodels/blob/59962a5407bf9c5e5be8d481b39a727fe3a6a122/statsmodels/tsa/holtwinters/model.py#L446-L447) and calls `_intialize_heuristic()`, which then calls `_initialization_heuristic()` which [doesn't permit fewer than 10](https://github.com/statsmodels/statsmodels/blob/59962a5407bf9c5e5be8d481b39a727fe3a6a122/statsmodels/tsa/exponential_smoothing/initialization.py#L43-L45) observations.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.8.5.final.0
OS: Linux 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.12.2 (/opt/oneten/muaddib/virtenv/lib/python3.8/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.19.5 (/opt/oneten/muaddib/virtenv/lib/python3.8/site-packages/numpy)
scipy: 1.6.0 (/opt/oneten/muaddib/virtenv/lib/python3.8/site-packages/scipy)
pandas: 1.2.0 (/opt/oneten/muaddib/virtenv/lib/python3.8/site-packages/pandas)
    dateutil: 2.7.3 (/usr/lib/python3/dist-packages/dateutil)
patsy: 0.5.1 (/opt/oneten/muaddib/virtenv/lib/python3.8/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.3.3 (/opt/oneten/muaddib/virtenv/lib/python3.8/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 1.0.0 (/opt/oneten/muaddib/virtenv/lib/python3.8/site-packages/joblib)

Developer Tools
================

IPython: 7.19.0 (/usr/local/lib/python3.8/dist-packages/IPython)
    jinja2: 2.10.1 (/usr/lib/python3/dist-packages/jinja2)
sphinx: Not installed
    pygments: 2.7.4 (/usr/local/lib/python3.8/dist-packages/pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by ChadFulton** [comment]
Thanks very much for this report!

I think this can be pretty easily fixed by using `_initialization_heuristic` if we have at least 10 observations and use `_initialization_simple` if we have fewer than that.

I could not see a good workaround for this at the moment, other than the fact that if you are focused on linear (not muliplicative) models, then you can use `sm.tsa.statespace.ExponentialSmoothing`:

```python
import pandas as pd
from statsmodels.tsa.statespace.exponential_smoothing import ExponentialSmoothing
data = [456.2713,  440.5881, 425.3325,  485.1494,  506.0482,  526.792 ,  514.2689,  494.211 ]
index= pd.date_range(start='2000', end='2008', freq='A')
oildata = pd.Series(data, index)
ExponentialSmoothing(oildata, initialization_method='estimated').fit()
```

**Comment by ChadFulton** [comment]
I've submitted a PR that should fix this, but I'm not sure when the next bugfix release will be.

**Comment by josterpi** [comment]
Thanks for the quick fix! `sm.tsa.statespace.ExponentialSmoothing` works for me and one can always ignore the future warning. I just didn't want the next release to come out with this bug and no option to ignore.
