### ISSUE TITLE
Unable to load builtin dataset data

### ISSUE THREAD

**Issue by ruslaniv** [statsmodels/statsmodels#7323]
#### Describe the bug

Unable to load builtin datasets data. 

#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.api as sm
```
then 

```python
df = sm.datasets.macrodata.load_pandas()
```
or

```python
df = sm.datasets.macrodata.load_pandas().data
```

All above code runs without any errors. 
When I try 
```python
df
```
I get

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-12-00cf07b74dcd> in <module>
----> 1 df

NameError: name 'df' is not defined
```

#### Expected Output

US Macroeconomic Data for 1959Q1 - 2009Q3

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>
INSTALLED VERSIONS
------------------
Python: 3.8.6.final.0
OS: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: en.UTF-8

statsmodels
===========

Installed: 0.12.2 (/Users/ruslan/.local/share/virtualenvs/jupiter-PHGqf7zl/lib/python3.8/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.20.1 (/Users/ruslan/.local/share/virtualenvs/jupiter-PHGqf7zl/lib/python3.8/site-packages/numpy)
scipy: 1.6.0 (/Users/ruslan/.local/share/virtualenvs/jupiter-PHGqf7zl/lib/python3.8/site-packages/scipy)
pandas: 1.2.2 (/Users/ruslan/.local/share/virtualenvs/jupiter-PHGqf7zl/lib/python3.8/site-packages/pandas)
    dateutil: 2.8.1 (/Users/ruslan/.local/share/virtualenvs/jupiter-PHGqf7zl/lib/python3.8/site-packages/dateutil)
patsy: 0.5.1 (/Users/ruslan/.local/share/virtualenvs/jupiter-PHGqf7zl/lib/python3.8/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.3.4 (/Users/ruslan/.local/share/virtualenvs/jupiter-PHGqf7zl/lib/python3.8/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: Not installed

Developer Tools
================

IPython: 7.20.0 (/Users/ruslan/.local/share/virtualenvs/jupiter-PHGqf7zl/lib/python3.8/site-packages/IPython)
    jinja2: 2.11.3 (/Users/ruslan/.local/share/virtualenvs/jupiter-PHGqf7zl/lib/python3.8/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.7.4 (/Users/ruslan/.local/share/virtualenvs/jupiter-PHGqf7zl/lib/python3.8/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed
</details>

**Comment by bashtage** [comment]
I think something is wrong with your environment.  I cannot reproduce:

```
In [1]: import pandas as pd
   ...: import matplotlib.pyplot as plt
   ...: import numpy as np
   ...: import statsmodels.api as sm

In [2]: df = sm.datasets.macrodata.load_pandas()

In [3]: type(df)
Out[3]: statsmodels.datasets.utils.Dataset

In [4]: df = sm.datasets.macrodata.load_pandas().data

In [5]: type(df)
Out[5]: pandas.core.frame.DataFrame
```

**Comment by ruslaniv** [comment]
Yes, it did look like I had some kind of problem with the installation. 
Having reinstalled everything and restarted the Jupyter I finally got it working.
