### ISSUE TITLE
DESIGN: procedure for removing old AR, ARMA, ARIMA in v0.13

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#7325]
These were deprecated in the v0.12 release and slated for removal in v0.13.

For v0.13, I guess we will want to remove them and replace them with faux classes that simply raise an exception and point to `sm.tsa.AutoReg` and `sm.tsa.arima.ARIMA` instead.

Then in v0.14, I guess we will want to set `sm.tsa.AR` to be an alias of `sm.tsa.AutoReg` and set `sm.tsa.ARIMA` to be an alias of `sm.tsa.arima.ARIMA`.

Does that sound okay?

**Comment by bashtage** [comment]
Could just insert a NotImplementedError in the unit of each with a useful
message. Also would be good for docstring to also point to preferred
models.

**Comment by jseabold** [comment]
One thing that may be helpful in the exception is to point users not only to the new models but also to the models in the api namespace. It took me a minute to find `sm.tsa.arima.ARIMA`.
