### ISSUE TITLE
`forecast` method of statsmodels.tsa.arima.model.ARIMAResults returns constant values when using ARIMA(0,1,1)

### ISSUE THREAD

**Issue by camilaagw** [statsmodels/statsmodels#7339]
#### Describe the bug

I have been using `statsmodels.tsa.arima_model.ARIMA` for some time, but after seeing that it is deprecate since v0.12, I migrated  to `statsmodels.tsa.arima.model.ARIMA`. 

Nevertheless, I observe a downgrade in the performance  of one of my models (`ARIMA(0,1,1)`) when using `statsmodels.tsa.arima.model.ARIMA`, which seems to be caused by  the`forecast` method of `statsmodels.tsa.arima.model.ARIMAResults` returning constant values.

#### Code to reproduce

Using  `statsmodels.tsa.arima.model.ARIMA`:
```python
import pandas as pd
from statsmodels.tsa.arima.model import ARIMA 

df = pd.read_csv('https://raw.githubusercontent.com/unit8co/darts/master/examples/AirPassengers.csv')

model = ARIMA(df['#Passengers'].values, order=(0, 1, 1))
model_results = model.fit()
model_results.forecast(steps=len(df))
```
![image](https://user-images.githubusercontent.com/22660466/108591969-b2990600-736b-11eb-8737-033d9ceaa577.png)

Using `statsmodels.tsa.arima_model.ARIMA` (deprecated):
```python
import pandas as pd
from statsmodels.tsa.arima_model import ARIMA as staARIMA 

df = pd.read_csv('https://raw.githubusercontent.com/unit8co/darts/master/examples/AirPassengers.csv')

model = staARIMA(df['#Passengers'].values, order=(0, 1, 1))
model_results = model.fit(disp=0)
model_results.forecast(steps=len(df))[0]
```
![image](https://user-images.githubusercontent.com/22660466/108592166-d7da4400-736c-11eb-8322-2a1db5378bac.png)

#### Expected Output

A similar result to the one I obtain when using `statsmodels.tsa.arima_model.ARIMA`

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
Python: 3.8.5.final.0
OS: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: None

statsmodels
===========

Installed: 0.12.2 (/Users/camilawilliamson/git/darts-env/lib/python3.8/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.17 (/Users/camilawilliamson/git/darts-env/lib/python3.8/site-packages/Cython)
numpy: 1.19.0 (/Users/camilawilliamson/git/darts-env/lib/python3.8/site-packages/numpy)
scipy: 1.5.0 (/Users/camilawilliamson/git/darts-env/lib/python3.8/site-packages/scipy)
pandas: 1.1.0 (/Users/camilawilliamson/git/darts-env/lib/python3.8/site-packages/pandas)
    dateutil: 2.8.1 (/Users/camilawilliamson/git/darts-env/lib/python3.8/site-packages/dateutil)
patsy: 0.5.1 (/Users/camilawilliamson/git/darts-env/lib/python3.8/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.2.2 (/Users/camilawilliamson/git/darts-env/lib/python3.8/site-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 1.0.0 (/Users/camilawilliamson/git/darts-env/lib/python3.8/site-packages/joblib)

Developer Tools
================

IPython: 7.15.0 (/Users/camilawilliamson/git/darts-env/lib/python3.8/site-packages/IPython)
    jinja2: 2.11.2 (/Users/camilawilliamson/git/darts-env/lib/python3.8/site-packages/jinja2)
sphinx: 3.2.1 (/Users/camilawilliamson/git/darts-env/lib/python3.8/site-packages/sphinx)
    pygments: 2.7.4 (/Users/camilawilliamson/git/darts-env/lib/python3.8/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by bashtage** [comment]
This is exactly what you expect to see when forecasting from this model.
The forecast is constant and it is equivalent to an EWMA.

**Comment by bashtage** [comment]
The difference between your models is that the old one includes a constant
by default. When d=1 the new model doesn't include a trend unless you
specifically add it.

**Comment by bashtage** [comment]
Nothing for us to do as this is the correct behavior.

**Comment by camilaagw** [comment]
Thank you for the clarification @bashtage. Makes sense!

**Comment by camilaagw** [comment]
Solved, it. To get the same result, I need to use:
```
model = ARIMA(df['#Passengers'].values, order=(0, 1, 1), trend=[0, 1])
```

**Comment by bashtage** [comment]
IIRC `trend =[1]` or `trend="t"` will work.  I think the 0 is misleading here.

**Comment by camilaagw** [comment]
I checked it, and `trend=[1]` produces the error: 

ValueError: In models with integration (`d > 0`) or seasonal integration (`D > 0`), trend terms of lower order than `d + D` cannot be (as they would be eliminated due to the differencing operation). For example, a constant cannot be included in an ARIMA(1, 1, 1) model, but including a linear trend, which would have the same effect as fitting a constant to the differenced data, is allowed.

However, `trend=t` works nicely! Thank you  @bashtage  ☺️

**Comment by bashtage** [comment]
The first sounds like a bug

**Comment by camilaagw** [comment]
If my understanding  of the documentation is correct, `trend='t'` is equivalent to `trend=[0,1]`  as the later represents the polynomial `a + bt`:

_**trend** 
Parameter controlling the deterministic trend. Can be specified as a string where ‘c’ indicates a constant term, ‘t’ indicates a linear trend in time, and ‘ct’ includes both. Can also be specified as an iterable defining a polynomial, as in numpy.poly1d, where [1,1,0,1] would denote 𝑎+𝑏𝑡+𝑐𝑡^3. Default is ‘c’ for models without integration, and no trend for models with integration._

**Comment by bashtage** [comment]
Oh, I thought it woudl be the powers like [0,1,3].  That is good news.
