### ISSUE TITLE
BUG: Change default pacf method

### ISSUE THREAD

**Issue by liseeocean** [statsmodels/statsmodels#7343]
#### Describe the bug
I found the calculated partial autocorrelation would be larger than 1 using sm.graphics.tsa.plot_pacf.

#### Code Sample

```python
import statsmodels.api as sm
import numpy as np
import matplotlib.pyplot as plt
x=np.linspace(0,1,num=512)
f=20
y=np.cos(2*np.pi*f*x)
plt.plot(x,y_trend)
sm.graphics.tsa.plot_pacf(y_trend, lags=25)
```
<details>

**Comment by bashtage** [comment]
Change the method to "ywmle" or "old".  The default option here is a poor choice and can produce insane plats.  It should be changed.

**Comment by liseeocean** [comment]
Thanks for your reply! It works reasonably after changing the method to 'ols' or 'ywmle'.

**Comment by tqa236** [comment]
Hello @bashtage , is there a plan to change the default pacf method in the future?

**Comment by bashtage** [comment]
Probably by the next release.

**Comment by tqa236** [comment]
Thanks for the quick reply.
