### ISSUE TITLE
Documentation for the param initialization_method of SimpleExpSmoothing seems misleading

### ISSUE THREAD

**Issue by camilaagw** [statsmodels/statsmodels#7352]
#### Describe the bug

The documentation for the param `initialization_method` of `SimpleExpSmoothing` seems misleading:

> **initialization_method** str, optional
> [...]
> None defaults to the pre-0.12 behavior where initial values are passed as part of fit. If any of the other values are passed, then the initial values must also be set when constructing the model. If ‘known’ initialization is used, then initial_level must be passed, as well as initial_trend and initial_seasonal if applicable. **Default is ‘estimated’. “legacy-heuristic” uses the same values that were used in statsmodels 0.11 and earlier.**
> 

According to the source code https://www.statsmodels.org/stable/_modules/statsmodels/tsa/holtwinters/model.html#SimpleExpSmoothing,
the current default value is not "estimated" but `None`.

**Comment by bashtage** [comment]
This is a sentinel value that let's us distinguish from the case where the
user specified one of the options and when they left the default. When the
user leaves the default we warn. The sentinel let's us distinguish these
two cases.
