### ISSUE TITLE
BUG: Fit method for Factor model using the EM algorithm resets the RNG seed

### ISSUE THREAD

**Issue by jmbejara** [statsmodels/statsmodels#7357]
#### Describe the bug

Every time you call the `fit` method to estimate a `Factor` model using maximum likelihood (implemented via the EM algorithm), the code calls `np.random.seed` to reset the seeding. This is a problem because if, say, you want to perform a Monte Carlo experiment that involves fitting a Factor model as described, the seeding will be reset and will jeopardize the Monte Carlo experiment.

#### Code Sample, a copy-pastable example if possible

Below is an example that randomly creates data from a multi-factor model. I then estimate the factor model using maximum likelihood. I create a loop that generates what should be 10 different randomly generated data sets and estimate the model on each independent data set. As you can see, the 9 of the 10 outputs are the same because `statsmodels` is resetting the seed. The first output is different from the remaining 9 because I set the seed myself at the beginning of my code.

```python
import numpy as np
import pandas as pd
import statsmodels.api as sm

np.random.seed(100)
N = 10
T = 40

def fit_factor():
    mu = np.zeros((N,1))
    beta = np.random.multivariate_normal(np.zeros(2), np.eye(2), size=N)
    f = np.random.multivariate_normal(np.zeros(2), np.eye(2), size=T).T
    epsilon = np.random.multivariate_normal(np.zeros(N), np.eye(N), size=T).T

    x = mu + beta @ f + epsilon
    mu_hat = x.mean(axis=1)
    x_tilde = x.T - mu_hat

    factor = sm.Factor(endog=x_tilde, n_factor=2, method='ml')
    fitted_factor = factor.fit()

    beta_hat = fitted_factor.loadings
    return epsilon[0,0], x[0,0], f[0,0]

for i in range(10):
    print(fit_factor())
```

This code produces the following output. Each line should be different, as they should come from independent random draws.

```
(-1.7046512057609624, -4.009211534145269, 1.6189816606752596)
(0.06541577104039452, -1.262462114689552, 0.023364219186334523)
(0.06541577104039452, -1.262462114689552, 0.023364219186334523)
(0.06541577104039452, -1.262462114689552, 0.023364219186334523)
(0.06541577104039452, -1.262462114689552, 0.023364219186334523)
(0.06541577104039452, -1.262462114689552, 0.023364219186334523)
(0.06541577104039452, -1.262462114689552, 0.023364219186334523)
(0.06541577104039452, -1.262462114689552, 0.023364219186334523)
(0.06541577104039452, -1.262462114689552, 0.023364219186334523)
(0.06541577104039452, -1.262462114689552, 0.023364219186334523)
```

This behavior will arise in a simpler example, such as the one below, but in that example the fit method will raise a warning because the fitting algorithm won't converge since the data isn't generate according to a factor model.

```python
import numpy as np
import statsmodels.api as sm

np.random.seed(100)
N = 10
T = 40

def fit_factor():
    epsilon = np.random.multivariate_normal(np.zeros(N), np.eye(N), size=T).T
    factor = sm.Factor(endog=epsilon, n_factor=2, method='ml').fit()
    return epsilon[0,0]

for i in range(10):
    print(fit_factor())
```

#### Expected Output

Each line in the output of the above code snippet should be different, since they are independent random draws. 

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.7.10.final.0

statsmodels
===========

Installed: 0.12.2 (C:\Users\Jeremy\Miniconda3\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.20.1 (C:\Users\Jeremy\Miniconda3\lib\site-packages\numpy)
scipy: 1.6.0 (C:\Users\Jeremy\Miniconda3\lib\site-packages\scipy)
pandas: 1.2.2 (C:\Users\Jeremy\Miniconda3\lib\site-packages\pandas)
    dateutil: 2.8.1 (C:\Users\Jeremy\Miniconda3\lib\site-packages\dateutil)
patsy: 0.5.1 (C:\Users\Jeremy\Miniconda3\lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.3.4 (C:\Users\Jeremy\Miniconda3\lib\site-packages\matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 1.0.1 (C:\Users\Jeremy\Miniconda3\lib\site-packages\joblib)

Developer Tools
================

IPython: 7.19.0 (C:\Users\Jeremy\Miniconda3\lib\site-packages\IPython)
    jinja2: 2.11.3 (C:\Users\Jeremy\Miniconda3\lib\site-packages\jinja2)
sphinx: 3.5.1 (C:\Users\Jeremy\Miniconda3\lib\site-packages\sphinx)
    pygments: 2.8.0 (C:\Users\Jeremy\Miniconda3\lib\site-packages\pygments)
pytest: 6.2.2 (C:\Users\Jeremy\Miniconda3\lib\site-packages\pytest)
virtualenv: Not installed

</details>

**Comment by josef-pkt** [comment]
looks like a bug to me

this should have at least a RandomState option, so users can override the randomness

**Comment by bashtage** [comment]
While this is clearly a bug, you shouldn't rely on the singleton random number generator in Monte Carlo code.  If you use your own `np.random.Generator` instance to generate your simulate data, then you aren't subject to changes in the singleton generator.

**Comment by jmbejara** [comment]
@bashtage Thanks! I wasn't aware of this as a best practice, but I am now after this and after reading about the new random sampling routines in Numpy  1.17.0 (as described in https://numpy.org/devdocs/reference/random/index.html).
