### ISSUE TITLE
MAINT: Renaming master to main

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#7361]
This is now happening pretty much everywhere and so it seems now is the time.  Any strong objections @josef-pkt @ChadFulton  @kshedden ?

**Comment by ChadFulton** [comment]
Yes, looks great to me, thanks @bashtage!

**Comment by josef-pkt** [comment]
how is github handling pull requests when master is renamed?

**Comment by josef-pkt** [comment]
I will backup some old stale GSOC PRs to be safe before renaming.

**Comment by bashtage** [comment]
> how is github handling pull requests when master is renamed?

It all get switched automatically.

**Comment by bashtage** [comment]
Actually, only @josef-pkt can rename. I think we should.  To rename go into the repo settings, select branches, and then edit the master to rename to main. It has been pretty painless, even for NumPy. Once you do this I will merge by PR in that fixes text and CI.

**Comment by jseabold** [comment]
Looks like I can do this, if helpful. Have done it a lot at work and agree it's been seamless.

**Comment by josef-pkt** [comment]
lets wait until I have merged my copula PR

I'm trying to figure out discrepancies to R and don't want to think about changing paths, remotes, whatever

**Comment by josef-pkt** [comment]
@jseabold 
If you want to change the name now, it's fine with me.  (I made a new clone, so I can have my old clone as backup.)
Otherwise, I will change it in the next days.

**Comment by bashtage** [comment]
It is ready.

**Comment by bashtage** [comment]
Just needs the github step

**Comment by josef-pkt** [comment]
I did the rename master to main.
I haven't checked anything yet how it works

**Comment by jseabold** [comment]
Nice, thanks. lgtm. Closing this.
