### ISSUE TITLE
DOC: fix misleading ETSModel implementation of simple exponential smoothing example

### ISSUE THREAD

**Issue by TomasBeuzen** [statsmodels/statsmodels#7365]
#### Describe the bug

In the [example page of using `ETSModel`](https://www.statsmodels.org/dev/examples/notebooks/generated/ets.html#Simple-exponential-smoothing), the simple exponential smoothing model is actually a Holt's model (it includes an additive trend).

#### Suggested fix

This is the current "simple exponential smoothing" model:

```python
model = ETSModel(oil, error='add', trend='add', damped_trend=True)
```
The above includes an additive (damped) trend which effectively makes it a Holt's model. For a simple exponential smoothing model, there should be no trend I believe, so the code should simply be:

```python
model = ETSModel(oil, error='add')
```

This change also ensures that the results match those from the R `forecast` package (the plot in the current page is not identical):

![plot](https://user-images.githubusercontent.com/40379073/110360838-1b32e480-7ff4-11eb-8feb-3284b6634846.png)

#### Next steps

I'm happy to make a PR with this small fix. As always, thanks to all for their hard work in developing, maintaining and improving this package.

**Comment by bashtage** [comment]
A PR is welcome. Thanks.
