### ISSUE TITLE
ModuleNotFoundError: No module named 'statsmodels.robust._qn'

### ISSUE THREAD

**Issue by thatsciencegal** [statsmodels/statsmodels#7370]
When trying to run `import statsmodels.formula.api as smf` it fails with error ModuleNotFoundError: No module named 'statsmodels.robust._qn'

```python
Traceback (most recent call last):
  File "D:/Dropbox/Dissertation/Chapter3/Code/package_for_time_series_reconstruction__atsa_buffer_nspi_/Python version/ATSA_python_20190917/ptest.py", line 1, in <module>
    import statsmodels.formula.api as smf
  File "C:\Users\starg\anaconda3\Lib\site-packages\statsmodels\formula\api.py", line 5, in <module>
    import statsmodels.robust.robust_linear_model as roblm_
  File "C:\Users\starg\anaconda3\Lib\site-packages\statsmodels\robust\__init__.py", line 6, in <module>
    from .scale import mad, Huber, HuberScale, hubers_scale
  File "C:\Users\starg\anaconda3\Lib\site-packages\statsmodels\robust\scale.py", line 23, in <module>
    from ._qn import _qn
ModuleNotFoundError: No module named 'statsmodels.robust._qn'

Process finished with exit code 1
```

```
     active environment : newenv
    active env location : C:\Users\starg\anaconda3\envs\newenv
            shell level : 3
       user config file : C:\Users\starg\.condarc
 populated config files : C:\Users\starg\.condarc
          conda version : 4.9.2
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __cuda=11.2=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\starg\anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\starg\anaconda3\pkgs
                          C:\Users\starg\.conda\pkgs
                          C:\Users\starg\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\starg\anaconda3\envs
                          C:\Users\starg\.conda\envs
                          C:\Users\starg\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.8 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
We have these dependencies installed:
```
numpy                     1.20.1           py37hd20adf4_0    conda-forge
pandas                    1.2.3            py37h08fd248_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
scipy                     1.6.0            py37h6db1a17_0    conda-forge
```

**Comment by bashtage** [comment]
How did you install statsmodels?  Using conda?  Or from master?

**Comment by thatsciencegal** [comment]
I tried installing it both ways, and it gave me the same error.

**Comment by bashtage** [comment]
Your virtual env and the statsmodels paths are inconsistent.  I don't think it is installed in `newenv`.

` active env location : C:\Users\starg\anaconda3\envs\newenv`

vs

`
"C:\Users\starg\anaconda3\Lib\site-packages\statsmodels\formula\api.py"
`

Note that this should be `C:\Users\starg\anaconda3\envs\newenv\lib\site-packages\statsmodels\formula\api.py`

Try a new virtual env:

```
conda create -n verynewenv python=3.8 numpy scipy pandas statsmodels ipython -y
conda activate verynewenv
python -c "import statsmodels;print(statsmodels.__file__)"
```

Mine shows

```text
C:\Anaconda\envs\verynewenv\lib\site-packages\statsmodels\__init__.py
```

**Comment by thatsciencegal** [comment]
This what I get from that code:
C:\Users\starg\anaconda3\Lib\site-packages\statsmodels\__init__.py

I am very new to python, so I really appreciate your help!

**Comment by bashtage** [comment]
Have you initialized conda?  That is, have you run

```
conda init
```
in your command prompt, and then reopened the command prompt.  Basically, you have a broken installation.  

If this doesn't work, I would recommend completely deleting Anaconda (uninstall) and reinstalling a fresh one which usually fixes these kinds of issues.

If you don't want to delete Anaconda and start over, you might consider uninstalling statsmodels from the base conda environment.

**Comment by thatsciencegal** [comment]
Looks like the uninstall/reinstall worked, at least for pointing to the right environment. Thanks!

**Comment by mio178** [comment]
Hi, i have the same problem, im using spyder and it show me this when i write import statsmodels.api as sn
import statsmodels.api as sn
I tried to uninstall and install the statsmodels on CMD and it did´t work. please help!!!
Traceback (most recent call last):

  Cell In[13], line 1
    import statsmodels.api as sn

  File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\api.py:78
    from . import datasets, distributions, iolib, regression, robust, tools

  File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\robust\__init__.py:6
    from .scale import mad, Huber, HuberScale, hubers_scale

  File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\robust\scale.py:21
    from ._qn import _qn

ModuleNotFoundError: No module named 'statsmodels.robust._qn'

**Comment by Joseisg** [comment]
Same problem here. But I refuse to install anaconda lmao. There has to be a normal fix...
