### ISSUE TITLE
BUG: error and failure in pre-release testing

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#7372]
https://dev.azure.com/statsmodels/statsmodels-testing/_build/results?buildId=3199&view=logs&j=d3aeec9b-5735-51da-6bfa-db4d86dad819&t=4a8eef27-4d92-5b93-41e2-3d1348afd29c&l=708

two compatibility bugs in prerelease testing 

statsmodels/regression/tests/test_rolling.py:266: Failed
no warning issued

statsmodels/stats/tests/test_descriptivestats.py:212: 
exception raised somewhere inside pandas

**Comment by josef-pkt** [comment]
@bashtage 

I'm not familiar with these parts

**Comment by bashtage** [comment]
These have been fixed.
