### ISSUE TITLE
reference missing /stats/proportions.py function proportion_confint

### ISSUE THREAD

**Issue by xhajnal** [statsmodels/statsmodels#7391]
Hello, I am writing a paper an I need this (will cite you as you well):

In function `proportion_confint` in `/stats/proportions.py` there is TODO to check the reference, it would be very nice to be sure that that you implement the methods as they are in that paper. Thank you very much.

**Comment by josef-pkt** [comment]
Hi,

I don't find a record or discussion in issues and PRs
For most of those functions where I implemented several methods, I used articles, that did a Monte Carlo comparison across methods. In some cases I had to go back to the original articles for some details.

e.g. IIRC this is one of the articles that I used for single proportion

Newcombe, R.G. (1998), Two‐sided confidence intervals for the single proportion: comparison of seven methods. Statist. Med., 17: 857-872. https://doi.org/10.1002/(SICI)1097-0258(19980430)17:8<857::AID-SIM777>3.0.CO;2-E

general text book reference is Agresti on Categorical Data Analysis

also I found two related articles that I had added to Zotero at the same time as Newcomb, but I don't remember if those are background readings or are used directly for the code.

Agresti, Alan, and Brian Caffo. 2000. “Simple and Effective Confidence Intervals for Proportions and Differences of Proportions Result from Adding Two Successes and Two Failures.” The American Statistician 54 (4): 280–88. https://doi.org/10.2307/2685779.

Agresti, Alan, and Yongyi Min. 2001. “On Small‐Sample Confidence Intervals for Parameters in Discrete Distributions.” Biometrics 57 (3): 963–71. https://doi.org/10.1111/j.0006-341X.2001.00963.x.

**Comment by josef-pkt** [comment]
another one I added to zotero at the same time, based on abstract ot also compares methods and argues agaist Wald intervals

Brown, Lawrence D., T. Tony Cai, and Anirban DasGupta. 2001. “Interval Estimation for a Binomial Proportion.” Statistical Science 16 (2): 101–17.

**Comment by josef-pkt** [comment]
unit test results mention binom.confint but with package pwr which might be copy paste error
"\statsmodels\stats\tests\results\results_proportion.py"

https://www.rdocumentation.org/packages/binom/versions/1.1-1/topics/binom.confint
uses the same references plus another reference that I had also read

A. Agresti and B.A. Coull (1998), Approximate is better than "exact" for interval estimation of binomial proportions, American Statistician, 52:119-126.

**Comment by xhajnal** [comment]
Oh, thanks for the fast reply and all the references.

So going one by one:
method and source of the implementation:

Agresti-Coull:
A. Agresti and B.A. Coull (1998), Approximate is better than "exact" for interval estimation of binomial proportions, American Statistician, 52:119-126.

Wilson:
Newcombe, R.G. (1998), Two‐sided confidence intervals for the single proportion: comparison of seven methods. Statist. Med., 17: 857-872. https://doi.org/10.1002/(SICI)1097-0258(19980430)17:8<857::AID-SIM777>3.0.CO;2-E

Clopper-Pearson:
??

Jeffreys:
?? (especially this one with all modified and equal tailed versions.)

Sorry for being such a stickler, but I simply do not see a straight line from the Brown et al. to your implementation.
It is kind of cryptic with all that inside notation, besides that cool paper. 

Btw, 
Dean, N. and Pagano, M., 2015. Evaluating confidence interval methods for binomial proportions in clustered surveys. Journal of Survey Statistics and Methodology, 3(4), pp.484-503.
does a pretty similar job.

Thank you very very much for your time.
