### ISSUE TITLE
Support for python 3.9

### ISSUE THREAD

**Issue by ghtmtt** [statsmodels/statsmodels#7392]
Hi! Is there any roadmap to include statsmodel in python 3.9?

I couldn't find the information elsewhere, sorry for the eventual noise

**Comment by bashtage** [comment]
It is already available: https://pypi.org/project/statsmodels/#files

**Comment by bashtage** [comment]
On Python 3.9, you can

```
python -m pip install statsmdoels --upgrade
```

to get the latest version.

You can also get it from conda forge if you use conda

```
conda install -c conda-forge statsmodels
```

or make a new virtual env

```
conda create -n py39sm -c conda-forge python=3.9 statsmodels
```

**Comment by ghtmtt** [comment]
thanks for the quick reply @bashtage!

**Comment by wonhyukchoi** [comment]
Nitpicky, but there's a typo in the first command.
Took me a while after I wondered why it wasn't working after I copy-pasted the command...
