### ISSUE TITLE
so strangely

### ISSUE THREAD

**Issue by qiezikuangge** [statsmodels/statsmodels#7396]
I am trying to use STLDecompose for my time series data and my code was
```python
from statsmodels.api import tsa
rd = tsa.seasonal_decompose(data,frea=12*24)
```
And then I want to observe the residuals,so I use
```python
rd.resid
```
and the result showed on jupyter notebook was
![image](https://user-images.githubusercontent.com/50002441/113252169-119c5400-92f6-11eb-8193-d928fd1014c1.png)
It seems like something is wrong but when I use plt.plot(rd.resid), it shows
![image](https://user-images.githubusercontent.com/50002441/113252281-34c70380-92f6-11eb-865b-1a5adc0801e3.png)
It was normally, so I am confused

**Comment by bashtage** [comment]
`seasonal_decompose` is not `STL`.  In `seasonal_decompose` you lost the first and last freq.

**Comment by qiezikuangge** [comment]
> `seasonal_decompose` is not `STL`. In `seasonal_decompose` you lost the first and last freq.

Yeah,yeah,yeah. I'm wrong. Thanks
