### ISSUE TITLE
acovf with groupby

### ISSUE THREAD

**Issue by pinpss** [statsmodels/statsmodels#7407]
#### Is your feature request related to a problem? Please describe
I am trying to implement the autocovariance function for i stocks with time t (lagged -23). 

#### Describe the solution you'd like
I tried to groupby('stocks') but the following code doesn't work.

` df['acovf_f']=df.groupby('id')['logret'].apply(lambda x: acovf(x, adjusted=False, demean=True, fft=None, missing='drop'))`

#### Describe alternatives you have considered

Looping by doesn't work neither.
```
appended_data1=[]
for i in range(659):
    stock=df[df['id'] == i]
    stock['acovf_func']=acovf(stock.logret, adjusted=False, demean=True, fft=None, missing='drop')
    appended_data1.append(stock)
appended_data1 = pd.concat(appended_data1)
```

#### Additional context
Add any other context about the feature request here.
Academics use autocovariances as a measure of bond/stock illiquidity. They are computed of the daily price changes within each month, multiplied by –1. (Bao, Pan, Wen, 2011). Liquidity measures.

**Comment by josef-pkt** [comment]
"doesn't work" is not helpful.

What is the problem? Show full traceback if there is an exception.

**Comment by pinpss** [comment]
Thank your for your reply josef-pkt. Sorry for the lack of precisions.

For `groupby('id')`, I get the column `df['acovf_f']` full of NaNs values. 

For the alternative loop, I get this traceback

```
/Users/mc/opt/anaconda3/lib/python3.8/site-packages/statsmodels/tsa/stattools.py:439: FutureWarning: fft=True will become the default after the release of the 0.12 release of statsmodels. To suppress this warning, explicitly set fft=False.
  warnings.warn(msg, FutureWarning)
/Users/mc/opt/anaconda3/lib/python3.8/site-packages/statsmodels/tsa/stattools.py:467: RuntimeWarning: Mean of empty slice.
  xo = x - x.mean()
Traceback (most recent call last):

  File "<ipython-input-613-5f16974a0b4e>", line 4, in <module>
    stock['acovf_func']=acovf(stock.logret, adjusted=False, demean=True, fft=None, missing='drop')

  File "/Users/mc/opt/anaconda3/lib/python3.8/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)

  File "/Users/mc/opt/anaconda3/lib/python3.8/site-packages/statsmodels/tsa/stattools.py", line 512, in acovf
    d = n * np.ones(2 * n - 1)

  File "/Users/mc/opt/anaconda3/lib/python3.8/site-packages/numpy/core/numeric.py", line 192, in ones
    a = empty(shape, dtype, order)

ValueError: negative dimensions are not allowed
```
However, if I fix the `i` in the loop the code "works" fine.  
```
stock=df[df['id'] == 24]
stock['acovf_func']=acovf(stock.logret, adjusted=False, demean=True, fft=None, missing='drop')
```
Is there other way to run the code with a group argument? for panel data structure or multi index?

**Comment by bashtage** [comment]
Works find with simulated data.

```
import pandas as pd
import numpy as np
from statsmodels.tsa.api import acovf

df = pd.DataFrame(np.random.standard_normal((1000,4)))
df = df.unstack()
df = df.reset_index()
df.columns = ["id","time","logret"]
df.head()
```

shows

```
   id  time    logret
0   0     0  1.225453
1   0     1 -1.205387
2   0     2  0.363658
3   0     3  0.701222
4   0     4 -1.417040
```

```python
df.groupby("id")["logret"].apply(lambda x: acovf(x, adjusted=False, demean=True, fft=None, missing='drop'))
```

then produces

```
id
0    [0.9831327680405364, -0.011122631780481052, 0....
1    [1.0453613399474693, 0.0013159763029344873, 0....
2    [0.9616796512830933, 0.075263464342919, 0.0476...
3    [0.9336718895314333, -0.03835163196029272, 0.0...
Name: logret, dtype: object
```

**Comment by bashtage** [comment]
I suspect that you have some columns with all missing data.

**Comment by bashtage** [comment]
If you share the underlying data then we can find out what is happening.

**Comment by pinpss** [comment]
Hi Kevin, thank you for your reply. 

Your code works indeed. However, I still have trouble merging the results to the `df` due to the returned series with rows == id (but without the time index). 

To illustrate the problem, 

This works (your example):

`df.groupby("id")["logret"].apply(lambda x: acovf(x, adjusted=False, demean=True, fft=None, missing='drop))
`

This creates a series (no time index):

`acovf_func=df.groupby("id")["logret"].apply(lambda x: acovf(x, adjusted=False, demean=True, fft=None, missing='drop'))
`

But this code, still returns NaNs.

`df['acovf_func']=df.groupby("id")["logret"].apply(lambda x: acovf(x, adjusted=False, demean=True, fft=None, missing='drop'))`

I have attached you a snippet of the data. All missing values are dropped. The data is highly unbalanced. Sometimes the returns are 252, sometimes they are less.  
[sample_2015.xlsx](https://github.com/statsmodels/statsmodels/files/6279884/sample_2015.xlsx)


**FYI**

I want to implement the illiquidity measure of Bao, Pan, and Wang (2011) and Bai, Bali, and Wen (2019) to construct bond-level autocovariances.

Specifically, let

<img src="https://latex.codecogs.com/gif.latex?\Delta&space;p_{itd}=&space;p_{itd}-p_{itd-1}" title="\Delta p_{itd}= p_{itd}-p_{itd-1}" />

be the log price change for stock i on day d of month t. Then, ILLIQ is defined as

<img src="https://latex.codecogs.com/gif.latex?ILLIQ&space;=&space;-&space;Cov(\Delta&space;p_{itd},&space;\Delta&space;p_{itd&plus;1})" title="ILLIQ = - Cov(\Delta p_{itd}, \Delta p_{itd+1})" />


Reference: [http://www.mit.edu/~junpan/bond_liquidity.pdf] [Bao, Pan and Wen (2021)]


Any advice would be great. Most certainly, it is just me that I am missing something.

**Comment by bashtage** [comment]
> df['acovf_func']=df.groupby("id")["logret"].apply(lambda x: acovf(x, adjusted=False, demean=True, fft=None, missing='drop'))

This line returns **some** NaNs because of how pandas works.  The index are the group ids which only do into the 100s.  Your DF has 131,000 rows in the sample you gave.  

If you run 
```
df.loc[[1,2,3], 'acovf_func']
```

you get 

```
1    [2.9963244388469342e-05, -3.0691192825475698e-...
2    [9.775937686463604e-06, 6.283195253277195e-07,...
3    [2.541098979709156e-06, -2.21081531095774e-07,...
Name: acovf_func, dtype: object
```
which is exactly what it should compute.  Given you only need the first autocovariance, you should just write a simple function to get this one

```
def first_ac(s):
     s = s.dropna()
     if s.shape[0] < 2:
         return np.nan
     return acovf(s, nlag=1, adjusted=False, demean=True, fft=True, missing="drop")[1]
```

```
df.groupby("id")["logret"].apply(first_ac)
Out[31]:
id
1     -3.069119e-06
2      6.283195e-07
3     -2.210815e-07
4      4.056136e-07
5     -1.929027e-07
           ...
655   -9.873775e-07
656   -2.338772e-08
657    2.396974e-06
658   -2.683648e-06
659   -1.402613e-05
Name: logret, Length: 659, dtype: float64
```

**Comment by bashtage** [comment]
I'm going to close since there are not bugs to fix in statsmodeles.  Stackoverflow is probably the best place for these types of pandas groupby or rolling usage questions.

**Comment by pinpss** [comment]
Thank you for you quick answer, and helpful replies. Sorry for the misplaced question.
