### ISSUE TITLE
ARIMA model d setting questions

### ISSUE THREAD

**Issue by Dianaumd** [statsmodels/statsmodels#7410]
Hello,

I have two models without exog variables (1) d=0, and I performed the first differencing before fit into the model: ARIMA(y_diff1, order(1, 0, 2) (2) d=1 and use the original y: ARIMA(y, order(1, 1, 2)
However, the parameter estimations are slightly different. Do you know why? I performed the same analysis on the deprecated tsa.ARIMA module and (1) and (2) matches exactly. 

Thanks

**Comment by bashtage** [comment]
The (1,1,2) model makes use of all of the data and so is not identical to differencing and dropping in finite samples.
