### ISSUE TITLE
"...Not be matched to the given index."

### ISSUE THREAD

**Issue by Rocket-Development** [statsmodels/statsmodels#7419]
#### Describe the bug

This error ("The given frequency argument could not be matched to the given index")  is given when I pass the "freq" argument (freq='D' ), I'm importing like this:  from statsmodels.tsa.arima_model import ARIMA

#### Code Sample, a copy-pastable example if possible

import pandas as pd
import numpy as np
import datetime as dt
from statsmodels.tsa.arima_model import ARIMA, ARMA

arimaModel=ARIMA(df_predict, freq='D', order=(2,1,2)).fit()
(arimaModel.resid ** 2).mean()

Some help, please

**Comment by bashtage** [comment]
`ARIMA` and `ARMA` are long deprecated and have been removed from master.  Use `from statsmodels.tsa.arima.model import ARIMA`.   If you still have a problem when using the new code, please open a new issue.
