### ISSUE TITLE
Use .2g for formatting mean_diff_plot annotations

### ISSUE THREAD

**Issue by reox** [statsmodels/statsmodels#7420]
#### Is your feature request related to a problem? Please describe

When using mean_diff_plot, it shows mean and +-sd.

The numbers are currently rounded to two digits:
https://github.com/statsmodels/statsmodels/blob/77bb1d276c7d11bc8657497b4307aa7575c3e65c/statsmodels/graphics/agreement.py#L132

However, if you put in small numbers, you will see zeros everywhere:
![image](https://user-images.githubusercontent.com/431045/115519431-7dd0fe80-a289-11eb-94ca-ee702ea471ff.png)

```
>>> import numpy as np
>>> import statsmodels.api as sm
>>> import matplotlib.pyplot as plt
>>> sm.graphics.mean_diff_plot(np.random.normal(0.000001, 0.0000001, 10), np.random.normal(0.0000015, 0.000001, 10))
<Figure size 640x480 with 1 Axes>
>>> plt.show()
```

#### Describe the solution you'd like

It should print some number which is not 0.0 - which is misleading.
Maybe using `.2g` as format would be a good, i.e.,:
```
 ax.annotate('-SD{}: {:.2g}'.format(sd_limit, lower), [...]
```

Example:
```
>>> f'{0.000001:.2g}'
'1e-06'
>>> f'{0.01:.2g}'
'0.01'
```

#### Describe alternatives you have considered
There are obviously many different formatting options... I'm not sure which one would be most fitting.

**Comment by bashtage** [comment]
A PR would be welcome.

**Comment by reox** [comment]
I can do that but what would be an appropriate format? Or should that be an additional argument to the function?

**Comment by bashtage** [comment]
0.2g sounds reasonable.  Ideally that would be passable as a new *kwds argument like that would allow the annotations to be reformatted.

https://github.com/statsmodels/statsmodels/blob/77bb1d276c7d11bc8657497b4307aa7575c3e65c/statsmodels/graphics/agreement.py#L48

**Comment by bashtage** [comment]
Maybe a dict wouldn't work since this isn't really a matplotlib keyword arg.
