### ISSUE TITLE
Please set default branch to 'main' in codecov.io

### ISSUE THREAD

**Issue by jedbrown** [statsmodels/statsmodels#7424]
#### Describe the bug

Click the codecov badge or [visit the site](https://app.codecov.io/gh/statsmodels/statsmodels) and click on files. This will use branch 'master', which is an old codecov result and no longer exists in the repository.
![image](https://user-images.githubusercontent.com/3303/116465839-ffe19a00-a82a-11eb-8318-02d352280d5d.png)

#### How to fix

A project administrator needs to visit https://app.codecov.io/gh/statsmodels/statsmodels/settings and change the default branch from 'master' to 'main'. It should look like this:
![image](https://user-images.githubusercontent.com/3303/116466192-69fa3f00-a82b-11eb-8dd6-f0900bcb0788.png)

**Comment by josef-pkt** [comment]
Done

Thanks for pointing this out, and showing what we need to do.

I was able to access codecov for pull request, but didn't know why other access didn't work properly

**Comment by jedbrown** [comment]
Cool, thanks.
