### ISSUE TITLE
Log-Likelihood Documentation in ETSModel

### ISSUE THREAD

**Issue by hxyue1** [statsmodels/statsmodels#7443]
Hello,

I think there might be a mistake in the documentation for the Log-Likelihood in the ETSModel.  This is what the docs have, 

![image](https://user-images.githubusercontent.com/42855604/117723040-bd0eb300-b196-11eb-9cd1-4f06bdefce89.png).

Shouldn't S^2 square the residuals before taking the mean? The referenced article seems to define it differently, 

![image](https://user-images.githubusercontent.com/42855604/117723497-4aea9e00-b197-11eb-847b-eaea446f5259.png)

**Comment by bashtage** [comment]
At a minimum there is a square missing.

**Comment by pkaf** [comment]
I have pushed the change and with this starting contributing to statsmodels
