### ISSUE TITLE
BUG: Remove/rewrite from_estimation from ArmaProcess

### ISSUE THREAD

**Issue by heinwol** [statsmodels/statsmodels#7446]
#### Describe the bug

An attempt to create a pure AR model results in attribute error

#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import statsmodels
from statsmodels.tsa.arima_process import ArmaProcess
from statsmodels.tsa.arima.model import ARIMA

some_data = np.random.randn(100)
modeling_result = ARIMA(some_data, order=(4, 0, 0)).fit()
process = ArmaProcess.from_estimation(modeling_result)
```
<details>

Error backtrace:

---------------------------------------------------------------------------
```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-49dc4cff01dd> in <module>
      6 some_data = np.random.randn(100)
      7 modeling_result = ARIMA(some_data, order=(4, 0, 0)).fit()
----> 8 process = ArmaProcess.from_estimation(modeling_result)

c:\python39\lib\site-packages\statsmodels\tsa\arima_process.py in from_estimation(cls, model_results, nobs)
    779         """
    780         arcoefs = model_results.arparams
--> 781         macoefs = model_results.maparams
    782         nobs = nobs or model_results.nobs
    783         return cls(np.r_[1, -arcoefs], np.r_[1, macoefs], nobs=nobs)

c:\python39\lib\site-packages\statsmodels\base\wrapper.py in __getattribute__(self, attr)
     32             pass
     33 
---> 34         obj = getattr(results, attr)
     35         data = results.model.data
     36         how = self._wrap_attrs.get(attr)

pandas\_libs\properties.pyx in pandas._libs.properties.CachedProperty.__get__()

c:\python39\lib\site-packages\statsmodels\tsa\statespace\sarimax.py in maparams(self)
   1946         zero.
   1947         """
-> 1948         return self._params_ma
   1949 
   1950     @cache_readonly

AttributeError: 'ARIMAResults' object has no attribute '_params_ma'
```
----------------------------------------------------------------------------

Just changing line 1948 in sarimax.py to 
```
        try:
            return self._params_ma
        except AttributeError:
            return []
```
fixes the issue.
</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

Some ARMA process instance

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.9.2.final.0

statsmodels
===========

Installed: 0.12.2 (c:\python39\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.19.5 (c:\python39\lib\site-packages\numpy)
scipy: 1.6.0 (c:\python39\lib\site-packages\scipy)
pandas: 1.2.1 (c:\python39\lib\site-packages\pandas)
    dateutil: 2.8.1 (c:\python39\lib\site-packages\dateutil)
patsy: 0.5.1 (c:\python39\lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.3.4 (c:\python39\lib\site-packages\matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 1.0.1 (c:\python39\lib\site-packages\joblib)

Developer Tools
================

IPython: 7.19.0 (c:\python39\lib\site-packages\IPython)
    jinja2: 2.11.2 (c:\python39\lib\site-packages\jinja2)
sphinx: Not installed
    pygments: 2.7.4 (c:\python39\lib\site-packages\pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by bashtage** [comment]
You are using the wrong `ARIMA`.  Unfortunately the right `ARIMA` is deprecated, and so the only workaround is to parse the model parameters yourself to ArmaProcess.

**Comment by heinwol** [comment]
Oh, I see. Thanks for reply then!

**Comment by bashtage** [comment]
Closing as answered.
