### ISSUE TITLE
Time trend, constant trend, constant and time trend

### ISSUE THREAD

**Issue by bkvsy** [statsmodels/statsmodels#7447]
Can anyone explain the difference between the 'time trend', 'constant trend', 'constant and time trend' in AutoReg()? As far as I know a constant trend is just one type of a time trend in time series. 
https://www.statsmodels.org/stable/generated/statsmodels.tsa.ar_model.AutoReg.html

**Comment by bashtage** [comment]
Constant means model is

Y(t) = delta + ...

Time Trend means

Y(t) = delta * t + ...

Both means

Y(t) = delta0 + delta1 * t + ...

where ... is the AR and seasonal component.
