### ISSUE TITLE
ARIMAX and SARIMAX support vector autoregression?

### ISSUE THREAD

**Issue by zollen** [statsmodels/statsmodels#7451]
Is it possible for the ARIMA and SARIMAX to support multiple time series data together (vector autoregression). For example, I want to combine multiple stock prices, dow jones and S&P index and feed them into a SARIMAX model.

**Comment by bashtage** [comment]
See VARMAX. https://www.statsmodels.org/stable/examples/notebooks/generated/statespace_varmax.html
