### ISSUE TITLE
Vector Autoregression with Markov-Switching Regime

### ISSUE THREAD

**Issue by ffs-sp** [statsmodels/statsmodels#7455]
Hi, 

I have been trying to run a Markov-Switching VAR using statsmodel and obtained the following error:

```ValueError: Must have univariate endogenous data.```

Is there a command that allows for VAR estimation? I have a 3x3 matrix and looking for a MS-VAR estimation.

Thanks!

**Comment by ChadFulton** [comment]
Unfortunately, we do not have the Markov switching VAR model (the existing Markov switching model is only univariate).

Closing as answered, but feel free to follow up if you have more questions.
