### ISSUE TITLE
is class DocString modifying c-extension `tp_doc` attributes after PyTypeReady?

### ISSUE THREAD

**Issue by mattip** [statsmodels/statsmodels#7460]
https://github.com/statsmodels/statsmodels/blob/77bb1d276c7d11bc8657497b4307aa7575c3e65c/statsmodels/tools/docstring.py#L534

It seems the DocString class is modifying `tp_doc` strings after `PyTypeReady` has been called, which does not work on PyPy. It works only by chance on CPython. Is it possible to modify this code to do that manipulation in a precompile step, write the docstrings out to a header file, and read them in before instantiating the type?

xref [PyPy issue 3471](https://foss.heptapod.net/pypy/pypy/-/issues/3471). Another option would be to (like NumPy) be aware that the `__doc__` attribute may be empty for optimized python (when using `python -OO`) or for PyPy.

**Comment by bashtage** [comment]
`Docstring` doesn't actually do anything other than make it easy to manipulate docstrings. 

For example, here `Docsting` is used but then `Substitution` does the work of attaching a doc string. 

https://github.com/statsmodels/statsmodels/blob/77bb1d276c7d11bc8657497b4307aa7575c3e65c/statsmodels/tsa/forecasting/stl.py#L66


I thought we had an -OO run in testing.  We should have one, and things that break -OO are not supposed to be allowed.

**Comment by bashtage** [comment]
If this new in PyPy?

I think statsmodels passed on PyPy here:

https://github.com/conda-forge/statsmodels-feedstock/pull/44

**Comment by bashtage** [comment]
I ran
```python
import importlib
import pkgutil
import statsmodels

blocked = ("l1_cvxopt",
"statsmodels.tsa.vector_ar.tests.example_svar",
"statsmodels.duration.tests.results.phreg_gentests",
".sandbox.",
"statsmodels.stats.libqsturng.make_tbls")

def import_submodules(module):
    """Import all submodules of a module, recursively."""
    for loader, module_name, is_pkg in pkgutil.walk_packages(module.__path__, module.__name__ + '.'):
        skip = False
        for block in blocked:
            skip |= block in module_name
        if skip:
            continue
        print(module_name)
        importlib.import_module(module_name)

import_submodules(statsmodels)

```

locally with `python -OO` and it doesn't show any problems.

**Comment by bashtage** [comment]
Here it handles the `-OO` case:

https://github.com/statsmodels/statsmodels/blob/77bb1d276c7d11bc8657497b4307aa7575c3e65c/statsmodels/tools/docstring.py#L547

**Comment by mattip** [comment]
It appears my guess as to the problem was wrong. Any ideas why [the user reported](https://foss.heptapod.net/pypy/pypy/-/issues/3471#note_159456)
```
so, how to patch ?
    print('_fit_params', _fit_params)
    print(" " * 8)
    @Substitution(fit_params=indent(_fit_params, " " * 8))
give
 _fit_params None

going  up line 63 gives

ds = Docstring(STL.fit.__doc__)
print('ds is', ds)
ds is None

print(Docstring(STL.fit.__doc__)) gives None,
but print(Docstring(STL.__doc__) gives a lot of text
```

**Comment by bashtage** [comment]
That does look fishy, and _fit_params is definitely None if the docstring has been stripped (so that `__doc__` is None).  Probably needs some protection there.  Still not sure why I coudl run that script.

**Comment by bashtage** [comment]
On my machine, `STL.__doc__` and all function docstrings are all present even when running with `-OO`.  I suspect this is a quirk of CPython's extension loading which doesn't strip docstrings from extension modules.

Start running `python -OO`, then
```
python -OO -c "from statsmodels.tsa.seasonal import STL;print(STL.__doc__);print(STL.fit.__doc__)"
```

where 

```
python -OO -c " python -OO -c "from statsmodels.tsa.forecasting.stl import STLForecast;print(STLForecast.__doc__)"
```

shows `None`.

**Comment by bashtage** [comment]
NumPy has the same behavior. If you run `python -OO` and then

```
import numpy as np
print(np.random.Generator.__doc__)
print(np.linalg.solve.__doc__)
```

You see the `Generator` doc but not `solve`.

Is PyPy doing the right thing here?

**Comment by mattip** [comment]
It is not really legal to modify the `tp_doc` slot after calling `PyTypeReady` with a c-function call that changes the pointer. See numpy/numpy#10167.

**Comment by bashtage** [comment]
This isn't really about modifying after ready.  CPython does not strip docstrings of Extensions even when run in `-OO`.  It seems like PyPy does strip these doc strings. This is why we never see a bug in CPython here since the docstring always exists and is never `None`.

**Comment by mattip** [comment]
It sounds like a bug in how PyPy is handling docstrings. I don't really understand where the bug is and have not had any luck reproducing. Building statsmodels for windows involves building SciPy from source (since there are no wheels for PyPy), so I will revisit this once conda has a windows build with SciPy.

**Comment by bashtage** [comment]
The bug here was calling `textwrap.indent` on an object that was `None` on PyPy.  When running on CPython, this object is always a `str` since it is read from a C-extension, irrespective of whether `-OO` was used or not.  This is fixed  @ #7462 so if this is all that is wrong then it should be fine.  Eventually would be good to get a CI for PyPy (even if minimal `--skip-slow`).

**Comment by mattip** [comment]
> CPython does not strip docstrings of Extensions even when run in -OO. It seems like PyPy does strip these doc strings.

Maybe I misunderstood. PyPy cannot implement numpy's `add_newdocs` because it modifies the `tp_doc` pointer after calling `PyTypeReady`. This is not good behavior. Nothing in the `PyTypeObject` is meant to change after `PyTypeReady`, the [docstring](https://github.com/numpy/numpy/blob/fb215c76967739268de71aa4bda55dd1b062bc2e/numpy/core/function_base.py#L511) states as much:
> Since this function grabs the `char *` from a c-level str object and puts it into the `tp_doc` slot of the type of `obj`, it violates a number of C-API best-practices, by:
> - modifying a `PyTypeObject` after calling `PyType_Ready`
> - calling `Py_INCREF` on the str and losing the reference, so the str will never be released

So I don't understand if PyPy is stripping docstrings or not modifying them as requested by numpy.

**Comment by stonebig** [comment]
hi all, 

on my two failing test, the patch, applied per notepad++ is effective.

test1:
```
# checking statsmodels
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
import statsmodels.api as sm
data = sm.datasets.anes96.load_pandas()
party_ID = np.arange(7)
labels = ["Strong Democrat", "Weak Democrat", "Independent-Democrat",
          "Independent-Independent", "Independent-Republican",
          "Weak Republican", "Strong Republican"]
plt.rcParams['figure.subplot.bottom'] = 0.23  # keep labels visible
plt.rcParams['figure.figsize'] = (6.0, 4.0)  # make plot larger in notebook
age = [data.exog['age'][data.endog == id] for id in party_ID]
fig = plt.figure()
ax = fig.add_subplot(111)
plot_opts={'cutoff_val':5, 'cutoff_type':'abs',
                                'label_fontsize':'small',
                                'label_rotation':30}
sm.graphics.beanplot(age, ax=ax, labels=labels,
                     plot_opts=plot_opts)
ax.set_xlabel("Party identification of respondent")
ax.set_ylabel("Age")
plt.show()
```

![image](https://user-images.githubusercontent.com/4312421/119392878-955c3680-bcd0-11eb-8f68-b7c60090bd45.png)

test2:
```
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from plotnine import *

n = 10
df = pd.DataFrame({'x': np.arange(n),
                   'y': np.arange(n),
                   'yfit': np.arange(n) + np.tile([-.2, .2], n // 2),
                   'cat': ['a', 'b'] * (n // 2)})

a = (ggplot(df)
     + geom_col(aes('x', 'y'))
     )

fig = a.draw()
fig.axes  # You can plot more stuff on the axes using Matplotlib !!!
plt.show()
```

![image](https://user-images.githubusercontent.com/4312421/119395673-27197300-bcd4-11eb-855d-23b4ea709701.png)
