### ISSUE TITLE
Question about the usage of the different regression type

### ISSUE THREAD

**Issue by zollen** [statsmodels/statsmodels#7461]
This is a question as I am unable to find any helpful information elsewhere.

https://www.statsmodels.org/stable/generated/statsmodels.tsa.stattools.adfuller.html
regression{“c”,”ct”,”ctt”,”nc”}
Constant and trend order to include in regression.
 - “c” : constant only (default).
 - “ct” : constant and trend.
 - “ctt” : constant, and linear and quadratic trend.
 - “nc” : no constant, no trend.

At what things/conditions I suspect in a time series data for using what regression type and what would be the expected P values?

**Comment by bashtage** [comment]
The constant instructs the test what you think about the alternative hypotheses:

"n": The time series is mean zero and covariance stationary
"c": The time series has a non-zero mean and is covariance stationary
"ct": The time series is linear trend stationary -- that is y - a - b t is mean zero and covariance stationary for some choice of a and b
"ctt": The time series is quadratic trend stationary -- that is y - a - b t - c t**2 is mean zero and covariance stationary for some choice of a, b,  and c.

In economic applications, c and ct are the most common choices.

**Comment by bashtage** [comment]
Closing since there is no action needed; fee free to ask clarification if needed.

**Comment by zollen** [comment]
Final question:
If a time series data is non-stationary and with trend, I use the regression "ct". Should I expect the resulting p values to be less than 0.05?

**Comment by bashtage** [comment]
Yes.

```
from statsmodels.tsa.stattools import adfuller

import numpy as np
g = np.random.default_rng(0)
y = 10 + np.arange(250) + g.standard_normal(250)
adfuller(y,regression="ct")
```

Returns (2nd value is the pvalue)

```
(-15.025126533759012,
 2.124966448163402e-22,
 0,
 249,
 {'1%': -3.9955950298398477,
  '5%': -3.428270807162781,
  '10%': -3.1374986908197946},
 675.8789690852451)
```

**Comment by FrancescoBonacina** [comment]
Hello, I have a related question, about the **usage of trend={'n','c','ct','ctt'} when fitting VAR models**.

From the [documentation](https://www.statsmodels.org/dev/generated/statsmodels.tsa.vector_ar.var_model.VAR.fit.html#statsmodels.tsa.vector_ar.var_model.VAR.fit) it seems to me that the `trend` parameter allows to automatically perform some pre-processing steps before fitting the VAR model. In particular, I understand that, when `trend` is:
- `n`: the VAR model $y_t = A_1 y_{t-1} + ... + A_p y_{t-p}$ is fitted on the series as it is;
-  `c`: the mean of the series is removed before the fit. So, the VAR model is fitted on the new series $(y_i - mean(y))_{i=1,...,N}$;
-  `ct`: the VAR model is fitted on the series where the linear trend has been removed: $(y_i - a - b * i)_{i=1,...,N}$;
-  `ctt`: the VAR model is fitted on the series where the quadratic trend has been removed: $(y_i - a - b * i - c* i^2)_{i=1,...,N}$.

However, **by some examples, I understand that this interpretation is NOT CORRECT**. In fact, if I consider a time series and remove the linear trend by hand and, then, I fit the VAR models on both the original and the transformed series, I find that the results do not match. [Here](https://stackoverflow.com/questions/75361018/time-series-fitting-use-of-trend-in-var-models-via-statsmodels-tsa-vector-ar) is an open question on stackoverflow with all the code and results in detail.

So, what are the calculations performed on the time series, when the  `trend` parameter is set to _n, c, ct_ and _ctt_ ?

Thank you in advance for your help!

**Comment by josef-pkt** [comment]
What you have looks like ols with VAR residuals. This is the common pattern for many tsa models.

However, VAR uses trend as regressor for the original y similar to exog x.

last sentence in the docs you linked to

`Note that these are prepended to the columns of the dataset.`

the relevant code in `_estimate_var` method is
```
            z = np.empty((x.shape[0], x.shape[1] + z.shape[1]))
            z[:, : self.k_trend] = temp_z[:, : self.k_trend]
            z[:, self.k_trend : self.k_trend + x.shape[1]] = x
            z[:, self.k_trend + x.shape[1] :] = temp_z[:, self.k_trend :]
```

However, the next part of the code makes a correction to the trend regressors, that I don't know about.
But it seems to just shift the origin of the trend.

```
        # the following modification of z is necessary to get the same results
        # as JMulTi for the constant-term-parameter...
        for i in range(self.k_trend):
            if (np.diff(z[:, i]) == 1).all():  # modify the trend-column
                z[:, i] += lags
            # make the same adjustment for the quadratic term
            if (np.diff(np.sqrt(z[:, i])) == 1).all():
                z[:, i] = (np.sqrt(z[:, i]) + lags) ** 2
```

**Comment by FrancescoBonacina** [comment]
Thank for your answer!

I'm still a bit confused. 

> However, VAR uses trend as regressor for the original y similar to exog x.

Does this mean, for example, that for `trend={n,c,ct}` the VAR model will be:
- `n`: $y_t = A_1 y_{t-1} + \dots + A_p y_{t-p}$
- `c`: $y_t = A_1 y_{t-1} + \dots + A_p y_{t-p} + c$
- `ct`: $y_t = A_1 y_{t-1} + \dots + A_p y_{t-p} + c_1 + c_2*t \quad$   ?

If so, why is the prediction of VAR(trend='n') on the translated series different from the prediction of VAR(trend='c') on the original series ? (pred_1n != pred_0c, in the last plot of [my question](https://stackoverflow.com/questions/75361018/time-series-fitting-use-of-trend-in-var-models-via-statsmodels-tsa-vector-ar) on stackoverflow)

**Comment by josef-pkt** [comment]
I'm not sure about the details, I have not looked at the VAR details in years.

Is your sample size only those 11 observations in the stackoverflow question?
If yes, then small differences like dropping initial observations will have a large effect. Those differences will disappear with increasing sample size.
VAR will need to drop the first p rows from endog, because they will be needed for regressors.

You can check the estimated trend parameter, constant and other trends. 
My guess is that those differ from the series mean or simple trend which has been directly estimated on original series.

Aside: 
It looks to me there is a bug in trend handling and there is no future exog in VAR.predict. (seems to be only for trend = "nc" or "c".)
However the VARProcess.forecast method seems to correctly build the "exog" matrix for future trend and user provided exog.
