### ISSUE TITLE
ENH: Drop testing and official support for Win32 and other 32-bit platforms

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#7463]
It is becoming more difficult to support win32 as some wheel builders are stopping support.  Should we stop testing on Win32?  

This seems reasonable to be.

**Comment by josef-pkt** [comment]
I'm fine with dropping Win32. I have not heard anything running that in a long time.

For other 32bit: Are there small or embedded devices based on Linux that we might still want to support?

**Comment by bashtage** [comment]
We don't test Linux32 or arm (too slow), so no one knows. I fixed the win32 CI for now, so it can stay, but I think its days are numbered until upstream also drop (probably pandas first).
