### ISSUE TITLE
Possibility to freeze parameters during fitting

### ISSUE THREAD

**Issue by FirefoxMetzger** [statsmodels/statsmodels#7491]
This is probably possible already, but I didn't manage to find it in the docs (maybe the wrong search terms?).

I have a feature for which I "know" what the relationship with the outcome should be, i.e., I have a-priori knowledge of what the `beta` value for this feature is. Is it possible to add such a constant feature to the model, or to freeze the parameter associated with that feature during a fit?

**Comment by bashtage** [comment]
Which model?

**Comment by FirefoxMetzger** [comment]
Wow, that was an insanely fast reply 🚀 

`statsmodels.discrete.discrete_model.Logit`

**Comment by bashtage** [comment]
You can use a `GLM` with `fit_constrained`. A Logit is a special case of a GLM where the link function is logit.

https://www.statsmodels.org/stable/generated/statsmodels.genmod.generalized_linear_model.GLM.fit_constrained.html

**Comment by bashtage** [comment]
Also https://stackoverflow.com/questions/29261018/how-to-add-sum-to-zero-constraint-to-glm-in-python

**Comment by FirefoxMetzger** [comment]
cool, I didn't know about `fit_constrained`, are those hard constraints or does it add a regularizer to the model? 
(Probably doesn't matter for my case, but does help my conceptual understanding :) )

**Comment by bashtage** [comment]
It is a hard constraint, known as a linear equality constraint.

**Comment by bashtage** [comment]
Closing since no action needed by us. Feel free to continue to post if useful.

**Comment by josef-pkt** [comment]
If the constraint is just on the parameter of an explanatory variable, then you can use `offset` for it, just set it to params * x for the fixed variable.

fit_constrained handles any linear (affine) restrictions on the parameters.
