### ISSUE TITLE
check state in repeated fit with different parameters

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#75]
for summary I would like to access the fit settings, which are currently defined in models

for example in robust

'''

> > > rlmres.model.cov
> > > 'H1'
> > > rlmres.model.scale_est
> > > 'mad'
> > > '''
> > > if fit is repeatedly called with different fit settings, then these might not be correct anymore when accessed through an earlier result instance

**Comment by bashtage** [comment]
This has been mostly fixed outside of known time series models.
