### ISSUE TITLE
Possible Problem with SARIMAX Predictions with Exogenous Regressors?

### ISSUE THREAD

**Issue by dkent603** [statsmodels/statsmodels#7512]
Just flagging this StackOverFlow posting re a possible problem with how the SARIMAX is producing predictions with models that include exogenous variables.

https://stackoverflow.com/questions/68037902/is-there-a-problem-with-sarimax-predictions-using-statsmodels

**Comment by ChadFulton** [comment]
The [SARIMAX model](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAX.html) is of the form "regression with SARIMA errors". For example, for an ARX(1) model, this is:

```
y(t) = beta' x(t) + e(t)
e(t) = phi e(t-1) + z(t)
```

while your forecasting equation would be accurate for a model of the form:

```
y(t) = beta' x(t) + phi y(t-1) + z(t)
```

If you are interested in an AR(p) model (i.e. does not include any MA terms), then you can use `sm.tsa.AutoReg`, which is of that form.

**Comment by ChadFulton** [comment]
Closing as answered, but feel free to follow up if you like.

**Comment by dkent603** [comment]
Ok, I've clearly got a gapping knowledge gap here!

Is it possible to validate how Statsmodels is arriving at the first prediction (i.e. 138068)?  In other words, how do I access e(t), phi and e(t-1)?

**Comment by ChadFulton** [comment]
The forecasting equation is:

`yhat(t+1) = beta' x(t+1) + ehat(t+1)`

For the AR(1) model, `ehat(t+1) = phi e(t)`, and you can rearrange to get `e(t) = y(t) - beta' x(t)`, and then:

```python
e = history - model_fit.params[0] * history_exog
yhat = model_fit.params[0] * future_exog[0] + model_fit.params[1] * e[-1]
```

For AR(p) models (p > 1), this is basically the same, except that the form of `ehat(t+1)` changes to include more lags.

However, if you have an MA component, then it is not straightforward to compute the exact forecasts by hand, as described in [this stack exchange answer](https://stats.stackexchange.com/questions/430186/how-statsmodels-predict-ma-process/430274#430274)
