### ISSUE TITLE
DOC: modernize example notebook prediction

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#7517]
https://www.statsmodels.org/dev/examples/notebooks/generated/ols.html

still uses the old `wls_prediction_std` instead of get_prediction

blog post that includes examples from notebooks and doesn't use get_prediction
https://translate.google.com/translate?sl=auto&tl=en&u=https://qiita.com/innovation1005/items/b712ce54a7a697a9bf03
(looks like a good overview post)

**Comment by vineethhk1993** [comment]
Hi,

Should I create examples in a document for get_prediction with similar theory as in this link? : https://translate.google.com/translate?sl=auto&tl=en&u=https://qiita.com/innovation1005/items/b712ce54a7a697a9bf03 

Or should we just stick to the style mentioned in this: https://www.statsmodels.org/dev/examples/notebooks/generated/ols.html

**Comment by josef-pkt** [comment]
Any usage of wls_prediction_std should be removed and replaced by calls to get_prediction.
Plus a bit of illustration what’s returned by get_prediction.

I’m travelling and have only ipad with me, so I cannot check details

**Comment by vineethhk1993** [comment]
[Get_Prediction_Document.zip](https://github.com/statsmodels/statsmodels/files/6913133/Get_Prediction_Document.zip)

I have attached the ipynb file in a zipped folder. Please can you review if this works. Or please can you let me know if there is a different way to submit this?

**Comment by bashtage** [comment]
@vineethhk1993 Can you open a PR with the modified notebook?

**Comment by vineethhk1993** [comment]
@bashtage I was not sure which notebook to modify. So I copy pasted the text from here https://www.statsmodels.org/dev/examples/notebooks/generated/ols.html into my jupiter notebook and then made changes to the parts where wls_prediction_std is used and made changes required. Should I add it as a new file or something?

**Comment by bashtage** [comment]
The edits should be made to ols.ipynb in the examples/notesbooks folder.  Once this notebook is updated, you can make a PR with the changes.

**Comment by bashtage** [comment]
It appears in 3 notebooks, which should all be updated:

examples/notebooks/wls.ipynb
examples/notebooks/robust_models_0.ipynb
examples/notebooks/ols.ipynb

**Comment by bashtage** [comment]
https://github.com/statsmodels/statsmodels/search?l=Jupyter+Notebook&q=wls_prediction_std

**Comment by vineethhk1993** [comment]
@bashtage Please can you check if this is okay. When running the code, it did not through any errors.

**Comment by vineethhk1993** [comment]
@bashtage and @josef-pkt I was not sure to do a rebase. I have closed the previous pull request and deleted the branch after removing the output. I hope this is the same as rebase. I will try to learn to do a rebase.

**Comment by bashtage** [comment]
This is not the same.

**Comment by bashtage** [comment]
I think you have lost the changes. The simplest way would be to start a new branch from main, incorporate the changes, make sure the notebooks are clear, and then start a new PR.

**Comment by bashtage** [comment]
I took your changes and incorporated them. Thanks for the help!
