### ISSUE TITLE
TypeError: predict() missing 1 required positional argument: 'params'

### ISSUE THREAD

**Issue by AryanBajaj104** [statsmodels/statsmodels#7518]
I am unable to understand this error. Please help me in solving this

**Comment by bashtage** [comment]
Can you paste the code you are running?

**Comment by AryanBajaj104** [comment]
Code: 
forecast1=model.predict(n_periods=8, return_conf_int=True)

Error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-70-490c65bf25d0> in <module>
----> 1 forecast1=model.predict(n_periods=8, return_conf_int=True)

TypeError: predict() missing 1 required positional argument: 'params'

**Comment by AryanBajaj104** [comment]
> Can you paste the code you are running?
Code:
forecast1=model.predict(n_periods=8, return_conf_int=True)

Error:
TypeError Traceback (most recent call last)
in
----> 1 forecast1=model.predict(n_periods=8, return_conf_int=True)

TypeError: predict() missing 1 required positional argument: 'params'

**Comment by AryanBajaj104** [comment]
> Can you paste the code you are running?

Code:
forecast1=model.predict(n_periods=8, return_conf_int=True)

Error:
TypeError Traceback (most recent call last)
in
----> 1 forecast1=model.predict(n_periods=8, return_conf_int=True)

TypeError: predict() missing 1 required positional argument: 'params'

**Comment by bashtage** [comment]
What is `model`?  Please past a full example showing completely what you are doing.

**Comment by AryanBajaj104** [comment]
> What is `model`? Please past a full example showing completely what you are doing.

model = sm.tsa.statespace.SARIMAX(db_T['compound'],order=(1,1,1),seasonal_order=(1,1,1,12))
results=model.fit()

**Comment by bashtage** [comment]
Make prediction from `result`, not `model`..

**Comment by bashtage** [comment]
I don't know what `n_periods` is, but it isn't one the variables in `predict`.

https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.sarimax.SARIMAXResults.predict.html

**Comment by bashtage** [comment]
Closing since no action for us.

**Comment by xuanhaodong** [comment]
Thanks for your answer!  But I still wonder that why change from model to result then predict() can function normally

**Comment by bashtage** [comment]
Model `predict`s always require parameters.  Result `predict`s always use the parameter of the fitted model.  No change.
