### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'DateOffset'

### ISSUE THREAD

**Issue by AryanBajaj104** [statsmodels/statsmodels#7519]
Code:
from pandas.tseries.offsets import DateOffset
future_dates = [db_T.index[-1] + DateOffset(minute=x) for x in range(0,24)]

Output:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-99-f3314c72ffff> in <module>
----> 1 future_dates = [db_T.index[-1] + DateOffset(minute=x) for x in range(0,24)]

<ipython-input-99-f3314c72ffff> in <listcomp>(.0)
----> 1 future_dates = [db_T.index[-1] + DateOffset(minute=x) for x in range(0,24)]

TypeError: unsupported operand type(s) for +: 'int' and 'DateOffset'

**Comment by bashtage** [comment]
This is a pandas issue.  Or probably more appropriate for stackoverflow.
