### ISSUE TITLE
SARIMAX - Plotly - Approach while using dynamic =True and dynamic = False in SARIMAX forecasting

### ISSUE THREAD

**Issue by Ruhul786** [statsmodels/statsmodels#7520]
I have a dataset containing monthly commodity price. I want to predict price using SARIMAX. I  want to predict price for next 24 months. Initially I had 509 rows of actual monthly price. Now I would like to forecast price for next 24 months (or 24 rows) for which I have created new Dataframe. The new Dataframe also consists of actual Dataframe rows.

*When I am using below code, I am getting this graph using "dynamic =True"*:

     future_df['forecast'] = results.predict(start = 508, end =533, dynamic =True)
     px.line(future_df, x='Date', y= ['Price','forecast'],template = 'plotly_dark')

[![enter image description here][1]][1]

*When I am using below code, I am getting this graph using "dynamic =False":*

    future_df['forecast'] = results.predict(start = 508, end =533, dynamic =False)
    px.line(future_df, x='Date', y= ['Price','forecast'],template = 'plotly_dark')

[![enter image description here][2]][2]

**Now the actual problem comes, I am getting different graphs**

*I am getting different graphs when I am using below codes using "dynamic =True" or "dynamic =False", which was not the case previously.*

future_df['forecast'] = results.predict(start = 400, end =533, dynamic =True)

px.line(future_df, x='Date', y= ['Price','forecast'],template = 'plotly_dark')

[![enter image description here][3]][3]

 
future_df['forecast'] = results.predict(start = 400, end =533, dynamic =False)                
     px.line(future_df, x='Date', y= ['Price','forecast'],template = 'plotly_dark')

[![enter image description here][4]][4]

**My Queries**
1) Why I am getting difference in graph. I can notice that dynamic =False gives better prediction in comparison to dynamic = True.
2) Which Approach (dynamic =False or dynamic = True) I should follow while forecasting (start = 508, end =533) and also while validating  (for eg start = 400, end =533 or  start = 400, end= 508)

  [1]: https://i.stack.imgur.com/Gpn21.png
  [2]: https://i.stack.imgur.com/mGsDM.png
  [3]: https://i.stack.imgur.com/MW2Jj.png
  [4]: https://i.stack.imgur.com/vyavM.png

**Comment by ChadFulton** [comment]
Statsmodels allows you to make two kinds of predictions: in-sample predictions (i.e. model-based predictions for time periods where you also have observed data in your sample) and out-of-sample predictions (i.e. forecasts of periods that are not in your sample.

By default (`dynamic=False`), in-sample predictions are one-step-ahead predictions. This means they are computing the prediction for the period `t+1` is conditional on all of the data through period `t`, while the prediction for the period `t+2` is conditional on all of the data through the period `t+1`. This is the red line in the last graph in your post.

However, sometimes you want to fix an ending point `t` within your sample and produce predictions `t+1`, `t+2`, ... each conditional on the data through period `t`. This is what the `dynamic` argument allows you to do. If you set `start=400, dynamic=True` then you will produce predictions for periods `400`, `401`, ... each conditional on the data through period `399`. This is the red line in the third graph in your post.

Out-of-sample forecasts are always "dynamic", because you are making predictions outside your sample.

**Comment by ChadFulton** [comment]
Closing this issue as answered, but feel free to follow up if you like.

**Comment by Ruhul786** [comment]
Hi @ChadFulton, thanks for the response.  Very Helpful;

I still have few more queries:

**Q1)** Initially I had 509 rows i.e. Monthly price for 509 time periods (= rows). Now I want to predict price for next 24 months. As per your comment, I understand that "dynamic=True" should be better approach for forecasting.   Please advise otherwise.

**Q2)** I have built SARIMAX model on all 509 rows. I want to validate model per graph. Which approach shall I use "dynamic = True" or "dynamic = False" ?  For e.g. I want to validate price for last 133 rows price within 509 rows using plotly.   I can see that "future_df['forecast'] = results.predict(start = 400, end =533, dynamic =False)"  is  giving me better graph in comparison to "future_df['forecast'] = results.predict(start = 400, end =533, dynamic =True)". Please advise.

**Q3)** My predictions using dynamic =true and false are same (refer Q1).  Please see below code with outputs.

**_##  Forecasting using dynamic =True_**
future_df['forecast'] = results.predict(start = 510, end =533, dynamic =True)

509            NaN
510    4697.509465
511    4856.310742
512    4755.252961
513    4787.155811
514    4663.267482
515    4797.953182
516    4888.939789
517    4867.187318
518    4914.688052
519    5096.828530
520    5220.873406
521    5295.573417
522    5542.382493
523    5575.436461
524    5475.326039
525    5524.854306
526    5314.567943
527    5512.470648
528    5556.571233
529    5434.857829
530    5363.764829
531    5541.740158

**_##  Forecasting using dynamic =False**
future_df['forecast'] = results.predict(start = 510, end =533, dynamic =False)

509            NaN
510    4697.509465
511    4856.310742
512    4755.252961
513    4787.155811
514    4663.267482
515    4797.953182
516    4888.939789
517    4867.187318
518    4914.688052
519    5096.828530
520    5220.873406
521    5295.573417
522    5542.382493
523    5575.436461
524    5475.326039
525    5524.854306
526    5314.567943
527    5512.470648
528    5556.571233
529    5434.857829
530    5363.764829
531    5541.740158

**Now I am confused which approach to use for forecasting price for next 24 months,
** if predictions are similar for next 24 months.

Please Advise. **Thanks for help in Advance!**

**Comment by bashtage** [comment]
Out of sample forecasts are always dynamic. Dynamic only matters if the
dynamic point is in sample.

**Comment by Ruhul786** [comment]
Thanks @bashtage. Why my predictions are same using both dynamic approaches   for predicting price for  next 24 months.  

Please,  can you also look into other queries.
