### ISSUE TITLE
Simulation of time series 

### ISSUE THREAD

**Issue by tomasj12** [statsmodels/statsmodels#7524]
Hi,

I would like to ask you what is the purpose of the method ```simulate``` of ```SARIMAX```. If I applied this function, what exactly received? Are those simulations predictions? Or just generated new sarimax time series? And what is the exact purpose of ```params``` parameter? Anyway, is there any option, how to generate time series, e.g for some research purposes?

**Comment by bashtage** [comment]
It simulates a time series the follows the same model.  It is otherwise different from the original one. It could be used, for example, to study the finite sample properties of an estimator.

**Comment by bashtage** [comment]
Closing since no action; please feel free to ask additional clarifying questions.

**Comment by tomasj12** [comment]
Okay, but i want to do simulations like that:

Y_{t} = b0 + b1X_{t} + gamma err_{t},

where X is exogenous (should be class of time series or not), but err is generated as ARMA process, how can I do such simulations ?

**Comment by bashtage** [comment]
https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAX.simulate.html

Pass `exog` to `simulate`.
