### ISSUE TITLE
BUG: Display error on the website under the category of forecasting example (which is Theta)

### ISSUE THREAD

**Issue by cuzy-zhi** [statsmodels/statsmodels#7537]
Please refer to the examples show below:
https://www.statsmodels.org/stable/examples/notebooks/generated/theta-model.html

In the second example, it forecasts using different theta values, however, the forecasted results are not shown in the pic due to a lack of freq in original data. 

The bug can be easily fixed by add one line of code before "mod = ThetaModel(np.log(pce))":
pce.index.freq = '3MS'

Thanks,
Zhi

**Comment by bashtage** [comment]
Thanks for the report. Fixed in master, and will get up as soon as doc builds resume.
