### ISSUE TITLE
DOC: Completing doc build move

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#7548]
@josef-pkt  docs are now build in PRs and after merges automatically using a GitHub action. Right now, these docs are committed but not pushed.  In order to push the docs, two things are needed:

- [x] Create a token for the https://github.com/statsmodels/statsmodels.github.io repo with push (write) access.
- [x] Store this token in the https://github.com/statsmodels/statsmodels repo secrets as `GITHUB_DOCBUILD_TOKEN`

This block can then be enabled to push the changes to the documentation hosting repo.

https://github.com/statsmodels/statsmodels/blob/aa96d18354d1d9f19b9ff2374fec4b6debe65cc0/.github/workflows/generate-documentation.yml#L57-L64

**Comment by josef-pkt** [comment]
Thanks for adding this.

I'm not sure what creating a token means.
Can I just add another deploy key to https://github.com/statsmodels/statsmodels.github.io/settings/keys ?
or do I need a personal access token?

I didn't find information in the github docs to understand this.
AFAICS, there are no organization or repo tokens.

**Comment by bashtage** [comment]
I think we will need a personal access token for the statsmodels org. This will need the ability to write.  This token can then be stored as a secret `GITHUB_DOCBUILD_TOKEN`

For PAT:

https://docs.github.com/en/actions/reference/authentication-in-a-workflow#granting-additional-permissions

For secret:

https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository

**Comment by bashtage** [comment]
Could also go with a deploy key.  This would need a more convoluted process than using the github action to push.

**Comment by bashtage** [comment]
The idea is to use https://github.com/ad-m/github-push-action to deploy, which is easy once a PAT has been stored in a secret.

**Comment by josef-pkt** [comment]
names of secrets are not allowed to start with github.
I added personal access token key as secret to statsmodels/statsmodels with name DOCBUILD_TOKEN
