### ISSUE TITLE
Wrong p-value in pairwise_tukeyhsd?

### ISSUE THREAD

**Issue by MarionBug** [statsmodels/statsmodels#7566]
#### Describe the bug

I need to perform an anova for repeated measures with a post-hoc Tukey test.
As I am very new to python, I tested my code with the example below. Here, I used only two groups, so that a comparison of results with a paired-sample t-test is possible (these should lead to the same p-values and meanDiffs). Also, I repeated both the t-test and the Tukey-test in Matlab (because here I have experience).

I am using the methods: statsmodels.stats.multicomp.pairwise_tukeyhsd and scipy.stats.ttest_rel My original data are a pd.dataframe, therefore I also used this in the example.

In my point of view, the p-values calculated in the Tukey test are wrong. The p-values from ttest_rel are in agreement with the ones I get in Matlab (agreement even of all digits) using both, t-test for paired samples and Tukey test.

```python
import numpy as np
import pandas as pd 

from scipy.stats import ttest_rel
from statsmodels.stats.multicomp import (MultiComparison, tukeyhsd, pairwise_tukeyhsd)

testData = [10, 12, 8, 9, 16, 13, 12, 13, 9, 15, 8, 14, 10, 13, 8, 15, 13, 12, 10, 11]
groups = [1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2]
testList = []

for ne, e in enumerate(testData):
    row = []
    row.append(e)
    row.append(groups[ne])
    testList.append(row)

dfTest = pd.DataFrame(data = testList, 
        columns=["data", "groups"])

d1 = dfTest[dfTest.groups == 1].data.to_numpy()
d2 = dfTest[dfTest.groups == 2].data.to_numpy()
ttestRes = ttest_rel(d1,d2,alternative = 'two-sided')
print(ttestRes)

tukeyResTest = pairwise_tukeyhsd(endog=dfTest['data'], 
                                  groups=dfTest['groups'],alpha=0.05)

print(tukeyResTest)
```

#### Expected Output

p-values from tukeyhsd should be exactly the same as those from ttest_rel.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.9.2.final.0

statsmodels
===========

Installed: 0.12.2 (C:\Users\bug01\AppData\Local\Programs\Python\Python39\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.20.1 (C:\Users\bug01\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy)
scipy: 1.6.1 (C:\Users\bug01\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy)
pandas: 1.2.3 (C:\Users\bug01\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas)
    dateutil: 2.8.1 (C:\Users\bug01\AppData\Roaming\Python\Python39\site-packages\dateutil)
patsy: 0.5.1 (C:\Users\bug01\AppData\Local\Programs\Python\Python39\lib\site-packages\patsy)

Optional Dependencies
=====================
matplotlib: 3.4.2 (C:\Users\bug01\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 1.0.1 (C:\Users\bug01\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib)

Developer Tools
================

IPython: 7.21.0 (C:\Users\bug01\AppData\Roaming\Python\Python39\site-packages\IPython)
    jinja2: 2.11.3 (C:\Users\bug01\AppData\Local\Programs\Python\Python39\lib\site-packages\jinja2)
sphinx: Not installed
    pygments: 2.8.1 (C:\Users\bug01\AppData\Roaming\Python\Python39\site-packages\pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by josef-pkt** [comment]
tukey-hsd assumes independent samples. The pvalues and critical values are derived under independence assumption.

tukeyResTest agrees with ttest_ind at 5 decimals in your example

**Comment by josef-pkt** [comment]
paired t-test like ttest_rel is just a one sample test on the difference

If you have several independent pairs of samples, then you can use tukeyhsd to test whether the difference in the pair values are statistically significant across pairs of paired samples.

**Comment by MarionBug** [comment]
Thanks josef-pkt. 
However, I have **dependent** pairs of samples! 
Sorry, that my description was not very clear: In fact, I compare **ttest_rel and pairwise_tukeyhsd** (please see my code above).

These should give the same p-values or not?

**Comment by josef-pkt** [comment]
> These should give the same p-values or not?

No, 
ttest_rel takes the difference between each paired observation and tests the mean difference.
ttest_ind computes the mean of each sample and tests the difference in means. tukey-hsd has the same assumptions as ttest_ind.

Because the tests are derived under different assumptions, the distribution of the test statistics, and so p-values, are not the same.

**Comment by josef-pkt** [comment]
How did you do that in matlab?
It should also be the same there, i.e. tukey-hsd is not compatible with paired t-tests.

**Comment by MarionBug** [comment]
Sure, ttest_ind and ttest_rel give different results.
What I mean is that the p-values from ttest_rel and pairwise_tukeyhsd should be the same, just as the ones of ttest_ind and tukeyhsd agree (as you pointed out above).

In matlab I used the functions ttest (obviously) and the statistics output from a repeated measures ANOVA as input for the multcompare function.

**Comment by MarionBug** [comment]
For my example above, I get p-values
0.051 for ttest_rel
0.034 for pairwise_tukeyhsd

In matlab, I get for both function
0.051
and this is definitely for pairwise samples

**Comment by MarionBug** [comment]
Well, it seems to me that the problem here is that pairwise_tukeyhsd is actually not treating pairwise samples. 
The output of pairwise_tukeyhsd is just the same as for tukeyhsd.

The description of pairwise_tukeyhsd, however says:
"Calculate all pairwise comparisons with TukeyHSD confidence intervals"

Can you confirm this?

**Comment by josef-pkt** [comment]
The name `pairwise_tukeyhsd` does not mean paired sample, it's short for "pairwise comparison of independent samples using tukeyhsd as multiplicity correction"

tukeyhsd and `pairwise_tukeyhsd` run the same test, the difference is in inputs:
The `tukeyhsd` function takes summary statistics mean_all, nobs_all, var_all to compute tukey hsd tests.
`pairwise_tukeyhsd` takes data, computes the summary statistic and then uses the tukeyhsd function for the actual test.

It would be better to rename tukeyhsd to indicate it's `tukeyhsd_from_summary_statistics`

**Comment by MarionBug** [comment]
this makes sense now. Thanks! 
At least the short description ""Calculate all pairwise comparisons with TukeyHSD" should be changed as it is quite misleading.

Are you aware if there is a function in python to perform a tukey test for dependent, repeated measures?

**Comment by josef-pkt** [comment]
i was looking at https://www.mathworks.com/help/stats/multiple-comparisons.html
and https://www.mathworks.com/help/stats/repeatedmeasuresmodel.multcompare.html

I don't understand what they are doing in the repeated measures case.

tukeyhsd itself assumes independent. I guess the repeated measures anova computes some summary statistics for each relevant group, so that those can be interpreted as independent across groups.
Then the group means/effects or group marginal means can then be compared with tukeyhsd, similar to my example above of using within differences of paired samples and test those across samples.

If we can compute the mean, var summary statistics for those groups, then we could use the `tukeyhsd` from summary statistic function to compute the pairwise comparison.

An alternative is to use one of the generic p-value correction for multiplicity that does not assume that individual p-values are uncorrelated.

I don't know of any package that has multiple testing for repeated measures.
The best post-hoc package in python is https://github.com/maximtrp/scikit-posthocs but I don't see it in the table of content.

**Comment by MarionBug** [comment]
Yeah, the application of post-hoc analysis to a 2-way repeated measures ANOVA in matlab was a bit of a pain. I managed to get plausible results but am far from understanding how it works. It may well be how you describe.

p-value corrections for multiplicity are an option - I will go for that first. 

Thanks again for your help and clarification!
