### ISSUE TITLE
Wrong import in tsa.deterministic.Fourier example

### ISSUE THREAD

**Issue by felipeangelimvieira** [statsmodels/statsmodels#7585]
The current example for generating Fourier decomposition terms is not importing Fourier correctly.

```
from statsmodels.datasets import sunspots
from statsmodels.tsa.deterministic import Seasonality
data = sunspots.load_pandas().data
fourier_gen = Fourier(11, order=2)
fourier_gen.in_sample(data.index)
```

#### Expected Output

Dataframe containing fourier terms

#### Output

NameError: name 'Fourier' is not defined

The fix is really simple, just need to change `import Seasonality` to `import Fourier`

**Comment by bashtage** [comment]
Thanks for reporting.
