### ISSUE TITLE
BUG: problems with kwarg checking in 7596

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#7598]
"attach_wls" GLM fit keyword now raises exception
https://github.com/statsmodels/statsmodels/pull/7597#issuecomment-884430376

there might be more keywords that are not unit testes

I think it's better to make this for now into a Warning and not an exception.
Exception is too risky to break code. And extra keywords are not fatal, so we don't really need to raise.

**Comment by josef-pkt** [comment]
(similarly: I issue a warning if df is inconsistent in GenericLikelihoodModel to catch mistakes, but most results don't depend on correct df_model)

**Comment by josef-pkt** [comment]
another problem for us

If we switch the default optimizer in a class, then all unit test might raise exception. And we cannot even see what the results are before having to fix all optimizer specific keywords.
Similarly, unit test subclasses cannot have generic keywords if subclasses use different methods with inconsistent keywords.
It's possible to clean those, but it adds a lot of cleaning burden during test development.

**Comment by bashtage** [comment]
> If we switch the default optimizer in a class, then all unit test might raise exception. And we cannot even see what the results are before having to fix all optimizer specific keywords.

If you just change `method` then you won't have any troubles.  

> Similarly, unit test subclasses cannot have generic keywords if subclasses use different methods with inconsistent keywords.

They would just need to set a cls variable with optimizer-specific keywords in the `setup_class`.  Or just use fixtures that pass model and optimizer kwargs.

**Comment by josef-pkt** [comment]
switching default `method` e.g. from bfgs to newton or reversed will require adjusting all unit test fit calls that use optimizer kwargs. 

I agree with everything, I only want to downgrade it to a Warning. 
Exceptions, if they are not for an essential/fatal problem, are a real pain for development. 

---

The advantage of kwargs, e.g. in `model.__init__` is that I write a new subclass with new keywords and most things work right away because of inheritance.
(If the super classes are not flexible enough, then a lot of time needs to spend on fixing inherited methods, e.g. what I had to two for handling the second exog in beta regression.)

**Comment by bashtage** [comment]
This is not a warning.  Raises on internal code in CI though.
