### ISSUE TITLE
Mistake in labels of qqplot_2samples

### ISSUE THREAD

**Issue by parthe** [statsmodels/statsmodels#7610]
#### Describe the bug

statsmodels.graphics.gofplots.qqplot_2samples docs have a bug.
data1 appears on y-axis and data2 appears on x-axis. This is contrary to what is mentioned in the docs.

#### Code Sample, a copy-pastable example if possible

```python
import matplotlib.pypot as plt
import numpy as np
from statsmodels.graphics.gofplots import qqplot_2samples
x=np.random.normal(10,1,(100,))
y=np.random.normal(1,.1,(100,))
qqplot_2samples(xx, xy, 'x', 'y')
plt.show()
```

**Comment by bertjebertjek** [comment]
May I suggest changing xlabel to label_1 and ylabel to label2 (or sth similar). Because now it is not clear from the docs that the labels change when data changes axes. Since the label does change with the axis, it would be more logical to refer to them as the data label than the axis label.
