### ISSUE TITLE
how intercept is calculate in the quantile regression

### ISSUE THREAD

**Issue by naarkhoo** [statsmodels/statsmodels#7622]
this is not really a bug and I appologize to ask it here - if there is any other place that suits for such a question please let me know.

I wonder where the intercept is calculate in the quantile regression because I don't see any where in the source code that it is calculate https://github.com/statsmodels/statsmodels/blob/main/statsmodels/regression/quantile_regression.py - I can see if I call the library and fit the model, the summary comes with an intercept. however, I am curious the underling code.

Thank you

**Comment by bashtage** [comment]
Intercept is just the parameter on a columns of 1s in the exog matrix.  The same as in OLS. There is no special treatment for the intercept.

**Comment by naarkhoo** [comment]
thanks for the prompt reply so if my input is a vector of 1xn - my exog is 

`exog = np.hstack((np.ones((X.shape[0], 1), dtype=X.dtype), X))`

?

**Comment by bashtage** [comment]
Just use `exog = sm.add_constant(X)`.
