### ISSUE TITLE
How to disable adfuller multi-threading/multi-processing/multi-cores?

### ISSUE THREAD

**Issue by GF-Huang** [statsmodels/statsmodels#7623]
![image](https://user-images.githubusercontent.com/4510984/128285375-e1cce735-32fd-4c03-bb39-6849d4e50a5b.png)

```py
import statsmodels.tsa.api as tsa

...
for x in xxx:
   result = tsa.adfuller(...)
...
```

**Comment by bashtage** [comment]
before you start you session set
```
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
```

to limit the BLAS libraries to a single thread.

Alternatively you can use https://github.com/joblib/threadpoolctl to dynamically change the number of threads.
