### ISSUE TITLE
Unable to install statsmodels on Python 3.9 on OSX ( Mojave )

### ISSUE THREAD

**Issue by nanashi95** [statsmodels/statsmodels#7626]
Hello,

I have tried installing statsmodels on my mac (Mojave) , but it does not seem to be working. I used python3 -m pip install statsmodels command on my command window and it output the following error "Failed to build statsmodels
ERROR: Could not build wheels for statsmodels which use PEP 517 and cannot be installed directly"

I have attached screenshot of the output below: 

<img width="1440" alt="スクリーンショット 2021-08-07 18 33 09" src="https://user-images.githubusercontent.com/9195698/128595854-61c4c8d3-7cf2-47a9-8a61-b1509729c837.png">

<img width="1440" alt="スクリーンショット 2021-08-07 18 33 30" src="https://user-images.githubusercontent.com/9195698/128595861-078d3ee6-b23e-451a-8077-2233e436e3d8.png">

I can successfully import Numpy in an ipython session so I guess my numpy is ok

<img width="470" alt="スクリーンショット 2021-08-07 18 39 40" src="https://user-images.githubusercontent.com/9195698/128596004-ce2357dc-0be9-4167-80ad-0d8eac3aa5af.png">

Anyone know what could be missing here ?

Thanks a lot for your help !

**Comment by bashtage** [comment]
Install Numpy, SciPy and cython. The pip install without build isolation so that it doesn't try to build the packages again.

**Comment by nanashi95** [comment]
Numpy and SciPy were alrd installed so I added cython.
I reran the command with the --no-build-isolation flag and it finally installed version 0.10.2 after yielding errors. on each version starting from 0.12.2

<img width="1440" alt="スクリーンショット 2021-08-07 19 40 23" src="https://user-images.githubusercontent.com/9195698/128597530-fb94e348-7875-491a-8358-73a2f7343571.png">
<img width="1440" alt="スクリーンショット 2021-08-07 19 40 39" src="https://user-images.githubusercontent.com/9195698/128597533-4db477d7-929d-4d0d-8993-95a5de03e5a5.png">
<img width="1440" alt="スクリーンショット 2021-08-07 19 40 54" src="https://user-images.githubusercontent.com/9195698/128597534-968cb737-8883-4852-9a0b-dbef3526664b.png">
<img width="1439" alt="スクリーンショット 2021-08-07 19 41 12" src="https://user-images.githubusercontent.com/9195698/128597535-f98f1b2b-be28-4962-9af1-84bb62525cee.png">
<img width="1440" alt="スクリーンショット 2021-08-07 19 41 22" src="https://user-images.githubusercontent.com/9195698/128597536-d4a9f7d9-d938-4b4e-a4eb-881510030108.png">
<img width="1440" alt="スクリーンショット 2021-08-07 19 41 37" src="https://user-images.githubusercontent.com/9195698/128597555-54c595b6-1b29-4e70-b286-8c91530a2bee.png">

In my case I need version 0.12.2 but upgrading from the current 0.10.2 does not work ( even with the no-build isolation ).

Is the version 0.12.2 available for python 3.9 ?

**Comment by bashtage** [comment]
Update setuptools and wheel using pip

**Comment by bashtage** [comment]
Please post the entire build log to a gist. Screens shots are not very easy to understand.

**Comment by nanashi95** [comment]
That was it !
After updating setuptools and wheel, I tried rebuilding statsmodels and 0.12.2 is now installed !

Just in case I added yesterday's trace into a gist, it might be useful to someone else.

[https://gist.github.com/nanashi95/8914004bc151dca7f0b602fce8153ca0](url)

Thank a lot for your help and patience !

**Comment by bashtage** [comment]
There was a hint about bdist_wheel in the log.
