### ISSUE TITLE
How can I find the intercept on a rollingOLS?

### ISSUE THREAD

**Issue by gautambak** [statsmodels/statsmodels#7634]
Hi There,

I can get the beta but I'm not sure how to get the intercept on a rollingOLS. I went through the options and documentation but it's not clear to me. We have tried params and

**Comment by bashtage** [comment]
If your exog contains a constant, then the rolling value of this coefficient is reported along side all other coefficients.  See cell [3] in this notebook: https://www.statsmodels.org/stable/examples/notebooks/generated/rolling_ls.html which shows two columns, const and Mkt-RF.  const is the constant.

**Comment by bashtage** [comment]
Closing as answered.  Please continue to post if this answer is not clear.
