### ISSUE TITLE
Does dynamic prediction ability still exist?

### ISSUE THREAD

**Issue by PeterGrant** [statsmodels/statsmodels#7635]
Hello,

I'm implementing SARIMAX to provide hourly building energy and PV power predictions over the next 24 hours. Since these predictions are for the next 24 hours I will not have access to the data earlier in the prediction cycle (E.g. When predicting at hour 20 I will not have measured data for hour 19). I've been implementing it following the [example in the introduction](https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_sarimax_stata.html) of your documentation, but a few things seem to have changed. Specifically:

- The get_predictions() method no longer seems to exist, and
- I don't see a method that provides dynamic prediction capabilities.

Do these capabilities still exist, but with different names? Is there currently a way to do this?

Thanks,
-Peter

**Comment by ChadFulton** [comment]
Hi Peter, I just want to double-check if you are using the method `get_prediction` - in your message, you have an extra "s" at the end? Possibly this will solve the problem, since dynamic prediction should still be available.

**Comment by PeterGrant** [comment]
Hi Chad, thanks for the quick reply. Yes I do have a typo in my message, and yes I did mean to enter get_prediction(). 

I'm still a bit confused here. I don't see get_prediction listed as a method in the [SARIMAX documentation](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAX.html) so I'm not sure what the parameters are or how to use it. I need to use dynamic from the very start of the timesteps that I pass to it. The example says that it start is not defined it is assumed to be 0. So can I simply use .get_prediction(dynamic)? Should it be .get_prediction(dynamic=0)?

Thanks,
-Peter

**Comment by ChadFulton** [comment]
Thanks for checking.

`get_prediction` is a method available for results objects, so it is available on the [`SARIMAXResults`](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAXResults.html) documentation page.

If you want to always use dynamic prediction from `start` onwards, you can pass `dynamic=True` or `dynamic=0`.

Please note that if you are forecasting out-of-sample, then using `dynamic` has no effect. The `dynamic` argument only matters for in-sample prediction.

Best,
Chad

**Comment by ChadFulton** [comment]
Closing as answered, but feel free to follow up.
