### ISSUE TITLE
SARIMAX sets first fittedvalue to 0

### ISSUE THREAD

**Issue by RylanSchaeffer** [statsmodels/statsmodels#7640]
I'm trying to use statsmodels' SARIMAX on some very simple data, but for some puzzling reason, the fittedvalues appear to be shifted by one.

The original data:

```
>>> log_values
0      2.499385
1      2.460272
2      2.638629
3      2.682869
4      2.853247
         ...   
518    3.701919
519    3.682937
520    3.788951
521    3.980933
522    4.141244
```

I run the following code:

```
mod = SARIMAX(log_values, order=(1, 0, 0,), seasonal_order=(0, 0, 0, 12))
results = mod.fit()
```

The first fitted value is 0 and the outputs are shifted by 1. I think this is a bug.

```
>>> results.fittedvalues
0      0.000000
1      2.498681
2      2.459580
3      2.637886
4      2.682114
         ...   
518    3.634403
519    3.700877
520    3.681900
521    3.787885
522    3.979813
```

**Comment by ChadFulton** [comment]
Closing as answered, but feel free to follow up.

**Comment by RylanSchaeffer** [comment]
I had no idea, and I don't think that's clear from the documentation (https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAXResults.html), which reads"(array) The predicted values of the model," which does not make explicit predicted means a single step prediction

**Comment by bashtage** [comment]
It is assumed in the docs that predicted values from SARIMAX models are predicted mean values, since a SARIMAX is a model of the conditional mean of the data/process.
