### ISSUE TITLE
BUG: error in unit test with new random state

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#7650]
I'm getting test failures on several machines with Frank copula `random`

https://dev.azure.com/statsmodels/statsmodels-testing/_build/results?buildId=3656&view=logs&j=6d200f9d-dbf4-5dc2-edd7-7b205dcb6b25&t=72e19cf2-5f62-5615-2202-828a25168f08&l=373

according to codecov in #7608, the numpy. default_rng has no unit test coverage

I didn't look at the details for new RandomState, but we need compatibility with older numpy and scipy.
I don't know what's the problem with my unit test case in #7648 in those cases.

**Comment by josef-pkt** [comment]
@bashtage @tupui

**Comment by bashtage** [comment]
Minimum NumPy is 1.17 so it should work with `default_rng` or `RandomState`.

**Comment by josef-pkt** [comment]
The ValueError is raised in scipy in check_random_state

Collecting numpy==1.18.5
  Downloading numpy-1.18.5-cp38-cp38-manylinux1_x86_64.whl (20.6 MB)
Collecting scipy==1.3.3
  Downloading scipy-1.3.3-cp38-cp38-manylinux1_x86_64.whl (25.2 MB)

```
/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py:970: in rvs
    self._random_state = check_random_state(rndm)
/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/scipy/_lib/_util.py:189: in check_random_state
    raise ValueError('%r cannot be used to seed a numpy.random.RandomState'
E   ValueError: Generator(PCG64) at 0x7FB5F086B400 cannot be used to seed a numpy.random.RandomState instance
```

**Comment by bashtage** [comment]
Looks like you need to explicitly pass a RandomState instance if you have to use an ancient SciPy.

**Comment by tupui** [comment]
This is because SciPy is too old. In later versions, `check_random_state` accept `RandomState` and just returns it.

**Comment by tupui** [comment]
Our function is doing the correct thing here. We support NumPy 1.17 so we want to let the users use `Generator`, hence we need to update SciPy to allow this.

**Comment by josef-pkt** [comment]
Then there should be a scipy version check and compat code in our tools check_random_state, as long as we haven't dropped older scipy.

**Comment by josef-pkt** [comment]
I haven't looked at #7605 yet. dropping scipy 1.3

**Comment by tupui** [comment]
Why not dropping SciPy 1.3? As per NEP29, it's deprecated and we should upgrade to 1.4.

**Comment by tupui** [comment]
> I haven't looked at #7605 yet. dropping scipy 1.3

This PR is not doing much (and started with a mistake of mine), it's not touching at the CI for instance. If we want to do this, we would need to do more OC.

**Comment by josef-pkt** [comment]
Another problem
our check_random_state doesn't use the global numpy random state by default.

I set a global seed, `np.random.seed(....)` but it doesn't fix the seed in the copulas.

I have been running around in circles for several hours because I cannot get consistent optimization in repeated runs my new CopulaModel unit tests. :(

**Comment by josef-pkt** [comment]
how do we get the global random state back?

**Comment by bashtage** [comment]
> Another problem
> our check_random_state doesn't use the global numpy random state by default.
> 
> I set a global seed, `np.random.seed(....)` but it doesn't fix the seed in the copulas.
> 
> I have been running around in circles for several hours because I cannot get consistent optimization in repeated runs my new CopulaModel unit tests. :(

This is absolutely by design (including more recent choices in both NumPy and SciPy). One should never use the singleton random state when reproducibility is important. 

If you really, really want the singleton random state, you can get it in numpy.random._mtrand module.

**Comment by josef-pkt** [comment]
I want the global random state when we have many random calls, I want to set one seed and not have to carry around the random state in every function. 

Especially because a random state is not supported in all functions and methods.

For now we need to have that when `seed is None`, then we get the global random state back.
Otherwise, we will have big problems if we add `check_random_state` and it is not backwards consistent in the rvs.

transition to full random state support will take a lot of time and work.

**Comment by josef-pkt** [comment]
numpy and scipy have mostly individual functions.
We have much larger classes and need to handle more difficult cases.

**Comment by josef-pkt** [comment]
numpy default_rng with seed is None, uses a new random initialization each time. Is that interpretation correct?

**Comment by josef-pkt** [comment]
checking the notbook https://www.statsmodels.org/dev/examples/notebooks/generated/copula.html
AFAICS, the random generation is not reproducible.

Setting a global seed at the beginning will not help, because each call to `random` generates a new random state with new seed/initialization.

If you want the new pattern, then each call to `random` needs to use the same random state instance.

**Comment by bashtage** [comment]
The (ab)use of the singleton random state has been hashed through a lot since NumPy 1.17.  This should not be the default method that underlies new code.

**Comment by bashtage** [comment]
The notebook should set the seed, and ideally discuss reproducible draws.

**Comment by bashtage** [comment]
> numpy default_rng with seed is None, uses a new random initialization each time. Is that interpretation correct?

Yes.  Calling `default_rng` gives you a fresh `Generator` with the preferred bit generator.  It is essentially the same as using the singleton `RandomState`, only where you need to reset the state rather than calling `seed` if you want this to be reproducible.

```
import numpy as np
rng = np.random.default_rng()
state = rng.bit_generator.state
rng.random(2)
array([0.36090011, 0.47255839])  # random
```

```
rng.bit_generator.state = state
rng.random(2)
array([0.36090011, 0.47255839])  # matches above
```

**Comment by josef-pkt** [comment]
I guess our pytest fixture will also be broken, if it cannot set the individual random states

@pytest.fixture()
def reset_randomstate():

**Comment by josef-pkt** [comment]
Is scipy also using now the default_rng by default if seed is None?

That would cause a huge backwards compatibility break.
I didn't pay much attention to changes in random state handling.

**Comment by bashtage** [comment]
> I guess our pytest fixture will also be broken, if it cannot set the individual random states
> 
> @pytest.fixture()
> def reset_randomstate():

Nope. it still works.  Any use of methods attached to the singleton `RandomState` will still produce the same values.  This issue here is that the `random` method of copulas does the modern things and generates values that aren't reproducible unless explicitly seeded.

**Comment by bashtage** [comment]
> Is scipy also using now the default_rng by default if seed is None?
> 
> That would cause a huge backwards compatibility break.
> I didn't pay much attention to changes in random state handling.

I think scipy is not breaking backward compat.  I think they are also using good practices for new code, like the copula module.

**Comment by josef-pkt** [comment]
No both scipy and sklearn still have the first if as

```
if seed is None or seed is np.random:
        return np.random.mtrand._rand
```

we need that also in our version

> copulas does the modern things

that's what I meant. 
Existing uses are fine, but any unit test for code that use our current `check_random_state like copulas will not work with the pytest fixture

**Comment by josef-pkt** [comment]
@tupui https://github.com/scipy/scipy/blob/master/scipy/stats/_qmc.py#L81 cannot be made scipy default even after old numpy is  dropped.

This would break a large amount of user code that relies on seeding the numpy global random state.

**Comment by bashtage** [comment]
> Both scipy and sklearn still have the first `if` in `check_random_state` as
> 
> ```
> if seed is None or seed is np.random:
>         return np.random.mtrand._rand
> ```
> 
> we need that also in our version
> 
> > copulas does the modern things
> 
> that's what I meant.
> Existing uses are fine, but any unit test for code that use our current `check_random_state` like copulas will not work with the pytest fixture

They have it because their code predates the revamp of the random module. The sense from NumPy is that exposing the global singleton RandomState is a mistake but one that cannot be reverted because lots of code, e.g., tests, depend on it.  This is precisely why there is no singleton `Generator` -- it is a bad idea.

The statsmodels copula module is legacy-free and so should follow best practices, which means not relying on the singleton `RandomState` (which is in many ways worse than the random values produced by `Generator`).

All you need to do is to write your own fixture that return an initialized `RandomState` if that is what you want.

```
@pytest.fixture(scope="function")
def random_state():
    return np.random.RandomState(1234)

def test_something(random_state):
    copula.random(seed=random_state)
```

**Comment by tupui** [comment]
> @tupui https://github.com/scipy/scipy/blob/master/scipy/stats/_qmc.py#L81 cannot be made scipy default even after old numpy is dropped.
> 
> This would break a large amount of user code that relies on seeding the numpy global random state.

Kevin said it all.

I can only add that, most of the time, making the change to the new architecture would take less time than discussing it (I know this as I had such endless discussions on many projects). In most libraries, there are just a few places with seeding and random numbers. Looking at SciPy, almost everything relies on a RNG getting passed as an argument. If not, then we forgot some places. And if I had to do the change on SciPy, going through all the functions and adding a rng param would not take me more than a couple of hours.

As for the tests, I would argue that we should try as much as possible to check for statistical properties instead of exact assertions on values.

Now, I think that for some things we should allow ourselves to break code. Here it's for good reasons and the old way was shown countless times to be bad. Keeping backward compatibility for something bad is preventing the change and introducing more hacks and hidden bugs than doing any good. I am not saying we should follow what is done on the web side of Python where they break all the time everything, but we should be more ok to do that. With CI/CD, we now catch easily things like this and are easy fixes (especially if you had a deprecation cycle before). Not breaking things while evolving is not always possible and here we have to do it.

**Comment by josef-pkt** [comment]
maybe eventually it makes sense. However, for now we need to stick with global random state as default.

Using new numpy random state by default each time will cause too many errors during the transition.
Using QMC in nested, sequential sampling cases has too many unknown potentially bad consequences.

One global random state will produce a sequence of independent draws, no matter how complex the code is. 

e.g. bootstrap, or bootstrap of a random effects model that uses qmc integration in the loglike for the random effect.

How does independent sampling work if we get new QMC states each time? (*)

This is about the default behavior not about recommending the new approach to users.
I think the check_random_state without global state if None, is too risky as a default. I can imagine many ways how this can go wrong and there is no experience with that in related packages, especially none at all in more complex situations.

Starting new numpy random states takes mainly away a convenient global seed. I'm not sure that, if new random states are created in a loop, then the separate sequences will be independent/uncorrelated, compared to using common, global state.

(*) Owen has a chapter that includes something about bootstrap using QMC https://link.springer.com/chapter/10.1007/978-3-642-04107-5_1
I didn't try to understand how that works.

**Comment by tupui** [comment]
> One global random state will produce a sequence of independent draws, no matter how complex the code is.
> 
> e.g. bootstrap, or bootstrap of a random effects model that uses qmc integration in the loglike for the random effect.
> 
> How does independent sampling work if we get new QMC states each time? (*)

Why should this be different without a global seeding? If you do the following:

```python
import numpy as np
rng = np.random.default_rng()
sample1 = rng.random((100, 10))
sample2 = rng.random((100, 10))
```
Then you have 2 independent draw. And this is still reproducible. I don't understand your point.

**Comment by bashtage** [comment]
> maybe eventually it makes sense. However, for now we need to stick with global random state as default.

It already makes sense to use the modern way of accessing random number generators since NumPy >= 1.17. 

> Starting new numpy random states takes mainly away a convenient global seed. I'm not sure that, if new random states are created in a loop, then the separate sequences will be independent/uncorrelated, compared to using common, global state.

In this case convenience masks complexity that the user should see and be aware of.   This has been hasshed through in 100+ post threads in NumPy. There are problems with using the singleton random state instead of handling seeding directly, e.g., when using multiprocess.

**Comment by josef-pkt** [comment]
> In this case convenience masks complexity that the user should see and be aware of. This has been hasshed through in 100+ post threads in NumPy. There are problems with using the singleton random state instead of handling seeding directly, e.g., when using multiprocess.

The same applies to many areas, but we still have majority of users that don't care or don't know about many details.

My main problem with bootstrap is not the random number generation, my problem is that there are lots of underlying assumptions that I and users barely know about. 
Using the wrong bootstrap looks more serious to me than using a limited random number generator.

Similarly, we don't use robust standard errors by default. However, I tried to sneak in the cov_type messages in the `summary` to make users (that don't come from economics background) at least curious.

What might be a good trade-off between convenience and correctness/robustness for the numpy audience is often not the same as for our userbase.

FYI #306 from 2012. It never got high enough priority to do something about it. And we don't rely heavily on simulations.

**Comment by tupui** [comment]
> What might be a good trade-off between convenience and correctness/robustness for the numpy audience is often not the same as for our userbase.

I would argue that, the audience of statsmodels should be made more aware than NumPy's wide audience, of RNG issues no? It's more important to the users here dealing with statistics to have good RNG than something half broken no? There are statistical bugs in `RandomState`, it's not just a design/speed change.

**Comment by josef-pkt** [comment]
> There are statistical bugs in RandomState

I thought all major bugs have been fixed. I haven't seen bugs in any distribution rvs in a long time, except maybe at corner case parameter values.

**Comment by josef-pkt** [comment]
Also, in 10 years of simulations to check things, I never could identify a problem with the global random number generator.
(I only used RandomState when I wanted to have two streams to seed and sample two groups of statistics independently.)
(but I always stayed away from parallel processing)

**Comment by bashtage** [comment]
This has been fixed.
