### ISSUE TITLE
Which="prob" gives an error for ZeroInflatedPoissonRegression

### ISSUE THREAD

**Issue by thiesben** [statsmodels/statsmodels#7690]
#### Describe the bug

I fitted a ZeroInflatedPoissonRegression, and I wanted to predict the probabilities with the `which="prob"` argument, but it does not work. I found several examples online which are supposed to be working, but do not.

#### Code Sample, a copy-pastable example if possible

```python
import statsmodels.distributions.discrete as distr
import numpy as np
from statsmodels.discrete.count_model import (ZeroInflatedNegativeBinomialP, ZeroInflatedPoisson,
                                              ZeroInflatedGeneralizedPoisson)
import statsmodels.discrete._diagnostics_count as dia
expected_params = [1, 1, 0.5]
np.random.seed(987123)
nobs = 500
exog = np.ones((nobs, 2))
exog[:nobs//2, 1] = 0
# offset is used to create misspecification of the model
# for predicted probabilities conditional moment test
#offset = 0.5 * np.random.randn(nobs)
range_mix = 0.5
offset = -range_mix / 2 + range_mix * np.random.rand(nobs)
offset = 0
mu_true = np.exp(exog.dot(expected_params[:-1]) + offset)
prob_infl = 0.15
endog = distr.zinegbin.rvs(mu_true, expected_params[-1],
                           2, prob_infl, size=mu_true.shape)

model_zip = ZeroInflatedPoisson(endog, exog)
res_zip = model_zip.fit(method='bfgs', maxiter=5000, maxfun=5000)

probs_zip = res_zip.predict(which='prob')
probsm_zip = probs_zip.mean(0)
```
<details>

Taken from [here](https://gist.github.com/josef-pkt/c932904296270d75366a24ee92a4eb2f)

It gives me a ValueError:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_24467/1748239506.py in <module>
      2 res_zip = model_zip.fit(method='bfgs', maxiter=5000, maxfun=5000)
      3 print(type(model_zip))
----> 4 res_zip.predict(which="prob")
      5 #probs_zip = model_zip._predict_prob(params = res_zip.params, exog=exog, exog_infl=np.ones((len(exog),1)),
      6 #                                    exposure=getattr(res_zip, 'exposure', 0),

~/.conda/envs/ma2/lib/python3.8/site-packages/statsmodels/base/model.py in predict(self, exog, transform, *args, **kwargs)
   1097             exog = np.atleast_2d(exog)  # needed in count model shape[1]
   1098 
-> 1099         predict_results = self.model.predict(self.params, exog, *args,
   1100                                              **kwargs)
   1101 

~/.conda/envs/ma2/lib/python3.8/site-packages/statsmodels/discrete/count_model.py in predict(self, params, exog, exog_infl, exposure, offset, which)
    449             return prob_main
    450         elif which == 'prob':
--> 451             return self._predict_prob(params, exog, exog_infl, exposure, offset)
    452         else:
    453             raise ValueError('which = %s is not available' % which)

~/.conda/envs/ma2/lib/python3.8/site-packages/statsmodels/discrete/count_model.py in _predict_prob(self, params, exog, exog_infl, exposure, offset)
    533         mu = self.model_main.predict(params_main, exog,
    534             offset=offset)[:, None]
--> 535         result = self.distribution.pmf(counts, mu, w)
    536         return result[0] if transform else result
    537 

~/.conda/envs/ma2/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py in pmf(self, k, *args, **kwds)
   3148         if np.any(cond):
   3149             goodargs = argsreduce(cond, *((k,)+args))
-> 3150             place(output, cond, np.clip(self._pmf(*goodargs), 0, 1))
   3151         if output.ndim == 0:
   3152             return output[()]

~/.conda/envs/ma2/lib/python3.8/site-packages/statsmodels/distributions/discrete.py in _pmf(self, x, mu, w)
     38 
     39     def _pmf(self, x, mu, w):
---> 40         return np.exp(self._logpmf(x, mu, w))
     41 
     42     def _cdf(self, x, mu, w):

~/.conda/envs/ma2/lib/python3.8/site-packages/statsmodels/distributions/discrete.py in _logpmf(self, x, mu, w)
     32 
     33     def _logpmf(self, x, mu, w):
---> 34         return _lazywhere(x != 0, (x, mu, w),
     35                           (lambda x, mu, w: np.log(1. - w) + x * np.log(mu) -
     36                           gammaln(x + 1.) - mu),

~/.conda/envs/ma2/lib/python3.8/site-packages/statsmodels/compat/scipy.py in _lazywhere(cond, arrays, f, fillvalue, f2)
     95     tcode = np.mintypecode([a.dtype.char for a in arrays])
     96     out = _valarray(np.shape(arrays[0]), value=fillvalue, typecode=tcode)
---> 97     np.place(out, cond, f(*temp))
     98     if f2 is not None:
     99         temp = tuple(np.extract(~cond, arr) for arr in arrays)

<__array_function__ internals> in place(*args, **kwargs)

~/.conda/envs/ma2/lib/python3.8/site-packages/numpy/lib/function_base.py in place(arr, mask, vals)
   1796                         "not {name}".format(name=type(arr).__name__))
   1797 
-> 1798     return _insert(arr, mask, vals)
   1799 
   1800 

ValueError: place: mask and data must be the same size
```

I am using statsmodels 0.12.2.
</details>

#### Expected Output

I thought the prediction output where a table of probabilities for every observation and possible count.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.8.10.final.0
OS: Linux 4.4.162-94.72-default #1 SMP Mon Nov 12 18:57:45 UTC 2018 (9de753f) x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.12.2 (/home/nikoch/.conda/envs/ma2/lib/python3.8/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.21.2 (/home/nikoch/.conda/envs/ma2/lib/python3.8/site-packages/numpy)
scipy: 1.7.1 (/home/nikoch/.conda/envs/ma2/lib/python3.8/site-packages/scipy)
pandas: 1.3.2 (/home/nikoch/.conda/envs/ma2/lib/python3.8/site-packages/pandas)
    dateutil: 2.8.2 (/home/nikoch/.conda/envs/ma2/lib/python3.8/site-packages/dateutil)
patsy: 0.5.1 (/home/nikoch/.conda/envs/ma2/lib/python3.8/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.4.3 (/home/nikoch/.conda/envs/ma2/lib/python3.8/site-packages/matplotlib)
    backend: module://matplotlib_inline.backend_inline 
cvxopt: Not installed
joblib: 1.0.1 (/home/nikoch/.conda/envs/ma2/lib/python3.8/site-packages/joblib)

Developer Tools
================

IPython: 7.27.0 (/home/nikoch/.conda/envs/ma2/lib/python3.8/site-packages/IPython)
    jinja2: 3.0.1 (/home/nikoch/.conda/envs/ma2/lib/python3.8/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.10.0 (/home/nikoch/.conda/envs/ma2/lib/python3.8/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed
</details>

**Comment by josef-pkt** [comment]
that's #7371 fixed by #7385
a backwards incompatible change in scipy distributions broke this. There is no simple workaround.

maybe the following works (adding to imports on top of module), I have not tried it

```
from scipy._lib._util import _lazywhere
import statsmodels.distributions.discrete
statsmodels.distributions.discrete._lazywhere = _lazywhere
``` 

You need to upgrade statsmodels to the current develeopment version (or downgrade scipy).
The fix will be in the next statsmodels release 0.13 (likely within a month)

**Comment by thiesben** [comment]
Much appreciated, thank you! Sorry, I haven't found it before.

**Comment by josef-pkt** [comment]
closing, our code has been fixed.

Users might still run into this if they use newer scipy with older statsmodels

Aside: now we can use `get_distribution` for similar use cases.
