### ISSUE TITLE
Missing warnings import in OrderedModel

### ISSUE THREAD

**Issue by m-richards** [statsmodels/statsmodels#7692]
#### Describe the bug

There is a missing import of `warnings` for the categorical series check in OrderModel, so instead of warning, the code crashes.

This was done with a pip install of master today `python -m pip install git+https://github.com/statsmodels/statsmodels` (into a conda environment, but that's irrelevant)

#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd
import scipy.stats as stats
from statsmodels.miscmodels.ordinal_model import OrderedModel
url = "https://stats.idre.ucla.edu/stat/data/ologit.dta"
data_student = pd.read_stata(url)
data_student['apply'] = pd.Categorical(data_student['apply'], ordered=False)

mod_prob = OrderedModel(data_student['apply'],
                        data_student[['pared', 'public', 'gpa']],
                        distr='probit')

res_prob = mod_prob.fit(method='bfgs')
res_prob.summary()

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-30-0fc4bf67676c> in <module>
----> 1 mod_prob = OrderedModel(data_student['apply'],
      2                         data_student[['pared', 'public', 'gpa']],
      3                         distr='probit')
      4 
      5 res_prob = mod_prob.fit(method='bfgs')

~\.conda\...\lib\site-packages\statsmodels\miscmodels\ordinal_model.py in __init__(self, endog, exog, offset, distr, **kwds)
    125         self.offset = offset
    126 
--> 127         endog, labels, is_pandas = self._check_inputs(endog, exog)
    128 
    129         super(OrderedModel, self).__init__(endog, exog, **kwds)

~\.conda\envs\...\lib\site-packages\statsmodels\miscmodels\ordinal_model.py in _check_inputs(self, endog, exog)
    197             if isinstance(endog.dtypes, CategoricalDtype):
    198                 if not endog.dtype.ordered:
--> 199                     warnings.warn("the endog has ordered == False, "
    200                                   "risk of capturing a wrong order for the "
    201                                   "categories. ordered == True preferred.",

UnboundLocalError: local variable 'warnings' referenced before assignment

```

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

No UnboundLocalError

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.8.10.final.0

statsmodels
===========

Installed: 0.13.0.dev0+665.gb0ce269bc (C:\Users\user\.conda\envs\env_name\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.20.3 (C:\Users\user\.conda\envs\env_name\lib\site-packages\numpy)
scipy: 1.6.3 (C:\Users\user\.conda\envs\env_name\lib\site-packages\scipy)
pandas: 1.2.4 (C:\Users\user\.conda\envs\env_name\lib\site-packages\pandas)
    dateutil: 2.8.1 (C:\Users\user\.conda\envs\env_name\lib\site-packages\dateutil)
patsy: 0.5.1 (C:\Users\user\.conda\envs\env_name\lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.4.2 (C:\Users\user\.conda\envs\env_name\lib\site-packages\matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: Not installed
joblib: 1.0.1 (C:\Users\user\.conda\envs\env_name\lib\site-packages\joblib)

Developer Tools
================

IPython: 7.24.1 (C:\Users\user\.conda\envs\env_name\lib\site-packages\IPython)
    jinja2: 3.0.1 (C:\Users\user\.conda\envs\env_name\lib\site-packages\jinja2)
sphinx: Not installed
    pygments: 2.9.0 (C:\Users\user\.conda\envs\env_name\lib\site-packages\pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by josef-pkt** [comment]
Thanks for reporting the bug.

I will fix it within a few days. 

Do you have any other feedback on OrderedModel? I want to review it once more before the upcoming release.

**Comment by m-richards** [comment]
On reflection, I have two other comments, but I don't use statsmodels super often. So it may be that while confusing for me, regular users would not struggle as much. 

With this error;
https://github.com/statsmodels/statsmodels/blob/42cf4c6c2a5cb6ebd7cb4fc8d32d1a4b11dbff20/statsmodels/miscmodels/ordinal_model.py#L146-L148
, I think it would be beneficial to be more explicit to the user about how this might occur (and how to fix it). For example saying something like 
"OrderedModel does not allow constants in the data. The data either contains an explicit constant, or a combination of variables are linearly dependent."

Reading the documentation notebook (https://www.statsmodels.org/dev/examples/notebooks/generated/ordinal_regression.html#Using-formulas---no-constant-in-model) and docstring again I can see this is mentioned "Using formulas - no constant in model¶
The parameterization of OrderedModel requires that there is no constant in the model, neither explicit nor implicit. The constant is equivalent to shifting all thresholds and is therefore not separately identified." but I think this point is true when using the constructor directly, and using `from_formula`, so perhaps makes sense further up this page?

Otherwise, re-reading over the documentation there, it seems clear enough, although it was confusing earlier. I think I was trying to get away with reading as little as possible 😅 and it didn't pay off.

**Comment by josef-pkt** [comment]
Thanks for the comments.

The no constant in formula is more difficult because, the is no way to directly specify in a patsy formula that we don't want a constant. It's messier to implement and to explain.

The user has direct control over whether there is a constant when using arrays or dataframe. 
I can see that I make that more explicit. and maybe cross-link to the notebook from the docstring.
