### ISSUE TITLE
RLS: Preparing for 0.13

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#7717]
Please edit with any items that are essential before 0.13rc0.

- [x] Test wheel build: See https://github.com/MacPython/statsmodels-wheels/pull/82
- [ ] Update documentation

**Comment by bashtage** [comment]
@josef-pkt Do you have anything that needs to go in before 0.13.0rc0 is cut?

**Comment by bashtage** [comment]
As a note, it looks like there will not be Windows 32 wheels as the build does not pass Win32 (we stopped testing too).

**Comment by josef-pkt** [comment]
I need 2 more days. I started with another look at copula yesterday.
I need to work on release notes.

Most doc fixes I can still do after rc0.

**Comment by bashtage** [comment]
@josef-pkt You ok with rc0?

**Comment by josef-pkt** [comment]
yes, rc0 is fine.

Docs and release notes still have missing parts.
I will be working mainly on docs for now
