### ISSUE TITLE
RLS: Release Candidate 0, Version 0.13.0rc0 is out now

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#7729]
The release candidate has been cut.  Please test using

```
pip install statsmodels==0.13.0rc0
```

**Comment by bashtage** [comment]
@josef-pkt if you added any models to the api entry point, could you add these to the API page?

**Comment by josef-pkt** [comment]
you mean `api.rst`?

I will go through it. 
I just saw that beta regression is not in the statsmodels api nor formula.api

Is the api.rst page supposed to include `stats` function like hypothesis tests and confidence intervals?
Currently, there is nothing except `describe` in it.

nonparametric KDE are also not in api.rst

(nonparametric/api.py doesn't include asymmetric kernels
)

**Comment by bashtage** [comment]
It should include a thing in sm.api, sm.tsa.api or smf

**Comment by josef-pkt** [comment]
I want to stop with 0.13 so I can start with things for 0.14.

**Comment by bashtage** [comment]
@josef-pkt Any reason not to finalize and release 0.13?

**Comment by josef-pkt** [comment]
I'm avoiding merging my PRs that make a lot of changes to existing code in case we need a 0.13.1, and work on new modules instead.
