### ISSUE TITLE
statsmodels.tsa.arima_model.ARIMA.fit function documentation web page returns 404 error.

### ISSUE THREAD

**Issue by snoop2head** [statsmodels/statsmodels#7730]
#### Describe the bug

`statsmodels.tsa.arima_model.ARIMA.fit` function documentation web page returns 404 error.

#### Screenshot & URL

https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima_model.ARIMA.fit.html

<img width="1211" alt="Screen Shot 2021-09-18 at 4 58 21 PM" src="https://user-images.githubusercontent.com/28736695/133881353-7029e7bb-8b7e-4ab6-a1cb-dcb421e0c326.png">

<details>
I tried to look up arguments for `statsmodels.tsa.arima_model.ARIMA.fit()`, but it seems like stable version's documentation webpage is returning 404 error.

</details>

**Comment by snoop2head** [comment]
I see that `arima_model.Arima.fit` documentation yields 404 page, but `arima.model.Arima.fit` shows me the page properly.
- [`arima_model.Arima.fit`](https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima_model.ARIMA.fit.html) : 404 error
- [`arima.model.Arima.fit`](https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima.model.ARIMA.fit.html) : functions properly

Has arima_model been depriciated I guess?

**Comment by bashtage** [comment]
Yes. It is gone from 0.13. 0rc0 which came out yesterday
