### ISSUE TITLE
Docu: Dead link for sample data in docu

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [statsmodels/statsmodels#7731]
In the stable docu is link to sample data which is dead.
This is the link to the docu
https://www.statsmodels.org/stable/examples/notebooks/generated/ordinal_regression.html

This is the dead link
https://stats.idre.ucla.edu/stat/data/ologit.dta

**Comment by josef-pkt** [comment]
maybe this is temporary outage
The entire site `idre.ucla.edu` seems to be down at the moment

AFAICS
the csv file in used in the unit tests
"statsmodels\miscmodels\tests\results\ologit_ucla.csv"

code for reading and preparing data is in 
"statsmodels\miscmodels\tests\results\results_ordinal_model.py"

**Comment by josef-pkt** [comment]
the idre.ucla site is back online
the datafile links seems to be working again

closing for now
If interruptions like this happen more often, then we need to look for an alternative location for the data.
