### ISSUE TITLE
REF/BUG: disallow weights in OLS

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#7753]
currently OLS does not warn or raise on invalid kwargs #7741

OLS accepts weights in kwargs and sends it to super class which is WLS.
However, whiten in OLS does not use weights.
So, this produces unweighted results.

I guess this might be a common enough mistake that we should explicitly warn in 0.13 and raise in 0.14

**Comment by josef-pkt** [comment]
I will add the explicit warning in #7751

separate from the generic warning for kwargs

**Comment by bashtage** [comment]
Fixed in #7751
