### ISSUE TITLE
allow to plot OR or RR instead of logOR and logRR with `plot_forest`

### ISSUE THREAD

**Issue by sbwiecko** [statsmodels/statsmodels#7771]
With `statsmodels.stats.meta_analysis` `effectsize_2proportions`, we get the log odds ratio or log risk ratio when use the corresponding statistic option, and we can get the OR and RR, as well as their corresponding CI, by using `exp`
`np.exp(res_eyding.summary_frame())`
But we cannot plot the OR or RR with `plot_forest`.

**Comment by josef-pkt** [comment]
good idea

Just changing the plot would only be one line (or 3 total)

(I just saw that we don't specify a plot title. That seems to be currently up to the user.
AFAICS, the plot doesn't specify which effect size is used.)

**Comment by josef-pkt** [comment]
What would be a good name for an option in `plot_forest`?
`use_exp=False`
anti-log or reverse log would be descriptive names

Stats uses `eform` to convert log-or and similar
#2235 my "eform" function only uses generic names like `transform`

another missing:
the plot_forest doesn't have `alpha=0.05, use_t=None` to forward options to summary_frame method

**Comment by sbwiecko** [comment]
`use_exp=False` makes a lot of sense

for the plot title, xlabels etc, it's no big deal we can always use `plt.gca().set_title('blabla')`

**Comment by josef-pkt** [comment]
question while I'm checking the unit tests:
is `res.use_t`  True for the combine results with log-or and similar proportion effect sizes?

I get a warning in the unit test, that `use_t=True` needs nobs

**Comment by josef-pkt** [comment]
PR is #7772

**Comment by josef-pkt** [comment]
In the unit test case the "or" plot doesn't look so good, because there are one or two large outliers.
But it looks correct visually. 

![image](https://user-images.githubusercontent.com/440735/135644640-a34f626e-5be7-4182-8657-5fe13aa6e6cb.png)
