### ISSUE TITLE
MLE reference

### ISSUE THREAD

**Issue by zeina-abuaisheh** [statsmodels/statsmodels#7780]
I have a univariate state space model, and I am trying to understand your MLE code, that starts here:
https://github.com/statsmodels/statsmodels/blob/main/statsmodels/tsa/statespace/kalman_filter.py#L966

My objective is to reproduce the results of your MLE to have a better understanding of it. I am struggling to understand all of the loglike parts in your code, is there any reference that could help me understand it?

Thanks so much

**Comment by ChadFulton** [comment]
We support a lot of cases, so the log-likelihood function definition there is a little bit complex. But the basic reference for our state space implementation is: **Durbin, James, and Siem Jan Koopman. Time series analysis by state space methods. Oxford university press, 2012**. See especially Chapter 7 for the log-likelihood formulas.

Closing as answered, but feel free to follow up here if you have additional questions.

**Comment by zeina-abuaisheh** [comment]
thanks so much for your quick answer, so is the main equation 7.2 in page 171? 
Is F_t the covariance? and v_t is the mean innovation/residual?
Using equation 7.2, is this problem a minimization one (i.e. is it solved using  scipy.optimize.minimize)?

Thanks
