### ISSUE TITLE
Misreported intercept value from `smf.wls`

### ISSUE THREAD

**Issue by dmadisetti** [statsmodels/statsmodels#7782]
#### Describe the bug
`smf.wls` has a discrepancy between the reported coefficients and the predicted value. The predicted value look to be fine, but sometimes (just once so far) the reported values are magnitudes different. If this was in C I'd think maybe a mantis overflow? I thought I would post here instead of digging into the code
```
model.params:Intercept    1.462944e+06
D           -1.462944e+06
K            3.836826e-05
dtype: float64

model.HC0_se: Intercept    3.857593e+06
D            3.857593e+06
K            2.212943e-07
dtype: float64
```
![image](https://user-images.githubusercontent.com/2689338/136055107-6ffb238a-be19-43d3-9ae6-c569b677fd65.png)

Notice that intercept and D are opposite signs. Which is weird?

If I take D = 1.462944e-06, then things look reasonable

![image](https://user-images.githubusercontent.com/2689338/136054316-8a7c5427-5c70-459c-9c87-a302e94396cf.png)

It's obviously data dependent. I was able to run this analysis for ~50 regressions before hitting this.

#### Code Sample, a copy-pastable example if possible

```python
  
  import numpy as np
  import matplotlib.pyplot as plt
  import statsmodels.formula.api as smf
  
  theta = np.linspace(0, np.pi, 1000)
  intensity = 1 / (theta+0.1)
  # Make fake data
  scatter = 0.01
  X = 0.05 * np.sin(theta + scatter)/np.cos(theta - scatter)
  T = X * np.cos(theta)
  K = np.sin(theta)
  plt.scatter(K**2, T**2, c=intensity)

  data = {"T":T**2, "K":K**2, "D":np.ones_like(K)}
  model = smf.wls(data=data,
                  weights=intensity,
                  formula="T ~ D + K",).fit()

  space = np.linspace(0, np.max(K), 1000)
  pred = model.get_prediction({"K":space**2, "D":np.ones_like(space)})
  mean = pred.predicted_mean
  print(f"model.params:{model.params}\n\nmodel.HC0_se: {model.HC0_se}")
  plt.plot(space**2, mean, label="model predict")
```
<details>
There are a ton of issues, and I did take a look, bt I couldn't find this problem. Compiled from main (head = https://github.com/statsmodels/statsmodels/commit/f67fc16d581767c030b6f191cf650c3a69d9ed5d) provides the same problem. But since this is a one off analysis, I'm not going to dig super deep. I can provide data if you need. For this regression should be like <5mb

This is running on vanilla google colab
```
INSTALLED VERSIONS
------------------
Python: 3.7.12.final.0
OS: Linux 5.4.104+ #1 SMP Sat Jun 5 09:50:34 PDT 2021 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

Statsmodels
===========

Installed: 0.10.2 (/usr/local/lib/python3.7/dist-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.24 (/usr/local/lib/python3.7/dist-packages/Cython)
numpy: 1.19.5 (/usr/local/lib/python3.7/dist-packages/numpy)
scipy: 1.4.1 (/usr/local/lib/python3.7/dist-packages/scipy)
pandas: 1.1.5 (/usr/local/lib/python3.7/dist-packages/pandas)
    dateutil: 2.8.2 (/usr/local/lib/python3.7/dist-packages/dateutil)
patsy: 0.5.1 (/usr/local/lib/python3.7/dist-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.2.2 (/usr/local/lib/python3.7/dist-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: 1.2.7 (/usr/local/lib/python3.7/dist-packages/cvxopt)
joblib: 1.0.1 (/usr/local/lib/python3.7/dist-packages/joblib)

Developer Tools
================

IPython: 5.5.0 (/usr/local/lib/python3.7/dist-packages/IPython)
    jinja2: 2.11.3 (/usr/local/lib/python3.7/dist-packages/jinja2)
sphinx: 1.8.5 (/usr/local/lib/python3.7/dist-packages/sphinx)
    pygments: 2.6.1 (/usr/local/lib/python3.7/dist-packages/pygments)
pytest: 3.6.4 (/usr/local/lib/python3.7/dist-packages)
virtualenv: Not installed
```
</details>

**Comment by bashtage** [comment]
Your model is nonsense because you are including both a constant and `D`, which is constant.

```python
import numpy as np
np.linalg.matrix_rank(model.model.data.exog)
```

prints

```
2
```


Use 

```python
model = smf.wls(data=data,
                  weights=intensity,
                  formula="T ~ D + K - 1",).fit()
```

to explicitly exclude the constant. 

so your coefficients are not point identified.

**Comment by dmadisetti** [comment]
Great. Thanks for the prompt response.
