### ISSUE TITLE
Can statsmodels calculate 'Bayes Factor'? If not, could it be implemented? 

### ISSUE THREAD

**Issue by alikaz3mi** [statsmodels/statsmodels#7800]
#### Describe alternatives you have considered
A clear and concise description of any alternative solutions or features you have considered.

#### Additional context
Add any other context about the feature request here.

**Comment by josef-pkt** [comment]
closing, 
no specific case or model and unlikely it will become available in statsmodels (except for maybe Bayesian models in tsa)
