### ISSUE TITLE
How are cconfidence intervals estimated in statsmodels ARIMA(p,d,q)?

### ISSUE THREAD

**Issue by gupta353** [statsmodels/statsmodels#7810]
I am using statsmodel package for fitting `ARIMA(p,d,q)` model to a time series. My question is how exactly does this package estimate confidence intervals of the parameters of this model? The documentation says that

"The confidence interval is based on the standard normal distribution if self.use_t is False. If self.use_t is True, then uses a Student’s t with self.df_resid_inference (or self.df_resid if df_resid_inference is not defined) degrees of freedom."

Then the question is how is the variance of different parameters estimated to apply the standard Normal or t-distribution method?

**What I have done:** I used the Hessian matrix method to compute the covariance matrix. But the confidence interval obtained using my approach are much wider than those produced by `statsmodels`. Which means that `statsmodels` is not using the Hessian matrix approach. Also, I noticed that as I increase the length of my time-series, the confidence intervals obtained by these approaches become similar.

**Comment by JPSchettino** [comment]
Well, in the case of a non-seasonal Arima model the package specifies to integrate the possible regressors and trend components as a regression with ARIMA errors. which means that:
Yt = B0 + B2X1 + ... + BNXT + Nt
Where NT represents the arima(P,D,Q) error in question (sum of deviations of arima model parameters(p,d,q)) . Calculating the range in multiple steps is a complicated matter, which requires more than a simple comment ( a good book to delve into at the end ). However, the interval for the first step is simply calculated.
it is just a matter of assuming that the residuals (NT) follow a normal or t distribution and calculating the range of interest.
Now, there are several ways to calculate the model's parameters and their deviations. I recommend checking the package specs to see them all. the default is to optimize by the method "innovations_mle", the difference may be coming from there.


Brockwell, Peter J., and Richard A. Davis. 2016.
       Introduction to Time Series and Forecasting. Springer.

**Comment by bashtage** [comment]
The default method uses the Outer Product of the Gradient, and so `res.cov_params()` is the same as `res.cov_params_opg`. You can see the others which are all named `cov_params_`*NAME*
