### ISSUE TITLE
The Wald test statistic is returned as a 1 x 1 matrix, not a scalar.

### ISSUE THREAD

**Issue by ssakatausa** [statsmodels/statsmodels#7865]
#### Describe the bug
The Wald test method returns a 1 x 1 array as the Wald test statistic. Because the statistic is always a scalar, I think that the statistic should be given as a scalar. In fact, when I tried to print out the statistic using the following command:

`print(f'Wald statistic = {waldRes.statistic:.2f}')`

where waldRes is what the wald_test method returned, I got an error message:

    TypeError: unsupported format string passed to numpy.ndarray.__format__

which puzzled me a minute or so.

I think that the attached patch to model.py fixes the problem. 

#### Code Sample, a copy-pastable example if possible
import numpy as np
import pandas as pd
import statsmodels.tools as smtools
import statsmodels.regression as smreg

df = pd.DataFrame(data=np.random.rand(100, 6),
                  columns=['Y', 'X1', 'X2', 'X3', 'X4', 'X5'])
Y = df['Y']
X = smtools.add_constant(df.iloc[:, 1:], prepend=False)
model = smreg.linear_model.OLS(Y, X)
res = model.fit(cov_type='HC0')
R = np.identity(6)[:3, :]
r = np.ones((3, 1))
waldRes = res.wald_test((R, r))
# The next line shows the Wald statistic in the double brackets.
print(waldRes)
# Also, see:
print(f'Wald statistic = {waldRes.statistic}')

#### Expected Output

The statistic attribute should be a float scalar, not a 1x1 array.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``
INSTALLED VERSIONS
------------------
Python: 3.9.2.final.0
OS: Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64
byteorder: little
LC_ALL: None
LANG: en_US.utf8

statsmodels
===========

Installed: 0.13.0 (/home/ssakata/.local/lib/python3.9/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.21 (/usr/lib/python3/dist-packages/Cython)
numpy: 1.19.5 (/usr/lib/python3/dist-packages/numpy)
scipy: 1.6.0 (/usr/lib/python3/dist-packages/scipy)
pandas: 1.3.4 (/home/ssakata/.local/lib/python3.9/site-packages/pandas)
    dateutil: 2.8.1 (/usr/lib/python3/dist-packages/dateutil)
patsy: 0.5.2 (/home/ssakata/.local/lib/python3.9/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.3.4 (/usr/lib/python3/dist-packages/matplotlib)
    backend: TkAgg 
cvxopt: 1.2.5 (/usr/lib/python3/dist-packages/cvxopt)
joblib: 0.17.0 (/usr/lib/python3/dist-packages/joblib)

Developer Tools
================

IPython: 7.20.0 (/usr/lib/python3/dist-packages/IPython)
    jinja2: 2.11.3 (/usr/lib/python3/dist-packages/jinja2)
sphinx: Not installed
    pygments: 2.7.1 (/usr/lib/python3/dist-packages/pygments)
pytest: 6.0.2 (/usr/lib/python3/dist-packages/pytest)
virtualenv: 20.4.0+ds (/usr/lib/python3/dist-packages/virtualenv)

[model-py-diff.txt](https://github.com/statsmodels/statsmodels/files/7493453/model-py-diff.txt)

**Comment by bashtage** [comment]
I agree that this should be fixed.  It will need a deprecation cycle and a method to make it scalar.
