### ISSUE TITLE
QUESTION: Why is test infeasible when residual variance is numerically 0

### ISSUE THREAD

**Issue by teoML** [statsmodels/statsmodels#7871]
Hello everyone,
I think that there is a possible error in the implementation of the function def grangercausalitytests(x, maxlag, addconst=True, verbose=True) (https://github.com/statsmodels/statsmodels/blob/main/statsmodels/tsa/stattools.py)

Lines (1381-1591)
   
'   

        if res2djoint.model.k_constant:   
  
            tss = res2djoint.centered_tss
        else:
            tss =res2djoint.centered_tss
        if (
                tss == 0
                or res2djoint.ssr == 0
                or np.isnan(res2djoint.rsquared)
                or (res2djoint.ssr / tss) < np.finfo(float).eps
                or res2djoint.params.shape[0] != dtajoint.shape[1]
        ):
            raise InfeasibleTestError(
                "The Granger causality test statistic cannot be compute "
                "because the VAR has a perfect fit of the data."
            )
`

I don't understand why we need the check "or (res2djoint.ssr / tss) < np.finfo(float).eps"
and I also don't think that  in the first if-else block we should have the same assignment `tss =res2djoint.centered_tss`
For input of the function:
`x = array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])`
I get the `InfeasibleTestError` which in my opinion should not be the case (tested the same input with the R-lib MVBAR and the f-test was performed successfully. After debugging the function with this input I found out that `or (res2djoint.ssr / tss) <np.finfo(float).eps` is True and that causes the exception. However, I don't see the point of checking this. Could someone explain to me if there is a bug in this function or I am missing something regarding the F-tests?
Thanks!
Maybe @bashtage or @josef-pkt  could help :)

**Comment by bashtage** [comment]
This checks if the model fits perfectly.  If the model first perfectly, then it isn't possible to be compute the GC test statistic. When you have a perfect fit, then the F-test has a divide by 0 error, and so it dhoulwnshouldn't be possible.  What does R report here?

**Comment by bashtage** [comment]
If you look here:

https://github.com/statsmodels/statsmodels/blob/718b4c5d8524d227bc170d162be80a74d07665cf/statsmodels/tsa/stattools.py#L1528-L1534

You'll see the ssr appears in the denominator.

**Comment by teoML** [comment]
@bashtage , thanks for your answer. However, I still don't understand what is the interpretation of `(res2djoint.ssr / tss) <np.finfo(float).eps`.  With the input I tried out and provided above, the test fails since ` (res2djoint.ssr / tss) < np.finfo(float).eps` is `True`. When I comment this line out, I get a result without any exceptions. With the same input the R code just outputs the result of the test, so it seems to work. This is the part of the R-code which does the statistical test:
```
restricted <- lm(Y[, 1] ~ X2)    
unrestricted <- lm(Y[, 1] ~ X1)
ssqR <- sum(restricted$resid^2)
ssqU <- sum(unrestricted$resid^2)
test <- ((ssqR - ssqU)/p)/(ssqU/(nrow(Y) - 2 * p - 1))
```
Here is the documentation of the R function https://www.rdocumentation.org/packages/MSBVAR/versions/0.9-2/topics/granger.test

**Comment by bashtage** [comment]
If SSR/TSS < eps then SSR is numerically 0, and so the model has produced a perfect fit (up to numerical precision).  Do you get an absurdly large test statistic in `test`? `ssrU` should be very small even if not 0.

**Comment by teoML** [comment]
In the python code I get: `(res2djoint.ssr / tss) = 6.710224330591428e-32` . In the R code I get a similar value, so you are right - the number is really large. The p-val is 0.00. However, my question is then: don't these large values of F-statistic indicate high significance? I think that  the check `(res2djoint.ssr` / tss) < np.finfo(float).eps ` should  be included as a warning, not an exception, since the test can still be calculated.

**Comment by bashtage** [comment]
In order for the test to have an F distribution when the null is true, the unrestricted model must have a non-zero variance.  If the unrestricted model has a 0 variance, then the test statistic doesn't have an F distribution under the null since it would be 0 / 0 in the limit.  In a nutshell, R is wrong here, or at least lazy in the sense of requiring more expertise of users.

**Comment by bashtage** [comment]
Closing since no action, but feel free to continue the conversation.
