### ISSUE TITLE
Confidence interval for a linear combination of parameters

### ISSUE THREAD

**Issue by ssakatausa** [statsmodels/statsmodels#7882]
#### Is your feature request related to a problem? Please describe
Currently, we can calculate the 95%-(two-sided) confidence interval for a linear combination of the parameters of various models by using the t_test method. If I wish to form a confidence interval with a different coverage probabililty (say, 90%), however, the t_test method does not help me.

#### Describe the solution you'd like
I would love to see either (1) the t_test method allow users to specify the coverage probability (or alpha = 1 - it) or (2) the conf_int method support the confidence interval for linear combinations. I think that (2) is more user-friendly, because no new comers would think that t_test is the method to get a confidence interval.

#### Describe alternatives you have considered
Please see above.

#### Additional context
None.

**Comment by josef-pkt** [comment]
The contrast results instance should have conf_int method and summary_frame that takes alpha to override the default.

**Comment by bashtage** [comment]
Closing as answered.

**Comment by ssakatausa** [comment]
bashtage, I think that you miunderstood the conversation. What I posted was a feature request, not a question. josef-pkt confirmed necessity of the requested feature. Please reopen this ticket and correct labels.

**Comment by josef-pkt** [comment]
No, my answer was that this should already be available. `dir(results.t_test(x1=2))`

I don't have an example right now,, but t_test and similer return an instance of a class with methods to use different alpha.

The design is to compute the test statistic and distribution only once, but we can evalueate confint with different options.

**Comment by ssakatausa** [comment]
josef.pkt, It sounds that I should have read "should have" as "have". But your claim is not consistent with my experience. Nonetheless, my experience is different from your claim. When I run:

  result.t_test(R, alpha=0.1)

where "result" is the returned value from the OLS regression, I just got an error message:

  SyntaxError: expression cannot contain assignment, perhaps you meant "=="?

**Comment by josef-pkt** [comment]
```
tt = result.t_test(R)
tt.conf_int(alpha=0.1)
tt.summary_frame(alpha=0.1)
```

"should" means it is supposed to be that way AFAIR, but I haven't used that in a while and didn't verify on an example.

**Comment by bashtage** [comment]
```python
import statsmodels.api as sm
from numpy.random import default_rng
g = default_rng(1234567890)
y=g.standard_normal(100)
x=g.standard_normal((100,3))
res = sm.OLS(y,sm.add_constant(x)).fit()
cr = res.t_test([1,1,1,1])
cr.conf_int(alpha=0.2)
```

```
 array([[-0.12289023,  0.37729558]])
```

**Comment by ssakatausa** [comment]
Thanks for your clarification. I checked help(res.t_test) many times but it just did not occur to me that the returned value could offer conf_int. Thanks again.
