### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [statsmodels/statsmodels#7886]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/statsmodels/lokal -name '*.py')
```

**Comment by bashtage** [comment]
These are not always free since augmented assignment of numpy arrays is inplace while `x = x + 1` creates a new copy.  Sometimes (often I suspect) the copy might be intentional.

**Comment by elfring** [comment]
:thinking:
* Would you like to follow the explanation any more by [the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13)?
* How do you think about to support another bit of collateral evolution accordingly?

**Comment by josef-pkt** [comment]
I think in most cases our current usage is intentional.

There are also casting problems where inplace assignment fails

a = x + y + z numpy broadcasts and assigns appropriate dtype

while the following will fail if adding z requires upcasting or broadcasting.
a = x + y
a += z

We still do this, but we have to make sure that dtypes and shape match.

**Comment by josef-pkt** [comment]
another problem is that unintentional inplace changes are difficult to find and require a lot of unit tests

```
def func(x, scale=None):
    if scale is not None:
        x = x * scale
    return x
```
versus

```
def func(x, scale=None):
    if scale is not None:
        x  *= scale
    return x
```

We almost never want the second.

**Comment by josef-pkt** [comment]
looks like elfrig is a bot according to pylint issue

**Comment by josef-pkt** [comment]
I blocked the user from the statsmodels organization account

**Comment by bashtage** [comment]
That was my guess.
