### ISSUE TITLE
docstrings of cached results

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#792]
Looking to clean up the documentation a little bit. In some cases, I've started moving the documentation out of, say, the results class docstring and into the cached results docstring. The problem is that the docstrings of these properties are not available at the interpreter. You only get the docstring of the object that they're contained in. This is fine for sphinx docs, but it's not quite as useful at the interpreter. That said, no one actually imports the results classes to read the documentation anyway. What to do?

I've thought about
- trying to use some dark arts to replace the object docstring (e.g., np.ndarray) with the property's. Seems doable, but I'm not positive
- Providing some kind of `help` function that will print some docs

```
sm.help(results_instance, 'aic')
```

or 

```
sm.help(results_instance)
```

or 

```
results_instance.help("aic")
```

Thoughts? Any other ideas?

**Comment by bashtage** [comment]
This is fixed in master.
