### ISSUE TITLE
Confidence Interval Upper Bound and Lower Bound Values not Changing with change in alpha

### ISSUE THREAD

**Issue by ayushpatidar** [statsmodels/statsmodels#7931]
#### Describe the bug

I am using SARIMAX for a timeseries forecasting problem. I am trying to get the upper bound and lower bound using forecast.conf_int() function of model.  

But  when i change the value of alpha the upper & lower bound remains same.

# Code

self.model = sm.tsa.SARIMAX(val, order=(1,1,1), seasonal_order=(0, 1, 1, 24),enforce_stationarity=False,enforce_invertibility=False)
self.model = self.model.fit()

forecast = self.model.get_forecast()
results = forecast.predicted_mean[0]
ci = forecast.conf_int(0.05)
upper_bound = ci[0,1]
lower_bound = ci[0,0]

output1 : 

lower_bound = 3014
upper_bound = 18711
predicted = 10862

when changing the value
ci = forecast.conf_int(0.5)

output2 : 

lower_bound = 3014
upper_bound = 18711
predicted = 10862

#### Expected Output
I expect the the lower and upper bound to change with change in value of alpha.

Is this is bug or  Is my understanding of confidence interval and alpha is wrong?

**Comment by ChadFulton** [comment]
> Is this is bug or Is my understanding of confidence interval and alpha is wrong?

This is just a syntax problem where you are inadvertently setting the wrong argument.  You should use:

```python
ci = forecast.conf_int(alpha=0.5)
```

**Comment by ayushpatidar** [comment]
@ChadFulton 

Thanks for the help!!

But i have one doubt
According to the Documentation
https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAXResults.conf_int.html

There are only two arguments 
alpha and cols 

And  as alpha is mentioned first in the function definition then it should be set without explicitly defining it while calling the function.

**Comment by ChadFulton** [comment]
> https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.sarimax.SARIMAXResults.conf_int.html

The linked method here is the one used to compute confidence intervals for the estimated parameters, not for the forecasts.  Unfortunately, it does not look like there is currently a page in the documentation for the method `forecasts.conf_int`.
