### ISSUE TITLE
Using array of bitarrays

### ISSUE THREAD

**Issue by tweber68** [statsmodels/statsmodels#7935]
### Proposed new feature or change:

I have a machine learning script in Logistic Regression with datasets with over 20000 columns. In effect, these columns only save 1s and 0s. It's a so called OneHotArray. As numpy's smallest dtype is uint8, the numpy array needs **8 times more memory than necessary**. And it becomes even worse. The machine learning algorithm (Logit) constructs a view with dtypes of float64. As a consequence, the numpy array needs **64 times more memory than necessary**.

So it would be nice, if there would be an alternative for example using an array of bitarrays (https://pypi.org/project/bitarray/). This could save 98% of memory in my case.

**Comment by bashtage** [comment]
This would need a fully custom implementation that is beyond the aims of statsmodels.  If you just want to fit your linear regression you can use 

https://towardsdatascience.com/strategies-to-train-out-of-memory-data-with-scikit-learn-7b2ed15b9a80

**Comment by josef-pkt** [comment]
We will eventually get our models to use sparse arrays for this.

**Comment by bashtage** [comment]
Using that idea, another good approach would be sparse + LSMR for linear regression, both of which are in SciPy.

**Comment by tweber68** [comment]
Thanks for your replies! I think I have some ideas, now. :-)
