### ISSUE TITLE
Execution time measurement

### ISSUE THREAD

**Issue by EmperorTransisthor** [statsmodels/statsmodels#7936]
How can I measure time of dataset smoothing? When I call ``fit()`` function I receive combined times of finding optimal values to fit data series I'm passing, etc. but how can I measure exponential smoothing time execution only? Is there a member function I can call or will below code be enough to measure simple exponential smoothing algorithm execution time?

```python
alpha = 0.2
%timeit simpleExponentialSmoothing(params, timeSeries, initState).block_until_ready()
%timeit SimpleExpSmoothing(timeSeries).fit(smoothing_level = alpha, optimized=False)
```

Console output:
```
47.3 ms ± 2.46 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.6 ms ± 136 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by EmperorTransisthor** [comment]
By the way, I think that `summary()` can be enhanced by adding execution times.

**Comment by bashtage** [comment]
If you want to measure fit time you should create the model first and then just time `fit` for the previously created model.

**Comment by bashtage** [comment]
Oh, and to see just the smoothing time, call fit the all parameters given, as you did above.

**Comment by EmperorTransisthor** [comment]
That is what I needed to know, thanks! :D
