### ISSUE TITLE
Documentation and Implementation Differ for Condition Number in OLSResults

### ISSUE THREAD

**Issue by JiaqiLiu** [statsmodels/statsmodels#7938]
Hi, 

Not sure if taking the square root is the convention, the doc and code is not consistent here.

https://github.com/statsmodels/statsmodels/blob/e741f3b22302199121090822353f20d794a02148/statsmodels/regression/linear_model.py#L1914

https://github.com/statsmodels/statsmodels/blob/e741f3b22302199121090822353f20d794a02148/statsmodels/regression/linear_model.py#L1917

If it's for computational stability, updating the documentation might be helpful.

Thank you!

**Comment by josef-pkt** [comment]
Looks inconsistent

There might be a mixup between singular values and eigenvalues.
Maybe there were some incomplete changes during refactoring.

For now, I don't know a reason why we define it this way. (as ratio of singular values, AFAICS)
