### ISSUE TITLE
Unpacking statsmodels wheel using the wheel package doesn't work

### ISSUE THREAD

**Issue by hoodmane** [statsmodels/statsmodels#7956]
#### Describe the bug
I am trying to move Pyodide over to using wheels to distribute packages https://github.com/pyodide/pyodide/pull/2027. After building the wheel, we need to do some postprocessing so we use `python -m wheel unpack wheel-name.whl`, then rearrange the wheel as appropriate, then pack the wheel again. The PyPa `wheel` package does not correctly handle commas in file names, so it breaks on statsmodels because of the following files:
```
statsmodels/datasets/tests/raw.github.com,vincentarelbundock,Rdatasets,master,csv,car,Duncan.csv.zip
statsmodels/datasets/tests/raw.github.com,vincentarelbundock,Rdatasets,master,datasets.csv.zip
statsmodels/datasets/tests/raw.github.com,vincentarelbundock,Rdatasets,master,doc,car,rst,Duncan.rst.zip
```
I made a pull request over at https://github.com/pypa/wheel/pull/427 to fix it.

#### Code Sample, a copy-pastable example if possible
```sh
python3.9 setup.py bdist_wheel
python3.9 -m wheel unpack dist/statsmodels-0.9.0-cp39-cp39-linux_x86_64.whl
```
#### Expected Output
It should succeed.

#### What happens instead
It prints:
```sh
Unpacking to: ./statsmodels-0.9.0...No hash found for file 'statsmodels/datasets/tests/raw.github.com,vincentarelbundock,Rdatasets,master,csv,car,Duncan.csv.zip'
```
and quits.

**Comment by bashtage** [comment]
Is there anything that needs a fix?  You appear to be using 0.9.0 which is no longer supported.

**Comment by bashtage** [comment]
The corresponding wheel on PyPI for statsmodels 0.13.1 unpacks as expected. These files are (correctly) not in the wheel.

**Comment by hoodmane** [comment]
No action needed here, the problem is with the wheels package.

> 0.9.0 which is no longer supported.

I see, and indeed it looks like the problematic file names are gone on master so that's good. Probably we are on the ancient version of statsmodels because we are using a very old scipy because of Fortran function pointer casting woes.

**Comment by hoodmane** [comment]
Thanks!
