### ISSUE TITLE
Adding Constant as Unity: sm.add_constant(data)

### ISSUE THREAD

**Issue by HARSHBARDHANK94** [statsmodels/statsmodels#7959]
In statsmodel OLS, WLS and GLS fitting examples consider adding a constant column to the predictor in datasets by using ```sm.add_constant(data.exog)```, that adds a 1s column to the predictor data column. 
As per my understanding the adding of constant term requires to fit in general Y=mX+c, where c is that constant. 
If, yes, then I want to add my first observation point as intercept point as **c** (constant) rather than 1s.
Just put here for knowing the idea of adding constant term 1s or first data point.
Thanks

**Comment by bashtage** [comment]
That is what `add_constant` does.  If you don't `add_constant` then the model you fit is y= m x. When you run `OLS(y, sm.add_constant(x))` you fit the model y = c + m x.

**Comment by HARSHBARDHANK94** [comment]
Ok that sound good and perfect !!
Actually I was going through one Trend estimation literature:
 (Babu, S.S., Manoj, M.R., Moorthy, K.K., Gogoi, M.M., Nair, V.S., Kompalli, S.K., Satheesh, S.K., Niranjan, K., Ramagopal, K., Bhuyan, P.K. and Singh, D., 2013. Trends in aerosol optical depth over Indian region: Potential causes and impact indicators. Journal of Geophysical Research: Atmospheres, 118(20), pp.11-794.):

Where they have considered initial year observed value as constant or offset term: 
![constant](https://user-images.githubusercontent.com/85699193/146528998-4526bc51-9bbe-44f8-842f-f7a8d0250c43.png)

That makes me to put the discussion here.

**Comment by HARSHBARDHANK94** [comment]
> That is what `add_constant` does. If you don't `add_constant` then the model you fit is y= m x. When you run `OLS(y, sm.add_constant(x))` you fit the model y = c + m x.

That means add_constant, usually add 1s and then calculate **constant c** for the fit, right

**Comment by bashtage** [comment]
> That means add_constant, usually add 1s and then calculate **constant c** for the fit, right

Yes, the estimate on the constant vector of 1s is the estimated value of c.

**Comment by cutie474** [comment]
what can i do if sm.add_constant(x)) does not seem to be effective ...however it runs without giving any syntax error

**Comment by josef-pkt** [comment]
If there is already a constant column (var(column) is approx 0), then a constant will not be added by default.
There is a keyword to force it for this case.

**Comment by josef-pkt** [comment]
@cutie474 
BTW: nice github name :)

**Comment by cutie474** [comment]
> If there is already a constant column (var(column) is approx 0), then a constant will not be added by default. There is a keyword to force it for this case.

Thanks for your response. Whats the keyword?

**Comment by josef-pkt** [comment]
`has_constant="add"`
need to look it up, I didn't remember it 
https://www.statsmodels.org/dev/generated/statsmodels.tools.tools.add_constant.html
