### ISSUE TITLE
Hessian inversion try/except should catch exception

### ISSUE THREAD

**Issue by jseabold** [statsmodels/statsmodels#797]
This will fail for any reason including a bug in the hessian code. Should only catch LinalgError or whatever it needs to.

https://github.com/statsmodels/statsmodels/blob/master/statsmodels/base/model.py#L336

**Comment by josef-pkt** [comment]
check if still relevant and which code it is, line L336 is obsolete link

**Comment by jbrockmendel** [comment]
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/base/model.py#L441

**Comment by josef-pkt** [comment]
@jbrockmendel thanks

it is still a plain catch all

**Comment by jseabold** [comment]
This code is gone now.
