### ISSUE TITLE
Question: How to apply AutoReg results to new data / help with AutoReg `initialize`

### ISSUE THREAD

**Issue by Malachov** [statsmodels/statsmodels#7981]
Hello, first thanks for great job.

I have a question. It's not feature request nor bug.

What i want to do with autoreg
 - I want to be able to just update model instead of new fit (lets call it partial fit or incremental learning)
 - I want to be able to make predictions on data that has no relation to fitted data (don't know index)
 - I want to be able to has similar iterface to use score evaluation and cross-validation as in sklearn
 
Why i think it could help others

In models based from MLEModel (ARIMA, SARIMAX) I'm able to use `apply` function so I am able to fit the model and then use it for unrelated data. I'm also able to update model with new data with `append`, therefore I'm able to use everything i need

Example:

```
from statsmodels.tsa.api import ARIMA

data = np.array(range(200))

order = (4, 2, 1)

model = ARIMA(data, order=order)
fitted_model = model.fit()


prediction = fitted_model.forecast(7)

new_data = np.array(range(600, 800))
fitted_model = fitted_model.apply(new_data)
new_prediction = fitted_model.forecast(7)

print(prediction)
print(new_prediction)
```

Is there any way how to achieve something similar in autoreg model?

My guess is to use `initialize` - create model with already fitted params and then somehow add the data.

Is it possible to add simple example to [initialize docs](https://www.statsmodels.org/dev/generated/statsmodels.tsa.ar_model.AutoRegResults.initialize.html#statsmodels.tsa.ar_model.AutoRegResults.initialize)? In apply, there is lovely example, in initialization, there are only described parameters.

Similar docs could be applied in other models like `statsmodels.tsa.holtwinters.HoltWintersResults` etc. also

And mainly - Is it possible somehow to achieve something similar as apply in autoreg module?

I guess somehow data can be added to initialized model...

Thanks...  Dan Malachov

**Comment by fkiraly** [comment]
+1, I'm coming here with the same question from `sktime`, from this issue: https://github.com/alan-turing-institute/sktime/issues/1788
(what do we put in `update` of the forecaster if `update_params=False`)

I think it might not be possible, looking at the docs, but I'm not sure.
Having the functionality in `statemodels` seems like the "right" place, but we couldn't find it there.

**Comment by laniakea** [comment]
Has there been any progress for this?
