### ISSUE TITLE
conda-forge says statsmodels not available?

### ISSUE THREAD

**Issue by rbelew** [statsmodels/statsmodels#7983]
#### Describe the bug

i'm building a conda environment on M1 osx-arm64 and have most of my tools.  but attempting to install statsmodels fails.  
#### Code Sample, a copy-pastable example if possible
Following https://anaconda.org/conda-forge/statsmodels i have tried:

- conda install statsmodel
- conda install -c anaconda statsmodel
- conda install -c conda-forge statsmodel
- conda install -c conda-forge/label/gcc7 statsmodels
- conda install -c conda-forge/label/cf201901 statsmodels 
- conda install -c conda-forge/label/cf202003 statsmodels 

all give the same result

		PackagesNotFoundError: The following packages are not available from current channels:

		- statsmodels

		Current channels:

		- https://conda.anaconda.org/conda-forge/label/cf202003/osx-arm64
		- https://conda.anaconda.org/conda-forge/label/cf202003/noarch
		- https://repo.anaconda.com/pkgs/main/osx-arm64
		- https://repo.anaconda.com/pkgs/main/noarch
		- https://repo.anaconda.com/pkgs/r/osx-arm64
		- https://repo.anaconda.com/pkgs/r/noarch

#### Expected Output

I'd expect to be able to do ``import statsmodels.api as sm; sm.show_versions()`` !

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

see above.

**Comment by bashtage** [comment]
What OS and python version?

**Comment by bashtage** [comment]
https://anaconda.org/conda-forge/statsmodels

All supported OS combinations are available on conda forge.  I'm going to close since no action for us, but please do continue to post in this issu eif this doesn't resolve your issue.

**Comment by rbelew** [comment]
> All supported OS combinations are available on conda forge.

Then why would my install report "PackagesNotFoundError: The following packages are not available from current channels:"  and mention having tried https://conda.anaconda.org/conda-forge/.../osx-arm64 ?

os=MacOS 12.1; Python=3.8.11

```
     active environment : cvsim
    active env location : .../miniconda3/envs/cvsim
            shell level : 1
       user config file : .../.condarc
 populated config files : .../.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.8.11.final.0
       virtual packages : __osx=12.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : .../miniconda3  (writable)
      conda av data dir : .../miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : .../miniconda3/pkgs
                          .../.conda/pkgs
       envs directories : .../miniconda3/envs
                          .../.conda/envs
               platform : osx-arm64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.8.11 Darwin/21.2.0 OSX/12.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```

**Comment by bashtage** [comment]
What version of statsmodels do you need?  Are you indirectly installing statsmodels from another package?  If so, it might be the case that the requested version is not available. 

Only 0.13.1 is available.  

What happens when you try

```
conda create -n testsm python
conda activate testsm
conda install -c conda-forge statsmodels
```

**Comment by bashtage** [comment]
FWIW there are no developes with OSX arm platforms to test, so there is no direct support.  This said, I trust conda forge to build for OSX arm.
