### ISSUE TITLE
proportion_confint inaccurate for method="binom_test"

### ISSUE THREAD

**Issue by qozet** [statsmodels/statsmodels#7985]
There is a symmetry for binomial proportion confidence interval therefore following property should holds (approximately):
proportion_confint(count, nobs, method="binom_test")[0] + proportion_confint(nobs-count, nobs, method="binom_test")[1] ==1.0
but for some cases this property does not hold, for example, the following code:
```python
from statsmodels.stats.proportion import proportion_confint
eps = 1e-8
for nobs in [47, 50]:
    for count in range(nobs+1):
        p1 = proportion_confint(count, nobs, method="binom_test")
        p2 = proportion_confint(nobs-count, nobs, method="binom_test")
        if abs(p1[0]+p2[1]-1.0)>eps:
            print(f"{nobs=} {count=} {p1[0]+p2[1]}")
```
gives ouput:
```
nobs=47 count=3 0.9899913901078568
nobs=47 count=6 0.9857792597568958
nobs=47 count=12 0.9864319871901812
nobs=47 count=16 0.9851553703015263
nobs=47 count=23 0.9802691065584829
nobs=47 count=24 0.980269106558583
nobs=47 count=31 0.978547082683319
nobs=47 count=35 0.9718877308702878
nobs=47 count=41 0.978042999703059
nobs=47 count=44 0.9680701802192785
nobs=50 count=21 0.9796386543796607
nobs=50 count=29 0.9798450168011505
```
Which indicate that there is some bug.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``
<details>

INSTALLED VERSIONS
------------------
Python: 3.8.5.final.0

statsmodels
===========

Installed: 0.13.1 (C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.17.3 (C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\numpy)
scipy: 1.3.3 (C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\scipy)
pandas: 0.25.3 (C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas)
    dateutil: 2.8.1 (C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dateutil)
patsy: 0.5.2 (C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.2.0rc1 (C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\matplotlib)
    backend: TkAgg
cvxopt: Not installed
joblib: Not installed

Developer Tools
================

IPython: 7.17.0 (C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\IPython)
    jinja2: 2.11.2 (C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jinja2)
sphinx: Not installed
    pygments: 2.6.1 (C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by josef-pkt** [comment]
Thanks for reporting

I can confirm this, but don't see any obvious problem.
It's either because of some discreteness in scipy.stats.binom_test or in scipy.optimize.brentq.
The differences in the confint are nontrivial, but inverting binom_test is not one of the recommended confints (both in the literature and in terms of the quickly done implementation).

But I don't have time to dig into this right now (It's too far away from what I'm currently working on.)

**Comment by josef-pkt** [comment]
label `bug-wrong` because we should have consistent results for symmetry.

However my guess is that they choose different solution because of non-monotonicities or discreteness, which are often a problem with hypothesis tests for proportions.
Requirement for size is only `<= alpha` but not `== alpha` because of the discreteness of the sample space.

**Comment by qozet** [comment]
I have tested the current version of proportion_confint for method="binom_test" and it looks like the new version works better. But symmetry still does not holds for some cases, for example, the following code:
```python
from statsmodels.stats.proportion import proportion_confint
eps = 1e-8
for nobs in range(45, 60):
    for count in range(nobs+1):
        p1 = proportion_confint(count, nobs, method="binom_test")
        p2 = proportion_confint(nobs-count, nobs, method="binom_test")
        if abs(p1[0]+p2[1]-1.0) > eps:
            print(f"{nobs=} {count=} {p1[0]+p2[1]}")
```
gives output:
```
nobs=45 count=45 0.991280515088538
nobs=51 count=51 1.0076714652881384
nobs=53 count=53 1.0073761192248545
nobs=54 count=54 0.9927631623092528
nobs=55 count=49 0.995421075648545
nobs=55 count=51 1.0079684524905446
nobs=58 count=58 0.9932712586455265
nobs=59 count=59 0.9933873005848147
```
Also, previously noted that "Requirement for size is only <= alpha" i.e. method="binom_test" should be conservative. But the current version is not conservative. This can be seen by plotting the graph via the following code:
```python
from statsmodels.stats.proportion import proportion_confint
from scipy.special import comb
import matplotlib.pyplot as plt
import numpy as np
def plot_coverage(methods_for_test, alpha, num, nobs_list):
    # start and end points are excluded to avoid any issue with 0**0
    p_points = np.linspace(1.0/num, 1.0, num, endpoint=False)
    for nobs in nobs_list:
        # compute in advance all binomial coefficients for nobs
        bc = comb(nobs, range(nobs+1))
        for method in methods_for_test:
            # compute in advance all confidence intervals
            all_ci = [[], []]
            for count in range(nobs+1):
                ci = proportion_confint(
                    count, nobs, alpha=alpha, method=method)
                all_ci[0].append(ci[0])
                all_ci[1].append(ci[1])
            plot_data = []
            for p in p_points:
                cp = 0.0
                for count in range(nobs + 1):
                    if all_ci[0][count] < p < all_ci[1][count]:
                        cp += bc[count]*(p**count)*((1.0-p)**(nobs-count))
                plot_data.append(cp)
                if cp < 1.0-alpha:
                    print(f"{nobs=} {p=:.5f} {cp=}")
            plt.plot(p_points, plot_data, label=method + f", {nobs=}")
    plt.hlines(1.0-alpha, 0.0, 1.0, label=f"confidence line, {alpha=}")
    plt.grid(True)
    plt.legend()
    plt.xlabel('p')
    plt.ylabel(r"coverage probability")
    plt.show()


methods_for_test = ["binom_test"]
plot_coverage(methods_for_test, alpha=0.05, num=1999, nobs_list=[31, 50, 75])
```
So we can see that in some cases coverage probability is less than 1-alpha, for example:
```
nobs=31 p=0.17150 cp=0.948454483652453
nobs=31 p=0.82850 cp=0.9484545872375366
nobs=50 p=0.07450 cp=0.9486301423455323
nobs=75 p=0.84900 cp=0.9493717635429614
```
Also, proportion_confint does not work when count is array_array_like and method="binom_test", for example code:
```python
from statsmodels.stats.proportion import proportion_confint
proportion_confint(range(10), 50, method="binom_test")
```
doesn't work.

**Comment by bashtage** [comment]
@qozet I checked your code and the only time you end up with coverage less than 95 is when one of the points is on the boundary.  While this could be changed to make a more asymmetric confidence interval, this would be a big change in the goal.  We should document it better.
