### ISSUE TITLE
pip install the git through google colab never ends

### ISSUE THREAD

**Issue by ahinazar** [statsmodels/statsmodels#7994]
Hey,

I'm working with the repo through google colab for few weeks, and recently i can't install it with pip, don't know why.

the command i do:
`!pip install git+https://github.com/statsmodels/statsmodels.git`

and it just stuck saying:
`Collecting git+https://github.com/statsmodels/statsmodels.git
  Cloning https://github.com/statsmodels/statsmodels.git to /tmp/pip-req-build-l7u9aefz
  Running command git clone -q https://github.com/statsmodels/statsmodels.git /tmp/pip-req-build-l7u9aefz
`

**Comment by bashtage** [comment]
Probably due to changes yesterday in pyproject.toml.  Should be fixed with #7993 is merged.

**Comment by bashtage** [comment]
In the meantime you can install a wheel rather than using master unless you need a very recent feature.

**Comment by bashtage** [comment]
If you want more debugging, you can postpend `-vv` to the `!pip` line.

**Comment by bashtage** [comment]
Should be fixed now. Please let me know if you have any further issues.
