### ISSUE TITLE
ConditionalLogit not available in version 0.13.1 of statsmodels

### ISSUE THREAD

**Issue by adrian-gonzalez-cr** [statsmodels/statsmodels#8008]
#### ConditionalLogit is not available in version 0.13.1 of statsmodels

[This is my first time using statsmodels (thank you so much btw for such great program) and I have no problem estimating some logit models using statsmodels but the conditionallogit  model is not available at all in my configuration and I get the following error:

![image](https://user-images.githubusercontent.com/95703515/148813661-3297c74c-435a-401c-8fa5-a29eb6e66c3d.png)

My current configuration/versions are:
Python 3.8.12
Numpy 1.22.0
Statsmodels 0.13.1

Also, I already tried by reinstalling statsmodels and I confirmed that ConditionalLogit is not installed by running the following:
![image](https://user-images.githubusercontent.com/95703515/148814065-68d0d5f0-4382-42bf-972a-43ce0b8a6ed7.png)
 

Thank you so much.

Adrian

**Comment by josef-pkt** [comment]
Looks like it has not been added to the api modules

try
`from  statsmodels.discrete.conditional_models import ConditionalLogit`

**Comment by josef-pkt** [comment]
As general tip: 
we can search the docs and find the full path
https://www.statsmodels.org/dev/generated/statsmodels.discrete.conditional_models.ConditionalLogit.html
The full path can be used to check if something is available in your version.

But that is also not always conclusive, because sometimes we also forget to add new functionality to the documentation.
(in that case only searching the code helps)

**Comment by adrian-gonzalez-cr** [comment]
Hi Josef,
Thanks for the 

> Looks like it has not been added to the api modules
> 
> try `from statsmodels.discrete.conditional_models import ConditionalLogit`

Hi Josef,

Thanks for this. It worked.

**Comment by adrian-gonzalez-cr** [comment]
> Looks like it has not been added to the api modules
> 
> try `from statsmodels.discrete.conditional_models import ConditionalLogit`

Hi Josef,
thanks for this tip and for the quick reply.
Best.
Adrian
