### ISSUE TITLE
Distributed Estimation example for Seasonal-Trend decomposition using LOESS (STL)

### ISSUE THREAD

**Issue by ehsanbarkhordar** [statsmodels/statsmodels#8024]
I tend to run [Seasonal-Trend decomposition using LOESS (STL)](https://www.statsmodels.org/dev/generated/statsmodels.tsa.seasonal.STL.html) algorithm to detect anomalies in large-scale datasets. To do this, I tried to use [Dask](https://dask.org/) which provides advanced parallelism for analytics, but I was not successful. Unlike [example of GLM model](https://www.statsmodels.org/dev/examples/notebooks/generated/distributed_estimation.html), STL only has endog parameter, so I do not know how to fit my [DistributedModel](https://www.statsmodels.org/dev/generated/statsmodels.base.distributed_estimation.DistributedModel.html?highlight=distributedmodel#statsmodels.base.distributed_estimation.DistributedModel)!

Can anyone help me?

**Comment by josef-pkt** [comment]
Distributed estimation assumes that we can split up the sample which is the case if observations are independent.
In time series analysis the observations are sequentially related and all observations together form just a single sample of the process.

So, the DistributedModel will not apply in that case.

**Comment by bashtage** [comment]
Do you have 1 long time series or many short ones? Many short should be easy.  One long time series is harder, and there is no trivial way to exactly reproduce.  You should get a very close result by segmenting your time series into overlapping segments. Assuming these segments are long relative to the parameters of the STL, then you should be able to fit piece by piece and then splice together.

**Comment by josef-pkt** [comment]
Is the `seasonal.STL` fully non-parametric with local smoothers?

**Comment by ehsanbarkhordar** [comment]
> Do you have 1 long time series or many short ones? Many short should be easy. One long time series is harder, and there is no trivial way to exactly reproduce. You should get a very close result by segmenting your time series into overlapping segments. Assuming these segments are long relative to the parameters of the STL, then you should be able to fit piece by piece and then splice together.

I have a map containing different tiles (cities) and I have a time series for each of them. Each record has two dimensions: GPS motion and time. For example, if we have an index value for each day, we will have an annual time series with 365 records for each tile.
My goal is to find anomalous points in this map, which I use the STL algorithm for.

The main question is what is the best method if we want to do this analysis with high data flow volume.

**Comment by ehsanbarkhordar** [comment]
> Do you have 1 long time series or many short ones? Many short should be easy. One long time series is harder, and there is no trivial way to exactly reproduce. You should get a very close result by segmenting your time series into overlapping segments. Assuming these segments are long relative to the parameters of the STL, then you should be able to fit piece by piece and then splice together.

I have a map containing different tiles (cities) and I have a time series for each of them. Each record has two dimensions: GPS motion and time. For example, if we have an index value for each day, we will have an annual time series with 365 records for each tile.
My goal is to find anomalous points in this map, which I use the STL algorithm for.

The main question is what is the best method if we want to do this analysis with high data flow volume.

**Comment by bashtage** [comment]
Sounds like you can just STL series by series and then continue processing the residuals later.  You could using something simple like `joblib` to apply STL to large groups of series.

**Comment by bashtage** [comment]
> Is the `seasonal.STL` fully non-parametric with local smoothers?

Yes. This is why I suspect that it can be well parallelized on a long series as long as there is enough overlap between segments.

**Comment by ehsanbarkhordar** [comment]
> `joblib`

Thank you very much.
Although `joblib` seems like a good choice to us, can Apache Spark be used instead of it for this purpose?

**Comment by bashtage** [comment]
Yes, of course.  joblib is a lower bar for most, but you can scatter/gather the analysis on a series by series basis.
