### ISSUE TITLE
Not reproducible even in Docker containers

### ISSUE THREAD

**Issue by mankoff** [statsmodels/statsmodels#8050]
#### Describe the bug

The following MWE returns different results (only the last digit!) when run on different computers. I am running this in a Docker container. 1000s of lines of codes are all bit-reproducible except the following MWE, which is why I am filing this issue here rather than with Docker.

Is it possible to have bit-reproducible output with statsmodel?

#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
import pandas as pd
import statsmodels
import statsmodels.api as sm
from statsmodels.sandbox.regression.predstd import wls_prediction_std
np.random.seed(42)

df = pd.DataFrame(columns=['foo', 'bar'], data=np.random.random((1000, 2)))

y = (df['bar'])
X = np.log10(df['foo'])
X = sm.add_constant(X)
model = sm.OLS(y, X)
fits = model.fit()
predictions = fits.predict(X)

XX = np.linspace(X['foo'].min(), X['foo'].max(), 50)
XX = sm.add_constant(XX)
yy = fits.predict(XX)
sdev, lower, upper = wls_prediction_std(fits, exog=XX, alpha=0.05)

bad = df.loc[df['bar'] < 50,'bar']

df.loc[df['bar'] < 50,'bar'] = fits.predict(sm.add_constant(np.log10(bad)))

fits.summary()

with open("output.txt", "w") as text_file:
    text_file.write(fits.summary().as_csv())

df.to_csv('out.csv', index=False)
```

#### Expected Output

Identical results because it is run in the same Docker image.

The differences in out.csv are small. For example,

```bash
$ sdiff <(cat out.csv) <(ssh remote_server cat out.csv) | tail
```

shows the following. Note that only the last digit has changed.

```
0.18610141784627732,0.5081884090422659                        | 0.18610141784627732,0.5081884090422658
0.45818688673789265,0.5082792408801786                        | 0.45818688673789265,0.5082792408801785
0.13347997241594378,0.5085994020210153                        | 0.13347997241594378,0.5085994020210152
0.7279393069737652,0.5082743139146337                         | 0.7279393069737652,0.5082743139146336
0.43685070261517955,0.5082054932289445                        | 0.43685070261517955,0.5082054932289444
0.7655128989911097,0.5084780190581778                         | 0.7655128989911097,0.5084780190581777
0.6102251494776413,0.5085067071667805                         | 0.6102251494776413,0.5085067071667804
0.7513750860290457,0.5082242252400639                           0.7513750860290457,0.5082242252400639
0.956614621083458,0.5086273010565618                            0.956614621083458,0.5086273010565618
0.05705472115125432,0.5083753342014574                        | 0.05705472115125432,0.5083753342014573
```

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

>>> import statsmodels.api as sm; sm.show_versions()

INSTALLED VERSIONS
------------------
Python: 3.9.5.final.0
OS: Linux 5.13.0-25-generic #26-Ubuntu SMP Fri Jan 7 15:48:31 UTC 2022 x86_64
byteorder: little
LC_ALL: C.UTF-8
LANG: C.UTF-8

statsmodels
===========

Installed: 0.13.0 (/opt/conda/lib/python3.9/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.21.2 (/opt/conda/lib/python3.9/site-packages/numpy)
scipy: 1.7.3 (/opt/conda/lib/python3.9/site-packages/scipy)
pandas: 1.3.5 (/opt/conda/lib/python3.9/site-packages/pandas)
    dateutil: 2.8.2 (/opt/conda/lib/python3.9/site-packages/dateutil)
patsy: 0.5.2 (/opt/conda/lib/python3.9/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.5.0 (/opt/conda/lib/python3.9/site-packages/matplotlib)
    backend: agg 
cvxopt: Not installed
joblib: Not installed

Developer Tools
================

IPython: 7.29.0 (/opt/conda/lib/python3.9/site-packages/IPython)
    jinja2: 3.0.2 (/opt/conda/lib/python3.9/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.10.0 (/opt/conda/lib/python3.9/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by josef-pkt** [comment]
> Is it possible to have bit-reproducible output with statsmodels?

No, There are no such guarantees.

You can check whether your LAPACK numpy.linalg.pinv has reproducible floating point noise.
AFAIK, it does not reproduce it in general.

Based on some stackoverflow questions, only elementary operations like sum have some floating point reproducibility.

Why do you need it?

This reproducibility is irrelevant for us, because differences across machines library versions and LAPACK libraries are much larger.

**Comment by mankoff** [comment]
> Why do you need it?

I don't need *this*, but reproducibility is nice when publishing scientific papers, and it's much easier to check reproduction by comparing the md5sum hash of outputs than checking for mostly-reproducible within some rounding error. That takes a few lines of code.

But given that this is running *in a Docker image*, it still seems like it should be bit-reproducible. I'll swim upstream to numpy. Thank you!
