### ISSUE TITLE
ordered logit

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#807]
It looks like Fabian has written a prototype for ordered logit (for eventual inclusion in sklear)
http://fseoane.net/blog/2013/logistic-ordinal-regression/

Maybe it can be partially reused for a statsmodels version of ordered logit.

**Comment by gabrielelanaro** [comment]
I was also looking into ordered logistic regression, but I can't wrap my mind on how to implement it in the statsmodels GLM framework.

**Comment by josef-pkt** [comment]
@gabrielelanaro   I never looked at a GLM version, but I think a `statsmodels.discrete`  maximum likelihood model for ordered logit or ordered probit should be reasonably straight forward.

**Comment by gabrielelanaro** [comment]
@josef-pkt Thank you very much for the pointer!

**Comment by jseabold** [comment]
I have code for some cumulative link models I'm hoping to contribute soon.

**Comment by josef-pkt** [comment]
GEE has an OrdinalGEE subclass
example at http://nbviewer.ipython.org/urls/umich.box.com/shared/static/y1fw0iameuixrq9zt02d.ipynb?create=1  (I haven't figured out how it calculates the estimate.)

**Comment by josef-pkt** [comment]
#2600 WIP PR to get started

references in R
http://www.uni-kiel.de/psychologie/rexrepos/posts/regressionOrdinal.html   documentation overview
package ordinal for cumulative link models https://cran.r-project.org/web/packages/ordinal/

**Comment by josef-pkt** [comment]
possibly share code with interval regression http://www.ats.ucla.edu/stat/stata/dae/intreg.htm

**Comment by quillan86** [comment]
Any update on this? I'd like to use ordinal regression for my work and ideally in python.

**Comment by josef-pkt** [comment]
miscmodels version merged #7035
follow-up issue #7069
