### ISSUE TITLE
Deprecated pandas index type still being used in statsmodels 0.13.1

### ISSUE THREAD

**Issue by Iqigai** [statsmodels/statsmodels#8090]
When importing pandas, a warning is raised stating that pandas.Int64Index has been deprecated and will be removed in the future. The code seems to be working so far, and it is not really a bug, however, soon or late this might cause issues.

```python
>>> import statsmodels. api as sm
Warning (from warnings module):
  File "C:\Program Files\Python39\lib\site-packages\statsmodels\compat\pandas.py", line 65
    from pandas import Int64Index as NumericIndex
FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
 
```
**Note**: The new pandas version has been released 10 days ago and I could not identify in the backlog any report on this issue
**Note**:  warning is present with statsmodels 0.13.1
**Note**: main branch release
#### Expected Output
No warning should be raised

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

INSTALLED VERSIONS
------------------
Python: 3.9.10.final.0

statsmodels
===========

Installed: 0.13.1 (C:\Program Files\Python39\lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: 0.29.24 (C:\Program Files\Python39\lib\site-packages\Cython)
numpy: 1.19.5 (C:\Program Files\Python39\lib\site-packages\numpy)
scipy: 1.7.0 (C:\Program Files\Python39\lib\site-packages\scipy)
pandas: 1.4.0 (C:\Program Files\Python39\lib\site-packages\pandas)
    dateutil: 2.8.1 (C:\Program Files\Python39\lib\site-packages\dateutil)
patsy: 0.5.2 (C:\Program Files\Python39\lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.4.2 (C:\Program Files\Python39\lib\site-packages\matplotlib)
    backend: Qt5Agg 
cvxopt: Not installed
joblib: 1.0.1 (C:\Program Files\Python39\lib\site-packages\joblib)

Developer Tools
================

IPython: 8.0.1 (C:\Users\Fennehk\AppData\Roaming\Python\Python39\site-packages\IPython)
    jinja2: 3.0.1 (C:\Program Files\Python39\lib\site-packages\jinja2)
sphinx: 4.0.2 (C:\Program Files\Python39\lib\site-packages\sphinx)
    pygments: 2.9.0 (C:\Program Files\Python39\lib\site-packages\pygments)
pytest: 6.2.5 (C:\Program Files\Python39\lib\site-packages\pytest)
virtualenv: Not installed
[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

</details>

**Comment by bashtage** [comment]
This has been already fixed in master.
