### ISSUE TITLE
Unobserved Component model - exog variables - out of sample predict

### ISSUE THREAD

**Issue by waudinio27** [statsmodels/statsmodels#8095]
Hello everybody, 

I am trying to predict/forecast out of sample with the UC model and exog. variables. 

I have added the recommended exog variable with a dataframe that has the required size and I can do predictions with it. 
But it is not possible to print out Predicted vs. observed values. It just prints out the change of the level. 

Below is my code: 

```
# these are the indicators arranged like in the thesis 
exog = df[['EMA_5','EMA_15','EMA_60','EMA_90', 'EMA_150', 'EMA_200']]

y = df['EMA_30']
plot_series(y)

import numpy as np

import statsmodels.api as sm

forecaster = sm.tsa.UnobservedComponents( endog = y,  level='smooth trend',  exog = exog)


res = forecaster.fit(maxiter=200)

res.plot_components(figsize=(18,18))
```
![grafik](https://user-images.githubusercontent.com/42875245/152369605-c21d9851-8d93-4ca1-bb04-f2e1043f6851.png)

```
# it is possible to enter 0 or None as a value of the added rows, 
# but with None the prediction does not work

d = pd.DataFrame(0, index=np.arange(22), columns=df.columns)
f = d[['EMA_5','EMA_15','EMA_60','EMA_90', 'EMA_150', 'EMA_200']]

df2 = pd.concat([df,f])

f.head()

# The columns now have been selected for exog :-D

start = len(df)+1
end = start +20
outlook = (res.predict(steps = 20,start = start, end = end, exog = f))

plt.plot(outlook)
```
![grafik](https://user-images.githubusercontent.com/42875245/152369526-cce03224-bf8b-46cf-9f29-2f0c895a9ecc.png)

What can I do to get the predicted value of y instead of the value for the level component? 

If I add y to res.predict I get:
```


# The columns now have been selected for exog :-D


​
start = len(df)+1


end = start +20



outlook = (res.predict(y, steps = 20,start = start, end = end, exog = f))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-99bf1f3e25c3> in <module>
      3 start = len(df)+1
      4 end = start +20
----> 5 outlook = (res.predict(y, steps = 20,start = start, end = end, exog = f))

~\anaconda3\lib\site-packages\statsmodels\base\wrapper.py in wrapper(self, *args, **kwargs)
    111             obj = data.wrap_output(func(results, *args, **kwargs), how[0], how[1:])
    112         elif how:
--> 113             obj = data.wrap_output(func(results, *args, **kwargs), how)
    114         return obj
    115 

TypeError: predict() got multiple values for argument 'start'
```
If it is possible to arrange the start values it should predict like expected and desired. Or at least I hope so.

**Comment by ChadFulton** [comment]
> `res.predict(steps = 20,start = start, end = end, exog = f)`
> `res.predict(y, steps = 20,start = start, end = end, exog = f)`

Neither of these are valid calls to the `predict` method, since it does not take a data argument `y` and it does not take a `steps` argument. See the documentation [here](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.structural.UnobservedComponentsResults.predict.html#statsmodels.tsa.statespace.structural.UnobservedComponentsResults.predict).

> What can I do to get the predicted value of y instead of the value for the level component?

For the "smooth trend" model, the prediction value of y is equal to the predicted value of the level component.

**Comment by ChadFulton** [comment]
Closing as answered, but feel free to follow up if you have questions.
