### ISSUE TITLE
OrderedModel: a bug and its version has been updated

### ISSUE THREAD

**Issue by EvgeniyZaz** [statsmodels/statsmodels#8116]
#### Describe the bug

The current example requires importing OrderedModel using the wrong code. It seems that you updated the package and the path to this tool has been changed.
In addition, there is a problem with the estimation of the ordered model. It always cannot estimate it because it cannot find a hessian matrix.

#### Code Sample, a copy-pastable example if possible

```python
from statsmodels.miscmodels.ordinal_model import OrderedModel #this is a wrong path
from statsmodels.discrete.discrete_model import OrderedModel #this is a correct path
#See the example.
url = "https://stats.idre.ucla.edu/stat/data/ologit.dta"
data_student = pd.read_stata(url)
data_student.head(5)
data_student.dtypes
data_student['apply'].dtype
pd.CategoricalDtype(categories=['unlikely', 'somewhat likely', 'very likely'], ordered=True)
mod_log = OrderedModel(endog=data_student['apply'],
                        exog=data_student[['pared', 'public', 'gpa']],
                        distr='logit')

res_log = mod_log.fit()
res_log.summary()
```
However, the model cannot be estimated. It seems, that the OrderedModels has been changed.

**Comment by josef-pkt** [comment]
`statsmodels.discrete.discrete_model.OrderedModel` was just a stub version, not a real model. It has been deleted.

the correct model is the one in `miscmodels`.
However, it does not have fit_regularized, only unpenalized `fit`

Do you use a recent version of statsmodels?

**Comment by josef-pkt** [comment]
discrete_model.OrderModel stub was removed in 0.13.0
https://github.com/statsmodels/statsmodels/commit/27777aaffa9a3685b289049e0bbac9c4d9102ce4

**Comment by EvgeniyZaz** [comment]
I use statsmodels 0.13.2 and it tells that there is no 'ordinal_model' in the miscmodel. I reinstalled by using pip, but it sill cannot find 'discrete'.

**Comment by josef-pkt** [comment]
Do you have the correct statsmodels version on the path?

import statsmodels
statsmodels.__version__

your example code works for me, when using the miscmodels import

**Comment by josef-pkt** [comment]
aside: OrderedModel is not in statsmodels.api

**Comment by EvgeniyZaz** [comment]
I have the 13.0-th version

```python
#in cmd
Name: statsmodels
Version: 0.13.0
Summary: Statistical computations and models for Python
Home-page: https://www.statsmodels.org/

#in python:
import statsmodels
```
