### ISSUE TITLE
Exciting Index Error

### ISSUE THREAD

**Issue by ashsharma96** [statsmodels/statsmodels#8132]
Hey Statsmodel Team,
Currently I'm working with SARIMAX function and I got this error that is share below:

    IndexErrorTraceback (most recent call last)
    <ipython-input-13-3a21437c0eb0> in <module>
    3 for param in tqdm_notebook(parameters_list):
    4     print(param[0], param[1], param[2], param[3])
    ----> 5     model=sm.tsa.statespace.SARIMAX(result.AvgLTV, order=(param[0], d, param[1]), seasonal_order=(param[2], D, 
    param[3], s)).fit(disp=-1)
    6     aic = model.aic
    7     print(aic)

    ~/.local/lib/python3.7/site-packages/statsmodels/tsa/statespace/mlemodel.py in fit(self, start_params, transformed, includes_fixed, 
    cov_type, cov_kwds, method, maxiter, full_output, disp, callback, return_params, optim_score, optim_complex_step, optim_hessian, 
    flags, low_memory, **kwargs)
        648         """
        649         if start_params is None:
    --> 650             start_params = self.start_params
        651             transformed = True
        652             includes_fixed = True

    ~/.local/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py in start_params(self)
        954             endog, self.k_ar, self.polynomial_ar, self.k_ma,
        955             self.polynomial_ma, self._k_trend, trend_data,
    --> 956             warning_description='ARMA and trend')
        957 
        958         # If we have estimated non-stationary start parameters but enforce

    ~/.local/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py in _conditional_sum_squares(endog, k_ar, 
    polynomial_ar, k_ma, polynomial_ma, k_trend, trend_data, warning_description)
        834                 # parameters
        835                 if k_ma > 0:
    --> 836                     Y = endog[k:]
        837                     X = lagmat(endog, k, trim='both')
        838                     params_ar = np.linalg.pinv(X).dot(Y)

    IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

So My data is monthly LTV Data. Two columns are present in result dataframe. My month column is in index. Even if I have two columns but its showing 0-D array which is not possible because I've checked the shape of the result dataframe and that shows 14 rows and 1 column. But here the turns comes up, whenever I add one more month data it works fine. I don't know what is causing this. If I have 14 months data then it shows above error and if I have 15 months data then it works fine. 
Any idea about this?

Regards

**Comment by bashtage** [comment]
Can you please post a complete example that will reproduce this issue?

**Comment by ashsharma96** [comment]
@bashtage Thank you for replying. I'll share the example data:

parameters_list = [(2, 2, 0, 0), (2, 2, 0, 1), (2, 2, 1, 0), (2, 2, 1, 1), (2, 3, 0, 0), (2, 3, 0, 1), (2, 3, 1, 0), (2, 3, 1, 1), (2, 4, 0, 0),
 (2, 4, 0, 1), (2, 4, 1, 0), (2, 4, 1, 1), (3, 2, 0, 0), (3, 2, 0, 1), (3, 2, 1, 0), (3, 2, 1, 1), (3, 3, 0, 0),
 (3, 3, 0, 1), (3, 3, 1, 0), (3, 3, 1, 1), (3, 4, 0, 0), (3, 4, 0, 1), (3, 4, 1, 0), (3, 4, 1, 1), (4, 2, 0, 0), (4, 2, 0, 1), (4, 2, 1, 0), (4, 2, 1, 1),
 (4, 3, 0, 0), (4, 3, 0, 1), (4, 3, 1, 0), (4, 3, 1, 1), (4, 4, 0, 0), (4, 4, 0, 1), (4, 4, 1, 0), (4, 4, 1, 1)]

There are two csv's attached named as result_with_14_values & result_with_14_values.  result_with_14_values csv gives error and result_with_15_values csv workes properly. Code where it gives error is this:

    for param in tqdm_notebook(parameters_list):
        print(param[0], param[1], param[2], param[3])
        model=sm.tsa.statespace.SARIMAX(result.AvgLTV, order=(param[0], d, param[1]), seasonal_order=(param[2], D, param[3], 
        s).fit(disp=-1)
        aic = model.aic
        print(aic)

[result_with_14_values.csv](https://github.com/statsmodels/statsmodels/files/8108116/result_with_14_values.csv)
[result_with_15_values.csv](https://github.com/statsmodels/statsmodels/files/8108118/result_with_15_values.csv)

s = 12
d = 1
D = 1
These are the other parameters which I've kept in the code. 
 So @bashtage it would be helpful if you help me with this.

**Comment by bashtage** [comment]
You are trying to fit models that cannot be estimated.  For example, you have seasonal AR orders of 4 with s=12 but only 14 or 15 data points.  While this issue should give you a more meaningful error message, there is no way to fit these models.

**Comment by ashsharma96** [comment]
@bashtage so what do you suggest what should be the correct Seasonality(s value) if I have to predict for next 6 months value depending on these past 14 or 15 values. Thank you so much for replying in a short time.
