### ISSUE TITLE
Displaying summary tables in LaTeX when converting Jupyter Notebooks to PDF via nbconvert

### ISSUE THREAD

**Issue by Max-FM** [statsmodels/statsmodels#8133]
#### Is your feature request related to a problem? Please describe
There's currently no built-in method to display tables in LaTeX when converting Jupyter Notebooks to PDF via nbconvert. Output is a string in the converted PDF.

#### Describe the solution you'd like
Including a method along the lines of:
```
def _repr_latex_(self):
    return self.as_latex()
```
somewhere in the summary table scripts would mean the tables could be displayed as both HTML directly in the Jupyter notebook and LaTeX in the converted PDF.

#### Describe alternatives you have considered
I can manually patch my Jupyter notebook to produce a centred LaTeX summary table in my output PDF file:
```
def _repr_latex_(self):
    return f"\\begin{{center}}\n{self.as_latex()}\n\\end{{center}}"

statsmodels.iolib.summary.Summary._repr_latex_ = _repr_latex_
```
however, it would be nice to have this feature built directly into statsmodels. :)

If I have time I'll try making a PR myself, but I've never contributed to statsmodels before, so it might take me a bit of time to ensure that I'm doing everything correctly.

**Comment by bashtage** [comment]
Great idea. Want to do a PR?

**Comment by josef-pkt** [comment]
I think you can use the web interface directly to edit the modules and make a pr, if you don't have a development setup

https://github.com/statsmodels/statsmodels/blob/main/statsmodels/iolib/summary.py#L763
https://github.com/statsmodels/statsmodels/blob/main/statsmodels/iolib/summary2.py#L29

centered or uncentered?
I don't know which looks better.

**Comment by Max-FM** [comment]
Okay, I've drafted something up and it seems like it centres by default. Admittedly I'm a bit unsure how to write unit tests for these new lines? I don't see any tests for the `_repr_html_` methods so maybe they're not required?

**Comment by josef-pkt** [comment]
We have smoke tests for summary, but not many real tests because results like time (and floating point noise) change with each run.

**Comment by Max-FM** [comment]
So the PR is ready for review with unit tests. Unfortunately, the `statsmodels.statsmodels`  workflow failed with error:

`##[error]We stopped hearing from agent Azure Pipelines 8. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610`

This seems like an external issue, as the unit tests successfully pass on my local machine.
