### ISSUE TITLE
BUG: etest_poisson_2indep() not allowing custom ygrid

### ISSUE THREAD

**Issue by stefanvodita** [statsmodels/statsmodels#8135]
[The documentation](https://www.statsmodels.org/dev/generated/statsmodels.stats.rates.etest_poisson_2indep.html#statsmodels.stats.rates.etest_poisson_2indep) states that `ygrid` is a parameter we can supply to `etest_poisson_2indep`, but this is broken at the moment:

```python
from statsmodels.stats.rates import etest_poisson_2indep
etest_poisson_2indep(1, 1, 1, 1, ygrid=1)
```

Output:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/voditas/.local/lib/python3.7/site-packages/statsmodels/stats/rates.py", line 249, in etest_poisson_2indep
    pdf1 = stats.poisson.pmf(y_grid, mean1)
UnboundLocalError: local variable 'y_grid' referenced before assignment
```

This happens in version 0.13.2 (but probably others too) for any value of `ygrid` that is not `None` and is because of the likely accidental usage of `y_grid` instead of `ygrid` in the function:

```python
  if ygrid is None:                                      # uses ygrid, like the API
        threshold = stats.poisson.isf(1e-13, max(mean1, mean2))
        threshold = max(threshold, 100)   # keep at least 100
        y_grid = np.arange(threshold + 1)                # changes to y_grid
pdf1 = stats.poisson.pmf(y_grid, mean1)                  # if ygrid was set, an error will be thrown
pdf2 = stats.poisson.pmf(y_grid, mean2)
```

The fix is easy - replace usages of `y_grid` with `ygrid`, as in the API. I will create a PR with this fix.

**Comment by stefanvodita** [comment]
I thought of doing that just to make less code changes, but I think it's confusing to have both `ygrid` and `y_grid`. There is no reason to make a distinction, is there?

**Comment by josef-pkt** [comment]
It's taste question when there is no convention yet, and I'm changing my pattern every once in a while. 
Our code convention has some preference for adding underlines, but not strict in borderline cases.

I like `y_grid`
Recently I added a `y_values` option to count model predict (which doesn't need to be a grid). 

So, I guess now I prefer to change the keyword in the function itself to `y_grid`, i.e. add y_grid and deprecate `ygrid`.
Or for now, at least we should make a renaming y_grid to ygrid

**Comment by stefanvodita** [comment]
I opened the PR deprecating `ygrid`. Let me know if it's what you wanted.
Had a hard time running the tests on my machine, so I'm waiting for the checks on the PR instead.

**Comment by josef-pkt** [comment]
I usually run the test only on a specific module (or even individual tests)
`pytest path_to_test_module`
This is usually fast (especially if import `statsmodels.api as sm` has been avoided in the unit tests
