### ISSUE TITLE
ARIMAResults.apply(series) does not return list

### ISSUE THREAD

**Issue by abbiesgame** [statsmodels/statsmodels#8141]
```
df = pd.read_csv('GOOG.csv')
close = df['Close']
model = sm.tsa.ARIMA(close, order=(3, 0, 0))
model_fit = model.fit()
new = pd.Series([3000, 2900], index=[300, 301])
result = model_fit.apply(new)
print(result)
```
Output
`<statsmodels.tsa.arima.model.ARIMAResultsWrapper object at 0x000001A573F4D2E0>`

Instead of a Wrapper object, I was expecting a list calculated with fitted parameters.

**Comment by bashtage** [comment]
Docs are pretty clear here:

https://www.statsmodels.org/dev/generated/statsmodels.tsa.arima.model.ARIMAResults.apply.html

`apply` produces a new set of results using the same parameter values with a different endog variable.

**Comment by bashtage** [comment]
Closing as answered. If you want the fitted value using different parameters, access the `fittedvalues` parameters of the results object.

Closing as answered.
