### ISSUE TITLE
PanelOLS .get.prediction ()?

### ISSUE THREAD

**Issue by someselectedprojects** [statsmodels/statsmodels#8151]
Hello,

I am looking for a way to retrieve the output or calculate standard errors and CI on fitted values.

Your example below shows how to use get.prediction() but it is not available for PanelOLS.

Can you help me out? Thank you!

https://gist.github.com/josef-pkt/1417e0473c2a87e14d76b425657342f5

**Comment by bashtage** [comment]
This should be on the linearmodels tracker.

**Comment by someselectedprojects** [comment]
@bashtage , would you be able to provide me the example that follows the logic this link below but for PanelOLS? I do not know where to find "linear models tracker"?
Thanks so much!!
Anna
https://gist.github.com/josef-pkt/1417e0473c2a87e14d76b425657342f5
