### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'double' but got 'float' when using KMeans

### ISSUE THREAD

**Issue by hibetterheyj** [statsmodels/statsmodels#8156]
#### Describe the bug

I plan to visualize the decision boundary of KMeans results, but when input data for predict function. It reports "ValueError: Buffer dtype mismatch, expected 'double' but got 'float'" although I have already cast dtype before input.

#### Code Sample, a copy-pastable example if possible

```python
# Your code here that produces the bug
# This example should be self-contained, and so not rely on external data.
# It should run in a fresh ipython session, and so include all relevant imports.
model = KMeans(n_clusters=3)
model.fit(shared_control_data_)

h = .02     # point in the mesh [x_min, m_max]x[y_min, y_max].    

# Plot the decision boundary. For that, we will assign a color to each
x_viz_data = shared_control_data_['max_crowd_density2_5'].values
y_viz_data = shared_control_data_['avg_crowd_density2_5'].values

x_min, x_max = x_viz_data.min() - 1, x_viz_data.max() + 1
y_min, y_max = y_viz_data.min() - 1, y_viz_data.max() + 1

# Meshgrid creation
xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
data_xy = np.c_[xx.ravel(), yy.ravel()]
data_xy.astype('double')
Z = model.predict(data_xy)   
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `main`. If your problem has been fixed in an unreleased version, you might be able to use `main` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the main branch of this repository? It helps the limited resources if we know problems exist in the current main branch so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

Correct prediction for meshgrid so that we could follow the tutorial to visualize the decision boundary

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.8.12.final.0
OS: Linux 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.13.0 (~/miniconda3/envs/py38cuda110/lib/python3.8/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.14 (/usr/lib/python3/dist-packages/Cython)
numpy: 1.21.4 (~/.local/lib/python3.8/site-packages/numpy)
scipy: 1.7.2 (~/.local/lib/python3.8/site-packages/scipy)
pandas: 1.3.4 (~/.local/lib/python3.8/site-packages/pandas)
    dateutil: 2.8.2 (~/.local/lib/python3.8/site-packages/dateutil)
patsy: 0.5.2 (~/miniconda3/envs/py38cuda110/lib/python3.8/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.1.2 (/usr/lib/python3/dist-packages/matplotlib)
    backend: module://matplotlib_inline.backend_inline 
cvxopt: Not installed
joblib: 0.17.0 (~/.local/lib/python3.8/site-packages/joblib)

Developer Tools
================

IPython: 7.29.0 (~/.local/lib/python3.8/site-packages/IPython)
    jinja2: 3.0.3 (~/.local/lib/python3.8/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.10.0 (~/.local/lib/python3.8/site-packages/pygments)
pytest: 4.6.9 (/usr/lib/python3/dist-packages)
virtualenv: Not installed

</details>

**Comment by josef-pkt** [comment]
statsmodels does not have KMeans
Is this for scikit-learn?

**Comment by bashtage** [comment]
Closing since this is scikit-learn.
