### ISSUE TITLE
DOC: Add a better description of the plot generated by plot_fit

### ISSUE THREAD

**Issue by druzmieres** [statsmodels/statsmodels#8175]
#### Is your feature request related to a problem? Please describe
The documentation of the function `plot_fit` does not describe the features of the plots it generates. The value in the y-axis and the fitted value are covered by the legend but there's no description of the vertical black lines.

#### Describe the solution you'd like
I'd like the docstring to include the meaning of the features of the plot, and especially the one of the vertical black lines.

#### Describe alternatives you have considered
I had to look for the information somewhere else. There's an answer here: https://stackoverflow.com/questions/30327329/vertical-lines-in-plot-fit-graphic-of-python-ststsmodels-package

**Comment by bashtage** [comment]
We are always happy to have a PR to improve documentation.
