### ISSUE TITLE
what is `_data_attr` in `statsmodels.base.Model` and `statsmodels.regression.linear_model.RegressionModel`?

### ISSUE THREAD

**Issue by naveen-marthala** [statsmodels/statsmodels#8197]
I have been trying to understand code of linear-regression models. I couldn't quite understand what `_data_attr` in [`statsmodels.base.Model`](https://github.com/statsmodels/statsmodels/blob/408eae829c8b3ebca2f0ea46e69f3a62b94a554d/statsmodels/base/model.py#L100=) and [`statsmodels.regression.linear_model.RegressionMode`](https://github.com/statsmodels/statsmodels/blob/408eae829c8b3ebca2f0ea46e69f3a62b94a554d/statsmodels/regression/linear_model.py#L194=). It is also not present in What is the purpose of fhose variables and what do they do?

I need to know that because, in [this line](https://github.com/statsmodels/statsmodels/blob/408eae829c8b3ebca2f0ea46e69f3a62b94a554d/statsmodels/regression/linear_model.py#L194=) of `statsmodels.regression.linear_model.WLS`, inherited class is being instantiated like this:
```
super(WLS, self).__init__(endog, exog, missing=missing, weights=weights, hasconst=hasconst, **kwargs)
```
But, neither [`RegressionModel`](https://github.com/statsmodels/statsmodels/blob/408eae829c8b3ebca2f0ea46e69f3a62b94a554d/statsmodels/regression/linear_model.py#L191), [`LikelihoodModel`](https://github.com/statsmodels/statsmodels/blob/408eae829c8b3ebca2f0ea46e69f3a62b94a554d/statsmodels/base/model.py#L269) or [`Model`](https://github.com/statsmodels/statsmodels/blob/408eae829c8b3ebca2f0ea46e69f3a62b94a554d/statsmodels/base/model.py#L92=) have `weights` in their constructor arguments, which should raise an error for invalid argument, but it somehow doesn't. and  [`self._data_attr`](https://github.com/statsmodels/statsmodels/blob/408eae829c8b3ebca2f0ea46e69f3a62b94a554d/statsmodels/regression/linear_model.py#L194) of `statsmodels.regression.linear_model.RegressionModel` has `weights` like this:
```
self._data_attr.extend(['pinv_wexog', 'wendog', 'wexog', 'weights'])
```

**Comment by josef-pkt** [comment]
to `_data_attr`:
see #1729 and similar issues

It lists the names of the attributes that are full data length and should be removed by `remove_data`.
This was created to support pickling without including all the data that is not needed for prediction.

> ... or Model have weights in their constructor arguments, which should raise an error for invalid argument

The base model classes allow for additional arguments in kwargs, intermediate classes transmit any kwargs to super.
The base model class handles data kwargs and attaches all kwargs as attributes.

This  is done this way, so subclasses can have arbitrary extra keywords, especially keywords that are extra data like weights.

The same applies to other models not just to linear RegressionModel

**Comment by josef-pkt** [comment]
There are several related issues, and several more attributes like `_data_attr`

e.g. avoiding that something invalid goes into kwargs
#7741
