### ISSUE TITLE
ENH: Generalize forecasting of STL to allow appending new data

### ISSUE THREAD

**Issue by gsamaras** [statsmodels/statsmodels#8204]
I have trained LSTM in my application to look-back at 3 data points and predict the next one (3-1 prediction). So now that I've deployed it in the real world, 3 values come in (i.e. a list of 3 elements) and LSTM predicts 1 value.

Is that possible with STL? Or it's just not applicable?

With STL I can forecast regardless of what comes at runtime. In the example below, STL forecasts 24 steps after the data that it has fit on:

```python
import matplotlib.pyplot as plt
from statsmodels.datasets import elec_equip as ds
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.forecasting.stl import STLForecast

elec_equip = ds.load().data
elec_equip.index.freq = 'MS'
stlf = STLForecast(elec_equip, ARIMA, model_kwargs=dict(order=(1, 1, 0), trend="t"))
stlf_res = stlf.fit()

forecast = stlf_res.forecast(24)
plt.plot(elec_equip)
plt.plot(forecast)
plt.show()
```

So my question is that if I deploy this now in my application, it will predict the same thing for the next 1 value regardless of what 3 values arrive as input. My worry is that in this way we don't know where we are in the Time Series plot, so we might predict poorly.

Let me put my worry into a picture:
![160822612-d4b74fad-0a97-4fbd-a548-e28846219a5f](https://user-images.githubusercontent.com/12050610/161049962-3489f7e5-0e7d-4f08-b1ab-980c501b9c1d.png)

---

With LSTM I'd do:
```python
X = np.array([1, 3.14, 2])
inp = X.reshape((X.shape[0], X.shape[1], 1))
yhat = trained_LSTM_model.predict(inp, verbose=0)
```

Can I do something similar with STL?

**Comment by bashtage** [comment]
STL Forecast is only really designed for simple out-of-sample forecasting from the end of a training sample. This is mostly because it only assumes that the underlying model can used to produce the forecast of the deseasonalized data supports this, but not other methods.  Adding a more nuanced forecast method that allows for more general train/forecast setups is challenging.

**Comment by gsamaras** [comment]
Thanks @bashtage.

So in general when you are talking about forecasting with time decomposition, we are talking about forecasting at the end of the training sample.

That means that even I wouldn't use `STLForecast()`, but STL to decompose and then train autoregressive models on the decomposed components, it would still be the same.

So my question boils down to this, is STL decomposition forecasting inapplicable to the application I describe in my image, i.e. for doing a 3-1 prediction?

**Comment by bashtage** [comment]
> That means that even I wouldn't use `STLForecast()`, but STL to decompose and then train autoregressive models on the decomposed components, it would still be the same.

Yes. This is what STL forecast does.  This and forecast the seasonal component.

1. STL to decompose
2. Forecast model on the deseasonalized data
3. Forecast from model in 2 + seasonal component forecast from 1

You can make STF forecast whenever you want.  You would normally just use the most recent `n` data points where `n` has to be big enough to fit the STL and the model in #2. 

An STL looks back many points because it does a lowess on the seasonal frequency. So in general describing it like 3-1 would not be correct. Something basic like a non-seasonal ARIMA(p,d,q) could be described like 3-1 for appropriate choices of p and d.

**Comment by gsamaras** [comment]
@bashtage bare with me but I want to make sure I understand if I can forecast with STL like I would do with LSTM. Allow me to explain what I do with LSTM and ask if it's possible to do the same 3-1 prediction with STL, hoping to compare the methods afterwards.

In the LSTM I have trained, the LSTM model has learned a function that maps a sequence of past observations as input
to an output observation. Consider a given univariate sequence:
`[10, 20, 30, 40, 50, 60, 80, 80, 90]`
We can divide the sequence into multiple input/output patterns called samples, where
three time steps are used as input and one time step is used as output for the one-step prediction that is being learned.
```
X,                       y
10, 20, 30               40
20, 30, 40               50
30, 40, 50               60
```

So I will train the LSTM model like this, and then I'll predict like that:
```
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input)
```
where I would expect the model to predict something like `[100]`. I am wondering if I can do the same with STL.

**Comment by bashtage** [comment]
STL + a forecasting model do not work like this.  The STL wants to forecast the seasonal and trend pattern based on the last seasonal cycle in the data plus the extrapolated trend. You cannot put in variables like the "covariates" you have in your example.

**Comment by gsamaras** [comment]
@bashtage this is what I had understood too, thank you so much! 
Last question: I guess the same applies with replacing STL with the Theta method, or the `seasonal_decompose()`, or HP filter, right?

**Comment by bashtage** [comment]
That is correct. The STL part only really works from the end of the sample.

**Comment by gsamaras** [comment]
Thanks a lot for the guidance, I am closing this issue since all of my questions are now answered! If you think otherwise, feel free to drive it.
