### ISSUE TITLE
BUG: Check input class in recursive_olsresiduals

### ISSUE THREAD

**Issue by cammarcott** [statsmodels/statsmodels#8222]
In version 13.2.2, the following code:

from statsmodels.tsa.arima.model import ARIMA
from statsmodels.stats.diagnostic import recursive_olsresiduals
import numpy as np
X = np.random.rand(100)
Y = np.random.rand(100)
model = ARIMA(endog=Y,order(2,0,0),exog=X,trend='c')
recursive_olsresiduals(model,alpha=0.95)

Produces the error:
ValueError: could not broadcast input array from shape (2,1). into shape (2,)

This same error occurs when using trend = 'c', 't', or 'ct'. The function recursive_olsresiduals works as expected with trend = 'n'.

**Comment by bashtage** [comment]
It is supposed to be a `RegressionResults` which you `model` is not.  Basically this should be disallowed with a useful error message.

**Comment by cammarcott** [comment]
Thank you for promptly addressing and adding the type check!
