### ISSUE TITLE
BUG/ENH: Remove print within graphics.plot_partregress

### ISSUE THREAD

**Issue by AmarAdilovic** [statsmodels/statsmodels#8248]
#### Describe the bug

Within regressionplots.py the plot_partregress function prints the eval_env variable. The default behavior is to print "eval_env: 1" to console. I believe that this parameter is better left to being explained within documentation and see little reason for why it is necessary to print the variable. It also causes any function that calls upon plot_partregress to print, such as plot_regress_exog. 

#### Code Sample

```regressionplots.py
fig, ax = utils.create_mpl_ax(ax)
    print("eval_env:", eval_env)
```

**Comment by josef-pkt** [comment]
I'm pretty sure that was left over from a debugging session.

PR to delete the line with the print would be welcome.

**Comment by josef-pkt** [comment]
Thanks for reporting this

**Comment by AmarAdilovic** [comment]
No problem! I'll create the PR shortly.
