### ISSUE TITLE
Update model with new exog or endog data

### ISSUE THREAD

**Issue by Zepp3** [statsmodels/statsmodels#8262]
I was trying to figure out if statsmodel also offers some kind of update function, where one can update the model with new y and X data.  The update function of the statsmodel module does not fulfill my needs, as far as I can see: https://www.statsmodels.org/devel/generated/statsmodels.tsa.arima.model.ARIMA.update.html.

I imagine it like the update function of the pmdarima module: https://alkaline-ml.com/pmdarima/modules/generated/pmdarima.arima.ARIMA.html#pmdarima.arima.ARIMA.update.
This function is really suitable for optimization loops in pipelines or framework, that handle multiple models, as many models can work with this function.

Right now I solve this problem by completely reloading the class (e.g. ExponentialSmoothing or ARIMA) with the wanted y and X data and fitting the model again, before doing predictions with the updated model. But this seems to be a very cumbersome way of solving this issue and I wish I knew a more elegant and universal way, as this has to be done for every model individually.

**Comment by ChadFulton** [comment]
You may be interested in the `append` method, see e.g. the documentation at https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_forecasting.html#Cross-validation
