### ISSUE TITLE
Wrong critical values for Hansen's test (1992)

### ISSUE THREAD

**Issue by oronimbus** [statsmodels/statsmodels#8265]
Refer to https://github.com/statsmodels/statsmodels/blob/27b797389ca1991ac691e6e6f91451a38f84a24d/statsmodels/stats/diagnostic.py#L1573  

The critical values are incorrect as per Greene's text book (section 7.5.1 page 134). They should be "1.01 for K = 2, 1.90
for K = 6, 3.75 for K = 15, and 4.52 for K = 19". See last sentence:

![image](https://user-images.githubusercontent.com/11311783/166480896-5f7a730c-29a7-4973-a2ce-db514f9e33f5.png)

I've created a PR for this [here](https://github.com/statsmodels/statsmodels/pull/8263).

**Comment by josef-pkt** [comment]
Thanks for reporting and the PR

looks like a typo   (the corrected value and reference is from Greene's 5th edition which I had used)

**Comment by oronimbus** [comment]
Many thanks @josef-pkt !
