### ISSUE TITLE
External features support for ETS

### ISSUE THREAD

**Issue by Manjubn777** [statsmodels/statsmodels#8273]
Hey team, 
I would like to know if any possibility of ETS supporting external features. Even any small info/reference links on implementation of multivariate ETS would be appreciable.

Thanks in advance..

**Comment by ChadFulton** [comment]
We don't support explanatory variables in ETS. Chapter 9 of Hydnman et al.,  "Forececasting with Exponential Smoothing" discusses ETS models with regressor variables.
