### ISSUE TITLE
tools for code maintenance

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#829]
we should add more code inspection tools, that come in handy sometimes.
(I'm always misplacing them on my computer)

example: 
in which class in the class hierarchy is a method defined? 
(I asked the question once on the scipy ? mailing list)

**Comment by jbrockmendel** [comment]
The author of this issue was wise yet humble.

**Comment by bashtage** [comment]
I'm not sure how/where these are needed. Closing for now.
