### ISSUE TITLE
Is it possible to make an AR prediction that includes the noise term?

### ISSUE THREAD

**Issue by dougiesquire** [statsmodels/statsmodels#8292]
Total newbie here, so my apologies in advance if the answer is obvious or I've misunderstood something.

#### Describe the solution you'd like
Predictions made with Autoregressive models do not include the noise term (epsilon). Is is possible to somehow include this so that I could, for example, generate an ensemble of dynamic predictions that would all differ in their noise component?

#### Describe alternatives you have considered
I've written my own function for making a prediction that includes the noise, but I would be nicer/cleaner/faster to have an approach that uses statsmodels `predict` if possible.

#### Additional context
I understand that what I'm asking here is maybe somewhat unusual. I'm trying to use `statsmodels` to generate synthetic time series with particular behaviours. One such behaviour can be included if I can work out how to do the above.

**Comment by ChadFulton** [comment]
If you use `ARIMA` or `SARIMAX`, you can do this using the `simulate` method combined with the argument `anchor='end'`, which will produce simulations starting from the end of the time series.  Here's an example

```python
np.random.seed(1234)
# Get some data
data = sm.datasets.macrodata.load_pandas().data
data.index = pd.date_range('1959Q1', periods=len(data), freq='Q')
y = np.log(data['cpi']).diff(1).iloc[1:-12] * 400

# Construct and fit a model
mod = sm.tsa.ARIMA(y, order=(1, 0, 0))
res = mod.fit()
# Compute the forecast and confidence intervals
sf = res.get_forecast(10).summary_frame(alpha=0.1)
# Compute a simulation, starting from the end
sim = res.simulate(10, anchor='end')

# Plot
fig, ax = plt.subplots(figsize=(12, 5))
plt.plot(y.iloc[-12:], label=y.name)
plt.plot(sf['mean'], label='Forecast')
plt.fill_between(sf.index, sf['mean_ci_lower'], sf['mean_ci_upper'], alpha=0.2, label='90% CI')
plt.plot(sim, label='Simulation');
plt.legend();
```

which produces:

![image](https://user-images.githubusercontent.com/280864/170166993-8b671243-335e-4287-95dc-04e687a86d3f.png)

**Comment by ChadFulton** [comment]
Closing as answered, but please feel free to follow up if you have additional questions about this.
