### ISSUE TITLE
TypeError: x is None but the model contains exogenous variables. You must provide expected values to use for the exogenous variables to construct forecasts.

### ISSUE THREAD

**Issue by LodewijkSweerts** [statsmodels/statsmodels#8312]
Hi all, 

I am working on a thesis where I want to use EGARCH models to forecast next month's residual variance. I want to describe the mean process with a LS regression where I have Excess Return as my dependent variable and as my independent variabels 'Mkt', 'SMB', 'HML'. I made the following code for forecasting next month residual variance but I get an error message. 

TypeError: x is None but the model contains exogenous variables. You must provide expected values to use for the exogenous variables to construct forecasts.

I do not know what to do actually and I can not find that much on the internet to solve my problem. Hope you guys can help. 

Here is my code:

X = dfC[['MKT', 'SMB' ,'HML']].values[:60]
y = dfC['Excess_Return'].values[:60]
forecasts = []
for i in range(1, 4):
      for j in range(1, 4):
            model = arch_model(y, X, mean='LS', vol='EGARCH', p=i, o=i, q=j, dist='normal')
            res = model.fit(disp='off', options={'iter': 1000})
            fcst = math.sqrt(res.forecast(res.params, horizon=1).residual_variance[-1:]['h.1'].to_list()[0])
            forecasts.append(fcst)

The error message:

TypeError: x is None but the model contains exogenous variables. You must provide expected values to use for the exogenous variables to construct forecasts.

**Comment by ChadFulton** [comment]
Statsmodels does not have `arch_model`. I think you are looking for https://github.com/bashtage/arch
