### ISSUE TITLE
Maximum Likelihood optimization failed to converge

### ISSUE THREAD

**Issue by yushiokamura** [statsmodels/statsmodels#8314]
Hi, I'm using state space model by `statsmodels.tsa.statespace.structural.UnobservedComponents`.
I choice "State space modeling: Local Linear Trends", by setting `lltrend` into `level` parameter, and I choice `bfgs` optimization. 

When I executed the model , A warning message  was called,  

```
ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
```

What is cause of this warning ?  Will something go wrong if left unattended?
If so, I want to know how to avoid this warning.

**Comment by ChadFulton** [comment]
This message suggests that the optimizer is having a hard time determining good values for all of the parameters. There are a number of possible reasons why this could happen, but one reason is if the model is not a good fit for your data.

For example, the local linear trend model assumes a trending series. If that’s not a good description of your data, it may have a hard time finding a good value for the associated variance parameter.

that’s just one example of something that might be happening. If you can post your data, we could probably be more specific.

**Comment by yushiokamura** [comment]
Thank you for your answer !

> For example, the local linear trend model assumes a trending series. If that’s not a good description of your data, it may have a hard time finding a good value for the associated variance parameter.

Data I treat contains intense noises and I add some external factors into the model. Perhaps these would be some of causes.

> that’s just one example of something that might be happening. If you can post your data, we could probably be more specific.

thanks. But I can't bring out the data. So I'll try find appropriate model myself! 

I thought our data contained liner trending, but my choice maybe isn't appropriate.
Is there any references for decision models in time series ?

**Comment by ChadFulton** [comment]
Closing as answered.

**Comment by MKPasha** [comment]
Hi, I am also getting this warning when I am trying to predict the weekly price of gasoline per gallon. My p is range(0,25,8) and q is (0,3,1) and order is (p,0,q). I am working on the weekly dataset from this link[https://www.eia.gov/dnav/pet/hist/LeafHandler.ashx?n=pet&s=emm_epm0_pte_nus_dpg&f=w](url). Can you please suggest which model should I use for this data?
