### ISSUE TITLE
ETS fit with missing values

### ISSUE THREAD

**Issue by chenghaoliu89** [statsmodels/statsmodels#8334]
Hi, I am trying to forecast from a time series with missing values. As mentioned early in this [issue](https://github.com/statsmodels/statsmodels/issues/2551), state space model could handle missing value in endogenous. Both ETS and SARIMA are special cases for state space model.  It works well for SARIMAX, but statsmodels.tsa.exponential_smoothing.ets.ETSModel will output NaN. Is there any way to fix it? Can we implement the ETS with a custom state space model?

**Comment by ChadFulton** [comment]
If you have a linear ETS model, then you can use `statsmodels.tsa.statespace.ExponentialSmoothing`, which has support for missing values.

If you have a multiplicative ETS model, then we don't have anything that supports missing values.

Closed as answered.
