### ISSUE TITLE
graphics missing plots in documentation

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#834]
several graphics functions don't have examples that create plots

**Comment by jtweeder** [comment]
Seems like an easy enough task to start working on, and would be useful to users.  Also looks like good examples already exist to learn from.  Below is a task list of the ones I have found at first glance.  If there are any others let me know and I can add them.

Looking through the [Graphics module ](http://www.statsmodels.org/dev/graphics.html#module-statsmodels.graphics) 
I can see the following do not have any examples:
- [ ] [plot.grids.scatter_eclipse](http://www.statsmodels.org/dev/generated/statsmodels.graphics.plot_grids.scatter_ellipse.html#statsmodels.graphics.plot_grids.scatter_ellipse)
- [ ] [regressionplots.plot_regress_exog](http://www.statsmodels.org/dev/generated/statsmodels.graphics.regressionplots.plot_regress_exog.html#statsmodels.graphics.regressionplots.plot_regress_exog)
- [ ] [regressionplots.plot_partregress](http://www.statsmodels.org/dev/generated/statsmodels.graphics.regressionplots.plot_partregress.html#statsmodels.graphics.regressionplots.plot_partregress)
- [ ] [regressionplots.plot_ccpr](http://www.statsmodels.org/dev/generated/statsmodels.graphics.regressionplots.plot_ccpr.html#statsmodels.graphics.regressionplots.plot_ccpr)
- [ ] [regressionplots.influence_plot](http://www.statsmodels.org/dev/generated/statsmodels.graphics.regressionplots.influence_plot.html#statsmodels.graphics.regressionplots.influence_plot) 
- [ ] [regressionplots.plot_leverage_resid2](http://www.statsmodels.org/dev/generated/statsmodels.graphics.regressionplots.plot_leverage_resid2.html#statsmodels-graphics-regressionplots-plot-leverage-resid2)
- [ ] [tsaplots.plot_acf](http://www.statsmodels.org/dev/generated/statsmodels.graphics.tsaplots.plot_acf.html#statsmodels.graphics.tsaplots.plot_acf)
- [ ] [tsaplots.plot_pacf](http://www.statsmodels.org/dev/generated/statsmodels.graphics.tsaplots.plot_pacf.html#statsmodels.graphics.tsaplots.plot_pacf)
- [ ] [tsaplots.quarter_plot](http://www.statsmodels.org/dev/generated/statsmodels.graphics.tsaplots.quarter_plot.html#statsmodels.graphics.tsaplots.quarter_plot)

These have examples that would produce a plot (minor tweaking may be needed), but do not display the plot in the example:
- [ ] [gofplots.qqplot_2samples](http://www.statsmodels.org/dev/generated/statsmodels.graphics.gofplots.qqplot_2samples.html#statsmodels.graphics.gofplots.qqplot_2samples)
- [ ] [correlation.plot_corr](http://www.statsmodels.org/dev/generated/statsmodels.graphics.correlation.plot_corr.html#statsmodels.graphics.correlation.plot_corr)
- [ ] [correlation.plot_corr_grid](http://www.statsmodels.org/dev/generated/statsmodels.graphics.correlation.plot_corr_grid.html#statsmodels.graphics.correlation.plot_corr_grid)
- [ ] [regressionplots.abline_plot](http://www.statsmodels.org/dev/generated/statsmodels.graphics.regressionplots.abline_plot.html)
- [ ] [mosaicplot.mosaic](http://www.statsmodels.org/dev/generated/statsmodels.graphics.mosaicplot.mosaic.html)

**Comment by josef-pkt** [comment]
@thequackdaddy @bashtage 
Is it possible to link from docstrings to notebooks as reference?

In cases where we have a more extensive notebook it would be useful to be able to link to them for further examples.

**Comment by bashtage** [comment]
I don't know an easy way.  It is possible to link from rst files to notebooks using [nbsphinx](https://nbsphinx.readthedocs.io/en/0.3.5/) and standard `ref` tags, but this would be big change in the doc build process since this has sphinx run the notebooks as part of the build and the notebooks are located inside the docs (this can be worked around by copying them into the docs early in conf.py)

**Comment by bashtage** [comment]
Of course, one could add a note and say see examples\NBNAME

**Comment by thequackdaddy** [comment]
I think the docs do it just by showing a relative link... e.g., in RLM...
https://raw.githubusercontent.com/statsmodels/statsmodels/ec28d8939f14fa90fea0663ddc466f0832a27249/docs/source/rlm.rst

```
* `Robust Models 1 <examples/notebooks/generated/robust_models_0.html>`__
* `Robust Models 2 <examples/notebooks/generated/robust_models_1.html>`__
```

**Comment by bashtage** [comment]
External URLs work from rst but wouldn't work from a docstring in practice. 

If one was really desperate, I think it would be possible to have a page with a list of the notebooks where each has an annotation, and then the docstring could have a ref to the annotation.  I think this would be pretty clunky, and it would be far simpler to just tell the user to look at the example notebooks for more complete examples of the use of a model.

**Comment by jtweeder** [comment]
I will work through the list with all of that in mind and post a PR when I get them completed.  I will see what looks clean with trying to integrate some links or 'see...' comments as needed.

**Comment by jtweeder** [comment]
I have gotten what I think should be working into my branch of the partial regression docstring.  I ran make clean and make html but nothing changed in my local version of the documents.  I wanted to make sure I was not missing something before moving on to prevent having to rework.  

Also is there a way to only rebuild the particular doc page I would expect changes on.  Not totally comfortable with sphinx yet so I wanted to make sure everything was showing up like I wanted, but did not want to wait for an entire rebuild every time.

**Comment by josef-pkt** [comment]
sphinx normally figures out what changed and only rebuilds those pages.
What I sometimes do, is to delete some of the `generated` rst files so sphinx is forced to rebuild them.

**Comment by bashtage** [comment]
Or just make clean followed by make html

**Comment by josef-pkt** [comment]
@jtweeder Is your branch installed and on the python path?
I haven't checked in a while, but AFAIR, sphinx uses the installed statsmodels for the docstring and not the one in a local checkout

**Comment by jtweeder** [comment]
Thanks @josef-pkt that appears to be the issue!  I knew it had to be something I was doing and assumed it was looking in my local checkout, which was a silly assumption.

**Comment by josef-pkt** [comment]
It's not a silly assumption, I ran into this a few times (that's why it finally sounded familiar).
But sphinx has to import the code and doesn't just parse the source tree, which allows us to use programmatically created docstrings.
