### ISSUE TITLE
pythran possibly breaking TestDynamicFactor_ar2_errors.test_mle

### ISSUE THREAD

**Issue by rebecca-palmer** [statsmodels/statsmodels#8341]
#### Describe the bug

Debian's scipy recently enabled pythran, which caused TestDynamicFactor_ar2_errors.test_mle to give the wrong result on s390x ([Debian discussion](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014278) ; full [log](https://ci.debian.net/data/autopkgtest/unstable/s390x/s/statsmodels/23275012/log.gz) including dependency versions).

So far, this problem has only been seen on unusual hardware (s390x) and if it can only happen there it's probably not worth fixing, but I don't know if it might be a sign of a more general problem with pythran breaking things.  (I may be overly concerned about this because I wasted a day to a (non-statsmodels) case of an optimization library breaking things.)  Does the statsmodels CI use a pythran-enabled scipy?

It's also possible that this test is numerically unstable, given its [history](https://github.com/statsmodels/statsmodels/issues/2672) of [failures](https://github.com/statsmodels/statsmodels/issues/2681) that went away but were never explained.

#### Code Sample, a copy-pastable example if possible

The standard test suite.

#### Expected Output

The tests should pass.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

scipy 1.8.1, statsmodels 0.13.2, pythran 0.11.0, see the above log if you need more.

**Comment by drew-parsons** [comment]
Incidentally in regards to pythran breaking tests with tight conversion tolerance, I raised the issue upstream at https://github.com/serge-sans-paille/pythran/issues/2000 (mentioned also at https://github.com/serge-sans-paille/pythran/issues/2002)

**Comment by bashtage** [comment]
We test against release versions of SciPy and the nightly version that is available on Anaconda.  We don't test at all against S390 as it is too exotic to get any attention. Could skip this test on s390 if it matters.

**Comment by drew-parsons** [comment]
Pythran seems to have shifted the goal posts for [mipsel](https://buildd.debian.org/status/fetch.php?pkg=statsmodels&arch=mipsel&ver=0.13.2%2Bdfsg-3&stamp=1657570865&raw=0) as well
```
____________________ TestGMMStOneiterOLS_Linear.test_basic _____________________

self = <statsmodels.sandbox.regression.tests.test_gmm.TestGMMStOneiterOLS_Linear object at 0x6c0ce0a0>

    def test_basic(self):
        res1, res2 = self.res1, self.res2
        # test both absolute and relative difference
        rtol,  atol = self.params_tol
        assert_allclose(res1.params, res2.params, rtol=rtol, atol=0)
>       assert_allclose(res1.params, res2.params, rtol=0, atol=atol)
E       AssertionError: 
E       Not equal to tolerance rtol=0, atol=1e-12
E       
E       Mismatched elements: 1 / 13 (7.69%)
E       Max absolute difference: 1.12443388e-12
E       Max relative difference: 1.53607078e-12
E        x: array([ 6.195478e-02,  2.712120e-03,  3.083947e-02,  4.216306e-02,
E              -9.629347e-02,  1.328993e-01, -5.420948e-02,  8.058085e-02,
E               2.075915e-01,  2.282237e-01,  2.226915e-01,  3.228747e-01,
E               4.235357e+00])
E        y: array([ 6.195478e-02,  2.712120e-03,  3.083947e-02,  4.216306e-02,
E              -9.629347e-02,  1.328993e-01, -5.420948e-02,  8.058085e-02,
E               2.075915e-01,  2.282237e-01,  2.226915e-01,  3.228747e-01,
E               4.235357e+00])

../.pybuild/cpython3_3.10_statsmodels/build/statsmodels/sandbox/regression/tests/test_gmm.py:207: AssertionError
```

Only a mild discrepancy in this case.  Relaxing tolerance from 1e-12 to 2e-12 would be enough to restore it.

**Comment by ChadFulton** [comment]
I know this is a little late :), but I think that `TestDynamicFactor_ar2_errors.test_mle` most likely that this is a numerically unstable test rather than a bug in pythran. As @bashtage says, please skip it if it matters.

Going to close this issue as it seems to be resolved, but please reopen if I've misunderstood.

**Comment by josef-pkt** [comment]
It also failed once yesterday after an unrelated merge, on LinuxTest python_39
https://dev.azure.com/statsmodels/statsmodels-testing/_build/results?buildId=4834&view=logs&j=3f9beef4-2a87-5b9a-d136-eeaf4b842580&t=bde20e0b-dfe9-50c5-4f8a-b07f464aecfb

**Comment by ChadFulton** [comment]
Thanks @rebecca-palmer and @josef-pkt, I'll rewrite this test soon so that we stop getting these failures.
