### ISSUE TITLE
`ETSModel` fails to fit time series accurately 

### ISSUE THREAD

**Issue by FedericoGarza** [statsmodels/statsmodels#8344]
#### Describe the bug

I ran an instance of `ETSModel` and I had strange fitted values.

#### Code Sample, a copy-pastable example if possible

```python
import numpy as np
from statsmodels.tsa.exponential_smoothing.ets import ETSModel

y = np.array([352000.,   4186.,   4171.,   4196.,   4184.,   4192.,   4192.,
         4178.,   4146.,   4153.,   4174.,   4158.,   4147.,   4135.,
         4153.,   4148.,   4168.,   4193.,   4209.,   4224.,   4256.,
         4249.,   4277.,   4304.,   4290.,   4304.,   4231.,   4205.,
         4182.,   4183.,   4181.,   4142.,   4157.,   4262.,   4256.,
         4251.,   4215.,   4210.,   4207.,   4230.,   4185.,   4055.,
         4014.,   4007.,   4035.,   4015.,   3997.,   3940.,   3975.,
         3971.,   3981.,   4013.,   4010.,   4053.,   4054.,   4015.,
         4062.,   4086.,   4272.,   4294.,   4301.,   4324.,   4319.,
         4169.,   4028.,   3993.,   3932.,   3987.,   4225.,   4191.,
         4316.,   4342.,   4402.,   4454.,   4493.,   4411.,   4330.,
         4119.,   4211.,   4240.,   4283.,   4256.,   4304.,   4264.,
         4278.,   4312.,   4337.,   4266.,   4278.,   4284.,   4310.,
         4324.,   4334.,   4422.,   4336.,   4294.,   4256.,   4255.,
         4247.,   4215.,   4219.,   4254.,   4285.,   4287.,   4251.,
         4263.,   4245.,   4152.,   4111.,   4081.,   3986.,   3965.,
         3973.,   3982.,   3929.,   3983.,   4021.,   4042.,   4038.,
         4081.,   4086.,   4119.,   4044.,   4131.,   4148.,   4108.,
         4113.,   4104.,   4103.,   4124.,   4151.,   4121.,   4126.,
         4117.,   4115.,   4126.,   4158.,   4153.,   4156.,   4156.,
         4194.,   4213.,   4175.,   4207.,   4196.,   4149.,   4154.,
         4156.,   4156.,   4166.,   4217.,   4229.,   4219.,   4215.,
         4213.,   4267.,   4255.,   4265.,   4226.,   4251.,   4289.,
         4282.,   4331.,   4250.,   4278.,   4316.,   4320.,   4336.,
         4289.,   4259.,   4254.,   4277.,   4298.,   4322.,   4309.,
         4319.,   4289.,   4288.,   4235.,   4215.,   4223.,   4209.,
         4214.,   4260.,   4244.,   4259.,   4272.,   4222.,   4194.,
         4141.,   4186.,   4156.,   4131.,   4137.,   4127.,   4101.,
         4105.,   4121.,   4083.,   4086.,   4024.,   4026.,   4026.,
         3978.,   3967.,   3958.,   3965.,   4027.,   3960.,   3921.,
         3924.,   3929.,   3954.,   3933.,   3913.,   3860.,   3861.,
         3886.,   3885.,   3894.,   3899.,   3852.,   3853.,   3862.,
         3861.,   3861.,   3877.,   3891.,   3944.,   4005.,   4006.,
         3994.,   3950.,   3978.,   4008.,   4000.,   4127.,   4078.,
         4033.,   3938.,   3995.,   3987.,   3994.,   3996.,   4027.,
         4032.,   3976.,   3993.,   3960.,   3972.,   4019.,   4044.,
         4074.,   4014.,   4017.,   4096.,   4087.,   4090.,   4034.,
         4057.,   4068.,   4057.,   4064.,   4003.,   4008.])

plt.plot(y, label='Actual')
plt.plot(ETSModel(y, error='mul', trend='add').fit(disp=False).predict(), label='Statsmodels')
plt.legend()
```
<img width="401" alt="image" src="https://user-images.githubusercontent.com/10517170/179121325-694d99d9-a1b7-489f-9939-0210a3bdf0a2.png">

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

INSTALLED VERSIONS
------------------
Python: 3.7.12.final.0
OS: Linux 5.13.0-1021-aws #23~20.04.2-Ubuntu SMP Thu Mar 31 11:36:15 UTC 2022 x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8

statsmodels
===========

Installed: 0.13.2 (/home/ubuntu/miniconda/envs/ets/lib/python3.7/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.30 (/home/ubuntu/miniconda/envs/ets/lib/python3.7/site-packages/Cython)
numpy: 1.21.4 (/home/ubuntu/miniconda/envs/ets/lib/python3.7/site-packages/numpy)
scipy: 1.7.3 (/home/ubuntu/miniconda/envs/ets/lib/python3.7/site-packages/scipy)
pandas: 1.3.5 (/home/ubuntu/miniconda/envs/ets/lib/python3.7/site-packages/pandas)
    dateutil: 2.8.2 (/home/ubuntu/miniconda/envs/ets/lib/python3.7/site-packages/dateutil)
patsy: 0.5.2 (/home/ubuntu/miniconda/envs/ets/lib/python3.7/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.5.2 (/home/ubuntu/miniconda/envs/ets/lib/python3.7/site-packages/matplotlib)
    backend: module://matplotlib_inline.backend_inline 
cvxopt: Not installed
joblib: 1.1.0 (/home/ubuntu/miniconda/envs/ets/lib/python3.7/site-packages/joblib)

Developer Tools
================

IPython: 7.34.0 (/home/ubuntu/miniconda/envs/ets/lib/python3.7/site-packages/IPython)
    jinja2: 3.1.2 (/home/ubuntu/miniconda/envs/ets/lib/python3.7/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.12.0 (/home/ubuntu/miniconda/envs/ets/lib/python3.7/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed

**Comment by ChadFulton** [comment]
Thanks for the report.

This is a bit of a pathological example, given the extreme difference between the first observation and the rest of the sample.

The issue comes in estimating the initial level and trend parameters. The starting values for the estimation routine use a very simple method by default for computing the initial values of these parameters (the level is set to the first observation, the trend is set to the second observation minus the first). Since this gives a very poor set of parameters here, the optimization routine is not able to make good progress towards a better set of parameters.

For example, you get much more reasonable results if you do:

```python
plt.plot(ETSModel(y, error='mul', trend='add').fit(
    start_params=[0.1, 0.01, 4000, 0], disp=False
).predict(), label='Statsmodels')
```

Closing as answered.
