### ISSUE TITLE
RegressionResults.scale is scale^2

### ISSUE THREAD

**Issue by user799595** [statsmodels/statsmodels#8349]
#### Describe the bug

`statsmodels.regression.linear_model.RegressionResults.scale` seems to be returning the square of a scale?

If your endogenous variable is height, than scale should be in metres or feet, not in squaremetres or squarefeet.

This issue is currently present on the main branch:
https://github.com/statsmodels/statsmodels/blob/be626481e32717fe7ff62ddb78c5b24125c8f7b4/statsmodels/regression/linear_model.py#L1691

#### Expected Output

```python
np.sqrt(np.dot(wresid, wresid) / self.df_resid)
```

**Comment by josef-pkt** [comment]
Too late to change.

It also threw me off when I ran into this the first time.

There should be an ancient issue for it. However I’m not able to search for it.

iPad at the pool bar :)

**Comment by josef-pkt** [comment]
#3760

**Comment by user799595** [comment]
Thanks for digging this up. 

> Too late to change.

Was worried this might be the case.
