### ISSUE TITLE
DynamicFactor Parameters Interpretation

### ISSUE THREAD

**Issue by joeewest** [statsmodels/statsmodels#8352]
I am trying to understand the `DynamicFactor` model using the artificial data generated below. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File>
<link rel=File-List
</head>

<body link="#0563C1" vlink="#954F72">

  |   |   | t | 0 | 1 | 2 | 3 | 4 | 5
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
A | 1.5000 |   | ft | 0.606 | 0.908 | 1.363 | 2.044 | 3.066 | 4.599
Λ1 | 0.8257 |   | y1t | 0.500 | 0.750 | 1.125 | 1.688 | 2.531 | 3.797
Λ2 | 1.2385 |   | y2t | 0.750 | 1.125 | 1.688 | 2.531 | 3.797 | 5.695
</body>

</html>

Using the data above, I tried running the following codes to create the model.

```
import statsmodels.api as sm
import pandas as pd

df = pd.DataFrame([[0.75,1.125],[1.125,1.688],[1.688,2.531],[2.531,3.797],[3.797,5.695]], columns=['Y1', 'Y2'])

model = sm.tsa.DynamicFactor(
    endog=df, k_factors=1, factor_order=1
)

results = model.fit(method='powell', disp=False, ftol=1e-10)

print(results.factors.filtered[0])
print(results.summary(separate_params=False))
```
The output of the code is 
```
[0.90838558 1.36298171 2.04366646 3.06590187 4.59845005]
                                   Statespace Model Results                                  
=============================================================================================
Dep. Variable:                          ['Y1', 'Y2']   No. Observations:                    5
Model:             DynamicFactor(factors=1, order=1)   Log Likelihood                  22.948
Date:                               Tue, 26 Jul 2022   AIC                            -35.897
Time:                                       15:46:59   BIC                            -37.850
Sample:                                            0   HQIC                           -41.138
                                                 - 5                                         
Covariance Type:                                 opg                                         
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
loading.f1.Y1     0.8257      1.808      0.457      0.648      -2.719       4.370
loading.f1.Y2     1.2385      2.714      0.456      0.648      -4.080       6.557
sigma2.Y1      1.447e-07      0.001      0.000      1.000      -0.002       0.002
sigma2.Y2      3.105e-10      0.002    1.4e-07      1.000      -0.004       0.004
L1.f1.f1          0.9499      0.651      1.458      0.145      -0.327       2.227
===================================================================================
Ljung-Box (L1) (Q):             1.12, 5.21   Jarque-Bera (JB):           0.45, 0.42
Prob(Q):                        0.29, 0.02   Prob(JB):                   0.80, 0.81
Heteroskedasticity (H):        12.44, 1.52   Skew:                      0.51, -0.41
Prob(H) (two-sided):            0.15, 0.79   Kurtosis:                   1.95, 1.85
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).

/home/joe/anaconda3/lib/python3.9/site-packages/statsmodels/base/model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
```

I get that the `loadings.f1.Y1` and `loadings.f2.Y2` came from Λ1 and Λ2, but I don't understand where the value of `L1.f1.f1` came from. I expected it to be 1.50 (value of A) but it gave a different value. What does `L1.f1.f1` represent? I'm using statsmodels version 0.13.2.

Thank you!

**Comment by ChadFulton** [comment]
By default the `DynamicFactor` model restricts the parameter space to models that are stationary. When `A=1.5`, the model is not stationary, so this is ruled out by default. You can pass the argument `enforce_stationarity=False` in the model constructor to remove this restriction (although with such a short dataset, you still will likely not get 1.5 as the estimate).

Closing as answered, but feel free to follow up if you have more questions.

**Comment by joeewest** [comment]
Thanks for the clarification @ChadFulton. I just have a follow-up regarding the factors. Running the code below produces the following output.
```
print(results.factors.filtered[0])

[0.90838558 1.36298171 2.04366646 3.06590187 4.59845005]
```
The values of the factors correspond to `A=1.5` (1.36298171/0.90838558=1.5, 2.04366646/1.36298171=1.5, etc.) even though the model says that `A=0.9499`. Why does the 1.5 "appear" in the factors?

Thank you!
