### ISSUE TITLE
Question: Is a GBLUP method available?

### ISSUE THREAD

**Issue by showhey0119** [statsmodels/statsmodels#8356]
Hi, I wonder if the statsmodels can handle a GBLUP method, a special case of linear mixed models.  I apologize in advance if I am wrong.

GBLUP follows `y = Xb + Zu + e`, where `y` is an `n` x 1 vector, `Xb` contains only an intercept, `Z` is an `n` x `n` identity matrix, and `u` is an `n` x 1 random effect vector.  `u` follows N (0, `G`\*`vu`), where `G` is an `n` x `n` matrix for the variance-covariance structure and `vu` is variance of `u`.  `e` follows N (0, `ve`).  I'd like to predict/estimate `u`, `vu`, and `ve` given known `y` and `G` with `n`= 800.

First, I ignored the variance-covariance structure and tried to run statsmodels  as
```
model = sm.MixedLM(endog=y, exog=np.ones(n), groups=np.arange(n))
```
It successfully ran, and the estimated Group Var (`vu`) and intercept were close to the expected values.
However, I tried to incorporate the variance-covariance structure as
```
model = sm.MixedLM(endog=y, exog=np.ones(n), groups=np.arange(n), exog_re=G)
```
It ran but never stopped.  
I'm afraid I used statsmodels in silly ways.  I'd appreciate it if you could give any suggestions.

**Comment by kshedden** [comment]
I am familiar with this type of model, but unfortunately I don't think we
can fit it in MixedLM.  We can fit the standard Laird & Ware formulation of
the linear mixed model, in which you have y_i = X_i b + Z_i u_i + e_i,
where i indexes independent groups, X_i and Z_i are known design matrices,
and y_i is the observed vector of responses (all for group i).  But in
Statsmodels each u_i either has an unstructured covariance matrix or a
diagonal covariance matrix, in either case with all parameters to be
estimated from the data.  You cannot have a specific fixed "G" matrix.

The other option Statsmodels supports is a variance components model in
which you have y_i = X_i b + M_1i u_1i + ... + M_ki u_ki + e_i, where the
M_ki are known design matrices and each u_i has a covariance matrix v_k*I,
where v_k is a scalar and I is an identity matrix of appropriate size.  In
other words, the elements of each u_ji vector are iid.

It is also possible to include both the Laird & Ware and the variance
components structures in the same model.

On a separate point, when you pass groups=np.arange(n), all the groups have
only one observation each.  In this case the group variance and error
variance are not identified.  So I don't know how you were able to conclude
that the group variance was close to the expected value in this case.
