### ISSUE TITLE
please make the statsmodels 0.14.0 (+502) version available on PyPi

### ISSUE THREAD

**Issue by prasanjitdash** [statsmodels/statsmodels#8358]
#### Is your feature request related to a problem? Please describe
I need to use some features available in the latest `statsmodels 0.14.0 (+502)` but not in `0.13.0`

#### Describe the solution you'd like
Please make the new version available on `PyPi`

#### Describe alternatives you have considered
-  I downloaded the zipped folder and installed, directly with `python setup.py install`. The installation worked fine but I could not `import statsmodels.tsa.seasonal` The error was due to unavailability of version information, i.e., the `_version.py` file
- git clone fails on my system due to ssh issues (I do not have admin rights, policy issues)

Thank you.

**Comment by josef-pkt** [comment]
I had the same problem.
python setup.py does not work anymore. It now requires pip install

**Comment by bashtage** [comment]
`pip install git+https://github.com/statsmodels/statsmodels.git`

**Comment by bashtage** [comment]
Can only publish releases on pypi, not arbitrary patch levels. You can also install the nightly wheels. Search in issues for the location on Anaconda.org.

**Comment by prasanjitdash** [comment]
thanks @bashtage @josef-pkt . Understand and appreciate your response. I will try the `pip install -i https://pypi.anaconda.org/scipy-wheels-nightly/simple statsmodels`.

The `pip install git...` encounters some `SSH` issues (on my side and I have no admin rights). 

The patch level version on github has some advanced statistical methods, so perhaps someday this will become the next release. Can the available zipped folder possibly be fixed and we can install directly with `python setup.py install`? It installed seamlessly but is missing the `_version.py` version information, so importing is being denied.

**Comment by bashtage** [comment]
You can also doesnload the zip from github, extract it, CD to where you extracted the code, and then enter `pip install .`  This is the modern equivalent to calling setup.py directly.

**Comment by bashtage** [comment]
You might need to use

`pip install. --no-build-isolation`

To use this you will need to have installed numpy, cython, scipy, pandas and setuptools-scm

**Comment by prasanjitdash** [comment]
Thanks, @bashtage. I was hoping this will work but it did not fully go through. Its still throwing some error that I did not understand.

>
    error: invalid command 'bdist_wheel'
    [end of output]
    note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.


I have `numpy, cython, scipy, pandas and setuptools-scm` packages installed

**Comment by bashtage** [comment]
You probably need `wheel` too.

**Comment by bashtage** [comment]
Sounds like you need to clone the repo locally, then you can build from the clone.  Seems to be less easy to build from a zip (or impossible now).

**Comment by prasanjitdash** [comment]
Thanks, again. Installed `wheel` and tried. The error still is:

> 
     × Preparing metadata (pyproject.toml) did not run successfully.
     exit code: 1
     LookupError: setuptools-scm was unable to detect version for$PATH/statsmodels-main


I will try the local repo approach.

**Comment by prasanjitdash** [comment]
Hi @bashtage , The installation now worked following what you suggested.

Local repo --> `pip install . ----no-build-isolation`

So, thank you again. But, some new issues exist now:

`from statsmodels.tsa.seasonal import seasonal_decompose`
`ModuleNotFoundError: No module named 'statsmodels.tsa.stl._stl'`
`from statsmodels.tsa.seasonal import STL`
`ModuleNotFoundError: No module named 'statsmodels.tsa.stl._stl'`

If I execute:
`dir(statsmodels.tsa)` it retuns:
['PytestTester', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'stl', 'test']

Any pointer would be useful. It seems like I have picked up a wrong version.
`pip list` shows `statsmodels        0.14.0.dev514+gedd843f`

**Comment by bashtage** [comment]
First, when you start `python` or `ipython` you _should not_ be in the git repo.  If you are in the git repo, it will look in the `statsmodels` folder and since you installed it to site-packages, it won't find the the compiled modules.  I suspect this is your problem.


Also, you should use 

```
python -m pip ...
```

rather than `pip` directly.  You should also confirm that `python` is the correct python.

**Comment by prasanjitdash** [comment]
hey @bashtage . Your suspicion was spot on. From a folder outside of the `local git clone`, running
`python -m pip install $PATH/localtemp/statsmodels`  ran through.

Python import does not throw any error now
`from statsmodels.tsa.seasonal import seasonal_decompose as SMA`
`from statsmodels.tsa.seasonal import STL`
...

I hope this will now work but I will be sure after I run some calculations.
Thanks again.

**Comment by bashtage** [comment]
Sounds solved.  I'm going to close, but please reopen if the issue pops up again.

**Comment by dodofit** [comment]
> `pip install git+https://github.com/statsmodels/statsmodels.git`

This worked for installing statsmodels 0.14.0.

**Comment by ksaha79** [comment]
Tried to install statsmodels through local repo but still getting the error (see screenshot)
![Screenshot from 2023-04-22 01-12-15](https://user-images.githubusercontent.com/17918648/233764580-a8b8c4aa-cb4f-4b34-a266-fcf5f0ffc1a6.png)
