### ISSUE TITLE
BUG: OLSResults.mse_model gives needs to use `df_resid`

### ISSUE THREAD

**Issue by cltdouglas** [statsmodels/statsmodels#8370]
#### Describe the bug

According to:
https://www.statsmodels.org/devel/generated/statsmodels.regression.linear_model.OLSResults.mse_model.html

mse_model should be the explained sum of squares divided by the model degrees of freedom.

However, it reports the explained sum of squares instead.

#### Code Sample, a copy-pastable example if possible

```python
import statsmodels.api as sm
import numpy as np
duncan_prestige = sm.datasets.get_rdataset("Duncan", "carData")
Y = duncan_prestige.data['income']
X = duncan_prestige.data['education']
X = sm.add_constant(X)
model = sm.OLS(Y,X)
result = model.fit()

print("The OLSResults.mse_model is " + str(round(result.mse_model, 2)))

Yhat = result.predict(X)
ESS = ((Yhat - Y.mean()) ** 2).sum()
print("The Explained Sum of Squares (ESS) is " + str(round(ESS, 2)))
```

#### Outputs

```python
The OLSResults.mse_model is 13790.23
The Explained Sum of Squares (ESS) is 13790.23
```

#### Expected Output

The OLSResults.mse_model should be divided by the model degrees of freedom.

INSTALLED VERSIONS
------------------
Python: 3.8.8.final.0

statsmodels
===========

Installed: 0.13.2 (C:\Users\cltd\anaconda3\lib\site-packages\statsmodels)

**Comment by bashtage** [comment]
The relevant code is 

https://github.com/statsmodels/statsmodels/blob/36f2f823594bc11a92e8456c845291d3e1eee679/statsmodels/regression/linear_model.py#L1779-L1781

It looks like you only get the same when df model is 0.  Is that this case here?

**Comment by bashtage** [comment]
Thinking about this should it be `df_resid` so definitely a bug!
