### ISSUE TITLE
robust descriptive measures, skew, kurtosis

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#838]
I think we should add a descriptive module in robust or maybe in stats.
We have robust location and scale/variances but they are mainly in support of RLM

http://stackoverflow.com/questions/16569105/what-is-the-python-numpy-or-scipy-or-pandas-equivalent-for-rs-adjboxstats-fun

there are some papers on robust skew and kurtosis. 
medcouple for skewness

also there are some outlier robust hypothesis tests (e.g. gof tests)

**Comment by bashtage** [comment]
Probably closeable

**Comment by PavloFesenko** [comment]
@josef-pkt Could we close this old issue as completed by #1234? Wow, that's a really nice PR number. 😎

**Comment by josef-pkt** [comment]
ok, closing, we still have #3152 open for refactoring and more statistics or methods.
