### ISSUE TITLE
Add optional difference parameter to confint_proportions_2indep

### ISSUE THREAD

**Issue by r0f1** [statsmodels/statsmodels#8398]
Hi,

I have a feature request for [statsmodels.stats.proportion.confint_proportions_2indep](https://www.statsmodels.org/dev/generated/statsmodels.stats.proportion.confint_proportions_2indep.html).
The function should take an additional optional parameter, called `d=0`. When `compare='diff'`, `d` is used, otherwise it is ignored. `d` indicates the difference between the two proportions. The only change that is necessary is that the numerator for the z calculation has to include `d`. 

For a complete example [look at Example 9.4.2 from this text](https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Book%3A_Introductory_Statistics_(Shafer_and_Zhang)/09%3A_Two-Sample_Problems/9.04%3A_Comparison_of_Two_Population_Proportions).

**Comment by josef-pkt** [comment]
To clarify:

Is this is for the hypothesis test and not for the confidence interval of the difference in proportion?

for hypothesis test, the usual pattern for non-zero null hypothesis is that

p1 - p2 = value  
or
p1 - p2 - value = 0

but I have not seen this for confidence intervals for 2indep tests

**Comment by r0f1** [comment]
Oh, your are right. For the confidence interval it does not make sense. 
I retract my feature request. I did not know this function does what I want: [statsmodels.stats.proportion.test_proportions_2indep](https://www.statsmodels.org/dev/generated/statsmodels.stats.proportion.test_proportions_2indep.html#statsmodels.stats.proportion.test_proportions_2indep).
