### ISSUE TITLE
model refitting with new data is slow and worse ( according to AIC) than new data self-fitted model

### ISSUE THREAD

**Issue by holder-fo** [statsmodels/statsmodels#8448]
i am new to ARIMA, sorry if i asked silly questions. 
i am asuuming similar time series would have similar ARIMA parameters (verified by separately modeling with same orders) so i am interested in whether refitting new data by the model of similar data would result close model. so i assuming refitting with new data would be cost less time and has close AIC.
when i refitted a model with new data using fuctions such as [`statsmodels.tsa.statespace.mlemodel.MLEResults.apply`](https://www.statsmodels.org/v0.13.0/examples/notebooks/generated/statespace_sarimax_faq.html#Comparing-trends-and-exogenous-variables-in-SARIMAX,-ARIMA-and-AutoReg) with setting `refit=True`, it fits slow than the model fited by the new data itself and has greater AIC while refitted model and self-fitted model do have close but different parameters.  that is why i got confused.
is it normal or my assumption is supposed to be invalid in any cases?  i.e. the parameters of refitting model and self-fitted model should not be the same? why refitting model cost more time?
wish i can be enlightened by some opinions here since i don't know where to ask.

**Comment by ChadFulton** [comment]
Closing as answered, but feel free to follow up if you want.

**Comment by holder-fo** [comment]
@ChadFulton thanks for your meticulous reply! would you make clear the setting `copy_initialization=True` will do in the refitting process for me? cuz i find it consumed more time refitting and resulted a better model, where i don't know why.
