### ISSUE TITLE
Add fvalue for full model

### ISSUE THREAD

**Issue by amichuda** [statsmodels/statsmodels#8451]
```
            return np.nan
```

https://github.com/amichuda/statsmodels/blob/c74f4a6e3b593ad4c2ec4dc4adc1a36d8ab48cf4/statsmodels/regression/linear_model.py#L1853

Right now we don't fun a f-stat for the full model, but the statsmodels table has it. Setting it to `np.nan` for now.

**Comment by bashtage** [comment]
Is this meant to go somewhere else?

**Comment by amichuda** [comment]
crap sorry about that!
