### ISSUE TITLE
adfuller produces different results on different environments with the same package version

### ISSUE THREAD

**Issue by a-lapedriza** [statsmodels/statsmodels#8456]
I am testing the adfuller function using two dummy dataframes that I have created.
The issue is that the test results that I obtain are different depending on the python environment where I run the code. Even though both environments are using the same version of statsmodels: 0.13.2

These are my two environments:
Environment 1:
- python version 3.9.12
- statsmodels version: 0.13.2
- numpy version: 1.21.5

Environment 2: 
- python version 3.9.15
- statsmodels version: 0.13.2
- numpy version: 1.21.5

I have run the test with two different datasets:

#### Dataset 1
```python
df = pd.DataFrame({"col": [1, 2, 3, 4, 5, 6, 7, 8, 9]})

adfuller(x=df)
```
Result in environment 1:

> **(1.1180339887498951,**
>  **0.9953676342362803,**
>  1,
>  7,
>  {'1%': -4.9386902332361515,
>   '5%': -3.477582857142857,
>   '10%': -2.8438679591836733},
>  -405.9988338797049)

Result in environment 2:

> 'Test Statistic': **0.7637626158259737,**
> 'p-value': **0.9910281286393751,**
> '#Lags Used': 1,
> 'Number of Observations Used': 7,
> 'Critical Value (1%)': -4.9386902332361515,
> 'Critical Value (5%)': -3.477582857142857,
> 'Critical Value (10%)': -2.8438679591836733,

#### Dataset 2
```python
df = pd.DataFrame(
        {
            "col": [
                251064.5924,
                178825.0161,
                65131.7014,
                254312.3299,
                243780.0552,
                393430.7753,
                83366.63126,
                143035.8812,
                -96424.38399,
                -5269.937133,
                159459.7266,
                270159.8715,
                223785.704,
                12248.85007,
                124493.6028,
                117839.9412,
                57278.71767,
                38988.29718,
                -11041.85481,
                136584.2049,
                -25865.88434,
            ]
        }
    )

adfuller(x=df)
```
Result in environment 1:

> (**-3.132431821712342,**
>  0.024244342216463495,
>  0,
>  20,
>  {'1%': -3.8092091249999998, '5%': -3.0216450000000004, '10%': -2.6507125},
>  311.3865088322439)

Result in environment 2:

> 'Test Statistic': **-3.1324318217123426,**
> 'p-value': 0.024244342216463495,
> '#Lags Used': 0,
> 'Number of Observations Used': 20,
> 'Critical Value (1%)': -3.8092091249999998,
> 'Critical Value (5%)': -3.0216450000000004,
> 'Critical Value (10%)': -2.6507125,

**Comment by josef-pkt** [comment]
same issue as in #8450

perfect prediction, residual variance = 0 + noise

and numerical/floating point noise is not reproducible across different environments, operating system, linalg libraries.
and sometimes noise is not even reproducible on the same computer in several different runs.

You need to use a "well-defined" data set, not degenerate data

**Comment by josef-pkt** [comment]
closing as duplicate, and nothing to do
