### ISSUE TITLE
ERROR: Failed building wheel for statsmodels Failed to build statsmodels ERROR: Could not build wheels for statsmodels, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by CesarG2022** [statsmodels/statsmodels#8457]
#### Hello, may you give a hand with this issue: https://stackoverflow.com/questions/73126998/fix-error-with-skforecast-and-pyproject-toml-based-projects,
thanks in advance.

**Comment by KrishnanRaja** [comment]
Hi, I am also facing the same issue. Any help on this?

**Comment by bashtage** [comment]
Install Visual Studio Build Tools 2022.

https://visualstudio.microsoft.com/downloads

**Comment by KrishnanRaja** [comment]
Thanks for your inputs. I have already installed recommended tools in the VS build tools list. I am not sure which one I am missing. Please see the attached screen shot of the installation details. Am I missing anything in the list specific for this issue? . Sorry I am new to this one. FYI. I am using Windows 11. 
![VSbuild tools](https://user-images.githubusercontent.com/94841071/198049392-41483664-8be7-477d-8309-6a7d0693a2e0.jpg)

**Comment by NEGU93** [comment]
This configuration worked for me.

![image](https://github.com/statsmodels/statsmodels/assets/9558385/cb784de0-d175-4072-bb70-3ef219a03d93)

**Comment by bashtage** [comment]
I think I'm going to close this.  We have had a release since and there do not seem to be any specific problems with 0.14.
