### ISSUE TITLE
[Feature request]: Plots should return matplotlib Axes

### ISSUE THREAD

**Issue by xpcosmos** [statsmodels/statsmodels#8508]
# Context

Statsmodels provid some graphics that is hard to handcode, but at same time is hard to costumize, mainly because the return is a Figure insted a matplotlib Axes.

# Suggestion 
Would be nice to have some changes at the code so we can always have Axes to costumize and change labels, titles etc...

# Final consideration:
I don't know with there's some way to get a matplotlib Axes with the statsmodels.graphics functions, if so, I'm sorry.

Thank you for your time!

**Comment by bashtage** [comment]
I think we are unlikely to change this.

1. Jupyter likes figures for notebook display
2. You can always call `fig.get_axes()` to get a list of axes, so you could just do `sm.graphics.some_plot().get_axes()[0]` to get the `Axes`
3. You can also get it with `plt.gca()` immediately after producing a plot.
4. Some figures have more than 1 axes, so there is not obvious return there.

**Comment by josef-pkt** [comment]
(most/all ?) graphics function have an `ax` or `fig` keyword so that the user can provide a matplotlib axis, (or fig in multi axis plot)

**Comment by josef-pkt** [comment]
closing as won't fix, we will not change the returns of plot functions
