### ISSUE TITLE
fit_regularized penalizes the intercept

### ISSUE THREAD

**Issue by malekbensliman** [statsmodels/statsmodels#8510]
#### Describe the bug

When using `fit_regularized`, the current code does not exclude the intercept from the penalization procedure. Instead, the intercept is treated like all the other variables. This is an unexpected behavior since the intercept is typically excluded from the penalization as in Tibshirani (1996). As a comparison, both scikit-learn and glmnet (in R) exclude the intercept. Theoretically, excluding the intercept would be akin to having a uniform prior on the intercept (as opposed to a Laplace prior for lasso for instance). In addition, by excluding the intercept, the intercept would be equal to the mean of the dependent variable (as for OLS).

The bug seems to stem from [this line ](https://github.com/statsmodels/statsmodels/blob/27335040eb196eb06f68cf2e4425009e32d430e3/statsmodels/base/elastic_net.py#L156) which sets `init_args['hasconst'] = False`. This is in contradiction with the definition of `hasconst` described [here](https://github.com/statsmodels/statsmodels/blob/a2653604190223b5ec3f9b2335fc24438c22a3ab/statsmodels/base/model.py#L53-L57). 

#### Code Sample

```python
import statsmodels.api as sm

import numpy as np
import pandas as pd

np.random.seed(10)  

x = np.array([i*np.pi/180 for i in range(60,300,4)])
y = 1+np.sin(x) + np.random.normal(0,0.1,len(x))
df = pd.DataFrame(np.column_stack([x,y]),columns=['x','y'])
for i in range(2,16):
    colname = 'x_%d'%i
    df[colname] = df['x']**i
X=(df.drop('y',axis=1)-df.drop('y',axis=1).mean())/df.drop('y',axis=1).std()
X=sm.add_constant(X,prepend=True)
y=df['y']

elasticnet_lasso = sm.OLS(y,X,hasconst=True)
res=elasticnet_lasso.fit_regularized(alpha=1,L1_wt=1,refit=False)
(np.mean(y),res.params)
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `main`. If your problem has been fixed in an unreleased version, you might be able to use `main` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the main branch of this repository? It helps the limited resources if we know problems exist in the current main branch so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

In the code above, the intercept should be closer to `np.mean(y)=1.03`.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.9.10.final.0
OS: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.13.1 (/Users/malekbensliman/.pyenv/versions/3.9.10/envs/science-3.9.10/lib/python3.9/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.23.3 (/Users/malekbensliman/.pyenv/versions/3.9.10/envs/science-3.9.10/lib/python3.9/site-packages/numpy)
scipy: 1.9.1 (/Users/malekbensliman/.pyenv/versions/3.9.10/envs/science-3.9.10/lib/python3.9/site-packages/scipy)
pandas: 1.5.0 (/Users/malekbensliman/.pyenv/versions/3.9.10/envs/science-3.9.10/lib/python3.9/site-packages/pandas)
    dateutil: 2.8.2 (/Users/malekbensliman/.pyenv/versions/3.9.10/envs/science-3.9.10/lib/python3.9/site-packages/dateutil)
patsy: 0.5.2 (/Users/malekbensliman/.pyenv/versions/3.9.10/envs/science-3.9.10/lib/python3.9/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.6.0 (/Users/malekbensliman/.pyenv/versions/3.9.10/envs/science-3.9.10/lib/python3.9/site-packages/matplotlib)
    backend: module://matplotlib_inline.backend_inline 
cvxopt: 1.3.0 (/Users/malekbensliman/.pyenv/versions/3.9.10/envs/science-3.9.10/lib/python3.9/site-packages/cvxopt)
joblib: 1.2.0 (/Users/malekbensliman/.pyenv/versions/3.9.10/envs/science-3.9.10/lib/python3.9/site-packages/joblib)

Developer Tools
================

IPython: 8.5.0 (/Users/malekbensliman/.pyenv/versions/3.9.10/envs/science-3.9.10/lib/python3.9/site-packages/IPython)
    jinja2: 3.0.3 (/Users/malekbensliman/.pyenv/versions/3.9.10/envs/science-3.9.10/lib/python3.9/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.13.0 (/Users/malekbensliman/.pyenv/versions/3.9.10/envs/science-3.9.10/lib/python3.9/site-packages/pygments)
pytest: 6.2.5 (/Users/malekbensliman/.pyenv/versions/3.9.10/envs/science-3.9.10/lib/python3.9/site-packages/pytest)
virtualenv: 20.16.5 (/Users/malekbensliman/.pyenv/versions/3.9.10/envs/science-3.9.10/lib/python3.9/site-packages/virtualenv)

</details>

**Comment by josef-pkt** [comment]
I'm not sure about the details here.

However, most of our code does not try to special case the constant/intercept. The penalization code allows in general for a weight vector that can be used to exclude specific parameters from being penalized.

According to the docstring, this weight array is `alpha` (not my preferred name)

Try 
alpha = np.ones(len(params))
alpha[idx_constant] = 0
alpha *= alpha_actual

from the general pattern this should work, but I never tried it for elastic net

**Comment by malekbensliman** [comment]
Thanks for the very prompt response. I have tried it and it did work.

That being said, what was the original intention behind `hasconst`? Or does it mean that `hasconst` is a deprecated parameter?

**Comment by josef-pkt** [comment]
hasconst and similar constant detection is a pain for the code in statsmodels.

The only case where we really need hasconst is for rsquared in OLS. If there is no constant, then the null reference model is that y=0 instead of y is constant. This follows the definition of rsquared in other packages like R.
Related is that df_model does not count the constant, i.e. only slope coefficients. That also still causes many headaches, and hours and days for me to think about how to change the design for this. (may latest issue for redefining things #8481 )

In models other than linear regression models, we always assume that the null model is a constant only model, even if there is no constant, implicitly assuming hasconst is True.

**Comment by malekbensliman** [comment]
Thanks for the info and context!
