### ISSUE TITLE
`_get_predict_out_of_sample` of `arima_model.py` using `mu` rather than constant estimate for AR(1)

### ISSUE THREAD

**Issue by GabCaz** [statsmodels/statsmodels#8535]
I do not really understand what method `_arma_predict_out_of_sample` of `arima_model.py` does for an AR(1), X_t = c + phi . X _{t - 1} + eps_t, with a constant: it gives predictions as 
```
mu[0] + np.dot(arparams, endog[:p]) + np.dot(maparams,
                                                                resid[:q])
```
When estimating an AR(1) model, we can see the constant parameter we get from the estimation is different than mu[0] (it seems to correspond to trendparam). Therefore, the prediction is not \hat{X_{t + 1}} = \hat{c} + \hat{phi} . X _t.

Why so? Here is a piece of code that reproduces the problem:
```
    from statsmodels.tsa.arima_model import ARMA
    import numpy as np

    # make fictitious data
    # real_c = 0.2
    # real_phi = 0.5
    # eps = np.random.normal(size=20, scale=0.1)
    # x = list()
    # x.append(eps[0])
    # last = eps[0]
    # for e in eps[1:]:
    #     nxt = last * real_phi + real_c + e
    #     x.append(nxt)
    #     last = nxt
    # x = np.asarray(x)
    x = np.array(
        [0.07226045550599362, 0.17499720609284417, 0.26540865063734354, 0.36189636616065146, 0.18682181208476684,
         0.18848483816792744, 0.2695247373872263, 0.09378488912383867, 0.14296313802471344, 0.25120520204457436,
         0.39105040060396606, 0.37196146849342365, 0.5248806922878547, 0.4500054221587069, 0.33427899498639746,
         0.037612956377969076, 0.27519170167752754, 0.4167794907203916, 0.2765729740429892, 0.3536068819920684])
    model = ARMA(x, (1, 0)).fit()
    print(model.summary())
    print("Manual prediction: {}".format(model.params[0] + model.params[1] * x[-1]))
    print("Statsmodels prediction: {}".format(model.forecast()))
```

Results: 
Manual prediction: 0.4139821411606334
Statsmodels prediction: (array([0.30337294]), array([0.11695348]), array([[0.07414834, 0.53259755]]))

**Comment by ChadFulton** [comment]
However, the issue here is that `model.params[0]` is an estimate of the mean of the process, not of an intercept term.  In the code you are referencing, `mu` is the intercept, but it is computed using the estimate of the mean (see `_get_predict_out_of_sample`).  You will get matching answers if you also compute the intercept term:

```
mean = model.params[0]
phi = model.params[1]
intercept = mean * (1 - phi)
print("Manual prediction: {}".format(intercept + phi * x[-1]))
```

Please note that the old version of the ARIMA estimator from `arima_model.py` that you are referencing here was deprecated in version 0.12 and was removed in version 0.13. However, the same answer still applies to the current ARIMA estimator, since it also estimates the mean of the process rather than the intercept.

**Comment by GabCaz** [comment]
I see, thank you! I got confused by the docstring
```
    params : ndarray
        The parameters of the model. The order of variables is the trend
        coefficients and the `k_exog` exogenous coefficients, then the
        `k_ar` AR coefficients, and finally the `k_ma` MA coefficients.
```
as well as the naming `mu` for intercept. but now it makes sense. I should update the libraries some time...

Thanks!!

**Comment by ChadFulton** [comment]
Glad this worked out, and thanks for the feedback on the "const" name introducing confusion here.
