### ISSUE TITLE
Durbin-Watson statistic may be wrongly calculated in ols

### ISSUE THREAD

**Issue by dustyant** [statsmodels/statsmodels#8539]
#### Describe the bug

When I run an OLS model with a pandas dataframe that is not sorted by the regressor variable (X), then the Durbin-Watson statistic is incorrectly calculated. The statistic gets reported in result summary.
Perhaps, this happens because, before calculating the statistic, the residuals (result.resid) need to be sorted by the X variable. A line for sorting the residuals should be added.

#### Code Sample, a copy-pastable example if possible

```python

# Datafile is attached as CSV
import statsmodels.formula.api as smf
import pandas as pd
from statsmodels.stats.stattools import durbin_watson
XY = pd.read_csv("sampleXY.csv").set_index('dy') #file has been attached.
f = 'XY["yield"] ~ XY["MaxNDVI"] '

result = smf.ols(formula=f, data = XY).fit()
result.summary()
print(result.summary().tables[2].data[0][3])
#Note: DW = 0.590

DWdata = pd.DataFrame(XY.sort_values('MaxNDVI')['MaxNDVI'])
DWdata['resid'] = result.resid
durbin_watson(DWdata.resid)
#Note: DW = 1.712
```

#### Expected Output
Durbin-Watson statistic value should be 1.712, and not 0.590

<details>
[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
Python: 3.9.7.final.0
OS: Linux 5.15.0-52-generi
[sampleXY.csv](https://github.com/statsmodels/statsmodels/files/10097760/sampleXY.csv)
c #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64
byteorder: little
LC_ALL: None
LANG: en_IN

statsmodels
===========

Installed: 0.12.2

</details>
[sampleXY.csv](https://github.com/statsmodels/statsmodels/files/10097778/sampleXY.csv)

**Comment by bashtage** [comment]
DW is a time series autocorrelation statistic and assumes that the data are already time ordered.

**Comment by dustyant** [comment]
DW can be used for spatial autocorrelation as well as other situations. 

In my use case, I'm applying it to detect autocorrelation with regressors already in use in OLS. Further, it could be used to identify potential regressors if error is ordered by new regressor shows autocorrelation.

Flagging this for future users that may stumble upon this issue.

**Comment by josef-pkt** [comment]
We have other autocorrelation tests as standalone functions with p-values, that can be used with sorted residuals.
We don't have p-values for DW. 

https://www.statsmodels.org/dev/stats.html#module-statsmodels.stats.stattools
it looks like acorr_ljungbox and acorr_lm use residuals as argument and do not require a results instance.
