### ISSUE TITLE
Please release 0.13.6 without explicit upper bound on scipy

### ISSUE THREAD

**Issue by tschm** [statsmodels/statsmodels#8543]
When installing scipy and statsmodels (0.13.5) the installer would choose scipy 1.9.3 somewhat contradicting the weak inequality < 1.9 you seem to impose somewhere. poetry (for poetry 1.2.2) is breaking then at poetry export. I see that in your live version you dropped the upper bound already. Maybe you could just release it on pypi. Many thanks

**Comment by bashtage** [comment]
I think 0.14 should be within a couple of months, so a 0.13.6 is unlikely.

**Comment by Lucasje19** [comment]
I too face this combined issue where statsmodels states a dependency mismatch, and where poetry fails to export its requirements. Since a deployed application relies on this mechanism, we are looking for a workaround. A fixed and released version would be so welcome to mitigate the need of a workaround. 

Thanks so much!

**Comment by JohnGiorgi** [comment]
Also facing this exact issue, which is preventing us from exporting a requirements file which we need to install on a certain machine

**Comment by picciama** [comment]
Adding to @JohnGiorgi 's comment (https://github.com/statsmodels/statsmodels/issues/8543#issuecomment-1362947102) above: In case poetry add fails for you, (which for me is the case with poetry>1.3) make sure you have libopenblas-dev liblapack-dev installed for compiling (on a debian based system).

**Comment by leebs778** [comment]
hi! the workaround to install statsmodels from github works but it's adding a significant amount of time to various projects' build steps. Are there any estimates on how soon 0.13.6 might be released?

**Comment by aeturrell** [comment]
I'm also having problems caused by this, would be very appreciative of a fix!

**Comment by injuryholmes** [comment]
same problems. Would be grateful if there is a fix or new release.

**Comment by nathanaellprice** [comment]
Same problems. +1 for a fix!

**Comment by oakstreetrec** [comment]
Same problem

**Comment by bashtage** [comment]
@josef-pkt Do you think 0.14 is ready?

**Comment by josef-pkt** [comment]
I have one open PR with small fixes that showed up recently.
Otherwise I have been looking mainly at things for 0.15 and wasn't working on 0.14 anymore.

It would be great if you can release 0.14 or rc1 soon.
I will merge the remaining PR tomorrow.

**Comment by bashtage** [comment]
Can someone who uses poetry check that the 0.14.0rc0 release (which should be on PyPI shortly) fixes this issue?

**Comment by nathanaellprice** [comment]
Works for me!

- Added `statsmodels = "0.14.0rc0"` to dependencies in pyproject.toml
- `poetry export -o requirements.txt -f requirements.txt --without-hashes`
- `statsmodels==0.14.0rc0 ; python_version >= "3.8" and python_version < "3.9"` inserted into requirements.txt

Thank you @bashtage and others!
