### ISSUE TITLE
statsmodels - very small p values always rounded to zero

### ISSUE THREAD

**Issue by dhairya02** [statsmodels/statsmodels#8550]
#### Describe the bug

For some reason the `model.summary()` outputs including p-value have lower precision of at max 4 values after decimal which leads to rounding of some values to zero. Is there a way to avoid that or get this as a feature added to get higher precision values.\

**Comment by bashtage** [comment]
You can always use `res.pvalues` to get the full floating point value.  You can then format these as you want.

**Comment by dhairya02** [comment]
So if I have variables X, y
`X2 = sm.add_constant(X)`
`est = sm.OLS(y, X2)`
`est2 = est.fit()`
so est2.pvalues() would get me the result?

**Comment by dhairya02** [comment]
Also is there something similar for coef and se as well?

**Comment by anbai106** [comment]
> You can always use `res.pvalues` to get the full floating point value. You can then format these as you want.

This does not really work for me:

> md = smf.ols("dne ~ Age + Sex + DLICV + scanner_lateral_x_brain_position_f25756_2_0 + scanner_transverse_y_brain_position_f25757_2_0 + scanner_longitudinal_z_brain_position_f25758_2_0 + pheno", data=data)
> model = md.fit()
> scientific_notation="{:e}".format(model.pvalues[-1])
> print(scientific_notation)
> 0.000000e+00
