### ISSUE TITLE
TravisCI add matplotlib

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#859]
installing pandas with apt-get triggered an install of matplotlib, which errors because of a missing display backend.

If we want to enable matplotlib in the TravisCI test, then Matthew's proposes

"""
We use a X virtual frame buffer on Linux, as in :

```
xvfb-run --server-args="-screen 0 1024x768x24" nosetests --verbosity=3
--with-doctest dipy
```

https://groups.google.com/d/msg/pystatsmodels/_SxG6tIL3Rw/9lohqnYJ0yUJ

https://github.com/nipy/nibotmi/blob/master/master.cfg#L331

I think I remember getting this trick from one of Gael's posts,
"""

**Comment by jbrockmendel** [comment]
Is this still an issue?
