### ISSUE TITLE
Question: robust poisson regression implementation status

### ISSUE THREAD

**Issue by toshiakiasakura** [statsmodels/statsmodels#8599]
I am currently looking for how to implement robust poisson regression in Python. 
I found one article explaining the way to implement the robust poisson regression in R language using the similar method implemented in statsmodels. 
- [POISSON REGRESSION | R DATA ANALYSIS EXAMPLES](https://stats.oarc.ucla.edu/r/dae/poisson-regression/)

The following code creates the output in R, 
```R
library(sandwich)
p <- read.csv("https://stats.idre.ucla.edu/stat/data/poisson_sim.csv")
p <- within(p, {
  prog <- factor(prog, levels=1:3, labels=c("General", "Academic", 
                                                     "Vocational"))
  id <- factor(id)
})
summary(p)
summary(m1 <- glm(num_awards ~ prog + math, family="poisson", data=p))
cov.m1 <- vcovHC(m1, type="HC0")
std.err <- sqrt(diag(cov.m1))
r.est <- cbind(Estimate= coef(m1), "Robust SE" = std.err,
"Pr(>|z|)" = 2 * pnorm(abs(coef(m1)/std.err), lower.tail=FALSE),
LL = coef(m1) - 1.96 * std.err,
UL = coef(m1) + 1.96 * std.err)

r.est
```
![Screenshot from 2022-12-30 22-58-26](https://user-images.githubusercontent.com/20488884/210116786-c30d4874-980d-46da-83e1-604a89cbba80.png)

and here is the corresponding code in statsmodels. 
```python
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
data = pd.read_csv("https://stats.idre.ucla.edu/stat/data/poisson_sim.csv")
res = smf.poisson("num_awards ~ C(prog) + math", data=data).fit(cov_type="HC0")
res.summary()
```
![Screenshot from 2022-12-30 22-59-33](https://user-images.githubusercontent.com/20488884/210116831-8e8a88c6-2598-4817-82ed-60078f433334.png)

It seems the results from both codes are matched quite well. 
However, exploring the past threads about heteroscedasticity for poisson regression, for example
- [Standard Error differences Binomial Regression vs Poisson Regression](https://stats.stackexchange.com/questions/206452/standard-error-differences-binomial-regression-vs-poisson-regression)
- [ENH: handling cluster_weights, freq_weights in models, cov_type, moments, descriptive statistics](https://github.com/statsmodels/statsmodels/issues/7861)

I am afraid  even cov_type HC0 is correctly implemented or not. 
If you have time, could you explain the current implementation situation around heteroscedasticity of the poisson regression? 
What is the potential problem not covered by the current package, and what is currently firmly implemented?

**Comment by josef-pkt** [comment]
Cov-type hc0 is correctly implemented. Originally verified against Stata.
However the defaults for some small sample adjustments differ between Statsmodels and Stata and possibly other packages.

The issue on weights is for user specified weights.
Those, var_weights, freq_weights are currently only available for GLM, missing in discrete.

I can provide more details in a few days when I’m back from a skiing trip
