### ISSUE TITLE
Granger causality less significant with higher lags

### ISSUE THREAD

**Issue by alecrimi** [statsmodels/statsmodels#8607]
#### Describe the bug

Hi
I am trying some Granger Causality with statsmodels, and I have something significant for maxlags = 5, and then non-significant for maxlags = 10. I use them as iterators so in theory,  if I have something valid at lag = 5, even if I start at maxlags = 10, it shuold still work. But no, setting maxlags = 5 gives significant, setting maxlags=10 or 15 not anymore. How is this possible?

#### Code Sample, a copy-pastable example if possible

```python
!pip install statsmodels
import pandas as pd
import numpy as np

subject_file = "sub-101915_TS.txt"
time_series = np.genfromtxt(subject_file, delimiter='\t')[:,1:]
n_subjects = 1
primary =  time_series[:,7]
supplementary = time_series[:,54]
 
from statsmodels.tsa.stattools import grangercausalitytests
# Perform Granger-Causality test
max_lags = 10
ROIs = ['primary','supplementary']#['visual','somatomotor','eyes']
causal_mat = np.zeros((len(ROIs), len(ROIs)))

def find_causality(max_lags,seriesto,seriesfrom):
  pvals = []
  for x in range(n_subjects):
    print(x)
    # Check whether the first variable is caused by the second one
    #df = pd.DataFrame(list(zip(seriesto.loc[:,x], seriesfrom.loc[:,x])))
    df = pd.DataFrame(list(zip(seriesto, seriesfrom)))
    
    gc_res = grangercausalitytests(df, maxlag=max_lags)
    # Remove List and Dict
    gc_res_lags =  (gc_res[max_lags])
    unlisted_gc_res_lags = gc_res_lags[0]
    pval = unlisted_gc_res_lags['ssr_ftest'][1]
    pvals.append(pval)
    #print(pvals)
    avg_pval = np.mean(pvals)
  return avg_pval,pvals

# Use a for loop to iterate over the list
j_ind = 0
for ROI_i in ROIs:
  i_ind = 0
  for ROI_j in ROIs:
     avg_pval,pvals = find_causality(max_lags, locals()[ROI_i] ,locals()[ROI_j])
     causal_mat[i_ind, j_ind] = avg_pval
     i_ind = i_ind + 1
  j_ind = j_ind + 1

print(causal_mat)
causal_mat<0.05


```
 

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

INSTALLED VERSIONS
------------------
Python: 3.8.16.final.0
OS: Linux 5.10.147+ #1 SMP Sat Dec 10 16:00:40 UTC 2022 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.12.2 (/usr/local/lib/python3.8/dist-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.32 (/usr/local/lib/python3.8/dist-packages/Cython)
numpy: 1.21.6 (/usr/local/lib/python3.8/dist-packages/numpy)
scipy: 1.7.3 (/usr/local/lib/python3.8/dist-packages/scipy)
pandas: 1.3.5 (/usr/local/lib/python3.8/dist-packages/pandas)
    dateutil: 2.8.2 (/usr/local/lib/python3.8/dist-packages/dateutil)
patsy: 0.5.3 (/usr/local/lib/python3.8/dist-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.2.2 (/usr/local/lib/python3.8/dist-packages/matplotlib)
    backend: module://ipykernel.pylab.backend_inline 
cvxopt: 1.3.0 (/usr/local/lib/python3.8/dist-packages/cvxopt)
joblib: 1.2.0 (/usr/local/lib/python3.8/dist-packages/joblib)

Developer Tools
================

IPython: 7.9.0 (/usr/local/lib/python3.8/dist-packages/IPython)
    jinja2: 2.11.3 (/usr/local/lib/python3.8/dist-packages/jinja2)
sphinx: 1.8.6 (/usr/local/lib/python3.8/dist-packages/sphinx)
    pygments: 2.6.1 (/usr/local/lib/python3.8/dist-packages/pygments)
pytest: 3.6.4 (/usr/local/lib/python3.8/dist-packages)
virtualenv: Not installed

**Comment by bashtage** [comment]
It is an F test.  There is no guarantee that is you reject with one model that you will with a larger one.  In this case, the maximum lag length affects the sample size used to estimate the model since it needs to "hold back" that number of observations.  Hence you can get different results.

**Comment by bashtage** [comment]
FWIW you cannot run repeated tests and have meaningful results since the test size is not controlled in multiple testing.

**Comment by bashtage** [comment]
Closing as answered, but feel free to post if not clear.

**Comment by alecrimi** [comment]
Hi,
ok, but I am questioning the meaning of the iterator as Maxlag.
If it is a 'maxlags' if I put maxlag=15, it is not able to see the maxlag=5?
I am using it as iterator not setting the largest lag [maxlag]

**Comment by bashtage** [comment]
Suppose you have 100 observations.  When you set maxlag to 15, all tests are done with 85 observations since 15 are needed to fit the first observation.  When you set maxlag to 5, 95 are used in the test.  Basically you cannot directly compare tests with different maxlag values since the sample used to estimate the model and the parameter covariance differ.
