### ISSUE TITLE
Lowess regression appears to drop intercept

### ISSUE THREAD

**Issue by joshdempster** [statsmodels/statsmodels#8620]
#### Describe the bug

The smoothed endogenous values returned by statsmodels.nonparametric.smoothers_lowess.lowess are wrong. They are much too close to zero, and ignore any constant offset from zero in the endogenous variable. They look like the result I would expect if the offset term were dropped. I've confirmed that I get the expected result from R's lowess. Statsmodels 0.13.5

#### Code Sample, a copy-pastable example if possible

```python
from statsmodels.nonparametric.smoothers_lowess import lowess
import numpy as np
from matplotlib import pyplot as plt

test1 = np.random.normal(size=10000, scale=1)
test2 = test1**2 + np.random.normal(scale=1, size=10000)+10
smoothed = lowess(test1, test2, .1, is_sorted=False, return_sorted=False)

plt.scatter(test1, test2, s=10, alpha=.25, color="blue", label="original")
plt.scatter(test1, smoothed, s=2, color='red', label="lowess")
plt.legend()
```
![statsmodels_lowess](https://user-images.githubusercontent.com/17988358/211916133-5354ef5c-c9c4-4862-92db-d1eae4b2eca6.png)

#### Expected Output

I expect a reasonable match for the trend, with some bias in the tails, as shown using the tidyverse lowess in R:

![R_lowess](https://user-images.githubusercontent.com/17988358/211916193-515e283c-22a2-4810-871a-35ad33fce31a.png)

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.10.6.final.0
OS: Darwin 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.13.5 (/usr/local/lib/python3.10/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.23.3 (/usr/local/lib/python3.10/site-packages/numpy)
scipy: 1.9.1 (/usr/local/lib/python3.10/site-packages/scipy)
pandas: 1.5.0 (/usr/local/lib/python3.10/site-packages/pandas)
    dateutil: 2.8.2 (/usr/local/lib/python3.10/site-packages/dateutil)
patsy: 0.5.2 (/usr/local/lib/python3.10/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.6.0 (/usr/local/lib/python3.10/site-packages/matplotlib)
    backend: module://matplotlib_inline.backend_inline 
cvxopt: Not installed
joblib: 1.2.0 (/usr/local/lib/python3.10/site-packages/joblib)

Developer Tools
================

IPython: 8.5.0 (/usr/local/lib/python3.10/site-packages/IPython)
    jinja2: 3.1.2 (/usr/local/lib/python3.10/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.13.0 (/usr/local/lib/python3.10/site-packages/pygments)
pytest: 7.2.0 (/usr/local/lib/python3.10/site-packages/pytest)
virtualenv: 20.16.6 (/Users/dempster/Library/Python/3.10/lib/python/site-packages/virtualenv)

</details>

**Comment by josef-pkt** [comment]
I guess it's because you reversed x and y

`lowess(endog, exog, ...)`

try
`smoothed = lowess(test2, test1, .1, is_sorted=False, return_sorted=False)`

**Comment by joshdempster** [comment]
Yup, that was it. Thanks!
