### ISSUE TITLE
initial_level doesn't appear to be respected in ExponentialSmoothing class

### ISSUE THREAD

**Issue by mattwinkler** [statsmodels/statsmodels#8634]
#### Describe the bug

[A clear and concise description of what the bug is. This should explain **why** the current behaviour is a problem and why the expected output is a better solution.]

#### Code Sample, a copy-pastable example if possible

```python
from statsmodels.tsa.holtwinters import ExponentialSmoothing
series = [0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 0.0]
es = ExponentialSmoothing(
    series,
    initialization_method='known',
    initial_level=20.0
)
es_fit = es.fit()
es_fit.params
```

Outputs:
```python
{'smoothing_level': 1.4901161193847656e-08,
 'smoothing_trend': nan,
 'smoothing_seasonal': nan,
 'damping_trend': nan,
 'initial_level': 14.239682618110056,
 'initial_trend': nan,
 'initial_seasons': array([], dtype=float64),
 'use_boxcox': False,
 'lamda': None,
 'remove_bias': False}
```

<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `main`. If your problem has been fixed in an unreleased version, you might be able to use `main` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the main branch of this repository? It helps the limited resources if we know problems exist in the current main branch so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

`es_fit.params` should return 20.0 in the `initial_level` field

Additionally, when calling `es_fit.fittedvalues` I was expecting the first returned value to be 20.0

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
Python: 3.10.6.final.0
OS: Linux 5.10.147-133.644.amzn2.x86_64 #1 SMP Fri Oct 14 01:16:24 UTC 2022 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.13.2 (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/statsmodels)

Required Dependencies
=====================

cython: 0.29.32 (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/Cython)
numpy: 1.22.4 (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/numpy)
scipy: 1.9.3 (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/scipy)
pandas: 1.5.1 (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pandas)
    dateutil: 2.8.2 (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/dateutil)
patsy: 0.5.3 (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.6.1 (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/matplotlib)
    backend: module://matplotlib_inline.backend_inline 
cvxopt: Not installed
joblib: 1.2.0 (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/joblib)

Developer Tools
================

IPython: 7.33.0 (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/IPython)
    jinja2: 3.1.2 (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/jinja2)
sphinx: 5.3.0 (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sphinx)
    pygments: 2.13.0 (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pygments)
pytest: 7.2.0 (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pytest)
virtualenv: Not installed

</details>

**Comment by ChadFulton** [comment]
Thanks for the report.  In the meantime, you might consider using `ETSModel` which is the most recent/supported exponential smoothing model.
