### ISSUE TITLE
Theta model adding 1 to forecasts

### ISSUE THREAD

**Issue by grotmol** [statsmodels/statsmodels#8661]
#### Describe the bug

In the Theta model, with the default settings of `use_test=True` and `method='auto'`, the forecasts are 1 too high if the seasonality test determines that the time series doesn't have seasonality.

#### Root cause

The `forecast_components` method in ThetaModelResults checks if the method starts with "add", which it doesn't (because the method is "auto"), so it sets the seasonal components to ones:

```python
         if self.model.method.startswith("add"):
             season = np.zeros(steps)
         else:
             season = np.ones(steps)
```

The `forecast` method in ThetaModelResults checks if the method starts with "mul", which it doesn't, so it adds the seasonal components, which are all ones:

```python
         if self.model.deseasonalize:
             seasonal = np.asarray(comp.seasonal)
             if self.model.method.startswith("mul"):
                 fcast *= seasonal
             else:
                 fcast += seasonal
```

The reason this issue doesn't trigger all the time, is that the `_deseasonalize_data` method in ThetaModel changes the `method` attribute from "auto" to either "add" or "mul", depending on its choice. However, this doesn't happen if the `_has_seasonality` flag is False, as can be seen from this code:

```python
        if not self._has_seasonality:
            return self._y, np.empty(0)
        self._method = (
            "mul" if self._method == "auto" and self._y.min() > 0 else "add"
        )
```

**Comment by bashtage** [comment]
Thanks for closing this.
