### ISSUE TITLE
BUG: summary2 output does not include extra_text

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#8663]
random OLS model

```
model1.summary2().extra_txt
[]
model1.summary().extra_txt
'Notes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.'
```

If there is an extra text as in `summary_col`, then it is not included in the html output, but is included in print output.
https://github.com/statsmodels/statsmodels/pull/8658#issuecomment-1426013984

**Comment by lanzariel** [comment]
This looks like an issue of `RegressionResults`, a class in `regression.linear_model`.

The method `summary2` creates an instance of `iolib.summary2.Summary` but does not provide the variable `etext` that is provided when the analogous `summary.Summary` is called by `summary`.

I guess that `summary2.Summary` is worth fixing anyway. But I'm wondering how `summary2` (method) ended up in `RegressionResults`. I thought `iolib.summary2` was being used to compare the results of multiple regressions.
