### ISSUE TITLE
OLS P value not consistent with t value 

### ISSUE THREAD

**Issue by gavinkress** [statsmodels/statsmodels#8668]
After running a simple univariate linear regression using OLS I obtain the following model summary

![image](https://user-images.githubusercontent.com/62406542/218344585-07ad7c81-b68d-4505-a1dd-c7c48030b909.png)

The t value is consistent with the t value I calculate manually when I use the R-squared value given. However a |t| of 2.76 in no way corresponds to a p value of 0.010. I am not able to replicate the exact value obtained from model.pvalues using any number of degrees of freedom.  

The code I use to create this model is:

`model = sm.OLS(list(DF[ind]),sm.add_constant(list(DF[de]))).fit()`

where 

`list(DF[ind])` = [1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1]

and 

`list(DF[de])` = [7087.9, 5820.3, 5726.5, 5092.200000000001, 6391.8, 8094.1, 6491.1, 6852.700000000001, 7096.9, 7336.2, 6315.3, 5800.7, 6961.6, 6389.700000000001, 7977.0, 7199.799999999999, 7672.700000000001, 5165.8, 5243.7, 6628.2, 6309.6, 8531.7, 5336.9, 6744.6, 6522.7, 7255.200000000001, 6494.5, 4757.799999999999, 3726.5, 7140.3, 5000.799999999999]

The exact p value it gives is 0.009916977768826793 where according to that t-statistic it should be 0.11065255490834112.

The closest I can get to the given p value is using a DF of 10 which gives 0.010067636348152975 even though it seems as though the DF should just be 1, and given the coefficient of -0.002 it should certainly not be significantly different than 0.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

INSTALLED VERSIONS
------------------
Python: 3.11.1.final.0
statsmodels
===========
Installed: 0.13.5 (C:\Users\gavin\PycharmProjects\FTDNS\venv\Lib\site-packages\statsmodels)
Required Dependencies
=====================
cython: Not installed
numpy: 1.24.1 (C:\Users\gavin\PycharmProjects\FTDNS\venv\Lib\site-packages\numpy)
scipy: 1.10.0 (C:\Users\gavin\PycharmProjects\FTDNS\venv\Lib\site-packages\scipy)
pandas: 1.5.2 (C:\Users\gavin\PycharmProjects\FTDNS\venv\Lib\site-packages\pandas)
    dateutil: 2.8.2 (C:\Users\gavin\PycharmProjects\FTDNS\venv\Lib\site-packages\dateutil)
patsy: 0.5.3 (C:\Users\gavin\PycharmProjects\FTDNS\venv\Lib\site-packages\patsy)
Optional Dependencies
=====================
matplotlib: 3.6.3 (C:\Users\gavin\PycharmProjects\FTDNS\venv\Lib\site-packages\matplotlib)
    backend: module://backend_interagg 
cvxopt: Not installed
joblib: 1.2.0 (C:\Users\gavin\PycharmProjects\FTDNS\venv\Lib\site-packages\joblib)
Developer Tools
================
IPython: Not installed
    jinja2: 3.1.2 (C:\Users\gavin\PycharmProjects\FTDNS\venv\Lib\site-packages\jinja2)
sphinx: Not installed
    pygments: Not installed
pytest: Not installed
virtualenv: Not installed

**Comment by josef-pkt** [comment]
looks correct to me, and it's heavily unit tested against R and Stata

 ```
stats.t.sf(2.76, 29) * 2
0.009913185201085792
```
