### ISSUE TITLE
BUG: Typo in argument name for HAC standard errors

### ISSUE THREAD

**Issue by singaldhruv** [statsmodels/statsmodels#8698]
#### Issue summary

The argument name for HAC robust standard errors (located [here](https://github.com/statsmodels/statsmodels/blob/9046d59cf1220c739a7904c8d8487e155ef91be5/statsmodels/regression/linear_model.py#L2432)) should be `maxlags` rather than `maxlag`. HAC standard errors always throw up errors.

#### To reproduce
```python
import statsmodels
import statsmodels.api as sm
sm.OLS(endog_var, exog_vars).fit(cov_type='HAC').summary()
```

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

INSTALLED VERSIONS
------------------
Python: 3.9.6.final.0
OS: Linux 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.12.2 (/ENV_LOCATION/lib/python3.9/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.20.3 (/ENV_LOCATION/lib/python3.9/site-packages/numpy)
scipy: 1.6.2 (/ENV_LOCATION/lib/python3.9/site-packages/scipy)
pandas: 1.3.1 (/ENV_LOCATION/lib/python3.9/site-packages/pandas)
    dateutil: 2.8.2 (/ENV_LOCATION/lib/python3.9/site-packages/dateutil)
patsy: 0.5.1 (/ENV_LOCATION/lib/python3.9/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.4.2 (/ENV_LOCATION/lib/python3.9/site-packages/matplotlib)
    backend: module://matplotlib_inline.backend_inline 
cvxopt: Not installed
joblib: Not installed

Developer Tools
================

IPython: 7.26.0 (/ENV_LOCATION/lib/python3.9/site-packages/IPython)
    jinja2: 3.1.2 (/ENV_LOCATION/lib/python3.9/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.8.0 (/ENV_LOCATION/lib/python3.9/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed

**Comment by singaldhruv** [comment]
Suggestion: In absence of any supplied number of lags, the HAC optimal rule of [Andrew (1991)](https://www.jstor.org/stable/2938229) could be used: $0.5 T^{1/3}$.

**Comment by josef-pkt** [comment]
same spelling mistake for hac-panel

both have correct "maxlags" in base.covtype.get_robustcov_results

**Comment by josef-pkt** [comment]
Thanks for the report
I fixed the doc string, but did not (yet) add any default for maxlags.
