### ISSUE TITLE
References for Copula Algorithms

### ISSUE THREAD

**Issue by cooper-mj** [statsmodels/statsmodels#8714]
I'm currently working on a copula modelling project, and I'm hoping to better understand the origins of some of your implementation decisions in this package.

Specifically, I'm looking at the `FrankCopula` and `ClaytonCopula` classes within [archimedean.py](https://github.com/statsmodels/statsmodels/blob/main/statsmodels/distributions/copula/archimedean.py), and I'm unclear about the algorithm that is used to generate the random samples when `rvs` is called. I'm primarily familiar with the [conditional distribution method](https://math.stackexchange.com/a/2696874) discussed in Nelson (2006), and I'm not quite seeing the connection between this method and the implementation you provide. I'd appreciate it if you could explain these connections to me, or point me to a reference that does.

**The Frank Copula:**
From the code, I see that the Frank copula implements the following equation, where $x$ is sampled from a uniform distribution, and $v$ is sampled from a transformed logarithmic series distribution:

$\frac{-1}{\theta} \log\left(1 + \exp \left(-(\frac{\log(x)}{v})\right) \left(\exp(-\theta) - 1\right)\right)$

Is this an example of the conditional distribution method I've linked above, or are you using a different method? If the method is different, could you please provide a couple more details to help me understand why this formula faithfully implements sampling from the Frank copula?

**The Clayton Copula:**

My question is largely the same for the Clayton copula - I'm not quite making the link between the procedure you implement (sampling $x$ uniformly, sampling $v$ from a transformed gamma distribution, and then applying one further transformation to $x$ and $v$), and the conditional distribution method to sample from the Clayton copula. Any further details on the algorithm you could provide would be greatly appreciated.

Thanks so much! (And thanks for all your hard work building this package - this is an outstanding piece of work!)

**Comment by josef-pkt** [comment]
I just went through this for #8642, but already lost the reference again
AFAIR, it was in the joe book
more details in articles by Hofert and co-authors

generic form is
`rvs = self.transform.inverse(- np.log(x) / v, th)`

There are 3 ways for sampling archimedean copulas. The one we use is only valid only for (totally) monotonic copulas, i.e. positive correlation.

**Comment by josef-pkt** [comment]
https://github.com/statsmodels/statsmodels/issues/7258#issuecomment-1408703000
sampling from archimedean
Joe 2014 p. 272, 273

**Comment by cooper-mj** [comment]
This is extremely helpful, thank you!
