### ISSUE TITLE
Weights for exogenous variables in SARIMAX model

### ISSUE THREAD

**Issue by mowgliamu** [statsmodels/statsmodels#8719]
Hello Everyone,

I would like to build a SARIMAX model where I am able to assign weights to my exogenous variables, something like this if I have two exogenous variables:

```
import pandas as pd
import statsmodels.api as sm

# Load the data
data = pd.read_csv('data.csv', index_col='date', parse_dates=True)

# Define the weights for the exogenous variables
weights = [1, 0.5] 

# Define the SARIMAX model with weighted exogenous variables
model = sm.tsa.SARIMAX(data['y'], exog=data[['x1', 'x2']], order=(1,0,1), seasonal_order=(1,0,1,12), exog_weights=weights)
# Fit the model 
results = model.fit()
# Print the summary
print(results.summary())
```

However, this doesn't seem to do anything! I tried to play around with the weights but it doesn't do anything! I also passed `exog_weights` to the `fit()` function instead of SARIMAX object, but to no avail.

Any idea how can we incorporate weights to exogenous variables in SARIMAX? Thanks!

**Comment by ChadFulton** [comment]
`exog_weights` is not supported by SARIMAX.

**Comment by bashtage** [comment]
If you multiply your exog by the weights, which must be weight per observation, you will get estimates as if exog weights have been applied.

**Comment by josef-pkt** [comment]
invalid keywords does not raise an exception?

(I changed GLM and discrete models to raise exceptions with invalid keyword in `__init__`)

**Comment by mowgliamu** [comment]
@bashtage: Thanks! This seems a good workaround. I tried it, and it doesn't seem to affect the AIC score at all. However, it does change the MAE/MAPE.

@josef-pkt: Yes, indeed! I was a bit surprised by this.
