### ISSUE TITLE
Wildly different answers replicating a GEE model from SPSS

### ISSUE THREAD

**Issue by jjsakon** [statsmodels/statsmodels#8720]
#### Describe the bug

I'm attempting to replicate a GEE model in statsmodels from a published paper that used SPSS (https://pubmed.ncbi.nlm.nih.gov/33279717/). I am getting very different answers for what seems like the same input structure. I even signed up for a free trial of SPSS and can confirm SPSS gives the answers reported in the paper.

The input matrices are being loaded from the same .csv (and I filter using pandas to achieve the same dataframe as in SPSS).

#### Code Sample, a copy-pastable example if possible

```SPSS
USE ALL. 
COMPUTE filter_$=(BehTaskNum = 1 or BehTaskNum = 2 or (BehTaskNum = 3 and  BlockNumber = 6)).  
FILTER BY filter_$. 
EXECUTE.
GENLIN DifferenceScore BY White Right (ORDER=ASCENDING) 
  /MODEL White Right White*Right INTERCEPT=YES 
 DISTRIBUTION=NORMAL LINK=IDENTITY 
  /CRITERIA SCALE=MLE PCONVERGE=1E-006(ABSOLUTE) SINGULAR=1E-012 ANALYSISTYPE=3(WALD) CILEVEL=95 
    LIKELIHOOD=FULL 
  /REPEATED SUBJECT=participantID SORT=YES
    CORRTYPE=EXCHANGEABLE ADJUSTCORR=YES COVB=ROBUST MAXITERATIONS=1000 PCONVERGE=1e-006(ABSOLUTE) 
    UPDATECORR=1 
  /PRINT CPS DESCRIPTIVES MODELINFO FIT SUMMARY SOLUTION.
```
```python
fam = sm.families.Gaussian(link=sm.families.links.identity)
ind = sm.cov_struct.Exchangeable()
GEE_model = smf.gee("DifferenceScore ~ White * Right", groups="ParticipantID",
                data=stim_df_with_facename,cov_struct=ind, family=fam)
stim_model_out = GEE_model.fit(maxiter=1000)
stim_model_out.summary()
```
SPSS results:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/29741844/222989361-34f313c6-b734-4a8b-af11-4d92265a0643.png">

statsmodel results:
<img width="233" alt="image" src="https://user-images.githubusercontent.com/29741844/222990165-e16ebe3f-98fc-4720-bf17-a0ff1498eee6.png">

The results aren't even close (seems statsmodels isn't converging--and I've tried up to 10000 iterations but get the same result). I should point out if I run a model with an additional predictor (White*Right+Macro) the results are closer...but still quite a bit different:
SPSS results:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/29741844/222990424-0acc50a6-85a8-4e02-8720-c4b72bd7880f.png">

statsmodel results:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/29741844/222990456-005431f9-cc72-44f6-81c3-c18a665847d0.png">

Thanks for the help--spent a lot of time on this. I'm much more familiar with Mixed Effect models...but trying those in statsmodels were not replicating the GEE results either (even though in principle they should be similar).

**Comment by kshedden** [comment]
SPSS uses 1 as the reference category so the results are not easy to compare by eye.  Is there a link to the data?

**Comment by jjsakon** [comment]
Data is here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7855810/#SD1

To get the dataframe to select the same data as in the paper (and as in that SPSS model in the Supplementary) need to do this:
```
stim_df_with_facename = pd.read_csv('/NIHMS1651820-supplement-2.csv')
stim_df_with_facename = stim_df_with_facename[((stim_df_with_facename.BehavioralTask!='FaceNameAssociativeMemory') | \
                                               (stim_df_with_facename.BlockNumber==6))] # for Mankin paper only block 6 of FaceName was used
```

**Comment by jjsakon** [comment]
![image](https://user-images.githubusercontent.com/29741844/223008385-b63e48ba-f5c1-498a-a267-57d4332a07bb.png)
My best guess is SPSS does some kind of fancy nesting by default? The Within-subject the authors of that paper defined in SPSS ('WITHINSUBJECT=SessionNumber*BlockNumber*BehTaskNum') didn't actually change anything. But 'SORT=YES' does. I don't even think I can set up such nesting in statsmodels while also using cov_struct=sm.cov_struct.Exchangeable()? Since I'd have to use cov_struct = sm.cov_struct.Nested().

**Comment by josef-pkt** [comment]
Can you try using independence covariance and redefine to nonwhite = 1 - white and left = 1-right?
or maybe use ORDER=DESCENDING in SPSS if that reverses the reference level.

One possible problem  for convergence might be cluster size = 1. I don't know how that is handled in GEE. 

In exchangeable covariance, the within subject ordering does not matter. So it's unlikely that that is a problem.

**Comment by kshedden** [comment]
On my system it converges (`stim_model_out.converged` is True).  Reverse coding gives this:

```
Intercept             0.1122      0.033      3.382      0.001       0.047       0.177
WhiteRev             -0.1285      0.048     -2.651      0.008      -0.223      -0.033
RightRev             -0.1224      0.039     -3.103      0.002      -0.200      -0.045
WhiteRev:RightRev     0.1104      0.057      1.933      0.053      -0.002       0.222
```

The agreement with SPSS is pretty good but not perfect.  Our testing is mainly against R (geepack) and Stata.  In R I get the following:

```
 Coefficients:
                    estimate     san.se      wald            p
(Intercept)        0.1122143 0.03119592 12.938997 0.0003218074
WhiteRev          -0.1284774 0.04359578  8.684900 0.0032085724
RightRev          -0.1223723 0.03803062 10.353788 0.0012920925
WhiteRev:RightRev  0.1103854 0.05304662  4.330202 0.0374418121
```

So the geepack and statsmodels coefficient estimates agree to 4 decimal places.  The differences in SE are probably due to difference scaling factors in the covariance estimates.  I once worked things out so that we can get perfect agreement with Stata (see the docs on the scaling_factor argument to `fit`).

**Comment by jjsakon** [comment]
Thanks a lot for the help Josef and Kerby. I hadn't considered the reverse coding and I'm glad it's not just a within-subject issue. The next step will be seeing how different the GEE is from the ME model :)

**Comment by jjsakon** [comment]
After reverse coding the variables to match SPSS, strangely on my system (I just updated to statsmodels 0.13.5 in a brand new env to be sure) I can match the coefficients to 2 decimal places but the SEs are much higher than what you show:
```
coef | std err | z | P>\|z\| | [0.025 | 0.975]
-- | -- | -- | -- | -- | --
0.1117 | 0.690 | 0.162 | 0.871 | -1.242 | 1.465
-0.1273 | 0.647 | -0.197 | 0.844 | -1.396 | 1.141
-0.1252 | 1.155 | -0.108 | 0.914 | -2.388 | 2.138
0.1123 | 2.922 | 0.038 | 0.969 | -5.614 | 5.839
```
and `stim_model_out.converged` is False.

In any case, when I change the cov_struct to Independence the statsmodels coefficients match SPSS coefficients exactly. The GEE w/ Independence coefficients also match the coefficients for the statsmodels Mixed Model almost exactly (the fact that these were not close before was my first red flag). Indeed, I originally posted this on [Cross Validated](https://stats.stackexchange.com/questions/608477/wildly-different-answers-replicating-a-gee-model-from-spss/608487#608487) as well, and Thomas Lumley was kind enough to take a look and thinks the issue is that the exchangeable model isn't stable for this dataset.

The code is the same as above, but just in case:
```
fam = sm.families.Gaussian(sm.families.links.identity())
ind = sm.cov_struct.Exchangeable()
GEE_model = smf.gee("DifferenceScore ~ White * Right", groups="ParticipantID",
                data=stim_df_with_facename,cov_struct=ind, family=fam)
stim_model_out = GEE_model.fit(maxiter=10000)
```

**Comment by jjsakon** [comment]
Going to close this since it seems like a data-dependent problem. Even though the exchangeable models did not match between SPSS and statsmodels, since the latter did not converge and the working correlation appears unreliable, statsmodels outputs were frankly better than SPSS (which does not indicate convergence AFAIK).
