### ISSUE TITLE
halton sequences

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#875]
http://elsa.berkeley.edu/Software/abstracts/train0196.html
the last paper K. Train, 1999, "Halton Sequences for Mixed Logit." Working paper
mentions that 

"In fact, with 125 Halton draws, he found the simulation error to be half as large as with 1000 random draws and smaller than with 2000 random draws."

for simulated likelihood models, e.g. mixed logit

I have a draft version for Halton sequences.

**Comment by tupui** [comment]
Can be closed, this is integrated in tools and now in SciPy.
