### ISSUE TITLE
statsmodels.api and statsmodels.formula.api give sum of squares that are different from manual computation from scratch

### ISSUE THREAD

**Issue by JinDepot** [statsmodels/statsmodels#8766]
#### Describe the bug

There is a discrepancy, only for one of the two given factors, between the sum of squares value from the statsmodels.api's anova_lm() function and  the manual computation results. (That is, sum of squares is the same for both statsmodel.api.anova_lm() and manual computation for one of the two given factors)

#### Code Sample, a copy-pastable example if possible

Below is my code computing sum of squares:
```python
import pandas as pd

p, q = len(pd.unique(df.category1)), len(pd.unique(df.category2))
n1, n2 = df.groupby('category1').size(), df.groupby('category2').size()

y_groupmean1, y_groupmean2 = df.groupby('category1')['feature'].mean(), df.groupby('category2')['feature'].mean()
y_totalmean = df['feature'].mean()
y_group12 = df.groupby(['category1','category2'])['feature']

ss_b1, ss_b2 = sum(n1*(y_groupmean1 - y_totalmean)**2), sum(n2*(y_groupmean2 - y_totalmean)**2)
ss_e = sum([sum((df['feature'][(df['category1']==f'G{i}') & (df['category2']==f'H{j}')] - y_group12.get_group((f'G{i}',f'H{j}')).mean())**2) for i in range(p) for j in range(q)])

ss_t = sum((df['feature']-y_totalmean)**2)

ss_i = ss_t-ss_b1-ss_b2-ss_e
```

Then, I checked my results against Python statsmodels package by using codes below:
```python
import statsmodels.api as sm
from statsmodels.formula.api import ols

model = ols('feature ~ C(category1) + C(category2) + C(category1):C(category2)', data=df).fit()
sm.stats.anova_lm(model, type=2)
```

#### Expected Output
Here is the ANOVA table using my codes:
<img width="305" alt="anova1" src="https://user-images.githubusercontent.com/9698083/229427162-260c1ebf-d474-45eb-9b1b-2d706cbd55a7.png">

Here's the ANOVA table statsmodel returns:
<img width="401" alt="anova2" src="https://user-images.githubusercontent.com/9698083/229427369-1a50e53a-98c8-4a8d-af87-5230433b22b2.png">

As you can see, while statsmodels yields the same results as mine for the first factor's and the residual sums of squares, there is a small yet clear discrepancy between sum of squares for the second categorical variable, hence resulting in different sum of squares for the interaction.

I think it is really weird that statsmodels gives different results for only one of the two factors as compared to my computation, since I use basically the same formula to calculate sum of squares for both factors. Can anyone help me figure out why these discrepancies occur?

Thank you!

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.9.13.final.0
OS: Linux 5.4.0-60-generic #67~18.04.1-Ubuntu SMP Tue Jan 5 22:01:05 UTC 2021 x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

</details>

**Comment by josef-pkt** [comment]
Is this a balanced sample, all cell sizes the same?
In unbalanced anova, the variance decomposition does not really make sense because the effects are not orthogonal.

Try Helmert coding.

I don't know what's going on (besides differences in unbalanced anova), I never looked at how type 2 anova in calculated in anova_lm.
(I prefer `wald_test_terms` because there I know what the hypothesis mean and the theory behind them.)

**Comment by JinDepot** [comment]
Thanks for your comment!

The objective of computing sums of squares from scratch is to implement and execute two-way ANOVA under the environment where only pandas package is allowed, and I rely on statsmodels to check the reliability of my computations. Hence, it is more important for me that my computations return results consistently aligning with those of statsmodels, rather than carrying out appropriate variance analysis fit for the given data.  The data I test my codes' results against statsmodel is toy data anyway. In this light, I'm afraid Helmert coding won't resolve my issue.

I ran additional tests and switched the order of factor variables in the ols estimation, and the results show that the factor appearing first in the estimation equation, as well as the residuals, matches manually computed sum of squares.

Manual computation results are as following:
<img width="305" alt="anova1" src="https://user-images.githubusercontent.com/9698083/229686556-8fdaa558-850a-4620-a83d-0db8a384aff3.png">

And here is the result putting category1 first in the ols estimation equation, as in the following codes:
```python
import statsmodels.api as sm
from statsmodels.formula.api import ols

model = ols('feature8 ~ C(category1) + C(category2) + C(category1):C(category2)', data=df).fit()
sm.stats.anova_lm(model, type=2)
```
<img width="401" alt="anova2" src="https://user-images.githubusercontent.com/9698083/229686767-705b4cdd-b676-46b3-be48-000d18af1b7d.png">

Finally, here is the result from placing category2 first in the ols estimation equation, as appearing in the following codes:
```python
model = ols('feature8 ~ C(category2) + C(category1) + C(category1):C(category2)', data=df).fit()
sm.stats.anova_lm(model, type=2)
``` 
<img width="394" alt="anova3" src="https://user-images.githubusercontent.com/9698083/229687045-5bb08033-053a-4614-88db-feaa6337a27e.png">

As you can see, only the factor appearing first in the [statsmodels.formula.api.ols] and the residual match the manual compuation results in terms of sums of squares.

Do you think sample imbalance is causing these? I have no idea behind this, so any input will be greatly appreciated.
Thanks again for looking into this!
