### ISSUE TITLE
BUG/TST: recursive_ls test failures, pandas incompatibility

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#8775]
recursive_ls has been failing for some time, first in pre and now in many environments which seem all to use pandas 2.0.0

AFAICS, the problem is with indexing into dataframe.values in 
https://github.com/statsmodels/statsmodels/blob/main/statsmodels/regression/recursive_ls.py#L99
`endog.values[:, 1:] = self._q_matrix[:, 0]`

It looks like this is not an inplace assignement anymore.

If I replace the affine constraint by a linear constraint in test_constraints_stata, then I get the same results as in the failing unit tests
`mod = RecursiveLS(endog, exog, constraints='m1 + unemp = 0')`
instead of `mod = RecursiveLS(endog, exog, constraints='m1 + unemp = 1')`

However, I don't know how to fix this.
I tried replacing indexing with `values` by `iloc`, but I did not get it to work with pandas 1.4.0 (my current dev environment.

**Comment by josef-pkt** [comment]
@ChadFulton @bashtage 

any ideas how to fix this.

(I also don't really understand what that assignment is supposed to do and what shapes it is supposed to support.)

**Comment by ChadFulton** [comment]
Thanks, and sorry I didn’t see these test failures earlier! I’ll take a look tomorrow

**Comment by bashtage** [comment]
Closed in favor of #8793
