### ISSUE TITLE
DOC: period in seasonal decompose is confusing, should be periodicity.

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#8778]
`period` sounds like it's the unit for one datetime or time period observation. as used in pandas

AFAIU, seasonal decompose needs length of a cycle, periodicity

I got confused looking at the seasonal decompose docstring to comment on
https://stackoverflow.com/questions/75954402/seasonal-decompose-you-must-specify-a-period-or-x-must-be-a-pandas-object-with

**Comment by bashtage** [comment]
The definition of periodicity shows it does not match the intent either

the quality or character of being periodic; the tendency to [recur](https://www.google.com/search?biw=2327&bih=1172&sxsrf=APwXEddlNuV5oTKGxZZv2iYkkez7JoRghw:1682326428637&q=recur&si=AMnBZoGP34IVl-vQ5XB3AyP2dfbgXHrMwCdqXaQd7gc6JbZNLXvHL4BYMJAwgHcpALgtGJkYZ60_DfYg6xpZCdeJY9KPiHovpQ%3D%3D&expnd=1) at intervals.
"the periodicity of the sunspot cycle"
