### ISSUE TITLE
Scale parameter of AutoReg model

### ISSUE THREAD

**Issue by fast-90** [statsmodels/statsmodels#8837]
I have noticed that the `scale` parameter for the `AutoReg` model is calculated by dividing the sum of squared residuals by the number of observations (see [here](https://www.statsmodels.org/dev/_modules/statsmodels/tsa/ar_model.html#AutoRegResults.sigma2)), whilst for an `OLS` model the `scale` parameter is calculated as the sum of squared residuals divided by the degrees of freedom (see [here](https://www.statsmodels.org/stable/_modules/statsmodels/regression/linear_model.html#RegressionResults.scale)).

Is this intentional, and if so can someone explain me why?

During my studies (which was a long time ago), I remember being that the scale should be calculated using the degrees of freedom rather than number of observations (i.e. the way it is calculated for an `OLS` model), and I believe it is also the number I need for the problem I am working on. Of course I could calculate the AR(x) model using the `OLS` class by transforming my data a little bit and creating the lagged series myself, but it defeats the purpose of having `AutoReg`, which I would rather use if it is available anyways.

Can someone help me understand the difference? I believe the question should be clear from the two links with source code I provided above, however I can provide some sample code and results if needed.

**Comment by bashtage** [comment]
Autoregression and inference are based on asymptotic results, and so it is not common to make finite sample adjustments.  THe finite sample adjustments are only really required when performing exact inference assuming errors are normal in a cross-sectional regression.
