### ISSUE TITLE
Seven Python syntax errors in forward annotations

### ISSUE THREAD

**Issue by cclauss** [statsmodels/statsmodels#8840]
#### Describe the bug

% `ruff --select=F722 .`
```
Error: statsmodels/tsa/ardl/model.py:335:42: F722 Syntax error in forward annotation: `raise`
Error: statsmodels/tsa/ardl/model.py:873:34: F722 Syntax error in forward annotation: `raise`
Error: statsmodels/tsa/ardl/model.py:1382:30: F722 Syntax error in forward annotation: `raise`
Error: statsmodels/tsa/ardl/model.py:1763:42: F722 Syntax error in forward annotation: `raise`
Error: statsmodels/tsa/ardl/model.py:1948:59: F722 Syntax error in forward annotation: `raise`
Error: statsmodels/tsa/ardl/model.py:2096:34: F722 Syntax error in forward annotation: `raise`
Error: statsmodels/tsa/tsatools.py:299:43: F722 Syntax error in forward annotation: `in`
Error: Process completed with exit code 1.
```

#### Code Sample, a copy-pastable example if possible

```python
# Your code here that produces the bug
# This example should be self-contained, and so not rely on external data.
# It should run in a fresh ipython session, and so include all relevant imports.
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `main`. If your problem has been fixed in an unreleased version, you might be able to use `main` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the main branch of this repository? It helps the limited resources if we know problems exist in the current main branch so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

</details>

**Comment by bashtage** [comment]
This looks wrong as far as I can tell;  It seems to not like the literal "raise".

**Comment by bashtage** [comment]
Closing as spurious.
