### ISSUE TITLE
DOC Broken link to Seasonal Decomposition example notebook + typo in STLForecast docstring

### ISSUE THREAD

**Issue by pierre-haessig** [statsmodels/statsmodels#8855]
I just came across two issues in the stable online doc:

- many links to the notebook [stl_decomposition.ipynb](https://github.com/statsmodels/statsmodels/blob/main/examples/notebooks/stl_decomposition.ipynb) are broken: https://www.statsmodels.org/stable/examples/notebooks/generated/stl_decomposition.html
  - in Examples homepage: https://www.statsmodels.org/stable/examples/index.html#time-series-analysis ([Exponential Smoothing](https://www.statsmodels.org/stable/examples/notebooks/generated/exponential_smoothing.html) broken as well)
  - in https://www.statsmodels.org/stable/generated/statsmodels.tsa.forecasting.stl.STLForecast.html
  - in https://www.statsmodels.org/stable/generated/statsmodels.tsa.seasonal.STL.html#statsmodels.tsa.seasonal.STL
- At the bottom of [statsmodels.tsa.forecasting.stl.STLForecast](https://www.statsmodels.org/stable/generated/statsmodels.tsa.forecasting.stl.STLForecast.html#statsmodels-tsa-forecasting-stl-stlforecast) documentation, the code for the last example (*Generate forecasts from an Exponential Smoothing model with trend*) doesn't render:

![image](https://user-images.githubusercontent.com/1010404/235624603-6e03270e-1d2b-43df-b4b0-63fc9d49d373.png)

Perhaps a blank line should be added in the docstring of class `STLForecast` (line 142 https://github.com/statsmodels/statsmodels/blob/main/statsmodels/tsa/forecasting/stl.py#L142) ?

**Comment by bashtage** [comment]
Thanks for reporting.  These should all be fixed in the dev docs: https://statsmodels.org/devel/

They will be fixed in stable once 0.14 is out next week.
