### ISSUE TITLE
Release 0.14

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#8864]
This is a tracking thread for any blockers for 0.14 release.  If there are no blockers, I plan to release on Friday.

**Comment by JMMarchant** [comment]
```
#16 165.5       running build_ext
#16 165.5       building 'statsmodels.tsa.stl._stl' extension
#16 165.5       creating build/temp.linux-x86_64-cpython-39
#16 165.5       creating build/temp.linux-x86_64-cpython-39/statsmodels
#16 165.5       creating build/temp.linux-x86_64-cpython-39/statsmodels/tsa
#16 165.5       creating build/temp.linux-x86_64-cpython-39/statsmodels/tsa/stl
#16 165.5       x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DCYTHON_TRACE_NOGIL=0 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/tmp/pip-build-env-youeg5xd/overlay/lib/python3.9/site-packages/numpy/core/include -I/tmp/pip-build-env-youeg5xd/overlay/lib/python3.9/site-packages/numpy/core/include -I/home/appuser/venv/include -I/usr/include/python3.9 -c statsmodels/tsa/stl/_stl.c -o build/temp.linux-x86_64-cpython-39/statsmodels/tsa/stl/_stl.o
#16 165.5       error: command 'x86_64-linux-gnu-gcc' failed: No such file or directory
#16 165.5       [end of output]
#16 165.5   
#16 165.5   note: This error originates from a subprocess, and is likely not a problem with pip.
#16 165.5   ERROR: Failed building wheel for statsmodels
```

We're seeing the following build error when trying to pip install the latest version in a Ubuntu Docker container; any insight?

**Comment by bashtage** [comment]
Do you hav Cython installed?

**Comment by bashtage** [comment]
Shouldn't be required but there could be a packaging issue.

**Comment by pashkov-v** [comment]
Trying to install the latest version in a fresh virtual environment with `pip install statsmodels`, it takes a really long time to do so. It seems like pip is building wheels for statsmodels. The system is Ubuntu 18.04.4, Python 3.8.

**Comment by bashtage** [comment]
> We're seeing the following build error when trying to pip install the latest version in a Ubuntu Docker container; any insight?

Build failure seems to be idiosyncratic.  

I just created a clean virtual environment and then ran

```
python -m pip install https://files.pythonhosted.org/packages/13/a3/a8bf1c9e6d0193f854d9a79cb86a65dac0866de64051ff96e35bc7ecedfe/statsmodels-0.14.0.tar.gz -vv
```

and it completed without issue.

If you still have problems, can you run the same command and post the full log to a gist? (Please include the -vv)
