### ISSUE TITLE
Multi-dimensional indexing error in statsmodels.stats.diagnostic.linear_reset when using Pandas

### ISSUE THREAD

**Issue by Encephala** [statsmodels/statsmodels#8879]
#### Describe the bug

I tried to do a linear RESET test, but I got an error: `ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.`

Complete error message down below.

#### Code Sample, a copy-pastable example if possible

```python
#!/usr/bin/env python3
import numpy as np
import pandas as pd
import statsmodels.stats.diagnostic as smdiag
import statsmodels.api as sm

n = 100

df = pd.DataFrame()

df["y"] = np.random.rand(n)
df["x"] = np.random.rand(n)

OLS_results = sm.OLS(df["y"], df["x"]).fit()

smdiag.linear_reset(OLS_results)
```
<details>

Complete error Traceback:
```
Traceback (most recent call last):
  File "/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/bug_report.py", line 16, in <module>
    smdiag.linear_reset(OLS_results)
  File "/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 210, in wrapper
    return func(*args, **kwargs)
  File "/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/statsmodels/stats/diagnostic.py", line 1065, in linear_reset
    aug = res.fittedvalues[:, None]
  File "/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/pandas/core/series.py", line 1033, in __getitem__
    return self._get_with(key)
  File "/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/pandas/core/series.py", line 1048, in _get_with
    return self._get_values_tuple(key)
  File "/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/pandas/core/series.py", line 1082, in _get_values_tuple
    disallow_ndim_indexing(result)
  File "/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/pandas/core/indexers/utils.py", line 343, in disallow_ndim_indexing
    raise ValueError(
ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.
```

The error does not occur if `y` and `x` are passed as NumPy arrays, only when passed as pandas dataframe.

Using `statsmodels.stats.outliers_influence.reset_ramsey` also doesn't give this same problem.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

I expect to get the results of the test, as `statsmodels.stats.outliers_influence import reset_ramsey` does.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]
INSTALLED VERSIONS
------------------
Python: 3.10.6.final.0
OS: Linux 6.2.6-76060206-generic #202303130630~1681329778~22.04~d824cd4 SMP PREEMPT_DYNAMIC Wed A x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.14.0 (/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.24.3 (/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/numpy)
scipy: 1.10.1 (/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/scipy)
pandas: 2.0.1 (/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/pandas)
    dateutil: 2.8.2 (/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/dateutil)
patsy: 0.5.3 (/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.7.1 (/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/matplotlib)
    backend: agg 
cvxopt: Not installed
joblib: 1.2.0 (/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/joblib)

Developer Tools
================

IPython: 8.13.2 (/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/IPython)
    jinja2: Not installed
sphinx: Not installed
    pygments: 2.15.1 (/home/jonathan/RietNAS/Opleiding/EUR/1. Pre-master/FEB22009S Seminar Case Study/.venv/lib/python3.10/site-packages/pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by josef-pkt** [comment]
looks like a bug with pandas compatibility
The function should use the unwrapped results instance internally.


`smdiag.linear_reset(OLS_results._results)` should have worked as workaround, however it breaks on the isinstance check.

So the only workaround I see right now (except for monkey patching fittedvalues) is to reestimate the model without pandas:

```

.model
res_np = sm.OLS(OLS_results.model.endog, OLS_results.model.exog).fit()
smdiag.linear_reset(res_np)
<class 'statsmodels.stats.contrast.ContrastResults'>
<Wald test (chi2): statistic=63.544945204592665, p-value=1.5899756467736924e-14, df_denom=2>
```

**Comment by spring-haru** [comment]
I have the same issue for `.compare_lm_test()`.

```
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

n = 100

df = pd.DataFrame()

for v in ["y","x","z","k"]:
    df[v] = np.random.rand(n)

res0 = smf.ols("y ~ x + z + k", data=df).fit()
res1 = smf.ols("y ~ x", data=df).fit()

res0.compare_lm_test(res1)
```

The above code generates the following error

```
ValueError: Multi-dimensional indexing (e.g. `obj[:, None]`) is no longer supported. Convert to a numpy array before indexing instead.
```

**Comment by RajarshiMaiti** [comment]
I have the same issue in 
matplotlib: 3.5.1
pandas: 2.1.1
statsmodels: 0.13.5

**Comment by colourfulspring** [comment]
Thank you!! I had the same error. I solved it by downgrading my pandas package from 2.0.1 to 1.5.3.
