### ISSUE TITLE
ExponentialSmoothing 

### ISSUE THREAD

**Issue by kim-com** [statsmodels/statsmodels#8883]
hello world!
Could you please verify if there is an issue with the formula in the predict function of Holt-Winters?
bold text is needed to change **s[i-1]** to **s[i-m]**

**"(https://github.com/statsmodels/statsmodels/tree/main/statsmodels/tsa/holtwinters) /model.py:1360"**
```python
 `elif` seasonal == "add":
            for i in range(1, nobs + 1):
                lvls[i] = (
                    y_alpha[i - 1]
                    - (alpha * s[i - 1]) # <<--- This line
                    + (alphac * trended(lvls[i - 1], dampen(b[i - 1], phi)))
                )
                if has_trend:
                    b[i] = (beta * detrend(lvls[i], lvls[i - 1])) + (
                        betac * dampen(b[i - 1], phi)
                    )
                s[i + m - 1] = (
                    y_gamma[i - 1]
                    - (gamma * trended(lvls[i - 1], dampen(b[i - 1], phi)))
                    + (gammac * s[i - 1]) # <<--- This line
                )
            _trend = b[1 : nobs + 1].copy()
            season = s[m : nobs + m].copy()
            lvls[nobs:] = lvls[nobs]
            if has_trend:
                b[:nobs] = dampen(b[:nobs], phi)
                b[nobs:] = dampen(b[nobs], phi_h)
            trend = trended(lvls, b)
            s[nobs + m - 1 :] = [
                s[(nobs - 1) + j % m] for j in range(h + 1 + 1)
            ]
            fitted = trend + s[:-m]
```

**Comment by bashtage** [comment]
I don't see any bold. Can you clarify using a comment in the code (i.e., `# <<--- This line`)

**Comment by kim-com** [comment]
@bashtage Okay, I have made the modifications as your request.

**Comment by xieliaing** [comment]
In Holt-Winters additive model, the kth prediction equation is: \hat{Y}_t = L_t + k*T_t + S_{t-m+k}, where S_{t-m+k}, but this corresponds to the "fitted = " line, I think, while the code in the "for" loop does smoothing. In this sense, I think the original code is correct.

**Comment by kim-com** [comment]
@xieliaing thank you! i could understand your comment... it means that If nobs is greater than m, smoothing is performed using new data to maintain appropriate data for freshness. is it right?
