### ISSUE TITLE
How can I use version 0.15.0?

### ISSUE THREAD

**Issue by dblim** [statsmodels/statsmodels#8918]
I'd like to use the fact that SARIMAX in 0.15.0 supports a maxiter argument. When will 0.15.0 be released? In the meantime, is there a way for me to use the code in 0.15.0?

**Comment by ChadFulton** [comment]
SARIMAX has has a `maxiter` argument for many versions now, so you do not need to install the development version if that is all you need.

However, you can install the development version by using `pip install git+https://github.com/statsmodels/statsmodels.git`.
