### ISSUE TITLE
How exactly does ARIMA(0,1,1)'s .predict() method work? 

### ISSUE THREAD

**Issue by dblim** [statsmodels/statsmodels#8931]
I'm trying to understand how ARIMA(0,1,1) does in sample predictions, and this is where I get confused. What I've done is generated a time series by hand and then done the following.

1. Get in sample predictions with the .predict() method.
2. If res  = model.fit(), save res.params and use this to "reconstruct" the predictions by hand manually. 

Here's the code block that does this:

```python
import numpy as np
import pandas as pd 
from statsmodels.tsa.arima.model import ARIMA

def f(X : np.ndarray, arima_params):
    theta, sigma2 = arima_params[0], arima_params[1]

    # Initialize your predicted series
    X_hat = np.zeros(len(X))

    # Set first value to the same as original series
    X_hat[0] = 0
    X_hat[1] = X[0]

    # Calculate the rest of the predictions
    for t in range(2, len(X)):
        X_hat[t] = X[t] + theta * (X_hat[t-1] - X[t-1])

    return X_hat

# Generate random time series
n = 10
theta = -0.6
np.random.seed(0)  
shocks = np.random.normal(0, 1, n)

# Initialize the time series
ts = np.zeros(n)
ts[0] = shocks[0]

# Generate the ARIMA(0,1,1) time series
for t in range(1, n):
    ts[t] = ts[t-1] + shocks[t] + theta * shocks[t-1]
df = pd.DataFrame({'X' :ts})

# Now predict with statsmodels and using function f above. 
model = ARIMA(df['X'].values, order = (0,1,1))
res = model.fit()
df['auto_pred'] = res.predict()
manual_prediction = f(df['X'], res.params)
df['manual_pred'] = manual_prediction
df
```
Here's the result of the code above: 

X | auto_pred | manual_pred
-- | -- | -- |
1.764052 | 0.000000 | 0.000000
1.105778 | 1.764051 | 1.764052
1.844422 | 1.388541 | 1.470347
3.498072 | 1.604289 | 3.710646
4.021094 | 2.446707 | 3.900296
1.923282 | 3.133034 | 1.991927
3.459737 | 2.609106 | 3.420728
2.738326 | 2.976724 | 2.760494
2.725922 | 2.873766 | 2.713325
3.198452 | 2.809930 | 3.205610

The column auto_pred is the result of calling .predict(), while manual_pred is predictions that I've reconstructed manually by hand using res.params. Why are these results totally different? I initialized the function f above to mimic the 0th and 1st values of .predict(), so you can see that auto_pred and manual_pred match for the 0th and 1st values. But after that they differ and I have no idea why. What's going on here? I believe what I've done using the function f is correct because the mse is much smaller than the one from .predict().

**Comment by bashtage** [comment]
The prediction in a statespace model is constructed using the MSE optimal prediction which is not the same as using an approximation to the previous error.  To better understand how the MSE optimal prediction is made, look up inverting an MA model.

**Comment by dblim** [comment]
> The prediction in a statespace model is constructed using the MSE optimal prediction which is not the same as using an approximation to the previous error. To better understand how the MSE optimal prediction is made, look up inverting an MA model.

Oh ok, this is very helpful

**Comment by dblim** [comment]
> The prediction in a statespace model is constructed using the MSE optimal prediction which is not the same as using an approximation to the previous error. To better understand how the MSE optimal prediction is made, look up inverting an MA model.

Huh ok, this is very helpful. It's a little confusing because for an AR(p) process what I'm doing works. Would you be able to point an exact reference on what's going on, and (if you have time) spell out the correction on how exactly the prediction should work? I searched online for "How does prediction work for ARIMA(0,1,1) work" and most of what I get is stuff on how to call code in R to predict.

**Comment by bashtage** [comment]
See https://stats.stackexchange.com/questions/430186/how-statsmodels-predict-ma-process/430274#430274

**Comment by bashtage** [comment]
In an AR(p) you excatly know all of the values needed for prediction once you have at least p observation.  In an MA(1), you never know the previous error even in when the sample size is large (it only converges asymptotically).  The Kalman filter always makes the prediction as E[Y(t+1)|Y(t),Y(t-1),...]. In an AR(P) this prediction is trivial. In an MA model, it is less trivial, although easy enough to derive.

**Comment by dblim** [comment]
Ah ok I see. So basically, here's what's going on.
1. Turn the ARIMA(0,1,1) model into its Harvey representation of a state space model (this is the default in SARIMAX). 
2. Now that we have stuff in the form of a Kalman filter, the prediction Y^(t+1) in ARIMA is given as Y^_{t +1 | t}, the a priori state estimate in a Kalman filter. Is this correct?

**Comment by ChadFulton** [comment]
Yes, as @bashtage wrote above, the predictions returned by Statsmodels are E[Y(t+1)|Y(t),Y(t-1),...], and we compute them by applying the Kalman filter to the state space form of the ARIMA(0, 1, 1) model. I think this is what you were saying in your item (2.) but I'm not entirely sure.
