### ISSUE TITLE
Can't import api for python 3.11.4.

### ISSUE THREAD

**Issue by Joseisg** [statsmodels/statsmodels#8934]
For some reason everything works when calling the exact function from the module but I just can't use the normal functions from the API so I had to use imports like this:
```python
import statsmodels.tools as sm_tools
import statsmodels.regression.linear_model as sm_regression
import statsmodels.graphics.gofplots as sm_gofplots

instead of the normals .OLS .add_constant or .qqplot
```
Any idea what could I do or what should I do? is there any version of python 11 that works just fine??? Im using spyder but the modules are directly from my system PATH. Im not using the spyder environment for the modules.

#### errors:

```python
import statsmodels.api as sm
Traceback (most recent call last):

  Cell In[120], line 1
    import statsmodels.api as sm

  File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\api.py:78
    from . import datasets, distributions, iolib, regression, robust, tools

  File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\robust\__init__.py:6
    from .scale import mad, Huber, HuberScale, hubers_scale

  File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\robust\scale.py:21
    from ._qn import _qn

ModuleNotFoundError: No module named 'statsmodels.robust._qn'


from statsmodels.formula.api import ols
Traceback (most recent call last):

  Cell In[122], line 1
    from statsmodels.formula.api import ols

  File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\formula\api.py:6
    import statsmodels.robust.robust_linear_model as roblm_

  File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\robust\__init__.py:6
    from .scale import mad, Huber, HuberScale, hubers_scale

  File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsmodels\robust\scale.py:21
    from ._qn import _qn

ModuleNotFoundError: No module named 'statsmodels.robust._qn'
```
btw: I already know there's a few people with the same problem, but I can't understand why or how the only real "fix" that everyone has is just using anaconda... there has to be another way right?
right?
😢

thanks in advance

**Comment by bashtage** [comment]
I did the following and had no issues.

1. Install Python from https://www.python.org/downloads/release/python-3114/   I would not use Python that comes from the Windows store.  You should change the permissions to allow writing to this directory.
2. Assuming you install it to the default location, run
```powershell
C:\Python311\python.exe -m pip install statsmodels spyder ipython -U
C:\Python311\python.exe -m IPython
```

Once you have IPython open, run

```python
import statsmodels.api as sm
```

Then finally, you should be able to run

```
C:\Python311\Scripts\spyder.exe
```

And have it work as expected.
