### ISSUE TITLE
two-sample ztest may have bug 

### ISSUE THREAD

**Issue by gorj-tessella** [statsmodels/statsmodels#8936]
#### Describe the bug

The implementation of the two sample ztest does not appear to match documented algorithms

Specifically, the calculation of `var_pooled` below deviates slightly from how it is calculated elsewhere. 

https://github.com/statsmodels/statsmodels/blob/114d812133c0b8360c6d2e6059414e0706007977/statsmodels/stats/weightstats.py#L1543-L1561

For reference consult the following documentation:

https://en.wikipedia.org/wiki/Student%27s_t-test#Independent_two-sample_t-test

The code most closely resembles the "Equal or unequal sample sizes, similar variances" equation, but on line 1552 should subtract `ddof` from the nobs e.g. `var_pooled = (nobs1 - ddof) * x1_var + (nobs2 - ddof) * x2_var`

However we should not assume that the variances are similar, and should be using the more general "Equal or unequal sample sizes, unequal variances" equation.

**Comment by melizwu** [comment]
Hi @gorj-tessella,
It seems there is a confusion between the z-test and the t-test. Your implementation aligns more with a t-test, considering the assumption of unequal variances. However, from my understanding, a z-test always assumes equal variances. Let me know if there is something I am missing.

**Comment by josef-pkt** [comment]
unequal variance would also be useful in the z-test.
I don't remember why the option was not implemented.

However, the Satterthwaite degrees of freedom correction in the t-test will not apply and is irrelevant for the z-test.

**Comment by josef-pkt** [comment]
A pull request would be great. it should be able to reuse the variance computation from the t-test (AFAIR).

I can look at it early August.
