### ISSUE TITLE
adfuller p-value exactly zero

### ISSUE THREAD

**Issue by daniel-finnan** [statsmodels/statsmodels#8945]
Hi, slightly confused by some of the results I'm getting from the adfuller function, notably with results giving me a p-value of exactly zero, with zero lags. Not sure if this is a bug, or I've just overlooked something in my use of the function, apologies in advance if it is the latter.

I'm using the same code as in the example in the docs

```python
def adf_test(timeseries):
    print("Results of Dickey-Fuller Test:")
    dftest = adfuller(timeseries, autolag="AIC")
    dfoutput = pd.Series(
        dftest[0:4],
        index=[
            "Test Statistic",
            "p-value",
            "#Lags Used",
            "Number of Observations Used",
        ],
    )
    for key, value in dftest[4].items():
        dfoutput["Critical Value (%s)" % key] = value
    print(dfoutput)
    return dfoutput
```
My time series data has 1492 observations. A sample of the data looks as follows:

```
0.0398
0.0479
0.0494
0.0629
0.064
0.06805
0.0697
0.0751
0.0783
0.0793
```
The full series is attached in csv format. There are no missing or zero values.

[p_value_zero.csv](https://github.com/statsmodels/statsmodels/files/11928961/p_value_zero.csv)

The output looks as follows:

```
Results of Dickey-Fuller Test:
Test Statistic                  -36.474824
p-value                           0.000000
#Lags Used                        0.000000
Number of Observations Used    1491.000000
Critical Value (1%)              -3.434743
Critical Value (5%)              -2.863480
Critical Value (10%)             -2.567803
```
I wondered whether the issue was simply the result being printed to the console. So within the variable storing the result of the function, i.e. `dftest`, the result is as follows:

![image](https://github.com/statsmodels/statsmodels/assets/90457760/9bac12bc-6006-4b6a-b583-36b362cc2cd9)

It seems odd to me that I'm getting exactly 0.0. I'm using this on 70 different columns and I'm getting this 5 times. I'm using statsmodels Version: 0.14.0

Is my p-value actually so small that it is actually hitting the limit of floating point precision? Thanks in advance.

**Comment by bashtage** [comment]
It is only 0 to numerical precision.  P values are always positive although can be arbitrarily small. This is the expected result when your test statistic is -36.  The critical value is in the range of -4, so you are way out in the tail.

**Comment by daniel-finnan** [comment]
@bashtage Thanks for clarifying
