### ISSUE TITLE
VAR model fit with different lags for each exog-variable

### ISSUE THREAD

**Issue by tim-mcwilliams** [statsmodels/statsmodels#8956]
Hi! 

Looking to build out a VAR model using `statsmodels.tsa.vector_ar.var_model.VAR`. However, each of the exogs need to have their own lag, instead of a default to 0. The source code has a `TODO` in the `fit()` method that talks about each exog-variable receiving a lag of 0 but if the need for dealing with different exogs a `lags_exog` param might make sense. 

The mentioned `TODO`: [VAR.fit](https://www.statsmodels.org/dev/_modules/statsmodels/tsa/vector_ar/var_model.html#VAR.fit)
`todo: this code is only supporting deterministic terms as exog.
This means that all exog-variables have lag 0. If dealing with
different exogs is necessary, a 'lags_exog'-parameter might make
sense (e.g. a sequence of ints specifying lags).
Alternatively, leading zeros for exog-variables with smaller number
of lags than the maximum number of exog-lags might work.`

Is this something being worked on? If so, what is the progress on the feature? If not, is there any other package that you folks know of or have that will allow the researcher to define lags for each exogs-variable?

Thanks!!

**Comment by ChadFulton** [comment]
In the `VAR` class, the only option right now is to manually construct the lags yourself, e.g. if your data is in the variable `X` and you want the 0, 1, 2 lags, then you could do:

```
exog = sm.tsa.lagmat(X, maxlag=2, original='in')

mod = sm.tsa.VAR(y, exog=X)
```

That TODO item is not being actively worked on.

Closing as answered, but feel free to follow up.

**Comment by tim-mcwilliams** [comment]
@ChadFulton, thanks for the quick reply! 

I have one question about how to use the output of `sm.tsa.lagmat` class. 

Let's say we have our data in the variable `X` and `X` is a 3-d array (3 exog vars). If we were to do a temporal correlation analysis and find that `X1` has a time lag of 5, `X2` has a time lag of 10, and `X3` has a time lag of 15. Given the results of the `lagmat` call, should we add all lags 0-15 in the `VAR` call or should we grab the  `X1.L5`, `X.L10`,`X.L15` columns and input those as the exog variables in the `VAR` call??

**Comment by tim-mcwilliams** [comment]
@ChadFulton , for example,

```
y = model_data[['date', 'y']]
# Using the lagmat function we can create our own lagged variables based on the temporal correlation analysis
v1_lag = sm.tsa.lagmat(
    model_data['v1'],
    maxlag=22,
    original='in',
    use_pandas=True
)
v2_lag = sm.tsa.lagmat(
    model_data['v2'],
    maxlag=17,
    original='in',
    use_pandas=True
)
v3_lag = sm.tsa.lagmat(
    model_data['v3'],
    maxlag=12,
    original='in',
    use_pandas=True
)
model_data_lags = pd.concat(
    [y, v1_lag, v2_lag, v3_lag],
    axis=1
)

var_model = VAR(model_data_lags)
var_results = var_model.fit(22)
```

**Comment by ChadFulton** [comment]
In the example you just posted, you are modifying the `endog` variable, not`exog` variables. Can you clarify what you're trying to achieve?

**Comment by tim-mcwilliams** [comment]
@ChadFulton, thanks for the reply!

It was my understanding that the `y` variable in the above example is the `endog` variable and all of the other variables `x1_lag, x2_lag, x3_lag` are the `exog` variables. Is that understanding correct?

What I'm trying to achieve here is using those `x` variables to predict the `y` variable.

**Comment by ChadFulton** [comment]
Okay, I see. In the `VAR` model, the `exog` variables are considered as additional explanatory variables above and beyond the lags of the left-hand-side variables.

Unfortunately, the `VAR` model does not have a way of restricting the lags of the left-hand-side (`endog`) variables. One option would be to construct the right-hand-side variables as you did above and use [`MultivariateOLS`](https://bashtage.github.io/linearmodels/system/examples/examples.html#Multivariate-OLS) from the `linearmodels` package.

**Comment by tim-mcwilliams** [comment]
Given your explanation of what the `exog` variables are, I may have been wrong in stating that the `y` is `endog` and the `x's` are `exog` variables.

Maybe I didn't fully explain the goal. Not only am I interested in the `x` variables predicting `y`, but also the inter relationships over time between the `x` variables in predicting each other. That is why I was going down the `VAR` route. Just happens to be that I am most interested in the `y` variable. 

So I can say, based on your explanation, all variables in the model are `endog` variables. However, in the case of a `VAR` model we can't restrict the lags of those variables. Which for my case is fine, just wanted to know if there was a way or if it was even possible.

Have you ever seen the results of a cross correlation analysis used when creating a `VAR` model, whether included in the model or as a guiding factor to assess the results of the model (IFR's & FEVD's)?

**Comment by ChadFulton** [comment]
> So I can say, based on your explanation, all variables in the model are endog variables. However, in the case of a VAR model we can't restrict the lags of those variables. Which for my case is fine, just wanted to know if there was a way or if it was even possible.

The estimated coefficients of VAR models can be restricted. For example, it is a pretty straightforward extension of the linear algebra to include linear restrictions when estimating the coefficients via least squares. Excluding certain lags counts as a linear restriction, because it is the restriction $\beta_{ij} = 0$.  Unfortunately, linear restrictions just aren't implemented for the statsmodels `VAR` model.

> Maybe I didn't fully explain the goal. Not only am I interested in the x variables predicting y, but also the inter relationships over time between the x variables in predicting each other. That is why I was going down the VAR route. Just happens to be that I am most interested in the y variable.

Since the `VAR` model uses least squares anyway, you will get identical results if you use the `MultivariateOLS` class I mentioned after constructing the right-hand-side variables you want as a subset of the full set of lags. However, there would then not be any built-in impulse response for forecast error variance decomposition analysis, so you would have to do that on your own.

So unfortunately, we don't have a perfect build-in solution for you.

**Comment by tim-mcwilliams** [comment]
> The estimated coefficients of VAR models can be restricted. For example, it is a pretty straightforward extension of the linear algebra to include linear restrictions when estimating the coefficients via least squares. Excluding certain lags counts as a linear restriction, because it is the restriction $\beta_{ij} = 0$. Unfortunately, linear restrictions just aren't implemented for the statsmodels VAR model.

Makes sense. Was researching up on the asymmetric VAR model yesterday which basically implements those linear restrictions. 

Got it, I will take a look a the `MultivariateOLS` class. Even though there isn't any built-in impulse response or forecast error variance decomposition analysis, will still be a good learning to dive into that model class.

Really appreciate the discussion here!!

**Comment by ChadFulton** [comment]
Glad it was helpful!

**Comment by josef-pkt** [comment]
Var model with restrictions requires SUR or similar estimation.
MultivariateLS has also the requirement of full exog without restrictions
like VAR
