### ISSUE TITLE
Dynamic Factor Models MQ: forecast latent factors

### ISSUE THREAD

**Issue by fipelle** [statsmodels/statsmodels#8964]
Hi there,

I am currently working on computing the forecast for the latent factor of a Dynamic Factor Model (DFM) estimated via statsmodels for h steps ahead. However, I have not been able to find much information on how to do it in the documentation. Could someone please guide me on how to proceed with this task?

Thank you!

**Comment by ChadFulton** [comment]
Yes, I don't think this is well documented, but when you call `get_forecast` it returns a results object that contains all the output from the Kalman filter iterations that construct the prediction.

Here's an example:

```python
dta = sm.datasets.macrodata.load_pandas().data
y = np.log(dta[['realgdp', 'realinv', 'realcons']]).diff().iloc[1:] * 400
mod = sm.tsa.DynamicFactorMQ(y, idiosyncratic_ar1=False, standardize=False)
res = mod.fit(maxiter=1000)

h = 10
fcast = res.get_forecast(h)
fcast.prediction_results.predicted_state
```

Closing as answered, but please feel free to follow up if you like.

**Comment by fipelle** [comment]
Hi Chad,

Just a quick follow-up. I understand that `fcast.prediction_results.predicted_state` is `no states x forecast horizon`. However, I am not clear states order. How can I get the index for the factors at time $t$?

**Comment by ChadFulton** [comment]
You can use the `state_names` attribute of the model. The naming scheme for the factors is:

- `{name}` for the factor [or] `{name}.{i}` if you specified a factor with multiplicity > 1
- `L{j}.{name}` for the $j$-th lag of the factor [or] `L{j}.{name}.{i}` if you specified a factor with multiplicity > 1

If you didn't specify names for your factors, then the {name}s are just integers starting at zero.

And then if you included idiosyncratic AR(1) terms, they are also in the state vector as `{eps}_{M|Q}.{endog name}`.

So in the above example:

```python
>>> print(mod.state_names)
['0']
```

Or in a more complicated example:

```python
>>> mod = sm.tsa.DynamicFactorMQ(y, factors={'realgdp': ['a'], 'realinv': ['a'], 'realcons': 'b'},
                                 factor_orders=2, factor_multiplicities={'a': 2, 'b': 1},
                                 idiosyncratic_ar1=True, standardize=False)
>>> print(mod.state_names)
['a.1', 'a.2', 'L1.a.1', 'L1.a.2', 'b', 'L1.b', 'eps_M.realgdp', 'eps_M.realinv', 'eps_M.realcons']
```
