### ISSUE TITLE
ImportError: cannot import name 'seasonal_naive' from 'statsforecast.models'

### ISSUE THREAD

**Issue by merajhasan88** [statsmodels/statsmodels#8970]
On a jupyter notebook with Windows, and Python `3.11.4`, while trying to import `seasonal_naive` I get an error:
```
ImportError: cannot import name 'seasonal_naive' from 'statsforecast.models'
```

I ran this code from [this](https://pypi.org/project/statsforecast/0.5.6/) pypi link:
```
import numpy as np
import pandas as pd
from IPython.display import display, Markdown

import matplotlib.pyplot as plt
from statsforecast import StatsForecast
from statsforecast.models import seasonal_naive, auto_arima
from statsforecast.utils import AirPassengers
```
I have `statsforecast-1.5.0 statsmodels-0.14.0`.
What am I doing wrong?

**Comment by bashtage** [comment]
You need to ask in the statsforecasts repo.  This is only for statsmodels.
