### ISSUE TITLE
unable to install stats models on ubuntu 18.04 container

### ISSUE THREAD

**Issue by doncans** [statsmodels/statsmodels#8984]
Collecting statsmodels
  Using cached statsmodels-0.14.0.tar.gz (19.4 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [147 lines of output]
      Ignoring numpy: markers 'python_version == "3.10" and platform_system == "Windows" and platform_python_implementation != "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.12"' don't match your environment
      Collecting setuptools>=59.2.0
        Obtaining dependency information for setuptools>=59.2.0 from https://files.pythonhosted.org/packages/4f/ab/0bcfebdfc3bfa8554b2b2c97a555569c4c1ebc74ea288741ea8326c51906/setuptools-68.1.2-py3-none-any.whl.metadata
        Using cached setuptools-68.1.2-py3-none-any.whl.metadata (6.2 kB)
      Collecting cython<3,>=0.29.26
        Obtaining dependency information for cython<3,>=0.29.26 from https://files.pythonhosted.org/packages/3f/d6/9eed523aeaca42acbaa3e6d3850edae780dc7f8da9df1bf6a2ceb851839c/Cython-0.29.36-py2.py3-none-any.whl.metadata
        Using cached Cython-0.29.36-py2.py3-none-any.whl.metadata (3.1 kB)
      Collecting oldest-supported-numpy
        Obtaining dependency information for oldest-supported-numpy from https://files.pythonhosted.org/packages/94/9a/756fef9346e5ca2289cb70d73990b4c9f25446a885c1186cfb93a85e7da0/oldest_supported_numpy-2023.8.3-py3-none-any.whl.metadata
        Using cached oldest_supported_numpy-2023.8.3-py3-none-any.whl.metadata (9.5 kB)
      Collecting scipy>=1.4
        Using cached scipy-1.10.1-cp38-cp38-linux_ppc64le.whl
      Collecting setuptools_scm[toml]~=7.0.0
        Using cached setuptools_scm-7.0.5-py3-none-any.whl (42 kB)
      Collecting numpy==1.17.3 (from oldest-supported-numpy)
        Using cached numpy-1.17.3-cp38-cp38-linux_ppc64le.whl
      INFO: pip is looking at multiple versions of scipy to determine which version is compatible with other requirements. This could take a while.
      Collecting scipy>=1.4
        Using cached scipy-1.10.0.tar.gz (42.4 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): finished with status 'done'
        Using cached scipy-1.9.3.tar.gz (42.1 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'error'
        error: subprocess-exited-with-error
      
        × pip subprocess to install build dependencies did not run successfully.
        │ exit code: 1
        ╰─> [100 lines of output]
            Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "aarch64" and platform_python_implementation != "PyPy"' don't match your environment
            Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
            Ignoring numpy: markers 'python_version == "3.9" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
            Ignoring numpy: markers 'platform_machine == "loongarch64"' don't match your environment
            Ignoring numpy: markers 'python_version == "3.10" and platform_system == "Windows" and platform_python_implementation != "PyPy"' don't match your environment
            Ignoring numpy: markers 'python_version == "3.9" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_machine != "loongarch64" and platform_python_implementation != "PyPy"' don't match your environment
            Ignoring numpy: markers 'python_version == "3.10" and (platform_system != "Windows" and platform_machine != "loongarch64") and platform_python_implementation != "PyPy"' don't match your environment
            Ignoring numpy: markers 'python_version == "3.11" and platform_python_implementation != "PyPy"' don't match your environment
            Ignoring numpy: markers 'python_version >= "3.12"' don't match your environment
            Ignoring numpy: markers 'python_version >= "3.8" and platform_python_implementation == "PyPy"' don't match your environment
            Collecting meson-python>=0.9.0
              Obtaining dependency information for meson-python>=0.9.0 from https://files.pythonhosted.org/packages/5e/ad/c51b346930e7050cae81bb9f360986da30e27e1bffd28a8495fcbe84ec73/meson_python-0.13.2-py3-none-any.whl.metadata
              Using cached meson_python-0.13.2-py3-none-any.whl.metadata (4.1 kB)
            Collecting Cython<3.0,>=0.29.32
              Obtaining dependency information for Cython<3.0,>=0.29.32 from https://files.pythonhosted.org/packages/3f/d6/9eed523aeaca42acbaa3e6d3850edae780dc7f8da9df1bf6a2ceb851839c/Cython-0.29.36-py2.py3-none-any.whl.metadata
              Using cached Cython-0.29.36-py2.py3-none-any.whl.metadata (3.1 kB)
            Collecting pybind11<2.11.0,>=2.4.3
              Using cached pybind11-2.10.4-py3-none-any.whl (222 kB)
            Collecting pythran<0.13.0,>=0.9.12
              Using cached pythran-0.12.2-py3-none-any.whl (4.2 MB)
            Collecting wheel<0.38.0
              Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
            Collecting numpy==1.18.5
              Using cached numpy-1.18.5.zip (5.4 MB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'error'
              error: subprocess-exited-with-error
      
              × Preparing metadata (pyproject.toml) did not run successfully.
              │ exit code: 1
              ╰─> [55 lines of output]
                  warning: /tmp/pip-install-edzyhp6r/numpy_43ff2c6468e64cc28f59b6d4642691ed/numpy/__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      
                  Error compiling Cython file:
                  ------------------------------------------------------------
                  ...
                          for i in range(1, RK_STATE_LEN):
                              self.rng_state.key[i] = val[i]
                          self.rng_state.pos = i
      
                          self._bitgen.state = &self.rng_state
                          self._bitgen.next_uint64 = &mt19937_uint64
                                                     ^
                  ------------------------------------------------------------
      
                  _mt19937.pyx:138:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
                  /tmp/pip-install-edzyhp6r/numpy_43ff2c6468e64cc28f59b6d4642691ed/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
                    required_version = LooseVersion('0.29.14')
                  /tmp/pip-install-edzyhp6r/numpy_43ff2c6468e64cc28f59b6d4642691ed/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
                    if LooseVersion(cython_version) < required_version:
                  Processing numpy/random/_bounded_integers.pxd.in
                  Processing numpy/random/_mt19937.pyx
                  Traceback (most recent call last):
                    File "/tmp/pip-install-edzyhp6r/numpy_43ff2c6468e64cc28f59b6d4642691ed/tools/cythonize.py", line 238, in <module>
                      main()
                    File "/tmp/pip-install-edzyhp6r/numpy_43ff2c6468e64cc28f59b6d4642691ed/tools/cythonize.py", line 234, in main
                      find_process_files(root_dir)
                    File "/tmp/pip-install-edzyhp6r/numpy_43ff2c6468e64cc28f59b6d4642691ed/tools/cythonize.py", line 225, in find_process_files
                      process(root_dir, fromfile, tofile, function, hash_db)
                    File "/tmp/pip-install-edzyhp6r/numpy_43ff2c6468e64cc28f59b6d4642691ed/tools/cythonize.py", line 191, in process
                      processor_function(fromfile, tofile)
                    File "/tmp/pip-install-edzyhp6r/numpy_43ff2c6468e64cc28f59b6d4642691ed/tools/cythonize.py", line 80, in process_pyx
                      subprocess.check_call(
                    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
                      raise CalledProcessError(retcode, cmd)
                  subprocess.CalledProcessError: Command '['/data/cc-agents/venv/bin/python3.8', '-m', 'cython', '-3', '--fast-fail', '-o', '_mt19937.c', '_mt19937.pyx']' returned non-zero exit status 1.
                  Running from numpy source directory.
                  <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
                  Cythonizing sources
                  Traceback (most recent call last):
                    File "/data/cc-agents/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                      main()
                    File "/data/cc-agents/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                      json_out['return_val'] = hook(**hook_input['kwargs'])
                    File "/data/cc-agents/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
                      return hook(metadata_directory, config_settings)
                    File "/tmp/pip-build-env-nex6ezkb/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
                      self.run_setup()
                    File "/tmp/pip-build-env-nex6ezkb/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 507, in run_setup
                      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
                    File "/tmp/pip-build-env-nex6ezkb/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
                      exec(code, locals())
                    File "<string>", line 488, in <module>
                    File "<string>", line 469, in setup_package
                    File "<string>", line 275, in generate_cython
                  RuntimeError: Running cythonize failed!
                  [end of output]
      
              note: This error originates from a subprocess, and is likely not a problem with pip.
            error: metadata-generation-failed
      
            × Encountered error while generating package metadata.
            ╰─> See above for output.
      
            note: This is an issue with the package mentioned above, not pip.
            hint: See above for details.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error
      
      × pip subprocess to install build dependencies did not run successfully.
      │ exit code: 1
      ╰─> See above for output.
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(venv) root@#######:/data/cc-agents# make test

**Comment by doncans** [comment]
I have installed numpy,pandas , cython, patsy, scipy even though it got failed

**Comment by bashtage** [comment]
You need to use Cython 0.29.x, not Cython 3.

**Comment by doncans** [comment]
> You need to use Cython 0.29.x, not Cython 3.

Yes , I have installed cython==0.29.26
