### ISSUE TITLE
`anova_single` fails both with `np.ndarray` and `pd.DataFrame`

### ISSUE THREAD

**Issue by jonathan-taylor** [statsmodels/statsmodels#8994]
#### Describe the bug

Running `anova_lm` with a single model, which calls `anova_single` fails.

#### Code Sample, a copy-pastable example if possible

```python

import numpy as np
import pandas as pd 
import statsmodels.api as sm
rng = np.random.default_rng(0)
print(sm.__version__) # 0.14.0
X = rng.standard_normal((100, 5))
Y = rng.standard_normal(100)
M1 = sm.OLS(Y, X)
R1 = M1.fit()
sm.stats.anova_lm(R1) # raises: AttributeError: 'ModelData' object has no attribute 'design_info'

D = pd.DataFrame(X, columns=['X%d' % i for i in range(5)])
M2 = sm.OLS(Y, D)
R2 = M2.fit()
sm.stats.anova_lm(R2) # raises AttributeError: 'PandasData' object has no attribute 'design_info'

```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `main`. If your problem has been fixed in an unreleased version, you might be able to use `main` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the main branch of this repository? It helps the limited resources if we know problems exist in the current main branch so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

In both cases an ANOVA table instead of an exception.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

INSTALLED VERSIONS
------------------
Python: 3.9.16.final.0
OS: Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.14.0 (/Users/jtaylo/anaconda3/envs/islp_test/lib/python3.9/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.24.2 (/Users/jtaylo/anaconda3/envs/islp_test/lib/python3.9/site-packages/numpy)
scipy: 1.11.1 (/Users/jtaylo/anaconda3/envs/islp_test/lib/python3.9/site-packages/scipy)
pandas: 1.5.3 (/Users/jtaylo/anaconda3/envs/islp_test/lib/python3.9/site-packages/pandas)
    dateutil: 2.8.2 (/Users/jtaylo/anaconda3/envs/islp_test/lib/python3.9/site-packages/dateutil)
patsy: 0.5.3 (/Users/jtaylo/anaconda3/envs/islp_test/lib/python3.9/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.7.1 (/Users/jtaylo/anaconda3/envs/islp_test/lib/python3.9/site-packages/matplotlib)
    backend: module://matplotlib_inline.backend_inline 
cvxopt: Not installed
joblib: 1.3.1 (/Users/jtaylo/anaconda3/envs/islp_test/lib/python3.9/site-packages/joblib)

Developer Tools
================

IPython: 8.12.0 (/Users/jtaylo/anaconda3/envs/islp_test/lib/python3.9/site-packages/IPython)
    jinja2: 3.1.2 (/Users/jtaylo/anaconda3/envs/islp_test/lib/python3.9/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.14.0 (/Users/jtaylo/anaconda3/envs/islp_test/lib/python3.9/site-packages/pygments)
pytest: Not installed
virtualenv: 20.23.0 (/Users/jtaylo/anaconda3/envs/islp_test/lib/python3.9/site-packages/virtualenv)

</details>

**Comment by bashtage** [comment]
This is expected.  Per the docs:

**Notes**

Model statistics are given in the order of args. 
Models must have been fit using the formula api.

**Comment by bashtage** [comment]
https://www.statsmodels.org/dev/generated/statsmodels.stats.anova.anova_lm.html

**Comment by jonathan-taylor** [comment]
Oops, just saw that. Seems a little limiting...

**Comment by josef-pkt** [comment]
without formula information there are no `terms` that `anova_lm` can analyse.

Related: Wald test only
`combine_terms` allows string matching to define `terms` for hypothesis that all coefficients in term are zero.
https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.RegressionResults.wald_test_terms.html
This also works without formula if names of columns are specified, e.g. with pandas DataFrame.

**Comment by jonathan-taylor** [comment]
There are certainly terms you __could__ use -- the sequence of columns of the design matrix. After all, these are named in the `summary`... Sure, a formula provides more nuance, but I don't see that this needs to be a failure IMO.

**Comment by jonathan-taylor** [comment]
It's also not true that they need to be fit with the formula API **except** when it's a single model. Passing a sequence of fits works fine.

**Comment by josef-pkt** [comment]
> There are certainly terms you could use -- the sequence of columns of the design matrix.

How would you define terms for an arbitrary list of strings as column names?
e.g. for Anova type 3

The only idea I could come up with is the string matching that I implemented with combine_terms in wald_test_terms
 

> It's also not true that they need to be fit with the formula API except when it's a single model. Passing a sequence of fits works fine (as it should).

That means we need to update and correct the docs.

**Comment by jonathan-taylor** [comment]
Well, the sm.OLS(Y,X).fit().summary() method auto-generates names. Why not just use those?

**Comment by josef-pkt** [comment]
Those are generic names with one unique name per column, or whatever pandas column names were used. There is no concept of multicolumn `terms` (as for example in categorical explanatory variables or interaction effects).

For one column terms the main results are the Wald tests in `summary`, params, bse, tvalues, pvalues.

**Comment by josef-pkt** [comment]
For type 1 anova, the sequence would be interpretable even with one column terms.
However, I never saw much use in type 1 anova, i.e. predefined sequence of all exog (except in special cases like lags or polynomials).

**Comment by jonathan-taylor** [comment]
Sure, but there is still a sensible ANOVA table. The p-values in the `summary()` are p-values one would get with a certain type of ANOVA (I always forget but I think this is Type III). As I said, I agree that a formula can give you a more nuanced answer to the expert, I just don't see why it's a failure when someone fits a models with e.g. an np.ndarray. If you're willing to report p-values in `summary()` then I don't see why you can't do Type I or Type III anova in `anova_lm`. Just my $0.02

**Comment by josef-pkt** [comment]
I always had and have problems with (multiway) ANOVA.
It's either too ambiguous, too limited or both, if we don't have an orthogonal design.

Wald test, score/LM test and likelihood ratio tests are well defined for any design.

wald test (f_test, wald_test, t_test) are the same as anova type III for some `terms`, but wald test have a unambiguous interpretation for misspecified models (sandwich cov_type) and don't rely on any sum of squares definitions.
(pvalues of t_test in summary should be exactly the same as anova_lm pvalues for single column terms for nonrobust cov_type)

We have now also score_tests for misspecified models, but so far no automatic "terms" version, i.e. interface for only one hypothesis.

LR, standard F-test are restrictive in that they assume correctly specified likelihood (otherwise we need a nonstandard distribution for p-values)

For both score_test and LR tests we could add a more user friendly version for the automatic type 3 or type 1 (arbitrary sequence) hypothesis tests. The current `compare_lr_test` only allows a single comparison between 2 nested models.

(Aside: I like wald and score tests because they also work for GLM and similar models with eg. excess dispersion or other likelihood misspecifications. The assumptions for anova or analysis of deviance are hidden in the computations, at least as far as I read the literature.)

**Comment by jonathan-taylor** [comment]
I agree that interpretations of ANOVA tables are dangerous. Caveat emptor. 

That's not why I raised the issue. My issue is that I don't see this raises an exception here, particularly if the Type III results (for some kwarg values) are implicitly available in `smOLS(y,X).fit().summary()`.

**Comment by josef-pkt** [comment]
I'm not against making changes to anova_lm.
If single column terms are interesting enough, then it shouldn't be too difficult to add them when there is no formula/design info available.

My comments above are essentially the reason that I never looked at improving anova_lm. anova_lm is essentially the same version as what Skipper added a long time ago.
My approach to get something similar as anova type 3 was adding `wald_test_terms`, mainly because I understood the theoretical background. (and I'm expanding score_test methods.)

**Comment by josef-pkt** [comment]
I'm reopening this. I should have a closer look to see whether we can do something.

I guess, allowing for comparing two or a sequence of models would be useful even without formulas.
(But that might correspond to a likelihood ratio type test (or comparing sum of squares) which assumes cov_type = nonrobust.

Type 1 anova only would really make sense if we have a meaningful sequence of regressor columns, e.g. only global polynomial terms like power polynomials or other numpy polynomial `vander`.
