### ISSUE TITLE
Possibility of musllinux wheels?

### ISSUE THREAD

**Issue by canton7** [statsmodels/statsmodels#9001]
Hi,

First of all, thank you so much for this amazing package.

You currently build wheels for manylinux. Unfortunately, Alpine linux (commonly used as the base for Docker containers) can't run manylinux wheels: manylinux compiles against the glibc standard library, whereas Alpine linux uses musl as its C standard library.

I appreciate I'm probably in the minority, but could you consider publishing musllinux wheels please?

Thank you!

**Comment by bashtage** [comment]
It probably can be done.  It looks like NumPy/Scipy/pandas all have musllinux wheels.  Probably won't be until he next (point) release.

**Comment by bashtage** [comment]
These are available of x86-64 on PyPi now. Can't build for arm since upstream wheels are missing.

**Comment by bashtage** [comment]
Sorry - not quite.

**Comment by canton7** [comment]
Fantastic, thank you so much!

**Comment by bashtage** [comment]
Should be up in the next few hours.  I built main not 0.14.0.

**Comment by bashtage** [comment]
Now it is finished.
