### ISSUE TITLE
Linear Regression fitting a model on single data point

### ISSUE THREAD

**Issue by nitenderk-darby** [statsmodels/statsmodels#9006]
#### Describe the bug

The Linear regression is fitting a model on a single data point. 
This should not happen as infinite lines can pass through a single point and the solution should be unique.
It is generating some coefficients based on the fitting. but at the same time it is failing to generate the summary

#### Code Sample

```python

    import statsmodels.api as sm

    target_variable = [7]
    independent_variables = [[5,12]]

    model = sm.OLS(target_variable, independent_variables).fit()

    model.summary()

```

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

The expected output should throw error stating there should be atleast 2 points to make a straight line. 

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>
NSTALLED VERSIONS
------------------
Python: 3.9.18.final.0
OS: Linux 6.2.0-33-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2 x86_64
byteorder: little
LC_ALL: None
LANG: en_IN
statsmodels
===========
Installed: 0.14.0 (/home/nitenderk/.venv/darby-c6-datascience-services/general/lib/python3.9/site-packages/statsmodels)
Required Dependencies
=====================
cython: Not installed
numpy: 1.26.0 (/home/nitenderk/.venv/darby-c6-datascience-services/general/lib/python3.9/site-packages/numpy)
scipy: 1.11.2 (/home/nitenderk/.venv/darby-c6-datascience-services/general/lib/python3.9/site-packages/scipy)
pandas: 2.1.1 (/home/nitenderk/.venv/darby-c6-datascience-services/general/lib/python3.9/site-packages/pandas)
    dateutil: 2.8.2 (/home/nitenderk/.venv/darby-c6-datascience-services/general/lib/python3.9/site-packages/dateutil)
patsy: 0.5.3 (/home/nitenderk/.venv/darby-c6-datascience-services/general/lib/python3.9/site-packages/patsy)
Optional Dependencies
=====================
matplotlib: Not installed
cvxopt: Not installed
joblib: Not installed
Developer Tools
================
IPython: Not installed
    jinja2: Not installed
sphinx: Not installed
    pygments: Not installed
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by bashtage** [comment]
statsmodels uses the psuedo inverse and so the numerical solution is always well-defined even when the regressors have reduced rank (as is the case here, 2 variable but only rank 1).  This is not a statistically sound estimate, and relies on a particular normalizatin to achieve uniqueness.  

This is intentional.
