### ISSUE TITLE
BUG: PCA scales eigenvalues incorrectly

### ISSUE THREAD

**Issue by vitormarquesr** [statsmodels/statsmodels#9026]
#### Describe the bug

Eigenvalues by `PCA` are bigger than those calculated by hand.

#### Code Sample, a copy-pastable example if possible

```python
from statsmodels.multivariate.pca import PCA
import pandas as pd
import numpy as np

# Data
df = pd.DataFrame([[1, 5, 3],
          [5, 12, 4],
          [7, 4, 10]])

# Calculating the correlation matrix
M = df.corr()

# PCA with standardize=True, so with regards to the correlation matrix
pca_df = PCA(df, standardize=True)

# Comparing the results of the two methods, they should be equal but are not
comp = pd.DataFrame({'statsmodels':pca_df.eigenvals, 'numpy': np.linalg.eigh(M)[0][::-1]})
comp
```

#### Possible root cause

https://github.com/statsmodels/statsmodels/blob/01b19d7d111b29c183f620ff0a949ef6391ff8ee/statsmodels/multivariate/pca.py#L451

I believe the cause of the problem in `eig` is related to the spectral decomposition being performed on `x.T.dot(x)` (`x` is the standardized data) which is not exactly the correlation matrix. This matrix is actually the number of factors times the correlation matrix, therefore the eigenvalues are scaled incorrectly by the number of factors. Somehow, this problem occurs for methods `nipals` and `svd` as well (As in the example).

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.11.3.final.0

statsmodels
===========

Installed: 0.14.0 (c:\Users\vmrod\anaconda3\envs\qslovenia-env\Lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.23.5 (c:\Users\vmrod\anaconda3\envs\qslovenia-env\Lib\site-packages\numpy)
scipy: 1.11.0 (c:\Users\vmrod\anaconda3\envs\qslovenia-env\Lib\site-packages\scipy)
pandas: 2.0.2 (c:\Users\vmrod\anaconda3\envs\qslovenia-env\Lib\site-packages\pandas)
    dateutil: 2.8.2 (c:\Users\vmrod\anaconda3\envs\qslovenia-env\Lib\site-packages\dateutil)
patsy: 0.5.3 (c:\Users\vmrod\anaconda3\envs\qslovenia-env\Lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.7.1 (c:\Users\vmrod\anaconda3\envs\qslovenia-env\Lib\site-packages\matplotlib)
    backend: module://matplotlib_inline.backend_inline 
...
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by bashtage** [comment]
This is by design.  The eigenvalue are of the inner-product, not inner product divided by the sample size. 

```python
comp.iloc[:2,0] / comp.iloc[:2,1]
```

```plaintext
0    3.0
1    3.0
dtype: float64
```
