### ISSUE TITLE
Negative binomial parameter "alpha"

### ISSUE THREAD

**Issue by Vlasovets** [statsmodels/statsmodels#9031]
Hi,

I experience some difficulties replicating `R` glm.nb() in Python, and I know that similar questions have been raised here and on Stackoverflow before, so sorry to raise it up again, but I'm trying to understand what's going on and would really appreciate if someone could help.

From this [discussion](https://github.com/statsmodels/statsmodels/issues/3339) I understood that stats implementation estimates both parameters of NB model jointly unlike the same model in R. And if one wants to get the dispersion parameter alpha (or in R notation Theta = 1/ alpha), he has to train the model for a range of alphas and choose the one corresponding to the minimal log-likelihood. 

I have tried this approach which unfortunately did not give me the same result as it is in R. 

So, I was wondering about parameter alpha in the output of a discrete model sm.NegativeBinomial() and why do we need to run the model in a loop in order to get Theta? 
In other words, why theta = 1 / mle_nb.params['alpha'] would be a wrong approach?

Here, is my example using both GLM and without GLM methods:

```
import statsmodels as stats
import statsmodels.api as sm

data = {
    's1': [3, 0, 0],
    's2': [0, 0, 3],
    's3': [2, 1, 2],
    's4': [2, 0, 0]
}

df = pd.DataFrame(data)

x = df.s1
intercept = np.ones(len(x))

n_samples = df.shape[1]
alphas = np.linspace(0, 10, n_samples)
llf = np.full(n_samples, fill_value=np.nan)

for i, alpha in enumerate(alphas):
    try:
        model = sm.GLM(x, intercept, family=sm.families.NegativeBinomial(alpha=alpha)).fit()
    except:
        continue
    llf[i] = model.llf

# Record the optimal value
alpha_opt = alphas[np.nanargmax(llf)]
dispersion = 1 / alpha_opt

mle_nb = sm.NegativeBinomial(x, exog=intercept).fit()
theta_nb = 1 / mle_nb.params['alpha']

print("Naive Estimated alpha (dispersion parameter):", theta_nb)
print("GLM Estimated alpha (dispersion parameter):", dispersion)
```
Output:
Optimization terminated successfully.
         Current function value: 1.334889
         Iterations: 5
         Function evaluations: 6
         Gradient evaluations: 6
Naive Estimated alpha (dispersion parameter): 0.3401267271501792
GLM Estimated alpha (dispersion parameter): 0.3

Thank you!

**Comment by josef-pkt** [comment]
what alpha or theta do you get in R?

check that R computes the MLE for alpha or theta.

What you are doing looks correct and should work correctly.
To get a more precise estimate using profile loglikelihood in GLM, you can use scipy minimize on a function that returns llf for given alpha (assuming there is overdispersion and alpha does not go to zero).

**Comment by Vlasovets** [comment]
thank you for your suggestion of using scipy minimize it resolved the issue:

here is the modified code:


```
import statsmodels as stats
import statsmodels.api as sm
import numpy as np

def neg_llf(alpha):
    try:
        model = sm.GLM(x, intercept, family=sm.families.NegativeBinomial(alpha=alpha)).fit()
        return -model.llf
    except:
        return np.inf

data = {
    's1': [3, 0, 0],
    's2': [0, 0, 3],
    's3': [2, 1, 2],
    's4': [2, 0, 0]
}

df = pd.DataFrame(data)

x = df.s1
intercept = np.ones(len(x))

# Initial guess for alpha
alpha_init = 1.0

# Find the optimal alpha
result = minimize(neg_llf, alpha_init, bounds=[(0, 10)])

# Get the optimal alpha and dispersion
alpha_opt = result.x[0]
dispersion = 1 / alpha_opt

mle_nb = sm.NegativeBinomial(x, exog=intercept).fit()
theta_nb = 1 / mle_nb.params['alpha']

print("Naive Estimated alpha (dispersion parameter):", theta_nb)
print("GLM Estimated alpha (dispersion parameter):", dispersion)
```
