### ISSUE TITLE
Missing values on my series after running SARIMA

### ISSUE THREAD

**Issue by pfrazeto1** [statsmodels/statsmodels#9049]
hello everybody, I am running a SARIMA modelo on data for Mcdonalds stock price as a university project, my data has no missing values, but after running a SARIMA, the graph shows lots of missing values on the original series, is this affecting my prediction? is this maybe a consecuence of the 0 values that appear after differencing the data in the model (p,d,q = 1,1,1 seasonal = 7,1,7,12)?

![image](https://github.com/statsmodels/statsmodels/assets/149453821/6d8275ec-3f58-4bdf-99ed-9c4ab0b796e5)

**Comment by bashtage** [comment]
It looks like you have daily data, and the missing values are weekends or other days where the market is closed.  Essentially your x data is not continuous.

**Comment by ChadFulton** [comment]
Closing as answered.
