### ISSUE TITLE
NotImplementedError in a custom state space model

### ISSUE THREAD

**Issue by rklees** [statsmodels/statsmodels#9055]
I defined a new class and get a NotImplementedError when fitting the model. The class is:
class IRW_plus_nonrecursive_cycle(sm.tsa.statespace.MLEModel):
    def __init__(self, endog, N, freq, dt):
      n = np.arange(0,N)
      t = n*dt
      t0 = np.min(t)
      a = np.cos(2*np.pi*freq*(t-t0))
      b = np.sin(2*np.pi*freq*(t-t0))
      exog = np.c_[a, b]
      k_states = 6
      k_posdef = 3 

      # Initialize the statespace
      super(IRW_plus_nonrecursive_cycle, self).__init__(
             endog, exog = exog, k_states = k_states, k_posdef = k_posdef, initialization = 'approximate_diffuse',
             loglikelihood_burn = k_states
      )

      # Initialize the system matrices
      self['design'] = np.zeros((1, k_states, N))
      self['design', 0, 0, :] = 1
      self['design', 0, 1, :] = 0
      self['design', 0, 2, :] = a
      self['design', 0, 3, :] = 0
      self['design', 0, 4, :] = b
      self['design', 0, 5, :] = 0     
      self['selection'] = np.zeros((k_states, k_posdef))
      self['selection', 1, 0] = self['selection', 3, 1] = self['selection', 5, 2] = 1
      self['transition'] = np.array([[1, 1, 0, 0, 0, 0],
                                       [0, 1, 0, 0, 0, 0],
                                       [0, 0, 1, 1, 0, 0],
                                       [0, 0, 0, 1, 0, 0],
                                       [0, 0, 0, 0, 1, 1],
                                       [0, 0, 0, 0, 0, 1]])   
      
      #Cache some indeces
      #self._state_cov_idx = ('state_cov',) + np.diag_indices(k_posdef)
      
      # Parameter names
      name_list = ['sigma2.irreg', 'sigma2.trend']
      name_list += ['sigma2.cycleAtrend']
      name_list += ['sigma2.cycleBtrend'] 
      self._param_names = name_list
    
      @property
      def start_params(self):
        params_start = [130, 0.1, 0.1, 0.1]
        return params_start
    
      def transform_params(self, unconstrained):
            constrained[self.positive_parameters] = (
                constrained[self.positive_parameters] ** 2
            )
            return constrained
    
      def untransform_params(self, constrained):
            unconstrained = constrained.copy()
            unconstrained[self.positive_parameters] = (
                unconstrained[self.positive_parameters] ** 0.5
            )
            return unconstrained
        
      def update(self, params, *args, **kwargs):
         params = super(IRW_plus_nonrecursive_cycle, self).update(params, *args, **kwargs)
         
         # Observation covariance   
         self['obs_cov', 0, 0] = params[0]
         # State covariance
         #self['state_cov'] = np.diag(params[1:3])
         self['state_cov', 0, 0] = params[1]
         self['state_cov', 1, 1] = params[2]
         self['state_cov', 2, 2] = params[3]

# Set-up the state space model
model = IRW_plus_nonrecursive_cycle(data['meas'], N, freq, dt)

# print some information about the state space model
#print(ssm.param_names)
#print(ssm.state_names)

# fit the state space model parameters and states
res = model.fit()
print(res.summary())

The error message is:
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[4], line 81
     74 model = IRW_plus_nonrecursive_cycle(data['meas'], N, freq, dt)
     76 # print some information about the state space model
     77 #print(ssm.param_names)
     78 #print(ssm.state_names)
     79 
     80 # fit the state space model parameters and states
---> 81 res = model.fit()
     82 print(res.summary())

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/tsa/statespace/mlemodel.py:650, in MLEModel.fit(self, start_params, transformed, includes_fixed, cov_type, cov_kwds, method, maxiter, full_output, disp, callback, return_params, optim_score, optim_complex_step, optim_hessian, flags, low_memory, **kwargs)
    530 """
    531 Fits the model by maximum likelihood via Kalman filter.
    532 
   (...)
    647 statsmodels.tsa.statespace.structural.UnobservedComponentsResults
    648 """
    649 if start_params is None:
--> 650     start_params = self.start_params
    651     transformed = True
    652     includes_fixed = True

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/statsmodels/tsa/statespace/mlemodel.py:1584, in MLEModel.start_params(self)
   1582     return self._start_params
   1583 else:
-> 1584     raise NotImplementedError

NotImplementedError: 

Any idea what went wrong?

**Comment by ChadFulton** [comment]
It's hard to tell from the source code you posted, but it looks as though your indentation is off.  The `def start_params` should not be a part of your `__init__` method, but it looks like you have it at the same indentation level as the last line of your `__init__` method (`self._param_names = name_list`).

**Comment by rklees** [comment]
That was the reason + that I did not define "constrained". Thanks for your fast response. Very much appreciated.

**Comment by ChadFulton** [comment]
No problem, and thanks for following up
