### ISSUE TITLE
Feature Request: Transformations interface

### ISSUE THREAD

**Issue by ParadaCarleton** [statsmodels/statsmodels#9057]
It would be great to have something like the `sklearn` transformation interface, where users can specify transformations like logarithms, power transforms, standardization, or variable encodings that can be applied prior to regression.

**Comment by josef-pkt** [comment]
can you reuse the ones from sklearn?

statsmodels does not have a pipeline.
The (almost) only way to preprocess data is in using formulas which `evals` function from user space.
The formula information also remembers those transforms for transforming exog in predict.

**Comment by ParadaCarleton** [comment]
> can you reuse the ones from sklearn?

I'd be happy to use those, if there were a way to plug sklearn pipelines into statsmodels, but unless I'm missing something I don't think they're compatible?

**Comment by josef-pkt** [comment]
closing as not planned

we have issues related to transforming exog, like #5347 and #1131.
However, those are specific cases we could be internally supported, We are not planning to add a pipeline. (that's not the focus for statistics)
