### ISSUE TITLE
How to establish the MSIH-AR model as the the statsmodels.api.tsa.MarkovAutoregression object uses the mean form（i.e., the deviation form） of the equation to implement the MS-AR model (i.e., the MSM-AR model) by default

### ISSUE THREAD

**Issue by nickcao123456** [statsmodels/statsmodels#9060]
Hello, I'm new in the Markov Switching autoregressive model. I need some help with implementing the MSIH-AR model in Python. This model requires introducing regime state variables into the intercept and error terms of the equation, as well as the heteroscedasticity in the error term. **However, the statsmodels.api.tsa.MarkovAutoregression object in Python uses the mean form（i.e., the deviation form） of the equation to implement the MS-AR model (i.e., the MSM-AR model) by default.** This makes me very confused. **How can I use statsmodels.api.tsa.MarkovAutoregression to implement the MSIH-AR model?**

**Comment by ChadFulton** [comment]
It's not clear to me what you're looking for - can you write the equations of the model you want to estimate? (GitHub supports Latex math now).

**Comment by nickcao123456** [comment]
Thanks for your reply~
I need to clarify my question. When I try to run one of the example codes on the statsmodels website https://www.statsmodels.org/stable/examples/notebooks/generated/markov_autoregression.html
```python
# Get the RGNP data to replicate Hamilton
dta = pd.read_stata("https://www.stata-press.com/data/r14/rgnp.dta").iloc[1:])
dta.index = pd.DatetimeIndex(dta.date, freq="QS")
dta_hamilton = dta.rgnp

# Plot the data
dta_hamilton.plot(title="Growth rate of Real GNP", figsize=(12, 3))

# Fit the model
mod_hamilton = sm.tsa.MarkovAutoregression(
    dta_hamilton, k_regimes=2, order=4, switching_ar=False
)
res_hamilton = mod_hamilton.fit()
```

By run this code which **sets the trend parameter equal to 'c' by default**, I implement a model with Markov-switching means like this known as MSM-AR model -a shorthand due to Krolzig (1997): 
<img width="551" alt="mean form" src="https://github.com/statsmodels/statsmodels/assets/79524971/f6a6ea4c-7636-4148-b247-84c060499ef6">
However, the MSIH-AR model I try to estimate is like this **with Markov-switching intercepts and variances but without Markov-switching means:**  



$$\begin{align}
y_t = a_{S_t} +  + \phi_{1, S_t}
        y_{t-1} + \dots +
        \phi_{p, S_t} y_{t-p} +
        \varepsilon_t \\
           \varepsilon_t \sim N(0, \sigma_{S_t}^2)
\end{align}$$

I try to run the following code which **sets trend parameter equal to 'n' to eliminate the mean effect and switching_variance=True**: 

```python
mod_hamilton = sm.tsa.MarkovAutoregression(
    dta_hamilton, k_regimes=2, order=4, trend='n', switching_ar=False, switching_variance=True
)
```
I guess I implement a model  with Markov-switching variances, unfortunately, without Markov-switching intercepts.
$$y_t - 0 = \sum_{i=1}^p \phi_i (y_{t-i} - 0) + \epsilon_{S_t}$$

Anyhow, I fail to implement the MSIH-AR model **with Markov-switching intercepts and variances but without Markov-switching means**. I was wondering if you could share your code or give me some guidance on how to code this model. I would really appreciate your assistance and I look forward to hearing from you soon. Thank you very much for your time and attention.

**Comment by nickcao123456** [comment]
I am trying to compare the performance of different forms of MS-AR models before running them on my data. Comparing the performance of different forms of MS-AR models before running them is a common practice in the literature. I am following the classification of MS-VAR models in 

> Krolzig, H.-M. 1997. Markov-switching vector autoregressions: Modelling, statistical inference and an application to the business cycle analysis. >

<img width="448" alt="0456cb9d733e31fbf7b39c6132936ee" src="https://github.com/statsmodels/statsmodels/assets/79524971/ff05f602-e9e3-4317-8fe6-b1386650ce9c">

**The attached figure is from this book, and although it is for MS-VAR models, I think it can be applied to MS-AR models as well.** 
It seems that statsmodels.api.tsa.MarkovAutoregression can only implement the models **in the first column of the figure (marked with a red circle)**. Is there a way to implement the other models and compare the performance? Thank you for your help and guidance.

**Comment by ChadFulton** [comment]
Thanks for clarifying.  Unfortunately we don't currently have implemented any state space Markov switching models, which I believe would be required for the models you're interested in.

(If you are interested in digging in and implementing this yourself, there was a start made on these models in a prior Google Summer of Code: https://github.com/statsmodels/statsmodels/pull/2921)

**Comment by ChadFulton** [comment]
Closing the issue as answered
