### ISSUE TITLE
SARIMAX.predict() exog

### ISSUE THREAD

**Issue by paullee42** [statsmodels/statsmodels#9061]
On SARIMAX.predict(), when you have an exog but the exog is only known today and in the past, how do you predict the endog's next 12 months off just the exog and data known through today?  Is that what the SARIMAX.predict() is doing as a default?  Example, my exog is SP500 price.  I do not know what it will be tomorrow, but I want to use the values through today as an exog to predict the next 12 months forward of my endog.

Or is SARIMAX.predict() wanting you to know what the future exog values will be for the 12 months into the future of the endog you are predicting?  Example, my exog is days  of the week.  I know today what day of the week things will happen on so I can fill in the future exog for the next 12 months to predict the endog for the same forward period.

And if the exog value is only known for today as in the SP500 example, will SARIMAX.forecast(steps = forecast_period, exog = exog[-forecast_period:]) result in an accurate modeled prediction of the 12 months ahead?  Is it by default calculating a single step 12 month ahead forecast.  Or is it trying to multistep off the exogs which in this case wouldn't be possible without predicting those exogs 1 step ahead as well.

Any help would be greatly appreciated!

**Comment by ChadFulton** [comment]
The SARIMAX model and forecasts are entirely conditional on given values of the exogenous variables, and the model performs iterative one-step-ahead forecasts, so you do need to provide future `exog` values when you forecast out of sample.

**Comment by paullee42** [comment]
Very much appreciated.  When using exog data that can only be known as of
today but will influence the endog in the months ahead, if I understand
correctly, SARIMAX.predict and SARIMAX.forecast would need that data to be
correctly shifted forward (reverse lagged)  and then fed into the exog
parameter both in evaluating and .fit() and also in the .predict() and
.forecast()?

I think a lot of people use these for manufacturing and production of
things type modeling.  If I understand correctly, if using something like a
profit margin to produce a good today that will be finished in 2 months,
then we would need to shift forward the exog by 2 months in all exogs
used.  We could use .forecast(steps = 2) for a 2 month forecast forward.
But we would not be able to SARIMAX.forecast() for anything past 2 months
forward since the exog is unknown past there?

I think my confusion is in the idea of if it's possible to use
SARIMAX.forecast() as a 1 step prediction where the 1 step is a 12 month
ahead forecast when the exog only influences 2 months ahead.   In theory,
the .forecast() can't go past the exogs forward predictability (reverse
lag) or the model runs out of data.

If I know all the exogs today and they have some influence on how the endog
reacts in the future, SARIMAX would not be able to give a 12 months 1 step
ahead forecast because the exog would be unknown.

Not sure if that makes sense.

**Comment by paullee42** [comment]
Just thinking of a better example.

Something like Crude oil.  The price of crude oil and steel today will
determine crude oil production and some time in the future between 3 to 6
months.  Crude oil production is endog.  Crude oil and steel price are
exog.

It would not be possible to use SARIMAX.forecast to predict the next 12
months crude production based on SARIMA Crude prices + today's current
crude oil and steel prices as the exog since the model will request a
future 12 months of exog that we would not know today?

Could be airlines sales endog and personal income today as exog as well.

**Comment by paullee42** [comment]
Highlighted below, that should say SARIMA of crude production, not prices.
Production being the endog

**Comment by ChadFulton** [comment]
If you think that a variable today influences prices 12 periods in the future, then you can create a model that uses the explanatory values lagged by 12 periods as `exog`. Then the last period from your training sample will use the exog from 12 period ago, and you can use the exog from 11 periods ago to the present as an argument for the `forecast` method.

But the bottom line is that the forecasts from `SARIMAX` are conditional on the `exog` values that you pass to the `forecast` method, and it does not provide any method for computing or estimating them.
