### ISSUE TITLE
in ADFuller test estimated lag length=0 !!

### ISSUE THREAD

**Issue by revolutionneur** [statsmodels/statsmodels#9079]
#### Describe the bug

[I some datasets when grid searching for the best SARIMA modeling, I satrted by determing the integration orders using ADFullet test and KPSS test, while examining the estimated lag legth. Surprisingly I've got so many exemple where lag length ==0.]

#### Code Sample, a copy-pastable example if possible

```python
![download](https://github.com/statsmodels/statsmodels/assets/57560787/9a029967-fc4c-45e3-b8df-843a8ff632ae)

# Your code here that produces the bug
# This example should be self-contained, and so not rely on external data.
# It should run in a fresh ipython session, and so include all relevant imports.
```
<details>

**Note**: As you can see, there are many issues on our GitHub tracker, so it is very possible that your issue has been posted before. Please check first before submitting so that we do not have to handle and close duplicates.

**Note**: Please be sure you are using the latest released version of `statsmodels`, or a recent build of `main`. If your problem has been fixed in an unreleased version, you might be able to use `main` until a new release occurs. 

**Note**: If you are using a released version, have you verified that the bug exists in the main branch of this repository? It helps the limited resources if we know problems exist in the current main branch so that they do not need to check whether the code sample produces a bug in the next release.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

[paste the output of ``import statsmodels.api as sm; sm.show_versions()`` here below this line]

</details>

**Comment by bashtage** [comment]
Going to close as it didn't look like this is a bug.  Feel free to post more detail if the answer above is not clear enough.

**Comment by revolutionneur** [comment]
Hi,
Thank you for the quick response,
Actually, the zero value is the estimated lag length from "adfuller.usedlag" after performing unit root test on the sample set. 
Or from the literature, the lag length must be at least =1

**Comment by bashtage** [comment]
The model is D y(t) = d0 + d1 t + d2 t^2 + p y(t-1) + g1 D y(t-1) + g2 D y(t-2) + ... + eps(t)

where D is the delta operator.  Lags 0 means that all of the g terms are excluded, but the key term p is always included.  The deterministic specification determines which of d0, d1 and d2 are included.
