### ISSUE TITLE
freq T not understood in STL decomposition

### ISSUE THREAD

**Issue by KurtP20** [statsmodels/statsmodels#9085]
My time series data of a temperature sensor has a frequency of 5 min and when I try to do a Seasonal-Trend decomposition using LOESS with `statsmodels.tsa.seasonal.STL(dummy, seasonal=288, robust=False)`, I get the error `ValueError: freq T not understood`. I have reproduced the error with the MVE below. It seems to me as if the 5 min (5T) interval is not understood by `statsmodel`. Using the same data with `sm.tsa.seasonal_decompose(dummy, model='additive', period=288)` works fine.

```python
import pandas as pd
import numpy as np
from statsmodels.tsa.seasonal import STL

# Generate a time series with a daily seasonality and a linear trend
np.random.seed(0)
n = 288 * 10  # 10 days of data with 5-minute intervals
t = pd.date_range(start='2020-01-01', periods=n, freq='5min')
seasonal_pattern = np.sin(2 * np.pi * np.arange(n) / 288)
trend = np.linspace(0, 1, n)
noise = np.random.normal(scale=0.5, size=n)
dummy = pd.Series(seasonal_pattern + trend + noise, index=t)

stl = STL(dummy, seasonal=288, robust=True)
stl_result = stl.fit()

stl_result.plot()
plt.show()
```

#### Expected Output

I expect no error message.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.12.0.final.0

statsmodels
===========

Installed: 0.14.0 (c:\Users\me\AppData\Local\anaconda3\envs\SB\Lib\site-packages\statsmodels)

</details>

**Comment by bashtage** [comment]
We don't know that to use for `T` automatically.  What is the length of a full period here?  288 (1 day)?  If so, set `period=288` 

I think you should be using

```python
stl = STL(dummy, period=288, robust=True)
```

**Comment by bashtage** [comment]
Closing as answered, but please feel free to respond if this isn't clear.

**Comment by KurtP20** [comment]
Ah, didn't understand the documentaion well enough. Specifying the `period` solved the problem. Thanks a lot!
