### ISSUE TITLE
0.14.1 release only on PyPI has wheels for Windows

### ISSUE THREAD

**Issue by thomasjpfan** [statsmodels/statsmodels#9093]
The latest [0.14.1](https://pypi.org/project/statsmodels/0.14.1/#files) wheels only contain wheels for Windows. The previous [0.14.0](https://pypi.org/project/statsmodels/0.14.0/#files) release had wheels for a wilder selection of platforms.

Was this an intended change?

**Comment by Pinky-Chaudhary** [comment]
+ 1 @bashtage can you please help, we are also facing the issue while installing statsmodel on Linux system with the new versions : 0.14.1
 ``` conda-env -c statsmodels/tsa/stl/_stl.c -o build/temp.linux-x86_64-cpython-39/statsmodels/tsa/stl/_stl.o
   error: command 'gcc' failed: No such file or directory
   ERROR: Failed building wheel for statsmodels```

**Comment by mitchell-gottlieb** [comment]
@Pinky-Chaudhary - we ran into the same issue with version 0.14.1. In the meantime, you could just pin your version to 0.14.0 which worked for us

**Comment by bashtage** [comment]
The remaining wheels should be up momentarily. Also should build fine form source tar.gz - it is tested in CI and I just checked in a clean venv and it worked as expected.
