### ISSUE TITLE
DOC: no docstrings describes diagnostic part of regression `summary`

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#9099]
I don't find a docstring that includes description and defintion summary info.

current point: I was not sure whether kurtosis is fisher or pearson, i.e. 0 or 3 in normal case.
It is pearson, normal = 3, after looking at the code in `jarque_bera`.

**Comment by luke396** [comment]
Hi @josef-pkt, I'd love to help improve the document. Could you provide more details? 

Do you think the page at https://www.statsmodels.org/devel/examples/notebooks/generated/regression_diagnostics.html#Regression-diagnostics needs a more detailed description of the data imported via URL? Or do you have other suggestions for improving the page?

**Comment by josef-pkt** [comment]
What I remember when I opened the issue, the missing docs are specifically for the `summary` results on linear regression.
For example in a Notes section in https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.RegressionResults.summary.html

The two top tables are mostly self explanatory. It's mainly the diagnostic bottom table that needs more description.

and/or a link to a notebook that explains the regression summary output.
I have seen something like that in a blog article some time ago, but don't remember where.

The regression_diagnostics.html doc notbook is more for what extra functions we have available for diagnostic and specification testing.
It's for functions that the user can call, but does not directly explain what the statistics in the summary table are besides normality.
jarque-bera also does not make it explicit that kurtosis is standard kurtosis and not excess kurtosis.
It's confusing because "kurtosis" is often used as name for excess kurtosis.

e.g. "kurtosis is the sample kurtosis, not the excess kurtosis. A sample from the normal distribution has kurtosis equal to 3."

Durbin Watson needs explanation that a value around 2 indicates no serial correlation.

asides:
Including Durbin Watson was a "econometrics tradition" from a very long time ago.
Ancient issue #87 but I never decided how we can improve it.

**Comment by josef-pkt** [comment]
I also just see that both diagnostic notebooks do not include autocorrelation tests
https://www.statsmodels.org/dev/stats.html#module-statsmodels.stats.stattools
