### ISSUE TITLE
Consider to remove numpy 2.0 caps from dev branch

### ISSUE THREAD

**Issue by bsipocz** [statsmodels/statsmodels#9104]
The nightly dev wheels currently have this cap, forcing downstream to workaround statsmodels (e.g. https://github.com/numpy/numpy-tutorials/issues/190#issuecomment-1865380467), while it's not clear where the blocking problems in library are.

(note, numpy 2.0 is getting close to its first RC (scheduled for end of Jan), so testing and getting compatible with it may be timely now anyway.)

**Comment by bashtage** [comment]
This has been fixed in #9106.
