### ISSUE TITLE
How to extract the data from plot_diagnostics?

### ISSUE THREAD

**Issue by mottarapp** [statsmodels/statsmodels#9109]
Hi, looking for help on how to extract the data using to plot the 4 charts that results from calling  "SARIMAXResults.plot_diagnostics" ?
for instance, the first chart on the left has the standardized residuals over time, I want to use this data to plot the standardized residuals against the fitted values. thanks

**Comment by bashtage** [comment]
You can follow the example [here](https://stackoverflow.com/questions/20130768/retrieve-xy-data-from-matplotlib-figure) to extract data from matplotlib lines.

**Comment by bashtage** [comment]
Alternatively you can looks at the code

https://github.com/statsmodels/statsmodels/blob/f5b6240404936eb819f3ca082a386c8bcae32a4d/statsmodels/tsa/statespace/mlemodel.py#L4543

to see what is used to produce the data that is then plotted.
