### ISSUE TITLE
Saved model does not predict given exogs

### ISSUE THREAD

**Issue by johnnyb1509** [statsmodels/statsmodels#9123]
#### Describe the bug

I have created an OLS models and save it as pickle file, then call it again and test if the predict function works properly. However, it does not work, even predict on the training data

#### Code Sample, a copy-pastable example if possible

```python
y = data_scaled[[target]]
X = data_scaled[[some features here]]

model = sm.OLS(y,sm.add_constant(X.astype(float)))
results = model.fit()
# Then save as pickle file
results.save("./models/test.pickle")

# After that, I load it again for inferencing
testload = sm.load('./models/test.pickle')

# Test on the same dataset
testload.predict(X.values[-1])

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
----> testload.predict(X.values[-1])

ValueError: shapes (1,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)
```

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.11.7.final.0
OS: Linux 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64
byteorder: little
LC_ALL: None
LANG: C.UTF-8

statsmodels
===========

Installed: 0.14.1 

Required Dependencies
=====================

cython: Not installed
numpy: 1.26.3 
scipy: 1.11.4
pandas: 2.1.4 
    dateutil: 2.8.2 
patsy: 0.5.6 

Optional Dependencies
=====================

matplotlib: 3.8.0
    backend: module://matplotlib_inline.backend_inline 
cvxopt: Not installed
joblib: 1.3.2 

Developer Tools
================

IPython: 8.20.0 
    jinja2: Not installed
sphinx: Not installed
    pygments: 2.17.2 
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by josef-pkt** [comment]
that's unrelated to pickling.

you used add_constant for the estimation data X but not for the predict data X, so shapes mismatch

**Comment by johnnyb1509** [comment]
> that's unrelated to pickling.
> 
> you used add_constant for the estimation data X but not for the predict data X, so shapes mismatch

oh thank you!
