### ISSUE TITLE
Long training times for relatively simple SARIMA model

### ISSUE THREAD

**Issue by sebiwtt** [statsmodels/statsmodels#9153]
Hey everyone,

I am currently working on a comparison between online learning models and their batch-learning counterparts. During some experiments I conducted, I ran an evaluation of the SARIMA model available in the statsmodels library (to compare it to an online learning SARIMA variant from the "River" library. 

I got huge numbers when measuring the model's time to fit the training set. My data is simple traffic data from a backbone router (measuring gb/s). Each data point represents the average gb/s over a whole hour, and a pattern repeats daily (-> daily seasonality). My training set contains 800 instances. The performance I am getting is okay, but it took 1min 14s on average to fit the data (I ran it 100 times and averaged the results), whereas the online variant took 200ms on the same machine.

Here is the code snippet of the model I defined:
```python
p, d, q = 6, 0, 6
P, D, Q, s = 2, 1, 2, 24 
sarima_model = sm.tsa.SARIMAX(train, order=(p, d, q), seasonal_order=(P, D, Q, s), initialization='approximate_diffuse')
```

The model became faster when I decreased the value of the variable s.

I would appreciate any ideas on why this happens (or maybe it is expected; I don't know) since I am working on this problem for my thesis :D 

Thanks,
Sebi

**Comment by ChadFulton** [comment]
(Closing this question as answered, but please feel free to add comments if you have more questions)

**Comment by sebiwtt** [comment]
Thank you very much for the clear explanation 😃

**Comment by sebiwtt** [comment]
@ChadFulton Thank you very much for the clear explanation 😃
