### ISSUE TITLE
`ARIMAResults.simulate` doesn't respect `random_state`

### ISSUE THREAD

**Issue by adaitche** [statsmodels/statsmodels#9162]
#### Describe the bug

The method `ARIMAResults.simulate` doesn't seem to respect the parameter `random_state`. It returns different results for a fixed random state parameter.

#### Code Sample

```python
from statsmodels.tsa.arima.model import ARIMA
import numpy as np

x = np.random.randn(100)
mod = ARIMA(x, order=(1, 0, 0))
res = mod.fit()

for i in range(5):
    print(i, res.simulate(1, random_state=7))
```

#### Expected Output

For me, this prints a different number for each of the iterations. My expectation, however, is that the same number is generated on each invocation of `simulate` because `random_state` is fixed.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.10.12.final.0
OS: Darwin 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 arm64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8

statsmodels
===========

Installed: 0.14.1 (/Users/adaitche/homebrew/lib/python3.10/site-packages/statsmodels)

Required Dependencies
=====================

cython: Not installed
numpy: 1.24.1 (/Users/adaitche/homebrew/lib/python3.10/site-packages/numpy)
scipy: 1.10.0 (/Users/adaitche/homebrew/lib/python3.10/site-packages/scipy)
pandas: 1.5.3 (/Users/adaitche/homebrew/lib/python3.10/site-packages/pandas)
    dateutil: 2.8.2 (/Users/adaitche/homebrew/lib/python3.10/site-packages/dateutil)
patsy: 0.5.6 (/Users/adaitche/homebrew/lib/python3.10/site-packages/patsy)

Optional Dependencies
=====================

matplotlib: 3.6.3 (/Users/adaitche/homebrew/lib/python3.10/site-packages/matplotlib)
    backend: MacOSX
cvxopt: Not installed
joblib: Not installed

Developer Tools
================

IPython: 8.9.0 (/Users/adaitche/homebrew/lib/python3.10/site-packages/IPython)
    jinja2: 3.1.2 (/Users/adaitche/homebrew/lib/python3.10/site-packages/jinja2)
sphinx: Not installed
    pygments: 2.14.0 (/Users/adaitche/homebrew/lib/python3.10/site-packages/pygments)
pytest: 7.4.3 (/Users/adaitche/homebrew/lib/python3.10/site-packages/pytest)
virtualenv: Not installed

</details>

**Comment by ChadFulton** [comment]
Thanks for reporting this. The problem appears to be that the `initial_state` is drawn without using the provided `random_state`: https://github.com/statsmodels/statsmodels/blob/main/statsmodels/tsa/statespace/mlemodel.py#L3648-L3656
