### ISSUE TITLE
DOC: ztest documentation says that it returns pvalue of the t-test .

### ISSUE THREAD

**Issue by Shakoth** [statsmodels/statsmodels#9169]
Just a minor mistype I think. Was a little confused when read that z-test function returns t-test p-value.
From the ztest docstring:

Returns
-------
tstat : float
    test statistic
pvalue : float
    pvalue of the t-test

**Comment by luke396** [comment]
Hi @Shakoth, could you please paste the specific document page you mentioned? If it still exists, I'd like to fix it.

**Comment by Shakoth** [comment]
Sure, here it is:
https://www.statsmodels.org/dev/generated/statsmodels.stats.weightstats.ztest.html

The docstring in the code says the same (my version is 0.14.0)
