### ISSUE TITLE
A new release with NumPy 2.0 support?

### ISSUE THREAD

**Issue by rgommers** [statsmodels/statsmodels#9194]
Hey all, it'd be great to get a new release with numpy 2.0 support out in the near future. My understanding of the current situation is this:
- the current stable release, 0.14.1, was released in December with a `numpy < 2` upper bound
- gh-9106 fixed a lot of compatibility issues and dropped the `< 2` bound in `main`
- what is needed now is changing the build-dependency in `pyproject.toml` to say `numpy>=2.0.0rc1` (no change to runtime dependencies needed) - see https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395 - and then making a new release which is built against numpy 2.0.0rc1

Could this be done, and would it be 0.14.2 or 0.15.0?

**Comment by bashtage** [comment]
Should probably backport the necessary changes to 0.14 and release an update for 0.14.

**Comment by josef-pkt** [comment]
> build-dependency in pyproject.toml to say numpy>2.0.0rc1 

But then we cannot update/build statsmodels in an old python requirement that uses numpy < 2.
A new point release would break the build environment in an old python environment.

Or do I see this incorrectly?   

I did not have to recompile statsmodels in some time because we didn't have changes in c/cython code, or at least, I did not break my current running of the `main` code.

**Comment by josef-pkt** [comment]
Also, AFAICS, numpy 2.0 is not even released, so I will not get a official numpy version (winpython) in some time.

**Comment by josef-pkt** [comment]
Ok, might still work.

What is build isolation? Does project.toml affect regular pip build in the system python?

**Comment by bashtage** [comment]
SciPy is build-time dependency.  Is SciPy (as used during build) also required to be NumPy 2 comparible?

For now I am assuming it is, and key bits of pyproject look like:

```
    "setuptools>=69.0.2; python_version>='3.12'",
    "setuptools>=63.4.3",
    "cython>=3.0.10,<4",  # Sync with CYTHON_MIN_VER in setup
    "numpy>=2.0.0rc1,<3",
    "scipy>=1.13",
    "setuptools_scm[toml]>=8,<9"
```

**Comment by rgommers** [comment]
> But then we cannot update/build statsmodels in an old python requirement that uses numpy < 2. A new point release would break the build environment in an old python environment.

You can an env with numpy 1.2x installed and build against that older numpy still with `pip install . --no-build-isolation`

> What is build isolation? Does project.toml affect regular pip build in the system python?

Build isolation means "set up a fresh virtual environment with the dependencies in pyproject.toml and nothing else, then build a wheel to install, then throw away that build env". If you want to use system Python and your existing env, you have to pass ` --no-build-isolation` - that's been the case for as long as you've had `pyproject.toml` with a `[build-system]` entry.

> SciPy is build-time dependency. Is SciPy (as used during build) also required to be NumPy 2 comparible?

Yes, SciPy 1.13.0 was just released and supports numpy 2.0. Using `"scipy>=1.13",` is right, and yes all your constraints look correct @bashtage 

> Also, AFAICS, numpy 2.0 is not even released, so I will not get a official numpy version (winpython) in some time.

That's the joys of dealing with a C API. You have to release before numpy 2.0 is out, because otherwise all your users will get broken envs.

**Comment by bashtage** [comment]
Mostly complete in #9195 .  Dealing with the break in the linkage between `dtype=int` and C `long` was a bit of a pain.  Only shows up on Windows when building with NumPy 2 and running on NumPy 1.

**Comment by rgommers** [comment]
I had a browse of the changes - huge diff, but mostly tool-generated. The `long`/`int64` thing, yeah that's one of the harder things to deal with unfortunately, but should be worth it to do so.

**Comment by rgommers** [comment]
Awesome, thanks @bashtage!
