### ISSUE TITLE
Jupyter Notebook kernel crash with new VSCODE update

### ISSUE THREAD

**Issue by mitchellggreenhalgh** [statsmodels/statsmodels#9196]
#### Describe the bug

I was using statsmodels perfectly fine until VSCODE updated to 1.88.0. Now whenever I try to run models, the kernel crashes.

#### Code Sample

```python
import statsmodels.api as sm
import numpy as np

print(sm.__version__)  # 0.14.1
print(np.__version__)  # 1.26.4

y = np.array([67, 70, 72])
X = np.array([[2,3,4],[7,8,9]]).T

sm.OLS(y, X).fit()
```
<details>

Here is the jupyter error: 

`[error] Disposing session as kernel process died ExitCode: 3228369022, Reason: 0.00s - Debugger warning: It seems that frozen modules are being used, which may`

Every other package in the conda environment works so far. Only running models has caused the crash. Both the formulas api and regular api cause crashes. I've reinstalled the package, restarted VSCODE, restarted my computer, and nothing has changed.

</details>

If the issue has not been resolved, please file it in the issue tracker.

#### Expected Output

statsmodels.regression.linear_model.RegressionResults Object

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.11.8.final.0

statsmodels
===========

Installed: 0.14.1 (\miniconda3\envs\webpy\Lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: 3.0.10 (\miniconda3\envs\webpy\Lib\site-packages\Cython)
numpy: 1.26.4 (\miniconda3\envs\webpy\Lib\site-packages\numpy)
scipy: 1.12.0 (\miniconda3\envs\webpy\Lib\site-packages\scipy)
pandas: 2.2.1 (\miniconda3\envs\webpy\Lib\site-packages\pandas)
    dateutil: 2.9.0 (\miniconda3\envs\webpy\Lib\site-packages\dateutil)
patsy: 0.5.6 (\miniconda3\envs\webpy\Lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.8.3 (\miniconda3\envs\webpy\Lib\site-packages\matplotlib)
    backend: module://matplotlib_inline.backend_inline 
cvxopt: Not installed
joblib: 1.3.2 (\miniconda3\envs\webpy\Lib\site-packages\joblib)

Developer Tools
================

IPython: 8.22.2 (\miniconda3\envs\webpy\Lib\site-packages\IPython)
    jinja2: 3.1.3 (\miniconda3\envs\webpy\Lib\site-packages\jinja2)
sphinx: Not installed
    pygments: 2.17.2 (\miniconda3\envs\webpy\Lib\site-packages\pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by bashtage** [comment]
What happens if you run the notebook directly in jupyter notebook or jupyter lab? I strongly suspect this is a vscode issue.

**Comment by mitchellggreenhalgh** [comment]
It still crashes in Jupyter. However, I ran the code in another environment that has statsmodels in it and it ran fine. The kernel must've corrupted during the update or something. I'll look into restoring the environment. Thanks.

**Comment by mitchellggreenhalgh** [comment]
Forgot to close in last comment, ignore
