### ISSUE TITLE
proportions_ztest function variance calculation is wrong

### ISSUE THREAD

**Issue by Hanchao-Zhang** [statsmodels/statsmodels#9201]
p_pooled = np.sum(count) * 1. / np.sum(nobs) in proportions_ztest should be p_pooled = value instead of sample probability.

here is the reference for proportional test where the std was calculated using reference probability instead of sample probability

https://online.stat.psu.edu/statprogram/reviews/statistical-concepts/proportions

**Comment by josef-pkt** [comment]
it's not wrong, it's just another method

see
https://stats.stackexchange.com/questions/447462/why-does-the-proportions-ztest-function-in-statsmodels-produce-different-values including comments by me
and issue #6488

I'm closing this as duplicate.
we can use #6488 for additional discussion
