### ISSUE TITLE
bug: 0.14.2 seems to have broken my dependency graph

### ISSUE THREAD

**Issue by inigohidalgo** [statsmodels/statsmodels#9214]
#### Describe the bug

The new release is setting `numpy>=2.0.0rc1`. Does this mean that from 0.14.2 we are expected to have that release candidate as the minimum dependency for numpy?

This has broken some CI pipelines on our end. It is a simple fix to pin statsmodels to 0.14.1, but I'm not sure if this breaking change was intentional.

Thanks

**Comment by bashtage** [comment]
NumPy 2 is needed for building.  The runtime requirements are NumPy 1.22.3+.

There has been a substantial bump in requirements NumPy 2 binary comparability -> NumPy >= 1.22.3 -> Scipy 1.8.0

**Comment by bashtage** [comment]
Also since NumPy 2 is only available for Python 3.9+, this statsmodels is also Python 3.9+

**Comment by inigohidalgo** [comment]
Sorry @bashtage I cannot seem to reproduce after refreshing the cache and recreating my venv from scratch.

In case it comes up in the future, the resolver was getting stuck somewhere with the packages

- `packaging`
- `cython`
- `numpy 2.0.0rc1`

and some others.

For context, I am using `uv` to install dependencies, so it's possible there was some weird glitch.
