### ISSUE TITLE
Failed to install on android 

### ISSUE THREAD

**Issue by Duuckjing** [statsmodels/statsmodels#9236]
```
(phantom) ~/phantom/statsmodels $ LDFLAGS=" -lnpymath" python -m pip install . --no-build-isolation                               Processing /data/data/com.termux/files/home/phantom/statsmodels    Preparing metadata (pyproject.toml) ... done                   Requirement already satisfied: numpy<3,>=1.22.3 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from statsmodels==0.0.0) (1.26.4)                                                 Requirement already satisfied: scipy!=1.9.2,>=1.7.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from statsmodels==0.0.0) (1.13.0)                                             Requirement already satisfied: pandas!=2.1.0,>=1.3.0 in /data/data/com.termux/files/home/phantom/lib/python3.11/site-packages (from statsmodels==0.0.0) (2.2.2)                                    Requirement already satisfied: patsy>=0.5.6 in /data/data/com.termux/files/home/phantom/lib/python3.11/site-packages (from statsmodels==0.0.0) (0.5.6)                                             Requirement already satisfied: packaging>=21.3 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from statsmodels==0.0.0) (24.0)                                                    Requirement already satisfied: python-dateutil>=2.8.2 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.3.0->statsmodels==0.0.0) (2.9.0.post0)               Requirement already satisfied: pytz>=2020.1 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.3.0->statsmodels==0.0.0) (2024.1)                              Requirement already satisfied: tzdata>=2022.7 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from pandas!=2.1.0,>=1.3.0->statsmodels==0.0.0) (2024.1)                            Requirement already satisfied: six in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from patsy>=0.5.6->statsmodels==0.0.0) (1.16.0)                                                Building wheels for collected packages: statsmodels                Building wheel for statsmodels (pyproject.toml) ... error        error: subprocess-exited-with-error                                                                                               × Building wheel for statsmodels (pyproject.toml) did not run successfully.                                                       │ exit code: 1                                                   ╰─> [19 lines of output]                                             running bdist_wheel                                              running build                                                    running build_py                                                 running build_ext                                                building 'statsmodels.tsa.stl._stl' extension                    aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DCYTHON_TRACE_NOGIL=0 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/core/include -I/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/core/include -I/data/data/com.termux/files/home/phantom/include -I/data/data/com.termux/files/usr/include/python3.11 -c statsmodels/tsa/stl/_stl.c -o build/temp.linux-aarch64-cpython-311/statsmodels/tsa/stl/_stl.o                                statsmodels/tsa/stl/_stl.c:21649:17: warning: using floating point absolute value function 'fabs' when argument is of integer type [-Wabsolute-value]                                               21649 |     __pyx_v_r = fabs(((__pyx_v_j + 1) - __pyx_v_xs));                                                                           |                 ^                                       statsmodels/tsa/stl/_stl.c:21649:17: note: use function 'labs' instead                                                             21649 |     __pyx_v_r = fabs(((__pyx_v_j + 1) - __pyx_v_xs));                                                                           |                 ^~~~                                           |                 labs                                    1 warning generated.                                             aarch64-linux-android-clang -shared -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v1/sysroot/usr/lib -L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--no-as-needed,-landroid-support,--as-needed -L/home/builder/.termux-build/_cache/android-r26b-api-24-v1/sysroot/usr/lib -lnpymath build/temp.linux-aarch64-cpython-311/statsmodels/tsa/stl/_stl.o -L/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/core/include/../lib -L/data/data/com.termux/files/usr/lib -lnpymath -lpython3.11 -o build/lib.linux-aarch64-cpython-311/statsmodels/tsa/stl/_stl.cpython-311.so                                                   ld.lld: error: unable to find library -lnpymath                  ld.lld: error: unable to find library -lnpymath                  aarch64-linux-android-clang: error: linker command failed with exit code 1 (use -v to see invocation)                             error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1                          [end of output]                                                                                                               note: This error originates from a subprocess, and is likely not a problem with pip.                                              ERROR: Failed building wheel for statsmodels                   Failed to build statsmodels                                      ERROR: Could not build wheels for statsmodels, which is required to install pyproject.toml-based projects
```
It mentioned npymath, but numpy is already installed.

**Comment by bashtage** [comment]
You need to have numpy >= 2.0.0rc1 available and installed.  Realistically you need to install all of the dependencies and the install with --no-build-isolation on Android.

**Comment by bashtage** [comment]
Ultimately this isn't some that that stats models can fix.  If you have trouble linking against NumPy, you might want to open an issue there.

**Comment by Duuckjing** [comment]
> Ultimately this isn't some that that stats models can fix.  If you have trouble linking against NumPy, you might want to open an issue there. 

Now I have installed numpy2.0.0rc1, but the error long has changed into a more horrible one
`running build_ext                                                        building 'statsmodels.tsa.exponential_smoothing._ets_smooth' extension                                                                            aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DCYTHON_TRACE_NOGIL=0 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/include -I/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/core/include -I/data/data/com.termux/files/usr/lib/python3.11/site-packages/numpy/_core/include -I/data/data/com.termux/files/usr/include/python3.11 -c statsmodels/tsa/exponential_smoothing/_ets_smooth.c -o build/temp.linux-aarch64-cpython-311/statsmodels/tsa/exponential_smoothing/_ets_smooth.o                     statsmodels/tsa/exponential_smoothing/_ets_smooth.c:34821:312: error: call to undeclared library function 'cpowf' with type '_Complex float (_Complex float, _Complex float)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
       34821 |     *((__pyx_t_float_complex *) ( /* dim=0 */ (__pyx_v_yhat.data + __pyx_t_24 * __pyx_v_yhat.strides[0]) )) = __Pyx_c_sum_float(__Pyx_c_prod_float((*((__pyx_t_float_complex *) ( /* dim=1 */ (( /* dim=0 */ (__pyx_v_xhat.data + __pyx_t_18 * __pyx_v_xhat.strides[0]) ) + __pyx_t_19 * __pyx_v_xhat.strides[1]) ))), __Pyx_c_pow_float((*((__pyx_t_float_complex *) ( /* dim=1 */ (( /* dim=0 */ (__pyx_v_xhat.data + __pyx_t_20 * __pyx_v_xhat.strides[0]) ) + __pyx_t_21 * __pyx_v_xhat.strides[1]) ))), __pyx_v_phi)), (*((__pyx_t_float_complex *) ( /* dim=1 */ (( /* dim=0 */ (__pyx_v_xhat.data + __pyx_t_22 * __pyx_v_xhat.strides[0]) ) + __pyx_t_23 * __pyx_v_xhat.strides[1]) ))));                                                        |                                                                                                                                                                                                                                                                                                                        ^                                            statsmodels/tsa/exponential_smoothing/_ets_smooth.c:3343:43: note: expanded from macro '__Pyx_c_pow_float'                                         3343 |         #define __Pyx_c_pow_float(a, b)  (cpowf(a, b))                 |                                           ^                      statsmodels/tsa/exponential_smoothing/_ets_smooth.c:34821:312: note: include the header <complex.h> or explicitly provide a declaration for 'cpowf'                                                                        statsmodels/tsa/exponential_smoothing/_ets_smooth.c:3343:43: note: expanded from macro '__Pyx_c_pow_float'                                         3343 |         #define __Pyx_c_pow_float(a, b)  (cpowf(a, b))                 |                                           ^                      statsmodels/tsa/exponential_smoothing/_ets_smooth.c:35442:316: error: call to undeclared library function 'cpow' with type '_Complex double (_Complex double, _Complex double)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]                   35442 |     *((__pyx_t_double_complex *) ( /* dim=0 */ (__pyx_v_yhat.data + __pyx_t_24 * __pyx_v_yhat.strides[0]) )) = __Pyx_c_sum_double(__Pyx_c_prod_double((*((__pyx_t_double_complex *) ( /* dim=1 */ (( /* dim=0 */ (__pyx_v_xhat.data + __pyx_t_18 * __pyx_v_xhat.strides[0]) ) + __pyx_t_19 * __pyx_v_xhat.strides[1]) ))), __Pyx_c_pow_double((*((__pyx_t_double_complex *) ( /* dim=1 */ (( /* dim=0 */ (__pyx_v_xhat.data + __pyx_t_20 * __pyx_v_xhat.strides[0]) ) + __pyx_t_21 * __pyx_v_xhat.strides[1]) ))), __pyx_v_phi)), (*((__pyx_t_double_complex *) ( /* dim=1 */ (( /* dim=0 */ (__pyx_v_xhat.data + __pyx_t_22 * __pyx_v_xhat.strides[0]) ) + __pyx_t_23 * __pyx_v_xhat.strides[1]) ))));                                                 |                                                                                                                                                                                                                                                                                                                            ^                                        statsmodels/tsa/exponential_smoothing/_ets_smooth.c:3381:44: note: expanded from macro '__Pyx_c_pow_double'                                        3381 |         #define __Pyx_c_pow_double(a, b)  (cpow(a, b))
            |                                            ^                     statsmodels/tsa/exponential_smoothing/_ets_smooth.c:35442:316: note: include the header <complex.h> or explicitly provide a declaration for 'cpow'                                                                         statsmodels/tsa/exponential_smoothing/_ets_smooth.c:3381:44: note: expanded from macro '__Pyx_c_pow_double'
       3381 |         #define __Pyx_c_pow_double(a, b)  (cpow(a, b))                 |                                            ^                     2 errors generated.                                                      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1                                          [end of output]                                                                                                                               note: This error originates from a subprocess, and is likely not a problem with pip.                                                              ERROR: Failed building wheel for statsmodels                           Failed to build statsmodels                                              ERROR: Could not build wheels for statsmodels, which is required to install pyproject.toml-based projects`

**Comment by bashtage** [comment]
Hard to say - sounds like you are missing a header for `<complex.h>`. Does android support this?

**Comment by bashtage** [comment]
Looks like this is resolved.

**Comment by Duuckjing** [comment]
@bashtage finally I installed it from source as you can see in the link above.
Yes, Finally I copied the version file to my android and it works fine.
At first installing from source seems to lack the _version.py, and after I add it and the installed it again, it works fine.
![Screenshot_2024-04-29-10-45-16-286_com.termux.jpg](https://github.com/statsmodels/statsmodels/assets/154486750/24202626-ae21-47a5-aa78-ee9db06b4e08)

**Comment by Duuckjing** [comment]
Installed statsmodels with numpy 1.26.4, and actually when using numpy 2.0.0rc1, many other packages are not supported such as pandas and scikit-learn, don't know whether it's the case on windows

**Comment by bashtage** [comment]
The correct procedure is to build stats models using NumPy 2 and Scioy 1.13 or later. You can then run it against NumPy 1.26 without warnings with lots of other packages.

**Comment by bashtage** [comment]
>  finally I installed it from source as you can see in the link above.
> Yes, Finally I copied the version file to my android and it works fine.
> At first installing from source seems to lack the _version.py, and after I add it and the installed it again, [it works fine](https://github.com/termux/termux-packages/issues/19960)
> 
> 

Version is dynamically greatest as part of install and isn't part of the code in the repo.

**Comment by Duuckjing** [comment]
Yep, but without _version.py it seems to have error on android because it is not automatically generated...... no way, I have to do homework now
