### ISSUE TITLE
ENH: proportion_confint only has two-sided confidence intervals, no "alternative" option

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#9239]
see
https://stats.stackexchange.com/questions/646445/multinomial-one-sided-confidence-intervals

same for multinomial_proportions_confint

I think for proportion_confint it should be just one interval at 2*alpha, except for "beta-test" which is minlike, and the one-sided will correspond to one side of equal-tail intervals.

I don't have a guess on one-sided interval for multinomial_proportions_confint. (too long ago). But it might be based on an equal-tail derivation.

**Comment by mcmrc** [comment]
@josef-pkt 
Hi, Josef.
I read the thread and agree that the one-sided interval is the same as one side of the two-sided interval for doubled alpha in a binomial distribution.
Can I take this issue on propotion_confint to add an option to explicitly get one-sided ci?

**Comment by josef-pkt** [comment]
Yes, we want to add the `alternative` option and include one sided intervals.

Note, "binomtest" will have different one-sided intervals which should be easy to compute.
The will be the same as for the central, equal-tail binom test.

pull request would be welcome.

**Comment by mcmrc** [comment]
@josef-pkt 
Hi, I made a PR. I'd be glad if you especially check the logic of binom_test and jeffreys.
