### ISSUE TITLE
ENH: confint_poisson only has two-sided confidence intervals

### ISSUE THREAD

**Issue by mcmrc** [statsmodels/statsmodels#9254]
https://www.statsmodels.org/dev/generated/statsmodels.stats.rates.confint_poisson.html

confint_poisson does not have an one-sided confidence interval option.
As mentioned in #9249, add a new option 'alternative' to confint_poisson.

Maybe same for multinomial_proportions_confint, later.

**Comment by josef-pkt** [comment]
for docstrings: 
I will come up with a short explanation for the meaning and direction of alternative option for confidence intervals. Then, we can copy it to all confint functions that have the alternative keyword.

**Comment by josef-pkt** [comment]
one sided confint for multinomial_proportions_confint will, most likely, not be obvious and we might have to check with the original articles.

**Comment by mcmrc** [comment]
For docstrings, should we create a new issue and PR like 'DOCS: XXX'?
