### ISSUE TITLE
[BUG] - ModuleNotFoundError: No module named 'numpy.char'

### ISSUE THREAD

**Issue by marcopeix** [statsmodels/statsmodels#9288]
#### Describe the bug

Running the line `from statsmodels.tsa.stattools import acf` returns `ModuleNotFoundError: No module named 'numpy.char'`

Actually, just running `import statsmodels` returns the same error.

I installed statsmodels v.0.14.2 via pip.

**Comment by bashtage** [comment]
If you are using NumPy 2 you must use 0.14.3.

**Comment by bashtage** [comment]
If you are using NumPy 2 you must use 0.14.3. closing as answered.
