### ISSUE TITLE
Suggesting updates on the doc of `statsmodels.tsa.ar_model.AutoReg`

### ISSUE THREAD

**Issue by DocInspector** [statsmodels/statsmodels#9304]
Hi,

We are an academic team of software engineering researchers from a university working on automated program analysis techniques to improve API documentation quality, ultimately contributing to improving data science software development practices. we would like to keep anonymity for the purpose of double-blind paper reviewing.

We discover an inconsistency issue between documentation and code in the class [`statsmodels.tsa.ar_model.AutoReg`](https://www.statsmodels.org/devel/generated/statsmodels.tsa.ar_model.AutoReg.html#statsmodels.tsa.ar_model.AutoReg). As mentioned in the description of parameter `deterministic`:

> **deterministic** : DeterministicProcess
A deterministic process. If provided, trend and seasonal are ignored. **A warning is raised if trend is not “n” and seasonal is not False.**

This means that the warning is triggered only when both conditions are met at the same time. However, the most relevant source code snippet looks like this:

```python
if deterministic is not None and (
    self._trend != "n" or self._seasonal
):
    warnings.warn(
        'When using deterministic, trend must be "n" and '
        "seasonal must be False.",
        SpecificationWarning,
        stacklevel=2,
    )
```

The actual code execution logic is that as long as one of the conditions is met, a warning will be triggered.

Maybe you can change the line in the aforementioned doc to "A warning is raised if trend is not “n” **or** seasonal is not False.".

**Comment by bashtage** [comment]
Happy to accept a PR.
