### ISSUE TITLE
mixing different types of smoothers in GAM

### ISSUE THREAD

**Issue by samdeoxys1** [statsmodels/statsmodels#9305]
Suppose I have a non-periodic and a periodic regressor. How can I include both in the GAM, one using BSplines and the other using CyclicCubicSplines? 

Thanks you!

**Comment by josef-pkt** [comment]
currently not possible #8929

closing as duplicate

**Comment by josef-pkt** [comment]
duplicate

**Comment by josef-pkt** [comment]
stupid github now only allows closing as either "completed" or "not planned"
