### ISSUE TITLE
BUG: UECM.from_ardl residuals

### ISSUE THREAD

**Issue by defra-ma** [statsmodels/statsmodels#9323]
#### Describe the bug

When using statsmodels.tsa.ardl.UECM.from_ardl, the residuals method of the resulting UECM subtracts the fitted values of the UECM (i.e., in differences) from the endogenous value of the ARDL (i.e., in levels). This flows through into the methods for testing residuals (serial correlation, etc.).

As a stop-gap, users can perform tests on the residuals from the ARDL. The UECM should have the same residuals as the equivalent ARDL, since no transformation is made to the residuals in deriving the UECM from the ARDL.

#### Code Sample, a copy-pastable example if possible

```python
import statsmodels.api as sm
import pandas as pd
import numpy as np
import matplotlib as mp

# simulate cointegrated series
w = [1,-1]
N = 100
S = np.ones([N,len(w)])*2000
kappa = 20
sigma = 20
dt = 1/N
corr = 0.6
C = np.ones([len(w),len(w)])*corr+(1-corr)*np.eye(len(w))
for t in range(1,N):
    eps = np.random.multivariate_normal([0]*len(w),C)
    for i in range(len(w)):
        si = 0
        for j in range(len(w)):
            si += w[j]/w[i]*S[t-1,j]
        S[t,i] = S[t-1,i] - kappa*dt*si + sigma**2*np.sqrt(dt)*eps[i]
        
mp.pyplot.plot(S)
mp.pyplot.show()

# fit ardl and uecm
ardl = sm.tsa.ARDL(S[:,[0]], 1, S[:,[1]], 1)
ardlfit = ardl.fit()
uecm = sm.tsa.UECM.from_ardl(ardl)
uecmfit = uecm.fit()

# observed
uecmfit.resid

# expected
ardlfit.resid

# check equality of UECM endog variable and observation in levels
S[:,0].squeeze() == uecmfit.model.endog.squeeze()

```

**Comment by bashtage** [comment]
Definitely not the correct behavior w.r.t. residuals. I took a look and I don't think this is realted to `from_ardl`, since you get the same by directly constructing using `UECM`

**Comment by defra-ma** [comment]
> Definitely not the correct behavior w.r.t. residuals. I took a look and I don't think this is realted to `from_ardl`, since you get the same by directly constructing using `UECM`

I'm not familiar enough with the package internals, but if there's no situation where `UECM` would ever be passed an already-differenced dependent variable, differencing that in the `resid` method should address this.

**Comment by bashtage** [comment]
Thanks for reporting this.  It has been fixed in main.

**Comment by defra-ma** [comment]
Many thanks
