### ISSUE TITLE
CITATION.cff

### ISSUE THREAD

**Issue by kubatjanf** [statsmodels/statsmodels#9328]
Hi, could you add citation to your repository?

It would be awesome!

Thanks, Jan

**Comment by bashtage** [comment]
Citation of what?  Or a method to cite statsmdoels?

**Comment by bashtage** [comment]
https://www.statsmodels.org/stable/index.html#citation

**Comment by kubatjanf** [comment]
I found the citation later, but also having a diract option from repository would be maybe easier: 
![image](https://github.com/user-attachments/assets/c12c6d13-4a49-4741-b450-a749d2bb99bd)
