### ISSUE TITLE
dataframe not printing after UnobservedComponents

### ISSUE THREAD

**Issue by joaogoliveira1** [statsmodels/statsmodels#9344]
#### Describe the bug

Hey. I was trying out the tutorial you have on [https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_tvpvar_mcmc_cfa.html]
However, when I try to plot inflation together with simulated trends, inflation does not appear in the plots. I tried printing the inflation variable but it gives an error "cannot use a string pattern on a bytes-like object". However, when I print it just after the data import it works. Is this supposed to happen? Is dta.infl being modified by sm.tsa.UnobservedComponents? See code below

#### Code Sample

```python
from importlib import reload
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

from scipy.stats import invwishart, invgamma

# Get the macro dataset
dta = sm.datasets.macrodata.load_pandas().data
dta.index = pd.date_range('1959Q1', '2009Q3', freq='QS')

## when I print the data here, it works
print(dta.infl)

# Construct a local level model for inflation
mod = sm.tsa.UnobservedComponents(dta.infl, 'llevel')

## when I print it here, it says TypeError: cannot use a string pattern on a bytes-like object
print(dta.infl)
```

#### Expected Output

I expected dta.infl to be printed in the terminal

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

INSTALLED VERSIONS

Python: 3.12.5.final.0

statsmodels

Installed: 0.14.2

Required Dependencies

cython: Not installed
numpy: 2.1.0 
scipy: 1.14.1 
pandas: 2.2.2
    dateutil: 2.9.0.post0 
patsy: 0.5.6 

Optional Dependencies

matplotlib: 3.9.2 
    backend: tkagg 
cvxopt: Not installed
joblib: Not installed

**Comment by bashtage** [comment]
I can't reproduce. I get:

```python
print(dta.infl)
```

```
1959-01-01    0.00
1959-04-01    2.34
1959-07-01    2.74
1959-10-01    0.27
1960-01-01    2.31
              ...
2008-07-01   -3.16
2008-10-01   -8.79
2009-01-01    0.94
2009-04-01    3.37
2009-07-01    3.56
Freq: QS-JAN, Name: infl, Length: 203, dtype: float64
1959-01-01    0.00
1959-04-01    2.34
1959-07-01    2.74
1959-10-01    0.27
1960-01-01    2.31
              ...
2008-07-01   -3.16
2008-10-01   -8.79
2009-01-01    0.94
2009-04-01    3.37
2009-07-01    3.56
Freq: QS-JAN, Name: infl, Length: 203, dtype: float64
```

Here are my versions.


```
➜ ~  pip list
Package           Version                  Editable project location
----------------- ------------------------ -------------------------
asttokens         2.4.1
colorama          0.4.6
contourpy         1.2.1
cycler            0.12.1
decorator         5.1.1
execnet           2.1.1
executing         2.0.1
fonttools         4.53.1
iniconfig         2.0.0
ipython           8.26.0
jedi              0.19.1
kiwisolver        1.4.5
matplotlib        3.9.2
matplotlib-inline 0.1.7
numpy             2.1.0
packaging         24.1
pandas            2.2.2
parso             0.8.4
patsy             0.5.6
pillow            10.4.0
pip               24.2
pluggy            1.5.0
prompt_toolkit    3.0.47
pure_eval         0.2.3
Pygments          2.18.0
pyparsing         3.1.2
pytest            8.3.2
pytest-xdist      3.6.1
python-dateutil   2.9.0.post0
pytz              2024.1
scipy             1.14.1
setuptools        72.1.0
six               1.16.0
stack-data        0.6.3
statsmodels       0.15.0.dev331+geef6ad3d5 C:\git\statsmodels
traitlets         5.14.3
tzdata            2024.1
wcwidth           0.2.13
wheel             0.43.0
```

**Comment by bashtage** [comment]
Also can't reproduce in jupyter lab

![image](https://github.com/user-attachments/assets/0767c1e9-8884-4c36-9de1-bd9ea5e7a34b)

**Comment by joaogoliveira1** [comment]
Im using statsmodels 0.14.2 in Pycharm. I confirmed your result in Jupyter, which also runs 0.14.2.
I reinstalled the statsmodels package in Pycharm and retried running the code. Apparently it works now. Dont know what happened but that seems to be the fix.
