### ISSUE TITLE
Unexpected ValueError while running STL with 'seasonal' > 7

### ISSUE THREAD

**Issue by sidbab94** [statsmodels/statsmodels#9345]
#### Describe the bug

I tried executing tsa.seasonal.STL() on a sample time-series with a non-default value greater than 7 for the parameter `seasonal`.
When providing anything other than 7, this raises the following error:

`ValueError: seasonal must be an odd positive integer >= 3`

#### Code Sample, a copy-pastable example if possible
```
def stl_decomposition(
        data: pd.DataFrame,
        periodicity = 288,
        seasonal_smooth_ws: int = 12
):
    stl = STL(data, period=periodicity, seasonal=8)
    result = stl.fit()
    seasonal, trend, resid = result.seasonal, result.trend, result.resid
    return seasonal, trend, resid

```
#### Expected Output

I expected STL to produce seasonal, trend and residual components, or atleast for the STL() instance to be created with the non-default parameters provided.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``
<details>
INSTALLED VERSIONS
------------------
Python: 3.9.0.final.0
statsmodels
===========
Installed: 0.13.5 (C:\Users\S\AppData\Local\pypoetry\Cache\virtualenvs\gws-datascience-SO0blG9k-py3.9\lib\site-packages\statsmodels)
Required Dependencies
=====================
cython: Not installed
numpy: 1.26.4 (C:\Users\S\AppData\Local\pypoetry\Cache\virtualenvs\gws-datascience-SO0blG9k-py3.9\lib\site-packages\numpy)
scipy: 1.13.0 (C:\Users\S\AppData\Local\pypoetry\Cache\virtualenvs\gws-datascience-SO0blG9k-py3.9\lib\site-packages\scipy)
pandas: 2.2.2 (C:\Users\S\AppData\Local\pypoetry\Cache\virtualenvs\gws-datascience-SO0blG9k-py3.9\lib\site-packages\pandas)
    dateutil: 2.9.0.post0 (C:\Users\S\AppData\Local\pypoetry\Cache\virtualenvs\gws-datascience-SO0blG9k-py3.9\lib\site-packages\dateutil)
patsy: 0.5.6 (C:\Users\S\AppData\Local\pypoetry\Cache\virtualenvs\gws-datascience-SO0blG9k-py3.9\lib\site-packages\patsy)
Optional Dependencies
=====================
matplotlib: 3.8.4 (C:\Users\S\AppData\Local\pypoetry\Cache\virtualenvs\gws-datascience-SO0blG9k-py3.9\lib\site-packages\matplotlib)
    backend: TkAgg 
cvxopt: Not installed
joblib: 1.4.2 (C:\Users\S\AppData\Local\pypoetry\Cache\virtualenvs\gws-datascience-SO0blG9k-py3.9\lib\site-packages\joblib)
Developer Tools
================
IPython: Not installed
    jinja2: 3.1.4 (C:\Users\SiddharthBaburaj\AppData\Local\pypoetry\Cache\virtualenvs\gws-datascience-SO0blG9k-py3.9\lib\site-packages\jinja2)
sphinx: Not installed
    pygments: 2.18.0 (C:\Users\S\AppData\Local\pypoetry\Cache\virtualenvs\gws-datascience-SO0blG9k-py3.9\lib\site-packages\pygments)
pytest: 7.4.4 (C:\Users\S\AppData\Local\pypoetry\Cache\virtualenvs\gws-datascience-SO0blG9k-py3.9\lib\site-packages\pytest)
virtualenv: 20.26.1 (C:\Users\S\AppData\Local\pypoetry\Cache\virtualenvs\gws-datascience-SO0blG9k-py3.9\lib\site-packages\virtualenv)

</details>

**Comment by bashtage** [comment]
Seasonal needs to be oddnn

**Comment by bashtage** [comment]
Seasonal needs to be odd.  This is a requirement of STL.

**Comment by sidbab94** [comment]
Oops sorry seemed to have missed that detail. Just curious, could you please point out why it has to be an odd integer?

**Comment by bashtage** [comment]
It is just that way in the STL code.  You could consider the original paper if you want to see if the author provides an explanation.

**Comment by bashtage** [comment]
Closing as answered.
