### ISSUE TITLE
STY: Move to 88 characters per line

### ISSUE THREAD

**Issue by bashtage** [statsmodels/statsmodels#9347]
statsmodels should move to 88 characters per line which is consistent with NumPy and pandas (and probably SciPy).  This said, the new limit is only for new code, no mass scale re-formats.

@josef-pkt @ChadFulton @jseabold @kshedden  thoughts?

**Comment by josef-pkt** [comment]
ok with me (giving in to peer pressure and updated conventions that don't cost much)

https://github.com/scipy/scipy/pull/19461
https://mail.python.org/archives/list/scipy-dev@python.org/thread/OXI3Q3DJCPQYJZHMVPAW6I22UBFVXUY2/#JDHHSQEADZUX4FGJ72OX6YSOOLYJ6M7R

**Comment by ChadFulton** [comment]
I am in favor of this, thanks @bashtage!
