### ISSUE TITLE
Pass-through method for multitest.multipletests

### ISSUE THREAD

**Issue by davidaarmstrong** [statsmodels/statsmodels#9352]
Currently, `statsmodels.stats.multitest.multipletests` can employ several methods for adjusting p-values.  It would be nice if an option existed for unadjusted p-values as well.  This could have two possible uses.  This would have pedagogical value as those teaching with these tools could show the consequences of not adjusting p-values.

**Comment by josef-pkt** [comment]
I'm not clear about the purpose.
The user already has the uncorrected p-values, so I don't see what we can add.

**Comment by davidaarmstrong** [comment]
I was writing a function for showing some multiple comparisons.  Rather than an if-else on the type of adjustment, I thought it might be useful to have all p-values pass through the multiple test function, like `p.adjust()` does in R.  I'm primarily an R programmer dabbling in python, so I think I was hoping to replicate the code I had written in R.  I'll close the issue now.

**Comment by josef-pkt** [comment]
reopening

undecided,  but possible
Even if it's not really needed, it would be cheap to add (similar to R p.adjust)
