### ISSUE TITLE
segmentation fault when running Logit(...).fit()  after connection to cloudera with jdbc driver

### ISSUE THREAD

**Issue by matteogrolla** [statsmodels/statsmodels#9367]
#### Describe the bug
The following sequence of operation ends with a segmentation fault

1) establish a connection to Impala db
    (part of Cloudera platform) through a JDBC driver (that runs on JVM)
2) perform a logistic regression with statsmodels
    using  sm.Logit(y_ga_regr_train_n, X_ga_regr_train_n).fit()

My hp is that the regression operation does an unsafe memory allocation which collides with the buffers used to communicate to impala.

#### Code Sample, a copy-pastable example if possible

import jpype
import pandas as pd
import numpy as np
import statsmodels.api as sm
from utils.connections import crea_connessione_impala
import jaydebeapi

resources_dir = os.path.join(os.getcwd(), "../resources")
args = [
    f'-Djava.security.auth.login.config={resources_dir}/jaas.conf',
    f'-Djava.security.krb5.conf={resources_dir}/krb5.conf',
    '-Djavax.security.auth.useSubjectCredsOnly=false',
    f'-DkeytabPath={resources_dir}'
    ]
jpype.addClassPath(f"{resources_dir}/ImpalaJDBC42.jar")
jvm_path = jpype.getDefaultJVMPath()
jpype.startJVM(jvmpath=jvm_path, *args)

impala_jdbc_path = resources_dir
conn = jaydebeapi.connect(jclassname="com.cloudera.impala.jdbc.Driver",
                            url=f'jdbc:impala://<hostname>:<port>/default;AuthMech=1;KrbRealm=<realm>;KrbHostFQDN=<fqdn>;KrbServiceName=impala')

def calcolo_beta(segmento_pav_train_n, list_best_regressor_ga_segmenton):
    X_ga_regr_train_n = segmento_pav_train_n[list_best_regressor_ga_segmenton]
    X_ga_regr_train_n = sm.add_constant(X_ga_regr_train_n)
    y_ga_regr_train_n = segmento_pav_train_n['bonis']
    log_reg_ga_n = sm.Logit(y_ga_regr_train_n, X_ga_regr_train_n).fit()
    return log_reg_ga_n

segmento_pav_train_1 = pd.read_pickle(<training set path>)
list_best_regressor_ga_segmento1 = [<comma separated regressor names>]

print("inizio calcolo beta")
log_reg_ga_1 = calcolo_beta(segmento_pav_train_1, list_best_regressor_ga_segmento1)
print("fine calcolo beta")

#### Expected Output

inizio calcolo beta
fine calcolo beta

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

inizio calcolo beta
Segmentation fault

#### dependencies 

JayDeBeApi==1.2.3
└── JPype1 [required: Any, installed: 1.2.1]
statsmodels==0.14.1
├── numpy [required: >=1.18,<2, installed: 1.24.4]
├── packaging [required: >=21.3, installed: 24.1]
├── pandas [required: >=1.0,!=2.1.0, installed: 2.0.3]
│   ├── numpy [required: >=1.20.3, installed: 1.24.4]
│   ├── python-dateutil [required: >=2.8.2, installed: 2.9.0.post0]
│   │   └── six [required: >=1.5, installed: 1.16.0]
│   ├── pytz [required: >=2020.1, installed: 2024.1]
│   └── tzdata [required: >=2022.1, installed: 2024.1]
├── patsy [required: >=0.5.4, installed: 0.5.6]
│   ├── numpy [required: >=1.4, installed: 1.24.4]
│   └── six [required: Any, installed: 1.16.0]
└── scipy [required: >=1.4,!=1.9.2, installed: 1.10.1]
    └── numpy [required: >=1.19.5,<1.27.0, installed: 1.24.4]

any version of JVM

**Comment by bashtage** [comment]
Which version of statsmodels? 

I would be very shocked if there is a memory allocation issue. If there is, it is almost certainly upstream of statsmodels (either NumPy or Blas). There is no compiled code from statsmodels in that model (only upstream). I suspect that it is more likely a threading issue. 

You should probably limit the number of threads used by BLAS using the cloud version of  `export OPENBLAS_NUM_THREADS=2` or `export MKL_NUM_THREADS=2`. By default, these BLAS libraries can ask for as many threads as there are vCPUs visible.  In high CPU count systems this can be a lot. Moreover, each thread requires a decent chunk of memory.

**Comment by matteogrolla** [comment]
Hi Kevin,
    in the last section of the issue i reported the dependencies, here are
the one from statsmodels  (output from pipdeptree)

statsmodels==0.14.1
├── numpy [required: >=1.18,<2, installed: 1.24.4]
├── packaging [required: >=21.3, installed: 24.1]
├── pandas [required: >=1.0,!=2.1.0, installed: 2.0.3]
│ ├── numpy [required: >=1.20.3, installed: 1.24.4]
│ ├── python-dateutil [required: >=2.8.2, installed: 2.9.0.post0]
│ │ └── six [required: >=1.5, installed: 1.16.0]
│ ├── pytz [required: >=2020.1, installed: 2024.1]
│ └── tzdata [required: >=2022.1, installed: 2024.1]
├── patsy [required: >=0.5.4, installed: 0.5.6]
│ ├── numpy [required: >=1.4, installed: 1.24.4]
│ └── six [required: Any, installed: 1.16.0]
└── scipy [required: >=1.4,!=1.9.2, installed: 1.10.1]
└── numpy [required: >=1.19.5,<1.27.0, installed: 1.24.4]

 I installed numpy from pip, so it should be compiled with OpenBlas, but
neither thread limiting seems to work
here is the full output after setting the env vars

***@***.***:~/Cerved/Projects/CPM/btb-score/test$ export
MKL_NUM_THREADS=2
***@***.***:~/Cerved/Projects/CPM/btb-score/test$ export
OPENBLAS_NUM_THREADS=2
***@***.***:~/Cerved/Projects/CPM/btb-score/test$ python
test_segfault.py
/home/matteo/.pyenv/versions/b2b-score/lib/python3.8/site-packages/paramiko/pkey.py:82:
CryptographyDeprecationWarning: TripleDES has been moved to
cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be
removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/home/matteo/.pyenv/versions/b2b-score/lib/python3.8/site-packages/paramiko/transport.py:219:
CryptographyDeprecationWarning: Blowfish has been moved to
cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be
removed from this module in 45.0.0.
  "class": algorithms.Blowfish,
/home/matteo/.pyenv/versions/b2b-score/lib/python3.8/site-packages/paramiko/transport.py:243:
CryptographyDeprecationWarning: TripleDES has been moved to
cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be
removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
log4j:WARN No appenders could be found for logger
(com.cloudera.impala.jdbc42.internal.apache.thrift.transport.TSaslTransport).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for
more info.
inizio calcolo beta
Segmentation fault
***@***.***:~/Cerved/Projects/CPM/btb-score/test$

Il giorno gio 19 set 2024 alle ore 16:46 Kevin Sheppard <
***@***.***> ha scritto:

**Comment by matteogrolla** [comment]
Without establishing the connection to impala, the regression works fine.
Establishing the connection through a pure python library: impyla, the
regression works fine  (but java implementation is much faster on
insertmany)
There's plenty of RAM (more than 16GB) and the training set in pkl format
is less than 7MB

Matteo

Il giorno gio 19 set 2024 alle ore 16:56 Matteo Grolla <
***@***.***> ha scritto:

**Comment by bashtage** [comment]
Aer you running the process locally or remotely? You might need to do something special to pass environmental variables to be visible in the process that is running the code. I used to work with Spark and there was a particular way to pass environmental variables there - setting the variables becore I launched my session in my terminal had no effect. 

What your last message tells us is that it is something specific to the way you are using statsmodels since th code works as expected in simpler environments. I don't think there is much we can do.  You might try stackoverflow or a board more specific to the way you are trying to run the code. 

The next thinkg I would try is using threadpoolctl

https://github.com/joblib/threadpoolctl

Run your code in a block like

```
from threadpoolctl import threadpool_limits

with threadpool_limits(limits=1, user_api='blas'):
    ... crashing code here ...
```

**Comment by matteogrolla** [comment]
I found some kind of explanation and a couple of workarounds:

the cause of the problem seems the same as the one decrribed here
https://github.com/jpype-project/jpype/issues/808

---workaround 1:
export OPENBLAS_NUM_THREADS=1

with blas single threaded I have no problems
2 threads -> seg fault

---workaround 2:
shrink java stack size

on the list of arguments given to jpype to start the JVM set
'-Xss2M'
which sets the stack size to 2 MB

Es.
jpype.addClassPath(f"{resources_dir}/ImpalaJDBC42.jar")
jvm_path = jpype.getDefaultJVMPath()
jpype.startJVM(jvmpath=jvm_path, ['-Xss2M'])

with this setting you don't need any env var to limit blas thread

**Comment by bashtage** [comment]
Ok. Going to close since it is a Java stack size memory management issue.
