### ISSUE TITLE
Cannot install 0.14.4 in python 3.11 slim bullseye Docker container

### ISSUE THREAD

**Issue by khaume** [statsmodels/statsmodels#9380]
#### Describe the bug

Installing 0.14.4 fails in my python 3.11 slim bullseye Docker container. 0.14.3 does not fail.

The error is 

`/usr/local/include/python3.11/Python.h:23:12: fatal error: stdlib.h: No such file or directory`

#### Expected Output

Expected to be able to install the newer version

**Comment by bashtage** [comment]
The wheels aren't all up yet.  Once they are It will work as expected.

**Comment by bashtage** [comment]
All wheels are up now
