### ISSUE TITLE
statsmodels.api.distributions.ECDF modifies base data in place

### ISSUE THREAD

**Issue by DeeFourCee-exe** [statsmodels/statsmodels#9383]
#### Describe the bug

When fitting an ECDF on a column of a Pandas dataframe, the column in sorted in place by value ascending, irrespective of the index of the dataframe and the dataframe's other columns.

Here is an example:
Example df before ECDF: 
![image](https://github.com/user-attachments/assets/98e3e54f-23f4-4a97-8cfe-b28794def73c)

Example df after ECDF:
![image](https://github.com/user-attachments/assets/eaa19550-7e10-4940-8325-6673c85d066c)

It can be clearly seen that the column we ran ECDF on was sorted in place, putting it out of sync with the rest of the dataframe and distorting the dataset.

#### Code Sample, a copy-pastable example if possible

```python
import pandas as pd
import numpy as np
import statsmodels.api as sm

# Start with a dataframe of values and dates
now = pd.to_datetime('2024-01-01')
weeks = 2
testdata = pd.DataFrame(columns=['dates', 'values', 'othervalues'])
testdata['dates'] = pd.date_range(start=now, periods=weeks*7, freq='D')

# Put random data in values and othervalues
testdata['values'] = np.random.randint(0, 100, size=(weeks*7))
testdata['othervalues'] = np.random.randint(0, 100, size=(weeks*7))

# Display the df to show the original order
display(testdata)

# Generate ECDF
ecdf = sm.distributions.ECDF(testdata['values'])

# Show that the data has been sorted even though no assignment has been made
display(testdata)
```
<details>
Did not see an issue for this, closed or open, in the tracker

Python version: 3.12.7 
Pandas version: 2.2.3
Numpy version: 2.1.2
Statsmodels version: 0.14.4

</details>

#### Expected Output

Expected behavior is that Pandas dataframe column should not be modified in place by ecdf function. Since there is no assignment of anything back to the original dataframe, the original should be untouched. All assignment is to the new ecdf object.

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

<details>

INSTALLED VERSIONS
------------------
Python: 3.12.7.final.0

statsmodels
===========

Installed: 0.14.4 (c:\Users\David\anaconda3\envs\doses\Lib\site-packages\statsmodels)

Required Dependencies
=====================

cython: 3.0.11 (c:\Users\David\anaconda3\envs\doses\Lib\site-packages\Cython)
numpy: 2.1.2 (c:\Users\David\anaconda3\envs\doses\Lib\site-packages\numpy)
scipy: 1.14.1 (c:\Users\David\anaconda3\envs\doses\Lib\site-packages\scipy)
pandas: 2.2.3 (c:\Users\David\anaconda3\envs\doses\Lib\site-packages\pandas)
    dateutil: 2.9.0.post0 (c:\Users\David\anaconda3\envs\doses\Lib\site-packages\dateutil)
patsy: 0.5.6 (c:\Users\David\anaconda3\envs\doses\Lib\site-packages\patsy)

Optional Dependencies
=====================

matplotlib: 3.9.2 (c:\Users\David\anaconda3\envs\doses\Lib\site-packages\matplotlib)
    backend: module://matplotlib_inline.backend_inline 
cvxopt: Not installed
joblib: 1.4.2 (c:\Users\David\anaconda3\envs\doses\Lib\site-packages\joblib)

Developer Tools
================

IPython: 8.28.0 (c:\Users\David\anaconda3\envs\doses\Lib\site-packages\IPython)
    jinja2: Not installed
sphinx: Not installed
    pygments: 2.18.0 (c:\Users\David\anaconda3\envs\doses\Lib\site-packages\pygments)
pytest: Not installed
virtualenv: Not installed

</details>

**Comment by josef-pkt** [comment]
In my old python/numpy/pandas environment, the dataframes are the same before and after ecdf.

The first two lines of ECDF are

```
x = np.array(x, copy=True)
x.sort()
```

can you check this for `x = testdata['values']` ?

What's the dtype of `testdata['values']` ?

either the behavior of numpy or pandas has changed in recent versions.

**Comment by josef-pkt** [comment]
numpy `array` docstring for `copy` options includes
"
Note that any copy of the data is shallow, i.e., for arrays with object dtype, the new array will point to the same objects.
"

which sounds like it's possible to have dtype problem between pandas and numpy.

**Comment by bashtage** [comment]
Tjamls for reporting.  np.array(PANDAS OBJECT) has gotten tougher to predict in recent versions as the CoW behavior has been implemented.

**Comment by bashtage** [comment]
The source of this issue is here: pandas-dev/pandas#57739
