### ISSUE TITLE
Interpretation of ggplot with line='45' parameter without fit = True

### ISSUE THREAD

**Issue by quant12345** [statsmodels/statsmodels#9387]
![norm](https://github.com/user-attachments/assets/c04644ee-167a-40f3-9783-801447f6ac99)

```
from scipy.stats import shapiro, kstest, jarque_bera, normaltest, norm
import matplotlib.pyplot as plt
import statsmodels.api as sm
import numpy as np

arr = [-8.5044, -7.1797, -5.4707, -4.6184, -4.5501, -4.2101, -4.1536, -4.0476, -3.8106, -3.7008,
       -3.6945, -3.6069, -3.468, -3.3366, -3.1668, -3.1258, -2.75, -2.6924, -2.497, -2.4168, -2.3217,
       -2.2436, -2.1468, -1.9389, -1.7493, -1.7377, -1.715, -1.6625, -1.5748, -1.4691, -1.2166,
       -1.1327, -1.0225, -0.9817, -0.959, -0.8627, -0.7509, -0.6627, -0.5959, -0.59, -0.5179, -0.5176,
       -0.4341, -0.4323, -0.4036, -0.3947, -0.2786, -0.131, -0.1242, -0.053, 0.1272, 0.14, 0.1439,
       0.3039, 0.3133, 0.3148, 0.4198, 0.5225, 0.561, 0.6601, 0.7113, 0.7156, 0.7357, 0.8004, 0.8717,
       0.9677, 1.1765, 1.187, 1.2718, 1.3771, 1.4697, 1.4815, 1.5578, 1.6279, 1.7556, 1.8794, 2.0358,
       2.0681, 2.1657, 2.2384, 2.3769, 2.4695, 2.6826, 2.7119, 2.7256, 2.8448, 3.0968, 3.2088, 3.2584,
       3.579, 3.8901, 4.0136, 4.2478, 4.5352, 4.7729, 4.9473, 5.0372, 5.3055, 6.7692, 7.5642]
arr = np.array(arr)

print('shapiro', shapiro(arr).pvalue)
print('kstest', kstest(arr, 'norm').pvalue)
print('jarque_bera', jarque_bera(arr).pvalue)
print('normaltest', normaltest(arr).pvalue)


fig, (ax1, ax2) = plt.subplots(nrows=2)
sm.qqplot(arr, line ='45', fit=True, ax=ax1)
sm.qqplot(arr, line ='45', ax=ax2)
ax1.legend(['fit=True'])
ax2.legend(['no fit'])

plt.show()
```

I have come across several examples on the Internet using qqplot with the `line = '45'` parameter, and the `fit = True` parameter is not used. On the graph, the points intersect the line at approximately the same place (as in the lower picture), and it is concluded that the data is not normally distributed. I assume that this is not the case? I have conducted four tests on the data, and three of them show that the data is normally distributed. Although if you normalize the data, then `kstest `also gives more than 0.05(I'm not too sure about this, as I've only recently started studying statistics).

On the upper picture, `line = '45'` with `fit = True`.
If the above is true, why use `line = '45'` without `fit = True`?

**Comment by bashtage** [comment]
If your data was already transformed so that it was standard normal, say by some other procedure, and you do not want to do additional fitting, you should use `fit=False`.

**Comment by josef-pkt** [comment]
to clarify more

there are two different null hypothesis

- data is distributed N(0, 1), fit=False, hypothesis is that data is **standard** normal distributed
- data is distributed N(mu, sigma), fit=True, hypothesis is that data is normal distributed for some mu and sigma (and we use an estimate for mu and sigma that matches the data). This is the same as using the standard normal (fit=False) test on z-scored data except for axes labeling.

**Comment by quant12345** [comment]
@bashtage @josef-pkt thanks for the detailed explanation.
