### ISSUE TITLE
Version 0.15.0 Release Timeline?

### ISSUE THREAD

**Issue by shaunporwal** [statsmodels/statsmodels#9420]
Hi! 

I wrote a package (dcurves) that depends on statsmodels, and I wanted to include support for python 3.12. However, that introduces some issues with the latest released statsmodels version (0.14.4). The dev version (0.15.0) works perfectly however. Do you know when you are thinking of making a new release to PyPI? 

Thank you!

**Comment by bashtage** [comment]
What is wrong with 0.14.4?

**Comment by bashtage** [comment]
No real target date for 0.15.x.  If important, might be easier to backport to 0.14.5.

**Comment by shaunporwal** [comment]
I was actually able to fix the errors I was seeing with 0.14.4, and now it works great. I initially though 0.14.4 was not compatible with Python 3.12 happy to learn I was wrong. Thank you!
