### ISSUE TITLE
Standard Deviation in Power Test and Sample Size Limit

### ISSUE THREAD

**Issue by quant12345** [statsmodels/statsmodels#9426]
1.To obtain the effect size, the difference in sample means is divided by the pooled standard deviation of the samples. If I use the standard deviation of the samples, the effect size is too large. And when I check the power, the results do not converge. I know that you can get an approximate standard deviation `std(population) = std(sample) * np.sqrt(N)` and if I use this then the power analysis gives similar results. Am I doing it right by transforming the sample standard deviation?

2.Power analysis gives a minimum sample size.  Suppose I selected a sample size based on the power analysis, but got lower power.  What should be the next steps, increase the sample size?
But if I increase the sample size infinitely, I still increase the power all the way to 1. And here again a similar situation as with p-value by increasing the sample size I eventually reach a value less than 0.05 (I asked about this [here](https://stats.stackexchange.com/questions/656828/does-the-risk-of-incorrectly-rejecting-the-null-hypothesis-increase-with-a-large).)

Made a script for clarity: `rvs` samples are made from `population` arrays, both sample distributions are drawn, power, p_value, effect sizes (`effect_sample` and `effect_inverse`, where std is transformed = `std(sample) * np.sqrt(N)`) are displayed on the screen. When changing the slider, N changes, redrawing the graph.

```
from statsmodels.stats.power import TTestPower
from scipy.stats import t, ttest_1samp
from matplotlib.widgets import Slider
import matplotlib.pyplot as plt
import numpy as np

power = TTestPower()
size = power.solve_power(nobs=None, effect_size = 0.31, power=0.74, alpha = 0.05, alternative='two-sided')
print('sample size = ' + str(size))

m0, m1 = 15, 15.3
n = 10000

fig, ax = plt.subplots()
fig.subplots_adjust(bottom=0.25)
ax_N = fig.add_axes([0.25, 0.1, 0.65, 0.03])
s_N = Slider(ax_N, "N", valmin=1, valmax=300,valinit=73, valstep=1)

population_0 = np.sort(t.rvs(loc=m0, scale=1, size=10000, df=n-1, random_state=1))
population_1 = np.sort(t.rvs(loc=m1, scale=1, size=10000, df=n-1, random_state=1))


def update(val):
    N = s_N.val
    df = n - 1
    rvs_0 = np.sort(np.array([(np.random.choice(population_0, N).mean()) for _ in range(1000)]).ravel())
    rvs_1 = np.sort(np.array([(np.random.choice(population_1, N).mean()) for _ in range(1000)]).ravel())
    mu_0, std_0, mu_1, std_1 = np.mean(rvs_0), np.std(rvs_0), np.mean(rvs_1), np.std(rvs_1)
    z_values_0, z_values_1 = (rvs_0 - mu_0) / std_0, (rvs_1 - mu_0) / std_0
    pdf_0, pdf_1 = t.pdf(rvs_0, loc=mu_0, scale=std_0, df=df), t.pdf(rvs_1, loc=mu_1, scale=std_1, df=df)

    l, r = t.ppf(1 - 0.975, df=df), t.ppf(0.975, df=df)
    val = t.ppf(0.975, loc=mu_0, scale=std_0, df=df)
    power = round((1 - t.cdf(val, loc=mu_1, scale=std_1, df=df)), 4)
    p_value = ttest_1samp(rvs_1, popmean=mu_0)[1]

    s_sample = np.sqrt((std_0 ** 2 + std_1 ** 2) / 2)
    s_sample_inverse = np.sqrt(((std_0 * np.sqrt(N)) ** 2 + (std_1 * np.sqrt(N)) ** 2) / 2)
    effect_sample = abs(mu_0 - mu_1) / s_sample
    effect_inverse = abs(mu_0 - mu_1)/ s_sample_inverse

    ax.clear()
    ax.plot(z_values_0, pdf_0)
    ax.plot(z_values_1, pdf_1)
    ax.axvline(x=l, linestyle="--", color="blue", label="alfa")  # alfa
    ax.axvline(x=r, linestyle="--", color="blue")  # alfa
    ax.text(0, (np.max(pdf_0) + np.min(pdf_0)) / 2, "power =" + str(power) +
               "\n" + "effect_sample =" + str(round(effect_sample, 4)) +
               "\n" + "effect_inverse =" + str(round(effect_inverse, 4)) +
               "\n" + "p - value =" + str(round(p_value, 4)))


s_N.on_changed(update)
update(0)

plt.show()
```

![Peek 2024-11-18 21-50](https://github.com/user-attachments/assets/60d23def-ea97-4319-8c79-80b5823580a1)

**Comment by josef-pkt** [comment]
I'm don't really understand the details of what you are asking.

to 1:
power and sample size computation for t-test use cohen's d as effect size, which divides by the population standard deviation, and not by the standard deviation of the test statistic.

to 2:
> Suppose I selected a sample size based on the power analysis, but got lower power.

Not clear why you get lower power.
Correct sample size computation should give you the desired power (subject to small sample problems, and possible distributional approximations).
If the power is not correct, then either the method is wrong, or the asymptotic distribution is not a good approximation for the power. In some cases it's possible to find a better method, in other cases Monte Carlo power analysis might provide a better approximation.

to the stats.stackexchange question

as the sample size increases, we reject smaller and smaller deviations from the null at a given power.
For fixed deviation from the null the power goes to inf.
These tiny deviations become statistically significant but will substantially be irrelevant.

One way to get around this is to replace the point null with an interval of what is a meaningful difference (effect) based on the subject matter

see this notebook searching for "nonequivalence". In an R package it is called mimimum effect test.
https://www.statsmodels.org/dev/examples/notebooks/generated/stats_poisson.html
