### ISSUE TITLE
Question: Is the "Beta" tag in PyPI intentional?

### ISSUE THREAD

**Issue by vyadh** [statsmodels/statsmodels#9435]
According to the [setup.py](https://github.com/statsmodels/statsmodels/blob/main/setup.py#L93) information, and therefore in PyPI, this package is stated as being "beta" in its lifecycle. Since this is a long running, actively maintained and popular project, can I asked whether this is intentional? Particularly as I don't see this anywhere else in the docs. The company I work for needs to make decisions about what packages we use and this project looks high quality. However, the beta label makes it at little problematic to be able to use it. It would be really helpful if we could understand if it's actually intentional or not - I wondered whether it was just an historical quirk that it's not been updated? Much appreciate any info!

#### Is your feature request related to a problem? Please describe
It's related to the bureaucracy of enterprise environments that requires "stable" software ;)

#### Describe the solution you'd like
For the `setup.py` and therefore PyPI be shown as `Development Status :: 5 - Production/Stable`

**Comment by bashtage** [comment]
I think beta is approprieate in the sense that the API isn't particularly stable, or stricly following any versioning system.  This said, it woudl be great to get statsmodels to 1.0 soon. It is nearly stable, and I don't think that the changes couldn't follow some form of sensible versioning and deprecation policy.

**Comment by vyadh** [comment]
Hey. Thanks for that. So presumably that means that it's "stable" in the sense that people use it to support important "production" workloads (particularly given this project's pervasive usage), and you're just using `beta` simply to make it clear that new versions need to be taken with particular care?

**Comment by bashtage** [comment]
Yes - that is a great summary of the status of statsmodels.  This said, we try not to break things without warning, but sometimes upstream changes (pandas or scipy) require us to move faster than ideal.

**Comment by josef-pkt** [comment]
I don't know what a statsmodels 1.0 would look like.

The core parts have been stable for a long time.
Our backwards compatibility is pretty strict, especially for older models and functions.
Refactorings are almost always backwards compatible. 
New features might occasionally have bugs.

But many parts need review and possible refactoring before the are "finished".
For example I'm pretty happy now with the state of robust linear models after 3 PRs #9186 #9210 #9227
Once those changed and new parts are a bit battle tested, then they will be very stable, but there are still missing enhancements in inference options and post-estimation.

Many other parts would similarly benefit from reviews and updating of the design, even though the current code works correctly and has been used for years.

(in statsmodels.stats:
Currently I'm unhappy about the state of power and sample size calculation. It works fine and was mainly modelled after an R package, but some internal and public api decisions are annoying, besides some features that are still missing.

I wrote the initial inference for proportion (hypothesis tests, ...) based on SAS and R docs, but I don't like the structure anymore. 
)

**Comment by vyadh** [comment]
That's really helpful, thank you both. Sounds like it won't move from the Beta tag for a while then, but clearly this package has massive adoption so that probably helps to evidence that it's fine :)

**Comment by vyadh** [comment]
Just a quick update to say that we have risk-accepted being able to use this library based on your helpful comments. Thanks guys :)
