### ISSUE TITLE
X13 makes invalid call to pd.DatetimeIndex

### ISSUE THREAD

**Issue by abielr** [statsmodels/statsmodels#9455]
https://github.com/statsmodels/statsmodels/blob/main/statsmodels/tsa/x13.py:430 calls `pd.DatetimeIndex` with the `start` argument, which has been deprecated. My understanding is that users are now supposed to use `pd.date_range` to accomplish something similar.

**Comment by bashtage** [comment]
Thanks for reporting.  Fixed in main now.
