### ISSUE TITLE
t_test ... after ARMA

### ISSUE THREAD

**Issue by josef-pkt** [statsmodels/statsmodels#947]
are they supposed to work, are there any substitutes?

```
>>> res.t_test(np.eye(len(res.params)))
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    res.t_test(np.eye(len(res.params)))
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2\statsmodels\statsmodels\base\model.py", line 1137, in t_test
    raise ValueError('Need covariance of parameters for computing '
ValueError: Need covariance of parameters for computing T statistics
```

```
>>> res.cov_params()
                const  ar.L1.D.cpi  ma.L1.D.cpi
const        0.042359    -0.001674     0.002629
ar.L1.D.cpi -0.001674     0.002089    -0.003507
ma.L1.D.cpi  0.002629    -0.003507     0.008056

>>> res._results.cov_params()
array([[ 0.04235854, -0.00167449,  0.00262911],
       [-0.00167449,  0.00208857, -0.00350679],
       [ 0.00262911, -0.00350679,  0.0080562 ]])

>>> res.t_test(np.eye(len(res.params)), cov_p=res._results.cov_params())
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    res.t_test(np.eye(len(res.params)), cov_p=res._results.cov_params())
  File "e:\josef\eclipsegworkspace\statsmodels-git\statsmodels-all-new2\statsmodels\statsmodels\base\model.py", line 1159, in t_test
    r_matrix=r_matrix, cov_p=cov_p)))
TypeError: cov_params() got an unexpected keyword argument 'r_matrix'
```

I would have expected the last case to work, maybe a problem in base.

**Comment by josef-pkt** [comment]
It looks like the same problem for `f_test`
http://stackoverflow.com/questions/35958857/python-and-statsmodels-how-to-evaluate-the-f-test-of-joint-parameters-in-arma-m

**Comment by josef-pkt** [comment]
check the status here, either fix or close if fixed

**Comment by josef-pkt** [comment]
t_test is still broken in master

```
>>> res_arma
<statsmodels.tsa.arima_model.ARMAResultsWrapper object at 0x0000000009ABA8D0>
>>> res_arma.t_test(np.eye(len(res_arma.params)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\statsmodels\base\model.py", line 1274, in t_test
ValueError: Need covariance of parameters for computing T statistics
    raise ValueError('Need covariance of parameters for computing '
```

**Comment by josef-pkt** [comment]
in ARMAResults

```
    @cache_readonly
    def bse(self):
        params = self.params
        hess = self.model.hessian(params)
        if len(params) == 1:  # can't take an inverse, ensure 1d
            return np.sqrt(-1./hess[0])
        return np.sqrt(np.diag(-inv(hess)))

    def cov_params(self):  # add scale argument?
        params = self.params
        hess = self.model.hessian(params)
        return -inv(hess)
```

I think there is no easy "quick-fix". 
or maybe
- rename cov_params to cov_params_default and make it into a cached property
- tvalues is inherited, pvalues are overwritten but look generic with hardcode t-distribution

BUG: in cov_params if repeated fit with different `method`
hessian is computed using numerical diff of loglike which depends on method which is attached to the model, and the `method` attribute is set and changed in fit.
(Asymptotically the `method` shouldn't matter, and either cov_params should be consistent.)

Fixing the stateful attribute in the model class will need more work and unit tests. e.g. attach method to results instance but loglike will need a method keyword argument. 
An immediate fix for bse/cov_params is to compute them in `Results.__init__` as in other models.

**Comment by josef-pkt** [comment]
postponed to 0.10

**Comment by bashtage** [comment]
Still a bug.

**Comment by bashtage** [comment]
> BUG: in cov_params if repeated fit with different method
hessian is computed using numerical diff of loglike which depends on method which is attached to the model, and the method attribute is set and changed in fit.
(Asymptotically the method shouldn't matter, and either cov_params should be consistent.)

This is fixed in master.  Models can no longer be refit with configurations that fundamentally alter the model. Might want to attach copy(self) to results instances for safety.
